### ISSUE TITLE
TCP support

### ISSUE THREAD

**Issue by chendo** [containous/traefik#10]
Would be awesome if this also supported TCP backends (ideally with optional TLS support)!

**Comment by EmileVauge** [comment]
It needs some (a lot of ?) work... But it would be awsome :)

**Comment by xiaods** [comment]
TCP + TLS ? need more details on this proposal

**Comment by pragone** [comment]
+1. 
I love the concept of traefik for a microservices environment as it facilitates service discovery and balancing. But not all services are HTTP based. So, from what I understand, it can't be used for load-balancing MySQL or similar services.
If I have a microservices environment where I need another LB technology for any non-http service (for example HAProxy + Marathon template) I won't adopt traefik just to keep the number of moving pieces low. I think therefore that this is an important feature.
My 2 cents

**Comment by Ozzadar** [comment]
I highly support the addition of this feature =)

**Comment by faddat** [comment]
+1

**Comment by rvm2015** [comment]
+1 on this, I've been pushing a similar project called Fabio that has already solved this with a consul backend to add Mesos/Marathon as an option but I'd really like to see this here.

**Comment by emilevauge** [comment]
Hi @rvm2015, as far as I know, fabio is only supporting HTTP/S right now. How are you doing this with Fabio?

**Comment by rvm2015** [comment]
You are correct, I am mistaken. I've been shopping around for a TCP load balancer and I misread their feature set.

**Comment by altvnk** [comment]
+1 for TCP services

**Comment by faddat** [comment]
+1 indeed.  We currently use an ugly hack to do it.  I feel that traefik
was a lot more elegant, not to mention stable.

Jacob Gadikian
E-mail: faddat@gmail.com
SKYPE: faddat
Phone/SMS: +84 167 789 6421

**Comment by tymofii-polekhin** [comment]
+1 for TCP

**Comment by klausenbusk** [comment]
+1

**Comment by hd-deman** [comment]
@faddat how did you hacked this?

**Comment by Ozzadar** [comment]
@hd-deman It wasn't with traefik. It was a combination of adding Consul to our marathon stack, using a marathon-consul container to report changes in applications to consul then using a haproxy-consul bridge to port forward from there.

I'm not going to link here but if you'd like links to the different components feel free to send me a message and I'll forward you to them. This stack isn't extremely suitable for production though as you'd need to write a watcher daemon to make sure that all the components don't explode on you. (as they tend to do)

**Comment by faddat** [comment]
see @ozzadar's answer-- he's the one who actually implemented the hack.
We're both glad to help if you need :).

Jacob Gadikian
E-mail: faddat@gmail.com
SKYPE: faddat
Phone/SMS: +84 167 789 6421

**Comment by spoon99** [comment]
+1

**Comment by cedvan** [comment]
:+1:

**Comment by referup-amontero** [comment]
+1 for TCP. It would be awesome!

**Comment by pataquets** [comment]
+1 for TCP/UDP. Added to TLS, would make the perfect solution.
Thanks for this software.

**Comment by saswatp** [comment]
+1 TCP Load balancing would make it awesome and reduce the feature parity with other LBs like HAProxy or NGINX

**Comment by gembin** [comment]
+ 1 for TCP

**Comment by darxkies** [comment]
+1 for TCP

**Comment by Gidipp** [comment]
:+1: for TCP!

**Comment by emdem** [comment]
+1 for TCP

**Comment by marshyski** [comment]
+1

**Comment by blsmth** [comment]
i know these are useless and code would be better, but +1

**Comment by emilevauge** [comment]
Locking conversation, to avoid `+1`.
