### ISSUE TITLE
Traefik failing on POST request

### ISSUE THREAD

**Issue by Tester98** [containous/traefik#1008]
### What version of Traefik are you using (`traefik version`)?
v1.1.2

### What is your environment & configuration (arguments, toml...)?
linux, simple file backend

[retry]

[backends]
[backends.testing]
[backends.testing.servers.server1]
url = "http://primary:80"
weight = 1
[backends.testing.servers.server2]
url = "http://backup:80"
weight = 1

### What did you do?
if the request is a POST request  and if the primary backend has failed, then traefik will retry the request to backup ( or vice-versa first backup then primary). 

### What did you expect to see?
Request being forwarded to another server and a response

### What did you see instead?
traefik fails to retry request and post data is destroyed. traefik  debug logs below

```
time="2016-12-31T10:50:50+01:00" level=warning msg="Error forwarding to http://primary:80, err: dial tcp primary:80: getsockopt: connection refused"
time="2016-12-31T10:50:50+01:00" level=debug msg="New attempt 2 for request: /api/adduser"
time="2016-12-31T10:50:50+01:00" level=warning msg="Error forwarding to http://backup:80, err: http: invalid Read on closed Body"
```

i have found out a similar case  here, please  have a look
https://github.com/flynn/flynn/issues/872

**Comment by bamarni** [comment]
Should be fixed with #1016
