### ISSUE TITLE
How to hide some existing containers ?

### ISSUE THREAD

**Issue by chermed** [containous/traefik#1028]
### What version of Traefik are you using (`traefik version`)?
Traefik version v1.1.2 built on 2016-12-15_10:21:15AM

### What is your environment & configuration (arguments, toml...)?
```
defaultEntryPoints = ["http"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"

[docker]
  endpoint = "unix:///var/run/docker.sock"
  domain = "docker.localhost"
  watch = true

[backends]
    [backends.dev8]
        backend = "dev8"
        enable = false
```

### What did you do?
Using the toml file

### What did you expect to see?
I use Traefik on existing docker cluster, so I have already a dozen of containers, now I want to hide some of them, group others, the problem is that there is no method to ama,ge containers labels, We can modify the domain anytime.

### What did you see instead?
I still see my container
![traef k 2017-01-09 17-22-43](https://cloud.githubusercontent.com/assets/7537574/21776069/9410f25a-d690-11e6-9847-faf754b53783.png)

**Comment by timoreimann** [comment]
How about setting the `traefik.enable` label to false?

**Comment by chermed** [comment]
@timoreimann I think that the problem is related to Docker, because when I made some searches, there is no method to set labels on existing docker containers (just setting labels on creating ..)

**Comment by timoreimann** [comment]
@chermed you could be right, I'm not too familiar with the Docker integration.

@vdemeester can probably clarify for sure.

**Comment by vdemeester** [comment]
@chermed @timoreimann there is no way to set labels to existing containers yep 😅. If you use swarm mode, that's another story, you can update labels on the services.

The best way to achieve what you want is to make sure Træfik doesn' export anything by default, thus you'll have to explicitely use labels on docker container for them to be taken into account by Træfik 👼.

**Comment by timoreimann** [comment]
@chermed @vdemeester is there anything we could do to improve clarity on this point (like extending documentation), or should we close this issue right away?
