### ISSUE TITLE
Traefik unable to redirect the request on being successful authenticated from passport in node js

### ISSUE THREAD

**Issue by keshavpeswani** [containous/traefik#1036]
### What version of Traefik are you using (`traefik version`)?
Traefik version : 1.1.2

### What is your environment & configuration (arguments, toml...)?
Docker swarm mode (docker version 1.12)
Traefik command : 
```shell
docker service create \
    --name traefik \
    --replicas=1 \
    --constraint=node.role==manager \
    --publish 80:80 --publish 8080:8080 \
    --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock \
    --network  services-overlay-net \
    traefik:v1.1.2 \
    --docker \
    --docker.swarmmode \
    --docker.watch \
    --logLevel=debug \
    --graceTimeOut=1000 \
    --web
```

### What did you do?
Node.js application that runs as a container in swarm mode. This app authenticates user(SSO) using passport nodejs module. When browser makes a post call to our app endpoint (/sso/saml/consume) with valid SAMLResponse, we validate using passport module and redirect to the home page of our app.  Below is the code snippet that consumes the SAML response and do redirection.

```js
app.post('/sso/saml/consume',
  passport.authenticate('saml', { failureRedirect: '/loginErr', failureFlash: true }),
  function(req, res) {
    res.redirect('/');
  }
);
```

We suspected its the redirection issue, but thats not the case.

Also, our app works perfectly fine and does the correct redirection after authenticating using passport *without* traefik.

### What did you expect to see?
Traefik to send redirect response to browser 

### What did you see instead?
Browser gets empty response error - "the site didn’t send any data for /sso/saml/consume".
Our app logs also indicate that then /sso/saml/consume endpoint gets hit multiple times for a single user going through SSO login. Interestingly, it seems passport module has setup the session with the browser, because the same user if opens up app again, then we dont redirect to SSO login page. For us, it is redirection thats not happening.

**Comment by dtomcej** [comment]
Are there any traefik logs generated when you attempt to post to `/sso/saml/consume`?

Can you show us what your DEBUG logs look like (So we can see the traefik config)?

**Comment by keshavpeswani** [comment]
When the redirection happens to the home page of our app, the following traefik logs are generated : 
```

time="2017-01-16T06:22:15Z" level=warning msg="Error copying upstream response Body: unexpected EOF" 
2017/01/16 06:22:15 server.go:2317: http: multiple response.WriteHeader calls
time="2017-01-16T06:22:15Z" level=debug msg="Round trip: http://10.0.0.5:8080, code: 302, duration: 71.27868ms" 
time="2017-01-16T06:22:15Z" level=warning msg="Error copying upstream response Body: unexpected EOF" 
2017/01/16 06:22:15 server.go:2317: http: multiple response.WriteHeader calls
time="2017-01-16T06:22:16Z" level=debug msg="Round trip: http://10.0.0.5:8080, code: 302, duration: 36.952048ms" 
time="2017-01-16T06:22:16Z" level=warning msg="Error copying upstream response Body: unexpected EOF" 
2017/01/16 06:22:16 server.go:2317: http: multiple response.WriteHeader calls
time="2017-01-16T06:22:16Z" level=info msg="Skipping same configuration for provider docker" 
time="2017-01-16T06:22:16Z" level=debug msg="Round trip: http://10.0.0.5:8080, code: 302, duration: 329.795458ms" 
time="2017-01-16T06:22:16Z" level=warning msg="Error copying upstream response Body: unexpected EOF" 
2017/01/16 06:22:16 server.go:2317: http: multiple response.WriteHeader calls
time="2017-01-16T06:22:17Z" level=debug msg="Round trip: http://10.0.0.5:8080, code: 302, duration: 335.283303ms" 
time="2017-01-16T06:22:17Z" level=warning msg="Error copying upstream response Body: unexpected EOF" 
2017/01/16 06:22:17 server.go:2317: http: multiple response.WriteHeader calls
time="2017-01-16T06:22:17Z" level=debug msg="Round trip: http://10.0.0.5:8080, code: 302, duration: 327.827471ms" 
time="2017-01-16T06:22:17Z" level=warning msg="Error copying upstream response Body: unexpected EOF" 
2017/01/16 06:22:17 server.go:2317: http: multiple response.WriteHeader calls
time="2017-01-16T06:22:19Z" level=debug msg="Round trip: http://10.0.0.5:8080, code: 302, duration: 703.935028ms" 
time="2017-01-16T06:22:19Z" level=warning msg="Error copying upstream response Body: unexpected EOF" 
2017/01/16 06:22:19 server.go:2317: http: multiple response.WriteHeader calls

```

**Comment by traefiker** [comment]
I'll close the issue due to inactivity but feel free to re-open if needed.
