### ISSUE TITLE
NodeJS update (current in version 14)

### ISSUE THREAD

**Issue by Bacto** [containous/traefik#10389]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Hi all,

It seems that Node.js 14 is in used for the WEB UI:
https://github.com/traefik/traefik/blob/6c19a9cb8fb9e41a274bf712580df3712b69dc3e/webui/Dockerfile#L1

This version is not supported anymore and has no more security updates sinces 9 months:
https://github.com/nodejs/Release#end-of-life-releases

Is it possible to upgrade this support to a recent LTS Node.js support?

Best,
Adrien

**Comment by ldez** [comment]
related to #9932 and #10387
