### ISSUE TITLE
multiply domains in consul Consul Catalog

### ISSUE THREAD

**Issue by abyrvalgmi** [containous/traefik#1045]
### What version of Traefik are you using (`traefik version`)?
Latest, from doocker repository

### What is your environment & configuration (arguments, toml...)?
default, with enabled [consulCatalog]
### What did you expect to see?
Is it possible to define multpily domains? possible by regex

**Comment by ldez** [comment]
I'll close the issue due to inactivity but feel free to re-open if needed.
