### ISSUE TITLE
Support load balancing for smtp and imap

### ISSUE THREAD

**Issue by farodin91** [containous/traefik#1047]
This would me help to replace all load balancer with traefik.

An advantage is also you can easily use the build in acme(letsencrypt) generation for smtps and imaps.

**Comment by ldez** [comment]
I'll close the issue due to inactivity but feel free to re-open if needed.

**Comment by buhl** [comment]
I have no experience with the go language or this project. Would it be feasible for me to look into this?

**Comment by MichelDiz** [comment]
Does Traefik have or do not support email protocols?
I commented it this week about balancing for smtp and imap and now I see that there is probably of no support.

Such a feature would be interesting for this application https://github.com/hardware/mailserver/issues/83#issuecomment-368767275

**Comment by timoreimann** [comment]
@MichelDiz Traefik supports HTTP(S) only.
