### ISSUE TITLE
(Question) : Proxy Frontend rule to another machine

### ISSUE THREAD

**Issue by DblK** [containous/traefik#1050]
Before moving to traefik, I look uppon the documentation and couldn't find if it's possible to have a front end rule to forward to another machine which doesn't run any containers?

For example, I have machine A and B.
A receives all trafic and is running traefik
B is running apache and handle some specific (sub)domains: let's say magic.example.com

So if I try to access to code.example.com, traefik will redirect to the according docker container, same for drone.example.com.
But when I try to access to magic.example.com, it should redirect to machine B which will handle its own way.

Is it possible to do that?
If yes, could you point me to the doc (because I couldn't find anything) or the configuration I should have?

Thanks in advance.

**Comment by f3l1x** [comment]
:+1:

**Comment by loganmzz** [comment]
I'm also looking for similar features. I have services which only offers proxy (HTTP or SOCKS) connection mode to manage traffic but need to configure consumer based only on URL. I'm expecting to use solutions like traefik to expose infrastructure as URL and then reroutes traffic to these services as proxy.

**Comment by traefiker** [comment]
I'll close the issue due to inactivity but feel free to re-open if needed.
