### ISSUE TITLE
Feature request: Specify path to .htpasswd file

### ISSUE THREAD

**Issue by krancour** [containous/traefik#1055]
Currently, one can do this:

```
[web]
address = ":8080"

  [web.auth.basic]
    users = ["test:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/", "test2:$apr1$d9hr9HBB$4HxwgUir3HP4EsggP/
```

The problem with this, however, is that users of Kubernetes are likely to stash their entire `traefik.toml` in a `configmap`. Storing secrets (like passwords) in a configmap, even if encoded, is frowned upon. To circumvent this, one could consider base64 encoding the _entire_ `traefik.toml` and storing that in a `secret` instead, but that unnecessarily obfuscates lots of non-sensitive configuration. From an operator's perspective, it's not ideal.

What would make all of this easier to deal with would be if, as with certificates, passwords could be loaded from a separate file-- an `.htpasswd` file in this case. What would the Traefik team think about making it possible in `traefik.yaml` to simply provide a path to such a file? This would help Kubernetes users quite a bit because _just_ the password could be stored in a `secret` while all the non-sensitive config remains in a `configmap`.

**Comment by errm** [comment]
sounds reasonable
