### ISSUE TITLE
Required nginx equivalent for proxy_pass_request_headers 

### ISSUE THREAD

**Issue by rokka-n** [containous/traefik#1074]
### What version of Traefik are you using (`traefik version`)?
latest

### What did you do?
Proxypass with basic auth for elasticsearch domain in aws

### What did you expect to see?
proxy pass works

### What did you see instead?
traefik add `authorization:Basic` header which breaks access to elasticsearch

Is it possible to add equivalent of proxy_pass_request_headers to the config? 
passHostHeader is not enough for cases like this

**Comment by Juliens** [comment]
Do you think #1236 can resolve your problem ?

**Comment by ldez** [comment]
Closed by #1236.

**Comment by tarunmangukiya** [comment]
I think this issue is not beel resolved with the latest release too!
