### ISSUE TITLE
etcd kv store with username and password

### ISSUE THREAD

**Issue by kleinsasserm** [containous/traefik#1075]
I like to use an etcd kv store for traefik and I would like to use the username and password (authentication) feature of etcd. I'am not able to find a documentation for a custom etcd.tmpl where it may be possible to configure the etcd credentinals.

Is it currently possible to configure user/pass for etcd or will I have to use confd to manage the config in kv store?

Thanks!

**Comment by tcolgate** [comment]
Have sumitted #1357

**Comment by ldez** [comment]
Closed by #1357
