### ISSUE TITLE
Custom access log format

### ISSUE THREAD

**Issue by kaiyou** [containous/traefik#1079]
Currently, access logs are generated by ``ServeHTTP`` in the ``logger`` middleware. There seems to be no clear way of configuring the output log format.

Some setups use traefik for serving multiple domains and frontend or backend rules are not ideal for detecting which domain is being accessed by the client. Logging the HTTP ``Host`` header from the request would be useful in such a case.

I suggest one of two options:
1. Include the request ``Host`` header in the logs
2. Have a configuration option to change the log format and use some more advanced formatting, performance might be an issue though and any guideline on how implementing would be welcome.

I will probably work on option 1. to have it setup quickly on my infrastructure. I could however start working on option 2. as well if anyone experienced enough with Go could shed some light on the performance issues when formatting strings.

**Comment by zet4** [comment]
Also would like to be able to do something like what Caddy does: `log / stdout "{>Cf-Connecting-Ip} - [{when}] \"{method} {uri} {proto}\" {status} {size} \"{>Referer}\" \"{>User-Agent}\""`
Where in my server is running behind CloudFlare proxy and adds `Cf-Connecting-Ip` as a header for real user's IP address, I would like to be able to log that header's value somehow.

**Comment by Issif** [comment]
+1

`Host` header for start will be great.

**Comment by elafarge** [comment]
+1 for the cluster IP entry. Traefik being the entry point of many infrastructures, collecting, logging (and forwarding ?) the WAN client IP seems relevant (a common use case is to use this IP to build a world map showing where requests are coming from).

**Comment by Josh-West-Bose** [comment]
+1
And `X-Forwarded-For` header too please.

**Comment by ldez** [comment]
Remember the gentle way to participate:
- add a "reaction" on the first message of the issue.
- add more useful and detailed information on the subject.
- resolve the issue by making a PR.

**Comment by terozio** [comment]
+1
We have similar needs. A mechanism to configure the access logs to contain any http headers delivered with the request would be superb!

**Comment by ldez** [comment]
Remember the gentle way to participate:
- add a "reaction" on the first message of the issue.
- add more useful and detailed information on the subject.
- resolve the issue by making a PR.

**Comment by kaiyou** [comment]
I am still willing to work on this and provide something more generic than the dirty patches deployed to my servers. However, could anyone experienced enough with Go and Traefik point me in the right direction for managing a configuration option?

**Comment by timoreimann** [comment]
@kaiyou [server/configuration.go](https://github.com/containous/traefik/blob/121c057b90d64fc07bbc15d2b3b373667492eac5/server/configuration.go) is a good starting point to see how configuration options are set. To get the full picture, it's probably helpful to read about the [staert](https://github.com/containous/staert) and [flaeg](https://github.com/containous/flaeg) packages too.

We can probably assist you better if you let us know what you want to do specifically. I suggest you join us on Slack on the `#dev` channel for such questions.

**Comment by sugun999** [comment]
+1

**Comment by athoune** [comment]
There is two parts for this ticket :
 * Listing and naming attributes. The actual list is here : https://github.com/containous/traefik/blob/master/middlewares/accesslog/logger_formatters.go#L27-L41
 * Add some attributes, like real IP, beyound the http proxy
 * Expose the line template

Oh, there is three parts.

**Comment by dtomcej** [comment]
With the updated logs provider, access logs are customizable, and you can filter headers to be included or excluded from the logs: (https://docs.traefik.io/configuration/logs/#access-logs)

For this reason, I will be closing this issue.

If you have any further concerns, please open a new issue.

Thanks!

**Comment by mback2k** [comment]
I also agree, because I would like to be able to include the requested Host header in the access logs, to produce something like the Apache2 vhost_combined style logs.

**Comment by ajardan** [comment]
That is the same header I am missing, so maybe we will all be happy if it is added in the common format :)
