### ISSUE TITLE
Kubernetes httpsEntrypoint for Ingress

### ISSUE THREAD

**Issue by bonifaido** [containous/traefik#1082]
### What version of Traefik are you using (`traefik version`)?
v.1.1.2-alpine Docker image.

### What is your environment & configuration (arguments, toml...)?
Kubernetes 1.5.1

### What did you do?
I wanted to specify a https entryPoint (instead of the default http) for my service in Ingress.

### What did you expect to see?
That this is possible.

### What did you see instead?
This is not possible.

**Comment by errm** [comment]
Could you be a little more specific about what you are trying to do.  What configuration have you provided? what is not working?

As far as I understand you want to proxy to a port where a https service is running, I think this should be possible IIRC just ensure the service port is 443...

**Comment by bonifaido** [comment]
Sorry, I was mistaken, my traefik had only a http entry point defined. Closing!
