### ISSUE TITLE
Lets encrypt + auto renewal

### ISSUE THREAD

**Issue by franciscocpg** [containous/traefik#1083]
I read the docs and isn't clear to me is if lets encrypt feature supports auto renewal?
If so, how it works?

**Comment by emilevauge** [comment]
@franciscocpg Certificates are automatically renewed 30 days before expiration :)

**Comment by franciscocpg** [comment]
Thank you

**Comment by DMWOO7** [comment]
Very cool feature! I Love you for this considered implementation <3

**Comment by chunlea** [comment]
This is an awesome feature and should add it to documents.

**Comment by chngtrn** [comment]
I get emails from letsencrypt saying that my certs are expiring in 20 days which letsencrypt supposed to renew already. Something I need to do or force a renew?

**Comment by Younn** [comment]
> I get emails from letsencrypt saying that my certs are expiring in 20 days which letsencrypt supposed to renew already. Something I need to do or force a renew?

the same for us 🤨 is someone find the reason why?

**Comment by ldez** [comment]
@chngtrn @Younn could you come on [Slack](https://slack.traefik.io) or open a new issue. Thanks.

**Comment by albertski** [comment]
The letsencrypt cert did not renew for me.  Is there a way to force it to renew?

**Comment by ldez** [comment]
@albertski could you come on [Slack](https://slack.traefik.io) or open a new issue. Thanks.

**Comment by albertski** [comment]
Still need to figure out why it didn't renew but restarting server recreated the cert.

**Comment by albertski** [comment]
@ldez By any chance do you know if anything changed with Let's Encrypt? Previously I think I restarted my server with Traefik and it recreated the certs.  I just restarted my server and the cert did not recreate.  I'm relatively new to Traefik so not sure if there is a way to restart Traefik with command line.

**Comment by albertski** [comment]
@ldez I ran into the same issue again. I was thinking that resetting my server fixed the issue.  I took a look at the log and I seen the following error:

```
Error renewing certificate from LE: acme: Error -> One or more domains had a problem:\n[mydomain.com] error presenting token: digitalocean: HTTP 401: unauthorized: Unable to authenticate you.
```

This is my my traefik.tml file:
```
################################################################
# Global configuration
################################################################

# Enable debug mode
debug = true
logLevel = "WARN"

# EntryPoints are the ports that are open for Træfik to respond to.
defaultEntryPoints = ["http", "https"]
[entryPoints]
  [entryPoints.api]
    address = ":8081"
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

# Acme setting are used for letsencrypt to get the wildcard cert.
[acme]
email = "admin@mydomain.com"
storage = "traefik/acme/account"
caServer = "https://acme-v02.api.letsencrypt.org/directory"
entryPoint = "https"
  [acme.dnsChallenge]
  provider = "digitalocean" # DNS Provider name (cloudflare, OVH, gandi...)
  delayBeforeCheck = 0
[[acme.domains]]
  main = "*.mydomainstaging.com"

# Consul entry point settings, where Træfik looks for the KV store.
[consul]
  endpoint = "127.0.0.1:8500"
  watch = true
  prefix = "traefik"

[traefikLog]
  filePath = "/var/log/traefik/traefik.log"
[accessLog]
  filePath = "/var/log/traefik/access.log"

[api]
  entrypoint = "api"
```

**Comment by albertski** [comment]
I was able to figure this out.  Another developer left the company and their personal token wasn't working. I had to create a new token in Digital Ocean and update the token in traefik.service.
