### ISSUE TITLE
[Docker hub tags] Suggestion: dropping `v` for future images tags

### ISSUE THREAD

**Issue by pascalandy** [containous/traefik#1085]
This is a suggestion for tags in the [docker hub](https://hub.docker.com/r/library/traefik/tags/).

I don't think it's useful to keep the letter `v` in the versionning. ie: traefik:v1.1.2-alpine
I would suggest to drop it.

Cheers!

**Comment by ldez** [comment]
Currently we provide the both : with `v` and without `v`
