### ISSUE TITLE
Set route priority in HTTP Route

### ISSUE THREAD

**Issue by Kaswob** [containous/traefik#10878]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

So far we've relied heavily on the `priority' parameter when using IngressRoute resources. Recently we tested a possibility to migrate to Gateway API v1.0 on Traefik v3.0.1, but unfortunately it's not possible to set priorities, so our config doesn't work properly.

It would be great to be able to customise it in the HTTP Route manifest.

**Comment by rtribotte** [comment]
Hello @Kaswob,

Thank you for opening this feature request!

Gateway API support will be improved in Traefik v3.1, the next minor release (still RC).
In particular, the priorities computed for HTTPRoutes now meet the expectations of the specification, and maybe it would fit better in your situation.

However, we wonder what your specific use case is that would motivate providing such an option for Gateway API route resources.
