### ISSUE TITLE
Loadbalance between 2 containers in Docker Swarm Mode

### ISSUE THREAD

**Issue by pascalandy** [containous/traefik#1095]
### What version of Traefik are you using (`traefik version`)?
IMG_traefik="traefik:v1.1.2-alpine"

The key here is `--replicas 2` and `--label traefik.backend.loadbalancer.method=drr`. I'm looking to get a basic Round Robin between these two container. 

At the moment, when I refresh the page I always get:
`This request was processed by host: a5c19563e3bd`

Any idea how to accomplish this ?

```
CTN_iamfoo=iamfoo

docker service create \
--name "$CTN_iamfoo" \
--network "$NETW_static" \
--replicas 2 \
--restart-condition any \
--restart-max-attempts 10 \
--update-delay 7s \
--update-parallelism 2 \
--constraint node.labels.apps_accepted==yes \
--label traefik.enable=true \
--label traefik.frontend.rule=Path:/"$CTN_iamfoo" \
--label traefik.backend="$CTN_iamfoo" \
--label traefik.docker.network="$NETW_static" \
--label traefik.backend.loadbalancer.method=drr \
--label traefik.port=80 \
devmtl/golang-http-server_1.0:2016-12-06_12h12
```

`docker service ls`
```
ID            NAME        MODE        REPLICAS  IMAGE
n3m7sxkz91ws  traefik     global      1/1       traefik:v1.1.2-alpine
s1ngiork1sq7  iamfoo      replicated  2/2       devmtl/golang-http-server_1.0:2016-12-06_12h12
```

**Comment by pascalandy** [comment]
Damm, just realized I open a similar issue a while back - https://github.com/containous/traefik/issues/833

Let me know which issue should I close. Cheers!

**Comment by emilevauge** [comment]
Let's close this one ;)
