### ISSUE TITLE
Restrict which hosts use acme

### ISSUE THREAD

**Issue by shaunc** [containous/traefik#1096]
### What version of Traefik are you using (`traefik version`)?

1.1.2

### What is your environment & configuration (arguments, toml...)?

using docker-compose labels as well as toml config for main.

### What did you do?

I am trying to use letsencrypt to serve one service, and also serve an admin console to localhost (later may also want to publish the admin console on a subdomain). For flexibility I am trying to use `OnHostRule=true` and use labels in the individual services.

I can get the certificate properly generated for the main service, but traefik also requests a certificate for the admin. Is there a tag I can include to exclude the admin service from certificate generation for the moment?

### What did you ~expect~ hope to see?

Certificate for domain, no request for localhost.

### What did you see instead?

Requests for both.

**Comment by dtomcej** [comment]
Are you serving the admin console via the same TLS entrypoint? If so, it will require a certificate. Unless you are providing your own, letsencrypt will request one due to the `OnHostRule`

If you are NOT using tls for the admin, it should NOT be requesting certs for non-TLS enabled entrypoints.

**Comment by ldez** [comment]
I'll close this issue, because I think the question is answered, but feel free to continue the conversation.
