### ISSUE TITLE
Kubernetes backend

### ISSUE THREAD

**Issue by gwwfps** [containous/traefik#11]
Any plans to add a configuration backend using Kubernetes annotations?

**Comment by philk** [comment]
It's on the [ROADMAP.md](https://github.com/EmileVauge/traefik/blob/42a23171ae39a5df9f884617ae3c9fabde341f2d/docs/ROADMAP.md) at least.

What's the current progress and priority? I'd be tempted to take it on if it's not going to happen for awhile otherwise.

**Comment by EmileVauge** [comment]
Hi
I will not be able to do it in the next days, but it's definitely something I want to. @philk, some help is always welcomed :)

**Comment by guybrush** [comment]
relevant documentation:
* https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/ingress.md
* https://github.com/kubernetes/contrib/tree/master/service-loadbalancer

**Comment by philk** [comment]
I think there's also an argument to be made for traefik to satisfy the ingress controller.

Nginx and GCE:
https://github.com/kubernetes/contrib/tree/master/Ingress/controllers

Haproxy:
https://github.com/kubernetes/contrib/pull/223

**Comment by ekozan** [comment]
any eta for this subject ?

**Comment by emilevauge** [comment]
Hi! I created PR #186. Help is welcome :)

**Comment by Smana** [comment]
+1

**Comment by zoidbergwill** [comment]
You can use [Romulus](https://github.com/albertrdixon/romulus) to configure Traefik/Vulcand using Kubernetes ingress controllers/annotations, which is mentioned in the PR too. In case someone is in a rush for native Traefik support.

**Comment by emilevauge** [comment]
FYI, Kubernetes will be Traefik in coming days.

**Comment by rimusz** [comment]
@emilevauge that's awesome

**Comment by Smana** [comment]
Great ! looking forward to it :+1:
