### ISSUE TITLE
Docker swarm and traefik always error 404

### ISSUE THREAD

**Issue by juanpaps03** [containous/traefik#1106]
### What version of Traefik are you using (`traefik version`)?
latest version on docker hub at the date

### What is your environment & configuration (arguments, toml...)?
I have 2 VM running with vagrants, both machines has docker swarm, one as a manager and another one as node, and I created a network with the next command:

    docker network create --driver overlay --subnet 10.0.9.0/24 my-network

### What did you do?

I add a service with traefik and a service with my own app (a simple nginx app), here I let the commands:

    docker service create \
         --name traefik \
         --constraint=node.role==manager \
         --publish 80:80 --publish 8080:8080 \
         --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock \
         --network my-network \
         traefik \
         --docker \
         --docker.swarmmode \
         --docker.domain=traefik \
         --docker.watch \
         --web

And to my app:

    docker service create --replicas 3 --name myapp --network my-network --label traefik.port=80 myappimage

And then I went to the manager vagrant IP and IP:8080

### What did you expect to see?

just with the IP I expected my app index screen (is working fine just with the container, and my app is just a simple nginx serving a html page

with IP:8080 I expected traefik dashboard

### What did you see instead?

just IP: 404 page not found
IP:8080: all right 👍 

<img width="1164" alt="screen shot 2017-02-02 at 15 42 54" src="https://cloud.githubusercontent.com/assets/1637171/22563320/dd7f507c-e95e-11e6-87a3-6174545d00cb.png">

**Comment by Chabane** [comment]
Same issue

**Comment by Chabane** [comment]
If we try : https://github.com/BerlinVagrant/vagrant-dns?

**Comment by WTFKr0** [comment]
Traefik is reverse proxy based on Host header in http protocol.
To join your nginx service, you have to set it to, in your case, "container_name.traefik", like the rule in the traefik dashboard
```
curl -H Host:container_name.traefik http://your_ip
```
See exemple on docs : https://docs.traefik.io/

**Comment by pascalandy** [comment]
Please check out [my setup](https://github.com/containous/traefik/issues/563#issuecomment-277382568). It's working perfectly over Docker Swarm Mode 1.13

Cheers!

**Comment by juanpaps03** [comment]
@Chabane even if use this plugin fixed the problem, I'm using vagrant just for development, I'll need it working to production env.
@pascalandy I used your configuration and now works!, but I'm with bug #563 :(

**Comment by ldez** [comment]
I'll close this issue, because I think the question is answered, but feel free to continue the conversation.

**Comment by trajano** [comment]
I have the same issue when I set replicas, but if I don't have the replica block it works correctly.

**Comment by trajano** [comment]
I also tried 

     sudo docker service scale proxy_traefik=2

Once I do that all my requests turn to 404.
