### ISSUE TITLE
Access frontend-Host outside of a virtualbox

### ISSUE THREAD

**Issue by Chabane** [containous/traefik#1117]
Hi,

### What version of Traefik are you using (`traefik version`)?
traefik:v1.1.2

### What is your environment & configuration (arguments, toml...)?
docker swarm 1.13

```
           docker service create \
            --name traefik \
            --constraint=node.role==manager \
            --publish 80:80 --publish 8080:8080 \
            --mount "type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock" \
            --network myapp-net \
            traefik:v1.1.2 \
            --docker \
            --docker.swarmmode \
            --docker.domain=myapp \
            --docker.watch \
            --web
```
```         
     docker service create \
           --name sonarqube \
           --label traefik.port=80 \
           --label traefik.frontend.rule=Host:sonarqube.myapp \
           --publish 9000:9000 \
           --network  myapp-net \
           --replicas 2 \
           sonarqube:6.2
```

### What did you do?
I created 2 virtualbox machines with vagrant.
1 manager with traefik & sonarqube
1 worker with sonarqube

When I tap "sonarqube.myapp" outside of the virtualbox I got a 404 error. But when I tap 192.168.77.21:9000 I access to the home page of sonarqube.

### What did you expect to see?
sonarqube home

### What did you see instead?
404 error

Thanks for help.

**Comment by dtomcej** [comment]
Can you lease set the logs to debug for traefik using `-l DEBUG `, and give us a snippet of the logs?

I would like to see what the request it sees when it returns the 404.

Thanks!

**Comment by dtomcej** [comment]
I just reviewd this, and you have told traefik that your container listens on port 80, and then told docker to listen on port 9000:

```
 --label traefik.port=80 \
 --label traefik.frontend.rule=Host:sonarqube.myapp \
 --publish 9000:9000 \
```

**Comment by ldez** [comment]
@Chabane can we close this issue?

**Comment by Chabane** [comment]
@ldez you can close it. 

@dtomcej Thanks for your reply.
