### ISSUE TITLE
Can access backend services over IP?

### ISSUE THREAD

**Issue by Chenpipi** [containous/traefik#1121]
### What version of Traefik are you using (`traefik version`)?
v1.1.2

### What is your environment & configuration (arguments, toml...)?
rancher 1.2.3
docker 1.12.5
system: centos7.3
vxlan environment

### What did you do?
I used traefik according to the guide.

### What did you expect to see?
I hope to be able to traefik host IP to access the back-end services, in the absence of external DNS, do not need to change each time to bind host domain mapping,At the same time, through the host IP access can achieve the purpose of high availability.

### What did you see instead?
According to the guide, I found that traefik not through the host IP to access back-end services.

thanks

**Comment by dtomcej** [comment]
Can you give an example of your traefik config or debug log files?

Thanks!

**Comment by Chenpipi** [comment]
@dtomcej  I set a traefik_lb=true label on each host, and then started with three different service,In addition to accessing the backend service through the guide:
### Services will be accessed throught hosts ip's whith $host_label:
    http://${service_name}.${stack_name}.${traefik.domain}:${http_port}
    https://${service_name}.${stack_name}.${traefik.domain}:${https_port}
    http://${stack_name}.${traefik.domain}:${http_port}
    https://${stack_name}.${traefik.domain}:${https_port}
    http://${traefik.alias}.${traefik.domain}:${http_port}
    https://${traefik.alias}.${traefik.domain}:${https_port}

 I would like to be able to access backend services via host IP:
http://10.50.131.[92,32,134]:${http_port}/

like:
![234](https://cloud.githubusercontent.com/assets/9670781/23250248/3468ca82-f9e3-11e6-9829-6443a0158da1.jpg)
![123](https://cloud.githubusercontent.com/assets/9670781/23250252/39e8db78-f9e3-11e6-9234-d6001003eab6.jpg)
Because there is no dns server to resolve the domain name, each access to the service needs to bind the address to the back of the domain name. like:
10.50.131.92 aaa.aaa.aaa epg.epg.epg ps.ps.ps
Different services through the path to distinguish, like nginx 7 layer agent.
http://10.50.131.[92,32,134]:${http_port}/aaa   --> backend:aaa
http://10.50.131.[92,32,134]:${http_port}/ps   --> backend:ps
Is it possible to do this?

thanks

**Comment by traefiker** [comment]
I'll close the issue due to inactivity but feel free to re-open if needed.
