### ISSUE TITLE
Dynamically ban ip when backend repeatedly returns specified status code. ( 403 )

### ISSUE THREAD

**Issue by Nossnevs** [containous/traefik#1136]
I can't find this feature in the documentation.

The feature I seek is to be able to:

- Drop requests that are coming from a banned IP.
- If requests from one IP repeatedly fail some rule (e.g. backend returns 403 more then 10 times) the IP is added to banned IP list.
- There should also be a list of IP addresses that should not be added to the banned IP list.

**Comment by emilevauge** [comment]
For now, we don't want to include this kind of feature into Traefik. This should be done instead by your firewall. Closing this one then :)

**Comment by Nossnevs** [comment]
@emilevauge Any change in this decision?
