### ISSUE TITLE
Docker Compose cant run when following "Quickstart" guide

### ISSUE THREAD

**Issue by Exstatic** [containous/traefik#1150]
First time on Github and kind of learning Docker along the way. Please excuse me if I look dumb

### What version of Traefik are you using (`traefik version`)?
Latest one (Dont know how to get version - Literally just ran: `docker run -d -p 8080:8080 -p 80:80 -v $PWD/traefik.toml:/etc/traefik/traefik.toml traefik`")

### What is your environment & configuration (arguments, toml...)?
Literally just - `docker run -d -p 8080:8080 -p 80:80 -v $PWD/traefik.toml:/etc/traefik/traefik.toml traefik` 

### What did you do?

1. First I ran the Docker command `docker run -d -p 8080:8080 -p 80:80 -v $PWD/traefik.toml:/etc/traefik/traefik.toml traefik`

2. Then I made a directory called `traefik` in `/home/test` (my username is `test` in Ubuntu)

3. I created a file called `docker-compose.yml`

4. I then installed Docker Compose (via `sudo apt install docker-compose`)

5. I run the command `docker-compose up -d` in the directory where the .yml file is located

6. I get hit with this:
In file `./docker-compose.yml` service `version` doesn't have any configuration options.
All top level keys in your `docker-compose.yml` must map to a dictionary of configuration options.

### What did you expect to see?

Something else other than an error?

### What did you see instead?

An error

**Comment by toby1991** [comment]
So u've got a error from ur dockr-compose.yml file. 
Try pasting ur docker-compose.yml here for solving ur problem.

**Comment by ldez** [comment]
I'll close the issue due to inactivity but feel free to re-open if needed.
