### ISSUE TITLE
Near line 15 (last key parsed 'backends.backend-monitor-viz.servers'): Key 'backends.backend-monitor-viz.servers.server-monitor_viz-1' has already been defined.

### ISSUE THREAD

**Issue by raarts** [containous/traefik#1154]
### What version of Traefik are you using (`traefik version`)?

 v1.2.0-rc1

### What is your environment & configuration (arguments, toml...)?

docker deploy (docker 1.13.1 in --experimental mode)

 --web --docker --docker.swarmmode --docker.domain=docker.localhost --docker.watch --debug --logLevel=DEBUG \
             --entryPoints='Name:https Address::443 TLS' \
             --entryPoints='Name:http Address::80 Redirect.EntryPoint:https' \
             --acme=true \
             --acme.entryPoint=https \
             --acme.email=ron.arts@xxxxxxxx.com \
             --acme.storage=/etc/traefik/acme/acme.json \
             --acme.domains=tc.xxxxxxxx.com \
             --acme.ondemand=true \
             --acme.onhostrule=true

### What did you do?

just deploy traefik

### What did you expect to see?

some backends defined

### What did you see instead?

Above error message followed by:

Configuration received from provider docker: null

traefik 1.1.0 has no problems.

**Comment by timoreimann** [comment]
I think this is a duplicate of #1138.

**Comment by raarts** [comment]
Yes, definitely seems so. I'm gonna close this one.
