### ISSUE TITLE
Add/Remove/Rename response headers

### ISSUE THREAD

**Issue by athoune** [containous/traefik#1155]
The ticket #160 ask for specific CORS headers, but manipulating headers is a common need for a proxy. For security purpose, some headers should be added (https://blog.appcanary.com/2017/http-security-headers.html), other should be hidden or renamed for security by obscurity (like server name and version).

This setup have to be global, and should be available per frontend, just like this PR https://github.com/containous/traefik/pull/1147

The syntax should be similar of requests headers : #669 

Do you need some PR?

**Comment by dtomcej** [comment]
I have been researching some ways to make this work cleanly. If you would like to open a PR, please feel free.

I would however, suggest that you tie them to backends, since the frontends are just rules, whereas backends correspond to server endpoints.

**Comment by ldez** [comment]
Closed by #1236.
