### ISSUE TITLE
Support basic auth with docker provider

### ISSUE THREAD

**Issue by ProPheT777** [containous/traefik#1162]
### What version of Traefik are you using (`traefik version`)?

1.1.2

### What is your environment & configuration (arguments, toml...)?

Linux with docker provider (swarm mode)

### What did you do?

Labels on container via docker inspect (see traefik.frontend.auth.basic) : 

```
            "Labels": {
                "com.docker.compose.config-hash": "0a7165cd3a2ad13a280875a2663cbefab478956e1446a39fb9f5431dfe9b6e87",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "dkron",
                "com.docker.compose.service": "dkron",
                "com.docker.compose.version": "1.10.0",
                "traefik.backend": "dkron",
                "traefik.docker.network": "traefik_http_proxy",
                "traefik.frontend.auth.basic": "test:$blf4$ZSFRUTi8$0KkhdBlzcNslp7YFcWx0B.",
                "traefik.frontend.rule": "Host:dkron.dev.io",
                "traefik.port": "8080"
            }

```

### What did you expect to see?

A modal asking for my username and password when i'm going on dkron.dev.io from my browser

### What did you see instead?

Access to my backend without authentication

Am I doing it wrong; or basic auth is not supported on docker provider yet ?

**Comment by shaunc** [comment]
I'm using docker but have basic auth configured via traefik.toml
```
  [entryPoints.https]
    address = ":443"
    [entryPoints.https.auth.basic]
      users = ['...']
```
(Note that basic auth is via entrypoint rather than frontend....)

**Comment by SantoDE** [comment]
At least as long as #1147 is not merged ;)

Afaik, only Basic Auth via Toml is supported currently @ProPheT777

**Comment by ProPheT777** [comment]
@SantoDE nice ! 

@shaunc Yes I know for toml configuration, but for my need, I need basic authentication per front end and not per entrypoint, every services (public or private) are in https, so ...

**Comment by shaunc** [comment]
@ProPheT777 -- one possible configuration (which I was thinking of using for other purposes), would be to have "slave" Traefiks defined on sub networks for each service, which had entrypoint config for auth via toml, and a "master" traefik that combines them all. (though -- would it forward the auth correctly?...)

**Comment by samreaves** [comment]
+1 for basic authentication per front end (or really just for traefik dashboard) using Docker.

**Comment by ldez** [comment]
Closed by #1147

**Comment by holms** [comment]
Why this been closed if there's still not basic auth frontend from docker-compose?

**Comment by turchinc** [comment]
In case anyone is using labels with docker and docker-compose and stumbles over this issue, another potential pitfall is that  any `$` characters in the md5 encoded password must be escaped in the value for the label such that given the parameters `user` and  `password` and the `htpasswd` command:
`htpasswd -nbm user password`
results in:
`user:$apr1$Xf15G/hF$B4b3xtWkbg7H5Bxwa9I9f/` 
The basic authentication label value must be escaped as 
`- "traefik.frontend.auth.basic=user:$$apr1$$Xf15G/hF$$B4b3xtWkbg7H5Bxwa9I9f/"`  
in your `docker-compose.yml` file.
