### ISSUE TITLE
secure network do not work ? 

### ISSUE THREAD

**Issue by yogurtnaturalny** [containous/traefik#1175]
### What version of Traefik are you using (`traefik version`)?
latest 1.1.2

### What is your environment & configuration (arguments, toml...)?
docker 1.13 in swarm mode just basic setup from docker pages and tutorial for traefik for swarm mode. 

### What did you do?
I have created a overlay network for traefik however I have added option secure ( -opt encrypted )  from docker docs https://docs.docker.com/engine/swarm/networking/

### What did you expect to see?
working backend

### What did you see instead?
gateway timeout

**Comment by ayansen** [comment]
We are seeing the same issue, is there update on this ?

**Comment by ldez** [comment]
Do you still have the same problem with the latest version? [releases](https://github.com/containous/traefik/releases)

**Comment by pascalandy** [comment]
It works here on 1.3.0

Cheers!
