### ISSUE TITLE
Multiple routes support with Docker or Marathon labels

### ISSUE THREAD

**Issue by avthart** [containous/traefik#118]
Is it possible to have multiple routes for a frontend when using Marathon or Docker labels?

For example:
I would like to define a frontend with two routes, e.g. Host and Path

**Comment by avthart** [comment]
Just found out that it is possible to define a frontend with multiple routes in Consul and Marathon labels for the registration of backends. That sounds like a working solution for us!

**Comment by xiaods** [comment]
@avthart how do you implementation?

**Comment by joost-van-weenen** [comment]
What was the solution using labels? Can you just comma separate them?

**Comment by andreimc** [comment]
@joost-van-weenen :    
```
"traefik.frontend.rule":"Host:au.example.com,nz.example.com,hk.example.com"
```

**Comment by emilevauge** [comment]
thanks @andreimc, closing this one.
