### ISSUE TITLE
One Acme Certificate per Registered Domain

### ISSUE THREAD

**Issue by ekozan** [containous/traefik#1190]
### What version of Traefik are you using (`traefik version`)?
1.1.2

### What is your environment & configuration (arguments, toml...)?
Kubernetes + Acme 

### What did you do?
Enable OnHost for acme 

### What did you expect to see?
one Certificate per domain 
Cert1
CN domain.tld
Alt CN sub1.domain.tld
Alt CN sub2.domain.tld
Alt CN : sub3.domain.tld
Cert2
CN domain2.tld 

### What did you see instead?
one certificate per sub domain 

Cert1
CN domain.tld
Cert2
CN sub1.domain.tld
Cert3
CN sub2.domain.tld
Cert4
CN : sub3.domain.tld
Cert5
CN domain2.tld 

So limit are reached sooo fast :(

**Comment by dtomcej** [comment]
Did you use a single host rule like this: `Host:domain.tld,sub1.domain.tld,sub2.domain.tld,sub3.domain.tld`
and another like:
`Host:domain2.tld`?

if not, what labels did you use?

**Comment by ekozan** [comment]
it's multi rules 
each service have one subdomain 

In any case we need to aggregate all need before ask cert to let's encrypt, Nop ?

**Comment by ekozan** [comment]
Any news on this one ?

**Comment by nmengin** [comment]
@ekozan  Can you declare your subdomains as SANs of your main domain as described below?

```toml
[[acme.domains]]
   main = "local1.com"
   sans = ["test1.local1.com", "test2.local1.com"]
```
Indeed, with the `onHost` option, when a new domain is declared (when a new container starts for example), Traefik checks if it already exists a certificate which can validate the domain (as CN or SAN), otherwise it generates a new one.
Of course, it's only if you know all the subdomains before to start Traefik...

**Comment by nathantreid** [comment]
I agree, this should be addressed as we use this with Docker via Traefik's auto-configuration and having a way to tell Traefik to group a certain set of subdomains would be very beneficial. However, there should be a way to control it, so I can tell traefik (via Docker labels) I want 1 certificate request group for my "permanent" domains like the following:
```
foo.com
www.foo.com
test.foo.com
staging.foo.com
demo.foo.com
```
and separate certificate request groups for my short-lived domains, like `feature-branch-a.test.foo.com`.
I'm envisioning a label like `traefik.frontend.certificateGroup=[name]` eg  `traefik.frontend.certificateGroup=foo.com-permanent`.

**Comment by puco** [comment]
Or possibly request certificate with SAN per ingress or even group ingresses by some label. If I update the ingress with another host rule that would go into the group and would result a new ACME request with the existing domains plus the additional one.

**Comment by traefiker** [comment]
I'll close the issue due to inactivity but feel free to re-open if needed.

**Comment by mariusstaicu** [comment]
It would be nice to have this feature, to dynamically be able to add subdomains via docker labels.

**Comment by beaussart** [comment]
Indeed, rate limit is attained too fast.
