### ISSUE TITLE
Bind to specific ip address

### ISSUE THREAD

**Issue by kleinsasserm** [containous/traefik#1193]
### What version of Traefik are you using (`traefik version`)?
1.1.2

I would like to bind an instance of traefik to a given ip address and not to all. I've looked in the documention but I did not see a configuration option for this. Furthermore I did not see an command line switch for that. It would be nice to run multiple instances of traefik on different network interfaces at the same time. Like ist is possible in nginx or httpd through the "listen" parameter like "listen a.b.c.d:1234". Please excuse me, if I've overlook it anywhere.

Thank you!

**Comment by timoreimann** [comment]
You should be able to provide an IP address before the `:<port>` specification [in the entry points](https://github.com/containous/traefik/blob/master/traefik.sample.toml#L221).

**Comment by kleinsasserm** [comment]
Oh... I did not try it because it is not documented ... I will test it and I will give feedback here.

**Comment by kleinsasserm** [comment]
Oh, yes indeed that works as expected 👍 - Sorry that I opened up this, maybe I line in the documentation would be helpful for others.

**Comment by timoreimann** [comment]
I think the syntax is fairly obvious to Go programmers, but that doesn't help end users like yours. :-)

I think you're right, we should improve the docs here. I'll try to file a PR over the weekend.

**Comment by benbucksch** [comment]
> we should improve the docs here

@timoreimann : That would be helpful. 2.5 years later, it's still not documented.

I'm trying to bind to 2 IP addresses, and I don't see how to do that. Could you please add this to the examples for [`entryPoint.http`](https://docs.traefik.io/configuration/entrypoints/)?

**Comment by timoreimann** [comment]
@benbucksch I added a piece of TOML example configuration on the same day as I made that comment. See the reference to PR 1194 above.

That was 2 years ago, I believe a lot of refactorings have happened since then. I couldn't immediately tell where the samples are these days.

Feel free to file a new issue and / or reach out to the community on Slack and the community forum for help; especially with regards to binding to multiple addresses / protocols which this issue did not address originally.

Thanks.

**Comment by benbucksch** [comment]
> I couldn't immediately tell where the samples are these days.

I've linked them in my comment :-)
https://docs.traefik.io/configuration/entrypoints/

**Comment by timoreimann** [comment]
@benbucksch sorry, I meant the explicit samples TOML file we used to maintain. I see it's still around, but [the 1.7 branch version](https://github.com/containous/traefik/blob/v1.7/traefik.sample.toml) does not seem to contain my extension anymore. It's either gone someplace else or was missed when we put more focused on the rendered documentation.

**Comment by benbucksch** [comment]
@timoreimann : I've filed #5059, with the solution.

The solution isn't in traefik.toml entryPoints sections at all, but in the docker start script / docker-compose file that starts traefik. Might seems obvious, but only if you know it :-) .
