### ISSUE TITLE
InsecureSkipVerify=true parameter is ignored in case of wss backend

### ISSUE THREAD

**Issue by akanto** [containous/traefik#1199]
### What version of Traefik are you using (`traefik version`)?
Version: 1.1.2, 1.2.0-rc1, master

### What is your environment & configuration (arguments, toml...)?
Setting `InsecureSkipVerify=true` parameter in toml or using the  `--InsecureSkipVerify=true` as docker commad option

### What did you do?
I tried to connect to a wss backend, which has a self signed certificate.

```
[file]

# rules
[backends]
  [backends.test-wss]
    [backends.test-wss.servers.gw]
    url = "wss://xxx.xxx.xxx.xxx:8443/test/ws"
[frontends]
  [frontends.test-wss]
  backend = "test-wss"
  passHostHeader = true
    [frontends.test-wss.routes.gw]
    rule = "PathPrefix:/test/ws" 
```     

### What did you expect to see?
I have expected that the request is properly proxied, but it fails with:
`
time="2017-02-28T12:51:31Z" level=warning msg="Error dialing xxx.xxx.xxx.xxx: x509: cannot validate certificate for xxx.xxx.xxx.xxx because it doesn't contain any IP SANs"
`

### Reason
The problem is that the tls config is not used from http.DefaultTransport but a new one is created in oxy: https://github.com/containous/oxy/pull/13

**Comment by ldez** [comment]
Fix in 1.2.1. Thanks for the contribution!
