### ISSUE TITLE
Add in support for regex on PathPrefix/Path

### ISSUE THREAD

**Issue by nikore** [containous/traefik#1202]
### What version of Traefik are you using (`traefik version`)?
1.2.0-RC1 and 1.1.2

### What is your environment & configuration (arguments, toml...)?
Consul KV Backend, Custom service discovery app

### What did you do?
I'm trying to match a PathPrefix of /test but in a case insensitive matter, so for example /test /Test /tEsT /TEST will all match and go to the same backend. Reason for the ask is I'm trying to replace a custom haproxy setup with traefik as traefik fits the usecase better; but in haproxy we do path_beg -i /test 

### What did you expect to see?
It would be nice to introduce some kind of regex support on PathPrefix so I can do something like ```(?i)test``` to try and match it, or in general support for some kind of case insensitive matching. 

### What did you see instead?
currently I get a 404 when I ask for anything other then /test

**Comment by timoreimann** [comment]
@nikore looks like regular expression support is generally available, even though the docs aren't overly specific about it: https://github.com/containous/traefik/issues/323

Not sure if that includes modifiers like case sensitivity though, which would make things a lot easier compared to `/[tT][eE][sS][tT]`.

**Comment by timoreimann** [comment]
Looking at the code, regular expression supports stems from the gorilla mux being used. I think the following should work (untested):

`PathPrefix:/{path:(?i)test}`

The name of the variable `path` should not matter.

**Comment by nikore** [comment]
well I can confirm that:

```PathPrefix:/{path:(?i)test}/```

worked as expected it now matches on test, Test, TeST and other combinations. Thanks for the help, ill close the ticket but likely this should be added in to the docs.

**Comment by furkanmustafa** [comment]
> Looking at the code, regular expression supports stems from the gorilla mux being used.

I have just wasted 3 hours just to find this. This is a huge lack of documentation and very hacky implementation of regex.

For people looking for this, keywords: `traefik` `PathPrefix` `regex` (well also, `kubernetes` and `ingress` )

```yaml
...
          # - path: /users/[^/]+/books # does not work.
          - path: /users/{user_id:([^/]+)}/books
            backend:
              serviceName: book-server
              servicePort: http
...
```

IMO that field is supposed to work with regex without gorilla syntax.
