### ISSUE TITLE
Mix frontends and backends from different providers

### ISSUE THREAD

**Issue by adamlc** [containous/traefik#1203]
Hey guys, it would be nice to be able to mix frontends and backends from different providers. I did try this but I didn't seem to work.

I have a microservices infrastructure where the services register themselves in the consulCatalog provider which works great. What I'd like to do is manage a frontend in the consul provider and point it to a consulCatalog backend, as its easier to do programmatically from our app.

If this were to be implemented then I guess we may need to prefix backends from different providers so there arent any naming collisions.

Thanks!

**Comment by timoreimann** [comment]
@adamlc does this go in the direction of #1122?

**Comment by adamlc** [comment]
I did come across that. I guess it could touch on that. From what I read though it sounds like you want everything to combined into 1 backend from different providers?

In this issue at least I'm proposing we allow backends and frontends from different providers to be used. I'm guessing your use case might be a little harder to implement, although I'm no go programmer ;)

**Comment by timoreimann** [comment]
@adamlc what I have in mind is to "merge" certain backends and frontends. I haven't thought about how that merging would be implemented; my initial thinking was to add a mapping configuration file that defines how configurations across providers should be wired.

My super spontaneous gut feeling tells me that such a configuration file could be designed flexible enough to cover both your and my use cases.

**Comment by ldez** [comment]
Close in favor of  #1122 - Feel free to subscribe there for updates.
