### ISSUE TITLE
An ECS cluster with > 100 tasks cannot be enumerated

### ISSUE THREAD

**Issue by owen** [containous/traefik#1210]
### What version of Traefik are you using (`traefik version`)?
1.2.0-rc2, HEAD (`5abffe4`)

### What is your environment & configuration (arguments, toml...)?
```
debug=true
[web]
address=":8080"
[ecs]
Watch=true
RefreshSeconds=30
ExposedByDefault=true
Region="us-east-1"
```

### What did you do?
* Started Traefik

### What did you expect to see?
* Traefik :-)

### What did you see instead?
* `time="2017-03-01T16:28:22Z" level=error msg="ECS connection error InvalidParameterException: taskIds can have at most 100 items.\n\tstatus code: 400, request id: 169119ff-fe9c-11e6-8373-19566efe7b68, retrying in 603.484233ms"`
*`time="2017-03-01T16:28:23Z" level=error msg="ECS connection error InvalidParameterException: taskIds can have at most 100 items.\n\tstatus code: 400, request id: 17055ecb-fe9c-11e6-8373-19566efe7b68, retrying in 537.351478ms"`
*(...)

The ECS backend then never comes up.

The problem is here:
https://github.com/containous/traefik/blob/master/provider/ecs.go#L209

PR https://github.com/containous/traefik/pull/1209 will fix it - but I don't know if the Go AWS API should actually be patched to chunk the input parameters there, or if that wouldn't be consistent - so merge/reject as you see fit :-)

**Comment by timoreimann** [comment]
It sounds like the AWS library should be patched. However, I see no problems with fixing the problem locally in Traefik first and follow up with an upstream contribution afterwards.

**Comment by piteur** [comment]
Hi there.

I'm really interested on the ECS implementation in Traefik.
For me, this patch make sense, I don't believe AWS will change any input limitation on their side. And it'll make more sense to adapt traefik against a third-party API than forcing this third-party API to adapt to us.

Anyway, thanks for taking time to fix this issue I'll encounter soon :)

**Comment by timoreimann** [comment]
#1209 should have fixed this.

Closing.

**Comment by Dgadavin** [comment]
@timoreimann I thinks this bug is still here. I cant find any code that you merge.

**Comment by timoreimann** [comment]
@Dgadavin PR #1209 should have fixed it. Please file a new bug report if you believe the problem persists -- a few releases have gone by since we've closed the issue.
