### ISSUE TITLE
Traefik cannot get rancher environments unknown schema

### ISSUE THREAD

**Issue by bseng** [containous/traefik#1218]
### What version of Traefik are you using (`traefik version`)?
v1.2.0-rc2

### What is your environment & configuration (arguments, toml...)?
rancher v1.4.1

### What did you do?
run traefik with the following compose

> version: '2'
> services:
>   traefik2:
>     image: traefik:v1.2.0-rc2-alpine
>     stdin_open: true
>     tty: true
>    ports:
>     - 8880:80/tcp
>     - 8443:443/tcp
>     - 9000:8080/tcp
>     command:
>     - --web
>     - --rancher
>     - --rancher.domain=rancher.localhost
>     - --logLevel=DEBUG
>     labels:
>       io.rancher.container.agent.role: environment
>       io.rancher.container.create_agent: 'true'
>       io.rancher.container.pull_image: always

### What did you expect to see?
logs with no error

### What did you see instead?

> 3/2/2017 4:16:50 PMINFO[2017-03-02T05:16:50Z] Skipping same configuration for provider rancher
> 3/2/2017 4:17:05 PMDEBU[2017-03-02T05:17:05Z] Refreshing new Data from Rancher API
> 3/2/2017 4:17:05 PMERRO[2017-03-02T05:17:05Z] Cannot get Rancher Environments Unknown schema type [environment]
> 3/2/2017 4:17:05 PMgithub.com/containous/traefik/vendor/github.com/rancher/go-rancher/client.(*RancherBaseClientImpl).doList
> 3/2/2017 4:17:05 PM	/go/src/github.com/containous/traefik/vendor/github.com/rancher/go-rancher/client/common.go:299
> 3/2/2017 4:17:05 PMgithub.com/containous/traefik/vendor/github.com/rancher/go-rancher/client.(*EnvironmentClient).List
> 3/2/2017 4:17:05 PM	/go/src/github.com/containous/traefik/vendor/github.com/rancher/go-rancher/client/generated_environment.go:119
> 3/2/2017 4:17:05 PMgithub.com/containous/traefik/provider.listRancherEnvironments
> 3/2/2017 4:17:05 PM	/go/src/github.com/containous/traefik/provider/rancher.go:293
> 3/2/2017 4:17:05 PMgithub.com/containous/traefik/provider.(*Rancher).Provide.func1.1.1
> 3/2/2017 4:17:05 PM	/go/src/github.com/containous/traefik/provider/rancher.go:253
> 3/2/2017 4:17:05 PMgithub.com/containous/traefik/safe.(*Pool).Go.func1
> 3/2/2017 4:17:05 PM	/go/src/github.com/containous/traefik/safe/routine.go:77
> 3/2/2017 4:17:05 PMgithub.com/containous/traefik/safe.GoWithRecover.func1
> 3/2/2017 4:17:05 PM	/go/src/github.com/containous/traefik/safe/routine.go:141
> 3/2/2017 4:17:05 PMruntime.goexit
> 3/2/2017 4:17:05 PM	/usr/local/go/src/runtime/asm_amd64.s:2086
> 3/2/2017 4:17:05 PMDEBU[2017-03-02T05:17:05Z] first container len: %!i(int=35)

**Comment by SantoDE** [comment]
Hey @bseng ,

this is caused by the go-rancher API client. Until tonight, it did not support rancher environments above 1.4. This is changed with the latest commit (#0133178b84e9ca440d2430a93632fe32578dd6e9) beeing merged into the v1.2 branch.

So the next release will have that fixed :)

**Comment by warroyo** [comment]
@SantoDE Any idea when the next release will be available?

**Comment by fabiorauber** [comment]
Waiting anxiously =D

**Comment by timoreimann** [comment]
1.2 should be released rather soonish. Please bear with us just a tad longer. :-)

**Comment by fabiorauber** [comment]
Using recently refreshed 1.2, and I'm getting the same error (Rancher 1.4.1):

```
21/03/2017 14:54:28time="2017-03-21T17:54:28Z" level=error msg="Cannot get Rancher Environments Unknown schema type [environment]\ngithub.com/containous/traefik/vendor/github.com/rancher/go-rancher/client.(*RancherBaseClientImpl).doList\n\t/go/src/github.com/containous/traefik/vendor/github.com/rancher/go-rancher/client/common.go:299\ngithub.com/containous/traefik/vendor/github.com/rancher/go-rancher/client.(*EnvironmentClient).List\n\t/go/src/github.com/containous/traefik/vendor/github.com/rancher/go-rancher/client/generated_environment.go:119\ngithub.com/containous/traefik/provider.listRancherEnvironments\n\t/go/src/github.com/containous/traefik/provider/rancher.go:293\ngithub.com/containous/traefik/provider.(*Rancher).Provide.func1.1.1\n\t/go/src/github.com/containous/traefik/provider/rancher.go:253\ngithub.com/containous/traefik/safe.(*Pool).Go.func1\n\t/go/src/github.com/containous/traefik/safe/routine.go:77\ngithub.com/containous/traefik/safe.GoWithRecover.func1\n\t/go/src/github.com/containous/traefik/safe/routine.go:141\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:2086"
21/03/2017 14:52:44time="2017-03-21T17:52:44Z" level=debug msg="first container len: %!i(int=100)"
```

**Comment by fabiorauber** [comment]
It's a long shot, but is it related to https://github.com/rancher/rancher/issues/6046?

**Comment by timoreimann** [comment]
Is #1298 possibly related? If so, does [my suggestion](https://github.com/containous/traefik/issues/1298#issuecomment-287472962) help?

**Comment by fabiorauber** [comment]
I'm happy to report that creating manually an environment API key and using the following docker-compose file Traefik was able to retrieve the configuration:

```
traefik:
  ports:
    - 8000:8080/tcp
    - 80:80/tcp
    - 443:443/tcp
  #labels:
    #io.rancher.container.agent.role: environment
    #io.rancher.container.create_agent: 'true'
  image: traefik:1.2.0-alpine
  command:
    - "--web"
    - "--rancher"
    - "--rancher.domain=my.rancher.domain"
    - "--rancher.endpoint=https://rancher.my.rancher.domain/v1/projects/xxxx"
    - "--rancher.accesskey=my_access_key"
    - "--rancher.secretkey=my_secret_key"
    - "--logLevel=DEBUG"
```
Note that I had to remove Rancher labels _io.rancher.container.agent.role_ and _io.rancher.container.create_agent_ for this to work, and only with v1 API.

**Comment by SantoDE** [comment]
Hy @fabiorauber ,

thanks for your debug information :) Are you on Slack? I'd like to talk to you :)

**Comment by fabiorauber** [comment]
Hi @SantoDE, I'm not on Slack, but you cant talk to me via Telegram (@fabiorauber).

**Comment by bseng** [comment]
I've tested locally and rancher 1.5.1 does not work as well.

**Comment by bseng** [comment]
Using the view in API function I can see that the default environment have null in api and for newly created new environment have blank in environment, that might be why. 

![image](https://cloud.githubusercontent.com/assets/1452937/24228437/5a495a6e-0fc8-11e7-8e6d-fe5344cabf36.png)


this is v2-beta api on rancher 1.5.1.

**Comment by fabiorauber** [comment]
Just a thought, why not use the Rancher Metadata service to get container information? @SantoDE

**Comment by SantoDE** [comment]
Hi @fabiorauber ,

I actually thought about that as well :) But I like #1269 and thus, metadata is not enought ;-)

However, we improved docs (PR to be merged soon!) and with the new information, the current provider works good :)

**Comment by bseng** [comment]
Hi @SantoDE , @fabiorauber 

I've done more digging and it turns out environment in api is not environment in ui. 

Environment in UI is project in api.

https://forums.rancher.com/t/api-key-for-all-environments/279/9

So the change is going to be changing listEnvironment to listProject. 

Unfortunately I don't have time to make the change in code and summit a PR. Maybe @SantoDE can have a look?

**Comment by SantoDE** [comment]
That is described in the changed docs in #1337. You wanna test that? :) I guess it's clear then

**Comment by gaieges** [comment]
I've been playing around with this a bit today (`v1.2.1` via `traefik:1.2-alpine` image, rancher server `v1.5.3`, boot2docker `1.13.0`) and have had no luck getting it to run.  

I get the exception that is presented at the beginning of this thread, in the case of both passing along the API endpoint and creds, as well as using the direct environment backend (the latter it seems like is not expected to work at this point).

In the case of using the API method, I tried a few different paths for the endpoint all with the same results:

- `/v1/projects/1a5`
- `/v2-beta/projects/1a5`
- `/v2-beta`
- `/v1`

The changed docs give a bit more guidance but hard to test they're accurate or not given this exception.

**Comment by bseng** [comment]
I've made a pull request and try to explain the situation further and provide a fix. 

https://github.com/containous/traefik/pull/1414

**Comment by gaieges** [comment]
@SantoDE helped me with my issue that I thought would be useful to share with others: I missed the part in the updated docs that indicate that you don't need the labels anymore, which was actually what was breaking my setup.

If you ensure that the `rancher.endpoint` url is just the base url (ie no `/v1` or `/v2-beta`), AND ensure that you **don't** have the label `io.rancher.container.create_agent: 'true'` set, using the API keys will work.

**Comment by bseng** [comment]
@gaieges I'll closed this then
