### ISSUE TITLE
Add X-Forwarded-Port header to incoming requests

### ISSUE THREAD

**Issue by Yggdrasil** [containous/traefik#1220]
### What version of Traefik are you using (`traefik version`)?
Version:      v1.2.0-rc1
Codename:     morbier
Go version:   go1.7.5
Built:        2017-02-06_08:45:49PM
OS/Arch:      linux/amd64

### What is your environment & configuration (arguments, toml...)?
File-based config on AWS Ubuntu instances.
`passHostHeader = true` on backend.

### What did you do?
When running behind a reverse-proxy, some popular web frameworks such as Symfony depend on various `X-Forwarded-*` headers to generate correct URL's, etc. Traefik correctly sets most of these headers, except for `X-Forwarded-Port`. Symfony requires that header to be set.

### What did you expect to see?
I expect Traefik to add an `X-Forwarded-Port` header when passing the request to a backend, in addition to the other `X-Forwarded-*` headers it already sets. The `X-Forwarded-Port` header contains the portnumber on which the incoming request was received, usually 80 or 443.

I'm now adding this header in my backend, but it should be done by the proxy since that's the only place where the actual portnumber is known.

### What did you see instead?
The following headers are already added by Traefik.
`X-Forwarded-For`
`X-Forwarded-Host`
`X-Forwarded-Proto`
`X-Forwarded-Server`
`X-Traefik-Reqid`

**Comment by dtomcej** [comment]
This might cross over with #669 that I am working on.

Do you think that a flag like `passForwardedPort = true` would be sufficient for configuration? that way we could parse out the value, and include the header to the backend request if configured?

**Comment by Yggdrasil** [comment]
Definitely, you could even make the default `true`. After all, Traefik's already adding a few other common X-Forwarded headers to the request. Amazon's ELB adds three headers automatically (X-Forwarded-For, X-Forwarded-Proto, X-Forwarded-Port) and I don't see that causing any problems in applications.

I don't really think this header is special enough to necessarily deserve its own parameter, compared to other X headers. 'Convention over configuration' and all that.

**Comment by dtomcej** [comment]
Didn't know it was stock in ELB. In that case, we can add it by default. Will do up a PR in the morning.

**Comment by dmetzler** [comment]
👍 to add it by default as it is with ELB.

**Comment by f3l1x** [comment]
👍  I'm looking forward to it.

**Comment by ldez** [comment]
Remember the gentle way to participate:
- add a "reaction" on the first message of the issue.
- add more useful and detailed information on the subject.
- resolve the issue by making a PR.

**Comment by dtomcej** [comment]
Sorry for the delay on this one. This will require an update in the oxy forwarder.

I will be working on this in PR:
https://github.com/containous/oxy/pull/16

And will update this ticket once a working traefik PR has been created.

**Comment by wallisonmarra** [comment]
This issue is very important!

**Comment by traefiker** [comment]
Closed by #2302.

**Comment by JohnnyCosta** [comment]
I am using 1.5.1-alpine (docker), still same issue, no X-Forwarded-Port is being added... can you re-open this issue?
