### ISSUE TITLE
Reverse proxy not working

### ISSUE THREAD

**Issue by localhosted** [containous/traefik#1224]
I'm trying to use traefik as a reverse proxy to send subdomain traffic to a port. But I can't get it to work, all I get is a 404.

### What version of Traefik are you using (`traefik version`)?
v1.2.0-rc2

### What is your environment & configuration (arguments, toml...)?

    debug = true
    traefikLogsFile = "log/traefik.log"
    accessLogsFile = "log/access.log"
    defaultEntryPoints = ["http", "https"]
    entryPoint = "https"
    [entryPoints]
      [entryPoints.http]
      address = ":80"
    
     [web]
      address = ":8070"
    
     [backends]
       [backends.backend1]
         [backends.backend1.servers.server1]
         url = "http://mydomain.com:8080"
    
     [frontends]
       [frontends.frontend1]
       backend = "backend1"
         [frontends.frontend1.routes.test_1]
         rule = "Host: sub.mydomain.com"

### What did you do?
./traefik --configFile=traefik.sample.toml

### What did you expect to see?
Output from http://mydomain.com:8080

### What did you see instead?
404 page not found

**Comment by emilevauge** [comment]
Before ` [backends]`, add `[file]` to enable file configuration.
