### ISSUE TITLE
Stale backends

### ISSUE THREAD

**Issue by rokka-n** [containous/traefik#1228]
### What version of Traefik are you using (`traefik version`)?
Version:      v1.1.2
Codename:     camembert
Go version:   go1.7.4
Built:        2016-12-15_10:21:15AM
OS/Arch:      linux/amd64

### What is your environment & configuration (arguments, toml...)?
Traefik in a container with consul integration

### What did you do?
Services are running for few weeks, but at some point backends stopped being updated. Traefik still fetches correct and updated info from consul

### What did you see instead?
Stale backends in the URL and respectively request to a service would fail with 502 or other errors

**Comment by klausenbusk** [comment]
Do you use any kinds of websocket? Could be related to https://github.com/containous/traefik/issues/1174 then.

**Comment by rokka-n** [comment]
I believe it's more related to healthchecks in consul, there is a PR opened already.

**Comment by ldez** [comment]
Should be fixed by #1241
