### ISSUE TITLE
Traefik healthcheck used as Marathon labels (and others providers)

### ISSUE THREAD

**Issue by rogeriollacerda** [containous/traefik#1232]
Hi, 

The healthcheck feature implemented on version 1.2.0-rc2 can be used as marathon label during an application deployment? 

I tried something like:

traefik.HealthCheck.Interval=10
traefik.HealthCheck.URL=/health

But traefik ignores it.

Tks!

**Comment by shouze** [comment]
👍 for docker/swarm provider

**Comment by timoreimann** [comment]
I need this for Marathon as well, so I plan to work on this one soonish.

**Comment by rogeriollacerda** [comment]
Tks @timoreimann :)

**Comment by composer22** [comment]
+1 need this as well. compose is not playing fair w/ swarm and need additional functionality in lb

**Comment by timoreimann** [comment]
This is implemented for Marathon now. Docker support is tacked in issue 1286.
