### ISSUE TITLE
ELB + Traefik anomaly?

### ISSUE THREAD

**Issue by ammaskartik** [containous/traefik#1234]
### What version of Traefik are you using (`traefik version`)?
v1.2.0-rc1 Docker-Compose

### What is your environment & configuration (arguments, toml...)?
Consul KV Backend

TOML:

[web]
address = ":8080"
[web.statistics]
    RecentErrors = 100
[web.auth.basic]
    users = ["xyz:----"]

### What did you do?

During our stage deployment was testing traefik behind an ELB in AWS, might be redundant, dont know if many are using it like this. ELB is HTTPS (443) and forwards to HTTP(80) when routing to traefik.

### What did you expect to see?

Traefik receives request, forwards to appropriate backend. 
Backend successfully parses request and sends back to Traefik, and request is responded up the chain

### What did you see instead?

Traefik receives the request, executes it in the appropriate backend, Traefik logs round trip. But some where between the response chain of traefik, back through the ELB, the request is lost/dropped, etc... as the client never receives a response. 

If i disable HTTPS in the ELB, and just route regular http through the chain, everything functions as planned. 

Any help, insight would be appreciated. Great product overall guys!

**Comment by murarisumit** [comment]
Did you got answer to this problem, how did you solve this ?

**Comment by dduportal** [comment]
Hi @murarisumit would you mind opening a topic on the Community Forum at <https://community.containo.us/> describing your configuration and the issues you are having?

I'm asking since commenting a closed issue might not be effective for getting an answer, and because the version of Traefik used in this topic is old and was not stable. Thanks a lot!
