### ISSUE TITLE
Degraded performance in swarm during a scale up

### ISSUE THREAD

**Issue by Yshayy** [containous/traefik#1238]
### What is your environment & configuration? 
Docker swarm mode.
Multiple traefik instances, multiple services.
Using traefik.backend.loadbalancer.swarm=false for a service (or just keeping it anything other then true).

### What did you do?
Scaling up a service.

### What did you expect to see?
Everything works and performs well.

### What did you see instead?
The service endpoint have significant degraded performance during the new containers startup.

This issue doesn't reproduce when using traefik.backend.loadbalancer.swarm=true.
I don't have much experience with Traefik or swarm, but it looks to me that swarm's tasks don't change their state to running (from starting) until health-check is complete.
While swarm VIP is aware of the difference between state "starting" and "running" and does not pass traffic to these containers, I think that Traefik as of 1.2.0-rc2 ignores it.

**Comment by timoreimann** [comment]
@Yshayy did you resolve the issue? If so, how?
