### ISSUE TITLE
https-only traefik config still tries to listen to port 80

### ISSUE THREAD

**Issue by creynders** [containous/traefik#1242]
### What version of Traefik are you using (`traefik version`)?
docker: traefik:v1.1.2-alpine

### What is your environment & configuration (arguments, toml...)?

```
## traefik.toml
InsecureSkipVerify = true

[web]
address = ":4080"

defaultEntryPoints = ["https"]

[entryPoints]
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
  email = "admin@example.com"
  storage = "/etc/traefik/acme/acme.json"
  entryPoint = "https"
  onDemand = true

    [[acme.domains]]
      main="deckard.example.com"

[file]
[frontends]
  [frontends.bladerunner]
  backend="harrison"
  entrypoints=["https"]
  passHostHeader=true
    [frontends.bladerunner.routes.default]
    rule = "Host:deckard.example.com"

[backends]
  [backends.harrison]
    [backends.harrison.servers.ford]
    url="http://ford.example.com"
```

### What did you do?

I have nginx listening on port 80 and try to spin up the alpine docker image of traefik.

### What did you expect to see?

To be able to run traefik, listening only on 443

### What did you see instead?

Traefik tries to listen to port 80. I.e. when spinning it up it will complain:

```
listen tcp 0.0.0.0:80: bind: address already in use
```

Now the funny thing is that I use the exact same traefik config (except for the frontend and backend declarations) on an another server, with the exact same setup and it will happily co-exist with nginx running on port 80.

Any ideas what I could be doing wrong?

**Comment by creynders** [comment]
Aargh, I keep on creating issues only to find my idiotic f*ckup a few minutes later. Sorry for bothering...

**Comment by timoreimann** [comment]
@creynders would you mind leaving behind a note on what you did wrong, just in case someone else runs into as well?
