### ISSUE TITLE
Let's encrypt renewal is not working

### ISSUE THREAD

**Issue by thedigital** [containous/traefik#1244]
### What version of Traefik are you using (`traefik version`)?
1.1.2

### What is your environment & configuration (arguments, toml...)?
Docker compose
    traefik:
        image: traefik
        ports:
            - 8080:8080
            - 80:80
            - 443:443
        labels:
            - traefik.enable=false
        volumes:
            - ./build/traefik/traefik.toml:/traefik.toml
            - /var/run/docker.sock:/var/run/docker.sock
            - ./build/traefik/acme.json:/acme.json
        restart: "always"
        networks:
            - frontend

Traefik Toml
defaultEntryPoints = ["http","https"]

[entryPoints]
   [entryPoints.http]
   address = ":80"
      [entryPoints.http.redirect]
      entryPoint = "https"
   [entryPoints.https]
   address = ":443"
      [entryPoints.https.tls]

[acme]
email = "my.email@domain.tld"
storageFile = "acme.json"
entryPoint = "https"
onDemand = true
caServer = "https://acme-v01.api.letsencrypt.org/directory"
acmeLogging = true

[[acme.domains]]
   main = "domain.tld"
   sans = ["A.domain.tld","B.domain.tld","C.domain.tld","D.domain.tld"]
[[acme.domains]]
   main = "domain2.tld"
   sans = ["www.domain2.tld"]

acme.json file is OK since domains were successfully created a few months ago.

### What did you do?
Nothing. I just discovered my https websites not working : time out.

### What did you see instead?
Webistes are not working anymore : https websites times out.

Error in log file : 
traefik log :   traefik_1           | time="2017-03-07T09:31:18Z" level=error msg="Error renewing certificate: tls: failed to find any PEM data in certificate input"

this a BIG issue since all my websites are in production and rely mostly on HTTPS links...

**Comment by emilevauge** [comment]
@thedigital there seems to be an issue with `acme.json` file. Could you join the slack channel and send me this file (in private)?

**Comment by emilevauge** [comment]
Closing this one, solved on Slack.

**Comment by emilevauge** [comment]
@Overbryd could you open a new issue instead and give us all details needed (config and debug logs) ?
