### ISSUE TITLE
Traefik routes traffic to containers before any healthcheck is performed

### ISSUE THREAD

**Issue by gnur** [containous/traefik#1245]
### What version of Traefik are you using (`traefik version`)?
1.1.1 and also testend on 1.2.0-rc2

### What is your environment & configuration (arguments, toml...)?
We are using DCOS with traefik 1.1.1

config (relevant part) looks like this
```
[marathon]
endpoint = "http://master.mesos:4242"
watch = true
exposedByDefault = false
```

Marathon healthcheck was defined like this:
```
  "healthChecks": [
    {
      "protocol": "HTTP",
      "path": "delayedHealthy",
      "gracePeriodSeconds": 1,
      "intervalSeconds": 2,
      "timeoutSeconds": 1,
      "maxConsecutiveFailures": 5,
      "ignoreHttp1xx": false
    }
  ],
```

### What did you do?
I created a container that fails healthChecks for n seconds (10 default, or changed by env var) and after that succeeds the healthcheck.

### What did you expect to see?
I expected that traefik would not route traffic to the container until after those 10 seconds had passed.

### What did you see instead?
As soon as the container entered the `running` state in DCOS, traefik started routing traffic to the container. After the first healthcheck was run, traefik stopped routing traffic. Then, after the ten seconds, traefik started routing traffic again to the container.
As you can see in the below excerpt, from 15:16:41 to 15:16:44 no healthCheck had run yet, but traefik was routing traffic to the container. And after 10 seconds (after 15:16:52) the healthCheck was passing and traffic was routed to the container correctly.

```
while sleep 0.5; do echo "$(date +%T) $(curl --silent -H 'Host: slowstart.example.com' http://dcos-agent:9997/)"; done 
15:16:39 404 page not found
15:16:40 404 page not found
15:16:40 404 page not found
15:16:41 ok
15:16:41 ok
15:16:42 ok
15:16:43 ok
15:16:43 ok
15:16:44 ok
15:16:44 404 page not found
15:16:45 404 page not found
15:16:45 404 page not found
15:16:46 404 page not found
15:16:46 404 page not found
15:16:47 404 page not found
15:16:48 404 page not found
15:16:48 404 page not found
15:16:49 404 page not found
15:16:49 404 page not found
15:16:50 404 page not found
15:16:50 404 page not found
15:16:51 404 page not found
15:16:51 404 page not found
15:16:52 404 page not found
15:16:52 ok
15:16:53 ok
15:16:54 ok
15:16:54 ok
15:16:55 ok
15:16:55 ok
15:16:56 ok
```

I already have PR ready for this, this issue serves as reference for that.

**Comment by timoreimann** [comment]
I'm going to close this issue for reasons outlined in #1246.

Refs #1185.

#1250 is supposed to improve documentation in this regards.
