### ISSUE TITLE
Add OnDemand check in ACME

### ISSUE THREAD

**Issue by emilevauge** [containous/traefik#1249]
If `OnDemand` is activated, check if new cert request is not already set in the manual config.

**Comment by CyrilPeponnet** [comment]
the current code is already returning the cert if present:

```
func (a *ACME) loadCertificateOnDemand(clientHello *tls.ClientHelloInfo) (*tls.Certificate, error) {
	domain := types.CanonicalDomain(clientHello.ServerName)
	account := a.store.Get().(*Account)
	if certificateResource, ok := account.DomainsCertificate.getCertificateForDomain(domain); ok {
		return certificateResource.tlsCert, nil
	}
```

As I'm in this part of code currently, let me know what you want to achive and I can help implementing it.

**Comment by ldez** [comment]
I'll close this issue, because I think the question is answered, but feel free to continue the conversation.

**Comment by MihaMarkic** [comment]
Ehm, what exactly is the problem that is causing it and the solution to it? I have the probably same problem. Thanks.
