### ISSUE TITLE
Ability to add multiple docker endpoint (failover)

### ISSUE THREAD

**Issue by WTFKr0** [containous/traefik#1255]
Hi,

I have a swarm cluster with 2 managers
I have a traefik instance (not in that swarm)
I want to tell traefik to fetch docker info from manager1:2375
But if this node is going down (for maintenance or crash), I want traefik to failover on manager2:2375
Is that possible ?

Thanx for reading

**Comment by CyrilPeponnet** [comment]
You can use an external solution like DNS RR or keepalived with a vip.

**Comment by nmengin** [comment]
@WTFKr0 , can you explain the context of you need.
Indeed, the normal behavior is to use Traefik **as a Docker containe**r on the swarm manager node.
So, if the manager goes down, Docker will move your Traefik container on the other manager.

**Comment by WTFKr0** [comment]
Hi, thanx for reading.
I don't remember exactly the purpose of this issue :rofl: 
But I think it was to provide a failover IP
If traefik in swarm, and one node goes down, you have to reach to other node (other IP)
Today we have a haproxy (on a third host) doing that failover between our 2 nodes, so I think we can close that !
Thanx
