### ISSUE TITLE
Set a default backend

### ISSUE THREAD

**Issue by llonchj** [containous/traefik#1256]
Given a network with backends defining specific names: `db.example.com`, `mail.example.com`, `www.example.com`, how can I set all the traffic not for `db` or `mail` backends  to go to `www`?

**Comment by llonchj** [comment]
setting a lower `priority` to www worked

**Comment by oppianmatt** [comment]
example would be nice? How do you set a default backend, i.e. a backend that all traffic will go to unless otherwise matched by some other rule?

**Comment by Neirda24** [comment]
👍 @llonchj : Can you show us an example please ? I'd like the same thing as @oppianmatt described.

**Comment by llonchj** [comment]
@Neirda24 It has been long time since i implemented that. By memory i used the priority definition https://docs.traefik.io/basics/#priorities
