### ISSUE TITLE
Possible bug using `--web.metrics.prometheus`

### ISSUE THREAD

**Issue by llonchj** [containous/traefik#1261]
### What version of Traefik are you using (`traefik version`)?

`traefik:morbier`

### What is your environment & configuration (arguments, toml...)?

See [`docker-compose.yml`](https://gist.github.com/llonchj/6750514d9fe03c3e2304a55e711b0b9c)

### What did you do?

Download [`docker-compose.yml`](https://gist.github.com/llonchj/6750514d9fe03c3e2304a55e711b0b9c) and run:

```
docker-compose up -d

sleep 10

curl localhost:8080/api/providers | jq '.docker["backends"]["backend-nginx"]["servers"]'
curl localhost:8081/api/providers | jq '.docker["backends"]["backend-nginx"]["servers"]'

docker-compose scale nginx=2

sleep 10

curl localhost:8080/api/providers | jq '.docker["backends"]["backend-nginx"]["servers"]'

curl localhost:8081/api/providers | jq '.docker["backends"]["backend-nginx"]["servers"]'

docker-compose down -v
```

### What did you expect to see?

After scaling up nginx, both traefik instances should show 2 servers.

### What did you see instead?

After scaling up nginx, `traefik-with-prometheus-metrics` (port 8080) shows only 1 server.

**Comment by timoreimann** [comment]
Hi @llonchj,

we believe the issue should be fixed by #1258. Do you possibly have a chance to run a test with a specific version of the current release candidate [mentioned here](https://github.com/containous/traefik/issues/1251#issuecomment-286566310)?

**Comment by llonchj** [comment]
Thanks @timoreimann, it works with `containous/traefik:c582ea5ff0c72df13962eeca4bff3b337db4e865`.
Closing the issue.

**Comment by timoreimann** [comment]
Glad to hear!

Thanks for reporting.
