### ISSUE TITLE
Docker and domains

### ISSUE THREAD

**Issue by dimitrov-adrian** [containous/traefik#1263]
Using morbier and previously camembert with docker (just starting to using, not on production yet), I found working with domains to be complex and difficult.

First `traefik.domain` label seems not to work, and even if it work in future, I can't set it on the fly because labels on dockers are immutable.

Then I decided to use container names as domains, seems to works for subdomains, but if I set docker.domain to empty string in the `traefik.toml` it append dot at the end so this is not an option too.

For docker containers, you could set domain and hostname as network options but this is not respected from traefik (sadly but true)

Then I'v tried to  setup manual rules from file and point frontend to already done backend from dockers (I mean `backend-CONTAINER_NAME`) which seems to not working too.

So what I found is the only working for me way.

Creating backend that point url to automatic docker generated (`CONTAINER_NAME.DOCKER_DOMAIN`) and create and associate frontend with this backend, and the only plus of having docker configured is that have automatic urls, nothing more.

May be the problem is on me as not understanding the tool very well, documentation didn't help a lot (may be I am missing something).
So could you point me where I am wrong? And may be implement in next versions mechanism of easy domain mapping and multiple domain (aliasing) assignment.

Don't let me wrong, this peace of software seems to be really helpful.

**Comment by pascalandy** [comment]
It would help you could share your traefik container commands arguments plus your container argument. 

Cheers!

**Comment by dimitrov-adrian** [comment]
These are my toml files

[rules.toml.txt](https://github.com/containous/traefik/files/833364/rules.toml.txt)
[traefik.toml.txt](https://github.com/containous/traefik/files/833365/traefik.toml.txt)

But reading what I already write, may be I should open new issues about the ideas that have.

**Comment by traefiker** [comment]
I'll close the issue due to inactivity but feel free to re-open if needed.
