### ISSUE TITLE
Make the CI great again!

### ISSUE THREAD

**Issue by emilevauge** [containous/traefik#1266]
I can remember the good old times when all our tests were passing in less than 10 minutes on Travis.
Now [it's more like](https://github.com/containous/traefik/pull/1209#issuecomment-285062581) that:
> gopkg.in is flaking again. Retriggered the build.
>...
>Grrr, and now the integration tests are flaking. :(
>Retrying HARDER...

ALL THE TIME!

This global issue is here to list all the work we need to do in order to make the CI great again.

- [x] replace fixed timeouts re: docker compose readiness with `utils.Try` #1267 by @timoreimann 
- [x] test Travis alternative like CircleCI or SemaphoreCI
- [x] Improving Parallelism of tests.
- [ ] Reducing the setup time of a testing environment
- [ ] Simplify the process for a contributer to add a parallel test such as integration

**Comment by dtomcej** [comment]
We should also work on:

- Improving Parallelism of tests.
- Reducing the setup time of a testing environment
- Simplify the process for a contributer to add a parallel test such as integration

**Comment by vdemeester** [comment]
> Simplify the process for a contributer to add a parallel test such as integration

It's more like : simplify the process for a contributor to add tests, mainly unit-test (we should have way more unit test, and very good coverage in unit test, than integration tests)

**Comment by atbore-phx** [comment]
Today I have performed a CI platform switch to circle-ci v.2 (cci2), forking the main traefik repo and the library too.
I've also translated the .travis.yml in the new .circleci/config.yml here https://github.com/atbore-phx/traefik.
The job created use the "machine" executor, cciv2 seams slower then travis see the picture and the link attached.
https://circleci.com/gh/atbore-phx/traefik/12
![cciv2_job](https://cloud.githubusercontent.com/assets/11421185/25540802/9ec2524a-2c4c-11e7-8ffd-a10eecc6b918.png)

those features could help to reduce the execution:
-  cache for the docker images
- test parallelization (we need to evaluate the impact on the actual test suite)
but the slower part is the cross compilation.

Next days I'll test SemaphoreCI.

**Comment by vdemeester** [comment]
The main problem is cross compilation. It is taking more than all other steps.. We should run it parallel/separate.

**Comment by timoreimann** [comment]
One idea is to only test a single architecture per operating system on each PR (e.g., Linux, Windows, and Darwin each on amd64) and postpone the other architectures to a less frequently running job. the latter could be the master branch, a daily cron, or a pre-release step.

**Comment by atbore-phx** [comment]
today i've done some tests related to the task "make crossbinary".
i have deployed several droplets on digital ocean changing the CPU/RAM ratio and just a try with semaphoreCI.

here the results:

| VM/task          | VM (digital ocean) 2 CPU 2GB RAM | VM (digital ocean) 4 CPU 8GB RAM | VM (digital ocean) 8 CPU 16G RAM | VM (digital ocean) 12 CPU 32GB RAM | VM (digital ocean) 16 CPU 48 GB RAM | semaphoreCI |
|------------------|----------------------------------|----------------------------------|----------------------------------|------------------------------------|-------------------------------------|-------------|
| make crossbinary | 27m10.272s                       | 18m3.101s                        | 16m40.817s                       | 16m59.277s                         | 18m6.143s                           | 9m19        |




semaphoreCI seems to have good performances, here its build :
https://semaphoreci.com/atbore/traefik/branches/master/builds/2

**Comment by atbore-phx** [comment]
i have introduced some parallelism ay make level (make -j2) reducing the execution time of make crossbinary of ~28%

**Comment by atbore-phx** [comment]
tested docker cache on semaphore https://semaphoreci.com/docs/docker.html, but i got "no space left on device" during the snapshoot.
https://semaphoreci.com/atbore/traefik/branches/master/builds/7
i have opened a ticket to semaphore support.

**Comment by atbore-phx** [comment]
docker cache is now working we reach the limit i think,
make -j3 + docker-cache 6 min

**Comment by atbore-phx** [comment]
SemaphoreCI has been added as integration to our repo, the cache has been disabled:

**Comment by atbore-phx** [comment]
I have started to reduce the docker image size with this PR: https://github.com/containous/traefik/pull/1580

**Comment by emilevauge** [comment]
I think we can close this one now (tests are built in 15m instead of 50m) :hugs:
