### ISSUE TITLE
Replace fixed readiness timeouts in docker-compose fixture setups by retry-based readiness checks

### ISSUE THREAD

**Issue by timoreimann** [containous/traefik#1267]
A number of our integration tests assume that the docker-compose fixture setup will be completed within a static time frame. This brings two drawbacks:

- If the setup completes earlier, we waste time waiting.
- If the setup would take tolerantly longer, we don't wait but shoot down the test.

We should try to move to an approach where we continuously determine the readiness state, capped by a reasonable upper time bound. `utils.Try` should be our friend.

Refs #1266.

**Comment by ldez** [comment]
Closed by #1599
