### ISSUE TITLE
Proxy set header

### ISSUE THREAD

**Issue by klud1** [containous/traefik#1270]
I'm learning about docker and its capabilities, i'm moving the most of the things i have to docker and recently found Traefik.

I used nginx as a reverse proxy, and now i'm trying to figure out a way have a Nextcloud installation working along with traefik, because of the ```proxy_set_header``` which i haven't found any existence of it in traefik (been reading the docs but nothing, maybe i missed anything? i don't know).

When using nginx as nextcloud proxy i add these headers:
```
proxy_set_header Strict-Transport-Security "max-age=31536000";
proxy_set_header X-Content-Type-Options nosniff;
proxy_set_header X-Frame-Options "SAMEORIGIN";
proxy_set_header X-XSS-Protection "1; mode=block";
proxy_set_header X-Robots-Tag none;
proxy_set_header X-Download-Options noopen;
proxy_set_header X-Permitted-Cross-Domain-Policies none;
```

is there a way to aproach this on traefik? otherwise it'd be amazing if this feature is added.

**Comment by dtomcej** [comment]
I am working on adding this functionality right now in
https://github.com/containous/traefik/pull/1236

**Comment by klud1** [comment]
@dtomcej amazing, hope this is available soon, thank you so much!

**Comment by dublinus** [comment]
What about something like this:

``
proxy_set_header Host $http_host;
``

Is this possible in traefik?
