### ISSUE TITLE
PathPrefixStrip should inject additional header

### ISSUE THREAD

**Issue by suyogbarve** [containous/traefik#1272]
Traefik version : 1.2.0

I am looking for resolution for my problem
I am trying to achieve multi-tenancy by using namespaces as follows

1. Container C1 runs webpage on its context root like `127.0.0.1/index`
1. This container gets deployed to multiple namespaces example Chicago, Houston, Miami
1. Each namespace has a kubernetes deployment+ service example `SVC=CityInfo`
1. This model should allow me to use same type of container image to create city specific services example `Chicago/CityInfo/index`, `Houston/CityInfo/index`, `Miami/CityInfo/index`
e. Using Traefik I am able to expose them like `http://LB/Chicago/CityInfo/index`, `http://LB/Houston/CityInfo/index`, `http://LB/Miami/CityInfo/index`
(Annotation `pathprefixstrip` helps me to directly route the request `/Chicago/CityInfo/index.html` to  corresponding pod directly on context root `/index` {pod correspoding to `NS=Chicago` and `SVC=CityInfo`} by stripping out `Chicago/CityInfo/` )

So far everything is good, but problem arises when we application tries to return hypermedia on index page

Example:
Since the original request `http://LB/Houston/CityInfo/index`  ------> gets converted to `http://LB/index`  when it hits the application running in pod (by virtue of `pathprefixstrip`) ------>
So now the application generates hypermedia in following format
`http/LB/Food`, `http://LB/Attractions`
however it should have ideally been `http://LB/Houston/CityInfo/Food`  and `http://LB/Houston/CityInfo/Attractions`

Note:
Please note that in my environment, I do not have luxury to create fqdn like
`houston.CityInfo.portal.com`  or `chicago.CityInfo.portal.com`
which would have completely eliminated above problem of url-rewriting

My recommendation is to inject additional header HTTP whenever `PathPrefixStrip` annotation is used

**Comment by timoreimann** [comment]
The usual solution to this problem is to parameterize the application with the prefix it's running under. I agree though that injecting the prefix through a header would be even more convenient.

**Comment by ldez** [comment]
Closed by #1442

**Comment by ldez** [comment]
may related to #1442

**Comment by kachkaev** [comment]
Does there exist a conventional header name for this purpose? I had the similar issue once, but I was able to resolve it by using relative links in the apps (both for links and css/js sources).

**Comment by dtomcej** [comment]
The current implementation of this is to inject the stripped path into the `X-Forwarded-Prefix` as per our docs. Your app can pick up the stripped path that way.

Since this has now been implemented, I will go ahead and close this issue.

If you have any further issues, feel free to open a new ticket.
