### ISSUE TITLE
Make sure published documentation match the latest stable release

### ISSUE THREAD

**Issue by timoreimann** [containous/traefik#1279]
Currently our published docs are ahead of the latest stable release since they are produced along the Travis CI run. We should improve the process so that users aren't confused by instructions that don't match what we announce as the stable release.

/cc @containous/traefik

**Comment by timoreimann** [comment]
We should debate whether we first try to match the single published doc version with stable; or go straight for a solution where we provide versioned documentations so that users not using the latest and greatest (and most stable) Traefik binary can still easily find "their" docs.

**Comment by vdemeester** [comment]
I vote for *versionned documentations* 👼

**Comment by timoreimann** [comment]
Me too. ☺️

The interesting question: should we go _straight_ to versioned docs; or is it significantly easier to match our single-versioned docs first so that users stop being confused _now_? That is, can we take an intermediate step to make things better in the short termwhile working on the big improvement?

**Comment by ldez** [comment]
Fixed by #2429
