### ISSUE TITLE
Use | , & instead of , and ; with frontend.rule

### ISSUE THREAD

**Issue by sriyer** [containous/traefik#1280]
traefik version : 1.1.1
we use traefik with consul catalog as its backend. Registrator popluates data to the consul catalog. Tags are use for configuring front end rules for a service to be picked and configured by traefik. Consul allows storing multiple tags irrespective of the purpose for which they are used, we do use tags for tagging the service with specific metadata, traefik front end rules being one of them. Each of these tags are required to be separated by ',' which in turn get picked as separate tag entries on the catalog for the service.

With traefik having ',' as a separator for `||` conditions, results in the rules that acutally intened to be part of an or condition, get added a separate tag entires.

eg> `traefik.frontend.rule=Host:myservice.domain.com,myservicetwo.domain.com` 
should result in rules that perform an `||` condition on the presence of either of the two as Host header values.

since the ',' character is being seen as a separator charter to separate multiple tags, the rules get put in as separate tags rather than a single rule.

consul catalog

`myservice {
         "traefik.frontend.rule=Host:myservice.domain.com",
         "myservicetwo.domain.com"
}`
instead of
`myservice {
         "traefik.frontend.rule=Host:myservice.domain.com,myservicetwo.domain.com"
}`

it would be better if `||` is used instead of `,` and `&&` instead of `;`

**Comment by sriyer** [comment]
@emilevauge based on your comments on the pull request #1860 we are looking to make the changes to rules.go to add the filtering for || and &&.

**Comment by gtrias** [comment]
Is there any plan to fix this? I find useless the Consul Catalog integration without this feature. I really need to define several `traefik.frontend.rule`but the registrator is splitting the tags by the ',' character.

**Comment by dtomcej** [comment]
Since the release of Traefik v2, rules now use `||` and `&&` to build rule chains:

https://docs.traefik.io/v2.0/routing/routers/#rule

For this reason, I will close this issue.
