### ISSUE TITLE
Go to backend if request contain custom http header

### ISSUE THREAD

**Issue by oleg-filiutsich** [containous/traefik#1289]
### What version of Traefik are you using (`traefik version`)?
    v1.1.2 

### What is your environment & configuration (arguments, toml...)?
`
docker service create --name traefik --network swarm-network --constraint=node.role==manager --publish 80:80 --publish 8080:8080 --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock traefik --docker --docker.swarmmode --docker.domain=traefik --docker.watch --web
`

### What did you do?
```
docker network create --driver=overlay --opt encrypted swarm-network

docker service create --name traefik --network swarm-network --constraint=node.role==manager --publish 80:80 --publish 8080:8080 --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock   traefik --docker --docker.swarmmode --docker.domain=traefik --docker.watch --web

docker service create --name whoami0_1 --network swarm-network --label traefik.port=80 --label traefik.frontend.rule=Path:/test;Headers:my-header/v1 --label traefik.weight=10 emilevauge/whoami
docker service create --name whoami0_2 --network swarm-network --label traefik.port=80 --label traefik.frontend.rule=Path:/test;Headers:my-header/v2 nginx

curl -v -H "Headers:my-header/v2" http://$(docker-machine ip mm-swarm-master)/test
```

### What did you expect to see?
nginx content from service whoami0_2

### What did you see instead?
404 page not found from traefik

**Comment by traefiker** [comment]
I'll close the issue due to inactivity but feel free to re-open if needed.
