### ISSUE TITLE
Backend server with weight "0"

### ISSUE THREAD

**Issue by rogeriollacerda** [containous/traefik#1294]
### What version of Traefik are you using (`traefik version`)?
1.2.0-rc2

### What is your environment & configuration (arguments, toml...)?
Zookeeper provider

### What did you do?
Set backend server with weight "0" and another two others with weight "100"

### What did you expect to see?
Server with weight "0" could not receive requests.

### What did you see instead?
For each 200 requests (2 servers with weight 100) 1 is going to server with weight "0"

When I set weight "1" instead "0", I have the same behavior: 200 requests and 1 to server with weight 1. I think that setting "0" or "1", traefik load as the same value.

**Comment by vdemeester** [comment]
(will be fixed by #1780)

**Comment by traefiker** [comment]
Closed by #3130.
