### ISSUE TITLE
Sticky sessions/cookie will not check if the backend still exists

### ISSUE THREAD

**Issue by christopherobin** [containous/traefik#1299]
Using the current `morbier` release candidate (`rc2`).

### Issue

Using docker let's say I start a service with replica set to 5 and sticky sessions, a user connects and gets assigned to the 5th backend, in the process setting the cookie to the IP of that service.

Now a couple days later the user tries to connect again but for some reason the service was scaled back to 3 replicas and replica 5 is gone, instead of doing a fallback to another server currently traefik will force the routing to go to the given target backend.

The cookie is set to be removed when the browsing session ends but Chrome 57 seems to be keeping it forever, maybe because I have set it to resume my session on exit/restart.

### Possible Solutions

* Check if the given backend is up on access if given a sticky cookie (might be a little expensive to do on every query)
* If we get a gateway timeout expire the cookie so that on next refresh we get a proper backend (though we might want to keep the cookie if the backend is in the configuration and just unhealthy)

**Comment by timoreimann** [comment]
@christopherobin thanks for filing the issue.

Do I understand correctly that according to your tests, Traefik does not switch the backend if the "sticky one" becomes unavailable? If that's not the case, then we have a bug (because the documentation states otherwise).

**Comment by christopherobin** [comment]
Tested some more, it seems to be kinda hit or miss, sometimes it will properly update the backend instantly, and sometimes I get a timeout with "Bad Gateway" after 30s that gets fixed with a couple more refreshes.

**Comment by christopherobin** [comment]
Sorry, it might actually have been bug #1156 since I can't seem to reproduce it once `traefik.docker.network` is set properly.
Closing the issue, will monitor some more and re-open if necessary.
