### ISSUE TITLE
Traefik cannot connect to containers on other servers in rancher HA environment

### ISSUE THREAD

**Issue by bseng** [containous/traefik#1300]
### What version of Traefik are you using (`traefik version`)?
v.1.2.0-rc2

### What is your environment & configuration (arguments, toml...)?
traefik docker with --web --rancher --rancher.domain --rancher.accesskey --rancher.secretkey as stack in rancher
rancher in HA and running agents on all multiple servers

### What did you do?
load balancing containers

### What did you expect to see?
able to access the container

### What did you see instead?
I can only access to the container when it is on the same server as traefik, but when the container is not on the same server, it can't access.
but the ip register on traefik dashboard without issues.

Can someone test this scenario as well? thanks.

**Comment by timoreimann** [comment]
Could you please paste the log output when running in debug mode (set the `--debug` switch)? Thanks.

**Comment by bseng** [comment]
I find out is actually the ipsec on rancher server goes into a state where I can't ping the internal ip of the other servers. I don't think is a problem now. thanks
