### ISSUE TITLE
Acme fails to work with Zookeeper

### ISSUE THREAD

**Issue by andrewl3wis** [containous/traefik#1301]
### What version of Traefik are you using (`traefik version`)?
Version:      v1.2.0-rc2
Codename:     morbier
Go version:   go1.7.5
Built:        2017-03-01_01:13:09PM
OS/Arch:      linux/amd64

### What is your environment & configuration (arguments, toml...)?
```shell
sudo ./traefik_linux-amd64 -c traefik.toml
```
Using the marathon backend, attempting to store configuration in zookeeper

### What did you do?
Setup the marathon backend successfully with ACME support and then tried to move its config into Zookeeper. 

### What did you expect to see?
Sucessfully use of the backend to store config for HA

### What did you see instead?

```shell
2017/03/15 17:41:12 Connected to 10.0.4.73:2181
2017/03/15 17:41:12 Authenticated: id=97413602563260474, timeout=30000
2017/03/15 17:41:13 structs.go:21: Connected to 10.0.4.73:2181
2017/03/15 17:41:13 structs.go:21: Authenticated: id=97413602563260475, timeout=30000
ERRO[2017-03-15T17:41:13Z] Datastore sync error: Object lock value: expected edee9a61-cb84-4c6d-84ad-ea8eb211b28f, got , retrying in 748.957544ms 
ERRO[2017-03-15T17:41:13Z] Datastore sync error: Object lock value: expected edee9a61-cb84-4c6d-84ad-ea8eb211b28f, got , retrying in 1.069770067s 
ERRO[2017-03-15T17:41:14Z] Datastore sync error: Object lock value: expected edee9a61-cb84-4c6d-84ad-ea8eb211b28f, got , retrying in 1.134574728s 
ERRO[2017-03-15T17:41:16Z] Datastore sync error: Object lock value: expected edee9a61-cb84-4c6d-84ad-ea8eb211b28f, got , retrying in 1.27403991s 
ERRO[2017-03-15T17:41:17Z] Datastore sync error: Object lock value: expected edee9a61-cb84-4c6d-84ad-ea8eb211b28f, got , retrying in 3.054537854s 
ERRO[2017-03-15T17:41:20Z] Datastore sync error: Object lock value: expected edee9a61-cb84-4c6d-84ad-ea8eb211b28f, got , retrying in 3.868985073s 
```

**Comment by meatlewis** [comment]
Also fails to work with latest release 1.1.2

**Comment by nmengin** [comment]
Hello @meatlewis.

In the new Træfik version (1.5), we migrate to the new version of `libkv` librairy which has to fix this kind of bug.
Can you try with this version?

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Slack workspace](https://traefik.herokuapp.com/) for more [community #support](https://traefik.slack.com/messages/C0CDT22PJ/).
