### ISSUE TITLE
send traefik access logs to stdout

### ISSUE THREAD

**Issue by r0bj** [containous/traefik#1306]
traefik: 1.1.2

I didn't find a way to send access logs `accessLogsFile` to stdout using official docker image.

It would be useful to have something like:
```
accessLogsFile = stdout
```

Or similar to `traefikLogsFile` - if not defined, send logs to stdout.

Using docker It's recommended to send all logs to stdout so that some collector could gather them, aggregate, etc.

**Comment by Regner** [comment]
I make no promises but I am at least looking into what this would take. Started asking some questions on Slack. Will let you know if I make any progress.

**Comment by marco-jantke** [comment]
We also need this feature in order to get Traefik production in our environment, therefore I will have a look at the issue and try to create a PR soon for it.

**Comment by ldez** [comment]
A huge refactor of the access logger,  see https://github.com/containous/traefik/pull/1485

**Comment by marco-jantke** [comment]
@ldez thank you for the hint. Honestly I think it makes more sense to await that PR and then to add another one adding the stdout logging capability. Otherwise it could be work for the 🗑

**Comment by argeiger** [comment]
@r0bj, you can do the following:

mkfifo -m 600 /tmp/logpipe
cat <> /tmp/logpipe 1>&2 &
chown traefik:traefik /tmp/logpipe

Then in your toml file point accesslogs to /tmp/logpipe.  I know this is a little dirty but it works.  Would still like a true implementation vs. workaround.

**Comment by timoreimann** [comment]
Fixed by #1683.
