### ISSUE TITLE
Update Kubernetes tests to properly handle endpoints not existing

### ISSUE THREAD

**Issue by Regner** [containous/traefik#1307]
In #1295 I introduced a temporary work around, this issue is for removing that and cleaning up the tests that break.

The code that originally causes the issue is this:
```
func (c clientMock) GetEndpoints(namespace, name string) (*v1.Endpoints, bool, error) {
	if c.apiEndpointsError != nil {
		return &v1.Endpoints{}, false, c.apiEndpointsError
	}

	for _, endpoints := range c.endpoints {
		if endpoints.Namespace == namespace && endpoints.Name == name {
			return endpoints, true, nil
		}
	}

	return &v1.Endpoints{}, true, nil
}
```

The final return has true as the second value being returned even if no endpoints for the service were found. This means the tests never hit the code path for `!exists` here: https://github.com/containous/traefik/blob/master/provider/kubernetes.go#L240

Instead what happens is all the tests that don't specify endpoints go through and hit the code path for `len(endpoints.Subsets) == 0`.

We need to update the mock `GetEndpoints` function to return `false` for the second return value when no endpoints are found, fix all the tests that break, and then ensure that there is a test that tests the current code path being used.

Here are the tests that fail when the `GetEndpoints` function returns correctly: TestHostlessIngress, TestLoadMultipleNamespacedIngresses, TestLoadNamespacedIngresses, TestGetPassHostHeader, TestOnlyReferencesServicesFromOwnNamespace, TestLoadIngresses

Related to this is defining and possibly changing what happens when endpoints are not found. Currently when a service is not found the referencing frontend is removed. However if no endpoints are found we still keep the frontend. Should we be removing the frontend if no endpoints are found?

**Comment by timoreimann** [comment]
Superb issue description, appreciated!

**Comment by timoreimann** [comment]
Looks like #1462 is now covering the endpoints-not-found case.
