### ISSUE TITLE
ip-per-task breaks Marathon provider for DCOS (mesos versions >= 0.25.0)

### ISSUE THREAD

**Issue by actaeon** [containous/traefik#1311]
### What version of Traefik are you using (`traefik version`)?
v1.2.0-rc2

### What is your environment & configuration (arguments, toml...)?
Running in Docker via the official v1.2.0-rc2 container. No args passed to traefik, just the config (below) via bind-mount at runtime.

The issue reported here occurs when viewing any backends in Traefik, but only with containers using BRIDGE mode. Containers using HOST networking do not seem to be effected. (Only one backend example is included below for brevity, but all backends using BRIDGE display this behavior.) 

DCOS version 1.8.4 which includes:
Mesos version: 1.0.1 (a22b5dd552168a8dd925682f3b349059e10fc3d3)
Marathon Version: 1.3.0

traefik.toml:

```
debug = false
logLevel = "DEBUG"
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"

[web]
address = ":8080"

[web.statistics]
  RecentErrors = 10

[marathon]endpoint = "http://<host 1>:8080,http://<host 2>:8080,http://<host 3>:8080,http://<host 4>:8080,http://<host 5>:8080"
watch = true
domain = "<domain>"
marathonLBCompatibility = true
```

### What did you do?
```
$ curl -s -XGET <traefik IP>:<traefik web port>/api/providers/marathon/backends/backend-teams-container-fabric-production-helloworld-service | jq
```

### What did you expect to see?

I expected to find the cluster routable addresses for the Mesos Agents used for the backends. 

The output from a 1.1.2 Traefik instance shows this:

```
{
  "servers": {
    "server-teams_container-fabric_production_helloworld-service-f90ad577-0b2d-11e7-8ca6-e27bcd87aa55": {
      "url": "http://10.11.13.24:27362",
      "weight": 0
    },
    "server-teams_container-fabric_production_helloworld-service-f90e09c8-0b2d-11e7-8ca6-e27bcd87aa55": {
      "url": "http://10.11.2.167:7374",
      "weight": 0
    }
  },
  "loadBalancer": {
    "method": "wrr"
  }
}
```

### What did you see instead?

I saw non-routable Docker bridge addresses used for the backends.

The output of a Traefik instance shows this:

v1.2.0-rc2

```
{
  "servers": {
    "server-teams_container-fabric_production_helloworld-service-f90ad577-0b2d-11e7-8ca6-e27bcd87aa55": {
      "url": "http://172.17.0.5:27362",
      "weight": 0
    },
    "server-teams_container-fabric_production_helloworld-service-f90e09c8-0b2d-11e7-8ca6-e27bcd87aa55": {
      "url": "http://172.17.0.8:7374",
      "weight": 0
    }
  },
  "loadBalancer": {
    "method": "wrr"
  }
}
```

### Speculate wildly about what might be wrong

I believe this was caused by [this function](https://github.com/diegooliveira/traefik/blob/c3088d02f9bebf0272cd927d95cce506daec9930/provider/marathon.go#L351), which was part of the IP-PER-TASK PR, in combination with [this mesos change](https://github.com/apache/mesos/blob/0.25.0/src/docker/executor.cpp#L177).

Mesos is sending the IP addresses assigned by Docker in its TaskStatus messages, which Marathon receives and reports as the Task's IP. The getBackendServer() function in the IP-PER-TASK PR sort of assumes that if it sees an IP in the Marathon Task, that it must have been deliberately assigned, and is therefore the preferred IP to use for the Task. Ordinarily, this would be a legit assumption, but because of the Mesos change above it isn't.

**Comment by actaeon** [comment]
BTW, if anybody else runs into this, the a workaround is to supply a custom Marathon template which references the host's IPs. [This one](https://github.com/containous/traefik/blob/404a73a712da4a283e77a15a89f66d1c18c466e6/templates/marathon.tmpl) should work.

**Comment by timoreimann** [comment]
A very related (possibly identical) issue has been discussed in #1243. We came up with the proposed solution to make the host part configurable.

Do you think that solution would work for you? If so, can we close this issue?

**Comment by actaeon** [comment]
I don't know how I missed that issue, apologies for the dup. Yes, that solution works just fine for us.
