### ISSUE TITLE
How to set up frontend and backend with both websocket (ws, wss) and https?

### ISSUE THREAD

**Issue by guyspronck** [containous/traefik#1327]
### What version of Traefik are you using (`traefik version`)?
v1.1.2

### What is your environment & configuration (arguments, toml...)?
Using file backend, running in docker.

**traefik.toml**
```
InsecureSkipVerify = true
defaultEntryPoints = ["http", "https","ws", "wss"]
[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
		entryPoint = "https"
  [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]

[acme]
...

[file]
filename = "/etc/traefik/servers.toml"
watch = true
```

**servers.toml**
```
[backends]
  [backends.backend1]
    [backends.backend1.servers.server1]
    url = "https://127.0.0.1:4433"
    
[frontends]
  [frontends.frontend1]
    backend = "backend1"
    passHostHeader = true
    [frontends.frontend1.routes.frontend1_1]
      rule = "Host:frontend1.domain"
```

### What do you want to do?
I have a host which has https and wss traffic, and I want to proxy this traffic through traefik. I cannot find proper documentation on this, if it's at all possible. 
How would I configure it that my requests from https://frontend1.domain go to https://127.0.0.1:4433 and wss://frontend1.domain go to wss://127.0.0.1:4433.

**Comment by guyspronck** [comment]
Anyone that can help me out? Otherwise I'll have to go back to my nginx proxy 😞

**Comment by emilevauge** [comment]
@guyspronck If you use `https://127.0.0.1:4433` in your backend server, it should work either with `https` and `wss`. Ave you tried this?

**Comment by emilevauge** [comment]
Can you update to the latest version 1.2.1?

**Comment by guyspronck** [comment]
@emilevauge there you go! Thanks for the tip, I've updated to 1.2.1 and websockets now just work 👍

**Comment by ianeinser** [comment]
@guyspr Hi, would you help me. I also have a host that supports both https and wss. The host serves multiple subdomains and one subdomain is particular for wss. The https subdomains work fine but the wss does not, it calls ws instead! this is my configuration

logLevel = "DEBUG"

## SSL ##
InsecureSkipVerify = true

defaultEntryPoints = ["http", "https", "ws", "wss"]

[traefikLog]
  filePath = "/etc/traefik/traefik.log"
  format   = "json"

[accessLog]
  filePath = "/etc/traefik/access.log"
  format = "json"

[web]
# Port for the status page
address = ":8080"
ReadOnly = true

[entryPoints]
  [entryPoints.http]
  address = ":80"
        [entryPoints.http.redirect]
        entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
.....

[docker]
.....

[file]
filename = "/etc/traefik/servers.toml"
watch = true

how to configure servers.toml?
