### ISSUE TITLE
Request certificate for other uses

### ISSUE THREAD

**Issue by strarsis** [containous/traefik#1328]
Is it possible to request a certificate over ACME using traefik as (HTTP) validation endpoint for 
a certificate that isn't intended to be used by traefik but by other services (e.g. mail server) - 
with custom options (SAN)?

**Comment by SantoDE** [comment]
No, currently this is not possible and we will probably not looking into this as it's far beyond traefik goals. 

You could use the regular [certbot](https://certbot.eff.org/) to achieve that :)

**Comment by strarsis** [comment]
How can I use certbot in combination with traefik? Traefik is already bound to HTTP port.
