### ISSUE TITLE
Referencing service variable which is nil in log message

### ISSUE THREAD

**Issue by Regner** [containous/traefik#1330]
In #1295 updated and added some log messages for when there is an error in retrieving a given service or the service does not exists.

See these two lines:
1) https://github.com/containous/traefik/pull/1295/files#diff-f9e99fb6bddb36d1640e40bc4bd36bc1R164
2) https://github.com/containous/traefik/pull/1295/files#diff-f9e99fb6bddb36d1640e40bc4bd36bc1R169

These log messages should be based on `i.ObjectMeta.Namespace` not `service.ObjectMeta.Namespace`.

**Comment by Regner** [comment]
@timoreimann I believe this can be closed now correct?

**Comment by timoreimann** [comment]
@Regner definitely -- thanks for the reminder!
