### ISSUE TITLE
Atempt to load balancing to the empty URL

### ISSUE THREAD

**Issue by yuriy-zhilovets2** [containous/traefik#1335]
### What version of Traefik are you using (`traefik version`)?
v1.2.0

### What is your environment & configuration (arguments, toml...)?
etcd backend on the bare Debian

### What did you do?
I have removed a key `/traefik/backends/servers/server1/url` but  `/traefik/backends/servers/server1` remained

### What did you expect to see?
Load balancing to the removed url has been stopped

### What did you see instead?
Traefik keeps sending requests to "server1" even when this server does not have any associated URL. As a result, clients get _500 Internal server error_.

**Comment by ldez** [comment]
Fixed by #2661
