### ISSUE TITLE
Docker build does not work on Windows

### ISSUE THREAD

**Issue by kelchm** [containous/traefik#1341]
### What version of Traefik are you using (`traefik version`)?
N/A - Current Master

### What is your environment & configuration (arguments, toml...)?
Windows 10
Docker version 1.13.0, build 49bf474

### What did you do?
I ran `make binary`

### What did you expect to see?
I expected the traefik binary to be built as documented in the contribution guide.

### What did you see instead?
```
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: invalid bind mount spec "/C/Program Files/Git/var/run/docker.sock;C:\\Program Files\\Git\\var\\run\\docker.sock": invalid volume specification: '/C/Program Files/Git/var/run/docker.sock;C:\Program Files\Git\var\run\docker.sock': invalid mount config for type "bind": invalid mount path: '\Program Files\Git\var\run\docker.sock' mount path must be absolute.
```

I was able to get the build working by setting `DOCKER_RUN_TRAEFIK` in the Makefile to `docker run $(TRAEFIK_ENVS) $(TRAEFIK_MOUNT) "$(TRAEFIK_DEV_IMAGE)"`.

**Comment by timoreimann** [comment]
I think the reason why we are bind-mounting the Docker socket into the build container is our integration tests which use docker-compose extensively. Thus, it's a case of Docker-in-Docker (dind).

According to [this StackOverflow answer](http://stackoverflow.com/a/41005007), adding an extra leading slash to the volume like

```
//var/run/docker.sock:/var/run/docker.sock
```

should work. Could you give it a try and report back?

Thanks!

**Comment by kelchm** [comment]
@timoreimann, I will test this next week. I also had to remove the `-it` flags from the docker run command as well.

**Comment by timoreimann** [comment]
:+1:

What happened when you kept the `-it` flag? We probably need it for the `shell` target.

**Comment by kelchm** [comment]
@timoreimann, the error received from docker was `cannot enable tty mode on non tty input`.

**Comment by timoreimann** [comment]
Hmm, I think you shouldn't get that error when you run Makefile targets from your Windows shell.

A quick Google search surfaced some issues with Cygwin vs. MiniGW vs. Bash. Maybe one of them pertain to you.

Calling @vdemeester for expert help.

**Comment by vdemeester** [comment]
yes @kelchm what is your setup ? i.e. cygwin, minigw, …, powershell, docker4windows (with linux containers) or just docker window native with windows containers (with or without docker4win) ?

**Comment by kelchm** [comment]
@vdemeester, I used the bash shell setup by the Git for Windows installer to run the makefile (https://git-for-windows.github.io/). Powershell doesn't work because it doesn't know what to do with make.sh.

**Comment by vdemeester** [comment]
@kelchm ah.. hum.. I think the Docker4win proxy to rewrite `-v` mount path might getting in the way.. I'll have to try that out at some point 😅

**Comment by kelchm** [comment]
After doing some more digging on this issue, it seems like Git-Bash is partially responsible.

Here is what I changed in my hacked together Makefile to make it all work:

```makefile
TRAEFIK_MOUNT := -v "C:\\Program Files\\Git\\Users\\mkelch\\Development\\traefik\\dist:/go/src/github.com/containous/traefik/dist"
...
INTEGRATION_OPTS := $(if $(MAKE_DOCKER_HOST),-e "DOCKER_HOST=$(MAKE_DOCKER_HOST)", -v "//var/run/docker.sock://var/run/docker.sock:ro")
...
DOCKER_RUN_TRAEFIK := winpty docker run $(INTEGRATION_OPTS) -it $(TRAEFIK_ENVS) $(TRAEFIK_MOUNT) "$(TRAEFIK_DEV_IMAGE)"```

I don't know very much about setting up a better bash environment on Windows (I generally stick to using Powershell on Windows).

**Comment by baluubas** [comment]
First time I ever attempted so build anything Go but it seemed microsoft/go-winio and golang.org/x/sys/windows was not compatible. 

Got a build through by copying a newer version of the golang.org/x/sys/windows code to vendor (since I couldn't figure out how to do the same thing with glide).

**Comment by ldez** [comment]
I'll close this issue, because I think the question is answered, but feel free to continue the conversation.
