### ISSUE TITLE
basic/digest auth per frontend..is that possible?

### ISSUE THREAD

**Issue by RXWatcher1** [containous/traefik#1351]
### What version of Traefik are you using (`traefik version`)?
2a61c9049f119b6e57c7d086f2c07f2086d7b2c1 / cheddar

### What did you do?

I am using Traefik with docker labels to setup dynamic paths ala:
	-l traefik.frontend.rule="PathPrefixStrip: /test"

I have http redirecting to https and basic auth setup for the https entry point.
It is working well.

### What did you expect to see?

I would like to setup basic/digest auth on a per frontend basis.

so
https://server/path1 uses  htpasswd1
https://server/path2 doesnt use any authentication
https://server/path3 uses htpasswd3

If it can be defined per frontend then I would have full control.

Thank you!

I love Traefik..I am finding more uses for it every day.

**Comment by timoreimann** [comment]
This looks very similar to #751. Could you please explain what the difference is supposed to be?

**Comment by RXWatcher1** [comment]
I did not see that issue. I will close this one. I see there is a pull request to resolve this. Hopefully it will allow   htpasswd use.

Thanks!
