### ISSUE TITLE
Broken SSL certificate when I am using HTTPS for Traefik

### ISSUE THREAD

**Issue by ilchebedelovski** [containous/traefik#1356]
I am using traefik 1.2.1 and I have problems with the SSL certificate that I am generating using ACME.

I am providing my .toml file:
logLevel = "DEBUG"
defaultEntryPoints = ["http","https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      MinVersion = "VersionTLS12"
      CipherSuites = ["TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"]
      [[entryPoints.https.tls.certificates]]
      CertFile = "/ssl/tls.crt"
      KeyFile = "/ssl/tls.key"
    [acme]
    email = "my.email@example.com"
    storage = "/acme/acme.json"
    entryPoint = "https"
    onDemand = true
    onHostRule = true
    acmeLogging = true
    caServer = "https://acme-staging.api.letsencrypt.org/directory"
    [[acme.domains]]
      main = "example.domain"
      sans = ["example.domain"]

I want to configure Letsencrypt certificates for HTTPS for my applications on Kubernetes 1.5.3 cluster.

When I am trying to access the url from browser (https://example.domain) I see: This site can’t provide a secure connection, ERR_SSL_PROTOCOL_ERROR

**Comment by caarlos0** [comment]
what was the problem? I'm having this issue as well...

**Comment by ilchebedelovski** [comment]
> what was the problem? I'm having this issue as well...

The solution was implemented by Traefik in v1.5.
