### ISSUE TITLE
[Question] Redirect requests that match a rule to an external URL?

### ISSUE THREAD

**Issue by gvilarino** [containous/traefik#1360]
### What version of Traefik are you using (`traefik version`)?
1.2.1

### What is your environment & configuration (arguments, toml...)?
```
traefik \
  --docker \
  --docker.swarmmode \
  --docker.domain=my.domain \
  --docker.watch \
  --web
```

I'd like all requests that go to `container.my.domain` to end up in a backend (it works, no problem) but among those, all for the root path (`container.my.domain/`) or for paths beginning with `/static` to get redirected to an external URL (i.e.: a CDN) while also being able to rewrite part of the URL (e.g.: for the root path, rewrite the URL to `/static/dist/index.html`)

Is this possible with the current state of Træfik by configuring a docker backend with labels?

If not, the workaround I'm thinking of would be adding an additional service (probably HAproxy) to the docker stack that matches the above path rules and that performs the required re-writes and re-directs the requests to the external CDN.

Any thoughts/ideas?

Thanks in advance, loving træfik so far.

**Comment by gvilarino** [comment]
Maybe a reasonable approach to this would be for a `backend` to specify different `servers` based on rules (just like `frontends`), via docker service/stack labels?

**Comment by dtomcej** [comment]
It should be possible to mount a toml with your rules defined. You can have multiple providers run, and forward to an external URL.

You would have to set the weight of your static rule to be much heavier than your docker rules to ensure it gets run.

**Comment by gvilarino** [comment]
@dtomcej would that be set at the `servers` level? I don't see from the docs that it supports rules. Also, I don't see how `frontents` can redirect to URLs, only to other `entrypoints` in the docs.

Would you be so kind to provide a super simple example?

**Comment by dtomcej** [comment]
I guess the question is:

Do you need a redirect? or are you wanting the request to be passed to your CDN?

If you want a full out redirect, you could look at the entrypoint regex redirect:
https://docs.traefik.io/toml/#entrypoints-definition

If you are looking to just have your request backed by something else (like a CDN, or another service), you can just use a file backend with an external url under the server definition:
https://docs.traefik.io/toml/#file-backend

:)

**Comment by gvilarino** [comment]
I want my request to be passed to a CDN with a bit of a re-write if the URL matches a pattern.

In essence, all URLs with their path beginning on `/api` or `/socket` should get forwarded to the backend, all others redirected to `cdn.mydomain.com`, while also adding `/static/dist/index.html` to the path if the URL matches no other rule.

From the docs I can tell this is possible on the `entryopoint` level, but there's no way of updating that from labels in a docker service (I'd like all configuration to come out of the docker swarm backends).

On a different aspect of this: how would you handle the external file configuration if this is running on a 3-master swarm and I can't foretell where the container will run and this where is the proper mountpoint for the `.toml` config file? (This is why I'd like to handle everything from labels in the docker stack file)

**Comment by traefiker** [comment]
I'll close the issue due to inactivity but feel free to re-open if needed.
