### ISSUE TITLE
Redirect route are refresh only for one provider

### ISSUE THREAD

**Issue by w3blogfr** [containous/traefik#1375]
### What version of Traefik are you using (`traefik version`)?

1.2.1

### What is your environment & configuration (arguments, toml...)?

I have static frontend declared in file part.
I'm connected to eureka provider to get backend, but I think other provider are concerned

```toml
[file]
  [frontends.api]
  backend = "backendEurekaMyApp"
    [frontends.api.routes.test_1]
    rule = "PathPrefixStrip:/main"
```

### What did you do?

I redirect frontend with rule `PathPrefixStrip` to backend declared in eureka part.

at startup,  i try url localhost/main/info, I get "404 not found" because backend is not here yet.

After 30 seconds, backend appeard in eureka. I refresh url. I still get "404 not found". 

Eureka has been refresh, but File rules frontend not.

**Temporary workarround.**

After few hours of search, I found a solution, I declared static rules in eureka tmpl instead of "File" part, so frontend rule is refresh in the same time as backend.

### What did you expect to see?

Furthermore, I think scope refresh is not applied in the same way depending rules used `Host`, `PathPrefixStrip`.

For host rule, refresh seem to be done in all case

### What did you see instead?

Thee is multiple solution:

1. First one could be to add details in documentation about refresh scope. (tell to add static frontend rule in the same provider as backend
2. Second, refresh should be done for all provider, but may be it not the more efficient.

**Comment by timoreimann** [comment]
Could you please post the output of a `--debug` run while you are expecting the refresh to have happened? Thank you!

**Comment by w3blogfr** [comment]
```
  [frontends.myapp]
  backend = "backendMYAPP"
    #[frontends.myapp.routes.test_1]
    #rule = "Host:api.tropevent.loc"
    [frontends.myapp.routes.test_1]
    rule = "PathPrefixStrip:/myApp"
```

Here is the code with frontend in file provider

```
traefik_1      | time="2017-04-02T11:24:20Z" level=debug msg="Configuration received from provider file: {\"frontends\":{\"myapp\":{\"entryPoints\":[\"https\",\"http\"],\"backend\":\"backendMYAPP\",\"routes\":{\"test_1\":{\"rule\":\"PathPrefixStrip:/myApp\"}},\"priority\":0}}}" 
traefik_1      | time="2017-04-02T11:24:20Z" level=debug msg="Last file config received more than 2s, OK" 
traefik_1      | time="2017-04-02T11:24:20Z" level=debug msg="Creating frontend myapp" 
traefik_1      | time="2017-04-02T11:24:20Z" level=debug msg="Wiring frontend myapp to entryPoint https" 

traefik_1      | time="2017-04-02T11:24:20Z" level=debug msg="Last eureka config received less than 2s, waiting..." 
traefik_1      | time="2017-04-02T11:24:21Z" level=debug msg="Basic auth success..." 
traefik_1      | time="2017-04-02T11:24:22Z" level=debug msg="Waited for eureka config, OK" 
traefik_1      | time="2017-04-02T11:24:22Z" level=debug msg="Creating frontend myapp" 
traefik_1      | time="2017-04-02T11:24:22Z" level=debug msg="Wiring frontend myapp to entryPoint https" 
traefik_1      | time="2017-04-02T11:24:22Z" level=debug msg="Creating route test_1 PathPrefixStrip:/myApp" 
traefik_1      | time="2017-04-02T11:24:22Z" level=debug msg="Creating backend backendMYAPP" 
traefik_1      | time="2017-04-02T11:24:22Z" level=error msg="Undefined backend 'backendMYAPP' for frontend myapp" 
traefik_1      | time="2017-04-02T11:24:22Z" level=error msg="Skipping frontend myapp..."
```

We can see thath frontend my app is not reconfigured at end ("Skipping").


Now, here is example, adding frontend rule in  eureka.t

**Comment by timoreimann** [comment]
You might possibly be affected by #679?

**Comment by timoreimann** [comment]
Could you try again with version 1.2.3+?

**Comment by w3blogfr** [comment]
Hello, 
I tested today with 1.2.3 docker image.

I still have th message "level=error msg="Skipping frontend myapp...""

**Comment by timoreimann** [comment]
It's been a while, sorry for the delay.

@w3blogfr any chance for you to try again with the latest 1.3 release?

**Comment by w3blogfr** [comment]
Sorry for the long delay.

I just tryied today with 1.3.3, and still the same "skipping" message in log

**Comment by trusta** [comment]
I just tryied with 1.3.8 and still the same problem.

Thank you @w3blogfr for the workarround :)

**Comment by ldez** [comment]
It's not possible to use a backend defined by a provider  (Eureka, Docker, ...) in a frontend defined by another provider (File, Docker, ...)
