### ISSUE TITLE
Support for dynamically loaded, pre-, post-, routing-, error-, processing filters

### ISSUE THREAD

**Issue by pparth** [containous/traefik#1378]
Hello, i wanted to ask whether Traefik supports the notion of dynamically loaded, pre-, post-, routing-, error-, processing filters, much like Netflix Zuul does? In general, is there a comparison chart between these 2 open source solutions?

**Comment by pparth** [comment]
Anything about this?

**Comment by timoreimann** [comment]
@pparth my gut feeling says no, but I don't know what the Zuul features are all about exactly. Could you elaborate please?
