### ISSUE TITLE
Is it possible to use the Docker backend but define forwarding-rules in traefik.toml instead of a container label?

### ISSUE THREAD

**Issue by dirkschneemann** [containous/traefik#1385]
### What version of Traefik are you using (`traefik version`)?
1.1.2 (Camembert) via the official Docker image

### What is your environment & configuration (arguments, toml...)?
```
docker run --rm
  -p 80:80 --net=host
  --name traefik
  -v /dev/null:/etc/traefik/traefik.toml
  -v /var/run/docker.sock:/var/run/docker.sock traefik --docker
```

### What did you do?
Started another container while setting some required labels:
```
docker run
  --name nginx
  --label traefik.backend="some-backend"
  --label traefik.frontend.rule="Host: localhost"
  --label traefik.port=80 nginx
```

Then, when doing `curl localhost`, the container logs correctly show me that the `traefik` container took over the request on port 80 and forwarded it to the `nginx` container which was not publicly exposed anywhere.

So far, so good... however, I do not like the fact that I have to configure my reverse-proxy forwarding rules (e.g. forward `Host: localhost` to container `nginx`) within the application itself (e.g. inside of my docker-compose files which also set up the build paths, volumes and other application-specific stuff). Rather, I would like to separate this from the application and configure it on the host machine as part of traefik's configuration instead.

I tried to do it by writing a `traefik.toml` file like this
```toml
[frontends]
  [frontends.frontend1]
  backend = "some-backend"
    [frontends.frontend1.routes.test_1]
    rule = "Host: localhost; Method: GET"
```
and load it at startup:
```
docker run --rm
  -p 80:80
  --net=host
  --name traefik
  -v $PWD/traefik.toml:/etc/traefik/traefik.toml
  -v /var/run/docker.sock:/var/run/docker.sock traefik --docker
```

### What did you expect to see?
When doing `curl localhost`, one should see in the container logs that the request got picked up by the `traefik` container and forwarded to the `nginx` container.

### What did you see instead?
The `traefik` container returns a `HTTP 404 Not found` error because apparently there is no connection between the frontend and the backend anymore.

Is this possible after all? Defining frontend forwarding rules in the `traefik.toml` file like "forward requests by rule XXX to the backend which is called YYY", then create a container and set a label which says "I am the backend called YYY"?

**Comment by traefiker** [comment]
I'll close the issue due to inactivity but feel free to re-open if needed.

**Comment by stepan-romankov** [comment]
@traefiker There is no possibility to apply multiple rules acting as OR for the same container. This might help to solve this. Could you reopen this issue? 

What I see in logs is :
```
Undefined backend 'xxx' for frontend yyy
Skipping frontend yyy..."
```

**Comment by ldez** [comment]
@stepan-romankov you can follow https://github.com/containous/traefik/issues/3026
