### ISSUE TITLE
Docker swarm mode not discovering services without explicitly setting traefik.port property.

### ISSUE THREAD

**Issue by ammaskartik** [containous/traefik#1388]
### What version of Traefik are you using (`traefik version`)?
Latest Docker Traefik version traefik:latest

### What is your environment & configuration (arguments, toml...)?
Docker swarm mode. OSX, 
```shell
docker service create \   
    --name traefik \
    --constraint=node.role==manager \
    --publish 80:80 --publish 8080:8080 \
    --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock \
    --network traefik-net \
    traefik \
    --docker \
    --docker.swarmmode \
    --docker.domain=traefik \
    --docker.watch \
    --web
```

### What did you do?

Added a service:
```shell
docker service create \
  --name whoami0 \
  --label traefik.weight=10 \
  --label traefik.frontend.rule=PathPrefix:/whoami \
  --label traefik.backend.loadbalancer.method=drr \
  --label traefik.backend.loadbalancer.swarm=true \
  --label traefik.enable=true  \
  --network traefik-net \
  -p 8000:8000 jwilder/whoami
```
or even using:
```shell
docker service create \
  --name whoami0 \
  --label traefik.weight=10 \
  --label traefik.frontend.rule=PathPrefix:/whoami \
  --label traefik.backend.loadbalancer.method=drr \
  --label traefik.backend.loadbalancer.swarm=true \
  --label traefik.enable=true \
  --network traefik-net \
  -p :8000 jwilder/whoami
```

### What did you expect to see?

Adding the above service, i would expect Traefik to pick it up, whether or not i explicitly publish a port or let docker pick a random port in the default port range 30000+.

### What did you see instead?

Without explicitly adding the traefik.port label traefik doesnt discover the port, I looked at the docker go code in the provider directory and it looks like Traefik tries to look at the ports property for the container, but this definitely looks like its not working at least for me. Is this by design, and if so how do you get it to work when u let docker publish a random port, or am I missing/not understanding something. Any help is appreciated. 

### If applicable, please paste the log output in debug mode (`--debug` switch)

```shell
time="2017-04-05T13:36:37Z" level=debug msg="Filtering container without port and no traefik.port label traefik.1" 
time="2017-04-05T13:36:37Z" level=debug msg="Configuration received from provider docker: {}" 
time="2017-04-05T13:36:37Z" level=info msg="Skipping same configuration for provider docker" 
time="2017-04-05T13:36:52Z" level=debug msg="Filtering container without port and no traefik.port label traefik.1" 
time="2017-04-05T13:36:52Z" level=debug msg="Configuration received from provider docker: {}" 
time="2017-04-05T13:36:52Z" level=info msg="Skipping same configuration for provider docker" 
time="2017-04-05T13:37:07Z" level=debug msg="Filtering container without port and no traefik.port label traefik.1" 
time="2017-04-05T13:37:07Z" level=debug msg="Configuration received from provider docker: {}" 
time="2017-04-05T13:37:07Z" level=info msg="Skipping same configuration for provider docker" 
time="2017-04-05T13:37:22Z" level=debug msg="Filtering container without port and no traefik.port label traefik.1" 
time="2017-04-05T13:37:22Z" level=debug msg="Configuration received from provider docker: {}" 
time="2017-04-05T13:37:22Z" level=info msg="Skipping same configuration for provider docker" 
```

**Comment by ammaskartik** [comment]
Looking at Docker issues logs, looks like the following issue discusses why this is happening: 
https://github.com/docker/docker/issues/26817

Should look into looking at the service and not the container for the exposed port if needed, as I would like to use random docker gen ports, so this will mean i wont have it b4 hand. I will work around it for now; but would love to see this added; I could help in implementation if needed.

**Comment by pascalandy** [comment]
Simple question. Why do you need those 2 arguments as my setup works without them?

```
  --label traefik.backend.loadbalancer.swarm=true \
  --label traefik.enable=true \
```

**Comment by nmengin** [comment]
@ammaskartik Did you try : 
* Only expose the port 8000 into your whoami container (option `--expose`),
* Add the label `traefik.port=8000` into your whoami container (to specify explicitly the port to contact from Traefik container)
* Add the label `traefik.docker.network=traefik-net` into your whoami container (to specify explicitly the network to use by Traefik container).

More information about the Docker traefik label in the [documentation](https://docs.traefik.io/toml/#docker-backend).

**Comment by traefiker** [comment]
I'll close the issue due to inactivity but feel free to re-open if needed.

**Comment by pascalandy** [comment]
If I may suggest, try this docker stack - https://github.com/pascalandy/docker-stack-this/tree/master/traefik-manager-noacme
