### ISSUE TITLE
Support for Unix Sockets as backend URLs

### ISSUE THREAD

**Issue by gabrielgrant** [containous/traefik#1396]
Traefik doesn't currently seem to support using unix sockets in the `url` field of a backend server. This would be useful for a project I'm currently working on, or any case of a local server accepting connections over a socket

**Comment by dtomcej** [comment]
Unfortunately sockets run at L4, whereas traefik currently only supports L7.

There has been discussion about L4 implementation, but no solid plans.

**Comment by ldez** [comment]
This is a duplicate of #10 - Feel free to subscribe there for updates.

**Comment by gabrielgrant** [comment]
I may be misunderstanding, but it's not clear to me that this is really something that requires full L4 support -- in the same way that treafik can send data from a given frontend to a particular backend port, could it not also send that data to a given unix socket as it's backend?
