### ISSUE TITLE
Support TCP Streams

### ISSUE THREAD

**Issue by RXWatcher1** [containous/traefik#1409]
nginx can proxy tcp steams. I would like to proxy tcp streams with traefik to support things like ssh proxying.

http://nginx.org/en/docs/stream/ngx_stream_proxy_module.html

thank you!
-RX

**Comment by krancour** [comment]
Related-- #1376

**Comment by timoreimann** [comment]
Closing as duplicate. Please post if you think this is incorrect.

Possibly also related: #10.
