### ISSUE TITLE
CNAME flattening

### ISSUE THREAD

**Issue by mikejihbe** [containous/traefik#141]
I'd like Traefik to support CNAME flattening so that when I have a domain with a CNAME that resolves to the proxy the proxy should:

1) Do a normal backend match to see if anything matches the given host name, do the normal thing if matched
2) When 1 fails to find a match, resolve DNS on the host name to check for cname records. 
3) If a CNAME record exists, retry #1
4) 404 as normal

We should probably also keep a capped in-memory cache that respects DNS TTL.

Happy to make a PR, just wanted to establish some consensus on approach.

**Comment by emilevauge** [comment]
Hi @mikejihbe, great idea :)
To make it clear, you want to provide [this feature](https://blog.cloudflare.com/introducing-cname-flattening-rfc-compliant-cnames-at-a-domains-root/)?

**Comment by mikejihbe** [comment]
Basically, yes. I have a PR almost ready, I just need to put some tests together for it. Expect it this week.

**Comment by emilevauge** [comment]
Awesome :)

**Comment by vdemeester** [comment]
:+1:

**Comment by Russell-IO** [comment]
@mikejihbe any progress ?

**Comment by mikejihbe** [comment]
Negative, sorry guys, we've been finalizing a product release for weeks, so
this got bumped down the priority queue. I'll get to it, it just might be a
week or two.

On Sat, Mar 5, 2016 at 5:23 AM, Russell Clare <notifications@github.com>
wrote:

> @mikejihbe <https://github.com/mikejihbe> any progress ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/containous/traefik/issues/141#issuecomment-192641477>.
>



-- 
Mike Ihbe
MustWin - Principal

mike@mustwin.com
mikejihbe@gmail.com
skype: mikeihbe
Cell: 651.283.0815

**Comment by kenden** [comment]
@mikejihbe would it cover this scenario?
https://www.jethrocarr.com/2013/11/02/nginx-reverse-proxies-and-dns-resolution/
(if the AWS ELB changes ip address, traefik would DNS-resolve and try again instead of failing)

**Comment by mikejihbe** [comment]
It's not aimed at targeting that, no. This is mostly useful for handling backends with different names than the HOST header that comes in.

**Comment by gregorybrzeski** [comment]
@mikejihbe any news on this ?

**Comment by mikejihbe** [comment]
Sorry guy, I'm no longer involved with projects utilizing Traefik - I don't think I'll have time to make the contribution in the near future.

**Comment by gamalan** [comment]
I was trying to figuring this, resolving the CNAME is simple. At first, I'm not sure where to put it. I thought the checking process in rules, and it does, but even if it the check process is resulting true, it still returns to 404 page not found. I'm not sure how to proceed.

**Comment by gamalan** [comment]
Updated, the CNAME flattening process is done, but there is SSL issue, sometimes it results to TRAEFIK DEFAULT CERT, other times it SSL handshake error in CF(i'm using CF), sometimes it return SSL protocol error. 

Any idea?

**Comment by gamalan** [comment]
Updated, after some check and change the config, it works. Ttraefik able to generate the request cert using onDemand = true and httpChallenge, dnsChallenge is possible if the requesting host is also managed by the same owner. Currently, I was testing in of our managed domain, managed in namecheap, cloudflare, or local provider.

@emilevauge should I proceed with the PR?

**Comment by emilevauge** [comment]
@gamalan Of course, let's open a PR on this :)
