### ISSUE TITLE
[Question] Update / Add backend through Api call

### ISSUE THREAD

**Issue by Franklin89** [containous/traefik#1410]
I am wondering if it is possible to add or update a giver configuration through the API? Similar to the way if using docker-compose scale adds a new configuration?

All I saw was the provider api put method but I dont assume I can update with that?

**Comment by timoreimann** [comment]
Looking at the code, it does seem like you can send a JSON configuration to the PUT endpoint.

However, there's some restriction saying that you can only modify the "web" provider, and it's checked by making sure that "web" is the target URL resource.

I'm not exactly sure I understand what the web provider is. @emilevauge, could you clarify?

**Comment by timoreimann** [comment]
@emilevauge put together an example here: https://github.com/containous/traefik/issues/362#issuecomment-236573071

See also the remainder of that issue.
