### ISSUE TITLE
Improve documentation on path matchers

### ISSUE THREAD

**Issue by timoreimann** [containous/traefik#1411]
We frequently get the question on Slack what the difference between the various path matchers is. We should likely take this as a signal to improve the docs.

My explanation in a nutshell:

All of them match by path.

- `Path`: match an exact path.
- `PathPrefix`: match a prefix of a path (the suffix can be arbitrary).
- `*Strip` variants: same as the other non-strip ones but remove the Path/PathPrefix after matching (do this if your application expects requests on the prefix-less route).

**Comment by bfqrst** [comment]
You couldn't be more right about this one mate! I am trying for days to match a SimpleHTTPServer served directory. I am either able to match the top level but NOT the underlying subdirs. When I get the subdirs, the toplevel isn't matched. It is highly frustrating. I'm not even getting into websockets et al...

I somehow can't wrap my head around this...

Cheers
Ralph

**Comment by timoreimann** [comment]
@bfqrst do you happen to have a reproducible example we could work with?

**Comment by bfqrst** [comment]
I'd very much like to send you the urls to my lab along with the Traefik config for review, but I'd rather do it privately as it contains some private links and routes. Should there be stuff that we identify would help others, I'm happy to share...

Thanks @timoreimann 
BTW good job on #1469

**Comment by timoreimann** [comment]
@bfqrst thanks for the kudos :)

Feel free to send your URLs/configs to my email address. It's on my Github profile.

**Comment by bfqrst** [comment]
...done!

THX

**Comment by aantono** [comment]
Is it possible to add/share an example of how to use AddPrefix and RemovePath modifiers, preferably in a combination with other matched rules?
