### ISSUE TITLE
ConsulCatalog ignoring prefix option with catalog tags

### ISSUE THREAD

**Issue by mattnathan** [containous/traefik#1415]
### What version of Traefik are you using (`traefik version`)?
```
traefik version
Version:      v1.2.1
Codename:     morbier
Go version:   go1.7.5
Built:        2017-03-27_03:19:40PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml...)?
docker + consul k/v + consulcatalog

### What did you do?
Try to constrain console catalog auto configuration via tags but prefixed with a custom prefix.

 1. Set the `traefik.consulCatalog.prefix` kv value in consul to `foo`. 
 2. Set the `traefik.consulCatalog.contraints.0` kv value to `hello-*`
 3. Register a service with the tag `foo.tags=hello-foo`
 4. Start traefik configured to use the consul k/v as config source

### What did you expect to see?

traefik should register the hello-foo service from above

### What did you see instead?

traefik filters out saying the `hello-*` constraint is responsible

### Notes

If the same test is run (with the same prefix set in the kv) but with the service being registered with the tag `traefik.tags=hello-foo` then the service is recognised by traefik as expected. It seems that only the default prefix is honored by traefik.

I should also note that I am brand new to Traefik so could just be configuring things completely wrong, in which case I apologise.

**Comment by traefiker** [comment]
I'll close the issue due to inactivity but feel free to re-open if needed.
