### ISSUE TITLE
Least connections/bandwidth load balancer?

### ISSUE THREAD

**Issue by JAremko** [containous/traefik#1416]
Why traefik doesn't have Least connections/bandwidth load balancing option?  Is it slow/hard to scale so it's something that will not be in traefik  or you simple haven't done it yet? :smile:

**Comment by timoreimann** [comment]
I'd say it's rather the latter: nobody really needed it yet or has had the motivation to provide a PR. So be the first. :-)

**Comment by ldez** [comment]
I'll close this issue, because I think the question is answered, but feel free to continue the conversation.

**Comment by gonberdeal** [comment]
I think it will be interesting a least connection algorithm for an application like MariaDB Galera Cluster.

More info can be read at:
https://severalnines.com/blog/mysql-docker-swarm-mode-limitations-galera-cluster-production-setups
