### ISSUE TITLE
Unable to build windows binary from Master

### ISSUE THREAD

**Issue by baluubas** [containous/traefik#1422]
### What version of Traefik are you using (`traefik version`)?
Master (12a0026)

### What is your environment & configuration (arguments, toml...)?
Docker image, golang:1.8.1

### What did you do?
Followed the the guide on building on the Contribution page:

```
docker run -it golang:1.8.1 bash
git clone https://github.com/containous/traefik.git src/github.com/containous/traefik
cd src/github.com/containous/traefik/
go get github.com/jteeuwen/go-bindata/...
go get github.com/mitchellh/gox/...
go generate
go build
gox -osarch="windows/amd64" -output="dist/traefik_{{.OS}}-{{.Arch}}"
```

### What did you expect to see?
A windows binary in dist/

### What did you see instead?
```
Number of parallel builds: 1

-->   windows/amd64: github.com/containous/traefik

1 errors occurred:
--> windows/amd64 error: exit status 2
Stderr: # github.com/containous/traefik/vendor/github.com/Microsoft/go-winio
vendor/github.com/Microsoft/go-winio/zsyscall_windows.go:15: undefined: windows.NewLazySystemDLL
vendor/github.com/Microsoft/go-winio/zsyscall_windows.go:16: undefined: windows.NewLazySystemDLL
vendor/github.com/Microsoft/go-winio/zsyscall_windows.go:17: undefined: windows.NewLazySystemDLL
```

**Comment by timoreimann** [comment]
Remotely related to #1341,  though this one is about natively.

**Comment by baluubas** [comment]
First time I ever attempted to build anything Go so I might be off here. Seems microsoft/go-winio and golang.org/x/sys/windows are incompatible.

However, got a build though by copying a new version of golang.org/x/sys/windows into ./vendor (since I don't know better)

**Comment by timoreimann** [comment]
@baluubas to make this properly, you need to bump the version of the affected package in the top-level `glide.yaml` file, run `script/glide.sh update` afterwards, and commit everything.

In the best case, this is all you need. In the worst, you'll have to deal with breaking APIs introduced by other updates. (glide only updates everything.) However, if you wouldn't mind submitting a PR, we could help you / take over from there. Thanks in advance!

**Comment by baluubas** [comment]
I gave it a try but couldn't even figure out how to find the right top level dependency that was causing the problem. Sorry, my go/googling skills are somewhat lacking.

**Comment by timoreimann** [comment]
@baluubas no worries -- dependency management in Go (and in particular with glide) can be quite tricky. I'll take a stab myself.

**Comment by timoreimann** [comment]
It's again one of those cases where you think a single library update should be easy, and before you know it you're deep down in the rabbit hole of transitive dependencies.

But I'm making steady progress, so stay tuned.

**Comment by vdemeester** [comment]
Should be fix in master 👼

**Comment by baluubas** [comment]
Good work, thanks
