### ISSUE TITLE
ACME.StorageFile is deprecated

### ISSUE THREAD

**Issue by ralphtheninja** [containous/traefik#1424]
### What version of Traefik are you using (`traefik version`)?

`1.2.2`

I see the following in the log. What does it mean and can I do to update?

```
time="2017-04-12T14:06:18Z" level=warning msg="ACME.StorageFile is deprecated, use ACME.Storage instead" 
time="2017-04-12T14:06:18Z" level=warning msg="A new release has been found: 1.2.2. Please consider updating." 
```

**Comment by dtomcej** [comment]
@ralphtheninja You have configured your toml using `StorageFile` instead of just `Storage`.

If you are using swarm, you are using `--acme.storagefile` instead of `--acme.storage`
