### ISSUE TITLE
Add signed SHA256 checksums

### ISSUE THREAD

**Issue by kostyrev** [containous/traefik#1426]
### What version of Traefik are you using (`traefik version`)?
doesn't matter

### What is your environment & configuration (arguments, toml...)?
doesn't matter

### What did you do?
Go to Releases

### What did you expect to see?
file with sha256 checksums and signature file

### What did you see instead?
nothing

**Comment by athoune** [comment]
Hashicorp does it right : https://www.hashicorp.com/security/

 * One corporate key findable on Keybase, and available on its public domain, with https.
 * One SHA256SUMS per release, built with the `shasum` tool
 * One signature file, SHA256SUMS.sig, using the official gpg key
 * Great doc with complete copypastable verification process

**Comment by dtomcej** [comment]
Since we have announced Traefik version 2, all releases have been included with SHA256 checksums as part of the release assets.

For this reason, I will close this issue.
