### ISSUE TITLE
too many redirects

### ISSUE THREAD

**Issue by JamesKyburz** [containous/traefik#1432]
### What version of Traefik are you using (`traefik version`)?
v1.2.2-alpine

### What is your environment & configuration (arguments, toml...)?
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  compress = true
    [entryPoints.https.tls]

### What did you do?

enter a https address

### What did you expect to see?

a valid response

### What did you see instead?

a recursive 302 redirect. In chrome this is prevented with too many redirects.

### If applicable, please paste the log output in debug mode (`--debug` switch)

using v1.2.1-alpine with exact same config works.

My toml should only redirect http not https.

**Comment by emilevauge** [comment]
Ducplicate if #1429

**Comment by JamesKyburz** [comment]
Ok thx. Sorry for duplicate, my search was too specific ;)


On Apr 13, 2017 16:32, "Emile Vauge" <notifications@github.com> wrote:

Ducplicate if #1429 <https://github.com/containous/traefik/issues/1429>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/containous/traefik/issues/1432#issuecomment-293912422>,
or mute the thread
