### ISSUE TITLE
Drop privileges after start 

### ISSUE THREAD

**Issue by kostyrev** [containous/traefik#1434]
Will traefik eventually get support to use setuid (to change to a non-root user once it's up and running)? I'd rather not have to run another proxy in front of it to alleviate security concerns if at all possible.

**Comment by dtomcej** [comment]
The reason for running as root is the privileged port access, and filesystem r/w access.

If you require neither of those (for example you just have a SNAT/IPTables rule forwarding privileged traffic to non-privileged ports), you should have no problems running as non-root.

Please be aware that to use certain providers may require elevated privileges accordingly (such as docker, etc).

**Comment by emilevauge** [comment]
Good point, but there seems to be issues with golang on `setuid` https://github.com/golang/go/issues/1435. You can still use capabilities for port binding: `setcap 'cap_net_bind_service=+ep' $(which traefik)`.

**Comment by kostyrev** [comment]
I do need traefik to bind to < 1024 ports but I'm very concern that traefik does not drop privileges afterwards.
there are no issues with FS perms if you set them correctly so it's not a problem.

**Comment by kostyrev** [comment]
@emilevauge thanks! I've forgotten that I used the very same technique with vault. (like [here](https://github.com/kostyrev/ansible-role-vault/blob/master/tasks/configure.yml#L97))

**Comment by ldez** [comment]
I'll close this issue, because I think the question is answered, but feel free to continue the conversation.

**Comment by westurner** [comment]
> `setcap 'cap_net_bind_service=+ep' $(which traefik)`

Is there any reason not to add this to the docker images?
- "You should not run as root" https://github.com/containous/traefik-library-image/issues/38

**Comment by dduportal** [comment]
Hi @westurner , How would you do that with the `scratch` base image?

**Comment by westurner** [comment]
> Hi @westurner , How would you do that with the scratch base image?

It may be easier to modify traefik? 

https://github.com/containous/traefik-library-image/issues/38#issuecomment-472765057 ... looks like launching a subprocess would be the surest way to go with go on linux. https://github.com/golang/go/issues/1435#issuecomment-374434789 :

> [...] There is no particular problem with starting another program using a new UID/GID. We already support that via SysProcAttr.Credential.
>
> The problem is with programs that want to change their effective uid/gid while executing. This is a more or less reasonable thing for a Unix program to do, but it doesn't currently work for Go programs on GNU/Linux. That is what this issue is about.

I have limited experience with go. Would tehse be helpful?

- https://github.com/tmiller/setuidgid/blob/master/main.go
- https://golang.org/src/syscall/exec_linux_test.go
  > `syscall.Syscall(syscall.SYS_CAPSET,`

**Comment by dduportal** [comment]
@westurner there are a lot of reasons why the subprocess/drop caps has not been implemented. As this is an open source project, if you feel it can be done, you are free to propose a contribution :)

**Comment by westurner** [comment]
Are there links to those other discussions? I truly do not have the expertise to implement these fairly simple fixes in go:

- If the user starts as root and the ports requested are less than 1024, drop privileges (by creating another process) after binding
- If the user starts as root, drop the capabilities (SYS_CAPSET) after binding

Both can be accomplished without any container modifications and without userspace utilities in alpine linux.
