### ISSUE TITLE
After modified ip of domain ,how to get new certificate of letsencrypt

### ISSUE THREAD

**Issue by goodforever** [containous/traefik#1438]
After modified ip of domain ,traefik cannot  get a new certificate of letsencrypt

**Comment by Yggdrasil** [comment]
Did you leave enough time between changing the IP and requesting the certificate, for the TTL te expire? After all, the Let's Encrypt servers use DNS to figure out which webserver to contact for validation.

If you did, please post the recent lines from the log (preferably with logLevel set to DEBUG). This should show what Traefik's acme-client is trying to do.

**Comment by ldez** [comment]
I'll close the issue due to inactivity but feel free to re-open if needed.
