### ISSUE TITLE
ACME certs not applying to frontends properly

### ISSUE THREAD

**Issue by obrienmd** [containous/traefik#1439]
### What version of Traefik are you using (`traefik version`)?
1.2.3

### What is your environment & configuration (arguments, toml...)?
Only arg is conf file, conf file is:
https://gist.github.com/obrienmd/5995764139111afcca9f90a85be3b33a

### What did you do?
Started Traefik with ACME configured to use Cloudflare-based DNS challenges (which I have verified with other ACME clients as working properly)

### What did you expect to see?
Successful use of ACME certificates in HTTPS frontend connections

### What did you see instead?
Failure in logs, and TRAEFIK DEFAULT as certificate CN. Strangely, in reviewing the log (bit below this para, full log gist in next section), it looks like the ACME part completes successfully (and /etc/traefik/ssl.json looks to have real cert data), but the certs are never applied to the sites. I'm not sure I'm reading this right, OTOH :)

time="2017-04-14T16:29:02-07:00" level=info msg="Retrieving ACME certificates..."
time="2017-04-14T16:29:02-07:00" level=info msg="Retrieved ACME certificates"

### If applicable, please paste the log output in debug mode (`--debug` switch)
Logs here:
https://gist.github.com/obrienmd/ea32e6dbb5917936d2b1e62a7933d120

**Comment by emilevauge** [comment]
@obrienmd What is the error seen at https://gist.github.com/obrienmd/ea32e6dbb5917936d2b1e62a7933d120#file-traefik-log-L50 ?

**Comment by obrienmd** [comment]
I think this may be resolved, had to do with internal resolver (see lego issue https://github.com/xenolf/lego/issues/379) not forwarding to cloudflare due to specific internal-only zones. If I change /etc/resolv.conf to point to external resolvers only, it works fine. However, If lego implements an env var to allow it to go direct to external resolvers for validation, I'd love to be able to use that in Traefik.
