### ISSUE TITLE
Mesos backend

### ISSUE THREAD

**Issue by tpolekhin** [containous/traefik#144]
Are there any plans for this in near future?
Also, possible to merge `mesos` and `marathon` backends in one.
Tested a little by myself with `megos` client:

```
Version: 0.23.0
Slaves: 9
broker-7 kafka mesos.traefik :  [9092-9092]
broker-6 kafka mesos.traefik :  [9092-9092]
broker-5 kafka mesos.traefik :  [9092-9092]
broker-4 kafka mesos.traefik :  [9092-9092]
broker-3 kafka mesos.traefik :  [9092-9092]
broker-2 kafka mesos.traefik :  [9092-9092]
broker-1 kafka mesos.traefik :  [9092-9092]
elasticsearch-executor elasticsearch mesos.traefik :  [4000-4001]
elasticsearch-executor elasticsearch mesos.traefik :  [4000-4001]
elasticsearch-executor elasticsearch mesos.traefik :  [4000-4001]
elasticsearch-executor elasticsearch mesos.traefik :  [4000-4001]
elasticsearch-executor elasticsearch mesos.traefik :  [4000-4001]
elasticsearch-executor elasticsearch mesos.traefik :  [4000-4001]
elasticsearch-executor elasticsearch mesos.traefik :  [4000-4001]
streamsets marathon mesos.traefik :  [31630-31630]
kafka-manager marathon mesos.traefik :  [31900-31900]
es-proxy marathon mesos.traefik :  [9200-9200, 9300-9300]
kafka-proxy marathon mesos.traefik :  [9098-9098]
es-scheduler marathon mesos.traefik :  [31100-31100]
mantl-api marathon mesos.traefik :  [9669-9669]
kafka-scheduler marathon mesos.traefik :  [31200-31200]
mesos-consul marathon mesos.traefik :  [10000-10000]
```

These are all tasks from Mesos printed like this:
`task.name framework.name "mesos.traefik : " task.Resources.Ports`

Containers from Marathon are at the bottom. What do you think about that?

**Comment by emilevauge** [comment]
This could be nice to merge Marathon and Mesos backend.
But I'm not sure that Mesos API will be as precise nor provide as many features as Marathon (health checks).
I need to look deeper in Mesos API. Be we could create a mesos backend without merging with Marathon.

**Comment by tymofii-polekhin** [comment]
@emilevauge yes, we could, but we may face duplications because is we use both `mesos` and `marathon` backends at the same time, because all the apps running in `marathon` are actually tasks in `mesos`. You can see in the output above i have, for example, `kafka-mesos` framework running:
the scheduler is launched via `marathon`: `kafka-scheduler marathon mesos.traefik :  [31200-31200]`
and brokers are simple mesos tasks, not running on marathon: `broker-1 kafka mesos.traefik :  [9092-9092]`

**Comment by emilevauge** [comment]
Yep you're right, we have to deal with dups.
Did you already create a mesos backend?

**Comment by tymofii-polekhin** [comment]
@emilevauge nope, i just played a little with `megos` client with my cluster. I'm not a developer myself, so it can take time for me to actually implement this to traefik :)
But i surely can try :)

**Comment by timoreimann** [comment]
Closing since we support a Mesos backend by now: https://docs.traefik.io/toml/#mesos-generic-backend

Please file more specific issues if there's anything missing.
