### ISSUE TITLE
Access log file per frontend

### ISSUE THREAD

**Issue by obrienmd** [containous/traefik#1451]
I haven't found anything in docs - but this is one thing I'm really missing from Caddy. Is it possible to specify a log file per frontend?

**Comment by traefiker** [comment]
I'll close the issue due to inactivity but feel free to re-open if needed.

**Comment by pedrodevoto** [comment]
Is there any way to implement this? Are there any plans to include it?

**Comment by timoreimann** [comment]
An alternative might be to use something like logstash or fluentd and filter by frontends (or any other key) in a post-processing step.

**Comment by src386** [comment]
+1
