### ISSUE TITLE
Enable http to https redirection per frontend

### ISSUE THREAD

**Issue by thedylman** [containous/traefik#1456]
### What version of Traefik are you using (`traefik version`)?
1.2.1

### What is your environment & configuration (arguments, toml...)?
Using docker stack deploy, traefik started with command:

```yml
command: [
      "traefik",
        "--docker",
        "--docker.swarmmode",
        "--docker.domain=sw.test.org",
        "--docker.watch",
        "--entryPoints=Name:http Address::80 Redirect.EntryPoint:https",
        "--entryPoints=Name:https Address::443 TLS:/run/secrets/domain.crt,/run/secrets/domain.key",
        "--defaultentrypoints=http,https",
        "--web",
        "--web.address=:8080"
      ]
```

### What did you do?
Is it possible to disable/enable the http to https redirection per service?

e.g:
service 1 (with http to https):
* frontend rule: Host:service1.sw.test.org
* entrypoints: http, https

service 2 (http only, is it possible to disable the http to https redirection here?)
* frontend rule: Host:service2.sw.test.org
* entrypoints: http

**Comment by traefiker** [comment]
I'll close the issue due to inactivity but feel free to re-open if needed.

**Comment by Yajo** [comment]
Please reopen, this is still missing.

**Comment by SantoDE** [comment]
Hey @Yajo,

please have a look at #2133 as this would bring in the functionality :)
