### ISSUE TITLE
Bad v1.2.x changelog

### ISSUE THREAD

**Issue by emilevauge** [containous/traefik#1460]
https://github.com/containous/traefik/pull/784 is missing from `CHANGELOG.md`.
/cc @lewisheadden

**Comment by timoreimann** [comment]
The change log for 1.2.2 and 1.2.3 is missing as well.

**Comment by emilevauge** [comment]
@timoreimann v1.2.3 has not been reported in master ;)

**Comment by timoreimann** [comment]
@emilevauge good point. Let's make sure then the change log amendment won't be forgotten as with 1.2.2. ;-)

**Comment by emilevauge** [comment]
Neither v1.2.2 nor v1.2.3 has been reported yet ^^ https://github.com/containous/traefik/pull/1383
Nothing forgotten :sweat_smile:

**Comment by timoreimann** [comment]
My bad then. :-)
