### ISSUE TITLE
Basic Auth Per Frontend enhancement to support htpasswd files

### ISSUE THREAD

**Issue by RXWatcher1** [containous/traefik#1466]
I really appreciate https://github.com/containous/traefik/pull/1147

You really have no idea. This has been holding me back.

I would also appreciate it if it could support a htpasswd file. I think in its current form that it does not.
Perhaps I'm wrong?

The idea is that I just have to update the password in one location(a shared htpasswd) without recreating the containers and adding more users is just updating the htpasswd file.

Thank you for all of the work. I truely appreciate the effort this entire team puts into it.

**Comment by SkypLabs** [comment]
👍

**Comment by pdemagny** [comment]
:+1:

**Comment by ldez** [comment]
Remember the gentle way to participate:
- add a "reaction" on the first message of the issue.
- add more useful and detailed information on the subject.
- resolve the issue by making a PR.

**Comment by ronaldscott** [comment]
Another reason this would be valuable is that password hashes frequently contain dollar signs `$`, which docker-compose interprets as a string interpolation character. Embedding hashes in docker-compose labels for proper dynamic operation of Traefik therefore becomes an exercise in doubling the dollar signs in one's password hash, which isn't really a maintainable solution.

**Comment by kachkaev** [comment]
@RXWatcher1 Docker docs for 1.7 mention this label: `traefik.frontend.auth.basic.usersfile=/path/.htpasswd` (see [table](https://docs.traefik.io/v1.7/configuration/backends/docker/#on-containers)). A couple of other providers mention `*.auth.basic.usersFile` too.

Is this what you were looking for?

**Comment by ldez** [comment]
Closed by #3559
