### ISSUE TITLE
Traefik as reverse proxy for >100 SSL sites

### ISSUE THREAD

**Issue by rnrbarbosa** [containous/traefik#1477]
### What version of Traefik are you using (`traefik version`)?
latest

### What is your environment & configuration (arguments, toml...)?
TBD

### What did you do?
I currently use consul+registrator+consult_template+nginx+letsencrypt to host almost 200 hundred sites each with its own domain with an SSL certificate. I am trying find an example or sample on how to create a well structured config to point each site to its certificate living on /etc/letsencrypt/live/<domain>.com/... eventuallly each domain with its own toml file

**Comment by kedare** [comment]
Hello, same kind of question here, we are more or less the same situation with around 5000 domains and many reverse proxy instances using autoscaling (Currently the SSL configuration is synchronized using local mongoDB slaves on each reverse proxy (using auto scaling))

**Comment by rnrbarbosa** [comment]
Any hints/pointers?

**Comment by ldez** [comment]
We are preparing the next release, we are a small team and we do not have time now to make a detailed response. Sorry for that.
We invite you to ask the question in our [Traefik community Slack channel](https://traefik.herokuapp.com).

**Comment by gytisgreitai** [comment]
@rnrbarbosa @kedare have you managed to solve this?

**Comment by kedare** [comment]
In our case we keept our existing solution
