### ISSUE TITLE
Rancher backend, external traefik lb instance.

### ISSUE THREAD

**Issue by dniel** [containous/traefik#1491]
### What version of Traefik are you using (`traefik version`)?
1.2.3

### What is your environment & configuration (arguments, toml...)?
I have three hosts running latest Debian 8.
* one for traefik which a manually installed binary of 1.2.3.
  * ip address 10.0.10.100 
* one for rancher managed docker containers, with rancher agent installed and running
  * ip address 10.0.30.111 
  * the rawmind/web-test has been added to the default stack and is running.
  * the rawmind/web-test port has been mapped from 9080 to docker container port 8080.
  * the docker container has[ the managed ip-address has address 10.42.16.247](http://docs.rancher.com/rancher/v1.5/en/rancher-services/networking/#bridgesubnet)
* one for rancher server to orchestrate the rancher agents.
  * ip address 10.0.60.100
  * Rancher version 1.5.3
  * deployed rawmind/web-test with [Managed network](https://docs.rancher.com/rancher/v1.3/en/rancher-services/networking/#managed) in rancher.
  * I have added traefik.enable and traefik.port labels to my service in Rancher.

Traefik on the LB has the rancher backend configured like this:
```
[rancher]
endpoint = "http://10.0.60.100:8080"
```
Which connects to Rancher successfully and list my service, but with wrong backend server ip-address that is not accessible from Traefik.

### What did you do?
Tried to use Rancher backend in Traefik. Was hoping to use an external instance of Traefik running on a LXC container outside Rancher as a reverse proxy. The backend connected successfully to rancher and created frontend and backend for my service.

### What did you expect to see?
When I open the dashboard UI of Traefik I expect to see the backend for rawmind/web-test service as exposed by the publicEndpoint http://10.0.30.111:9080 address.

### What did you see instead?
Traefik backend server internal managed address http://10.42.16.247:8080, which is not accessible from outside the Rancher hosts.

**Comment by matq007** [comment]
Related to #1498

**Comment by ldez** [comment]
Closed by #2101.
