### ISSUE TITLE
IP Whitelists for Frontend (with ConsulCatalog and Consul support)

### ISSUE THREAD

**Issue by tniswong** [containous/traefik#1500]
Feature Request

IP Whitelists ala #1332 with ConsulCatalog and Consul support

**Comment by nmengin** [comment]
@tniswong Even if adding the Ip white list support for Consul and the others frontend is a good idea, by waiting these implementations, a workaround will be to use the development done in the PR #1702.

It allows to specify IP white list for an endpoint.

**Comment by ldez** [comment]
Closes by #2646
