### ISSUE TITLE
Bug in Traefik when opening additional ports using Docker Swarm Mode

### ISSUE THREAD

**Issue by ascora** [containous/traefik#1503]
### Do you want to request a *feature* or report a *bug*?
BUG

### What did you do?
We launched traefik and all containers using the Docker Swarm Mode. Traefik is launched like this:
```shell
	docker service create \
	    --network web \
	    -p 80:80 -p 443:443 \
	    --mount type=bind,src=/ds/rtsync/traefik/etc,dst=/etc/traefik \
	    --mount type=bind,src=/ds/rtsync/traefik/ssl/,dst=/ssl \
	    --mount type=bind,src=/var/run/docker.sock,dst=/var/run/docker.sock,ro=1 \
	    --limit-memory 2GB \
	    --name traefik \
	    traefik:v1.2.3
```

Adding new containers in the `--network web`  works fine and they are added to traefik and are reachable. e.g.

```shell
	docker service create \
	    --network web \
	    --name test \
	    --label traefik.port=80 \
	    --label traefik.protocol=http \
	    --label traefik.frontend.rule=Host:my.domain.com \
	    --label traefik.enable=true \
	    nginx
```

However, if we add a port then the container is not reachable anymore:

```shell
	docker service create \
	    --network web \
	    **-p 123:456 \**
	    --name test \
	    --label traefik.port=80 \
	    --label traefik.protocol=http \
	    --label traefik.frontend.rule=Host:my.domain.com \
	    --label traefik.enable=true \
	    nginx
```

I saw that traefik lists the container with the following IP: 10.255.0.x

However, when I do a docker exec into another container from the web network and then do a   dig test  then I get 10.0.0.x instead of 10.255.0.x

I looked into this using 
`docker service inspect test`

```json
 "VirtualIPs": [
                {
                    "NetworkID": "59c0bp2aqdq2wnu8nsm4a2quc",
                    "Addr": "10.255.0.4/16"
                },
                {
                    "NetworkID": "6djjytf6pm40b00uf8811zpe3",
                    "Addr": "10.0.0.5/24"
                }
```

so it looks like the container has both IPs. I then used `docker ps` to sing the ID and did a 
`docker inspect 06jqmv9ulojr`
This shows that the 10.0.0.x IP belongs to the "web" network and the 10.255.0.x belongs to the docker ingress network.

So it looks like traefik is using the wrong IP. It should use the web one but uses the ingress one instead.

### What did you expect to see?
A correct routing to 10.0.0.x

### What did you see instead?
A routing to 10.255.0.x

### Output of `traefik version`: (_What version of Traefik are you using?_)
v1.2.3

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
Ubuntu 16.04, Docker  17.04.0-ce

**Comment by sunnysideocean** [comment]
I can confirm this problem

**Comment by ascora** [comment]
As a short follow-up: The result of the wrong internal IP above is that Traefik cannot reach the container and thus, the container is unavaibale to the outside world.

**Comment by nmengin** [comment]
@ascora Did you try to add a label into your nginx container in the way to specify the network Traefik has to use? You can do it with the label `traefik.docker.network`.

More information about this label into the [documentation](https://docs.traefik.io/toml/#docker-backend).

**Comment by ascora** [comment]
Indeed, that solved it. Sorry: Obviously this has been my fault
