### ISSUE TITLE
Strange things with docker-ce 17.04

### ISSUE THREAD

**Issue by opavlov24** [containous/traefik#1513]
### Do you want to request a *feature* or report a *bug*?
Bug

### What did you do?
I've upgraded my docker swarm mode cluster to 17.04-ce

### What did you expect to see?
Working traefik :)

### What did you see instead?
I looked at my traefik logs and saw this error:

```
time="2017-04-29T20:39:10Z" level=debug msg="Docker connection established with docker 17.04.0-ce (API 1.28)" 
time="2017-04-29T20:39:10Z" level=error msg="Failed to list services for docker swarm mode, error Error response from daemon: rpc error: code = 2 desc = proto: wrong wireType = 2 for field DesiredStates" 
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

1.23 and the same error with ver. 1.21

**Comment by ascora** [comment]
I can confirm this with 17.05.0-ce

**Comment by ascora** [comment]
@opavlov24 Did you find any workaround for this except for downgrading docker?

**Comment by ascora** [comment]
@vdemeester have you been able to reproduce the problem or do you have an idea what we could do as a temporary workaround?

**Comment by ascora** [comment]
As a follow-Up info: We got 2 different Docker versions running in our cluster: 17.03.0-ce and 17.05.0-ce. The problem only happens on the node with 17.05.0-ce. Maybe the mix of docker versions is contributing to this problem? However, I'm a bit hesitating to update all nodes to 17.05.0-ce as I fear that this would mean that we couldn't run Traefik at all.

I'm thankful for any ideas/feedback

**Comment by ascora** [comment]
I setup a fresh 2 node cluster and created a swarm and I can confirm that this problem appears as soon as 2 docker versions are mixed in the swarm: Traefik works fine with 17.03.0-ce and 17.05.0-ce.  However, as soon as one node in a 17.03 cluster is updated to 17.05, the problem appears in case that traefik is running on the 17.05 node.

As soon as the last node is updated to 17.05, the problem disappears

**Comment by vdemeester** [comment]
@ascora I asked internaly on #swarmkit… because this really should not happen between `17.03` and `17.06` (stables)

**Comment by aaronlehmann** [comment]
There is a real compatibilty problem here. I've opened https://github.com/docker/swarmkit/pull/2186.

**Comment by timoreimann** [comment]
As the root cause seems to be a Docker issue, shall we close this (Traefik) issue?

**Comment by ascora** [comment]
Yes, I think we can close it here. 
@vdemeester A big **thank you** for looking into this. :-)

**Comment by vdemeester** [comment]
@ascora :wink: thank you for the report !
