### ISSUE TITLE
UDP Support

### ISSUE THREAD

**Issue by drasko** [containous/traefik#1520]
Related to https://github.com/containous/traefik/issues/10, I would like to see UDP support with DTLS also.

To elaborate, in the IoT context we would like to proxy both MQTT (which is TCP) and CoAP/LWM2M (which is UDP) requsts to the clustered set of nodes in the backend. So UDP proxy is also needed.

**Comment by Wirone** [comment]
Another use case for proxying UDP communication to specified container is sending GELF packets to Logstash. Right now I'm binding 12201 port and from client's side I must use machine's hostname which is different than I would like to use (I prefer to set some abstraction by `Host` label so migrating ELK to different host wouldn't require changing configuration within clients).

**Comment by lakano** [comment]
Could be useful for WebRTC / TURN application too. Since TCP is now supported in the 2.0 version, may be we could have a little chance to see UDP support in soon ?

**Comment by ldez** [comment]
[The Road to the Final Version](https://blog.containo.us/back-to-traefik-2-0-2f9aa17be305#3d1b)

**Comment by rijnhard** [comment]
> [The Road to the Final Version](https://blog.containo.us/back-to-traefik-2-0-2f9aa17be305#3d1b)

If I had to make an analogy about how much this teased me, the comment woul have to be removed.

**Comment by juliens** [comment]
Close in favor #5048
