### ISSUE TITLE
Minikube example: traefik-ui.local → traefik-ui.minikube?

### ISSUE THREAD

**Issue by kachkaev** [containous/traefik#1521]
Hey guys! A newbie speaking here!

I installed minikube on my macOS today and started going through the [Kubernetes Ingress Controller](https://docs.traefik.io/user-guide/kubernetes/#kubernetes-ingress-controller) tutorial. After getting into a pretty unexpected os-related trap, I decided to share the experience here as I think that the trap may be avoided by a slight refactoring of the traefik examples.

Launching traefik inside minikube went well until I needed to configure DNS. The tutorial suggested to hardcode a few domains in `/etc/hosts` like this:
```
echo "$(minikube ip) traefik-ui.local" | sudo tee -a /etc/hosts
echo "$(minikube ip) stilton.local cheddar.local wensleydale.local" | sudo tee -a /etc/hosts
echo "$(minikube ip) cheeses.local" | sudo tee -a /etc/hosts
```

I've been using [dnsmasq](http://www.thekelleys.org.uk/dnsmasq/doc.html) for controlling local DNS zones for years, so intuitively decided to bind the entire `*.local` to my minikube IP with it, just like I did this earlier for `*.dev` or `*.docker` zones. The idea was to keep `/etc/hosts` clean and to be also ready for any further experiments with Traefik inside my shiny-new minikube.

After vainly trying to figure out why the trick with `*.local` DNS zone did not work just as it did for `*.dev`, `*.test` and  even`*.local2`, I discovered [one very odd peculiarity of macOS](https://support.apple.com/en-gb/HT201275), which was in treating `*.local` in a special way. The maddest thing is that `*.*.local`, unlike `*.local` was routed as expected!

__Here is my conclusion and suggestion:__

I'm wondering if it would be possible to switch from `*.local` to, let's say, `.minikube` in your tutorial and just keep everything else as is. The instructions will still contain the same sequence of steps, but those macOS users who think that they are ‘smart enough’ to control DNS dynamically instead of hacking `/etc/hosts` wont be wasting half a day like me 😃 If the yamls in [`examples/k8s`](https://github.com/containous/traefik/tree/master/examples/k8s) are changed too, it'll be possible to just `kubectl apply -f https://raw.githubusercontent.com/containous/traefik/master/examples/k8s/ui.yaml` etc. directly without downloading and tweaking the files. Given your scale, this can save days of someone's lives 👍 

What do you guys think? What caveats would this minor DNS zone switch hold?

**Comment by timoreimann** [comment]
hey @kachkaev, thanks a lot for sharing the problem you've found.

I can't really comment on whether we should replace the current guide as you suggest or not. My gut feeling is that we should amend them by your findings. FWIW, I personally never bothered to install minikube for the sake of testing out Traefik as I am lucky enough to have a real cluster at hand that I can use. So it wouldn't make a difference to me (and I suppose other people in a similar role), but of course other folks' mileage may vary.

@dtomcej @errm any thoughts?

**Comment by kachkaev** [comment]
Thanks for your comment @timoreimann!

Here is the reason why I ended up with traefik on minikube today: I'm new to both and I'm looking into switching to this bundle from my current `single VM` / `docker` / [`nginx-proxy`](https://github.com/jwilder/nginx-proxy) setup. My exploration happens in free time, so before I go buying new VMs, I'd like to play with the API of both kubernetes and traefik and check out how traefik dashboard behaves when I deploy something. Local setup feels like the best option given the simplicity of minikube and the fact that no extra hardware implies no extra costs :–)

Of course I don't have a wide picture of what other entry paths people take in the community, but given the prevalence of macs among devs, I assume that my case is not be the least common one :–)

**Comment by timoreimann** [comment]
@kachkaev I think minikube is a totally valid and good way to test out Traefik; it just happens to be the case that _I_ did not use it. I'm completely okay with including your approach in the docs though -- it's just a matter of whether we swap out `*.local` by `.minikube` or let both options stand next to each other.

I'm happy to let @dtomcej and @errm (the other two members on the maintainer team familiar with Kubernetes) make the call / provide feedback.

**Comment by errm** [comment]
Yeah there is no real significance in the fact I chose `.local` when writing the tutorial ... there is nothing wrong with changing to `.minikube`... PR coming up

**Comment by pathcl** [comment]
Well the k8s user-guide stills points to 'traefik-ui.local' instead of 'traefik-ui.minikube' referred on .yaml

**Comment by ldez** [comment]
@pathcl The documentation's site (https://docs.traefik.io/) points to the latest stable version (1.3.3).

This issue has been fixed in 1.4 documentation (https://github.com/containous/traefik/pull/1551).

Look at https://github.com/containous/traefik/tree/master/docs.

**Comment by pathcl** [comment]
@ldez I followed the current guide for k8s: https://github.com/containous/traefik/blob/master/docs/user-guide/kubernetes.md

However when I get to 'path-based-routing' which is here https://github.com/containous/traefik/blob/master/docs/user-guide/kubernetes.md#path-based-routing

I only get '404' for 'bg.png'

**Comment by DJviolin** [comment]
I try to install Traefik Web UI, but under Vagrant, without Minikube. On the host machine, I tried to reach UI both under `localhost:8081` (guest 8080 port exposed to host in Vagrantfile) and `https://localhost:6443/api/v1/namespaces/kube-system/services/https:traefik-web-ui:/proxy/` without luck. Can you recommend a working setting?
