### ISSUE TITLE
Traefik serves two certificates, one self-signed and one ACME, confusing some software.

### ISSUE THREAD

**Issue by Yggdrasil** [containous/traefik#1528]
### What version of Traefik are you using?
```
Version:      v1.2.3
Codename:     morbier
Go version:   go1.7.5
Built:        2017-04-13_07:21:10PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml...)?
Basic file-based config with http and https entrypoints. No explicit certs configured. All certs are retrieved via Acme.

```toml
[entryPoints.http]
address = ":80"
[entryPoints.https]
address = ":443"
[entryPoints.https.tls]
[acme]
onDemand = true
```

```json
{
 "GraceTimeOut": 10,
 "Debug": false,
 "CheckNewVersion": true,
 "AccessLogsFile": "/var/log/traefik/access.log",
 "TraefikLogsFile": "/var/log/traefik/daemon.log",
 "LogLevel": "INFO",
 "EntryPoints": {
  "http": {
   "Network": "",
   "Address": ":80",
   "TLS": null,
   "Redirect": null,
   "Auth": null,
   "Compress": false
  },
  "https": {
   "Network": "",
   "Address": ":443",
   "TLS": {
    "MinVersion": "",
    "CipherSuites": null,
    "Certificates": null,
    "ClientCAFiles": null
   },
   "Redirect": null,
   "Auth": null,
   "Compress": false
  }
 },
 "Cluster": null,
 "Constraints": [],
 "ACME": {
  "Email": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "Domains": null,
  "Storage": "/var/lib/traefik/acme.json",
  "StorageFile": "",
  "OnDemand": true,
  "OnHostRule": false,
  "CAServer": "",
  "EntryPoint": "https",
  "DNSProvider": "",
  "DelayDontCheckDNS": 0,
  "ACMELogging": false,
  "TLSConfig": null
 },
 "DefaultEntryPoints": [
  "http",
  "https"
 ],
 "ProvidersThrottleDuration": 2000000000,
 "MaxIdleConnsPerHost": 200,
 "InsecureSkipVerify": false,
 "Retry": null,
 "Docker": null,
 "File": {
  "Watch": false,
  "Filename": "",
  "Constraints": null
 },
 "Web": {
  "Address": ":8081",
  "CertFile": "",
  "KeyFile": "",
  "ReadOnly": true,
  "Statistics": {
   "RecentErrors": 10
  },
  "Metrics": null,
  "Auth": null
 },
 "Marathon": null,
 "Consul": null,
 "ConsulCatalog": null,
 "Etcd": null,
 "Zookeeper": null,
 "Boltdb": null,
 "Kubernetes": null,
 "Mesos": null,
 "Eureka": null,
 "ECS": null,
 "Rancher": null,
 "ConfigFile": "/etc/traefik/traefik.toml"
}
```

### What did you do?
Tried to use the [httpie](https://httpie.org/) cli http client to perform REST request against an app that's behind Traefik, which failed.

I also tried to use `openssl s_client`, which fails as well.

`curl` appears to work fine.

### What did you expect to see?
Expected to get a signed https connection, with a Let's Encrypt cert, instead of a self-signed cert.

### What did you see instead?
```shell
$ http https://www.insiders.nl/
http: error: SSLError: [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
```

```shell
$ openssl s_client -connect www.insiders.nl:443
CONNECTED(00000003)
depth=0 CN = TRAEFIK DEFAULT CERT
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN = TRAEFIK DEFAULT CERT
verify error:num=21:unable to verify the first certificate
verify return:1
---
Certificate chain
 0 s:/CN=TRAEFIK DEFAULT CERT
   i:/CN=TRAEFIK DEFAULT CERT
---
```

When checking the SSL config via SSLLabs I see Traefik responds with _two_ cert chains: The Let's Encrypt cert and the self-signed "TRAEFIK DEFAULT CERT".

See https://www.ssllabs.com/ssltest/analyze.html?d=www.insiders.nl&s=2a05%3ad018%3aade%3a1ff%3ac28e%3a546f%3a4780%3a5e2&latest

I'm assuming that both httpie and openssl s_client try a non-SNI connection first, then receive the self-signed cert, which fails to verify. Curl (and browsers) appear to use SNI first.

**Comment by codebje** [comment]
I have this issue.  It causes Chrome to also report an invalid certificate error on some connects, though it appears to cache something about the connection such that it only occurs a few times per session.

My environment is Kubernetes (1.5.3, 1.6.2), Traefik (1.1.6, 1.2.3), client CA certs off and on respectively, and multiple domains enabled.  I observe, from the command line using OpenSSL, that I will randomly be given either the default certificate or the correct certificate, with no discernible pattern, always supplying SNI information.

Debug logging indicates that when the incorrect certificate is supplied, the code path being followed is _not_ logging anything: no ACME certificate discovered, nothing.  This can mean that either `acme/acme.go:getCertificate` is not invoked by the Go TLS layer, or that same method is matching a name and certificate in `TLSConfig.NameToCertificate`.  Unfortunately, there's no logging for the latter case, so I can't distinguish these.

A local build and execute inside Docker with the same config, the same Kubernetes server (but with external access to the API server), and same `acme.json` fails to fail: I will try it inside minikube and see if the Kubernetes environment itself is causing problems.

**Comment by codebje** [comment]
Further investigation shows that in my case, there is no bug in Traefik: there is a massive glaring flaw in Google Cloud's networking design, instead.  You cannot remap ports.  If you receive traffic externally on port 443, then by gum it's going to port 443 internally, no ifs, buts, or maybes.  You also cannot direct traffic to one of the Google Container Engine's service IP addresses, only to the host node IP addresses.

The end result is simply creating two external IP addresses and attempting to direct traffic from them to your Traefik instances will either have a fragile configuration in which a pod restart and rehoming on a new node breaks your service, or a broken configuration in which connections are randomly distributed to one of your instances, not to the correct one.

This would equally apply to anyone running Traefik in Kubernetes where some other service in the cluster is offering a port-443 or port-80 service.  It just won't work.  It can't work.  The networking model in GCE for Kubernetes is flat out broken.

In my specific case, I could work around it if Traefik supported client certificates only for some back-ends, at least until some other service tries to expose port 443.  Otherwise, in GCE, one is probably better off not using Traefik at all.

**Comment by jkaberg** [comment]
I'm actully seeing the very same as OP with similar tests and scenario.

**Comment by nmengin** [comment]
@Yggdrasil @jkaberg I'm currently working on this problem.
As @jkaberg , can you give me more information about your configuration (toml file, compose file?).

Thanks in advance.

**Comment by nmengin** [comment]
I recently updated acme tests as you can see in PR #1772 and I had the same kind of issue.

After many searches, I found the reason. For my use case, it's question of timing.

Indeed, if Traefik receives the first HTTPS request **before** to generate the LE certificate, it will returns a default certificate generated when it starts (named xxxx.xxxx.traefik.default).
Then, the HTTPS server (from the Go Standard library), validates the connection's handshake. This validation avoids all the others HTTPS requests, based on the same connection, to call the method `getCertificate` and, in my case, to get the LE certificate.

In my tests, I just had to close the request between two calls in the way to reset the connection and force the handshake... I found the explanation [here](https://stackoverflow.com/questions/17714494/golang-http-request-results-in-eof-errors-when-making-multiple-requests-successi/23963271#23963271)

For me, it's not a bug into Traefik.

@Yggdrasil , @jkaberg , @codebje Do you think your problem get the same reason as mine?

**Comment by Yggdrasil** [comment]
@nmengin I don't think it's the same reason. For me these had been happening on sites that have had LE certs for weeks/months. I think your issue may be a different one.

At this point, I don't think my issue was an actual Traefik bug but just a difference between clients that do or don't support SNI.

For example: `openssl s_client -connect www.insiders.nl:443` (non-SNI) returns the Traefik cert and an invalid-cert-error. Adding the servername, like `openssl s_client -connect www.insiders.nl:443 -servername www.insiders.nl` enables SNI in the client and gets the right cert, which then validates correctly. So apparently, openssl doesn't enable SNI support unless you tell it to.

As for `httpie`, it appears to be a version thing. httpie 0.8.0 fails, while httpie 0.9.9 works fine. I'm guessing they added SNI support somewhere between these versions, though I couldn't find it in their [changelog](https://github.com/jakubroztocil/httpie/blob/master/CHANGELOG.rst).

SSLlabs is explicit in their results, in that they get try the requests both with and without SNI and show both chains.

I'm not sure what Traefik's response should be for non-SNI requests, I even looked through the RFCs, but the current behaviour seems right to me.

I appreciate your work and comments @nmengin. I suggest we close this particular issue, since both mine and other commentors appear to have been client-side problems.
