### ISSUE TITLE
Forward all requests to backend unconditionally

### ISSUE THREAD

**Issue by zyzop** [containous/traefik#1562]
### Do you want to request a *feature* or report a *bug*?
Feature, possibly.

### What did you do?
I need traefik to forward all http(s) requests to my backend, no matter what is requested. I use EC2 cluster for backend.
Thing is that there will be a lot of domains pointing to my traefik server, and they will be added periodically, so I want everything to be proxied to backend with a minimal configuration(or even without). 
Problem is I cannot figure out how to configure that. I'm not sure if that's not supported or I'm just doing it wrong.
Please clarify if that can be done.

### Output of `traefik version`: (_What version of Traefik are you using?_)
latest stable from docker hub

**Comment by timoreimann** [comment]
This should be possible by specifying a fitting Host/Path matcher and an adequate priority.

**Comment by zyzop** [comment]
@timoreimann 
I tried setting a label like "traefik.frontend.rule=Host:*" on my ECS cluster, didn't help. Am I doing it wrong?

**Comment by timoreimann** [comment]
Try using the `HostRegexp` matcher for the rule and pass a regular expression [as documented](https://docs.traefik.io/basics/#frontends).

**Comment by dtomcej** [comment]
@zyzop You can also try `traefik.frontend.rule=Path: /`

That will match all requests

**Comment by zyzop** [comment]
@dtomcej Hello, sorry that doesn't work, I'm getting "404 page not found" from traefik.

**Comment by dtomcej** [comment]
@zyzop can you provide the debug logs from traefik when you:

A. Start traefik (so we can see what configuration was parsed)
B. Attempt to access your page (so we can see what proxy request traefik is attempting).

Thanks!

**Comment by zyzop** [comment]
@dtomcej I successfully accomplished this using PathPrefix: / instead of Path: /
