### ISSUE TITLE
Consider exposing services explicit, not implicit

### ISSUE THREAD

**Issue by hamann** [containous/traefik#1587]
It's nice to see that traefik is able to add routes for every consul services it finds, but IMHO that's completly out of touch with reality. The second question after first try is probably "How can I prevent traefik from exposing my internal http apis/services to the outside?".  Guess it makes more sense to say/or document "Hey, if you want a service to be exposed, add a tag! Here is how.."

**Comment by traefiker** [comment]
I'll close the issue due to inactivity but feel free to re-open if needed.
