### ISSUE TITLE
Unable to establish WSS connection when using Kubernetes

### ISSUE THREAD

**Issue by Regner** [containous/traefik#1591]
Currently unable to establish a WSS connection from a web application running seperatly to a service I have in Kubernetes and exposed via Traefik. My Kube cluster is a GKE cluster, fairly standard stuff.

I am currently running Traefik v1.3.0-rc1 / raclette.

Of note this did work on another test cluster that was running a very outdated version of Traefik 1.1.

My backend service is exposed in Kubernetes on port 8080, which means the Kubernetes provider adds it as a Traefik backend with HTTP.

When deployed I can make normal HTTP requests such as GET and POST.

However when I attempt to establish a WSS connection I get the following error in the Traefik logs.

```
Unable to hijack the connection: *middlewares.responseRecorder
```

A quick bit of Googling lead me to this issue: https://github.com/containous/traefik/issues/467

@emilevauge seems to suggest that the backend needs to be accessed as HTTPS instead of HTTP.

To accomplish that with Kube I set the service port to 443 and the Kubernetes provider started using HTTPS instead. I verified the backend was set to that through the web UI for Traefik.

With Traefik using HTTPS however I get this error:

```
Error forwarding to https://10.0.1.74:8080, err: tls: oversized record received with length 20527
```

A quick bit more Googling on that lead me to understand that error essentially just means a connection was attempted on a TLS socket that didn't support TLS. That makes sense.

I was hopeful that maybe setting InsecureSkipVerify to true would help avoid this however it doesn't seem to have worked. I set InsecureSkipVerify to true in my config, and verified with the output of the global config when Traefik starts, but I still get the same error.

It seems I either need a way to tell Traefik to fall back and not use TLS on a TLS port, have Traefik support making a standard WS connection to the backend, or I just need to ship some self signed certs with my backend.

**Comment by ldez** [comment]
Closed by #1598
