### ISSUE TITLE
basic auth on kubernetes - unexpected watch event object type

### ISSUE THREAD

**Issue by Eriner** [containous/traefik#1596]
### Issue
When using basic auth on kubernetes (introduced by #1488), traefik produces some noisy logs due to glog ([upstream kubernetes ref](https://github.com/kubernetes/kubernetes/issues/17162)), in particular the following log:
```
ERROR: logging before flag.Parse: E0512 22:57:36.808273       1 reflector.go:359] github.com/containous/traefik/vendor/k8s.io/client-go/tools/cache/reflector.go:94: expected type *v1.Endpoints, but watch event object had type *v1.Secret
```
At least in my case, it produces exactly 208 of these log entries per hour.

### Mitigation

This bug does **not** impact the functionality of basic auth, only log production.
 
Disabling basic auth and redeploying the container ceases the production of this log entry.

### Traefik version

Docker contianer: `traefik:v1.3.0-rc1-alpine`

### Configuration and Environment

There's nothing special about this environment, and the authentication is implemented per the PR referenced above, functions as expected, and fits the constraints mentioned in that PR.

### Debugging

If it's helpful, I can redeploy the container with debugging.

**Comment by ajtrichards** [comment]
We are also getting this same message filling up our log files. Using the same container image: `traefik:v1.3.0-rc1-alpine`

**Comment by kekoav** [comment]
@timoreimann  I have submitted a fix for this issue ☝️ . This looks to be a minor typo, and resolves the error messages when running in Kubernetes.

This error happens regardless of if basic auth is in use. I am not using basic auth and it still happens when the watchers are looking for changes.

@Eriner @ajtrichards

**Comment by Eriner** [comment]
@kekoav I haven't tested the PR, but I have extensive logs from A/B tests that show the bug only triggering when basic auth is enabled, FWIW. It's very possible that alternate configurations (not just the basic auth feature, perhaps something else about your environment triggers it as well) can/will trigger the bug, but at least in my case, simply disabling kubernetes-backed basic auth prevents this bug from being triggered.

Cheers for the potential fix :+1:

**Comment by kekoav** [comment]
@Eriner That is interesting, I never did anything to enable it, even with no Ingress objects this just started appearing in my logs after updating to 1.3.0. I was unaware of basic auth support until my logs started filling up and I found this issue 🤷‍♂️ .

**Comment by ldez** [comment]
I'll close this issue, because I think the question is answered, but feel free to continue the conversation.
