### ISSUE TITLE
Flaky integration tests

### ISSUE THREAD

**Issue by atbore-phx** [containous/traefik#1600]
We have switched our tests to Semaphore CI (https://github.com/containous/traefik/issues/1266) and we got a execution time boost (~2x).
We also restored the ci_retry function (https://github.com/containous/traefik/pull/1573) because the integration tests are still flaking.

I'm starting to deploy a simple scenario based on tests series to obtain a closer perimeter and to understand which tests have the higher "flaky probability".

Reiterating the same test on semaphore 100 times (deactivating the ci_retry function), 
i get those results: [link](https://docs.google.com/spreadsheets/d/12W7UmE8sAnqk_hCWnZ8HD-gKBuCLOqUJ0I8AQqNExs4/edit?usp=sharing)

**Comment by atbore-phx** [comment]
Series : S1
KO: 14%
higher errors:
acme_test	5
eureka_test	4

**Comment by atbore-phx** [comment]
Series: S2 (acme and eureka tests are executed first):
KO: 15%
higher errors:
acme_test 7
eureka_test 4

Acme and eureka tests are still the tests with the higher flaky probability.
The test's order doesn't affect the final results so we "could" exclude an hw resource exhaustion issue.

**Comment by atbore-phx** [comment]
Series: S3 (increasing acme and eureka timeouts).
KO: 8%
higher errors:
acme_test 2
eureka_test 3

An higher timeout on the most flaky tests seems reduce the error probability (especially for the acme test )

**Comment by atbore-phx** [comment]
This PR https://github.com/containous/traefik/pull/1599 has the main goal to deflake the integration tests.

**Comment by ldez** [comment]
Closed by #1599
