### ISSUE TITLE
Is it possible to use ssh protocol with traefik ?

### ISSUE THREAD

**Issue by tbouvet** [containous/traefik#1611]
### Do you want to request a *feature* or report a *bug*?
Question

### What did you do?
I have a docker container with a ssh daemon inside. I just expose the port 22 and I want use an url to connect to my ssh container.

So I just want to do:
```
ssh mylogin@mycontainer.domain.com
```` 

### What did you expect to see?
ssh connection ok

### What did you see instead?
Connection closed by remote host

### Output of `traefik version`: (_What version of Traefik are you using?_)
1.1.2

**Comment by emilevauge** [comment]
@tbouvet as mentioned in the README, Traefik is an http (only) reverse proxy, then the answer is no. We want to add TCP support in the future, you can follow this issue https://github.com/containous/traefik/issues/10.
