### ISSUE TITLE
Cannot use Host rule when port != 80/443

### ISSUE THREAD

**Issue by Yajo** [containous/traefik#1617]
### Do you want to request a *feature* or report a *bug*?

bug

### What did you do?

I exposed a service on port 90 and wanted to set `Host:example.com` as the frontend rule.

I tried with labels:

- `frontend.rule=Host:example.com`
- `frontend.rule=Host:example.com:90`
- `frontend.rule=Host:example.com;Host:example.com:90`

None of them redirects to the right service. Going to `http://example.com:90/someprefix/here` gets me to Traefik's 404 error page.

This label, however, works:

- `frontend.rule=PathPrefix:/someprefix/`

Going to `http://example.com:90/someprefix/here` gets me to the service.

### What did you expect to see?

A way to discriminate by host when using a custom port.

### What did you see instead?

Although it should theoretically work, it does not.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.2.3
Codename:     morbier
Go version:   go1.7.5
Built:        2017-04-13_07:21:10PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Arguments:

        - --ACME.ACMELogging
        - --ACME.Email=***
        - --ACME.EntryPoint=https
        - --ACME.OnHostRule
        - --ACME.Storage=/etc/traefik/acme/acme.json
        - --DefaultEntryPoints=http,https
        - --EntryPoints=Name:http Address::80 Redirect.EntryPoint:https Compress:on
        - --EntryPoints=Name:https Address::443 TLS Compress:on
        - --EntryPoints=Name:special Address::90 Compress:on
        - --LogLevel=DEBUG
        - --Docker
        - --Docker.EndPoint=http://dockersocket:2375
        - --Docker.ExposedByDefault=false
        - --Docker.Watch

### If applicable, please paste the log output in debug mode (`--debug` switch)

Wiring seems right:

```
DEBU[2017-05-17T10:26:23Z] Creating server server-example_proxy_1 at http://172.18.0.5:80 with weight 0 
DEBU[2017-05-17T10:26:23Z] Creating frontend frontend-Host-example-com-90-Host-example-com 
DEBU[2017-05-17T10:26:23Z] Wiring frontend frontend-Host-example-com-90-Host-example-com to entryPoint redsys 
DEBU[2017-05-17T10:26:23Z] Creating route route-frontend-Host-example-com-90-Host-example-com Host:example.com:90;Host:example.com 
DEBU[2017-05-17T10:26:23Z] Creating backend backend-example-proxy-redsys-1 
DEBU[2017-05-17T10:26:23Z] Creating load-balancer wrr                   
DEBU[2017-05-17T10:26:23Z] Creating server server-example_proxy_redsys_1 at http://172.18.0.2:80 with weight 0 
```

**Comment by emilevauge** [comment]
@Yajo Sorry, but I don't understand your needs ;)
Could you explain in details what you want to do?

**Comment by aantono** [comment]
I might be mistaken, but it sounds like you want to map your entrypoint named - `special`, which is listening on port 90, to the desired Frontend using the configuration, something like this:
```
[frontends.frontend1]
entrypoints = ["special"]
```

your default entry points - `--DefaultEntryPoints=http,https` don't have `special` listed in it, so there is no route by default from port 90 to the frontend pipes.

since you seem to be using a `Docker` provider, you might want to try to add `special` to the default entrypoints list, or use `traefik.frontend.entryPoints` label to override which entrypoint you want to be linked to the given frontend.

**Comment by Yajo** [comment]
Yes @aantono, I had that into account and added the corresponding label.

The problem is that if you:

- use a special entrypoint that requires the user to add the port in the web browser (anything but http 80 or https 443).
- want to filter by host

You simply can't. Try adding a container such as:

    docker container run -it --rm --label traefik.frontend.entryPoints=special --label "traefik.frontend.rule=Host:example.com" --label traefik.port=80 --label traefik.enable=true stackatoapps/phpinfo

Then enter `http://example.com:90` and you will see an error.

**Comment by rcuza** [comment]
@Yajo  - Can you add your `config.toml` to the issue? I had a similar problem and realized I didn't have the correct entry points.

```
# traefik.toml
logLevel = "DEBUG"
defaultEntryPoints = ["http"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.http8080]
  address = ":8080"
  [entryPoints.http8181]
  address = ":8181"

[file]

# rules
[backends]
  [backends.backend1]
    [backends.backend1.servers.server1]
    url = "http://10.0.0.5:4000"
  [backends.backend2]
    [backends.backend2.servers.server1]
    url = "http://10.0.0.6:8080"
  [backends.backend3]
    [backends.backend3.servers.server1]
    url = "http://10.0.0.6:8181"

[frontends]
  [frontends.frontend1]
  backend = "backend1"
  entrypoints = ["http"]
    [frontends.frontend1.routes.test_1]
    rule = "Host:www.example.com"
  [frontends.frontend2]
  backend = "backend2"
  entrypoints = ["http8080"]
    [frontends.frontend2.routes.test_1]
    rule = "Host:app.example.com"
  [frontends.frontend3]
  backend = "backend3"
  entrypoints = ["http8181"]
    [frontends.frontend3.routes.test_1]
    rule = "Host:app.example.com"
```

I've only been using traefik for two days, so there might be a better way to do this.

## What the code does
DNS is set up so `app.example.com` and `www.example.com` both point to my traefik server. When I go to `http://www.example.com/` I get the content from `http://10.0.0.5:4000`. When I go to `http://app.example.com:8080` I get the content from `http://10.0.0.6:8080` and when I go to `http://app.example.com:8181` I get the content from `http://10.0.0.6:8181`. Be sure your firewall/security group rules allows ports `80`, `8080`, and `8181` through.

# Something I Would Like to Do
If you mean you would like to go to `http://app.example.com/someprefix` and hit `http://10.0.0.6:8080` (using my example), I have not been able to successfully do this yet. I've assumed it was my own ignorance at this point, so I will be watching this issue with interest.

**Comment by Yajo** [comment]
I have no `traefik.toml`, all is configured through CLI args + docker labels.

I'll try and see if I had something wrong too.

**Comment by rcuza** [comment]
Now that I've had a few more hours playing with traefik, I believe @aantono said what I was trying to say more succinctly and explicitly pointed out the importance of routes.

**Comment by traefiker** [comment]
I'll close the issue due to inactivity but feel free to re-open if needed.

**Comment by emj365** [comment]
try

```
traefik \
  --entryPoints='Name:special Address::90' \
  ...
```
