### ISSUE TITLE
IPsource mesos backend

### ISSUE THREAD

**Issue by davidmartini** [containous/traefik#1618]
Hello,

I trying to connect my Traefik instance to my mesos cluster. The connexion works and all tasks appear but the url/address are empty. I tried with IPsource parameter = docker, mesos and host.

![sans titre](https://cloud.githubusercontent.com/assets/14126223/26160290/21a7603c-3b21-11e7-9d97-1a78f0ce3e29.png)

When Traefik connected to my mesos cluster, I have this message with URL empty :

```shell
DEBU[2017-05-17T16:52:31+02:00] Configuration received from provider mesos: {"backends":{"backend-apps1":{"servers":{"server-apps1-70ae7369-3afc-11e7-8e4e-024277e994ab":{"url":"**http://:31141**","weight":0}},"loadBalancer":{"method":"wrr"}},"backend-elasticclusterpei01":{"servers":{"server-elasticclusterpei01-d5b7a862-3941-11e7-8e4e-024277e994ab":{"url":"http://:31413","weight":0}},"loadBalancer":{"method":"wrr"}},"backend-elasticexecutor-PEI01":{"servers":{"server-elasticsearch-uabigviz11-creteil-francetelecom-fr-20170515T074414-284Z":{"url":"http://:31000","weight":0},"server-elasticsearch-uabigviz12-creteil-francetelecom-fr-20170515T074414-387Z":{"url":"**http://:31000**","weight":0},"server-elasticsearch-uabigviz14-creteil-francetelecom-fr-20170515T074400-117Z":{"url":"http://:31000","weight":0}},"loadBalancer":{"method":"wrr"}},"backend-grafana":{"servers":{"server-grafana-df172e13-3afb-11e7-8e4e-024277e994ab":{"url":"http://:31005","weight":0}},"loadBalancer":{"method":"wrr"}},"backend-prometheus":{"servers":{"server-prometheus-a9519322-3afa-11e7-8e4e-024277e994ab":{"url":"http://:31824","weight":0}},"loadBalancer":{"method":"wrr"}}},"frontends":{"frontend-apps1-70ae7369-3afc-11e7-8e4e-024277e994ab":{"entryPoints":["http"],"backend":"backend-apps1","routes":{"route-hostapps1-70ae7369-3afc-11e7-8e4e-024277e994ab":{"rule":"Host:apps1.si.fr.intraorange"}},"priority":0,"basicAuth":null},"frontend-elasticclusterpei01-d5b7a862-3941-11e7-8e4e-024277e994ab":{"entryPoints":["http"],"backend":"backend-elasticclusterpei01","routes":{"route-hostelasticclusterpei01-d5b7a862-3941-11e7-8e4e-024277e994ab":{"rule":"Host:elasticclusterpei01.si.fr.intraorange"}},"priority":0,"basicAuth":null},"frontend-elasticsearch-uabigviz12-creteil-francetelecom-fr-20170515T074414-387Z":{"entryPoints":["http"],"backend":"backend-elasticexecutor-PEI01","routes":{"route-hostelasticsearch-uabigviz12-creteil-francetelecom-fr-20170515T074414-387Z":{"rule":"Host:elasticexecutor-pei01.si.fr.intraorange"}},"priority":0,"basicAuth":null},"frontend-grafana-df172e13-3afb-11e7-8e4e-024277e994ab":{"entryPoints":["http"],"backend":"backend-grafana","routes":{"route-hostgrafana-df172e13-3afb-11e7-8e4e-024277e994ab":{"rule":"Host:grafana.si.fr.intraorange"}},"priority":0,"basicAuth":null},"frontend-prometheus-a9519322-3afa-11e7-8e4e-024277e994ab":{"entryPoints":["http"],"backend":"backend-prometheus","routes":{"route-hostprometheus-a9519322-3afa-11e7-8e4e-024277e994ab":{"rule":"Host:prometheus.si.fr.intraorange"}},"priority":0,"basicAuth":null}}}
```
Can you help me? I used v1.2.3 and v1.3.0-rc2 version.

Thanks for your help.

**Comment by ldez** [comment]
If you want support, don't hesitate join the [Traefik community Slack channel](https://traefik.herokuapp.com)

**Comment by timoreimann** [comment]
Just to clarify: do you run on Mesos directly or possibly via Marathon?

**Comment by davidmartini** [comment]
@timoreimann I have a Mesos Cluster with Marathon Framewok. I need to list mesos task lunched by other Framework (ES for exemple) where there are not listed on Marathon.

**Comment by davidmartini** [comment]
**My traefik.toml:**

------------------------------------------------------------------------------------------------
[web]
address = ":90"

[mesos]
endpoint = "10.195.51.13:5050,10.195.51.14:5050,10.195.51.15:5050"
#endpoint = "zk://10.195.51.13:2181,10.195.51.14:2181,10.195.51.15:2181/mesos"
domain = "si.fr.intraorange"
ExposedByDefault = true
IPSources = "mesos"
filename = "mesos.tmpl"
------------------------------------------------------------------------------------------------

**My mesos.tmpl:**

------------------------------------------------------------------------------------------------
{{$apps := .Applications}}
[backends]{{range .Tasks}}
    [backends.backend{{getBackend . $apps}}.servers.server-{{getID .}}]
    url = "{{getProtocol . $apps}}://{{getHost . }}:{{getPort . $apps}}"
    weight = {{getWeight . $apps}}
{{end}}

[frontends]{{range .Applications}}
  [frontends.frontend-{{getFrontEndName .}}]
  backend = "backend{{getFrontendBackend .}}"
  passHostHeader = {{getPassHostHeader .}}
  priority = {{getPriority .}}
  entryPoints = [{{range getEntryPoints .}}
    "{{.}}",
  {{end}}]
    [frontends.frontend-{{getFrontEndName .}}.routes.route-host{{getFrontEndName .}}]
    rule = "{{getFrontendRule .}}"
{{end}}
------------------------------------------------------------------------------------------------


My logs at launch:

------------------------------------------------------------------------------------------------
INFO[2017-05-18T14:20:35+02:00] Traefik version v1.2.3 built on 2017-04-13_07:32:59PM
INFO[2017-05-18T14:20:35+02:00] Using TOML configuration file /FS01/traefik/traefik.toml
DEBU[2017-05-18T14:20:35+02:00] Global configuration loaded {"GraceTimeOut":10,"Debug":true,"CheckNewVersion":true,"AccessLogsFile":"","TraefikLogsFile":"","LogLevel":"DEBUG","EntryPoints":{"http":{"Network":"","Address":":80","TLS":null,"Redirect":null,"Auth":null,"Compress":false}},"Cluster":null,"Constraints":[],"ACME":null,"DefaultEntryPoints":["http"],"ProvidersThrottleDuration":2000000000,"MaxIdleConnsPerHost":200,"InsecureSkipVerify":false,"Retry":null,"Docker":null,"File":null,"Web":{"Address":":90","CertFile":"","KeyFile":"","ReadOnly":false,"Statistics":null,"Metrics":null,"Auth":null},"Marathon":null,"Consul":null,"ConsulCatalog":null,"Etcd":null,"Zookeeper":null,"Boltdb":null,"Kubernetes":null,"Mesos":{"Watch":true,"Filename":"mesos.tmpl","Constraints":[],"Endpoint":"10.195.51.13:5050,10.195.51.14:5050,10.195.51.15:5050","Domain":"si.fr.intraorange","ExposedByDefault":true,"GroupsAsSubDomains":false,"ZkDetectionTimeout":30,"RefreshSeconds":30,"IPSources":"mesos","StateTimeoutSecond":30,"Masters":null},"Eureka":null,"ECS":null,"Rancher":null}
INFO[2017-05-18T14:20:35+02:00] Preparing server http &{Network: Address::80 TLS:<nil> Redirect:<nil> Auth:<nil> Compress:false}
INFO[2017-05-18T14:20:35+02:00] Starting provider *main.WebProvider {"Address":":90","CertFile":"","KeyFile":"","ReadOnly":false,"Statistics":null,"Metrics":null,"Auth":null}
INFO[2017-05-18T14:20:35+02:00] Starting provider *provider.Mesos {"Watch":true,"Filename":"mesos.tmpl","Constraints":[],"Endpoint":"10.195.51.13:5050,10.195.51.14:5050,10.195.51.15:5050","Domain":"si.fr.intraorange","ExposedByDefault":true,"GroupsAsSubDomains":false,"ZkDetectionTimeout":30,"RefreshSeconds":30,"IPSources":"mesos","StateTimeoutSecond":30,"Masters":null}
INFO[2017-05-18T14:20:35+02:00] Starting server on :80
DEBU[2017-05-18T14:20:35+02:00] mesos
DEBU[2017-05-18T14:20:35+02:00] new masters detected: [10.195.51.13:5050 10.195.51.14:5050 10.195.51.15:5050]
ERROR: 2017/05/18 14:20:35 generator.go:232: Get http://10.195.51.13:5050/master/state.json: dial tcp 10.195.51.13:5050: getsockopt: connection refused
WARN[2017-05-18T14:20:35+02:00] Error checking new version: Get https://update.traefik.io/repos/containous/traefik/releases: dial tcp: lookup update.traefik.io on 192.168.0.232:53: no such host
DEBU[2017-05-18T14:20:35+02:00] Load balancer method '<nil>' for backend backend-elasticexecutor-PEI01: Invalid method, using default. Using default wrr.
DEBU[2017-05-18T14:20:35+02:00] Load balancer method '<nil>' for backend backend-prometheus: Invalid method, using default. Using default wrr.
DEBU[2017-05-18T14:20:35+02:00] Load balancer method '<nil>' for backend backend-apps1: Invalid method, using default. Using default wrr.
DEBU[2017-05-18T14:20:35+02:00] Load balancer method '<nil>' for backend backend-elasticclusterpei01: Invalid method, using default. Using default wrr.
DEBU[2017-05-18T14:20:35+02:00] Configuration received from provider mesos: {"backends":{"backend-apps1":{"servers":{"server-apps1-f458c5ac-3bb4-11e7-a091-000c297c0f6d":{"url":"http://:31788","weight":0},"server-apps1-f46b152d-3bb4-11e7-a091-000c297c0f6d":{"url":"http://:31985","weight":0}},"loadBalancer":{"method":"wrr"}},"backend-elasticclusterpei01":{"servers":{"server-elasticclusterpei01-19a28f71-3bb6-11e7-a091-000c297c0f6d":{"url":"http://:31275","weight":0}},"loadBalancer":{"method":"wrr"}},"backend-elasticexecutor-PEI01":{"servers":{"server-elasticsearch-uabigviz09-creteil-francetelecom-fr-20170518T104111-646Z":{"url":"http://:31000","weight":0},"server-elasticsearch-uabigviz12-creteil-francetelecom-fr-20170518T104029-402Z":{"url":"http://:31000","weight":0},"server-elasticsearch-uabigviz13-creteil-francetelecom-fr-20170518T104111-568Z":{"url":"http://:31000","weight":0}},"loadBalancer":{"method":"wrr"}},"backend-prometheus":{"servers":{"server-prometheus-96f4e2d0-3bb5-11e7-a091-000c297c0f6d":{"url":"http://:31501","weight":0}},"loadBalancer":{"method":"wrr"}}},"frontends":{"frontend-apps1-f46b152d-3bb4-11e7-a091-000c297c0f6d":{"entryPoints":["http"],"backend":"backend-apps1","routes":{"route-hostapps1-f46b152d-3bb4-11e7-a091-000c297c0f6d":{"rule":"Host:apps1.si.fr.intraorange"}},"priority":0},"frontend-elasticclusterpei01-19a28f71-3bb6-11e7-a091-000c297c0f6d":{"entryPoints":["http"],"backend":"backend-elasticclusterpei01","routes":{"route-hostelasticclusterpei01-19a28f71-3bb6-11e7-a091-000c297c0f6d":{"rule":"Host:elasticclusterpei01.si.fr.intraorange"}},"priority":0},"frontend-elasticsearch-uabigviz09-creteil-francetelecom-fr-20170518T104111-646Z":{"entryPoints":["http"],"backend":"backend-elasticexecutor-PEI01","routes":{"route-hostelasticsearch-uabigviz09-creteil-francetelecom-fr-20170518T104111-646Z":{"rule":"Host:elasticexecutor-pei01.si.fr.intraorange"}},"priority":0},"frontend-prometheus-96f4e2d0-3bb5-11e7-a091-000c297c0f6d":{"entryPoints":["http"],"backend":"backend-prometheus","routes":{"route-hostprometheus-96f4e2d0-3bb5-11e7-a091-000c297c0f6d":{"rule":"Host:prometheus.si.fr.intraorange"}},"priority":0}}}
DEBU[2017-05-18T14:20:35+02:00] Last mesos config received more than 2s, OK
DEBU[2017-05-18T14:20:35+02:00] Creating frontend frontend-apps1-f46b152d-3bb4-11e7-a091-000c297c0f6d
DEBU[2017-05-18T14:20:35+02:00] Wiring frontend frontend-apps1-f46b152d-3bb4-11e7-a091-000c297c0f6d to entryPoint http
DEBU[2017-05-18T14:20:35+02:00] Creating route route-hostapps1-f46b152d-3bb4-11e7-a091-000c297c0f6d Host:apps1.si.fr.intraorange
DEBU[2017-05-18T14:20:35+02:00] Creating backend backend-apps1
DEBU[2017-05-18T14:20:35+02:00] Creating load-balancer wrr
DEBU[2017-05-18T14:20:35+02:00] Creating server server-apps1-f46b152d-3bb4-11e7-a091-000c297c0f6d at http://:31985 with weight 0
DEBU[2017-05-18T14:20:35+02:00] Creating server server-apps1-f458c5ac-3bb4-11e7-a091-000c297c0f6d at http://:31788 with weight 0
DEBU[2017-05-18T14:20:35+02:00] Creating frontend frontend-elasticclusterpei01-19a28f71-3bb6-11e7-a091-000c297c0f6d
DEBU[2017-05-18T14:20:35+02:00] Wiring frontend frontend-elasticclusterpei01-19a28f71-3bb6-11e7-a091-000c297c0f6d to entryPoint http
DEBU[2017-05-18T14:20:35+02:00] Creating route route-hostelasticclusterpei01-19a28f71-3bb6-11e7-a091-000c297c0f6d Host:elasticclusterpei01.si.fr.intraorange
DEBU[2017-05-18T14:20:35+02:00] Creating backend backend-elasticclusterpei01
DEBU[2017-05-18T14:20:35+02:00] Creating load-balancer wrr
DEBU[2017-05-18T14:20:35+02:00] Creating server server-elasticclusterpei01-19a28f71-3bb6-11e7-a091-000c297c0f6d at http://:31275 with weight 0
DEBU[2017-05-18T14:20:35+02:00] Creating frontend frontend-elasticsearch-uabigviz09-creteil-francetelecom-fr-20170518T104111-646Z
DEBU[2017-05-18T14:20:35+02:00] Wiring frontend frontend-elasticsearch-uabigviz09-creteil-francetelecom-fr-20170518T104111-646Z to entryPoint http
DEBU[2017-05-18T14:20:35+02:00] Creating route route-hostelasticsearch-uabigviz09-creteil-francetelecom-fr-20170518T104111-646Z Host:elasticexecutor-pei01.si.fr.intraorange
DEBU[2017-05-18T14:20:35+02:00] Creating backend backend-elasticexecutor-PEI01
DEBU[2017-05-18T14:20:35+02:00] Creating load-balancer wrr
DEBU[2017-05-18T14:20:35+02:00] Creating server server-elasticsearch-uabigviz09-creteil-francetelecom-fr-20170518T104111-646Z at http://:31000 with weight 0
DEBU[2017-05-18T14:20:35+02:00] Creating server server-elasticsearch-uabigviz13-creteil-francetelecom-fr-20170518T104111-568Z at http://:31000 with weight 0
DEBU[2017-05-18T14:20:35+02:00] Creating server server-elasticsearch-uabigviz12-creteil-francetelecom-fr-20170518T104029-402Z at http://:31000 with weight 0
DEBU[2017-05-18T14:20:35+02:00] Creating frontend frontend-prometheus-96f4e2d0-3bb5-11e7-a091-000c297c0f6d
DEBU[2017-05-18T14:20:35+02:00] Wiring frontend frontend-prometheus-96f4e2d0-3bb5-11e7-a091-000c297c0f6d to entryPoint http
DEBU[2017-05-18T14:20:35+02:00] Creating route route-hostprometheus-96f4e2d0-3bb5-11e7-a091-000c297c0f6d Host:prometheus.si.fr.intraorange
DEBU[2017-05-18T14:20:35+02:00] Creating backend backend-prometheus
DEBU[2017-05-18T14:20:35+02:00] Creating load-balancer wrr
DEBU[2017-05-18T14:20:35+02:00] Creating server server-prometheus-96f4e2d0-3bb5-11e7-a091-000c297c0f6d at http://:31501 with weight 0
INFO[2017-05-18T14:20:35+02:00] Server configuration reloaded on :80
------------------------------------------------------------------------------------------------

**Comment by traefiker** [comment]
I'll close the issue due to inactivity but feel free to re-open if needed.
