### ISSUE TITLE
ACME.CAServer setting ignored

### ISSUE THREAD

**Issue by Yajo** [containous/traefik#1625]
### Do you want to request a *feature* or report a *bug*?

bug

### What did you do?

I exceded Let's Encrypt rate limits while testing a domain and traefik, so I switched Traefik to start using the staging environment.

### What did you expect to see?

New cert downloaded from staging CA.

### What did you see instead?

The same error as before.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.2.3
Codename:     morbier
Go version:   go1.7.5
Built:        2017-04-13_07:21:10PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
arguments:

      - --ACME.ACMELogging
      - --ACME.Email=***
      - --ACME.EntryPoint=https
      - --ACME.CAServer=https://acme-staging.api.letsencrypt.org/directory
      - --ACME.OnDemand
      - --ACME.OnHostRule
      - --ACME.Storage=/etc/traefik/acme/acme.json
      - --DefaultEntryPoints=http,https
      - --Docker
      - --Docker.ExposedByDefault=false
      - --Docker.Watch
      - --EntryPoints=Name:http Address::80
        Redirect.EntryPoint:https Compress:on
      - --EntryPoints=Name:https Address::443
        TLS Compress:on
      - --LogLevel=DEBUG

### If applicable, please paste the log output in debug mode (`--debug` switch)

```shell
INFO[2017-05-18T11:22:51Z] Traefik version v1.2.3 built on 2017-04-13_07:21:10PM 
DEBU[2017-05-18T11:22:51Z] Global configuration loaded {"GraceTimeOut":10,"Debug":false,"CheckNewVersion":true,"AccessLogsFile":"","TraefikLogsFile":"","LogLevel":"DEBUG","EntryPoints":{"http":{"Network":"","Address":":80","TLS":null,"Redirect":{"EntryPoint":"https","Regex":"","Replacement":""},"Auth":null,"Compress":true},"https":{"Network":"","Address":":443","TLS":{"MinVersion":"","CipherSuites":null,"Certificates":[],"ClientCAFiles":null},"Redirect":null,"Auth":null,"Compress":true}},"Cluster":null,"Constraints":[],"ACME":{"Email":"support+interna@example.com","Domains":null,"Storage":"/etc/traefik/acme/acme.json","StorageFile":"","OnDemand":true,"OnHostRule":true,"CAServer":"https://acme-staging.api.letsencrypt.org/directory","EntryPoint":"https","DNSProvider":"","DelayDontCheckDNS":0,"ACMELogging":true,"TLSConfig":null},"DefaultEntryPoints":["http","https"],"ProvidersThrottleDuration":2000000000,"MaxIdleConnsPerHost":200,"InsecureSkipVerify":false,"Retry":null,"Docker":{"Watch":true,"Filename":"","Constraints":null,"Endpoint":"http://dockersocket:2375","Domain":"","TLS":null,"ExposedByDefault":false,"UseBindPortIP":false,"SwarmMode":false},"File":null,"Web":null,"Marathon":null,"Consul":null,"ConsulCatalog":null,"Etcd":null,"Zookeeper":null,"Boltdb":null,"Kubernetes":null,"Mesos":null,"Eureka":null,"ECS":null,"Rancher":null} 
INFO[2017-05-18T11:22:51Z] Preparing server http &{Network: Address::80 TLS:<nil> Redirect:0xc4201b2ba0 Auth:<nil> Compress:true} 
INFO[2017-05-18T11:22:51Z] Preparing server https &{Network: Address::443 TLS:0xc42000d440 Redirect:<nil> Auth:<nil> Compress:true} 
INFO[2017-05-18T11:22:51Z] Starting server on :80                       
INFO[2017-05-18T11:22:51Z] Loading ACME Account...                      
INFO[2017-05-18T11:22:51Z] Loaded ACME config from store /etc/traefik/acme/acme.json 
DEBU[2017-05-18T11:22:51Z] Building ACME client...                      
DEBU[2017-05-18T11:22:51Z] AgreeToTOS...                                
legolog: 2017/05/18 11:22:52 [INFO] acme: Querying account for https://acme-v01.api.letsencrypt.org/acme/reg/**********
[...]
DEBU[2017-05-18T11:22:53Z] LoadCertificateForDomains [server-007.example.com]... 
DEBU[2017-05-18T11:22:53Z] Loading ACME certificates [server-007.example.com]... 
legolog: 2017/05/18 11:22:53 [INFO][server-007.example.com] acme: Obtaining bundled SAN certificate
legolog: 2017/05/18 11:22:53 [INFO][server-007.example.com] AuthURL: https://acme-v01.api.letsencrypt.org/acme/authz/****************
legolog: 2017/05/18 11:22:53 [INFO][server-007.example.com] acme: Authorization already valid; skipping challenge
legolog: 2017/05/18 11:22:53 [INFO][server-007.example.com] acme: Validations succeeded; requesting certificates
ERRO[2017-05-18T11:22:58Z] map[server-007.example.com:acme: Error 429 - urn:acme:error:rateLimited - Error creating new cert :: too many certificates already issued for exact set of domains: server-007.example.com] 
ERRO[2017-05-18T11:22:58Z] Error getting ACME certificates [server-007.example.com] : Cannot obtain certificates map[server-007.example.com:acme: 
Error 429 - urn:acme:error:rateLimited - Error creating new cert :: too many certificates already issued for exact set of domains: server-007.example.com]+v 
```

Is it possible this is happening because that same server had been using the production ca server before? I understand this would be then still a bug; Traefik should use the same CA server for certs it had before, but use the new one for new certs.

**Comment by dtomcej** [comment]
Hello @Yajo, you are correct. The issuing auth URL and associated CA URL are stored in the acme object for that certificate. This is so that if you are running multiple traefik instances in a cluster, the certificate information can be transfered between them.

In your case, you may want to remove that certificate from your acme.json file, and it should build a new certificate request with the staging server.

**Comment by Yajo** [comment]
But if I'm not wrong, if it tries to download the new cert it is because the old one is not available in `acme.json`. Then maybe the solution would be not to store cert info in `acme.json` until we actually have a valid cert, don't you think?

**Comment by dtomcej** [comment]
Pre-challenge data is stored in acme.json.

**Comment by Yajo** [comment]
Then, could we discard that data if we have no valid cert yet and the CA server changed?

**Comment by traefiker** [comment]
I'll close the issue due to inactivity but feel free to re-open if needed.

**Comment by Yajo** [comment]
Please reopen, this is still valid.
