### ISSUE TITLE
vendoring dependencies

### ISSUE THREAD

**Issue by drewwells** [containous/traefik#1633]
the vendored deps appear to be out of date, I'm seeing many errors attempting to build Traefik now.

Does this only build within a docker image now?

**Comment by ldez** [comment]
Hello @drewwells,

the vendored deps are up to date. 😉 You can build as normal. 😃 

Could you give more information about your problem?

**Comment by ldez** [comment]
I'll close the issue due to inactivity but feel free to re-open if needed.
