### ISSUE TITLE
Performance profiling: Consider adding net/http/pprof endpoint

### ISSUE THREAD

**Issue by seryl** [containous/traefik#1648]
### Feature Request

Add [pprof](https://golang.org/pkg/net/http/pprof/) endpoint so we can get better detail into where and why the router's spending it's time.

[go-torch](https://github.com/uber/go-torch) should help a lot with visualization if we put this in place.

![Example-torch](https://uber.github.io/go-torch/meta.svg)

Likely we'll want to get this in place if we want to hit top-end limits for number of routing rules or time per routing rule.

There's some examples of getting graphviz output [here](https://blog.golang.org/profiling-go-programs).

Like this:

![dotgraph of pprof output](https://blog.golang.org/profiling-go-programs_havlak4a-mallocgc.png)

**Comment by timoreimann** [comment]
We've had a few performance questions / issues on this area already, so I think having a proper pprof endpoint would be super valuable. I've used it myself on other projects with great success.

It should come with a switch to enable/disable on a per-need basis.
