### ISSUE TITLE
Support all tags from Providers for constraint filtering

### ISSUE THREAD

**Issue by aantono** [containous/traefik#1656]
The use-case here is to enable the ability to filter (use tag constraints) on the existing provider tags (Consul tags, Docker labels, etc), not only the ones that are defined in `traefik.tags`. 

Many places with existing SD infrastructure already have quite an elaborate tagging setup for their services, so being able to leverage those for filtering is a big plus.

 For example, each Spring Boot application that uses `sping-cloud-consul` module, will automatically register the management endpoint using `management` tag. 

Because it might not be desired to expose LB routes to management endpoints, one might want to create a constraint rule like constraints = `["tag!=management"]`, and when coupled with `AllTagsConstraintFiltering=true`, it will use the "raw" `management` tag value, instead of only the values provided by `traefik.tags` tag.

**Comment by traefiker** [comment]
Closed by #4965.
