### ISSUE TITLE
Kill -HUP kills traefik

### ISSUE THREAD

**Issue by papey** [containous/traefik#1660]
### Do you want to request a *feature* or report a *bug*?

**bug**

### What did you do?

Send a kill -HUP signal to traefik PID

### What did you expect to see?

Treafik reload or nothing.

Looking at the code, https://github.com/containous/traefik/blob/master/server/server.go#L82, in particular, there is nothing visible for SIGHUP signal handling so normal behavior is "ignore the signal"

### What did you see instead?

Traefik stops

### Some testing steps

 1. Start traefik
 2. Find pid
 3. Send kill -HUP to $PID

`./dist/traefik`

then in another terminal : 

`kill -HUP $(pidof traefik)
`
### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2643271053eeb03ca2f6a5f6c8d0af7c776c4849
Codename:     cheddar
Go version:   go1.8.2
Built:        2017-05-24_08:51:38AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```json
{
 "GraceTimeOut": 10000000000,
 "Debug": false,
 "CheckNewVersion": true,
 "AccessLogsFile": "",
 "TraefikLogsFile": "",
 "LogLevel": "ERROR",
 "EntryPoints": {},
 "Cluster": null,
 "Constraints": [],
 "ACME": null,
 "DefaultEntryPoints": [],
 "ProvidersThrottleDuration": 2000000000,
 "MaxIdleConnsPerHost": 200,
 "IdleTimeout": 180000000000,
 "InsecureSkipVerify": false,
 "Retry": null,
 "HealthCheck": {
  "Interval": 30000000000
 },
 "Docker": null,
 "File": null,
 "Web": null,
 "Marathon": null,
 "Consul": null,
 "ConsulCatalog": null,
 "Etcd": null,
 "Zookeeper": null,
 "Boltdb": null,
 "Kubernetes": null,
 "Mesos": null,
 "Eureka": null,
 "ECS": null,
 "Rancher": null,
 "DynamoDB": null,
 "ConfigFile": ""
}
```

### If applicable, please paste the log output in debug mode (`--debug` switch)

```shell
INFO[2017-05-24T11:00:52+02:00] Traefik version 2643271053eeb03ca2f6a5f6c8d0af7c776c4849 built on 2017-05-24_08:51:38AM 
DEBU[2017-05-24T11:00:52+02:00] Global configuration loaded {"GraceTimeOut":10000000000,"Debug":true,"CheckNewVersion":true,"AccessLogsFile":"","TraefikLogsFile":"","LogLevel":"DEBUG","EntryPoints":{"http":{"Network":"","Address":":80","TLS":null,"Redirect":null,"Auth":null,"Compress":false}},"Cluster":null,"Constraints":[],"ACME":null,"DefaultEntryPoints":["http"],"ProvidersThrottleDuration":2000000000,"MaxIdleConnsPerHost":200,"IdleTimeout":180000000000,"InsecureSkipVerify":false,"Retry":null,"HealthCheck":{"Interval":30000000000},"Docker":null,"File":null,"Web":null,"Marathon":null,"Consul":null,"ConsulCatalog":null,"Etcd":null,"Zookeeper":null,"Boltdb":null,"Kubernetes":null,"Mesos":null,"Eureka":null,"ECS":null,"Rancher":null,"DynamoDB":null} 
INFO[2017-05-24T11:00:52+02:00] Preparing server http &{Network: Address::80 TLS:<nil> Redirect:<nil> Auth:<nil> Compress:false} 
INFO[2017-05-24T11:00:52+02:00] Starting server on :80  
```

**Comment by timoreimann** [comment]
As speculated by @emilevauge, the culprit could be some library / third-party dependency registering a handler for SIGHUP.

**Comment by timoreimann** [comment]
Turned out Traefik is just exhibiting the default behavior: From the [signal package documentation](https://golang.org/pkg/os/signal/):

>A SIGHUP, SIGINT, or SIGTERM signal causes the program to exit.

Since we only handle `SIGINT` and `SIGTERM` gracefully but don't ignore `SIGHUP`, Traefik ends up getting killed by the latter.

There doesn't seem a good reason to change the behavior; as such, I'll close the issue.

(Kudos to @dtomcej who spotted this!)

**Comment by phaseOne** [comment]
@timoreimann Can we re-evaluate this proposed change? nginx already has this behavior, and it would be useful during development.

For instance, I am using traefik in a docker-compose stack, and I would like to reload traefik's configuration without bringing the whole stack down.

**Comment by emilevauge** [comment]
@phaseOne you can still restart your Traefik container without bringing the whole stack down right ?

**Comment by rmetzler** [comment]
I was curious how NGINX and other long living processes handle SIGHUP, so I looked it up. From what I learned, SIGHUP is indeed often used to reload configuration, but it's not a standard behaviour every daemon process implements.

- NGINX: http://nginx.org/en/docs/control.html
> HUP | changing configuration, keeping up with a changed time zone (only for FreeBSD and Linux), starting new worker processes with a new configuration, graceful shutdown of old worker processes

- Apache has similar behaviour: https://httpd.apache.org/docs/2.4/stopping.html#hup
> Sending the HUP or restart signal to the parent causes it to kill off its children like in TERM, but the parent doesn't exit. It re-reads its configuration files, and re-opens any log files. Then it spawns a new set of children and continues serving hits.

- Wikipedia's last sentence of "Modern Usage": https://en.wikipedia.org/wiki/SIGHUP#Modern_usage
> Daemon programs sometimes use SIGHUP as a signal to restart themselves, the most common reason for this being to re-read a configuration file that has been changed.

- SSHD https://linux.die.net/man/8/sshd
 > sshd rereads its configuration file when it receives a hangup signal, SIGHUP, by executing itself with the name and options it was started with, e.g. /usr/sbin/sshd.
- named https://linux.die.net/man/8/named
> SIGHUP Force a reload of the server.

- NTPD does something similar, but from the docs it seems like only parts of the config are reloaded https://docs.ntpsec.org/latest/ntpd.html


- slapd seems to use SIGHUP in a manual process if you want to change configuration, but that's not the only usecase https://linux.die.net/man/5/slapd.conf 
> A SIGHUP signal will only cause a 'gentle' shutdown-attempt: Slapd will stop listening for new connections, but will not close the connections to the current clients. Future write operations return unwilling-to-perform, though. Slapd terminates when all clients have closed their connections (if they ever do), or - as before - if it receives a SIGTERM signal. This can be useful if you wish to terminate the server and start a new slapd server with another database, without disrupting the currently active clients. The default is off. You may wish to use idletimeout along with this option.

- HAPROXY dumps the config on SIGHUP
- Caddy uses SIGUSR1 https://github.com/mholt/caddy/issues/107
