### ISSUE TITLE
arm32 and arm64 docker Images on Docker Hub for Traefik 

### ISSUE THREAD

**Issue by gdeverlant** [containous/traefik#1665]
### Do you want to request a *feature* or report a *bug*?

**FEATURE**

Is it possible for you guys to push arm32 and arm64 docker Images on Docker Hub for Traefik

**Comment by klud1** [comment]
+1 to this!

It would be great!

I've been using this image (https://hub.docker.com/r/hypriot/rpi-traefik/) made by people at Hypriot, they even wrote a post about how to build ARM images on Travis (https://blog.hypriot.com/post/setup-simple-ci-pipeline-for-arm-images/)

**Comment by jsrz** [comment]
Hello,

Is this something I could contribute to?

It shouldn't be terribly difficult. I've basically already done this in a private repo. I would focus on ARM64 first though. 64-bit architectures are the target for server workloads.

There would be a few questions to answer:
- Where in containous/traefik-library-image would this new ARM (or rather aarch64) Dockerfile be placed?

- Something a bit more radical from just creating another Dockerfile for aarch64. 
Create a Dockerfile.template with all the x86 default stuff in it. Then build from a Makefile. This file will check the architecture, and then use the Dockerfile template as is if it's x86, or if it's aarch64, run sed to swap out the bits that are needed for aarch64. This would make it a easier to add new architectures down the road (reduce the copying of Dockerfiles that are 99% the same). Of course, at some point, Docker is supposed to gain the manifest feature (https://github.com/docker-library/official-images/issues/2289) which should eliminate the need for something like this, but anyway, perhaps the long term multi-architecture support question is a discussion for another time.

- Could we agree to call the file Dockerfile.aarch64?

- What docker tag would we agree to? I would suggest something like v1.3.0-alpine-aarch64. If did a distroless version, it could be called v1.3.0-aarch64.

- Let's say I got all of this done. Who would build the image and then push it to Docker hub?

**Comment by klud1** [comment]
Hi,  @jsrz. I think `v1.3.0-aarch64` /  `latest-aarch64` and `v1.30-armhf` / `latest-armhf` should be good (^_^), and the images must be part of the official repo in Docker Hub.

**Comment by ldez** [comment]
@jsrz follow the "alpine" structure in https://github.com/containous/traefik-library-image: Create a folder by arch, with a `Dockerfile.template` inside.

**Comment by jsrz** [comment]
PR is here:
https://github.com/containous/traefik-library-image/pull/10

I'm hoping this initial upload can start the discussion on how this should be organized. I figure I'll need to make some more changes/updates.

**Comment by tianon** [comment]
The Alpine image doesn't have official multiarch bits (yet), but see https://github.com/docker-library/official-images/blob/e20de254bcdfbee34da8192c4394d7ceee9a8338/README.md#multiple-architectures for some details about how this sort of thing will work for official images.

The goal is to avoid architecture-specific `Dockerfile`s at all costs, since they tend to increase the maintenance/review burden somewhat exponentially.

**Comment by ldez** [comment]
Closed by containous/traefik-library-image#15
