### ISSUE TITLE
Multiple path separators in the url path causing redirect

### ISSUE THREAD

**Issue by dylanmei** [containous/traefik#167]
When Traefik handles an url with multiple path separators in the url path, it creates a 301 redirect.

Example:

```
$ curl -i http://traefik.local:80/http://app.local
HTTP/1.1 301 Moved Permanently
Location: /http:/app.local
Date: Sat, 16 Jan 2016 17:21:16 GMT
Content-Length: 0
Content-Type: text/plain; charset=utf-8
```

The redirect is caused by gorilla/mux: https://github.com/gorilla/mux/issues/94

I've discovered two backend apps that no longer function as designed.

- [thumbor/thumbor](https://github.com/thumbor/thumbor)
- [Capgemini/mesos-ui](https://github.com/Capgemini/mesos-ui)

Like the example above, both of these apps use urls with their proxy data embedded in the url path (as opposed to a query-string). For example:

    http://my-app/proxy/http://another-app

While I don't personally agree with their design decisions, these apps and probably many more are unusable due to the path cleaning / redirect.

**Comment by emilevauge** [comment]
Hi @dylanmei, ouch! If I have to merge a PR with that:

![](http://i.giphy.com/40m8VCOyPsvF6.gif)

@vdemeester: WDYT?

**Comment by vdemeester** [comment]
Ohhh that's kinda bad… :sweat: 

![mario](https://cloud.githubusercontent.com/assets/6508/12444026/8df1e7c2-bf5c-11e5-9c80-bf39c6b87548.gif)
