### ISSUE TITLE
Migrate from docker/engine-api to moby/moby/client

### ISSUE THREAD

**Issue by cirocosta** [containous/traefik#1674]
Hey,

right now the Docker provider uses solely 'engine-api' and one or another library (like 'docker-events'). These libraries, however, are considered deprecated. As I see it'd be nice to update the Docker provider code to rely solely on the official 'github.com/moby/moby/{client,api}'. 

This could be seen as the first step to better support Docker Swarm Mode when it comes to handling cluster events (https://github.com/moby/moby/pull/32421) which just landed (as future features).

Wdyt?

Thanks!

**Comment by timoreimann** [comment]
Yep, that would definitely be nice.

**Comment by ldez** [comment]
Closed by #1823
