### ISSUE TITLE
WebSockets connections sometimes drop in Kubernetes

### ISSUE THREAD

**Issue by indrekj** [containous/traefik#1685]
We’re using Traefik for sticky websocket connections in Kubernetes. Occasionally all Traefik instances drop some percentage of websocket connections. This usually happens once or twice every few days.

**Our setup**:
AWS Application Load Balancer -> Traefik -> Socket Servers
Both Traefik and Socket servers are in Kubernetes.
Traefik version: v1.2.1
Kubernetes version: v1.5.7

**Traefik logs**:
There's a lot of logs like this when connections drop:
```
172.244.67.0 - - [29/May/2017:20:39:47 +0000] "GET /socket.io/ HTTP/1.1" 0 0 "" "Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_1 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) CriOS/58.0.3029.113 Mobile/14E304 Safari/602.1" 16174457 "[server-retracted]" "http://172.244.10.55:3000" 16012ms
```
I guess the status code 0 also shows that the connection dropped. Debug logs don't seem to reveal anything useful.

**WebSocket connections**
Example what happens with active Users (each line represents connections count in one of our socket servers):
![users-drop](https://cloud.githubusercontent.com/assets/3438/26622987/ea0c8fec-45f4-11e7-86f7-2651ae213eeb.png)

We have not been able to reproduce this in non-production environments. This may not even be a Traefik bug.

**Comment by timoreimann** [comment]
@indrekj thanks for the report.

Do you have a chance to try the latest 1.3 release candidate of Traefik? Some improvments have been made in the area of web-sockets.

**Comment by indrekj** [comment]
Will be updating to traefik v1.3 next week. Will let you know soon.

**Comment by indrekj** [comment]
No luck, same problem with v1.3.0.

**Comment by timoreimann** [comment]
@indrekj any chance you could do some pprof profiling on your app and share the results?

**Comment by traefiker** [comment]
I'll close the issue due to inactivity but feel free to re-open if needed.

**Comment by indrekj** [comment]
This problem was not caused by Traefik. Apparently AWS ALB was rebalancing connections when the connection count got high enough which triggered a lot of reconnects.
