### ISSUE TITLE
Marathon directory as a subdomain

### ISSUE THREAD

**Issue by yurinnick** [containous/traefik#169]
Change default frontend Host value from `foobar.marathon.localhost` to `foo.bar.marathon.localhost` for Marathon apps with ID `/foo/bar`.

**Comment by assertrandom** [comment]
This will be a big win for us. We have apps in folders marked dev/test/staging/prod and right now front end looks like prod_xyz.com

**Comment by emilevauge** [comment]
Hi everyone, don't you think it would be even better to reverse the name like in: `/foo/bar/myapp` > `myapp.bar.foo` ?

**Comment by darKoram** [comment]
We use wildcard certs and they only support single depth. So perhaps it could be an option which format you want. The extra depth of subdomains here we'll break our cert usage

**Comment by yurinnick** [comment]
@darKoram maybe you can set `-` as default delimiter, but leave an option to change it.

**Comment by yurinnick** [comment]
@darKoram another solution is using path like `marathon.localhost/foo/bar` for app with `/foo/bar` id. It's not so elegant, but still be better than now.

**Comment by emilevauge** [comment]
OK, I added an optional `groupsAsSubDomains` parameter in PR #426 :)
