### ISSUE TITLE
context does not work with traefik latest/1.2 

### ISSUE THREAD

**Issue by marwan-at-work** [containous/traefik#1691]
### Do you want to request a *feature* or report a *bug*?

bug

### What did you do?
created a simple Go server the listens to the `request.Context.Done()` channel. 
Here's the handler:

```
    http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
        time.Sleep(time.Second * 2)
        ctx := r.Context()
        select {
        case <-ctx.Done():
            fmt.Println("context is done")
            fmt.Fprintln(w, "bye bye")
        default:
            fmt.Fprintln(w, "hi there")
        }
    })
```

### What did you expect to see?
If I `curl` the above server then hit `ctrl+C` in my terminal in less than 2 seconds, I expect the server to log `context is done`. 

### What did you see instead?
Traefik did not send a `context.Done` signal back to the server. I suspect when the frontend connection closes, Traefik doesn't properly close the corresponding connection to the backend. 

Note, that `1.3` fixes this issue : ) 

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
Traefik latest/1.2 - default toml config

**Comment by timoreimann** [comment]
@marwan-at-work so this works as expected with 1.3? In that case, I think it's legitimate to close this issue as we don't really provide support for multiple stable versions of Traefik.

**Comment by marwan-at-work** [comment]
@timoreimann yep! i was advised on the slack channel to open an issue but that's totally fine with me : )

**Comment by timoreimann** [comment]
@marwan-at-work yeah I was the one who advised you. :) Unfortunately, I hadn't realized this was only a 1.2 issue. :(

Sorry for the extra work I've created!
