### ISSUE TITLE
Add support for log file rotation

### ISSUE THREAD

**Issue by rjshep** [containous/traefik#1696]
Traefik can currently write to two log files, the traefik log and an access log.  These log files grow continuously and there is no mechanism for rotating, compressing, or archiving them.

I propose adding functionality for Traefik to handle a SIGUSR1 signal, on receipt of which any (file-backed) logs in use will be closed and opened again.  This will allow tools such as logrotate to be used to manage the logs.

**Comment by juherr** [comment]
I was looking for this feature and it looks logrotate may already work with traefik files: https://github.com/mantl/mantl-packaging/pull/9

**Comment by rjshep** [comment]
There's nothing there to tell Traefik to actually close and reopen the file though.  Without that, even if log rotate moves and compresses the files, Traefik will continue to use the existing file handles to write to the old files.  Unless I'm missing something?

**Comment by emilevauge** [comment]
@rjshep seems like a good idea, but do you if it's possible to handle this easily with logrus ?

**Comment by rjshep** [comment]
@emilevauge Yes we've already implemented this on our fork and it's working fine. Just wanted to check it's something you guys would accept a PR for - sounds like it is?

**Comment by emilevauge** [comment]
Let's go then :)

**Comment by ovizii** [comment]
Would someone please share their logrotate configuration which works with traefik running as a docker container?
