### ISSUE TITLE
[Feature Request] ElasticSearch 5.x compatible logs

### ISSUE THREAD

**Issue by bintut** [containous/traefik#1710]
Hi all,

I am requesting a feature to create the Traefik logs for Filebeat to ship it to (LogStash then) ElasticSearch 5.x if streaming it directly is not possible.

Thank you in advance.

Kind regards,

Marvin

**Comment by timoreimann** [comment]
We'll likely get support for JSON logging in the next version. Might that be enough to have a logstash parser configuration allowing to ingest logs properly into ES 5 (and any other data sink that's able to parse JSON)?

**Comment by ldez** [comment]
Related to #1669

**Comment by bintut** [comment]
Hi @timoreimann,

Yes, JSON is enough. Thanks for the heads up.

Kind regards,


Marvin

**Comment by timoreimann** [comment]
@bintut thanks for the update. Okay for you if you close this issue then and refer to the in-flight PR?

**Comment by bintut** [comment]
Hi @timoreimann,

Yes. Please go ahead. Thanks!

Kind regards,

Marvin

**Comment by timoreimann** [comment]
Thanks, appreciated. :+1:
