### ISSUE TITLE
Provide means to specify traefik toml like config via standard input.

### ISSUE THREAD

**Issue by mrjrieke** [containous/traefik#1711]
There are times where it would be nice to be able to configure traefik without it having to know anything about the local file system.

In this case, it would be nice to be able to configure traefik via toml formatted standard input instead of from a config file.  So, for instance, I could do something like the following:

cat mytraefikconfig.toml | traefik.exe --configFile=<stdin>

-- or --

cat mytraefikconfig.toml | traefik.exe --configStdin

**Comment by mrjrieke** [comment]
It turns out I may not need this, but it seems it would add flexibility to the utility.

**Comment by ldez** [comment]
Could you give a real use case?

**Comment by mrjrieke** [comment]
I found a workaround for the problem I was trying to solve using Traefik, so it turns out I don't really need this feature (or traefik for my particular problem) anymore unless I come across it sometime again in the future.

Having this feature would have helped me although maybe only part way because certificates would have eventually become a problem as well and would have needed those passed via stdio as well.

Feel free to close it unless you think some others might find it useful.

Interesting thing: traefik solved my problem in 2 hours what code took a couple days to solve.  But the code solution in our case ends up working better for us.

**Comment by timoreimann** [comment]
@ldez okay we close? we can reopen or have users file new requests should the need arise again.

**Comment by ldez** [comment]
I'll close this issue, because I think the question is answered, but feel free to continue the conversation.
