### ISSUE TITLE
Allow client certificates to be optional

### ISSUE THREAD

**Issue by samgurtman** [containous/traefik#1715]
Currently (correct me if I'm wrong), you can either enable to disable client certificate verification. In conjunction with the subject name and certificate forwarding soon to be merged, it would be beneficial to allow client certificates to be optional. If a client certificate exists and is valid, forward the subject name in a header, otherwise forward a blank header.

Let me know if this makes sense.

**Comment by emilevauge** [comment]
@samgurtman could you give us a use case ?

**Comment by samgurtman** [comment]
Use case is:
We have some operations that are highly critical and should only be performed from certain devices. These devices are installed with a client certificate. It is then up to the reverse proxy to determine if a given request has come from an authorised device, and if so pass that information on to the back end so an access control decision can be made. However most of the operations are less critical and can be done from any device so they will not present client certificates.

**Comment by emilevauge** [comment]
@samgurtman Not sure it's possible in golang sadly. What tool do you use today that suits these requirements ?

**Comment by samgurtman** [comment]
Nginx and HAProxy both support it.

**Comment by emilevauge** [comment]
My bad, it's totally doable in golang : https://golang.org/pkg/crypto/tls/#ClientAuthType :tada:

**Comment by nmengin** [comment]
This issue seems to be solved by the PR #2306 .
