### ISSUE TITLE
support new config option for consul acl token

### ISSUE THREAD

**Issue by bitsofinfo** [containous/traefik#1717]
Please add support or documentation for the traefik consul backend config to permit a consul ACL token to be specified.

Currently the only way you can do this, is to be aware of the underlying libraries Traefik uses and be have knowledge that those libraries consume an env var "CONSUL_HTTP_TOKEN". 

I only became aware of this via this issue: https://github.com/containous/traefik/issues/767

**Comment by ldez** [comment]
@bitsofinfo Could you create a PR on the documentation with this information?

**Comment by bitsofinfo** [comment]
done

**Comment by bitsofinfo** [comment]
Updated PR w/ requested changes

**Comment by ldez** [comment]
Closed by #1720
