### ISSUE TITLE
Add support for Kubernetes' `ingress.kubernetes.io/rewrite-target`

### ISSUE THREAD

**Issue by mlaccetti** [containous/traefik#1722]
Feature request:

Add support for `ingress.kubernetes.io/rewrite-target` - the ability to strip a path off the frontend URL when passing it to the backend.

I.e. if I request `foo.bar/api/` and I have the following ingress annotation `ingress.kubernetes.io/rewrite-target: /`, I'd expect Traefik to add in a rule for the frontend to replace `/api/` with `/`.

**Comment by kachkaev** [comment]
Should this be closed given that the relevant PR has been merged?

**Comment by timoreimann** [comment]
Yep, I think so. Thanks.

**Comment by kolleroot** [comment]
Hi there, I'm currently testing the rc and I'm not quite sure, that I understand this feature. Does this mean that when requesting /api/v1/some-resource that the url will be rewritten to /v1/some-resource? The behavior, that I observe is, that all urls will be rewritten to /

**Comment by timoreimann** [comment]
@kolleroot The _path_ (not the entire URL) should be rewritten to whatever you have specified in the annotation. Technically, the feature is implemented in terms of the [`ReplacePath` modifier](https://docs.traefik.io/basics/#modifiers).

If you have further questions please don't hesitate to reach out to the Traefik community either on Slack or Stackoverflow. Thank you!
