### ISSUE TITLE
Exempt the /metrics from HTTPS with Authentication

### ISSUE THREAD

**Issue by bintut** [containous/traefik#1725]
Hi all,

I would like to request that if possible, exempt the /metrics from HTTPS with Basic Authentication if it's configured in [web] API.

The /metrics is for exporting internal metrics so that Prometheus can scrape on it. If the TLS certificate was a self-signed certificate, Prometheus will fail to scrape the /metrics from Traefik because it doesn't have an option to ignore for TLS certificate error (or maybe I'm not aware of its existence if it does exist).

Thank you in advance.

Kind regards,

Marvin

**Comment by ldez** [comment]
Please modify the #1560 instead of create a new one.

**Comment by ldez** [comment]
Related to #1560

**Comment by ldez** [comment]
Closed by #2335
