### ISSUE TITLE
Middleware chaining refactor

### ISSUE THREAD

**Issue by ldez** [containous/traefik#1730]
### Do you want to request a *feature* or report a *bug*?

feature (refactor)

### What did you want?

Speaking about Negroni replacement.

From #1391:
@rjshep 
> After digging into this a bit more I'm not sure whether it makes sense to continue with removing Negroni.
>
> I like the fact that removing it allows the use of simple `net/http handlers`. However in order to do that we either need to build of the chain of middlewares from right to left (i.e. starting with the last in the chain) or we go left to right and then need to keep track of the last in the chain and update it each time a new middleware is added.
>
> The former means quite a lot of reordering of code within `server.go`, in order to build the chains right to left and is counter-intuitive.  The latter means we're effectively duplicating what Negroni does at the moment, just in a different way.
>
> If we were to move ahead with removing Negroni then my preference is for the former approach, however I'm not sure that they amount of effort involved is really worth it.  I'd value your thoughts.

 @timoreimann 
> At my workplace, we use https://github.com/justinas/alice to chain regular net/http handlers in a human-friendly manner. It's a very small dependency that does the job well.
> 
> Given that we have a net win of ~400 files being removed (including one dependency), I personally think it's still worth pursuing the effort to remove Negroni. (Admittedly, that's easy for me to say as I'm not the one doing the hard work.)

**Comment by dtomcej** [comment]
This may be a silly question, but what would the benefit be from removing negroni?

**Comment by timoreimann** [comment]
Reduced complexity: We can get rid of one dependency and only have to care about a single type of handler, which also conforms to the standard net/http one.

We would also lose a net of 400-ish lines of code.

**Comment by rjshep** [comment]
I'll look into using [https://github.com/justinas/alice](https://github.com/justinas/alice) and see how straightforward it would to be to replace Negroni.

**Comment by ldez** [comment]
Closed by v2.0
