### ISSUE TITLE
glide.lock outdated, I can't install new dep using ./script/glide.sh get some_repo

### ISSUE THREAD

**Issue by j3r0lin** [containous/traefik#1734]
Current dependencies are outdated, `./script/glide.sh up` was broken for dependencies conflict.

**Comment by ldez** [comment]
Thanks for your interest in Traefik !

`glide.lock` is not outdated, it's sync with the `vendor/`.

The dependencies conflicts that you show when you do `./script/glide.sh up` is normal : some dependencies depends on several same sub dependencies but with different version.

Don't do `./script/glide.sh up`.

**Comment by j3r0lin** [comment]
Then how could I add a new dependency, Manual edit the lock file and run glide install?

**Comment by ldez** [comment]
You should not edit manually the lock file.

For now, you must follow a process: https://github.com/containous/traefik/pull/1332#issuecomment-297569884

I'm thinking about a more simple new process to add a dependency.
A PR coming soon on this subject.

**Comment by j3r0lin** [comment]
😄 a little bit awful. But it does work. Thanks. Maybe you could send a PR to ask glide for this feature.

**Comment by timoreimann** [comment]
@j3r0lin a feature request with glide has long been filed in this regard. Unfortunately, all eyes are on golang/dep these days. :-\
