### ISSUE TITLE
Kubernetes example references Deployment|RS uses DaemonSet

### ISSUE THREAD

**Issue by DazWilkin** [containous/traefik#1764]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Following the Kubernetes Ingress Controller documentation.

The page describes and the in-page YAML show a Deployment with one Replica but
https://github.com/containous/traefik/blob/master/docs/user-guide/kubernetes.md#deploy-træfik-using-a-deployment-object

"We are going to deploy Træfik with a Deployment.."
"...and run more than 1 replica of Træfik for high availability"

The referenced example and command deploys a DaemonSet

https://github.com/containous/traefik/tree/master/examples/k8s/traefik.yaml

### What did you expect to see?

A Deployment called "traefik-ingress-controller"
One pod

### What did you see instead?

A DaemonSet called " traefik-ingress-controller"
One pod/node 

### Recommend

Revise documentation to be consistent with YAMLs

**Comment by timoreimann** [comment]
This is already being handled by #1735.
