### ISSUE TITLE
Kubernetes example inconsistent ingress for cheese websites

### ISSUE THREAD

**Issue by DazWilkin** [containous/traefik#1765]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

In the name-based *and* path-based routing sections:
https://github.com/containous/traefik/blob/master/docs/user-guide/kubernetes.md#name-based-routing
https://github.com/containous/traefik/blob/master/docs/user-guide/kubernetes.md#path-based-routing

The in-page YAMLs include:

`kubernetes.io/ingress.class: traefik`

The referenced YAMLs:
https://github.com/containous/traefik/blob/master/examples/k8s/cheese-ingress.yaml
https://github.com/containous/traefik/blob/master/examples/k8s/cheeses-ingress.yaml

Do not include annotations.

### What did you expect to see?

Consistency.

**Comment by timoreimann** [comment]
I just checked, and it looks like this is covered already by #1735 too.

I'll close the issue, but please don't hesitate to post / reopen again if it turns out that I missed something.

Thanks!
