### ISSUE TITLE
Using Portainer with Traefik

### ISSUE THREAD

**Issue by pascalandy** [containous/traefik#1766]
It's a Bug

### What did you do?

Here is the way to run Portainer without traefik. It's all good. 

```
docker service create \
--name "$CTN_portainer" \
--network "ntw_front" --replicas "1" \
--publish 9000:9000 \
--constraint 'node.role == manager' \
--mount type=bind,src=/var/run/docker.sock,dst=/var/run/docker.sock \
--mount type=bind,src=/localpath/portainer/data,dst=/data \
--reserve-memory "20M" --limit-memory "40M" \
--restart-condition "any" --restart-max-attempts "55" \
--update-delay "5s" --update-parallelism "1" \
portainer/portainer:1.13.2 \
-H unix:///var/run/docker.sock
```

When I run:

```
docker service create \
--name "tool-portainer" \
--network "ntw_front" --replicas "1" \
--mount type=bind,src=/var/run/docker.sock,dst=/var/run/docker.sock \
--mount type=bind,src=/mnt/deployGRP-133/config/portainer/data,dst=/data \
--label "traefik.frontend.rule=Host:nightshift.tk;PathPrefixStrip:/tool-portainer" \
--label "traefik.backend=tool-portainer" \
--label "traefik.port=9000" \
--label "traefik.docker.network=ntw_front" \
--reserve-memory "20M" --limit-memory "40M" \
--restart-condition "any" --restart-max-attempts "55" \
--update-delay "5s" --update-parallelism "1" \
portainer/portainer:1.13.2
```
I can see this (Chrome on the top, FireFox on the bottom):

<img width="840" alt="screen shot 2017-06-16 at 10 43 43 pm" src="https://user-images.githubusercontent.com/6694151/27249580-da5329f4-52e6-11e7-8acf-7eead653b2ca.png">

When I click on Validate, nothing!?!?

In traefik dashboard it looks normal:
- `frontend-Host-nightshift-tk-PathPrefixStrip-tool-portainer`
- `backend-tool-portainer`

But in the logs, `docker service logs -f proxy_traefik` there is NO mention of `tool-portainer`. Now I'm clueless!

### What did you expect to see?

Access Portainer normally. It worked with Traefik:1.2.3

### What did you see instead?
Stocked on the login screen

### Output of `traefik version`: (_What version of Traefik are you using?_)

I use the image containous/traefik:f275e4ad3c0a660aa8170d0f5f709df5a9f7ebf4
I tested it with @dtomcej regarding the redirect bug from http to https.

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

See all my configs, toml, other container at:
https://github.com/pascalandy/docker-stack-this/tree/edge-acme/traefik-manager

Thank you!

**Comment by Duvel** [comment]
I encountered this problem as well. I "solved" it by using an extra forward slash at the end in the browser and didn't look into it any further.

**Comment by pascalandy** [comment]
The PathStrip issue was fixed with version 1.3. I don't think it's related. All my other containers are working normally. It's really about portainer.

**Comment by ajardan** [comment]
Works great for me with 1.3.1, so I would recommend to upgrade traefik and see if it fixes it.

**Comment by ldez** [comment]
I'll close this issue, because I think the question is answered, but feel free to continue the conversation.

**Comment by pascalandy** [comment]
All good @ldez !
