### ISSUE TITLE
Traefik's /ping endpoint should answer to HTTP HEAD

### ISSUE THREAD

**Issue by martinbaillie** [containous/traefik#1767]
It seems common for upstream load balancers/proxies, particularly in the cloud vendor space, to make `HTTP HEAD` requests when performing ping checks on their backends.

Traefik's `/ping` endpoint currently does not answer to anything other than `HTTP GET` which means that endpoint can't be used for pings in a scenario where Traefik is sitting downstream from e.g. a GCE network loadbalancer.

**Comment by timoreimann** [comment]
FWIW, we run Traefik behind a GCE network LB and it's totally happily doing `GET` requests against the `/ping` endpoints. Maybe there are different "flavors" of network load balancer in the Google cloud?

That's not to say we shouldn't be supporting `HEAD`. @emilevauge to review as well.

**Comment by martinbaillie** [comment]
@timoreimann possibly I was imagining things when briefly playing with GCE!

I think a common design pattern for pings anyway. I vaguely recall F5s doing the same from consultancy gigs I've had (again could have been to their individual flavours/setup).
