### ISSUE TITLE
Stop using MD5 for basic auth password hashing

### ISSUE THREAD

**Issue by dbsanfte** [containous/traefik#1778]
MD5 is broken. Stop using it. 

Also, please offer SHA-2, as SHA-1 will be deprecated in the medium term.

**Comment by DanielRuf** [comment]
I would recommend bcrypt, scrypt and so on. Also Sodium / libsodium is great.

**Comment by DanielRuf** [comment]
How could we help here? With a PR?

**Comment by DanielRuf** [comment]
It seems it is already merged.

https://github.com/containous/traefik/blob/bf43149d7e67ee872a85c9c979dd254f1ad59388/docs/configuration/backends/web.md#basic-authentication

https://github.com/containous/traefik/pull/677/files

**Comment by dtomcej** [comment]
As noted above, Traefik now supports MD5, SHA1 and BCrypt as options: (https://docs.traefik.io/configuration/entrypoints/#basic-authentication).

Therefore I will be closing this issue.

If you have any further concerns, please open a new issue.

Thanks!
