### ISSUE TITLE
[support] Match against multiple hosts

### ISSUE THREAD

**Issue by emil-nasso** [containous/traefik#179]
Is there any way to match against multiple different hosts for a frontend?

Here is an example. None of these hosts matches. If i remove on of them, the other matches.

```
[backends.example]
  [backends.example.servers.server1]
  url = "http://127.0.0.1:10082"
 
[frontends.example]
backend = "example"
  [frontends.example.routes.test_1]
  rule="Host"
  value="example.test.se"
  [frontends.example.routes.test_2]
  rule="Host"
  value="example.nu"
```

Looking at the web interface, it looks like it should work.

![https://dl.dropboxusercontent.com/s/adonv8fw5g658t6/2016-01-30%20at%2020.56%202x.png?dl=0](https://dl.dropboxusercontent.com/s/adonv8fw5g658t6/2016-01-30%20at%2020.56%202x.png?dl=0)

But when i open the page in a browser i get a 404.

This can be solved by adding another frontend for the same backend. Would still be interested in how you would do it with one frontend though.

**Comment by emilevauge** [comment]
Hi @emil-nasso, for now, there is a AND operator between rules of a frontend (not a OR).
A workaround to solve your issue is to create multiple frontends for now:

```
[backends.example]
  [backends.example.servers.server1]
  url = "http://127.0.0.1:10082"

[frontends.exampletest]
backend = "example"
  [frontends.exampletest.routes.test]
  rule="Host"
  value="example.test.se"
[frontends.examplenu]
backend = "example"
  [frontends.examplenu.routes.test]
  rule="Host"
  value="example.nu"
```

But, as I said in #116:
> I'm planning to modify the behavior of routes, now there is a AND operation between routes from a frontend, and I think it would be more useful to have a OR. WDYT?

**Comment by emilevauge** [comment]
Duplicate #116

**Comment by emil-nasso** [comment]
@emilevauge Yeah. That sounds great. Maybe a configuration flag on the frontend where you can set "match: all" or "match: any"? Where all is and and any is or. It would be great to be able to tweak it. It could default to "match: all" to not break and backwards compatibility.
