### ISSUE TITLE
Reflect backend state in UI

### ISSUE THREAD

**Issue by jdorothy** [containous/traefik#180]
It would be extremely helpful for monitoring if both the UI and /api endpoint could reflect the status of a backend, e.g. a background color change after a CB triggers.

**Comment by emilevauge** [comment]
Hi @jdorothy, this would be great indeed :) But would require first to add health checks in Traefik.

**Comment by jdorothy** [comment]
I think that for right now, you could simply return whether the CB for that backend is currently triggered.  But I agree, if you take #181 into account then health checks make more sense long-term.

**Comment by ldez** [comment]
Close in favor of  #1783 - Feel free to subscribe there for updates.
