### ISSUE TITLE
failed to create in-cluster configuration after upgrade to v1.3.2

### ISSUE THREAD

**Issue by karlvlam** [containous/traefik#1803]
### Do you want to request a feature or report a bug?
bug
### What did you do?
After upgrade from v1.2.3  to v1.3.2, traefik doesn't route the request to the service, and always return 404 not found.
### What did you expect to see?
the http request will be routed to the service as the old version.

### What did you see instead?
It always return 404 not found.

Output of traefik version: (What version of Traefik are you using?)

The traefik is running in the k8s cluster v1.6.6 as DaemonSet.

### traefik version
```
Version:      v1.3.2
Codename:     raclette
Go version:   go1.8.3
Built:        2017-06-29_04:52:35PM
OS/Arch:      linux/amd64
```

### command to start
```
traefik --debug --web --web.address=:8182 --kubernetes --kubernetes.endpoint=http://my-k8s-api.local:8080
```

### debug log
```shell
time="2017-06-30T03:03:16Z" level=info msg="Traefik version v1.3.2 built on 2017-06-29_04:52:35PM" 
time="2017-06-30T03:03:16Z" level=debug msg="Global configuration loaded {"GraceTimeOut":10000000000,"Debug":true,"CheckNewVersion":true,"AccessLogsFile":"","TraefikLogsFile":"","LogLevel":"DEBUG","EntryPoints":{"http":{"Network":"","Address":":80","TLS":null,"Redirect":null,"Auth":null,"Compress":false}},"Cluster":null,"Constraints":[],"ACME":null,"DefaultEntryPoints":["http"],"ProvidersThrottleDuration":2000000000,"MaxIdleConnsPerHost":200,"IdleTimeout":180000000000,"InsecureSkipVerify":false,"Retry":null,"HealthCheck":{"Interval":30000000000},"Docker":null,"File":null,"Web":{"Address":":8182","CertFile":"","KeyFile":"","ReadOnly":false,"Statistics":null,"Metrics":null,"Path":"","Auth":null},"Marathon":null,"Consul":null,"ConsulCatalog":null,"Etcd":null,"Zookeeper":null,"Boltdb":null,"Kubernetes":{"Watch":true,"Filename":"","Constraints":[],"Endpoint":"http://my-k8s-api.local:8080","Token":"","CertAuthFilePath":"","DisablePassHostHeaders":false,"Namespaces":null,"LabelSelector":""},"Mesos":null,"Eureka":null,"ECS":null,"Rancher":null,"DynamoDB":null}" 
time="2017-06-30T03:03:16Z" level=info msg="Preparing server http &{Network: Address::80 TLS:<nil> Redirect:<nil> Auth:<nil> Compress:false}" 
time="2017-06-30T03:03:16Z" level=info msg="Starting provider *server.WebProvider {"Address":":8182","CertFile":"","KeyFile":"","ReadOnly":false,"Statistics":null,"Metrics":null,"Path":"","Auth":null}" 
time="2017-06-30T03:03:16Z" level=info msg="Starting provider *kubernetes.Provider {"Watch":true,"Filename":"","Constraints":[],"Endpoint":"http://my-k8s-api.local:8080","Token":"","CertAuthFilePath":"","DisablePassHostHeaders":false,"Namespaces":null,"LabelSelector":""}" 
time="2017-06-30T03:03:16Z" level=info msg="Starting server on :80" 
time="2017-06-30T03:03:16Z" level=info msg="Creating in-cluster Provider client with endpoint http://my-k8s-api.local:8080
" 
time="2017-06-30T03:03:16Z" level=error msg="Error starting provider *kubernetes.Provider: failed to create in-cluster configuration: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory" 
```

**Comment by ldez** [comment]
Every time someone does not respect the issue's template, a little bunny dies.

![southpark - estrella kill rabbit](https://user-images.githubusercontent.com/5674651/27143914-3cea7896-5130-11e7-81f8-02d8ac2da7a7.gif)
![southpark - estrella kill rabbit2](https://user-images.githubusercontent.com/5674651/27143924-49104c72-5130-11e7-82ae-ccedbd5dfa1c.gif)

Please edit your issue description to respect the [issue template](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE.md) as more as possible.

**Comment by timoreimann** [comment]
@karlvlam are you trying to run Traefik in-cluster or out-of-cluster?

**Comment by karlvlam** [comment]
@timoreimann sorry for missing the issue template. the traefik is running in the cluster as DaemonSet.

**Comment by timoreimann** [comment]
@karlvlam I cannot reproduce your problem on my GKE cluster.

It looks like your Kubernetes installation does not inject any default service account properly. Can you do `kubectl get pod <one of your Traefik pods> -o yaml` and verify that you get a volume mount associated to a proper service account token? If that's not the case, you should take a look at your admission controller's logs and watch for errors/problems.

Are you absolutely positive that Traefik 1.2 works fine in the same cluster and the same namespace while 1.3 doesn't?

**Comment by karlvlam** [comment]
@timoreimann Yes. Traefik 1.2 works fine in the same cluster. But my cluster setup is a little bit different: I do not use any service account or any authentication in the cluster for internal development. Is it a must requirement for 1.3 ?

**Comment by timoreimann** [comment]
@karlvlam alright, the client setup behavior apparently changed between the two versions. Could you try clearing either the `KUBERNETES_SERVICE_HOST` or `KUBERNETES_SERVICE_PORT` environment variable in your Traefik Pod spec? That should force Traefik to use the out-of-cluster configuration.

**Comment by karlvlam** [comment]
@timoreimann It works, thank you. I set them both to empty string.
