### ISSUE TITLE
Possible for CB to disable server instead of entire backend?

### ISSUE THREAD

**Issue by jdorothy** [containous/traefik#181]
This may be a middleware rather than Traefik issue, but how feasible would it be to apply a backend's 'parent' CB to each of the defined servers as well?  Sometimes a server instance fails for reasons unrelated to the service itself, and if it triggers the CB the whole backend is disabled, which is problematic.  Ideally, only that server is removed from round-robin until it recovers and the service backend remains available.

**Comment by emilevauge** [comment]
Hi @jdorothy, as in #180, this could be made using health checks on backend. Backends which fail to pass the health check would have weights set to zero to inhibit any traffic from being routed into their direction. WDYT?

**Comment by jdorothy** [comment]
I think adding health checks would be great and I'd certainly be interested in using them.  Setting the weight to 0 on failure would be a clean way to take a server out of rotation - I like it!

**Comment by eldondevcg** [comment]
I agree that it would be nice if traefik did proactive health checks. What needs to be done to implement this? Ideally, the health check would be performed prior to attempting to send any traffic to the backend. It seems to me like the only configuration option for a first pass at this feature would be a url at the backend level, and possibly a specific http status that would be expected.

**Comment by klausenbusk** [comment]
@eldondevcg There is a open issue for that: https://github.com/containous/traefik/issues/824 , something like HAProxy httpchk should be enough I think :)

**Comment by traefiker** [comment]
I'll close the issue due to inactivity but feel free to re-open if needed.
