### ISSUE TITLE
Marathon API calls are inefficient

### ISSUE THREAD

**Issue by sgran** [containous/traefik#1846]
Traefik does the following:
Request all applications
Request all tasks
Filter applications returned
Filter tasks returned

Marathon's REST API allows all of this in one call
GET /v2/apps?embed=apps.tasks&label=traefik.tags==mumble

This also makes the marathon server workload smaller, as it doesn't have to return a large body of data to each traefik server.

**Comment by timoreimann** [comment]
I submitted #1815 just a few days before you, and it seems to address this issue.

I'll continue discussing implementation details on your PR.
