### ISSUE TITLE
Add sprig library in FuncMap for traefik templates

### ISSUE THREAD

**Issue by alanbover** [containous/traefik#1848]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you do?

Try to configure traefik with custom template for mesos. On our setup, we need multiple frontend for the same app (tasks in a backend are not only by application but also by another custom field). With current functions in traefik template, this is not possible.

### What did you expect to see?

To have a "minimum" set typical functions for templating

### What did you see instead?

Only 5 "custom" defined functions

### Details

Currently traefik define some default functions for templates:
https://github.com/containous/traefik/blob/a7ec7859944a712e875c3db5e9b4bf5dd370bc23/provider/provider.go#L63-L67

Those functions limits the "logic" that can be implemented when defining custom templates. It would be super useful to include sprig template library into traefik to have more powerfull templating system.
(https://github.com/Masterminds/sprig).

This would mean that, for the current functions:
- "replace" function could be removed from provider.go and use the one provided in sprig library
- "tolower" could be renamed to "lower" and use the function provided in sprig library
- "contains"  function could be removed from provider.go and use the one provided in sprig library

This library is being used by other projects, like for example kubernetes-helm (https://github.com/kubernetes/helm)

I would be happy to open a PR with those changes if you think it's a good idea

**Comment by ldez** [comment]
Every time someone does not respect the issue's template, a little bunny dies.

<details>

![southpark - estrella kill rabbit](https://user-images.githubusercontent.com/5674651/27143914-3cea7896-5130-11e7-81f8-02d8ac2da7a7.gif)
![southpark - estrella kill rabbit2](https://user-images.githubusercontent.com/5674651/27143924-49104c72-5130-11e7-82ae-ccedbd5dfa1c.gif)

</details>

Please edit your issue description to respect the [issue template](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE.md) as more as possible.
