### ISSUE TITLE
Memory leak accessing own traefik instance via frontend rule

### ISSUE THREAD

**Issue by diacu** [containous/traefik#1849]
### Do you want to request a *feature* or report a *bug*?
*bug*

### What did you do?
I started traefik in docker (either with docker or docker-compose). 
    `docker run -d --rm -p 8080:8080 -p 80:80 -v /dev/null:/traefik.toml -v /var/run/docker.sock:/var/run/docker.sock --name traefik traefik --web --docker --docker.domain=docker.localhost --logLevel=DEBUG`

### What did you expect to see?
Admin interface should be accessible via `localhost:8080` or `traefik.docker.localhost`. Accessing traefik interface using automatically set rule for frontend should work:
    `Host:traefik.docker.localhost`

### What did you see instead?
A memory leak starts immediately after accessing http://traefik.docker.localhost:80 and in 10-15 seconds 8GB of RAM is consumed.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.3.3
Codename:     raclette
Go version:   go1.8.3
Built:        2017-07-06_05:32:56PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
- default config for docker

### If applicable, please paste the log output in debug mode (`--debug` switch)
Nothing is displayed during access, but after stopping the request to *http://traefik.docker.localhost:80*, I get many lines like that `time="2017-07-10T14:58:16Z" level=warning msg="Error forwarding to http://172.17.0.2:80, err: context canceled" `. I suppose it has to do with the fact that I stopped the request.

**Comment by dumyan** [comment]
I can confirm this bug on a k8s cluster. There were random 502 errors and the logs reported the same error as OP mentioned. After downgrading to `1.3.2` everything went back to normal.

**Comment by ldez** [comment]
When you call `traefik.docker.localhost` you call `traefik.docker.localhost:80` but  `traefik.docker.localhost:80` is Traefik itself: you create a cyclic call.

If you want to show admin interface you must call `traefik.docker.localhost:8080`.

![dashboard](https://user-images.githubusercontent.com/5674651/28161708-c6d4d466-67c4-11e7-9e03-9152e93ae7c7.png)

**Comment by diacu** [comment]
Yes, I figure it out that it was a cyclic call, but shouldn't this be treated somehow? Accessing it causes a high memory leak.

**Comment by ldez** [comment]
@dumyan the @diacu's problem is present in all Traefik versions, downgrading don't change anything.

**Comment by traefiker** [comment]
I'll close the issue due to inactivity but feel free to re-open if needed.
