### ISSUE TITLE
Add an integration test for the Kubernetes Ingress controller client logic.

### ISSUE THREAD

**Issue by timoreimann** [containous/traefik#1889]
### Do you want to request a *feature* or report a *bug*?
feature.

### What did you do?
Make the already very awesome Traefik Ingress controller client implementation even more awesome.

### What did you expect to see?
My change being covered by an integration test proving the next level in awesomeness achieved.

### What did you see instead?
Being on my own with just unit tests, but nothing that tests the actual client.

### Details
While we have fairly decent unit test coverage to validate our Ingress controller business logic, we are lacking integration tests for the client part (i.e., everything related to creating a client, but most importantly the functionality setting up the Informer). Unit-testing this part doesn't really make sense IMHO since the logic is highly dependent on interactions with an actual k8s API server.

I've done a bit of research how to best set up a Kubernetes system/cluster suitable for integration testing purposes (but not much more). There seem to be two viable options:

1. Use the [test apiserver](https://github.com/kubernetes/kubernetes/tree/6fdf0e4157c76eeaf7619e8411ee7231305f7d87/cmd/kube-apiserver/app/testing). The nice thing is that it runs all in-process and comes with its own etcd testing copy. Note that 1.7 doesn't come with the test apiserver yet, but something similar exists in [test/integration/framework](https://github.com/kubernetes/kubernetes/tree/release-1.7/test/integration/framework). Back-porting the test apiserver to 1.7 should also be fairly trivial.
1. Use [Mirantis's kubeadm-dind-cluster](https://github.com/Mirantis/kubeadm-dind-cluster), which brings a full cluster that only needs Docker.

AFAICS, the test apiserver would make for a more light-weight approach but might require a bit of preparation (e.g., creating a Docker image for the k8s release we're targeting). The dind approach is presumably simpler to integrate into our pre-existing docker-compose-based infrastructure but gives us things we don't really need; for instance, a multi-node setup is not strictly required to test the Informer.

**Comment by timoreimann** [comment]
Kudos to @luxas and @sttts for providing consultancy on the different integration testing options. 🎉

**Comment by luxas** [comment]
What about doing both the e2e (full cluster with `n` dind nodes and everything set up) that deploys a CI image with the recommended k8s YAML file + some test deployments etc. _and_ the more lightweight integration test that tests parts of the code (do we use this informer correctly here etc.)?

**Comment by timoreimann** [comment]
@luxas thanks for chiming in. Executing both e2e and simpler (Informer) integration tests could be valuable, especially if we start having multiple cases where we can test more rapidly with the light-weight approach. I can imagine a proper fix for #1784 to justify such a cause.

For now, I think we should start of with something that covers some good amount of basic integration testing ground since we really have nothing at the moment.

**Comment by luxas** [comment]
@timoreimann Sounds good to me

**Comment by timoreimann** [comment]
The test apiserver approach turned out to be more complex than I thought: While backporting the server to the 1.7 branch worked flawlessly, we now have to carve out a library of a specific part of Kubernetes that's responsible for the testing. Even if we managed to do that (which sounds tricky), it'd probably lead us to vendoring woes, partly because the version of client-go used by Kubernetes 1.7 doesn't have to be one Traefik uses. That's some undesirable level of coupling and would likely make it impossible to test against multiple versions of Kubernetes.

This makes the dind approach look more promising for now.

**Comment by timoreimann** [comment]
So I took a stab at bootstrapping kubeadm-dind-cluster within our test container. Unfortunately, I'm running into a problem -- access to the Kubernetes cluster is apparently not working.

`bash -x` output:

```bash
* Deploying k8s dashboard 
+ kubectl create -f https://rawgit.com/kubernetes/dashboard/bfab10151f012d1acc5dfb1979f3172e2400aa3c/src/deploy/kubernetes-dashboard.yaml
The connection to the server localhost:8080 was refused - did you specify the right host or port?
+ dind::cleanup
+ '[' 0 -gt 0 ']'
```

Strangely, when I `docker exec` into the container, `kubectl create` works just fine.

I also have no problems when I fire up kubeadm-dind-cluster directly on my host machine, so I'm guessing the problem is related to the fact that we are trying to executing Docker inside Docker (which is notoriously difficult but does work for our Marathon integration tests).

The setup script isn't for the faint of heart -- I'll have to dig deeper and/or file an upstream issue.

**Comment by luxas** [comment]
cc @ivan4th

**Comment by ivan4th** [comment]
@timoreimann do you use k-d-c against a remote docker engine? In this case, you need to forward apiserver port (8080 by default) from localhost to the machine that runs docker daemon.

**Comment by timoreimann** [comment]
@ivan4th it might be a bit more complicated with this project: for Traefik, we run all tests inside a test(-runner) container. (The goal is to not require developers to install all dependencies but keep everything inside the test container.)

Trying to adapt your suggestion to our environment, does that mean we'd need to forward port 8080 from the test container to the host machine? (Is that even possible? 🤔)

(/cc @vdemeester for some backup Docker expertise.)

**Comment by ivan4th** [comment]
@timoreimann well, there's always an option to use socat to forward ports over docker, see e.g. [this script](https://github.com/Mirantis/virtlet/blob/master/build/portforward.sh) which we use to run DIND for Virtlet testing in CircleCI (see [CircleCI config](https://github.com/Mirantis/virtlet/blob/master/.circleci/config.yml#L42) -- we're currently moving from Travis to CircleCI there, currently using both) CircleCI runs your builds in a container and uses remote docker engine, so that's rather complicated situation. Do you have an option to run build container with `--net=host` in your case? In this case, maybe you can use something simpler than aforementioned socat hack.

**Comment by timoreimann** [comment]
So here's a summary on what I figured is making things difficult for us:

- We run our test container with the host Docker daemon socket bind-mounted in (i.e., what's often considered "the easy way to get dind").
- k-d-c publishes port 8080. AFAIU, the port will get exposed on the daemon's host due to the socket bind mount. Effectively, this means that inside our test container, `localhost:8080` is not bound to anything.

@ivan4th theoretically, I guess we could use host networking. Practically, it might be harder to do because our current test setup assumes that all integration tests are executed with similar setups (i.e., always bind-mount the Docker daemon socket, and always use bridging with each system we integration-test using docker-compose). Also, host networking isn't properly supported in Docker for Mac, so Mac developers couldn't execute the k8s tests locally.

I see a few options to get this to work:

1. Try the socat approach you mentioned (although the sample usage you linked to for Circle CI seems to require host networking too).
1. Figure out the host end of the Docker interface and tell the k-d-c bash script to use that one when talking to the API server. To my understanding, this requires extending the bash script as it's currently hard-wired to connecting to `127.0.0.1`.
1. Make our test container connect to k-d-c's custom network (`kubeadm-dind-net`) and also tell the script to talk to `kube-master` (the name of the k-d-c container). This seems slightly better than the previous solution (as we don't need to fiddle with IP addresses), but comes with the caveat that the custom network isn't created before the k-d-c script has at least run once; and the script does not seem to support preparing just the basic environment (i.e., without also trying to deploy the dashboard). Maybe we could extend it in this regard as well?

None of the options seems overly elegant, so I wonder what the least worse pick is. Chances are though that I missed something.

Happy to hear your thoughts. I really appreciate your help on this! 🎉

**Comment by ivan4th** [comment]
@timoreimann I think I'll extend the script to support 2 and 3. Basically 3 you can use right now, the code that sets up the docker network is [this](https://github.com/Mirantis/kubeadm-dind-cluster/blob/d85c415ed9f2689bacb668ff31729cd67a065b14/dind-cluster.sh#L361) `DIND_SUBNET` here being `10.192.0.0` (it should really use CIDR notation like `10.192.0.0/16` but I was a bit lazy...). So you can just use `docker network create` before starting the script and it will use the network you created. Problem is that this is not documented, so perhaps I really should add a command to prepare environment.

**Comment by timoreimann** [comment]
@ivan4th great, sounds good to me!

Let me know if I can help somehow -- I'd be happy to file a tracking issue or maybe even take a stab and implementing 2/3 (though I'm currently running somewhat short on bandwidth, so it may take a while before I can get to it).

**Comment by timoreimann** [comment]
FWIW, here's a project showing how to use minikube on Travis: https://github.com/LiliC/travis-minikube.

**Comment by timoreimann** [comment]
Quick update: been working on this once again over the last few days. Running the test locally works, issues on Semaphore CI still remaining.

WIP branch at https://github.com/timoreimann/traefik/tree/k8s-add-integration-test

**Comment by timoreimann** [comment]
Over the past few months, I have continued to work on an approach on and off that allows to spin up a minikube-powered setup suitable for both local testing and the CI environment. (It actually uses VirtualBox on my Mac and minikube's `none` driver on Semaphore CI.) While it has come a long way, my branch is still not complete. Moreover, the implementation is far from trivial.

At this point, I believe it's best to focus on unit/integration tests based on client-go's fake helper first. This should cover a fair ground, even though we'll still need a means to run end-to-end tests (in particular, to verify our example manifests, which my branch currently tries to achieve).

**Comment by dtomcej** [comment]
With the advent of k3s, this is now possible.

The Traefik v2 release has integration tests via k3s for both the ingress and ingressRoute providers.

For this reason, I will be closing this issue.
