### ISSUE TITLE
Configure error log

### ISSUE THREAD

**Issue by BirgerK** [containous/traefik#1902]
### Do you want to request a *feature* or report a *bug*?
FEATURE

### What did you do?
I'm trying to secure my traefik-server by fail2ban. For that fail2ban needs access to the nginx `error.log`. But there's no option for traefik to configure where to store the error.log file

### What did you expect to see?
A config param like `accessLogsFile`for configuring where to store the error.log.

### What did you see instead?
No config param for this.

**Comment by ldez** [comment]
Closed in favor of the #2875
