### ISSUE TITLE
cannot change listen http port via commandline?

### ISSUE THREAD

**Issue by jeroenjacobs1205** [containous/traefik#1918]
Am I correct that it is impossible to change the listen port for incoming web requests, and it always binds on port 80?

I don't want to create a config file just to change the listen port for web requests. It's even more weird that you do specify a commandline parameter to change the port for the web-admin interface (--web.address), but not for the actual web port itself...

I don't see any parameter in `traefik --help` that always me to complete this simple straightforward task...

I'm want to run traefik as a k8s ingress controller, as a daemonset using host networking, but I need to specify another port.

**Comment by timoreimann** [comment]
You can specify the listening port along the `--entryPoints` parameter. For instance,

```
--entryPoints='Name:http Address::8080'
```

will cause Traefik to listen on port 8080 for HTTP traffic.

If you have further or other user-related question, please use either our Slack channel or StackOverflow. We try to limit the usage of Github issues for feature requests and bug reports. Thank you!
