### ISSUE TITLE
Traefik frontend and backend blinking when creating new service on Rancher stack

### ISSUE THREAD

**Issue by VP2405** [containous/traefik#1919]
### What did you do?

I'm working with Rancher v1.5.3. I have two hosts with docker 17.03.1-ce.
I've created a global service with Traefik (v1.2.3) as explained[ here](http://rancher.com/traefik-active-load-balancer-on-rancher/); so on both hosts, `traefik_lb` is set to true.
I've created a new stack, named `app`, and on it I'm adding some services, with custom images based on Node.JS. 

### What did you expect to see?
I expect that the service will be available at `service_name.stack_name.domain` 

### What did you see instead?

Sometimes it happens that when I add a service to the stack, on Traefik dashboard that service frontend or backend starts appearing and disappearing, and I can't reach the service at `service_name.stack_name.domain` (which is the rule given by Traefik).
From the host, I can reach the container and check the service is effectively running.

It happens that after some time (the last time, after a whole night) the service stops blinking and I can reach it at the frontend rule, without changing anything in the configuration (magic?)

Besides, if I create simple containers with the same images instead of services on stacks, I can use the applications reaching them at `rancher_host_ip:container_port`.

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Every service has:
- health check on port used by the service
- labels:
  - `traefik.port` = port used by service
  - `traefik.domain` = mydomain
  - `traefik.enable `= true

Where is the problem?

**Comment by dtomcej** [comment]
@VP2405 Version 1.2 is quite old now, and there have been literally hundreds of improvements since its release.

Can you update to a newer version (perhaps 1.3.5) and see if your issue is still present?

**Comment by traefiker** [comment]
I'll close the issue due to inactivity but feel free to re-open if needed.
