### ISSUE TITLE
Docker usersFile option

### ISSUE THREAD

**Issue by dimitrov-adrian** [containous/traefik#1920]
### Do you want to request a *feature* or report a *bug*?
feature

### What did you do?
Using traefik to route between apps for users and admins, so in general some of them should be public and the others - not.
Additionally the traefik ui is hidden behind subdomain like `traefik.<docker compose group>.<domain>` and the auth does not works as it's only for the port usage.

### What did you expect to see?
Having option like `traefik.frontend.auth.usersFile=/path/to/.htpasswd` as it will make sharing of users and password between given containers possible and ease. It will be good if this file is watched so changes will take affect.

### What did you see instead?
Copy traefik.frontend.auth.basic configuration to containers, if need to add new user then recreate the container.

### Output of `traefik version`: (_What version of Traefik are you using?_)
v1.3.5

**Comment by ldez** [comment]
Every time someone does not respect the issue's template, a little bunny dies.

<details>

![southpark - estrella kill rabbit](https://user-images.githubusercontent.com/5674651/27143914-3cea7896-5130-11e7-81f8-02d8ac2da7a7.gif)
![southpark - estrella kill rabbit2](https://user-images.githubusercontent.com/5674651/27143924-49104c72-5130-11e7-82ae-ccedbd5dfa1c.gif)
</details>

Please edit your issue description to respect the [issue template](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE.md) as more as possible.

**Comment by emilevauge** [comment]
Hi @dimitrov-adrian, I'm sorry, but we don't plan to implement this in the near future. We prefer to invest more time in the [new forward auth mechanism](http://docs.traefik.io/configuration/entrypoints/#forward-authentication) in 1.4 :)
Closing this one for now.
