### ISSUE TITLE
when responding with gzip compression traefik converts HTTP 201 to 200 v1.3.5

### ISSUE THREAD

**Issue by gamykla** [containous/traefik#1937]
BUG v1.3.5

### What did you do?
POSTED to traefik, traefik proxied request to my backend which responded with a 201.
Traefik then responded to my client with a 200

### What did you expect to see?
HTTP 201 response

### What did you see instead?
HTTP 200

### Output of `traefik version`: (_What version of Traefik are you using?_)

v1.3.5

[wtf.zip](https://github.com/containous/traefik/files/1215365/wtf.zip)

to reproduce:
1) build dockerfile
2) update k8s.yaml to use your docker image
3) deploy k8s.yaml -> kubectl create -f k8s.yaml
4) update test.py to point to the ingress
5) send request.
notice the response is a 200 not a 201

special notes:
* this seems to be a problem specific to gzip compression. I noticed this problem by trying to front core-os clair with traefik.. to reproduce the problem i created a dummy python flask service that behaves like clair, and with this i was able to reproduce the problem

**Comment by kevinjqiu** [comment]
Tested with different versions of Traefik. Seems the bug was introduced since v1.3.4. It might be related to the fix for the [double-compression issue](https://github.com/containous/traefik/issues/1851).

**Comment by ldez** [comment]
@kevinjqiu yes and I have already fixed this bug 😃

**Comment by gamykla** [comment]
Thanks @ldez  that's excellent turnaround :D
