### ISSUE TITLE
Traefik is chunking HTTP responses

### ISSUE THREAD

**Issue by Nicnl** [containous/traefik#1940]
### What did you do?
I was given the task to connect very old hardware (running poorly-written C) to a modern web server.
This poorly-written C absolutely can't handle `Transfer-Encoding: chunked`.

I have a backend apache server, hosting some XML files :
```
root@b31eb54d791b:/var/www/html# nc 127.0.0.1 80
GET /download/file.xml HTTP/1.1
Host: 127.0.0.1

HTTP/1.1 200 OK
Date: Fri, 11 Aug 2017 09:16:45 GMT
Server: Apache/2.4.10 (Debian)
Last-Modified: Fri, 11 Aug 2017 09:12:31 GMT
ETag: "138c-55676b67c6019"
Accept-Ranges: bytes
Content-Length: 5004
Vary: Accept-Encoding
Content-Type: application/xml

<?xml version="1.0" encoding="iso-8859-1" ?>
[...]
```

I have a front traefik :
```
nicnl@desktop-dev:~/Projects/Server$ nc 127.0.0.1 80
GET /download/file.xml HTTP/1.1
Host: 192.168.60.138

HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Type: application/xml
Date: Fri, 11 Aug 2017 09:15:05 GMT
Etag: "138c-55676b67c6019-gzip"
Last-Modified: Fri, 11 Aug 2017 09:12:31 GMT
Server: Apache/2.4.10 (Debian) PHP/5.4.45
Vary: Accept-Encoding
Transfer-Encoding: chunked

138c
<?xml version="1.0" encoding="iso-8859-1" ?>
[...]
```

As you can see, Traefik is chunking the response even if the backend server isn't.  
Since the very old hardware I'm forced to work with is not _(and will not be)_ able to deal with chunked responses, I must find a way to force traefik to do a proper `Content-length` response.

### Output of `traefik version`:
```
Version:      v1.3.5
Codename:     raclette
Go version:   go1.8.3
Built:        2017-08-01_04:18:59PM
OS/Arch:      linux/amd64
```

**Comment by ldez** [comment]
Thanks for your interest in Traefik !

It's not possible to set a  `Content-length` when the response is chunked https://developer.mozilla.org/fr/docs/Web/HTTP/Headers/Transfer-Encoding.
Need more investigation but the `Transfer-Encoding` seems to be set by oxy.

You can come to the [Traefik community Slack channel](https://traefik.herokuapp.com) to see if someone have the same problem.

**Comment by Nicnl** [comment]
Thank you for your response!

I know that you can't set both a `Content-length` and `Transfer-Encoding` to `chunked`, since the latter is made to send arbitrary sized blocks of data.

Because the chunked transfer encoding was implemented with `HTTP/1.1`, performing the same request to Traefik with `HTTP/1.0` forces it to respond with `Content-length`.  
Sadly, I have no way to modify the software of the legacy hardware I'm working with.  
It shouldn't be performing `HTTP/1.1` requests if it's unable to parse them correctly, but whatever...

I still wonder why Traefik responds in chunked mode when the backend server responds with a fixed content size...

I never heard of Oxy before. I've been reading their docs, maybe it's linked to this?  
http://godoc.org/github.com/vulcand/oxy/stream

**Comment by fbuecklers** [comment]
Hi,
I think I found the issue which causes this behavior. Traffic seems to request the resource with gzip and then unpack the response before sending it back to the client. That's why the content becomes chuncked encoded.
This behavior is really ugly since proxy caches may cache content with a wrong ETag. This is very dangerous. Read more about it here: https://bz.apache.org/bugzilla/show_bug.cgi?id=39727
The problem seems not to occur if Accept-Encoding: plain is explicit send by the client.
I think the correct behavior here is that traefik must request content with plain encoding if the client does not send any Accept-Encoding Header.

**Comment by traefiker** [comment]
I'll close the issue due to inactivity but feel free to re-open if needed.
