### ISSUE TITLE
Document access log fields

### ISSUE THREAD

**Issue by timoreimann** [containous/traefik#1947]
We need to document the fields of the access log.

Here's the summary I put together for Slack:

```
<remote IP address> - <client user name (if available> [<timestamp>] "<request method> <request path> <request protocol>" <origin server HTTP status> <origin server content size> <request referrer> <user agent> <number of requests received since Traefik started> <Traefik frontend name> <Traefik backend URL> <request duration in ms>
```

**Comment by alastairs** [comment]
As mentioned on Slack, I'm happy to put together the docs for this. I'd appreciate some guidance on where to put the documentation, as it doesn't seem to fit any of the existing sections or concepts described so far.

**Comment by ldez** [comment]
@alastairs I think you can add the documentation here: https://github.com/containous/traefik/blob/master/docs/basics.md

**Comment by dtomcej** [comment]
We now have a list of access log fields, and how to configure them: (https://docs.traefik.io/configuration/logs/#list-of-all-available-fields)

Due to this, I will be closing this issue.

If you have any further concerns, please feel free to open a new issue.

Thanks!

**Comment by alcohol** [comment]
I still believe this could use more documentation. For example, it is unclear to me what the difference between Downstream and Origin is. I cannot find any related documentation.
