### ISSUE TITLE
Update Frontend Matchers configuration documentation

### ISSUE THREAD

**Issue by aantono** [containous/traefik#1979]
Current documentation for [Frontend Matchers](https://docs.traefik.io/basics/#frontends) states that:

> Separate multiple rule values by `,` (comma) in order to enable ANY semantics (i.e., forward a request if any rule matches). Does not work for `Headers` and `HeadersRegexp`.

Looking at the code, there is nothing to indicate that this is indeed the case.  Can someone from the maintainers verify that this is indeed how it currently function (should function) and update the documentation if it's in error?

**Comment by ldez** [comment]
That works.

https://github.com/containous/traefik/blob/5313922bb73e059fb9146f0be06108a9db0c3b36/server/rules.go#L178-L180
