### ISSUE TITLE
Websocket proxy drops headers

### ISSUE THREAD

**Issue by mikejihbe** [containous/traefik#198]
Shouldn't a well-behaved proxy keep headers intact by default?

https://github.com/emilevauge/traefik/blob/5ee6981410252067b77282e7bc8669b24d16fde9/middlewares/websocketproxy.go#L96

**Comment by emilevauge** [comment]
Hi @mikejihbe, indeed, I should reuse the same behaviour.

**Comment by emilevauge** [comment]
Fixed by #256
