### ISSUE TITLE
Doc: Missing a list of labels

### ISSUE THREAD

**Issue by jmaitrehenry** [containous/traefik#1985]
### Do you want to request a *feature* or report a *bug*?
Documentation improvment

### What did you expect to see?

A simple list of available label we can use split by type (frontend, backend)

### What did you see instead?

Nothing or I miss it

### More information
I try to implement traefik in swarm mode without using a static configuration file. The documentation is incomplete when you try to not use the toml configuration file and having a quick list of available labels would be useful.

I can create a new user guide as a starting point.

**Comment by tboerger** [comment]
And the list of labels available at http://docs.traefik.io/toml/#docker-backend are not enough?

**Comment by jmaitrehenry** [comment]
Hum... didn't see it, yeah it's enough.

Envoyé de mon iPhone

**Comment by tboerger** [comment]
> Hum... didn't see it, yeah it's enough.

Than I think this issue can be closed :P

**Comment by jmaitrehenry** [comment]
I reformat this part of the doc for having a more readable list of labels, what do you think?
https://github.com/containous/traefik/pull/1993
