### ISSUE TITLE
Where is the certificate script/ca-certificates.crt originally from?

### ISSUE THREAD

**Issue by rumyantseva** [containous/traefik#1988]
Hello,

I noticed what `Dockerfile` contains this string:

`COPY script/ca-certificates.crt /etc/ssl/certs/`

I understand that it is a necessary thing to deal with external `https://` requests from the container.

But where is the certificate `script/ca-certificates.crt` originally from?

I was trying this command to find some information about the certificate:
`openssl x509 -in ./script/ca-certificates.crt -text -noout`

And this is the result:

```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 93214 (0x16c1e)
        Signature Algorithm: sha1WithRSAEncryption
        Issuer: C=AT, O=A-Trust Ges. f. Sicherheitssysteme im elektr. Datenverkehr GmbH, OU=A-Trust-nQual-03, CN=A-Trust-nQual-03
        Validity
            Not Before: Aug 17 22:00:00 2005 GMT
            Not After : Aug 17 22:00:00 2015 GMT
        Subject: C=AT, O=A-Trust Ges. f. Sicherheitssysteme im elektr. Datenverkehr GmbH, OU=A-Trust-nQual-03, CN=A-Trust-nQual-03
...
```

Looks like this certificate is not valid after Aug 17, 2015. And also the issuer is not obvious. 
Could you please answer, why is it possible to use this certificate?

Thank you very much.

**Comment by emilevauge** [comment]
@rumyantseva You can have a look at this repo to understand how is built the official Docker image: https://github.com/containous/traefik-library-image
The certs come from an alpine distribution.

**Comment by rumyantseva** [comment]
Thank you! 👍
