### ISSUE TITLE
Websocket proxy hides HTTP status code

### ISSUE THREAD

**Issue by benschumacher** [containous/traefik#199]
HTTP status code are hidden when proxying websockets.

The code at https://github.com/emilevauge/traefik/blob/master/middlewares/websocketproxy.go#L142 converts **all errors** into 502 Bad Gateway, including any HTTP 400 errors (403, 404, etc.).

**Comment by emilevauge** [comment]
Hi @benschumacher, thanks for reporting this, I will refactor websockets in coming weeks.

**Comment by emilevauge** [comment]
Fixed by #256
