### ISSUE TITLE
bind password

### ISSUE THREAD

**Issue by navinSing** [containous/traefik#201]
something like http-request auth  inhttp-request auth  haproxy... while accessing the port .. an alert with user:pass defined in config can be used to check.. 

something like : http://serverfault.com/questions/239749/possible-to-add-basic-http-access-authentication-via-haproxy

this one looks small to me,, should be a quick one ,, can be added at frontends or backends like `auth user pass`

**Comment by emilevauge** [comment]
You mean basic auth?
https://github.com/containous/traefik/issues/77
