### ISSUE TITLE
Add documentation for Error Pages on various configurations

### ISSUE THREAD

**Issue by kcrawley** [containous/traefik#2035]
Feature / Documentation Request:

Error pages documentation only covers usage for file based configuration, see: https://docs.traefik.io/basics/#custom-error-pages

Documentation should either specify that other configurations are incompatible with the error pages middleware or examples should be provided for aforementioned configurations. Re: docker, swarm, etcd, etc.

Related to #1675

**Comment by ReidWeb** [comment]
> Documentation should either specify that other configurations are incompatible with the error pages middleware or examples should be provided for aforementioned configurations. Re: docker, swarm, etcd, etc.

Which configurations are incompatible with the error pages middleware?

**Comment by kcrawley** [comment]
@ReidWeb i wouldn't know, there are no documented examples for anything other than the file provider.

**Comment by 0xbaadf00d** [comment]
By example: How to enable the same error pages for all available backends ?  In microservice environment  its seems """idiot""" to have to set error pages per backend rather than globally.

**Comment by timoreimann** [comment]
To my knowledge, error pages do not play together directly with dynamic providers such as Docker. (@bparli, please correct me if I'm wrong from the perspective of your PR.)

A possible workaround is to [customize the template for a particular provider](https://github.com/containous/traefik/tree/d54417acfe2be53021c60576e645964dc2d3a236/templates), apply whatever Go template logic seems necessary to incorporate error handlers, and reference the customized template in the Traefik configuration. The downside is that this won't be fully dynamic.

Feel free to file additional feature request to ask for functionality expansion.

**Comment by kachkaev** [comment]
I'm using k8s and i'd be interested in seeing some statement about custom error pages in the docs for my provider. After digging through the repo I conclude there are not supported yet, but newcomers could be given an easier path to figure that out.

A link to some umbrella issue with tick boxes would be ideal (one can subscribe and be notified about a PR or a long-awaited change in a new release).

**Comment by timoreimann** [comment]
I think it'd be good to use this issue in order to track leaving a general remark on the current restrictions of error pages.

An alternative path to trying to control error pages from various providers via labels might be to only extend error pages so much that the information about which frontend / backend failed is forwarded to the error-handling container. That way, it'd be totally up to the handler implementation to return per-service error pages.
This needs to be discussed separately though, likely on a feature request issue.

**Comment by bparli** [comment]
Thats right @timoreimann .  The error pages could be configured today with the File or Etcd providers (although I haven't tested Etcd much) for example, but I suspect most of the remaining providers would need to be extended to support the [ErrorPage type](https://github.com/containous/traefik/blob/master/types/types.go#L65).

**Comment by timoreimann** [comment]
Thanks @bparli, appreciate the prompt response.

**Comment by timoreimann** [comment]
@bparli when you say etcd, does that actually include every K/V store supported by Traefik?

**Comment by bparli** [comment]
I'm thinking so @timoreimann but am hesitant to say with certainty since I haven't tested them

**Comment by timoreimann** [comment]
Fair enough. I'm not super familiar with the K/V integrations either, so I'll resort to the other maintainers.

Thanks again!

**Comment by timoreimann** [comment]
PR is out. ^

**Comment by ldez** [comment]
Closed by #2104
