### ISSUE TITLE
Build Error after adding a dependent library

### ISSUE THREAD

**Issue by adityacs** [containous/traefik#2046]
I am trying to add the following dependency
`./script/glide.sh get github.com/go-kit/kit/metrics/generic`

glide run is successfull. When I try to build, I get the following error
```
go build ./cmd/traefik
# github.com/containous/traefik/vendor/github.com/xenolf/lego/providers/dns/azure
vendor/github.com/xenolf/lego/providers/dns/azure/azure.go:137:79: undefined: azure.ServicePrincipalToken
vendor/github.com/xenolf/lego/providers/dns/azure/azure.go:138:39: azure.PublicCloud.OAuthConfigForTenant undefined (type azure.Environment has no field or method OAuthConfigForTenant)
vendor/github.com/xenolf/lego/providers/dns/azure/azure.go:142:9: undefined: azure.NewServicePrincipalToken
```

How to resolve this?

**Comment by ldez** [comment]
Thanks for your interest in Traefik !

Every question in the issues means features less 😉.

The issue tracker is for reporting bugs and feature requests only.

Go to  the [Traefik community Slack channel](https://traefik.herokuapp.com) channel #dev
