### ISSUE TITLE
Access log not working

### ISSUE THREAD

**Issue by 0xbaadf00d** [containous/traefik#2070]
### Do you want to request a *feature* or report a *bug*?

Report a bug

### What did you do?

I try to get all http queries log on the console.

### What did you expect to see?

See all http requests on the console (stdout)

2017-08-25T13:43:23 127.0.0.1 GET xxxxxxxxxxx  404
2017-08-25T13:43:24 127.0.0.1 GET xxxxxxxxxxx  404
2017-08-25T13:43:25 127.0.0.1 GET xxxxxxxxxxx  404

### What did you see instead?

See nothing - no output

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.3.7
Codename:     raclette
Go version:   go1.8.3
Built:        2017-08-25_08:36:23PM
OS/Arch:      darwin/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[entryPoints]
  [entryPoints.http]
  address = ":8080"

[accessLog]
```

**Comment by ldez** [comment]
This options is a 1.4 feature:

before 1.4.0-rc1 (1.3)
```toml
accessLogsFile = "log/access.log"
```

since 1.4.0-rc1
```
[accessLog]
```
