### ISSUE TITLE
The word "official" is used twice in a row in traefik's README.md

### ISSUE THREAD

**Issue by f4f09d107e** [containous/traefik#2097]
![chrome_2017-09-10_19-32-06](https://user-images.githubusercontent.com/31597066/30251383-d1926e90-965e-11e7-9a77-9e7c821b397b.png)

**Comment by f4f09d107e** [comment]
I just noticed that the same issue is present on traefik's home page https://traefik.io/.

![chrome_2017-09-10_22-13-05](https://user-images.githubusercontent.com/31597066/30252583-4c83fb4e-9675-11e7-80ea-1c0a391a358b.png)

**Comment by traefiker** [comment]
Closed by #2095.
