### ISSUE TITLE
bad gateway during rolling service deployment using the Marathon backend

### ISSUE THREAD

**Issue by tayzlor** [containous/traefik#210]
I've noticed that when you do a rolling update of a service via marathon if you constantly hit traefik on service backend it will occassionally throw out bad gateway errors. Seems as if traefik is still holding 'stale' instances in the load balancer when marathon has already destroyed them. 

Wondering if this is perhaps an ordering issue, or if traefik is not responding the correct event via the marathon event stream. Unfortunately the docs on marathon events are pretty thin on the ground. It seems like this is happening 

- deployment initiated in marathon
- marathon removes old instance
- marathon sends event saying it removed an instance 
- traefik removes backend

whereas  the following would avoid 'stale' instances  - 
- deployment initiated
- marathon sends event saying its going to remove backend
- traefik removes backend instance
- marathon removes old instance

this is just a theory any insight would be appreciated or any way to circumvent the bad gateway issue.
This follows a similar design to what is proposed in https://github.com/mesosphere/marathon/blob/2f3c8a72a2302f3b173a47c1d5a71ec7c6f1dfda/docs/docs/deployment-design-doc.md so may be that some work is required on the marathon side to implement these features

**Comment by iamruinous** [comment]
Having similar issues with etcd

**Comment by emilevauge** [comment]
Hi @tayzlor 
We need to investigate on that.
If you could provide traefik DEBUG logs during the issue, that would help a lot :)

**Comment by tayzlor** [comment]
Here's a log 


time="2016-02-25T12:38:58Z" level=debug msg="Creating frontend frontend-nodejs"
time="2016-02-25T12:38:58Z" level=debug msg="Wiring frontend frontend-nodejs to entryPoint http"
time="2016-02-25T12:38:58Z" level=debug msg="Creating route route-host-nodejs Host:nodejs.apollo.example.com"
time="2016-02-25T12:38:58Z" level=debug msg="Creating backend backendnodejs"
time="2016-02-25T12:38:58Z" level=debug msg="Creating load-balancer wrr"
time="2016-02-25T12:38:58Z" level=debug msg="Creating server server-nodejs-ba80dd44-dbbc-11e5-9b11-ae012201fe0c at http://52.50.45.40:31793 with weight 0"
time="2016-02-25T12:38:58Z" level=info msg="Preparing server"
time="2016-02-25T12:38:58Z" level=info msg="Starting server on :80"
time="2016-02-25T12:38:59Z" level=info msg="Stopping old server"



time="2016-02-25T12:39:19Z" level=debug msg="Marathon event receveivedtype: status_update_event, event: &{status_update_event 2016-02-25T12:39:19.288Z e0ca3bd9-6e54-4f91-84db-81511bae9335-S1 nodejs.c94eb095-dbbc-11e5-9b11-ae012201fe0c TASK_RUNNING /nodejs 52.31.181.168 [%!s(int=31424)] 2016-02-25T12:39:18.066Z}"
time="2016-02-25T12:39:19Z" level=debug msg="Filtering marathon task /nodejs with bad healthcheck"
time="2016-02-25T12:39:19Z" level=debug msg="Configuration receveived from provider marathon: {\"backends\":{\"backendnodejs\":{\"servers\":{\"server-nodejs-ba80dd44-dbbc-11e5-9b11-ae012201fe0c\":{\"url\":\"http://52.50.45.40:31793\"}}}},\"frontends\":{\"frontend-nodejs\":{\"backend\":\"backendnodejs\",\"routes\":{\"route-host-nodejs\":{\"rule\":\"Host\",\"value\":\"nodejs.apollo.example.com\"}}}}}"
time="2016-02-25T12:39:19Z" level=debug msg="Last marathon config received more than 2s, OK"
time="2016-02-25T12:39:19Z" level=debug msg="Creating frontend frontend-nodejs"
time="2016-02-25T12:39:19Z" level=debug msg="Wiring frontend frontend-nodejs to entryPoint http"
time="2016-02-25T12:39:19Z" level=debug msg="Creating route route-host-nodejs Host:nodejs.apollo.example.com"
time="2016-02-25T12:39:19Z" level=debug msg="Creating backend backendnodejs"
time="2016-02-25T12:39:19Z" level=debug msg="Creating load-balancer wrr"
time="2016-02-25T12:39:19Z" level=debug msg="Creating server server-nodejs-ba80dd44-dbbc-11e5-9b11-ae012201fe0c at http://52.50.45.40:31793 with weight 0"
time="2016-02-25T12:39:19Z" level=info msg="Preparing server"
time="2016-02-25T12:39:19Z" level=info msg="Starting server on :80"
time="2016-02-25T12:39:20Z" level=debug msg="Round trip: http://52.50.45.40:31793, code: 200, duration: 2.219402ms"
time="2016-02-25T12:39:20Z" level=info msg="Stopping old server"
time="2016-02-25T12:39:20Z" level=info msg="Server stopped"
time="2016-02-25T12:39:20Z" level=debug msg="Round trip: http://52.50.45.40:31793, code: 200, duration: 810.398µs"
time="2016-02-25T12:39:21Z" level=debug msg="Round trip: http://52.50.45.40:31793, code: 200, duration: 800.255µs"
time="2016-02-25T12:39:21Z" level=debug msg="Round trip: http://52.50.45.40:31793, code: 200, duration: 774.88µs"
time="2016-02-25T12:39:22Z" level=debug msg="Round trip: http://52.50.45.40:31793, code: 200, duration: 738.688µs"
time="2016-02-25T12:39:22Z" level=debug msg="Round trip: http://52.50.45.40:31793, code: 200, duration: 771.339µs"
time="2016-02-25T12:39:23Z" level=debug msg="Round trip: http://52.50.45.40:31793, code: 200, duration: 824.264µs"
time="2016-02-25T12:39:23Z" level=debug msg="Marathon event receveivedtype: health_status_changed_event, event: &{health_status_changed_event 2016-02-25T12:39:23.218Z /nodejs nodejs.c94eb095-dbbc-11e5-9b11-ae012201fe0c 2016-02-25T12:39:18.066Z %!s(bool=true)}"
time="2016-02-25T12:39:23Z" level=debug msg="Configuration receveived from provider marathon: {\"backends\":{\"backendnodejs\":{\"servers\":{\"server-nodejs-ba80dd44-dbbc-11e5-9b11-ae012201fe0c\":{\"url\":\"http://52.50.45.40:31793\"},\"server-nodejs-c94eb095-dbbc-11e5-9b11-ae012201fe0c\":{\"url\":\"http://52.31.181.168:31424\"}}}},\"frontends\":{\"frontend-nodejs\":{\"backend\":\"backendnodejs\",\"routes\":{\"route-host-nodejs\":{\"rule\":\"Host\",\"value\":\"nodejs.apollo.example.com\"}}}}}"
time="2016-02-25T12:39:23Z" level=debug msg="Last marathon config received more than 2s, OK"
time="2016-02-25T12:39:23Z" level=debug msg="Creating frontend frontend-nodejs"
time="2016-02-25T12:39:23Z" level=debug msg="Wiring frontend frontend-nodejs to entryPoint http"
time="2016-02-25T12:39:23Z" level=debug msg="Creating route route-host-nodejs Host:nodejs.apollo.example.com"
time="2016-02-25T12:39:23Z" level=debug msg="Creating backend backendnodejs"
time="2016-02-25T12:39:23Z" level=debug msg="Creating load-balancer wrr"
time="2016-02-25T12:39:23Z" level=debug msg="Creating server server-nodejs-ba80dd44-dbbc-11e5-9b11-ae012201fe0c at http://52.50.45.40:31793 with weight 0"
time="2016-02-25T12:39:23Z" level=debug msg="Creating server server-nodejs-c94eb095-dbbc-11e5-9b11-ae012201fe0c at http://52.31.181.168:31424 with weight 0"
time="2016-02-25T12:39:23Z" level=info msg="Preparing server"
time="2016-02-25T12:39:23Z" level=info msg="Starting server on :80"
time="2016-02-25T12:39:23Z" level=error msg="Error forwarding to http://52.50.45.40:31793, err: dial tcp 52.50.45.40:31793: getsockopt: connection refused"
time="2016-02-25T12:39:23Z" level=debug msg="Marathon event receveivedtype: health_status_changed_event, event: &{health_status_changed_event 2016-02-25T12:39:23.633Z /nodejs nodejs.ba80dd44-dbbc-11e5-9b11-ae012201fe0c 2016-02-25T12:38:53.125Z %!s(bool=false)}"
time="2016-02-25T12:39:23Z" level=debug msg="Filtering marathon task /nodejs with bad healthcheck"
time="2016-02-25T12:39:23Z" level=debug msg="Marathon event receveivedtype: failed_health_check_event, event: &{/nodejs failed_health_check_event {%!s(float64=3) %!s(float64=5) %!s(float64=3) / %!s(float64=0) HTTP %!s(float64=10)} 2016-02-25T12:39:23.633Z}"
time="2016-02-25T12:39:23Z" level=debug msg="Configuration receveived from provider marathon: {\"backends\":{\"backendnodejs\":{\"servers\":{\"server-nodejs-c94eb095-dbbc-11e5-9b11-ae012201fe0c\":{\"url\":\"http://52.31.181.168:31424\"}}}},\"frontends\":{\"frontend-nodejs\":{\"backend\":\"backendnodejs\",\"routes\":{\"route-host-nodejs\":{\"rule\":\"Host\",\"value\":\"nodejs.apollo.example.com\"}}}}}"
time="2016-02-25T12:39:23Z" level=debug msg="Last marathon config received less than 2s, waiting..."
time="2016-02-25T12:39:23Z" level=debug msg="Configuration receveived from provider marathon: {\"backends\":{\"backendnodejs\":{\"servers\":{\"server-nodejs-c94eb095-dbbc-11e5-9b11-ae012201fe0c\":{\"url\":\"http://52.31.181.168:31424\"}}}},\"frontends\":{\"frontend-nodejs\":{\"backend\":\"backendnodejs\",\"routes\":{\"route-host-nodejs\":{\"rule\":\"Host\",\"value\":\"nodejs.apollo.example.com\"}}}}}"
time="2016-02-25T12:39:23Z" level=debug msg="Last marathon config received less than 2s, waiting..."
time="2016-02-25T12:39:23Z" level=debug msg="Marathon event receveivedtype: status_update_event, event: &{status_update_event 2016-02-25T12:39:23.643Z e0ca3bd9-6e54-4f91-84db-81511bae9335-S0 nodejs.ba80dd44-dbbc-11e5-9b11-ae012201fe0c TASK_KILLED /nodejs 52.50.45.40 [%!s(int=31793)] 2016-02-25T12:38:53.125Z}"
time="2016-02-25T12:39:24Z" level=debug msg="Configuration receveived from provider marathon: {\"backends\":{\"backendnodejs\":{\"servers\":{\"server-nodejs-c94eb095-dbbc-11e5-9b11-ae012201fe0c\":{\"url\":\"http://52.31.181.168:31424\"}}}},\"frontends\":{\"frontend-nodejs\":{\"backend\":\"backendnodejs\",\"routes\":{\"route-host-nodejs\":{\"rule\":\"Host\",\"value\":\"nodejs.apollo.example.com\"}}}}}"
time="2016-02-25T12:39:24Z" level=debug msg="Last marathon config received less than 2s, waiting..."
time="2016-02-25T12:39:24Z" level=error msg="Error forwarding to http://52.50.45.40:31793, err: dial tcp 52.50.45.40:31793: getsockopt: connection refused"
time="2016-02-25T12:39:24Z" level=info msg="Stopping old server"
time="2016-02-25T12:39:24Z" level=info msg="Server stopped"
time="2016-02-25T12:39:24Z" level=error msg="Error forwarding to http://52.50.45.40:31793, err: dial tcp 52.50.45.40:31793: getsockopt: connection refused"
time="2016-02-25T12:39:25Z" level=debug msg="Round trip: http://52.31.181.168:31424, code: 200, duration: 4.535606ms"
time="2016-02-25T12:39:25Z" level=error msg="Error forwarding to http://52.50.45.40:31793, err: dial tcp 52.50.45.40:31793: getsockopt: connection refused"
time="2016-02-25T12:39:26Z" level=debug msg="Waited for marathon config, OK"
time="2016-02-25T12:39:26Z" level=debug msg="Creating frontend frontend-nodejs"
time="2016-02-25T12:39:26Z" level=debug msg="Wiring frontend frontend-nodejs to entryPoint http"
time="2016-02-25T12:39:26Z" level=debug msg="Creating route route-host-nodejs Host:nodejs.apollo.example.com"
time="2016-02-25T12:39:26Z" level=debug msg="Creating backend backendnodejs"
time="2016-02-25T12:39:26Z" level=debug msg="Creating load-balancer wrr"
time="2016-02-25T12:39:26Z" level=debug msg="Creating server server-nodejs-c94eb095-dbbc-11e5-9b11-ae012201fe0c at http://52.31.181.168:31424 with weight 0"
time="2016-02-25T12:39:26Z" level=info msg="Preparing server"
time="2016-02-25T12:39:26Z" level=info msg="Starting server on :80"
time="2016-02-25T12:39:27Z" level=info msg="Stopping old server"
time="2016-02-25T12:39:36Z" level=info msg="Server stopped"
time="2016-02-25T12:39:44Z" level=info msg="Server stopped"
time="2016-02-25T12:39:45Z" level=info msg="Server stopped"

**Comment by emilevauge** [comment]
What is strange is that `52.50.45.40:31793` seems to be up during errors, isn't it?

**Comment by emilevauge** [comment]
@tayzlor: I can reproduce it using Marathon.
The issue comes from Marathon that send events too late.
Here is an example scaling down an app during an `ab` bench.
You can clearly see that errors begin before the log `Configuration receveived from provider marathon`.

```
...
ERRO[2016-03-01T21:03:02+01:00] Error forwarding to http://127.0.0.1:31343, err: dial tcp 127.0.0.1:31343: getsockopt: connection refused 
ERRO[2016-03-01T21:03:02+01:00] Error forwarding to http://127.0.0.1:31343, err: dial tcp 127.0.0.1:31343: getsockopt: connection refused 
ERRO[2016-03-01T21:03:02+01:00] Error forwarding to http://127.0.0.1:31343, err: dial tcp 127.0.0.1:31343: getsockopt: connection refused 
ERRO[2016-03-01T21:03:02+01:00] Error forwarding to http://127.0.0.1:31343, err: dial tcp 127.0.0.1:31343: getsockopt: connection refused 
ERRO[2016-03-01T21:03:02+01:00] Error forwarding to http://127.0.0.1:31343, err: dial tcp 127.0.0.1:31343: getsockopt: connection refused 
ERRO[2016-03-01T21:03:02+01:00] Error forwarding to http://127.0.0.1:31343, err: dial tcp 127.0.0.1:31343: getsockopt: connection refused 
ERRO[2016-03-01T21:03:02+01:00] Error forwarding to http://127.0.0.1:31343, err: dial tcp 127.0.0.1:31343: getsockopt: connection refused 
ERRO[2016-03-01T21:03:02+01:00] Error forwarding to http://127.0.0.1:31343, err: dial tcp 127.0.0.1:31343: getsockopt: connection refused 
ERRO[2016-03-01T21:03:02+01:00] Error forwarding to http://127.0.0.1:31343, err: dial tcp 127.0.0.1:31343: getsockopt: connection refused 
ERRO[2016-03-01T21:03:02+01:00] Error forwarding to http://127.0.0.1:31343, err: dial tcp 127.0.0.1:31343: getsockopt: connection refused 
ERRO[2016-03-01T21:03:02+01:00] Error forwarding to http://127.0.0.1:31343, err: dial tcp 127.0.0.1:31343: getsockopt: connection refused 
ERRO[2016-03-01T21:03:02+01:00] Error forwarding to http://127.0.0.1:31343, err: dial tcp 127.0.0.1:31343: getsockopt: connection refused 
ERRO[2016-03-01T21:03:02+01:00] Error forwarding to http://127.0.0.1:31343, err: dial tcp 127.0.0.1:31343: getsockopt: connection refused 
ERRO[2016-03-01T21:03:02+01:00] Error forwarding to http://127.0.0.1:31343, err: dial tcp 127.0.0.1:31343: getsockopt: connection refused 
ERRO[2016-03-01T21:03:02+01:00] Error forwarding to http://127.0.0.1:31343, err: dial tcp 127.0.0.1:31343: getsockopt: connection refused 
ERRO[2016-03-01T21:03:02+01:00] Error forwarding to http://127.0.0.1:31343, err: dial tcp 127.0.0.1:31343: getsockopt: connection refused 
ERRO[2016-03-01T21:03:02+01:00] Error forwarding to http://127.0.0.1:31343, err: dial tcp 127.0.0.1:31343: getsockopt: connection refused 
ERRO[2016-03-01T21:03:02+01:00] Error forwarding to http://127.0.0.1:31343, err: dial tcp 127.0.0.1:31343: getsockopt: connection refused 
ERRO[2016-03-01T21:03:02+01:00] Error forwarding to http://127.0.0.1:31343, err: dial tcp 127.0.0.1:31343: getsockopt: connection refused 
ERRO[2016-03-01T21:03:02+01:00] Error forwarding to http://127.0.0.1:31343, err: dial tcp 127.0.0.1:31343: getsockopt: connection refused 
ERRO[2016-03-01T21:03:02+01:00] Error forwarding to http://127.0.0.1:31343, err: dial tcp 127.0.0.1:31343: getsockopt: connection refused 
ERRO[2016-03-01T21:03:02+01:00] Error forwarding to http://127.0.0.1:31343, err: dial tcp 127.0.0.1:31343: getsockopt: connection refused 
ERRO[2016-03-01T21:03:02+01:00] Error forwarding to http://127.0.0.1:31343, err: dial tcp 127.0.0.1:31343: getsockopt: connection refused 
ERRO[2016-03-01T21:03:02+01:00] Error forwarding to http://127.0.0.1:31343, err: dial tcp 127.0.0.1:31343: getsockopt: connection refused 
ERRO[2016-03-01T21:03:02+01:00] Error forwarding to http://127.0.0.1:31343, err: dial tcp 127.0.0.1:31343: getsockopt: connection refused 
ERRO[2016-03-01T21:03:02+01:00] Error forwarding to http://127.0.0.1:31343, err: dial tcp 127.0.0.1:31343: getsockopt: connection refused 
ERRO[2016-03-01T21:03:02+01:00] Error forwarding to http://127.0.0.1:31343, err: dial tcp 127.0.0.1:31343: getsockopt: connection refused 
ERRO[2016-03-01T21:03:02+01:00] Error forwarding to http://127.0.0.1:31343, err: dial tcp 127.0.0.1:31343: getsockopt: connection refused 
ERRO[2016-03-01T21:03:02+01:00] Error forwarding to http://127.0.0.1:31343, err: dial tcp 127.0.0.1:31343: getsockopt: connection refused 
ERRO[2016-03-01T21:03:02+01:00] Error forwarding to http://127.0.0.1:31343, err: dial tcp 127.0.0.1:31343: getsockopt: connection refused 
ERRO[2016-03-01T21:03:02+01:00] Error forwarding to http://127.0.0.1:31343, err: dial tcp 127.0.0.1:31343: getsockopt: connection refused 
ERRO[2016-03-01T21:03:02+01:00] Error forwarding to http://127.0.0.1:31343, err: dial tcp 127.0.0.1:31343: getsockopt: connection refused 
INFO[2016-03-01T21:03:02+01:00] Configuration receveived from provider marathon: {"backends":{"backend-whoami":{"servers":{"server-whoami-87e8abd2-dfe7-11e5-bf65-b228ab373846":{"url":"http://127.0.0.1:31758","weight":1},"server-whoami-87f26fd4-dfe7-11e5-bf65-b228ab373846":{"url":"http://127.0.0.1:31616","weight":1}}}},"frontends":{"frontend-whoami":{"backend":"backend-whoami","routes":{"route-host-whoami":{"rule":"Host","value":"whoami.marathon.localhost"}}}}} 
INFO[2016-03-01T21:03:02+01:00] Preparing server                             
INFO[2016-03-01T21:03:02+01:00] Starting server on :4443                     
ERRO[2016-03-01T21:03:02+01:00] Error forwarding to http://127.0.0.1:31343, err: dial tcp 127.0.0.1:31343: getsockopt: connection refused 
ERRO[2016-03-01T21:03:02+01:00] Error forwarding to http://127.0.0.1:31343, err: dial tcp 127.0.0.1:31343: getsockopt: connection refused 
ERRO[2016-03-01T21:03:02+01:00] Error forwarding to http://127.0.0.1:31343, err: dial tcp 127.0.0.1:31343: getsockopt: connection refused 
ERRO[2016-03-01T21:03:02+01:00] Error forwarding to http://127.0.0.1:31343, err: dial tcp 127.0.0.1:31343: getsockopt: connection refused 
ERRO[2016-03-01T21:03:02+01:00] Error forwarding to http://127.0.0.1:31343, err: dial tcp 127.0.0.1:31343: getsockopt: connection refused 
ERRO[2016-03-01T21:03:02+01:00] Error forwarding to http://127.0.0.1:31343, err: dial tcp 127.0.0.1:31343: getsockopt: connection refused 
ERRO[2016-03-01T21:03:02+01:00] Error forwarding to http://127.0.0.1:31343, err: dial tcp 127.0.0.1:31343: getsockopt: connection refused 
ERRO[2016-03-01T21:03:02+01:00] Error forwarding to http://127.0.0.1:31343, err: dial tcp 127.0.0.1:31343: getsockopt: connection refused 
ERRO[2016-03-01T21:03:02+01:00] Error forwarding to http://127.0.0.1:31343, err: dial tcp 127.0.0.1:31343: getsockopt: connection refused 
ERRO[2016-03-01T21:03:02+01:00] Error forwarding to http://127.0.0.1:31343, err: dial tcp 127.0.0.1:31343: getsockopt: connection refused 
ERRO[2016-03-01T21:03:02+01:00] Error forwarding to http://127.0.0.1:31343, err: dial tcp 127.0.0.1:31343: getsockopt: connection refused 
...
```

Doing the same thing on Docker doesn't lead to such errors...

**Comment by tayzlor** [comment]
Could this be down to the method used to get the events here? We're using "event subscriptions". The preferred method to get events (since marathon 0.9.0) is to attach to the event stream API (documented here https://mesosphere.github.io/marathon/docs/rest-api.html#get-v2-events). 

See this comment here https://github.com/mesosphere/marathon/pull/3282#issuecomment-187064854

Even if that's not the issue in play here, it would seem sensible in any case to move to the event stream API.

**Comment by emilevauge** [comment]
@tayzlor, I will look at this.
In the meantime, could you test with the branch https://github.com/containous/traefik/tree/add-retries-request ? Added retries ;)

**Comment by tayzlor** [comment]
@emilevauge will do and will report back when I can / have tested it, just opened #230 to switch over to the event stream.

**Comment by emilevauge** [comment]
I just created this PR #232 to retry requests that failed due to new network errors.
This should improve things a bit ;)

**Comment by sample** [comment]
Have same problem with traefik and marathon. PR #232 really works as workaround.

**Comment by emilevauge** [comment]
Thanks @sample for your feedback. I will merge #232 soon then ;)
