### ISSUE TITLE
Whole folder for certs

### ISSUE THREAD

**Issue by strarsis** [containous/traefik#211]
It would be great (e.g. for letsencrypt-auto) if traefik could support a folder with cert/key files 
instead having to list each cert/key file separately in traefik configuration.
Otherwise a script would have to watch the key/cert folder of letsencrypt-auto and 
render a configuration file from template using the filenames inside.

**Comment by emilevauge** [comment]
This will be addressed when implementing let's encrypt support.
Duplicate #89

**Comment by mischief** [comment]
@emilevauge - i don't think this is solved. i'd like something similar, to have traefik put letsencrypt certificates and private keys in per-domain directories on disk. accessing them from acme.json is cumbersome.

**Comment by chulkilee** [comment]
I think it's useful for non-ACME use cases. For example, I do not want to update toml files to add new certs after adding new front/backend via dynamic backend (e.g. docker).

To do that traefik also needs to watch and reload certs as well..

Can we remove "duplicate" label from this issue?

**Comment by mfuezesi** [comment]
+1
Any news or other suggestions for solutions to this issue?

**Comment by ldez** [comment]
I'll close the issue due to inactivity but feel free to re-open if needed.
