### ISSUE TITLE
Marathon 1.5.0 breaks Traefik Marathon integration

### ISSUE THREAD

**Issue by mikekatica** [containous/traefik#2115]
### Do you want to request a *feature* or report a *bug*?

Report a bug.

### What did you do?

Recently upgraded DCOS cluster from 1.9 to 1.10, which includes an upgrade to Marathon 1.5.0-SNAPSHOT-713-g14280a6.

### What did you expect to see?
Backends generated by marathon plugin use IP-per-task IP. For the service below, expected the backend to be set to 9.0.6.133:80.
```json
{
    "app": {
        "backoffFactor": 1.15,
        "backoffSeconds": 1,
        "container": {
            "docker": {
                "forcePullImage": false,
                "image": "<redacted>",
                "parameters": [],
                "privileged": false
            },
            "portMappings": [
                {
                    "containerPort": 80,
                    "labels": {},
                    "name": "http",
                    "protocol": "tcp",
                    "servicePort": 10107
                }
            ],
            "type": "DOCKER",
            "volumes": []
        },
        "cpus": 0.2,
        "deployments": [],
        "disk": 0,
        "executor": "",
        "gpus": 0,
        "healthChecks": [
            {
                "delaySeconds": 15,
                "gracePeriodSeconds": 300,
                "ignoreHttp1xx": false,
                "intervalSeconds": 60,
                "maxConsecutiveFailures": 3,
                "path": "/",
                "portIndex": 0,
                "protocol": "HTTP",
                "timeoutSeconds": 20
            }
        ],
        "id": "/internal-ticketing",
        "instances": 1,
        "killSelection": "YOUNGEST_FIRST",
        "labels": {<Redacted>},
        "maxLaunchDelaySeconds": 3600,
        "mem": 512,
        "networks": [
            {
                "mode": "container",
                "name": "dcos"
            }
        ],
        "requirePorts": false,
        "tasks": [
            {
                "appId": "/internal-ticketing",
                "healthCheckResults": [
                    {
                        "alive": true,
                        "consecutiveFailures": 0,
                        "firstSuccess": "2017-09-12T21:18:31.612Z",
                        "instanceId": "internal-ticketing.marathon-ea90760d-97ff-11e7-8013-629e7338b525",
                        "lastFailure": null,
                        "lastFailureCause": null,
                        "lastSuccess": "2017-09-13T14:24:52.122Z"
                    }
                ],
                "host": "10.172.130.189",
                "id": "internal-ticketing.ea90760d-97ff-11e7-8013-629e7338b525",
                "ipAddresses": [
                    {
                        "ipAddress": "9.0.6.133",
                        "protocol": "IPv4"
                    }
                ],
                "ports": [],
                "slaveId": "c26773ac-c1e8-44d2-a012-4bb3159e1762-S3",
                "stagedAt": "2017-09-12T21:18:26.589Z",
                "startedAt": "2017-09-12T21:18:29.319Z",
                "state": "TASK_RUNNING",
                "version": "2017-09-12T21:18:26.559Z"
            }
        ],
        "tasksHealthy": 1,
        "tasksRunning": 1,
        "tasksStaged": 0,
        "tasksUnhealthy": 0,
        "unreachableStrategy": {
            "expungeAfterSeconds": 600,
            "inactiveAfterSeconds": 300
        },
        "upgradeStrategy": {
            "maximumOverCapacity": 1,
            "minimumHealthCapacity": 1
        },
        "version": "2017-09-12T21:18:26.559Z",
        "versionInfo": {
            "lastConfigChangeAt": "2017-09-12T21:18:26.559Z",
            "lastScalingAt": "2017-09-12T21:18:26.559Z"
        }
    }
}
```

### What did you see instead?
Instead the backend is created using the host IP: 10.172.130.189:80

### Output of `traefik version`: (_What version of Traefik are you using?_)

(Running in container based off of roquefort-alpine)
```
Version:      v1.4.0-rc2
Codename:     roquefort
Go version:   go1.9
Built:        2017-09-08_07:31:37PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

No arguments. Platform is DCOS 1.10 running in AWS.

```toml
defaultEntryPoints = ["http","https"]

[web]

# Web administration port
#
# Required
#
address = ":8080"

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"
  [entryPoints.es]
  address = ":10020"
[marathon]
watch = true
domain = "marathon.mesos"
forceTaskHostname = false
exposedByDefault = true
marathonLBCompatibility = true
endpoint = "http://marathon.mesos:8080"
```

### If applicable, please paste the log output in debug mode (`--debug` switch)

N/A

**Comment by mikekatica** [comment]
I believe the offending code snippet is from Marathon.go:
```go
case application.IPAddressPerTask == nil || p.ForceTaskHostname:
		return task.Host
```
It appears that in this update of marathon, the top level IPAddress field is missing, and the library used by traefik is expecting this when returning IPAddressPerTask, and will always return nil. I will open an issue with that repo as well.

**Comment by mikekatica** [comment]
There is already an issue in the marathon library repo [here](https://github.com/gambol99/go-marathon/issues/324). I'll see what can be done.

**Comment by mikekatica** [comment]
After some investigating, it looks like in Marathon 1.5 API, the "ipAddress" field is not present at all for  docker runtime services, but in Marathon 1.4 the field is created but empty. Changing the logic to something like this might fix it without needing the underlying library to accommodate this api change.
```go
case (application.Container.Type != "DOCKER" && application.IPAddressPerTask == nil) || p.ForceTaskHostname:
		return task.Host
```

**Comment by timoreimann** [comment]
@mikekatica thanks for your report.

I'm still trying to understand how Marathon expects IP-per-task users to adjust: with the top-level `ipAddress` field gone, what's the replacement? I had a look at the change log that comes with [a section on the changed API fields](https://github.com/mesosphere/marathon/blob/616030a508d89c80afedaf6b414e90b6736badfb/changelog.md#app-json-fields-changed-or-moved), but it doesn't clarify things for me.

I don't happen to have a working IP-per-task configuration at hand. Could you maybe post how the JSON representation looks like when retrieved from Marathon 1.5?

**Comment by kshitizbakshi** [comment]
@timoreimann The replacement for `ipAddress` field is the `container` networking mode. There are some examples towards the end of the page [here](https://github.com/mesosphere/marathon/blob/616030a508d89c80afedaf6b414e90b6736badfb/docs/docs/networking.md).

**Comment by timoreimann** [comment]
@mikekatica I'm not certain I understand how this can be solved in Traefik alone: if the IP-per-task addresses are now part of a field that go-marathon doesn't even know about yet, wouldn't we have to extend the underlying library for sure to be able to get a hold of the necessary fields?

**Comment by mikekatica** [comment]
Right. It may not be the best option to handle this purely in traefik, but the changes in the Marathon API may force the marathon GO library to change it's API as well. Currently, both are broken for Marathon 1.5. It might be worth it to just wait until gambol/marathon is fixed to support 1.5.

**Comment by timoreimann** [comment]
@mikekatica go-marathon is still pre-stable from a semver point; while breaking API changes should be avoided where reasonably possible, it's okay to introduce some if it makes sense.

That said, the Marathon document describes most (all?) changes as additive as far as the JSON fields are concerned. go-marathon has only minimal behavior and mostly does direct serialization / deserialization. So to me, it looks like we could extend the library without breaking (too much) and build the remainder of the Marathon 1.5 support on top into Traefik.

WDYT? Happy to review any PRs on either the library or application side if you'd like to take a stab.

**Comment by mikekatica** [comment]
I'll have to brush on up my go, but I can try to work on the library a bit. I think the network changes made are going to require additional fields be added to the application representation in the library. Once those are done and accepted, then changes to traefik can be made to accomodate.

**Comment by timoreimann** [comment]
Quick update: A [PR for go-marathon](https://github.com/gambol99/go-marathon/pull/327) (the Go library powering access to Marathon) bringing support for 1.5 is in progress. It didn't make it into Traefik 1.5 anymore, but I'm confident we can integrate it into the subsequent release.

**Comment by YP28** [comment]
I've been following the Traefik + Marathon 1.5 threads for a few weeks now. It seems that the virtual overlay network IP's that are assigned to tasks aren't exposed through the Marathon API. A solution would be to use the l4lb address to route to. However, that might be quite a change since you'd rely on something other than Marathon itself. On top of that, you wouldn't route to several ip addresses but rather an internal dns address. 

Curious how this will be handled. This is the only thing keeping me from using Traefik as an edge router for our cluster.

**Comment by timoreimann** [comment]
@YP28 I am hoping that adding support for Marathon 1.5 can be as simple as extending the check for the Marathon-1.4-and-lower IP address field by the corresponding Marathon 1.5 field.

**Comment by YP28** [comment]
My bad, Marathon *does* expose the IP addresses through the API. So it shouldn't be hard to implement once `go-marathon` has support for 1.5.

**Comment by alenkacz** [comment]
I'll try to help pushing the go-marathon 1.5 out so this will be unblocked...
