### ISSUE TITLE
Traefik is unable to discovery if the docker service opens more than 1 port. [Marathon backend]

### ISSUE THREAD

**Issue by anhcuong** [containous/traefik#213]
Hi, 

I have observed this behavior from traefik 8-Dec to the latest version (18-Feb).

Since my application needs to talk with client (default port 80) and other server (other ports), I have to open 2 ports on the docker application. But it makes the Traefik not functioning. 

I find my need quite reasonable and more flexible than always limiting to 1 port. Hope it will be a new feature in upcoming version.

**Comment by emilevauge** [comment]
Duplicate #61

**Comment by adrm** [comment]
In my case, I launched a container which EXPOSEs three ports. I ran it publishing just one of them, with the appropiated traefik labels. Every other container is working properly with traefik except for this one, which is not even discovered by traefik. I think this is not the same problem as #61. My backend is docker.

Any advice? Thanks!
