### ISSUE TITLE
rancher.metadata container name collision in backend (different behaviour compared to rancher.api)

### ISSUE THREAD

**Issue by PicoCreator** [containous/traefik#2130]
### Do you want to request a *feature* or report a *bug*?

Bug (Unless its intentional)

### What did you do?

Docker System : Rancher v1.6.5
Deployed latest official image : `traefik:v1.4.0-rc2-alpine`

With the following command for meta-data mode (formatted to be easier to read)

```
--web --rancher 
	--rancher.domain=rancher.localhost 
	--rancher.enableservicehealthfilter=false 
	--rancher.exposedbydefault=false 
	--rancher.metadata
```

Along with the following container labels

```
io.rancher.container.agent.role=environment
io.rancher.container.create_agent=true
```

Multiple stacks was then created, with different stack names. But **same container names** (web-studio in this case)

Each container is defined with the following traefik labels

```
traefik.enable=true
traefik.frontend.rule=Host:the-container-unique-url.domain.something
traefik.port=80
```

Note: this is a followup from https://github.com/containous/traefik/issues/2125

### What did you expect to see?

Every container, from each stack, with its own "host name rule" for frontend, and its own backend, as seen below, when traefik is using rancher.api

![screen shot 2017-09-18 at 1 13 33 pm](https://user-images.githubusercontent.com/17175484/30529889-a1ddb08a-9c74-11e7-880d-152451d5080a.png)

### What did you see instead?

A single backend, for all the various frontend, when traefik is using rancher.metadata

![screen shot 2017-09-18 at 1 13 15 pm copy](https://user-images.githubusercontent.com/17175484/30529949-313fd564-9c75-11e7-84c7-072d4b0ee624.png)

Note : that both this traefik configuration was deployed side by side to the same rancher testing infrastructure. So both configuration was expected to be same

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.4.0-rc2
Codename:     roquefort
Go version:   go1.9
Built:        2017-09-08_07:31:37PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

None: See setup above

**Comment by SantoDE** [comment]
Hi @PicoCreator ,

this is already fixed in #2107, so it should be available with the next rc for 1.4 :)
