### ISSUE TITLE
Traefik stopped being able to renew TLS cert

### ISSUE THREAD

**Issue by cpuguy83** [containous/traefik#2158]
### Do you want to request a *feature* or report a *bug*?
bug

### What did you do?

I've been running traefik for months with no issue and randomly this popped up.
Restarting traefik resolved the issue.

### What did you expect to see?

TLS cert should not be expired

### What did you see instead?

Visitors reporting that my TLS cert was expired.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.1.2
Codename:     camembert
Go version:   go1.7.4
Built:        2016-12-15_10:21:15AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```
--debug --web --docker --acme --acme.email=<redacted> --acme.ondemand=true --acme.storage=/var/acme/acme.json --acme.entrypoint=https --accesslogsfile=/var/acme/access.log --acme.onhostrule=true --entryPoints='Name:https Address::443 TLS' --entryPoints='Name:http Address::80' --acme.caserver="https://acme-v01.api.letsencrypt.org/directory"
```

### If applicable, please paste the log output in debug mode (`--debug` switch)
This same nonce error appears in my logs every day from the 2017-08-04 on.

```
{"log":"time=\"2017-08-04T15:17:38Z\" level=debug msg=\"Round trip: http://10.0.0.5:80, code: 200, duration: 291.277868ms\" \n","stream":"stderr","time":"2017-08-04T15:17:38.092418278Z"}
{"log":"time=\"2017-08-04T15:17:39Z\" level=debug msg=\"Challenge GetCertificate www.container42.com\" \n","stream":"stderr","time":"2017-08-04T15:17:39.283296205Z"}
{"log":"time=\"2017-08-04T15:17:39Z\" level=debug msg=\"ACME got domain cert www.container42.com\" \n","stream":"stderr","time":"2017-08-04T15:17:39.283370743Z"}
{"log":"time=\"2017-08-04T15:17:39Z\" level=debug msg=\"Round trip: http://10.0.0.5:80, code: 200, duration: 2.513388ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:www.container42.com\" \n","stream":"stderr","time":"2017-08-04T15:17:39.58961092Z"}
{"log":"time=\"2017-08-04T15:17:39Z\" level=debug msg=\"Challenge GetCertificate www.container42.com\" \n","stream":"stderr","time":"2017-08-04T15:17:39.823618823Z"}
{"log":"time=\"2017-08-04T15:17:39Z\" level=debug msg=\"ACME got domain cert www.container42.com\" \n","stream":"stderr","time":"2017-08-04T15:17:39.823816299Z"}
{"log":"time=\"2017-08-04T15:17:40Z\" level=debug msg=\"Round trip: http://10.0.0.5:80, code: 404, duration: 1.094497ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:www.container42.com\" \n","stream":"stderr","time":"2017-08-04T15:17:40.073418533Z"}
{"log":"time=\"2017-08-04T15:17:44Z\" level=debug msg=\"Round trip: http://10.0.0.5:80, code: 304, duration: 403.551µs\" \n","stream":"stderr","time":"2017-08-04T15:17:44.056814143Z"}
{"log":"time=\"2017-08-04T15:17:49Z\" level=warning msg=\"A new release has been found: 1.3.5. Please consider updating.\" \n","stream":"stderr","time":"2017-08-04T15:17:49.417808917Z"}
{"log":"time=\"2017-08-04T15:17:50Z\" level=debug msg=\"Testing certificate renew...\" \n","stream":"stderr","time":"2017-08-04T15:17:50.280442104Z"}
{"log":"time=\"2017-08-04T15:17:50Z\" level=debug msg=\"Renewing certificate {Main:container42.com SANs:[www.container42.com]}\" \n","stream":"stderr","time":"2017-08-04T15:17:50.280544169Z"}
{"log":"time=\"2017-08-04T15:17:50Z\" level=error msg=\"Error renewing certificate: acme: Error 400 - urn:acme:error:badNonce - JWS has invalid anti-replay nonce K7r2s6IyIO3VWEgmRi5_VAMH04oFNQfU4WAZkXpOyi0\" \n","stream":"stderr","time":"2017-08-04T15:17:50.666190577Z"}
{"log":"time=\"2017-08-04T15:17:50Z\" level=debug msg=\"Renewing certificate {Main:www.container42.com SANs:[]}\" \n","stream":"stderr","time":"2017-08-04T15:17:50.666664267Z"}
{"log":"time=\"2017-08-04T15:17:50Z\" level=debug msg=\"Challenge Present www.container42.com\" \n","stream":"stderr","time":"2017-08-04T15:17:50.972293191Z"}
{"log":"time=\"2017-08-04T15:17:51Z\" level=debug msg=\"Challenge GetCertificate 04e0a38705efaf6be59465c891656f09.57a482d1969d9262ab43c067953b3e44.acme.invalid\" \n","stream":"stderr","time":"2017-08-04T15:17:51.628908881Z"}
{"log":"time=\"2017-08-04T15:17:51Z\" level=debug msg=\"ACME got challenge 04e0a38705efaf6be59465c891656f09.57a482d1969d9262ab43c067953b3e44.acme.invalid\" \n","stream":"stderr","time":"2017-08-04T15:17:51.635167524Z"}
{"log":"time=\"2017-08-04T15:17:52Z\" level=debug msg=\"Challenge CleanUp www.container42.com\" \n","stream":"stderr","time":"2017-08-04T15:17:52.607912335Z"}
{"log":"time=\"2017-08-04T15:17:52Z\" level=debug msg=\"Renewed certificate {Main:www.container42.com SANs:[]}\" \n","stream":"stderr","time":"2017-08-04T15:17:52.85885864Z"}
{"log":"time=\"2017-08-04T15:18:31Z\" level=debug msg=\"Round trip: http://10.0.0.5:80, code: 200, duration: 615.7664ms\" \n","stream":"stderr","time":"2017-08-04T15:18:31.100504979Z"}```

**Comment by ldez** [comment]
Could you try with the next stable release (1.3.8) ?

**Comment by cpuguy83** [comment]
Yeah I upgraded.
This issue didn't crop up until 5 months of uptime.

**Comment by zyzop** [comment]
same problem here, traefik doesnt update ACME certificate until I restart it. I had, I think, 1.3.7, not sure.
One day it was simply wooops your certificate is expired, I just restarted it and certificate got renewed.

**Comment by nmengin** [comment]
Hello @cpuguy83 @zyzop.

I am currently analyzing deeply the problem and it seems to be a relied  to the data storage concurrent access during the certificate renewing.

Can you give me more information about your configuration :
- How many instances of Træfik are running?
- Do they all access to the data storage?
- @zyzop  Are you using a storage file or a KV store? 

Thanks in advance.

**Comment by cpuguy83** [comment]
> How many instances of Træfik are running?

1

> Do they all access to the data storage?

Only 1 instance

**Comment by nmengin** [comment]
OK @cpuguy83.

Many thanks for your feedback.

**Comment by zyzop** [comment]
@nmengin Hello, it was a Consul with two instances in my case.

**Comment by nmengin** [comment]
OK @zyzop, thank you.

Are you using the [deprecated](https://github.com/containous/traefik/issues/2212) option `onDemand` too?

**Comment by zyzop** [comment]
@nmengin well yeah, it's set to true. Done months ago, actually, didn't touch configs since then.

**Comment by nmengin** [comment]
@cpuguy83 @zyzop 

This problem is very hard to debug! I launched an environment which runs for 3 days and renews its certificates once per hour. So far, so good...

As you can read into the PR #2520, I changed the `logLevel` of ACME renewing messages. This modification will be available in Træfik 1.5.0-rc2. Don't hesitate to migrate to this version.

Moreover, I can see you use the `onDemand` option. This option is [deprecated](https://github.com/containous/traefik/issues/2212) and I advice you to replace it ASAP by the `onHostRule` option.

I'll give you a feedback if something new appears.

**Comment by nmengin** [comment]
Hello @cpuguy83 @zyzop .

Can you tell me if the problem still appears?

**Comment by cpuguy83** [comment]
I can't because I only had the issue once and it took months to manifest.
I recently switched to netlify for that site too, so 🤷‍♂️ 
It could have been a fluke, not sure.

**Comment by nmengin** [comment]
Ok @cpuguy83.

I close this PR for the moment, feel free to re-open it if necessary or to contact us on our Slack.

**Comment by rvaidya** [comment]
I have just run into something like this myself - Traefik did not renew my LE certificate today after running for months.   I had the default log level of ERROR, but there was nothing relevant in the log file, just a lot of:

`Jan 02 11:23:27 loadbalancer-cluster-gslz traefik[1886]: 2019/01/02 11:23:27 transport.go:1748: Unsolicited response received on idle HTTP channel starting with "<!-- html is corrupted -->"; err=<nil>`

I restarted the process on my servers and the certificate renewed itself after a while.

Traefik version 1.6.5

**Comment by marciorf** [comment]
I have the same issue with traefik 1.5

**Comment by Bhlowe** [comment]
I just experienced it.. Would be nice to know when the next renewal is scheduled, the date and status of the last renewal.. and perhaps when created the first time. This could also be written to the acme.json file.. or added to the web interface..
