### ISSUE TITLE
Set new default values for docker-based frontends?

### ISSUE THREAD

**Issue by emil-nasso** [containous/traefik#216]
I ran into issues with redirects and ran into the `passPostHeader`-flag.

Is there any way to change the default for this? We don't actually put any labels on our containers and the default configuration seems to work fine. Except for one thing, the `passPostHeader` needs to be set to true.

Is there any way for me to change this globally, without having to add labels to all containers?

Another one just for my curiosity... ;) Why is `passPostHeader` false by default? What is the usecase for that?

**Comment by emilevauge** [comment]
Hi @emil-nasso, we could indeed change the default behavior.
But, for now, you can use this workaround: use a customized template.
For example, if you use Docker as a backend, you can provide a custom template with `passHostHeader` set to true:
```
[backends]{{range .Containers}}
    [backends.backend-{{getBackend .}}.servers.server-{{.Name | replace "/" "" | replace "." "-"}}]
    url = "{{getProtocol .}}://{{.NetworkSettings.IPAddress}}:{{getPort .}}"
    weight = {{getWeight .}}
{{end}}

[frontends]{{range $frontend, $containers := .Frontends}}
  [frontends."frontend-{{$frontend}}"]{{$container := index $containers 0}}
  backend = "backend-{{getBackend $container}}"
  passHostHeader = true
  entryPoints = [{{range getEntryPoints $container}}
    "{{.}}",
  {{end}}]
    [frontends."frontend-{{$frontend}}".routes."route-frontend-{{$frontend}}"]
    rule = "{{getFrontendRule $container}}"
    value = "{{getFrontendValue $container}}"
{{end}}
```

and in the TOML config file:
```
################################################################
# Docker configuration backend
################################################################
[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "docker.localhost"
watch = true
filename = "mydocker.tmpl"
```

**Comment by kirillDanshin** [comment]
Hey! I think it'll be really cool, but can break someone's config. Can we add a new boolean parameter, like `passHostHeadDef` that will control default value?

**Comment by emil-nasso** [comment]
Is there any plans to change the default for this? Could perhaps be a good time to do it in/before a 1.0 release? Better than doing it after releasing 1.0 at least. :)

**Comment by emilevauge** [comment]
Hi, we don't see any issue in changing this default value, we also don't see why it would break someone's config. WDYT?
We are OK to change the default behavior for the 1.0.0 release.
Does anyone want to make a PR?

**Comment by mathieu-pousse** [comment]
make sense to have it by default, it is kind of a must have for a reverse proxy

**Comment by Spy-Seth** [comment]
It seems to be logic to change the `passPostHeader` to be present by default. Adding a global `defaultPassPostHeader` options to globally change this value could be nice too (like `defaultEntryPoints`).

**Comment by samber** [comment]
+1 for passPostHeader=true by default ;-)

**Comment by xinity** [comment]
a totaly agree for enabling this option at True by default.
basically i don't see a usecase for this option at False :+1:

**Comment by stongo** [comment]
I've got a good start on this. should be able to PR tomorrow

**Comment by stongo** [comment]
The `x-forwarded-for` and `user-agent` still don't get set correctly when `passHostHeader` is set to true. Does it make sense to include those headers in the `passHostHeader` option too?

**Comment by emilevauge** [comment]
@stongo: Headers are managed by `vulcand/oxy` library here: https://github.com/vulcand/oxy/blob/master/forward/rewrite.go
What is wrong here ? In my tests, it seems OK ;)
