### ISSUE TITLE
Cannot specify ECS cluster in 1.4rc3

### ISSUE THREAD

**Issue by zyzop** [containous/traefik#2160]
### Do you want to request a *feature* or report a *bug*?
bug
### What did you do?

I tried to use a new feature - support of multiple ECS clusters
So I tried to configure it.
Simplest variant: `--ecs --ecs.clusters=["dashboard-dev"]` does not work

I get these errors - 
```
time="2017-09-21T20:11:03Z" level=debug msg="ECS Clusters: [["dashboard-dev"]]" 
time="2017-09-21T20:11:03Z" level=error msg="Provider connection error ClusterNotFoundException: Cluster not found.
```

If I try to specify several ECS clusters then traefic doesnt even start (BTW, what's a correct way to specify multiple ones? it's not clear).

### What did you expect to see?

ECS tab in traefik UI with my cluster found. or at least empty tab

### What did you see instead?

no ECS tab in UI, and errors as above

### Output of `traefik version`: (_What version of Traefik are you using?_)

1.4rc3

**Comment by ldez** [comment]
Please try with:

```shell
--ecs --ecs.clusters="dashboard-dev"
 ```
more complex example:
```shell
--ecs --ecs.clusters="dashboard-dev,dashboard-staging,dashboard-prod"
```

**Comment by zyzop** [comment]
@ldez in docs you have
clusters = ["default"]
If I requestes help from command line, then I have
--ecs.clusters                             ECS Clusters name       (default "[default]")

So, three options - ["default"] , "[default]" and your variant "dashboard-dev".

**Comment by zyzop** [comment]
And no luck anyway - 
time="2017-09-22T18:33:54Z" level=debug msg="ECS Clusters: ["dashboard-dev"]" 
time="2017-09-22T18:33:54Z" level=error msg="Provider connection error ClusterNotFoundException: Cluster not found.

Cluster is named exactly like this, I have all needed rights granted in IAM role.

**Comment by ldez** [comment]
the docs use TOML file:
```toml
clusters = ["default"]
```

the command line display with a Go slice "toString' representation:
```
[default]
```

and the parser use this format:
```
foo,bar,fii,bir
```

**Comment by zyzop** [comment]
Okay, so I decided to try "autodiscoverclusters" flag, and got this -

Error here : unknown flag: --autodiscoverclusters

But docs clearly say this flag is available
# Enable auto discover ECS clusters.
#
# Optional
# Default: false
#
autoDiscoverClusters = false

**Comment by ldez** [comment]
with TOML:

```toml
# Enable ECS configuration backend.
[ecs]
autoDiscoverClusters = true
```

with CLI:

```shell
--ecs.autodiscoverclusters
```


the CLI help:
```shell
   --ecs                                      Enable ECS backend with default settings                                         (default "true")
    --ecs.accesskeyid                          The AWS credentials access key to use for making requests                        
    --ecs.autodiscoverclusters                 Auto discover cluster                                                            (default "false")
    --ecs.cluster                              deprecated - ECS Cluster name                                                    
    --ecs.clusters                             ECS Clusters name                                                                (default "[default]")
    --ecs.constraints                          Filter services by constraint, matching with Traefik tags.                       (default "[]")
    --ecs.debugloggeneratedtemplate            Enable debug logging of generated configuration template.                        (default "false")
    --ecs.domain                               Default domain used                                                              
    --ecs.exposedbydefault                     Expose containers by default                                                     (default "true")
    --ecs.filename                             Override default configuration template. For advanced users :)                   
    --ecs.refreshseconds                       Polling interval (in seconds)                                                    (default "15")
    --ecs.region                               The AWS region to use for requests                                               
    --ecs.secretaccesskey                      The AWS credentials access key to use for making requests                        
    --ecs.trace                                Display additional provider logs (if available).                                 (default "false")
    --ecs.watch                                Watch provider                                                                   (default "true")
    --entrypoints                              Entrypoints definition using format: --entryPoints='Name:http Address::8000      (default "map[]")
```

**Comment by ldez** [comment]
could you try:

```shell
--ecs --ecs.clusters=dashboard-dev
```

I don't have ECS cluster to try the command, sorry.

**Comment by zyzop** [comment]
Okay, my bad. Autodiscover works now.
With one remark - I had one cluster without instances. Until I removed it, ecs backend wasnt working at all, giving me this error "time="2017-09-22T19:01:33Z" level=error msg="Provider connection error InvalidParameterException: Container instance cannot be empty." There wasn't even a ecs tab in UI.
I believe this is a wrong behaviour, you should just skip empty clusters, not bring down whole backend.

PS "clusters" still doesnt work no matter what I try.

**Comment by ldez** [comment]
if you do:
```shell
--ecs --ecs.cluster="dashboard-dev"
```
It is working ?


Next time, could you go to the [Traefik community Slack channel](https://traefik.herokuapp.com) before open an issue?

**Comment by ldez** [comment]
https://github.com/containous/traefik/blob/dd23ceeeadadb4c2e5c2cf0f42944e4f613b9207/provider/ecs/ecs.go#L242-L250

As you can see the deprecated  `--ecs.cluster` use the same slice than the new `--ecs.clusters`.

When I read the code and when I use the same parser for others options, I can say that the valid syntax is:
```shell
--ecs --ecs.clusters="dashboard-dev,dashboard-staging,dashboard-prod"
```

**Comment by zyzop** [comment]
Well you wont believe it but
`--ecs --ecs.clusters=dashboard-dev`
is the only way that works.

**Comment by ldez** [comment]
Do you use this option in a compose file?


Because when I do `sudo ./traefik --ecs.clusters="dashboard-dev"`

I have this log: `time="2017-09-22T21:25:43+02:00" level=info msg="ECS Clusters: [dashboard-dev]" `

see the difference:
- me : `ECS Clusters: [dashboard-dev]`
- you : `ECS Clusters: ["dashboard-dev"]`

you have another problem.

**Comment by zyzop** [comment]
Well I put this into ECS task definition,
it looks like this ( a part of it )
```
      "readonlyRootFilesystem": null,
      "image": "traefik:v1.4",
      "command": [
        "--consul",
        "--dynamodb",
        "--dynamodb.region=eu-west-1",
        "--ecs",
        "--ecs.cluster=template-basic-dev"
      ],
      "user": null,
      "dockerLabels": null,

```
and that's it. Then Amazon parses it and starts my container.
I guess I'll go with autodiscover then.

**Comment by ldez** [comment]
ok I think you must use single quote:

```
"--ecs.cluster='template-basic-dev'"
```

**Comment by ldez** [comment]
> But please take into account my remark about empty clusters that I made earlier.

Could you open a new issue ?
