### ISSUE TITLE
Feature Request: Configurable sticky cookie name

### ISSUE THREAD

**Issue by MichaelErmer** [containous/traefik#2175]
### Do you want to request a *feature* or report a *bug*?

*feature*

This feature request is related to https://github.com/containous/traefik/issues/1574 and https://github.com/containous/traefik/pull/1716, https://github.com/containous/traefik/pull/1712 already had the perfect solution but was dropped.

For heavy traffic applications like ours it would be very good if the LB cookie name would be configurable, the old implementation already had a VERY long cookie name, now it can become even longer, what we see with 1.4RC3 is `_TRAEFIK_BACKEND_backend-adserver-production` at ~800M Requests per day, this cookie name alone accounts for ~35GB of traffic.

It would be great to have a) the backend addition https://github.com/containous/traefik/pull/1716#issuecomment-307330224 optional and b) to make the cookie name configurable, we are very careful with cookies, 99% of our users only have a cookie i=someid, so it would be good if we could use `t=` or `_=` for traefik.

**Comment by ldez** [comment]
Every time someone does not respect the issue's template, a little bunny dies.

<details>

![southpark - estrella kill rabbit](https://user-images.githubusercontent.com/5674651/27143914-3cea7896-5130-11e7-81f8-02d8ac2da7a7.gif)
![southpark - estrella kill rabbit2](https://user-images.githubusercontent.com/5674651/27143924-49104c72-5130-11e7-82ae-ccedbd5dfa1c.gif)

</details>
<br>

Please edit your issue description to respect the [issue template](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE.md) as much as possible.

**Comment by MichaelErmer** [comment]
@ldez I added the one headline related to this feature request.

**Comment by ldez** [comment]
@MichaelErmer Sorry I closed by mistake.

**Comment by indrekj** [comment]
This would be nice. Especially because #1716 was not a backward compatible change. Would make the upgrade process easier.

**Comment by emilevauge** [comment]
Thanks for your feedback @MichaelErmer, a PR will follow up soon :)

**Comment by traefiker** [comment]
Closed by #2232.
