### ISSUE TITLE
dynamic upstream load balancer

### ISSUE THREAD

**Issue by mavencode01** [containous/traefik#218]
Am wondering how can I do dynamic upstream load balancer with this amazing tool.

I'm trying to find a way to roundrobin request to my services based on an Id in my request header.

For example, all premium users can be routed to a different upstream servers and regular users routed to another servers.

Any ideas ?

**Comment by emilevauge** [comment]
Hi @mavencode01 
You want to route request based on headers?

**Comment by mavencode01** [comment]
@emilevauge correct...any idea how to do this ?

**Comment by emilevauge** [comment]
You can use `Headers` rule to route your traffic for example: http://docs.traefik.io/basics/#frontends

**Comment by ldez** [comment]
I'll close this issue, because I think the question is answered, but feel free to continue the conversation.
