### ISSUE TITLE
Sticky backend isn't detected as being unavailable (with consulCatalog)

### ISSUE THREAD

**Issue by aksdb** [containous/traefik#2192]
### Do you want to request a feature or report a bug?
BUG (probably a regression of #1299)

### What did you do?
Using the `consulCatalog` I started a service redundant with the tag `traefik.backend.loadbalancer.sticky=true`. I started a request against that endpoint using a browser then took down the service instance specified in the cookie.

### What did you expect to see?
A response from the other, still intact instance as well as a new stick cookie referring to the new service.

### What did you see instead?
"Bad Gateway"
Reloading multiple times didn't work. Waiting several minutes didn't work. Only removing the cookie worked.

### Output of traefik version:
```
Version:      v1.4.0-rc3
Codename:     roquefort
Go version:   go1.9
Built:        2017-09-18_04:38:27PM
OS/Arch:      linux/amd64
```

**Comment by ldez** [comment]
Fixed by #2216
