### ISSUE TITLE
multiple toml file not recognised for [file] backend

### ISSUE THREAD

**Issue by linuxexp** [containous/traefik#2194]
I have simple toml configuration file    

`
defaultEntryPoints = ["http"]
logLevel = "DEBUG"
debug = true
[entryPoints]
  [entryPoints.http]
  address = ":80"

[file]
 directory = "/etc/traefik/rules.d/"
 watch = true
`

the toml files inside rules.d/ are not recognised nor loaded, I am using latest docker build of traefik. If I use filename instead of directory, it works.

**Comment by ldez** [comment]
Thanks for interest 👍 

1. I suppose you are using 1.3.8 (please respect issue template when you open an issue)
2. the support of `directory` come with 1.4 (#1672)

**Comment by JesusIslam** [comment]
I am using v1.4.4, it doesn't work too.
