### ISSUE TITLE
Feature Request: LXD Backend

### ISSUE THREAD

**Issue by async-cl** [containous/traefik#2195]
Anyone working on an LXD Backend?

LXD being very similar to Docker in architecture, it seems to me that converting the Docker backend to an LXD backend is possibly low hanging fruit.

I like the idea of having an outer Traefik proxy to LXD containers, each of which then use Traefik to proxy to Docker containers. The symmetry here is too nice to ignore.

If anyone has any comments on this or are working on it already let me know, as it's something I have a use case for.

Thanks

Ritchie

**Comment by emilevauge** [comment]
@async-cl I'm sorry, but we don't plan to support LXD for now. I will close this one then :)

**Comment by corradomatt** [comment]
@async-cl did you attempt to make this work yourself? I'm very interested in exploring this in my stack.
