### ISSUE TITLE
Flaky Integration Test: AccessLog TestAccessLog

### ISSUE THREAD

**Issue by marco-jantke** [containous/traefik#2204]
### Do you want to request a *feature* or report a *bug*?

*bug*

### Summary

- *Which test is flaky?* -> `AccessLogSuite.TestAccessLog`
- *Cause* -> Log line does not match expected format. Probably because frontend/backend was not yet registered and thus log line contains `-` instead of `frontend` name.
- *Failed build* -> https://semaphoreci.com/containous/traefik/branches/master/builds/188

### Log excerpt

```
----------------------------------------------------------------------
FAIL: access_log_test.go:27: AccessLogSuite.TestAccessLog

access_log_test.go:82:
    CheckAccessLogFormat(c, line, i)
access_log_test.go:102:
    c.Assert(tokens[11], checker.HasPrefix, "frontend")
... obtained string = "-"
... prefix string = "frontend"
```

**Comment by ldez** [comment]
Already fixed
