### ISSUE TITLE
Flaky Integration Test: ConsulCatalogSuite TestSingleService

### ISSUE THREAD

**Issue by marco-jantke** [containous/traefik#2206]
### Do you want to request a *feature* or report a *bug*?

*bug*

### Summary

- *Which test is flaky?* -> ` ConsulCatalogSuite.TestSingleService`
- *Cause* -> Consul seems not able to start properly.
- *Failed build* -> https://semaphoreci.com/containous/traefik/branches/master/builds/185

### Log excerpt

```
----------------------------------------------------------------------
FAIL: consul_catalog_test.go:122: ConsulCatalogSuite.TestSingleService

consul_catalog_test.go:148:
    c.Assert(err, checker.IsNil)
... value *errors.errorString = &errors.errorString{s:"try operation failed: got status code 500, wanted 200"} ("try operation failed: got status code 500, wanted 200")
```

**Comment by ldez** [comment]
Fixed by #2148
