### ISSUE TITLE
Plugins, Benchmarking

### ISSUE THREAD

**Issue by madhurranjan** [containous/traefik#221]
I've been trying to search for documentation that shows benchmarking of traefik against nginx. Can you point me out to benchmarking  docs if available?   I'd like to use Traefik as part of Kubernetes and I'd like to see if it meets our needs in terms of performance.

I've another question . Do you see Traefik support some sort of plugin model like lua with nginx ?

**Comment by emilevauge** [comment]
Hi @madhurranjan 

There is only basic benchmarks in the doc for now: https://github.com/containous/traefik/blob/master/docs/index.md#benchmarks

There is no plugin support un Traefik right now. Go does not provide any way to create dynamic library.
But I'm thinking of creating a plugin mechanism based on javascript, maybe one day ;)
In the meantime, you can provide custom templates for your backends (docker, marathon, etcd, consul...).

**Comment by drasko** [comment]
@emilevauge I think Lua is better candidate here (for plugin scripting). You can take a look at how Erlio team handles this for VerneMQ: https://github.com/erlio/vmq_diversity

**Comment by Dongss** [comment]
Looking forward to plugin support too ...
