### ISSUE TITLE
On-demand LetsEncrypt does not work with multiple `Host` frontends

### ISSUE THREAD

**Issue by else** [containous/traefik#2228]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I want to access a frontend that has two or more `Host` rules configured via TLS using LetsEncrypt certificates and expect the correct certificate to be returned.

I have not configured any special `acme.domain`s because I expect this to be entirely dynamic depending on my deployments. I am using a Consul catalog backend for automatic service discovery and tag my services accordingly.

In this case I have a consul service definition that is tagged like this:

```
service {
	// …
	tags = [
		"traefik.enable=true",
		"traefik.frontend.rule=Host:ingress-elb-2045608753.eu-central-1.elb.amazonaws.com,acmetest.example.com",
	]
}
```

### What did you expect to see?

I expected the correct certificate to be requested from LetsEncrypt and returned by traefik depending on the host that I am accessing.

### What did you see instead?

When I accessed `https://acmetest.example.com` in my browser I got a certificate error because the browser was presented with the default traefik certificate.

Things work correctly when I remove the `ingress-elb-2045608753.eu-central-1.elb.amazonaws.com` host from the definition and only the `Host:acmetest.example.com` rule is left. It looks like the second host poses a problem to traefik because it cannot correctly determine the host to be used for generating the ACME challenge.

I also tried adding a separate frontend rule tag for each domain but got the same results.

### Output of `traefik version`:

```
Version:      v1.4.0-rc4
Codename:     roquefort
Go version:   go1.9
Built:        2017-10-02_02:19:32PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

I am running traefik (experimental, `cf508b6d481599c4ffd83c52e48beb9cf561314a`) via Nomad via Docker with the following args:

```
"--loglevel=DEBUG",
"--defaultentrypoints=http,https",
"--entrypoints=Name:http Address::80",
"--entrypoints=Name:https Address::443 TLS",
"--web.readonly",
"--consul",
"--consulcatalog",
"--consulcatalog.watch",
"--acme",
"--acme.acmelogging",
"--acme.entrypoint=https",
"--acme.email=me@example.com",
"--acme.onhostrule",
"--acme.ondemand",
"--acme.storage=traefik/acme/account"
```

(Instead of `acmetest.example.com` I obviously have configured an existing domain name with proper records.)

### If applicable, please paste the log output in debug mode (`--debug` switch)

```
time="2017-10-08T19:24:44Z" level=debug msg="Look for provided certificate to validate [acmetest.example.com]..."
time="2017-10-08T19:24:44Z" level=debug msg="No provided certificate found for domains [acmetest.example.com], get ACME certificate."
time="2017-10-08T19:24:44Z" level=debug msg="Challenge GetCertificate acmetest.example.com"
time="2017-10-08T19:24:44Z" level=debug msg="ACME got nothing acmetest.example.com"
```

**Comment by nmengin** [comment]
@else Can you share all the Træfik logs in DEBUG mode?

**Comment by else** [comment]
I tried it again and it works fine. It was probably another problem.
