### ISSUE TITLE
Disable Cipher Suites using "3DES"

### ISSUE THREAD

**Issue by patrickbaber** [containous/traefik#2247]
I get "WEAK" warnings when I'm testing the HTTPS entrypoint with [https://www.ssllabs.com/ssltest/](https://www.ssllabs.com/ssltest/) and there is no option in the `traefik.toml` to disable cipher suites with "3DES", like "TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA".

I would by nice to get slightly more options for HTTPS connections. Thanks!

Result on ssllabs.com/ssltest/:

![bildschirmfoto 2017-10-11 um 13 54 59](https://user-images.githubusercontent.com/3321255/31439357-26bd6664-ae8c-11e7-9e76-07e7ca42131b.png)

**Comment by dtomcej** [comment]
Hello @patrickbaber, in http://docs.traefik.io/configuration/entrypoints/#specify-minimum-tls-version,

you have the option of specifying which cipher suites you would like traefik to allow.

You can provide it a list of Non-3DES suites.

The full enabled list can be found at https://github.com/containous/traefik/blob/871d097b30ac2adc581f650c74e7e6faee1a4f60/configuration/configuration.go#L390

Thanks!

**Comment by patrickbaber** [comment]
Thanks for the hint, but I can't get it working with traefik 1.3 or the RC 5 of version 1.4.

My entrypoint config looks like this:

```
[entryPoints]
  [entryPoints.http]
  address = ":80"
     [entryPoints.http.redirect]
       entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
    minVersion = "VersionTLS10"
    cipherSuites = ["TLS_RSA_WITH_AES_128_CBC_SHA256", "TLS_RSA_WITH_AES_128_GCM_SHA256", "TLS_RSA_WITH_AES_256_GCM_SHA384", "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA", "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA", "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256", "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384", "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"]
```

The browser can't establish a connection to the server via HTTPS. The log doesn't show anything special about the TLS configuration. The certificates came from ACME. What am I doing wrong?

**Comment by dtomcej** [comment]
@patrickbaber you can view the loaded configuration via the Debug log, to confirm that the specified cipher suites have been selected.

What does the debug log say?
