### ISSUE TITLE
"expected value but found '\n' instead" consul_catalog

### ISSUE THREAD

**Issue by gabrielfsousa** [containous/traefik#2249]
### Do you want to request a *feature* or report a *bug*?

bug

### What did you do?

added tag on service / app `traefik.backend.loadbalancer.stickiness=true`

### What did you expect to see?

Sticky session cookie name.

### What did you see instead?

have this error:
```
level=error msg="Failed to create config" error="Near line 42 (last key parsed 'Backends.backend-myappl.LoadBalancer.Stickiness.cookieName'): expected value but found '\n' instead"
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
version:v1.4.0-rc5
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# (paste your configuration here)
```

**Comment by traefiker** [comment]
Closed by #2251.
