### ISSUE TITLE
Please add definition for variables using in RFC2136 dns provider 

### ISSUE THREAD

**Issue by tiukhtinvladimir** [containous/traefik#2281]
### Do you want to request a *feature* or report a *bug*?

feature

### What did you do?

Set up DNS challenge using RFC2136 dns provider

Traefik allows us to use variables to set up provider parameters:
```
RFC2136_TSIG_KEY
RFC2136_TSIG_SECRET
RFC2136_TSIG_ALGORITHM
RFC2136_NAMESERVER
```
Unfortunately there is no definition for this, and I spend some hours before finally managed to get it work. For example all what I was getting form traefik log was:
```bad key algorithm```
There should be a description like:
For HmacMD5 use "hmac-md5.sig-alg.reg.int." as value
For HmacSHA1 use "hmac-sha1." as value
For HmacSHA256 use "hmac-sha256." as value
For HmacSHA512 use "hmac-sha512." as value

Similar for RFC2136_TSIG_KEY - it should be exactly the same as configured on DNS server side

### Ps

Thanks. If I can help documenting this - I am ready to share my experience

**Comment by tiukhtinvladimir** [comment]
One more thing I have found out - no upper case are allowed in RFC2136_TSIG_KEY otherwise getting ```dns: no secrets defined```

**Comment by GabrielL** [comment]
I am trying to use ddns updates for the DNS challenge. The documentation for the environment variable is in [lego](https://github.com/xenolf/lego), the acme client library used.

From https://github.com/xenolf/lego/blob/master/providers/dns/rfc2136/rfc2136.go#L26 :

```
// NewDNSProvider returns a DNSProvider instance configured for rfc2136
// dynamic update. Configured with environment variables:
// RFC2136_NAMESERVER: Network address in the form "host" or "host:port".
// RFC2136_TSIG_ALGORITHM: Defaults to hmac-md5.sig-alg.reg.int. (HMAC-MD5).
// See https://github.com/miekg/dns/blob/master/tsig.go for supported values. 
// RFC2136_TSIG_KEY: Name of the secret key as defined in DNS server configuration.
// RFC2136_TSIG_SECRET: Secret key payload.
// RFC2136_TIMEOUT: DNS propagation timeout in time.ParseDuration format. (60s)
// To disable TSIG authentication, leave the RFC2136_TSIG* variables unset.
```

And the values for `RFC2136_TSIG_ALGORITHM`: https://github.com/miekg/dns/blob/master/tsig.go#L17

```go
// HMAC hashing codes. These are transmitted as domain names.
const (
	HmacMD5    = "hmac-md5.sig-alg.reg.int."
	HmacSHA1   = "hmac-sha1."
	HmacSHA256 = "hmac-sha256."
	HmacSHA512 = "hmac-sha512."
)
```

**Comment by GabrielL** [comment]
Also, It seems that the present documentation is misleading, the correct name is rfc2136 and not RFC2136.

**Comment by dtomcej** [comment]
Hello @tiukhtinvladimir and @GabrielL, We have updated our documentation significantly this year, and have added a new section to document what the different Lego DNS providers require. We have directly linked the provider to the rfc2136 implementation to give clarity as to what is required.

Do you think this is still an issue? or do you think we can close this ticket?
Thanks!

**Comment by GabrielL** [comment]
That is much better now, at least there is the link to LEGO to see its documentation (sadly, only the code, but better than nothing)

Thanks!

**Comment by dtomcej** [comment]
Excellent!

I will close this ticket.
