### ISSUE TITLE
Brew formula

### ISSUE THREAD

**Issue by vonagam** [containous/traefik#2300]
Just wanted to inform that brew (package manager for mac) now has a formula for traefik:
https://github.com/Homebrew/homebrew-core/blob/master/Formula/traefik.rb

So now on mac it is possible to install traefik through `brew install traefik`.

You may want to add this info to "Test it" section of README.md. Or not.

**Comment by ldez** [comment]
Thanks for the information 👍 

I added a link into our community wiki https://awesome.traefik.io.
