### ISSUE TITLE
Getting "404 page not found" when accessing the load balanced url

### ISSUE THREAD

**Issue by iyermahadevan** [containous/traefik#231]
I have traefik using marathon as the backend with the following config
The http://__traefikip__:8080 shows me the backend instances started by marathon/mesos, looks ok
When I access port 80 I get a "404 page not found"
I am not using any dns in my mesos/marathon setup, maybe I have a problem with the domain ?
I do not see any logs in the stdout, I am using the traefik/containous image
----------------
#traefik.toml
port = ":80"
[web]
address = ":8080"
[marathon]
endpoint = "http://__marathonip__:8080"
networkInterface = "eth0"
watch = "true"
domain = "marathon.localhost"
logLevel = "DEBUG"
--------------------------------------

**Comment by emilevauge** [comment]
@iyermahadevan please connect to [slack](https://traefik.herokuapp.com/) to get support :)
