### ISSUE TITLE
Disable or filter TLS from error logs

### ISSUE THREAD

**Issue by MichaelErmer** [containous/traefik#2319]
### Do you want to request a *feature* or report a *bug*?

*feature*

### What did you do?

Run traefik with logLevel ERROR

### What did you expect to see?

logs about severe errors

### What did you see instead?

100-300x per second `server.go:2848: http: TLS handshake error`

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
v1.4.0 / roquefort
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
docker swarm
```

**Comment by mmatur** [comment]
Duplicate of #1827

**Comment by MichaelErmer** [comment]
Oh yes, the line number changed...
