### ISSUE TITLE
Add ability to disable checking acme record after updating DNS

### ISSUE THREAD

**Issue by tiukhtinvladimir** [containous/traefik#2321]
### Do you want to request a *feature* or report a *bug*?

feature

### What did you do?

So, traefik after updating DNS in case of acme DNS challenge is trying to verify the record. But if for update it is using server defined in RFC2136_NAMESERVER variable, for record validation it is using server defined in /etc/resolv.conf or whatever. If there is split dns feature is in place, server will not able to resolve the record, because it does not exist in local view - it is exist only in global view.
```
ERRO[2017-10-25T11:50:00Z] map[development.example.com:Time limit exceeded. Last error: NS ns01.example.com. returned NXDOMAIN for _acme-challenge.development.example.com.]
```
The idea is to add abilit to disable record validation, or add ability to chose the server for record validation

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.4.1
Codename:     roquefort
Go version:   go1.9.1
Built:        2017-10-24_05:25:28PM
OS/Arch:      linux/amd64
```

**Comment by nmengin** [comment]
Hello @tiukhtinvladimir. Many thanks for your interest in the project.

I'm not sure to really understand your need.

Do you want to add an option in the frontends you defined in the way to disable ACME as demand(like `traefik.frontend.acme.disable=true`?

**Comment by tiukhtinvladimir** [comment]
Hi @nmengin. Thanks for your reply. No, I would like to get something different. I am talking about DNS challenge using RFC2136. So, in my current understanding of the problem, it works like this:
1. Let's encrypt asks traefik to put token into DNS
2. Traefik contacts DNS server defined in RFC2136_NAMESERVER variable
3. DNS server accept an update from traefik
4. Traefik tries to verify the record doing new DNS query to server defined in RFC2136_NAMESERVER variable
5. If the record is OK traefik replies to let's encrypt
6. let's encrypt does new DNS query to NS servers defined for this zone
7. If the record is OK let's encrypt issues certificate

I would like to have ability to influence on the step 4, means I would like to have ability to change server IP or to have ability to switch verification completely, because it causes server confusion if you use split DNS function (traefik updates server on local interface, but verification should happen on global interface)

**Comment by nmengin** [comment]
Many thanks for the information @tiukhtinvladimir .

Maybe I am wrong but I guess all this kind of operation are done in LEGO and we can not modify the behavior.

Maybe can you open an issue it [lego](https://github.com/xenolf/lego).

I close the issue but feel free to re-open it if you think we can do anything in Træfik.
