### ISSUE TITLE
Add ability to select which traefik to use

### ISSUE THREAD

**Issue by gabrielfsousa** [containous/traefik#2322]
### Do you want to request a *feature* or report a *bug*?

feature

### What did you expect to see?
several traefik with ONE consul

In a BIG swarm, with many microservices/apps , would be nice to use several traefiks,
Using service/conteiner label or consul DC to specified on witch traefik will be configured the MS/APP

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
1.4
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
docker swarm + consul
```

**Comment by ldez** [comment]
Every time someone does not respect the issue's template, a little bunny dies.

<details>

![southpark - estrella kill rabbit](https://user-images.githubusercontent.com/5674651/27143914-3cea7896-5130-11e7-81f8-02d8ac2da7a7.gif)
![southpark - estrella kill rabbit2](https://user-images.githubusercontent.com/5674651/27143924-49104c72-5130-11e7-82ae-ccedbd5dfa1c.gif)

</details>
<br>

Please edit your issue description to respect the [issue template](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE.md) as much as possible.

**Comment by gabrielfsousa** [comment]
updated ;)

**Comment by ldez** [comment]
I think `constraints` can be use in this case https://docs.traefik.io/configuration/commons/#constraints

**Comment by gabrielfsousa** [comment]
yeah, but i have to change the image name... and restart the traefik .. i think in conteiner/service label or consul datacenter would be much better

**Comment by gabrielfsousa** [comment]
`docker service create --name traefik-consul2 --network mynet --publish 90:80 --publish 8093:8080 --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock containous/traefik --consulcatalog --consulcatalog.endpoint="consul:8500" --web --logLevel=DEBUG --consulcatalog.constraints='tag==traefik2' --constraints='tag==traefik2'`

logs

`traefik-consul2.1.oxxrnimefkyc@docker01    | time="2017-10-25T16:07:49Z" level=info msg="Server configuration reloaded on :80"
traefik-consul2.1.oxxrnimefkyc@docker01    | time="2017-10-25T16:07:49Z" level=debug msg="Service consul pruned by 'tag==traefik2' constraint"
traefik-consul2.1.oxxrnimefkyc@docker01    | time="2017-10-25T16:07:49Z" level=debug msg="Fetching service" service=myappl
traefik-consul2.1.oxxrnimefkyc@docker01    | time="2017-10-25T16:07:49Z" level=debug msg="Service myappl pruned by 'tag==traefik2' constraint"
traefik-consul2.1.oxxrnimefkyc@docker01    | time="2017-10-25T16:07:49Z" level=debug msg="Service myappl pruned by 'tag==traefik2' constraint"
traefik-consul2.1.oxxrnimefkyc@docker01    | time="2017-10-25T16:07:49Z" level=debug msg="Service myappl pruned by 'tag==traefik2' constraint"
traefik-consul2.1.oxxrnimefkyc@docker01    | time="2017-10-25T16:07:49Z" level=debug msg="Service myappl pruned by 'tag==traefik2' constraint"
traefik-consul2.1.oxxrnimefkyc@docker01    | time="2017-10-25T16:07:49Z" level=debug msg="Service myappl pruned by 'tag==traefik2' constraint"
traefik-consul2.1.oxxrnimefkyc@docker01    | time="2017-10-25T16:07:49Z" level=debug msg="Service myappl pruned by 'tag==traefik2' constraint"
traefik-consul2.1.oxxrnimefkyc@docker01    | time="2017-10-25T16:07:49Z" level=debug msg="Configuration received from provider consul_catalog: {}"
traefik-consul2.1.oxxrnimefkyc@docker01    | time="2017-10-25T16:07:49Z" level=info msg="Skipping same configuration for provider consul_catalog"
`

i dont have any frontend and backend :(

**Comment by gabrielfsousa** [comment]
constraint isnt working :(

**Comment by ldez** [comment]
Before open an issue, could you ask question on:
- the [Traefik community Slack channel](https://traefik.herokuapp.com)

Thanks.

**Comment by ldez** [comment]
Seems related to #2009

**Comment by bitsofinfo** [comment]
@gabrielfsousa did u ever end up w/ a solution for this?

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Slack workspace](https://traefik.herokuapp.com/) for more [community #support](https://traefik.slack.com/messages/C0CDT22PJ/).
