### ISSUE TITLE
constraint isnt working

### ISSUE THREAD

**Issue by gabrielfsousa** [containous/traefik#2326]
### Do you want to request a *feature* or report a *bug*?

bug

### What did you do?

`docker service create --name traefik-consul2 --network mynet --publish 90:80 --publish 8093:8080 --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock traefik:1.4.1 --consulcatalog --consulcatalog.endpoint="consul:8500" --web --logLevel=DEBUG --consulcatalog.constraints='tag==traefik*'`

### What did you expect to see?

all services with traefik tag on traefik

![image](https://user-images.githubusercontent.com/722744/32012276-3ad17ce8-b9af-11e7-878b-9087fed528b3.png)

### What did you see instead?

![image](https://user-images.githubusercontent.com/722744/32011611-2a47607e-b9ad-11e7-95a2-f192c1e65b6e.png)

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
1.4.1
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
docker + consul
```

### If applicable, please paste the log output in debug mode (`--debug` switch)

![image](https://user-images.githubusercontent.com/722744/32012236-20d279c8-b9af-11e7-9536-c46223e679f3.png)

**Comment by mmatur** [comment]
@gabrielfsousa 
With you constraint `--consulcatalog.constraints='tag==traefik*'` the correct tag in consul is `traefik.tags=traefik2` and not `traefik2`

**Comment by gabrielfsousa** [comment]
i think traefik.tags is deprecated 

`Error here : invalid argument "traefik.tags==traefik2" for --consulcatalog.constraints=traefik.tags==traefik2: constraint must be tag-based. Syntax: tag==us-*
traefik is a modern HTTP reverse proxy and load balancer made to deploy microservices with ease.
Complete documentation is available at https://traefik.io`

**Comment by ldez** [comment]
@gabrielfsousa 
`--consulcatalog.constraints='tag==traefik*'`
and **in**  consul the correct tag  is `traefik.tags=traefik2`

**Comment by ldez** [comment]
I'll close this issue, because I think the question is answered, but feel free to continue the conversation on the [Traefik community Slack channel](https://traefik.herokuapp.com)
