### ISSUE TITLE
[consul] allow using "stale" data

### ISSUE THREAD

**Issue by jippi** [containous/traefik#2332]
The consul Go SDK allow using `stale` data - [meaning it can talk to any consul client to get information from the catalog instead of the elected leader](https://github.com/hashicorp/consul/blob/master/api/api.go#L72)

Due to how raft work, stale data usually mean 50ms delay in updates, and everything otherwise works like normal (blocked queries etc)

This setting is crucial in scaling out usage of consul, and would be a nice improvement to the consul catalog backend, and should probably always be default on

I can submit a PR with this change if needed

**Comment by Juliens** [comment]
@jippi Happy to see a PR if you can :wink:

**Comment by jippi** [comment]
we are unfortunately not using traefik any more due to other issues :)

**Comment by ldez** [comment]
@jippi could you give us more information about those other issues?

**Comment by josegonzalez** [comment]
> Note: I work with @jippi .

We decided against Traefik as it performed extremely poorly in production due to the aforementioned stale read issue. We are currently using Linkerd and mostly happy with it (apart from grpc issues).  Hope that clarifies things.
