### ISSUE TITLE
Custom response headers are overwritten by backend

### ISSUE THREAD

**Issue by pdf** [containous/traefik#2341]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Set a custom response header that conflicts with headers sent by the backend.

### What did you expect to see?

Custom header value equal to the value set in traefik configuration.

### What did you see instead?

Custom header value overwritten by value sent from backend.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.4.1
Codename:     roquefort
Go version:   go1.9.1
Built:        2017-10-24_05:25:28PM
OS/Arch:      linux/amd64
```

I discovered this while writing a new middleware to allow header rewriting.  This occurs because the headers middleware is injected only once, and tries to set both request and response headers, before the response has been retrieved from the backend.

Unfortunately, the way the load-balancers have been written, they do not function as middleware, and so additional middleware cannot be injected to process the response.  I started looking at it, but onboarding that whole chain and doing all the plumbing exceeds my time-budget currently.

**Comment by dtomcej** [comment]
Hmmmm. If backends are setting the response headers, Im not sure that we would want them overwritten by traefik. I would assume that backend responses would be held as superior. Not sure if this is outside of the intended behavior.

Perhaps we should note that in the documentation.

**Comment by ldez** [comment]
@pdf could try with 1.5.0-rc1 ?

**Comment by pdf** [comment]
Looks good, thanks for the fix @mmatur and for the follow-up @ldez :heart:
