### ISSUE TITLE
Context Canceled error  with heavy load

### ISSUE THREAD

**Issue by warroyo** [containous/traefik#2346]
I mentioned this in an older issue(https://github.com/containous/traefik/issues/1926) but I am creating a new one to hopefully get some visibility.

version: `1.4.0`

I am seeing the `context canceled` error. this is extremely noticeable when under heavy load.

i ran a, performance test with `wrk` 

`wrk -t10 -c100 -d20s --latency`

here are the results:

```
10 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   527.92ms  218.30ms   1.89s    65.72%
    Req/Sec    19.46     11.15    60.00     82.91%
  Latency Distribution
     50%  517.02ms
     75%  684.67ms
     90%  800.57ms
     99%    1.06s
  3023 requests in 20.09s, 3.21MB read
  Socket errors: connect 0, read 0, write 0, timeout 99
Requests/sec:    150.48
Transfer/sec:    163.84KB
```

notice the 99 timeouts these are all `time="2017-10-27T21:44:46Z" level=warning msg="Error forwarding to http://10.42.24.15:80, err: context canceled" `

if i increase the connections it gets much worse sometimes to the point all requests are failing

are there some settings that need to be tweaked for heavier load? 

not sure if this could be related https://github.com/containous/traefik/issues/1849

**Comment by dottgonzo** [comment]
i've the same problem on ruby on rails heavy app

**Comment by timoreimann** [comment]
Sorry for losing attention on #1926. In order to stay focused, I'll close this issue and comment on the other one. Let's see if we can figure out the reason.

Thanks for the bump!
