### ISSUE TITLE
Websocket metrics

### ISSUE THREAD

**Issue by geekgonecrazy** [containous/traefik#2349]
### Do you want to request a *feature* or report a *bug*?
Feature

### Details
In the metrics provided we have visibility to all http requests.  Which is great to see that kind of traffic coming in.  But we have no way of seeing how many websockets are open.

I have traefik in front of several servers and one of the primary data channels is websockets.  Which works great.  I just have no insight into the websockets currently being proxied through by traefik.

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
Traefik as a deployment in kubernetes acting as my ingress controller.

**Comment by marco-jantke** [comment]
HI @geekgonecrazy, which metrics provider do you use? I just opened https://github.com/containous/traefik/pull/2567 which provides open connections on a backend or entrypoint level split up by protocol (http, SSE, websocket).

**Comment by geekgonecrazy** [comment]
@marco-jantke prometheus.  Your PR looks very interesting!  I'll take a look

**Comment by geekgonecrazy** [comment]
Familiar with go, but not as familiar with the code base here.

But from what I can tell you are tracking open connections.  Which would solve what I'm looking for.
