### ISSUE TITLE
no matching manifest for linux/amd64 in the manifest list entries

### ISSUE THREAD

**Issue by JurJean** [containous/traefik#2359]
### Do you want to request a *feature* or report a *bug*?
Bug

### What did you do?
docker pull traefik:roquefort
docker pull traefik:latest

### What did you expect to see?
traefik image pulled

### What did you see instead?
no matching manifest for linux/amd64 in the manifest list entries

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
I have the same result on various Ubuntu servers and macbooks.

**Comment by mmatur** [comment]
@JurJean I close this issue because it is due to a docker-library [issue](https://github.com/docker-library/official-images/issues/3673)

**Comment by JurJean** [comment]
Thnx for your response, @mmatur
