### ISSUE TITLE
Docker manifest broken?

### ISSUE THREAD

**Issue by sokoow** [containous/traefik#2360]
### Do you want to request a *feature* or report a *bug*?

Issue

### What did you do?

Tried to use examples/k8s/trafeik-ds.yaml on my new kube cluster

### What did you expect to see?

Working traefik DS on my kube

### What did you see instead?
```
  2m		1m		4	kubelet, 10.255.13.173	spec.containers{traefik-ingress-lb}	Warning		Failed			Failed to pull image "traefik": rpc error: code = 2 desc = no supported platform found in manifest list
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

Latest

**Comment by tiangolo** [comment]
Docker Hub amd64 build server is temporarily down.

Check out this comment: https://github.com/docker-library/official-images/pull/3668#issuecomment-341711153

And follow this issue: https://github.com/docker-library/official-images/issues/3673

Meanwhile, as a workaround, you can set the tag to `traefik:v1.4.1`

**Comment by ldez** [comment]
It's fixed! 🎉
