### ISSUE TITLE
traefik won't start in rancher version v1.6.10 - Unhealthy

### ISSUE THREAD

**Issue by MichelDiz** [containous/traefik#2366]
### Do you want to request a *feature* or report a *bug*?

Appears to be a bug

### What did you do?

1 - Start a VM in Google Cloud. n1-standard-1 (1 vCPUj, 3,75 GB de mem)
2 - Install Docker in CentOS 7
3 - Install Rancher Latest
4 - Install Rancher Agent in the same Machine (mb is this problem?)
5 - I go to the catalog, I look for Traefik. I put the parameters, I generate the API key and so on.
6 - Fails

### What did you expect to see?
Traefik starting and working

### What did you see instead?

Neither starts the container and already gives Unhealthy

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
(paste your output here)
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

answers.txt ==> https://pastebin.com/VsJM7ngy
rancher-compose.yml ==>https://pastebin.com/HYExd0Gj
docker-compose.yml.tpl ==>https://pastebin.com/bRXAFAVM
Readme ==>https://pastebin.com/r790wqc7

rawmind/alpine-traefik:1.4.0-3
Rancher | v1.6.10
-- | --
Cattle | v0.183.22
User Interface | v1.6.23
Rancher CLI | v0.6.4
Rancher Compose | v0.12.5
CentOS Linux 7 (3.10.0)
Docker  17.09.0-ce

**Comment by SantoDE** [comment]
Hi @micheldiz,

Could you set traefik to debug (also the logLevel) and get us your log? :)

**Comment by MichelDiz** [comment]
how could I do this if traefik does not start? Is there any how?

**Comment by MichelDiz** [comment]
traefik is compatible with cloudflare?

**Comment by SantoDE** [comment]
What do you mean by compatible with cloud flare? Even if it’s exiting immediately, you should at least something in Rancher

**Comment by MichelDiz** [comment]
The "way" that I follow in this video https://www.youtube.com/watch?v=0zVwqWwHo5w worked

I think the problem is with this catalog version. Maybe is a bug from Rancher.

**Comment by MichelDiz** [comment]
>What do you mean by compatible with cloud flare?
The CloudFlare image is a "infra" stack. Has different approach and as it comes to a stack that DNS handles I thought would be conflicting. But I deactivated it and nonetheless the issue continued.
>Even if it’s exiting immediately, you should at least something in Rancher
Rancher just gives me simple logs. I posted above, I only have this information. He even din't "pull" the image from docker hub. So it's probably Rancher that is not compatible with some of the Stack configuration you offer in the catalog.

**Comment by MichelDiz** [comment]
However my problem is solved. But this continues, the issue related to catalog can lead to problems with other people.

If you want to repeat what I did, just follow the steps there at the beginning. I've done this same procedure even with other systems. I have tested in Debian, Rancher Os (I created my image) and CentOS.

**Comment by SantoDE** [comment]
Glad that it worked out. Thanks for pointing the catalog item. I’ll glve it a check :)

**Comment by MichelDiz** [comment]
Sorry to write again here, but just in case. I did a new test. I was able to easily install an old version of Traefik. Soon after I did upgrading version by version until I got the last one that I opened the issue. Only this version is interrupting the correct operation of the Traefik service..

Cheers.
