### ISSUE TITLE
Add support for InsecureSkipVerify option for each backend

### ISSUE THREAD

**Issue by ryayon** [containous/traefik#2367]
### Do you want to request a *feature* or report a *bug*?

I want to request a feature

### What did you do?

I think it is useful to add a "InsecureSkipVerify" possibilty for specific backends and not as a global parameter.

### What did you expect to see?

I want to be able to make sure some backends have correct SSL certificates while others, that I trust, although they have self signed certificate, can be reached by Traefik as reverse proxy (using file backend).

### What did you see instead?

I get the error ```x509: certificate signed by unknown authority``` once I try to access a SSL self signed certificated backend.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.4.2
Codename:     roquefort
Go version:   go1.9.2
Built:        2017-11-02_01:47:46PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# (paste your configuration here)
```

### If applicable, please paste the log output in debug mode (`--debug` switch)

```
time="2017-11-06T15:33:29Z" level=warning msg="Error forwarding to https://self_signed_certificate_website, err: x509: certificate signed by unknown authority"
```

**Comment by arno01** [comment]
Could this be closed in favor of https://github.com/containous/traefik/issues/3038 ?

**Comment by ryayon** [comment]
Hi,

I am not sure to understand the issue.
However, if you think it can be closed, then please proceed.

Regards,
Rudy

**Comment by arno01** [comment]
@ryayon well, IIUC, once https://github.com/containous/traefik/issues/3038 is implemented, there won't be ``InsecureSkipVerify`` option. Instead, Traefik will (optionally !) generate x509 certificate bits to use between itself and the backend service if the latter is running without TLS. And according to:
> For all server certificate verification, add support for certification revocation lists and verification depth. 
I presume there will be an option ``verifyDepth = 0`` (self-signed only) which will deprecate the need of ``InsecureSkipVerify`` option. Please correct me if I misunderstood the proposal.

As to your issue:

> I want to be able to make sure some backends have correct SSL certificates while others, that I trust, although they have self signed certificate, can be reached by Traefik as reverse proxy (using file backend).

You can work it around without the need for ``InsecureSkipVerify = true`` by using this script https://git.nixaid.com/arno/gencert

**Comment by ryayon** [comment]
Sounds good.
I close this issue.

**Comment by 12wrigja** [comment]
@arno01 I don't believe that Mutual TLS would accomplish this, as this is used for verifying the identity of clients connecting to a TLS-enabled server. In other words, it will not just "magically" enable TLS communication between an HTTP-only server and a TLS-enabled server. To correct your previous statement:

> Instead, Traefik will (optionally !) generate x509 certificate bits to use between itself and the backend service if the latter is running **with** TLS.

I do think this is a good idea however - adding another option (using a similar implementation strategy to the `passTLSCerts` functionality) would enable this.

ryayon, want to re-open this?

**Comment by arno01** [comment]
@12wrigja the [proposal](https://github.com/containous/traefik/issues/3038) clearly states 

> mutual TLS authentication **with backends**

So, IIUC, this is not to enable self-signed x509 certificate pass-through (``passTLSCerts``), but rather to enable TLS between the backend and the reverse proxy without the need to enable ``InsecureSkipVerify`` globally, instead the user will be able to do this selectively as the proposal shows.
As of verifying the identity of the clients connecting to a TLS-enabled server, the TLS termination will be done at the Traefik's side or somewhere higher.

> In other words, it will not just "magically" enable TLS communication between an HTTP-only server and a TLS-enabled server. 

Well, I think it actually already does this even with the global ``InsecureSkipVerify = true`` :-)

Please correct me if I am wrong.

**Comment by arno01** [comment]
@12wrigja as the proposal says it will deprecate the global ``InsecureSkipVerify`` option, I am naturally thinking it will allow skipping the certificate verification per backend, besides enabling the mutual TLS authentication.

> To get back to the matter at hand - it seems that we could enable this per-frontend pretty easily in a similar manner to the passTLSCerts option, but not per backend. 

If you are implying the mutual TLS authentication, then I am suggesting we continue discussing this matter in the [proposal](https://github.com/containous/traefik/issues/3038).

**P.S.**
I was not sure the proposal implies x509 bits generation by Traefik so I have added this point to the proposal.

**Comment by ryayon** [comment]
Hi,

I Don't know what to say actually.
My request remains the same.
If you see a solution, please proceed.
I prefer to let you discuss the technical parts although I think the request is pretty much simple and should be fixed with a same simple solution.

Rudy

**Comment by joeldeteves** [comment]
I agree with Rudy; this would be a really useful feature.
