### ISSUE TITLE
Invalid X-Forwarded-Port header

### ISSUE THREAD

**Issue by alkar** [containous/traefik#2373]
### What did you do?

Running `traefik` in kubernetes as an ingress controller. The hops to reach a pod are:

1. AWS ELB with SSL/TCP listeners (for SSL offloading) and proxy protocol enabled
2. traefik service nodePort (some high port)
3. traefik container (see arguments below)

I'm also running a simple 'http echo' service in kubernetes that prints the headers of the requests it receives.

### What did you expect to see? / What did you see instead?

When I'm hitting the echo service:

```console
$ curl https://foo.bar.baz/
{
    "url": "http://foo.bar.baz/",
    "protocol": "http",
    "host": "foo.bar.baz",
    "path": "/",
    "method": "GET",
    "headers": {
        "host": "foo.bar.baz",
        "user-agent": "curl/7.43.0",
        "accept": "*/*",
        "x-forwarded-for": "10.91.62.52",
        "x-forwarded-host": "foo.bar.baz",
        "x-forwarded-port": "80",
        "x-forwarded-proto": "http",
        "x-forwarded-server": "internal-ingress-tcp-proxy-8495446487-m6nw6",
        "x-real-ip": "10.91.62.52",
        "accept-encoding": "gzip"
    },
    "query": {},
    "body": {}
}
```

I understand that `X-Forwarded-Proto` reads `http`, [since traffic hitting traefik is not encrypted](https://github.com/vulcand/oxy/blob/master/forward/rewrite.go#L37) but I can't see where port `80` comes from.

I don't use port 80 anywhere in this setup and I haven't found any place in the code where it would default to `80`. I can only assume that it's set to 80 because the URL reads `http://foo.bar.baz`, which is inaccurate.

So instead, I was expecting to see:
```
URL:               http://foo.bar.baz:443
X-Forwarded-Port:  443
```

Running `tcpdump` inside the traefik container, I can see the proxyproto header:
```
PROXY TCP4 10.91.62.52 10.66.23.101 49614 443
```
the original request hitting traefik,
```
    10.2.10.0.39195 > 10.2.7.183.443: Flags [P.], cksum 0xbb83 (correct), seq 2569673526:2569673621, ack 642188022, win 106, options [nop,nop,TS val 3304917303 ecr 3082179752], length 95
```
```
GET / HTTP/1.1
Host: foo.bar.baz
User-Agent: curl/7.43.0
Accept: */*
```
and the proxied request,
```
    10.2.7.183.54610 > 10.2.10.88.3000: Flags [P.], cksum 0x2788 (incorrect -> 0x8acf), seq 1379237775:1379238110, ack 1404536111, win 229, options [nop,nop,TS val 1276350355 ecr 3744100919], length 335
```
```
GET / HTTP/1.1
Host: foo.bar.baz
User-Agent: curl/7.43.0
Accept: */*
X-Forwarded-For: 10.91.62.52
X-Forwarded-Host: foo.bar.baz
X-Forwarded-Port: 80
X-Forwarded-Proto: http
X-Forwarded-Server: internal-ingress-tcp-proxy-8495446487-m6nw6
X-Real-Ip: 10.91.62.52
Accept-Encoding: gzip
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
/ # traefik version
Version:      v1.4.2
Codename:     roquefort
Go version:   go1.9.2
Built:        2017-11-02_01:47:46PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```
        - --web
        - --web.metrics
        - --web.metrics.prometheus
        - --logLevel=ERROR
        - --kubernetes
        - --entryPoints=Name:https-proto Address::443 ProxyProtocol.TrustedIPs:10.66.23.0/24,10.2.0.0/16
        - --defaultentrypoints=https-proto
```

**Comment by alkar** [comment]
I just did another simple test: identical setup with the above but with ProxyProtocol not enabled on either ELB or traefik. My echo service still gives me port `X-Forwarded-Port: 80` although that port is not used anywhere in the setup.

**Comment by aantono** [comment]
I suspect the issue might be here: https://github.com/containous/traefik/blob/master/vendor/github.com/vulcand/oxy/forward/rewrite.go#L69

Oxy checks if the request has TLS on it, and only then assigns port `443`, unless an explicit port was given in the request URL.

Do you have an actual certificate connected to your Traefik entry point, as I don't see it indicated in the config above?  If there is no cert binding, then Traefik doesn't do anything other than listen on port 443 and treat it as a regular HTTP request.  The same is true for `X-Forwarded-Proto` header.  The `https` value will only be set, if there is an actual TLS request being made.

**Comment by ldez** [comment]
Related to #2224

**Comment by alkar** [comment]
@aantono That sounds right. As described above, traefik sits behind an ELB that does the SSL offloading so from its point of view, the traffic it receives is not encrypted (hence, `X-Forwarded-Proto` is truly `http`).

However, that ELB also has Proxy Protocol enabled and the header clearly states the port is 443, which is what I expect to see in `X-Forwarded-Port`.

Failing that, I would at least expect to see the actual port traefik receives traffic on (the entrypoint), which again, would be port `443`.

From a quick look at the proxyproto package being used, it looks like there might be no way to receive the destination port, it's not exposed - hope I'm wrong.

**Comment by errm** [comment]
At this point the work around I would suggest is to terminate ssl on traefik and use the ELB in TCP mode...

**Comment by dtomcej** [comment]
@alkar Is this still an issue? We have updated oxy, and it should now respect the header being set.

Please let us know if we can close this issue.

**Comment by george-angel** [comment]
Can confirm this works correctly with 1.6.0 now:

```
curl -i -L https://foo.bar.baz/
HTTP/2 200
date: Tue, 08 May 2018 10:42:24 GMT
content-type: application/json; charset=utf-8
content-length: 730
etag: W/"2da-8V5gPflP/ENRN0HY17VRFp+pV84"
x-powered-by: Express

{
    "url": "http://foo.bar.baz/",
    "protocol": "http",
    "host": "foo.bar.baz",
    "path": "/",
    "method": "GET",
    "headers": {
        "host": "foo.bar.baz",
        "user-agent": "curl/7.59.0",
        "accept": "*/*",
        "x-amzn-trace-id": "Root=1-5af17f10-14c339ac581b08f300f399f0",
        "x-forwarded-for": "10.91.62.55, 10.2.2.0",
        "x-forwarded-host": "foo.bar.baz",
        "x-forwarded-port": "443",
        "x-forwarded-proto": "https",
        "x-forwarded-server": "internal-ingress-proxy-6796bb6568-dx6rt",
        "x-real-ip": "10.2.2.0",
        "accept-encoding": "gzip"
    },
    "query": {},
    "body": {}
}
```

Close it, thanks!
