### ISSUE TITLE
Better Docs (e.g Rancher)

### ISSUE THREAD

**Issue by MichelDiz** [containous/traefik#2375]
### Do you want to request a *feature* or report a *bug*?

Docs are the best feature we could ask for - so we do not have to look for support without needing taking time from you.

PS. Sorry for the huge text, but what I have to say can not be summed up. Please address as feedback please.

For example, I'm testing absolutely all possibilities. From third party to "official" and always encounter different configurations. Sometimes I have to cause failure to know if I'm doing something right. Applying "science" of "right and wrong".

About Docs, I believe all other docker-related documentation or any other (k8) documentation is well written. However, there is a gap as far as documentation related to Rancher is concerned. I have over 15 tabs of Chrome open each with a different solution / issue of the same product (Traefik) and in none of them I had 100% success. I did, but always with something small that I did not understand or there is a bug and I can not see or talk about it.

Continuing. There is a video on Youtube that a member of Team (Traefik) explains how to configure TK using "add service" in Rancher and adding all parameters in a command line only. I did not find what he did in the documentation. So That would be a "problem". Someone publicly sell a product with a technique that is not completely clear and consolidated in the official documentation. And this form (as service) does not allow you to use Labels for this Tk services it sellf (only command option) and some commands seemed to have no effect. At least I tested (use labels) and it did not work.

One thing I'm wondering is - Should I install Traefik configured to docker (sock) off the "Rancher" or are there no limitations keeping it as a service inside a "Rancher" stack? There are no technical explanations about this. Which is better. To spend time on.

A step by step of each configuration technique would be very good to have in the documentation. I think that only in Rancher is there more than one way to "install" and configure Traefik and I do not know which one is the best.

One detail is, in my case, I was able to install Traefik through the catalog and the "video technique". Although it is working, there are flaws in HTML, CSS and etc of the services - spite I've tested it on another public PORT and it's perfect. Only at Traefik that route wrong. When there are only responses like "404" or a blank page that in "dashboard / health" appears with negative status. See the video - By the way this issue isn't to support me. I'm already requesting this support in Slack. Here are just references.

Anyway, I think I ramified the writing a bit. But the very focus is on the documentation related to Rancher. I really wanted to see Traefik running on my project along with Rancher. If I had not been stubborn I would have given up. Please put all possibilities in your documentation. After all you sell that there is indeed support for Rancher.

https://youtu.be/0zVwqWwHo5w?t=14m53s "video technique".

https://youtu.be/7ZO3lB5K8aA - My video.

https://docs.traefik.io/configuration/backends/rancher/ - The Rancher TK Doc.

**Comment by traefiker** [comment]
I'll close the issue due to inactivity but feel free to re-open if needed.
