### ISSUE TITLE
stickiness on kubernetes wont work 

### ISSUE THREAD

**Issue by gabrielfsousa** [containous/traefik#2392]
### Do you want to request a *feature* or report a *bug*?

bug

### What did you do?

stickiness on kubernet

### What did you expect to see?

stickiness active tab/label on traefik

### What did you see instead?

stickiness not active

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
1.4.2
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
vmware / centos 7 / kubernetes 1.8.2
```

![image](https://user-images.githubusercontent.com/722744/32662315-02e01522-c622-11e7-8c0c-02f28231d432.png)

**Comment by mcorbin** [comment]
We also encounter this bug. we tried `traefik.backend.loadbalancer.stickiness` and `traefik.backend.loadbalancer.sticky` but no cokkie are set in the response.

**Comment by timoreimann** [comment]
The label must be set on the Service, not the Ingress object. I just verified that it works for me.

Closing for now. Please reopen if you think this is still relevant.
