### ISSUE TITLE
Traefik is using the wrong VirtualIPs

### ISSUE THREAD

**Issue by pascalandy** [containous/traefik#2402]
### Do you want to request a *feature* or report a *bug*?

Bug

### General 

I run Docker swarm mode. At this moment I run about 60 services. Few `docker run` and mostly `docker service create`.

I have this bug for months now. Always thought something was wrong on my side but **now** I can show the bug is for real. I provisioned 50+ VPS (and bare metal) servers with the same issue. Over the months I re-create this bug with different versions of Traefik and docker-ce. (I didn’t know how to show it to you back then.)

You can my Traefik docker stack [here](https://github.com/pascalandy/docker-stack-this/tree/master/traefik_stack5).

### What did you do?

**The issue**

- I have about 20 services that are online behind Traefik. (They are blogs CMS)
- When I redeploy those 20 services, one of them (sometimes 2 or 3) are not getting served by Traefik.
- The service impacted is totally random. 
- In this case, the service is named **stupendous**.
- It’s the one that is not getting served by Traefik.
- I use only one network.

### What did you expect to see?

Traefik should forget the old VirtualIPs and find the VirtualIPs of the last provisioned container.

### What did you see instead?

**1) Traefik GUI**

![screen shot 2017-11-13 at 7 54 12 pm](https://user-images.githubusercontent.com/6694151/32758678-9ad32e1c-c8b3-11e7-970e-95b7d3923fe7.png)

We can see that Traefik sees **stupendous** service = 10.21.10.68:2368 **(68)**

**2) docker service logs proxy_traefik**

```
json
{"backends":{"backend-10000014-attila-1":
{"servers":{"server-10000014-attila-1":{"url":"http://10.21.10.68:2368","weight":10}},
"loadBalancer":{"method":"wrr"}}
```

Here we can see that another service **attila** is using 10.21.10.68:2368 **(68)**.

YOU SEE THE ISSUE HERE?

**3) docker service inspect stupendous**

When I inspect **stupendous**, docker is telling us that this service uses 10.21.10.67/24. **(67)**

```console
docker service inspect **stupendous** | grep Addr

            "VirtualIPs": [
                {
                    "NetworkID": "ytw4xxdv4tan8lt5tev6ioabx",
                    "Addr": "10.21.10.67/24"
                }
            ]
```

- It looks **stupendous** was using `10.21.10.68/24` **(68)**
- Then I updated the service and the new address is now `10.21.10.67/24`. **(67)**

Traefik is not aware of it :-(

In the logs, there NO services is using 10.21.10.67:2368 **(67)**

### Output of `traefik version`: (_What version of Traefik are you using?_)

1.4.1 

I could replicate with 1.4.2, 1.4.0 and earlier versions 1.3.x.

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Ubuntu 16.04, docker-ce 17.09.0-ce, packet.net

**TOML** — https://github.com/pascalandy/docker-stack-this/blob/master/traefik_stack1/configs/traefik.toml

### If applicable, please paste the log output in debug mode (`--debug` switch)

you can see above

### Ways to resolute this

**1)** If I leave this alone, it takes between 3-24 hours and Traefik fix itself. But it’s really random and totally not production grade.

**2)** When I …
- Shutdown **stupendous**
- Restart Traefik Docker stack
- Wait for Traefik to be alive
- Start the service **stupendous**
- I’m all good… until I have to stop and re-create a new service.

### Conclusion

I’ll be prompt to test your suggestions or even to jump on team viewer.

Thank you for this amazing piece of software and I hope I can contribute to making it even better!

Cheers!
[Pascal](https://twitter.com/askpascalandy)
 
 ps: docker service ls
 
<img width="1293" alt="screen shot 2017-11-13 at 7 56 38 pm" src="https://user-images.githubusercontent.com/6694151/32758717-c9c93432-c8b3-11e7-8955-5a773cf3088a.png">

**Comment by centerorbit** [comment]
Could be related to this?: https://github.com/containous/traefik/issues/979

**Comment by pascalandy** [comment]
In my case, I use only one network, not two.

**Comment by pascalandy** [comment]
Well, it looks someone had the issue as well - https://github.com/containous/traefik/issues/2459

It's part of v1.4.5. I will test and report back!

**Comment by pascalandy** [comment]
Following up. I still have the same bug using 1.5.0-rc2 since last week.

**Comment by mmatur** [comment]
Hi @pascalandy , Thanks for your detailed issue.

How do you run your service update ? 
What are types of changes on your services ?

Are you able to reproduce with your [Træfik docker stack](https://github.com/pascalandy/docker-stack-this/tree/master/traefik_stack5) ?

I have played a little bit with it and I a not able to reproduce your issue.

**Comment by pascalandy** [comment]
Hi @mmatur 

I do not update. 
I do `docker service rm serviceXYZ` then I do 
`docker service create serviceXYZ`.

I do this because I reset the data from the mounted directory. 

Yes I recreate this issue using https://github.com/pascalandy/docker-stack-this/tree/master/traefik_stack5

Actually... I need to re-test my stack using all these labels:

```
labels:
- "traefik.frontend.rule=PathPrefixStrip:/"
- "traefik.backend=home"
- "traefik.port=2015"
- "traefik.weight=10"
- "traefik.enable=true"
- "traefik.passHostHeader=true"
- "traefik.docker.network=ntw_front"
- "traefik.frontend.entryPoints=http"
- "traefik.backend.loadbalancer.swarm=true"
- "traefik.backend.loadbalancer.method=drr"
```

Let me follow up in few days. I don't have access to my whole setup at the moment.

**Comment by pascalandy** [comment]
I'm following up:

- I did remove then create Traefik using 1.5.0-rc3 ✨
- I did remove then create all my CMS containers using these labels:

```
--label "traefik.frontend.rule=Host:example.com/blog1" \
--label "traefik.backend=$CTN_ghost_app" \
--label "traefik.port=2368" \
--label "traefik.enable=true" \
--label "traefik.frontend.entryPoints=http" \
--label "traefik.docker.network=$NTW_FRONT" \
--label "traefik.frontend.priority=100" \
--label "traefik.weight=10" \
--label "traefik.passHostHeader=true" \
--label "traefik.backend.loadbalancer.swarm=true" \
--label "traefik.backend.loadbalancer.method=drr" \
```

I’ll report back 🙈 ASAP.

**Comment by pascalandy** [comment]
The issue happened exactly 1 time at since 48 hours. Traefik recovered the issue within one hour. 

What I'll do next is to start a new node using docker 17.12 CE. (Using 17.09 at the moment.)

**Comment by pascalandy** [comment]
@mmatur 

No I can't For small setup I can't reproduce the issue. 

> Are you able to reproduce with your Træfik docker stack ?
> I have played a little bit with it and I a not able to reproduce your issue.

**Comment by pascalandy** [comment]
Since 2 weeks, I'm glad that since I upgrade to Traefik 1.5.4 and Docker-CE 18.03 this bug is resolved. 

I can't say if the issue was on which side but I FU**ING happy I don't have to deal with it anymore. 

I'll leave it open for few weeks on continue to monitor the situation.

**Comment by pascalandy** [comment]
Still perfectly stable. 
Closing the issue great happiness :)
Cheers!
