### ISSUE TITLE
Bug with using different configuration engines for frontend & backend

### ISSUE THREAD

**Issue by Russell-IO** [containous/traefik#241]
Hello,

In this commit:
https://github.com/containous/traefik/compare/11781087cadf9068d1d0b43902b6161ee10ea458...0e683cc5355bc507dabac68bbc7559d3f179e185

this feature stopped working,
Using docker configuration to discover nodes automatically.

Using consul to configure multiple frontend routes.
Works with docker image: v1.0.alpha.11781087cadf9068d1d0b43902b6161ee10ea458
Doesn't work with docker image: v1.0.alpha.0e683cc5355bc507dabac68bbc7559d3f179e185

Steps to reproduce, with below configuration:
[consul]
endpoint = "192.168.99.100:8500"
watch = true
prefix = "traefik"
[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "internal"
watch = true

Start up v1.0.alpha.0e683cc5355bc507dabac68bbc7559d3f179e185.
Start up a docker container called demo
Demo now appears in docker section under traefik called demo.internal
Now create consul key/value pairs:
traefik/frontends/demo/backend => backend-demo
traefik/frontends/demo/routes/demo-com/rule => Host
traefik/frontends/demo/routes/demo-com/value => demo.com

Now traefik errors & doesn't make any changes..
But now start up v1.0.alpha.11781087cadf9068d1d0b43902b6161ee10ea458
And it works in that demo.com routes to the demo container.

**Comment by emilevauge** [comment]
Hi @Russell-IO, the commit your are talking about only concerns a typo fix.
I don't think it is reasonable to blame it ;)
Making links between frontends from a configuration engine and a backend from another configuration engine has never been supported. I don't see why it should haver ever work in fact ^^

**Comment by Russell-IO** [comment]
Hi @emilevauge Maybe a Feature Bug, then because running with the latter commit I do indeed get the error message referenced, whereas with the prior commit, I am able to point a consul frontend to a docker backend.
