### ISSUE TITLE
The WebUI interface shows an incorrect number of frontends (Docker swarm mode)

### ISSUE THREAD

**Issue by DmitriyProkhorov** [containous/traefik#2410]
### I want to request a bug.

Web UI for traefik in docker swarm mode:

When the backends scale, the number of frontends becomes equal to the number of backends on the Web UI dashboard
The problem began with version 1.4.2 and is repeated on version 1.4.3

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
docker run traefik:1.4.3-alpine
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# docker swarm on debian
```

![web-ui-1 4 1](https://user-images.githubusercontent.com/21653186/32834865-ca16429a-ca0c-11e7-8402-bfe468ad1aae.jpg)
![web-ui-1 4 3](https://user-images.githubusercontent.com/21653186/32834867-ca2e7130-ca0c-11e7-9cfc-9769ba6324c0.jpg)

**Comment by llitfkitfk** [comment]
same issue

**Comment by traefiker** [comment]
Closed by #2434.
