### ISSUE TITLE
TLS.CipherSuites not working with KV (Consul)

### ISSUE THREAD

**Issue by vincentmele** [containous/traefik#2416]
### Do you want to request a *feature* or report a *bug*?
Report a bug.

### What did you do?
Added traefik/entrypoints/https/tls/cipherSuites key in Consul 1.0 to set cipherSuites. ( I have the consul prefix to "traefik" and the entrypoint name is "https". )
 Similar to the .toml file configuration, I tried individually: 
`["TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"]` 
`"TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"`, and 
`TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256`

### What did you expect to see?
I expected Traefik to use only the specified ciphersuite on the https frontend.

### What did you see instead?
Traefik logs show:
```time="2017-11-15T18:52:11Z" level=error msg="Load config error: 1 error(s) decoding:

* error decoding 'EntryPoints[https].TLS.CipherSuites': illegal base64 data at input byte 0, retrying in 1.896190287s"
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.4.2
Codename:     roquefort
Go version:   go1.9.2
Built:        2017-11-02_01:47:46PM
OS/Arch:      linux/amd64
```

Note that setting "minVersion" key to "VersionTLS12" works successfully. The problem seems to only be related to "cipherSuites" key.

**Comment by menew** [comment]
As far as I can see (by checking behaviour of `storeconfig`), staert seems to put each items of an array into separate keys that are suffixed with its index.

For example, this configuration:

    [entryPoints]
      [entryPoints.https]
        [entryPoints.https.tls]
        cipherSuites = ["TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256", "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA"]

will be saved as following on Consul:

    traefik/entrypoints/https/tls/ciphersuites/0:TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
    traefik/entrypoints/https/tls/ciphersuites/1:TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA

So, simply putting value `TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256` into `traefik/entrypoints/https/tls/ciphersuites/0` key should work correctly, I think.

**Comment by chr4** [comment]
I ran into this issue as well, but I could fix it by using the correct order of ciphers.
Below is a working configuration for TLSv1.1 which prefers ChaCha/ Poly and removes the insecure 3DES ciphers. 

```
[entryPoints.https.tls]
minVersion = "VersionTLS11"
cipherSuites = [
   "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
  "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
  "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
  "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
  "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
  "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
  "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
  "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
  "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA",
  "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA",
  "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA",
  "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA",
  "TLS_RSA_WITH_AES_128_GCM_SHA256",
  "TLS_RSA_WITH_AES_256_GCM_SHA384",
  "TLS_RSA_WITH_AES_128_CBC_SHA",
  "TLS_RSA_WITH_AES_256_CBC_SHA",
]
```

**Comment by vincentmele** [comment]
@menew 's suggestion to add consul keys like `traefik/entrypoints/https/tls/ciphersuites/0` , `traefik/entrypoints/https/tls/ciphersuites/1` etc. worked successfully. However, I then ran into an error that http/2 didn't like some of the ciphers (because they were part of TLS 1.2, but were blacklisted.) 

HTTP/2 also *mandates* that TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 be enabled: I received the error, "http2: TLSConfig.CipherSuites is 
missing HTTP/2-required TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256" in the traefik logs without it.

Therefore, I obtained a clean nmap ssl-enum-cipher scan rated A by setting in consul:
```
traefik/entrypoints/https/tls/ciphersuites/0 to TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
traefik/entrypoints/https/tls/ciphersuites/1 to TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
traefik/entrypoints/https/tls/ciphersuites/2 to TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
traefik/entrypoints/https/tls/ciphersuites/3 to TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
```

Resulting `nmap -sV --script ssl-enum-ciphers -p 443 [redacted host]`:
```PORT    STATE SERVICE  VERSION
443/tcp open  ssl/http Golang net/http server (Go-IPFS json-rpc or InfluxDB API)
|_http-server-header: nginx
| ssl-enum-ciphers:
|   TLSv1.2:
|     ciphers:
|       TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (rsa 4096) - A
|       TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (rsa 4096) - A
|     compressors:
|       NULL
|     cipher preference: server
|_  least strength: A
```

**Comment by dtomcej** [comment]
Hello @vincentmele! Just checking in on this ticket. Is this still an issue? or can we close this one?

It appears you were able to get the ciphersuites working the way you wanted.

Thanks!

**Comment by vincentmele** [comment]
Not an issue anymore once I figured out the configuration, documented in the Feb 28th comment.
