### ISSUE TITLE
Proposal: Kubernetes service backend

### ISSUE THREAD

**Issue by arschles** [containous/traefik#245]
It would be interesting to use Traefik as a single point of entry to a cluster and route to various cluster-internal services. We do something like this in the Deis project with an Nginx based solution, but I think it would be interesting to see a pure-Go implementation, complete with the dashboard, etc... that this project provides. See https://github.com/deis/router for the example in Deis

**Comment by emilevauge** [comment]
Hi @arschles, I'm working on adding traefik as an ingress backend #186 (but I still have issue with the huge dependencies of k8s client). Does it fit your needs?
If you're planning to use it on Deis, I would be glad to talk about it on [traefik's slack ](https://traefik.herokuapp.com/) ;)

**Comment by arschles** [comment]
@emilevauge sounds very promising. I'll keep an eye on #186 

Also, I feel your pain on the large Go client library size...

**Comment by emilevauge** [comment]
Fixed by #186
