### ISSUE TITLE
Redirect documentation/ log missing hierarchy rule

### ISSUE THREAD

**Issue by dfredell** [containous/traefik#2472]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

- I wanted to do a redirect of http to https only if the host matched my regex 
- So I read the docs and had both entryPoints.http.redirect.entryPoint and entryPoints.http.redirect.regex because it said nothing against doing both
- This didn't work as I had expected, so I read the source code https://github.com/containous/traefik/blob/39c1cc1b3ca096423202054e07b81796051e6d06/server/server.go#L1287 
- The source says if entryPoints.http.redirect.entryPoint is defined replace the regex and replacement fields
- I shouldn't have to read source to figure this out

### What did you expect to see?

A message in the logs saying this was an invalid configuration. Or something in the documentation saying this was invalid.

After reading the source I do see https://github.com/containous/traefik/blob/39c1cc1b3ca096423202054e07b81796051e6d06/server/server.go#L1298 but it didn't make it into my logs. Probably an issue on my side. 

### What did you see instead?

No warning in the logs that my configs got overwritten. No documentation saying this would happen. 

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
docker run traefik:v1.4.1-alpine

Version:      v1.4.1
Codename:     roquefort
Go version:   go1.9.1
Built:        2017-10-24_05:25:28PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Using Consul Config, and Consul Catalog. I unBASE64ed the values.

My first attempt:
```json
[
	{
		"key": "traefik/entrypoints/http/address",
		"flags": 0,
		"value": ":80"
	},
	{
		"key": "traefik/entrypoints/http/redirect/regex",
		"flags": 0,
		"value": "^http:\/\/dan\.website\.com.*$"
	},
	{
		"key": "traefik/entrypoints/http/redirect/entrypoint",
		"flags": 0,
		"value": "https"
	},
	{
		"key": "traefik/loglevel",
		"flags": 0,
		"value": "DEBUG"
	}
]
```

After I got it working:
```json
[
	{
		"key": "traefik/entrypoints/http/address",
		"flags": 0,
		"value": ":80"
	},
	{
		"key": "traefik/entrypoints/http/redirect/regex",
		"flags": 0,
		"value": "^(?:https?:\/\/)?(dan\.website\.com|dan\.website2\.com)(?::\d+)?(.*)$"
	},
	{
		"key": "traefik/entrypoints/http/redirect/replacement",
		"flags": 0,
		"value": "https://$1:443$2"
	}
]
```

**Comment by dtomcej** [comment]
This issue has been resolved in https://github.com/containous/traefik/pull/2243. 

There are multiple notices in the documentation now about this situation, warning of the behavior of filling out all the fields. This should be live in 1.5.
