### ISSUE TITLE
Super-tables are not created automatically (or don't work as expected)

### ISSUE THREAD

**Issue by mvasin** [containous/traefik#2484]
### Do you want to request a *feature* or report a *bug*?

A bug.

### What did you do?

I created a `traefik.toml` file with the only line:
```
[web.statistics]
```
and started it with `docker run -p 8080:8080 -v $PWD/traefik.toml:/etc/traefik/traefik.toml traefik`

### What did you expect to see?

A working container, because as `toml` specification says,
> You don't need to specify all the super-tables if you don't want to. TOML knows how to do it for you.
> ```
> # [x] you
> # [x.y] don't
> # [x.y.z] need these
> [x.y.z.w] # for this to work
> ```

so I don't have to specify `[web]` in addition to `[web.statistics]`, especially if `[web]` is supposed to be empty.

### What did you see instead?

A failed container with `time="2017-11-29T07:28:45Z" level=fatal msg="Error creating server: listen tcp :80: bind: address already in use"` log message.

If I add `[web]` in addition to `[web.statistics]` it works, but I don't want to be verbose where I don't have to, and I'd like the Traefik config to behave according to `toml` spec; if I didn't specify a super-table I assume it's there automatically.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.3.8
Codename:     raclette
Go version:   go1.8.3
Built:        2017-09-07_08:46:19PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```json
{
 "GraceTimeOut": 10000000000,
 "Debug": false,
 "CheckNewVersion": true,
 "AccessLogsFile": "",
 "TraefikLogsFile": "",
 "LogLevel": "ERROR",
 "EntryPoints": {},
 "Cluster": null,
 "Constraints": [],
 "ACME": null,
 "DefaultEntryPoints": [],
 "ProvidersThrottleDuration": 2000000000,
 "MaxIdleConnsPerHost": 200,
 "IdleTimeout": 180000000000,
 "InsecureSkipVerify": false,
 "Retry": null,
 "HealthCheck": {
  "Interval": 30000000000
 },
 "Docker": null,
 "File": null,
 "Web": {
  "Address": ":8080",
  "CertFile": "",
  "KeyFile": "",
  "ReadOnly": false,
  "Statistics": {
   "RecentErrors": 10
  },
  "Metrics": null,
  "Path": "",
  "Auth": null
 },
 "Marathon": null,
 "Consul": null,
 "ConsulCatalog": null,
 "Etcd": null,
 "Zookeeper": null,
 "Boltdb": null,
 "Kubernetes": null,
 "Mesos": null,
 "Eureka": null,
 "ECS": null,
 "Rancher": null,
 "DynamoDB": null,
 "ConfigFile": "/etc/traefik/traefik.toml"
}
```

**Comment by ldez** [comment]
Do you still have the same problem with the latest version (1.5.0-rc3)?

**Comment by mvasin** [comment]
@ldez Yes, the issue is still there in `traefik:v1.5.0-rc3` and `traefik:v1.5.0-rc4` docker images.

**Comment by ldez** [comment]
I don't reproduce with 1.5 🤔 
No matter because Web backend is deprecated: we divided into API/REST/Metrics/Ping backend.

**Comment by mvasin** [comment]
"I don't reproduce" means you can see the web interface with just "[web.statistics]"?

Can you please point me to the docs about the new approach? I randomly opened [https://github.com/containous/traefik/blob/master/docs/basics.md](https://github.com/containous/traefik/blob/master/docs/basics.md) and it still mentions the `[web]` section.

**Comment by ldez** [comment]
In https://docs.traefik.io/archive/ you can find http://v1-5.archive.docs.traefik.io/.

- [web](http://v1-5.archive.docs.traefik.io/configuration/backends/web/) deprecated.
- [rest](http://v1-5.archive.docs.traefik.io/configuration/backends/rest/)
- [api](http://v1-5.archive.docs.traefik.io/configuration/api/)
- [ping](http://v1-5.archive.docs.traefik.io/configuration/ping/)
- [metrics](http://v1-5.archive.docs.traefik.io/configuration/metrics/)

**Comment by mvasin** [comment]
OK, thanks.
