### ISSUE TITLE
A non-existent entry point makes an existing entry point inaccessible

### ISSUE THREAD

**Issue by mvasin** [containous/traefik#2494]
### Do you want to request a *feature* or report a *bug*?

A bug.

### What did you do?

I tried to serve NGINX container's default html file through Traefik.

I created this `toml` file:
```toml
[entryPoints]
[entryPoints.http]
address = ":80"


[web]
address = ":8080"

[docker]
```

then started Traefik: `docker run --network traefik -p 8080:8080 -p 80:80 -v $PWD/traefik.toml:/etc/traefik/traefik.toml -v /var/run/docker.sock:/var/run/docker.sock traefik`

then started NGINX: `docker run --network traefik -l "traefik.frontend.rule=Host:localhost.dev" -l "traefik.docker.network=traefik" -l "traefik.backend=nginx" -l "traefik.port=80" -l "traefik.enable=true" nginx`

then tried to access it with `curl --verbose --header 'Host: localhost.dev' http://127.0.0.1`

### What did you expect to see?

A default NGINX html page accessible on port 80.

### What did you see instead?

A 404 error.

### Further investigations

If I assign NGINX entry point to http (`-l "traefik.frontend.entryPoints=http"`), it works.
It I set `defaultEntryPoints = ["http"]` or `defaultEntryPoints = ["http", "https"]`, it works. But leaving default `defaultEntryPoints = ["https", "http"]` (with `https` first, and while `https` is not being specified in `toml`) makes http entry point inaccessible.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.4.4
Codename:     roquefort
Go version:   go1.9.2
Built:        2017-11-23_10:53:58AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```json
{
 "GraceTimeOut": 10000000000,
 "Debug": true,
 "CheckNewVersion": true,
 "AccessLogsFile": "",
 "AccessLog": null,
 "TraefikLogsFile": "",
 "LogLevel": "ERROR",
 "EntryPoints": {
  "http": {
   "Network": "",
   "Address": ":80",
   "TLS": null,
   "Redirect": null,
   "Auth": null,
   "WhitelistSourceRange": null,
   "Compress": false,
   "ProxyProtocol": null,
   "ForwardedHeaders": null
  },
  "https": {
   "Network": "",
   "Address": ":443",
   "TLS": null,
   "Redirect": null,
   "Auth": null,
   "WhitelistSourceRange": null,
   "Compress": false,
   "ProxyProtocol": null,
   "ForwardedHeaders": null
  }
 },
 "Cluster": null,
 "Constraints": [],
 "ACME": null,
 "DefaultEntryPoints": [
  "https",
  "http"
 ],
 "ProvidersThrottleDuration": 2000000000,
 "MaxIdleConnsPerHost": 200,
 "IdleTimeout": 0,
 "InsecureSkipVerify": false,
 "RootCAs": null,
 "Retry": null,
 "HealthCheck": {
  "Interval": 30000000000
 },
 "RespondingTimeouts": null,
 "ForwardingTimeouts": null,
 "Docker": {
  "Watch": true,
  "Filename": "",
  "Constraints": null,
  "Trace": false,
  "DebugLogGeneratedTemplate": false,
  "Endpoint": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "Domain": "",
  "TLS": null,
  "ExposedByDefault": true,
  "UseBindPortIP": false,
  "SwarmMode": false
 },
 "File": null,
 "Web": {
  "Address": ":8080",
  "CertFile": "",
  "KeyFile": "",
  "ReadOnly": false,
  "Statistics": null,
  "Metrics": null,
  "Path": "",
  "Auth": null,
  "Debug": false,
  "CurrentConfigurations": null,
  "Stats": null,
  "StatsRecorder": null
 },
 "Marathon": null,
 "Consul": null,
 "ConsulCatalog": null,
 "Etcd": null,
 "Zookeeper": null,
 "Boltdb": null,
 "Kubernetes": null,
 "Mesos": null,
 "Eureka": null,
 "ECS": null,
 "Rancher": null,
 "DynamoDB": null,
 "ConfigFile": "/etc/traefik/traefik.toml"
}
```

**Comment by traefiker** [comment]
Closed by #2501.
