### ISSUE TITLE
Rancher: missing certificate

### ISSUE THREAD

**Issue by wu3rstle** [containous/traefik#2507]
### Do you want to request a *feature* or report a *bug*?

bug

### What did you do?

Initialize Traefik 1.4.4 from rancher catalog with rancher 1.6.10.

### What did you expect to see?

The certificate file should contain the main and the chain certificates.

### What did you see instead?
Only the main certificate is in certs/traefik.crt.
So the browser displays an untrusted certificate error.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
v1.4.4-rancher1
```

**Comment by nmengin** [comment]
WDYT @containous/rancher @rawmind0 ?

**Comment by rawmind0** [comment]
Hi @wu3rstle , 

are you concatenating your main certificate and your chain certificate into "Https crt" catalog text box?? I'm testing it concatenating certificates (main + chain) and it works properly, i got 2 certificates into `certs/traefik.crt` file.

**Comment by wu3rstle** [comment]
Certificates are concatenated correctly.

After an upgrade of the container image to `v1.4.6-rancher1` it seems to be fixed.

**Comment by wu3rstle** [comment]
I copied the certs from the working rancher config.

After an upgrade to `v1.4.6-rancher-1` it's working again.
I think the problem was in the container image.
