### ISSUE TITLE
Feature Request: Allow request header modifying / appending via configuration

### ISSUE THREAD

**Issue by yue9944882** [containous/traefik#2515]
### Do you want to request a *feature* or report a *bug*?
feature request

### What did you do?
I want add/set HTTP Headers for all in coming HTTP request to explicitly force them using HTTP keep-alived connection. But I actually didn't find any documentation about it or traefik doesn't support it currently.

### What did you expect to see?
Simply add some configuration entries to make it happen.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
v1.4.2
```

**Comment by yue9944882** [comment]
Or rather, I'm expecting implementations of [this annotation](https://github.com/containous/traefik/blob/e042ef3f27d61c142e55a9c69993e3395e0fa1a1/provider/kubernetes/kubernetes.go#L45)

**Comment by ldez** [comment]
This come in 1.5, see #2460.

You can try the 15.0-rc1.
