### ISSUE TITLE
Docker backend doesn't support customresponseheaders with ":" or ","

### ISSUE THREAD

**Issue by captn3m0** [containous/traefik#2517]
### Do you want to request a *feature* or report a *bug*?

BUG

### What did you do?

As a workaround to https://github.com/containous/traefik/issues/2493, I attempted to use customresponseheaders to set the XFO header:

`"traefik.frontend.headers.customresponseheaders" = "X-Frame-Options:ALLOW-FROM https://domain.tld"`

### What did you expect to see?

The XFO header being set on all responses.

### What did you see instead?

The header is not set.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.5.0-rc1
Codename:     cancoillotte
Go version:   go1.9.2
Built:        2017-11-28_02:11:24PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```tf
"traefik.frontend.headers.customresponseheaders" = "X-Frame-Options:ALLOW-FROM https://domain.tld"
```

Set using terraform docker label.

### If applicable, please paste the log output in debug mode (`--debug` switch)

```
time="2017-12-04T06:34:04Z" level=error msg="Could not load "traefik.frontend.headers.customresponseheaders"" 
```

/cc @dtomcej

**Comment by ldez** [comment]
Closed by #2509
