### ISSUE TITLE
feature: native Let's Encrypt support on Kubernetes

### ISSUE THREAD

**Issue by Thermi** [containous/traefik#2527]
### Do you want to request a *feature* or report a *bug*?

*feature*

### Current state

Currently, traefik only supports Let's Encrypt using a file as storage or a KV store like etcd.
However, on Kubernetes neither is easily possible. The first is completely impossible if several traefik instances need to coordinate and the latter requires an additional etcd instance. 

### Proposal

A much better and well supported method in a Kubernetes cluster would be to use the Kubernetes API to communicate between traefik processes. This can be done by using a configmap or a secret, for example. For obvious reasons, a secret would be preferred, but there's a known notification mechanism for configmaps. Traefik would read and write the Kubernetes object using its API and use it the same way the file would be.

**Comment by dtomcej** [comment]
I will come up with a proposal for this.

**Comment by nmengin** [comment]
Closed in favor of #2542 .
