### ISSUE TITLE
Dynamic health check path/interval labels for Docker backend

### ISSUE THREAD

**Issue by bitsofinfo** [containous/traefik#2535]
### Do you want to request a *feature* or report a *bug*?

feature

For Docker swarm services it would be great to be able to use labels to define the health check endpoints for a give service i.e. `traefik.backend.healthcheck.interval` and `traefik.backend.healthcheck.path`

### Output of `traefik version`: (_What version of Traefik are you using?_)

1.4.4

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

linux,docker

**Comment by MichaelErmer** [comment]
It would also be great if the timeout would be configurable
