### ISSUE TITLE
PathPrefixStrip frontend rule in `docker` mode strips part of the path when accessing without trailing slash

### ISSUE THREAD

**Issue by dirkschneemann** [containous/traefik#2543]
### Do you want to request a *feature* or report a *bug*?
Report a bug, if it is one and not expected behaviour. I know that a similar issue was discussed in [issue 563](https://github.com/containous/traefik/issues/563). However, it got closed without a general solution except for "should be fixed since v1.3" but I can still reproduce the issue explained below in v1.5. 

### What did you do?

Given a HTML file `index.html`:
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8"> 
    <title>Some Title</title>
    <script src="./myscript.js"></script>
  </head>
  <body>
    I was written from HTML file.
  </body>
</html>
```

The imported JavaScript file `myscript.js` looks like this:
```js
document.write("I was written from JavaScript file.<br>");
```

If I navigate to the folder of that file in a terminal and type `python3 -m http.server` then I can access that page in my webbrowser via the following URLs:

 - `http://localhost:8000`
 - `http://localhost:8000/`
 - `http://localhost:8000/index.html`

Now, I start a docker container running `traefik` in `docker` mode which will listen for changes on my local docker socket:

```shell
docker run \
  -d \
  --name traefik-reverse-proxy \
  --network="host" \
  -p 80:80 \  
  -v /var/run/docker.sock:/var/run/docker.sock \
  traefik:1.5-alpine \
    --docker
```

My simple webserver is packaged in a Docker image using the following `Dockerfile`:

```Dockerfile
FROM python:3-alpine
WORKDIR /files
COPY ./index.html /files/index.html
COPY ./myscript.js /files/myscript.js
EXPOSE 8000
CMD ["python3", "-m", "http.server"]
```

The image is built by: `docker build -t httpserver .`

Finally, a container is started for that image, setting container labels such that the `traefik` container will forward any requests to it which have a path after the domain starting with `/files`:

```shell
docker run \
  -d \
  --rm \
  --name httpserver \
  --label traefik.frontend.rule="PathPrefixStrip: /files" \
  httpserver
```

### What did you expect to see?
If I access `http://localhost/files/` or `http://localhost/files/index.html` in my webbrowser, everything works fine. I expect two see both lines of output (one from the HTML and one from the JavaScript file) as well when accessing `http://localhost/files`. 

### What did you see instead?
Trying to access `http://localhost/files` (without the trailing slash), however, only shows the output of the HTML file in the browser. The browser console shows that importing the JavaScript file failed. It was expected to be available at `http://localhost/myscript.js` which it is not, rather it should look for `http://localhost/files/myscript.js` but the `/files` part is somehow stripped away by `traefik`.

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
Version:      v1.5.0-rc2
Codename:     cancoillotte
Go version:   go1.9.2
Built:        2017-12-06_03:07:42PM
OS/Arch:      linux/amd64
```
### What is your environment & configuration (arguments, toml, provider, platform, ...)?
Official Docker image with tag `1.5-alpine`. Same result with tag `1.5`.

**Comment by emilevauge** [comment]
This is how it is supposed to work. Traefik does not modify your request body. I suggest to use relative paths in your HTML files instead. I will close this one then 😉

**Comment by dirkschneemann** [comment]
How would a relative path in the HTML file look like?
`<script src=myscript.js>` was an unfortunate copy/paste error but the result is the same for `<script src=./myscript.js>`.

**Comment by kachkaev** [comment]
Hey @dirkschneemann! I think I know your pain, but at the same time I can't disagree with @emilevauge's position. Resolving `./myscript.js` into either `/files/myscript.js` or `/myscript.js` is what the browser decides, not traefik.

Adding trailing slash to a URL in order to make relative links resolvable to `/files/*` is the developer's responsibility no matter if the microservice architecture is used or not. If you prefer to not have a slash in the end of the URL, then it's necessary to make the app aware of this condition to override paths to assets on the server side when generating the html.

I have a few apps running at `example.com/something/` with `PathPrefixStrip` attached to the traefik rule. Redirects from `/something` to `/something/` are not automated (yet?) so I have to imply an additional routing rule mentioned in https://github.com/containous/traefik/issues/563#issuecomment-346143132. One other issue to watch out for is https://github.com/containous/traefik/issues/1957 (if you're using HTTP -> HTTPS redirects by traefik).

Hope this helps!

**Comment by dirkschneemann** [comment]
Thank you your your compassion, @kachkaev ;-)

> Adding trailing slash to a URL in order to make relative links resolvable to /files/* is the developer's responsibility no matter if the microservice architecture is involved or not. If you prefer to not have a slash in the end of the URL, then it's necessary to make the app aware of this condition to override paths to assets on the server side when generating the HTML.

This is how I solved it in the end. While there might be different possibilities, I make use of the [<base> tag in HTML](https://www.w3schools.com/tags/tag_base.asp) which globally sets the base folder for all following relative `src` or `href` paths. This way they are independent of whatever gets forwarded by `traefik`.

If all necessary information regarding the base folder is already available at build time, just add this tag into your static HTML file or append it at Docker image build time. Otherwise, if some dynamic part is needed which is only available at runtime (e.g. different assets for test/preprod/prod), it can also be appended at container runtime using an [entrypoint script](https://www.camptocamp.com/en/actualite/flexible-docker-entrypoints-scripts/).
