### ISSUE TITLE
Host Rules bundling of kubernetes backend

### ISSUE THREAD

**Issue by miadabrin** [containous/traefik#2554]
### Do you want to request a *feature* or report a *bug*?

bug

### What did you do?

I Created host rules using kubernetes
### What did you expect to see?

I expected to see subdomain bundlings on front end rules. for example I expect www.somedomain.com to be bundled with somedomain.com

### What did you see instead?

They are considered seperately which causes a lot of issues like acme certificate conflicts

### Output of `traefik version`: (_What version of Traefik are you using?_)

1.4.5

**Comment by emilevauge** [comment]
@miadabrin Could you give us more details (ingress, config)?

**Comment by miadabrin** [comment]
@emilevauge Definitely on the ingress side . (Maybe a traefik config would help as well) What I meant was there should be a way to recognize similar domains and put them inside the same group so there can be correct ACME certificate generations.
Right now `www.something.com` is different from `something.com` which makes traefik to request for two separate certificates for ACME.

**Comment by dtomcej** [comment]
Traefik currently bundles multiple hosts that are generated within the same ingress. If multiple ingresses are requesting subdomains, they will be handled separately.

Also wildcards now make this less of an issue, so I will close this ticket :)
