### ISSUE TITLE
Documentation / examples yaml update externalTrafficPolicy

### ISSUE THREAD

**Issue by sanderPostma** [containous/traefik#2566]
Please add this to the user guide + sample yaml for the Kubernetes service descriptor:

```yml
spec:  
  externalTrafficPolicy: Local
```

Annotation `service.beta.kubernetes.io/external-traffic` no longer works on Kubernetes 1.8.x+ and `externalTrafficPolicy` will be set to "Cluster" by default.

**Comment by timoreimann** [comment]
I have only learned about _externalTrafficPolicy_ through this issue; reading [the documentation](https://kubernetes.io/docs/api-reference/v1.8/#servicespec-v1-core), however, it does not seem to relate to functionality directly affecting Traefik. To me it should be a decision made by the user to decide for either _Local_ or _Cluster_ on a per-service basis.

Thoughts?

**Comment by sanderPostma** [comment]
When I used the service yaml exactly as documented on [this page](https://docs.traefik.io/user-guide/kubernetes/), I ran into the problem where my white listed IP's were  rejected anyway. It took my a while to figure this out, so at least mentioning this setting might be helpful.

**Comment by timoreimann** [comment]
@sanderPostma ah, this is about _white-listing_. You should have mentioned that. :)

**Comment by timoreimann** [comment]
I think we should leave a note with [the documentation of the corresponding Kubernetes annotation](http://docs.traefik.io/configuration/backends/kubernetes/#annotations).

**Comment by sanderPostma** [comment]
Details are documented [here](https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/) under "Preserving the client source IP"

**Comment by dtomcej** [comment]
@sanderPostma Is this still an issue? We can update our docs to use the new spec if you feel they would be useful.

Thanks!

**Comment by sanderPostma** [comment]
For me it's no issue anymore, but I remember it took me a while to figure out that the service.beta.kubernetes.io/external-traffic annotation was no longer supported in 1.8+. 
I thought I'd share this info to save other users some time and frustrations.

**Comment by dtomcej** [comment]
Hey @sanderPostma Would that snippet be added to the `traefik-ingress-service`?  or to the ingress services?

**Comment by dtomcej** [comment]
Since this has been merged in #3294 , I will close this issue!
