### ISSUE TITLE
Option to tell Let's Encrypt which port to use to send the challange on

### ISSUE THREAD

**Issue by igoratencompass** [containous/traefik#2571]
### Do you want to request a *feature* or report a *bug*?

This is a **feature** request.

#### Description

Let's Encrypt provides the client with an option to specify the port on which it is listening for the challenge which is useful in case of multiple LE clients behind a proxy or a router. In this case we might have several Traefik instances with `443` port as `https` entry point which:

- in some cases may not be available, i.e. that port is already used by some other service behind the fronting proxy
- can not be used for multiple Traefik servers behind the same fronting proxy

It would be useful in these cases to have an option to set the client port to 8443 and forward that one to Traefik's port 443 on the proxy/router. When if we launch a second Traefik instance we can use port 9443 lets say which we redirect to this instance's port 443 and so on.

I went through the documentation and could not find any option of doing this in Traefik. Please let me know if I'm wrong and have missed something.

**Comment by nmengin** [comment]
Hello @igoratencompass,

Many thanks for your interest in the project.

The option you talked about, allow exposing the client on a different port but you have to add a redirection between the port 443 and the customized port (than to a RP for example).

Unfortunately, the limitation is not on the Træfik side but on the Let's Encrypt side.
Indeed, as you can read [here](https://community.letsencrypt.org/t/support-for-ports-other-than-80-and-443/3419/72), only standard ports are allowed.

I close the issue but feel free to re-open it if you impress that I didn't answer your question.
