### ISSUE TITLE
Consul Catalog service not reloaded on port change 

### ISSUE THREAD

**Issue by dacameron** [containous/traefik#2572]
### Do you want to request a *feature* or report a *bug*?

bug

### What did you do?

On updating a service in consul to use a different port, traefik does not reload the service so I get a bad gateway.

### What did you expect to see?
Traefik reloading the service with a new port
### What did you see instead?
A bad gateway error due to traefik using the old port

### Output of `traefik version`: (_What version of Traefik are you using?_)
Not in front of machine where noticed this issue but I was running the docker image traefik:1.4.5

**Comment by mmatur** [comment]
Every time someone does not respect the issue's template, a little bunny dies.

<details>

![southpark - estrella kill rabbit](https://user-images.githubusercontent.com/5674651/27143914-3cea7896-5130-11e7-81f8-02d8ac2da7a7.gif)
![southpark - estrella kill rabbit2](https://user-images.githubusercontent.com/5674651/27143924-49104c72-5130-11e7-82ae-ccedbd5dfa1c.gif)

</details>
<br>

Please edit your issue description to respect the [issue template](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE.md) as much as possible.

**Comment by dacameron** [comment]
Lol, done.

**Comment by traefiker** [comment]
Closed by #2574.

**Comment by dacameron** [comment]
Thanks for the quick fix!
