### ISSUE TITLE
Marathon provider: Condition for task to be filtered

### ISSUE THREAD

**Issue by Gidipp** [containous/traefik#258]
I have configured traefik to use marathon as a backed. 

All my tasks are filtered by traefik with the following message: 
"Filtering disabled marathon task  /task-name "

What are the condition for a task to be filtered? 

How can I add a marathon container to traefik? I would like traefik to act as a proxy and loadbalancer, marathon is starting  container to random ports and I would like the container to be added to a loadbalancer pool with a proxy redirection for a specific Host value. 

Would be possible to do that with traefik?

**Comment by emilevauge** [comment]
Hi @Gidipp, this is due to this PR https://github.com/containous/traefik/pull/251.
But I just found that the doc hasn't been updated with that :'( I will do it quickly.
