### ISSUE TITLE
Redirect to another entrypoint only if it is enabled

### ISSUE THREAD

**Issue by kazigk** [containous/traefik#2596]
### Do you want to request a *feature* or report a *bug*?
I want to request a feature.

### What did you do?
I'm running Traefik configured to work with Let's Encrypt and redirection from http to https enrypoint. I need encrypted connection only on a few backends so I had to use regular expressions, because http protocol is already setted up with redirect and I can't just create another entrypoint on the same port. 

### What did you expect to see?
A way to redirect to another entrypoint (https in this case) only if it is enabled for a backend.

### What did you see instead?
Pretty messed up configuration file. ¯\_ツ_/¯

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.4.5
Codename:     roquefort
Go version:   go1.9.2
Built:        2017-12-06_10:16:48AM
OS/Arch:      linux/amd64

```

**Comment by ldez** [comment]
Seems like a duplicate of #1456

**Comment by kazigk** [comment]
Yes, it’s a duplicate and #2133 solves this issue.
