### ISSUE TITLE
dial tcp 10.254.0.1:443: i/o timeout

### ISSUE THREAD

**Issue by zouhuigang** [containous/traefik#2597]
1 reflector.go:199] github.com/containous/traefik/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Secret: Get https://10.254.0.1:443/api/v1/secrets?resourceVersion=0: dial tcp 10.254.0.1:443: i/o timeout

**Comment by timoreimann** [comment]
Looks like you cannot connect to your Kubernetes API server. This seems unrelated to Traefik per se.

For further end user support, please join the Traefik Slack channel or submit a question to Stackoverflow; the issue tracker is meant for feature requests and bug reports only. If you think this is indeed a Traefik bug, let us know and we'll reopen the issue.
