### ISSUE TITLE
Marathon label traefik.port cannot be parsed

### ISSUE THREAD

**Issue by ktf** [containous/traefik#261]
I am trying to use traefik to redirect to some marathon app running with `--net=host` so I try to force the port by setting the marathon label `traefik.port` to 8888. Treafik however complains it cannot parse it seems to print the message in https://github.com/containous/traefik/pull/138/files#diff-fca3fabc700de27831fb573ad618a81dR140 . If I drop the label and switch to bridge mode, it works just fine.

**Comment by boymaas** [comment]
Same Issue here. Trying to run a marathoh app with --net=host and not able to explicitly define a port with traefik.port due to https://github.com/containous/traefik/blob/master/provider/marathon.go#L202

**Comment by timoreimann** [comment]
This was fixed in #1394 and will be part of the upcoming 1.3 release.
