### ISSUE TITLE
document letsencrypt support

### ISSUE THREAD

**Issue by mischief** [containous/traefik#263]
it's great that letsencrypt support was added, but there should be some documentation for it. having to dig through the code to figure it out is not very fun.

**Comment by emilevauge** [comment]
Hi @mischief, I agree it needs to be improved but you can find some documentation in the traefik.sample.toml and also in the documentation section :)

**Comment by xinity** [comment]
@mischief i've used this example successfully: http://docs.traefik.io/user-guide/examples/#lets-encrypt-support

ping me if you need a bit of a help :)

**Comment by emilevauge** [comment]
Closing it for now. @mischief if you need some help, repoen it ;)
