### ISSUE TITLE
Traefik Ingress controller attempts to access cluster-wide Secrets in Kubernetes

### ISSUE THREAD

**Issue by trondhindenes** [containous/traefik#2632]
*bug*

### What did you do?
With traefik set up as an Ingress controller on Kubernetes, my apiserver logs indicate that Traefik attempts to list all cluster-wide secrets in Kubernetes (Which I have configured to deny). Everything works fine, which is an proves that access to Secrets aren't needed.

### What did you expect to see?
Traefik should not attempt to access Cluster-wide secrets if it doesn't need them

### What did you see instead?
```
kube-apiserver[4140]: I1229 15:50:48.377476    4140 rbac.go:116] RBAC DENY: user "system:serviceaccount:default:traefik-ingress-controller-dev" groups ["system:serviceaccounts" "system:serviceaccounts:default" "system:authenticated"] cannot "list" resource "secrets" cluster-wide
```

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
v1.5.0-rc3 / cancoillotte
```

We're running on Kubernetes 1.8.

**Comment by timoreimann** [comment]
Yep, this is a known issue as documented in #1784. While 1.5 brought support for namespace-specific watches, thereby constraining the problem to a set of namespaces (as opposed to cluster-wide access), we still need to solve this issue more fundamentally.

I'll be closing this one as duplicate. Please track the referenced issue to be notified about updates.

**Comment by trondhindenes** [comment]
great, thanks for the update! Closing it is fine.
