### ISSUE TITLE
traefik should not require ingress addon to work on minikube

### ISSUE THREAD

**Issue by dfang** [containous/traefik#2633]
traefik is an another ingress controller.  why i must enable ingress addon to make traefik rules work on minikube ?

### Do you want to request a *feature* or report a *bug*?
bug

### What did you do?
following this guide: https://github.com/containous/traefik/blob/master/docs/user-guide/kubernetes.md

### What did you expect to see?
traefik should work on minikube whether ingress addon enabled or disabled

### What did you see instead?
when ingress addon disabled, http://traefik-ui.minikube refused to connect.
when ingress addon enabled, http://traefik-ui.minikube works.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
docker image traefik:1.4.5, also tried helm chart 1.14.5
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```
traefik --web --kubernetes
```

**Comment by timoreimann** [comment]
The Ingress controller should not be necessary.

I suspect you rolled out Traefik using a Deployment and did not append the NodePort to the request. Sadly, we have not documented the need to specify the NodePort consistently throughout the entire guide, which is something that we should do.

**Comment by dfang** [comment]
@timoreimann 

yes, if i append the port, in my case, the port is 31081.  traefic-ui.minikube:31081 works.

but if enable ingress addon. i don't need to append the port to access traefik dashboard. that makes me confused.

**Comment by timoreimann** [comment]
@dfang I don't know for sure how the Ingress addon in minikube works. What I suspect though is that it fires up something like an Nginx Ingress controller listening on port 80 on the minikube machine, watches over the available Ingress objects, and forwards traffic accordingly. In essence, it works like a cloud-based Ingress controller in your local environment (except for the fact that it apparently does not respect the Ingress class annotation which should actually keep it from handling Traefik-classified Ingress objects).

If you disable the addon again and provision Traefik as a Daemonset listening on port 80, you should be able to observe the same behavior.

**Comment by dfang** [comment]
got it, thanks
