### ISSUE TITLE
Missing quotes arround the Referer field in access logs

### ISSUE THREAD

**Issue by antoine-roux** [containous/traefik#2649]
### Do you want to request a *feature* or report a *bug*?
Both at the same time...

### What did you do?
We are sending Træfik access logs to a Logstash instance through a Docker GELF log driver.
All is working smoothly, but...

### What did you expect to see?
The access log format of Træfik do not quote the Referrer field when it is empty
https://github.com/containous/traefik/blob/8339139400e5dfd1fed6cb3545d611d8311ab381/middlewares/accesslog/logger_formatters.go#L66

However in the common Apache2 Combined format, this field needs to be quoted
(see https://github.com/elastic/logstash/blob/v1.4.2/patterns/grok-patterns#L91)

As a result, we are not able to parse the access log correctly.

### What did you see instead?
A typical access log line without a Referrer is like:
`x.x.112.4 - - [03/Jan/2018:09:45:13 +0000] "GET / HTTP/1.1" 200 24829 - "curl/7.55.1" 5 "HostRegexp-domain-8" "http://10.0.0.5:80" 3ms`
Note the `-` without surrounding quotes before the User-Agent.

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
Version:      v1.4.5
Codename:     roquefort
Go version:   go1.9.2
Built:        2017-12-06_10:16:48AM
OS/Arch:      linux/amd64
```

Thanks for this wonderful reverse-proxy!
Antoine

**Comment by ldez** [comment]
@antoine-roux Maybe you can use JSON log instead of CLF.

**Comment by ldez** [comment]
Put a `-` when value are missing in the part of CLF.

**Comment by antoine-roux** [comment]
Hello,
You are not using Common Log Format but **Combined** Log Format (yes, it's also CLF)

In this syntax, the Referrer and the User-Agent are always quoted (see https://httpd.apache.org/docs/trunk/logs.html#combined)
` "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-agent}i\"" combined`
Please consider that.

See you,
Antoine
