### ISSUE TITLE
Stickiness cookie secure flag

### ISSUE THREAD

**Issue by maritz** [containous/traefik#2653]
### Do you want to request a *feature* or report a *bug*?

Feature 

### What did you do?

Configured stickiness

### What did you expect to see?

An option to configure the stickiness cookie to be sent with the `secure` flag, so that it only gets sent over https requests.

### What did you see instead?

No option to do that.

**Comment by anantsaraswat** [comment]
Any update on this :)

**Comment by mayrbenjamin92** [comment]
We also need this :)!!

**Comment by gheibia** [comment]
I've submitted https://github.com/vulcand/oxy/pull/174. When merged, I can perhaps submit a PR here to address this.

**Comment by gheibia** [comment]
This is now available on V2 and can be closed.
