### ISSUE TITLE
"No matching manifest" error when pulling Docker image

### ISSUE THREAD

**Issue by sandersaares** [containous/traefik#2672]
### Do you want to request a *feature* or report a *bug*?
bug

### What did you do?
Attempting to follow the quick start instructions in the readme. The `docker run` command fails. Upon narrowing it down to its essentials, it appears that pulling the image is what fails.

```
PS C:\WINDOWS\system32> docker pull traefik
Using default tag: latest
latest: Pulling from library/traefik
no matching manifest for windows/amd64 in the manifest list entries
```

### What did you expect to see?

Successfully pulled image.

### What did you see instead?

Error and no image was pulled.

### Output of `traefik version`: (_What version of Traefik are you using?_)

N/A

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Windows 10 v1709 with Docker 17.10.0-ce.

### If applicable, please paste the log output in debug mode (`--debug` switch)

N/A

**Comment by ldez** [comment]
@sandersaares we don't support Windows (`windows/amd64`) as image.

**Comment by sandersaares** [comment]
I see. Is Windows supported in general? I saw Windows under releases, so it is a bit unexpected to not also see it in Docker.

**Comment by ldez** [comment]
> Is Windows supported in general, outside Docker context?
yes.

For now, we have a binary for Windows, but no dedicated Docker image.

**Comment by sandersaares** [comment]
I will close this then, as it appears to be by design.
