### ISSUE TITLE
Let's Encrypt: use ACME API V2

### ISSUE THREAD

**Issue by nmengin** [containous/traefik#2674]
### Do you want to request a *feature* or report a *bug*?

Feature
### What did you do?

Using ACME to generate certificate for all of mine (sub)domains.
### What did you expect to see?

One certificate per domain.

### What did you see instead?

Use the new ACME API V2 to generate one wildcard certificate.

### Additional information

* ACME API V2 is currently in testing version : https://community.letsencrypt.org/t/staging-endpoint-for-acme-v2/49605
* Træfik is using [lego](https://github.com/xenolf/lego) to manage ACME certificates, an issue reports that the work to use LEGO for ACME API V2 is yet [in progress](https://github.com/xenolf/lego/issues/457#issuecomment-353636846)

**Comment by rvaidya** [comment]
Having this ready for use by the February 27, 2018 LetsEncrypt production rollout would be awesome.

**Comment by jmagnusson** [comment]
The support for wildcard certificates in v2 should be a good match to frontend rules like `HostRegexp: traefik.io, {subdomain:[a-z]+}.traefik.io` where we might have thousands of subdomains dynamically generated from the backend proxy. With Let's Encrypt we're only allowed to issue [20 certificates per domain per week](https://letsencrypt.org/docs/rate-limits/) which is by no means hard to reach today.

**Comment by nmengin** [comment]
Hello,

Any information about this issue : 

* We are still waiting for the LEGO ACME V2 implementation. **WIP** : https://github.com/xenolf/lego/issues/457#issuecomment-365326009

* Please note that **only DNS Challenge** will be able to generate wildcard certificates as explained here : 

> The V2 API supports issuing wildcard certificates. To request a wildcard certificate simply send a wildcard DNS identifier in the newOrder request. Wildcard identifiers may only be authorized by DNS-01 challenge, so order authorizations corresponding to wildcard identifiers will only include a pending DNS-01 challenge. DNS names in certificates may only have a single wildcard character, and it must be the entire leftmost DNS label, for instance “*.example.com”. A single certificate can have wildcard DNS identifiers for multiple base domains.

(https://community.letsencrypt.org/t/staging-endpoint-for-acme-v2/49605)

Be sure we know the importance of this feature and we'll prevent you when the subject will evolve.

**Comment by palmerabollo** [comment]
ACMEv2 and wildcard certificate support is now live
https://community.letsencrypt.org/t/acme-v2-and-wildcard-certificate-support-is-live/55579

**Comment by mavimo** [comment]
There is also implementation on stdlib https://github.com/golang/go/issues/21081

**Comment by sarkistlt** [comment]
I'm trying to use it with docker backend like so `'traefik.frontend.wildcard.rule=HostRegexp:{subdomain:[a-z]+}.domain.com'`, but it still generates certs pear each defined subdomain `- 'traefik.frontend.rule=Host:traefik.domain.com'`,

or support is not on production yet?

**Comment by siwyd** [comment]
@sarkistlt No, ACMEv2 is live but that doesn't mean Traefik supports it. When this ticket is closed at some point, you should check the docs on how to implement this.

**Comment by sarkistlt** [comment]
I see, hope it will be soon, really like this proxy, already switched my production projects to traefik, works perfect

**Comment by bclermont** [comment]
@mavimo x/* is not stdlib!
