### ISSUE TITLE
Add option to ignore broken certificate on backend 

### ISSUE THREAD

**Issue by ktf** [containous/traefik#268]
Hi, I need to proxy a backend (not in my control) which exposes only an SSL endpoint and which has a bogus certificate setup. Is / Would it be possible to ignore any SSL error (ala `curl -k`)?

**Comment by emilevauge** [comment]
@ktf Yep, traefik should support insecure backends.
PR are welcomed ;)

**Comment by ktf** [comment]
For the moment i simply spawned a separate nginx and used traefik to redirect to it.

**Comment by distributorofpain** [comment]
This is something that would be preferred in environments like mantl where we need to do pass through ssl to containers.

**Comment by stuart-c** [comment]
I've just submitted #557

**Comment by Regner** [comment]
Looks like #557 was merged and so this can be closed. @timoreimann
