### ISSUE TITLE
Support http-01 LetsEncrypt protocol

### ISSUE THREAD

**Issue by eldondev** [containous/traefik#2688]
### Do you want to request a *feature* or report a *bug*?

feature

### What did you do?

reviewed acme challenge code.

### What did you expect to see?

http-01 support for getting DV certificates from LE via ACME

### What did you see instead?

http-01 challenge appears to be excluded.

Since LE has disabled tls-sni due to shared hosting provider issues, renewing or generating certificates with traefik is probably failing or going to fail for many people soon. I am sorry if this is a dupe or misfiled, but I didn't see any previous discussion of it except for [this](https://stackoverflow.com/questions/48192975/traefik-error-forwarding-eof-bad-gateway-lets-encrypt-related) without signing into slack, and the lack of public logging makes me consider slack harmful for OSS.

**Comment by ldez** [comment]
Duplicate of #1832
