### ISSUE TITLE
Slow UI

### ISSUE THREAD

**Issue by krjensen** [containous/traefik#2693]
Hi,

Could we get some performance work on the UI, we have about 300 services coming from consul, and when I open the UI, it takes a long time to load and its just really slow when i click around.

Kristian

**Comment by immobilien-zeitung** [comment]
Hallo, warum bekomme ich ihre E-Mails?

Viele Grüße aus Wiesbaden
 
Mirko Tinz
Leiter Marketing & Vertrieb
 
Telefon +49 611 / 97326-68
Telefax +49 611 / 97326-5568
tinz@iz.de <mailto:tinz@iz.de>
www.immobilien-zeitung.de <http://www.immobilien-zeitung.de/>
www.iz-research.de <http://www.iz-research.de/>
 



 
IZ Immobilien Zeitung Verlagsgesellschaft mbH
Luisenstr. 24
65185 Wiesbaden
 
Geschäftsführung: Jan Mucha
Registergericht: AG Wiesbaden, HRB 22996
 
Eine Beteiligung der dfv Mediengruppe

**Comment by traefiker** [comment]
Every time someone does not respect the issue's template, a little bunny dies.

<details>

![southpark - estrella kill rabbit](https://user-images.githubusercontent.com/5674651/27143914-3cea7896-5130-11e7-81f8-02d8ac2da7a7.gif)
![southpark - estrella kill rabbit2](https://user-images.githubusercontent.com/5674651/27143924-49104c72-5130-11e7-82ae-ccedbd5dfa1c.gif)

</details>
<br>

Please edit your issue description to respect the [issue template](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE.md) as much as possible.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Slack workspace](https://traefik.herokuapp.com/) for more [community #support](https://traefik.slack.com/messages/C0CDT22PJ/).
