### ISSUE TITLE
HTTP Chunked Encoding Termination Internal Server Error

### ISSUE THREAD

**Issue by danieladams456** [containous/traefik#2696]
### Do you want to request a *feature* or report a *bug*?
Bug

### What did you do?
- Real environment case: Spring Boot services on upstream and downstream ends of Traefik
- Reproduction case: load test against Traefik -> Spring Boot Actuator env endpoint with https://github.com/tsenart/vegeta

### What did you expect to see?
HTTP 200 responses from the service

### What did you see instead?
Traefik is logging HTTP 500 internal server errors instead of HTTP 200s for some responses.  There are also log entries for `multiple response.WriteHeader calls` and `Error copying upstream response body: unexpected EOF` corresponding to those 500s.

The response to the client also has `Internal Server Error` appended to the HTML payload.  Thankfully we haven't seen any application issues with it yet, but it is concerning because a JSON parse of that chunk will probably fail which could cause an app impact.

### Further troubleshooting
During my efforts to understand what was going on and gather the most information possible for bug reports, I took packet captures inside the Traefik and origin service docker containers.  I am adding screenshots here of the issue, but I can privately send the full packet captures if necessary.

It appears that at the end of the TCP stream, Spring Boot ([Actuator](https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html) specifically in this example, but we're seeing it for other standard Spring Boot service calls as well) is not correctly terminating the HTTP chunked encoding.  For the last response in a reused TCP stream, about 60% of the time it does not send the closing HTTP chunk with the standard 0 length.  It instead closes the TCP stream with a FIN/ACK, FIN/ACK, ACK.  This seems to show it's not a network issue of the TCP stream being cut off prematurely.   https://tools.ietf.org/html/rfc2616#section-3.6.1 says that the HTTP chunked encoding should always be closed, so it appears Spring Boot is at fault here, but Traefik is handling it in a way that has the potential to be problematic for downstream services.

### Expected output given the corner case here
Ideally the Traefik logs would show the HTTP response as given by the origin.  I think the more important issue though is that the body be passed on to the client unmodified to avoid JSON parsing errors.

### Output of `traefik version`: (_What version of Traefik are you using?_)
I also tested with ```v1.5.0-rc3``` to make sure it hadn't been fixed already.
```
Version:      v1.4.1
Codename:     roquefort
Go version:   go1.9.1
Built:        2017-10-24_05:25:28PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
real environment:
```yaml
services:
  traefik:
    image: traefik:v1.4.1-alpine
    command:
      - --web
      - --logLevel=WARN
      - --accessLog
      - --accessLog.format=json
      - --entryPoints=Name:https Address::443 TLS:/run/secrets/traefik-cert,/run/secrets/traefik-key
      - --defaultEntryPoints=https
      - --docker
      - --docker.swarmmode
      - --docker.watch
      - --docker.domain=redacted.net
      - --forwardingTimeouts.dialTimeout=10s
      - --forwardingTimeouts.responseHeaderTimeout=60s
    ports:
      - "8443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - source: traefik-cert-v1
        target: traefik-cert
      - source: traefik-key-v1
        target: traefik-key
    networks:
      - redacted-one
      - redacted-two
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-1
        awslogs-group: /internal/ddc/traefik
    labels:
      com.docker.ucp.access.label: devops
    deploy:
      mode: global
      placement:
        constraints:
          - node.role==manager
      labels:
        com.docker.ucp.access.label: devops
      update_config:
        parallelism: 1
        delay: 30s
        # failure_action: rollback
        monitor: 10s
        max_failure_ratio: 0.2
      restart_policy:
        max_attempts: 3
        window: 10s


networks:
  redacted-one:
    external: true
  redacted-two:
    external: true

secrets:
  traefik-cert-v1:
    external: true
  traefik-key-v1:
    external: true
```
Reproduction environment: (HTTPS turned off for better packet captures, did not seem to affect behavior)
```yaml
version: '3.1'

services:
  traefik:
    image: traefik:v1.4.1-alpine
    command:
      - --web
      - --logLevel=WARN
      - --accessLog
      - --accessLog.format=json
      - --entryPoints=Name:https Address::80
      - --defaultEntryPoints=https
      - --docker
      - --docker.swarmmode
      - --docker.watch
      - --docker.domain=test.net
      - --forwardingTimeouts.dialTimeout=10s
      - --forwardingTimeouts.responseHeaderTimeout=60s
    ports:
      - "8443:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - testnet
    deploy:
      mode: global
      placement:
        constraints:
          - node.role==manager

networks:
  testnet:
    external: true
```

### If applicable, please paste the log output in debug mode (`--debug` switch)

```
docker logs -f f940db541c47 | grep EOF
2018/01/10 16:08:26 server.go:2848: http: multiple response.WriteHeader calls
time="2018-01-10T16:08:26Z" level=warning msg="Error copying upstream response body: unexpected EOF" 
2018/01/10 16:08:31 server.go:2848: http: multiple response.WriteHeader calls
time="2018-01-10T16:08:31Z" level=warning msg="Error copying upstream response body: unexpected EOF" 
2018/01/10 16:11:15 server.go:2848: http: multiple response.WriteHeader calls
time="2018-01-10T16:11:15Z" level=warning msg="Error copying upstream response body: unexpected EOF" 
2018/01/10 16:11:20 server.go:2848: http: multiple response.WriteHeader calls
time="2018-01-10T16:11:20Z" level=warning msg="Error copying upstream response body: unexpected EOF" 
time="2018-01-10T16:11:23Z" level=warning msg="Error copying upstream response body: unexpected EOF" 
2018/01/10 16:11:23 server.go:2848: http: multiple response.WriteHeader calls
time="2018-01-10T16:11:23Z" level=warning msg="Error copying upstream response body: unexpected EOF" 
2018/01/10 16:11:23 server.go:2848: http: multiple response.WriteHeader calls
2018/01/10 16:11:24 server.go:2848: http: multiple response.WriteHeader calls
time="2018-01-10T16:11:24Z" level=warning msg="Error copying upstream response body: unexpected EOF" 
time="2018-01-10T16:11:24Z" level=warning msg="Error copying upstream response body: unexpected EOF" 
2018/01/10 16:11:24 server.go:2848: http: multiple response.WriteHeader calls
2018/01/10 16:11:27 server.go:2848: http: multiple response.WriteHeader calls
time="2018-01-10T16:11:27Z" level=warning msg="Error copying upstream response body: unexpected EOF" 
2018/01/10 16:31:35 server.go:2848: http: multiple response.WriteHeader calls
time="2018-01-10T16:31:35Z" level=warning msg="Error copying upstream response body: unexpected EOF" 
2018/01/10 16:31:37 server.go:2848: http: multiple response.WriteHeader calls
time="2018-01-10T16:31:37Z" level=warning msg="Error copying upstream response body: unexpected EOF" 
2018/01/10 16:31:38 server.go:2848: http: multiple response.WriteHeader calls
2018/01/10 16:31:38 server.go:2848: http: multiple response.WriteHeader calls
time="2018-01-10T16:31:38Z" level=warning msg="Error copying upstream response body: unexpected EOF" 
time="2018-01-10T16:31:38Z" level=warning msg="Error copying upstream response body: unexpected EOF" 
2018/01/10 16:31:41 server.go:2848: http: multiple response.WriteHeader calls
time="2018-01-10T16:31:41Z" level=warning msg="Error copying upstream response body: unexpected EOF" 
2018/01/10 16:31:42 server.go:2848: http: multiple response.WriteHeader calls
time="2018-01-10T16:31:42Z" level=warning msg="Error copying upstream response body: unexpected EOF" 
```

![full round trip with issue](https://user-images.githubusercontent.com/3953840/34832225-43e8ac58-f6b7-11e7-8837-3f7bd48d77f2.png)
![no chunked encoding termination but tcp was closed gracefully](https://user-images.githubusercontent.com/3953840/34832227-441e43e0-f6b7-11e7-912d-99ce44e658ba.png)

**Comment by timoreimann** [comment]
@danieladams456 thanks for the detailed bug report!

Just to be safe, could you also please try out the latest 1.5 release candidate (-rc4 as of now)? There were a few bug fixes, though none seems to match your case perfectly.

Thanks.

**Comment by timoreimann** [comment]
Do you think there's a possibility to provide that faulty Spring server in a reduced, easy to reproduce fashion? That could help a lot.

**Comment by danieladams456** [comment]
@timoreimann  we are off Monday for Martin Luther King Jr day, but I will work with the developers on Tuesday to see if we can get a stripped down demo container.  Who knows, we might even be able to find a root cause on the Spring side.  I'll also try the RC4 build.  I had tried RC3 earlier, but might as well be sure.

We have two other services that are causing the same error, just not as frequently as this one.  Hopefully those can help in providing some insight.  Worst case we can take the current one and make sure anything sensitive is stripped out if we can't reproduce by building a demo from scratch.

**Comment by danieladams456** [comment]
Yesterday we were trying to reproduce the issue in a gutted demo container and kept not being able to.  Eventually we were back at the original service on the exact git commit.  After some thinking, I realized the only thing that had changed was the Docker base image.  That service was using `anapsix/alpine-java:8`, which currently is 8 days old since it isn't pinned to an exact version.  The container in question was several months old, so built on a different base image.  I can't be certain, but it looks like it might have been an issue with the base Java runtime, since the Spring dependency versions are the same as before.

We are now switched to the preferred OpenJDK with a pinned exact version (`openjdk:8u151-jre-alpine`.)  We'll let this run in dev and qa for a week and see if we can break it.  I'll update the issue if we experience the same HTTP problems.
