### ISSUE TITLE
Decision logic before calling the docker container

### ISSUE THREAD

**Issue by christinhyun** [containous/traefik#2705]
### Do you want to request a *feature* or report a *bug*?
feature

### What did you do?
Manual check and Google search.

I built a service on Amazon ECS using traefik.
I use Route53 and ELB. ( *.test.net )
All requests are made through traefik.
http://aa.test.net  -> ELB -> traefik -> docker container

### What did you expect to see?
Add custom logic.

I would like traefik to be able to handle simple logic before calling the docker container.
For example, I want to limit the calls per month for each Docker container.
However, I could not find out which function of traefik should be used.

I would like traefik to be able to add simple custom logic before calling this docker container.
If  already have a feature, let me know.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
(paste your output here)
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```
--web,--logLevel=DEBUG,--ecs,--ecs.clusters=ecs-test,--ecs.domain=test.net,--ecs.watch,--ecs.refreshseconds=30
```

**Comment by ldez** [comment]
Thanks for your interest in Træfik !

I don't really understand your need.

Take a look on [rate limiting](http://v1-5.archive.docs.traefik.io/configuration/commons/#rate-limiting)

Before open an issue, you can ask a question on the [Træfik community Slack](https://traefik.herokuapp.com).

Related to https://stackoverflow.com/questions/48250788/related-to-traefiks-container-call-restriction

**Comment by christinhyun** [comment]
@ldez  Thank you for quick response.
I've looked at the Rate Limiting content of the link.
In the example, Traefik's Rate Limiting feature is limited by client IP.
extractorfunc = "client.ip"

Can I limit it to a full request for all clients, not for each client?
I am thinking of SaaS(Software as a Service).
So I want to limit the calls per service domain. (ex. aa.test.net)

For example, when i set the amount of Rate Limiting to aa.test.net as follows:
period = "2592000s"
average = 10
burst = 20

I would like to the following scenarios.
A User client calls five times in a month ...
And B User client calls five times in a month ...
A total of 10 calls occurred within a month.
I want to prevent further calls because it exceeds the rate limit I set.


How do I set the extractorfunc value to work the way I want?
extractorfunc = "client.ip"

If it is not supported now, it would be better to put the call limit function.

With different requirements ...
For developers who want to add their own business logic ...
it would be nice if developer's could control traefik by return value Yes or No in conjunction with DB or something.
I am sorry that my English is poor.
I hope you can understand what I want.

**Comment by emilevauge** [comment]
Sorry @christinhyun, we don't plan to add this feature in Traefik.
Closing this issue then.
Thanks for your understanding.
