### ISSUE TITLE
Benchmark is misleading

### ISSUE THREAD

**Issue by vincentbernat** [containous/traefik#271]
Hi!

The benchmark provided in documentation is quite misleading: the performances are pretty low. I didn't test myself but you should first benchmark the "whoami" service. Moreover, you are likely to hit the limit on the local port range. You should increase it (`net.ipv4.ip_local_port_range`). The performance should increase with just this setting. You could increase the number of backends too. You will still hit the limit between wrk and the tested reverse proxy. You should use several ports (or several IP) to alleviate this limit.

**Comment by emilevauge** [comment]
HI @vincentbernat 

Benchmarks given in the documentation are only **early, quick&dirty** benchmarks ;) (But even those ones have been made increasing some ulimit...).
Of course, serious benchmarks should be made with several machines, more than two backends, etc, etc... And that's clearly in my todo list.

But,

1. It takes some time to do this seriously :)
2. I need a strong infrastructure. I exactly asked https://twitter.com/traefikproxy/status/715466984528347137 yesterday, I'm looking for some help on that ;)

**Comment by vincentbernat** [comment]
Well, if help is only getting some VM, I can propose you to create an account here: https://www.exoscale.ch and I can add you 50 CHF of credit to do your tests (mail me at vbe@ when you have your account, or here). Unfortunately, I don't have time either to do the benchmarks. Always easier to ask others to do the work. :)

**Comment by emilevauge** [comment]
Great @vincentbernat ! Thanks a lot :)
