### ISSUE TITLE
Access to labels/annotations from templates

### ISSUE THREAD

**Issue by tcolgate** [containous/traefik#2746]
Previously custom templates could access the kubernetes/marathon providers objects fairly directly. Whilst this access was very different per provider, it gave considerable raw power to build custom policies. This access has been reduced in favour of a more common set of features between providers.

The marathon provider still provides the raw access to the underlying marathon objects. The Kubernetes provider does not. This makes it impossible to build custom policies around labels or annotations on an ingress. This, in turn, significantly reduces the usefulness of custom templates.

A more specific example is as follows.
* We have traditionally defaulted to having all apps redirect http -> https
* We would like to allow an opt-out to allow direct http
* Traditionally we would add a label/annotation to the ingress to indicate this.

With current traefik (1.5rc5), this option could be implemented via the standard annotations, however, I cannot change the defaults. I can't default to redirect, and selectively opt-out, without redeploying all our ingresses to include the require annotation. I can't build any custom policy around non-standard annotations. The only option would be multiple traefik instances with different label selectors or classes, but this would make for a much more complicated deployment (ours is already quite complicated).

Would it be possible to pass the raw ingress objects to the template?

**Comment by ldez** [comment]
@tcolgate I currently work on this 😃

**Comment by tcolgate** [comment]
@ldez out of interest, what approach are you taking? and is it likely to make it into 1.5?

**Comment by ldez** [comment]
1.5 is freeze 😉 .
Check what I have done on the master branch 😃 .
I still working to have a better more stable functions in provider templates.
Some PRs coming soon.

**Comment by tcolgate** [comment]
Had a quick look at master, have not noticed much different from 1.5rc5 in terms of the template objects. If you can, would be great to get a CC: on anything related. Some provider-specific template data, with a relatively stable interface), would be really handy.

**Comment by ldez** [comment]
Closed in favor of #2785
