### ISSUE TITLE
404 url

### ISSUE THREAD

**Issue by daodaovps** [containous/traefik#2753]
> !!! note For this example to work you need a TLS entrypoint. You don't have to provide a TLS certificate at this point. For more details see here.  

see here target href  is 404

**Comment by traefiker** [comment]
Every time someone does not respect the issue's template, a little bunny dies.

<details>

![southpark - estrella kill rabbit](https://user-images.githubusercontent.com/5674651/27143914-3cea7896-5130-11e7-81f8-02d8ac2da7a7.gif)
![southpark - estrella kill rabbit2](https://user-images.githubusercontent.com/5674651/27143924-49104c72-5130-11e7-82ae-ccedbd5dfa1c.gif)

</details>
<br>

Please edit your issue description to respect the [issue template](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE.md) as much as possible.

**Comment by ldez** [comment]
Thanks for your interest in Traefik 😃 

The link works https://docs.traefik.io/master/user-guide/kubernetes/#add-a-tls-certificate-to-the-ingress

https://docs.traefik.io/master/configuration/entrypoints/
