### ISSUE TITLE
enabling of prometheus metrics requires "entrypoint=traefik"

### ISSUE THREAD

**Issue by tcolgate** [containous/traefik#2755]
### What did you do?

Started traefik 1.5rc5 with:

`--web.metrics.prometheus=true`

### What did you expect to see?

Prometheus metrics on the web port at /metrics

### What did you see instead?

404 not found

If I add 

`--web.metrics.prometheus.entrypoint=traefik`

Things appear.

This appears to be due to lacking defaults in configuration/configuration.go and likely impacts other metrics sources.

**Comment by Juliens** [comment]
Can you try with the 1.5.0 ?

**Comment by tcolgate** [comment]
Can confirm this is clear in 1.5
