### ISSUE TITLE
[Feature Request] Annotations for setting ratelimit for ingress

### ISSUE THREAD

**Issue by yue9944882** [containous/traefik#2783]
### Do you want to request a *feature* or report a *bug*?
feature

### What did you expect to see?

I want to try out rate limiting features of traefik by simply adding annotations for kubernetes ingress instead of manually modifying toml configuration files:

- `traefik.frontend.rateLimit.extractorFunc`
- `traefik.frontend.rateLimit.rateSet.burst`
- `traefik.frontend.rateLimit.rateSet.period`
- `traefik.frontend.rateLimit.rateSet.average`

I think corresponding configurations for ratelimiting should be appended here at first

[https://github.com/containous/traefik/blob/master/templates/kubernetes.tmpl](https://github.com/containous/traefik/blob/master/templates/kubernetes.tmpl)

Any plan on this feature plz?

**Comment by ldez** [comment]
already done in #2612
