### ISSUE TITLE
Add the ability to globaly configure Security Headers for all frontend

### ISSUE THREAD

**Issue by waldo2188** [containous/traefik#2786]
### Do you want to request a *feature* or report a *bug*?
feature

### What did you do?

Configure Security Headers for docker backend.

### What did you expect to see?

I want to be able to configure Security Headers once for all frontend and not in each fontend configuration.

### What did you see instead?

In my docker-compose I have 10 frontends. I have to add in labels section of each services configuration these properties :

```yaml
      - traefik.frontend.headers.SSLRedirect=true
      - traefik.frontend.headers.SSLHost=exemple.com
      - traefik.frontend.headers.STSSeconds=315360000
      - traefik.frontend.headers.STSIncludeSubdomains=true
      - traefik.frontend.headers.STSPreload=true
      - traefik.frontend.headers.frameDeny=true
      - traefik.frontend.headers.browserXSSFilter=true
```
It’s a lot to set and to maintain.

### Output of `traefik version`: (_What version of Traefik are you using?_)

Traefik 1.5

**Comment by dtomcej** [comment]
@waldo2188 If you wanted to apply this to all of your services, you could create a custom template that implements those configurations, so that they would be applied to all containers.

**Comment by waldo2188** [comment]
Thanks for your reply. How do you do that ?
Is therer a documentation for creating template?

**Comment by dtomcej** [comment]
hello @waldo2188 , http://docs.traefik.io/configuration/commons/#override-default-configuration-template is where the configuration is documented.

It would involve taking the provider template from `/templates` in this repo, and adding the sections you want. Then when you apply that template following the documentation above, it will be applied.

I will go ahead and close this issue, but I would invite you to join our slack team (https://traefik.herokuapp.com/) for further assistance or if you have any questions!
