### ISSUE TITLE
Is there a mirror feature such as tee proxy in nginx

### ISSUE THREAD

**Issue by unisqu** [containous/traefik#2791]
Is there already a feature like this for traefik?
http://nginx.org/en/docs/http/ngx_http_mirror_module.html

**Comment by ldez** [comment]
Thanks for your interest in Traefik !

Every question asked in issues means less features 😉.

The issue tracker is for reporting bugs and feature requests only.
For end-user related support questions, refer to one of the following:
- the [Traefik community Slack channel](https://traefik.herokuapp.com)
