### ISSUE TITLE
Command line configuration issue

### ISSUE THREAD

**Issue by Toub** [containous/traefik#2797]
### Do you want to request a *feature* or report a *bug*?

DOCUMENTATION ISSUE

### What did you expect to see?

1) The following example is wrong: https://docs.traefik.io/user-guide/cluster-docker-consul/

```bash
traefik \
    --entrypoints=Name:http Address::80 Redirect.EntryPoint:https \
    --entrypoints=Name:https Address::443 TLS \
    --defaultentrypoints=http,https
```

At least when using with "docker service create", the end of the line is not taken into account, but the following works:

```bash
traefik \
    --entrypoints='Name:http Address::80 Redirect.EntryPoint:https' \
    --entrypoints='Name:https Address::443 TLS' \
    --defaultentrypoints=http,https
```

2) The documentation is not clear about how to use command line configuration.

A link to [configuration.go](https://github.com/containous/traefik/blob/master/configuration/configuration.go) would be useful:

```bash
# EntryPoints EntryPoints `description:"Entrypoints definition using format: 
--entryPoints='Name:http Address::8000 Redirect.EntryPoint:https' --entryPoints='Name:https Address::4442 TLS:tests/traefik.crt,tests/traefik.key;prod/traefik.crt,prod/traefik.key'" export:"true"`
```

### What did you see instead?

Missing `'` in the documentation + missing link to [configuration.go](https://github.com/containous/traefik/blob/master/configuration/configuration.go)

### Output of `traefik version`: (_What version of Traefik are you using?_)

Documentation issue (and using last version: 1.5.1)

**Comment by traefiker** [comment]
Closed by #2798.
