### ISSUE TITLE
WebUI development / help needed

### ISSUE THREAD

**Issue by debovema** [containous/traefik#281]
Hello,

Does the Web UI running in development with `gulp serve` command is supposed to connect to a running Træfɪk instance ?

On this [documentation file](https://github.com/containous/traefik/blob/master/webui/readme.md), it is stated :

> Træfɪk API connections are defined in:
> 
> webui/src/app/core/health.resource.js
> webui/src/app/core/providers.resource.js

The second file contains
> return $resource('/api/providers');

The default instance actually serves at _http://localhost:8080/api/providers_

I am not sure whether this configuration allows to bind the Web UI running in development mode to a Træfɪk instance (is it at least possible?)

My goal is to have an instance of Træfɪk running (with binary or docker image) and to have the development version of Web UI (run with `gulp serve`) connecting to this instance to display its backends and frontends in order to test full features of the Web UI and not only the header bar which is the only element I can change in development mode.

Thanks in advance !

**Comment by emilevauge** [comment]
Hi @debovema, @ldez should help you on this ;)

**Comment by ldez** [comment]
Hi @debovema,

For the Web UI development, I mock all the Traefik Rest API, it's more easy than have a lot of services running.

Instead you can override resources endpoints like that:

```javascript
return $resource('http://localhost:8080/api/providers');
```
```javascript
return $resource('http://localhost:8080/health');
```

I going to create a specific task do to this more easily.

**Comment by debovema** [comment]
Hi @ldez,

It turns out that I already tried this syntax. Instead of localhost I am using the hostname of the machine where Træfɪk and Web UI are deployed (since connections with Træfɪk API are performed on client-side). All HTTP response codes are 200 but there is no data:

![traefik](https://cloud.githubusercontent.com/assets/8082252/14318024/4180464a-fc0b-11e5-9eb4-a92384ed8cff.png)

whereas the same request originated from default port 8080 gives:

![traefik2](https://cloud.githubusercontent.com/assets/8082252/14318029/464e5a22-fc0b-11e5-8bd4-4ab4081fab60.png)

Could it be some restriction when API and Web UI are not on the same port ?

**Comment by emilevauge** [comment]
@debovema what do you get when you curl this URL?

**Comment by debovema** [comment]
Hi @emilevauge,

I get the correct response (see below).

> $ curl 'http://traefik.****.**:8080/api/providers'`

`{"docker":{"backends":{"backend-foo":{"servers":{"server-example-v1-1":{"url":"http://172.17.0.3:80","weight":1},"server-example-v1-2":{"url":"http://172.17.0.4:80","weight":1}},"loadBalancer":{"method":"wrr"}},"backend-foo2":{"servers":{"server-example-v1-3":{"url":"http://172.17.0.5:80","weight":1}},"loadBalancer":{"method":"wrr"}}},"frontends":{"\"frontend-Path-other\"":{"entryPoints":["http1"],"backend":"backend-foo2","routes":{"\"route-frontend-Path-other\"":{"rule":"Path:/other"}}},"\"frontend-Path-test\"":{"entryPoints":["http"],"backend":"backend-foo","routes":{"\"route-frontend-Path-test\"":{"rule":"Path:/test"}}}}}}%`

As I suspected and confirmed with FireBug, it seems to be an XSS-related issue.

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://traefik.****.**:8080/api/providers. (Reason: CORS header 'Access-Control-Allow-Origin' missing).

And it seems to happen directly in Angular stack.

**Comment by emilevauge** [comment]
This probably comes from the server side in fact... CORS are not enable on the server.

**Comment by debovema** [comment]
I found a solution with no need to enable CORS on server.

It's as simple as setting a "proxy" to the backend of the UI (Træfɪk) this way:
In file _https://github.com/containous/traefik/blob/master/webui/gulp/server.js_, replace line
` // server.middleware = proxyMiddleware('/users', {target: 'http://jsonplaceholder.typicode.com', changeOrigin: true});`

by

` server.middleware = proxyMiddleware('http://example.com:8080', {changeOrigin: true});`

where _example.com_ has to be changed.

I wonder if there is a possibility to provide this argument in some way (I am no expert in node.js/gulp/... stack). Something like:
`gulp serve --proxy http://example.com:8080` would be great !

Maybe @ldez can help on this ? :innocent: 

Otherwise the issue is resolved on my side.
Many thanks to both of you :satisfied: :+1:
