### ISSUE TITLE
Eureka configuration stops refreshing after a failure

### ISSUE THREAD

**Issue by cbos** [containous/traefik#2831]
We have a traefik docker container connected to Eureka.

It is fetching the configuration each 30seconds and after a while it stops fetching new configurations:
![image](https://user-images.githubusercontent.com/255404/36020791-224c7ed8-0d84-11e8-98c9-230a83d134cf.png)

Last message is:
`
level=error msg="Failed to refresh Provider configuration, error: 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
`
Then it stops fetching the services from Eureka.

The issue is in the Eureka.go code:
https://github.com/containous/traefik/blob/6a92ac0b7b04ea69a995f7635c0a7fb81fdfc952/provider/eureka/eureka.go#L58

Once there is an issue, it stops the loop for checking new updates, rather then skipping that iteration and wait for the next tick.

**Comment by traefiker** [comment]
Closed by #2838.
