### ISSUE TITLE
Clickable frontend link in the web UI

### ISSUE THREAD

**Issue by Horkyze** [containous/traefik#2835]
### Do you want to request a *feature* or report a *bug*?

Feature

![image](https://user-images.githubusercontent.com/1040383/36036842-386b9df2-0dbb-11e8-8b47-3d949ac614e2.png)

I would really love to be able to click the link in the red rectangle, just like in the backend

**Comment by emilevauge** [comment]
Hi @Horkyze 
We support multiple [matchers](http://docs.traefik.io/basics/#matchers) and it's not possible to generate a link for all of them (ie `HostRegexp`). As we prefer to have a homogeneous behavior we cannot add a clickable link for one matcher type only.
