### ISSUE TITLE
revision of client-go dependency in vendor needs bumped!

### ISSUE THREAD

**Issue by yue9944882** [containous/traefik#2840]
### Do you want to request a *feature* or report a *bug*?
feature

### What did you expect to see?
[https://github.com/containous/traefik/blob/6a92ac0b7b04ea69a995f7635c0a7fb81fdfc952/Gopkg.toml#L189](https://github.com/containous/traefik/blob/6a92ac0b7b04ea69a995f7635c0a7fb81fdfc952/Gopkg.toml#L189)
I think it's sort of outdated. Any plan on upgrading this?

And kubernetes release-1.5 seems not maintained any more. Bumping this can activate more client-side utilities without breaking the compatibility. WDYT?

| Branch         | Canonical source code location       | Maintenance status            |
|----------------|--------------------------------------|-------------------------------|
| client-go 1.4  | Kubernetes main repo, 1.4 branch     | = -                           |
| client-go 1.5  | Kubernetes main repo, 1.5 branch     | = -                           |
| client-go 2.0  | Kubernetes main repo, 1.5 branch     | = -                           |
| client-go 3.0  | Kubernetes main repo, 1.6 branch     | = -                           |
| client-go 4.0  | Kubernetes main repo, 1.7 branch     | ✓                             |
| client-go 5.0  | Kubernetes main repo, 1.8 branch     | ✓                             |
| client-go 6.0  | Kubernetes main repo, 1.9 branch     | ✓                             |
| client-go HEAD | Kubernetes main repo, master branch  | ✓                             |

**Comment by yue9944882** [comment]
@timoreimann

**Comment by timoreimann** [comment]
Updating client-go has definitely been on my list for quite a while. Apart from some improved functionality in the library itself, it might also help us reduce the amount of dependencies we have as upstream client-go has had a few unnecessary deps in the past.

glide used to be a blocker; with our transition to dep, however, updating should now be easier. Whoever does the change must be prepared though that a ton of packages have moved around, so it might not be that easy.

@yue9944882 if you want to take a stab, I'd be happy!

**Comment by yue9944882** [comment]
@timoreimann Of course I will have a try on that :-)
