### ISSUE TITLE
Ensure deterministic routing behavior when multiple providers define the same frontend

### ISSUE THREAD

**Issue by timoreimann** [containous/traefik#2856]
### Do you want to request a *feature* or report a *bug*?

Bug (probably)

### What did you do?

Define the same frontend (in terms of equal path/host rules and prioritys) in two providers.

### What did you expect to see?

Some kind of deterministic routing behavior. For instance, balancing backends from both providers evenly for the matching frontend.

### What did you see instead?

Some provider always getting preferred; presumably, it depends on some implementation detail located [around here](https://github.com/containous/traefik/blob/029fa8369003873bc35b17075e48183ba4411651/configuration/provider_aggregator.go#L84:27).

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

File, Marathon, and Kubernetes providers in usage.

/cc @ldez @dtomcej

**Comment by Juliens** [comment]
We talk about it on slack with @timoreimann.
There is no preffered provider, if two frontents priority are equals, this is random (`for` on a `map`).
