### ISSUE TITLE
Rancher + Traefik + DNS / Watch internal domain

### ISSUE THREAD

**Issue by MichelDiz** [containous/traefik#2857]
### Do you want to request a *feature* or report a *bug*?

feature

### What did you do?

added two host in the same Traefik among Rancher.
One external Other internal.

### What did you expect to see?

The Traefik tracks and manage correctly the internal traffic in Rancher. At the same time that deal with incoming external traffic.

### What did you see instead?

Traefik receives the settings of the Labels. Shows the provider information correctly. Including the correct port and IP of the container. But it does not listen to queries on the given host. 
For example: 
```console
cURL mytest.rancher.internal
Returns ==>> curl: (7) Failed to connect to mytest.rancher.internal port 80: Connection refused
```

This example does not work, it's as if Traefik did not have access to Rancher's DNS.

### Output of `traefik version`: (_What version of Traefik are you using?_)

But happens in old ones too.

```
v1.5.2 / cancoillotte
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```shell
--web --rancher --rancher.api.endpoint=http://192.168.25.140:8080 --rancher.api.accesskey=xxxxxxxxxxxxxxxxx --rancher.api.secretkey=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx --rancher.domain=mysite.com.br, rancher.internal --logLevel=DEBUG
```

I mean I tried hard before opening this issue. Now I believe that this is a feature that doesn't exist in Traefik.

I tried to open questions in StackOverflow, conversations with no precise answers in Slack. And hours reading the Docs and doing tests.

I have everything working perfectly, except this question.

I want to understand if it is possible for Traefik to handle external and internal traffic (between applications). I would like to make small internal webhooks that are triggered at appropriate times. And also make the micro services model more dynamic without having to use many ports and having to offset ports.

My case is with Rancher. Traefik is configured to receive traffic from an X domain. I would like it to manage the rancher.internal domain. That is resolved by Rancher's internal DNS. But Traefik does not solve ...

No matter what I do, he just does not obey.

An application besides firing Webhooks internally. would be the possibility of interconnecting two distinct APIs created in GraphQL. Merging them into one. This can be done perfectly in Rancher, but the problem is that it requires a lot of attention and a rain of "PORST" if you happen to have many APIs of the type isolated.

With Traefik managing this traffic I do not have to worry about anything if I need to escalate the services.

Anyway, that's it. Cheers.

**Comment by traefiker** [comment]
Every time someone does not respect the issue's template, a little bunny dies.

<details>

![southpark - estrella kill rabbit](https://user-images.githubusercontent.com/5674651/27143914-3cea7896-5130-11e7-81f8-02d8ac2da7a7.gif)
![southpark - estrella kill rabbit2](https://user-images.githubusercontent.com/5674651/27143924-49104c72-5130-11e7-82ae-ccedbd5dfa1c.gif)

</details>
<br>

Please edit your issue description to respect the [issue template](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE.md) as much as possible.

**Comment by MichelDiz** [comment]
Done my friend @traefiker

**Comment by Juliens** [comment]
WDYT @containous/rancher

**Comment by SantoDE** [comment]
Hey @MichelDiz , 

I would like to try help you on that one. Can you give me a little more information in terms of what you're trying to do? e.g. the curl you mentioned above - where do you do that? On the host machine or in one of the containers?

**Comment by MichelDiz** [comment]
The CURL is on the container.

I have an environment with multiple service stacks and etc. I made a stack with some tools. Like cURL, WebHook Tool, CD-CI and Traefik itself in this same stack of tools.

The services I want to achieve are in other stacks, but in the same environment. I can reach via cURL any of them normally.

I need traefik in this case as it seems to me to be the best and easiest solution to scale the services I use. I am using a database (Dgraph) for example and it uses several distinct ports. It has its own way of scaling, but I'm wanting to use multiple instances of the same service in addition to other things. And only the traefik could save me.

When I have a service running on Stack I can fire at it from anywhere inside the Rancher. But in this case I can only fire for containers with defined ports. Port 80 is Rancher's exclusive through traefik. Who listens at 80 and 443.


Example of Rancher domain config.
169.254.169.250
dbzero1.rancher.internal
zero.dbzero1.rancher.internal
rancher.internal

Example the idea behind that:
![image](https://user-images.githubusercontent.com/6570955/36378276-fbafe5da-1558-11e8-80af-a51520145114.png)

**Comment by MichelDiz** [comment]
@nmengin "nmengin added the contributor/need-more-information  " which information need?

**Comment by nmengin** [comment]
Hello @MichelDiz,

We discussed with @containous/rancher about your issue and it appears that we cannot reproduce the use case.
That's why I added the label.

Can you come on the [Traefik Slack](https://traefik.herokuapp.com) to discuss about your need with the team?

Thanks in advance.

**Comment by MichelDiz** [comment]
@nmengin I already tried to talk about that usage over there. The problem is that from time to time I need to solve other problems and when I go back to Slack the conversation is lost. Then I would have to start a new conversation with the same theme and explain it again.

But the concept is simple. I would need my services to talk with each other internally. Even a Traefik contributor in Slack said that it was possible and was left to give me an example. But I could not see if he answered, because I came back weeks later to look. And Slack blocked me.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Slack workspace](https://traefik.herokuapp.com/) for more [community #support](https://traefik.slack.com/messages/C0CDT22PJ/).
