### ISSUE TITLE
Traefik uses HTTP2, but its clients don't support it.

### ISSUE THREAD

**Issue by opavlov24** [containous/traefik#2873]
### Do you want to request a *feature* or report a *bug*?

bug / question

### What did you do?

I have the next chain of reverse proxies.

Traefik (HTTP2 )   ------>   Zuul (Netflix) (HTTP 1.1)    --->        A service (HTTP 1.1)

When I try to post a file (multipart/form-data) by curl (that supports HTTP2) I see that curl connects to Traefik using HTTP 2.0, but my clients (Zuul and the service) don't support it. 

`Connection state changed (HTTP/2 confirmed)` 

Also, an interesting thing. I have a feel that Traefik gets the whole file from a client and after that tries to pass it further, because I get 401 (for instance) only after 20 seconds.

### What did you expect to see?

curl and traefik use HTTP1.1

### What did you see instead?

curl and traefik use HTTP2

### Output of `traefik version`: 

1.3.8 (the same thing in 1.5.2)

### Question

Can I force Traefik to use HTTP 1.1?

**Comment by ldez** [comment]
Thanks for opening this issue :smiley:

We need to better understand this issue and the environment in which you are testing.

Could you join us on the [Traefik Slack](https://traefik.herokuapp.com) (channel [#support](https://traefik.slack.com/messages/C0CDT22PJ/)) to discuss?

It should allow us to more quickly understand the issue.

Thanks.

**Comment by opavlov24** [comment]
Ok. I'll try to create an example of the problem.

**Comment by morpheuskafka** [comment]
I'm not sure this is a bug... there would still be a substantial performance benefit from client to proxy using HTTP/2, even if 1.1 is used on the fast intranet/localhost backend link.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Slack workspace](https://traefik.herokuapp.com/) for more [community #support](https://traefik.slack.com/messages/C0CDT22PJ/).
