### ISSUE TITLE
traefik occassionally delivers wrong (default) certificate - remote error: tls: unknown certificate authority

### ISSUE THREAD

**Issue by dac388** [containous/traefik#2874]
### Do you want to request a *feature* or report a *bug*?

BUG

### What did you do?

Open frontend url in browser.

### What did you expect to see?

secure webpage

### What did you see instead?

Sporadically, and rarely, the page shows insecure, traefik delivers traefik default cert

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.5.2
Codename:     cancoillotte
Go version:   go1.9.4
Built:        2018-02-12_10:56:31AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```json
{
 "LifeCycle": null,
 "GraceTimeOut": 0,
 "Debug": true,
 "CheckNewVersion": true,
 "SendAnonymousUsage": false,
 "AccessLogsFile": "",
 "AccessLog": {
  "file": "/var/run/traefik-access.log",
  "format": "common"
 },
 "TraefikLogsFile": "",
 "TraefikLog": {
  "format": "xxxx"
 },
 "LogLevel": "INFO",
 "EntryPoints": {
  "http": {
   "Network": "",
   "Address": "xxxx",
   "TLS": null,
   "Redirect": null,
   "Auth": null,
   "WhitelistSourceRange": null,
   "Compress": false,
   "ProxyProtocol": {
    "Insecure": false,
    "TrustedIPs": []
   },
   "ForwardedHeaders": null
  },
  "https": {
   "Network": "",
   "Address": "xxxx",
   "TLS": {
    "MinVersion": "",
    "CipherSuites": null,
    "Certificates": null,
    "ClientCAFiles": null,
    "ClientCA": {
     "Files": null,
     "Optional": false
    }
   },
   "Redirect": null,
   "Auth": null,
   "WhitelistSourceRange": null,
   "Compress": false,
   "ProxyProtocol": {
    "Insecure": false,
    "TrustedIPs": []
   },
   "ForwardedHeaders": null
  }
 },
 "Cluster": null,
 "Constraints": [],
 "ACME": null,
 "DefaultEntryPoints": [
  "https",
  "http"
 ],
 "ProvidersThrottleDuration": 2000000000,
 "MaxIdleConnsPerHost": 200,
 "IdleTimeout": 0,
 "InsecureSkipVerify": false,
 "RootCAs": null,
 "Retry": null,
 "HealthCheck": {
  "Interval": 30000000000
 },
 "RespondingTimeouts": null,
 "ForwardingTimeouts": null,
 "Web": {
  "Address": ":8080",
  "CertFile": "",
  "KeyFile": "",
  "ReadOnly": false,
  "Statistics": null,
  "Metrics": null,
  "Path": "",
  "Auth": null,
  "Debug": false
 },
 "Docker": {
  "Watch": true,
  "Filename": "",
  "Constraints": null,
  "Trace": false,
  "DebugLogGeneratedTemplate": false,
  "Endpoint": "xxxx",
  "Domain": "xxxx",
  "TLS": null,
  "ExposedByDefault": true,
  "UseBindPortIP": false,
  "SwarmMode": true
 },
 "File": {
  "Watch": true,
  "Filename": "",
  "Constraints": null,
  "Trace": false,
  "DebugLogGeneratedTemplate": false,
  "Directory": "/srv/traefik/configs/"
 },
 "Marathon": null,
 "Consul": null,
 "ConsulCatalog": null,
 "Etcd": null,
 "Zookeeper": null,
 "Boltdb": null,
 "Kubernetes": null,
 "Mesos": null,
 "Eureka": null,
 "ECS": null,
 "Rancher": null,
 "DynamoDB": null,
 "ServiceFabric": null,
 "Rest": null,
 "API": null,
 "Metrics": null,
 "Ping": null,
 "ConfigFile": "/etc/traefik/traefik.toml"
}
```

### If applicable, please paste the log output in debug mode (`--debug` switch)

```
ops-traefik_service.0.xmxdiu4b5bmq@redacted    | time="2018-02-16T14:10:01Z" level=debug msg="http2: server: error reading preface from client 10.17.59.203:56658: remote error: tls: unknown certificate authority"
```

When a user gets insecure page and then refreshes the page, normal access logs are produced and the page loads securely.

**Comment by dac388** [comment]
I'm happy to provide any additional information required.  We still have this exact problem with every service we've deployed with TLS.

**Comment by salzig** [comment]
run into the similar problem while using a "catch-all" host.

**Comment by dac388** [comment]
?Do you mean a wildcard certificate?

**Comment by salzig** [comment]
no, when using a frontend with a wildcard rule. Like `HostRegexp:{catchall:.*}`

**Comment by nmengin** [comment]
Hello @dac388. 

Many thanks for your interest in the project.

Can you give us more information about your configuration ?

- Are you using wildcard certificates?
- Are you using SANs?
- Can you provide us your Træfik configuration file content?
- Can you provide us all your logs?

@salzig, can you provide this kind of information too?

Thanks in advance.

**Comment by dac388** [comment]
-Are you using wildcard certificates?
+No
Are you using SANs?
+Our preferred configuration is to have a cert with myurl and test.myurl as a SAN.  But, I have tested with certs that use only myurl, and test.myurl and no SAN.
Can you provide us your Træfik configuration file content?
+
debug = true
logLevel = "INFO"
defaultEntryPoints = ["https","http"]
#sendAnonymousUsage = true  maybe add to test someday when parameterized

[traefikLog]

# Enable accessLog to stdout
[accessLog]
# Use accessLog file for debug only
filePath = "/var/run/traefik-access.log"

# NOTE: Use proxyProtocol only in conjunction with nginx,
# configure nginx using: "proxy_protocol on;" in "server" block.
# This allows traefik to get the actual incoming client ips 
# instead of the ip address of the server where nginx is running.
# The trustedIPs in this case is the address of the nginx server.
# The proxyProtocol config should be fine to deploy to production,
# even though it will not actually be needed there.
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.proxyProtocol]
      trustedIPs = ["132.236.118.146"]
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
    [entryPoints.https.proxyProtocol]
      trustedIPs = ["132.236.118.146"]

[web]
address = ":8080"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "docker.localhost"
watch = true
swarmmode = true

#[docker.tls]
insecureskipverify = true

[file]
watch = true
directory = "/srv/traefik/configs/"

Can you provide us all your logs?
+That'd be quite a bit - how would you prefer that I do that?  We are using sematext logsene - I could provide you temporary access there.  The only message I've found about the failure was pasted in the original post.  If we refresh the page, it works fine and we see proper access logs.  Very hard to reproduce the error, I have to slack our whole development group and ask them to test, occassionally someone will get the traefik default cert.

**Comment by nmengin** [comment]
Hello @dac388.
Many thanks for these information.

After analyzing the part of code which is used to serve the certificates, this kind of behavior can happen when Træfik does not find any provided certificate to check the request domain.
Maybe there is a problem in the communication between your LoadBalancer and Træfik.

How many instances of Træfik are you using? Indeed, if you are using many instances of Træfik, many one of them cannot access to the certificates.

In the way to have more information, I just created a Pull Request to add a `DEBUG` log when no certificate can be found (#2938).
This fix will be available in the next minor version (1.5.3) which will be released soon.

When this version version will be available, can you use it and turn you `logLevel` to `DEBUG`?
Thus we'll have more information in the way to understand the problem and, I hope, solve it.

WDYT?

**Comment by dac388** [comment]
-Maybe there is a problem in the communication between your LoadBalancer and Træfik.
+we are using nginx upstream directive as a tcp passthrough load balancer for test (rudimentary), and the University's hardware redundant load balancer for production (robust).  We have the same issue in both.
-How many instances of Træfik are you using? Indeed, if you are using many instances of Træfik, many one of them cannot access to the certificates.
+Traefik is deployed to test and production as a global service in Docker Datacenter.  This is required in test due to the rudimentary load balancer.  I don't think there's a way one traefik container could not access the certificates, but I can test for this.  Every host has the netapp NFS share mounted.  Also, I think stickiness would produce the error more than once...ie if I got the traefik default cert, refreshing the page would produce repeat behavior?
-This fix will be available in the next minor version (1.5.3) which will be released soon.
+Happy to try this version in test and turn on debug as soon as it is released.  Thanks

**Comment by nmengin** [comment]
@dac388 If traefik is used in cluster mode, configuration has to be set in a KV store. That allows a better management of the concurrent access.
You can copy your configuration from the TOML file thanks to the `storeconfig` command.

Moreover, you can add `tls` configuration directly in the kv store.

Finally, I suggest you, if it's possible, to provide the TLS file content to Traefik instead of the file names.

I hope the next version will help us to have more details about your issue.

**Comment by dac388** [comment]
> You can copy your configuration from the TOML file thanks to the storeconfig command.

Could you point me to that documentation?

>Moreover, you can add tls configuration directly in the kv store.  

I was under the impression only file backend and Letsencrypt could be used for TLS.  Which KV store is best supported?  Do I need to run this as a separate service?

>Finally, I suggest you, if it's possible, to provide the TLS file content to Traefik instead of the file names.

Do you mean the cert and key themselves?  Is there an example in documentation?

Thanks!

**Comment by nmengin** [comment]
@dac388 

For all the information you need about KV store, you can refer to this [User Guide](https://docs.traefik.io/user-guide/kv-config/).

> Do you mean the cert and key themselves? Is there an example in documentation?

Yes, it's possible to add directly the file content.
An example is given [here](https://docs.traefik.io/user-guide/kv-config/#upload-the-configuration-in-the-key-value-store). Even if it's about the certificates attached (statically) to the EntryPoint, dynamic certificates work in the same way.

Do not hesitate to come to the [Traefik community Slack](https://traefik.herokuapp.com) for more help/information.

**Comment by dac388** [comment]
With v1.5.3-alpine, I now see:

level=debug msg="http2: server: error reading preface from client (my IP):53669: timeout waiting for client preface

Then a refresh shows normal traffick, eg

time="2018-02-28T14:13:43Z" level=debug msg="source-IP myIP matched whitelist &{[] [%!s(*net.IPNet=&{[mysubnet] [255 255 254 0]}) %!s(*net.IPNet=&{[10 17 59 0] [255 255 255 0]}) %!s(*net.IPNet=&{[10 17 44 0] [255 255 255 0]})] %!s(bool=false)} - passing" 

time="2018-02-28T14:13:47Z" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" Request="{"Method":"GET","URL":{"Scheme":"","Opaque":"","User":null,"Host":"","Path":"/","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"Proto":"HTTP/2.0","ProtoMajor":2,"ProtoMinor":0,"Header":{"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8"],"Accept-Encoding":["gzip, deflate, br"],"Accept-Language":["en-US,en;q=0.9"],"Upgrade-Insecure-Requests":["1"],"User-Agent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36"]},"ContentLength":0,"TransferEncoding":null,"Host":"test.speciesadmin.ornith.cornell.edu","Form":null,"PostForm":null,"MultipartForm":null,"Trailer":null,"RemoteAddr":"myIP:53981","RequestURI":"/","TLS":null}"

**Comment by nmengin** [comment]
@dac388 

Many thanks for your feedback.
I guess the problem appears before the dynamic certificates checking.

That's why Træfik serves the default one.

I have to investigate more and I'll give you a feedback ASAP.

**Comment by dac388** [comment]
Excellent thanks.  We'll be ecstatic if there's a fix.
