### ISSUE TITLE
Instana tracing backend

### ISSUE THREAD

**Issue by Gabology** [containous/traefik#2876]
Since you have implemented the OpenTracing API now, I wanted to ask if you would be open to accepting a PR adding support for the [Instana golang sensor](https://github.com/instana/golang-sensor) as a tracing backend.

**Comment by notsureifkevin** [comment]
https://github.com/notsureifkevin/traefik/tree/2876-add-instana-tracer

this is a WIP but shows promise

![image](https://user-images.githubusercontent.com/3759919/52095519-cdcc2980-2588-11e9-960d-c9102a87d32d.png)

**Comment by notsureifkevin** [comment]
#4453
