### ISSUE TITLE
Feature request: Expose meaningful websocket/SSE metrics

### ISSUE THREAD

**Issue by puco** [containous/traefik#2905]
### Scenario

I have a site with a websocket endpoint and an HTML page that connects to this WS endpoint. When user hits the site he makes 2 HTTP requests (to `/` and WS endpoint) and stays on the page for 1m

### What did you expect to see?

When my site works correctly I expect that the `traefik_request_duration_seconds_sum` metric shows that. 
I would expect to see duration for the initial get request and duration of the WS initiation summed up. And possibly have the websocket total duration as separate metric

### What did you see instead?

I see the value at 60.2s and count = 2 (total sum of durations is 1 minute and there are 2 requests). Which shows my site in a very bad light.

### Output of `traefik version`: (_What version of Traefik are you using?_)

`traefik:1.5-alpine`

**Comment by marco-jantke** [comment]
In master the metric already has a protocol label (sse, http, websocket). It will be available with the next release 1.6. I think that should solve your problem. Let me know if this is not the case :)

**Comment by puco** [comment]
That should solve it perfectly 👍  In that case you can close the issue

**Comment by ldez** [comment]
Closed by #2567
