### ISSUE TITLE
Documentation link broken for "https://docs.traefik.io/toml/#docker-backend"

### ISSUE THREAD

**Issue by LaurentTardif** [containous/traefik#2917]
### What did you do?

I was doing the tutorial on  katacoda. When i was on the page : https://docs.traefik.io/toml/#docker-backend
there's a link to have additional information pointing to : https://docs.traefik.io/toml/#docker-backend
then i got a beautiful : "404 - Not found".
In case it's browser specific, i'm using firefox.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
(paste your output here)
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# (paste your configuration here)
```

### If applicable, please paste the log output in debug mode (`--debug` switch)

```
(paste your output here)
```

**Comment by LaurentTardif** [comment]
The links on documentation is also broken on stackoverflow : https://stackoverflow.com/questions/44430604/redirecting-a-path-to-the-same-container-but-different-port-with-traefik

so, you may have introduce a breaking change in the documentation recently :)

**Comment by ldez** [comment]
We made some change in documentation, you find the old documentation https://docs.traefik.io/v1.3/toml/#docker-backend.

**Comment by LaurentTardif** [comment]
thanks for the link. For the "users" navigating stackoverflow, or using katacoda, it may be good if you add some automated redirect to the doc.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Slack workspace](https://traefik.herokuapp.com/) for more [community #support](https://traefik.slack.com/messages/C0CDT22PJ/).
