### ISSUE TITLE
Alert on invalid configuration reload

### ISSUE THREAD

**Issue by samber** [containous/traefik#292]
Hi guys,

One of my pain point with Traefik is there is no alerting method for failed configuration reload.

I mean, my Traefik instance can watch consul updates, but, i have no way to detect that the new configuration is invalid.

The load balancer being the entrypoint of the whole stack, it is a huge SPOF if a consul service block the deployment of any other service because of an invalid config.

It’s probably not the best method, but what about making a Twilio or SMTP request ? Starting with a flag in Traefik metrics could also be great.

**Comment by emilevauge** [comment]
What do you mean by invalid config ?

**Comment by samber** [comment]
For example, using the consul provider, if you accidentally set a tag to "traefik.backend.weight=foobar" in the consul catalog, traefik will throw an error "Failed to create config" [...] "Skipping empty configuration".

**Comment by samber** [comment]
We could add this to traefik.toml:
```onConfigError = "POST http://whatever.io/path"```

Sending a post request with message in body, to whatever.io/path when configuration fail to update. 
Then, it can be parsed and redirected by zapier, to Twilio, SendGrid...

**Comment by emilevauge** [comment]
@samber: I think this is a bit too specific for traefik.
This should rather be delegated to a monitoring app like [prometheus](https://prometheus.io/).
For example, you could send an email at each `ERROR` log.
But the best solution would be to get this info in `/health` traefik API in the futur.
WDYT?

**Comment by samber** [comment]
Yes, prometheus looks good, that's why we should set a counter in Traefik health api to allow Prometheus to detect errors.
Unfortunately, for people not using prometheus, there is still no solution.

**Comment by emilevauge** [comment]
Closing this one for now, as I think that monitoring tools should be used in that case.

**Comment by samber** [comment]
How do you monitor that ?

**Comment by emilevauge** [comment]
You can monitor `ERROR` logs.

**Comment by nsouleman** [comment]
Hi,
@emilevauge your idea to get this information from /health sounds good as it would be easy to any monitoring software be aware of reload issues.
Do you guys plan to add this feature soon ?
Monitoring error log is not the right solution imho... 
Thanks.
