### ISSUE TITLE
hello I would like to collaborate with your project by serving as a translator to Spanish. could translate all your text documents

### ISSUE THREAD

**Issue by UlisesTJ** [containous/traefik#2924]
### Output of `traefik version`: (_What version of Traefik are you using?_)

```
(paste your output here)
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# (paste your configuration here)
```

### If applicable, please paste the log output in debug mode (`--debug` switch)

```
(paste your output here)
```

**Comment by ldez** [comment]
Thanks for your interest in Traefik !

Every question asked in issues means less features 😉.

The issue tracker is for reporting bugs and feature requests only.

Please to go the [Traefik community Slack](https://traefik.herokuapp.com) in the channel [#dev](https://traefik.slack.com/messages/C2S653DAM/)
