### ISSUE TITLE
Better reference documentation would be valuable

### ISSUE THREAD

**Issue by glennschmidt** [containous/traefik#2931]
### Do you want to request a *feature* or report a *bug*?

A feature I guess. I consider good documentation to be a software feature :)

### What did you do?

I looked for a comprehensive listing of configuration parameters and their meaning.

### What did you expect to see?

For each supported config parameter
1. What does it do?
2. Where can it appear? eg. static configuration, dynamic configuration
2. What are the valid set of values and how are they interpreted?

Maybe something like these directive guides:
http://nginx.org/en/docs/dirindex.html
https://httpd.apache.org/docs/2.4/mod/quickreference.html
I know Traefik's configuration structure is more hierarchical so may need a slightly different approach, but the important thing is that it's centralised, consistent and comprehensive.

### What did you see instead?

A mixture of various examples config files, conceptual overviews, how-tos and discussions of specific features.

Don't get me wrong, a lot of this is good stuff, but it's more like a collection of support articles than a reference guide.

For the record, the things I found most unclear as a new user were:
- Inconsistent terminology, using the word 'backend' to mean both an upstream HTTP server, and a source of configuration data. I would strongly recommend standardising on the term 'configuration *provider*' instead of 'configuration *backend*', to avoid this confusion.
- A lack of clarity about what configuration has to be set at startup, and what can be dynamically applied at runtime
- How multiple config providers interact with one another. eg. Can you define a frontend in one provider, and override some of its properties in another? Or does each frontend have to live entirely within one provider? Also do the frontends need to be given unique names, or is each provider a different namespace?
- When relative filenames are referenced in the config, how are they resolved? Relative to the toml file where they appear, relative to `/etc/traefik`, relative to the CWD when traefik is executed, or something else?

**Comment by endersonmaia** [comment]
I'd add to the list a "Glossary" section.

Eg.: I couldn't find anywhere the definition of "Provider", I see that there's a list of providers like Docker, Consul Catalog but I can't find nothing about what is a provider, or what's a provides does in [Overview](https://docs.traefik.io/#overview) or in [Concepts](https://docs.traefik.io/basics/#concepts).

**Comment by dtomcej** [comment]
Hello @glennschmidt 

With the release of Traefik v2, we completely rewrote our documentation site.

For this reason, I will be closing this issue.
