### ISSUE TITLE
Not working with intermediate certs from InCommon

### ISSUE THREAD

**Issue by dimm0** [containous/traefik#2957]
### Do you want to request a *feature* or report a *bug*?

bug

### What did you do?
Deployed traefik as kubernetes ingress with SSL certificate from InCommon. The certificate if multi-domain wildcart (domain.com, *.domain.com)

### What did you expect to see?
Work properly with chain of certificates.

### What did you see instead?
It works fine if I only use the certificate itself, but fails if I use certificate with intermediate certs, in any order.

I'm getting:
```time="2018-03-02T00:44:26Z" level=error msg="Unable to add a certificate to the entryPoint "https" : unable to generate TLS certificate : tls: private key does not match public key"```

### Output of `traefik version`: (_What version of Traefik are you using?_)

1.5.3

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

kubeadm kubernetes 1.9.3

**Comment by dimm0** [comment]
I'm looking at traefik code at https://github.com/containous/traefik/blob/a2db3e0499ce8319f3346d0f123d9d62a73d997c/tls/certificate.go#L144

Seems like this https://golang.org/pkg/crypto/tls/#LoadX509KeyPair function supports intermediate certs, while the one used in traefik https://golang.org/pkg/crypto/tls/#X509KeyPair does not

**Comment by ldez** [comment]
I think it's just a missing comment because the difference between `LoadX509KeyPair` and `X509KeyPair` is only `ioutil.ReadFile`

https://github.com/golang/go/blob/1023b016d51ee0e6b7245482b9d8715170d785ee/src/crypto/tls/tls.go#L173-L188

**Comment by dimm0** [comment]
Ok, agree... I guess I'll submit the bug to go directly then, after making a minimal test example.

**Comment by dimm0** [comment]
I figured it. Needed to manually combine the provided certs to have the order right.

**Comment by themaxx32000** [comment]
@dimm0 what's the correct order? I'm experiencing a similar issue...
