### ISSUE TITLE
Authentication for web dashboard

### ISSUE THREAD

**Issue by zs-zs** [containous/traefik#296]
As a system administrator
I want to restrict the access for my Traefik web dashboard
So that I can be sure that nobody sees my traffic & health info :)

(I hope its not a duplicate of #77 ...)

**Comment by sandstrom** [comment]
Simple solution is to bind to localhost (loopback) and then ssh + port-forward, say, 8080. That way only you will have access and you'll use ssh as the security layer.

**Comment by nizq** [comment]
+1

**Comment by emilevauge** [comment]
Fixed by #677
