### ISSUE TITLE
Feature Request: Add rate limiting of speed per frontend

### ISSUE THREAD

**Issue by michacassola** [containous/traefik#2964]
Please add the feature of rate limiting the speed/bandwidth for frontends after a certain time, like nginx can do it as described here: https://www.scalescale.com/tips/nginx/how-to-limit-nginx-download-speed/

Feature
```
limit_rate_after 1m;
limit_rate 150k;
```
Something like that would be perfect.

Use case:
One of ten web apps on the same server with 1Gbit Uplink will not be able to hog the bandwidth.
After 1 second the rate could go down to 500Mbit and then to 100Mbit after 15 seconds.

Thanks!

**Comment by traefiker** [comment]
Every time someone does not respect the issue's template, a little bunny dies.

<details>

![southpark - estrella kill rabbit](https://user-images.githubusercontent.com/5674651/27143914-3cea7896-5130-11e7-81f8-02d8ac2da7a7.gif)
![southpark - estrella kill rabbit2](https://user-images.githubusercontent.com/5674651/27143924-49104c72-5130-11e7-82ae-ccedbd5dfa1c.gif)

</details>
<br>

Please edit your issue description to respect the issue template as much as possible:

- [Basic template](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE.md)
- [Feature template](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/features.md)
- [Bug template](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/bugs.md)

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Slack workspace](https://traefik.herokuapp.com/) for more [community #support](https://traefik.slack.com/messages/C0CDT22PJ/).

**Comment by nuriel77** [comment]
I am also curious about this feature. It is not mentioned anywhere whether Traefik is able to limit bandwidth?
