### ISSUE TITLE
Suggestion to use github.com/kevinburke/go-bindata

### ISSUE THREAD

**Issue by ilovezfs** [containous/traefik#2965]
I've just added a [formula for go-bindata in Homebrew](https://github.com/Homebrew/homebrew-core/pull/24801) based on [Kevin Burke's fork](https://github.com/kevinburke/go-bindata)

Instead of https://github.com/containous/go-bindata, would you consider using https://github.com/kevinburke/go-bindata ? He's making release tags https://github.com/kevinburke/go-bindata/releases and others are having good luck with compatibility. See https://github.com/Dr-Terrible/go-overlay/issues/76#issuecomment-360482724

>That fork is API compatible with the original package and the author doesn't wish to diverge from it, or add new incompatible features

**Comment by ldez** [comment]
We don't plan to change for now.

**Comment by ilovezfs** [comment]
OK. Just a heads up then that I will be using it to build traefik in Homebrew.

**Comment by ldez** [comment]
For memory, the 2 most up to date fork are:
- https://github.com/shuLhan/go-bindata (47 stars)
- https://github.com/kevinburke/go-bindata (17 stars)

**Comment by ilovezfs** [comment]
Nice. Do you know if shuLhan has maintained API compat with the original? That seems to be the main thing in terms of trying to get everyone using the dead repo onto the same upstream project again.

**Comment by ldez** [comment]
Yes it's fully compatible and with more configuration options.

But it's not the place to discuss, please come to the [Traefik community Slack](https://traefik.herokuapp.com) channel #dev, if you want to discuss more.

PS: next time, please try to respect the template as much as possible or come ask your question on Slack.

**Comment by ilovezfs** [comment]
OK, thanks.
