### ISSUE TITLE
Etcd ACME store with alternative back-ends.

### ISSUE THREAD

**Issue by bweston92** [containous/traefik#2967]
### Do you want to request a *feature* or report a *bug*?

*Feature*

### What did you expect to see?

Ability to use Etcd to store ACME configuration but still use Docker Swarm for SD.

### What did you see instead?

No options to do this.

### Output of `traefik version`: (_What version of Traefik are you using?_)

1.5

**Comment by fmauNeko** [comment]
That already works, just configure both backends according to the documentation

**Comment by traefiker** [comment]
I'll close this issue, because I think the question is answered, but feel free to continue the conversation.

**Comment by traefiker** [comment]
I'll close this issue, because I think the question is answered, but feel free to continue the conversation.

**Comment by bweston92** [comment]
Given the following it does not work, is there some prerequisites I am missing?

Config flags:
```
traefik:1.5-alpine --entryPoints='Name:https Address::443 TLS' --defaultEntryPoints=http,https --etcd.endpoint=merh:2379 --acme.entryPoint=https --acme.email=devs@merh.org.uk --acme.storage=/traefik/acme/account --acme.httpChallenge.entryPoint=http --web.metrics.prometheus.buckets="0.1,0.3,1.2,5.0" --docker.swarmmode --docker.domain=merh --web;
```

Errors:
```
traefik-etcd-test.1.xk33olkzlb6w@BREEZE    | time="2018-03-05T12:48:10Z" level=error msg="Error creating TLS config: Key not found in store" 
traefik-etcd-test.1.xk33olkzlb6w@BREEZE    | time="2018-03-05T12:48:10Z" level=fatal msg="Error preparing server: Key not found in store" 
```

**Comment by fmauNeko** [comment]
Is there anything in your etcd at /traefik/acme/account ?
You should have two values, lock and object.
If they aren't present at all, Traefik will fail to start, just create them with empty values and you should be fine !

**Comment by bweston92** [comment]
Hmm provisioned it with `traefik storeconfig` worked fine, turned on Traefik and got a panic.

```
traefik.1.s7sibcu161fy@BREEZE    | panic: runtime error: invalid memory address or nil pointer dereference
traefik.1.s7sibcu161fy@BREEZE    | [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x9e9f07]
traefik.1.s7sibcu161fy@BREEZE    | 
traefik.1.s7sibcu161fy@BREEZE    | goroutine 227 [running]:
traefik.1.s7sibcu161fy@BREEZE    | github.com/containous/traefik/vendor/github.com/xenolf/lego/acme.(*Client).getChallenges.func1(0x0, 0xc420adc720, 0xc420adc6c0, 0xc4206866e0, 0x9)
traefik.1.s7sibcu161fy@BREEZE    | 	/go/src/github.com/containous/traefik/vendor/github.com/xenolf/lego/acme/client.go:550 +0xd7
traefik.1.s7sibcu161fy@BREEZE    | created by github.com/containous/traefik/vendor/github.com/xenolf/lego/acme.(*Client).getChallenges
traefik.1.s7sibcu161fy@BREEZE    | 	/go/src/github.com/containous/traefik/vendor/github.com/xenolf/lego/acme/client.go:547 +0x133
```
