### ISSUE TITLE
Logjam

### ISSUE THREAD

**Issue by navossoc** [containous/traefik#2974]
Is Traefik vulnerable to Logjam?

I did a quick test with this tool and it looks like it is affected.
https://tools.keycdn.com/logjam

I tried to change some ciphers, but it did not work.
I also tried to look in the commit logs and found nothing about logjam.

**Comment by dtomcej** [comment]
Traefik does not support export cipher suites, nor does it use low-bit key negotiation, and therefore is not susceptible to LogJam.


If you would like to discuss an implementation issue, please reach out to our slack team:

https://traefik.slack.com
