### ISSUE TITLE
Sort routes' Paths by length to avoid overlap

### ISSUE THREAD

**Issue by emilevauge** [containous/traefik#298]

**Comment by mathieu-pousse** [comment]
# Context

If we have 2 containers, one mapping `/api` to the backend and the other one mapping `/` to an http server, traefik seems to fail sometime to properly proxy the request to the appropriated container.

# Proposal

It seems that context overlapping `/` contains `/api` is not properly handled. 
Ordering and setting the priority of the mapping automatically would be really nice this is kind of a pain to find the more precise match, it becomes a nightmare when you add host matching, path, path prefix and the magic of regexps.

Maybe as a first step it would be nice to somehow be able to add a priority label to the containers to tell traefik how to guess the good mapping in case of multiple match.

Let's say highest is defined as the most precise

container matching `/` is priority 0
container matching `/api` is priority 10

a request for `/api/resource` will match both but as the routes are properly sorted it will match `/api` first and works as expected.

**Comment by damoon** [comment]
Could it be fine just to order the mappings descending by length? It would avoid the (in my experience error prone) manual configuration via priorities.

**Comment by damoon** [comment]
Sorry was not reading the title...

**Comment by pferrot** [comment]
The proposal makes sense!

**Comment by KnownSubset** [comment]
Is problem described above solvable by adding additional [Header rules](https://docs.traefik.io/basics/#frontends) to the frontend?

**Comment by emilevauge** [comment]
See PR #433 :)
