### ISSUE TITLE
Ping not enabled, healthcheck cmd fails

### ISSUE THREAD

**Issue by brodkin** [containous/traefik#2995]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Attempted to check health of the Traefik instance.

  1. Started Docker container using `library/traefik` and `--ping` flag.
  2. Verified container serving content from other containers.
  3. Sent exec to container with command `/traefik healthcheck`

### What did you expect to see?

Return code of `0` confirming healthy instance.

### What did you see instead?

Return code `1` with error message:
```
Error calling healthcheck: please enable `ping` to use health check
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.5.3
Codename:     cancoillotte
Go version:   go1.9.4
Built:        2018-02-27_02:47:04PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```json
{
 "LifeCycle": {
  "RequestAcceptGraceTimeout": "0s",
  "GraceTimeOut": "0s"
 },
 "GraceTimeOut": "0s",
 "Debug": false,
 "CheckNewVersion": true,
 "SendAnonymousUsage": false,
 "AccessLogsFile": "",
 "AccessLog": null,
 "TraefikLogsFile": "",
 "TraefikLog": null,
 "LogLevel": "ERROR",
 "EntryPoints": {},
 "Cluster": null,
 "Constraints": [],
 "ACME": null,
 "DefaultEntryPoints": [
  "http"
 ],
 "ProvidersThrottleDuration": "2s",
 "MaxIdleConnsPerHost": 200,
 "IdleTimeout": "0s",
 "InsecureSkipVerify": false,
 "RootCAs": null,
 "Retry": null,
 "HealthCheck": {
  "Interval": "30s"
 },
 "RespondingTimeouts": null,
 "ForwardingTimeouts": null,
 "Web": null,
 "Docker": null,
 "File": null,
 "Marathon": null,
 "Consul": null,
 "ConsulCatalog": null,
 "Etcd": null,
 "Zookeeper": null,
 "Boltdb": null,
 "Kubernetes": null,
 "Mesos": null,
 "Eureka": null,
 "ECS": null,
 "Rancher": null,
 "DynamoDB": null,
 "ServiceFabric": null,
 "Rest": null,
 "API": null,
 "Metrics": null,
 "Ping": null,
 "ConfigFile": ""
}
```

**Comment by ldez** [comment]
Thanks for your interest in Traefik 😃 

The CLI configuration is not shared between commands, you need to run the health check command like that:

```shell
docker run traefik:1.5 healthcheck --ping
```

or to define `[ping]` in `traefik.toml` https://docs.traefik.io/configuration/ping/

**Comment by brodkin** [comment]
@ldez May I suggest an update to the docs? To get this working on our installation, I had to set `--web` on the run command and then exec `/traefik healthcheck --ping` on the Docker healthcheck. It should be noted that executing `/traefik --ping healthcheck` attempts to start a new instance of Traefik and fails.
