### ISSUE TITLE
More advanced middlewares

### ISSUE THREAD

**Issue by lucmichalski** [containous/traefik#30]
Hi guys,

Hope you are all well !

Here are the 
- Transform Request/Response
- Managing templates for frontends body transformation
- Concurrent sub-requests to nest json responses in a middleware

Cheers,

**Comment by seeder** [comment]
So i just tried putting traefik in front of Jenkins ... no joy, it needs some response rewriting ( in Location header for example )
Great project, makes stuff cleaner than any apache/haproxy/nginx frankensteins monsters, but needs a bit more feature oomph exposed

**Comment by EmileVauge** [comment]
@seeder could you give me a concrete exemple? I already have some implementation ideas, but I'm still not completely satisfied by those ones ^^

**Comment by seeder** [comment]
@EmileVauge https://wiki.jenkins-ci.org/display/JENKINS/Jenkins+says+my+reverse+proxy+setup+is+broken

**Comment by lucmichalski** [comment]
For my part, it would be great to have a rewrite module like on Vulcand (https://vulcand.io/proxy.html#rewrites-and-redirects).

My use case is to embbed Traefik inside a docker container in order to map several services:

Current use (with a file generated during the build of the container):
/service_1 going to loadbalanced ports or different front-ends
/service_2 going to one specific front-end

Wished use of Traefik:
/api/v1/service1/function1
/api/v1/service1/function2
/api/v1/service2/

**Comment by mathieu-pousse** [comment]
+1 would be very nice !

**Comment by ekozan** [comment]
@emilevauge Yop, may be can we discuss about many middlewares like auth, logs, etc ... for example I want to use the next feature of Coreos/Dex ( groups ) for make an oauth2 login on some admin applications on my k8s cluster. the real question is "How we can pass the options to the middleware"

**Comment by sandstrom** [comment]
Transforming request/response would be great! Ability to adjust headers (add/remove/edit) would probably go a long way.

**Comment by sybrandy** [comment]
Hello,

Not sure if this is the right place to mention this, but I recently had to fork/modify Traefik to support SSL cert forwarding to our backends, setting client certs for the backends (e.g. the backend HTTP client uses a client cert), and authorization capabilities so the users can be authenticated at the proxy.  The last part was done to support a custom authorization system that's in-house, but I did create a Basic Auth version using the same interface.  We're still testing it, but so far it appears to be working well.  As soon as we've had things running for a while and things look good, I plan on creating some pull requests.  As of right now I don't have an ETA as we want to be sure everything is working well before we release the changes.

**Comment by fentas** [comment]
Hey is there any solution for this nowadays?
I want to replace haproxy with traefik in our docker swarm infrastructure but in order to do that, I have to replace a Lua script, rerouting incoming traffic to certain docker service depending on user auth (request against a rest API) and header/URL information.

also asked on StackOverflow:
https://stackoverflow.com/questions/46980439/user-authentication-and-dynamic-routing-in-traefik

**Comment by emilevauge** [comment]
Closing this one in favor of #1336
