### ISSUE TITLE
Feature Request: Support Oxy ConnLimiter in Traefik

### ISSUE THREAD

**Issue by kevioke** [containous/traefik#300]
**Problem**
By stress testing Traefik, we've noticed that it is possible for Traefik to overwhelm downstream services with too many requests. This causes services hosted in Marathon to constantly thrash via stopping and starting again because they cannot handle the load from Traefik.

**Proposal**
Many loadbalancers support a notion of "maximum connections" to a service in order to safeguard services behind the loadbalancer from being overwhelmed by heavy traffic. I see that Traefik is already using the oxy library and leveraging features such as roundrobin and circuitbreakers. It seems very feasible to add another feature for connection limit which the oxy library has support for https://github.com/vulcand/oxy/blob/master/connlimit/connlimit.go.

We would simply need to add another configuration for Traefik for maxConnections and presumably wire it up where the oxy decorators are being wrapped and constructed here https://github.com/containous/traefik/blob/6308ce2740b7c92e3c50b70eb82dd94ea89425a4/server.go?ts=2#L330

**Comment by emilevauge** [comment]
Great idea!

**Comment by kevioke** [comment]
Sweet! I'm working on the code change and will hopefully have it up soon.
