### ISSUE TITLE
Don't use Consul tags for backendName in consulCatalog backend

### ISSUE THREAD

**Issue by 007reader** [containous/traefik#3002]
### Do you want to request a *feature* or report a *bug*?
feature

### What did you do?
It's specific to consulCatalog backend. If a service registered in Consul has some Traefik tags, those tags are used in backendName (https://github.com/containous/traefik/blob/59f7b2ea98517c1b5168e996b3894add3065b36b/provider/consul/consul_catalog.go#L409-L422). It has a couple of problems. One,the backendName can become quite long and difficult to differentiate in a case of many services, e.g. "test--127-0-0-1--9999--traefik-backend-loadbalancer-drr--1" and it will be even longer if more then one tag is defined. Second, If Consul tag is updated or removed at some point, the name will become irrelevant.

I'd like to see more deterministic backendName that will not change if Consul tags are modified.

**Comment by mmatur** [comment]
Hi @007reader ,

Thanks for you interest in Træfik. 

This feature has already been implemented in #2646
