### ISSUE TITLE
Naming consistency in configuration: paramName vs ParamName

### ISSUE THREAD

**Issue by kachkaev** [containous/traefik#3005]
Some parameters [in `traefik.toml`](https://docs.traefik.io/configuration/commons/) such as `graceTimeOut`, `checkNewVersion`, `debug`, etc begin with a lowercase character, while others start with a capital letter (`ProvidersThrottleDuration`, `MaxIdleConnsPerHost`, `RootCAs`, etc). A quick glance through the traefik's repo and the PRs suggests that a decision to make each parameter styled in its particular way is justified by how it is named in the source code. However, this logic is out of reach for an end user and so the params in `traefik.toml` simply look inconsistently named without any clear reason.

I was going to add `InsecureSkipVerify` option [to traefik's official helm chart](https://github.com/kubernetes/charts/tree/master/stable/traefik) and somewhat stumbled, because I could not figure out how to name it. If I kept the first uppercase letter, I'd get inconsistency with all other chart parameters, while if I named the option as `insecureSkipVerify`, the inconsistency would shift, but not disappear. At the moment, there seems to be no good naming solution that would not raise end users' questions and thus their waste of time.

It looks like both `InsecureSkipVerify` and `insecureSkipVerify` work equally well in `traefik.toml`, which means that the existing naming inconsistency can be resolved by just updating the docs and this will not introduce any breaking changes. Given the size of the traefik's community, I find it worth investing a bit of time in making config naming more coherent and thus avoid time-draining questions like _should this parameter start with a cap? and this?_

WDYT of going through the docs and renaming all configuration parameters that begin with a capital letter (e.g. `RootCAs` → `rootCAs`)? What can this break?

**Comment by timoreimann** [comment]
Personally, I'm all in favor of agreeing to a consistent style and applying it throughout our documentation. A little note somewhere mentioning that capitalization does not matter also seems in order.

**Comment by kachkaev** [comment]
@timoreimann would you prefer `lowerCamelCase` or `UpperCamelCase`?

**Comment by timoreimann** [comment]
My favorite bike shed color would be lower camel case. :-)

Let's hear what the others have to say though before making a bigger move on the docs.

**Comment by emilevauge** [comment]
@kachkaev thanks for reporting ! I think `lowerCamelCase` is great.
We would love you help on this :)

**Comment by kachkaev** [comment]
I'll try to produce a PR in a couple of weeks. If you are reading this and want to contribute instead of waiting, feel free! 🤝

**Comment by kachkaev** [comment]
See https://github.com/containous/traefik/pull/3132 as a possible solution to this issue.

**Comment by ldez** [comment]
The lib we use for TOML produce **Upper** Camel Case.

I prefer lower Camel Case but but we must be careful not to limit the possibilities of automation.

For now, use lower Camel Case is not a problem, and I agree with the changes if they are only on the first letter.

**Comment by traefiker** [comment]
Closed by #3132.
