### ISSUE TITLE
Bug: concurrency issue in oxy memmetrics

### ISSUE THREAD

**Issue by kevioke** [containous/traefik#302]
While stress testing Traefik, we've noticed that the Traefik will crash due to the issue noted here https://github.com/vulcand/oxy/issues/34.

The edge case occurs when two threads try to insert a metric counter for the first time at the same time. A simple fix would be to simply use a mutex as @emilevauge has noted in the oxy issue. Considering that containous has forked oxy how should we go about making sure this bug is fixed?

**Comment by emilevauge** [comment]
Hi @kevioke, indeed, we have to correct this bug.
I suggest we make the correction in `containous/oxy`, and them make a pull request on `vulcand/oxy` in order to save time :)

**Comment by kevioke** [comment]
Makes sense. I'll get a PR for this soon.

**Comment by kevioke** [comment]
PR is here https://github.com/containous/oxy/pull/1

**Comment by emilevauge** [comment]
Fixes by #306
