### ISSUE TITLE
Acme Requirements and Questions

### ISSUE THREAD

**Issue by stongo** [containous/traefik#304]
Are there any requirements beyond running Traefik for ACME Let's Encrypt to function?
I've added an A and AAAA DNS record for the ip where Traefik is running.
Here's the configuration I've used:
```
[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
email = "ops@test.com"
storageFile = "/etc/acme/acme.json"
entryPoint = "https"
onDemand = true
[[acme.domains]]
  main = "test.foo.com"
```

This is the error I get in Traefik logs:
```
time="2016-04-13T14:55:54Z" level=error msg="map[test.foo.com:acme: Error 0 - urn:acme:error:connection - Failed to connect to host for DVSNI challenge\nError Detail:\n\tValidation for test.foo.com:443\n\tResolved to:\n\t\t147.75.9999.99\n\tUsed: 147.75.9999.99\n\n]"
time="2016-04-13T14:55:54Z" level=error msg="Error getting ACME certificate for domain [test.foo.com]: Cannot obtain certificates map[test.foo.com:acme: Error 0 - urn:acme:error:connection - Failed to connect to host for DVSNI challenge\nError Detail:\n\tValidation for test.foo.com:443\n\tResolved to:\n\t\t147.75.9999.99\n\tUsed: 147.75.9999.99\n\n]+v"
time="2016-04-13T14:55:54Z" level=info msg="Retrieved ACME certificates"
```

Wondering if I'm missing any steps?

**Comment by emilevauge** [comment]
Hi @stongo, you're missing a point ;)
Let's Encrypt should be able to join traefik on the domain `test.foo.com` and I assume that's not the case here ;)
In 
```
[[acme.domains]]
  main = "VALID_DOMAIN"
```
you should provide a valid domain that points to your traefik instance.

**Comment by stongo** [comment]
I just substituted test.foo.com in this issue. The A/AAAA record does 
point to the ip where traefik is running.
Traefik should answer the acme challenge then?
In the case of setting `main = "real.domain.com"` does there already 
need to be a valid SSL certificate for real.domain.com for example?

**Comment by emilevauge** [comment]
Hum, then I don't know, maybe your are not lucky: https://letsencrypt.status.io/

**Comment by stongo** [comment]
It's working now, so definitely might have just been good luck. Added a quick PR to docs to make it a bit easier to get started with ACME

**Comment by emilevauge** [comment]
Great :) Closing then.
