### ISSUE TITLE
Add support to additional httpheaders in healthchecks

### ISSUE THREAD

**Issue by zetaab** [containous/traefik#3043]
### Do you want to request a *feature* or report a *bug*?

feature

### What did you do?

I am trying to create healthcheck which contains custom httpheaders. If I understand correctly traefik does not support Hostname in backend healthcheck?

### What did you expect to see?

I except that I should have possibility to configure hostname and other additional httpheaders in healthchecks. In my opinion in kubernetes have pretty good custom httpheaders example https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#define-a-liveness-http-request If traefik could have something like similar it would be awesome. Then we could configure hostname(and others custom headers) in healthchecks 

### What did you see instead?

I do not see possibility to configure these headers

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
(paste your output here)
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# (paste your configuration here)
```

### If applicable, please paste the log output in debug mode (`--debug` switch)

```
(paste your output here)
```

**Comment by ldez** [comment]
Thanks for your interest in Traefik 😃 

Could you provide a use-case?

**Comment by zetaab** [comment]
![screen shot 2018-03-19 at 12 16 13](https://user-images.githubusercontent.com/22482503/37589945-62fc8ef6-2b6f-11e8-8a46-32d62924673d.png)

We are thinking to use traefik in front of two different kubernetes cluster ingress routers. With traefik, we can handle only one kubernetes cluster ingress traffic. But we would like to install one traefik to front of two(or more) clusters. Why we would like to do that? Kubernetes clusters are usually cloudprovider or region specific installations. We have currently two different kubernetes installations in different regions and we would like make these highly available. This is kind of kubernetes federation. Kubernetes ingress router needs to have Host header in place, otherwise it does not check the correct endpoint in cluster.
