### ISSUE TITLE
Documentation has broken link

### ISSUE THREAD

**Issue by JensErat** [containous/traefik#3045]
### Do you want to request a *feature* or report a *bug*?

bug: documentation has broken link

### What did you do?

Clicked on the link in the "notes" section of https://docs.traefik.io/configuration/backends/kubernetes/#tls-communication-between-traefik-and-backend-pods

### What did you expect to see?

(Probably) a link to https://docs.traefik.io/configuration/commons/#main-section

### What did you see instead?

404 not found on https://docs.traefik.io/configuration/backends/configuration/commons/#main-section

### Output of `traefik version`: (_What version of Traefik are you using?_)

Fetched documentation page on 2018-03-18.

**Comment by timoreimann** [comment]
sorry @emilevauge, I missed that you had already assigned @geraldcroes to the task.

You get the next docs bug, promised. :)

**Comment by geraldcroes** [comment]
You should feel the opposite of sorry ^^ 
I still have a lot on my plate, so I won't miss the issue :-)

**Comment by timoreimann** [comment]
@JensErat thanks for reporting -- link is now fixed. 😀
