### ISSUE TITLE
support rate limiting for the service fabric provider

### ISSUE THREAD

**Issue by AviMualem** [containous/traefik#3046]
### Do you want to request a *feature* or report a *bug*?
Feature

### What did you do?
Ive tried to configure rate limits for my frontend rule by using the Traefik labels for service fabric.

### What did you expect to see?
i expected to be able to use the following annotations in my servicemanifest.xml configuration.
traefik.frontend.rateLimit.extractorFunc
traefik.frontend.rateLimit.rateSet.burst
traefik.frontend.rateLimit.rateSet.period
traefik.frontend.rateLimit.rateSet.average

although the service fabric documentation  (https://docs.traefik.io/configuration/backends/servicefabric/ ) doesn't have these labels on the supported label list i assumed it will be just like the traefik.backend.healthcheck label which is basically supported but for some reason isnt mentioned in the supported lables.

### What did you see instead?
i couldnt define a rate limit for my frontend rule. my labels were basically ignored.
I noticed that the service fabric template still doesnt support the mentioned annotations,while it looks like the vast majority of the other templates (kubernetes.tmpl,marathon.tmpl etc..) support them.
im basing my opinion on the template file which can be found here:
https://github.com/containous/traefik-extra-service-fabric/blob/master/servicefabric_tmpl.go 

### Output of `traefik version`: (_What version of Traefik are you using?_)
im using traefik 1.5.2

**Comment by ldez** [comment]
Thanks for your interest in Traefik !

Could you move this issue on the Service Fabric repository: https://github.com/containous/traefik-extra-service-fabric

**Comment by AviMualem** [comment]
sure.
