### ISSUE TITLE
Must close all IIS port 80 connections before Traefik will start

### ISSUE THREAD

**Issue by stzoid** [containous/traefik#3053]
**Do you want to request a feature or report a bug?**
Bug

**What did you do?**
Configured and started Traefik. My configuration uses specific ports for entryPoints such as:

```toml
[entryPoints.http]
address = "xxx.247.131.221:80"
```

**What did you expect to see?**
Normal startup.

**What did you see instead?**

Traefik fatal error message in log: 
```
time="2018-03-20T04:52:38-05:00" level=info msg="Preparing server atg &{Network: Address:xxx.247.131.221:80 TLS:<nil> Redirect:0xc04259ef30 Auth:<nil> WhitelistSourceRange:[] Compress:true ProxyProtocol:<nil> ForwardedHeaders:0xc042358a60} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s" 
time="2018-03-20T04:52:38-05:00" level=error msg="Error opening listener listen tcp xxx.247.131.221:80: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted." 
``` 

**Notes**

1. I use IIS to redirect from port 80 to 443 on a few websites. Those Sites are bound to specific IP address and port number. Those specific IP addresses are **not** part of my Traefik configuration. In my Traefik configuration my entryPoint is also a specific IP address. The issue is only present when first starting (like after a server restart). 
2. I have to stop all of my IIS Sites, start up Traefik, then go back to start all of my IIS sites. 
3. After this, there is no conflict even if I start/stop Traefik.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Træfik!

Please edit your issue and use the [provided template](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE.md).

Issue templates help us help you by providing all necessary information.

Here are the available templates:

- [Standard issue](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE.md)
- [Feature request](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/features.md)
- [Bug report](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/bugs.md)

And remember: each time someone ignores the template, a cute little bunny dies.
<details>
<summary>#SaveTheCuteBunny :heart: :rabbit: :heart:</summary>

![southpark - estrella kill rabbit](https://user-images.githubusercontent.com/5674651/27143914-3cea7896-5130-11e7-81f8-02d8ac2da7a7.gif)

![southpark - estrella kill rabbit2](https://user-images.githubusercontent.com/5674651/27143924-49104c72-5130-11e7-82ae-ccedbd5dfa1c.gif)

</details>

**Comment by emilevauge** [comment]
Hi @stzoid 
Traefik has probably nothing to do with this.
You can configure which port you want to bind with Traefik.
I suppose IIS is binding to the same port by default.
I suggest to join us on our [Slack channel](http://slack.traefik.io/) instead :)
Closing this one for now.
