### ISSUE TITLE
feature: add security/web application firewall middleware

### ISSUE THREAD

**Issue by mtbdeano** [containous/traefik#3060]
### What did you do?

We use a web application firewall (www.signalsciences.com) to inspect and reject suspect we traffic. We are using traefik as an ingress controller for kubernetes. If we could add the signal sciences middleware to traefik, the WAF could protect all traefik traffic. To implement this without these code changes, you must run a nginx proxy with the signal sciences collector in reverse proxy mode wrapped around traefik. This is a lot of layers. By connecting the WAF middle ware directly I can avoid adding the reverse proxy and all the associated overhead.

### What did you expect to see?

I expected a standard pattern to add optional middleware.

### What did you see instead?

I see ways to add metrics, logging, but not firewall middlewares.

### Who could work on this?

I'd gladly see if I can prototype something and submit a PR if the team maintainers think this is worthwhile.

**Comment by nmengin** [comment]
Hello @mtbdeano .

Many thanks for your interest in the project.

Your need seems to be the same as the issue #1336.
That's why I close this issue in favor of it.

Fell free to re-open it if necessary.
