### ISSUE TITLE
Feature Request: Expose web/dashboard through subdomain

### ISSUE THREAD

**Issue by spawnia** [containous/traefik#3076]
I have been using traefik for a few weeks now, it has been really great so far.

However, i and my team members have been unhappy with the way the dashboard is exposed. Rather than having to remember a specific port to view the dashboard or call the api, i would like to be able to easily configure a subdomain for traefik to use.

### Reasons to implement this:
It is easier to remember some URL like `traefik.example.com`, rather than `example.com:1234`.

Having https enabled for the web backend is important for security. Running the dashboard on port 443 would make it easily possible to use a `Let's Encrypt` certificate for it - they currently do not support other ports than 80 or 443.

### Possible solutions
I did find an easy workaround, which was to register the admin port on the same domain as a backend and point a frontend to it, with the subdomain i wanted. Then i was able to get a certificate for it. What could also work is defining an entrypoint that has a subdomain defined as `address` instead of a different port, although i am not sure on that.

If this is already possible, we could agree here on the best way to configure traefik, I would be willing to change the documentation to mention it.

**Comment by nmengin** [comment]
Hello @spawnia.

Many thanks for your interest in the project.

If you want, you can expose your Træfik DashBoard through Træfik and profits of all its mechanisms.
An example of the docker loabels you have to use to do this kind of mechanism is enable [here](https://github.com/containous/traefik/blob/master/examples/acme/docker-compose.yml#L91).

I close the issue but feel free to reopen it if necessary or to join our [Slack workspace](https://traefik.herokuapp.com/) for more [community #support](https://traefik.slack.com/messages/C0CDT22PJ/).

**Comment by spawnia** [comment]
This works fine for now, i was already doing something similar through the file provider. It is just that this feels like a bit of a hack - there should be a more clear and straight forward way to do this.

**Comment by nmengin** [comment]
Sure, @spawnia we should add an example about this use case in documentation.
I'll try to do it in the way to improve our documentation.

Many thanks for your feedback.
