### ISSUE TITLE
Backend server healthcheck handles status codes incorrectly

### ISSUE THREAD

**Issue by SniperCZE** [containous/traefik#3081]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

1) There is healthcheck configured on backend server pool
2) Backend server returns 301 on healthcheck request

### What did you expect to see?

All status codes lower than 500 (strictly spoken lower than 400) should be consider as valid answer.

### What did you see instead?

Any code other than 200 results in disabled backend server. No info in documentation about this behavior.

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
1.5.3
```

**Comment by kuruwan87** [comment]
I'm falling in the same kind of situation here, too bad traefik handle only 200, this part should be customizable imho.
For instance I try to LB influxdb servers and the /ping request return a 204 which is quite accurate.
