### ISSUE TITLE
Traefik 1.6 docker image segfaults if acme is enabled

### ISSUE THREAD

**Issue by micw** [containous/traefik#3085]
### Do you want to request a *feature* or report a *bug*?

BUG

### What did you do?

docker run -it --rm traefik:1.6 --acme

### What did you expect to see?

traefik starting, enabling acme or complaining about missing config

### What did you see instead?

```
A segfault:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1993544]

goroutine 1 [running]:
github.com/containous/traefik/configuration.(*GlobalConfiguration).ValidateConfiguration(0xc4201a6000)
	/go/src/github.com/containous/traefik/configuration/configuration.go:339 +0x184
main.runCmd(0xc4201a6000, 0x0, 0x0)
	/go/src/github.com/containous/traefik/cmd/traefik/traefik.go:159 +0xc5
main.main.func1(0x56, 0x18)
	/go/src/github.com/containous/traefik/cmd/traefik/traefik.go:53 +0x42
github.com/containous/traefik/vendor/github.com/containous/staert.(*Staert).Run(0xc420670c20, 0xc4201a6000, 0xc4206717a0)
	/go/src/github.com/containous/traefik/vendor/github.com/containous/staert/staert.go:84 +0x2e
main.main()
	/go/src/github.com/containous/traefik/cmd/traefik/traefik.go:141 +0x1b19
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
docker run -it --rm traefik:1.6 version
Version:      v1.6.0-rc1
Codename:     tetedemoine
Go version:   go1.10
Built:        2018-03-26_02:47:02PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Linux debian 9, no configuraction

### If applicable, please paste the log output at DEBUG level (`--logLevel=DEBUG` switch)

Same output as above

**Comment by mmatur** [comment]
Hi @micw, 

Thanks for your interest in Træfik !

This issue is fixed by #3084. It will be available in version v1.6.0-rc2
