### ISSUE TITLE
Consul Catalog: Invalid config is generated from services with multiple port mappings

### ISSUE THREAD

**Issue by zs-zs** [containous/traefik#309]
I have the following services in Consul Catalog:

```
{
    "api": ["traefik.frontend.rule=PrefixPath:/api"],
    "consul": [],
    "consul-12000": [],
    "consul-12001": ["udp"],
    "consul-12002": ["udp"],
    "swarm": [],
    "traefik-80": [],
    "traefik-8080": [],
    "web": ["traefik.frontend.rule=PrefixPath:/web"]
}
```

When I run Traefik using the Consul Catalog provider, it seems it tries to generate an invalid config - probably the name of the backend configuration generated by Traefik is not unique, it's already been defined:

`time="2016-04-14T15:05:53Z" level=error msg="Failed to create config" error="Near line 18, key 'backends.backend-consul-12001.servers': Key 'backends.backend-consul-12001.servers.consul-12001--104-130-0-242--12001' has already been defined."`

**Comment by keis** [comment]
The page I linked in the other issues has something interesting to say about unique names too. 
>  The id is set to the name if not provided. It is required that all services have a unique ID per node, so if names might conflict then unique IDs should be provided.

But I'm not sure if it's a strong guarantee that is enforced in the api or if it's something left to the operator.

https://www.consul.io/docs/agent/services.html

**Comment by samber** [comment]
Consul expose some ports in tcp AND udp. So some ports or registered two times in the consul service discovery. When traefik watch consul catalog, it retrieves both services with same ip+port, but one have an "udp" tag.

You should add an env variable to your docker run: SERVICE_12001_IGNORE=true SERVICE_12002_IGNORE=true. Registrator won't register these ports in consul catalog

Actually, I think you don't even need to contact Consul through Traefik. So just use: SERVICE_TAGS=traefik.enable=false

**Comment by emilevauge** [comment]
@samber, traefik should definitely support that, without error. Other service (than Consul) can be deployed with tcp AND udp.

**Comment by zs-zs** [comment]
@samber Hmm if you mean adding environment variables when I run Consul, I just cannot do that unfortunately, because I'm on a cloud where the Consul agent started by the host not me.

**Comment by samber** [comment]
@emilevauge I can do it, but how does traefik will process the udp packets ?
When traefik establish a connection with the backend, it's gonna be tcp/http, right ?

@zs-zs i mean adding environment variables on the container ;-) (see the registrator doc)

**Comment by emilevauge** [comment]
@samber I don't want to manage udp in traefik, I just want that when you deploy a service with udp in consul, traefik does not produce error ;)

**Comment by samber** [comment]
@emilevauge I updated https://github.com/containous/traefik/pull/310

**Comment by samber** [comment]
This issue can be closed ;-)
