### ISSUE TITLE
Frontend rule doesn't work on Docker

### ISSUE THREAD

**Issue by Juliens** [containous/traefik#3094]
### Do you want to request a *feature* or report a *bug*?
bug

### What did you do?

I launch a container with label
```
docker run --name test --label "traefik.frontend.rule=Host:test.com" --label "traefik.enable=true" emilevauge/whoami
```

### What did you expect to see?
I expect to see my new container in the list of frontend/backend

### What did you see instead?
My container is filtered

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
Version:      v1.6.0-rc2
Codename:     tetedemoine
Go version:   go1.10
Built:        2018-03-27_03:02:20PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```
docker run -v /var/run/docker.sock:/var/run/docker.sock traefik:1.6.0-rc2 --docker --api --debug
```

### If applicable, please paste the log output at DEBUG level (`--logLevel=DEBUG` switch)

```
time="2018-03-28T13:49:24Z" level=debug msg="Filtering container with empty frontend rule /test "
```

**Comment by traefiker** [comment]
Closed by #3091.
