### ISSUE TITLE
Setup Traefik for selective services

### ISSUE THREAD

**Issue by samber** [containous/traefik#311]
Hi guys,

My whole infrastructure is registered in consul catalog. When I start Traefik, it creates every single services that do not have a traefik.enable flag set to false.

But I would like to start many instances of traefik, each on routing a selective list of services.

I think we should be able to declare a regex in traefik.toml, for each provider, to filter by a restricted list of services. Example: `serviceNameFilter = "api-*"`
## Updates

Curent status (04-06-2016):
- [x] Constraints implementation
- [x] Command line
- [x] Consul Catalog (see #342)
- [x] KV stores (Etcd, Consul, BoltDB, Zookeeper - see #439)
- [x] Docker (see #438)
- [ ] Marathon
- [x] Kubernetes (see #363)

**Comment by keis** [comment]
I think we might need something similar eventually to but I would much rather base this on tags. E.g you could have the api load balancer only pick up things tagged "api"

**Comment by samber** [comment]
Do you mean like docker constraints ?

**Comment by keis** [comment]
Not familiar with docker constraints but I'm thinking something very much like what you suggest but instead of having a regexp you would have list of tags

```serviceTagFilter = "api"```

and if you have a few services like

```
"api-foo": ["api", "internal", ...],
"gui-bar": ["gui"],
"api-baz": ["api"],
```

you would get api-foo and api-baz in your traefik

**Comment by samber** [comment]
Your model LGTM, but what about mixing both, and match with multiple conditions, following [Docker specs](https://docs.docker.com/swarm/scheduler/filter/#how-to-write-filter-expressions) ?

Example:

- Traefik instances:

  - traefik 1: ```instanceTags = ["api", "web"]```

  - traefik 2: ```instanceTags = ["api", "web", "canary"]```

  - traefik 3: ```instanceTags = ["us-dc1"]```

- Consul Catalog:
  - service-api-foo: ```["traefik.contraint==api"]```

  - service-gui-foo: ```["traefik.contraint==web", "traefik.contraint!=canary"]```

  - service-api-bar: ```["traefik.contraint==us-*"]```


I think we should also export a tag/instance-name to Traefik health metrics because monitoring tools like Prometheus and Grafana allow to filter by regular expressions :
```
{
  "tag": ["web", "v2", "canary"],             // or [] by default
  "pid": 1234,
  ...
}
```

**Comment by emilevauge** [comment]
@samber LGTM with the whole idea :)

- In `traefik.toml`: new parameter `Tags`: `Tags = [ "api", "web"]`
- New label (for Docker, Marathon, Consul services, KV stores) `traefik.constraint:tag==api`, `traefik.constraint:tag!=us*`

**Comment by emilevauge** [comment]
Hi all, I was thinking about this one.
Don't you think it would be better to do the opposite here?
- In `traefik.toml`: new parameter `constraint:tag==api`, `constraint:tag!=us*`
- New label: `Tags`: `Tags = [ "api", "web"]`

**Comment by samber** [comment]
I was asking myself the same question.

I was thinking it would be better to follow the Docker filtering model: constraints on containers. Ex: Traefik tag ```us-ny``` matching with container constraints ```us-*```.

But in the real world, it will be probably more useful to set the constraint on the Traefik instance. Examples:
- filter by microservice domains: containers ```external-web```, ```internal-monitoring```, ```internal-elk``` filtered by Traefik constraint ```internal-*```
- scale a load balancer for a website: containers ```website-api```, ```website-static```, ```website-auth``` matching with Traefik constraint ```website-*```
- canary mode: containers ```v-1.42.0```, ```v-2.0.0-beta``` filtered by Traefik constraint ```v-2*```

Then region would be filtered with regex: containers ```["ny-dc1", "par-dc2"]```, ```["par-dc2"]``` matching with Traefik constraint ```par-dc2```

@emilevauge what use cases do you see for both methods ?

**Comment by emilevauge** [comment]
@samber: I agree with your use cases.
It seems like a better solution.

**Comment by mgoodness** [comment]
I *think* a good approach to this for Kubernetes would be adding the tags as annotations on each Ingress. The constraint(s) would then be fed into a Traefik controller as an environment variable or as part of a `traefik.toml` ConfigMap.

**Comment by samber** [comment]
I just pushed a first implementation of constraints. It supports globing (```"ny-*"```) but not regex yet (```/(ny|par)-.*/```)

Please review, I will write doc and tests when implementation gonna be confirmed.

FYI, I added a new dependency for globing: ```github.com/ryanuber/go-glob```

Please note following details about this implementation of constraints:
- If multiple constraints are provided, every single one have to match (AND condition).
- A constraint expression with ```!=``` must match none of tags.
- For Consul Catalog: 2 containers of the same service can have different tags (and then matching rules)

To test:
- Consul tags: ```traefik.tags=helloworld,rev-1.0.0-beta``` (or ````traefik.tags=helloworld``` + ```traefik.tags=rev-1.0.0-beta```)
- ```./traefik --consulCatalog --consulCatalog.constraint 'tag==helloworld'```
- ```./traefik --consulCatalog --consulCatalog.constraint 'tag!=api'```
- ```./traefik --consulCatalog --consulCatalog.constraint 'tag==hel*rld'```
- ```./traefik --consulCatalog --consulCatalog.constraint 'tag==helloworld' --consulCatalog.constraint 'tag!=rev-*-beta'```
- ```./traefik --configFile=/etc/traefik/traefik.toml``` with following configuration:
````
# /etc/traefik/traefik.toml

[consulCatalog]
        watch = true
        constraints = ["tag==hel*rld", "tag!=rev-*-beta"]
```

@emilevauge : Could you please ping some contributors for developing constraints on other backends ?

**Comment by lorn** [comment]
Just to make sure, if this feature is implemented for marathon, we will have something like what marathon-lb call groups? https://github.com/mesosphere/marathon-lb#direct-invocation

**Comment by dtomcej** [comment]
Now that provider-specific constraints have been implemented: (https://docs.traefik.io/configuration/commons/#provider-specific)

I will go ahead and close this issue.

If you have any further issues, please open a new ticket.

Thanks!
