### ISSUE TITLE
contrib: dumpcerts.sh needs updating

### ISSUE THREAD

**Issue by mathuin** [containous/traefik#3115]
### Do you want to request a *feature* or report a *bug*?

I wish to report a bug.

### What did you do?

I ran the `dumpcerts.sh` script against a legit ACME JSON file.

### What did you expect to see?

A directory populated with certificates and keys.

### What did you see instead?

An error prevented the script from actually executing -- this same error was mentioned here: https://github.com/containous/traefik/pull/1484#issuecomment-376046953 -- but when I addressed that issue, a number of other minor issues arose.  Apparently the JSON file's architecture has changed!

I have a working version and can submit a pull request, I just wanted to report the issue first.

### Output of `traefik version`: (_What version of Traefik are you using?_)

I wasn't running Traefik per se, but `dumpcerts.sh` was last modified about 27 days ago in commit `8380de1bd9c5fdd751361fc3b40a81076a8a498b`.

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

I ran this on an Ubuntu Linux system with `jq` and other tools installed as needed.

**Comment by nmengin** [comment]
Hello @mathuin 

Many thanks for you interest in the project.

As explained [here](https://github.com/containous/traefik/issues/2418#issuecomment-376165878), the ACME Json file format has been changed.
You have to run Træfik once to migrate automatically the file to the new format before to dump it.

I guess your issue is a deplucate of #2418 .

**Comment by mathuin** [comment]
I had not noticed #2418 as a duplicate of this issue as its original purpose was a feature request, with the "bug report" part falling much later in the issue.  Since you said in your comment that you were going to close it but didn't, I'll close it now.  Thanks!
