### ISSUE TITLE
Do SSLRedirect before auth.basic

### ISSUE THREAD

**Issue by HitkoDev** [containous/traefik#3134]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Deploy a docker service with the following labels:

```yaml
        - traefik.frontend.rule=Host:private.example.com
        - traefik.frontend.entryPoints=http,https
        - traefik.frontend.auth.basic=username:password
        - traefik.frontend.headers.SSLRedirect=true
```

### What did you expect to see?

Opening `http://private.example.com` redirects to `https://private.example.com` before prompting for authorisation.

### What did you see instead?

`http://private.example.com` requires authorisation before redirecting. This means user has to enter authorisation data twice, and the first authorisation data is sent over an insecure connection.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
1.5.4
```

**Comment by traefiker** [comment]
Closed by #3187.
