### ISSUE TITLE
ConsulCatalog: exclude/blacklist services

### ISSUE THREAD

**Issue by zs-zs** [containous/traefik#314]
As a user of the ConsulCatalog provider
I want to exclude services from Traefik
So that I won't get bothered by them

This is an improvement idea, related to #309 :)
What do you think?

**Comment by zs-zs** [comment]
Probably also related to #311?

**Comment by emilevauge** [comment]
You can use the tag `traefik.enable=false` : http://docs.traefik.io/toml/#consul-catalog-backend :)

**Comment by zs-zs** [comment]
@emilevauge The problem is that I cannot tags to an already running service. Consul is started by the cloud infrastructure, not me. 
For the record: here is the regarding pull request: https://github.com/docker/docker/pull/18958
