### ISSUE TITLE
Manage bad ACME certificates

### ISSUE THREAD

**Issue by nmengin** [containous/traefik#3162]
### Do you want to request a *feature* or report a *bug*?

Bug
### What did you do?

I helped users who had a ACME certificate for a domain with no generated certificate/key in their `acme.json` file.

```json
    {
      "Domain": {
        "Main": "*.*.foobar.io",
        "SANs": null
      },
      "Certificate": null,
      "Key": null
    }
```

### What did you expect to see?

Træfik retries to generate a valid certificate. Or do not store bad formatted certificates and generate an error message.

### What did you see instead?

Error message : `Error loading new configuration, aborted unable to generate TLS certificate : tls: failed to find any PEM data in certificate input`.

### Output of `traefik version`: (_What version of Traefik are you using?_)

1.6-RC4 (an older versions I guess)

**Comment by traefiker** [comment]
Closed by #3191.
