### ISSUE TITLE
Is "traefik.enable=false" applied to application or backend ?

### ISSUE THREAD

**Issue by samber** [containous/traefik#317]
Hi guys,

```traefik.enable=false``` has not the same definition in documentation:
- ```disable this application in Træfɪk``` (marathon backend)
- ```disable this container in Træfɪk``` (consul catalog + docker backends)

Which one is correct ?

**Comment by emilevauge** [comment]
@samber, this is because you put labels on application with marathon, and on container with docker ;) No mistake here.

**Comment by samber** [comment]
Does it make sense to disable only a container for docker, consul, etcd... backends ?

**Comment by emilevauge** [comment]
Yes, you can then disable some containers that you don't want to see in traefik.

**Comment by samber** [comment]
Ok, no problem.
