### ISSUE TITLE
My file api some requests end up in a 502, random everytime

### ISSUE THREAD

**Issue by eele94** [containous/traefik#3176]
**I'm submitting a bug**
**Action taken**
Hello I have made a file api for requesting files on my site.

On the website I request every media that is uploaded via the file api.

**Expected result**
The expected result is that every file gets loaded.

**Actual result**
When I am loading the page 7/8 or 6/8 images are loaded everytime I refresh.
![traefik](https://user-images.githubusercontent.com/8152346/38617686-f30e8604-3d97-11e8-84f8-0a85738491af.PNG)
![failload](https://user-images.githubusercontent.com/8152346/38617692-f5e75932-3d97-11e8-9886-b97bfe6681cf.PNG)

The weird thing is when I go to the URL directly it never seems to fail.
https://file.iturnit.com/8c6bac716cbf27372a6a291e968b5569e6b84f5e7462.jpg

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Træfik!

Please edit your issue and use the [provided template](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE.md).

Issue templates help us help you by providing all necessary information.

Here are the available templates:

- [Standard issue](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE.md)
- [Feature request](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/features.md)
- [Bug report](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/bugs.md)

And remember: each time someone ignores the template, a cute little bunny dies.
<details>
<summary>#SaveTheCuteBunny :heart: :rabbit: :heart:</summary>

![southpark - estrella kill rabbit](https://user-images.githubusercontent.com/5674651/27143914-3cea7896-5130-11e7-81f8-02d8ac2da7a7.gif)

![southpark - estrella kill rabbit2](https://user-images.githubusercontent.com/5674651/27143924-49104c72-5130-11e7-82ae-ccedbd5dfa1c.gif)

</details>

**Comment by eele94** [comment]
fixed it. mb
