### ISSUE TITLE
update https://github.com/unrolled/secure vendor dependency

### ISSUE THREAD

**Issue by aek** [containous/traefik#3194]
I have merged a PR with a new option SSLForceHost in https://github.com/unrolled/secure in the https://github.com/unrolled/secure/pull/35
It will be awesome to have it available into Traefik too. It was created with Traefik in mind to handle all SSL Redirects through unrolled/secure. I don't know how to proceed for Traefik. Should I make a PR for traefik too? or there is something else to update that dependency in Traefik?

**Comment by ldez** [comment]
Hi,

Feel free to open a PR, you can follow this guide: https://github.com/containous/traefik/blob/master/CONTRIBUTING.md

In your case, you also need:
- `dep ensure -update github.com/unrolled/secure`
- `make dep-ensure` (required even if you do the previous command)
- modify templates: https://github.com/containous/traefik/tree/master/templates
- modify template function: https://github.com/containous/traefik/blob/21b8b2deb552e01d163e12ba2e587786573e7962/provider/label/partial.go#L182-L213
- modify k8s function: https://github.com/containous/traefik/blob/21b8b2deb552e01d163e12ba2e587786573e7962/provider/kubernetes/kubernetes.go#L596-L626
- update providers/backends documentation for labels/annotations: https://github.com/containous/traefik/tree/master/docs/configuration/backends

**Comment by aek** [comment]
@ldez with the 1.7.0 release I have noticed that there is no support for file provider config to be able to use SSLForceHost support introduced on #3246

**Comment by ldez** [comment]
@aek theFfile provider support `SSLForceHost` in 1.7.0: there is no need for explicit modification for the provider File.

**Comment by m-nouredini** [comment]
> Can I use SSLForceHost to redirect http://www.foo.example.com to https://foo.example.com? I've set these labels:
> 
> ```
> labels:
>   - "traefik.docker.network=web"
>   - "traefik.enable=true"
>   - "traefik.frontend.rule=Host:foo.example.com,www.foo.example.com"
>   - "traefik.port=80"
>   - "traefik.protocol=http"
>   - "traefik.frontend.headers.SSLRedirect=true"
>   - "traefik.frontend.headers.SSLHost=foo.example.com"
>   - "traefik.frontend.headers.SSLForceHost=true"
> ```
> but it does not work for me...
> When I visit http://www.foo.example.com I'll be redirected to https://www.foo.example.com

I've found the problem,
by removing these two lines from my `traefik.toml`:
```
[entryPoints]
  ...
    [entryPoints.http.redirect] --> should be removed
    entryPoint = "https" --> should be removed
```  
 `SSLForceHost` and `SSLHost` are working correctly.
