### ISSUE TITLE
[Proposal] Matching route with multiple rules

### ISSUE THREAD

**Issue by samber** [containous/traefik#323]
Hi guys,

It would be awesome to set a route according to an hostname and a path in a regular expression. Example: ```rule = "Host:www.example.com,Path:/api/(v1|v2)/"```

**Comment by samber** [comment]
Sorry, it already exist. It is missing in the doc ;-)

**Comment by jippi** [comment]
has this been added to the docs? :)

**Comment by emilevauge** [comment]
@jippi yep, here: http://docs.traefik.io/basics/#frontends :)
