### ISSUE TITLE
Provide templating for serviceName in Tracing provider

### ISSUE THREAD

**Issue by gaui** [containous/traefik#3233]
### Do you want to request a *feature* or report a *bug*?

Feature

When using `tracing` provider you can provide a name for the service Jaeger/Zipnik registers (`tracing.serviceName`). The recommended value is `traefik` but I think it would be more useful if you could use templating for dynamic values, so it would be possible to filter by individual frontend/backend and that the dependencies/DAG visibility would make more sense. So instead of [this](https://i.imgur.com/tuXPn6V.png) we would get something like [this](https://pbs.twimg.com/media/DQbirDbVoAAtNR3.jpg).

I don't know how the templating syntax should be, but the possibility to set frontend/backend as the `tracing.serviceName` would be useful.

**Comment by mmatur** [comment]
Hi @gaui,

Thanks for your interest in Træfik. 

After some investigation. I think it is not the good approach to have dynamic values for `serviceName`. 

You can find a docker-compose project that give you a sample how to integrate [Træfik with Jaeger](https://github.com/mmatur/traefik-jaeger-integration)

This example provide DAG like that:
![screenshot from 2018-04-26 12-09-45](https://user-images.githubusercontent.com/1776972/39300254-5fd3ca06-494b-11e8-9abe-1c5f31031e4c.png)

So if you set dynamic value based on frontend/backend for serviceName. You will have something like that
![screenshot from 2018-04-26 12-22-48](https://user-images.githubusercontent.com/1776972/39300621-9cdde89a-494c-11e8-9c8a-c551c3ff2437.png)


I will close this issue, please feel free to reopen it if necessary
