### ISSUE TITLE
Feature: Allow multiple frontends to be defined using docker labels in swarm mode

### ISSUE THREAD

**Issue by ajardan** [containous/traefik#3235]
### Do you want to request a *feature* or report a *bug*?
Request a *feature*

### What did you do?

I was planning to have multiple frontends for a single swarm service with different settings (hostname, IP whitelist, etc)

### What did you expect to see?

I expected to be able to define multiple frontends as it is possible to do so manually when using a config file

### What did you see instead?

According to the docs, only 1 frontend can be defined per docker service (unless it listens on multiple ports)

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.6.0-rc6
Codename:     tetedemoine
Go version:   go1.10.1
Built:        2018-04-17_11:59:31AM
OS/Arch:      linux/amd64 ```

**Comment by nmengin** [comment]
Hello @ajardan .

Many thanks for your interest in the project.

The feature you described seems to already exists : it's the `segment labels`.

You can find more information about it in the [documentation](https://docs.traefik.io/v1.6/configuration/backends/docker/#on-containers-with-multiple-ports-segment-labels).

I close the issue, but feel free to reopenit if necessary or join our [Slack workspace](https://traefik.herokuapp.com/) for more [community #support](https://traefik.slack.com/messages/C0CDT22PJ/).
