### ISSUE TITLE
Traefik sends invalid close code 1006 to servers when client close TCP gracefully

### ISSUE THREAD

**Issue by jd3nn1s** [containous/traefik#3236]
### Do you want to request a *feature* or report a *bug*?
bug

### What did you do?
Configure a websocket server
Configure traefik to front the websocket server
Configure AWS ALB to front traefik
Connect a websocket client to ALB
Kill the websocket client, noting that OS sends TCP RST to ALB.

### What did you expect to see?

Traefik closes the underlying TCP connection like ALB. 

### What did you see instead?

Traefik sent a websocket close frame with close code 1006. Note that according to RFC6455 1006 should never be sent on the wire.

### Output of `traefik version`: (_What version of Traefik are you using?_)

1.5.4

**Comment by ldez** [comment]
Closed by #3425
