### ISSUE TITLE
API backend confs disappear when doing docker up

### ISSUE THREAD

**Issue by vito-c** [containous/traefik#3240]
### What did you do?

Create a docker-compose with docker labels for traefik rules. Run traefik with a docker backend and an api backend. Add some rules via api calls and then execute docker-compose up <service name>

The rules for <service name> appear but the configs for all the api are gone.

### What did you expect to see?

I expected traefik to not destroy the api rules/configs

### What did you see instead?
api rules disappeared

### Output of `traefik version`: (_What version of Traefik are you using?_)
1.5.4

**Comment by ldez** [comment]
Thanks for your interest in Traefik !

Traefik don't store data from the API, it's the expected behavior.
