### ISSUE TITLE
UX issues in the new dashboard

### ISSUE THREAD

**Issue by kachkaev** [containous/traefik#3258]
### Do you want to request a *feature* or report a *bug*?

bug

### What did you do?

While we're [waiting for the official 1.6 docker image](https://github.com/docker-library/official-images/pull/4304), I downloaded a shiny new traefik 1.6 from `containous/traefik@sha256:74c7e144161a850b648e4a690ad6940c1ef152c7797787e56673c6352846e51c` (https://github.com/containous/traefik-library-image/issues/29#issuecomment-385984440) and started playing with the fresh dashboard. Here's a CSS glitch that I'm observing in Firefox:

<img width="981" alt="screen shot 2018-05-02 at 18 41 54" src="https://user-images.githubusercontent.com/608862/39539999-492994a0-4e39-11e8-93e2-eb29c4623874.png">

Context:

<img width="1232" alt="screen shot 2018-05-02 at 18 42 51" src="https://user-images.githubusercontent.com/608862/39540009-4ffa65ca-4e39-11e8-9ba8-3e30bcdb000c.png">

The same divs in Chrome look a bit different, but styling is still glitchy:

![kapture 2018-05-02 at 18 48 58](https://user-images.githubusercontent.com/608862/39540076-84fb71b0-4e39-11e8-9739-3b870fa6564a.gif)

**Comment by kachkaev** [comment]
A few more other minor UX issues I've noticed:

* Despite that I've set `--web.statistics=true --web.statistics.recenterrors=200`, I can't seem to find a list of errors anywhere in the interface. Once it is added, it'd be great if it was possible to select text in it or even click on the urls. The old implementation was refreshing the real DOM nodes every couple of seconds, which made text selecting quite a challenge 😅 

![dashboard-errors](https://user-images.githubusercontent.com/608862/39579978-f23c06ee-4edf-11e8-8dda-00158ddf9606.gif)


* The new _Average Response Time_ and _Total Status Code Count_ take over 5 secs to appear, which feels a bit too much for a dockerized localhost traefik with no load. The requests for the data are blazingly fasts, so it must be something on the client side that causes the delay (I may be wrong).

  ![dashboard-health](https://user-images.githubusercontent.com/608862/39580009-fe0c4984-4edf-11e8-94ac-a348e9617a7b.gif)

* The lack of colour in _Total Status Code Count_ makes this chart a bit more laborious to read than in the previous version, where colour encoded HTTP state. Because colour is a pre-attentive visual variable, it is one of the ’cheapest’ data encoding methods for the human brain. It'd be great to see it back to do a search task quicker  (e.g. to spot the rise of 5xx immediately, not after 1-2 secs).

* Movement (animation) is also a pre-attentive visual variable, which means that we should be always careful with it to avoid unwanted distraction. This timeline fading attracts a bit too much attention and could be ‘calmed down’:

    ![dashboard-timeline](https://user-images.githubusercontent.com/608862/39580032-0c5897ae-4ee0-11e8-9448-7428d7f9224e.gif)

* Going to ‘Health’ tab (e.g. http://localhost:8080/dashboard/status) and then refreshing the page strips `status` from the URI and brings back to the main dashboard page.

Please don't take my comments as criticism – I think it's great that the new dashboard made it to 1.6! ❤️ I wish I knew Angular as well as React to fix some of the above issues, but I hope that my plain feedback is helpful at this point too!

**Comment by ldez** [comment]
for the recent errors section, I think you have mix `--api` and `--web`, you can use both.

replace `--web.statistics=true --web.statistics.recenterrors=200` by `--metrics.statistics.recenterrors=200`

https://docs.traefik.io/v1.6/configuration/metrics/#statistics

**Comment by kachkaev** [comment]
@ldez ouch, my fault! I simply did not add those flags despite that I was sure I did. This is because I have to commands for starting Traefik in docker and the dev one did not include statistics. Both `--metrics.statistics.recenterrors=200` and `--web.statistics=true --web.statistics.recenterrors=200`, so things are backwards-compatible. False alarm!

There're still a couple of issues in the list. One being that the URLs are not clickable and the other that the DOM resets every couple of seconds and so selecting and copying remains challenging as in previous versions.
![kapture 2018-05-03 at 17 47 01](https://user-images.githubusercontent.com/608862/39590880-029864dc-4efa-11e8-8e97-68af2ae0e01d.gif)

I though Angular would be smart enough to reuse the DOM nodes and not produce this side-effect, just as React. 🤔 Is there a cheap fix for this? 

I'd also use `white-space: nowrap` css in _Status_ and even possibly _Time_ column. That's so that the their short values values did not look torn on narrow screens. URLs could either have `overflow:hidden` or use more than one line if they don't fit the rest of the table width.

**Comment by trondhindenes** [comment]
Just to add on this (might warrant a separate issue but):
If the "filter" text box has input when a change happens in a service, the filter is cleared.

**Comment by ldez** [comment]
I'm preparing a PR, I already fix most points.

I still have the main problem at the origin of the issue, it's very impacting, I must think about the best solution.

**Comment by YP28** [comment]
@ldez is there a main thread to keep track of the UI issues? I found another one, and it would be nice to have an overview of all the issues currently present.

![screen shot 2018-05-09 at 12 55 14](https://user-images.githubusercontent.com/4119194/39811259-640cbd70-5388-11e8-84ab-43fee027e332.png)

There's a floating bar in the bar chart here.

**Comment by ldez** [comment]
@YP28 Thanks, a PR coming really soon.

**Comment by ldez** [comment]
> Going to ‘Health’ tab (e.g. http://localhost:8080/dashboard/status) and then refreshing the page strips status from the URI and brings back to the main dashboard page.

It's a choice and a technical constraint: the page is automatically updated every 3s, if you do it manually, you will lose all the data in the graphs because all the graph data are in the client side (like the previous version of the webui).

> I'd also use white-space: nowrap css in Status and even possibly Time column. That's so that their rather short values did not look torn on narrow screens. URLs could either have overflow:hidden or use more than one line if they don't fit the rest of the table width.

I'm sure that `overflow:hidden` is a good idea in this case, I will try to create something more human readable as you suggested in the PR.

**Comment by kachkaev** [comment]
> I will try to create something more human readable as you suggested in the PR.

It can be a human-readable time in UTC or a local time zone (say, with a minute precision) with a more technically looking time coordinate shown when the value is hovered. A simple and quite a common way of implementing this is just assigning `title="TTTT"` to a span. Could this trick be applied to status codes too? I.e. the first column would say `404` or `500` (coloured the same way as the chart above) and hovering over a box with the number would reveal `title="Not Found"`.

> It's a choice and a technical constraint: the page is automatically updated every 3s, if you do it manually, you will lose all the data in the graphs because all the graph data are in the client side (like the previous version of the webui).

I understand that the chart data would be lost, that's fine. Nevertheless, it'd be still great if the URL was not changing on page refresh and so a user was not ‘redirected’ from _Health_ to _Dashboard_. React Router or Next.js router would do this out of box, so I hope that the same trick in Angular is also cheap to implement.

**Comment by ldez** [comment]
Angular do that also but we have other constraints: like support custom path prefix.

**Comment by kachkaev** [comment]
Yeah, I understand. But perhaps the app could still check if the path ends with `/status` and init accordingly? I guess that this context info should be somehow known regardless of the path prefix, because:

* http://localhost:8080/ → http://localhost:8080/dashboard/
* http://localhost:8080/dashboard/ – OK
* http://localhost:8080/dashboard/status – OK
* http://localhost:8080/dashboard/anything-else – 404

PS: Checking out your image now 👍

**Comment by ldez** [comment]
I'm not sure you have a full overview of the constraints in the server side.
I have already spend time to try to do something about that and I don't find a better solution.

**Comment by kachkaev** [comment]
OK, never mind – it's not a big deal anyway! I guess that the only practical scenario for refreshing the web UI is resetting the page it's buggy. So if _Health_ UI is stable, users would not need to press `CMD+R` and see `/status` trimmed 😉

**Comment by traefiker** [comment]
Closed by #3299.

**Comment by mavimo** [comment]
@ldez some issue seems not solved:

![image](https://user-images.githubusercontent.com/43941/40076945-86173092-5880-11e8-872b-8f494709707a.png)

**Comment by ldez** [comment]
@mavimo thnak you I will fix that.
