### ISSUE TITLE
Content-Md5 -> Content-MD5

### ISSUE THREAD

**Issue by TeaBough** [containous/traefik#326]
When making a diff between two requests (one coming from traefik and one directly from the client) I've noticed a subtle difference that is causing big trouble in my use case : 

direct request : 
```
User-Agent: aws-sdk-java/1.10.33 Linux/4.4.5-1-ARCH Java_HotSpot(TM)_64-Bit_Server_VM/25.66-b17/1.8.0_66
Date: Tue, 19 Apr 2016 16:19:00 GMT
Content-Type: application/octet-stream
Content-MD5: vezJlJfiuNp6geRswa7w9w==
Content-Length: 478
Connection: Keep-Alive
Expect: 100-continue
```

from `traefik` :
```
User-Agent: aws-sdk-java/1.10.33 Linux/4.4.5-1-ARCH Java_HotSpot(TM)_64-Bit_Server_VM/25.66-b17/1.8.0_66
Date: Tue, 19 Apr 2016 16:18:26 GMT
Content-Type: application/octet-stream
Content-Md5: vezJlJfiuNp6geRswa7w9w==
Content-Length: 478
Expect: 100-continue
X-Forwarded-For: 192.168.76.248
X-Forwarded-Host: mesos-slave2.ny1.teads.tech:31856
X-Forwarded-Proto: http
X-Forwarded-Server: mesos-slave2
Accept-Encoding: gzip
```

The problem comes from the field `Content-MD5` that is different when coming from `traefik`  : `Content-Md5`.

**Comment by emilevauge** [comment]
Hi @TeaBough, I have to investigate this point.
But be aware that header field names are case-insensitive in RFC.

**Comment by emilevauge** [comment]
This is due to golang: https://golang.org/src/net/textproto/reader.go?s=14875:14919#L552
Maybe I will be able to change this behavior, but clearly that's not a bug.
If you have a backend that rely on header case sensitivity, you should fix it :)

**Comment by TeaBough** [comment]
Hi, yes. My use case is this one. I'm using a scala aws client and s3rver (https://www.npmjs.com/package/s3rver) and we the request goes through `traefik` I get a nice : 
```
Unable to verify integrity of data upload
```

**Comment by emilevauge** [comment]
https://github.com/aws/aws-sdk-java/issues/436 ^^

**Comment by emilevauge** [comment]
This should be supported by the latest aws-sdk-java: https://github.com/aws/aws-sdk-java/pull/590. Maybe you should just upgrade?

**Comment by TeaBough** [comment]
Thanks for your input ! It was indeed a problem with `aws-sdk-java`. I've updated the version in [AWSScala](https://github.com/seratch/AWScala.git) and now it's working. Thanks again for you reactivity !
