### ISSUE TITLE
Traefik tracing reports unprecise tags

### ISSUE THREAD

**Issue by trondhindenes** [containous/traefik#3273]
### What did you do?
With Jaeger tracing enabled, the backend url collected in "tags" is not correct.

Given a frontend/backend rule as such:
`Host:apistuff.com;PathPrefixStrip: /client/2`

I'm getting the following:
Entrypoint span tag: `http.url "/client/2/channel/flat"`
"forward" span tag: `http.url "http://10.245.20.241:8000"`

### What did you expect to see?
Entrypoint span tag: `http.url "/client/2/channel/flat"`
"forward" span tag: `http.url "http://10.245.20.241:8000/channel/flat"` (this is the actual url sent from Traefik to the backend node)

### What did you see instead?
See above

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
1.6.0
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

all Jaegertracing components: `1.4.1`

**Comment by traefiker** [comment]
Closed by #3279.
