### ISSUE TITLE
InfluxDB Metrics via TCP instead of UDP

### ISSUE THREAD

**Issue by podilra** [containous/traefik#3280]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?
Currently the Traefik metrics backend for InfluxDB assumes access to the UDP port for InfluxDB. We currently use InfluxDB for metrics collection in Kubernetes without the UDP port enabled with all metrics being sent over HTTP. 
I would like to have a feature to select the port type (HTTP/UDP) in the configuration file and send metrics over HTTP as well.

### Misc Details
I'll look into contributing for this feature and submit a pull request.

From my initial research looks like the InfluxDB client in Go has 2 methods to send data : 
- HTTP : NewHTTPClient()
- UDP: NewUDPClient() "Currently used as the default in Traefik"

**Comment by mmatur** [comment]
Fixed by https://github.com/containous/traefik/pull/3391
