### ISSUE TITLE
Documentation - clarify entrypoint command line for TLS

### ISSUE THREAD

**Issue by jgoodall** [containous/traefik#3289]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

The [documentation on `--entryPoints` command line options](https://docs.traefik.io/configuration/entrypoints/#all-available-options) for TLS is ambiguous. The docs have `TLS:goo,gii`, which does not tell the reader what the `goo` and `gii` are. I believe those represent the certificate file and key file, respectively.

### What did you expect to see?

```
TLS:<path_to_cert_file>,<path_to_key_file>
```

### What did you see instead?

```
TLS:goo,gii
```

**Comment by traefiker** [comment]
Closed by #3290.
