### ISSUE TITLE
HTTP report backend in Host

### ISSUE THREAD

**Issue by dotmpe** [containous/traefik#329]
Hi,

running Jenkins behind traefik is not possible.

Looking at the whoami docker-compose example, I thought this was due to the Host header. However, checking does not show this is the case. I may have to move tje issue to jenkins, but there's some questsion. It did not seem this issues has come up yet. But I am new to traefik.

Is it alternatively perhaps possible to add/rewrite response headers? The only configuration I use now
are docker labels (traefik.frontend.rule, traefik.ports, or traefik.enable=false).

**Comment by emilevauge** [comment]
Hi,
You can do that by enabling parameter `passHostHeader = true` in your  frontend definition (if your are using Docker, use label `traefik.frontend.passHostHeader=true`).
