### ISSUE TITLE
Add possiblity to the API and UI to browse the access/request log

### ISSUE THREAD

**Issue by matthiasbaldi** [containous/traefik#3292]
### Description

I asked in the new UI #2226 PR if it would be possible to add a possibility to see the request/access log in the UI.

I got some reactions but no answer for this, so I openend this this issue because I think this feautre includes more than just an UI thing. When I understood the documentation correctly [API Doc](https://docs.traefik.io/configuration/api/) there is at the moment no API for that.

So it would be required to expand the API and the UI.

### Feature Request

* Expand the API with a new endpoint for the access/request log
* Include the new API into the UI (new tab or request/access log per "Backend/Frontend"

What do you think? Is that possible or do you have some consideration vs a such feature?

**Comment by emilevauge** [comment]
Hey @matthiasbaldi, thanks for your contribution!
After some discussion, we think that exposing access logs in an API leads to multiple security issues that would be complex to deal with.
We prefer to not implement this one then ;)

**Comment by matthiasbaldi** [comment]
@emilevauge Thanks for your answer.
Yeah I thought that this could be a too big issue for the security in Traefik.
