### ISSUE TITLE
no TXT record found on subdomain - it was created on the tld

### ISSUE THREAD

**Issue by SvenDowideit** [containous/traefik#3306]
using traefik v1.6 docker image. 

If I set `--acme.domains=*.ona.im` the cert is working.

If I set `--acme.domains=*.tower.ona.im` it fails with:

```
infra_traefik.1.pw77d3lcp0tw@TOWER-SL    | legolog: 2018/05/11 04:56:57 [INFO][*.tower.ona.im] acme: Obtaining bundled SAN certificate
infra_traefik.1.pw77d3lcp0tw@TOWER-SL    | legolog: 2018/05/11 04:56:59 [INFO][*.tower.ona.im] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz/Ce83WLVQ0mSgJD-RjPh70pP4wwMrwn2Ebei6r074T4M
infra_traefik.1.pw77d3lcp0tw@TOWER-SL    | legolog: 2018/05/11 04:56:59 [INFO][tower.ona.im] acme: Trying to solve DNS-01
infra_traefik.1.pw77d3lcp0tw@TOWER-SL    | legolog: 2018/05/11 04:57:00 [INFO][tower.ona.im] Checking DNS record propagation using [127.0.0.11:53]
infra_traefik.1.pw77d3lcp0tw@TOWER-SL    | time="2018-05-11T04:57:17Z" level=error msg="Unable to obtain ACME certificate for domains \"*.tower.ona.im\" : cannot obtain certificates map[tower.ona.im:acme: Error 403 - urn:ietf:params:acme:error:unauthorized - No TXT record found at _acme-challenge.tower.ona.im]"
```

interestingly, it seems to be creating a TXT entry for `_acme-challenge.ona.im` when it should be creating one for `_acme-challenge.tower.ona.im`.

the rest of my cmdline (I'm not using a cfg file) looks like:

```
    command: [
      "--debug", 
      "--docker", 
      "--docker.swarmmode", 
      "--docker.domain=tower.ona.im", 
      "--docker.watch", 
      "--api=true", 
      "--api.entrypoint=api", 
      "--accesslog=true", 
      "--loglevel=DEBUG", 
      "--traefiklog=true",
      "--entrypoints=Name:api Address::8686", 
      "--entrypoints=Name:http Address::80", 
      "--entrypoints=Name:alt-http Address::8080", 
      "--entrypoints=Name:https Address::443 TLS", 
      "--defaultentrypoints=http", 
      "--acme",
      "--acme.acmelogging",
      "--acme.dnschallenge", 
      "--acme.email=sven-tower@home.org.au", 
      "--acme.domains=*.tower.ona.im", 
       "--acme.dnschallenge", 
      "--acme.dnschallenge.provider=namedotcom", 
      "--acme.dnschallenge.delaybeforecheck=10", 
      "--acme.entrypoint=https", 
      "--acme.storage=/etc/traefik/acme/acme.json"]
```

**Comment by SvenDowideit** [comment]
when I change to use a domain i have on gandi.net, things work - so presumably its just something specific to name.com

hopefully https://github.com/xenolf/lego/issues/543 is the root cause?

**Comment by ldez** [comment]
It's a problem with your DNS provider (name.com).

You must contact (name.com)[https://www.name.com/support]

https://docs.traefik.io/v1.6/configuration/acme/#dns-provider-support

**Comment by SvenDowideit** [comment]
hopefully this can be solved with a small change to lego: https://github.com/xenolf/lego/pull/545

**Comment by ldez** [comment]
@SvenDowideit For the wildcard support you need to use the https://github.com/xenolf/lego/tree/acmev2, but the current state of this branch is "experimental" (the CLI don't really works well).

**Comment by SvenDowideit** [comment]
@ldez yup - it turns out there's a problem with the namedotcom provider for non-wildcard subdomains too - assuming that can be solved the next part should work too.

hopefully @pmoroney can help out  - I'm having dns timeout issues as well, so have to move on to doing my dayjob.

**Comment by ldez** [comment]
Since lego v1.1.0 and Traefik v1.7, you can set some extra env vars to customize TTL and timeout:
```
NAMECOM_POLLING_INTERVAL
NAMECOM_PROPAGATION_TIMEOUT
NAMECOM_TTL
NAMECOM_HTTP_TIMEOUT
```

Could you try with v1.7?

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Slack workspace](https://traefik.herokuapp.com/) for more [community #support](https://traefik.slack.com/messages/C0CDT22PJ/).

**Comment by SvenDowideit** [comment]
Sorry, I needed things to work, so moved my domains away from name.com.
