### ISSUE TITLE
Support for backend based on chef search result (or other CM tools)

### ISSUE THREAD

**Issue by adesprez** [containous/traefik#3325]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

In my company we are currently using HAProxy as a proxy/loadbalancer in front of microservices. Some of our microservices are scaling up/down.
HAProxy configuration changes are made by a Chef cookbook which will search for the roles attached to each nodes and assign the corresponding backend to the role/node. This Chef cookbook is executed by a daemon.

This process is working but is error prone: daemon running correctly, cookbook bugs...
There are other solutions based on the new HAProxy runtime API but this will involve specific devs to trigger the API.

It would be so much easier to have a proxy which can query Chef in order to build its backends/servers configuration.

Going further, Puppet and Ansible users would be keen to have this kind of backend support as well.

Thanks,

Adrien

**Comment by emilevauge** [comment]
Hi @adesprez, thanks for your proposal!
Nowadays, most companies are using/are planning to use an orchestrator like Kubernetes/Swarm/Mesos to manage their deployments/runtime. Connecting Traefik to a CM tool may be useful to few users but I'm afraid that the use case is too limited.
I will close this one for now, and will reopen if more users ask for this kind of connectors in the future. 
Thanks again!
