### ISSUE TITLE
Kubernetes Documentation Examples Port Configuration

### ISSUE THREAD

**Issue by dtomcej** [containous/traefik#3348]
### Do you want to request a *feature* or report a *bug*?

Documentation Update

### What needs updating?

The kubernetes examples (https://docs.traefik.io/user-guide/kubernetes/) and (https://github.com/containous/traefik/tree/master/examples/k8s/traefik-ds.yaml) Have a nodeport service fronting a daemonset with hostports. This creates duplicate methods for accessing traefik, and is not clear for new users.

We should clean up the examples to keep the deployment/daemonset examples as close to each other as possible, and update the port configurations to be the same.

We should also make a note about hostports, and how they are not supported in production, and possibly a link to the k8s documentation.

**Comment by traefiker** [comment]
Closed by #3368.
