### ISSUE TITLE
Support per-namespace Kubernetes Ingresses

### ISSUE THREAD

**Issue by mgoodness** [containous/traefik#336]
Right now Traefik handles all ingresses in all namespaces. It might be desirable to have Traefik running in multiple namespaces, with a different configuration per namespace. This would be enabled by passing the namespace into the Traefik container as an environment variable using the downward API.

**Comment by ekozan** [comment]
linked to https://github.com/containous/traefik/issues/311

**Comment by errm** [comment]
I have had a quick bash at this, seems like quite a good strategy, and I quite like it.

It might also be desirable to allow an instance to handle ingresses for a number of namespaces... but then again that might be overkill...

**Comment by errm** [comment]
@mgoodness could this be closed now?

**Comment by mgoodness** [comment]
@errm Nice work! Shutting it down.
