### ISSUE TITLE
Feature Request - Notifications for security advisories

### ISSUE THREAD

**Issue by aabashkin** [containous/traefik#3369]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I'd like to request a way to receive notifications for security advisories / critical patches. Perhaps a mailing list and/or RSS feed?

**Comment by dtomcej** [comment]
Hello @aabashkin,

Containous and Traefik have a security mailing list for security issues and patches:

https://github.com/containous/traefik#mailing-lists

For this reason, I will be closing this issue.
