### ISSUE TITLE
Manage Nodes with many overlay networks

### ISSUE THREAD

**Issue by sebmoule** [containous/traefik#338]
Hi

I have a swarm cluster with containers that are mapped so several overlay networks.

When Traefik retrieve it's conf from the swarm master it concatene all the IP result that it won't works:

```json
   "backend-test": {
      "servers": {
        "server-seb_test_1": {
          "weight": 1,
          "url": "http://192.168.6.2192.168.8.2:80"
        }
      }
    },
```

my container have 2 ip 192.168.6.2 & 192.168.8.2

is there a way to specify traefik which network to use in this case somethink like **traefik.network** ?

```
    labels:
      - "traefik.backend=test"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:test.example.com"
      - "traefik.network=net_front"  
    networks:
      - net_front
      - net_back_api
      - net_back_tool

```

**Comment by vdemeester** [comment]
This is almost the same as https://github.com/containous/traefik/issues/229 :)

**Comment by sebmoule** [comment]
@vdemeester seams you right ;) should I close this one ?

**Comment by vdemeester** [comment]
@sebmoule yes but could you comment with the content of this issue :angel: Q

**Comment by sebmoule** [comment]
added int comment in #229 but don't know how to close this one..
