### ISSUE TITLE
ACME DNS-01 error: Error presenting token: Unexpected response code 'SERVFAIL'

### ISSUE THREAD

**Issue by EugenMayer** [containous/traefik#3396]
### What did you do?
Configure DNS-01 with cloudflare as provider for ACME challenges

### What did you expect to see?
validating the domain

### What did you see instead?

```
level=error msg="Unable to obtain ACME certificate for domains \"www.gateway.XXX\" detected thanks to rule \"Host:www.gateway.XXX\" : cannot obtain certificates: acme: Error -> One or more domains had a problem:\n[www.gateway.neptun.XXXX] Error presenting token: Unexpected response code 'SERVFAIL' for _acme-challenge.www.gateway.XXXX.\n"
```

```
dig www.gateway SOA

; <<>> DiG 9.10.3-P4-Debian <<>> www.gateway.XXXX SOA
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 20191
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;www.gateway.XXXXX. IN SOA

;; AUTHORITY SECTION:
XXXX.	1622	IN	SOA	lars.ns.cloudflare.com. dns.cloudflare.com. 2027911299 10000 2400 604800 3600

;; Query time: 5 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Sun May 27 20:44:52 CEST 2018
;; MSG SIZE  rcvd: 125
```

So the SOA record is no issue - i am using at public DNS server. I have no TXT records present at all and the domain i ask for has no DNS entry at all

```
dig www.gateway.XXX A | grep 'ANSWER'                                                                                                                                                [20:46:33]
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
```

Also using cloudflare with the usual API tokens set. Used `acmeLogging=true` and `logLevel=debug` but no additional informations other then 

```
time="2018-05-27T20:47:49+02:00" level=debug msg="Using DNS Challenge provider: cloudflare"
time="2018-05-27T20:47:49+02:00" level=debug msg="Delaying 10000000000 rather than validating DNS propagation now."
```

I am using `traefik 1.6.2` with the default ca-Server `time="2018-05-27T20:47:49+02:00" level=debug msg="https://acme-v02.api.letsencrypt.org/directory"`

i validated a couple of other domains successfully at some point. also with the very same domain just 

www.proxmox - same suffix.

### Output of `traefik version`:

```
traefik version                                                                                                                                                                                            [20:47:53]
Version:      v1.6.2
Codename:     tetedemoine
Go version:   go1.10.2
Built:        2018-05-22_03:19:06PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[acme]
  email = "ssl@XXXXX"
  storage = "/etc/traefik/internal/acme.json"
  entryPoint = "https"
  onHostRule = true
  acmeLogging = true
[acme.dnsChallenge]
  provider="cloudflare"
  delayBeforeCheck = 10
```

**Comment by EugenMayer** [comment]
Maybe also interesting, on a different traefik server, 100% same configuration, i could get the certificate for `www.gateway.YYYY` without issue, while its basically 99% the same suffix, just a different "servername" like <servername>.domain.tld

**Comment by EugenMayer** [comment]
@mmatur i would keep this open and link the issue on LEGO or you will get more request/issues like that - what do you think. I mean the problem is expressed in Traefik, it does not really help closing the issue if its inside a libarary or not - people will encounter this.

Seeing that we are waiting for a library issue to fix would be more interesting, i suppose.

Nevertheless i am with you, thats a LEGO bug, the possible issues are:

- https://github.com/xenolf/lego/issues/551
- https://github.com/xenolf/lego/issues/544

Its yet not clear which one is it ( or both )

**Comment by mmatur** [comment]
I am agree with your. I reopen this issue

**Comment by EugenMayer** [comment]
for anybody running into this and basically blocked by LEGOs implementation, use the `typetransparent` mode on your local DNS, not `transparent`

@mmatur for me, this issue can be close - you decide

**Comment by mmatur** [comment]
Thanks @EugenMayer for your feedback. I will close this issue.
