### ISSUE TITLE
 can not proxying http2 without HTTPS (for python-gRPC )

### ISSUE THREAD

**Issue by cczzff** [containous/traefik#3406]
The grpc server-side is written by Python. 
Use example from  https://github.com/grpc/grpc/example/python/helloworld
The server port is 50051
backend: "h2c://192.168.0.190:50051"

result: grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.CANCELLED, Received http2 header with status: 500)>

ps: proxying http2 without https on go-server is normal

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Træfik!

Issue templates help us help you by providing all necessary information.

Please edit your issue and use the available templates:

- [Feature request](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/Feature_request.md)
- [Bug report](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/Bug_report.md)

And remember: each time someone ignores the template, a cute little bunny dies.
<details>
<summary>#SaveTheCuteBunny :heart: :rabbit: :heart:</summary>

![southpark - estrella kill rabbit](https://user-images.githubusercontent.com/5674651/27143914-3cea7896-5130-11e7-81f8-02d8ac2da7a7.gif)

![southpark - estrella kill rabbit2](https://user-images.githubusercontent.com/5674651/27143924-49104c72-5130-11e7-82ae-ccedbd5dfa1c.gif)

</details>

**Comment by FrontMage** [comment]
Same here, but with go server.
Can u post your configuration file for traefik? @cczzff

**Comment by ldez** [comment]
Thanks for your interest in Traefik.

The support of h2c will be available in [v1.7](https://github.com/containous/traefik/pulls?q=is%3Apr+in%3Atitle+h2c+is%3Aclosed+milestone%3A1.7)

- v1.6 documentation: https://docs.traefik.io/v1.6/user-guide/grpc/
- Future v1.7 documentation: https://docs.traefik.io/master/user-guide/grpc/
