### ISSUE TITLE
Cannot exit after Ctrl+C

### ISSUE THREAD

**Issue by guotie** [containous/traefik#3435]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you expect to see?

process exit after ctrl+c

### What did you see instead?

program hanged infinited

```
^CINFO[2018-06-05T18:40:02+08:00] I have to go...                              
INFO[2018-06-05T18:40:02+08:00] Stopping server gracefully                   
DEBU[2018-06-05T18:40:02+08:00] Waiting 10s seconds before killing connections on entrypoint https... 
DEBU[2018-06-05T18:40:02+08:00] Waiting 10s seconds before killing connections on entrypoint http... 
DEBU[2018-06-05T18:40:02+08:00] Entrypoint http closed                       

DEBU[2018-06-05T18:40:12+08:00] Wait is over due to: context deadline exceeded
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

1.6.2

```
(paste your output here)
^CINFO[2018-06-05T18:40:02+08:00] I have to go...                              
INFO[2018-06-05T18:40:02+08:00] Stopping server gracefully                   
DEBU[2018-06-05T18:40:02+08:00] Waiting 10s seconds before killing connections on entrypoint https... 
DEBU[2018-06-05T18:40:02+08:00] Waiting 10s seconds before killing connections on entrypoint http... 
DEBU[2018-06-05T18:40:02+08:00] Entrypoint http closed                       

DEBU[2018-06-05T18:40:12+08:00] Wait is over due to: context deadline exceeded
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Linux Ubuntu 16.04

```toml
# (paste your configuration here)
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
(paste your output here)
```

**Comment by Skarlso** [comment]
Hi. Could you please elaborate in what way you were using Traefik? Did you just start it and tried to quit or way you using a special configuration of some sort?

**Comment by Skarlso** [comment]
Ping @guotie.

**Comment by timoreimann** [comment]
Please also describe whether you are running the Traefik binary directly or in a containerized format (and if so, which image you use).

**Comment by akvadrako** [comment]
I also have this issue. I'm running traefik in a docker container as a systemd service. So it sends SIGTERM to the process and sometimes it just outputs "Wait is over due to: context deadline exceeded" then hangs instead of exiting.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Slack workspace](https://traefik.herokuapp.com/) for more [community #support](https://traefik.slack.com/messages/C0CDT22PJ/).

**Comment by akvadrako** [comment]
How can I reopen it?
