### ISSUE TITLE
rancher integration

### ISSUE THREAD

**Issue by rawmind0** [containous/traefik#344]
Hi,

i made this repos to get a traefik integration with rancher. As rancher-metadata is not on your discovery backends, i made the integration with confd. 

https://github.com/rawmind0/alpine-traefik
https://github.com/rawmind0/rancher-traefik

Best regards,

**Comment by emilevauge** [comment]
@rawmind0 thanks :)
If you want to add Rancher support in Traefik, I would help with pleasure :)

**Comment by rawmind0** [comment]
@emilevauge, It would be very nice if we could do a full rancher integration.

I have confd templates to generate rules.toml, could you guide me a starting point to do it??

Thanks :)

**Comment by emilevauge** [comment]
@rawmind0 can you join us on [traefik slack](https://traefik.herokuapp.com/)? it will be easier ;)

**Comment by rawmind0** [comment]
http://rancher.com/traefik-active-load-balancer-on-rancher/ :)

**Comment by emilevauge** [comment]
@rawmind0 thanks a lot, great article :)

**Comment by fabiorauber** [comment]
Seeing native support for Rancher Metadata would be really awesome.

**Comment by ldez** [comment]
Now, Traefik has a native support for Rancher and Rancher Metadata. 😄
