### ISSUE TITLE
Configuring default value for traefik.docker.network

### ISSUE THREAD

**Issue by JoyceBabu** [containous/traefik#3449]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?
I was told from the Slack channel that it is not possible to define a default value for `traefik.docker.network` via toml configuration file.

I request you to add a new configuration parameter in the toml file for setting the default value for the docker network.

**Comment by nmengin** [comment]
Seems to be solved by #3471.

I close the issue.
