### ISSUE TITLE
did traefik support traefik.ingress.kubernetes.io/whitelist-useXForwardedFor in k8s ingress?

### ISSUE THREAD

**Issue by mdh67899** [containous/traefik#3453]
### Do you want to request a *feature* or report a *bug*?

treafik v1.6 support use ip white list to filter http request. [doc in here](https://docs.traefik.io/master/configuration/backends/kubernetes/)

<pre>
traefik.frontend.whiteList.sourceRange=RANGE 
traefik.frontend.whiteList.useXForwardedFor=true
</pre>

In k8s ingress, how to achieve it in k8s? there [doc](https://docs.traefik.io/master/configuration/backends/kubernetes/)  has no document to achieve useXForwardedFor 
<pre>
traefik.ingress.kubernetes.io/whitelist-source-range: "1.2.3.0/24, fe80::/16"
</pre>

### What did you expect to see?
which annotations be achieved use  x-forwarded-for ip to filter http request in k8s ingress?  thanks

**Comment by ldez** [comment]
It's a missing element in our documentation, it's `ingress.kubernetes.io/whitelist-x-forwarded-for: "true"`

**Comment by traefiker** [comment]
Closed by #3454.
