### ISSUE TITLE
Filtering Docker container without port

### ISSUE THREAD

**Issue by mithrandi** [containous/traefik#346]
I'm using overlay networks for my backends on Carina (Docker Swarm), so there is no globally mapped port (by design) as I only want the backends exposed to Traefik. Setting the `traefik.port` label would do what I want (I think), but unfortunately this does not override the "no ports" filter. Could this be changed?

**Comment by emilevauge** [comment]
@mithrandi are your container exposing ports in its Dockerfile ?

**Comment by mithrandi** [comment]
There are no ports "exposed" by the container at all (either via the Dockerfile / image or when creating the container). If I expose a random fake port with `--expose 12345` then that's enough to pass the first "filtering" check, and after that `traefik.port` takes effect.

At this point, I guess I'm not actually clear on what the expected relationship between Docker networks and `EXPOSE` / `--expose` is meant to be. I definitely don't want to *publish* the backend port; if I just expose it without ever creating any container links or using `-P`, it'll still be there in the container metadata for traefik to see so that should work, but I'm not sure if there's any other effects I need to worry about?

**Comment by mithrandi** [comment]
Reading further at https://docs.docker.com/engine/userguide/networking/work-with-networks/#linking-containers-in-user-defined-networks it seems like EXPOSEing the ports is in fact a sensible/expected thing, so I'm going to close this bug.
