### ISSUE TITLE
Add request body regex matcher

### ISSUE THREAD

**Issue by nuriel77** [containous/traefik#3464]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Add to "Matchers" ability to match regex in request body. Because request body length can be very large, perhaps only allow to inspect n first bytes.

**Comment by mmatur** [comment]
Hi @nuriel77,

First of all thanks for your interest in Træfik!

After discussing with the team, we think that it is not a good idea to manipulate body and add matcher on it.

For these reasons, we will be closing your issue.

Thanks
