### ISSUE TITLE
Manage entirely the TLS handshake

### ISSUE THREAD

**Issue by nmengin** [containous/traefik#3472]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

So far, for each HTTPS requests, Træfik checks internaly if a certificate provided dynamically or throught ACME exist.
If there is no certificate, Træfik let the GO HTTPServer implementation find a static certificates.

This behavior has some limitations and few issues are opened in relation with it.

I propose to check all the certificates internaly to manage entirely the behavior and the response.

This issue can solve #3293 #2874 and it can probably fix the flaky tests detected in ACME.

**Comment by dtomcej** [comment]
Could probably also solve https://github.com/containous/traefik/issues/3095 by allowing for a default

**Comment by dtomcej** [comment]
Would also be able to solve https://github.com/containous/traefik/issues/2118 too.

**Comment by dtomcej** [comment]
And by extension https://github.com/containous/traefik/issues/1814
