### ISSUE TITLE
Support versions of the https protocol in communication with the backend

### ISSUE THREAD

**Issue by riav** [containous/traefik#3495]
### Do you want to request a feature or report a bug?
Feature

### What did you expect to see?
The traefik does not currently support the version of the protocol https that the traefik communicates with the backend is set. In old systems (java 6 earlier than version 6_111)
only accept version 1.0, but traefik accesses the backend through protocol https 1.1/1.2, this forces a change in the backend, the update of java, but this is not always possible.

One way to make this option feasible was to have the traefik.protocol:"https" label come with the version:
Ex.:
traefik.protocol:"https:1.0"

**Comment by dtomcej** [comment]
Hello @riav 

Traefik uses the golang `crypto/tls` package to handle TLS and crypto (https://golang.org/pkg/crypto/tls/#pkg-constants). As you can see, there is a list of Ciphersuites that the package supports. Of these, 4 are TLS-1.0 compatible:
```
TLS_RSA_WITH_RC4_128_SHA
TLS_RSA_WITH_3DES_EDE_CBC_SHA
TLS_RSA_WITH_AES_128_CBC_SHA
TLS_RSA_WITH_AES_256_CBC_SHA
```

That being said, those ciphers are enabled by default, but are often disabled to increase security. It is not possible, or feasible to backport insecure crypto to support legacy uses.

As for the HTTP request, Traefik _should_ have no problems with handling `HTTP/1.0` requests/responses.

For these reasons, I will be closing this ticket.

If you would like to further discuss, please visit our slack channel: traefik.slack.com

Thanks!
