### ISSUE TITLE
Provide a way to allow connection by docker container name in whiteList.sourceRange or new configuration option.

### ISSUE THREAD

**Issue by Yivan** [containous/traefik#3514]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Actually, traefik.frontend.whiteList.sourceRange accept only IPs/IPs ranges.

It will be great to be able to restrict front end connection by container name too, as container ip are volatile and should usualy not be managed manually.

Use case:
Docker is limited to 31 networks maximum (overlay doesn't have this limitation but need swarm).
For each project (more than 31) we need to provide a connection between container of the same project.
Using proxy traefik is a solution as we can define which container can access to the backend, by restricting frontend with whiteList.sourceRange. Problem is we need to provide container ip... and using docker-compose we cannot know IP, just container name.
As container name resolve to IP, maybe it would be possible to use container name in traefik.frontend.whiteList.sourceRange, it will make restricting access more easy.

If needed a new configuration option could be added:
traefik.frontend.whiteList.container="mycontainer1,mycontainer2"

Thanks for reading this proposal.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Træfik!

Issue templates help us help you by providing all necessary information.

Please edit your issue and use the available templates:

- [Feature request](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/Feature_request.md)
- [Bug report](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/Bug_report.md)

And remember: each time someone ignores the template, a cute little bunny dies.
<details>
<summary>#SaveTheCuteBunny :heart: :rabbit: :heart:</summary>

![southpark - estrella kill rabbit](https://user-images.githubusercontent.com/5674651/27143914-3cea7896-5130-11e7-81f8-02d8ac2da7a7.gif)

![southpark - estrella kill rabbit2](https://user-images.githubusercontent.com/5674651/27143924-49104c72-5130-11e7-82ae-ccedbd5dfa1c.gif)

</details>

**Comment by geraldcroes** [comment]
Hi and thank you for your feature request.

The current design of whiteListing is indeed to accept IPs only.

In a docker environment, it would technically be possible to add container names to these, but we feel like it wouldn't be true whiteListing anymore, but ACL in disguise, which is a whole different topic.

I'll close the issue for now, but feel free to add your thoughts in the comments.

**Comment by Yivan** [comment]
@geraldcroes Thanks for your answer, I agree with you. I was thinking it like the Require directive from Apache (see: https://httpd.apache.org/docs/2.4/howto/access.html#host) which can handle ip or host.

So maybe it should be a new frontend config parameter, different than whiteList, only available for docker ? (or any container environment, like kubernetes, etc.) ? Something like:
`traefik.frontend.restrict.container="mycontainer1,mycontainer2"`
