### ISSUE TITLE
Did traefik have any plan to support calulate response status count by domain?

### ISSUE THREAD

**Issue by mdh67899** [containous/traefik#3530]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

In traefik server, we can get global response status count via `http://traefik_ip:traefik_dashbaord_port/health`

In my k8s production environment，We
have lots for domain,  and I want get response status count per domain by using  `http://traefik_ip:traefik_dashbaord_port/health?domain=www.test.com`

thanks

```console
$ curl -s http://127.0.0.1:8091/health | python -mjson.tool
{
    "average_response_time": "5.573789ms",
    "average_response_time_sec": 0.005573789,
    "count": 11,
    "pid": 52363,
    "status_code_count": {
        "200": 5,
        "302": 6
    },
    "time": "2018-06-25 17:15:40.776214247 +0800 CST m=+888938.628826285",
    "total_count": 104045479,
    "total_response_time": "161h5m27.584235569s",
    "total_response_time_sec": 579927.584235569,
    "total_status_code_count": {
        "200": 57639557,
        "204": 1912417,
        "206": 723,
        "301": 70,
        "302": 43632790,
        "304": 730561,
        "400": 15447,
        "401": 15,
        "403": 2222,
        "404": 12764,
        "405": 32,
        "500": 94816,
        "502": 308,
        "503": 4,
        "504": 3753
    },
    "unixtime": 1529918140,
    "uptime": "246h55m38.519252975s",
    "uptime_sec": 888938.519252975
}
```

**Comment by geraldcroes** [comment]
Hi and thank you for your interest in Traefik.

We have discussed your proposal, and we feel that it is not Traefik's job to compute these numbers.
 
We encourage you to enable [metrics](https://docs.traefik.io/configuration/backends/web/#metrics)) in Traefik so you can get the numbers you're looking for.

Let us know what you think.

**Comment by mdh67899** [comment]
thanks @geraldcroes
