### ISSUE TITLE
kubernete ingress support header rule annotation

### ISSUE THREAD

**Issue by xuzhiop** [containous/traefik#3543]
### Do you want to request a *feature* or report a *bug*?

Feature
 I can't found any annotation to set header rule , please add  header rule annotation to allow header rule route.
### What did you expect to see?
the annotation could be like  ingress.kubernetes.io/rule-header: Content-Type, application/json

**Comment by dtomcej** [comment]
Hello @xuzhiop,
Unfortunately the kubenetes ingress spec does not have any allowance for custom header based routing.

 https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource

If you require header based routing, you can do so using the file provider, and use service IPs as backend URLs. Note that this will  incurr an extra hop, as the service IP will be routed.

If you feel that header based routing should be part of the ingress spec, You would have to open a feature request with kubernetes, as that has to come from upstream.

You are not alone in wanting that feature as seen here (https://github.com/kubernetes/ingress-nginx/issues/2419). 

If header based routing _does_ become part of the ingress spec, we will support it completely.

Thanks!

**Comment by xuzhiop** [comment]
Hello @dtomcej 
Thanks for your reply
But I don't think  ingress spec can block my request.  why not set header rule by ingress annotation (not ingress spec)
Scenario is below:
We deploy two deployments for one application , One for production , one for gray test . In my idea, we want to rout request to application (both two deployments ) based on  host, and route to deployment based on header (we can set a special header to label gray user ) . In real network, it should be two  route, one to production deployment, one to gray deployment . And both routes should have header rule and host rule . If traefik can support header based routing with ingress annotation like  "traefik.ingress.kubernetes.io/rule-header: grayTag, gray" ,  I can carry out my idea convinently.

**Comment by omegarus** [comment]
+1

**Comment by devypt** [comment]
> The feature is published as part of version 0.21.0: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#canary
I've written a blog post https://www.elvinefendi.com/2018/11/25/canary-deployment-with-ingress-nginx.html showing how to use it with examples.


https://github.com/kubernetes/ingress-nginx/issues/2419#issuecomment-441613125

**Comment by mhball** [comment]
+1 on this, would be great to have support for header rules as annotations

**Comment by xiangkaiy** [comment]
If I use JavaScript to send an AJAX request to the backend server.
There is no Host Header in this AJAX request,
How do I route this AJAX request to the right microservice in my K8S cluster?
