### ISSUE TITLE
Integration test with Kubernetes e2e framework

### ISSUE THREAD

**Issue by yue9944882** [containous/traefik#3555]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Currently, we don't have an end-to-end test with Kubernetes provider. But fortunately, Kubernetes has already provided a complete e2e framework and it might save a lot of work if we build our integration test system above it. 😸

@timoreimann

**Comment by timoreimann** [comment]
Related: #1889

**Comment by timoreimann** [comment]
@yue9944882 this sounds very interesting -- what would it take to leverage the upstream e2e framework? I suppose some VMs running somewhere?

Do you know if it would be possible to run the tests locally as well?

**Comment by timoreimann** [comment]
Another question: how can we access the framework? is it part of client-go?

**Comment by yue9944882** [comment]
@timoreimann tricked. sadly, we can't use that framework unless we vendor the entire kubernetes repo. making use of e2e seems impossible.
