### ISSUE TITLE
"source IP" displayed in the "Recent HTTP Errors" section of the API dashboard

### ISSUE THREAD

**Issue by ryayon** [containous/traefik#3574]
### Do you want to request a *feature* or report a *bug*?

Hi,
I get a lot of scans of my different websites (such as /robots.txt, etc).
I would like to know the origin of these scans. 

### What did you expect to see?

I would like to know the origin of these scans. 
Moreover, I would like to be able to tune the column entries I can implement in the  "Recent HTTP Errors" section of the API Dashboard.

**Comment by ldez** [comment]
Hi, for more information, you must look at the access log.

https://docs.traefik.io/v1.6/configuration/logs/#access-logs
