### ISSUE TITLE
Traefik docker backend error

### ISSUE THREAD

**Issue by gdippolito** [containous/traefik#360]
The traefik container is logging few errors even if the service is apparently behaving correctly (the dashboard is available and the nodes are added to the default lb pool). 

**I have the following setup:**
Centos 7.2 
Docker 1.9.1
Traefik version: v1.0.0-beta.666

**Traefik configuration:**
port = ":80"
logLevel = "DEBUG"
[web]
address = ":8888"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "my.domain.com"
watch = true

**I have seen the following error message in the logs:**
`level=error msg="Docker connection error Error response from daemon: json: cannot unmarshal object into Go value of type []string, retrying in 58.133390694s`

What this error is about?

**Comment by vdemeester** [comment]
Hum, it might be an API version problem or the need to upgrade the engine-api used in traefik, I'll take a look :wink:

**Comment by hsablonniere** [comment]
Hey,

I have the same error message :

```
Docker connection error Error response from daemon: json: cannot unmarshal object into Go value of type []string, retrying in 1m4.240396564s
```

I have the error even when I don't have any other containers than Træfɪk.

It's a DigitalOcean machine with CoreOS. There's nothing wrong on my machine with a Docker 1.11.1.

Docker version :

```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   9894698
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   9894698
 Built:        
 OS/Arch:      linux/amd64
```

Docker info :

```
Containers: 3
Images: 15
Server Version: 1.9.1
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.3.6-coreos
Operating System: CoreOS 899.17.0
CPUs: 2
Total Memory: 1.958 GiB
Name: huitparfait
ID: O2SH:YLZZ:5KEV:6VAM:5IXJ:EMW2:ZI4F:UTG7:MU33:NIHR:ALVC:4KCI
```

**Comment by hsablonniere** [comment]
Great !!
