### ISSUE TITLE
Please add Windows based docker image

### ISSUE THREAD

**Issue by artisticcheese** [containous/traefik#3603]
There is seems to be already a solution available (https://github.com/StefanScherer/dockerfiles-windows/blob/master/traefik/Dockerfile). Can this be incorporated in official docker hub repo?

**Comment by beaudryj** [comment]
Please!!! 👍 💯  Would love to use this and saves @StefanScherer from having to maintain another one of his one million base images :p

**Comment by StefanScherer** [comment]
The easy part is the Dockerfile, but for Windows the more challenging part is to support all relevant Windows base images directly without Hyper-V isolation.

- microsoft/nanoserver:sac2016
- microsoft/nanoserver:1709
- microsoft/nanoserver:1803

Beginning with 1709 it is possible to bind mount the docker socket via the default named pipe. This makes it very interesting as running Traefik is much simpler now.
But also beginning with 1709 the Traefik binary does not work out of the box in nanoserver due to a missing netapi32.dll

More details about that see https://github.com/golang/go/issues/21867
It's a dependency in the glog that uses `user.Current()`.

My Docker image is built with an unofficial tool to build three images with only the one AppVeyor builder available which only can produce the sac2016 based image. See https://github.com/StefanScherer/dockerfiles-windows/blob/master/traefik/push.ps1 for the "dirty" details as I don't have a CI pipeline for all three Windows platforms.

**Comment by beaudryj** [comment]
Why not build else where and publish? Seems like a lazy excuse

**Comment by ldez** [comment]
We use the [official Docker image system](https://github.com/docker-library/official-images/) to publish our multi-platform official images.

This has many benefits for users and for us.

As @mmatur says, we (the Traefik team, especially @SantoDE and @dduportal) will work to add Windows images as soon as possible.

**Comment by artisticcheese** [comment]
@StefanScherer Does not this thing will fix all the issues once and forever https://blogs.msdn.microsoft.com/stevelasker/2018/07/16/acr-build-supports-windows-preview/

**Comment by StefanScherer** [comment]
@artisticcheese Looks promising 👍

**Comment by StefanScherer** [comment]
The official Docker images are built in a separate environment. Don't know if ACR can be used.

**Comment by dduportal** [comment]
Hello!
After a first discussion with @SantoDE , here is the the proposed action plan for this:

- [ ] Step 1: get a working build with nanoserver:sac2016 (easy, thanks to @StefanScherer !) and update it to latest Traefik 1.7.x (@SantoDE I've added this last "1.7.x" item, let me know if it is ok or if we want to make it a separate step)
- [ ] Step 2: find a way to get it integrated into the docker-library using the following resources:
  * https://github.com/docker-library/official-images/#multiple-architectures 
  * https://github.com/docker-library/official-images/blob/master/NEW-IMAGE-CHECKLIST.md
  * https://github.com/docker-library/official-images/blob/master/library/traefik
- [ ] Step 3: get the other images supported, based on @StefanScherer 's feedback in https://github.com/containous/traefik/issues/3603#issuecomment-404329465


=> Some "raw" thoughts about these steps:

* Step 1: We need to think a way to integrate the "Windows" build in the Traefik's CI Pipeline. 
  - @StefanScherer work is awesome, and the "request packet host as a service" could be a good one to start with. I'm afraid of the build time though: It would be interesting to measure that and parallelize steps as much as possible to avoid slowing down the main CI pipeline.
  - Thanks @artisticcheese for raising https://blogs.msdn.microsoft.com/stevelasker/2018/07/16/acr-build-supports-windows-preview/ . We'll check this as soon as it would be available: could be a great solution to improve feedback time in the pipeline and leverage cost for building such an image.

* Step 2: 
  - We need to agree on the docker image tag's convention, taking in account we'll have different declination of the base OS. Here is how the golan image is doing: https://github.com/docker-library/official-images/blob/master/library/golang#L68 , a general convention "version-os[-osversion]", which could be coherent with the alpine declination of the current Traefik image: `1.7-nanoserver-sac2016`, `1.7-nanoserver-1709`, `1.6-nanoserver-1709`, etc.

* Step 3: we need to keep track of https://github.com/golang/go/issues/21867 to know when glog would be updated, to update the dependency in Traefik.

**Comment by StefanScherer** [comment]
@dduportal Thanks. :-)

The windows image should be published to `winamd64/traefik:v1.7.0-nanoserver-sac2016`.

And add it to the manifest list

```
$ docker run --rm mplatform/mquery traefik
Image: traefik
 * Manifest List: Yes
 * Supported platforms:
   - linux/amd64
   - linux/arm/v6
   - linux/arm64/v8
   - windows/amd64:10.0.14393.2363
```

PS: The mongo and golang images ( `docker run --rm mplatform/mquery golang` ) already have three windows platforms listed. Maybe @tianon can give us more insights how you can use this CI infrastructure to build Windows images as well. :-)

**Comment by SantoDE** [comment]
It's alright @dduportal :) Makes sense as 1.7 is in RC already anyways.

**Comment by dduportal** [comment]
@SantoDE you can find some initial work here to start integrating AppVeyor (a tradeoff between packet host and Azure to build Windows container). It is targeted at `microsoft/nanoserver:sac2016`, as first version and tries to follow existing Traefik Docker image structure. It is inspired a lot from @StefanScherer 's work (thanks again!)

- Code: https://github.com/dduportal/traefik-library-image/tree/initial-windows-docker-image
- CI: https://ci.appveyor.com/project/dduportal/traefik-library-image

**Comment by dduportal** [comment]
Hello @StefanScherer , I am not sure on how should we publish the image under winamd64 ? 
I was not able to find any information on https://hub.docker.com/u/winamd64/ neither on https://github.com/docker-library/official-images#architectures-other-than-amd64 .

**Comment by dduportal** [comment]
@seal-ss You're initial assumption was right: we would want to have the image built by Docker's infrastructure. Now I understand better: having it built by Janky will push it to winamd64 automatically, with no action required from us. Nice !

The build step done by ourselves is more a validation process. It is not aimed at being pushed by ourselves.

Thanks for the quick answer!

**Comment by artisticcheese** [comment]
@dduportal Yes, this is in fact the ONLY image I can run (nanoserver ltsc)

**Comment by dduportal** [comment]
Thanks for the feedback @artisticcheese , this is awesome.

A quick note about the PR linked on my previous comment which had been closed.
It was missing 2 elements:

- Træfik's Pull Requests against the [Docker's official-library repository](https://github.com/docker-library/official-images/blob/master/library/golang#L89) are generated by an internal bot (automation FTW!), and I was not aware of this 
  * [] Bot has to be updated
  * [] This information has to be documented (to be added into https://github.com/containous/traefik-library-image/blob/master/CONTRIBUTING.md)

- A discussion with some maintainers was required to validate the tags:
  * On one hand, there is a convention with some images (as Golang) which embed both windows base image's mainline (`windowsservercore` or `nanoserver`), and the version (`ltsc`, `sac2016`, etc.). But this generate very very long tags.
  * On the other hands, Træfik's official image based on Alpine Linux is not specifying the version: it assumes "always latest working stable base os" to avoid complexity of long tags (as the maven official image...).
  * After discussing and checking carefully the golang's official image, it appears that my first assumption was too light: both kind of tags exists: https://github.com/docker-library/official-images/blob/master/library/golang#L133 and https://github.com/docker-library/official-images/blob/master/library/golang#L134.
  * Decisions is made to have the following tags:
    - `v.1.7.0-rcX-nanoserver-sac2016`
    - `v.1.7.0-rcX-nanoserver`
    - `1.7.0-rcX-nanoserver-sac2016`
    - `1.7.0-rcX-nanoserver`
    - `v.1.7-nanoserver-2016`
    - `v.1.7-nanoserver`
    - `1.7-nanoserver-sac2016`
    - `1.7-nanoserver`
    - `maroilles-nanoserver-sac2016`
    - `maroilles-nanoserver`

- Please note the image should land with the next Release Candidate

cc @emilevauge @mmatur @vdemeester

**Comment by dduportal** [comment]
For followers of this issue, status update:

- The Containous' internal bot had been updated to generate the Windows tags.
- It has been documented here: https://github.com/containous/traefik-library-image/pull/33 (just a few sentences to give awareness)
- The upcoming 1.7.0-rc3 will have its first nanoserver image, unless I messed up and need to fix the metatdatas (in this case, you'll have to wait for the next rc :) ).

**Comment by dduportal** [comment]
The release `1.7.0-rc3` is here with its windows declination 🎆 

You can now `docker run traefik:maroilles-nanoserver` if you want!
All tags are visible on the DockerHub: https://hub.docker.com/r/library/traefik/tags/ .

For What It's Worth, there is an upcoming tiny update which will remove the 2 `VOLUME` definitions (and internal tooling with no user visible change): https://github.com/containous/traefik-library-image/pull/34 

I am closing this issue now. Feel free to open new issues if you encounter problems with this new image declination.
