### ISSUE TITLE
Support more than one docker tcp:// unix:// endpoints. (mixed swarm/non-swarm providers)

### ISSUE THREAD

**Issue by systemmonkey42** [containous/traefik#3623]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I would like to add a number of docker hosts to traefik, and have it proxy for them.

Traefik sites in a front-end network with tcp access to multiple developer and test environments (which are isolated from each other).  I would like to tell Traefik about each of the environments and have it manage all forwarding from a single public IP.

The current solution is to manage a config or key/value store and add each endpoint manually.

(I have a suspicion that I could have an agent per host/swarm and have it update a key/value store which a central traefik instance picks up on, but that is beyond anything I can imagine constructing.)

**Comment by ldez** [comment]
Duplicate of #182

**Comment by systemmonkey42** [comment]
So it is.  and its been languishing since 2016, so I expect I'll need to find an external solution.

Thanks
