### ISSUE TITLE
Backend protocol selection for Kubernetes provider

### ISSUE THREAD

**Issue by alexleigh** [containous/traefik#3641]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

With 1.7.0 we have the new h2c backend protocol. To support h2c backends with the Kubernetes provider, we need some way to specify which backend protocol to use in the Kubernetes ingress configuration. Perhaps a new Kubernetes annotation can be added to allow the backend protocol to be explicitly selected?

**Comment by SantoDE** [comment]
Hey @alexleigh, 

I did put up PR #3648 to address this issue :)

**Comment by alexleigh** [comment]
TYVM!

**Comment by traefiker** [comment]
Closed by #3648.
