### ISSUE TITLE
marathon traefik.backend=foo seems broken

### ISSUE THREAD

**Issue by kbroughton** [containous/traefik#366]
If i add this to labels in a marathon .json job

traefik.backend=k4b4-mantl-worker-001.example.com

 level=error msg="Error loading new configuration, aborted Undefined backend: backendk4b4-mantl-worker-001.example.com"

either the error message is formatted wrong, or the value is concatenated badly.

If it is just badly formatted error, how do I make k4b4-mantl-worker-001.example.com defined when k4b4-mantl-worker-001.node.consul is the default value?

**Comment by emilevauge** [comment]
`traefik.backend` cannot ne used to change the backend url ;)
It seems more logical to change your DNS settings here, to match your needs.
Can I close this one?

**Comment by kbroughton** [comment]
Yes.
However, i would suggest changing the docs to be more clear.  foo suggests it can be any old thing.  If i understand right, it should be 1 or 2 if there are multiple backends.

https://docs.traefik.io/toml/
traefik.backend=foo: assign the application to foo backend

If you explain how to submit PRs for docs I can contribute.
However, i don't see these docs at
https://github.com/containous/traefik/tree/master/docs

**Comment by emilevauge** [comment]
That would be great! You can find contributing docs here: https://github.com/containous/traefik/blob/master/.github/CONTRIBUTING.md :)
