### ISSUE TITLE
Debug Logs should not private certificates 

### ISSUE THREAD

**Issue by drubin** [containous/traefik#3669]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

When I start traffic with traefik with `--loglevel=DEBUG` traefik logs all information it gets back from the k8s in the line `Configuration received from provider kubernetes which contain the json`  contains private certs data as well from ingress tls secret's.

### What did you expect to see?

Logs that were safe to share and free of my private SSL certs. I would like traefik to never dump my private certificates into standard out. Which is generally pushed to external log collection like ELK or even a 3rd party

### What did you see instead?

Traefik dumping my private SSL certs to standard out. Which would be fine if I wasn't running in kubernetes which pushes all logs to our log collector. 

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
v1.7.0-rc2
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

na

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

this is the exact problem, the logs are impossible to share because they contain secret data.

**Comment by traefiker** [comment]
Closed by #3665.

**Comment by traefiker** [comment]
Closed by #3788.
