### ISSUE TITLE
DNS TTL honoring

### ISSUE THREAD

**Issue by Rowern** [containous/traefik#3687]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Here is our setup:

       +---------------+         +---------------+         +---------------+       +---------------+
       |               |         |               |         |               |       |               |
       |               |         |               |         |               |       |               |
       |      ALB      +-------> |    Traefik    +-------> |      ALB1     +-----> |      App      |
       |               |         |               |         |               |       |               |
       |               |         |               |         |               |       |               |
       +---------------+         +---------------+         +---------------+       +---------------+

                                                           +---------------+       +---------------+
                                                           |               |       |               |
                                                           |               |       |               |
                                                           |      ALB2     +-----> |      App      |
                                                           |               |       |               |
                                                           |               |       |               |
                                                           +---------------+       +---------------+

What is important is:

 - One backend that points to app.local.blabla.com
 - ALB1 has a A record (aws route53) of app.local.blabla.com with a weight of 100 (multiple IPs)
 - ALB2 has a A record (aws route53) of app.local.blabla.com with a weight if 0 (multiple IPs)

Our problem is when we deploy a new version (behind ALB2).

1. We deploy the code
2. We change the weight from ALB1 to ALB2 (so now when we do a DNS request to app.local.blabla.com we get the IPs of ALB2)
3. We delete the APP behind ALB1.

### What did you expect to see?

No errors as the new app was ready behind ALB2.

### What did you see instead?

503 pages as traefik kept on using the old IPs of ALB1.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.6.5
Codename:     tetedemoine
Go version:   go1.10.3
Built:        2018-07-10_03:52:30PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

We are on AWS

```toml
[backends]
  [backends.ark_front]
    [backends.ark_front.servers.one]
    url = "http://app.local.blabla.com"
```

To note, before switching to traefik we used nginx and it was possible to have nginx re-resolve the proxy_pass host on each request.

**Comment by Rowern** [comment]
Is there a setting to tell traefik to resolve a backend on all requests, or override the DNS ttl of the resolved value for the backend?

**Comment by dduportal** [comment]
Hi @Rowern ! Thanks you for your interest in Træfik, and for this detailed feedback.

As Træfik is using the Golang's embedded DNS client, it might be a delegated issue.
For your information, Træfik does not have any feature as the Nginx's "custom domain name resolution".

However, we would need more information to help us reproducing the issue and understanding what is going on:

- How/Where is Træfik is running exactly?
  * Is it inside a Docker container? If yes, what is the base OS used inside this image, and what are the packages (name and version) implementing dns clients?
  * If it is not using Docker, what is the underlying Operating system (and same question for the DNS-utils or equivalent packages)?
- Do you have any custom DNS or are you using the one provided by Route53?
- Could you give us results of the `dig` command when you see the issues on all ALBs (the master one, and ALB1 / ALB2) to help us checking the DNS specificities
- Last question: do you have the same behaviour when using Træfik version 1.7.0-rc2?

Thanks in advance for you help investigating this behaviour!

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Slack workspace](https://traefik.herokuapp.com/) for more [community #support](https://traefik.slack.com/messages/C0CDT22PJ/).

**Comment by souphan-adsk** [comment]
Would it be possible that it's related to the following lines?
https://github.com/containous/traefik/blob/v1.7/hostresolver/hostresolver.go#L36-L38
If it is, it would be great to have the value configurable for this situation.
