### ISSUE TITLE
traefik 1.7.0-rc2 does not enable prometheus metrics by default

### ISSUE THREAD

**Issue by arno01** [containous/traefik#3691]
Hello,

this bug is similar to https://github.com/containous/traefik/issues/2755 

According to the traefik CLI it says the prometheus metrics should be available by default:

```
/ # traefik --help |grep prometheus
    --metrics.prometheus                          Prometheus metrics exporter type             (default "true")
    --metrics.prometheus.buckets                  Buckets for latency metrics                  (default "[0.1 0.3 1.2 5]")
    --metrics.prometheus.entrypoint               EntryPoint                                   (default "traefik")
    --web.metrics.prometheus                      Prometheus metrics exporter type             (default "false")
    --web.metrics.prometheus.buckets              Buckets for latency metrics                  (default "[0.1 0.3 1.2 5]")
    --web.metrics.prometheus.entrypoint           EntryPoint                                   (default "traefik")
```

However it is not:

```
# curl -X GET traefik:8080/metrics
404 page not found
```

- traefik version

```
/ # traefik version
Version:      v1.7.0-rc2
Codename:     maroilles
Go version:   go1.10.3
Built:        2018-07-17_12:42:38PM
OS/Arch:      linux/amd64
```

- /metrics are working only if I set the following block in ``traefik.toml`` file:

```
# Metrics definition
[metrics]
  # To enable Traefik to export internal metrics to Prometheus
  [metrics.prometheus]
    # Name of the related entry point
    entryPoint = "traefik"

    # Buckets for latency metrics
    buckets = [0.1,0.3,1.2,5.0]
```

**Comment by emilevauge** [comment]
Linked to https://github.com/containous/flaeg/pull/35 & https://github.com/containous/flaeg/pull/36

**Comment by ibexmonj** [comment]
this still doesnt work for me even on latest traefik image. straight up 404's

**Comment by ldez** [comment]
Prometheus is not enable by default, the CLI help have a bug with some boolean value: it display `true` instead of `false`.

**Comment by diogopms** [comment]
Hi team, I've using version traefik V1.7.24 and I can't get working with prometheus.
Do you know if it's still an issue?
Thanks

**Comment by diogopms** [comment]
Hi, I'm version traefik V1.7.24 and I can't get working with Prometheus.

The "/metrics" returns always 404.

Do you know if it's still an issue?
Thanks

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Community Forum](https://community.containo.us/).
