### ISSUE TITLE
alpine 3.8

### ISSUE THREAD

**Issue by FernandoMiguel** [containous/traefik#3692]
Feature

traefik 1.7 upgrade alpine images to v3.8

**Comment by FernandoMiguel** [comment]
I'm pretty sure I wrote a description....
Humm

**Comment by FernandoMiguel** [comment]
there you, description fixed

**Comment by FernandoMiguel** [comment]
@ldez want to reconsider?

**Comment by mmatur** [comment]
Fixed by https://github.com/containous/traefik-library-image/pull/35
