### ISSUE TITLE
Documentation no longer available through https://docs.traefik.io/

### ISSUE THREAD

**Issue by jcgleissner** [containous/traefik#3737]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
I tried to access https://docs.traefik.io/

### What did you expect to see?
I expected to see the documentation.

### What did you see instead?
A 404 Message.

Cache clears and different browsers, or access points did not resolve the issue.

Started arround 13:00 GMT

### Output of `traefik version`: (_What version of Traefik are you using?_)
-

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
-

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)
-

**Comment by ldez** [comment]
I'm on it

**Comment by ldez** [comment]
Problem fixed

**Comment by jcgleissner** [comment]
Thanks for the quick resolution.
