### ISSUE TITLE
PathPrefixStrip that ends with `/` causes `400 bad request`

### ISSUE THREAD

**Issue by AlmogBaku** [containous/traefik#374]
Using `PathPrefixStrip` that ends with a slash causes errors:

I.E:

```
PathPrefixStrip:/weather/v1/
```

Now, when requesting:
1. `GET example.com/weather/v1/` -> works properly
2. `GET example.com/weather/v1/another-endpoint` -> throws `400 bad request`, and the end-service doesn't even get to handle it.

**Comment by christianhuening** [comment]
Also true for `PathPrefixStrip:/` which is immediately faulty and makes the controller fall back to "PathPrefix" as default rule. Problem is I want to host the main UI of my app on <ip/hostname>/ and give access to REST services on <ip/hostnam>/somePath, which does not work atm

**Comment by ldez** [comment]
Closed by #1638, in the version 1.3.0-rc3.
