### ISSUE TITLE
Allow for multiple entry points on the same address

### ISSUE THREAD

**Issue by trajano** [containous/traefik#3746]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Allow for multiple entry points on the same address *as long as only one is active for a service*.  For example:

    - "--entryPoints=Name:https Address::443 Compress:true TLS"
    - "--entryPoints=Name:internal Address::443 Compress:true TLS CA:/ca.pem CA.Optional:false"

When the service being requested has specified the entrypoint `internal` it should require a Client Certificate.

**Comment by geraldcroes** [comment]
Hi and thanks for your interest in Traefik!

We don't think that the feature you're looking for belongs to the entryPoints.

We think that a new rule on the frontends would be a better fit for your need.

We’ll close this issue, but feel free to add a new proposal taking the above into consideration.

**Comment by trajano** [comment]
Does that capability to do it via frontend rules already exist or should I open up a new proposal taking the above into consideration?
