### ISSUE TITLE
LE certificate renewal issue

### ISSUE THREAD

**Issue by HitkoDev** [containous/traefik#3750]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

- have Traefik acquire LE certificate for a backend with multiple domains (i.e. `Host:domain1.com,domain2.com,www.domain1.com`)
- remove `domain2.com` from the backend (new rule is `Host:domain1.com,www.domain1.com`)

### What did you expect to see?

After 3 months, Traefik successfully obtains new LE certificate for the backend

### What did you see instead?

Traefik tries to validate the original set of domains (`domain1.com,domain2.com,www.domain1.com`) instead of the current set of domains (`domain1.com,www.domain1.com`), and fails because `domain2.com` is no longer available.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
1.6, 1.7, possibly earlier versions as well
```

**Comment by nmengin** [comment]
Duplicate #3376
