### ISSUE TITLE
Use docker swarm/config as a kv-store

### ISSUE THREAD

**Issue by trajano** [containous/traefik#3759]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

One thing to note, this is only for storing the acme data.  Not the full config which should just be replicated as command parameters in the yml.

Rather than setting up another KV store inside docker swarm environment.  Why not just use `docker config` APIs to actually get and store configurations assuming the instance has `/var/run/docker.sock` mounted.

Using `/proc/self/cgroup` will allow you to get the ID of the container https://stackoverflow.com/questions/20995351/docker-how-to-get-container-information-from-within-the-container#25729598

then use service labels to update the "current config" to use.  Only service labels are mutable in Docker services.

So what I am thinking is one of the labels designates a node that is the "master" which is responsible for the updates.  If it detects that no node is the traefik master (i.e. the container ID designated is no longer running) it will elect another one automatically.

The update process does the following only on the master

1. let [config-uid] be a unique id for the configuration data
2. let [old-config-uid] be the ID for the current configuration data which is the label "config.uid".  Can be nil
3. create config [config-uid] with the acme data
4.  set the label "config.uid" to [config-uid]
5. delete config [old-config-uid]
6. trigger a `docker service update --force ` for the nodes
7. once stable reelect the master (since all the containers are restarted).

**Comment by mmatur** [comment]
Hi  @trajano,

First of all thanks for your interest in Træfik.

Unfortunately I will close this issue because this is something that we don't want to do due to a security concerns.

Today Træfik use the docker socket to watch events in read only. And we don't want to give write access to traefik on the docker socket.
