### ISSUE TITLE
Multiple SSL certificates assigned to different frontends?

### ISSUE THREAD

**Issue by distributorofpain** [containous/traefik#376]
Just wondering if it is possible to have and assign mutiple certs.

My working setup. I have a wildcard certificate for "*.apps.mydomain.io"  I would like to have a single cert ( one of the advanced certs, like a bank has ).  The single cert would be for "ui.apps.mydomain.io".  So i would have two in place, one for a single sub domain and a wild card for the rest of the domains.

Could i just add the other cert first and then have the wild card second, like the SNI example?
```
defaultEntryPoints = ["http", "https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
        CertFile = "/etc/traefik/certs/host.cert"
        KeyFile = "/etc/traefik/certs/host.key"
```

**Comment by emilevauge** [comment]
Yes, it should work :)

**Comment by ayaz** [comment]
@distributorofpain Would you be so kind as to share an example of how you managed to do this? I am unable to find documentation on how to use multiple SSL certificates with Traefik. Thank you.

**Comment by distributorofpain** [comment]
I never got around to implementing it.  We have since switched to mesosphere which uses haproxy.

This is what i found originally in the documents:

```
defaultEntryPoints = ["http", "https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      CertFile = "integration/fixtures/https/snitest.com.cert"
      KeyFile = "integration/fixtures/https/snitest.com.key"
      [[entryPoints.https.tls.certificates]]
      CertFile = "integration/fixtures/https/snitest.org.cert"
      KeyFile = "integration/fixtures/https/snitest.org.key"
```
which is from here:  https://docs.traefik.io/user-guide/examples/#http-https-with-sni  

SNI is the ability to do named endpoints... E.G. like the way IIS uses host header redirection, where its based on the name
