### ISSUE TITLE
Traefik ingress controller fails to communicate to kubernetes api

### ISSUE THREAD

**Issue by zencircle** [containous/traefik#3766]
I am trying to install traefik controller on Kubernetes 1.10.6 Framework on DCOS/Mesos
Kubernetes is enabled with RBAC

```
E0816 04:28:56.619017       1 reflector.go:205] github.com/containous/traefik/vendor/k8s.io/client-go/informers/factory.go:86: Failed to list *v1.Service: Get https://10.100.0.1:443/api/v1/services?limit=500&amp;resourceVersion=0: dial tcp 10.100.0.1:443: i/o timeout
E0816 04:28:56.620215       1 reflector.go:205] github.com/containous/traefik/vendor/k8s.io/client-go/informers/factory.go:86: Failed to list *v1.Endpoints: Get https://10.100.0.1:443/api/v1/endpoints?limit=500&amp;resourceVersion=0: dial tcp 10.100.0.1:443: i/o timeout
E0816 04:29:27.619201       1 reflector.go:205] github.com/containous/traefik/vendor/k8s.io/client-go/informers/factory.go:86: Failed to list *v1beta1.Ingress: Get https://10.100.0.1:443/apis/extensions/v1beta1/ingresses?limit=500&amp;resourceVersion=0: dial tcp 10.100.0.1:443: i/o timeout
```
### What did you do?
Followed instruction mentioned here and deployed  traefik ingress controller
https://docs.traefik.io/user-guide/kubernetes/

Further debugging.
I copied the Kubernetes generated token from the ingress controller to a sample pod in kub-system namespace and was able to connect to kubenetes-api
```
/ # ls -l /var/run/secrets/kubernetes.io/serviceaccount/..data/token 
-rw-r--r--    1 root     root           928 Aug 16 03:55 /var/run/secrets/kubernetes.io/serviceaccount/..data/token

curl -k -H "Authorization: Bearer $token" https://10.100.0.1/version
{
  "major": "1",
  "minor": "10",
  "gitVersion": "v1.10.6",
  "gitCommit": "a21fdbd78dde8f5447f5f6c331f7eb6f80bd684e",
  "gitTreeState": "clean",
  "buildDate": "2018-07-26T10:04:08Z",
  "goVersion": "go1.9.3",
  "compiler": "gc",
  "platform": "linux/amd64"
```

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
/ # traefik version
Version:      v1.6.5
Codename:     tetedemoine
Go version:   go1.10.3
Built:        2018-07-10_03:54:03PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
```       
 args:
        - --api
        - --kubernetes
        - --insecureskipverify 
        - --logLevel=DEBUG
```

RHEL 7, DCOS 1.11.3, Kubernetes 1.10.6, Docker-ee 1.7
Note: I am not using Traefik as DCOS app, instead I am using Traefik within Kubernetes deployed on DCOS

Similar issue
https://github.com/containous/traefik/issues/484
https://github.com/containous/traefik/issues/486

Note: Traefik is not routing traffic either.

**Comment by zencircle** [comment]
[tf-full.txt](https://github.com/containous/traefik/files/2292423/tf-full.txt)

**Comment by mmatur** [comment]
Hi @zencircle,

Thanks for your interest in the project. 

I can see in your `Deployment` that your are using `traefik:alpine` docker image. 
Could you please try to ssh into traefik container and try your curl request 
```console
$ curl -k -H "Authorization: Bearer $token" https://10.100.0.1/version
```

You issue seems related to a network communication problem. Maybe due to your RBAC policies. 

In your file `tf-full.txt` I can not see the service account definition.

**Comment by zencircle** [comment]
[
[tf-role.yaml.txt](https://github.com/containous/traefik/files/2295373/tf-role.yaml.txt)
](url)

**Comment by zencircle** [comment]
```
/ # curl -v --trace-time -k https://10.100.0.1/version
02:14:03.634097 *   Trying 10.100.0.1...
02:14:03.634153 * TCP_NODELAY set
02:16:10.871123 * connect to 10.100.0.1 port 443 failed: Operation timed out
02:16:10.871178 * Failed to connect to 10.100.0.1 port 443: Operation timed out
02:16:10.871212 * Closing connection 0
curl: (7) Failed to connect to 10.100.0.1 port 443: Operation timed out
```
Custom image with curl
containers:
      - image: zencircletech/docker-repo:traefik-curl

Correct, it turns out to be a Networking Issue. 

I am trying to run Traefik on Kubernetes which is deployed on DCOS
As per Mesosphere documentation Ingress controller is suppose to be installed on the public node. 
https://docs.mesosphere.com/services/kubernetes/1.2.1-1.10.6/ingress/

DCOS/Kubernetes networking is blocking communication between pods-running-on-public-node to kubernetes-api which is internal
Once I moved traefik pod to a private-node, communication to kubernetes-api was successful

**Comment by mmatur** [comment]
Hi @zencircle,

I think you should expose the Kubernetes API to allow container running in public agent to communicate with the Kubernetes API.

I will close this issue because I think that the question is answered.

Please feel free to continue the discussion on Slack workspace
