### ISSUE TITLE
potential memory leak in kubernetes ingress backend

### ISSUE THREAD

**Issue by nlf** [containous/traefik#377]
@emilevauge and i have talked about this in slack as well, but it appears that when using the kubernetes ingress backend there is a slow memory leak.

a container configured to use kubernetes but with no traffic directed to it and no other configuration steadily consumes more memory over time until it finally runs out and crashes, often with this error:

```
time="2016-05-16T02:20:21Z" level=error msg="Error watching kubernetes events: failed to create watch: failed to do watch request: GET \"https://172.17.0.1:443/apis/extensions/v1beta1/ingresses?watch&resourceVersion=2467988\": Get https://172.17.0.1:443/apis/extensions/v1beta1/ingresses?resourceVersion=2467988&watch=: dial tcp 172.17.0.1:443: connect: cannot assign requested address"
time="2016-05-16T02:20:21Z" level=fatal msg="Cannot connect to Kubernetes server failed to create watch: failed to do watch request: GET \"https://172.17.0.1:443/apis/extensions/v1beta1/ingresses?watch&resourceVersion=2467988\": Get https://172.17.0.1:443/apis/extensions/v1beta1/ingresses?resourceVersion=2467988&watch=: dial tcp 172.17.0.1:443: connect: cannot assign requested address"
```

which seems to imply that sockets may be leaking as well.

**Comment by errm** [comment]
I think I am seeing this too.

I am limiting traefik to 256Mi and its getting killed every 4 or 5 minutes.

Is there anything I can do to help track this down....
