### ISSUE TITLE
own SSL certificate - traefik with rancher

### ISSUE THREAD

**Issue by mkoczorowski** [containous/traefik#3772]
I have a service deployed in rancher along with rancher traefik.
Everything plays nicely but I cant get my own certificates to woek. Only the acme ones.

labels on the service:
```
traefik.acme = false
traefik.enable = true
traefik.entryPoints.https.tls.certificates.certFile = /opt/traefik/certs/cert.crt (files are present in traefik container)
traefik.entryPoints.https.tls.certificates.keyFile = /opt/traefik/certs/key.crt
traefik.frontend.headers.SSLRedirect = true
```

### What did you expect to see?
I would expect my cert was used for https

### What did you see instead?
Traefik does not use given certificate

**Comment by dduportal** [comment]
Hello @mkoczorowski !

Thanks for you interest in the project.

Based on your feedback, it appears that some of the labels you are providing are not listed in the documentation (cf. https://docs.traefik.io/configuration/backends/rancher/#labels-overriding-default-behavior ): `traefik.entryPoints.https.tls.certificates.certFile` and `traefik.entryPoints.https.tls.certificates.keyFile`.
It explains why the certificate are not taken in account.

You should use the entrypoint definitions to specify your certificates as in https://docs.traefik.io/basics/#entrypoints .

I am closing the issue, do not hesitate to ask help on our Slack Channel at https://slack.traefik.io/ if you need help to configure.

Have a nice day!

**Comment by nitrique** [comment]
+1

same needs here
editable configuration only on rancher labels

Thanks
