### ISSUE TITLE
acme.json don't update when restart traefik with new backend

### ISSUE THREAD

**Issue by seedinho** [containous/traefik#3789]
Bug

### What did you do?

I have a docker-compose with traefik, multiple backend and let's encrypt for SSL. That work correctly. I can go to my differents front in https and i have cert in acme.json file. No problems.

Recently, i add a new service in a docker-compose file. i configure the traefik.toml like the other services. But when i restart traefik and up my new backend, my new website work without SSL and the acme.json are not updated. 
I try to delete the acme.json file but that don't work. 

### What did you expect to see?

I want to go to my new website in https mode and i want to see the cert in the acme.json.

### What did you see instead?

I can see the new website in insecure mode and the acme.json file are not updated (same before update docker-compose.yml)

### Output of `traefik version`: (_What version of Traefik are you using?_)

Version:      v1.6.5
Codename:     tetedemoine
Go version:   go1.10.3
Built:        2018-07-10_03:54:03PM
OS/Arch:      linux/amd64

ps: sorry for my english...

**Comment by nmengin** [comment]
Hello @seedinho ,

Many thanks for your interest in the project.

Can you give us more information about your configuration (Træfik TOML file, docker-compsoe file) and your logs in `DEBUG` mode please?

**Comment by seedinho** [comment]
tks for the response, 
i resolve my probleme with the help of Idez (via the traefik slack). It's not a bug but a problem of configuration. I close this.
