### ISSUE TITLE
Parsing error for configuration provided by kubernetes

### ISSUE THREAD

**Issue by kalise** [containous/traefik#3803]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
Configured Traefik as ingress controller for kubernetes.
Enabled forward authentication with annotations in ingress objects.
Ingresses point to external services:`type: ExternalName`.

```
    traefik.ingress.kubernetes.io/auth-type: forward
    traefik.ingress.kubernetes.io/auth-url: https://kubew00:6443
    traefik.ingress.kubernetes.io/auth-tls-secret: tls-auth
    traefik.ingress.kubernetes.io/rule-type: "PathPrefixStrip"
```

### What did you expect to see?
Mutual TLS authentication between Traefik and remote backends. I'm using Traefik as API GW for multiple remote API servers. I do not want to pass client certificates (used for frontends) to the backends. I'm expecting Traefik to use certificates stored into kubernetes secrets to autenticate against remote API servers.

### What did you see instead?
Traefik fails parsing the configuration above provided by kubernetes.
Also, it claims there are no secrets in the current namespace.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
traefik_linux-amd64.1.7.0rc3
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# (paste your configuration here)
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
time="2018-08-21T13:40:40+02:00" level=error msg="Failed to retrieve auth configuration for ingress kube-system/caldera: failed to load auth secret: secret \"kube-system\"/\"tls-auth\" does not exist"
time="2018-08-21T13:40:40+02:00" level=debug msg="Configuration received from provider kubernetes: {\"backends\":{\"/clusters/caldera/\":{\"loadBalancer\":{\"method\":\"wrr\"}}}}"
time="2018-08-21T13:40:40+02:00" level=debug msg="Received Kubernetes event kind *v1.Secret"
time="2018-08-21T13:40:40+02:00" level=error msg="Near line 51 (last key parsed 'frontends.clusters/caldera/.auth.forward.tls.cert'): strings cannot contain newlines"
```

**Comment by traefiker** [comment]
Closed by #3804.
