### ISSUE TITLE
missing CORS accessing api

### ISSUE THREAD

**Issue by AvoMMH** [containous/traefik#3823]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I wrote my own Dashboard including more functionality than the default one.
Now I want to get the data from the api into my Dashboard requesting http://**/api/providers

### What did you expect to see?
I expect to get the providers JSON into my Application

### What did you see instead?

Cross-Origin blocked (Reason: CORS-Header 'Access-control-Allow-Origin' missing)

The api is accessible, I can get the JSON if I request it on my own.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.6.6
Codename:     tetedemoine
Go version:   go1.10.3
Built:        2018-08-20_01:10:06PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[api]
address = ":8080"
dashboard = false
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
```

**Comment by ldez** [comment]
Hello,

You configuration is invalid:
```toml
[api]
address = ":8080" # <- this option doesn't exist
dashboard = false
```

To use a custom port you need to define an entry point: https://docs.traefik.io/v1.6/configuration/api/#address-port

In you case, eg. `8080`, you don't need to define the port because `8080` it's the default value.

**Comment by AvoMMH** [comment]
Okay, I fixed that. But it still throws the missing CORS header Exception

**Comment by SantoDE** [comment]
When you say, that you created your own frontend: did you add the CORS header to the request you make in code?

**Comment by SantoDE** [comment]
Well, that totally depends. Maybe one question upfront: are you running your new frontend in a totally separate way (e.g. on a nodejs server)? My assumption is, that this is the case and therefore the CORS error pops up, which is fine.

The Port is included in the origin, so you have two origins trying to speak to each other. Better way is to really include your frontend in the binary and then the error will be gone. If you still want to have it seperated, yes, the API and your client requesting something from the API need to set the corresponding CORS header (Access-Control-Allow-Origin).

[click me for detailed cors information](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS)

**Comment by AvoMMH** [comment]
I defined a route for the api and added the cors header, that worked for me.
