### ISSUE TITLE
Support logical OR in routing rules

### ISSUE THREAD

**Issue by hsmade** [containous/traefik#3827]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

As a better alternative to segmentation in the consul catalog provider (https://github.com/containous/traefik/pull/3796) I would like to be able to specify multiple rules and have these applied as a logical OR. So for example (not actual syntax):
```Host: A;PathPrefix: /A OR Host: B;Pathprefix: /B```

As discussed, this should wait for / be implemented by the general refactoring of the routing rule syntax. So this feature request is just a way of tracking that this functionality is implemented.

**Comment by dtomcej** [comment]
@hsmade,

Traefik v2 has full support for complex rule trees built with `&&` and `||`.

For this reason, I will be closing this issue.
