### ISSUE TITLE
Add command to export ACME Account from KV store

### ISSUE THREAD

**Issue by nmengin** [containous/traefik#3847]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

In the way to store a lot of ACME certificates in all KV stores, the ACME Account is stored in a binary format into the KV stores.

To obtain this binaries data Træfik:

- Converts the *ACME Account* object into *JSON* (Go provides a `[]byte`)
- Compresses the `[]byte`

This format is not readable and not esay to maintain.

It should be helpful and useful to create a tool (shell script or subcommand) to allow users to export these data into a readable format.

**Comment by alwinmarkcf** [comment]
I know there are already two formats existing, but I personally would try to explode the meta acme object into own key/value pairs per certificate using an own struct. [This meta object](https://github.com/containous/traefik/blob/v1.7/cluster/datastore.go#L20-L24) is just a bad design and will cause problems in future. Also it is just a workaround and is limiting for [no known reason](https://github.com/containous/traefik/issues/1325#issuecomment-288985067) the number of certificates.

**Comment by camilb** [comment]
I'm currently using these commands to export certificates from Consul

```bash
#export JSON containing certificate and private key
consul kv get traefik/acme/account/object | gzip -dc | jq -r '.DomainsCertificate.Certs[] | select(.Domains.Main=="'www.example.com'") | .Certificate'

#export certificate only
consul kv get traefik/acme/account/object | gzip -dc | jq -r '.DomainsCertificate.Certs[] | select(.Domains.Main=="'www.example.com'") | .Certificate.Certificate' | base64 -D 

#export private key only
consul kv get traefik/acme/account/object | gzip -dc | jq -r '.DomainsCertificate.Certs[] | select(.Domains.Main=="'www.example.com'") | .Certificate.PrivateKey' | base64 -D 
```

<img width="1490" alt="export-cert-only-traefik" src="https://user-images.githubusercontent.com/2655869/46201884-9701b080-c315-11e8-952e-0bdb618a7f5c.png">
<img width="1060" alt="export-cert-traefik" src="https://user-images.githubusercontent.com/2655869/46201886-9701b080-c315-11e8-8eb5-96f2c8829705.png">

**Comment by alwinmarkcf** [comment]
Cool I'll try that, because than I don't have to run my monkey patch version anymore and can use this to implement a hook into the helm chart creating backups automatically.

**Comment by camilb** [comment]
Some notes related to backup/restore process. You have to use `-base64`flag to correctly export the value. Otherwise it will add some weird escaping and traefik will fail: `"Error reloading: 1 error(s) decoding:\n\n* error decoding 'Object': unexpected EOF"`

Ex.

```bash
#backup
consul kv get -base64 traefik/acme/account/object > backup-base64

#restore
cat -s backup-base64 | base64 --decode | consul kv put traefik/acme/account/object -
```

**Comment by alwinmarkcf** [comment]
@camilb hi, its been a while I promised to look into it and I finally found the time. So the according script to yours for etcd using the official traefik helm Chart is:

```
kubectl run --namespace kube-system  --rm -it traefik-etcd-test --image=quay.io/coreos/etcd:v3.1.8 --restart=Never --env="ETCDCTL_API=3" -l app=traefik -- etcdctl --endpoints=http://traefik-etcd-cluster-client:2379 get traefik/acme/account/object --prefix --print-value-only --hex  | sed 's/\\x//g' | xxd -r -p | gzip -dc | jq .
```

or with plain etcdctl:

```
etcdctl --endpoints=http://traefik-etcd-cluster-client:2379 get traefik/acme/account/object --prefix --print-value-only --hex  | sed 's/\\x//g' | xxd -r -p | gzip -dc | jq .
```

But I guess we still should implement this as an traefik native function which is independent of the storage solution.

**Comment by Thomvaill** [comment]
Thanks for your commands @camilb !
Thanks to them, I found the inspiration to write a fork of SvenDowideit/traefik-certdumper that support automatic certs dumping from Consul.

Here is the PR: https://github.com/SvenDowideit/traefik-certdumper/pull/1

**Comment by alwinmarkcf** [comment]
Yeah but still, when traefik would have an export itself, we could e.g. use it in the helm chart to export certs 
1. before updating traefik
2. regulary

to a pvc of choice

**Comment by ldez** [comment]
I created a more robust tool: https://github.com/ldez/traefik-certs-dumper/

**Comment by alwinmarkcf** [comment]
@ldez but afaik your tool is dumping from json file while the other tool is dumping directly from consul. Actually a cli command which is dumping from any file the json file would be awesome.

**Comment by ldez** [comment]
PR are welcomes :smile_cat:

**Comment by cecchisandrone** [comment]
> I'm currently using these commands to export certificates from Consul
> 
> ```shell
> #export JSON containing certificate and private key
> consul kv get traefik/acme/account/object | gzip -dc | jq -r '.DomainsCertificate.Certs[] | select(.Domains.Main=="'www.example.com'") | .Certificate'
> 
> #export certificate only
> consul kv get traefik/acme/account/object | gzip -dc | jq -r '.DomainsCertificate.Certs[] | select(.Domains.Main=="'www.example.com'") | .Certificate.Certificate' | base64 -D 
> 
> #export private key only
> consul kv get traefik/acme/account/object | gzip -dc | jq -r '.DomainsCertificate.Certs[] | select(.Domains.Main=="'www.example.com'") | .Certificate.PrivateKey' | base64 -D 
> ```
> 
> <img alt="export-cert-only-traefik" width="1490" src="https://user-images.githubusercontent.com/2655869/46201884-9701b080-c315-11e8-952e-0bdb618a7f5c.png"> <img alt="export-cert-traefik" width="1060" src="https://user-images.githubusercontent.com/2655869/46201886-9701b080-c315-11e8-8eb5-96f2c8829705.png">

Thanks for sharing these commands, anyway I notice that quite often I receive `unexpected end of file` or the content is incomplete. Do you have any idea why data could be corrupted?

**Comment by alwinmarkcf** [comment]
@cecchisandrone It may happend that the container you spawned was not removed correctly or you run into timeouts using this command. 

For me it was always the first case when I ran into that problem (or it was totally my fault and I was in the wrong namespace). Removing the orphan pod  solved it for me.

**Comment by alwinmarkcf** [comment]
@ldez I my Golang skills seem to be too limited, I was not able yet to clone the storeconfig job into a exportconfig job. (Simply I'm not able to get a hello world job running).

In the meantime to move on, I extended the kubernetes chart doing this job: https://github.com/helm/charts/pull/12817

It uses a custom Container of mine but as soon as there is a job this could be picked up to use it with all kv providers

**Comment by ldez** [comment]
Thanks to @smueller18, now [traefik-certs-dumper](https://github.com/ldez/traefik-certs-dumper) support KV stores.

**Comment by ldez** [comment]
[traefik-certs-dumper](https://github.com/ldez/traefik-certs-dumper) feature:

- Supported sources:
    - file ("acme.json")
    - KV stores (Consul, Etcd, Zookeeper, Boltdb)
- Watch changes:
    - from file ("acme.json")
    - from KV stores (Consul, Etcd, Zookeeper)
- Output formats:
    - use domain as sub-directory (allow custom names and extensions)
    - flat (domain as filename)

This tool is now "feature complete", so I will close this issue.

Thanks to all contributors.

**Comment by bradjones1** [comment]
A note to anyone who is working in a constrained environment (e.g., busybox) where `xxd -r` is not available:
```
ETCDCTL_API=3 etcdctl --endpoints http://your.etcd:2379 get /traefik/acme/account/object -w json | jq '.kvs[0].value' | base64 -d - | gzip -d
```
