### ISSUE TITLE
Documentation: Incorrect link in the API / Dashboard

### ISSUE THREAD

**Issue by thernstig** [containous/traefik#3849]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Regarding documentation at: https://docs.traefik.io/configuration/api/

The link to "examples" early on in in the text links to https://docs.traefik.io/user-guide/examples/#ping-health-check which is non-existant. The document exists, but the actual section seems to be gone.

### What did you expect to see?

For it to work. Or rather, a proper example of the [api] configuration.

### What did you see instead?

Just ended up at the top of the page at https://docs.traefik.io/user-guide/examples/

**Comment by thernstig** [comment]
@geraldcroes Of course, I cannot believe I forgot that. It's been added.

**Comment by traefiker** [comment]
Closed by #3850.
