### ISSUE TITLE
Backend URL can't be configured using Docker

### ISSUE THREAD

**Issue by bclermont** [containous/traefik#3855]
Since https://github.com/containous/traefik/pull/3387 it's now possible to use gRPC without https.

[gRPC user guide](https://github.com/containous/traefik/blame/4055654e9b59492a3e9bcc657e6a1b215b372f30/docs/user-guide/grpc.md#L27) specify the backend `url` must be set to `h2c://....`

But on [Docker backend guide](https://github.com/containous/traefik/blame/4055654e9b59492a3e9bcc657e6a1b215b372f30/docs/configuration/backends/docker.md#L218) there is no way to configure that "url".

**Comment by SantoDE** [comment]
Hey @bclermont,

it's the `traefik.protocol` label you're looking for. (https://docs.traefik.io/configuration/backends/docker/) :)

**Comment by bclermont** [comment]
oh yes that work, thanks
