### ISSUE TITLE
get subdomain certificate not working of name.com

### ISSUE THREAD

**Issue by emfox** [containous/traefik#3861]
I need wildcard ssl certs, so I use dns-01 provider namedotcom, example.com and *.example.com works fine, but any sub.example.com or sub2.sub.example.com didn't work.

I did a little research from the log, and found that it search for _acme-challenge.sub.example.com, but on name.com there's only records of _acme-challenge.example.com, no matter what sub domain I use, it only write challenge records to to top level domain.

**Comment by emfox** [comment]
ok, no need now. I found the same one:
https://github.com/containous/traefik/issues/3306

and it seems lego does not very active in solving it, even if there's already pull request for that.

**Comment by ldez** [comment]
duplicate of #3306
