### ISSUE TITLE
File provider not working (with separate files)

### ISSUE THREAD

**Issue by Pea13** [containous/traefik#3865]
Hello,

I'm trying to use traefik with the file provider.
Everything works fine if I put the configuration in the configuration file.

For exemple, at the end of my traefik.toml:

[file]
[backends]
    [backends.backsup0]
	[backends.backsup0.servers.server1]
    	url = "http://sup0.xxxx.priv:80"
[frontends]
    [frontends.sup0]
    entryPoints = ["http", "https"]
    backend = "backsup0"
	[frontends.sup0.routes.route0]
    	rule = "Host:sup0.xxx.com"

I launch traefik with the --file option and everything is fine.

But if I want to use a separate file or directory : https://docs.traefik.io/configuration/backends/file/#one-separate-file or https://docs.traefik.io/configuration/backends/file/#multiple-separated-files, traefik doesn't seems to see my files and on the api dashboard the file section is empty.

I tried with 1.6.6-alpine and with the latest 1.7-rc3.
Any ideas or examples of working setup ?

Regards,

### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
I added a [file] section to my configuration file

### What did you expect to see?
If i use separate files, i expect to see my configuration files parsed and reported to the api dashboard

### What did you see instead?
Traefik started fine but the file configuration was not parsed

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
1.6.6-alpine
Version:      v1.6.6
Codename:     tetedemoine
Go version:   go1.10.3
Built:        2018-08-20_01:10:06PM
OS/Arch:      linux/arm


1.7-rc3-alpine
Version:      v1.7.0-rc3
Codename:     maroilles
Go version:   go1.10.3
Built:        2018-08-01_01:37:51PM
OS/Arch:      linux/arm
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# (paste your configuration here)
# end of traefik.toml
[file]
directory = "/config/files"
watch = true
```

traefik started with --file

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
Nothing special in the logs
```

**Comment by Pea13** [comment]
Of course, i have verified path and permissions.
For example:

[file]
directory = "/config/files"
watch = true

And : 
# ls -hl /config/files/
total 4
-rw-r--r--    1 root     root         286 Sep  7 11:04 sup.toml

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Træfik!

Issue templates help us help you by providing all necessary information.

Please edit your issue and use the available templates:

- [Feature request](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/Feature_request.md)
- [Bug report](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/Bug_report.md)

And remember: each time someone ignores the template, a cute little bunny dies.
<details>
<summary>#SaveTheCuteBunny :heart: :rabbit: :heart:</summary>

![southpark - estrella kill rabbit](https://user-images.githubusercontent.com/5674651/27143914-3cea7896-5130-11e7-81f8-02d8ac2da7a7.gif)

![southpark - estrella kill rabbit2](https://user-images.githubusercontent.com/5674651/27143924-49104c72-5130-11e7-82ae-ccedbd5dfa1c.gif)

</details>

**Comment by Pea13** [comment]
Issue updated ;)

**Comment by Pea13** [comment]
Hi,

Traefik is started as a swarm service.

`
docker service create --detach=false --name TRAEFIK 
       --constraint "node.role == manager" 
       --publish 80:80 --publish 443:443 
       --network traefik_network 
       --mount type=bind,source=/run/docker.sock,target=/var/run/docker.sock 
       --mount type=volume,source=traefik,target=/config 
       --label traefik.enable=true 
       --label traefik.backend="Traefik" 
       --label traefik.frontend.rule="Host:traefik.xxx.xxx" 
       --label traefik.port=8080 
       --label traefik.docker.network=traefik_network 
       --label traefik.frontend.entryPoints=http,https 
       --label traefik.frontend.whiteList.sourceRange="192.168.1.0/24, 192.168.255.0/24, 10.0.0.0/8" \
       traefik:1.6-alpine 
       --acme.storage=/config/acme.json 
       --configfile=/config/traefik.toml 
       --file
`

Like i said before, if the configuration is in the file traefik.toml, everything works fine.
You can find the logs in the attachment called log_1
[log_1.txt](https://github.com/containous/traefik/files/2379872/log_1.txt)

And we can see this in the logs:
`
TRAEFIK.1.8oysiopj22du@docker00    | time="2018-09-13T15:04:31Z" level=debug msg="Configuration received from provider file: {\"backends\":{\"backnas\":{\"servers\":{\"server1\":{\"url\":\"\
http://qnap.XXXXX.priv:8080\",\"weight\":0}},\"loadBalancer\":{\"method\":\"wrr\"}},\"backsup0\":{\"servers\":{\"server1\":{\"url\":\"http://sup0.XXXXX.priv:80\",\"weight\":0}},\"loadBalanc\
er\":{\"method\":\"wrr\"}}},\"frontends\":{\"nas\":{\"entryPoints\":[\"http\",\"https\"],\"backend\":\"backnas\",\"routes\":{\"route0\":{\"rule\":\"Host:nas.XXXXX.org\"}},\"priority\":0,\"b\
asicAuth\":null,\"whiteList\":{\"sourceRange\":[\"192.168.1.0/24\",\"192.168.255.0/24\",\"10.0.0.0/8\"]}},\"sup0\":{\"entryPoints\":[\"http\",\"https\"],\"backend\":\"backsup0\",\"routes\":\
{\"route0\":{\"rule\":\"Host:sup0.XXXXX.org\"}},\"priority\":0,\"basicAuth\":null,\"whiteList\":{\"sourceRange\":[\"192.168.1.0/24\",\"192.168.255.0/24\",\"10.0.0.0/8\"]}}}}"
`

As a reminder, the configuration file is this one: 
[config_included.txt](https://github.com/containous/traefik/files/2379896/config_included.txt)




Now if i try to change the main config file (traefik.toml) : 
`
[file]
directory = "/config/files/"
watch = true
`

In the directory /config/files, i created a file named sup.toml (permissions are ok).
The debug log is here: 
[log_2.txt](https://github.com/containous/traefik/files/2379932/log_2.txt)

Tell me if you need more informations.
Regards,

**Comment by geraldcroes** [comment]
Hi, could you check #3550 and get back to us if what you find there doesn't fix your problem?

**Comment by Pea13** [comment]
Hi,

After a lot of tests, i finally found the problem.. Sorry it was my bad.
If i remove the option --file from the command line, everything works fine (conf included or separated files).
With the --file option, the separated files case doesn't work.

Regards,

**Comment by geraldcroes** [comment]
Hi, thx for letting us know.

Next time though, beware the issue template guardian, he's an angry bot that bites from time to time 😈 

Enjoy using traefik!
