### ISSUE TITLE
Filter domains using ACME

### ISSUE THREAD

**Issue by drewwells** [containous/traefik#3868]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I should be able to filter which ingress objects the controllers tries to request ACME certs for. The cert-manager way of annotating ingress objects makes the most sense instead of relying on values.yaml to modify these settings. My environment uses a mixture of external and internal domains. The internal domains use certs from a different source and the external ones rely on ACME. The ingress controller is continuouslly requesting certificates from let's encrypt for these internal domains which will always fail.

Is the domainList supposed to filter which domains are requested? If so, I could not figure out the right syntax to make that work.

**Comment by drewwells** [comment]
Using: https://github.com/helm/charts/tree/master/stable/traefik

Chart version: 1.43.0
Traefik image tag: 1.6.5
appVersion: 1.6.6

**Comment by fearlsgroove** [comment]
If this implementation could allow filtering by docker labels on backends, that would be ideal for my use cases

**Comment by ldez** [comment]
Close in favor of #4872 - Feel free to subscribe there for updates.
