### ISSUE TITLE
Add a Changelog

### ISSUE THREAD

**Issue by sandstrom** [containous/traefik#388]
Forgive me if I'm blind, but I cannot find a change log. 🙈 

Here are a few things that make a change log great:
- Made for humans, not machines, so legibility is crucial.
- Easy to link to any section (hence Markdown over plain text).
- One sub-section per version.
- List releases in reverse-chronological order (newest on top).
- Write all dates in YYYY-MM-DD format. (https://xkcd.com/1179/)
- have an "Unreleased" section at the top for keeping track of any changes.

*Source: http://keepachangelog.com*

**Comment by keis** [comment]
I've been using this tool to generate changelogs a few times https://github.com/lalitkapoor/github-changes

It's not perfect but I can recommend if you just want to get something going without much effort :)

**Comment by emilevauge** [comment]
Hi @sandstrom, you are right. We spoke multiple times of adding one but:

- I wanted to update it automatically (using a  generator) and I have not found a way to do that at each merge on the master
- Knowing that, the only way is to generate it manually. As we are soon going to release the 1.0.0, I was thinking of generating a changelog at each new version starting from this version.

**Comment by firehist** [comment]
Maybe it's not the appropriate tools, but I'm using a lot `commitizen` tools to generate Changelog. It follows some commit rules from Angular Team.
https://github.com/commitizen/cz-cli
https://github.com/conventional-changelog/conventional-changelog
