### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by zieckey** [containous/traefik#389]
There is no Go code in here : github.com/containous/traefik/autogen

  ```
$ go build
  web.go:10:2: no buildable Go source files in d:\goworkspace\src\github.com\containous\traefik\autogen
```

**Comment by emilevauge** [comment]
Hi @zieckey, you should have read the contributing doc: https://github.com/containous/traefik/blob/master/.github/CONTRIBUTING.md

`go generate` before your first `go build`

**Comment by zieckey** [comment]
Thanks for your quick response.
