### ISSUE TITLE
Not all treafiks in cluster mode reload acme storage after new certificate is issued

### ISSUE THREAD

**Issue by tiukhtinvladimir** [containous/traefik#3892]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I noticed that after certificate is issued not all traefik nodes reload acme storage which means that in some cases web site works in some default traefik certificate is being returned

### What did you expect to see?

All traefik nodes acknowledge new certificate

### What did you see instead?

Not all traefik node acknowledge new certificate, but some

### Output of `traefik version`:

```
Version:      v1.6.6
Codename:     tetedemoine
Go version:   go1.10.3
Built:        2018-08-20_01:10:06PM
OS/Arch:      linux/amd64

```

### What is your environment & configuration?

We run traefik in kubernetes using daemonset. This is our args:
```
        - --defaultentrypoints=http,https
        - --entryPoints=Name:http Address::80 Compress:true
        - --entryPoints=Name:https Address::443 TLS Compress:true
        - --entryPoints=Name:api Address::8080
        - --api
        - --api.dashboard
        - --api.entrypoint=api
        - --api.statistics
        - --etcd
        - --etcd.endpoint=etcd.example.com:2379
        - --etcd.trace
        - --etcd.watch
        - --etcd.useapiv3
        - --etcd.prefix=/traefik
        - --kubernetes
        - --kubernetes.watch
        - --acme
        - --acme.dnschallenge.provider=rfc2136
        - --acme.email=support@asergis.com
        - --acme.storage=/traefik/acme/account
        - --acme.entrypoint=https
        - --acme.acmelogging
        - --acme.dnschallenge
        - --acme.dnschallenge.delaybeforecheck=3
        - --acme.onhostrule
        - --loglevel=INFO
        - --ping
        - --ping.entrypoint=api
```

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Slack workspace](https://traefik.herokuapp.com/) for more [community #support](https://traefik.slack.com/messages/C0CDT22PJ/).
