### ISSUE TITLE
add support for zipkin tracing

### ISSUE THREAD

**Issue by jstrachan** [containous/traefik#390]
[zipkin](http://zipkin.io/) is a great way to do inter-microservice invocation tracing and visualisation. It'd be awesome to add zipkin support to traefik. 

There's notes on [zipkin instrumenting here](http://zipkin.io/pages/instrumenting.html). There's an existing go implementation of zipkin tracing at https://github.com/elodina/go-zipkin

**Comment by jippi** [comment]
Any plan for this? :)

**Comment by martinbaillie** [comment]
I took a quick look at this the other day. I was thinking I'd implement some base OpenTracing server/client spans for v1.5.

**Comment by Vlaaaaaaad** [comment]
Any updates on this?

**Comment by ldez** [comment]
Closed by #2587
