### ISSUE TITLE
Traefik keeps opening new sockets when docker swarm loses quorum

### ISSUE THREAD

**Issue by givasthefirst** [containous/traefik#3904]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
I am running traefik on top of docker swarm and when the swarm cluster loses quorum traefik does not respect the timeouts for connections and keeps opening new sockets connections until file descriptors be full and raises **too many open files**.   

### What did you expect to see?

Expect traefik to close socket connections when the timeouts and maxIdleConnection limits are reached.

### What did you see instead?
Traefik keeps openning new sockets until file descriptors max are reached causing **too many open files**.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
traefik version
Version:      v1.6.6
Codename:     tetedemoine
Go version:   go1.10.3
Built:        2018-08-20_01:10:06PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```Args
              "--api",
                "--docker",
                "--docker.swarmmode",
                "--docker.watch",
                "--logLevel=DEBUG",
                "--respondingtimeouts.idletimeout=3s",
                "--maxidleconnsperhost=20",
                "--forwardingtimeouts.dialtimeout=3s",
                "--forwardingtimeouts.responseheadertimeout=3s"
```

**Comment by nmengin** [comment]
Hello @givasthefirst 

Many thanks for your interest in the project.

Can you provide the logs generated by Træfik (in DEBUG mode if possible) please?

Thanks in advance.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Slack workspace](https://traefik.herokuapp.com/) for more [community #support](https://traefik.slack.com/messages/C0CDT22PJ/).
