### ISSUE TITLE
support for subrequest authorization (nginx auth_request)

### ISSUE THREAD

**Issue by munkyboy** [containous/traefik#391]
Desired request flow:
1. a request for `/service` comes into traefik
2. traefik is configured to first send the request to an _authorization_ backend
3.  
   1. if the HTTP response code from the _authorization_ backend is 2xx, forward original request to `/service`
   2. if the HTTP response code from the _authorization_ backend is 401 or 403,  respond to original request with _authorization_ code

This request is based on the [nginx auth_request directive](http://nginx.org/en/docs/http/ngx_http_auth_request_module.html#auth_request)

**Comment by ekozan** [comment]
linked to https://github.com/containous/traefik/issues/30

**Comment by Toflar** [comment]
I like this proposal. This aims to be a generic solution and allows every developer to implement the authorization stuff they need.
There's one thing I would like to mention here: traefik must cache the response and allow for cache invalidation. Forwarding the request to the authorization back end is an additional round trip for every single request and in most cases you'll have a username/password or token based authorization which will not change very often.
I think the best solution would be for traefik to do something like this:

## Scenario A: No Caching at all

traefik forwards the request to the authorization back end. The back end sends the response using the `Cache-Control: no-cache` HTTP header.

## Scenario B: Regular HTTP caching

The back end sends the regular HTTP caching headers to ask traefik to cache the authorization for a specific amount of time or use E-Tag handling (settings like `Max-Age`, `Expire` or even `E-Tag`).

## Scenario C: Cache invalidation

I would like to be able to tell traefik to cache forever unless I invalidate the cache. This would save so many useless roundtrips. Two things are needed here:

1. The back end has to tell treafik how to calculate the "request identity".
2. The back end has to provide an invalidation key.

So the response must be something like this (as an idea, maybe you have way better ones):

```json
{
    "requestIdentifier": "http.host + http.headers.Authorization",
    "invalidationKey": "his-is-my-unique-cache-key-for-this-requestIdentifier"
}
```

I should then be able to call the back end via HTTP using something like `DELETE /auth-caches/his-is-my-unique-cache-key-for-this-requestIdentifier`.

I'm not satisfied with the `requestIdentifier` part at all but I think cache invalidation is really important from a performance perspective. Any better ideas maybe?

**Comment by diegooliveira** [comment]
Hello, I did a pull request #764 to address this issue. 

Please review, any change, code style or design problem, please let know.

**Comment by byrnedo** [comment]
This is currently stopping me from switching over from a homebaked solution with nginx. This would be a great feature for traefik.

**Comment by Vlaaaaaaad** [comment]
Is this not closed by https://github.com/containous/traefik/pull/1972?

**Comment by Globegitter** [comment]
@Vlaaaaaaad as far as I can see with #1972 one can just implement that for all requests. So you specific that for your entrypoints and can not differentiate between some endpoints that do not need to be authenticated vs other ones that should. But yes, would be great to be able to have the auth forward on a per request basis and is also a blocker for us to migrate.

**Comment by munkyboy** [comment]
yes. I believe [commit 79bf19c8](https://github.com/containous/traefik/commit/79bf19c897bec1891eb5d6a1bca8e2a8f6d0c5ba)  implements the request. closing
