### ISSUE TITLE
Traefik won't run on Window Server 2016 1803

### ISSUE THREAD

**Issue by rychannel** [containous/traefik#3910]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Tried to start the Traefik Windows container

### What did you expect to see?

Traefik start running

### What did you see instead?
```
C:\Program Files\Docker\docker.exe: Error response from daemon: container 87222e3f85f1f25019849dec73ae0f3749fea27f1107d524d76cb10e8b427832 encountered an error during CreateContainer: failure in a Windows system call: The operating system of the container does not match the operating system of the host. (0xc0370101) extra info: {"SystemType":"Container","Name":"87222e3f85f1f25019849dec73ae0f3749fea27f1107d524d76cb10e8b427832","Owner":"docker","IsDummy":false,"VolumePath":"\\\\?\\Volume{6e78f17e-a7a9-4697-a6fc-913ed50c09b8}","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\docker\\windowsfilter\\87222e3f85f1f25019849dec73ae0f3749fea27f1107d524d76cb10e8b427832","Layers":[{"ID":"aebb51c4-f10d-5dc8-83bc-ad0c46652f32","Path":"C:\\ProgramData\\docker\\windowsfilter\\5afe0f2c3729cd9033f4d1a722a5e65ecd9107b10ec9ad93d8378e3a6dab36d4"},{"ID":"e503ff11-3c6f-50d5-bbc8-ff6786acd437","Path":"C:\\ProgramData\\docker\\windowsfilter\\2f577ec4bc7dd9e6576fa5811ef02fab0e87de55874f8dc9fb10b9ed4f88a1c0"}],"HostName":"87222e3f85f1","MappedDirectories":[],"HvPartition":false,"EndpointList":["b76d20c3-26e1-47a0-a63c-22b15a093eeb"],"Servicing":false,"AllowUnqualifiedDNSQuery":true}.
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

Was trying 1.7, tried most of the nanoserver variations

```
(paste your output here)
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# (paste your configuration here)
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
(paste your output here)
```

**Comment by dduportal** [comment]
Hello @rychannel , thanks for your interest on the project.

As described in https://github.com/containous/traefik-library-image/pull/31, the initial implementation of the Windows-based Docker image is built on Nanoserver-sac2016.

Based on the compatibility provided by Microsoft at https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility,
 the alternative for you is to run the container with the Hyper-V isolation, 
by adding the flag `--isolation=hyperv` to `docker run`, if this isolation engine is available on your machine.

We are working on providing more Windows versions in the future, but as the issues linked earlier states, they are some Golan issues preventing us for now.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Slack workspace](https://traefik.herokuapp.com/) for more [community #support](https://traefik.slack.com/messages/C0CDT22PJ/).
