### ISSUE TITLE
benchmarks with different number of threads?

### ISSUE THREAD

**Issue by kontrafiktion** [containous/traefik#392]
At http://docs.traefik.io/benchmarks/ there might be an error.

It looks like the command and its output do not match (8 threads in the command line, 20 threads in the reported output):
![image](https://cloud.githubusercontent.com/assets/198502/15454550/2c3a0898-203c-11e6-9408-a63057ee18e4.png)

For nginx it looks consistent:
![image](https://cloud.githubusercontent.com/assets/198502/15454546/fd5e0484-203b-11e6-94a8-5078a8f05384.png)

**Comment by emilevauge** [comment]
Oops, indeed, bad copy-paste. The right answer is `-t20` ;)
