### ISSUE TITLE
GCP Ingress Error: Error 400: Invalid value for field 'namedPorts[0].port': '0'. Must be greater than or equal to 1, invalid

### ISSUE THREAD

**Issue by DakshMiglani** [containous/traefik#3921]
### Do you want to request a *feature* or report a *bug*?

GCP Ingress is not getting created.
err: 

Error 400: Invalid value for field 'namedPorts[0].port': '0'. Must be greater than or equal to 1, invalid

### What did you do?

Well, in general I did this:

helm install --values traefik-val.yaml  stable/traefik

cat traefik-val.yaml =>
dashboard:
  enabled: true
  domain: dashboard.domain.com
kubernetes:
  namespaces:
    - default
    - kube-system

### What did you expect to see?
The ingress could have been created?

**Comment by dduportal** [comment]
Hello @DakshMiglani ,

Some informations are missing to help us understand (and reproduce the issue).

Could you please provide the elements requested when you open an issue (there is a pre-filled template):

- More configuration / YAML from your application (there is no Ingress Rule nor Service definition provided while the error message reports issue on a Service object) 
- When is the error message occuring exactly? Which command did you typed? Which configuration/YAML?
- Some Traefik Logs could help a lot also.
