### ISSUE TITLE
Unable to pull latest docker image on armhf

### ISSUE THREAD

**Issue by SuperSandro2000** [containous/traefik#3924]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Tried to pull the latest traefik docker image from a raspberry pi 3 running Raspbian.

### What did you expect to see?

That the latest tag is pulled like before.

### What did you see instead?

````
$ docker pull traefik
Using default tag: latest
latest: Pulling from library/traefik
no matching manifest for unknown in the manifest list entries

$ docker pull traefik:alpine
Using default tag: latest
latest: Pulling from library/traefik
no matching manifest for unknown in the manifest list entries
````

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
$ docker run traefik:alpine version
Version:      v1.6.6
Codename:     tetedemoine
Go version:   go1.10.3
Built:        2018-08-20_01:10:06PM
OS/Arch:      linux/arm

```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

toml doesn't apply 

Raspberry Pi 3 running latest Raspian (Debian Stretch)
````
$ docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:30:52 2018
 OS/Arch:           linux/arm
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:26:37 2018
  OS/Arch:          linux/arm
  Experimental:     false
````

**Comment by SuperSandro2000** [comment]
Thanks for the very kind and fast response. I really appreciate it!
And you were right that the image was still being build. The image now works correctly and so far I did not find any bugs ;)

**Comment by dduportal** [comment]
Thanks for the feedback! Have fun :)
