### ISSUE TITLE
Error on Docker back-ends with 1.7 not present in 1.6.6

### ISSUE THREAD

**Issue by br2490** [containous/traefik#3943]
## Bug
or a kind request for help or explanation of change/documentation.

### What did you do?
Using Traefik 1.7 on Docker (image: traefik:latest) without defined `traefik.backend`s defined causes errors not present in 1.6.6 - no front ends appear.  Moreover when attempting to specify the `backend` by label no front-ends appear with the same errors...

### What did you expect to see?
No output as with 1.6.6.

### What did you see instead?
```
isle-proxy-ld     | time="2018-09-27T19:31:37Z" level=error msg="undefined backend 'backend-traefik-isledevelopment' for frontend frontend-Host-admin-isle-localdomain-1. Skipping frontend frontend-Host-admin-isle-localdomain-1..."
isle-proxy-ld     | time="2018-09-27T19:31:37Z" level=error msg="undefined backend 'backend-isle-portainer-isledevelopment' for frontend frontend-Host-portainer-isle-localdomain-0. Skipping frontend frontend-Host-portainer-isle-localdomain-0..."
isle-proxy-ld     | time="2018-09-27T19:31:39Z" level=error msg="undefined backend 'backend-traefik-isledevelopment' for frontend frontend-Host-admin-isle-localdomain-2. Skipping frontend frontend-Host-admin-isle-localdomain-2..."
isle-proxy-ld     | time="2018-09-27T19:31:39Z" level=error msg="undefined backend 'backend-apache-isledevelopment' for frontend frontend-Host-isle-localdomain-PathPrefix-adore-djatoka-cantaloupe-0. Skipping frontend frontend-Host-isle-localdomain-PathPrefix-adore-djatoka-cantaloupe-0..."
isle-proxy-ld     | time="2018-09-27T19:31:39Z" level=error msg="undefined backend 'backend-isle-portainer-isledevelopment' for frontend frontend-Host-portainer-isle-localdomain-1. Skipping frontend frontend-Host-portainer-isle-localdomain-1..."
```

### Output of `traefik version`:

```
Version:      v1.7.0
Codename:     maroilles
Go version:   go1.11
Built:        2018-09-24_09:57:21AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration:
Docker on CentOS; Docker on Mac OS.
toml config: 
https://github.com/Islandora-Collaboration-Group/ISLE/blob/master/config/proxy/traefik.toml
docker-compose: (have since downgraded from `latest` to `1.6`)
https://github.com/Islandora-Collaboration-Group/ISLE/blob/master/docker-compose.yml

Thank you!

**Comment by ldez** [comment]
@br2490 could you provide more logs (from the start of Træfik) and do you have a minimal reproducible case?

**Comment by br2490** [comment]
@ldez https://gist.github.com/br2490/a1804ffc5fe696c3a4131e643dc7cd7a
Unfortunately I do not have a minimal reproducible case.

**Comment by ldez** [comment]
I think the problem is here:
```
time="2018-09-27T21:34:16Z" level=warning msg="unable to find a binding for the container \"/isle-apache-ld\": ignoring server"
time="2018-09-27T21:34:16Z" level=warning msg="cannot determine the IP address (got 0.0.0.0) for the container \"/isle-portainer-ld\": ignoring server"
time="2018-09-27T21:34:16Z" level=warning msg="cannot determine the IP address (got 0.0.0.0) for the container \"/isle-proxy-ld\": ignoring server"
```

**Comment by ldez** [comment]
Could you try to remove `usebindportip = true`?

**Comment by br2490** [comment]
Heck yes I can and did!  Works perfectly now 👍 
Will this be an issue in multi-environments through the single proxy? i.e. spinning more than one of these "ISLE" stacks up?
Thank you @ldez! 💯

**Comment by ldez** [comment]
FYI, before #3638 the behavior was buggy because `usebindportip` doesn't really work.

I don't think it it's a issue in multi-environments.

**Comment by br2490** [comment]
Now the frontends are not available via HTTPS.  Is there something else wrong?
https://gist.github.com/br2490/c1cc49555240303df638e0b036d2b49f

**Comment by ldez** [comment]
The `https` entry point exists:

```
time="2018-09-27T22:55:57Z" level=info msg="Preparing server https &{Address::443 TLS:0xc0000103f0 Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] WhiteList:<nil> Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc0006bca40} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
...
time="2018-09-27T22:55:57Z" level=info msg="Starting server on :443"
...
time="2018-09-27T22:55:57Z" level=debug msg="Creating entry point redirect http -> https"
```

But seems not be applied to your frontends.
```
{\"backends\":{\"backend-isle-portainer-isledevelopment\":{\"servers\":{\"server-isle-portainer-ld-af38c7d17d35b49dd0f7bb8527d5970f\":{\"url\":\"http://172.24.0.2:9000\",\"weight\":1}},\"loadBalancer\":{\"method\":\"wrr\"}},\"backend-traefik-isledevelopment\":{\"servers\":{\"server-isle-proxy-ld-a70155c11090148735dd5b54e77f41d5\":{\"url\":\"http://172.24.0.4:8080\",\"weight\":1}},\"loadBalancer\":{\"method\":\"wrr\"}}},\"frontends\":{\"frontend-Host-admin-isle-localdomain-0\":{\"entryPoints\":[\"http\"],\"backend\":\"backend-traefik-isledevelopment\",\"routes\":{\"route-frontend-Host-admin-isle-localdomain-0\":{\"rule\":\"Host:admin.isle.localdomain;\"}},\"passHostHeader\":true,\"priority\":0,\"basicAuth\":null},\"frontend-Host-portainer-isle-localdomain-1\":{\"entryPoints\":[\"http\"],\"backend\":\"backend-isle-portainer-isledevelopment\",\"routes\":{\"route-frontend-Host-portainer-isle-localdomain-1\":{\"rule\":\"Host:portainer.isle.localdomain;\"}},\"passHostHeader\":true,\"priority\":0,\"basicAuth\":null}}}
```


Check that `defaultEntryPoints = ["http","https"]` is at the top of the file.

You can also try to add the label `traefik.frontend.entryPoints=http,https` on containers.


In order to keep the issues consistent, and because this is another topic, I suggest you continue the discussion in the #support channel in [Slack](https://slack.traefik.io).

**Comment by ad-bitmed** [comment]
Experienced the same issue. Traefik v1.6.6 works just fine, v1.7 complains about not finding bindings for various containers. Getting rid of usebindportip = true in traefik.toml fixed it.

**Comment by geraldcroes** [comment]
Thanks @ad-bitmed for your message.

I'd like to put emphasis on the purpose of the usebindportip option for the docker provider.

This option tells traefik to use the containers' bound ip/port for the route instead of their internal ip/port. This option should have very specific use cases (for instance when your traefik instance isn't on the containers' network).

Before 1.7, this option was broken (traefik was unable to detect the bound ip/ports because of a case sensitivity issue #3622) and we fixed its behaviour. By fixing the behaviour, some users (including you) find that traefik complains that it cannot find the required (because of the option) binding for some containers.

Even if this strict behaviour could be defendable, I'm thinking that we should fallback on the container ip/port "if" there is no "complete" binding for the container. This mechanism should enable people to use a mix of binds / no bind for their setup.

**Comment by ldez** [comment]
These logs only appear if you use `useBindPortIP`:
https://github.com/containous/traefik/blob/546bebc860001aa96c0c6c3e4e54b8cc454c4605/provider/docker/config.go#L341-L349

Check your configuration (TOML, CLI, ...)
