### ISSUE TITLE
Ignore 'Global Default Backend' Kubernetes ingresses

### ISSUE THREAD

**Issue by negz** [containous/traefik#3945]
### Do you want to request a *feature* or report a *bug*?
Feature

### What did you expect to see?
I'd like to be able to configure Traefik to ignore [global default backend](https://docs.traefik.io/configuration/backends/kubernetes/#global-default-backend-ingresses) Kubernetes ingresses, aka [single service ingresses](https://kubernetes.io/docs/concepts/services-networking/ingress/#single-service-ingress). I'd be happy to contribute this functionality myself if you thought it were appropriate.

### Use case
At Planet Labs we run a few Kubernetes clusters in which our internal customers manage their own Kubernetes Ingress resources. Some of these folks aren't super familiar with Kubernetes, so there's a high risk of them accidentally creating an ingress with a global default backend that handles requests it should not. To make matters worse, a while back we used to run a bespoke ingress controller that _only_ supported global default backend style ingresses, so people often copy ingress configs from that system and expect them to work. In general, it's a safer for us to discard them. We're not using Traefik yet, but we are considering doing so, and this functionality is something we'd need.

**Comment by negz** [comment]
As I hit enter to submit this issue it occurred to me that because the global default frontend/backend have [predictable names](https://github.com/containous/traefik/blob/master/provider/kubernetes/kubernetes.go#L44) it's very likely possible to simply ignore them via a slight change to the [default Kubernetes config template](https://github.com/containous/traefik/blob/master/templates/kubernetes.tmpl). I'll leave this issue open just in case folks think this is still worth doing.

**Comment by dduportal** [comment]
Hello @negz , thanks for your interest in the project. 
After a discussion, we think that this behavior should stay the same since it follows how Kubernetes works: if it is specified by Kubernetes, Traefik should follow it.

In your case, to avoid the kind of risk you raised, a Kubernetes good practise is to use separated namespaces for different users/entities: the ingress controller will have one default global rule per namespace, which would avoid any inter-user conflicts. (And you would be able to tune ressources quotas and advanced rights per namespace :) ).

**Comment by negz** [comment]
> After a discussion, we think that this behavior should stay the same since it follows how Kubernetes works: if it is specified by Kubernetes, Traefik should follow it.

I'd normally agree with this, except with the beta `Ingress` resource which is woefully underspecified and handled subtly differently depending on which ingress controller you use.

> In your case, to avoid the kind of risk you raised, a Kubernetes good practise is to use separated namespaces for different users/entities: the ingress controller will have one default global rule per namespace, which would avoid any inter-user conflicts.

Even in this namespace-per-team scenario nothing stops a user in a namespace they own creating two Ingress resources, each with a default global backend. In this case the behaviour of ingress controllers in undefined. (Unless the ingress controller extends the Kubernetes spec with weightings _and_ the users remember to set weightings.)

This all said, I don't feel the need to push this issue as I believe I can work around it with templates.
