### ISSUE TITLE
Option not to use stack name for Auto generated docker urls

### ISSUE THREAD

**Issue by robertbaker** [containous/traefik#3955]
I want to avoid using labels, as I'm aiming got more of a OttB setup. The default naming 
convention is service.stack.domain.tld.

I would like a way with a command line argument to change it globally to service.domain.tld. I'm using docker compose and so far have removed the need for a TOML and docker labels with the exception of changing the hostname of services.

**Comment by ldez** [comment]
seems to be a duplicate of #2578
