### ISSUE TITLE
Environment Variable $DOCKER_VERSION not set locally

### ISSUE THREAD

**Issue by cocap10** [containous/traefik#396]
Command `make binary` issue : in https://github.com/containous/traefik/blob/master/build.Dockerfile#L9 : `ARG DOCKER_VERSION=1.10.1` doesn't work locally, but is OK on travis due to https://github.com/containous/traefik/blob/master/.travis.yml#L10. Then, curl command at https://github.com/containous/traefik/blob/master/build.Dockerfile#L13 downloads https://get.docker.com/builds/Linux/x86_64/docker- which is not the docker binary...
It comes from this PR :https://github.com/containous/traefik/pull/368

**Comment by vdemeester** [comment]
`ARG DOCKER_VERSION=1.10.1` sets the default value so it definitely should work though :sweat:

**Comment by emilevauge** [comment]
It doesn't ;)

**Comment by vdemeester** [comment]
:scream:

**Comment by vdemeester** [comment]
Fixing this in #397
