### ISSUE TITLE
Can't pull traefik:latest on AMD hardware

### ISSUE THREAD

**Issue by MFAshby** [containous/traefik#3965]
To reproduce:
Use an AMD architecture computer (e.g. a raspberry pi..) 
Try to pull the latest traefik docker image:
`docker pull traefik:latest`

Expected behaviour: the image is downloaded and can be run 
Actual behaviour: the image is not retrieved, instead you get the following error message:
```
pi@raspberrypi:/mnt/vol/docker/traefik $ docker pull traefik:latest
latest: Pulling from library/traefik
no matching manifest for unknown in the manifest list entries
pi@raspberrypi:/mnt/vol/docker/traefik $ 
```

I expect this has happened only with the latest push to the docker hub repository: I can pull the previous version `1.7.0` with no problems.
```
pi@raspberrypi:/mnt/vol/docker/traefik $ docker pull traefik:1.7.0
1.7.0: Pulling from library/traefik
9dac48e51b23: Pull complete 
f6574aee0ec1: Pull complete 
Digest: sha256:257a45cfef110e8e0e75b2fb7d113c680032e65ec2c3ddcd5da305ddaac17da1
Status: Downloaded newer image for traefik:1.7.0
```

Possibly the latest tag does not refer to a [manifest list](https://docs.docker.com/edge/engine/reference/commandline/manifest/), which is necessary for multi-architecture images.

**Comment by ldez** [comment]
@MFAshby the official Docker is currently building in the Docker build system.
It's normal that you can not pull it yet.
We announced the availability too early.

**Comment by MFAshby** [comment]
Ah ok! guess I got unlucky. It work now.
