### ISSUE TITLE
Ability to use self-signed certificates for local development

### ISSUE THREAD

**Issue by shankiesan** [containous/traefik#399]
Hi traefik team,

I'd like to be be able to replicate my prod environment as completely as possible on my local machine, and for me, that involves using SSL certificates.

Is it possible to get the ACME configuration to generate self-signed certificates for when we're developing locally?

Cheers

**Comment by emilevauge** [comment]
Hi @shankiesan, maybe you could deploy your own test CA: https://github.com/letsencrypt/boulder

**Comment by shankiesan** [comment]
That's an interesting idea @emilevauge . I hadn't considered running my own CA!

How would you get Boulder to issue certificates, assuming that `.localhost` isn't reachable from the CA. Or is the idea that because you're running Boulder and Traefik on the same host that .localhost is valid?

**Comment by emilevauge** [comment]
You will have to configure a DNS to make it work.
