### ISSUE TITLE
Configuration problem

### ISSUE THREAD

**Issue by zieckey** [containous/traefik#401]
I have a HTTP Echo server at `http://10.16.28.17:8091/echo`, and I use the folling configuration to start `traefik` as a proxy:

<pre>
logLevel = "DEBUG"

defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
  address = ":8080"

[web]
address = ":8000"

[backends]
  [backends.httpecho]
    [backends.httpecho.servers.server1]
    url = "http://10.16.28.17:8091/echo"
    weight = 1

[frontends]
  [frontends.fe1]
  backend = "httpecho"
  [frontends.fe1.routes.localhost]
  rule = "Host"
  value = "localhost"
</pre>

but it don't work. I test it using `curl http://localhost:8080/echo` and it returns `404 page not found` as follows:

<pre>
$ curl http://localhost:8080/echo
404 page not found
</pre>

The `traefik` log as follows:
<pre>
time="2016-05-24T16:11:34+08:00" level=debug msg="Global configuration loaded {\"GraceTimeOut\":10,\"AccessLogsFile\":\"\",\"TraefikLogsFile\":\"\",\"LogLevel\":\"DEBUG\",\"EntryPoints\":{\"http\":{\"Network\":\"\",\"Address\":\":8080\",\"TLS\":null,\"Redirect\":null}},\"ACME\":null,\"DefaultEntryPoints\":[\http\"],\"ProvidersThrottleDuration\":2000000000,\"MaxIdleConnsPerHost\":200,\"Retry\":null,\"Docker\":null,\"File\":null,\"Web\":{\"Address\":\":8000\",\"CertFile\":\"\",\"KeyFile\":\"\",\"ReadOnly\":false},\"Marathon\":null,\"Consul\":null,\"ConsulCatalog\":null,\"Etcd\":null,\"Zookeeper\":null,\"Boltdb\":null,\"Kubernetes\":null}"
time="2016-05-24T16:11:34+08:00" level=info msg="Preparing server http &{Network: Address::8080 TLS:<nil> Redirect:<nil>}"
time="2016-05-24T16:11:34+08:00" level=info msg="Starting provider *main.WebProvider {\"Address\":\":8000\",\"CertFile\":\"\",\"KeyFile\":\"\",\"ReadOnly\":false}"
</pre>

Please help me to point out what's wrong here. Thanks.

**Comment by zieckey** [comment]
Can anyone help me? Thanks.

**Comment by errm** [comment]
a) does `curl -H 'Host: localhost' http://localhost:8080/echo` work?
b) you should check out the slack channel . . . https://traefik.herokuapp.com/

**Comment by emilevauge** [comment]
@zieckey, I don't see any `[file]` enabled in your toml, then traefik is not reading your rules right now.

**Comment by zieckey** [comment]
@errm Thanks. 
`curl -H 'Host: localhost' http://localhost:8080/echo`  don't work.

<pre>
$ curl -H 'Host: localhost' http://localhost:8080/echo
404 page not found
</pre>

**Comment by zieckey** [comment]
@emilevauge `[file]` is an optional configuration. I put all the rules in the same one toml file.
Thanks.

**Comment by zieckey** [comment]
Thanks all you guys.
