### ISSUE TITLE
Malformed ACME identifiers with trailing period

### ISSUE THREAD

**Issue by cpu** [containous/traefik#4011]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

N/A - I'm an employee of Let's Encrypt and noticed in our server-side logs that Traefik (versions 1.6.4 ... 1.7.2.) are responsible for a large portion of the `"urn:ietf:params:acme:error:malformed"` type error responses to newOrder requests. The majority of these have the detail message `"Error creating new order :: DNS name ends in a period"` indicating there is probably a common mis-configuration at work Traefik might be able to address.

### What did you expect to see?

The Traefik user-agent not being a dominant source of malformed errors in our logs :-)

### What did you see instead?

Many malformed errors being returned to Traefik users indicating that a newOrder request was received containing identifiers with a trailing period character, not a valid domain name.

I expect this is a result of browsers/HTTPS user-agents sending a request to a domain with a trailing period backed by a Traefik instance that doesn't strip the trailing period before creating an order with Lego/Let's Encrypt. It probably makes sense for Traefik to be responsible for stripping that trailing period instead of handling that corner-case in Lego.

### Output of `traefik version`: (_What version of Traefik are you using?_)

N/A, in the last 3 days of logs I see versions 1.6.4 through 1.7.2 represented.

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

N/A

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

N/A

**Comment by ldez** [comment]
:wave: Hello @cpu, do you have more information about the type of challenge or additional information?

**Comment by cpu** [comment]
> do you have more information about the type of challenge or additional information?

What kind of information would be most helpful? I can't say anything about the type of challenge based on the failed requests alone because the issuance process is failing at the time of `newOrder`, e.g. before any authorizations are created or challenges POSTed.

I've spot checked a couple of the problematic source IP addresses and can only see these malformed responses. No successful issuances to guess at the deployed challenge mode.

Looking at one Traefik 1.7.0 user I see ~40-60 `urn:ietf:params:acme:error:malformed` responses to `newOrder` every minute for the past 7+ days. The rejected identifiers are all of the form `"<word>.example.com."`, that is, many individual sub-domains off a base domain with a trailing dot. Maybe in this one case someone is bootstraping their Traefik instance with certificates by moving through a wordlist making requests in a way that's sending a host header value with a trailing dot that Traefik/Lego are passing along un-changed to the ACME API when attempting issuance?

**Comment by ldez** [comment]
I'm trying to see if this needs to be corrected in Lego or Traefik. :thinking:

**Comment by ldez** [comment]
I made a fix for the future version v1.7.3.
I hope users will update their Træfik.

Sorry for this large portion of errors in your logs :disappointed_relieved: 

Keep me informed of the evolution of the situation :phone:.

**Comment by traefiker** [comment]
Closed by #4015.

**Comment by cpu** [comment]
@ldez Thanks for the quick fix! Much appreciated :-)
