### ISSUE TITLE
Mutual authentication using client certificate

### ISSUE THREAD

**Issue by joost-van-weenen** [containous/traefik#402]
Hi,

Is it possible to authenticate clients with their public certificate to achieve mutual authentication? If so could you please provide a configuration snippet?

Joost van Weenen

**Comment by joost-van-weenen** [comment]
I'm not sure, but maybe this is a duplicate of #364??

**Comment by joost-van-weenen** [comment]
As a workaround we could place nginx in front of traefik. I have found that nginx doesn't scale well out of the box. If traefik can't do the client authentication then maybe we need to use both at this point in time.

**Comment by emilevauge** [comment]
Hi @joost-van-weenen, sorry for the delay... For now, traefik doesn't support mutual certificate authentication.

**Comment by joost-van-weenen** [comment]
Thanks for the reply! For now iam using nginx in front of Traefik purely for the secure authentication. It works great :) This way we can stil use the great dynamic scaling of Traefik.

**Comment by djtm** [comment]
This seems to be resolved for the entrypoint in #461.

**Comment by ldez** [comment]
I'll close this issue, because I think the question is answered, but feel free to continue the conversation.

**Comment by samgurtman** [comment]
Is there any way to pass the client certificate or subject name in a header to the backend? This would be useful to perform authorization.

**Comment by salzig** [comment]
@samgurtman: Nginx uses variables to store the information. You could pass them further down the line as headers. 
>  The verification result is stored in the $ssl_client_verify variable.
  http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_verify_client

> The contents of the certificate is accessible through the $ssl_client_cert variable.
  http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_verify_client

```
proxy_set_header X-SSL-Client-Verify $ssl_client_verify;
proxy_set_header X-SSL-Client-Cert $ssl_client_cert;
```

@ldez would a nice feature to have this without nginx in front. Is there a feature request issue to follow you know of?
