### ISSUE TITLE
Support IP blacklisting

### ISSUE THREAD

**Issue by negz** [containous/traefik#4026]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?
Traefik currently supports IP whitelisting at the entrypoint level. I'd like to be able to support blacklisting. It seems like such a feature would be fairly straightforward; I'd be happy to contribute it if there were interest.

For further context; I'm considering how a GeoIP database might be used to block certain requests by IP address at Traefik. These databases tend to have particular file formats, and are occasionally updated. One approach would be to build a specific GeoIP middleware that could read these databases (and ideally reload them without reloading Traefik), but it seems like a simple blacklist functionality might be a good first step in this direction.

**Comment by RRAlex** [comment]
A way to reload the configuration live, with specific blacklisting for a given k8s ingress (based on some logs or a trigger from fail2ban, etc) would be very useful to many I'm sure!

**Comment by HitkoDev** [comment]
I currently use HAProxy with confd in front of Traefik, to fetch blacklisted IPs from etcd. That obviously ads a lot of overhead compared to proposed solution, especially since Traefik instances already connect to the same etcd instance.

**Comment by aido93** [comment]
Guys, what's about geoip? Is this feature in plans or in progress? If someone has already begun this work I can help.

**Comment by hb3b** [comment]
GeoIP/Maxmind support would be helpful to us.

**Comment by joeldeteves** [comment]
GeoIP blocking would be very useful

**Comment by H2so4** [comment]
I have a quick write-up on how to use the ForwardAuth middleware to block a list of IPs https://scaleup.us/2020/06/21/how-to-block-ips-in-your-traefik-proxy-server

I really hope this is built in soon. Traefik is a great modern tool.

This can easily be modified to do blocking based on GeoIP.

**Comment by notsureifkevin** [comment]
Greetings! I wrote a Traefik Plugin for this use case specifically -- feel free to try it out!

https://pilot.traefik.io/plugins/272416229286740480/deny-ip-plugin
