### ISSUE TITLE
Istio mTLS support

### ISSUE THREAD

**Issue by courcelm** [containous/traefik#4035]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Is it possible in any way to use Istio service mesh (with mTLS)?

**Comment by dtomcej** [comment]
Hello @courcelm, We have looked into the feasibility of using traefik in Istio. Unfortunately, although theoretically possible, the amount of work required to accomplish the task would be quite high, as all of the api calls would have to be translated, and envoy functionality would have to be duplicated.

It is unlikely that we would be able to dedicate the time to make traefik a drop in replacement.

Thanks!

**Comment by ndeloof** [comment]
for the record, nginx has such a replaceable component as nginmesh.
This one uses an agent to translate [istio pilot API](https://github.com/nginxinc/nginmesh/blob/master/istio/agent/pilot/client.go) into nginx configuration.

Being written in Go, it sounds to me it would be easier for traefic to just implement [pilot API](https://github.com/istio/api/blob/master/mesh/v1alpha1/proxy.pb.go), assuming concepts can apply to traefic features.
