### ISSUE TITLE
Support for custom frontend redirect codes

### ISSUE THREAD

**Issue by danielrs** [containous/traefik#4040]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Currently, frontend redirects only support the `permanent` option which maps to either 301 or 302. However, I think we need to be able to specify which code to use for some cases e.g. POSTing to a redirected URL only works with 307 redirect.

**Comment by dm17** [comment]
Now: how to use them? I'm trying to do a 307 redirect.

**Comment by ldez** [comment]
Fixed by #4116
