### ISSUE TITLE
Documentation: docker provider and configuration parameter domain is not required

### ISSUE THREAD

**Issue by thernstig** [containous/traefik#4056]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Read the documents at https://docs.traefik.io/configuration/backends/docker/#docker and https://docs.traefik.io/configuration/backends/docker/#docker-swarm-mode

In normal docker mode (link 1) it says that `domain` is mandatory. In docker swarm modle (link 2) it says it is optional.

I believe the correct answer is that both should be optional.

**Comment by traefiker** [comment]
Closed by #4086.
