### ISSUE TITLE
Documentation: The word "provider" is used but not fully explained

### ISSUE THREAD

**Issue by thernstig** [containous/traefik#4058]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Read _all_ documentation at https://docs.traefik.io/

Having read all documentation, it most refers to the term "provider" just once on https://docs.traefik.io/ and just once https://docs.traefik.io/basics/. There is no real explanation of what a provider is or what it solves in general.

Also, looking the table of contents (on the left) and expanding "Configuration" and clicking one of the "Providers" have the URL have the term "backends" in it e.g. https://docs.traefik.io/configuration/backends/docker/

There is no easy way to understand the distinction between a provider and a backend in the documentation.

**Comment by thernstig** [comment]
I would also suggest that if the "backends" part is changed to "providers" in the URL, you also sub-categorize the sections under the table of content "Configuration" part so that providers gets its own section, and that possibly all other sections are moved to the top. This is to easily dinstiguish them.

**Comment by ldez** [comment]
We did not change the URL in order to not break links after we rename backend to provider.

**Comment by thernstig** [comment]
@lidez Maybe you could still keep the old links, but have them re-direct to new links. That way both works. From a pedagogical standpoint it is most likely best to have the new term going forward.

**Comment by ldez** [comment]
The documentation is a simple Github page, we cannot set a redirect.

**Comment by thernstig** [comment]
@ldez Oh, that's a shame. It will most likely have more people wonder going forward.

**Comment by thernstig** [comment]
@geraldcroes That is an excellent idea. It struck me as well that it was a possibility but I forgot to post it. I think it is definitely worth to do as an URL nowadays usually tell a lot about what kind of content you are reading. Not to mention SEO.

**Comment by thernstig** [comment]
@dduportal You might want to check if this is solved in 2.0, and if so, closed.

**Comment by dduportal** [comment]
Good catch @thernstig !

The page https://docs.traefik.io/v2.0/providers/overview/ answers your initial request: closing this issue.

Thanks a lot!
