### ISSUE TITLE
Docker rule for automatic domain with custom service name 

### ISSUE THREAD

**Issue by koliyo** [containous/traefik#4067]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I would like to customize the `traefik.frontend.rule` without specifying the domain explicitly.
eg something like

```
traefik.frontend.rule: HostPrefix: whoami
```

Right now if I do not specify anything I get `myservice-whoami.${my-domain}` automatically, according to https://docs.traefik.io/configuration/backends/docker/
> Overrides the default frontend rule. Default: Host:{containerName}.{domain} or Host:{service}.{project_name}.{domain} if you are using docker-compose.

But I want to set this to `whoami.${my-domain}` without specifying the domain.

Maybe this is already possible?

Or some way of declaring that host rule should resolve to `${traefik.backend}.${my-domain}`

**Comment by ldez** [comment]
Seems like a duplicate of #2578

**Comment by koliyo** [comment]
Yes, thanks, did not find that issue!
