### ISSUE TITLE
Aliases leaking into Consul KV Paths

### ISSUE THREAD

**Issue by sybrandy** [containous/traefik#407]
Hello,

I'm trying out traefik for the first time and I'm trying to get atomic updates working for Consul.  I have everything set up according to the documentation, however I'm running into a very strange bug.  If I put my configurations in /configs and reference them as "/configs/1", consul looks for paths like the following:

    /configs/1/backends/configs/servers/
    /configs/1/frontends/configs/routes/

These are not defined anywhere and I don't want them.  I thought I could dummy up some values, but that didn't work.  I did a quick search of the source for references to the alias, but I only saw that when getting the prefix, so I'm not sure what's going on.

My consul config is very simple:

    [consul]
    endpoint = "<consul_host:port>"
    watch = true
    prefix = traefik

Am I doing something wrong or is this just a weird bug?

**Comment by emilevauge** [comment]
@sybrandy this is strange... Could you give us you toml file? And your traefik logs?

**Comment by emilevauge** [comment]
Maybe linked to #411

**Comment by sybrandy** [comment]
@emilevauge Hey, sorry...I got really busy at work.  Unfortunately, I don't have the logs any more, but if/when I get back to using traefik and consul, I'll keep any eye out for it.

Again, sorry...priorities change.

**Comment by sybrandy** [comment]
O.K.  It looks like this is still happening.  I get warnings/errors that look like this:

    "Error getting key /traefik_prefix/1/frontends/traefik_prefix/backend..."

The consul config in my toml looks like this:

    [consul]
    endpoint = "<consul-sever>:<port>"
    watch = true
    prefix = "traefik"

In the current scenario, I'm trying to set this up to use the /traefik/alias to allow for atomic config changes, hence why the path in the error message is different from the configured prefix.

**Comment by sybrandy** [comment]
O.K.  I found the bug, but I'm not sure what the correct fix is.  In kv.go, the list method loops over kvPairs.  For each Key, the TrimPrefix method is used to remove the value of joinedKeys from the start of the string, then the remaining value is split and only the first part is kept.  This trimming of the prefix is failing in my case because the Key does not start with a "/" while the joinedKeys does start with a "/".

For example, let's say I have the path /traefik_test/1/frontends/ and one of the frontends is called github.  Now, I pass in /traefik_test/1/frontends/ to kv.list.  I get they key from Consul (traefik_test/1/frontends/github/), try to strip the key, which produces traefik_test/1/frontends/github/ since it doesn't start with a "/".  Then, this string is split on "/" and the first element is captured (traefik_test).  This gets appended to the provided path, which results in /traefik_test/1/frontends/traefik_test.

Now, I don't know if the kvclient.List method is working properly or not.  In my case, I put a fix in to simply ensure that both the Key and joinedKeys do not start with "/" and it seems to work so far.  However, this is a bit of a hack, IMHO.  The way I see it, there are 3 ways to fix this:

1. Have the kvclient code updated to ensure paths always start with a "/".  May/may not be correct.  I haven't played with it at all and I haven't used the other KV providers, so I can't say.
1. In the list method, ensure that any Keys returned by kvclient.List start with a "/".
1. Implement my hack.  It didn't require any additional variables or if statements, so it seemed reasonable.

Anyway, I'll let you decide which is correct.  I honestly wonder if the kvclient is working properly, but it may be best to assume that this can occur and ensure that the strings are always correct in your code.

**Comment by mikey179** [comment]
I just had the same problem while trying to get it running using the configuration described in [atomic configuration changes](https://docs.traefik.io/toml/#atomic-configuration-changes). After lots of investigation I got it to work by setting `traffic/alias` to a value which does **not** start with `/`, i.e. with `traefik_configurations/1` it works, but with `/traefik_configurations/1` as described in the documentation I get the behavior described by @sybrandy.
