### ISSUE TITLE
FR: Put headers in normal case for 'staying with the norm' 

### ISSUE THREAD

**Issue by EugenMayer** [containous/traefik#4073]
### What did you expect to see?
 - Headers like "Location: " to be upper case

### What did you see instead?
All in lower case
```
HTTP/2 302
content-type: text/html; charset=utf-8
date: Thu, 18 Oct 2018 10:20:47 GMT
location: /sky/issuer/auth/ldap?req=xxxx
x-content-type-options: nosniff
x-download-options: noopen
x-xss-protection: 1; mode=block
content-length: 74
```

### Output of `traefik version`: (_What version of Traefik are you using?_)
1.7.3

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

- docker based

I would expect the configuration to be not interesting here.

I am not sure if this is considered a FR, Glitch, expected or by design, please downgrade / upgrade as you need.

**Comment by voidengineer** [comment]
RFC 2616, Paragraph 4.2 states that http headers are case-insensitive, so it should not matter.

**Comment by EugenMayer** [comment]
Ah, ok - then the implementation i used was just not following the RFC. 

Little hint: I had this service behind HAproxy beforehand and the case was "usual case", so first letter big case. so this is a HAproxy to Traefik migration issue for me.

I understand, that RFC defines it is valid, but maybe it safes some peoples time by sticking to the "norm"? It's fixed by me, fixed the falsy implementation of mine, but maybe that is a quick-win for you helping more people in the transition.

My use case was: using curl to get a form token parsing the headers for and OAuth case.

**Comment by kachkaev** [comment]
In Express (popular node.js web server) the headers are lowercase. So the “norm” is different and depended on where you are looking at it from.

IMO lowercase-only headers make life a lot easier because naming ‘the rule of thumb’ you have to keep in your head is extremely simple. Otherwise, is the cap “just the first letter” or “every letter after -“ or “every start of a new word” or “every new word except in abbeviations”?

**Comment by EugenMayer** [comment]
I am not really make a choice for the better here, just what i experienced for now, AFAICS:
 - nginx
 - haproxy
 - lighthttpd
 - apache

Seem to put them in first letter upper. But really, i have no buy in into this, whatever suits best for Traefik.

**Comment by ldez** [comment]
duplicate of #1756
