### ISSUE TITLE
Documentation: Dashboard incorrectly called admin panel

### ISSUE THREAD

**Issue by thernstig** [containous/traefik#4077]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

In the section here https://docs.traefik.io/configuration/api/#address-port it the **dashboard** is refered to as an **admin panel.** This is the only place in the documentation where it is called admin panel. In all other instances it is called dashboard. As such, it is probably best to rename for coherency and to decrease confusion.

**Comment by ldez** [comment]
We will happy if open a pull request on this point.
The documentation is here: https://github.com/containous/traefik/tree/master/docs

**Comment by thernstig** [comment]
@ldez I will try to do this next week if noone has taken upon themselves to fix this, as I have to head out right now.

**Comment by traefiker** [comment]
Closed by #4156.
