### ISSUE TITLE
Documentation: Distinction between static and dynamic Traefik configuration is ambigous

### ISSUE THREAD

**Issue by thernstig** [containous/traefik#4078]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Regarding this section: https://docs.traefik.io/v1.7/basics/#configuration

- The heading "Static Traefik configuration" reads: "The static configuration is the global configuration which is setting up connections to configuration backends and entrypoints." At the same time, the heading "Dynamic Traefik configuration" says "backends" in one of the lists. As such, one is made to believe both can configure backends. It is likely one of these want to refer to the term "provider"? See also #4058 
- The heading "Dynamic  Traefik configuration"  mentions that "servers" is part of it. But servers is not a term on the same level as frontends and backends that are also mentioned in the list. Actually, in many providers (such as docker) the term "server" is never even used. I am thus wondering if "servers" should be removed from that list, due to that servers are part of the [file] provider.

**Comment by andrewmclagan** [comment]
Im actually confused about what dynamic and static even means in this concept.

**Comment by dduportal** [comment]
With Traefik v2.0, the documentation had been revamped and is defining these 2 concepts: https://docs.traefik.io/v2.0/getting-started/configuration-overview/
