### ISSUE TITLE
Documentation: The term "commons" is used in the table of contents but not in any documentation

### ISSUE THREAD

**Issue by thernstig** [containous/traefik#4079]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

In the documentation, the table of contents on the left side contains the word "Commons" (underneath Configuration". When clicking the link you come to https://docs.traefik.io/configuration/commons/ that has the heading "Global Configuration."

The term "commons" is never used anywhere else in the entire documentation at https://docs.traefik.io/ as far as I am aware. As such, it needs to change to reflect its real intent.

**Comment by dtomcej** [comment]
Hello @thernstig,

Since Traefik v2 has been released, we completely reconfigured how the documentation is structured.

As such, this issue is not applicable, and I will close it.
