### ISSUE TITLE
mDNS/zeroconf support

### ISSUE THREAD

**Issue by rdehuyss** [containous/traefik#4092]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I'm using traefik for my home-assistant setup using docker-compose and labels. One thing I'm missing is mDNS support (e.g. going to traefik using something like homeassistant.local).

Here somebody is doing it for mailcather (https://github.com/hausgold/docker-mailcatcher). Would be great if we could configure traefik to add a certain hostname with which it then would be available on the local network.

Is it possible to add this feature?

**Comment by ldez** [comment]
seems to be a duplicate of #1205 or #1191

**Comment by teohhanhui** [comment]
Actually not a duplicate, as this is about mDNS/DNS-SD (e.g. Avahi), which is a much cleaner solution than having to run a DNS server in Traefik or on the host.
