### ISSUE TITLE
Kubernetes backend configuration is unclear

### ISSUE THREAD

**Issue by jimmycuadra** [containous/traefik#410]
I'm trying to use Traefik as a Kubernetes ingress controller, but I'm getting an error and I am not able to figure out what might be wrong with my configuration from the Traefik documentation.

Any help figuring out the issue here or improved documentation about the expected configuration for all these various resources would be much appreciated! Let me know if there's other information I can provide to help diagnose.

Traefik version: v1.0.0-beta.704 (via official Docker image)
Traefik itself is running in the default Kubernetes namespace.

The error appearing in Traefik's logs is:

```
time="2016-05-25T21:51:09Z" level=error msg="Error loading new configuration, aborted Undefined backend: foo.example.com"
```

Here's the full log with debug logging enabled: https://gist.github.com/jimmycuadra/9a5ef319796d6b1dc73a401946b07a4a

traefik.toml:

``` toml
defaultEntryPoints = ["http", "https"]

[entryPoints]

[entryPoints.http]
address = ":80"

[entryPoints.http.redirect]
entryPoint = "https"

[entryPoints.https]
address = ":443"

[entryPoints.https.tls]

[[entryPoints.https.tls.certificates]]
CertFile = "/etc/ssl/cert.pem"
KeyFile = "/etc/ssl/key.pem"

[kubernetes]

[web]
address = ":8080"
ReadOnly = true
```

I also tried setting kubernetes.namespaces to an empty array, since from looking at the code it seems it will read ingresses from all namespaces if and only if that array is empty. But again, the documentation doesn't explain this so I'm not totally sure. In either case, both the default value and an empty array produce the same error.

The ingress resource I'm attempting to fulfill:

``` yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  creationTimestamp: 2016-05-25T00:44:03Z
  generation: 1
  name: foo
  namespace: foo
  resourceVersion: "1122189"
  selfLink: /apis/extensions/v1beta1/namespaces/foo/ingresses/foo
  uid: c7861949-2211-11e6-a0d7-064f66afdabf
spec:
  rules:
  - host: foo.example.com
    http:
      paths:
      - backend:
          serviceName: foo
          servicePort: http
status:
  loadBalancer: {}
```

The service it points to:

``` yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2016-05-25T00:44:03Z
  name: foo
  namespace: foo
  resourceVersion: "1122187"
  selfLink: /api/v1/namespaces/foo/services/foo
  uid: c756d03b-2211-11e6-a0d7-064f66afdabf
spec:
  clusterIP: 10.3.0.241
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: foo
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

**Comment by errm** [comment]
Hey @jimmycuadra I have been working on some documentation for k8s for a few days, I will let you know when I am done.

Regarding you configuration, it seems like traefik is not getting the backend configuration (the service) from kubernetes properly.  You may wan't to double check that your service is up properly....

**Comment by jimmycuadra** [comment]
The service is definitely up. A couple things I see that might be a problem, but I'm not sure if they matter:

1. The service is not in the same namespace as the ingress controller. The controller is in the default namespace, but the service (as well as the pods and the ingress resource that go with it) are in the "foo" namespace.
2. The error in the logs report that there is no backend "foo.example.com" but that is not the name of the service. The name is just "foo". I'm not sure whether the error message means that it's looking for a service with the name "foo.example.com" or it's just printing the hostname it matched and it really means "no backend for frontend 'foo.example.com'"

**Comment by jimmycuadra** [comment]
It also might be helpful to note that the response from the `/api` endpoint on Traefik's own API just returns an empty JSON object: `{}`.

**Comment by errm** [comment]
The reason is that you are referring to the service port by name and not number.  I fixed this in #380.  If you upgrade to version v1.0.0-beta.723 or above your issue should be fixed.

Sorry I didn't notice any earlier :(

**Comment by ekozan** [comment]
using text on `servicePort: ` is just not compilant with the spec ( in 1.2 )

`A backend is a service:port combination as described in the services doc.`

```go
type ServicePort struct {
	// The name of this port within the service. This must be a DNS_LABEL.
	// All ports within a ServiceSpec must have unique names. This maps to
	// the 'Name' field in EndpointPort objects.
	// Optional if only one ServicePort is defined on this service.
	Name string `json:"name,omitempty" protobuf:"bytes,1,opt,name=name"`

	// The IP protocol for this port. Supports "TCP" and "UDP".
	// Default is TCP.
	Protocol Protocol `json:"protocol,omitempty" protobuf:"bytes,2,opt,name=protocol,casttype=Protocol"`

	// The port that will be exposed by this service.
	Port int32 `json:"port" protobuf:"varint,3,opt,name=port"`

	// Number or name of the port to access on the pods targeted by the service.
	// Number must be in the range 1 to 65535. Name must be an IANA_SVC_NAME.
	// If this is a string, it will be looked up as a named port in the
	// target Pod's container ports. If this is not specified, the value
	// of the 'port' field is used (an identity map).
	// This field is ignored for services with clusterIP=None, and should be
	// omitted or set equal to the 'port' field.
	// More info: http://releases.k8s.io/HEAD/docs/user-guide/services.md#defining-a-service
	TargetPort intstr.IntOrString `json:"targetPort,omitempty" protobuf:"bytes,4,opt,name=targetPort"`

	// The port on each node on which this service is exposed when type=NodePort or LoadBalancer.
	// Usually assigned by the system. If specified, it will be allocated to the service
	// if unused or else creation of the service will fail.
	// Default is to auto-allocate a port if the ServiceType of this Service requires one.
	// More info: http://releases.k8s.io/HEAD/docs/user-guide/services.md#type--nodeport
	NodePort int32 `json:"nodePort,omitempty" protobuf:"varint,5,opt,name=nodePort"`
}

```

but actually it's work but dont know if it's normal ^^

```go
type IngressBackend struct {
	// Specifies the name of the referenced service.
	ServiceName string `json:"serviceName"`

	// Specifies the port of the referenced service.
	ServicePort intstr.IntOrString `json:"servicePort"`
}
```

**Comment by jimmycuadra** [comment]
Ah ha! Switching the port name to the port number got rid of the error, and now both the frontend and backend are showing up in Traefik's API.

Now when I curl the external URL from outside the cluster, I get an SSL handshake error:

```
$ curl -i -v https://foo.example.com/lita/info
*   Trying <redacted IP>...
* Connected to foo.example.com (<redacted IP>) port 443 (#0)
* Server aborted the SSL handshake
* Closing connection 0
curl: (35) Server aborted the SSL handshake
```

I don't see anything at all in Traefik's logs. I want it to terminate SSL at Traefik before forwarding the request to the service over plain HTTP. Do I have another configuration problem causing this? Here's the output of Traefik's `/api` endpoint:

``` json
{
  "kubernetes": {
    "backends": {
      "foo.example.com": {
        "servers": {
          "c756d03b-2211-11e6-a0d7-064f66afdabf": {
            "url": "http://10.3.0.241:80",
            "weight": 1
          }
        },
        "loadBalancer": {
          "method": "wrr"
        }
      }
    },
    "frontends": {
      "foo.example.com": {
        "entryPoints": ["http", "https"],
        "backend": "foo.example.com",
        "routes": {
          "foo.example.com": {
            "rule": "Host:foo.example.com"
          }
        },
        "passHostHeader": true
      }
    }
  }
}
```

Thanks for the help on this.

**Comment by jimmycuadra** [comment]
Any ideas on the SSL handshake error? Should I open a new issue for that? It may not be related to the original issue.

**Comment by jimmycuadra** [comment]
The problem with SSL was not Traefik, it was ports we hadn't allowed from our ELB to the cluster. Very sorry for the trouble and thank you for the help figuring out the original issue!
