### ISSUE TITLE
case insensitive match service name

### ISSUE THREAD

**Issue by xaclincoln** [containous/traefik#4100]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Hi, I'm trying traefik with consul catalog. After creating a service named CustomerConfig (Pascal style service name)  in the consul, the dashboard always show a front-end named customerconfig which lowercase all letters. And more important,  when a HTTP client send a request to http://host.com/CustomerConfig, a 404 is always returned . The traefik log  said: backend CustomerConfig not found.  If the url is changed to  http://host.com/customerconfig, 200 is returned.  My traefik version is 1.7.0.
I'm wondering is it feasible to support matching service name case insensitively, since CustomerConfig is more readable than customerconfig, especially for long service names?  I have no idea  whether it is  by design or for other unknown reasons, so i issue a feature request.

**Comment by Jaans** [comment]
Case sensitivity on PathPrefix rule bit me today. Unfortunately nothing in the documentation 1.7 made this clear.

How do I use path prefix **without** case sensitivity?

**Comment by rkodey** [comment]
> How do I use path prefix **without** case sensitivity?

Just to get an answer in the books...  Standard inline flags seems to be supported by the regex engine, so (?i:) works for case-insensitive matching:
```
rule: "PathPrefix(`/{path:(?i:customerconfig)}`)"
```

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Community Forum](https://community.containo.us/).
