### ISSUE TITLE
Weird Unicode characters on Docker example on the Homepage

### ISSUE THREAD

**Issue by falsovsky** [containous/traefik#4102]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Open the Oficial site: https://traefik.io/

Find "Easy To Install", click on "Docker Image".

The example command there is filled with the Unicode char "Zero Width Space" (http://www.fileformat.info/info/unicode/char/200b/index.htm) and if you copy and paste that to a terminal the command wont work because of that weird char in the example.

Do an Inspect element to see.

### What did you expect to see?

The command without the "Zero Width Space" after each "/"

### What did you see instead?

A command that isnt possible to execute because of weird unicode chars in it.

### Output of `traefik version`: (_What version of Traefik are you using?_)

Doesnt matter.

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Doesnt matter.

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

Doesnt matter.

**Comment by falsovsky** [comment]
Screenshot

![bug](https://user-images.githubusercontent.com/142947/47434680-ee6f3100-d79a-11e8-8991-c9b3f221c522.jpg)

**Comment by falsovsky** [comment]
Ahh, and another problem there on that example. It is missing a "-v /var/run/docker.sock:/var/run/docker.sock"

**Comment by geraldcroes** [comment]
Hi @falsovsky : Nice catch!

We were using the empty space so that the text would be nicely wrapped depending on screen sizes ... but we forgot the copy/paste issue in the process!

This is now fixed. Thanks for taking the time to point the issue.
