### ISSUE TITLE
Exclude docker backends from ACME

### ISSUE THREAD

**Issue by fearlsgroove** [containous/traefik#4103]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I'm using traefik in front of a multi tenant platform, configured with many public domains using docker swarm. I want to leverage Traefik's automagic ACME/Let's  Encrypt support for the domains to which it applies. Since I don't control DNS for these domains, I can't use a DNS challenge. Some domains may not yet be pointed at the right IP, and it testing scenarios none of the domains have the IP setup for public consumption yet.

This means lets encrypt/ACME fails to resolve http challenges, which leads to rate limits failures.

I'd love to be able to use docker labels to exclude domains from acme (or vice versa, to opt them in) so that we're only solving domains that we can be reasonably sure will succeed.

**Comment by ldez** [comment]
Similar to #3868
