### ISSUE TITLE
Multiple basic auth entries with same username

### ISSUE THREAD

**Issue by koliyo** [containous/traefik#4109]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
Looks like basic auth entries are overwritten when using multiple entries for the same username?

I want multiple passwords for same user.

I am using `traefik.frontend.auth.basic.users`

### What did you expect to see?
Use all the provided entries

### What did you see instead?
Only last entry was used for the username

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
(paste your output here)
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# (paste your configuration here)
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
(paste your output here)
```

**Comment by dtomcej** [comment]
Hello @koliyo,

Looking at RFC 7617 and 2617, it is not obvious that a user can have multiple passwords with basic auth. However, it does not seem explicit that a user _cannot_ have multiple passwords.

Can you provide us an RFC section that would suggest that this is possible?

If so, we can have it implemented, but are hesitant to do so without an RFC to go off of.

Thanks!

**Comment by koliyo** [comment]
I think you are right! I assumed this was possible, but seems like it is not supposed to work. An error message / warning would be nice though :)

Thanks for feedback!
