### ISSUE TITLE
Traefik is not using consul tags properly.

### ISSUE THREAD

**Issue by Armatorix** [containous/traefik#4110]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
I'm using docker container with Traefik:1.7.3-alpine in my stack with config:
```
defaultEntryPoints = ["https"]
[entryPoints]
    [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]
        ...
[consulCatalog]
    endpoint = "$NGINX_CONSUL"
    exposedByDefault = false
    watch=true
    [consulCatalog.tls]
        ...
        insecureSkipVerify = true
[api]
  entryPoint = "traefik"
  dashboard = true
  debug = true
```

And I've got some services registered to this consul.
So with these tags, the service is not showing in traefik: 
```
dumbTag traefik.frontend.rule=Host: example.com.traefik traefik.protocol.https traefik.enable=true
```
When I move my dumbTag at the end, so it looks like here:
```
traefik.frontend.rule=Host: example.com.traefik traefik.protocol.https traefik.enable=true dumbTag
```
then it works fine
### What did you expect to see?
Traefik should check all tags, despite their order.

**Comment by ldez** [comment]
Your tags have syntax errors (extra whitespace, missing `=`), try this:
```
dumbTag traefik.frontend.rule=Host:example.com.traefik traefik.protocol=https traefik.enable=true
```

**Comment by Armatorix** [comment]
Yup, my bad. Sry. 
Anyway, strange that in one case (even with syntax errors) it was working...
