### ISSUE TITLE
Traefik Service Weights on Kubernetes should support services that specify an External Name

### ISSUE THREAD

**Issue by dchw** [containous/traefik#4119]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I need to transition services from outside Kubernetes to inside. I tried using service weights to canary test traffic into the cluster, but Traefik seems to expect actual endpoints on the service. However, an [externalName](https://kubernetes.io/docs/concepts/services-networking/service/#externalname) service doesn't have endpoints, but instead just routes traffic to the domain specified.

I was surprised that these _didn't_ work with service weights, as Traefik seems just fine to send traffic in all other instances where we are using externalName services.

**Comment by yue9944882** [comment]
@dchw thx for reporting the bug

will open a fix for that

**Comment by traefiker** [comment]
Closed by #4135.
