### ISSUE TITLE
Custom Error page additional queries are prefixed with request path.

### ISSUE THREAD

**Issue by darkl0rd** [containous/traefik#4163]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
Setup a custom error page on a service using Docker labels.
```
deploy:
  labels:
        - "traefik.frontend.errors.all.status=404"
        - "traefik.frontend.errors.all.query=/index.html"
        - "traefik.frontend.errors.all.backend=traefik-errorpage"
```

### What did you expect to see?
When browsing to https://valid.frontend.rule/some/garbage, that the custom error page, including all resources it refers to, would be served from the backend "traefik-errorpage"

### What did you see instead?
Only the index.html page is rendered, the relative resources it refers to (e.g. img/404.png) are not being looked up correctly, but rather get the original request path prefixed (e.g. /some/garbage/img/404.png)

### Output of `traefik version`: (_What version of Traefik are you using?_)
1.7.4

**Comment by dduportal** [comment]
Hi @darkl0rd , thanks for your interest in this project.

The behaviour you describe is exactly what is described on the w3c contents: <https://www.w3schools.com/html/html_filepaths.asp> :

| Path | Description|
|-- | --|
|`<img src="picture.jpg">` | picture.jpg is located in the same folder as the current page|
|`<img src="images/picture.jpg">` | picture.jpg is located in the images folder in the current folder|
|`<img src="/images/picture.jpg"> `| picture.jpg is located in the images folder at the root of the current web|
|`<img src="../picture.jpg">` | picture.jpg is located in the folder one level up from the current folder|

What is the absolute URL for the `img/404.png` file should be accessed to?
Based on this value, you might want to adapt the relative path by prepending a `/` to `img/404.png` ?


Another solution might be to use the markup `<base>` : <https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base>.

**Comment by darkl0rd** [comment]
I think my example might require some further clarification:

contents of index.html:

```<img src="/img/404.png"```

I'm hitting a working Traefik frontend at "http://my.frontend", to then test my custom error page, I change this URL to something which does not exist and thus returns a 404 (like http://my.frontend/garbage).
The "index.html" located at traefik-errorpage (http://traefik-errorpage/index.html) is served correctly, however all the resources referred to by index.html (e.g. /img/404.png) are being looked up in /garbage/img/404.png instead. I would not expect /garbage to be prepended to the requests.

**Comment by darkl0rd** [comment]
In addition to the above:

* Using absolute URL's which use the internal service name results in timeouts, as it seems the request is not being proxied to the error backend but rather a direct GET is being performed by the client browser.
* Using absolute URL's with the external service name works; this however means that all resources would require the full URL to be prepended for each resource in the HTML.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Slack workspace](https://traefik.herokuapp.com/) for more [community #support](https://traefik.slack.com/messages/C0CDT22PJ/).
