### ISSUE TITLE
Grammar error on front page of traefik.io

### ISSUE THREAD

**Issue by rjw57** [containous/traefik#4164]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Visit https://traefik.io/

### What did you expect to see?

Information on Traefik free from typos or grammar errors.

### What did you see instead?

> A reverse proxy / load balancer that's easy, dynamic, automatic, fast, full-featured, open source, production proven, provides metrics, and **integrates with every major cluster technologies**... 

I would expect to see "integrates with all major cluster technologies" or "integrates with every major cluster technology".

### Output of `traefik version`: (_What version of Traefik are you using?_)

NA

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

NA

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

NA

**Comment by geraldcroes** [comment]
Thank you for pointing that out! 

I'm a bit embarrassed (I'm the culprit), but now that it is fixed, I feel better ^^

**Comment by rjw57** [comment]
No probs - I only noticed it myself because a colleague pointed it out.
