### ISSUE TITLE
Does traefik supports for Mac? (For devlelopment) 

### ISSUE THREAD

**Issue by kumarsiva07** [containous/traefik#417]
Does traefik supports for Mac ?

**Comment by emilevauge** [comment]
It should. Do you have any issue, or are you just asking?

**Comment by kumarsiva07** [comment]
How do I compile the source in Mac?  Executable not available for Mac.

**Comment by emilevauge** [comment]
There is a documentation on how to build it here: https://github.com/containous/traefik/blob/master/.github/CONTRIBUTING.md#building

**Comment by emilevauge** [comment]
Can I close this one ?

**Comment by kumarsiva07** [comment]
Yes

On 1 June 2016 at 01:47, Emile Vauge <notifications@github.com> wrote:

> Can I close this one ?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/containous/traefik/issues/417#issuecomment-222807101>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHXgdlJ1oMPDKrAIgE1GNkr3Ph4YJOiHks5qHJdtgaJpZM4IpOFO>
> .
>



-- 
Regards,
*Kumar SIVA <http://www.facebook.com/kumarsiva07>*
