### ISSUE TITLE
support more than one rule to Docker backend

### ISSUE THREAD

**Issue by NicolasGeraud** [containous/traefik#419]
Hi,

Traefik is awesome and it could be useful if supported more than 1 rule for docker backend.

I have 3 containers and I want to access to them via those urls :
demo.gravitee.io -> service1
demo.gravitee.io/api -> service2
demo.gravitee.io/gateway -> service3

The "theorical" way to achieve that is using those labels : 
service 1: `Host:demo.gravitee.io`
service 2: `Host:demo.gravitee.io` `PathPrefix:/api`
service 3: `Host:demo.gravitee.io` `PathPrefix:/gateway`

Do you think allow more than 1 rule for docker backends could be useful ?

**Comment by emilevauge** [comment]
Of course it could be useful :+1:

**Comment by vdemeester** [comment]
@emilevauge is this only for docker backend though ?

**Comment by emilevauge** [comment]
@vdemeester for docker / marathon / consul services / kubernetes (every backend using labels/tags for creating rules)

**Comment by NicolasGeraud** [comment]
I probably can do it for Docker. I'm not a Go dev, not at all, but I think I have to modify 
https://github.com/containous/traefik/blob/master/provider/docker.go#L224
and
https://github.com/containous/traefik/blob/master/templates/docker.tmpl#L15
and add some tests.

**Comment by emilevauge** [comment]
For now, traefik support mutliple rules of the same kind https://github.com/containous/traefik/pull/285 ie:

- `Host: foo.domain.com, bar.domain.com`
- `Path: /foo, /bar`
- `PathStrip: /foo, /bar`

And it also works with `PathPrefix` and `PathPrefixStrip`.

The idea would be to support multiple kind of routes, ie: 
- `Host: foo.domain.com, bar.domain.com; PathStrip: /foo`

We could use the separator `;` between rules.
I think everything could be done by modifying only `rules.go`.

WDYT?

**Comment by fclaeys** [comment]
If it's OK for you, I'll try to implement this enhancement, for my first contribution

**Comment by shouze** [comment]
@emilevauge I've seen you've entered in `rc`. To me this feature is a must have for 1.0 as composing micro services often require to have this kind of configuration:
- `domain/path1` points to microservice `foo`
- `domain/path2` points to microservice `bar`
- `domain/path1/deeper` points to microservice `foobar`

**Comment by emilevauge** [comment]
@shouze: I know :) @fclaeys was working on that. It will be in the rc2.

**Comment by shouze** [comment]
@NicolasGeraud I guess you can close this one ;)
