### ISSUE TITLE
Traefik setting Accept-Encoding: gzip on requests (Traefik may also be broken with chunked responses)

### ISSUE THREAD

**Issue by severnt** [containous/traefik#421]
Setup:
- traefik beta794 prebuilt amd64
- nginx HTTP backend configured with file

For some reason, it looks like traefik is adding Accept-Encoding: gzip to the requests, which causes nginx to send back a chunked gzip response, which results in a 0 length 0 content-length response to the client. If I disable gzip on nginx, everything seems to work fine.

I've verified with packet caps that my client isn't setting the Accept-Encoding header, and that nginx is responding properly to the request.

**Comment by emilevauge** [comment]
Maybe due to https://github.com/containous/oxy/commit/183212964e13e7b8afe01a08b193d04300554a68. I need to investigate on this.

**Comment by emilevauge** [comment]
I suspect that this is due to a regression that occurred in v1.0.0-beta.754 #398.
Could you test using v1.0.0-beta.744 instead? I cannot reproduce this issue on my laptop.
