### ISSUE TITLE
docs need updating for new frontend rules format

### ISSUE THREAD

**Issue by kbroughton** [containous/traefik#423]
on
https://docs.traefik.io/toml/
existing
```
[frontends]
  [frontends.frontend1]
  backend = "backend2"
    [frontends.frontend1.routes.test_1]
    rule = "Host:test.localhost"
```
should be the above mentioning v < 1.0

Also, I get file not found when I put 
filename = "rules.toml" and place the file in /etc/traefik or /etc/traefik/configs

It works fine if i use a fully qualified path to rules.toml
and for v >= 1.0
```
[frontends]
  [frontends.frontend1]
  backend = "backend2"
    [frontends.frontend1.routes.test_1]
    rule = "Host
    value = "test.localhost,otherfrontend.localhost"
```

**Comment by emilevauge** [comment]
@kbroughton, to clarify:

```
[frontends]
  [frontends.frontend1]
  backend = "backend2"
    [frontends.frontend1.routes.test_1]
    rule = "Host
    value = "test.localhost,otherfrontend.localhost"
```

is the OLD deprecated way, and 

```
[frontends]
  [frontends.frontend1]
  backend = "backend2"
    [frontends.frontend1.routes.test_1]
    rule = "Host:test.localhost"
```

is the NEW (less verbose) way to create frontend rules :)

Concerning `filename = "rules.toml"`, it should be placed in the working dir, or you should use an absolute path.

**Comment by kbroughton** [comment]
Ah, thanks.

I'm straddling two deployments one < 1.0.0 and one > 1.0.0 and got them
backwards.

On Tue, May 31, 2016 at 2:35 AM, Emile Vauge <notifications@github.com>
wrote:

> @kbroughton <https://github.com/kbroughton>, to clarify:
>
> [frontends]
>   [frontends.frontend1]
>   backend = "backend2"
>     [frontends.frontend1.routes.test_1]
>     rule = "Host
>     value = "test.localhost,otherfrontend.localhost"
>
> is the OLD deprecated way, and
>
> [frontends]
>   [frontends.frontend1]
>   backend = "backend2"
>     [frontends.frontend1.routes.test_1]
>     rule = "Host:test.localhost"
>
> is the NEW (less verbose) way to create frontend rules :)
>
> Concerning filename = "rules.toml", it should be placed in the working
> dir, or you should use an absolute path.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/containous/traefik/issues/423#issuecomment-222613548>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AKErsg0seGUiSdnQjtE1NsaQf523K3jdks5qG-SkgaJpZM4IqI2k>
> .
>



-- 
kesten broughton
devops @ cognitivescale
