### ISSUE TITLE
Traefik should not start with an TLS error in a static configuration

### ISSUE THREAD

**Issue by athoune** [containous/traefik#4233]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

In the main config file, or conf.d, tls error should be blocking.

Starting a server wich will not handle tls connection is a curse.
With ACME, tls is automagic (when you don't hit LE limits), but with static certificates, you can be annoyed with wrong path, wrong permissions, wrong format.

For dynamic certificates, cureent behavior is correct.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

Issue templates help us help you by providing all necessary information.

Please edit your issue and use the available templates:

- [Feature request](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/Feature_request.md)
- [Bug report](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/Bug_report.md)

And remember: each time someone ignores the template, a cute little bunny dies.
<details>
<summary>#SaveTheCuteBunny :heart: :rabbit: :heart:</summary>

![southpark - estrella kill rabbit](https://user-images.githubusercontent.com/5674651/27143914-3cea7896-5130-11e7-81f8-02d8ac2da7a7.gif)

![southpark - estrella kill rabbit2](https://user-images.githubusercontent.com/5674651/27143924-49104c72-5130-11e7-82ae-ccedbd5dfa1c.gif)

</details>

**Comment by ldez** [comment]
Hello, thanks for reporting and for updating your issue :+1: .

Be blocking at the start of Traefik will be an issue too.
We already meet this problem with ACME (see #791 and #2794)

I think you want more information when there are errors with certificates and we can understand this.
So I propose you to open a new issue about this specific problem.
