### ISSUE TITLE
Traefik supporting things reataed to tcp

### ISSUE THREAD

**Issue by rifaterdemsahin** [containous/traefik#4257]
my colleagues did not want to use traefik mentioning that it does not support features around TCP.

Which was not clear for me... ( communication gap as I am Aspergers it could be me not getting them)
What is the case for traefik for that?
What is the roadmap?

PS: We need to be able to support NATS
https://nats.io/

I was planning to do this on-premise
![image](https://user-images.githubusercontent.com/5270036/49290424-d7f57d00-f49e-11e8-9393-07fefff51210.png)

**Comment by ldez** [comment]
Duplicate of #10
