### ISSUE TITLE
Serve different backends based on header value on kubernetes

### ISSUE THREAD

**Issue by devypt** [containous/traefik#4261]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I'm not sure if there is a way currently to make frontend use different backend based on request header value like user-agent or any custom header, I tried to go through the code and I found  ``` traefik.frontend.rule ``` but didn't manage to get it to work for kubernetes setup.

**Comment by jbdoumenjou** [comment]
Duplicate, close in favor of #3543

**Comment by devypt** [comment]
The feature is published as part of version 0.21.0: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#canary

I've written a blog post https://www.elvinefendi.com/2018/11/25/canary-deployment-with-ingress-nginx.html showing how to use it with examples.
