### ISSUE TITLE
No docker tags pushed for 1.7.5

### ISSUE THREAD

**Issue by tanuck** [containous/traefik#4265]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
`docker pull traefik:1.7.5`

### What did you see instead?

`Error response from daemon: manifest for traefik:1.7.5 not found`

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
(paste your output here)
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# (paste your configuration here)
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
(paste your output here)
```

**Comment by kachkaev** [comment]
@tanuck see https://github.com/docker-library/official-images/pull/5135

**Comment by kachkaev** [comment]
I guess that the official announcement of the new version will follow the merge of that PR. Until then, we can't consider 1.7.5 as released. The presence of a [tag](https://github.com/containous/traefik/releases/tag/v1.7.5) on GitHub does not mean we are there yet 😉
