### ISSUE TITLE
Acme DNS Challenge : support for ionos / 1and1

### ISSUE THREAD

**Issue by seuf** [containous/traefik#4267]
### Ionos / 1and1.fr Acme DNS challenge support

Thanks for such a great tool !

Do you think it's possible to support ionos (ex 1and1.fr) for Acme DNS-01 challenge ?
I'd love to have a wildcard tls certificate :smile:

**Comment by ldez** [comment]
Hi, thanks.

Could you open an issue on [Lego](https://github.com/xenolf/lego)?

Thanks.

**Comment by ldez** [comment]
Closed in favor of https://github.com/xenolf/lego/issues/727
