### ISSUE TITLE
Send custom response headers on redirects, errors, etc.

### ISSUE THREAD

**Issue by zroug** [containous/traefik#4273]
### Do you want to request a *feature* or report a *bug*?

Feature (or maybe a bug?)

### What did you expect to see?

Traefik should send custom response headers on redirects, errors, etc. This would be especially useful for security headers and is needed to enforce security policies.

Example usecase:
Lets say Traefik is configured to redirect from example.com to subdomain.example.com. If you want to add example.com to the HSTS preload list (https://hstspreload.org/), the redirect itself needs to have a HSTS header.

**Comment by SuperSandro2000** [comment]
I think this needs a higher priority as you should not be excluded from hsts preloading when using traefik.

**Comment by traefiker** [comment]
Closed by #7230.
