### ISSUE TITLE
Support for TLS 1.3

### ISSUE THREAD

**Issue by benoitmaudet** [containous/traefik#4275]
Hello !

When do you plan to support TLSv1.3 ?

Regards,

**Comment by ldez** [comment]
https://github.com/golang/go/issues/9671

**Comment by benoitmaudet** [comment]
TLS1.3 available with Go 1.12beta1 : https://tip.golang.org/pkg/crypto/tls/

**Comment by nshtg** [comment]
Go1.12 has been released. Any ETA for 1.3 to land in traefik?

**Comment by kush-patel-hs** [comment]
Can I take on this issue ?
