### ISSUE TITLE
Allow default TLS certificate to be used for Kubernetes Ingresses that don't specify a "tls" section

### ISSUE THREAD

**Issue by DrEsteban** [containous/traefik#4276]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

We are running a multi-tenanted service where each customer's resources are contained within their own k8s namespace.  Each customer gets their own DNS subdomain that they can use to access their resources.  (E.g. "customerA.foo.com")  To enable HTTPS we have a wildcard TLS certificate for "*.foo.com".

Now, in Kubernetes, there is an unfortunate requirement that Ingresses can only reference TLS secrets within the same namespace.  But in our setup, this would mean copying the *exact same* secret to each customers k8s namespace.

The Nginx Ingress Controller allows us to set a "default TLS certificate", which will automatically be used if a particular Ingress resource doesn't specify a TLS secret.  This means we can leave the "tls" section out of our customer's Ingress resources and Nginx will automatically use "*.foo.com" - perfect!

**Unfortunately Traefik does not behave the same way.**  If an Ingress resource doesn't specify a "tls" section (when TLS is enforced), it will refuse to load the Ingress with an error message like:
```
"Error configuring TLS for ingress mynamespace/myingress: secret mynamespace/ does not exist"
```

So, my feature request is if an Ingress resource _doesn't_ specify a TLS secret, Traefik should use the "default" certificate.

**Comment by dtomcej** [comment]
@DrEsteban You can use the `DefaultCertificate` option to provide this:

https://docs.traefik.io/configuration/entrypoints/#default-certificate

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

Thanks again for your interest in Traefik!

I'm glad to close the issue because I think that the question has been answered (Yes, I'm quite an advanced AI :smile:)

Join our [Slack workspace](https://slack.traefik.io/) for more [community #support](https://traefik.slack.com/messages/C0CDT22PJ/).

**Comment by DrEsteban** [comment]
@dtomcej I was able to discover some more information, and realized this is more of a bug in Traefik than a feature request.  Since, as you suggest, it sounds like the "default certificate" flow is intended to work.  It had to do with how my Ingress object was formed; but is something _other_ Ingress Controllers can handle.

I've logged #4280
