### ISSUE TITLE
key/value storing ACME certs. 

### ISSUE THREAD

**Issue by sarkistlt** [containous/traefik#4290]
I'm working on a SaaS platform, and found one pretty significant drawback in using traefik with any multi tenant/domain projects.

it stores all certs. in one key. And with any new domain/tenant it should overwrite the same key, or read it. Let's say there some glitch and key wasn't properly saved then all domains will be affected.

Is it possible to store certs per domain?

Lets say `traefik/acme/accounts/domain/object` instead of `traefik/acme/account/object`?

**Comment by shane-axiom** [comment]
Duplicate:

https://github.com/containous/traefik/issues/3833
https://github.com/containous/traefik/issues/4290
