### ISSUE TITLE
multiarch images on docker hub

### ISSUE THREAD

**Issue by paulbsch** [containous/traefik#4291]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Please create an image for ppc64le.  FYI, docker machine works well if ppc64le hardware isn't available:
https://developer.ibm.com/linuxonpower/2017/06/08/build-test-ppc64le-docker-images-intel/

**Comment by runlevel5** [comment]
I second this. For the time-being I build the image locally :(

**Comment by paulbsch** [comment]
I updated the title to one that makes a bit more sense.  We are still primarily interested in having a ppc64le image available as a part of any multiarch builds.

**Comment by ldez** [comment]
We already have a multi-arch image: https://hub.docker.com/_/traefik?tab=tags

The official image is built by Docker it-self with a special process (it's a not the basic Docker Hub process),  so we have to check the possibilities.

You find here our base repo to create the official image https://github.com/containous/traefik-library-image/

We already have an issue on this repo about the ppc64le topic (https://github.com/containous/traefik-library-image/issues/73).

So I will close this issue, I will invite you to follow the issue on the image repository https://github.com/containous/traefik-library-image/issues/73

**Comment by paulbsch** [comment]
Thank you.  I didn't realize.  It's a bit confusing since this repo is still getting updates:  https://hub.docker.com/r/containous/traefik

It might be helpful to put a quick blurb there pointing out where the official images are.

**Comment by paulbsch** [comment]
Never mind.  I see the blurb now.  I didn't notice when I previously scanned.
