### ISSUE TITLE
Multiple Domains Rule

### ISSUE THREAD

**Issue by pilgrim2go** [containous/traefik#430]
Hi,

I want to capture both requests
api-xxx.123.com
and 
api-yyy.456.com

Here is my rule
```
      - "traefik.frontend.rule=HostRegexp:{subdomain:api-([^.]+)+}.(123|456).([a-z]+)+"
```
But It failed for me.

Is it possible to handle both domains ? or where am I wrong?

**Comment by leokhoa** [comment]
Try this:

- "traefik.frontend.rule=HostRegexp:{subdomain:api-([^.]+)+.(123|456).([a-z]+)+}"

**Comment by emilevauge** [comment]
@pilgrim2go: is your issue solved?
