### ISSUE TITLE
Support TLS_FALLBACK_SCSV

### ISSUE THREAD

**Issue by Finkes** [containous/traefik#4330]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I used [this sslscan](https://github.com/rbsec/sslscan) tool to check how "good" the TLS config of my traefik server is performing. The result looks fine except for the following feature:

```
  TLS Fallback SCSV:
Server does not support TLS Fallback SCSV
```

SCSV is described in [this rfc](https://tools.ietf.org/html/rfc7507).

@nmengin pointed me to the list of supported TLS ciphers in go (which is used by traefik). They are available here: https://golang.org/pkg/crypto/tls/#pkg-constants.

The list mentions the following option:
```
        // TLS_FALLBACK_SCSV isn't a standard cipher suite but an indicator
        // that the client is doing version fallback. See
        // https://tools.ietf.org/html/rfc7507.
        TLS_FALLBACK_SCSV uint16 = 0x5600
```

Unfortunately it looks like Traefik doesn't support this option at the moment.
I think this is an important security feature since attackers can attack certain ciphers more easily without this protection mechanism.

**Comment by togetheragency** [comment]
Whats the possibility of rolling this in with #4529 in release? I'm staring down Qualsys comparisons during pen testing, and it looks like it's just incompatibility with the upstream Go library?
