### ISSUE TITLE
http to https without prefixpath www not redirecty

### ISSUE THREAD

**Issue by alpertandogan** [containous/traefik#4338]
My version just 1 hour before (last one)
My platform on OEL 7.6 (Final updated one)
My backend servers also OEL 7.6 (Apache 2.4) 

In all browsers (chrome final,firefox final,IOS Safari finals)

`
You end this url                               --->Goes to this url                                   >RESULT

  http://www.example.com/img.gif	--->https://www.example.com/img.gif	WORKS WELL	
  https://www.example.com/img.gif -->https://www.example.com/img.gif	WORKS WELL	

  http://example.com/img.gif		--->https://example.com/img.gif		404 not found
  https://example.com/img.gif	--->https://example.com/img.gif		404 not found

`

This is configuration parts of entry and redirect.(The other parts works very well ) backend loadbalance . Port forwarding etc.

> 
'''
[entryPoints]
	[entryPoints.http]
		address = "xx.xx.xx.xx:80"
	[entryPoints.http.redirect]
		entryPoint = "https"  
	[entryPoints.https]
		address = "xx.xx.xx.xx:443"
		compress = true
	[entryPoints.https.redirect]
		regex = "^https://example.com/(.*)"
		replacement = "https://www.example.com/$1"      
		permanent = true

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

Issue templates help us help you by providing all necessary information.

Please edit your issue and use the available templates:

- [Feature request](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/Feature_request.md)
- [Bug report](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/Bug_report.md)

And remember: each time someone ignores the template, a cute little bunny dies.
<details>
<summary>#SaveTheCuteBunny :heart: :rabbit: :heart:</summary>

![southpark - estrella kill rabbit](https://user-images.githubusercontent.com/5674651/27143914-3cea7896-5130-11e7-81f8-02d8ac2da7a7.gif)

![southpark - estrella kill rabbit2](https://user-images.githubusercontent.com/5674651/27143924-49104c72-5130-11e7-82ae-ccedbd5dfa1c.gif)

</details>

**Comment by alpertandogan** [comment]
No solution yet.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Slack workspace](https://traefik.herokuapp.com/) for more [community #support](https://traefik.slack.com/messages/C0CDT22PJ/).
