### ISSUE TITLE
jwt authentication 

### ISSUE THREAD

**Issue by LincolnBruce** [containous/traefik#4339]
### Do you want to request a *feature* or report a *bug*?

Feature

**Comment by LincolnBruce** [comment]
Based on jwt permission authentication, when can I support it?

**Comment by jlevesy** [comment]
Hey @LincolnBruce, thanks for your interest in the project. 

We're dealing with this issue in https://github.com/containous/traefik/issues/3311.

**Comment by LincolnBruce** [comment]
good job
