### ISSUE TITLE
Traefik doesn't listen on IPv4 ports

### ISSUE THREAD

**Issue by sybrandy** [containous/traefik#434]
Hello,

I hope I said that right.  Basically, when I look at netstat, I see that traefik is listening on the specified port, but only on the IPv6 instance (tcp6).  Is there any way I can force traefik to listen on IPv4?

**Comment by sybrandy** [comment]
Ignore this.  It looks like the problem is elsewhere.

**Comment by kmorton1988** [comment]
Would love to know where you found the error, working through the same (or at least a similar issue)

**Comment by sybrandy** [comment]
@kmorton1988 Sorry, I don't remember what the exact issue was.  I double-checked the local git repo I have the code in, but I don't see anything related to this in the commits.

**Comment by kmorton1988** [comment]
No worries.
