### ISSUE TITLE
Change automatic host with Docker compose

### ISSUE THREAD

**Issue by ebuildy** [containous/traefik#4350]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Using Traefik with Docker compose, using "default" discovery, frontend host names are built like this:

https://github.com/containous/traefik/blob/a09dfa3ce10f222ab6e10ac11386d330698ff6f8/old/provider/docker/config.go#L194

    CONTAINER_NAME + "." + COMPOSE_PROJECT_NAME + "." + DOCKER_DOMAIN

### Idea

I propose a new config option: 

``docker.compose.host.template`` which default to ``"{{container.name}}.{{compose.project_name}}.{{config.docker.domaine}}"`` 

or a new option ``docker.compose.use_project_name: false|true``

**Comment by geraldcroes** [comment]
Hi @ebuildy, and thanks for your proposal.

Could you tell us more about your use case? We don't see why this "advanced" option would be useful to traefik users.

Thanks!

**Comment by ebuildy** [comment]
hello @geraldcroes , this is to control how the final frontend host is generated. 

Most of the time, the COMPOSE_PROJECT_NAME is let to default, the parent folder name, so this can be not very valuable to add it in the host.

**Comment by ldez** [comment]
Seems like a duplicate of #2578

**Comment by ebuildy** [comment]
Yes you are right, I didnt find it because I search "docker-compose" :/ 

I can close this one, thanks you and sorry.
