### ISSUE TITLE
Autoscaling based on demand (traffic)?

### ISSUE THREAD

**Issue by MishUshakov** [containous/traefik#4356]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Hey, thank you for creating traefik. It works surprisingly well with my docker stack. Bye Bye Nginx!
I would like to request an idler feature. Since traefik works with both Prometheus and Docker it could make use of them and scale the backends to zero, when there is no incoming traffic. There is a similar feature in another project - [OpenFaaS](https://github.com/openfaas-incubator/faas-idler) called faas-idler

> Premise: functions (Deployments) can be scaled to 0/0 replicas from 1/1 or N/N replicas when they are not receiving traffic. Traffic is observed from Prometheus metrics collected in the OpenFaaS API Gateway.

Could it be possible, to implement a similar feature? Because I want to save some CPU-time and make sure my microservices are only running when they actually need to

Thank you a lot.

**Comment by RealKanashii** [comment]
Maybe something like httping monitoring response time or a own defined service check, seems a nice feature althoug I prefer TCP reverse proxy first.

**Comment by jbdoumenjou** [comment]
Hi @MishUshakov, thanks for your interest in the project.

We know / understand the on-demand management of server provisioning that can be done by FAAS.
For this, the FAAS records a function (a route) without provisioning server.

The operation of Traefik consists of creating routes for servers, without servers there are no routes.

Moreover we think that the scalability must remain in charge of the orchestrator.

Traefik is only a reader/consumer of the orchestrator data, it does not modify this data.

I hope our explanation is clear and that you will understand why we are closing your issue.
Thank you for taking the time to make your proposal :+1:.
