### ISSUE TITLE
Add href link on frontend

### ISSUE THREAD

**Issue by WTFKr0** [containous/traefik#436]
Hi

If I have a frontend : www.mycorp.org
On the left i got : 
route-frontend-Host-www-mycorp-org        	Host:www-mycorp-org

I think the Host part should be a link (on new tab) to http://www.mycorp.org
How do you think ?

Thx

**Comment by emilevauge** [comment]
@WTFKr0 Unfortunately, this is not that simple. We can have complex rules (Headers + Path with regex for example) that will prevent generating a href link :'(

**Comment by WTFKr0** [comment]
Well i see. Maybe an URL regexp ? :D

**Comment by emilevauge** [comment]
I'm closing this one for now, as I don't have any simple solution in mind to do that :)
