### ISSUE TITLE
Simplify monitoring of certificate transparency logs (save requested certificates)

### ISSUE THREAD

**Issue by zroug** [containous/traefik#4377]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

An option to store all certificates created by Traefik into a directory.

#### Motivation

Certificate transparency, especially with things like the `Expect-CT` header or browsers that only accept certificates that where added to a certificate transparency log, is a great way to improve the security of your domains. But for certificate transparency to work, you have to actually monitor the certificates that are logged for your domains. ACME integration into Traefik is great because it makes it very easy to request certificates for all your domains. On the other hand it makes it hard for you to monitor the certificate transparency logs because you don't really know when and what certificates are requested for your domains.

To solve this situation a tool would be helpful that automatically monitors the certificate transparency logs. Such a tool would need to know what certificates where issued by you. A simple option in Traefik to log all certificates it requests into a directory could make that possible.

**Comment by geraldcroes** [comment]
Hi, and thanks for your feature request!

Isn't the [storage as a file option](https://docs.traefik.io/configuration/acme/#as-a-file) enough for your use case?

**Comment by zroug** [comment]
It is possible to use the `acme.json` file to read the required information. But I think doing it this way has some drawbacks:

1. You must be able to read a custom file format. While this file format is not complicated, I think it is not documented and might change at anytime.
2. Whoever reads this file has access to your private keys.
3. It doesn't keep the history of created certificates I think. Normally the lifetime of a certificate is more than enough for you to catch every certificate but it doesn't feel right that there is a deadline.

**Comment by zroug** [comment]
Thank you. I wasn't aware of this script. Maybe a link in the ACME documentation would be useful so others can find it.

I still think that the feature I proposed would be useful because there are still some rough edges in using the script. For example I can't run this script from within the simple Traefik docker container, meaning I need another one with necessary dependencies and I have to keep everything in sync manually. I also can't schedule this script to run when Traefik requests new certificates.

But this script makes the situation definitively better and if you think that such a feature isn't useful enough to be included in Traefik I think you can close this issue.

**Comment by geraldcroes** [comment]
Thank you for your feedback on this. 

I will close this issue for now.
