### ISSUE TITLE
ECC Support in Certdumper

### ISSUE THREAD

**Issue by CupCakeArmy** [containous/traefik#4381]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

The certdumper script (https://github.com/containous/traefik/blob/master/contrib/scripts/dumpcerts.sh)
fails if the certificate is an ECC one. Since traeffik supports ECC natively, the script should too in order to avoid confusion.

**Comment by ldez** [comment]
@CupCakeArmy I build a tool to dump certificates: https://github.com/ldez/traefik-certs-dumper/releases

**Comment by ldez** [comment]
Closed by #4783
