### ISSUE TITLE
Allow client certificate propagation to backend with optional or no verification

### ISSUE THREAD

**Issue by evsrao** [containous/traefik#4385]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Requesting NGINX equivalent feature, ssl_verify_client optional_no_ca, in Traefik. NGINX is propagating client certificate with no CA verification. 

Went through Traefik source code and found that the implementation is using tls.VerifyClientCertIfGiven for optional=true and tls.RequireAndVerifyClientCert for optional=false. Local testing with tls.RequestClientCert seemed to help. Looking for an enhancement around this, may be through an additional configuration.

**Comment by nmengin** [comment]
Hello @evsrao ,

Many thanks for your interest in the project.

Do you think your use case can be solved by using both [pass-tls-client-cert](https://docs.traefik.io/configuration/commons/#pass-tls-client-cert) and [optional TLS Mutual Authentication](https://docs.traefik.io/configuration/entrypoints/#tls-mutual-authentication)?

**Comment by evsrao** [comment]
Hi @nmengin,

The following config is what I tried out. 
traefik.toml:
-----------
debug = true
logLevel = "DEBUG"
defaultEntryPoints = ["http", "https"]
[entryPoints]
    [entryPoints.http]
    address = ":8180"
      [entryPoints.http.redirect]
      entryPoint = "https"
    [entryPoints.https]
    address = ":8443"
      [entryPoints.https.tls]
        [entryPoints.https.tls.ClientCA]
          files = ["./ca2.crt"]
          #files = []
          optional = true
[file]
filename = "./rules.toml"
watch = false

rules.toml
----------
[frontends]
  [frontends.frontend1]
  backend = "backend1"
  passHostHeader = true

  [frontends.frontend1.passTLSClientCert]
    pem = true
    [frontends.frontend1.routes.test_1]
    rule = "Host: test.example.com"

[backends]
  [backends.backend1]
    [backends.backend1.servers.server1]
    url = "http://127.0.0.1:9000/"

---------

The above config is working for 1 and 2 below, but not 3: 
1. Client is sending a request without any certs.
2. Client is sending a request with a cert signed by CA2, then Traefik is propagating the cert in the header.
3. Client is sending a request with a cert NOT signed by CA2, then Traefik is not propagating the cert in the header.

What I am looking for is case 3 to also work having certificate getting propagated to the backend.  As mentioned in the feature request description. Locally built Traefik having the code change, then saw cert being propagated. Also another issue observed that the browser is not getting prompted to present whatever the certificate it has. Browser is showing the certificate prompt only when matching CAs present in the Traefik's config. 

Did the similar testing with NGINX, the following config helped all 3 cases to work as well as browser is getting prompted to present whatever cert it has. Looking for similar in Traefik as well if possible.

server {
        listen 443 ssl;
        access_log logs/access.log main;
        error_log logs/error.log debug;
 
        ssl_certificate         /etc/nginx/mtl/server.crt;
        ssl_certificate_key     /etc/nginx/mtl/server.key;

        #ssl_trust_certificate  /etc/nginx/mtl/ca.crt;

        ssl_verify_client optional_no_ca;
 
        location / {
            proxy_set_header X-CLIENT-CERT $ssl_client_escaped_cert;
            proxy_pass_request_headers      on;
            proxy_pass http://127.0.0.1:9000/;
        }
      }

**Comment by mazhead** [comment]
Can confirm that tls.RequestClientCert did help for that case.

**Comment by traefiker** [comment]
Closed by #5078.
