### ISSUE TITLE
Implement login dialog and session state for auth.forward

### ISSUE THREAD

**Issue by FireDrunk** [containous/traefik#4414]
### Do you want to request a *feature* or report a *bug*?
Feature

### What did you expect to see?
Using auth.forward, Traefik expects the X-Auth-User and X-Auth-Secret. It would be nice to have the option to let Traefik request these values via basic HTTP Authentication (like it does with the auth.basic setting).

I think it's technically possible because all the technical code requirements are already implemented in different parts of Traefik. This requires 3 things if I'm correct:

- Session management (already in sticky sessions part) to see if a user already provided credentials, and to store the provided credentials.
- A HTTP Basic Authentication login box (already in the auth.basic part)
- A setting to enable/disable showing the login box upon missing the X-Auth-* headers (some people obviosuly don't want the dialog box, because they handle the login somewhere else.)

It might be something fun for me to take on myself, I'm just wondering wether people are interested in the function.

My usecase is that I have a tiny Python container which handles the X-Auth-* headers to connect to LDAP, and just returns a 200/401, but doesn't do any GUI like requests.
A basic login box would be fine, and the one used in auth.basic would work just perfect for me.

This means that the authentication daemon is only used for the first request pointed to Traefik, and afterwards, the session cookie in Traefik would still be 'valid' and can be used for multiple backends.

Any comments/suggestions before is start working on this?

**Comment by nmengin** [comment]
Hello @FireDrunk ,

Thank you for your interest in the project.

After analyze, it appears that your proposition does not match with the features we want to implement in the authentication middleware.

For example, it needs to provide an HTTP page which is a mechanism which has not been implemented in Traefik.
Maybe, can you solve your use by adding a backend to manage the authentication behind TRaefik?

You can find a discussion about this subject in the (huge) proposal #593.

I close the issue.
