### ISSUE TITLE
 Traefik grpc agent does not work in h2c mode

### ISSUE THREAD

**Issue by LincolnBruce** [containous/traefik#4421]
I wrote a grpc demo, the local server and client can communicate, but after passing the traefik proxy server, the client will report an error, the error is as follows
```
2019/01/23 16:48:47 Do Format error:rpc error: code = Internal desc = transport: received the unexpected content-type "text/plain; charset=utf-8"
```
Traefik's access log has been received, as shown below
( Grpc server uses port 80)
```
111.200.53.2 - - [23/Jan/2019:08:52:44 +0000] "POST /protos.UserService/GetInfo HTTP/2.0" 200 16 "-" "grpc-go/1.19.0-dev" 617 "my-grpc-t-exx-com" "h2c://my-grpc.web:80" 1ms
```

**Comment by LincolnBruce** [comment]
go grpc server code:
`package main

import (
	"context"
	"eoffcn/protos"
	"fmt"
	"google.golang.org/grpc"
	"net"
)

type UserService struct {
}

// Get接口方法实现
func (this *UserService) GetInfo(ctx context.Context, req *protos.UserReq) (*protos.User, error) {
	fmt.Println("GetInfo", req)
	return &protos.User{Id: 1, Name: "linyang"}, nil
}

func main() {
	// 开启服务监听
	lis, err := net.Listen("tcp", ":80")
	if err != nil {
		fmt.Println("listen error!")
		return
	}
	fmt.Println("listen start")
	// TLS认证
	//creds, err := credentials.NewServerTLSFromFile("../tls/server.pem", "../tls/server.key")
	//if err != nil {
	//	grpclog.Fatalf("Failed to generate credentials %v", err)
	//}

	// 实例化grpc Server, 并开启TLS认证
	grpcServer := grpc.NewServer() //grpc.Creds(creds))
	// 重点：向grpc服务中注册一个api服务，这里是UserService，处理相关请求
	protos.RegisterUserServiceServer(grpcServer, &UserService{})
	// 可以添加多个api
	// TODO...

	// 启动grpc服务
	grpcServer.Serve(lis)
}
`

go grpc client code:
`package main

import (
	"context"
	"eoffcn/protos"
	"google.golang.org/grpc"
	"log"
)

// 定义请求地址
const (
	ADDRESS string = "my-grpc.t.exx.com:80"
)

// main 方法实现对 gRPC 接口的请求
func main() {
	// TLS连接
	//creds, err := credentials.NewClientTLSFromFile("../tls/server.pem", "my-grpc.web")
	//if err != nil {
	//	grpclog.Fatalf("Failed to create TLS credentials %v", err)
	//}
	conn, err := grpc.Dial(ADDRESS, grpc.WithInsecure()) //, grpc.WithTransportCredentials(creds))

	if err != nil {
		log.Fatalln("Can't connect: " + ADDRESS)
	}
	defer conn.Close()
	client := protos.NewUserServiceClient(conn)
	resp, err := client.GetInfo(context.Background(), &protos.UserReq{Id: 1})
	if err != nil {
		log.Fatalln("Do Format error:" + err.Error())
	}
	log.Println(resp.Name)
}
`

**Comment by LincolnBruce** [comment]
traefik conf 
![image](https://user-images.githubusercontent.com/7814560/51595967-de4e2580-1f32-11e9-807d-c44a90ae8dca.png)
traefik version v1.7.7

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Slack workspace](https://traefik.herokuapp.com/) for more [community #support](https://traefik.slack.com/messages/C0CDT22PJ/).
