### ISSUE TITLE
Failed to pull image "errm/cheese:cheddar"

### ISSUE THREAD

**Issue by stantonxu** [containous/traefik#4423]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you expect to see?

Following the instructions of "https://docs.traefik.io/user-guide/kubernetes/", the pods "cheddar", "stilton", "wensleydale" should be created.

### What did you see instead?

Pods were not created.

Failed to pull image "errm/cheese:cheddar": rpc error: code = Unknown desc = error pulling image configuration: Get https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/05/05cbb2fce885009ab9540ecef52d54ffd5829e6a2700058258e36f8762267f9b/data?<........>: x509: certificate has expired or is not yet valid

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
v.1.7.7
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# bare metal kubernetes v1.13 with MetalLB
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
(paste your output here)
```

**Comment by mmatur** [comment]
Hi @stantonxu,

Thanks for your interest in the project.

After some test it is working has expected.

```docker pull errm/cheese:cheddar
cheddar: Pulling from errm/cheese
6c123565ed5e: Pull complete 
8380043c1909: Pull complete 
bc193245541a: Pull complete 
f6058f41c33e: Pull complete 
ac2762a84738: Pull complete 
Digest: sha256:d0b44559d3671ff436e08012aed235e2d84eba0f61410eeadd2def55cb48f2da
Status: Downloaded newer image for errm/cheese:cheddar
```

The issue seems on your side, so I will close the issue

**Comment by stantonxu** [comment]
Thank you @mmatur . I just figured out the reason, it is true that the problem is on my side. I run the kubernetes clusters with raspberry pi images on VMware. The clock of my raspberry pi systems is very old, which cause the certificate expiration problem. Once I set the clock to current time, the problem is resolved.

Thank you again.
