### ISSUE TITLE
Docker - 2 independant rules on same container

### ISSUE THREAD

**Issue by WTFKr0** [containous/traefik#444]
Is this case is possible ?

I have a container exposing 2 ports, 80 and 81
I want myapp1.mydomain go to 80 and myapp2.mydomain go to 81

Today i can configure labels to one :
- traefik.port=80
- traefik.frontend.rule=myapp1.mydomain

Or to other : 
- traefik.port=81
- traefik.frontend.rule=myapp2.mydomain

Can I have the two rules active at same time ?

Thanx

**Comment by emilevauge** [comment]
@WTFKr0: not for now. We have to find a way to do that using labels.
Any suggestion?

**Comment by WTFKr0** [comment]
The traefik.port param is linked to a backend
So, we have to find a way to set 2 backends for one container : 
- backend ; foo80 => traefik.port : 80
- backend ; foo81 => traefik.port : 81

And then link frontend rules to these backends : 
- frontend : Host:app1.mydomain => foo80
- frontend : Host:app2.mydomain => foo81

Today, I think the frontend rule is linked by default to the only backend (one container = one backend)
I don't know how this can be implemented

**Comment by WTFKr0** [comment]
Hi !

I really need that :D 

Current labels using default entry point
Opt launch : 
--entryPoints='Name:http Address::80' --defaultEntryPoints=http
```
    - "traefik.port=80"
    - "traefik.frontend.rule=Host:myapp1.mycorp.org"
```
=> Create a server "server-container_name" with url "IP:80" (weight 1)
=> Create a backend "backend-container-name" linked to this server
=> Create a frontend on "myapp1.mycorp.org:80" to that backend

Proposition with multiple independants routes (with two entrypoints) : 
Opt launch : 
--entryPoints='Name:http Address::80' --entryPoints='Name:http2 Address::8080' --defaultEntryPoints=http
```
    - "traefik.ports=80,8080"
    - "traefik.frontend.rules=Host:myapp1.mycorp.org"
    - "traefik.frontend.entryPoints=http,http2"
```
=> Create a server "server-container_name-80" with url "IP:80" (weight 1)
=> Create a server "server-container_name-8080" with url "IP:8080" (weight 1)
=> Create a backend "backend-container-name-80" linked to the 80 server
=> Create a backend "backend-container-name-8080" linked to the 8080 server
=> Create a frontend on "myapp1.mycorp.org:80" to the 80 backend
=> Create a frontend on "myapp1.mycorp.org:8080" to the 8080 backend

I don't know if this is the goal to traefik to do that...
Thanx

**Comment by emilevauge** [comment]
Hi @WTFKr0 
I think that it's would be a bit confusing for users because the actual label

>`traefik.frontend.entryPoints=http,https`: assign this frontend to entry points http and https.

assigns both `http` and `https` entrypoints to the same frontend.

We should be able to:

- create multiple frontends with different rules mapping the multiple ports
- assign these frontends to different entrypoints

To keep backward compatibility, I think we don't have any other choice than to introduce a new kind of label.

The simplest way I found is to put the port number in the label key, and keep the actual labels format (except `traefik.port` obviously):

- `traefik.80.frontend.rule=Host:test.traefik.io`
- `traefik.80.backend=testBakend`
- `traefik.80.entrypoints=http,https`
- `traefik.8080.frontend.rule=Host:antoherTest.traefik.io`
- `traefik.8080.backend=anotherBackend`
- `traefik.8080.entrypoints=anotherHttp`

WDYT?

/cc @vdemeester @samber @errm

**Comment by vdemeester** [comment]
Hum thinking about it, but this could work 😉 😝

**Comment by emilevauge** [comment]
Or we could even use a more generic way:
- `traefik.{serviceName}.frontend.xxx=x`

That would gives:

- `traefik.myfirstservice.port=80`
- `traefik.myfirstservice.frontend.rule=Host:test.traefik.io`
- `traefik.myfirstservice.frontend.backend=testBakend`
- `traefik.myfirstservice.frontend.entrypoints=http,https`
- `traefik.mysecondservice.port=8080`
- `traefik.mysecondservice.frontend.rule=Host:antoherTest.traefik.io`
- `traefik.mysecondservice.frontend.backend=anotherBackend`
- `traefik.mysecondservice.frontend.entrypoints=anotherHttp`

**Comment by vdemeester** [comment]
I like that :smile_cat:

**Comment by WTFKr0** [comment]
I love the service style. Sounds good for me !

**Comment by sdurrheimer** [comment]
Hi there,

It would also be usefull to be able to specify multiples frontend rules, without removing the single rule case, something like:

```yml
labels:
    - "traefik.myfirstservice.frontend.rules.test=Host:test.traefik.io"
    - "traefik.myfirstservice.frontend.rules.subtest=Host:subtest.traefik.io;Path:/subtest"
```

**Comment by MartinLG** [comment]
I also really like the service style !

**Comment by emilevauge** [comment]
@sdurrheimer:

>Hi there,
It would also be usefull to be able to specify multiples frontend rules, without removing the single rule case, something like:
```yml
labels:
    - "traefik.myfirstservice.frontend.rules.test=Host:test.traefik.io"
    - "traefik.myfirstservice.frontend.rules.subtest=Host:subtest.traefik.io;Path:/subtest"
```

Multiple rules are already managed, I don't get your point. Why adding `subtest` if we can already add multiple rules using `traefik.myfirstservice.frontend.rule=Host:test.traefik.io;Path:/test` ?

**Comment by sdurrheimer** [comment]
@emilevauge Maybe I'm mistaken, does `traefik.myfirstservice.frontend.rule=Host:test.traefik.io;Path:/test` mean 

- `Host:test.traefik.io` && `Path:/test` 

or 

- `Host:test.traefik.io` || `Path:/test` ?

**Comment by emilevauge** [comment]
`Host:test.traefik.io` && `Path:/test`

`OR` is only available inside a rule type, for example, `Host:test.traefik.io,test.traefik.com` will match `test.traefik.io` || `test.traefik.com`.

**Comment by sdurrheimer** [comment]
That is what I thought, my idea was to have the possibility to do rules like:

- `Host:main.traefik.io`

||

- `Host:sub.traefik.io` && `Path:/test`

**Comment by sdurrheimer** [comment]
I'm fine with that solution, if having multiple services on the same port will be possible :).

**Comment by jgangemi** [comment]
is there any forward movement on this issue? i am currently in need of this functionality in order to use the docker registry support in sonatype's nexus 3 software.

**Comment by gajus** [comment]
A summary of proposal for an alternative syntax (discussed https://traefik.slack.com/archives/support/p1474558940001576).

```
#		port 80
#		host foo.com
#		path /test
port:80,rule.host=foo.com,rule.path=/test

#		port 80 or 90
#		host foo.com
#		path /test
port:80,port:90,rule.host=foo.com,rule.path=/

#		port 80
#		host foo.com or bar.com
#		path /test
port:80,rule.host=foo.com,rule.host=bar.com,rule.path=/test

#		port 80
#		host foo.com
#		path /test1
# or
#		port 80
#		host bar.com
#		path /test2
port:80,rule.host=foo.com,rule.path=/test1;port:80,rule.host=bar.com,rule.path=/test2
```

In words:

* Multiple frontends are separated using a semi-column `;`
* Individual options are separated using a comma `,`
* Multiple declarations of a rule create an OR condition

**Comment by emilevauge** [comment]
To be closer to the old convention: `port=80 backend=foo rule=Host:foo.com rule=Path:/test1 entrypoints=http,https ; port=80 backend=bar rule=Host:bar.com rule=Path:/test2,/test3 entrypoints=http`

**Comment by gajus** [comment]
@emilevauge its been almost 5 months since this issue was raised. Is there a timeline, priority assigned to this? Are you working on it or do you expect a PR in order to proceed further?

**Comment by emilevauge** [comment]
@gajus This issue may be solved in 1.2. Help on this would be really appreciated :heart_eyes:

**Comment by vdemeester** [comment]
I'll work on that, I'm going for :

- `traefik.myfirstservice.port=80`
- `traefik.myfirstservice.frontend.rule=Host:test.traefik.io`
- `traefik.myfirstservice.frontend.backend=testBakend`
- `traefik.myfirstservice.frontend.entrypoints=http,https`
- `traefik.mysecondservice.port=8080`
- `traefik.mysecondservice.frontend.rule=Host:antoherTest.traefik.io`
- `traefik.mysecondservice.frontend.backend=anotherBackend`
- `traefik.mysecondservice.frontend.entrypoints=anotherHttp`

👼

**Comment by nnordrum** [comment]
@vdemeester Might I suggest you also make `{serviceName}` available for rules like 

`Host:{serviceName}.api.traefik.io`

**Comment by amenophis** [comment]
Why not something like this:
```docker run ... --label traefik.service name=service1;port=80;frontend.rule=Host:service1.traefik.io;frontend.entrypoints=http,https, backend= testBakend --label traefik.service name=service2;port=81;frontend.rule=Host:service2.traefik.io;frontend.entrypoints=http,https, backend= testBakend2```

**Comment by vdemeester** [comment]
@amenophis pretty sure `docker run --label foo=bar --label foo=baz` ends up with only one label `foo` (label keys can't be duplicated)

**Comment by amenophis** [comment]
yes, maybe put the service name in the label like
```bash
docker run ... --label traefik.service.service1=port:80; ... --label traefik.service.service2=port:81;
```

**Comment by shaunc** [comment]
While I like the @vdemeester's service name proposal, I don't see why entrypoints aren't treated as first-class objects, as the [basics] section of the documentation suggests. 
Sometimes, might you not want to route different container ports to different external ports? So instead of 
```
traefik.myfirstservice.frontend.entrypoints=http,https
```
why not have:
```
traefik.myfirstservice.frontend.entrypoints=e1,e2
```
then on the traefik service itself,
```
traefik.entrypoints.e1.protocol=http
traefik.entrypoints.e1.port=80
traefik.entrypoints.e2.protocol=https
traefik.entrypoints.e2.port=443
```
(which would be named versions of the anonymous defaults, but) to which you could add other entrypoint connections (and, if supported in the future or with plugins, protocols) if required?

**Comment by sandeepone** [comment]
Any update??

**Comment by rafilkmp3** [comment]
this is in roadmap ?

**Comment by emilevauge** [comment]
FYI, @benoitf made a PR on this. Your help on reviewing is welcome :)

**Comment by timoreimann** [comment]
PR merged. Feature should be available in 1.3. :)

**Comment by WTFKr0** [comment]
Thanx

**Comment by Gnouc** [comment]
It's not working for me with these lines:

```
  foo:
    image: my-foo
    restart: unless-stopped
    depends_on:
      - foo_backend
    ports:
      - "81:80"
    volumes:
      - media:/assets
      - static:/static
    labels:
      traefik.backend: nginx
      traefik.enable: "true"
      traefik.prod.frontend.rule: "Host:cuonglm.xyz;AddPrefix:/static/public/"
      traefik.prod.port: "80"
      traefik.dev.frontend.rule: "Host:dev.cuonglm.xyz"
      traefik.dev.port: "80"
      monitor.required: "true"
```

The reason is `traefik.prod.port` and `traefik.dev.port` are 80, no?

**Comment by ldez** [comment]
@Gnouc could you remove `traefik.backend: nginx`

Come to the [Traefik community Slack channel](https://traefik.herokuapp.com)
