### ISSUE TITLE
How to define local / rule when using consul_catalog?

### ISSUE THREAD

**Issue by sokoow** [containous/traefik#445]
I thought that defining:
```
defaultEntryPoints = ["http"]
```
in the config is enough to get something like redirecting / on traefic's IP to http.domain , but it does not work. How to do that ?

**Comment by emilevauge** [comment]
@sokoow what version of traefik are you using? Any logs?

**Comment by sokoow** [comment]
I just built from source

**Comment by sokoow** [comment]
what I'm looking for is when I don't specify subdomain, to redirect to some default frontend

**Comment by emilevauge** [comment]
@sokoow, please give us more details to allow us to investigate your issue. We need debug logs of traefik. Thanks.

**Comment by ldez** [comment]
I'll close the issue due to inactivity but feel free to re-open if needed.
