### ISSUE TITLE
domain label doesn't work on docker

### ISSUE THREAD

**Issue by aacebedo** [containous/traefik#447]
Hi !

I've tried to use the traefik.domain label on one of my container in order to change the default domain applied to the frontend but unfortunately it doesn't work :(

I've created the label with docker run --label traefik.domain=mydomain.com

Can you confirm the bug ?

Regards

**Comment by emilevauge** [comment]
@aacebedo, in fact I think we should remove this label from the doc. This is too old ;) You can use a label like `traefik.frontend.rule=Host:app.mydomain.com` instead.

**Comment by aacebedo** [comment]
Oh ! Ok ! Maybe you shall inform users that the doc is outdated :)
Strange thing is that the code is still containing a method referencing the functionality:
https://github.com/containous/traefik/blob/d1ffbd8a03a4fd399c0cc57a5709e5ad07240f02/provider/docker.go#L286
