### ISSUE TITLE
Custom root CA for generated certificates

### ISSUE THREAD

**Issue by julienfalque** [containous/traefik#4470]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

When enabling TLS on HTTPS entrypoints, Traefik generates a self-signed certificate for any domain that does not already have one. This is nice because it allows using HTTPS for dev purposes but the certificate is not trusted by the browser and must be manually accepted first.

Without Traefik, I use [`mkcert`](https://github.com/FiloSottile/mkcert) in my Docker setup to create trusted certificates. The browser trusts the root CA from [`mkcert`](https://github.com/FiloSottile/mkcert) and thus trusts any certificate signed by it.

As far as I understand, this is currently not possible with Traefik because it uses a random key to generate certificates. I'd like to be able to provide a trusted root CA to Traefik so it uses it instead.

**Comment by ldez** [comment]
Hello,
I think you can use https://docs.traefik.io/configuration/entrypoints/#default-certificate

**Comment by julienfalque** [comment]
If I understand correctly, using a default certificate would require to manually create a new certificate each time I want Traefik to serve a new domain. Being able to provide a trusted root CA would allow me to let Traefik do that job on the fly just like now but with trusted certificates.

**Comment by ldez** [comment]
> To enable a default certificate to serve, so that connections without SNI or without a matching domain will be served this certificate.

> If no default certificate is provided, a self-signed certificate will be generated by Traefik, and used instead.

So you don't need to create a certificate for each new domain, the default certificate will used instead of the Traefik self signed certificate.

**Comment by julienfalque** [comment]
Is it possible to have a default certificate that is valid for any domain served by Traefik?

**Comment by dduportal** [comment]
Hi @julienfalque , as specified in the `mkcert` documentation (https://github.com/FiloSottile/mkcert#mkcert), you can issue a certificate with either:
- A wildcard domain as `*.company.dev`
- A collection of domains as `front.company.dev,back.company.dev`

If you generate a certificate with the list of domain and/or the wildcard domain, then use this certificate as the default one, following the instructions given earlier, so any application with

Then, any application with any domains served by Traefik will use this default, with no issue if the domain is on the certificate's list.

Let us know.

**Comment by julienfalque** [comment]
Indeed, I was able to generate a default certificate using `mkcert`. But I will have to maintain the list of domains. I still think this would be easier to have Traefik do that.

**Comment by dtomcej** [comment]
@julienfalque Another option would be to run your own boulder image with your trusted CA as the signing authority.

Then you could leverage Traefik's LetsEncrypt functionality to automatically generate your certificates with your trusted CA as the root.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Slack workspace](https://traefik.herokuapp.com/) for more [community #support](https://traefik.slack.com/messages/C0CDT22PJ/).
