### ISSUE TITLE
Option to turn on/off x-forwarded-* headers

### ISSUE THREAD

**Issue by sidv93** [containous/traefik#4473]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I was wondering if there was an option to disable Traefik from adding headers like "x-forwarded-for" and "x-real-ip". 
Could not find any option to disable it in the docs, but a boolean flag to enable/disable such headers would be a welcome option.

**Comment by geraldcroes** [comment]
Hi, and thank you for your interest in Traefik!

There is currently no plan to add such an option. 

Could you explain your use case so we can understand what you're looking for?

**Comment by sidv93** [comment]
Hi, 
Thank you for the fast response.
I am currently using nginx for a bunch of usecases like reverse-proxy, load balancing. I came across Traefik and decided to migrate from nginx to Traefik. I'm still in the process of migrating. 
Currently, I am currently running Traefik behind nginx and once I have migrated all the functionality from nginx to Traefik, I'll be removing the nginx layer. 

The problem I ran into was with the "x-forwarded-for" and "x-real-ip" headers. Nginx sets these headers with the actual client ip. Traefik also sets these headers with nginx's container IP which is of no use. 
I'm left with two headers now, "x-forwarded-for"(from Traefik) and "x-forwarded_for"(from nginx) in a single request.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Slack workspace](https://traefik.herokuapp.com/) for more [community #support](https://traefik.slack.com/messages/C0CDT22PJ/).
