### ISSUE TITLE
kubernetes: backends not updated when i scale replication controller?

### ISSUE THREAD

**Issue by jonaz** [containous/traefik#448]
Im running: containous/traefik:v1.0.0-rc2

If i scale a rc up or down: ```kubectl scale rc --replicas=4 app```

The backends in traefik does not get updated immediately the the new IPs from the pods. 
If i try accessing service it seems to fetch the new config after a few minutes. Im not really sure. But it should be instant. Or proxy to the service IP and let the service balance it?

Ingress looks like this:
```
kubectl get ingress app-ingress -o yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  creationTimestamp: 2016-05-19T12:47:24Z
  generation: 1
  name: app-ingress
  namespace: default
  resourceVersion: "1902110"
  selfLink: /apis/extensions/v1beta1/namespaces/default/ingresses/app-ingress
  uid: d61148e3-1dbf-11e6-b22b-005056880f6d
spec:
  rules:
  - host: app.domain.com
    http:
      paths:
      - backend:
          serviceName: app
          servicePort: 8080
        path: /
status:
  loadBalancer: {}

```

service looks like this:
```
kubectl get svc app -o yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2016-05-19T12:47:08Z
  name: app
  namespace: default
  resourceVersion: "1902061"
  selfLink: /api/v1/namespaces/default/services/app
  uid: cc2c9d93-1dbf-11e6-b22b-005056880f6d
spec:
  clusterIP: 10.3.130.87
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: app
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

```

**Comment by jonaz** [comment]
I think this is related to #449 since i get "Last kubernetes config received less than 2s, waiting..." and it keeps repeating it self resulting in the config not getting updated.

**Comment by errm** [comment]
sounds like this is caused by #449.

**Comment by errm** [comment]
@emilevauge I am thinking that even in the case that the provider is spamming updates at the server, the correct behaviour would be to update the configuration every 2 seconds?  If this is not the case it seems like there might be a bug somewhere in `Server#listenProviders` ?

**Comment by emilevauge** [comment]
@errm, the property `ProvidersThrottleDuration` as been created to avoid being spammed by providers (for example if you kill 50 containers one shot on Docker). This is not a bug, but a feature :smile:.
What can be done here is to decrease this property to `100ms` for example.
Finally, a deepEquals check is made in `listenConfigurations` https://github.com/containous/traefik/blob/master/server.go#L178, I think it would be better to move it in `listenProviders` https://github.com/containous/traefik/blob/master/server.go#L144, before the Providers Throttle check. Then we would not even wait if configuration doesn't change and skip the event.
WDYT?

**Comment by errm** [comment]
Yeah, thats how I think it should work . . .
