### ISSUE TITLE
How to configure to get ACME ECC cert?

### ISSUE THREAD

**Issue by guotie** [containous/traefik#4488]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I have not see how to get ECC cert in the docs.

**Comment by ldez** [comment]
https://docs.traefik.io/v1.7/configuration/acme/#configuration

```toml
# KeyType to use.
#
# Optional
# Default: "RSA4096"
#
# Available values : "EC256", "EC384", "RSA2048", "RSA4096", "RSA8192"
#
KeyType = "EC384"
```

**Comment by guotie** [comment]
thanks.
