### ISSUE TITLE
Traefik doesn't reload when part of the configuration changes

### ISSUE THREAD

**Issue by gadoor** [containous/traefik#4489]
### Do you want to request a *feature* or report a *bug*?
Bug

### What did you do?
I Changed parts of the configuration, such as for `[tracing]`, `[accessLog]` and `logLevel`...

### What did you expect to see?
I Expected `Traefik` to reload after configuration changed

### What did you see instead?
`Traefik` didn't reload, so I had to reload it manually (`service traefik reload` , `systemctl reload traefik`)

### Output of `traefik version`: 1.7.8

**Comment by ldez** [comment]
https://docs.traefik.io/basics/#configuration
