### ISSUE TITLE
Update lego

### ISSUE THREAD

**Issue by Garogat** [containous/traefik#4491]
Please update lego to version 2.2.0 to include some fixex: 

- [cli] CLI and key type.
- [dnsprovider] httpreq: Endpoint with path.
- [dnsprovider] fastdns: Do not overwrite existing TXT records
- Log wildcard domain correctly in validation

**Comment by ldez** [comment]
all ready done: https://github.com/containous/traefik/pull/4480

https://github.com/containous/traefik/blob/v1.7/CHANGELOG.md#v179-2019-02-11

**Comment by Garogat** [comment]
Sorry missed that.
