### ISSUE TITLE
traefik.toml constraints error: `Expected map but found 'string'.`

### ISSUE THREAD

**Issue by calvinmorrow** [containous/traefik#451]
Using the `containous/traefik:v1.0.0-rc2` docker image against a consulCatalog backend:

traefik.toml snippet:
>[consulCatalog]
>  constraints = ["tag==foo"]

Errors with:
`2016/06/10 15:20:16 Error reading TOML config file /etc/traefik/traefik.toml : Type mismatch for 'main.TraefikConfiguration.ConsulCatalog': Type mismatch for 'provider.ConsulCatalog.Constraints': Type mismatch for types.Constraint. Expected map but found 'string'.`

Using the following command line option works:
`--consulCatalog.constraints=tag==foo`

**Comment by emilevauge** [comment]
Hi @calvinmorrow 
It seems there is an issue with toml documentation on constraints sorry.
```
[[consulCatalog.constraints]]
  key = "tag==foo"
```
should work.
/cc @samber

**Comment by tiagostutz** [comment]
Well, I trying to achieve this with docker, but didn't work. Using global constraint works, but the configuration had to be slightly different:

```
[[constraints]]  
  key = "tag"  
  mustmatch = true  
  regex = "app"  
```

If I put just `key = "tag==foo"` then the **Constraints** object on Global configuration will be:
`"Constraints":[{"Key":"tag","MustMatch":false,"Regex":""}]` 

Putting as I suggest above will fix it, but it is a strange behavior as the code manages to split the constraint into the attributes (Key, MustMatch and Regex). 


Also, I'm confused with the correct syntax. In [#481](https://github.com/containous/traefik/pull/438) it suggests the following syntax, which doesn't work:
```
[docker]
  endpoint = "unix:///var/run/docker.sock"
  constraints = ["tag==api", "tag==he*ld"]
```

**Is the syntax for this configuration already defined as a consensus?**

**Comment by emilevauge** [comment]
Hi @tiagostutz, there is also an issue on toml parsing with constraints. Constraints will fully supported in 1.1.
