### ISSUE TITLE
Add support for web sockets with a mask

### ISSUE THREAD

**Issue by whalehub** [containous/traefik#4513]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

> We got a [user report](https://github.com/Ylianst/MeshCentral/issues/89) that Traefik is reporting a error when our [MeshCentral](https://www.meshcommander.com/meshcentral2) agent connects to the our server thru Traefik:
> 
> `2019-02-10T00:50:54Z" level=error msg="vulcand/oxy/forward/websocket: Error when copying from client to backend: websocket: incorrect mask flag`
> 
> This is likely due to our agent using web sockets without using a "mask". As per [RFC6455](https://tools.ietf.org/html/rfc6455#page-32), we set the "frame-masked" bit to zero and do not provide a mask or XOR the payload.
> 
> We could add a mask, but would prefer not because we are always secured with TLS so don't need to worry about proxies and so, the process seems wasteful. NGNIX and Apache both handle it correctly, but feedback on this topic appreciated. - Thanks. Ylian.

https://github.com/containous/traefik/issues/4487

**Comment by geraldcroes** [comment]
closed in favor of #4487
