### ISSUE TITLE
Lets Encrypt fails for dns-01

### ISSUE THREAD

**Issue by stevens-r** [containous/traefik#4518]
Im following this guide: https://www.smarthomebeginner.com/traefik-reverse-proxy-tutorial-for-docker/

Taefik fails when it tries to get the certs
`
Attaching to traefik
traefik             | 2019-02-22T21:57:42.960507539Z time="2019-02-22T21:57:42Z" level=info msg="legolog: [WARN] [*.domain.xyz] acme: error cleaning up: cloudflare: failed to find zone domain.xyz.: ListZones command failed: error from makeRequest: HTTP status 400: content \"{\\\"success\\\":false,\\\"errors\\\":[{\\\"code\\\":6003,\\\"message\\\":\\\"Invalid request headers\\\",\\\"error_chain\\\":[{\\\"code\\\":6103,\\\"message\\\":\\\"Invalid format for X-Auth-Key header\\\"}]}],\\\"messages\\\":[],\\\"result\\\":null}\" "
traefik             | 2019-02-22T21:57:42.960553769Z time="2019-02-22T21:57:42Z" level=info msg="legolog: [INFO] [domain.xyz] acme: Cleaning DNS-01 challenge"
traefik             | 2019-02-22T21:57:43.051132425Z time="2019-02-22T21:57:43Z" level=debug msg="Wiring frontend frontend-Host-traefik-domain-xyz-0 to entryPoint https"
traefik             | 2019-02-22T21:57:43.051306277Z time="2019-02-22T21:57:43Z" level=debug msg="Creating backend backend-traefik"
traefik             | 2019-02-22T21:57:43.051443235Z time="2019-02-22T21:57:43Z" level=debug msg="Adding secure middleware for frontend frontend-Host-traefik-domain-xyz-0"
traefik             | 2019-02-22T21:57:43.051576761Z time="2019-02-22T21:57:43Z" level=debug msg="Adding TLSClientHeaders middleware for frontend frontend-Host-traefik-domain-xyz-0"
traefik             | 2019-02-22T21:57:43.051723178Z time="2019-02-22T21:57:43Z" level=debug msg="Creating load-balancer wrr"
traefik             | 2019-02-22T21:57:43.051872729Z time="2019-02-22T21:57:43Z" level=debug msg="Creating server server-traefik-e42dd141b28258fda36b39d92119a422 at http://172.19.0.2:8080 with weight 1"
traefik             | 2019-02-22T21:57:43.052062411Z time="2019-02-22T21:57:43Z" level=debug msg="Creating route route-frontend-Host-traefik-domain-xyz-0 Host:traefik.domain.xyz"
traefik             | 2019-02-22T21:57:43.052191661Z time="2019-02-22T21:57:43Z" level=debug msg="Wiring frontend frontend-Host-traefik-domain-xyz-0 to entryPoint http"
traefik             | 2019-02-22T21:57:43.052318378Z time="2019-02-22T21:57:43Z" level=debug msg="Creating backend backend-traefik"
traefik             | 2019-02-22T21:57:43.052447342Z time="2019-02-22T21:57:43Z" level=debug msg="Adding secure middleware for frontend frontend-Host-traefik-domain-xyz-0"
traefik             | 2019-02-22T21:57:43.052574749Z time="2019-02-22T21:57:43Z" level=debug msg="Adding TLSClientHeaders middleware for frontend frontend-Host-traefik-domain-xyz-0"
traefik             | 2019-02-22T21:57:43.052710661Z time="2019-02-22T21:57:43Z" level=debug msg="Creating load-balancer wrr"
traefik             | 2019-02-22T21:57:43.052847951Z time="2019-02-22T21:57:43Z" level=debug msg="Creating server server-traefik-e42dd141b28258fda36b39d92119a422 at http://172.19.0.2:8080 with weight 1"
traefik             | 2019-02-22T21:57:43.053016640Z time="2019-02-22T21:57:43Z" level=debug msg="Creating route route-frontend-Host-traefik-domain-xyz-0 Host:traefik.domain.xyz"
traefik             | 2019-02-22T21:57:43.053160849Z time="2019-02-22T21:57:43Z" level=info msg="Server configuration reloaded on :8080"
traefik             | 2019-02-22T21:57:43.053288911Z time="2019-02-22T21:57:43Z" level=info msg="Server configuration reloaded on :443"
traefik             | 2019-02-22T21:57:43.053416512Z time="2019-02-22T21:57:43Z" level=info msg="Server configuration reloaded on :80"
traefik             | 2019-02-22T21:57:43.213580521Z time="2019-02-22T21:57:43Z" level=info msg="legolog: [WARN] [domain.xyz] acme: error cleaning up: cloudflare: failed to find zone domain.xyz.: ListZones command failed: error from makeRequest: HTTP status 400: content \"{\\\"success\\\":false,\\\"errors\\\":[{\\\"code\\\":6003,\\\"message\\\":\\\"Invalid request headers\\\",\\\"error_chain\\\":[{\\\"code\\\":6103,\\\"message\\\":\\\"Invalid format for X-Auth-Key header\\\"}]}],\\\"messages\\\":[],\\\"result\\\":null}\" "
traefik             | 2019-02-22T21:57:43.213764750Z time="2019-02-22T21:57:43Z" level=error msg="Error obtaining certificate retrying in 604.561091ms"
traefik             | 2019-02-22T21:57:43.818706022Z time="2019-02-22T21:57:43Z" level=info msg="legolog: [INFO] [*.domain.xyz, domain.xyz] acme: Obtaining bundled SAN certificate"
traefik             | 2019-02-22T21:57:44.189473674Z time="2019-02-22T21:57:44Z" level=info msg="legolog: [INFO] [*.domain.xyz] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz/KESr-WIVhlTZB5havZwTjtF4KS6sFOhSZF912Hl8ObA"
traefik             | 2019-02-22T21:57:44.189659999Z time="2019-02-22T21:57:44Z" level=info msg="legolog: [INFO] [domain.xyz] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz/w-ZThRpMaTtLDgVRrxK3gpaCWrertsFI-5BeZeHpBOs"
traefik             | 2019-02-22T21:57:44.189803992Z time="2019-02-22T21:57:44Z" level=info msg="legolog: [INFO] [*.domain.xyz] acme: use dns-01 solver"
traefik             | 2019-02-22T21:57:44.189934622Z time="2019-02-22T21:57:44Z" level=info msg="legolog: [INFO] [domain.xyz] acme: Could not find solver for: tls-alpn-01"
traefik             | 2019-02-22T21:57:44.190052400Z time="2019-02-22T21:57:44Z" level=info msg="legolog: [INFO] [domain.xyz] acme: Could not find solver for: http-01"
traefik             | 2019-02-22T21:57:44.190170528Z time="2019-02-22T21:57:44Z" level=info msg="legolog: [INFO] [domain.xyz] acme: use dns-01 solver"
traefik             | 2019-02-22T21:57:44.190368074Z time="2019-02-22T21:57:44Z" level=info msg="legolog: [INFO] [*.domain.xyz] acme: Preparing to solve DNS-01"
traefik             | 2019-02-22T21:57:44.294536846Z time="2019-02-22T21:57:44Z" level=info msg="legolog: [INFO] [domain.xyz] acme: Preparing to solve DNS-01"
traefik             | 2019-02-22T21:57:44.575616590Z time="2019-02-22T21:57:44Z" level=info msg="legolog: [INFO] [*.domain.xyz] acme: Cleaning DNS-01 challenge"
traefik             | 2019-02-22T21:57:44.795070770Z time="2019-02-22T21:57:44Z" level=info msg="legolog: [WARN] [*.domain.xyz] acme: error cleaning up: cloudflare: failed to find zone domain.xyz.: ListZones command failed: error from makeRequest: HTTP status 400: content \"{\\\"success\\\":false,\\\"errors\\\":[{\\\"code\\\":6003,\\\"message\\\":\\\"Invalid request headers\\\",\\\"error_chain\\\":[{\\\"code\\\":6103,\\\"message\\\":\\\"Invalid format for X-Auth-Key header\\\"}]}],\\\"messages\\\":[],\\\"result\\\":null}\" "
traefik             | 2019-02-22T21:57:44.795106017Z time="2019-02-22T21:57:44Z" level=info msg="legolog: [INFO] [domain.xyz] acme: Cleaning DNS-01 challenge"
traefik             | 2019-02-22T21:57:45.041477954Z time="2019-02-22T21:57:45Z" level=info msg="legolog: [WARN] [domain.xyz] acme: error cleaning up: cloudflare: failed to find zone domain.xyz.: ListZones command failed: error from makeRequest: HTTP status 400: content \"{\\\"success\\\":false,\\\"errors\\\":[{\\\"code\\\":6003,\\\"message\\\":\\\"Invalid request headers\\\",\\\"error_chain\\\":[{\\\"code\\\":6103,\\\"message\\\":\\\"Invalid format for X-Auth-Key header\\\"}]}],\\\"messages\\\":[],\\\"result\\\":null}\" "
traefik             | 2019-02-22T21:57:45.041515443Z time="2019-02-22T21:57:45Z" level=error msg="Error obtaining certificate retrying in 713.888017ms"
traefik             | 2019-02-22T21:57:45.755536785Z time="2019-02-22T21:57:45Z" level=info msg="legolog: [INFO] [*.domain.xyz, domain.xyz] acme: Obtaining bundled SAN certificate"
traefik             | 2019-02-22T21:57:46.151961870Z time="2019-02-22T21:57:46Z" level=info msg="legolog: [INFO] [*.domain.xyz] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz/KESr-WIVhlTZB5havZwTjtF4KS6sFOhSZF912Hl8ObA"
traefik             | 2019-02-22T21:57:46.151996828Z time="2019-02-22T21:57:46Z" level=info msg="legolog: [INFO] [domain.xyz] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz/w-ZThRpMaTtLDgVRrxK3gpaCWrertsFI-5BeZeHpBOs"
traefik             | 2019-02-22T21:57:46.152008672Z time="2019-02-22T21:57:46Z" level=info msg="legolog: [INFO] [*.domain.xyz] acme: use dns-01 solver"
traefik             | 2019-02-22T21:57:46.152017422Z time="2019-02-22T21:57:46Z" level=info msg="legolog: [INFO] [domain.xyz] acme: Could not find solver for: tls-alpn-01"
traefik             | 2019-02-22T21:57:46.152028645Z time="2019-02-22T21:57:46Z" level=info msg="legolog: [INFO] [domain.xyz] acme: Could not find solver for: http-01"
traefik             | 2019-02-22T21:57:46.152078075Z time="2019-02-22T21:57:46Z" level=info msg="legolog: [INFO] [domain.xyz] acme: use dns-01 solver"
traefik             | 2019-02-22T21:57:46.152212963Z time="2019-02-22T21:57:46Z" level=info msg="legolog: [INFO] [*.domain.xyz] acme: Preparing to solve DNS-01"
traefik             | 2019-02-22T21:57:46.253755156Z time="2019-02-22T21:57:46Z" level=info msg="legolog: [INFO] [domain.xyz] acme: Preparing to solve DNS-01"
traefik             | 2019-02-22T21:57:46.498062604Z time="2019-02-22T21:57:46Z" level=info msg="legolog: [INFO] [*.domain.xyz] acme: Cleaning DNS-01 challenge"
traefik             | 2019-02-22T21:57:46.752529624Z time="2019-02-22T21:57:46Z" level=info msg="legolog: [WARN] [*.domain.xyz] acme: error cleaning up: cloudflare: failed to find zone domain.xyz.: ListZones command failed: error from makeRequest: HTTP status 400: content \"{\\\"success\\\":false,\\\"errors\\\":[{\\\"code\\\":6003,\\\"message\\\":\\\"Invalid request headers\\\",\\\"error_chain\\\":[{\\\"code\\\":6103,\\\"message\\\":\\\"Invalid format for X-Auth-Key header\\\"}]}],\\\"messages\\\":[],\\\"result\\\":null}\" "
traefik             | 2019-02-22T21:57:46.752574223Z time="2019-02-22T21:57:46Z" level=info msg="legolog: [INFO] [domain.xyz] acme: Cleaning DNS-01 challenge"
traefik             | 2019-02-22T21:57:46.995785914Z time="2019-02-22T21:57:46Z" level=info msg="legolog: [WARN] [domain.xyz] acme: error cleaning up: cloudflare: failed to find zone domain.xyz.: ListZones command failed: error from makeRequest: HTTP status 400: content \"{\\\"success\\\":false,\\\"errors\\\":[{\\\"code\\\":6003,\\\"message\\\":\\\"Invalid request headers\\\",\\\"error_chain\\\":[{\\\"code\\\":6103,\\\"message\\\":\\\"Invalid format for X-Auth-Key header\\\"}]}],\\\"messages\\\":[],\\\"result\\\":null}\" "
traefik             | 2019-02-22T21:57:46.995824679Z time="2019-02-22T21:57:46Z" level=error msg="Error obtaining certificate: acme: Error -> One or more domains had a problem:\n[*.domain.xyz] [*.domain.xyz] acme: error presenting token: cloudflare: failed to find zone domain.xyz.: ListZones command failed: error from makeRequest: HTTP status 400: content \"{\\\"success\\\":false,\\\"errors\\\":[{\\\"code\\\":6003,\\\"message\\\":\\\"Invalid request headers\\\",\\\"error_chain\\\":[{\\\"code\\\":6103,\\\"message\\\":\\\"Invalid format for X-Auth-Key header\\\"}]}],\\\"messages\\\":[],\\\"result\\\":null}\"\n[domain.xyz] [domain.xyz] acme: error presenting token: cloudflare: failed to find zone domain.xyz.: ListZones command failed: error from makeRequest: HTTP status 400: content \"{\\\"success\\\":false,\\\"errors\\\":[{\\\"code\\\":6003,\\\"message\\\":\\\"Invalid request headers\\\",\\\"error_chain\\\":[{\\\"code\\\":6103,\\\"message\\\":\\\"Invalid format for X-Auth-Key header\\\"}]}],\\\"messages\\\":[],\\\"result\\\":null}\"\n"
traefik             | 2019-02-22T21:57:46.995861761Z time="2019-02-22T21:57:46Z" level=error msg="Unable to obtain ACME certificate for domains \"*.domain.xyz,domain.xyz\" : unable to generate a certificate for the domains [*.domain.xyz domain.xyz]: acme: Error -> One or more domains had a problem:\n[*.domain.xyz] [*.domain.xyz] acme: error presenting token: cloudflare: failed to find zone domain.xyz.: ListZones command failed: error from makeRequest: HTTP status 400: content \"{\\\"success\\\":false,\\\"errors\\\":[{\\\"code\\\":6003,\\\"message\\\":\\\"Invalid request headers\\\",\\\"error_chain\\\":[{\\\"code\\\":6103,\\\"message\\\":\\\"Invalid format for X-Auth-Key header\\\"}]}],\\\"messages\\\":[],\\\"result\\\":null}\"\n[domain.xyz] [domain.xyz] acme: error presenting token: cloudflare: failed to find zone domain.xyz.: ListZones command failed: error from makeRequest: HTTP status 400: content \"{\\\"success\\\":false,\\\"errors\\\":[{\\\"code\\\":6003,\\\"message\\\":\\\"Invalid request headers\\\",\\\"error_chain\\\":[{\\\"code\\\":6103,\\\"message\\\":\\\"Invalid format for X-Auth-Key header\\\"}]}],\\\"messages\\\":[],\\\"result\\\":null}\"\n"
`

traefik.toml

debug = true

logLevel = "ERROR" #DEBUG, INFO, WARN, ERROR, FATAL, PANIC
InsecureSkipVerify = true
defaultEntryPoints = ["https", "http"]

[api]
  entryPoint = "traefik"
  dashboard = true
  address = ":8080"
  usersFile = "/shared/.htpasswd"

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[file]
  watch = true
  filename = "/etc/traefik/rules.toml"

[acme]
email = "email@me.com" #any email id will work
storage="/etc/traefik/acme/acme.json"
caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
entryPoint = "https"
acmeLogging=true
onDemand = false #create certificate when container is created
[acme.dnsChallenge]
  provider = "cloudflare"
  delayBeforeCheck = 0
[[acme.domains]]
   main = "*.domain.xyz"
   sans = ["domain.xyz"]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "domain.xyz"
watch = true
exposedbydefault = false

docker-compose.yml

traefik:
    hostname: traefik
    image: traefik:latest
    container_name: traefik
    restart: always
    domainname: ${DOMAINNAME}
    networks:
      - default
      - traefik_proxy
    ports:
      - "80:80"
      - "443:443"

    environment:
      - CF_API_EMAIL=${CLOUDFLARE_EMAIL}
      - CF_API_KEY=${CLOUDFLARE_API_KEY}
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.frontend.rule=Host:traefik.${DOMAINNAME}"
      - "traefik.port=8080"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=example.com"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${USERDIR}/docker/traefik:/etc/traefik
      - ${USERDIR}/docker/shared:/shared

**Comment by stevens-r** [comment]
requested a new API key from cloudflare and everything is working now

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

Thanks again for your interest in Traefik!

I'm glad to close the issue because I think that the question has been answered (Yes, I'm quite an advanced AI :smile:)

Join our [Slack workspace](https://slack.traefik.io/) for more [community #support](https://traefik.slack.com/messages/C0CDT22PJ/).
