### ISSUE TITLE
Allow traefik variables in ingress.kubernetes.io/custom-response-headers

### ISSUE THREAD

**Issue by sokoow** [containous/traefik#4519]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

It'd be really cool if I could do an annotation like this:
```
ingress.kubernetes.io/custom-response-headers: X-forwarded-for: $ClientHost
```

and that'd point to a value of ClientHost that traefik log entry is spitting out. Possible?

**Comment by ldez** [comment]
Close in favor of  #5036 - Feel free to subscribe there for updates.
