### ISSUE TITLE
"Not Found" api response needed instead of 404 

### ISSUE THREAD

**Issue by erolg** [containous/traefik#454]
When we sent request that is not correct (typo, deleted backend etc.) return 404

``/api/providers/docker/backends/backend-whoam` -> 404`

If it returns to "Not Found" json object, I think could be more usefull to handle response.

**Comment by samber** [comment]
Hi @erolg 

Do you mean returning a json instead of a raw string ?

Something like :

```
{
    "error": 404,
    "message": "Not found"
}
```

You can already handle the error using the returned status code ;-)

**Comment by emilevauge** [comment]
As @samber said, traefik already returns a 404 status code. As there is no standard on how to format errors in a JSON response, I prefer to stay simple for now and use status codes :)
