### ISSUE TITLE
More visibility into ACME state

### ISSUE THREAD

**Issue by atombender** [containous/traefik#4552]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

We use Traefik as an ingress controller with Kubernetes. Today we waited 3 hours for a new host to get an ACME cert. During that time, there was absolutely nothing in the log about the cert's state.

While this might be caused by a bug, the fact remains that Traefik provides very little visibility into the state of ACME cert registration.

The logs usually aren't very helpful when nothing is happening, and the ACME object in the K/V store only has information about allocated certs, not in-flight ones.

**Comment by geraldcroes** [comment]
Hi, and thanks for reporting this issue.

I might be wrong, but it seems to me that there are many available logs with the debug mode and the acmeLogging option.

I've looked into it, and I don't see an obvious  use case / setup where Traefik would silently wait 3 hours to get its certificate without giving the user any information on what's going on.

Could you elaborate a bit more on your setup so we can understand this better?

Thanks a lot.

**Comment by atombender** [comment]
[Here](https://github.com/containous/traefik/files/2932493/traefik-newhost.log.gz) is an extract from our log, with `acmeLogging` and debug logging enabled. The log shows from the point when a new host `test.internal.plocal.io` has been added to the ingress, then nothing interesting, except for the periodic "No certificate found or generated" messages. Then 5 minutes later, the ACME cert is finally allocated. Before that time, there is no information relating to the domain being logged, and it's completely unclear what Traefik is up to. 

Our earlier scenario took about 3 hours before we got a cert. [This Slack thread](https://traefik.slack.com/archives/C0CDT22PJ/p1551721394095800) has all the information you need such as configuration. I was talking to @dtomcej and @ldez yesterday. I didn't get much from them. I've not heard back since yesterday.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Slack workspace](https://traefik.herokuapp.com/) for more [community #support](https://traefik.slack.com/messages/C0CDT22PJ/).
