### ISSUE TITLE
Traefik Failed Acme Renewal for unused cert

### ISSUE THREAD

**Issue by morganphilo** [containous/traefik#4567]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I assigned a domain 'example.com' to Traefik and it generated the cert and my site ran well. Months later I removed the domain and migrated it to another kubernetes cluster on another IP and another Traefik instance. 

### What did you expect to see?
Ignores the old certificate renewal as there is no binding for it. 

### What did you see instead?
The original cluster is now trying to renew the old certificate even though no ingress is assigned to it, and it is not in the domain list. 
This also causes memory usage spikes leading to OOM errors so I increased the resource limit in Kubernetes; but I have no solid evidence to substantiate it.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
1.7.4
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
loadBalancerIP: ***.**.***.***
debug:
    enabled: false
ssl:
    enabled: true
    enforced: true
acme:
    enabled: true
    challengeType: http-01
    email: ***@example.com
    staging: false
    logging: true
    domains:
        domainList: ['notexample.com']
dashboard:
    enabled: true
    domain: ingress.notexample.com
sendAnonymousUsage: true
memoryLimit: 300Mi
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
legolog: [INFO] [example.com] acme: Trying renewal with 23 hours remaining
legolog: [INFO] [example.com] acme: Obtaining bundled SAN certificate
Error renewing certificate from LE: {example.com []}, acme: Error 429 - urn:ietf:params:acme:error:rateLimited - Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/
```

**Comment by emilevauge** [comment]
Hey @morganphilo, after discussing with the team, we think your issue is maybe due to a bad configuration. At each restart, Traefik tries to renew the certificate, hits the memory limit, is killed, and finally, reaches the Let's Encrypt rate limits.
You should raise the memory limits on your pod, and then wait for the LE rate limits to be cleared.
WDYT?

**Comment by morganphilo** [comment]
Hi Emile, yup that sounds like a good solution and it's exactly what I did as you can see in the config above. It's a bit of a gotcha because the default helm chart had the memory limit at 20Mi. 

It would be nice if it didn't try and renew the cert (for a domain no longer pointing to this traefik instance) and hitting the rate limit for certs that are no longer bound in the domain list. Just so it doesn't spike memory and also doesn't flood LE causing it to be throttled. But with your suggested config change all is resolved.
