### ISSUE TITLE
Docker Provider: add traefik.backend.circuitbreaker & maxconn support

### ISSUE THREAD

**Issue by shouze** [containous/traefik#457]
Is it planned (and possible) to support circuit breaker in docker (so swarm?) provider, like in the [consul catalog provider](https://github.com/containous/traefik/pull/254)?

If yes, interested to take on it (even more if swarm compatibility). Also, is it recommended to use consul catalog rather than docker (swarm) backend in production?

**Comment by traefiker** [comment]
I'll close the issue due to inactivity but feel free to re-open if needed.
