### ISSUE TITLE
storeconfig error json: unsupported type: func() time.Time

### ISSUE THREAD

**Issue by devster31** [containous/traefik#4574]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
```
docker run -it --rm --network=home_default traefik:maroilles-alpine storeconfig \
  --accesslog \
  --api \
  --docker \
  --docker.domain="<domain>,home" \
  --docker.network=backend \
  --acme.acmelogging=true \
  --acme.dnschallenge.provider=cloudflare \
  --acme.dnschallenge=true \
  --acme.domains="*.<domain>,<domain>" \
  --acme.email="<email>" \
  --acme.entrypoint=https \
  --acme.storage="traefik/acme/account" \
  --acme.tlsconfig=true \
  --acme=true \
  --defaultentrypoints="http,https" \
  --entryPoints="Name:http Address::80 Redirect.EntryPoint:https" \
  --entryPoints="Name:https Address::443 Compress:true TLS Tls.minVersion:VersionTLS12" \
  --etcd \
  --etcd.endpoint=etcd:2379 \
  --etcd.useapiv3=true \
  --keeptrailingslash=true \
  --debug
```

### What did you expect to see?
config uploaded into ETCD

### What did you see instead?
```
2019/03/10 13:19:40 Error running traefik: json: unsupported type: func() time.Time
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.9
Codename:     maroilles
Go version:   go1.11.5
Built:        2019-02-11_11:36:32AM
OS/Arch:      linux/amd64
```

**Comment by ddtmachado** [comment]
This error comes from acme and is not related to ETCD at all. 
You can check by removing the acme config flags.

Maybe the problem resides in [lego](https://github.com/go-acme/lego) and not Traefik but I still need to confirm that.

**Comment by ddtmachado** [comment]
@devster31 I just confirmed that this issue is related to the flag `--acme.tlsconfig=true`, which is not a supported flag at all and marked as deprecated internally.

By removing this flag everything else should work well. And if you are not sure how to configure TLS when using a wildcard certificate with acme feel free to ask on the community forums at https://community.containo.us/
