### ISSUE TITLE
rateLimit as docker service label do not apply

### ISSUE THREAD

**Issue by sebastianlutter** [containous/traefik#4576]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I have set up a docker stack including traefik and nginx. Want to use rateLimit labels in my docker-compose.yml for the nginx webservice. I added the labels according to the [docker backend documentation](https://docs.traefik.io/configuration/backends/docker/#using-docker-compose) which describes the following labels:
```
traefik.frontend.rateLimit.rateSet.<name>.period
traefik.frontend.rateLimit.rateSet.<name>.burst
traefik.frontend.rateLimit.rateSet.<name>.average
traefik.frontend.rateLimit.extractorfunc
```

I used them as service labels and deploy labels in my docker-compose.yml file, with and without the `<name>` part, but the rate limit was never applied to the container (tested with apache benchmarks)

Here you can find the code/stack configuration I used (minmal runable example):
* https://github.com/sebastianlutter/traefik_ratelimit

### What did you expect to see?

I expected that the rate limits apply to the webservice when the rateLimit labels are set as deploy labels in the service in docker-compose.yml.

### What did you see instead?

When I use some random name for the <name> placeholder the traefik service does not start up with 500 config error in logs. Without the <name> part traefik does start.

When used as service deploy labels the labels are part of **.Spec.Labels** when inspecting the service, but the container does not show them. 

When used as service labels they show up in **.TaskTemplate.ContainerSpec.Labels** when inspecting the service, and they show up in **.Config.Labels** on the task container the service creates.

In both cases the rate limit does not work when I test it with apache benchmark. Set rate limit to average=100, burst=200,period=10s, and got ~600 #/sec when doing benchmark.

Is rateLimits via service labels in a docker stack supported? Do I use the right syntax? Why does the rateLimit not apply to the service?

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.9
Codename:     maroilles
Go version:   go1.11.5
Built:        2019-02-11_11:36:32AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Configuration of traefik is done in docker stack configuration file (docker-compose.yml) via command tag
```yml
    command: >
      --docker
      --docker.swarmmode
      --docker.watch
      --docker.exposedbydefault=false
      --constraints=tag==public-gateway
      --entrypoints='Name:http Address::80'
      --entrypoints='Name:https Address::443 TLS'
      --consul
      --consul.endpoint="consul-leader:8500"
      --logLevel=DEBUG
      --accessLog
      --api
```

Frontend and backend configuration is done by service deploy labels:
* https://github.com/sebastianlutter/traefik_ratelimit/blob/master/docker-compose-gateway.yml

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

Don't think log is relevant, but I can add it if requested. Just ask.

**Comment by tretail** [comment]
Hello,

Did you try to write extractorfunc in camelCase? And without time unit for the period?

```
        - traefik.frontend.rateLimit.rateSet.period=10
        - traefik.frontend.rateLimit.rateSet.burst=200
        - traefik.frontend.rateLimit.rateSet.average=100
        - traefik.frontend.rateLimit.extractorFunc=client.ip
```

**Comment by sebastianlutter** [comment]
Thanks, you made my day :)

Camel case for extractorFunc did the trick. RateLimit works well with docker swarm services when you use them as deploy labels in your services and with <name> filled with an arbitrary name.

```bash
    deploy:
      labels:
        - traefik.frontend.rule=Host:${DOMAIN}
        - traefik.enable=true
        - traefik.port=80
        - traefik.tags=public-gateway
        - traefik.docker.network=public-gateway
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
#        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https
        # Rate limits with rateSet name "test" (traefik config error)
        - traefik.frontend.rateLimit.rateSet.test.period=10s
        - traefik.frontend.rateLimit.rateSet.test.burst=200
        - traefik.frontend.rateLimit.rateSet.test.average=100
        - traefik.frontend.rateLimit.extractorFunc=client.ip
```

Then in the traefik service log it starts to mention rateLimits (log level debug)
```bash
[ ... ]
time="2019-03-19T09:43:25Z" level=debug msg="Creating load-balancer rate limiter"
[ ... ]
```

When doing a benchmark the rate limit works
```bash
$ ab -c1 -n500 -l http://foo.bar/
[ ... ]
Time taken for tests:   0.675 seconds
Complete requests:      500
Failed requests:        0
Non-2xx responses:      294
[ ... ]
```
```bash
[ ... ]
time="2019-03-19T09:45:12Z" level=warning msg="limiting request GET /, limit: max rate reached: retry-in 100ms"
10.255.0.2 - - [19/Mar/2019:09:45:12 +0000] "GET / HTTP/1.0" 429 32 "-" "ApacheBench/2.3" 498 "rate limit for frontend-redirectorservice-gateway-webservice-redirectorservice" "/" 0ms
time="2019-03-19T09:45:12Z" level=warning msg="limiting request GET /, limit: max rate reached: retry-in 100ms"
10.255.0.2 - - [19/Mar/2019:09:45:12 +0000] "GET / HTTP/1.0" 429 32 "-" "ApacheBench/2.3" 499 "rate limit for frontend-redirectorservice-gateway-webservice-redirectorservice" "/" 0ms
time="2019-03-19T09:45:12Z" level=warning msg="limiting request GET /, limit: max rate reached: retry-in 100ms"
10.255.0.2 - - [19/Mar/2019:09:45:12 +0000] "GET / HTTP/1.0" 429 32 "-" "ApacheBench/2.3" 500 "rate limit for frontend-redirectorservice-gateway-webservice-redirectorservice" "/" 0ms
[ ... ]
```

It allowed about 200 queries and after that the benchmark got 294 non-2xx responses. :)

The documentation shows **extractorFunc** in camel case, so it was just a dump typo. I nevertheless answer this a little more verbose because I found it hard to gather all needed informations about traefik 
rateLimit in docker stack services.

**Comment by ValentinoDefelice** [comment]
Hello! Can anyone tell me if Traefik have some option to display IP client blocked? Or how to do it?
Thank you so much.
