### ISSUE TITLE
Make Host entry in Dashboard clickable

### ISSUE THREAD

**Issue by turbo** [containous/traefik#4583]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Because there are many services running in my swarm, I frequently use Traefik's dashboard to as a starting point in order to navigate to a given service. Currently, the `Host` entry in frontends is an inline-code element, and it would be nice for it to be a link, too.

**Comment by ldez** [comment]
Duplicate of #2835
