### ISSUE TITLE
INWX Provider Docs Wrong

### ISSUE THREAD

**Issue by ksm2** [containous/traefik#4586]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Navigated to https://docs.traefik.io/configuration/acme/#provider

### What did you expect to see?

The docs should state the env variable `INWX_USER`.

### What did you see instead?

The docs state the env variable `INWX_USERNAME` which is not working.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Traefik version v1.7.9 built on 2019-02-11_11:36:32AM
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# (paste your configuration here)
```

**Comment by ldez** [comment]
Hello, the env vars for INWX are `INWX_USERNAME` and `INWX_PASSWORD`.

The documentation is right :
- https://github.com/containous/traefik/blob/v1.7/docs/configuration/acme.md#provider
- https://go-acme.github.io/lego/dns/inwx/

https://github.com/containous/traefik/blob/fcc4cab61447adeeb2311da004fd9580442b78b9/vendor/github.com/go-acme/lego/providers/dns/inwx/inwx.go#L45

**Comment by ksm2** [comment]
Yeah, I am sorry, it did not work and after finding [this repository](https://github.com/smueller18/traefik-inwx) I gave it a try and it worked (funny enough). Sorry for bothering!
