### ISSUE TITLE
Traefik Does Not Assign SSL from LetsEncrypt

### ISSUE THREAD

**Issue by patientplatypus** [containous/traefik#4608]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I'm creating a docker-swarm with traefik as a load balancer and attempting to get an ssl through letsEncrypt.

### What did you expect to see?

My site to be able to get an ssl and have an `https://` address.

### What did you see instead?

I've got this: 

<img width="1680" alt="Screen Shot 2019-03-16 at 3 50 44 PM" src="https://user-images.githubusercontent.com/24575107/54481518-88478100-4803-11e9-89aa-a45db14ac806.png">

### Output of `traefik version`: (_What version of Traefik are you using?_)

Version 1.5

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

You can view that here: https://stackoverflow.com/questions/55201034/traefik-ssl-letsencrypt-faulty

### Why I am submitting this as a bug report (rather than support)

Lack of clear examples to get even a simple version of letsEncrypt to work is incredibly frustrating. This example (https://stackoverflow.com/questions/48408184/traefik-will-issue-certificate-instead-of-lets-encrypt?rq=1) is the only other place on the internet that has a mention of this issue after a week of looking and that doesn't solve the issue. It's also worth mentioning that here (and elsewhere) https://docs.traefik.io/configuration/acme/ has: 

```
[acme]
  # ...
  entryPoint = "https"
  [acme.httpChallenge]
    entryPoint = "http"
```

Which appears to be incorrect. Rather it should be the following as far as I can tell: 

```
[acme]
  # ...
  entryPoint = "https"
    [acme.httpChallenge]
      entryPoint = "http"
```

The above mentioned documentation nor https://docs.traefik.io/user-guide/docker-and-lets-encrypt/ is helpful here. As far as I can tell this is an issue with traefik itself.

**Comment by Power2All** [comment]
I have the same problem.
403 errors even on requesting new certificates.

**Comment by patientplatypus** [comment]
This issue is interesting enough that I will place a bounty tomorrow when I am able. One of the things you may try Power2All is to `docker service logs <YOURTRAEFICLB>` and make sure that you are not getting any weird bugs - a common one is that you are requesting to many certs from letsencrypt. You can check that and other potential problem by going to letsdebug.net. I hope that helps

**Comment by jbdoumenjou** [comment]
Hi @patientplatypus , thanks for your interest in the project.

Could you try with the last version of traefik ?

**Comment by patientplatypus** [comment]
Ah, apologies for misspeaking, but I believe I am. My `traefik.yaml` file has `image: traefik` which I spin up in a docker-compose swarm. You can see the full architecture at the stackoverflow link above.

**Comment by dtomcej** [comment]
@patientplatypus
```
image: traefik
```
Just runs the latest image that you have on your machine, which can be quite old if not pulled explicitly.

Could you try with:
```
image: traefik:v1.7.9
```
To confirm that you are running the latest version?

**Comment by patientplatypus** [comment]
Ok, I've gone ahead and done that but I am currently seeing the following:

`too many certificates already issued for exact set of domains: lowteck.com,www.lowteck.com: see https://letsencrypt.org/docs/rate-limits/, url: `

So it would appear that I have to wait a few more days (again...) to get this resolved.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

Thanks again for your interest in Traefik!

I'm glad to close the issue because I think that the question has been answered (Yes, I'm quite an advanced AI :smile:)

Join our [Slack workspace](https://slack.traefik.io/) for more [community #support](https://traefik.slack.com/messages/C0CDT22PJ/).
