### ISSUE TITLE
Traefik generates really long Jaeger operation names

### ISSUE THREAD

**Issue by kinghuang** [containous/traefik#4619]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I've configured Traefik to send traces to Jaeger. My Traefik frontends and backends come from Docker Swarm services. Traefik appears to generate operation names by concatenating the frontend and backend names as `frontend name/backend name`.

In my case, this results in really long operations like `forward frontend-externalroutes-oauth2-server-uat-oauth2-server-externalroutes/backend-oauth2-server-uat-oauth2-server-externalroutes`. These super long operation names are unreadable in the Jaeger UI.

![image](https://user-images.githubusercontent.com/27340/54545660-b47c1280-4967-11e9-93b5-6ece7201511c.png)

### What did you expect to see?

I've filed jaegertracing/jaeger#1429 about how the Jaeger UI handles long operation names. From a Traefik perspective, perhaps there should be a way to generate shorter/custom operation names.

### What did you see instead?

Traefik generated a super long operation name.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.9
Codename:     maroilles
Go version:   go1.11.5
Built:        2019-02-11_11:36:32AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Traefik is running on Docker Swarm, and auto registering Docker services.

```
--docker
--docker.swarmmode
--docker.watch
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

N/A

**Comment by dduportal** [comment]
Hi @kinghuang , thanks for your interest in the project and your complete feedback.

Alas there is no way to allows overriding these names, as the conveyed information, and the need of homogeneity across different sub system make this "way" of generating the name to be mandatory.

Feel free to reach the community on our Slack channel at slack.traefik.io if you require more help, as this request is not considered a bug in Traefik.
