### ISSUE TITLE
Support for FQDNs with trailing period.

### ISSUE THREAD

**Issue by lomkju** [containous/traefik#4622]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
Tried to use a FQDN with trailing period.

### What did you expect to see?
Traefik should accept FQDNs with trailing periods for frontend rules.

In simple words the host with the extra dot at the end doesn’t get matched with the frontend rule without the extra last dot.
```
myhost.com
vs
myhost.com. (still FQDN)
```
The slack thread with @dtomcej about this issue.
https://traefik.slack.com/archives/C0CDT22PJ/p1552912165642000
The RFC:
https://tools.ietf.org/html/rfc3986#section-3.2.2

### What did you see instead?
The frontend rule doesn’t seem to match with the FQDN when a trailing period is used.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
traefik:v1.7.9
```

**Comment by dtomcej** [comment]
Confirmed issue. Having a FQDN terminated with a `.` is within the spec of the RFC, and may be present in the host header/request

**Comment by traefiker** [comment]
Closed by #4763.
