### ISSUE TITLE
Issue with empty responses

### ISSUE THREAD

**Issue by emilevauge** [containous/traefik#463]
Between beta 744 and 754, traefik, sometimes (...), replies empty reponses.
It is likely linked to the fix https://github.com/vulcand/oxy/pull/44/files#diff-d86a3ca91dd50cb2fd715e585145d6dcL180

/cc @pferrot

**Comment by pferrot** [comment]
This is indeed fixed, but it seems that there is a new bug in RC3 (see #485) . Might have been introduced with the fix...!?
