### ISSUE TITLE
Using rancher 2.1.6 as provider: Cannot get Provider Stacks Unknown schema type

### ISSUE THREAD

**Issue by melkishengue** [containous/traefik#4637]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

 I coonfigured traefik to connect to rancher 2.1.6 but I am getting unexpected errors:

```
ERRO[2019-03-19T20:07:11Z] Provider connection error Bad response statusCode [404]. Status [404 Not Found]. Body: [404 page not found
] from [https://rancher-hip.cs.upb.de/v2-beta], retrying in 5.392911182s
```

For some reason traefik is trying to connect to the endoint https://rancher-hip.cs.upb.de/v2-beta although I specified in .toml file as endpoint https://rancher-hip.cs.upb.de

BTW: generating the credentials in rancher UI gave me https://rancher-hip.cs.upb.de/v3 as endpoint, but I got some errors and removed the /v3 as specified in this issue report [#1218](https://github.com/containous/traefik/issues/1218). Now he is trying for some reason to connect to /v2-beta

```
################################################################
# Rancher Provider
################################################################

[rancher]

domain = "rancher.localhost"

watch = true

refreshSeconds = 15


exposedByDefault = true



[rancher.api]

endpoint = "https://rancher-hip.cs.upb.de"

accessKey = "xxxxxxx"

secretKey = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

```
### What did you expect to see?

Traefik connecting to rancher and be able to see traefik dashboard

### What did you see instead?

```
ERRO[2019-03-19T20:07:11Z] Provider connection error Bad response statusCode [404]. Status [404 Not Found]. Body: [404 page not found
] from [https://rancher-hip.cs.upb.de/v2-beta], retrying in 5.392911182s
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

Version:      v1.7.9
Codename:     maroilles
Go version:   go1.11.5
Built:        2019-02-11_11:36:32AM
OS/Arch:      linux/amd64

```
ERRO[2019-03-19T20:07:11Z] Provider connection error Bad response statusCode [404]. Status [404 Not Found]. Body: [404 page not found
] from [https://rancher-hip.cs.upb.de/v2-beta], retrying in 5.392911182s
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# (paste your configuration here)
```

**Comment by SantoDE** [comment]
traefik does not work with the rancher provider in rancher v2. In that case, please use the kubernetes provider

**Comment by tonnenpinguin** [comment]
Just stumbled upon the same issue. Any chance we could add a note to the docs letting people know that rancher v2 isn't actually supported? :)

**Comment by ldez** [comment]
https://github.com/containous/traefik/pull/4999 :wink:
