### ISSUE TITLE
ReplacePathRegex seems not to work in v2.0.0-alpha2

### ISSUE THREAD

**Issue by ThomasSchoenbeck** [containous/traefik#4648]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

* switched from traefik 1.7.9 to traefik v2.0.0-alpha2 without changing the configuration
* test system is self-build alpine docker image running prometheus

### What did you expect to see?
```shell
~ $ curl localhost:40700
<a href="/graph">Found</a>.
```

### What did you see instead?
```shell
~ $ curl localhost:40700
404 page not found
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```shell
~ $ traefik version
Version:      2.0.0-alpha2
Codename:     faisselle
Go version:   go1.12.1
Built:        2019-03-19T18:44:59Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Platform: alpine 3.9

```toml

defaultEntryPoints = ["http"]

[entryPoints]
    [entryPoints.http]
    address = ":40700"
    compress = true

  [backends]
        
    [backends.backend1]
      [backends.backend1.servers.1]
      url = "http://127.0.0.1:9090"
      weight = 1


  [frontends]

    [frontends.frontend1]
      entryPoints = ["http"]
      backend = "backend1"

    [frontends.frontend1.routes]
      [frontends.frontend1.routes.route0]
        rule = "ReplacePathRegex:^/(.*) /$1"
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```shell
~ $ traefik --configFile=/etc/traefik/traefik.toml &
~ $ ERRO[2019-03-21T16:06:25Z]
You haven't specify the sendAnonymousUsage option, it will be enable by default.
ERRO[2019-03-21T16:06:33Z] Error while Peeking first byte: EOF
ps aux
PID   USER     TIME  COMMAND
    1 nobody    0:00 /sbin/tini -- /usr/local/bin/start_processes.sh
    9 nobody    0:00 {start_processes} /bin/sh /usr/local/bin/start_processes.s
   14 nobody    0:04 /opt/prometheus/prometheus --config.file=/etc/prometheus/p
   54 nobody    0:00 /bin/sh
  126 nobody    0:00 sleep 60
  147 nobody    0:01 traefik --configFile=/etc/traefik/traefik.toml
  165 nobody    0:00 ps aux
~ $ curl localhost:ERRO[2019-03-21T16:06:43Z] Error while Peeking first byte: EOF
~ $ curl localhost:40700
404 page not found
~ $ ERRO[2019-03-21T16:06:53Z] Error while Peeking first byte: EOF
```

**Comment by ldez** [comment]
Hello, the v1 configuration is not compatible with Traefik v2.

You can find the new configuration inside our documentation https://docs.traefik.io/v2.0

Thank you for your interest, do not hesitate to come on Slack to tell us about the v2.

**Comment by ThomasSchoenbeck** [comment]
I probably should have checked the docs first. Only came across the release page in Github and thought, since the release notes do not mention anything i should be good to go.

Thank you for the answer.
