### ISSUE TITLE
File frontend > Marathon Backend

### ISSUE THREAD

**Issue by rogeriollacerda** [containous/traefik#465]
Hi,

We are using Traefik with mesos/marathon application backend. When we try to set a file type frontend using a marathon application backend, we receive an error because during traefik startup, the file frontend is loaded before traefik get marathon events. The log files print that the backend does not exist yet. There is some config about it? Tks

ps.: File frontend is necessary to set a specific host header value.

**Comment by emilevauge** [comment]
@rogeriollacerda Could you use the label `traefik.frontend.rule=Host:your.domain.com` in your marathon app http://docs.traefik.io/toml/#marathon-backend instead ?

**Comment by rogeriollacerda** [comment]
@emilevauge thanks again. 

Those parameters, I must use in Traefik container? Will It set same frontend rule for all of marathon application?

**Comment by emilevauge** [comment]
Here is an example json marathon file using labels: https://github.com/containous/traefik/blob/master/examples/whoami.json

The idea is to set one rule by application.

These labels override the default behavior which generates a sub-domain using the rule: `Host:{application Name}.{domain}`.

**Comment by rogeriollacerda** [comment]
@emilevauge tks

Just one more question about:

Can I set more than one host on the same rule?

**Comment by emilevauge** [comment]
Yep: http://docs.traefik.io/basics/#frontends
```
Host:test.traefik.io,www.traefik.io
```
