### ISSUE TITLE
Incomprehensible warning

### ISSUE THREAD

**Issue by andsens** [containous/traefik#4650]
Traefik v1.7.9

Got the log message
> Into EntryPoint http, try to add certificate for domains which already have this certificate ([...]). The new certificate will not be append to the EntryPoint.

I hope you will be able to join me in a collective "wat".  
I'm not trying to ridicule anybodies proficiency at english, but this message is super confusing and could use a rewrite. I understand what it is saying, but only by looking at the code itself: https://github.com/containous/traefik/blob/f1b085fa364f3d3184bccd294974db408e77cbf3/pkg/tls/certificate.go#L194-L199

**Comment by traefiker** [comment]
Closed by #4765.
