### ISSUE TITLE
CLI help default value wrong sometimes

### ISSUE THREAD

**Issue by SantoDE** [containous/traefik#4653]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

traefik --help

### What did you expect to see?

Correct default values

### What did you see instead?

providers.file is shown with a default value of true, but in fact, it's false

### Output of `traefik version`: (_What version of Traefik are you using?_)

At least v2. Not sure about v1

**Comment by traefiker** [comment]
Closed by #4935.
