### ISSUE TITLE
failed to download stable/traefik

### ISSUE THREAD

**Issue by beide** [containous/traefik#4668]
### Do you want to request a *feature* or report a *bug*?

Bug

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
(paste your output here)
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# (paste your configuration here)
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
(paste your output here)
```

**Comment by beide** [comment]
I am getting this error Error: failed to download "stable/traefik" when run 
helm install stable/traefik

**Comment by geraldcroes** [comment]
Hi and thank you for reporting the issue!

Unfortunately, this is not the correct place to report a problem with the helm chart. 

You create an issue [here](https://github.com/helm/charts/issues) instead.
