### ISSUE TITLE
proxy connect aborted

### ISSUE THREAD

**Issue by brusand** [containous/traefik#4669]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

i want to access to the traefik dashboard via https
on my desk 
1/ `ssh -L 4443:192.168.10.69:443 k8s-soft-node1`
2/  `https_proxy=http://127.0.0.1:5443 curl -vvv - https://traefik-ui.traefik.io:443`

### What did you expect to see?
the traefik dashboard realm page

### What did you see instead?
```
* Rebuilt URL to: https://traefik-ui.traefik.io:443/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 5443 (#0)
* Establish HTTP proxy tunnel to traefik-ui.traefik.io:443
> CONNECT traefik-ui.traefik.io:443 HTTP/1.1
> Host: traefik-ui.traefik.io:443
> User-Agent: curl/7.54.0
> Proxy-Connection: Keep-Alive
>
* Proxy CONNECT aborted
* Connection #0 to host 127.0.0.1 left intact
curl: (56) Proxy CONNECT aborted
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
the latest traefik version
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
on kubernetes / flannel on openstack
```yml
# (paste your configuration here)
data:
  traefik.toml: |
    defaultEntryPoints = ["http","https"]
    [entryPoints]
      [entryPoints.http]
        address = ":80"
      [entryPoints.https]
        address = ":443"
        [entryPoints.https.tls]
          [[entryPoints.https.tls.certificates]]
              CertFile = "/ssl/tls.crt"
              KeyFile = "/ssl/tls.key"
      [entryPoints.traefik]
        address = ":8080"
        [entryPoints.traefik.auth.basic]
           users = ["admin:\$apr1\$5hQ3HP8c\$XU1VWlD3ns3BUqmAqP1FX1"]
    [kubernetes.ingressEndpoint]
        publishedService = "traefik/traefik"
    [ping]
        entryPoint = "http"
    [api]
        entryPoint = "traefik"

<!--
Add more configuration information here.
-->


### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
(paste your output here)
```

**Comment by mmatur** [comment]
Hi @brusand,

Thanks for your interest in the project.

I can see that you create SSH tunnel on port `4443` and in your second command you are using port 5443.

I will close your issue because the question is answered.
