### ISSUE TITLE
Add a provider for ECS in Traefik v2

### ISSUE THREAD

**Issue by jbdoumenjou** [containous/traefik#4674]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Traefik v1 supports dynamic config generation for and from a ECS cluster, i.e. it has an ECS provider.

Now that the main changes for v2 are out, we can re-add previously supported providers, such as the one for ECS.

The existing providers, such as docker, as well as the code for the ECS provider in v1.7, can be used for inspiration.

**Comment by m13t** [comment]
It’s a real shame that ECS Support was dropped as part of V2, but some were brought forward. We have quite a lot of V1 instances running which we were looking forward to bringing up to V2.

**Comment by SantoDE** [comment]
It's not really "dropped", just not done yet. If you like, take a shot ;)

**Comment by m13t** [comment]
Okay that’s good to know. I thought given v2 is now released and it didn’t make the cut, it must have been dropped.

**Comment by JavierPandu** [comment]
How about using a "resolver" like in nginx?

**Comment by ysz** [comment]
@SantoDE can I take a shot? 🎄

**Comment by ldez** [comment]
@ysz Traefik is an open source project, so feel free to work on this.

**Comment by andrewelkins** [comment]
Has anyone made progress on creating support for ECS in v2?

**Comment by a6patch** [comment]
> It's not really "dropped", just not done yet. If you like, take a shot ;)

Isn't this sort of a lie?  ECS is supported in the 2.x EE version, which means it HAS been done already.  While I think that adding features to an open source project and bundling them as paid premium tier is perfectly ok, REMOVING a feature that already existed as you go from version 1.7 to 2.x is a violation of the spirit of open source and the people that freely contributed to getting the feature into V1.7.  

Will ECS ever be added to the Community edition of 2.x?

**Comment by SantoDE** [comment]
not sure what you talking about @a6patch or where you get that information from. EE 2.X *does NOT* have ECS as a provider. If its listed somewhere, we'll need to correct it as its untrue.

For ECS in Traefik 2.X, there is the PR #6749 which I'm currently testing on ECS :-)

**Comment by a6patch** [comment]
Sorry if I misunderstood.  After waiting a number of months after 2.0 for ECS to get added, I had a conversation with a salesperson that very specifically said that that was an EE feature and wasn't available in the non-EE 2.x Traefik. She must have been mistaken.  

I did check your site and the current home page for Traefik 2.x clearly say "Services auto-discovery (Kubernetes, Docker Swarm, Red Hat OpenShift, Rancher, **Amazon ECS**, Key-Value Stores)".....

**Comment by kevingimbel** [comment]
@SantoDE let me know if you need another pair of eyes for testing! I'm very interested in getting 2.x on ECS!

**Comment by kevingimbel** [comment]
@SantoDE Might be worth adding: I can test against our internal test system where we have a bunch of services running, so we could test the PR against a "real" system (if I can get a docker image from the PR)

**Comment by alekitto** [comment]
@kevingimbel If you need a docker image for testing I've created an alpine based image a month ago and pushed it on docker hub (https://hub.docker.com/r/alekitto/traefik-alpine).

**Comment by kevingimbel** [comment]
@alekitto Neat! I'll see when I can give this a go! :)

**Comment by SantoDE** [comment]
Can you share your results then @kevingimbel? Probably, tests from a real system would be more "worth / important" already :-) Maybe we can also talk on the Traefik slack ;-)

**Comment by kevingimbel** [comment]
@SantoDE We can talk on the Traefik Slack, I'm there as "Kevin Gimbel" - just hit me up. I'll need to see when I can try it, maybe tonight or tomorrow!

**Comment by aravind-jl** [comment]
Found a vulnerability on 1.7 with ECR scan and finally  upgraded to 2x, and now I am here! fingers crossed!

**Comment by SantoDE** [comment]
@aravind-jl WDYM? I can't really follow, but I'd like to.

**Comment by jbdoumenjou** [comment]
Closed by #6749

**Comment by anilmaurya** [comment]
I used Traefik v2 on ECS, published blog post about it https://dev.to/anilmaurya/traefik-v2-with-lets-encrypt-on-amazon-s-elastic-container-service-ecs-1h4h
