### ISSUE TITLE
Add a provider for ConsulCatalog in Traefik v2

### ISSUE THREAD

**Issue by jbdoumenjou** [containous/traefik#4675]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Traefik v1 supports dynamic config generation for and from a Consul Catalog service, i.e. it has a ConsulCatalog provider.

Now that the main changes for v2 are out, we can re-add previously supported providers, such as the one for ConsulCatalog.

The existing providers, as well as the code for the ConsulCatalog provider in v1.7, can be used for inspiration.

**Comment by sirkjohannsen** [comment]
really dear developers. I am looking forward to traefik 2.0 and I like that you care about K8s so much.
But, it would be awesome to support the same Configuration discovery mechanisms as version 1 does.
Especially consul is super important imho.

**Comment by robloxrob** [comment]
👍

**Comment by boostbob** [comment]
Is this feature going to be abandoned?

**Comment by TheVendiniPhil** [comment]
Hashicorp systems every are being made to feel like second class citizens, I look forward to some future release of Traefik which enables support for all things Consul.

**Comment by brpaz** [comment]
I would like to use Traefik 2 as a load balancer / ingress on a k8s cluster. I would like to use Lets encrypt so I need a distributed way to store the ACME certificates so their are available on all my nodes.  In traefik 1 you could use consul. If consul is not supported in Traefik 2 is there an alternate way?

**Comment by frederikbosch** [comment]
@brpaz See PR #5395, Consul support is close to merging in 2.0.

**Comment by ldez** [comment]
Consul Catalog is not Consul (KV).
