### ISSUE TITLE
tech debt - remove usage of github.com/satori/go.uuid package

### ISSUE THREAD

**Issue by aaslamin** [containous/traefik#4717]
### Do you want to request a _feature_ or report a _bug_?

feature / tech debt

### What did you expect to see?

Traefik is currently utilizing the https://github.com/satori/go.uuid package to generate UUIDs which has a [critical defect](https://github.com/dotmesh-io/dotmesh/issues/626) (_tl;dr UUIDs may not be random ⚠️_)  

### Proposal

- 💥 remove github.com/satori/go.uuid package & it's usages
- replace with https://github.com/pborman/uuid to generate UUIDs instead

---

If this sounds good to you, I can raise a PR 🤚

**Comment by ldez** [comment]
@aaslamin I made a PR on v2.0 branch, as v2 is really different than v1, you can do a PR on the branch v1.7.

You can use https://github.com/gofrs/uuid or https://github.com/google/uuid.
Don't forget to update github.com/Masterminds/sprig

**Comment by aaslamin** [comment]
Sounds good! Thank you @ldez, working on it now 🙌

**Comment by traefiker** [comment]
Closed by #4718.
