### ISSUE TITLE
Make it possible to use static segment backend names with the Docker provider

### ISSUE THREAD

**Issue by mback2k** [containous/traefik#4723]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I expected the Docker container/service label "traefik.{segment-name}.backend" to behave the same way as "traefik.backend". Its raw value should have been used as the backend name instead of it being prefixed with the service name.

I understand that the default is to include the service name to avoid naming conflicts due to duplicates. But wouldn't this already be achieved by including the segment name inside the backend name?

The function used for "traefik.backend" is [getDefaultBackendName](https://github.com/containous/traefik/blob/ba44619828f9be7815d00a7d58e390bf4efc59db/provider/docker/config.go#L287) which either uses just the provided value or the service name.

The function used for "traefik.{segment-name}.backend" is [getSegmentBackendName](https://github.com/containous/traefik/blob/ba44619828f9be7815d00a7d58e390bf4efc59db/provider/docker/config.go#L278) which either uses the provided value prefixed with the service name or the segment name prefixed with the service name. So the segment name is already, but only used in case no value was given.

I think the behaviour of getSegmentBackendName is not consistent and causes trouble with random container names showing up, e.g. in Prometheus metrics. I would like to see it aligned with getDefaultBackendName by using the provided value or the service name, each suffixed with the segment name instead of always including the service name.

Basically this would mean to use the segment instead of the service name with the provided value, and make the service name the default value.

Examples of label to backend name conversion **at the moment**:

* traefik.backend: "my-single-backend" --> "my-single-backend"
* traefik.backend: unset --> "my-container/service-name"
* **traefik.my-segment.backend**: "my-single-backend" --> "my-container/service-name-my-single-backend"
* traefik.my-segment.backend: unset --> "my-container/service-name-my-segment"

Examples of label to backend name conversion **with this feature request implemented**:

* traefik.backend: "my-single-backend" --> "my-single-backend"
* traefik.backend: unset --> "my-container/service-name"
* **traefik.my-segment.backend**: "my-single-backend" --> "my-single-backend-my-segment"
* traefik.my-segment.backend: unset --> "my-container/service-name-my-segment"

This would make it possible to have static backend names by setting the .backend label. What do you think?

At the moment I am unable to really monitor the metrics produced by traefik from my docker services with prometheus and grafana due to random metric names.

**Comment by ldez** [comment]
To understand the current behavior you need to read #3485, #3482, #3317, #3351

**Comment by mback2k** [comment]
@ldez Thanks for the hints. Actually I already came across most of these. That is why I am open for discussion on how to make it possible to have both dynamic (scalable) and constant (fixed) backend names. Both PRs I just posted still allow dynamic backend names if the corresponding .backend label is not set.

**Comment by ldez** [comment]
Note that in branch v1.7, we only accept bug-fixes.

**Comment by mback2k** [comment]
That is very unfortunate for me. Anything I can do to have a solution before / without migrating to v2?

**Comment by ldez** [comment]
You can try to use custom template:

https://docs.traefik.io/configuration/backends/docker/#docker

```
[docker]
templateVersion = 2
filename = "my_docker.tmpl"
```

https://github.com/containous/traefik/blob/v1.7/templates/docker.tmpl

**Comment by mback2k** [comment]
Sorry, but I don't understand how I can influence the internal backend name via the template. To me it looks like [$backendName](https://github.com/containous/traefik/blob/de6e365b744c56db730e504bccb8633bb99cde21/templates/docker.tmpl#L3) is already setup outside of this template. And in another place it for some reason uses [getBackendName](https://github.com/containous/traefik/blob/de6e365b744c56db730e504bccb8633bb99cde21/templates/docker.tmpl#L75) instead. Could you please give me another pointer in the right direction? Thanks in advance!

**Comment by mback2k** [comment]
@dduportal thanks for considering it for v2, please see #4731 and #4732 for possible implementation variants.

**Comment by ldez** [comment]
@mback2k sorry but @dduportal made a mistake: in the v2 the segments don't exist at all.

**Comment by ldez** [comment]
In the template, you can use [sprig function](http://masterminds.github.io/sprig/) and basic [Golang template operations](https://golang.org/pkg/text/template/)

https://github.com/containous/traefik/blob/de6e365b744c56db730e504bccb8633bb99cde21/templates/docker.tmpl#L3

` $servers` is a `dockerData`:

https://github.com/containous/traefik/blob/de6e365b744c56db730e504bccb8633bb99cde21/provider/docker/docker.go#L56-L65

`dockerData` contains all information to build a custom name.

**Comment by mback2k** [comment]
@ldez thanks a lot, again. I managed to implement #4731 via the following template snippets:

**Backends:**

```
[backends]
{{range $backendName, $servers := .Servers}}
  {{ $backend := index $servers 0 }}

  {{ $composeService := getLabelValue $backend.Labels "com.docker.compose.service" "" }}
  {{ $composeProject := getLabelValue $backend.Labels "com.docker.compose.project" "" }}
  {{ $serviceName := $backend.ServiceName }}
  {{if and $composeService $composeProject }}
  {{ $serviceName = print $composeService "_" $composeProject }}
  {{end}}
  {{ $backendName := getLabelValue $backend.SegmentLabels "traefik.backend" $serviceName }}
  {{ $segmentName := $backend.SegmentName }}
  {{if $segmentName }}
  {{ $backendName = print $backendName "-" $segmentName }}
  {{end}}
  {{ $backendName = $backendName | replace "." "-" }}
...
```

**Frontends:**

```
[frontends]
{{range $frontendName, $containers := .Frontends }}
  {{ $container := index $containers 0 }}

  {{ $composeService := getLabelValue $container.Labels "com.docker.compose.service" "" }}
  {{ $composeProject := getLabelValue $container.Labels "com.docker.compose.project" "" }}
  {{ $serviceName := $container.ServiceName }}
  {{if and $composeService $composeProject }}
  {{ $serviceName = print $composeService "_" $composeProject }}
  {{end}}
  {{ $backendName := getLabelValue $container.SegmentLabels "traefik.backend" $serviceName }}
  {{ $segmentName := $container.SegmentName }}
  {{if $segmentName }}
  {{ $backendName = print $backendName "-" $segmentName }}
  {{end}}
  {{ $backendName = $backendName | replace "." "-" }}
...
```

**Comment by mback2k** [comment]
Slightly updated version due to the fact that the backend label value must already be unique and it is therefore not required to always append the segment name.

**Backends:**

```
[backends]
{{range $backendName, $servers := .Servers}}
  {{ $backend := index $servers 0 }}

  {{ $composeService := getLabelValue $backend.Labels "com.docker.compose.service" "" }}
  {{ $composeProject := getLabelValue $backend.Labels "com.docker.compose.project" "" }}
  {{ $serviceName := $backend.ServiceName }}
  {{if and $composeService $composeProject }}
  {{ $serviceName = print $composeService "_" $composeProject }}
  {{end}}
  {{if $backend.SegmentName }}
  {{ $serviceName = print $serviceName "-" $backend.SegmentName }}
  {{end}}
  {{ $backendName := getLabelValue $backend.SegmentLabels "traefik.backend" $serviceName }}
  {{ $backendName = $backendName | replace "." "-" }}
...
```

**Frontends:**

```
[frontends]
{{range $frontendName, $containers := .Frontends }}
  {{ $container := index $containers 0 }}

  {{ $composeService := getLabelValue $container.Labels "com.docker.compose.service" "" }}
  {{ $composeProject := getLabelValue $container.Labels "com.docker.compose.project" "" }}
  {{ $serviceName := $container.ServiceName }}
  {{if and $composeService $composeProject }}
  {{ $serviceName = print $composeService "_" $composeProject }}
  {{end}}
  {{if $container.SegmentName }}
  {{ $serviceName = print $serviceName "-" $container.SegmentName }}
  {{end}}
  {{ $backendName := getLabelValue $container.SegmentLabels "traefik.backend" $serviceName }}
  {{ $backendName = $backendName | replace "." "-" }}

  [frontends."frontend-{{ $frontendName }}"]
    backend = "backend-{{ $backendName }}"
...
```

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

Thanks again for your interest in Traefik!

I'm glad to close the issue because I think that the question has been answered (Yes, I'm quite an advanced AI :smile:)

Join our [Slack workspace](https://slack.traefik.io/) for more [community #support](https://traefik.slack.com/messages/C0CDT22PJ/).

**Comment by mback2k** [comment]
@ldez Is @traefiker right in this case? Or is this something that still needs to be considered for v2 even though segments are no longer in use?

**Comment by ldez** [comment]
yes Traefiker in right: v2 has a completely different approach, the label system has been rewritten.
