### ISSUE TITLE
Add documentation for prometheus metrics

### ISSUE THREAD

**Issue by xinau** [containous/traefik#4725]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

It seems like the implementation for [prometheus](https://github.com/containous/traefik/blob/v2.0/pkg/metrics/prometheus.go) is done, but I can't find any documentation on this topic in traefik version 2.0.0-alpha3.

I think it would be a good idea to add some :upside_down_face: 

Thanks.

**Comment by ldez** [comment]
For now Metrics are not implemented, we will work on it soon.

**Comment by dduportal** [comment]
Hi @xinau , thank you for your interest.

Given the work is currently in progress on the v2.0 line, we'll close this issue.

"Wait & see" as the adage says :)
