### ISSUE TITLE
Empty TCP connections cause error to be logged

### ISSUE THREAD

**Issue by dtomcej** [containous/traefik#4726]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Accessing Traefik v2 with an empty TCP connection results in an error being logged

### What did you expect to see?

Potentially a record in an access log, but nothing in the traefik log.

### What did you see instead?

```
time="2019-03-21T18:28:46Z" level=error msg="Error while Peeking first byte: EOF"
time="2019-03-21T18:28:48Z" level=error msg="Error while Peeking first byte: EOF"
time="2019-03-21T18:28:56Z" level=error msg="Error while Peeking first byte: EOF"
time="2019-03-21T18:28:58Z" level=error msg="Error while Peeking first byte: EOF"
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

v2 Alpha3

The solution is if there is no first byte, ignore the connection, and don't log an error, since there is going to be no routing on an empty connection.

**Comment by traefiker** [comment]
Closed by #4733.
