### ISSUE TITLE
Hooks for execution before or after requesting TLS cerfiticates

### ISSUE THREAD

**Issue by vsund** [containous/traefik#4727]
### Do you want to request a *feature* or report a *bug*?
Feature

### What did you expect to see?
I'm using Traefik for requesting certificates and would like to execute things before (e.g. starting [`acme-dns`](https://github.com/joohoi/acme-dns)) and after (e.g. stopping `acme-dns`, restarting various services or extracting the certificates).

While researching this, I found some solutions which watch the `acme.json` file and execute [`dumpcerts.sh`](https://github.com/containous/traefik/blob/master/contrib/scripts/dumpcerts.sh). This way I could execute whatever I need to do afterwards, but I didn't find any way for doing something _before_.

I think this would mainly need support in [`lego`](https://github.com/go-acme/lego) ([which has a renew hook since some days](https://github.com/go-acme/lego/pull/845)). Though I didn't find a way to use these options which `lego` provides. Does this need to be re-exposed by Traefik to be usable in the configuration? If so, I'd like to request this :)

---
Additionally I couldn't find any other requests or needs of other people who'd need to do this. Which leads me to think that I'm maybe missing something?

**Comment by dduportal** [comment]
Hi @vsund , thanks for your interest in the project.

We understand your feature request, however it looks like it's out of the scope of Traefik.
Traefik is aimed at being a reverse proxy, and not really a task orchestrator for Certificates.

We should recommend to you to use a worfklow engine outside Traefik, which delivers the certificates into Traefik, it would separate concerns.

Feel free to join our support channel on Slack if you have more questions.
