### ISSUE TITLE
Ability to display average response time for the last n minutes

### ISSUE THREAD

**Issue by timoschwarzer** [containous/traefik#4736]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I'm missing the ability to view the average response time for a limited time window only in træfik's dashboard. Currently, when one request takes unusally long, the whole average response time is skewed until I restart træfik. It would be great if we could choose to display the average response time for the last 1 minute, hour or day to see if e.g. fixing a bug resulted in lower response times.

**Comment by juliens** [comment]
Hi,

Thanks for your interest in the Traefik.

We want to keep the statistics on the Traefik webui simple. If you want more information about your requests etc... You should use the metric system to have those information.
https://docs.traefik.io/configuration/metrics/
