### ISSUE TITLE
High cpu load when letsencrypt is set to ondemand

### ISSUE THREAD

**Issue by aacebedo** [containous/traefik#474]
traefik consumes > 4.0 load when ondemand is set to true on RPI

**Comment by emilevauge** [comment]
@aacebedo could you be more specific and give more details?

**Comment by aacebedo** [comment]
I am running traefik on a rpi with 5 docker containers. 
Each of them are have one specific subdomain. 
I ran traefik with docker watch flag to true and letsencrypt ondemand mode to true. 
When running top, traefik seems to consume 400% cpu. 
Requests are not served as they reach the http connection timeout.

**Comment by aacebedo** [comment]
Traefik is also running in a container

**Comment by emilevauge** [comment]
Does High load occur only during first request (`OnDemand`) or all the time?

**Comment by aacebedo** [comment]
All time. 
I can investigate more tonight playing with the ondemand flag if it can help you.

**Comment by emilevauge** [comment]
@aacebedo any news on this ?

**Comment by aacebedo** [comment]
I close it, the high cpu demand is caused by ssh key generation when starting traefik.
sorry for trouble
