### ISSUE TITLE
Documentation: Incorrect link "edit page"

### ISSUE THREAD

**Issue by powerman** [containous/traefik#4742]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Click on "edit page" icon at https://docs.traefik.io/v2.0/providers/docker/

### What did you expect to see?

https://github.com/containous/traefik/edit/v2.0/docs/content/providers/docker.md

### What did you see instead?

https://github.com/containous/traefik/edit/v2.0/content/providers/docker.md (404)

**Comment by traefiker** [comment]
Closed by #4743.

**Comment by traefiker** [comment]
Closed by #4744.
