### ISSUE TITLE
dumpcerts.sh compatibility

### ISSUE THREAD

**Issue by mlan** [containous/traefik#4777]
The dumpcerts.sh script uses OpenSSL to verify that the private key is valid. 
In doing so, the key is piped to the command openssl, without limiting the line lengths. 
This appears not to work for all implementations of SSL.

To exemplify:
Within a Docker image based on alpine:3.8 the key line length need to be less than 80 characters.

```
# cat test.pem | fold -w 79 | openssl rsa -inform pem -out key.pem
writing RSA key
```

```
# cat test.pem | fold -w 80 | openssl rsa -inform pem -out key.pem
unable to load Private Key
140046610254796:error:09FFF064:PEM routines:CRYPTO_internal:bad base64 decode:pem/pem_lib.c:800:
```

This limitation does not appear on other systems. The reason for this compatibility issue might be that 
Alpine Linux use an openssl implementation based on LibreSSL:

```
# openssl version
LibreSSL 2.7.4
```

**Comment by ldez** [comment]
Hello,

We want to remove this script from the Traefik repository.
You can find more explanation and alternatives here: #4783
