### ISSUE TITLE
Support fallback servers

### ISSUE THREAD

**Issue by mason-mcglothlin** [containous/traefik#4782]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

When there are no available servers on a backend (either because none are currently configured or because all of the configured servers have failed their health checks) then Traefik should support falling back to a different set of servers. In the file configuration, the syntax might look something like this:

```toml
[backends.srweb.fallbackservers]
      [backends.srweb.fallbackservers.server1]
        url = 'https://maintenancepage.localhost'
```

This would open up several possibilities:

- Automatically displaying a maintenance page when the main servers are down (fail health checks)
- Allowing a site to be manually taken down for maintenance by unregistering all the normal servers, and automatically having a maintenance page appear
- falling back to servers that offered a degraded but still functional service, perhaps by failing over to a disaster recovery datacenter

Barracuda load balancers have this feature, where it's called a [Last Resort Server](https://campus.barracuda.com/product/loadbalanceradc/knowledgebase/50160000000HB7wAAG/How+should+I+configure+the+Last+Resort+Server+on+my+Barracuda+Load+Balancer/). Here is how they describe it:

> The Barracuda Load Balancer allows you to specify a "Last Resort Server," which is the server to which all traffic for a particular Service is routed in the event that all Real Servers associated with that service are not available. This Last Resort Server can be located on a different network, or even across the internet, so long as the Barracuda's WAN port has a route to that server. If all Real Servers for a particular Service are unavailable, the Barracuda Load Balancer will route all traffic bound for that Service's VIP to the Last Resort Server specified using a simple NAT. The Last Resort Server does not need to be configured as a Real Server under the Service, and the Barracuda Load Balancer will not perform any health checks on the Last Resort Server.

**Comment by ldez** [comment]
Hello,

To do what you want you have to play with [priorities](https://docs.traefik.io/basics/#priorities): you have to define 2 frontends with the same [rule](https://docs.traefik.io/basics/#frontends) and set a low priority on your "fallback" server.
 

FYI: The v1 of Traefik is in maintenance mode, only bug fixes can be done.

**Comment by mason-mcglothlin** [comment]
@ldez 
> To do what you want you have to play with [priorities](https://docs.traefik.io/basics/#priorities): you have to define 2 frontends with the same [rule](https://docs.traefik.io/basics/#frontends) and set a low priority on your "fallback" server.

That looks like it would always route traffic to the front end with the highest priority. That doesn't appear that it would start routing to a lower priority front end if all the backend servers fail their healthchecks. Or am I missing something?

**Comment by ldez** [comment]
You have to use a "catch-all" rule if you want to create a global "fallback".

You can also play with [custom error pages](https://docs.traefik.io/configuration/commons/#custom-error-pages).

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Slack workspace](https://traefik.herokuapp.com/) for more [community #support](https://traefik.slack.com/messages/C0CDT22PJ/).
