### ISSUE TITLE
Basic authentication with strong password encryption causes high latency

### ISSUE THREAD

**Issue by micw** [containous/traefik#4791]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

* Run traefik ingress
* Expose some service without basic auth
* Expose the same service with basic auth and weak password encryption (e.g. bcrypt, complexity 5)
* Expose the same service with basic auth and strong password encryption (e.g. bcrypt, complexity 11)

### What did you expect to see?

* roughly the same response time with/without basic auth

### What did you see instead?

* response without basic auth: ~20ms
* response with basic auth (bcrypt 5): ~25ms
* response with basic auth (bcrypt 11): ~200ms

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
1.7.10
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```
  - args:
    - --logLevel=INFO
    - --api
    - --kubernetes
    - --kubernetes.ingressEndpoint.ip=127.0.0.1
    - --insecureskipverify
    - --entryPoints=Name:http Address::80 Redirect.EntryPoint:https
    - --entryPoints=Name:https Address::443 TLS Compress:true
    - --defaultentrypoints=http,https
    - --metrics.prometheus
```

**Comment by micw** [comment]
Update: I identified the root cause and updated the issue title and description

**Comment by jbdoumenjou** [comment]
Hi @micw,

Thank you for your interest in Traefik.

Nothing unexpected here, the complexity of the encryption increases the response time.

If you have any other questions or concerns, feel free to visit our [slack channel](https://slack.traefik.io).
