### ISSUE TITLE
loadConfig modifies configuration causing same config check to fail

### ISSUE THREAD

**Issue by keis** [containous/traefik#480]
Moving my comment from #478 to make it easier to track.

In same config check the "old" config also have `loadBalancer` blocks in the backend config where the new from the provider does not. This from line 444 in server.go

I think the fix to this is to never modify the config in loadConfig but I'm not really sure where should go instead.

```
        "backend-eremetic": {
            "servers": {
                "eremetic--10-4-72-161--8182--monitor--api--monitor--6": {
                    "url": "http://10.4.72.161:8182",
                    "weight": 0
                }
            },
            "loadBalancer": {
                "method": "wrr"
            }
        },
```

```
        "backend-eremetic": {
            "servers": {
                "eremetic--10-4-72-161--8182--monitor--api--monitor--6": {
                    "url": "http://10.4.72.161:8182",
                    "weight": 0
                }
            }
        },
```

**Comment by emilevauge** [comment]
@keis Nice catch! I will fix this for the 1.0.

**Comment by emilevauge** [comment]
@keis you can test it using `containous/traefik:pr-491` ;)

**Comment by keis** [comment]
Tried the current master and it all works great now. I see the messages about defaulting the load balancer method followed by "Skipping same configuration for provider consul_catalog".  :+1:
