### ISSUE TITLE
Traefik and ddos protection

### ISSUE THREAD

**Issue by udanpe** [containous/traefik#4803]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I used nginx with rate limit and fail2ban. When rate limit detected fail2ban blocked ip. Can you add some feature for rate limit with ban for ip for some time? traefik.frontend.rateLimit.ban=300s

**Comment by mpl** [comment]
Hi,
If you want to achieve rate limiting with fail2ban, we think you should probably apply it on the access logs. They can be enabled in Traefik configuration: https://docs.traefik.io/v2.0/observability/access-logs/
WDYT?

**Comment by udanpe** [comment]
@mpl I know about log, i use it with goaccess. And i hope you will add different logs file for different domains traefik.frontend. accessLogsFile=filename.log. But about ratelimit i think you can add ban value too. (period, burst, ban better then average)

**Comment by gregorybrzeski** [comment]
@udanpe wouldn't middleware in v2 be the place to put such logic ? I am sure a PR with such middleware would be considered.

**Comment by cguentherTUChemnitz** [comment]
@udanpe Are you looking for the rate-limit feature? https://docs.traefik.io/v2.0/middlewares/ratelimit/
