### ISSUE TITLE
Multiple service definition not working 

### ISSUE THREAD

**Issue by riadmaouchi** [containous/traefik#4807]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [ x] No

### What did you do?
Creating multiple service for the same container
...
labels:
      - "traefik.http.routers.service1.rule=host(`service1.docker.localhost`)"
      - "traefik.http.services.service1.loadbalancer.server.port=8381"
      - "traefik.http.routers.service2.rule=host(`service2.docker.localhost`)"
      - "traefik.http.services.service2.loadbalancer.server.port=8380"
   

### What did you expect to see?
I run docker compose
I m expecting to see multiple service for a single docker container

### What did you see instead?
An error message: 
"Could not define the service name for the router: too many services"

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
traefik:2.0.0-alpha4
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# command:
      - "--api"
      - "--providers.docker"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
traefik    | time="2019-04-23T23:55:53Z" level=error msg="Could not define the service name for the router: too many services"
```

**Comment by riadmaouchi** [comment]
After checking the code,  I found that adding those label make it works.

 - "traefik.http.routers.pricing1.service=pricing1"
 - "traefik.http.routers.pricing2.service=pricing2"

**Comment by ldez** [comment]
Hello, you have to define the service name:

```
labels:
- "traefik.http.routers.router1.rule=host(service1.docker.localhost)"
- "traefik.http.routers.router1.service=service1"
- "traefik.http.services.service1.loadbalancer.server.port=8381"
- "traefik.http.routers.router2.rule=host(service2.docker.localhost)"
- "traefik.http.routers.router2.service=service2"
- "traefik.http.services.service2.loadbalancer.server.port=8380"
```

**Comment by nmengin** [comment]
I close this issue which seems to be solved.
