### ISSUE TITLE
[2.0] add context to middleware error log entry for docker provider

### ISSUE THREAD

**Issue by andig** [containous/traefik#4810]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

Run traefik with docker:

    docker run -v /var/run/docker.sock:/var/run/docker.sock traefik:v2.0  --api --providers.docker --global.sendanonymoususage

### What did you see instead?

Log error:

    time="2019-04-24T09:44:02Z" level=error msg="error during instanciation of docker.api: cannot create middleware: multi-types middleware not supported, consider declaring two different pieces of middleware instead" entryPointName=traefik routerName=docker.api

The error itself is certainly ok- configuration mistake. However, without enabling debug logs, the error message does not give any indication which of the docker services is the actual problem. It would be nice to add docker service name or similar as context.

### Output of `traefik version`: (_What version of Traefik are you using?_)
    ❯ docker run -v /var/run/docker.sock:/var/run/docker.sock traefik:v2.0  version
    Version:      2.0.0-alpha4
    Codename:     faisselle
    Go version:   go1.12.4
    Built:        2019-04-17T11:38:21Z
    OS/Arch:      linux/amd64

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

    ❯ docker run -v /var/run/docker.sock:/var/run/docker.sock traefik:v2.0 --api --providers.docker --global.sendanonymoususage --log.level=debug
    time="2019-04-24T09:44:02Z" level=info msg="Traefik version 2.0.0-alpha4 built on 2019-04-17T11:38:21Z"
    time="2019-04-24T09:44:02Z" level=debug msg="Static configuration loaded {\"Global\":{\"Debug\":false,\"CheckNewVersion\":true,\"SendAnonymousUsage\":false},\"ServersTransport\":{\"InsecureSkipVerify\":false,\"RootCAs\":null,\"MaxIdleConnsPerHost\":200,\"ForwardingTimeouts\":null},\"EntryPoints\":{\"http\":{\"Address\":\":80\",\"Transport\":{\"LifeCycle\":{\"RequestAcceptGraceTimeout\":0,\"GraceTimeOut\":10000000000},\"RespondingTimeouts\":{\"ReadTimeout\":0,\"WriteTimeout\":0,\"IdleTimeout\":180000000000}},\"ProxyProtocol\":null,\"ForwardedHeaders\":{\"Insecure\":false,\"TrustedIPs\":null}},\"traefik\":{\"Address\":\":8080\",\"Transport\":{\"LifeCycle\":{\"RequestAcceptGraceTimeout\":0,\"GraceTimeOut\":10000000000},\"RespondingTimeouts\":{\"ReadTimeout\":0,\"WriteTimeout\":0,\"IdleTimeout\":180000000000}},\"ProxyProtocol\":null,\"ForwardedHeaders\":{\"Insecure\":false,\"TrustedIPs\":null}}},\"Providers\":{\"ProvidersThrottleDuration\":2000000000,\"Docker\":{\"Constraints\":null,\"Watch\":true,\"Endpoint\":\"unix:///var/run/docker.sock\",\"DefaultRule\":\"Host(`{{ normalize .Name }}`)\",\"TLS\":null,\"ExposedByDefault\":true,\"UseBindPortIP\":false,\"SwarmMode\":false,\"Network\":\"\",\"SwarmModeRefreshSeconds\":15},\"File\":null,\"Marathon\":null,\"Kubernetes\":null,\"KubernetesCRD\":null,\"Rest\":null,\"Rancher\":null},\"API\":{\"EntryPoint\":\"traefik\",\"Dashboard\":true,\"Statistics\":null,\"Middlewares\":null},\"Metrics\":null,\"Ping\":null,\"Log\":{\"Level\":\"debug\",\"format\":\"common\"},\"AccessLog\":null,\"Tracing\":null,\"HostResolver\":null,\"ACME\":null}"
    time="2019-04-24T09:44:02Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://docs.traefik.io/basics/#collected-data\n"
    time="2019-04-24T09:44:02Z" level=debug msg="No default certificate, generate one"
    time="2019-04-24T09:44:02Z" level=info msg="Starting provider aggregator.ProviderAggregator {}"
    time="2019-04-24T09:44:02Z" level=debug msg="Start TCP Server" entryPointName=http
    time="2019-04-24T09:44:02Z" level=debug msg="Start TCP Server" entryPointName=traefik
    time="2019-04-24T09:44:02Z" level=info msg="Starting provider *docker.Provider {\"Constraints\":null,\"Watch\":true,\"Endpoint\":\"unix:///var/run/docker.sock\",\"DefaultRule\":\"Host(`{{ normalize .Name }}`)\",\"TLS\":null,\"ExposedByDefault\":true,\"UseBindPortIP\":false,\"SwarmMode\":false,\"Network\":\"\",\"SwarmModeRefreshSeconds\":15}"
    time="2019-04-24T09:44:02Z" level=debug msg="Provider connection established with docker 18.09.2 (API 1.39)" providerName=docker
    time="2019-04-24T09:44:02Z" level=debug msg="Configuration received from provider docker: {\"HTTP\":{\"routers\":{\"/awesome_ganguly\":{\"entryPoints\":null,\"service\":\"/awesome_ganguly\",\"rule\":\"Host(`awesome-ganguly`)\"},\"api\":{\"entryPoints\":null,\"middlewares\":[\"api\"],\"service\":\"api\",\"rule\":\"Host(`volkszaehler.io`) \\u0026\\u0026 PathPrefix(`/api`)\"},\"apt-cacher-ng_pi-gen\":{\"entryPoints\":null,\"service\":\"apt-cacher-ng_pi-gen\",\"rule\":\"Host(`apt-cacher-ng-pi-gen`)\"},\"aux\":{\"entryPoints\":null,\"service\":\"aux\",\"rule\":\"Host(`whoami.localhost.org`) \\u0026\\u0026 PathPrefix(`/org`)\"},\"frontend\":{\"entryPoints\":null,\"service\":\"frontend\",\"rule\":\"Host(`volkszaehler.io`)\"},\"main\":{\"entryPoints\":null,\"service\":\"main\",\"rule\":\"Host(`whoami.localhost.com`)\"},\"traefik_tf\":{\"entryPoints\":null,\"service\":\"traefik_tf\",\"rule\":\"Host(`traefik-tf`)\"}},\"middlewares\":{\"api\":{\"stripPrefix\":{\"prefixes\":[\"/api\"]},\"compress\":{}}},\"services\":{\"/awesome_ganguly\":{\"loadbalancer\":{\"servers\":[{\"url\":\"http://172.17.0.2:80\",\"weight\":1}],\"method\":\"wrr\",\"passHostHeader\":true}},\"api\":{\"loadbalancer\":{\"servers\":[{\"url\":\"http://172.23.0.3:8080\",\"weight\":1}],\"method\":\"wrr\",\"passHostHeader\":true}},\"apt-cacher-ng_pi-gen\":{\"loadbalancer\":{\"servers\":[{\"url\":\"http://172.18.0.2:3142\",\"weight\":1}],\"method\":\"wrr\",\"passHostHeader\":true}},\"aux\":{\"loadbalancer\":{\"servers\":[{\"url\":\"http://172.23.0.2:80\",\"weight\":1}],\"method\":\"wrr\",\"passHostHeader\":true}},\"frontend\":{\"loadbalancer\":{\"servers\":[{\"url\":\"http://172.23.0.3:8080\",\"weight\":1}],\"method\":\"wrr\",\"passHostHeader\":true}},\"main\":{\"loadbalancer\":{\"servers\":[{\"url\":\"http://172.23.0.2:80\",\"weight\":1}],\"method\":\"wrr\",\"passHostHeader\":true}},\"traefik_tf\":{\"loadbalancer\":{\"servers\":[{\"url\":\"http://172.23.0.4:80\",\"weight\":1}],\"method\":\"wrr\",\"passHostHeader\":true}}}},\"TCP\":{},\"TLSOptions\":null,\"TLSStores\":null}" providerName=docker
    ...
    time="2019-04-24T09:44:02Z" level=debug msg="Creating middleware" serviceName=api entryPointName=http middlewareName=pipelining routerName=docker.api middlewareType=Pipelining
    time="2019-04-24T09:44:02Z" level=debug msg="Creating wrr load-balancer" serviceName=api entryPointName=http routerName=docker.api
    time="2019-04-24T09:44:02Z" level=debug msg="Creating server 0 at http://172.23.0.3:8080 with weight 1" serviceName=api serverName=0 entryPointName=http routerName=docker.api
    time="2019-04-24T09:44:02Z" level=debug msg="Added outgoing tracing middleware api" routerName=docker.api middlewareName=tracing middlewareType=TracingForwarder entryPointName=http
    time="2019-04-24T09:44:02Z" level=error msg="error during instanciation of docker.api: cannot create middleware: multi-types middleware not supported, consider declaring two different pieces of middleware instead" entryPointName=http routerName=docker.api
    ...
    time="2019-04-24T09:44:02Z" level=debug msg="Creating middleware" middlewareType=Recovery entryPointName=http middlewareName=traefik-internal-recovery
    time="2019-04-24T09:44:02Z" level=debug msg="Creating middleware" entryPointName=traefik middlewareName=pipelining middlewareType=Pipelining routerName=docker.api serviceName=api
    time="2019-04-24T09:44:02Z" level=debug msg="Creating wrr load-balancer" serviceName=api entryPointName=traefik routerName=docker.api
    time="2019-04-24T09:44:02Z" level=debug msg="Creating server 0 at http://172.23.0.3:8080 with weight 1" routerName=docker.api serverName=0 serviceName=api entryPointName=traefik
    time="2019-04-24T09:44:02Z" level=debug msg="Added outgoing tracing middleware api" middlewareType=TracingForwarder entryPointName=traefik routerName=docker.api middlewareName=tracing
    time="2019-04-24T09:44:02Z" level=error msg="error during instanciation of docker.api: cannot create middleware: multi-types middleware not supported, consider declaring two different pieces of middleware instead" entryPointName=traefik routerName=docker.api
    time="2019-04-24T09:44:02Z" level=debug msg="Creating middleware" entryPointName=traefik middlewareName=traefik-internal-recovery middlewareType=Recovery
    ...

**Comment by ldez** [comment]
Hello,

The error is produce inside the server, at this point of the process we don't have any information about the container, service, pod, etc.

So the log cannot be enhanced.

**Comment by andig** [comment]
Thank you. Forgot to mention the possible minor typo in instanciation. I‘m no native speaker- not sure if it should be instantiation?

**Comment by ldez** [comment]
I confirm the typo :smile:

**Comment by andig** [comment]
Actually, I feel at least the middleware name is available in https://github.com/containous/traefik/blob/11f04a453ef9a255c4b6bd3cff7e1938ee3e16ba/pkg/server/middleware/middlewares.go#L95. Not sure what this looks like or if it could be helpful?

**Comment by ldez** [comment]
Only the middleware name is available here.
Internally all middleware names are prefixed by the name of the provider but there are no other data related to the provider specific information.
