### ISSUE TITLE
Create BlockPathRegex Middleware

### ISSUE THREAD

**Issue by dtomcej** [containous/traefik#4813]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Since golang and goregexp does not support lookaheads and readbehinds, issues come into play when we want to expose all except a specific path. For example, `PathPrefix: /`, but NOT `/bacon`.

There should be configurable response codes for the block match.

By having this coded in middlewares, it could be re-used, and shared between providers.

**Comment by ldez** [comment]
duplicate of #4812
