### ISSUE TITLE
svg logo

### ISSUE THREAD

**Issue by siddharthist** [containous/traefik#482]
Do you have an SVG (or similar vector graphic) logo available? I'd like to make a graphic for http://mantl.io that includes the Traefik logo.

**Comment by emilevauge** [comment]
Hey! Yep https://traefik.io/traefik.logo.svg :)

**Comment by siddharthist** [comment]
Awesome, thank you!

**Comment by ohkeenan** [comment]
Hey! Link is dead and I'm hoping to do the same thing!

**Comment by ldez** [comment]
PNG and SVG logo: [traefik.logo.zip](https://github.com/containous/traefik/files/2959254/traefik.logo.zip)

**Comment by ohkeenan** [comment]
Thank you!
