### ISSUE TITLE
Sec-WebSocket-Extensions header missing in response

### ISSUE THREAD

**Issue by tangtony** [containous/traefik#4843]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [X] No

### What did you do?

I am initiating a WebSocket connection from my browser to a service that runs behind Traefik v1.7.9. The service response contains a `Sec-WebSocket-Extensions` header but Traefik doesn't seem to forward it back to the client.

### What did you expect to see?

`Sec-WebSocket-Extensions` header should be forwarded to the client.

### What did you see instead?

`Sec-WebSocket-Extensions` header is not forwarded to the client.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.9
Codename:     maroilles
Go version:   go1.11.5
Built:        2019-02-11_11:36:32AM
OS/Arch:      linux/amd64
```

This issue seems to have been raised in https://github.com/containous/traefik/issues/1945 but was only partially addressed before being closed.

**Comment by tangtony** [comment]
I did some digging myself and it looks like the root cause is the fact that `github.com/gorilla/websocket` does not let you define your own `Sec-WebSocket-Extensions` header. 

This can be easily tested within `github.com/vulcand/oxy/forward` using the `TestWebSocketRequestWithHeadersInResponseWriter` test and changing the key from `HEADER-KEY` to `Sec-WebSocket-Extensions`. This causes the test to fail with the following:
```
time="2019-05-15T20:02:21-04:00" level=error msg="vulcand/oxy/forward/websocket: Error while upgrading connection : websocket: application specific 'Sec-WebSocket-Extensions' headers are unsupported"
--- FAIL: TestWebSocketRequestWithHeadersInResponseWriter (0.00s)
    oxy\forward\require.go:794: 
        	Error Trace:	fwd_websocket_test.go:477
        	Error:      	Received unexpected error:
        	            	websocket: bad handshake
        	Test:       	TestWebSocketRequestWithHeadersInResponseWriter
        	Messages:   	Error during Dial with response: websocket: bad handshake%!(EXTRA *http.Response=&{500 Internal Server Error 500 HTTP/1.1 1 1 map[Content-Length:[22] Content-Type:[text/plain; charset=utf-8] Date:[Thu, 16 May 2019 00:02:21 GMT] Sec-Websocket-Extensions:[HEADER-VALUE] Sec-Websocket-Version:[13] X-Content-Type-Options:[nosniff]] {0xc00012e2a0} 22 [] false false map[] 0xc000108300 <nil>})
FAIL
FAIL	github.com/vulcand/oxy/forward	0.611s
Error: Tests failed.
```

One potential workaround I had in mind was to detect the presence of `permessage-deflate` within `Sec-WebSocket-Extensions` and then enable compression in the header instead. But then it may be possible to have different compression schemes negotiated between the client+traefik and traefik+application.

Or maybe we need some sort of way to enable blind forwarding of websocket traffic to avoid having to create a proxy websocket connection entirely? Not sure if that's feasible or not.

**Comment by davidpope** [comment]
Poking around in the code, my read is that `vulcand/oxy/forward` deliberately strips out all the "interesting" WS headers both on the connection request to the backend service (see `fwd.go` line 502) and on the connection response from the backend (see `fwd.go` line 383). This makes sense if it's acting as a reverse proxy, since the frontend and backend connections are separately negotiated WS sessions.

It might be that what's needed is to set `dialer.EnableCompression = true` in `vulcand/oxy/foward`, i.e. a feature request in that project.

**Comment by cbrherms** [comment]
Having this same issue myself with an app that is requiring permessage-deflate in the response. 
Without it, handshake fails.

**Comment by jpambrun** [comment]
This behavior is very unexpected. Anyone found a workaround to be able to use deflate with web sockets at all?

**Comment by strowk** [comment]
And all of a sudden, once the number of messages increased, I learn that ingress controller at the cloud breaks compression and ticket here stuck for almost a year. 
It's quite sad, that "a modern HTTP reverse proxy" suddenly cannot do what have been never a trouble for nginx. Would really appreciate some workaround here.

**Comment by juliens** [comment]
Hi all,
As we're not relying on `vulcand/oxy` and `gorilla/websocket` anymore in the v2, could you try your use cases with the v2?
I'm waiting for your feedback, thx!

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Community Forum](https://community.containo.us/).
