### ISSUE TITLE
Response is compressed when not requested

### ISSUE THREAD

**Issue by pferrot** [containous/traefik#485]
I have a backend application that supports optional response compression (see [here](http://spray.io/documentation/1.1.2/spray-routing/encoding-directives/compressResponseIfRequested/) for details).

Since 1.0 RC3, the response is compressed even if not requested. E.g. I hit http://myserver/path/to/service/version with my browser: it is supposed to return some JSON, but the browser actually prompts me to download a `version.gz`file, which itself contains a `version` file with the actual JSON. This was not the case with previous versions (inculding RC2), i.e. I would see the actual JSON in the browser window.

It looks like (just guesses, I did not do much investigation) that Traefik now requests the response to be compressed from the backend but does not uncompress it before sending it to the original client...!?

**Comment by emilevauge** [comment]
@pferrot sadly, I can't reproduce this one :'(
I tried using a backend that accepts gzip compression (`emilevauge/whoami`) but it never ends in this issue. Could you provide a docker-compose file that reproduces this issue?

**Comment by emilevauge** [comment]
@pferrot Did you activate `retry` request ?

**Comment by pferrot** [comment]
Yes, I have `retry`enabled, with a fixed value (`attempts = 10` if I remember correctly). I will test the latest build when I am back from vacation :-)

**Comment by pferrot** [comment]
I confirm that I cannot reproduce the issue with the v1.0.0 release. Thanks and congrats for that big milestone!

**Comment by gardnervickers** [comment]
I am seeing this behavior on v1.1.0, but not on v1.0.0.

**Comment by emilevauge** [comment]
@gardnervickers Can you give more details ? Are you using retry ?

**Comment by gardnervickers** [comment]
@emilevauge I was not using retry but I am seeing the same behavior with:
```
[retry]
attempts = 3
```
I am using these charts to deploy traefik with helm to Kubernetes in order provide ingress to our Jenkins dash.
https://github.com/kubernetes/charts/tree/master/stable/traefik

I know that's not a lot to go on, I'll try to make a better repro.
