### ISSUE TITLE
Kubernetes Ingress backend: using self-signed certificates

### ISSUE THREAD

**Issue by mapolone** [containous/traefik#486]
I've created a self-signed certificate for connection towards Kubernetes Ingress backend.
I can't use it even if added on system with update-ca-certificates (CoreOS).

Adding in Kubernetes section the following line:
`insecureskipverify = true`
does not work either.

**Comment by errm** [comment]
are you running traefik in a kubernetes pod?  If you do that you shouldn't have to do anything by default as kubernetes will inject the correct ca and token into the container so traefik can connect to the kubernetes api.

**Comment by discordianfish** [comment]
@mapolone Had the same issue, try running `kubectl get serviceAccounts`, does this return default with a secret? If not, check if your controller-manager is running.

**Comment by mapolone** [comment]
@discordianfish and @errm thank you! It's working now.
