### ISSUE TITLE
Enable to define empty TLS option by flag for Let's Encrypt

### ISSUE THREAD

**Issue by Slashgear** [containous/traefik#488]
I wanted to configure traefik for my project only by flags, in order to limit my configuration file to a simple docker-compose.
This is an extract of my docker-compose file.

service-front:
  labels:
     - "traefik.backend=front"
     - "traefik.port=80"
     - "traefik.frontend.rule=Host:domain.com"
     - "traefik.frontend.entryPoints=http,https"
  image: kebuu/zenquizz-front:dev
traefik:
  image: traefik
  command: --web --docker --acme --acme.domains=domain.com --acme.email=test@traefik.io --entryPoints='Name:http Address::80 Redirect.EntryPoint:https' --entryPoints='Name:https Address::443 TLS' --acme.storagefile=acme.json --docker.domain=localhost --logLevel=DEBUG
  ports:
    - "80:80"
    - "443:443"
    - "8080:8080"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /dev/null:/traefik.toml
    - /opt/acme/acme.json:/acme.json
  labels:
    - "traefik.enable=false"

In my logs I could see that TLS option was not set:

\"https\":{\"Network\":\"\",\"Address\":\":443\",\"TLS\":null,\"Redirect\":null}}

**Comment by doctorpangloss** [comment]
Some people may find this error with the cryptic log 

```
time="..." level=fatal msg="Entrypoint \"https\" has no TLS configuration for ACME configuration"
```

Simply omit the colon after TLS like so:

```
      --entryPoints="Name:http Address::80 Redirect.EntryPoint:https" \
      --entryPoints="Name:https Address::443 TLS" \
```
