### ISSUE TITLE
Traffic Splitting by Headers

### ISSUE THREAD

**Issue by santiagopoli** [containous/traefik#4898]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

It would be nice to provide a way to do Traffic Splitting based on Request Headers (or other request parameters) rather than Service Weights. This would allow to deploy multiple versions of a service, but route only a subset of the requests to the new version. This is a very common approach for doing internal testing before promoting to production (or doing a canary release). Clients will never reach the new version of the service because they will never send those headers, but internal employees can set the headers to test the application in a production environment.

It is also useful for providing a way for users to use the "edge" versions of your app, because you can easily set those headers for a given set of users.

Thanks!

**Comment by ldez** [comment]
Close in favor of  #1164 - Feel free to subscribe there for updates.
