### ISSUE TITLE
Increase Docker API version to work with Linux Containers on Windows

### ISSUE THREAD

**Issue by prochnowc** [containous/traefik#4905]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I tried to run the `traefik:v2.0-alpine` image on Windows Docker with LCOW support.

### What did you expect to see?

I expected traefik to be able to connect to the docker daemon.

### What did you see instead?

An error message:

`level=error msg="Provider connection error Error response from daemon: client version 1.21 i
s too old. Minimum supported API version is 1.24, please upgrade your client to a newer version, retrying in 3.093711959
s" providerName=docker`

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.0.0-alpha4
Codename:     faisselle
Go version:   go1.12.4
Built:        2019-04-17T11:38:21Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Traefik arguments:

`--providers.docker.endpoint=tcp://host.docker.internal:2375`

Docker version:

```
Client: Docker Engine - Community
 Version:           19.03.0-beta3
 API version:       1.40
 Go version:        go1.12.4
 Git commit:        c55e026
 Built:             Thu Apr 25 19:05:10 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.0-beta3
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.4
  Git commit:       c55e026
  Built:            Thu Apr 25 19:06:34 2019
  OS/Arch:          windows/amd64
  Experimental:     true
```

**Comment by traefiker** [comment]
Closed by #4909.
