### ISSUE TITLE
Add Let's Encrypt - DNS challenge RequestIP parameter

### ISSUE THREAD

**Issue by ch-lukas** [containous/traefik#4912]
### Error

I have Traefik setup with Kubernetes and am using DNS challenge with Namecheap to get Let's Encrypt SSL certificates.

Unfortunately I get this error message:
`acme: error presenting token: namecheap: Invalid request IP: 115.70.XXX.XXX [1011150]`.

More details on the Namecheap error can be found from this link - https://www.namecheap.com/support/api/error-codes.aspx. 

### Background

Namecheap only accepts API requests from a pre-authorised whitelist of IP addresses. So when the DNS challenge is called - the "request IP" has to match an item from this whitelist.

The problem I have is although I have a static public IP address (which always connects to me), additionally my ISP assigns a rotating proxy address as my "fake" public IP address. E.g. If you do a "what's my IP address" internet check it will only ever display the "fake" address.

As the fake public address is always changing and is used in the DNS challenge, it is being declined.

### Suggestion

Update the DNS challenge logic with:
Option 1 - Use the real wan IP (and not use reverse lookup)
Option 2 - Add a "requestIP" parameter option e.g.

[acme.dnsChallenge]
  delayBeforeCheck = 0\n
  provider = "namecheap"
  requestIP = "200.0.0.1"

**Comment by dduportal** [comment]
Hi @ch-lukas ,

as Traefik relies on the [go-acme/lego](https://github.com/go-acme/lego) library for implementing Let's Encrypt features, could you open an issue on Lego for this?
