### ISSUE TITLE
Supporting ETCD as provider for Traefik v2

### ISSUE THREAD

**Issue by xmonader** [containous/traefik#4914]
It'd be amazing if we can continue using etcd provider from traefik 1.7 in traefik v2.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

Issue templates help us help you by providing all necessary information.

Please edit your issue and use the available templates:

- [Feature request](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/Feature_request.md)
- [Bug report](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/Bug_report.md)

And remember: each time someone ignores the template, a cute little bunny dies.
<details>
<summary>#SaveTheCuteBunny :heart: :rabbit: :heart:</summary>

![southpark - estrella kill rabbit](https://user-images.githubusercontent.com/5674651/27143914-3cea7896-5130-11e7-81f8-02d8ac2da7a7.gif)

![southpark - estrella kill rabbit2](https://user-images.githubusercontent.com/5674651/27143924-49104c72-5130-11e7-82ae-ccedbd5dfa1c.gif)

</details>

**Comment by dduportal** [comment]
Hi @xmonader , for information, we have the a project task board for the v2.0.

The etc provider re-implementation in v2.0 is tracked in the card "KV providers": <https://github.com/containous/traefik/projects/3?card_filter_query=kv>

**Comment by xmonader** [comment]
@dduportal thank you so much :)
