### ISSUE TITLE
Allow multiple addresses per frontend (IPv4 + IPv6)

### ISSUE THREAD

**Issue by fuzzykiller** [containous/traefik#4932]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

In Apache httpd and others, I can set up multiple listeners for any number of IPv4 and IPv6 addresses and ports. This should also be possible with Traefik.

This way, I could listen for both IPv4 and IPv6 connections on the same frontend.

Listening on `[::]` is not a replacement, binding to specific IPv4 and IPv6 addresses should be possible.

**Comment by dduportal** [comment]
Hi @fuzzykiller , thanks for your interest.

As Traefik uses the function [`net.Listen`](https://golang.org/pkg/net/#Listen) for the entrypoint definitions, you could totally configure the entrypoint to listen on a specific  ipv4 or ipv6 address:

```toml
[entryPoints]
  [entryPoints.httpLoopback]
    address = "127.0.0.1:80"
```

You can then create different entrypoints, each one listening on a couple (IP + port). The only requirements is to add all these entrypoints to the list of `defaultEntrypoints`, or define the `frontend.entrypoint=xxxx` on your applications.

The documentation is lacking a proper explanation and/or example to make this explicit.
If it works for you, would you be willing to contribute to the documentation?

If you are having issues or question, we recommend you to reach our support Slack channel at slack.traefik.io, so anyone from the community could help, as your concern looks like to already be configurable.

**Comment by fuzzykiller** [comment]
Thanks for your reply!

What you’re suggesting is not really supported. For example, on `[acme]`, I can specify only a single entry point. On the API, I can only specify a single entry point.

So even if we go ahead and fight with all the inconveniences of having 4 entry points (IPv4/6 × HTTP/S), it just cannot work. HTTPS fails on the “other” entry point, because it doesn’t know how to get certificates from Let’s Encrypt.

To have IPv4-IPv6 parity, the entry point must be the same.

**Comment by dduportal** [comment]
Hi @fuzzykiller , thanks for the clarification.

If our understanding is correct, you would want to be able to configure Traefik to listen to different couples ( `IPv4(v6)` / `ports` ) for a given entrypoint.

The root requirement being to be able to configure ACME for this collection of "IP/ports", including challenges right?

Did we miss something on your initial requirement?

**Comment by fuzzykiller** [comment]
No, that sounds about right. 👍

**Comment by dduportal** [comment]
Cool ! As the initial question of this issue has been answered, may we ask you to open a new issue of type "Feature request", which description would come from the summary I wrote, and give details about your root use case (explaining you need the `acme` option and it doesn't work with multiple endpoints)?

The goal is to have a clear feature request for the future, so anyone with the same issue could have the base answer here when searching, while the contributors would have a dedicated feature request without having to review all of ou exchange :)

**Comment by fuzzykiller** [comment]
So, something like this perhaps?

> # Listen on multiple addresses/ports with entry point 
> An entry point should be able to listen on multiple IP addresses/ports. This would enable the use of Let’s Encrypt (`[acme]`) for both IPv4 and IPv6 on situations were both addresses are equivalent. `[acme]` works only with a single entry point.

The issue I see is that there is another possible solution: Making the Let’s Encrypt code support multiple entry points. I’m not sure which is more difficult to implement.

**Comment by dduportal** [comment]
This description looks good, thanks @fuzzykiller !

We should try to describe a high-level requirement, more than a possibility of implementation, for numerous reasons:

- Describing the "Why" avoid biasing ourselves (and the possible contributors implementing the feature): we want different proposed solutions to solve this
- The Traefik project is currently focusing on the release of the brand new 2.0 (currently in alpha state). As explained in https://blog.containo.us/back-to-traefik-2-0-2f9aa17be305, a lot of internals are changing, so better to wait for the code freeze and start sharing the need with the maintainers.

Ready for opening the feature request?

**Comment by fuzzykiller** [comment]
Opened https://github.com/containous/traefik/issues/4961
