### ISSUE TITLE
Dashboard/API: Discussion around the User Experience and Security

### ISSUE THREAD

**Issue by dduportal** [containous/traefik#4934]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

This issue is a placeholder for a discussion around the Dashboard / API.

We want to let our users enjoy a full-featured dashboard, but in a way that enforces security, and that doesn’t enable this feature unless using proper credentials.

The goal is to underline the expected features/fixes to be done in Traefik v2.x based on the community feedbacks.

The context is the following: we published 2 CVEs in 1 year about sensitive data available through the API. The impact is low, as we do not recommend to enable the Dashboard/APi in production, except when it's correctly secured (ref. https://docs.traefik.io/configuration/api/#security).

However, having feedbacks on how the Dashboard and API could be improved in the future to find the right balance between a good Traefik user experience with a set of good enough security practises is a good start.

So the 🎤 is yours!

This discussion is expected to last until Traefik v2.0 final version is released.
Any feature request would result on specific issues, to be planned and worked on on time.

**Comment by polarathene** [comment]
Could Traefik be aware of basic/digest/forward auth applying to the api/dashboard routes? Then you could just raise an error in the logs and not serve the request until auth middleware is applied?

**Comment by shaun-blake** [comment]
I don't know if this is already possible and whether it will be possible in v2 since we're just starting with Traefik at v2, but we only need to view the current configuration but not make changes - so a read-only mode. If we see something that needs to be changed we'll change it at the source (the docker swarm labels for us).

**Comment by andypost** [comment]
Moreover if you're secure dashboard with basic auth, it should use TLS

**Comment by ldez** [comment]
Closed by #5311
