### ISSUE TITLE
Traefik ingress weight not working as per expectation

### ISSUE THREAD

**Issue by nagendra547** [containous/traefik#4940]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

 No

### What did you do?

I have configured the following ingress for traefik but traefik is sending the entire traffic to app-blue-release. Ideally it should send only 30% traffic to blue and 70% traffic to green, but it's not working as per expectation.

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    traefik.frontend.entryPoints: http
    traefik.ingress.kubernetes.io/service-weights: |-
      app-green-release: 70.0
      app-blue-release: 30.0
  creationTimestamp: 2019-06-04T06:00:37Z
  generation: 2
  labels:
    app: traefik-app
  name: traefik-app
  namespace: mynamespace
  resourceVersion: "645536328"
  selfLink: /apis/extensions/v1beta1/namespaces/mynamespace/ingresses/traefik-app
  uid: 4637377-747b-11e9-92ea-005056aeabf7
spec:
  rules:
  - host: mycompany2.com
    http:
      paths:
      - backend:
          serviceName: app-release
          servicePort: 8080
  - host: mycompany.com
    http:
      paths:
      - backend:
          serviceName: app-ui-release
          servicePort: 80
        path: /widget
      - backend:
          serviceName: app-green-release
          servicePort: 8080
        path: /
      - backend:
          serviceName: app-blue-release
          servicePort: 8080
        path: /
status:
  loadBalancer: {}

```

-->

### What did you expect to see?

Traffic should be distributed as per weight provided.
30 % traffic should go to app-blue-release
70 % traffic should go to app-green-release

### What did you see instead?

Entire traffic (100%) traffic went to app-blue-release

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
traefik:v1.7.11-alpine
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```
TOML-
defaultEntryPoints = ["http"]
allowMinWeightZero = true
[respondingTimeouts]
idleTimeout = "15s"
[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.traefik]
  address = ":8877"

[accessLog]
  filePath = "/var/access.log"

[api]
  dashboard = true
  entryPoint = "traefik"
```

Earlier when the weight was configured with 10 (for blue) and 90(for green) then it was working fine. But once we changed to 30 and 70 respectively then this problem is happening.

So this issue is inconsistent. But I have seen this 50% of time happening.
One more thing, In the traefik dashboard the configuration is displaying perfectly fine, but  for the real traffic it's not following the weights.

**Comment by dduportal** [comment]
Hi @nagendra547, could you follow up in #4494 which is the same topic ?

Thanks a lot for your feedback.
