### ISSUE TITLE
Sticky coookie value should be hashed

### ISSUE THREAD

**Issue by sylr** [containous/traefik#4958]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I enabled stickiness on my backend and the sticky cookie value contained the endpoint of the server selected

### What did you expect to see?

I expected to see a random value or a hash, not a value divulging an internal ip address.

**Comment by dduportal** [comment]
Closing as duplicate of #2299.

Feel free to subscribe to the updates of #2299.
