### ISSUE TITLE
Add more documentation

### ISSUE THREAD

**Issue by emilevauge** [containous/traefik#497]
More documentation and examples should be added to https://docs.traefik.io.
Please give your expectations in a comment :)

**Comment by Slashgear** [comment]
## Traefik flags
I used traefik with a docker-compose and I wanted to get rid of the traefik toml. I wanted to use flags to configure it. I didn't have the choice to start the binary of traefik on my host to have the list of available flags. It would be very useful to have them somewhere in the documentation.

## Let's encrypt support
There are two example of Let's encrypt support in the documentation with few differences.The few differences can raise doubts.
* [Let's encrypt](https://docs.traefik.io/user-guide/examples/#lets-encrypt-support)
* [Acme](https://docs.traefik.io/toml/#acme-lets-encrypt-configuration)

## Examples
[This](https://docs.traefik.io/#test-it) example is very simple, it use *whoami* images, but we may need a more complete example which use a common application (RocketChat, Ghost, ..). It would be much more striking.

**Comment by WTFKr0** [comment]
I don't use traefik.toml
For traefik binary options, you can launch :
```
docker run traefik:reblochon --help
```
Maybe we can add this to the doc

**Comment by ldez** [comment]
The documentation has been improved, I think we can close.
