### ISSUE TITLE
Add cookie support for Rules

### ISSUE THREAD

**Issue by richierg** [containous/traefik#4974]
### Do you want to request a *feature* or report a *bug*?

Feature

### Context
I'm currently in a situation where I need to access 2 same applications with the same URL but different Front UX/UI technologies and design.
One have a new UI/UX, the other have the old one.
I would like to set cookie which contain the user preference UI/UX (old or new).

### Proposal
I propose that traefik can read custom cookie and redirect to the right backend thanks to Rules : 
eg:
traefik.frontend.rule=CookieName:<custom_cookie>
traefik.frontend.rule=CookieContent:"new"

**Comment by dduportal** [comment]
Hi @richierg , could you try with the matcher `HeadersRegexp` (ref. https://docs.traefik.io/basics/#matchers ) to capture the key + value of your cookie and let us if it works for your use case?

**Comment by richierg** [comment]
Hi, thanks for the answer.
Finally I find an other acceptable way for my case (I will use Path rules).
But I think your solution will work too.
Thanks

**Comment by dduportal** [comment]
Thanks for the (fast) feedback @richierg !
