### ISSUE TITLE
runAsNonRoot for v2

### ISSUE THREAD

**Issue by bill-within** [containous/traefik#4991]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Hi guys,
It'd be great to be able to run traefik with the `runAsNonRoot` security context in kubernetes, but we can't because it exposes port 80. As a bit of a work-around we can use the `capabilities` mechanism to drop: ALL and add: CAP_NET_BIND_SERVICE, but that's a bit non-K8s-ish. I'm not entirely sure what work port 80 is doing when there are no entryPoints pointing to it. But maybe there are overriding concerns re: backwards compatibility or compatibility with non-k8s-environments.

Thanks!

**Comment by ldez** [comment]
Duplicate of https://github.com/containous/traefik-library-image/issues/38
