### ISSUE TITLE
Basic Auth with DynamoDB lacks users field

### ISSUE THREAD

**Issue by jmkgreen** [containous/traefik#4998]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [X] No

### What did you do?

Upgraded from 1.7.11 to 1.7.12

### What did you expect to see?

Front-end should continue to authenticate users using embedded basic user list.

### What did you see instead?

HTTP Basic credentials dialog is repeatedly shown, no access is granted ever.

### Output of `traefik version`: (_What version of Traefik are you using?_)

1.17.12 using AWS Fargate

```
Traefik version v1.7.12 built on 2019-05-29_07:35:02PM
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

We use Fargate with the following parameters:

```
            - !Sub --dynamodb.tablename=${ProductName}-Traefik
            - !Sub --dynamodb.region=${AWS::Region}
            - --dynamodb.debugloggeneratedtemplate=true
            - --dynamodb.trace=true
```

The entry within Dynamodb is set using python. It has this record for the front-end item:

```
    Item={
        "id": "es-frontend",
        "name": "elasticsearch-frontend",
        "frontend": {
            "backend": "elasticsearch-backend",
            "routes": {
                "subdomains": {
                    "rule": "HostRegexp:{subdomain:search.*}"
                }
            },
            "auth": {
                "basic": {
                    "users": [ "xxx:$apr1$m1xce2g0$K8Z0x5kckkEdIFVl/8rxw/" ],
                    "removeHeader": True
                }
            }
        }
    }
```

(Password is irrelevant, it has already been changed)

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

With 1.7.11 we can clearly see the config has "users" field set. With 1.7.12, no such field is present in the logs

1.7.11 (apologies for the white-space that has been introduced):
```
time = "2019-06-21T13:27:23Z" level = debug msg = "Configuration received from provider dynamodb: {" backends ":{" elasticsearch - backend ":{" servers ":{" es ":{" url ":" https: //vpc-ancilla-elasti-xxxxx.eu-west-2.es.amazonaws.com","weight":10}},"loadBalancer":{"method":"wrr"}}},"frontends":{"elasticsearch-frontend":{"entryPoints":["http"],"backend":"elasticsearch-backend","routes":{"subdomains":{"rule":"HostRegexp:{subdomain:search.*}"}},"priority":0,"basicAuth":null,"auth":{"basic":{"users":["xxx:$apr1$m1xce2g0$K8Z0x5kckkEdIFVl/8rxw/"],"removeHeader":true}}}}}"
```

1.7.12 (no `users` field exists):
```
time="2019-06-21T13:38:50Z" level=debug msg="Configuration received from provider dynamodb: {"backends":{"elasticsearch-backend":{"servers":{"es":{"url":"https://vpc-ancilla-elasti-xxxxx.eu-west-2.es.amazonaws.com","weight":10}},"loadBalancer":{"method":"wrr"}}},"frontends":{"elasticsearch-frontend":{"entryPoints":["http"],"backend":"elasticsearch-backend","routes":{"subdomains":{"rule":"HostRegexp:{subdomain:search.*}"}},"priority":0,"basicAuth":null,"auth":{"basic":{"removeHeader":true}}}}}"
```

**Comment by traefiker** [comment]
Closed by #5002.
