### ISSUE TITLE
Route by path

### ISSUE THREAD

**Issue by rogeriollacerda** [containous/traefik#500]
I have something like 600 microservices running on Mesos/Marathon and the access if from the same host. Ex: api.traefik.io/api1 api.traefik.io/api2. How can I route the requests to each API by context using marathon labels? Is it possible?

**Comment by emilevauge** [comment]
@rogeriollacerda you should get more information from http://docs.traefik.io/basics/#frontends on using `PathPrefixStrip` rules with label `traefik.frontend.rule` http://docs.traefik.io/toml/#marathon-backend. For example: `traefik.frontend.rule=Host:api.traefik.io;PathPrefixStrip:/api1`

**Comment by rogeriollacerda** [comment]
@emilevauge Thanks! Everything Ok now!
