### ISSUE TITLE
PathPrefixStrip in 2.0

### ISSUE THREAD

**Issue by lsgroup** [containous/traefik#5004]
Feature
PathPrefixStrip rule is missing in 2.0.  We're using it quite a bit in 1.7.  Is there another way to strip the path before forwarding to the backend when using 2.0?

**Comment by ldez** [comment]
In the v2, the ["modifiers"](https://docs.traefik.io/v1.7/basics/#modifiers) became middleware: https://docs.traefik.io/v2.0/middlewares/stripprefix/

**Comment by lsgroup** [comment]
Great thanks! I knew it had to be somewhere. I'll need to read up on middleware.
