### ISSUE TITLE
Kubernetes provider: should allow the master url to be override

### ISSUE THREAD

**Issue by javefang** [containous/traefik#501]
When using Traefik with Kubernetes, there are currently 3 ways to define where the Kubernetes api server is running:
1. Environment variable: KUBERNETES_SERVICE_HOST
2. The "/etc/traefik/traefik.toml" config file
3. The "--kubernetes.endpoint" command line parameter

Currently 1 seems to be used as a priority, regardless of what value is set in 2 or 3. I think the correct priority should be 3(command line) > 2 (config) > 1 (default env var).

**Comment by javefang** [comment]
I think Kubernetes also has a bug related to this. People who want to use Traefik with high availability kubernetes master should either
1. Override the kube apiserver url in Traefik config with the load balancer's URL
2. Wait for this issue to be fixed https://github.com/kubernetes/kubernetes/issues/22609

**Comment by errm** [comment]
Yes that sounds reasonable to me.

It might be possible to work around by setting `KUBERNETES_SERVICE_HOST` in your Traefik PodSpec . . . but perhaps not, I haven't tried.

**Comment by javefang** [comment]
@errm thanks, I tried, but doesn't seem to work correctly... (i.e. it's not calling the URLs set by the env var)
