### ISSUE TITLE
Reusing Variables from Host Rule Regex

### ISSUE THREAD

**Issue by port22** [containous/traefik#5018]
Perhaps this is already possible, but I didn't found it documented.

Assume a Host Rule like this (docker-compose style):

```
    labels:
      - "traefik.frontend.rule=HostRegexp:{portal:.+}.example.org"
```

Now I want to forward this regex'd variable to the app via HTTP Header like this:

```
      - "traefik.frontend.headers.customRequestHeaders=portal:$portal"
```

Is that anyhow possible?

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI tells me this one is neither of them.

I encourage your to seek community support: join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

You can of course double check [Traefik's documentation](https://docs.traefik.io/) :sweat_smile:

**Comment by dduportal** [comment]
Hi @port22 , you might want to use the header `X-Forwarded-Header` to provide this information to your backend information, what do you think?

**Comment by port22** [comment]
Hi @dduportal , 
maybe you got me wrong - I want to extract a part of the domain and re-use it at another place.
If it's the `X-Forwarded-Header` or a custom HTTP Header I don't actually care, but how's it gonna be written?

In nginx you do this:
```
server_name ~^(?<portal>.+?)\.example\.intra$;
proxy_set_header PORTAL "$portal";
```
portal is just an example to reflect any arbitrary part of the domain.
