### ISSUE TITLE
Traefik --api.address argument not implemented

### ISSUE THREAD

**Issue by Artiume** [containous/traefik#5025]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?
I use arguments to create my traefik setup in docker so that I don't have to use a traefik.toml file. The option to change the api address via command line (--api.address) is not implemented. Request it is added so that the api address can be changed via arguments.

I can't find the ticket where I found the full list however I made my own copy. Could this be readily added to the traefik website so that it easily referable? The only other way I know of accessing this list is to provide a bad argument to the traefik container.
https://github.com/Artiume/docker-swarm/blob/master/traefikflags.txt

I haven't set up consul yet so that I can make a frontend/backend traefik so that the docker socket isn't exposed, however, I was hoping my example could be added to the website. It took a while to get it working and I feel that others could benefit from it.
https://github.com/Artiume/docker-swarm/blob/master/traefik-swarm-mode.yml

**Comment by ldez** [comment]
https://docs.traefik.io/configuration/api/#address-port

**Comment by Artiume** [comment]
Yes, if I use a file.toml or traefik.toml, I can modify the port. 

I tried to use 
--entrypoint.foo
--api.entrypoint.foo=8080 

but --entrypoint.var is also not enabled or I don't have the correct via commandline arguments so I was not able to provide a workaround the lack of --api.address without using a toml file.

That's another reason, I would like a full list in one single area so that I don't have to dig through several different pages to find the answer I am looking for.

**Comment by ldez** [comment]
The documentation for entrypoints with the CLI: https://docs.traefik.io/configuration/entrypoints/#cli

The transcription of the TOML example https://docs.traefik.io/v1.7/configuration/api/#address-port for the CLI:

```bash
--defaultEntryPoints="http"
--entryPoints='Name:http Address::80'
--entryPoints='Name:foo Address::8082'
--entryPoints='Name:bar Address::8083'
--ping.entryPoint=foo
--api.entryPoint=bar
```



Take a look to the documentation of Traefik v2 :wink:  https://docs.traefik.io/v2.0/reference/static-configuration/cli/

**Comment by Artiume** [comment]
thanks, that works :) i'll close the ticket since there's a work around. 

and wow! i'll have to start looking at v2 soon enough :)
