### ISSUE TITLE
Documentation seems to be out of sycn with repository / deprecated onDemand example

### ISSUE THREAD

**Issue by dragetd** [containous/traefik#5027]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

Check the example page under https://docs.traefik.io/user-guide/examples/

### What did you expect to see?

Examples using the current configuration options and avoiding deprecated options.

### What did you see instead?

An example using the deprecated option `onDemand`.

I wanted to create a PR that would update the example, but I was unable to find the documentation files for the examples in the repository. So the documentation might no longer be in sync with the repository…?

**Comment by geraldcroes** [comment]
Hi! And thank you for your help.

Actually, the documentation in docs.traefik.io is based on the 1.7 branch, and the file you were looking for is [here](https://github.com/containous/traefik/blob/v1.7/docs/user-guide/examples.md)

The master branch is the documentation for the upcoming 2.0 ([readable here](https://docs.traefik.io/master/)).

We might want to fix the button though ...

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Community Forum](https://community.containo.us/).
