### ISSUE TITLE
Streamline case of options in v2.0 documentation

### ISSUE THREAD

**Issue by josefglatz** [containous/traefik#5028]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

Hi, I'm relatively new to traefik. I started using v1.x and now I test v2.0. It's really hard to get the correct cases for all the options. In some of the configuration snippets in the v2.0 documentation options are uppercamelcase. In some lowercamelcase. In the local navigation lowercase.

### What did you expect to see?

It would be nice to have those consistently the same case.

**Comment by ldez** [comment]
Related to  #4987

**Comment by traefiker** [comment]
Closed by #5043.
