### ISSUE TITLE
Changed host rules in docker label do not work after "docker-compose restart"

### ISSUE THREAD

**Issue by josefglatz** [containous/traefik#5035]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

When I change the rules for a docker container via labels and run `docker-compose restart` afterwards, the changed labels are not changed in Traefik's v2 `/api/rawdata`.

### What did you expect to see?

I expect to see the changed label for the rule.

### What did you see instead?

The prior existing label.

---

Is this a bug in docker or in Traefik? Or is it just as-is and I I have `docker-compose stop && docker-compose up -d`?

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI tells me this one is neither of them.

I encourage your to seek community support: join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

You can of course double check [Traefik's documentation](https://docs.traefik.io/) :sweat_smile:

**Comment by geraldcroes** [comment]
Hi! I'm tagging along, we'd like to discuss this on the community forum with you, please join us 👍
