### ISSUE TITLE
How to use  AddPrefix Add multiple paths prefix to a backend  in ingress

### ISSUE THREAD

**Issue by G-master** [containous/traefik#5053]
For example, I have a domain name： 
 
```
                         |---svc/api1
                 |/toapi1/
pro.hxx.com     |
                 |/toapi2/
                         |---svc/api2
```

I want to add a different prefix to the backend request via url

When I visit  pro.hxx.com/toapi1/       i want  get  request from  svc/api1

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI tells me this one is neither of them.

I encourage your to seek community support: join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

You can of course double check [Traefik's documentation](https://docs.traefik.io/) :sweat_smile:
