### ISSUE TITLE
Traefik not renewing certs, "missing credentials" but not really

### ISSUE THREAD

**Issue by daninfuchs** [containous/traefik#5054]
traefik (I believe) 1.7.12; 'latest' tag as of July 2, 2019

Established stable configuration has been running for quite some time (long enough for the certs to need to be renewed, at least once - honestly I can't even remember how long) and today, all of my sites fail SSL - certificate out of date. Traefik has not been renewing them. As a diagnostic, I attempted to reset acme data by removing acme.json - now when I start Traefik, I get the following:

`time="2019-07-02T08:06:45Z" level=error msg="Unable to obtain ACME certificate for domains \"<snip>\" detected thanks to rule \"Host:<snip>\" : cannot get ACME client cloudflare: some credentials information are missing: CLOUDFLARE_EMAIL,CLOUDFLARE_API_KEY"`

Meanwhile, Portainer (and docker inspect) both show the same environment variables I had previously configured, during initial setup. These values have not changed; I use the same email, and it has the same API key.

Clip from 'docker inspect core_traefik_1';
 `           "Env": [
                "CF_API_EMAIL = \"SNIP\"",
                "CF_API_KEY = \"SNIP\"",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],`
 
Portainer shows the same environment variables, and they're also correct (of course);
![portainer](https://user-images.githubusercontent.com/42219549/60496219-35d18980-9c67-11e9-8437-83c46d11527e.png)

I attempted to 'docker exec' a shell to inspect it from the inside but there don't seem to be any (that I can figure out) and from there I don't know where to go.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI tells me this one is neither of them.

I encourage your to seek community support: join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

You can of course double check [Traefik's documentation](https://docs.traefik.io/) :sweat_smile:

**Comment by daninfuchs** [comment]
This is absolutely a bug report.

**Comment by ldez** [comment]
Hello, could you join our [Community Forum](https://community.containo.us), I will help you.

**Comment by daninfuchs** [comment]
Joined, post is pending.
