### ISSUE TITLE
Traefik must not trust X-Forwarded-Ssl-Client-Cert-Infos headers from client

### ISSUE THREAD

**Issue by rinokadijk** [containous/traefik#5061]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

Use an http client to send X-Forwarded-Ssl-Client-Cert-Infos header without presenting a valid client certificate. A backend can't trust this header because a client can send in a header without presenting a valid client certificate.

### What did you expect to see?

Traefik removing or modifying this header when no valid client certificate is present.

### What did you see instead?

Traefik forwarding this header to backend without modification. 

### Output of `traefik version`: 1.7.12

```
(paste your output here)
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
1.7.12
```

```    [entryPoints.https]
    address = ":443"
    compress = true
        [entryPoints.https.tls]
        minVersion = "VersionTLS12"
        cipherSuites = [
              "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
              "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
              "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
              "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
              "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
              "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
              "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256",
              "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256"
            ]
            [[entryPoints.https.tls.certificates]]
            certFile = "{{ traefik_cert_dir }}/{{ traefik_domain }}.pem"
            keyFile = "{{ traefik_cert_dir }}/{{ traefik_domain }}.key"
            [entryPoints.https.tls.ClientCA]
            files = ["{{ traefik_cert_dir }}/ca.pem"]
            optional = true
        [entryPoints.https.forwardedHeaders]
            trustedIPs = ["127.0.0.1/32", "xxx.yyy.zzz.aaa", "xxx.yyy.zzz.aaa", "xxx.yyy.zzz.aaa", "xxx.yyy.zzz.aaa"]
        [entryPoints.https.proxyProtocol]
            trustedIPs = ["127.0.0.1/32", "xxx.yyy.zzz.aaa", "xxx.yyy.zzz.aaa", "xxx.yyy.zzz.aaa", "xxx.yyy.zzz.aaa"]
```

**Comment by ldez** [comment]
Hello, it's already fixed by https://github.com/containous/traefik/pull/4963

**Comment by rinokadijk** [comment]
Ok, thanks!
