### ISSUE TITLE
X-Request-Start header

### ISSUE THREAD

**Issue by scalp42** [containous/traefik#5063]
Hi folks,

Looking at the headers documentation (https://docs.traefik.io/v2.0/middlewares/headers/), we can't figure out if Traefik supports setting a dynamic header based on micro/milliseconds since epoch.

Example with Nginx:

```
proxy_set_header X-Request-Start "t=${msec}";
```

or Apache:

```
RequestHeader set X-Request-Start "%t"
```

By setting the header, it allows visibility into requeust queuing to the app from farther upstream (Traefik in our scenario).

It's also needed for APM vendors (New Relic, Scout, Instana, etc):

- https://docs.newrelic.com/docs/apm/applications-menu/features/request-queue-server-configuration-examples
- https://docs.scoutapm.com/#http-header

Let us know if it's possible.

Thanks in advance ✌️

**Comment by ldez** [comment]
Hello,

We think that your request is covered by the proposal #5036
