### ISSUE TITLE
HTTP/2

### ISSUE THREAD

**Issue by matjazmav** [containous/traefik#5065]
I couldn't find any documentation regarding HTTP/2, does Treafik support it?

I'm using Traefik with Let's Encrypt service now I want all traffic to go over HTTP/2, how can I do that?

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI tells me this one is neither of them.

I encourage your to seek community support: join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

You can of course double check [Traefik's documentation](https://docs.traefik.io/) :sweat_smile:
