### ISSUE TITLE
HTTPS Backend with self-signed cert on MacOS X

### ISSUE THREAD

**Issue by dudleycarr** [containous/traefik#507]
Contacting a backend on OS X with a self-signed cert yields an error about validating the certificate.

There's an issue with self-signed certificates on MacOSX El Capitan and Go. Take a look at this issue:
https://github.com/golang/go/issues/14514

The recommended workaround until Golang 1.8 is this:
https://github.com/hashicorp/go-rootcerts

**Comment by ldez** [comment]
I'll close this issue, because I think the question is answered, but feel free to continue the conversation.
