### ISSUE TITLE
Problem with wildcard certificate used several times

### ISSUE THREAD

**Issue by sylr** [containous/traefik#5079]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [X] No

### What did you do?

We are using a single wildcard certificates for numerous kubernetes ingresses. There seems to be a corner case when we want to test the renewal of the certificate on a single ingress.

Unless I'm mistaken Traefik seems to cache certificates by CN and does not add a certificate when it already knows it.

This makes it impossible to use a new version of a wildcard certificate on a limited number of ingresses. You have to apply the new version of the certificate on all ingresses which use it so that Traefik accept to replace it.

**Comment by mpl** [comment]
@sylr you did not specify what version of Traefik you are using, which matters for the answer we're going to give you.

**Comment by sylr** [comment]
1.7

**Comment by mpl** [comment]
@sylr There's indeed a cache, but it should expire after a while (in the order of the hour), so your problem should resolve by itself after that expiration.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
