### ISSUE TITLE
Flag --etcd.endpoint default

### ISSUE THREAD

**Issue by JulienBalestra** [containous/traefik#508]
Hi !
When using etcd backend, the default is set to "127.0.0.1:400" : [configuration.go](https://github.com/containous/traefik/blob/6e5a221180e6bb209c52668cd7b5607524b78d13/configuration.go#L254)

> 
	// default Etcd
	var defaultEtcd provider.Etcd
	defaultEtcd.Watch = true
	defaultEtcd.Endpoint = "127.0.0.1:400"
	defaultEtcd.Prefix = "/traefik"
	defaultEtcd.Constraints = []types.Constraint{}

But in fact, the legacy default port, for etcdv1, was over 4001.
Maybe you freed this one for BoltDB.

Today, most of the etcd v2 or v3 consider you are running for clients over 2379 (2380 against peers), so can I suggest to set up the default over 2379 ?

[iana etcd](https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=etcd)

Thanks a lot for the project !

**Comment by errm** [comment]
seems sensible
