### ISSUE TITLE
Traefik 2 - failed to run traefik using docs tutorial 

### ISSUE THREAD

**Issue by abusaidm** [containous/traefik#5094]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?
No

### What did you do?

Followed the documentation on https://docs.traefik.io/v2.0/user-guides/crd-acme/ ro run Traefik 2 ok a k3s configured single machine.

### What did you expect to see?
Traefik to work and the new service to be reachable

### What did you see instead?
Traefik didn't load correctly and when checking its logs I got:

`command traefik error: failed to decode configuration from flags: field not found, node: trace`

### Output of `traefik version`: (_What version of Traefik are you using?_)
I am pulling the same at the tutorial, `traefik:v2.0`

**Comment by ldez** [comment]
Hello, thanks for reporting.

There is an error in the deployment definition, you have to remove `--providers.kubernetescrd.trace`

**Comment by abusaidm** [comment]
thanks, this worked.

**Comment by traefiker** [comment]
Closed by #5096.
