### ISSUE TITLE
Frequent Skipping Configuration

### ISSUE THREAD

**Issue by timeandtimeago** [containous/traefik#5107]
Hi, 
I was wondering if someone could tell me what it means when traefik outputs a line like this:
```level=info msg="Skipping same configuration for provider docker"```

When nothing is happening on my server - it will sit there outputting this same line over and over.

I just want to make sure I don't have something going on. If this is expected - apologies for the unnecessary issue.

**Comment by fopina** [comment]
Second this. Search this repository for the string does not show anything...

**Comment by dduportal** [comment]
Hi @timeandtimeago, this message is normal: when the Docker API emits an event for any change,
Traefik is notified and react by retrieving the configuration from the API, and compare it to its last know version.

If nothing changed from last known version (meaning no item related to Traefik has changed), then this message is printed.

**Comment by fopina** [comment]
Any chance this would make sense as debug message instead of info?
For log sanity :)

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

Issue templates help us help you by providing all necessary information.

Please edit your issue and use the available templates:

- [Feature request](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/Feature_request.md)
- [Bug report](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/Bug_report.md)

And remember: each time someone ignores the template, a cute little bunny dies.
<details>
<summary>#SaveTheCuteBunny :heart: :rabbit: :heart:</summary>

![southpark - estrella kill rabbit](https://user-images.githubusercontent.com/5674651/27143914-3cea7896-5130-11e7-81f8-02d8ac2da7a7.gif)

![southpark - estrella kill rabbit2](https://user-images.githubusercontent.com/5674651/27143924-49104c72-5130-11e7-82ae-ccedbd5dfa1c.gif)

</details>

**Comment by CybotTM** [comment]
seems already be declined: https://github.com/containous/traefik/pull/5718

**Comment by dduportal** [comment]
Thanks @CybotTM for pointing this. We are closing this issue as the answer to the initial question is "yes it is expected behavior". More details on the PR you pointed.

Follow up on #5693.
