### ISSUE TITLE
Make an HTTPS Forward Proxy with Authentication

### ISSUE THREAD

**Issue by clintnetwork** [containous/traefik#5110]
Hi,

I would like to make a forward https proxy with authentication, do you think that its possible with `traefik` ?

By example:
user1 = xx.xx.xx.XX
user2 = xx.xx.xx.XY
user3 = xx.xx.xx.XZ
etc

Thank you

PS: sorry to use bug report feature but I didn't found anything :(

**Comment by dduportal** [comment]
Hi @clintnetwork , could you use the community forum for such question please: http://community.containo.us ? Thanks for your interest in the project.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by clintnetwork** [comment]
TY 💃
