### ISSUE TITLE
Healthcheck probes "hangs up" too fast

### ISSUE THREAD

**Issue by colinleroy** [containous/traefik#5124]
Hi,
In some circumstances, it looks like the healthcheck probe closes connection too quickly. Traefik-wise, this poses no problem as the 200 code is registered and the backend is set healthy. On the other side though, this triggers huge backtraces in our Spring-boot application, along the lines of:

```
Jul 19 11:53:52 leg-node4 stack_b_admin_3_1[1748]: org.apache.catalina.connector.ClientAbortException: java.io.IOException: Connection reset by peer
Jul 19 11:53:52 leg-node4 stack_b_admin_3_1[1748]: #011at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:393)
Jul 19 11:53:52 leg-node4 stack_b_admin_3_1[1748]: #011at org.apache.tomcat.util.buf.ByteChunk.flushBuffer(ByteChunk.java:426)
Jul 19 11:53:52 leg-node4 stack_b_admin_3_1[1748]: #011at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:342)
Jul 19 11:53:52 leg-node4 stack_b_admin_3_1[1748]: #011at org.apache.catalina.connector.OutputBuffer.flush(OutputBuffer.java:317)
Jul 19 11:53:52 leg-node4 stack_b_admin_3_1[1748]: #011at org.apache.catalina.connector.CoyoteOutputStream.flush(CoyoteOutputStream.java:110)
```

Tcpdump of the conversation between traefik and the backend shows:
![image](https://user-images.githubusercontent.com/1016317/61527253-48481300-aa1c-11e9-80f8-0bf223571727.png)
![image](https://user-images.githubusercontent.com/1016317/61527267-50a04e00-aa1c-11e9-8dec-13bb343ba1af.png)

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
