### ISSUE TITLE
Changeable dashboard port

### ISSUE THREAD

**Issue by TheSpixxyQ** [containous/traefik#5142]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I'd like to change dashboard port internally, not just endpoint. 
Why? I'm using Traefik in docker with network_mode set to host so I can listen to any port I want. But now I have another service running on port 8080 and I cannot have these two simultaneously, it gives me error this port is already in use.

I think it may be configurable in traefik.toml, like
```
[api]
  port = 8081
```

or something like that. I don't know if it is as simple as it looks like, but I would really appreciate this option

**Comment by ldez** [comment]
Take a look here https://docs.traefik.io/v1.7/configuration/api/#address-port

**Comment by TheSpixxyQ** [comment]
Sorry, I didn't mention that I'm using experimental latest version because of certificatesResolvers

**Comment by ldez** [comment]
Then take a look here https://github.com/containous/traefik/pull/5119

**Comment by MartinBecker** [comment]
As an addition (as it is not currently documented): The Dashboard Port can be changed by setting the traefik endpoint.

```
[API]
  Dashboard = true

[entryPoints]
  [entryPoints.traefik]
    address = ":9090"
```

(This will start Dashboard on Port 9090)

**Comment by ldez** [comment]
it's documented https://docs.traefik.io/v1.7/configuration/api/#address-port

**Comment by dduportal** [comment]
In addition, with the release of the new version 2.0, you can find this information here: https://docs.traefik.io/operations/dashboard/#enabling-the-dashboard .

Closing as it's not a challenge anymore with the 2.0.0 release.
