### ISSUE TITLE
Upgrade go-acme/lego to 2.7.1

### ISSUE THREAD

**Issue by dabeck** [containous/traefik#5165]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [ ] No

### What did you do?

As our Let's Encrypt Certificate expired I investigated that there is a problem with the DNS-Challenge provider we use.

### What did you expect to see?

A proper DNS-Challenge 

### What did you see instead?

An error while talking to the DNS provider

### Output of `traefik version`: 1.7.12

```
time="2019-07-29T06:57:44Z" level=error msg="Error renewing certificate from LE: {*.sub.domain.com []}, acme: Error -> One or more domains had a problem:\n[*.sub.domain.com] [*.sub.domain.com] acme: error presenting token: otc: unable to get zone: Get https://dns.eu-de.otc.t-systems.com/v2/zones?name=sub.domain.com.: net/http: request canceled (Client.Timeout exceeded while awaiting headers)\n"
```

### Suggestion

As this problem has already been addressed in acme-lego (https://github.com/go-acme/lego/issues/902) I would appreciate an upgrade to version v2.7.1

**Comment by traefiker** [comment]
Closed by #5166.
