### ISSUE TITLE
Add a provider for Key Value (KV) Store in Traefik v2

### ISSUE THREAD

**Issue by SantoDE** [containous/traefik#5169]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Traefik v1 supports dynamic config generation for and from a Key Value Store, i.e. it has a kv provider.

Now that the main changes for v2 are out, we can re-add previously supported providers, such as the one for Key Value Stores.

The existing providers, can be used for inspiration.

**Comment by lokeshpeta** [comment]
when can we expect this feature?

**Comment by bradjones1** [comment]
See https://github.com/containous/traefik/issues/5426

**Comment by lokeshpeta** [comment]
Oh good. Thanks very much.

**Comment by dduportal** [comment]
Hi @bradjones1 @lokeshpeta , for information, Traefik v2.0 only drops the "HA" part as explained in #5426 
But the provider "KV", which allows dynamic configuration of Traefik to be stored in KV systems as etcd, consul, etc. is still an upcoming feature.
