### ISSUE TITLE
Automatically add DNS entries to cloudflare

### ISSUE THREAD

**Issue by fredlahde** [containous/traefik#5175]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Cloudflare (execpt for their Enterprise Plan) does not allow routing wildcard DNS records over their infrastructure, and thus you do not get DDOS protection and so on. While Traefik's DNS Acme challenge works flawlessly with Cloudflare, you have to disable DDOS protection.

My idea is, since Traefik knows when Ingresses come and go in Kubernetes (and in a similar manner also in Docker Swarm), couldn't we add a feature to make a REST call to the Cloudflare API and add a fully qualified DNS A Record? 

That way we could use Cloudflare's DDOS protection with ease.

Is this in scope for Traefik? Would be happy to open a PR!

**Comment by dtomcej** [comment]
Hello @fredlahde,

The External-DNS project already does exactly what you want! (https://github.com/kubernetes-incubator/external-dns).

Traefik v1 is fully compatable with External-DNS, and just requires you to set the approprite `ingressEndpoint` flag in Traefik: (https://docs.traefik.io/v1.7/configuration/backends/kubernetes/#ingressendpoint)

Thanks!

**Comment by mmatur** [comment]
Hello @fredlahde,

Thanks for your interest in the project. 

I will close this issue because I think the question is answered.

**Comment by fredlahde** [comment]
Hey @dtomcej,

thanks for that quick and comprehensive response! It looks like this is exactly what I was looking for :)
