### ISSUE TITLE
When attempting to use static configuration environment variables errors are not clear

### ISSUE THREAD

**Issue by forrest-lookback** [containous/traefik#5179]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [X] No

### What did you do?

I'm experimenting with the new 2.0 beta container for Traefik using the [static configuration](https://docs.traefik.io/master/reference/static-configuration/overview/) with [environment variables](https://docs.traefik.io/master/reference/static-configuration/env/). I would like to use ECS as after reviewing https://github.com/containous/traefik/pull/4935 it seems as though it should be supported even though it is not documented, however I get `command traefik error: failed to decode configuration from environment variables: field not found, node: ecs`. I thought perhaps I misunderstood the PR, so I tried to use Kubernetes which it says is supported, but I get the same error: `command traefik error: failed to decode configuration from environment variables: field not found, node: kubernetes`, attempting to run traefik in debug mode (which is pasted below in the requested section) does not provide any additional help or details. From what I understand however you can only use flags or environment variables, so the output below may not be beneficial, so I've included the same command-line option with debug as well.

### What did you expect to see?

I expected the container to start using a default configuration for the service or to report a more detailed error regarding what fields were missing.

### What did you see instead?

Errors related to missing fields that did not provide further troubleshooting details.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.0.0-beta1
Codename:     faisselle
Go version:   go1.12.7
Built:        2019-07-19T16:04:34Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

This is using the default dockerfile that is available for V2 beta1 with a declaration of an environment variable for testing:

```
FROM alpine:3.9
RUN apk --no-cache add ca-certificates tzdata
RUN set -ex; \
	apkArch="$(apk --print-arch)"; \
	case "$apkArch" in \
		armhf) arch='armv6' ;; \
		aarch64) arch='arm64' ;; \
		x86_64) arch='amd64' ;; \
		*) echo >&2 "error: unsupported architecture: $apkArch"; exit 1 ;; \
	esac; \
	wget --quiet -O /tmp/traefik.tar.gz "https://github.com/containous/traefik/releases/download/v2.0.0-beta1/traefik_v2.0.0-beta1_linux_$arch.tar.gz"; \
	tar xzvf /tmp/traefik.tar.gz -C /usr/local/bin traefik; \
	rm -f /tmp/traefik.tar.gz; \
	chmod +x /usr/local/bin/traefik

ENV TRAEFIK_PROVIDERS_KUBERNETES true
COPY entrypoint.sh /
EXPOSE 80
ENTRYPOINT ["/entrypoint.sh"]
CMD ["traefik"]

# Metadata
LABEL org.opencontainers.image.vendor="Containous" \
      org.opencontainers.image.url="https://traefik.io" \
      org.opencontainers.image.title="Traefik" \
      org.opencontainers.image.description="A modern reverse-proxy" \
      org.opencontainers.image.version="v2.0.0-beta1" \
			org.opencontainers.image.documentation="https://docs.traefik.io"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

Debug with env variable:
```
time="2019-08-06T18:27:22Z" level=info msg="Configuration loaded from flags."
time="2019-08-06T18:27:22Z" level=info msg="Traefik version 2.0.0-beta1 built on 2019-07-19T16:04:34Z"
time="2019-08-06T18:27:22Z" level=debug msg="Static configuration loaded {\"global\":{\"checkNewVersion\":true},\"serversTransport\":{\"maxIdleConnsPerHost\":200},\"entryPoints\":{\"http\":{\"address\":\":80\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{}}},\"providers\":{\"providersThrottleDuration\":2000000000},\"log\":{\"level\":\"DEBUG\",\"format\":\"common\"}}"
time="2019-08-06T18:27:22Z" level=error msg="\nYou haven't specified the sendAnonymousUsage option, it will be enabled by default.\n"
time="2019-08-06T18:27:22Z" level=info msg="\nStats collection is enabled.\nMany thanks for contributing to Traefik's improvement by allowing us to receive anonymous information from your configuration.\nHelp us improve Traefik by leaving this feature on :)\nMore details on: https://docs.traefik.io/basics/#collected-data\n"
time="2019-08-06T18:27:22Z" level=debug msg="No default certificate, generating one"
time="2019-08-06T18:27:22Z" level=info msg="Starting provider aggregator.ProviderAggregator {}"
time="2019-08-06T18:27:22Z" level=debug msg="Start TCP Server" entryPointName=http
```

Debug running command directly with env variable scrubbed from dockerfile and container rebuilt:
```
docker run 0659 --providers.kubernetes true --log.level=DEBUG
2019/08/06 18:31:40 command traefik error: failed to decode configuration from flags: field not found, node: kubernetes
```

Setting the environment variable on the command line instead of the dockerfile:
```
docker run -e TRAEFIK_PROVIDERS_KUBERNETES=true -e TRAEFIK_LOG_LEVEL=DEBUG 0659
2019/08/06 18:54:48 command traefik error: failed to decode configuration from environment variables: field not found, node: kubernetes
```

**Comment by ldez** [comment]
Hello,

the current v2.0.0-beta1 supports:
- Docker
- Kubernetes (ingress and ingressRoute)
- Rancher
- Marathon
- File

You can find this list in the documentation: https://docs.traefik.io/v2.0/providers/overview/

```
command traefik error: failed to decode configuration from environment variables: field not found, node: ecs.
```
It's because ECS is not supported then the option is not supported.

```
command traefik error: failed to decode configuration from environment variables: field not found, node: kubernetes
```

It's because `TRAEFIK_PROVIDERS_KUBERNETES` is not an valid option, it's `TRAEFIK_PROVIDERS_KUBERNETESINGRESS`

You can find all the available env vars here: https://docs.traefik.io/v2.0/reference/static-configuration/env/

**Comment by forrest-lookback** [comment]
@ldez 

Ahh I see. I did look at the overview but since `TRAEFIK_PROVIDERS_KUBERNETES` is part of the [environment variables](https://docs.traefik.io/master/reference/static-configuration/env/):
![Screen Shot 2019-08-06 at 12 18 13 ](https://user-images.githubusercontent.com/44782113/62570520-8a5abc80-b844-11e9-8fd8-5d06fa1adcd1.png)

I thought it just hadn't been documented yet. Thanks for clearing that up, looking forward to when these providers are in.

**Comment by ldez** [comment]
FYI master is late compared to beta1.

So k8s in already available but with the name `kubernetesingress`

https://github.com/containous/traefik/pull/5180
