### ISSUE TITLE
Traffic 2.0 misses defaultEntrypoints

### ISSUE THREAD

**Issue by apollo13** [containous/traefik#5184]
It would be great if it were possible to set `defaultEntryPoints`. Maybe a global option as well as per-provider?

**Comment by ldez** [comment]
in the v2 the default entry points system is different from the v1: by default all existing entry points are used as default for the router, if you can want to use only some entry points on a router you have to define them on the router.

**Comment by apollo13** [comment]
This is weird, when I tried it with the docker service discover it always bound to the `traefik` entrypoint, have to double check

**Comment by apollo13** [comment]
Ok, I have just checked and the service is indeed reachable via all entrypoints, but the logs are somewhat confusing:

```
time="2019-08-08T13:52:22+02:00" level=debug msg="Configuration received from provider docker: {\"http\":{\"routers\":{\"whoami\":{\"service\":\"whoami_docker\",\"rule\":\"Host(`docker.bap.co.at`)\",\"tls\":{}}},\"services\":{\"whoami_docker\":{\"loadBalancer\":{\"servers\":[{\"url\":\"http://172.23.0.2:80\"}],\"passHostHeader\":true}}}},\"tcp\":{}}" providerName=docker
time="2019-08-08T13:52:22+02:00" level=debug msg="Creating middleware" entryPointName=https routerName=whoami@docker serviceName=whoami_docker middlewareName=pipelining middlewareType=Pipelining
time="2019-08-08T13:52:22+02:00" level=debug msg="Creating load-balancer" entryPointName=https routerName=whoami@docker serviceName=whoami_docker
time="2019-08-08T13:52:22+02:00" level=debug msg="Creating server 0 http://172.23.0.2:80" routerName=whoami@docker serviceName=whoami_docker serverName=0 entryPointName=https
time="2019-08-08T13:52:22+02:00" level=debug msg="Added outgoing tracing middleware whoami_docker" entryPointName=https routerName=whoami@docker middlewareName=tracing middlewareType=TracingForwarder
time="2019-08-08T13:52:22+02:00" level=debug msg="Creating middleware" middlewareName=traefik-internal-recovery middlewareType=Recovery entryPointName=https
time="2019-08-08T13:52:22+02:00" level=debug msg="Creating middleware" entryPointName=traefik middlewareName=traefik-internal-recovery middlewareType=Recovery
time="2019-08-08T13:52:22+02:00" level=debug msg="Creating middleware" entryPointName=http middlewareName=traefik-internal-recovery middlewareType=Recovery
```

From the looks of it tje middleware etc are all scoped to the https entrypoint?

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
