### ISSUE TITLE
Forward auth exceptions for sub-directory domains

### ISSUE THREAD

**Issue by hwwilliams** [containous/traefik#5188]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

It would be useful to have forward authentication server for the main domain/subdomain but also allow access to a sub-directory domain (https://example.domain.com/api) without forward authentication for an api.

```
traefik.frontend.rule: 'Host:example.domain.com'
traefik.frontend.auth.forward.address: 'http://oauth/'
traefik.frontend.auth.forward.address.exception: '/api'
```

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by dduportal** [comment]
Hi @hwwilliams , after opening the topic on the forum, you might want to look at creating 2 frontends :)

**Comment by hwwilliams** [comment]
I hadn't thought of trying to setup two frontends for it since I'm using docker as a backend but after a few tries I can't seem to get it to work so I'll move to the forums.

Thanks.
