### ISSUE TITLE
Binding outgoing ip/interface to a backend

### ISSUE THREAD

**Issue by akuscu-smartpulse** [containous/traefik#5189]
I am using haproxy for a reverse proxy.But i tested and realized that traefik is much more efficent and fast.But in my case there is remote server and there are multiple network cards.In haproxy i can manage outgoing traffic.So i can tell my backends to go via this network  card.Config in  haproxy  is below:
  server server1 192.168.15.39:3000 source 192.168.15.142 maxconn 4 check
  server server2 192.168.15.39:3000 source 192.168.15.143 maxconn 4 check
here my remote server is 192.168.15.39:3000 
my first network card's ip is 192.168.15.142
my second network card's ip is 192.168.15.142
So this proxy doing a load balancing between network cards.
How can i achieve this in traefik ?

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
