### ISSUE TITLE
ACME/Cloudflare can't request cert for subdomains

### ISSUE THREAD

**Issue by chocolat2000** [containous/traefik#5190]
### Do you want to request a *feature* or report a *bug*?
bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [X] No

### What did you do?

Create an Kubernetes ingress with host : my.sub.domain.tld
### What did you expect to see?

A cert for my.sub.domain.tld created with DNS-01 challenge with Cloudflare

### What did you see instead?

Error when creating challenge :
```" level=error msg="Error getting ACME certificates [my.sub.domain.tld] : cannot obtain certificates: acme: Error -> One or more domains had a problem:\n[my.sub.domain.tld] [my.sub.domain.tld] acme: error presenting token: cloudflare: failed to find zone sub.domain.tld.: Zone could not be found\n"```

Of course root domain domain.tld is a valid domain at Cloudflare's account.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
traefik:1.7.12
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

k8s Ingress :
```toml
  - host: my.sub.domain.tld
    http:
      paths:
      - backend:
          serviceName: my-service
          servicePort: https
```

### If applicable, please paste the log output at DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
