### ISSUE TITLE
I access my service through traefik when the service rolling update in kubernetes

### ISSUE THREAD

**Issue by lijunyong** [containous/traefik#5193]
I deploy a service in kubernetes, it has two replicas. I access my service through NodePort when the service rolling update, it success, don't throw exception. but I access my service through traefik when the service rolling update, it throw exception,After a few seconds it normal.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
