### ISSUE TITLE
Specify root certificate for use with ACME

### ISSUE THREAD

**Issue by mmalone** [containous/traefik#5196]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I work on [an open source internal certificate authority](https://github.com/smallstep/certificates) and we're about to release ACME support. We'd like to integrate with Traefik, which should be easy given its integrated ACME client.

In general, I've found that getting an existing ACME client to connect to an ACME server that's not Let's Encrypt requires two steps:

1. Point the client at the server's ACME directory URL, and
2. Tell the client to trust the root certificate of the CA that issued the ACME server's certificate

Note that the second step is only necessary if the relevant root certificate is not already trusted by default (i.e., its certificate isn't in the default system trust store). For example, this step is not necessary for Let's Encrypt's staging server because that server uses a certificate issued by (non-staging) Let's Encrypt. However, an internal ACME server is likely to use a certificate issued by an internal CA. In that case, the internal CA's root certificate likely *isn't* in the system's trust store and *won't* be trusted by Traefik by default.

With Traefik, the `caServer` directive takes care of the first part. But there doesn't appear to be any way to configure the root certificate(s) that Traefik trusts when it speaks to the ACME server using HTTPS. You can install the necessary root certificate in your system's trust store, but that's a global operation that will affect most TLS communication on the machine. There are lots of situations where that's not desirable.

It would be great if there was a directive to specify which root certificate(s) should be trusted when Traefik connects to an ACME server. This would allow Traefik to manage internal mTLS certificates more effectively, and would be useful in development and other pre-production environments.

**Comment by ldez** [comment]
Hello,
you can use `LEGO_CA_CERTIFICATES` and `LEGO_CA_SERVER_NAME` to specify your CA.

https://github.com/go-acme/lego/blob/bc4b57accc090b9c61bde051c99fcb14e952f6e6/lego/client_config.go#L18-L28

**Comment by mmalone** [comment]
Oh nice! That seems to work! Is this an endorsed solution though, or more of a workaround? Seems like the sort of thing that might go away without warning..?

**Comment by ldez** [comment]
I will speak as a lego maintainer: this feature will not go away at all, it's a requirement to allow to use []
