### ISSUE TITLE
blacklist & multiple redirect

### ISSUE THREAD

**Issue by jianzzz** [containous/traefik#5198]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Refer to [#4454](https://github.com/containous/traefik/pull/4454) and [#987](https://github.com/containous/traefik/issues/987), is this the final word that traefik will never support ip/path blacklist, as well as multiple redirect-regex.

**Comment by jianzzz** [comment]
> > We want to keep the IP filtering section as simple as possible and we think that your use case could be addressed differently.
> > We think that a blacklisting task can be better achieved using a firewall.
> > So, for now, and I insist on the "for now", we will decline your pull request.
> 
> [#4454 (comment)](https://github.com/containous/traefik/pull/4454#issuecomment-460298115)

What about multiple redirect in one ingress?

**Comment by dduportal** [comment]
Hi @jianzzz , about the redirects in Traefik, the upcoming v2.0 is currently worked on.
Stay tuned on this (for watching work, please check the v2 project board here: <https://github.com/containous/traefik/projects/3?card_filter_query=redirect>)
