### ISSUE TITLE
HTTP/2 Denial of Service

### ISSUE THREAD

**Issue by codestation** [containous/traefik#5200]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [X] No

### What did you do?

Netflix has published an [advisory](https://github.com/Netflix/security-bulletins/blob/master/advisories/third-party/2019-002.md) about multiple vulnerabilities on HTTP/2 that causes various denials of service. Go has already published an updated version (1.12.8) that addresses those vulnerabilities.

Note that this version introduces an [incompatibility](https://github.com/golang/go/commit/3226f2d492963d361af9dfc6714ef141ba606713) with the URL parser. Caddy addresed this on their [update](https://github.com/caddyserver/caddy/commit/914f39d78461c410730920fed749d8ad09cdb6ea) today,  not sure is this applies to Traefik too.

Traefik needs to be recompiled with Go 1.12.8 and optionally address the url.Parse incompatibility.

**Comment by traefiker** [comment]
Closed by #5201.
