### ISSUE TITLE
Websocket request cannot find backend

### ISSUE THREAD

**Issue by llacroix** [containous/traefik#5202]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

Tried to use rocketchat behind traefik in a docker setup using swarm mode behind an nginx proxy. I tried to create a config like this in docker both http and websocket are technically on the same endpoint...

    traefik.enable=true
    traefik.protocol=http
    traefik.frontend.rule=Host:some.host
    traefik.docker.network=mynet
    traefik.port=8069

Then:

    traefik.enable=true
    traefik.basic.protocol=http
    traefik.frontend.rule=Host:some.host
    traefik.docker.network=mynet
    traefik.port=8069
    traefik.wss.protocol=ws

Nginx config 

```
    proxy_read_timeout 720s;
    proxy_connect_timeout 720s;
    proxy_send_timeout 720s;

    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Real-IP $remote_addr;

    # Pass hsot necessary for multi proxy
    proxy_set_header Host $host;

    location ~ ^/(.*)/websocket$ {
        rewrite ^/(.*)/websocket$ /$1/websocket break;
        proxy_pass http://127.0.0.1:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Sec-WebSocket-Protocol $http_sec_websocket_protocol;
        proxy_set_header Sec-WebSocket-Key $http_sec_websocket_key;
        proxy_set_header Sec-WebSocket-Version $http_sec_websocket_version;
        proxy_set_header Cookie $http_cookie;
        proxy_redirect off;
    }
```

### What did you expect to see?

I expect traefik to actually find the backend as the host matches and the port is the same. There's literally nothing different between http and websocket frontend except the headers being passed but technically those are all proxied through nginx and traefik doesn't care about them for finding the right route.

### What did you see instead?

    proxy.1.q8q2ykk4dj2v@node3    | 10.255.x.x - - [14/Aug/2019:03:59:31 +0000] "GET /sockjs/499/jb2lvdhq/websocket HTTP/1.1" 404 19 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0" 1841 "backend not found" "/sockjs/499/jb2lvdhq/websocket" 0ms

It seems traefik isn't capable of finding the right host.

### Output of `traefik version`: (_What version of Traefik are you using?_)

I couldn't print the output as traefik version didn't return anything but the image is this one traefik:1.7.13-alpine 

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```
debug = false
logLevel = "INFO"
# defaultEntryPoints = ["https", "http"]
defaultEntryPoints = ["http"]

[accessLog]

[entryPoints]
  [entryPoints.http]
      address = ":8080"

  [entryPoints.traefik]
      address = ":9090"
      [entryPoints.traefik.auth.basic]
          users = [
            "admin:$apr1$XGLig54t$JqypuiDn5YErDwKxb29qK/"
          ]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "proxy"
watch = true
exposedByDefault = false
swarmMode = true

[api]
entrypoint="traefik"

```

**Comment by llacroix** [comment]
I saw an other issue regarding the Sec-Websocket header being stripped could this be related?

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
