### ISSUE TITLE
signalr 

### ISSUE THREAD

**Issue by 93Kamuran** [containous/traefik#5205]
I have a docker swarm with 3 nodes. In windows, node ı have an aspnet web API Project that works in Microsoft/IIS based image. Normally when ı work on IIS my projects works fine. However to put them into. docker swarm. my signalR has broken. I use signalR on the server-side for send data to client-side then I have code like this

            var hubConnection = new HubConnection("http://api.mydomain.com");
            IHubProxy stockTickerHubProxy = hubConnection.CreateHubProxy("MyHub");
          
            await hubConnection.Start(new LongPollingTransport());

            stockTickerHubProxy.Invoke("RefreshData", ID); 
I use Traefik for proxy and using let's encrypt SSL certificates. Normally when this on IIS, the hub could create the connection with subdomain and stars the connection.

But now ı m having an issue like this

"A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond MYmasterNodeIp:433"(this is my master node's IP address it's a Linux VM and Traefik is on the master node for forwarding request to the services ).

I tried lots of things but I couldn't achieve to connect signalR with my API. Everything works perfectly except signalR hub connection on my services. Can anyone help me?

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
