### ISSUE TITLE
Provider a docker image with tag v1

### ISSUE THREAD

**Issue by Yivan** [containous/traefik#5213]
Hello,

Docker images of traefik provide tag "v1.7" but not "v1".
Please see https://hub.docker.com/_/traefik

It would be nice to have a tag "v1" so we can update it easily and stay on the v1 all long.
Using "latest" as tag could make a problem when v2 will arrive.

Thanks.

**Comment by dtomcej** [comment]
Hello @Yivan.

The 1.7 release will be the last v1 minor release, and there will not be a 1.8.

You can use the 1.7 tag once v2 arrives, as it will still continue to receive bugfixes.

**Comment by Yivan** [comment]
Ok great, thanks for your fast answer!
