### ISSUE TITLE
Add Yandex DNS provider for Let's Encrypt DNS-01 challenge

### ISSUE THREAD

**Issue by Akkarine** [containous/traefik#5215]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Easy way to get wildcard certificates for domains delegated on Yandex DNS.

### References:

Yandex API:
* https://tech.yandex.com/domain/doc/reference/dns-add-docpage/

Projects with implemented API:
* https://github.com/AnalogJ/lexicon/tree/v3.2.7  
* https://github.com/actionm/certbot-dns-pddyandex

**Comment by ldez** [comment]
Hello,

Traefik uses [lego](https://github.com/go-acme/lego) for the ACME features.

Could you open an issue on [lego](https://github.com/go-acme/lego/issues) ?

Take a look here https://github.com/go-acme/lego/pull/278

Thanks for your time.
