### ISSUE TITLE
reference issues/2944 Stil getting 404 when using PUT for providers update with API

### ISSUE THREAD

**Issue by meedel** [containous/traefik#5220]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [X] No

### What did you do?
I try to update the provider to use the REST API

### What did you expect to see?

I want to get an update on the provider docker.

### What did you see instead?

I get an 404 page not found.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
1.7.12
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```API call from client
# (paste your configuration here)
curl -u admin:xxxxxx -XPUT -d input.json "http://'hostname':8080/api/providers/docker"
404 page not found

The command curl -u  admin:xxxxxx http://'hostname':8080/api/providers/docker gives the output of the fontends and backends

```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```

**Comment by meedel** [comment]
I followed the instruction on https://docs.traefik.io/configuration/backends/rest/

**Comment by ldez** [comment]
Hello,

The REST provider allow to manage only the provider `rest` as suggested in the [documentation](https://docs.traefik.io/v.7/configuration/backends/rest/#api).

That means that you cannot use the REST provider to modify the data of the other providers (docker, ...)

**Comment by meedel** [comment]
Ok. thanks for your quick reply.

Is that deliberately programmed that way, or will it be expanded?

**Comment by dduportal** [comment]
Hi @meedel , it is the expected behavior, as the docker provider is dynamically filed by watching the Docker API, and it's not expected to be manually managed.

Please note that you can totally enable multiple provider: Docker for automatically route to your docker containers, and still add more routing with the rest of file providers.
