### ISSUE TITLE
Traefik v2 - Loading mixed active content blocked

### ISSUE THREAD

**Issue by zandercodes** [containous/traefik#5223]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [X] No

### What did you do?
I loaded my website via https.
Contents like css js etc. are not loaded over https despite forwarding to https from this issue [#4688](https://github.com/containous/traefik/issues/4688)

### What did you expect to see?
That my website is displayed with css and js etc.

### What did you see instead?
My website without css and js etc.

Anybody got an idea?

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
