### ISSUE TITLE
More detailed metrics for DataDog

### ISSUE THREAD

**Issue by eli-betito** [containous/traefik#5227]
It would be great if **Traefik** could provide and add more information about **traefik.backend.request.*** metrics for DataDog or any other monitoring tools.

Could you explain to me what is the difference between these metrics:

- traefik.backend.request.duration.count
- traefik.backend.request.duration.avg
- traefik.backend.request.total

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
