### ISSUE TITLE
Docker Backend not refreshing when there are new containers launched or killed

### ISSUE THREAD

**Issue by tachu** [containous/traefik#523]
I'm using traefik version 1.0 under amazon ECS starting up the container works as expected it gets the configuration from the docker socket and setups backends and frontends. but when I kill one of my backend containers the configuration does not get updated. I have the watch option enabled and I see traefik calling the events api on docker on startup. I've opened a connection to the docker socket as well in the events api and I do see the notifications of changes for start and kill of the other containers so i'm not sure why traeffik is not seeing it.

**Comment by errm** [comment]
Could you please set logLevel to DEBUG and post the logs?

**Comment by emilevauge** [comment]
Traefik doesn't work on ECS for now. Their API is not compliant with Docker.

**Comment by Poeschl** [comment]
Is it still this way or is it now working with version 1.1.2?

**Comment by ldez** [comment]
I'll close the issue due to inactivity but feel free to re-open if needed.
