### ISSUE TITLE
Stop using your own inferior forum

### ISSUE THREAD

**Issue by remotezygote** [containous/traefik#5239]
I've already elaborated on this in the comments here: https://github.com/containous/traefik/issues/5135

You'll have to unhide those comments to see anything, of course.

Google doesn't index your forum.
Your forum's search sucks.
You refuse to provide support on GitHub.

We actually do need support, and you're not giving it.

**Comment by ldez** [comment]
We choose to use GitHub issues only for bugs and features, like many others large projects.

We give support on our recently created [forum](https://community.containo.us/), like many others large projects.

In agreement with [our code of conduct](https://github.com/containous/traefik/blob/master/CODE_OF_CONDUCT.md) I will close this issue.
