### ISSUE TITLE
Docker Provider: backend load balancing methods

### ISSUE THREAD

**Issue by tbouvet** [containous/traefik#525]
Just a question please : is it possible to put the load balancing method with docker swarm configuration ?

I just want to use the **drr** method instead of **wrr**.

I try with traefik v1.0.0 and I have a warning when traefik start for each backend :

```
Error loading load balancer method '<nil>' for backend backend-xxx: Invalid method, using default. Using default wrr.
```

So can I put these informations in my container labels ?

**Comment by AlmogBaku** [comment]
facing the same issue with kubernetes provider

**Comment by lvnilesh** [comment]
I just found this `traefik.backend.loadbalancer.method=drr` while browsing the doc https://docs.traefik.io/toml/#docker-backend.

Is this the right solution?

**Comment by timothyallan** [comment]
Works for me @lvnilesh

**Comment by dcrystalj** [comment]
does anyone know what drr or wrr means?  i guess `d`rr is for docker but then what is  `w`??

**Comment by timoreimann** [comment]
wrr = weighted round-robin 
drr = dynamic round-robin

**Comment by ldez** [comment]
I'll close this issue, because I think the question is answered, but feel free to continue the conversation.
