### ISSUE TITLE
[question] Traefik for external resources?

### ISSUE THREAD

**Issue by giopas** [containous/traefik#526]
Hi,

I have recently discovered this project (which has been quickly packaged for QNAP NAS[1]) and I wonder to know if it would be possible to use Traefik to connect to external resources (e.g. an external https website or the webinterface of a security camera).

I have set many reverse proxies on apache and I am considering now to move to Traefik as it seems more straight forward.

Thanks,

giopas

ps: sorry I did not find a mailing list or forum where to submit this question.

[1] http://www.forum-nas.fr/viewtopic.php?f=21&t=4791

**Comment by morvans** [comment]
Using the File backend (https://docs.traefik.io/toml/#file-backend) should for this use case.

**Comment by ldez** [comment]
I'll close the issue due to inactivity but feel free to re-open if needed.
