### ISSUE TITLE
Adds support for zipkin v2

### ISSUE THREAD

**Issue by jcchavezs** [containous/traefik#5260]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Currently Traefik only supports zipkin v1 by using [zipkin-go-opentracing v0.3.x](https://github.com/containous/traefik/blob/89150e1164b1422386824fc883e66bec405dbb12/go.mod#L71). This is because it uses the old version of `zipkin-go-opentracing` which only supported v1 reporting. [Version 0.4.2 of zipkin-go-opentracing uses zipkin v2 format](https://github.com/openzipkin-contrib/zipkin-go-opentracing/releases/tag/v0.4.0) which is smaller and the default reporting format ([read this to understand how v2 is better than v1](https://github.com/openzipkin/zipkin/releases/tag/2.10.1)).

We have two options here:
1. We move to new version of zipkin-go-opentracing and reports in v2 format, meaning that users will need to change their reporter URL from `:host/api/v1/spans` into `:host/api/v2/spans`. Feels like a breaking change but there is nothing else users will need to do.
2. We maintain both versions of zipkin-go-opentracing, this is weird because basically we might need to maintain both versions of zipkin-go-opentracing: 0.3 for v1 and 0.4 for v2 but `go modules` support that. This will require for us to find a way in [configuration](https://docs.traefik.io/configuration/tracing/#zipkin) to determine if v1 or v2, it can be another parameter but then it feels odd as the `httpEndpoint` is different depending on `v1` or `v2`. 

Personally I would go for **1** but I would like to hear other's opinion. I am happy to come up with a PR for this.

Ping @adriancole @basvanbeek

**Comment by jbdoumenjou** [comment]
Hi @jcchavezs,

It doesn't seem possible to use go modules to keep both versions of zipkin-go-opentracing, unless  you have specific idea.
Anyway, we think it is reasonable to migrate to the V2 version and stop the support of the v1.

**Comment by basvanbeek** [comment]
That is correct. You need to either pick a V1 old style release < 0.4.0 or pick a v2 bridge release 0.4.x.
The 0.4.3 release is the best minimum release to start from.

**Comment by jcchavezs** [comment]
Interesting. I thought we could do it as explained in here for example: https://www.melvinvivas.com/go-version-1-11-modules/ but I haven't done it yet. My specific idea was to create another package for zipkin-v2 and decide accordingly to config, **however** I am really happy we can just migrate to the new version. I will see if I can work on that today.

**Comment by ldez** [comment]
To use 2 versions, the 2 versions must be 2 different major versions (semver) and v0 is not evaluate as different as v1.

**Comment by traefiker** [comment]
Closed by #5283.
