### ISSUE TITLE
docker run syntax in swarm example has changed

### ISSUE THREAD

**Issue by batwicket** [containous/traefik#528]
The Swarm example at https://docs.traefik.io/user-guide/swarm/ works for me with Docker 1.12.0-rc3 after i change:

docker $(docker-machine config mhs-demo0) run \
    -d \
    -p 80:80 -p 8080:8080 \
    --net=my-net \
    -v /var/lib/boot2docker/:/ssl \
    traefik \
    -l DEBUG \
    -c /dev/null \
    --docker \
    --docker.domain traefik \
    --docker.endpoint tcp://$(docker-machine ip mhs-demo0):3376 \
    --docker.tls \
    --docker.tls.ca /ssl/ca.pem \
    --docker.tls.cert /ssl/server.pem \
    --docker.tls.key /ssl/server-key.pem \
    --docker.tls.insecureSkipVerify \
    --docker.watch  \
    --web

to:

docker $(docker-machine config mhs-demo0) run \
    -d \
    -p 80:80 -p 8080:8080 \
    --net=my-net \
    -v /var/lib/boot2docker/:/ssl \
    traefik \
    -l DEBUG \
    -c /dev/null \
    --docker \
    --docker.domain=traefik \
    --docker.endpoint=tcp://$(docker-machine ip mhs-demo0):3376 \
    --docker.tls \
    --docker.tls.ca=/ssl/ca.pem \
    --docker.tls.cert=/ssl/server.pem \
    --docker.tls.key=/ssl/server-key.pem \
    --docker.tls.insecureSkipVerify \
    --docker.watch  \
    --web

**Comment by billglover** [comment]
I have been able to replicate this issue. Will have a crack at addressing this now.

**Comment by emilevauge** [comment]
Fixed by #707
