### ISSUE TITLE
Omit private key from acme logs

### ISSUE THREAD

**Issue by ddtmachado** [containous/traefik#5284]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [X] No

### What did you do?

Try to load an incomplete/invalid private key to acme configuration

### What did you expect to see?

An error during marshall 

### What did you see instead?

An error during marshall with the private key included

### Output of `traefik version`: (_What version of Traefik are you using?_)

1.7.14

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Ubuntu 18.04.1
TraefikEE v1.1.9
Kubernetes

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
{"level":"info","msg":"Testing certificate 
renew...","time":"2019-08-30T11:42:37Z"} 
{"level":"error","msg":"Cannot unmarshal private key 
[MY_PRIVATE_KEY]","time":"2019-08-30T11:42:37Z"} 
```
Reference to the code:

https://github.com/containous/traefik/blob/4cae8bcb104a515d32c6174687ac0624bb047908/acme/account.go#L109-L116

**Comment by traefiker** [comment]
Closed by #5941.
