### ISSUE TITLE
[HELP] Can I setup traefik with 2 different domains?

### ISSUE THREAD

**Issue by MiguelNdeCarvalho** [containous/traefik#5303]
Hey,
Basically I have been using ´nginx´ for reverse proxy stuff since I started needing it. Now I am try to find a way to come to ´traefik´. I have a noob question and it is: Can I add 2 different domains?
I wanted to setup a gerrit docker with a ´abc.com domain´ but all the other containers with ´cba.com domain´.
Thanks,
Miguel de Carvalho

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
