### ISSUE TITLE
Traefik v2 ping configuration doesn't work

### ISSUE THREAD

**Issue by dahu33** [containous/traefik#5326]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [X] No

### What did you do?

Followed the documentation to configure the /ping health-check URL: https://docs.traefik.io/v2.0/operations/ping/

### What did you expect to see?

I was expecting to have Traefik starting, and be able to access the /ping URL.

### What did you see instead?

Traefik refused to start with the following output: `command traefik error: field not found, node: entryPoint`

NOTE: after removing the `entryPoint = "ping"` node from the `[ping]` section, traefik started but I was still unable to access /ping (it would return an error 404).

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.0.0-rc2
Codename:     montdor
Go version:   go1.13rc2
Built:        2019-09-03T20:10:11Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[entryPoints]
  [entryPoints.ping]
    address = ":8082"

[ping]
  entryPoint = "ping"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```

**Comment by ldez** [comment]
hello,

with the RC2 it's not possible to define entry point.

This will be possible in the next release.

**Comment by dahu33** [comment]
> This will be possible in the next release.

Thanks. By next release you mean RC3/2.0.0 or a version beyond 2.0.0?
