### ISSUE TITLE
Traefik not detecting failed node containers in swarm

### ISSUE THREAD

**Issue by sronsiek** [containous/traefik#533]
docker v1.11.2
swarm v1.2.3
Traefik v1.0.0
Consul v0.6.4

I'm running a docker swarm on 3 physical nodes linked via a switch in a private VLAN.

Node 1 is running the following containers:
consul1, manager1 (swarm agent server), node1 (swarm join)
traefik_1
my_web_app_1, weight 0

Node 2 is running the following containers:
consul2, manager2 (swarm agent server), node2 (swarm join)
my_web_app_2, weight 100

Node 3 is running the following containers:
consul3, manager3 (swarm agent server), node3 (swarm join)
my_web_app_3, weight 0

Traefik and the 3 instances of my_web_app are all in the same docker network, and all 3 are displayed in the traefic UI as expected.
Node 2 is primary.

I now disconnect node 2 from the physical LAN (actually disabling the port on the switch).
- consul+swarm sense the node is down, node 3 is elected new primary.
- `docker -H :4000 info` no longer displays details for node2
- `docker network inspect my_docker_lan` still lists all containers, including those from node2

Traefik web-ui continues to show my_web_app on node2, it seems unaware that the node is not reachable. It did update when I launched / stopped my_web_app containers.

BTW - is it expected that there is no content under the consul tab in the traefik web-ui? Docs say this is active by default. When I set `--consul` and and endPoint, the consul tab disappears!

One last qu: Is there some documentation on how to use the config file & health checks as found here:
https://github.com/containous/traefik/blob/master/examples/whoami.json

**Comment by emilevauge** [comment]
/cc @vdemeester do you know if failover in Swarm could be managed easily ?

>BTW - is it expected that there is no content under the consul tab in the traefik web-ui? Docs say this is active by default. When I set --consul and and endPoint, the consul tab disappears!

Hum, I don't get it. Consul tab will stay empty until you put some configuration in Consul. Could you give more details ?

>One last qu: Is there some documentation on how to use the config file & health checks as found here:
https://github.com/containous/traefik/blob/master/examples/whoami.json

This is a JSON file used for Marathon, not Swarm. No health check in traefik right now (but Docker will add health checks in 1.12).

**Comment by ldez** [comment]
I'll close the issue due to inactivity but feel free to re-open if needed.
