### ISSUE TITLE
CLI parsing error

### ISSUE THREAD

**Issue by fgallese** [containous/traefik#5333]
In this guide: https://github.com/containous/traefik/edit/v2.0/docs/content/user-guides/crd-acme/index.md

I think there is a mistake, cause the flag `--certificatesresolvers.default.acme.tlschallenge` is missing the `=true` value.

At least in my test server it won´t work without that, I get this error:

`time="2019-09-09T18:21:05Z" level=error msg="Unable to obtain ACME certificate for domains \"my.domain\": cannot get ACME client ACME challenge not specified, please select TLS or HTTP or DNS Challenge" providerName=default.acme routerName=traefik/traefik-c4832920e2dbeca43c rule="Host(`my.domain`)"`

Unless I am missing something, I think this should be updated in the doc.

**Comment by ldez** [comment]
`--certificatesresolvers.default.acme.tlschallenge` is a boolean flag so you don't need to explicitly set `true`

 You need to configure the `certResolver` on the router.

https://docs.traefik.io/v2.0/routing/routers/#certresolver

**Comment by traefiker** [comment]
Closed by #5372.
