### ISSUE TITLE
v2.0.0-rc3 no matching manifest for linux/amd64

### ISSUE THREAD

**Issue by nagelm** [containous/traefik#5348]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?
docker pull traefik:v2.0
docker pull traefik:v2.0.0-rc3

### What did you expect to see?
traefik rc-3 image pulled

### What did you see instead?
Error: no matching manifest for linux/amd64 in the manifest list entries

### Output of `traefik version`: (_What version of Traefik are you using?_)
v2.0.0-rc2

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Unraid OS, docker

**Comment by ldez** [comment]
Hello,

The Official Docker Image of Traefik is built by Docker we must wait until the image is built by Docker.

https://doi-janky.infosiftr.net/job/multiarch/view/images/view/traefik/

**Comment by nagelm** [comment]
Ok thanks for the info, sorry for my impatience. I saw the release was 14 hours ago so I thought there might be some issue with the docker build.

**Comment by denysvitali** [comment]
In the meantime, you can use my image: `nanosdenys/traefik:2.0.0-rc3` :)
