### ISSUE TITLE
Add custom headers for services

### ISSUE THREAD

**Issue by denysvitali** [containous/traefik#5350]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

In v2.0, by reading the [Services documentation](https://docs.traefik.io/v2.0/routing/services/) it seems that it's only possible to add custom headers for the healt-check endpoint. My goal is to add a custom header on the service end.

My current goal is to set a custom `X-Forwarded-For` since I'm proxying the request to another proxy. Ideally an user should be able to do something like this:

```
[http.services]
  [http.services.registry.LoadBalancer]
    [[http.services.registry.LoadBalancer.servers]]
        url = "https://service-1"
        [[http.services.registry.LoadBalancer.servers.headers]]
          X-Custom-Header = "foo"
```

The server listening on `service-1:443` should then receive a request with the additional header (`X-Custom-Header`) specified in the service section.

It seems to me that maybe this feature is already implemented but not documented (or at least, I wasn't able to find it) since this use case was included for the health-check section.

**Comment by ldez** [comment]
Hello,

To add headers you have to use the middlewares `headers`: https://docs.traefik.io/v2.0/middlewares/headers/

**Comment by denysvitali** [comment]
This is indeed what I was looking for. Thank you and have a wonderful day 🚀
