### ISSUE TITLE
Version 2.0-r2 examples case insensitive in docker documentation

### ISSUE THREAD

**Issue by SrMouraSilva** [containous/traefik#5355]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

I try to use the example following in https://docs.traefik.io/v2.0/middlewares/headers/#adding-and-removing-headers

```yml
  - "traefik.http.middlewares.testheader.headers.customrequestheaders.X-Script-Name=test"
```

In the example, `customrequestheaders` are all in low case and the code doesn't works with me. When i try to use `customResponseHeaders` instead (like https://docs.traefik.io/v2.0/middlewares/headers/#customresponseheaders), works

The problem is only case insensitive documentation examples

### What did you expect to see?

Fix documentation

### What did you see instead?

Example that doesn't works

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.0.0-rc2
Codename:     montdor
Go version:   go1.13rc2
Built:        2019-09-03T20:10:11Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# (paste your configuration here)
```

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by SrMouraSilva** [comment]
There is a wrong information in the documentation, this is not a code bug, is something like documentation bug.

The mistake made me waste hours, I wish others didn't have the same problem.

**Comment by SrMouraSilva** [comment]
https://github.com/containous/traefik/issues/2832#issuecomment-364460134

**Comment by jbdoumenjou** [comment]
Hi @SrMouraSilva , 

I tried the following label (with the traefik:v2.0.0-rc2 docker image) :
```
 - traefik.http.middlewares.testheader.headers.customrequestheaders.X-Script-Name=test
```

I activated the API and I checked the configuration on localhost:8080/api/http/middlewares

And I can see the middleware created :
```
{
    "headers": {
      "customRequestHeaders": {
        "X-Script-Name": "test"
      }
    },
    "status": "enabled",
    "name": "testheader@docker",
    "provider": "docker",
    "type": "headers"
  }
```

Can you check your middlewares configuration?

**Comment by SrMouraSilva** [comment]
Hi @jbdoumenjou, 

I tried to simulate the problem and it did not occur. So I conclude that I really made some other mistake.

Thank you for your attention

**Comment by jbdoumenjou** [comment]
I am glad to see that the issue is solved.
Don't hesitate to join our forum https://community.containo.us/ to ask questions and share your experience with Traefik. :smile:
