### ISSUE TITLE
File/directory watch does not work in Docker

### ISSUE THREAD

**Issue by xmflsct** [containous/traefik#5375]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

Both file watch and directory watch do not work in my Docker setup.

I mount volume `./data` to `/etc/traefik` with `rw`. Inside this folder, I have the default `traefik.toml`.
In my `traefik.toml`, I tried to define below cases.
First case:
```
[file]
filename = "/etc/traefik/rules.toml"
watch = true
```
In this case, I place a `rules.toml` directly inside my `./data` folder right next to `traefik.toml`.
Second case:
```
[file]
directory = "/etc/traefik/rules/
watch = true
```
In this case, I place the `rules.toml` inside folder `rules` within `./data`.

Both cases do not work. 
I see in debug `level=info msg="Starting provider *file.Provider {\"Watch\":true,\"Filename\":\"/etc/traefik/rules.toml\",\"Constraints\":null,\"Trace\":false,\"TemplateVersion\":0,\"DebugLogGeneratedTemplate\":false,\"Directory\":\"\",\"TraefikFile\":\"/etc/traefik/traefik.toml\"}"` which seems to understand to read such file. But right after this line I get `level=debug msg="Configuration received from provider file: {}"`. When I live make changes to `rules.toml`, there are few logs popping up with the same `level=debug msg="Configuration received from provider file: {}"`, and nothing happens.

I have read other cases, and I don't have any `--file` in my docker-compose file.
Before generating `rules.toml`, the lines are within `traefik.toml` which worked very well.

### What did you expect to see?

File being read.

### What did you see instead?

Seems like file is not read.

### Output of `traefik version`: (_What version of Traefik are you using?_)

I have been using 1.7.14, and today updated to 1.7.15, still the same.

```
1.7.14 and 1.7.15
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
debug = true
defaultEntryPoints = ["http", "https"]

[file]
filename = "/etc/traefik/rules.toml"
watch = true

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
traefik         | time="2019-09-13T09:33:11Z" level=info msg="Starting provider configuration.ProviderAggregator {}"
traefik         | time="2019-09-13T09:33:11Z" level=info msg="Starting provider *file.Provider {\"Watch\":true,\"Filename\":\"/etc/traefik/rules.toml\",\"Constraints\":null,\"Trace\":false,\"TemplateVersion\":0,\"DebugLogGeneratedTemplate\":false,\"Directory\":\"\",\"TraefikFile\":\"/etc/traefik/traefik.toml\"}"
traefik         | time="2019-09-13T09:33:11Z" level=debug msg="Configuration received from provider file: {}"
traefik         | time="2019-09-13T09:33:21Z" level=info msg="Server configuration reloaded on :80"
traefik         | time="2019-09-13T09:33:21Z" level=info msg="Server configuration reloaded on :443"
```

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
