### ISSUE TITLE
Add additional host rules to match on

### ISSUE THREAD

**Issue by fredlahde** [containous/traefik#5377]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Currently Traefik looks for host entries in Ingresses, creates Certificates for them and routes traffic accordingly. 
I'd be nice, to have a way to define additional host headers to match routing on, but without creating certificates for. 

Use Case:

We have the Domain `domainA.com` as our main domain. Traefik uses this domain in the host spec and creates certificates for it. We also have the domain `domainB.com` which points with a CNAME record to `foo.domainA.com`. We added `domainB.com` as SAN in our Traefik config, TLS works already. 

Only Problem is, the `Host` header is still set to `domainB.com` and such, Traefik answers with a 404.

One could implement this with labels on an Ingress resource, to denote additional `Host` Headers to match on, but with the important distinction that Traefik will not try to create Certificates for them.

**Comment by mpl** [comment]
Hi,

Could you please provide all the information that was required in the provided template, notably the traefik version you're talking about?
Without this information, we cannot help you.

**Comment by fredlahde** [comment]
Hey, its 1.7.14, and the template for a feature request does not ask for more info

If you need more context, I'm happy to elaborate on my idea

**Comment by dduportal** [comment]
Hi @fredlahde , thanks for the feedback. Yes, can you elaborate? We are not sure to understand the problem you are facing with `Only Problem is, the Host header is still set to domainB.com and such, Traefik answers with a 404.`

Could you share a reproductible case with us please, and give us a curl request as you see the behavior and also as you would expect it to be?

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Community Forum](https://community.containo.us/).
