### ISSUE TITLE
Can I use Traefik without a domain name?

### ISSUE THREAD

**Issue by siddharthist** [containous/traefik#539]
I am a developer of [mantl](http://mantl.io/). We use Traefik in our stack, but we don't have a bunch of domain names lying around for our devs to use for testing. Is it possible to use Traefik (especially with Marathon backend) without a domain name? 

What I'd like is to be able to do something like 
```
curl http://<marathon-service>.<my-edge-node-ip>
``` 
and have it work.

One workaround is to set your domain to `example.com` and do something like
```
echo '<my-edge-node-ip> example.com' >> /etc/hosts
```
but this feels like a hack. I'd rather not require users to modify their environment because they don't own a domain name.

**Comment by emilevauge** [comment]
@siddharthist yes you can :)
For example, you can use labels defined http://docs.traefik.io/toml/#marathon-backend on an app to modify its route: `traefik.frontend.rule=PathPrefixStrip:/test` will route every requests made on `/test` to this app.
If you need that for all you applications, you can also provide a custom template, here is the default template used: https://github.com/containous/traefik/blob/master/templates/marathon.tmpl

**Comment by siddharthist** [comment]
@emilevauge Thanks for taking the time to fill me in! I'll probably make another issue when I can't figure it out :stuck_out_tongue_winking_eye:
