### ISSUE TITLE
Ratelimit on Multiple Frontend/URL

### ISSUE THREAD

**Issue by lokesh12002** [containous/traefik#5396]
Hi All,

We are using Traefik on Kubernetes as ingress controller
We would like to uptake Rate limiting capability

But not sure how to implement below scenario

We have wild card routing URLs like

ingress:
  hosts:
    - "*.identity.env12.ociqa1.c9dev1.oc9qadev.com"
    - "*.identity.uscom-central-1.env12.ociqa1.c9dev1.oc9qadev.com"

We are applying rate limiting in annotation like 

traefik.ingress.kubernetes.io/rate-limit: |
      extractorfunc: request.host
      rateset:
        tenant:
          period: 1s
          average: 100
          burst: 20

This gets applied on all the host as single value

we want to introduce custom rate limiting per host for example 
    - "*.identity.env12.ociqa1.c9dev1.oc9qadev.com"
  Rate limit of 300
 Idcs-cloudtest.identity.env12.ociqa1.c9dev1.oc9qadev.com
Reate limit of 500

I heard something rate limit per frontend

can someone provide guidance how to achieve custom rate limit wild card or 2 different rate limit are not supported

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
