### ISSUE TITLE
DockerHub push of 2.0 screwed up v1.7 example traefik-ds.yaml

### ISSUE THREAD

**Issue by errge** [containous/traefik#5398]
The `traefik-ds.yaml` at `https://raw.githubusercontent.com/containous/traefik/v1.7/examples/k8s/traefik-ds.yaml` contains this line: `- image: traefik`.

In Kubernetes this means to take the latest docker image, so the one tagged as `traefik:latest`.  Recently you guys changed this tag to point to version 2.0.0 on DockerHub.  

Therefore this line in the yaml file on the v1.7 branch has to be updated to `- image: traefik:v1.7.16`.

**Comment by traefiker** [comment]
Closed by #5399.
