### ISSUE TITLE
https redirection not using path from original url

### ISSUE THREAD

**Issue by gerbil** [containous/traefik#5406]
Hi, im using https redirect on whoami, but in my case full url is looking like this:
http://test.com/cloud/whoami/ so after https redirect its become https://test.com/whoami/ which is not correct (it should be https://test.com/cloud/whoami/)

_deploy:
      labels:
        - "traefik.http.routers.whoami.rule=PathPrefix(`/whoami`)"
        - "traefik.http.services.whoami.loadbalancer.server.port=80"
        - "traefik.http.middlewares.redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.whoami.middlewares=redirect"_

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

Issue templates help us help you by providing all necessary information.

Please edit your issue and use the available templates:

- [Feature request](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/Feature_request.md)
- [Bug report](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/Bug_report.md)

And remember: each time someone ignores the template, a cute little bunny dies.
<details>
<summary>#SaveTheCuteBunny :heart: :rabbit: :heart:</summary>

![southpark - estrella kill rabbit](https://user-images.githubusercontent.com/5674651/27143914-3cea7896-5130-11e7-81f8-02d8ac2da7a7.gif)

![southpark - estrella kill rabbit2](https://user-images.githubusercontent.com/5674651/27143924-49104c72-5130-11e7-82ae-ccedbd5dfa1c.gif)

</details>

**Comment by dduportal** [comment]
Hi @gerbil , the routing rule should be ```
- "traefik.http.routers.whoami.rule=PathPrefix(`/cloud/whoami`)"
```

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by gerbil** [comment]
Still got -> /cloud/ is nginx virtual directory for all of me services, so i wont get this in url.. 
"GET /whoami/ HTTP/1.0" 404

The only solution i got now is to strip prefix after forward:

      - "traefik.http.routers.whoami.rule=PathPrefix(`/whoami`)"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
      - "traefik.http.middlewares.whoami-fix.stripprefix.prefixes=/whoami"       
      - "traefik.http.routers.whoami.middlewares=whoami-fix"

**Comment by dduportal** [comment]
@gerbil can you please switch to the community forum.
