### ISSUE TITLE
How to migrate v1 rule to a v2 routing version?

### ISSUE THREAD

**Issue by gerbil** [containous/traefik#5408]
All my services got simple v1 working frontend rule:

_"traefik.frontend.rule=PathPrefix:/test;ReplacePathRegex: ^/test/(.*) /$$1"_

Is there any example doc describing how to migrate this rule to a v2 routing version?

I've tried _PathPrefix(`/test`)_, _PathPrefix(`/test/`)_, _PathPrefix(`/test/*`_) ... etc but all internal calls like for /test/folder/folder/script.js are not working!

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
