### ISSUE TITLE
TCP router never used. Immediate fallback to http 

### ISSUE THREAD

**Issue by svenwiltink** [containous/traefik#5420]
### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?
I am trying to forward TCP traffic to a tcp socket (super simple nc -kl 8888).

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.0.0
Codename:     montdor
Go version:   go1.13
Built:        2019-09-16T17:35:17Z
OS/Arch:      linux/amd64

```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
################################################################
# Global configuration
################################################################
[global]
  checkNewVersion = false
  sendAnonymousUsage = false

################################################################
# Entrypoints configuration
################################################################
[entrypoints]
[entrypoints.banana-entry]
      address = ":7777"
[tcp]
   [tcp.routers]
      [tcp.routers.banana-router]
         entrypoints = ["banana-entry"]
         rule = "HostSNI(`*`)" # Catches every request
         service = "banana-service"

[tcp.services]
    [tcp.services.banana-service.loadBalancer]
      [[tcp.services.banana-service.loadBalancer.servers]]
        address = "localhost:8888"


[log]
    level = "DEBUG"

[api]
    insecure = true
```

When I telnet to the port I don't connect to the banana-service. Instead I get a 400 Bad Request response, even though no http router is defined. From what I have been able to find in the documentation there is a fallback from tcp to http, which I would like to disable entirely for this entrypoint. 

The output of telnet:
```
telnet localhost 7777
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
asfd
HTTP/1.1 400 Bad Request
Content-Type: text/plain; charset=utf-8
Connection: close

400 Bad RequestConnection closed by foreign host.
```

Log:
```
traefik --configFile=/home/swiltink/code/traefik-playground/traefik.toml
INFO[0000] Configuration loaded from file: /home/swiltink/code/traefik-playground/traefik.toml 
INFO[2019-09-19T00:24:29+02:00] Traefik version 2.0.0 built on 2019-09-16T17:35:17Z 
DEBU[2019-09-19T00:24:29+02:00] Static configuration loaded {"global":{},"serversTransport":{"maxIdleConnsPerHost":200},"entryPoints":{"banana-entry":{"address":":7777","transport":{"lifeCycle":{"graceTimeOut":10000000000},"respondingTimeouts":{"idleTimeout":180000000000}},"forwardedHeaders":{}},"traefik":{"address":":8080","transport":{"lifeCycle":{"graceTimeOut":10000000000},"respondingTimeouts":{"idleTimeout":180000000000}},"forwardedHeaders":{}}},"providers":{"providersThrottleDuration":2000000000},"api":{"insecure":true,"dashboard":true},"log":{"level":"DEBUG","format":"common"}} 
INFO[2019-09-19T00:24:29+02:00] 
Stats collection is disabled.
Help us improve Traefik by turning this feature on :)
More details on: https://docs.traefik.io/v2.0/contributing/data-collection/ 
DEBU[2019-09-19T00:24:29+02:00] No default certificate, generating one       
INFO[2019-09-19T00:24:29+02:00] Starting provider aggregator.ProviderAggregator {} 
DEBU[2019-09-19T00:24:29+02:00] Start TCP Server                              entryPointName=traefik
DEBU[2019-09-19T00:24:29+02:00] Start TCP Server                              entryPointName=banana-entry
```

Interestingly enough the dashboard doesn't show any http or tcp services, which is odd as well. 

From what I have been able to find in the documentation this should work. Please do let me know if I simply screwed something up, but from what I have been able to read from the documentation it should just work.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by svenwiltink** [comment]
pebkac. When moving the tcp configuration to a separate file and telling traefik to load it using the file provider it works as indended. After rereading the documentation this makes sense, but it would be nice if starting traefik with unknown config keys fails instead of silently ignoring them.
