### ISSUE TITLE
command traefik error: field not found, node: redirect

### ISSUE THREAD

**Issue by NadamHL** [containous/traefik#5422]
系统版本：
# uname -a
Linux b0108011 3.10.0-327.el7.x86_64 #1 SMP Thu Oct 29 17:29:29 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux
# kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"archive", BuildDate:"2019-08-06T07:09:54Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"archive", BuildDate:"2019-08-06T07:09:54Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"linux/amd64"}
#docker   19.03.1
kubernetes ： 15.2版本 

报错现象：
# kubectl describe pods traefik-ingress-controller-5964dc5f45-xzgdm -n kube-system
Name:           traefik-ingress-controller-5964dc5f45-xzgdm
Namespace:      kube-system
Node:           172.22.108.12/172.22.108.12
Start Time:     Thu, 19 Sep 2019 10:58:19 +0800
Labels:         k8s-app=traefik-ingress-lb
                name=traefik-ingress-lb
                pod-template-hash=5964dc5f45
Annotations:    <none>
Status:         Running
IP:             172.30.92.18
Controlled By:  ReplicaSet/traefik-ingress-controller-5964dc5f45
Containers:
  traefik-ingress-lb:
    Container ID:  docker://1ee1518e7bd65ca0d376135a17a831b0c860d020a1c02b2fb30f78b2e4406d44
    Image:         traefik
    Image ID:      docker-pullable://traefik@sha256:0226dc713901a6fe91c618fe64a17dfa8fdadd10ce2059433e11a911d75086c4
    Ports:         80/TCP, 443/TCP, 8080/TCP
    Host Ports:    80/TCP, 443/TCP, 8080/TCP
    Args:
      --api
      --kubernetes
      --logLevel=INFO
      --configFile=/etc/kubernetes/traefik/traefik-https.toml
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Thu, 19 Sep 2019 11:14:48 +0800
      Finished:     Thu, 19 Sep 2019 11:14:48 +0800
    Ready:          False
    Restart Count:  8
    Environment:    <none>
    Mounts:
      /etc/kubernetes/pki/ from ssl (rw)
      /etc/kubernetes/traefik/ from config (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from traefik-ingress-controller-token-zwmjp (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  ssl:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  traefik-ui-tls-cert
    Optional:    false
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      traefik-conf
    Optional:  false
  traefik-ingress-controller-token-zwmjp:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  traefik-ingress-controller-token-zwmjp
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  traefik=master
Tolerations:     <none>
Events:
  Type     Reason     Age                   From                    Message
  ----     ------     ----                  ----                    -------
  Normal   Scheduled  19m                   default-scheduler       Successfully assigned kube-system/traefik-ingress-controller-5964dc5f45-xzgdm to 172.22.108.12
  Normal   Pulled     18m (x4 over 19m)     kubelet, 172.22.108.12  Successfully pulled image "traefik"
  Normal   Created    18m (x4 over 19m)     kubelet, 172.22.108.12  Created container traefik-ingress-lb
  Normal   Started    18m (x4 over 19m)     kubelet, 172.22.108.12  Started container traefik-ingress-lb
  Normal   Pulling    17m (x5 over 19m)     kubelet, 172.22.108.12  Pulling image "traefik"
  Warning  BackOff    4m12s (x71 over 19m)  kubelet, 172.22.108.12  Back-off restarting failed container
--------------------------------
# kubectl logs traefik-ingress-controller-5964dc5f45-xzgdm -n kube-system
2019/09/19 03:14:48 command traefik error: field not found, node: redirect
# 
-----------------------------------------------------------------------------------------------------------

问题描述：

Traefik has been running successfully, and in a few days, it suddenly hangs up and then reports an error.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by dduportal** [comment]
Hello @NadamHL , set the image to `traefik.v1.7.16`.

> Friends don't let friends use "latest".

The error is because you are using a Traefik 1.7 configuration while the latest image is 2.0 (with breaking change).

**Comment by anoxi** [comment]
Using "image: traefik:v1.7.16" in my docker-compose.yml fixed it for me.

**Comment by MaxiReglisse** [comment]
where can you find documentation that shows the differences in documentation between version 1.7 and version 2.0?

**Comment by dduportal** [comment]
Hi @MaxiReglisse , following our friendly friend the "traefiker bot", do you mind switching such question to the community forum please? The goal is to help the maintainers to keep the github issue tracker for bug and feature request, while knowledge sharing and questions/community support should happen in the Community Forum to make things clearer.

By the way, you might want to read this page to get the main "things" to know for migrating from v1 to v2: <https://docs.traefik.io/v2.0/migration/v1-to-v2/>.
