### ISSUE TITLE
1.X Middleware documentation missing

### ISSUE THREAD

**Issue by acouette** [containous/traefik#5436]
Hello,

I am using traefik 1.7 on kubernetes.

I have been looking for some documentation about the 1.X Middlewares (without kubernetes CRDs).
The documentation seems to be gone. Even when selecting the v1.7 documentation on the website.

Could you please restore it ?

Thank you

**Comment by ldez** [comment]
Hello,

In v1, there is no section dedicated to middleware.
The current documentation served by https://docs.traefik.io/v1.7/ is the whole documentation of the v1.

I think you are looking for this section: https://docs.traefik.io/v1.7/configuration/backends/kubernetes/#annotations

**Comment by acouette** [comment]
Indeed.. sorry for bothering !

Thank you 😁
