### ISSUE TITLE
Traefik 2.0 Helm Chart

### ISSUE THREAD

**Issue by tanwarsatya** [containous/traefik#5440]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I recently deployed traefik 2.0 in kubernets dev environment, I was trying to find out if there is any work in progress for traefik 2.0 helm chart. This will help everyone in streamlining application dependencies in helm charts.

**Comment by tanwarsatya** [comment]
Helm v3.0.0-beta.3 is out, would be nice to see a new chart in a newer format.

**Comment by dtomcej** [comment]
There is a chart under development. We will update this ticket when it is available for testing!

**Comment by obeyler** [comment]
> Helm v3.0.0-beta.3 is out, would be nice to see a new chart in a newer format.
Please stay first in Helm 2 format ... as Traefik  V2 is a big evolution  dont force us  to do another big evolution with a new helm chart version in same time... Changing Ingress to IngressRoute already impact all K8S cluster apps...

**Comment by dperezmavro** [comment]
+1 at what @obeyler said, personally we'd like as small a delta as possible per update and changing a major version is already a big enough change imho

**Comment by ryaneorth** [comment]
@dtomcej - is there an ETA for when the Helm chart will be available for traefik 2.0? The reason I ask is I am curious whether it is worth spending the cycles deploying Traefik 2.0 to our Kubernetes clusters. Thanks!

Also - I am happy to help contribute to the official traefik 2.0 helm chart if it will help speed along its development!

**Comment by vitobotta** [comment]
I just installed Traefik to try it and saw a message in the logs saying that there's the 2.x version available. When will it be available with helm? :)

**Comment by ldez** [comment]
We are on it, so please be patient.

**Comment by dtomcej** [comment]
Hello All!

We have created a dedicated repository for the incubator helm chart:
https://github.com/containous/traefik-helm-chart

This chart is for version 2 only. Please be aware that it is minimal to start with, since many of the features are enabled via the CRD.

Please open PRs against that repo for chart updates.

Once we are comfortable with the chart, we will pull to the main helm repository.

Thanks!

**Comment by ekjuanrejon** [comment]
Hi

when will the traefik helm chart be ready for production?

**Comment by leifcr** [comment]
> when will the traefik helm chart be ready for production?

When they close this issue, and add a release. Patience is gold. If you are in a hurry, follow the steps here: https://docs.traefik.io/v2.0/user-guides/crd-acme/ and deploy manually...

**Comment by isavcic** [comment]
It seems like the Helm chart repo is very low traffic, with very few commits going in. Just wondering, is this a low priority or?

**Comment by dtomcej** [comment]
Since https://github.com/containous/traefik-helm-chart/pull/104, the helm chart is production ready.

Closing this issue.

If you have any issues with the chart, please open an issue on that repo.
