### ISSUE TITLE
Fail without provider being configured

### ISSUE THREAD

**Issue by dragetd** [containous/traefik#5441]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

When starting traefik 2.0.0 without any provider configured via CLI (i.e. no --providers.file configured), traefik still parses `/etc/traefik/traefik.toml` (or the `.yml` respecively).

Configuring logging etc. works via this configuration file, which is also an expected behavior for me.

There are default entry points, so configuring (only) some routers, services etc. inside this file, I expect traefik to recognize these.

Instead, it ignores the routers. One has to configure a `[providers]` (`providers:` in yml) section with `file`, only then traefik recognizes the routers and services configured in the very same file.

This is not really intuitive. If traefik already parses the config file, I expect it to also recognize the configured routers etc.
Since adding this behavior is a bit of a large change for a maintenance release, I purpose to add an ERROR (or at least WARNING) if there is no provider configured. This would give people at least a hint that they should add this section to the config.

**Comment by ldez** [comment]
Hello,

In the v1 the file provider (`[file]`) must also be activated to read frontends and backends.

We made the choice to separate explicitly by default static configuration and dynamic configuration.

So I will decline your request.

Thanks.
