### ISSUE TITLE
2.0 version of the tengine question about the traefik reverse proxy aspect

### ISSUE THREAD

**Issue by zlw310282** [containous/traefik#5446]
### Do you want to request a *feature* or report a *bug*?
other

### Did you try using a 1.7.x configuration for the version 2.0?
version 2.0
- [ ] Yes

### What did you do?

The 2.0 version of the document looks very confused and the new version almost does not search for the corresponding third-party article, so I have to come under this consultation.

I am currently using the latest version 2.0 of traefik, and now load balancing has been built to test the available, but now I have a problem.
Please see:
I have a server, using tengine, the domain name of this binding is www.meng.cc, the server ip is 1.2.3.4, now I am accessing http://1.2.3.4 will report error 404, this is normal, visit http:// Www.meng.cc has normal access to the resources you need.
Then I need to reverse proxy in traefik. This server 1.2.3.4, www.meng.cc domain name has been resolved to the traefik server, by visiting www.meng.cc can get the correct resources through the proxy, how do I need to operate now.
Many thanks！

Below is my partial configuration：

  [http.middlewares]
    [http.middlewares.myip.headers]
	[http.middlewares.myip.headers.customRequestHeaders]
		
         X-Script-Name = "Host: www.meng.cc"
      [http.middlewares.myip.headers.customResponseHeaders]
	     X-Script-Name = "Host: www.meng.cc"
#        X-Custom-Response-Header = "value"

[http.services]
   [http.services.myip]
    [http.services.myip.loadBalancer]
      [[http.services.myip.loadBalancer.servers]]
        url = "http://1.2.3.4/"
      [[http.services.myip.loadBalancer.servers]]
        url = "http://127.0.0.1:32769/"

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
