### ISSUE TITLE
Traefik upgrade from 1.7.16 to 2.0 leads to brick -> not enough documentation for reconfiguration

### ISSUE THREAD

**Issue by bd8392** [containous/traefik#5449]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [x] Yes
- [ ] No

### What did you expect to see?

working traefik

### What did you see instead?

not working traefik

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
(paste your output here)
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# (paste your configuration here)
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```

I don't see any eyamples how to configure traefic 2.0 in contrast to 1.7.16! My whole server structure depends on this reverse proxy and im not able to configure it anymore! please URGENTLY provide better configuration examples, or make the old config files compatible!

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by ldez** [comment]
Hello,

you don't need to upgrade to Traefik v2, Traefik v1 will still continue to be maintain (bugfixes only)

You just need to use the tag `v1.7` instead of `latest`.

If you really want to upgrade now:
- https://docs.traefik.io/v2.0/getting-started/configuration-overview/
- https://docs.traefik.io/v2.0/user-guides/docker-compose/basic-example/
- https://docs.traefik.io/v2.0/migration/v1-to-v2/
- https://github.com/containous/traefik-migration-tool

**Comment by bd8392** [comment]
Thanks!
