### ISSUE TITLE
2.0 is missing Alpine Docker images

### ISSUE THREAD

**Issue by kernle32dll** [containous/traefik#5453]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [X] No

### What did you do?

I am using a containerized version of Traefik 2.0, with the Alpine flavor.

I rewrote my existing configuration from 1.7 to 2.0. After finally being greeted by the new dashboard, I immediately noticed an odd version at the top: "Traefik 2.0.0-rc3".

### What did you expect to see?

"Traefik 2.0.0" - not a release candidate.

### What did you see instead?

Well... a release candidate?

After checking the digests (double-checking if maybe something wrong was pulled), I can confirm that the `v2.0-alpine` tag is stuck on rc3:

https://hub.docker.com/layers/traefik/library/traefik/v2.0-alpine/images/sha256-163059236ff2710378a9527865aefcfcde6cfdd811d749c3b73ff45cf27589a8

That digest is the same as of the tag `v2.0.0-rc3-alpine`. What seems extra odd is the fact that there never was a rc4 Alpine tag.

I can only assume that Alpine support was dropped, but I was unable to find any documentation or blog indicating so.

**Comment by ldez** [comment]
Hello,

since the GA of Traefik v2.0, we have remove the `from scratch` Docker image, now Traefik use alpine for all the Docker images.

So, the tags `-alpine` has been dropped because it's not needed anymore.

**Comment by kernle32dll** [comment]
Okay, makes sense. Would you clarify that in the documentation then?

Because here:

https://docs.traefik.io/getting-started/install-traefik/

It still states:

> Docker images comes in 2 flavors: scratch based or alpine based

**Comment by ldez** [comment]
I will fix that

**Comment by rockwyc992** [comment]
**Is there any discuss for dropped `from scratch` base image?**

The most popular images, like [redis](https://hub.docker.com/_/redis), [postgres](https://hub.docker.com/_/postgres), [node](https://hub.docker.com/_/node) and [nginx](https://hub.docker.com/_/nginx), they all provide `${version}-alpine` and `alpine` tags.
Even `latest` and `alpine`  are the same image, it still a good idea for common usage.

I think we should keep `alpine` tag, even we don't provide any images with other base image(or flavors).

**Comment by kernle32dll** [comment]
> The most popular images, like [redis](https://hub.docker.com/_/redis), [postgres](https://hub.docker.com/_/postgres), [node](https://hub.docker.com/_/node) and [nginx](https://hub.docker.com/_/nginx), they all provide `${version}-alpine` and `alpine` tags.
> Even `latest` and `alpine` are the same image, it still a good idea for common usage.

Well, the thing with traefik is, that its a bit different than than the usual images.

traefik - before v2 - provided Alpine and **scratch** images. Scratch meaning "just the binary" - e.g. no shell. Good for production (size), bad for debugging. You can see that [here](https://github.com/containous/traefik-library-image/blob/v2.0.0/scratch/Dockerfile).

The other images you listed provide tags based on Debian, Ubuntu, or the likes, plus additionally Alpine. There never was something like a Debian based traefik Docker image.

---

That being said - 

- For one - pointing `v2.0-alpine` to an RC is confusing.

- I can see the incentive for providing bare scratch images - size and attack surface.

- On the other hand, being able to shell into the container for debugging proved invaluable during migration (which I was only able to do because of `v2.0-alpine` existing, albeit as an RC)

**Comment by ldez** [comment]
Hello,

We held a vote within maintainers about this topic.

We mainly (but not only) did that because of some remarks from Docker staff:

- https://github.com/docker-library/official-images/pull/6541#issuecomment-525005179
- https://github.com/docker-library/official-images/pull/5633#issuecomment-478142109
- https://github.com/docker-library/official-images/pull/5426#issuecomment-462561556
