### ISSUE TITLE
Complete configuration for https redirect with basic auth

### ISSUE THREAD

**Issue by bd8392** [containous/traefik#5454]
Please provide a complete configuration [docker-compose] (best only with docker labels) for https redirect with basic auth, as i can't get it to work right now (coming from 1.7). Also the service which should be proxied, is only available on special ports (8080)...please help!

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
