### ISSUE TITLE
ability to specify default TLS certificate for Kubernetes CRD

### ISSUE THREAD

**Issue by artiommocrenco** [containous/traefik#5468]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Currently it is possible to configure default TLS certificate via TOML/YAML using:
```toml
[tls.stores]
  [tls.stores.default]
    [tls.stores.default.defaultCertificate]
      certFile = "path/to/cert.crt"
      keyFile  = "path/to/cert.key"
```

with KubernetesCRD, however, it is not possible, because the only things we can configure are those via using CRDs (`tlsoption`, `ingressroute`, `middleware`, `ingressroutetcp`) and CLI, or by mounting `configmap`/`secret` containing the tls.crt and tls.key to Traefik container.

As far as I understand it, the latest is not possible because Traefik generates a self-signed TLS cert at runtime and stores it in memory.

CLI does not have such an option.

**Comment by artiommocrenco** [comment]
There **seems** to be a way to do it, though.

To use file provider when starting the traefik pod, define necessary defaults you can't configure with KubernetesCRD provider, and then to define additional Kubernetes provider in the YAML/TOML config.

This is an **extremely ugly** solution (if working at all). Are there some features supported only in file provider and not other providers?

**Comment by andrewsav-datacom** [comment]
>This is an extremely ugly solution (if working at all). Are there some features supported only in file provider and not other providers?

To me it looks like File Provider supports all available features, but the rest of providers really shaped by what particular orchestration provides, so they are limited to only those features that are relevant to that orchestration.

I even briefly contemplated writing a new kubernetes provider, that supports everything file provider supports, via labels a la traefik v1. It would be a lot of work though.

**Comment by ybizeul** [comment]
@artiommocrenco I'm not sure I get what you suggest, I did add this in my `ConfigMap` :
```
[...]
    [tls.stores]
      [tls.stores.default]
        [tls.stores.default.defaultCertificate]
          certFile = "/ssl/tls.crt"
          keyFile  = "/ssl/tls.key"
    [tls.certificates]
      certFile = "/ssl/tls.crt"
        keyFile  = "/ssl/tls.key"
```

It doesn't seem to have an effect. (I checked the container, and it has all these files mounted)

Traefik documentation is probably one of the worst I was ever trying to decipher, I can't make any sense of it.

It seems so silly to me that you can't define a default certificate global to the controller, I'm not even sure that's actually the case...

**Comment by artiommocrenco** [comment]
Hello, I was able to do that providing
`--configFile=/etc/traefik/traefik.yaml` arg to traefik (via k8s
deployment) and mounting configmap to /etc/traefik/traefik.yaml.

In the config file (k8s configmap) I also specified all configuration for
features which can not be used/configured by using just traefik Custom
Resource Definitions alone.

I also remember that in the config file, aside from kubernetescrd provider,
it was necessary for me to specify file provider and point it to
/etc/traefik/traefik.yaml . Without that, my configurations from
traefik.yaml were ignored by traefik and only kubernetescrd was working
properly.

What can I say.. it works.. not sure all have to go through all this pain
to make it working properly :)

I will post an example how it all can be done on Monday.

**Comment by adhodgson1** [comment]
I am in the same boat. Getting it working by using a yaml config file and mount that as a configmap volume along with the certificates. I have not gone to Traefik 2.x yet in production as I wanted to use the official chart as much as possible.  I did try and get it working using command-line arguments but found out it wasn't possible to set the default cert using this either.

**Comment by dtomcej** [comment]
Currently working on implementing TLSStore into the CRD similar to TLSOptions.

This will allow for configuring the default certificate by creating a CRD object pointing to the secret that holds the certificate.

No mounting, no configfiles.

I will reference this Issue in the PR that should be dropping shortly.

**Comment by bradjones1** [comment]
For what it's worth, if you are looking to enable a file-based default certificate when using the Kubernetes Ingress (and possibly the CRD?) provider, you must apparently specify the file provider in your main "static" configuration, and then specify the certificate in that "dynamic" config file. E.g.:

`/etc/traefik/traefik.toml`:
```toml
[providers]
  [providers.file]
    filename = "/etc/traefik/dynamic.toml"
```
`/etc/traefik/dynamic.toml`:
```toml
[tls.stores]
  [tls.stores.default]
    [tls.stores.default.defaultCertificate]
      certFile = "/secrets/tls.crt"
      keyFile  = "/secrets/tls.key"
```

Furthermore, it appears that in Traefik 2.x vs. 1.x, for ingresses to be processed by the Kubernetes provider (and take advantage of this default cert) the host for TLS must be specified in the ingress spec. (That is, specify `hosts` but not `secretName`.)

**Comment by cameronbraid** [comment]
The other downside is that when you start using a config file the CLI args are ignored so you need to migrate all cli args into the config file

**Comment by ldez** [comment]
> The other downside is that when you start using a config file the CLI args are ignored so you need to migrate all cli args into the config file

@cameronbraid You are mixing the [dynamic configuration](https://docs.traefik.io/v2.1/getting-started/configuration-overview/#the-dynamic-configuration) and the [static configuration](https://docs.traefik.io/v2.1/getting-started/configuration-overview/#the-static-configuration):
- the `tls`section is a part of the dynamic configuration so there is no link with CLI flags because CLI flags are the static configuration.

The provider file can be enable by using CLI flags, the content of the file (dynamic configuration) used by the file provider don't conflict with the static configuration.

```bash
--providers.file.filename=/etc/traefik/dynamic.toml
```

/etc/traefik/dynamic.toml:
```
[tls.stores]
  [tls.stores.default]
    [tls.stores.default.defaultCertificate]
      certFile = "/secrets/tls.crt"
      keyFile  = "/secrets/tls.key"
```

**Comment by cameronbraid** [comment]
Ok, I had done the following : 

````
--configFile=/etc/traefik-config/static.toml
```

Which caused all other cli args to be ignored. 

I didn't know I could just enabled the dynamic file provider with 

```
--providers.file.filename=/etc/traefik/dynamic.toml
```

Thanks - thats a much better solution
