### ISSUE TITLE
Long term support for Traefik 1.7.x?

### ISSUE THREAD

**Issue by djerfy** [containous/traefik#5475]
### Question

Traefik v1.7.x will continue to have support?
If yes for a long time?

Thank you

**Comment by geraldcroes** [comment]
Hi, and thank you for your question.
The current plan is to support 1.7 for a year, starting with the v2.0.0 release. We want to give the community time to adapt their stack and time to provide feedback to make sure the transition to 2.0 is as great as expected.

**Comment by emilevauge** [comment]
Hi all, we decided to extend the support of Traefik 1.x [until the end of 2021](https://containo.us/blog/traefik-2-1-in-the-wild) 🎉
