### ISSUE TITLE
Traefik-V2 Doesn't support Wildcard certificate generation By DNS-N1

### ISSUE THREAD

**Issue by robinwangrubin** [containous/traefik#5476]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I used Traefik 2.0 with Docker-Swarm environment, Below is How i started Traefik-v2:

```
docker service create \
    --name traefik-v2 \
    --mode global \
    --network docker-proxy \
    --network web \
    --publish mode=host,target=80,published=80,protocol=tcp \
    --publish mode=host,target=443,published=443,protocol=tcp \
    --publish mode=host,target=8080,published=8080,protocol=tcp \
    --env 'ALICLOUD_REGION_ID=xxxxxx' \
    --env 'ALICLOUD_ACCESS_KEY=this is my secret' \
    --env 'ALICLOUD_SECRET_KEY=this is my super secret' \
    --mount type=bind,source=/usr/share/zoneinfo,destination=/usr/share/zoneinfo,ro=1 \
    --mount type=volume,source=traefik-v2,destination=/docker-volume \
    traefik:v2.0 \
    --providers.docker=true \
    --providers.docker.endpoint="tcp://docker-proxy:2375" \
    --providers.docker.swarmMode=true \
    --providers.docker.swarmModeRefreshSeconds=10s \
    --providers.docker.exposedByDefault=false \
    --entryPoints.web.address=:80 \
    --entryPoints.web-secure.address=:443 \
    --log=true \
    --log.level=INFO \
    --accesslog=true \
    --accesslog.bufferingsize=100 \
    --api.insecure=true \
    --certificatesresolvers.mydnschallenge.acme.dnschallenge=true \
    --certificatesresolvers.mydnschallenge.acme.dnschallenge.provider=alidns \
    --certificatesresolvers.mydnschallenge.acme.email=myemail@email.com \
    --certificatesresolvers.mydnschallenge.acme.storage=/docker-volume/acme.json \
    --certificatesresolvers.mydnschallenge.acme.dnschallenge.delaybeforecheck=10s \
    --certificatesresolvers.mydnschallenge.acme.dnschallenge.resolvers=114.114.114.114:53,8.8.8.8:5
```

In addition, This is How my docker service started: (I copy it from your document)

```
docker service create \
    --name whoami \
    --mode global \
    --network web \
    --label 'traefik.enable=true' \
    --label 'traefik.docker.network=web' \
    --label 'traefik.http.routers.whoami.rule=Host(`whoami.mydomain.com`)' \
    --label 'traefik.http.services.whoami.loadbalancer.server.port=80' \
    --label 'traefik.http.routers.whoami.tls.certresolver=mydnschallenge' \
    containous/whoami:latest
```

My First question is :
**If i configure certresolver, my service only can be accessed by HTTPS, But http is not working.** 

My Second question is:
**It can generate a specific domain certificate by useing above configuration, But I have hundreds of domains,  It's impossible to generate a Wildcard certificate and How?**

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by ldez** [comment]
https://docs.traefik.io/https/acme/#wildcard-domains
