### ISSUE TITLE
HTTP AND HTTPS cannot work together at same Route

### ISSUE THREAD

**Issue by robinwangrubin** [containous/traefik#5477]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

No

### What i did?

I used Traefik 2.0 with Docker-Swarm environment, Below is How i started Traefik-v2:

```
docker service create \
    --name traefik-v2 \
    --mode global \
    --network docker-proxy \
    --network web \
    --publish mode=host,target=80,published=80,protocol=tcp \
    --publish mode=host,target=443,published=443,protocol=tcp \
    --publish mode=host,target=8080,published=8080,protocol=tcp \
    --env 'ALICLOUD_REGION_ID=xxxxxx' \
    --env 'ALICLOUD_ACCESS_KEY=this is my secret' \
    --env 'ALICLOUD_SECRET_KEY=this is my super secret' \
    --mount type=bind,source=/usr/share/zoneinfo,destination=/usr/share/zoneinfo,ro=1 \
    --mount type=volume,source=traefik-v2,destination=/docker-volume \
    traefik:v2.0 \
    --providers.docker=true \
    --providers.docker.endpoint="tcp://docker-proxy:2375" \
    --providers.docker.swarmMode=true \
    --providers.docker.swarmModeRefreshSeconds=10s \
    --providers.docker.exposedByDefault=false \
    --entryPoints.web.address=:80 \
    --entryPoints.web-secure.address=:443 \
    --log=true \
    --log.level=INFO \
    --accesslog=true \
    --accesslog.bufferingsize=100 \
    --api.insecure=true \
    --certificatesresolvers.mydnschallenge.acme.dnschallenge=true \
    --certificatesresolvers.mydnschallenge.acme.dnschallenge.provider=alidns \
    --certificatesresolvers.mydnschallenge.acme.email=myemail@email.com \
    --certificatesresolvers.mydnschallenge.acme.storage=/docker-volume/acme.json \
    --certificatesresolvers.mydnschallenge.acme.dnschallenge.delaybeforecheck=10s \
    --certificatesresolvers.mydnschallenge.acme.dnschallenge.resolvers=114.114.114.114:53,8.8.8.8:5
```

In addition, This is How my docker service started: (I copy it from your document)

```
docker service create \
    --name whoami \
    --mode global \
    --network web \
    --label 'traefik.enable=true' \
    --label 'traefik.docker.network=web' \
    --label 'traefik.http.routers.whoami.rule=Host(`whoami.mydomain.com`)' \
    --label 'traefik.http.services.whoami.loadbalancer.server.port=80' \
    --label 'traefik.http.routers.whoami.tls.certresolver=mydnschallenge' \
    containous/whoami:latest
```

### What's the problem?

If my server configured certresolver, It will olny work with HTTPS.

When i try to access my website with http://whoami.mydomain.com, I got 404 page not found.

By the way, The Bot is ridiculous. It always closes my issus.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by dduportal** [comment]
Hi @robinwangrubin , the bot helps us to keep the github issue tracker easier to manage for the community, by using it only for bug and enhancement.

Could you please raise a topic on the community forum please: the community could help you in solving your issue by pointing to the right documentation resource and providing you configuration snippets.

The maintainers are also doing their best to follow topics on the community forum, at least daily, so you might have a answer fast enough.

In the case you underline here, it is clearly not a bug hence the bot closing the issue, by inviting you to ask support and help on the right place where this knowledge sharing happen.

We understand the frustration of not having the tool working but please keep in mind we're human doing our best and we'll help you for sure.
