### ISSUE TITLE
Traefik 2.0 & Docker auto discovery with compose and without compose: 404 in Traefik dashboard

### ISSUE THREAD

**Issue by BulloRosso** [containous/traefik#5489]
When using Traefik 2.0 with auto discovery and Docker Desktop on Windows 10 I notice a difference between the detection of containers deployed with docker-compose and containers deployed via the Docker API:

![image](https://user-images.githubusercontent.com/10236695/65601931-52017000-dfa3-11e9-90c0-36aa0126e84c.png)

All containers which are deployed directly via Docker API are internally **prefixed with a dash** at auto discovery - whitch in turn leads to a 404 in the drilldown with Traefik dashboard because a double slash in the URL:

`/dashboard/#/http/services//dmg-package-manager@docker`

You can't fix it by just hacking the URL - the whole loadbalancer doesn't work.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by ldez** [comment]
Hello,

Next time could you try to follow the issue template, thanks.

**Comment by traefiker** [comment]
Closed by #5491.
