### ISSUE TITLE
[CI] wiredep marked as unmaintained

### ISSUE THREAD

**Issue by emilevauge** [containous/traefik#550]
It appears that [wiredep](https://libraries.io/npm/wiredep) as been marked as unmaintained and that leads [dependencyci](https://dependencyci.com/github/containous/traefik/builds/25) to fail.

@ldez any advice?

**Comment by ldez** [comment]
Currently Wiredep is not clearly flag as unmaintained.

If we must change, we can switch to gulp-inject or others.

**Comment by emilevauge** [comment]
>Currently Wiredep is not clearly flag as unmaintained.

![sure?](https://cloud.githubusercontent.com/assets/6207234/17021396/135ccdac-4f48-11e6-90b9-d710c34e85ed.png)

**Comment by ldez** [comment]
For me the truth is in NPM https://www.npmjs.com/package/wiredep

**Comment by ldez** [comment]
The better and the quick way to migrate seems to recreate the WebUI with a generator.
https://github.com/FountainJS/generator-fountain-webapp
