### ISSUE TITLE
Traefik 1.7 Allow use of socket for Datadog metrics

### ISSUE THREAD

**Issue by morsok** [containous/traefik#5502]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Currently we have to specify an url:port for the datadog metrics. On kubernetes, you can't provide 127.0.0.1 but instead provide the ip of the node on which the pod is running, which can be done using the downward api, and when using the helm chart, you use cli arguments to set the address.

However Traefik when in HA mode with consul for example, only use consul configuration and ignores cli arguments and so tries to use the default value of 127.0.0.1.

One easy way to fix that issue when in HA would be to allow using the datadog unix socket that you can mount into the pod (see https://docs.datadoghq.com/developers/dogstatsd/unix_socket/), when doing that, every traefik pod will talk to the locally mounted socket from the agent running on the same node without any issues.

**Comment by dduportal** [comment]
Hi @morsok , thanks a lot for reporting this feature request as we released Traefik v2.0, the v1.7 is still supported but does not accept new features: only bug fixes and security fixes.

As Traefik v2.0 is not supporting yet Consul as KV provider, would you mind describing the problem on our Community forum so a solution to help you might be found and shared.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by morsok** [comment]
@dduportal Ok thank you for your swift answer, that's what i was afraid of.

I openned https://github.com/helm/charts/pull/17466#issuecomment-535564512 to compensate.
