### ISSUE TITLE
Traefik not resolving containers ip by name when attached to the default network

### ISSUE THREAD

**Issue by bd8392** [containous/traefik#5510]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you expect to see?

Working traefik

### What did you see instead?

Not working traefik with the message in the logs:
Couldn't find ip of container

### Output of `traefik version`: (_What version of Traefik are you using?_)
2.0

```
(paste your output here)
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# (paste your configuration here)
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```

The problem is, that I use rancherOS with the Cloud-init configuration method...this doesn't allow to define custom networks...but traefik doesn't seem to work in the default docker bridge, as this does not resolve the ip of the container by it's name...how can I resolve that? Has someone ever configured traefik in rancherOS Cloud-init? (It's using rancher compose where some options are stripped away). I also can't find any hint in the documentation that I've to define a custom network... please help!

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by bd8392** [comment]
Hi traefiker has accidentally closed my issue...please reopen.

**Comment by dduportal** [comment]
Hi @bd8392 , it is not an error: the problems you are facing are related to configuration or need support. As we keep the github for bugs and features, can you please ask for help in the community forum at <https://community.containo.us/> please? Thanks a lot for your understanding!

**Comment by bd8392** [comment]
Ok thank you :-)
