### ISSUE TITLE
Missing Docker image for Træfik 1.7.18 (Linux AMD64)

### ISSUE THREAD

**Issue by ayosec** [containous/traefik#5512]
The image for 1.7.18 is not available for Linux AMD64.

    $ uname -om
    x86_64 GNU/Linux

    $ docker pull traefik:1.7.18
    1.7.18: Pulling from library/traefik
    no matching manifest for unknown in the manifest list entries

According to https://hub.docker.com/_/traefik?tab=tags&name=1.7.18 it is only for Windows AMD64 and Linux ARM.

**Comment by ldez** [comment]
The official Docker is currently under construction in the Docker build system.
It's normal that you can not pull it yet.

You have to wait a bit.
