### ISSUE TITLE
Problem using ssl Backend with selfsigned certificates

### ISSUE THREAD

**Issue by bd8392** [containous/traefik#5526]
I want to use a backend (server) on version 2.0, that uses a self-signed certificate. How can I configure this with labels or cli? the option --serverstransport.insecureskipverify=true does not seem to work...when I call the service over traffic I only see: Internal server error. What am I doing wrong?

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by bd8392** [comment]
Please don't close this issue! I need this config and I can't find it in the documentation...

**Comment by dduportal** [comment]
Hi @bd8392 , as asked on each issue, the problems you are facing are related to configuration or need support. As we keep the github for bugs and features, can you please ask for help in the community forum at <https://community.containo.us/> please? Thanks a lot for your understanding!
