### ISSUE TITLE
Unable to use the name provider namedotcom

### ISSUE THREAD

**Issue by josuemotte** [containous/traefik#5537]
Hello, 

While trying to get a certificate using the latest version of traefik which is 2.0.1, I'm getting an error message like this : 

``` time="2019-09-28T17:25:41Z" level=debug msg="legolog: [WARN] [*.coucou.rocks] acme: error cleaning up: namedotcom: Get https://https//api.name.com/v4/domains/coucou.rocks/records: dial tcp: lookup https on 127.0.0.11:53: server misbehaving " ``` 

I would say https://https// seems to be the issue...

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
