### ISSUE TITLE
SSL Passthrough with LetsEncrypt

### ISSUE THREAD

**Issue by los93sol** [containous/traefik#5541]
As I understand it traffic going to an https endpoint will be https between the browser and Træfik then http from Træfik to the endpoint.

I am attempting to keep it https all the way through and let Træfik handle retrieving/renewing certificates from LetsEncrypt.  The issue I have is the acme.json file...most applications expect a .cert and .key file in pem format to bind at the endpoint itself.  If those files were created it would be trivial to share the volume and be good to go.  I’ve seen the other issues where it is recommended to use a separate container or certbot to do this, but I do not understand the logic behind that.  It seems to be a lot of unnecessary complexity for simple setups.  I guess it makes sense to have something else doing it and pumping it in everywhere when you have an HA Træfik setup, but with the verbose config on 2.0 I’m wondering why make it even harder than it already is to get a truly secure setup.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

Issue templates help us help you by providing all necessary information.

Please edit your issue and use the available templates:

- [Feature request](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/Feature_request.md)
- [Bug report](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/Bug_report.md)

And remember: each time someone ignores the template, a cute little bunny dies.
<details>
<summary>#SaveTheCuteBunny :heart: :rabbit: :heart:</summary>

![southpark - estrella kill rabbit](https://user-images.githubusercontent.com/5674651/27143914-3cea7896-5130-11e7-81f8-02d8ac2da7a7.gif)

![southpark - estrella kill rabbit2](https://user-images.githubusercontent.com/5674651/27143924-49104c72-5130-11e7-82ae-ccedbd5dfa1c.gif)

</details>

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Community Forum](https://community.containo.us/).

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Community Forum](https://community.containo.us/).
