### ISSUE TITLE
Exclude some frontends in consul catalog

### ISSUE THREAD

**Issue by minhdanh** [containous/traefik#555]
There are some services in consul such as nomad, nomad-client, etc. that I want to exclude from the auto discovered frontends by consul catalog backend. Currently is there a way to prohibit those frontends (and theirs corresponding backends) from being included by consul catalog?

**Comment by keis** [comment]
You can add a `traefik.enable=false` tag to a service to exclude it

**Comment by minhdanh** [comment]
Unfortunately Nomad, (and maybe some other services) registers itself with Consul without an option to specify a tag/label. So I think this is not a preferable way to exclude some system services from traefik.

**Comment by emilevauge** [comment]
I do see tags in Nomad : https://www.nomadproject.io/docs/jobspec/servicediscovery.html#tags

**Comment by minhdanh** [comment]
That's not what I'm talking about. I can assign the tag with a nomad `job`, but not with Nomad itself. As when bootstrapping a Nomad cluster, Nomad register itself with Consul, so that other Nomad agents can refer to this Nomad service by using `nomad.service.consul:4747`. I want to exclude the Nomad service, not Nomad jobs' services.

**Comment by emilevauge** [comment]
OK I see. Hum, then I don't see any way for traefik to filter those services... Any idea?

**Comment by minhdanh** [comment]
I'm thinking of something like this in consul catalog backend configuration:
```
exclude_services = "nomad,redis"
```
Which will exclude the specified services. It'll be nice if `exclude_services` also supports regex. But I'm not sure this is the best way possible.

**Comment by emilevauge** [comment]
In fact, there is already a way to do that, but it is not documented for now https://github.com/containous/traefik/pull/479, we are waiting this issue https://github.com/containous/traefik/issues/451 to be fixed to add documentation on constraints ;)

**Comment by minhdanh** [comment]
I see. That looks cool. So I would be able to use a `constraints` directive to specify which frontends should be included and excluded, right?

**Comment by emilevauge** [comment]
Yep, and it already works, but the toml config have to be refined.
You can use it with `traefik --consulcatalog --consulcatalog.constraints="tag==traefik"` and then add a `traefik` on all the services you want to expose in traefik.

**Comment by minhdanh** [comment]
Thank you.

**Comment by emilevauge** [comment]
Can we close this one?

**Comment by minhdanh** [comment]
Ok. Never mind. Closing.

**Comment by nhaumont** [comment]
Hi

I tried the solution you provided:
"You can use it with traefik --consulcatalog --consulcatalog.constraints="tag==traefik" and then add a traefik tag on all the services you want to expose in traefik."

And I cannot make it work, every time I set the constraints, it excludes all the services even if I have some in consul which have the traefik label like:

   "ServiceTags":[
      "traefik"
   ],

I'm starting traefik with the docker image (docker run -t traefik -c /dev/null --web --consul --consulcatalog.constraints=tag==traefik --logLevel=DEBUG)

Thanks

**Comment by nhaumont** [comment]
Ok, I got it working, my mistake.
In consul, it has to be something like: "ServiceTags":["traefik.tags=traefik"]

**Comment by Cryson** [comment]
@nhaumont That works perfectly in consul. Thanks!!

**Comment by bilke** [comment]
@nhaumont 's solutions works but I would like to use Consuls default tags such as `http` as a constraint. I think the syntax for defining the Traefik tag is a bit weird in contrast to just plain tags such as `http`

```hcl
service {
        tags = ["traefik.tags=traefik", "http"]
        ...
}
```
@emilevauge Can I somehow configure `consulCatalog` to use simple tags? I played with the `prefix`-parameter but this did not help... Thanks!

**Comment by dduportal** [comment]
Hi @bilke , as Traefik v2.0 is currently worked on (alpha state), the behavior of the KV stores (as Consul Backends) might be subject to change, so stay tuned! You can track the work on the Kanban board on this repository (tab "Projects").
