### ISSUE TITLE
Traefik  overwritten  X-Forwarded-For header

### ISSUE THREAD

**Issue by sifksky** [containous/traefik#5551]
Hi:
   The traefik is a good tools. I want to use it for ratelimiting. But I find the X-Forwarded-For header will be overwritten.

   Client(10.70.1.27) --->Nginx(10.70.1.31) --> Traefik(10.70.1.36:90) -->BackendServer(10.70.1.36:9999)
I use docker-compose to lanuch the container, then use docker logs -f tracefik. 
1. At the client machine(10.70.1.27), curl http://10.70.1.31 ,  return  X-Forwarded-For and X-Real-Ip   is 10.70.1.31. But I already config nginx  "proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;".  So  the traefik must be overwritten the X-Forwarded-For header. I think  the true value  should be  10.70.1.27  not the lan ip of nginx (10.70.1.31).
2. At the client machine(10.70.1.27),  curl -H "X-Forwarded-For: 1.1.1.1" http://10.70.1.36:9999, the return has the "X-Forwarded-For: 1.1.1.1"  and I use curl -H "X-Forwarded-For: 1.1.1.1" http://10.70.1.36:90, the return  has the "X-Forwarded-For: 10.70.1.27", so the traefik overwritten the X-Forwarded-For header.

Q:  What is way I can disable the traefik  overwritten the X-Forwarded-For headers? Because I should  put the traefik behind the Nginx and use it for rate limiting. Thank you very much.

**Comment by sifksky** [comment]
Another: I also lanuch the traefik behind the AWS ALB, the X-Forwarded-For header also be overwritten to lan ip of AWS ALB.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

Issue templates help us help you by providing all necessary information.

Please edit your issue and use the available templates:

- [Feature request](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/Feature_request.md)
- [Bug report](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/Bug_report.md)

And remember: each time someone ignores the template, a cute little bunny dies.
<details>
<summary>#SaveTheCuteBunny :heart: :rabbit: :heart:</summary>

![southpark - estrella kill rabbit](https://user-images.githubusercontent.com/5674651/27143914-3cea7896-5130-11e7-81f8-02d8ac2da7a7.gif)

![southpark - estrella kill rabbit2](https://user-images.githubusercontent.com/5674651/27143924-49104c72-5130-11e7-82ae-ccedbd5dfa1c.gif)

</details>

**Comment by hsartoris-bard** [comment]
@sifksky https://docs.traefik.io/routing/entrypoints/#forwarded-header

You need to configure Traefik to trust your reverse proxy in front of it.

**Comment by denysvitali** [comment]
May be related to #5482

**Comment by hsartoris-bard** [comment]
@denysvitali No, this is user error; at worst documentation that's difficult to parse.

There's no reason for any reverse proxy, not just Traefik, to trust X-Forwarded-For headers by default. Anyone can set them; try this with a whoami server:
`curl -H "X-Forwarded-For: <whatever you want>" <whoami_ip>`

Until whatever you're using, be that Traefik, nginx, httpd, haproxy, etc. etc., is specifically told to trust that header when it originates from a particular IP; i.e., your initial load balancer, of course it just drops it and overwrites with the load balancer IP, which is the only one it really knows the request came from.

**Comment by sifksky** [comment]
@hsartoris-bard   You are right. When I add the 
"- --entryPoints.web.forwardedHeaders.trustedIPs=10.70.0.0/16"  in traefik-daemonSet.yaml  and
 ```    sourceCriterion:
      ipStrategy:
        excludedIPs:
        - 10.70.1.31/32"  
```
in rate-limt.yaml .  10.70.1.31 is the lan ip of nginx.   The traefik work normally.
Thank you very much.
