### ISSUE TITLE
Deny domains with Traefik

### ISSUE THREAD

**Issue by SGarridoDev** [containous/traefik#5560]
### Do you want to request a *feature* or report a *bug*?

Feature

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

I've configured a Docker Swarm arquitecture with 3 managers and 3 workers (3 servers). 
I've installed the traefik containers in global mode for the managers with consul.
I've a floating IP with keepalive in the 3 managers.
I've this DNS entries:
domain.com -> My floating IP
*.domain.com -> My floating IP
I'm receiving any request to xxxx.domain.com and this subdomain don't exists.
I'll need, if exists any way, to block all request to this subdomain (xxxx.domain.com) with traefik.

### What did you expect to see?
I need any rule, entrypoint or feature for block all request to domain.

### What did you see instead?
I see a lot of logs with "Backend not found" (traffic) to xxxx.domain.com. I want to eliminate that traffic.
In other projects I'm use haproxy with ACL for this purpose.
Is there anything like it for traefik?

### Output of `traefik version`: (_What version of Traefik are you using?_)

traefik:1.7.18 from DockerHub

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
