### ISSUE TITLE
Matcher: PathPrefixStrip in 2.0 

### ISSUE THREAD

**Issue by ptr1120** [containous/traefik#5562]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Documentation on how the matcher PathPrefixStrip [Documentaion v1.7](https://docs.traefik.io/v1.7/basics/#matchers) can be used in traefik version 2.

**Comment by ldez** [comment]
Hello,

`PathPrefixStrip` has been replaced by the rule [`PathPrefix`](https://docs.traefik.io/rv2.0/outing/routers/#rule) and the middleware [`stripPrefix`](https://docs.traefik.io/v2.0/middlewares/stripprefix/)
