### ISSUE TITLE
InfluxDB metrics: support SNI for https endpoints

### ISSUE THREAD

**Issue by ercpe** [containous/traefik#5577]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

SNI support for influxdb servers via https. The InfluxDB client does not pass a servername to the TLS config by default. As a result, the https transport is basically unusable except when you happen to have a dedicated ip address for your influxdb input.

I think it's safe to enable it by default for every https endpoint in https://github.com/containous/traefik/blob/a20a6636b4582e4e7b562fc01f64567775fc8a9a/pkg/metrics/influxdb.go

I tried with 

```
tlsConfig := new(tls.Config)
tlsConfig.ServerName = w.config.Address

if w.config.Protocol == "http" {
    return influxdb.NewHTTPClient(influxdb.HTTPConfig{
        Addr:     w.config.Address,
        Username: w.config.Username,
        Password: w.config.Password,
        TLSConfig: tlsConfig,
    })
}
```

but ran into an unspecified `tls: internal error` (never touched Go before).

**Comment by sgofferj** [comment]
Yeah, it's kinda funny that of all pieces of software, Traefik wouldn't support SNI outbound :laughing:
I do run an influxdb behind traefik at home and ran into this issue when I wanted to collect metrics from a remote traefik running on my AWS...

**Comment by sgofferj** [comment]
That issue does not appear to be present in 2.2 any more.

**Comment by ercpe** [comment]
I can confirm that pushing metrics to influxdb via https with SNI works as expected in 2.2.0.
Thanks!
