### ISSUE TITLE
Documentation for v2.0 middleware: forwardedheaders

### ISSUE THREAD

**Issue by Sarke** [containous/traefik#5580]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

Wanted to forward headers.  Only found them in

https://github.com/containous/traefik/tree/v2.0.1/pkg/middlewares/forwardedheaders

but not on 

https://docs.traefik.io/middlewares/overview/#available-middlewares

### What did you expect to see?

Documentation about forwarding headers.

### What did you see instead?

No documentation about forwarding headers.

### Output of `traefik version`: (_What version of Traefik are you using?_)

2.0.1

**Comment by Sarke** [comment]
Nevermind, it's actually part of the static config, not a middleware like the rest.  See:

https://docs.traefik.io/routing/entrypoints/#forwarded-header

**Comment by dduportal** [comment]
Hi @Sarke , thanks for the feedback, good catch :)
