### ISSUE TITLE
For version 2.x, will examples / k8s /* yaml be available for k8s?

### ISSUE THREAD

**Issue by mpv945** [containous/traefik#5587]
A favorite project has been used in version 1.7 from 1.6. I wonder if there are examples of kubernetes deployment after version 2.x.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
