### ISSUE TITLE
Standard unit for traefik latency in access log

### ISSUE THREAD

**Issue by krishnanvrphonepe** [containous/traefik#559]
Request to fix the unit of time in the latency field in the traefik access log ( either ms OR s or configurable ). Right now it alternates between msec and sec based on the magnitude, which makes it non-trivial process, like for example for elk.
Samples below:
10.84.192.15 - - [25/Jul/2016:13:43:37 +0530] "GET /apis/" HTTP/1.1" 200 78 "" "Jersey/2.13 (HttpUrlConnection 1.8.0_60)" 234252 "api" "http://prd-server:8080" 6.45837ms

10.84.192.16 - - [25/Jul/2016:13:44:49 +0530] "POST /apis/" 200 67 "" "Jersey/2.13 (HttpUrlConnection 1.8.0_60)" 235155 "api" "http://prd-server:8080" 1.053089843s  #===>  Prefer this to be msec too.

**Comment by jangie** [comment]
@krishnanvrphonepe functionality for consistency is merged as of #619
