### ISSUE TITLE
allow to configure external middlewares to be compiled with traefik

### ISSUE THREAD

**Issue by thewilli** [containous/traefik#5591]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

A simple way to compile traefik with custom middlewares in a non-intrusive way.

* Considering the many *thumbs up* and long discussion of #1336, there is a clear need for user-specific middlewares. 
* Providing a way to add external plugins to a pre-compiled traefik binary is quite difficult to accomplish, it is unlikely to be realized soon (#1336 was created in 2017).
* #1336 => Adding custom middlewares into traefik requires lots of changes, and can't be automated safely without breaking things.

What I'd like to propose is a compromise to allow those of us who do require additional functionality to maintain this without having to hand-patch traefik on each new release: Couldn't we modify the way (or extend it) middlewares are currently processed internally, so adding new ones won't require a single code change of traefik?

Consider the [AddPrefix](https://docs.traefik.io/v2.0/middlewares/addprefix/) Middleware to see the complexity of this: Its [configuration](https://github.com/containous/traefik/blob/v2.0.1/pkg/config/dynamic/middlewares.go#L42-L45) is defined outside of its [package](https://github.com/containous/traefik/tree/v2.0.1/pkg/middlewares/addprefix) and is referred to twice ([k8s/CRD](https://github.com/containous/traefik/blob/v2.0.1/pkg/provider/kubernetes/crd/traefik/v1alpha1/middleware.go#L23), [dynamic configuration](https://github.com/containous/traefik/blob/v2.0.1/pkg/config/dynamic/middlewares.go#L17)).
 
What I'd like to have is a configuration file that contains external middlewares as Go Modules, and could be consumed by e.g. `go generate` to generate the required glue code. Provided that there are no conflicting dependencies, this would work great with CI/CD environments. And it would prevent non-dev users to stick to unmainted, outdated forks where someone managed to handcraft a specific middleware (consider the lua examples of #1336).

**Comment by dduportal** [comment]
Hi @thewilli , thanks for your interest! We want to avoid spreading issues on the same topic. Can we continue the discussion on #1336 please? Thanks for your understanding

**Comment by thewilli** [comment]
> We want to avoid spreading issues on the same topic. Can we continue the discussion on #1336 please?

@dduportal while my issue and the original issue are related, that are not about the same *solution*, i.e. my proposal won't lead to closing / resolving #1336. Let’s be realistic, there won‘t be a solution for the dynamic part any time soon - if ever. So why not give this one a chance for the time being?
