### ISSUE TITLE
how deploy Traefik2.0 on kubernetes

### ISSUE THREAD

**Issue by kong62** [containous/traefik#5602]
### Do you want to request a *feature* or report a *bug*?

Feature

**Comment by kong62** [comment]
I cannot  find any docs，please provide deploy Traefik2.0 on kubernetes docs

**Comment by LincolnBruce** [comment]
@kong62 https://traefik.io  @traefiker When to support etcd provider

**Comment by zerosym** [comment]
A bit scattered around their docs, but the needed information is there.

https://docs.traefik.io/user-guides/crd-acme/
https://docs.traefik.io/v2.0/providers/kubernetes-ingress/
https://docs.traefik.io/v2.0/providers/kubernetes-crd/

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by dduportal** [comment]
Hi! For information, we created another issue (#5627) to centralize the documentation needs as you requested it.

Thanks a lot for reporting and for the exchange of knowledge. We are sorry for the inconvience and hope the user experience will be improved with this!
