### ISSUE TITLE
Update to go-acme/lego to 3.1.0

### ISSUE THREAD

**Issue by dakky** [containous/traefik#5603]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [X] No

### What did you expect to see?
A proper DNS-01 cert request on ARM7 architecture

### What did you see instead?
a integer overflow which is fixed with lego 3.1.0

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.0.1
Codename:     montdor
Go version:   go1.13.1
Built:        2019-09-26T16:18:03Z
OS/Arch:      linux/arm
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

this update fixes the broken "dns-01 acme/ovh/arm7" setup

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
acme: error presenting token: ovh: error when call api to add record (/domain/zone/my.domain/record): json: cannot unmarshal number 5039775146 into Go struct field Record.id of type int\n" providerName=default.acme
```

**Comment by traefiker** [comment]
Closed by #5607.
