### ISSUE TITLE
Ingress Path Matching In Traefik v1.7+

### ISSUE THREAD

**Issue by zhaoguangqiang** [containous/traefik#5606]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I use k8s ingress with Traefik 1.7+. After migrating services to k8s. I found many ingress paths backend to one service. So i want to get a regex method to resolve this problem. But i cannot find it. Only found a method in ingress-nginx controller.

Ingress.yaml

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
spec:
  rules:
  - http:
      paths:
      **- path: /nc/v1/(routing|routeDiffusion).*$**
        backend:
          serviceName: route
          servicePort: 80

**Comment by dtomcej** [comment]
Hello @zhaoguangqiang,

The path can be set using a regex, however it has to be a go regexp.

From our documentation: https://docs.traefik.io/v1.7/basics/#matchers:

```
In order to use regular expressions with Host and Path matchers, you must declare an arbitrarily named variable followed by the colon-separated regular expression, all enclosed in curly braces. Any pattern supported by Go's regexp package may be used (example: /posts/{id:[0-9]+}).
```

I will close this issue, however, if you would like to further discuss configuration questions, please open a topic on our discussion forum: https://community.containo.us/

**Comment by zhaoguangqiang** [comment]
Thx, i have a try, it works

**Comment by zhaoguangqiang** [comment]
> Hello @zhaoguangqiang,
> 
> The path can be set using a regex, however it has to be a go regexp.
> 
> From our documentation: https://docs.traefik.io/v1.7/basics/#matchers:
> 
> ```
> In order to use regular expressions with Host and Path matchers, you must declare an arbitrarily named variable followed by the colon-separated regular expression, all enclosed in curly braces. Any pattern supported by Go's regexp package may be used (example: /posts/{id:[0-9]+}).
> ```
> 
> I will close this issue, however, if you would like to further discuss configuration questions, please open a topic on our discussion forum: https://community.containo.us/

Thx, i have a try, it works
