### ISSUE TITLE
macOs Catalina, Google Chrome TLS error  (NET::ERR_CERT_INVALID)

### ISSUE THREAD

**Issue by boesbo** [containous/traefik#5609]
OS: macOs 10.15
Chrome: Version 77.0.3865.90
Docker Engine: 19.03.2
Docker Compose: 1.24.1

**Traefik image:**
traefik:v1.7.16-alpine

**Docker compose command:**
`-c /dev/null --docker --logLevel=INFO --defaultEntryPoints='http,https' --entryPoints="Name:https Address::443 TLS" --entryPoints="Name:http Address::80"`

**Do you want to request a feature or report a bug?**
Bug

**What did you expect to see?**
Before the upgrade to macOs Catalina everything worked perfectly. Chrome detected a problem with the certificate but it kept me going.

Now Chrome gives me a blocking error (on firefox it keeps me going).

**Screenshots:**
![Screenshot 2019-10-09 at 12 18 27](https://user-images.githubusercontent.com/12744378/66473187-0cf33880-ea8f-11e9-81db-72f30a4b9901.png)
![Screenshot 2019-10-09 at 12 19 19](https://user-images.githubusercontent.com/12744378/66473197-1086bf80-ea8f-11e9-8e7d-b26dcdfd047a.png)

**Comment by dtomcej** [comment]
It appears cert-manager may have a similar issue: https://github.com/jetstack/cert-manager/issues/2168

**Comment by boesbo** [comment]
The problem is that the certificate is not good for the new Apple policies. Who should align?

https://support.apple.com/en-us/HT210176

**Comment by dtomcej** [comment]
Reproduced.

**Comment by traefiker** [comment]
Closed by #5662.
