### ISSUE TITLE
Case sensitive domain names breaks routing 

### ISSUE THREAD

**Issue by max-10001** [containous/traefik#562]
Case sensitive domain names breaks routing since all latest browsers do case insensitive lookup and send request to traefik with small case host name header(even if domain has upper case letters) and since traiefik does a case sensitive search it fails to locate the service/domain with lower case and returns 404. Don't you think traefik should also adhere to standards which browsers are following and do case insensitive search?

**Comment by emilevauge** [comment]
True, I will fix this in 1.1 ☺️

**Comment by Russell-IO** [comment]
@emilevauge I've been hitting this issue with acme registrations, I (finally) switched to using Traefik for all my personal stuff after using it for clients. 

My O365 email address is registered as Acmecorperation.com, which Traefik responded with the default Traefik certificate when routing for acmecorperation.com was configured.

This resulting in certificate prompts for all email users as they try to complete autodiscover lookups (Outlook only...) which worked fine on OSX, but on Windows... Prevented the clients from receiving email.

I resolved the issue, by simply creating a frontend for Acmecorperation.com, but this means I now have two certificates in my acme store for the same domain name

**Comment by Russell-IO** [comment]
@emilevauge Running latest build
sudo docker images | grep traefik
REPOSITORY           TAG                 IMAGE ID            CREATED             SIZE
traefik              v1.1.0-rc1          1f608d3f9975        12 days ago         15.88 MB

**Comment by emilevauge** [comment]
Fixed by #733
