### ISSUE TITLE
Traefik documentation on kubernetes installation 404

### ISSUE THREAD

**Issue by 3Golds** [containous/traefik#5635]
I found that traefik has a lot of links to the documentation deployed to kubernetes, and most of the sample `containers.args` have changed, and I hope to update the documentation as soon as possible, which will help me a lot.

 And, I hope that the helm chart can also be provided or updated.

 The meaning of the document is great.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
