### ISSUE TITLE
Support for MaxVersion parameter in tls.Options

### ISSUE THREAD

**Issue by kmeekva** [containous/traefik#5649]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Would like to be able to set MaxVersion in the tls.Options section of the traefik.toml similarly to how you can set MinVersion.  The MaxVersion options is not supported.

golang tls library has an option **MaxVersion** in the tls.Options config. https://golang.org/pkg/crypto/tls/#Config

**Use Case:**
While testing traefik v2.0.1 using client certificate authentication, we found some chrome clients had difficulty negotiating tls connections using the same tls options (ciphers) as we used successfully with traefik v.1.7.  The problem appears to be related to the attempted negotiation of   TLS13 downgrading  to TLS12  during negotiations, and chrome closing the connection.

To test, I created simple golang tls http server and verified that when I set MaxVersion to VersionTLS12  it connects successfully ( not attempting the TLS13 in the negotiation).  But if MaxVersion is set to TLS13 it tries TLS13 and then fails to downgrade to a TLS12 connection.  

I would like to be able to set the MaxVersion tls.option in traefik to work around this problem.

I have a pull request I will submit.

**Comment by ldez** [comment]
Closed by #5650
