### ISSUE TITLE
Error while Peeking first byte

### ISSUE THREAD

**Issue by kong62** [containous/traefik#5652]
### Do you want to request a *feature* or report a *bug*?
bug

### What did you do?
I deploy traefik 2.0.5 as daemonset(HostNetwork 80 and 443) on alicloud and txcloud，when use LoadBalance on alicloud and txcloud and turn on LoadBalance TCP healthcheck, the Traefik pod has a lot of errors.
I use wireshark to capture packets, loadbalancing uses tcp three-way handshake for health check, and RST is interrupted immediately after checked.

### Output of `traefik version`: (_What version of Traefik are you using?_)
2.0.5

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
k8s

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)
kubectl logs --tail=20 -n traefik -f traefik-4fcs2

time="2019-10-15T01:51:44Z" level=error msg="Error while Peeking first byte: read tcp 192.168.38.17:80->192.168.38.2:61659: read: connection reset by peer"
time="2019-10-15T01:51:44Z" level=error msg="Error while Peeking first byte: read tcp 192.168.38.17:80->192.168.38.2:42823: read: connection reset by peer"
time="2019-10-15T01:51:45Z" level=error msg="Error while Peeking first byte: read tcp 192.168.38.17:80->192.168.38.2:62255: read: connection reset by peer"
time="2019-10-15T01:51:45Z" level=error msg="Error while Peeking first byte: read tcp 192.168.38.17:80->192.168.38.2:51043: read: connection reset by peer"
time="2019-10-15T01:51:49Z" level=error msg="Error while Peeking first byte: read tcp 192.168.38.17:80->192.168.38.2:3104: read: connection reset by peer"
time="2019-10-15T01:51:49Z" level=error msg="Error while Peeking first byte: read tcp 192.168.38.17:80->192.168.38.2:47346: read: connection reset by peer"
time="2019-10-15T01:51:49Z" level=error msg="Error while Peeking first byte: read tcp 192.168.38.17:80->192.168.38.2:33006: read: connection reset by peer"
time="2019-10-15T01:51:50Z" level=error msg="Error while Peeking first byte: read tcp 192.168.38.17:80->192.168.38.2:18426: read: connection reset by peer"
time="2019-10-15T01:51:50Z" level=error msg="Error while Peeking first byte: read tcp 192.168.38.17:80->192.168.38.2:41629: read: connection reset by peer"
time="2019-10-15T01:51:50Z" level=error msg="Error while Peeking first byte: read tcp 192.168.38.17:80->192.168.38.2:37347: read: connection reset by peer"
time="2019-10-15T01:51:50Z" level=error msg="Error while Peeking first byte: read tcp 192.168.38.17:80->192.168.38.2:54091: read: connection reset by peer"
time="2019-10-15T01:51:50Z" level=error msg="Error while Peeking first byte: read tcp 192.168.38.17:80->192.168.38.2:16593: read: connection reset by peer"
time="2019-10-15T01:51:54Z" level=error msg="Error while Peeking first byte: read tcp 192.168.38.17:80->192.168.38.2:3195: read: connection reset by peer"

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

Issue templates help us help you by providing all necessary information.

Please edit your issue and use the available templates:

- [Feature request](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/Feature_request.md)
- [Bug report](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/Bug_report.md)

And remember: each time someone ignores the template, a cute little bunny dies.
<details>
<summary>#SaveTheCuteBunny :heart: :rabbit: :heart:</summary>

![southpark - estrella kill rabbit](https://user-images.githubusercontent.com/5674651/27143914-3cea7896-5130-11e7-81f8-02d8ac2da7a7.gif)

![southpark - estrella kill rabbit2](https://user-images.githubusercontent.com/5674651/27143924-49104c72-5130-11e7-82ae-ccedbd5dfa1c.gif)

</details>

**Comment by ihadeed** [comment]
In case it helps debug/resolve: I got this error trying to view the Traefik Dashboard with proxy protocol enabled on my load balancer.

Still haven't figured out why some apps on k8s don't like the proxy protocol.

**Comment by kong62** [comment]
who can help me?

**Comment by dduportal** [comment]
Hi @kong62 , your issue seems related to #5297 , but we are not completely sure as we are missing information for reproduction here.

Would you mind switching to our community forum to get help from the community? There is already a topic about this kind of errors as well: https://community.containo.us/t/error-while-peeking-first-byte-connection-reset-by-peer/1918 you might want to add your use case here.

Thanks a lot!
