### ISSUE TITLE
Bring back defaultEntryPoints in v2

### ISSUE THREAD

**Issue by snowzach** [containous/traefik#5672]
I would like to propose bringing back the defaultEntryPoints option in version 2. 

While it's not a huge deal to have to specify the entrypoints on your routers, having it default to every entrypoint if not specified can lead to unintended consequences. 

In my case, I have services opened to the internet and some opened internally. If I forget to specify the entrypoint option, it will open my internal services to the internet. It would be nice to have the defaultEntryPoints option again such that if it's forgotten or omitted, it will default to what it specified which might be more restrictive than just automatically enabling it for all entryPoints. 

Happy to work on a quick pull request if you give me some hints as to where you want it in the config and what files I should be looking at.

**Comment by sylr** [comment]
Related to https://github.com/containous/traefik/issues/5624

**Comment by dduportal** [comment]
Hi @snowzach , thanks for the feature request.

The `defaultEntrypoints` directive had a meaning in v1 when TLS options where set per entrypoint.
With v2, TLS being defined at router level + ability to route at TCP level, the default entrypoint does not make sense as it could break the TCP router, or accidentally mux HTTP/TCP.

This is why we're going to close this issue as declined.

**Comment by snowzach** [comment]
@dduportal couldn't this be considered at least for the base `http` option. The logs even sort of imply it should be a thing. I had some old docker labels in my config and started traefik v2 and by default: `No entryPoint defined for this router, using the default one(s) instead: [http https ext_http ext_https]` and I've just exposed a service to the internet that should never be open to the internet. It's just a safety net feature.
