### ISSUE TITLE
IngressRouteTCP cannot connect

### ISSUE THREAD

**Issue by kong62** [containous/traefik#5677]
'''
        # 为了 tcp 路由
        - --entrypoints.tcp.Address=:2222

        # 使用 tls 验证这种方式
        - --certificatesresolvers.default.acme.tlschallenge=true
        # 邮箱配置
        - --certificatesresolvers.default.acme.email=foo@you.com
        # 保存 ACME 证书的位置
        - --certificatesresolvers.default.acme.storage=acme.json
'''

'''
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  namespace: zabbix
  name: mariadb-server
  labels:
    app: mariadb-server
spec:
  entryPoints:
    - tcp
  routes:
  - match: HostSNI(`mariadb-server.ingress.hupu.io`)
    services:
    - name: mariadb-server
      port: 3306
  tls:
    passthrough: false
    secretName: mariadb-server-certs
or
  tls:
    passthrough: false
    certResolver: default
'''

telnet will hang：
'''
# telnet mariadb-server.ingress.hupu.io 2222
Trying 47.98.137.124...
Connected to mariadb-server.ingress.hupu.io.
Escape character is '^]'.
^]
telnet> quit
Connection closed.
'''

ncat will get mysql info:
'''
# ncat --ssl mariadb-server.ingress.hupu.io 2222 -v
Ncat: Version 7.50 ( https://nmap.org/ncat )
Ncat: SSL connection to 47.98.137.124:2222.
Ncat: SHA-1 fingerprint: C719 7766 EB40 EFA5 EEA6 EAFC 7793 490A 3EE9 3407
J
5.7.285/(v
N`+ftJ.mysql_native_password
'''

mysql cli will hang：
'''
# mysql -uroot -p -h mariadb-server.ingress.hupu.io        
Enter password: 

^C
root@mariadb-server-79f5949c6f-pd79c:/# ^C
'''

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
