### ISSUE TITLE
Doc / ACME: DNS Wildcard problems

### ISSUE THREAD

**Issue by denysvitali** [containous/traefik#5678]
Currently the [ACME Wildcard Domain description](https://docs.traefik.io/master/https/acme/#wildcard-domains) is really brief and doesn't really explain how to setup a wildcard certificate generation using a DNS provider:
![Screenshot 2019-10-17 at 13 48 26](https://user-images.githubusercontent.com/4939519/67006207-d055bb80-f0e4-11e9-9684-84405d330c03.png)

In the [Routers](https://docs.traefik.io/master/routing/routers/#domains) page there's a small paragraph explaining how to use a generated wildcard certificate, but there is no mention of [this](https://github.com/containous/traefik/pull/5320#issuecomment-529134760) anywhere.

In v1.7 apparently there was an `acme.domains` syntax. What I'm trying to do is to deploy a wildcard certificate like `*.subdomain.domain.tld` so that I don't neeed (or traefik doesn't need) to request a new certificate for every new host I'll add in the future. I'm obviously using the DNS-Challenge - but I still haven't found a way to generate a wildcard certificate and expect traefik to automatically use it when a `host.subdomain.domain.tld` is added.
```
[acme]
email = "dymkod@gmail.com"
entryPoint = "https"
storage = "/acme.json"
caServer = "https://acme-v02.api.letsencrypt.org/directory"
onHostRule = true
  [acme.dnsChallenge]
  provider = "vultr"
[[acme.domains]]
 main = "*.kaktus.host"
 sans = ["kaktus.host"]
```

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by denysvitali** [comment]
WTF.

**Comment by djmaze** [comment]
@denysvitali It has been documented [in the forum](https://community.containo.us/t/cant-create-letsencrypt-wildcard-certificates-with-traefik-2-0-0-beta1/976/2).

**Comment by denysvitali** [comment]
This issue is about a missing information in the documentation, and it was closed for no reason - I don't think that the forum is the right place to put the documentation...
