### ISSUE TITLE
Documentation missing for dyn-traefik config file

### ISSUE THREAD

**Issue by wimgoeman** [containous/traefik#5679]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I was trying to configure my own SSL certificates (no Acme). The docs refer to adding parameters to the dynamic configuration. The link to dynamic configuration only seems to show how to configure providers.

Eventually I fixed my issue by adding the config to dyn-traefik.yaml. I could not find this in the documentaton.

### What did you expect to see?

Have the documentation section of the dynamic config mention that 'dyn-traefik' is used as a filename.

### What did you see instead?

Only providers mentioned in documentation.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.0.2
Codename:     montdor
Go version:   go1.13.1
Built:        2019-10-09T19:26:05Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
Not applicable

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)
Not applicable

**Comment by ldez** [comment]
hello,

there are no hard-coded `dyn-traefik` as filename.

**Comment by wimgoeman** [comment]
I was wrong... Renaming the file got rid of my error, but that's simply because the config file is no longer being picked up. 

Where am I supposed to place this config on v2?

```
# Dynamic configuration

[[tls.certificates]]
  certFile = "/path/to/domain.cert"
  keyFile = "/path/to/domain.key"

[[tls.certificates]]
  certFile = "/path/to/other-domain.cert"
  keyFile = "/path/to/other-domain.key"
```

**Comment by wimgoeman** [comment]
Thanks for the response. That link does indeed point to what I was looking for. I guess I wasnt searching well enough.

**Comment by ldez** [comment]
Ok, you can join our support for more community support https://community.containo.us/
