### ISSUE TITLE
[Feature Request] middlewares for tcp routers

### ISSUE THREAD

**Issue by Shawak** [containous/traefik#5680]
I'm requesting middlewares for tcp routers so that we can use whitelisting on tcp routers.

Or is there any ETA already?

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Community Forum](https://community.containo.us/).

**Comment by dmaasland** [comment]
I second this request. Very silly that something this trivial isn't possible.

**Comment by mpl** [comment]
@dmaasland if it's that trivial, feel free to create a proposal and a PR for it. Thank you.
