### ISSUE TITLE
Discontinue TOML support

### ISSUE THREAD

**Issue by Kitanotori** [containous/traefik#5684]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Requesting discontinuation of a useless feature.

Reasons:

1. YAML is industry standard; no need for multiple configuration formats
2. TOML doesn't offer any benefit over YAML
3. TOML is a poor fit for highly nested configuration such as what Traefik tends to have
4. Maintaining code and documentation for both formats requires unnecessary effort
5. Having documentation showing examples in multiple formats is confusing for newcomers

**Comment by ldez** [comment]
Hello,

Traefik v2 support TOML and YAML

**Comment by Kitanotori** [comment]
@ldez I'm curious, what advantage does TOML have over YAML? Can anyone honestly say this kind of configuration is easy to read: https://docs.traefik.io/reference/dynamic-configuration/file/ ?

The language spec of TOML might be simple, but deciphering such nested configuration files is far from simple. In small projects without highly nested configuration structure, TOML might make sense, but I doubt it makes sense in this case. My main point is that having multiple configuration file formats creates confusion and discourages adoption.

Please at least consider making YAML the default and recommended option.

**Comment by SuperSandro2000** [comment]
I talked with a friend about this exact topic and toml makes sense when you don't have 3 level deep nested options but with traefik you easily have 5 or 6 levels deep at which toml repeats itself way to much.
