### ISSUE TITLE
traefik version command contains incorrect information when building from master branch

### ISSUE THREAD

**Issue by keiths-osc** [containous/traefik#569]
When building traefik from the master branch recently, I noticed that when I execute the `traefik version` command, the data displayed are the default hard coded values:

```
Version:      dev
Codename:     cheddar
Go version:   go1.6.3
Built:        I don't remember exactly
OS/Arch:      linux/amd64
```

I believe the problem is related to [this changeset](https://github.com/containous/traefik/commit/58b6d92ce28ec646a1e100bc9df6cccf495f0d71) moving the version-related variables out of the main package.

To fix, I think [this line](https://github.com/containous/traefik/blob/master/script/binary#L29) needs changed so that the variables that are being replaced contain the fully qualified package name, like this:

```
CGO_ENABLED=0 GOGC=off go build $FLAGS -ldflags "-s -w -X github.com/containous/traefik/version.Version=$VERSION -X github.com/containous/traefik/version.Codename=$CODENAME -X github.com/containous/traefik/version.BuildDate=$DATE" -a -installsuffix nocgo -o dist/traefik .
```

When I make that change locally, the version command seems to print the right stuff:

```
Version:      7abe68fac10ab42bbc59dddef622d730abff950a
Codename:     cheddar
Go version:   go1.6.3
Built:        2016-07-29_07:17:47PM
OS/Arch:      linux/amd64
```

I don't know Go all that well. I'd be willing to submit a pull request but I'm hoping someone from this project will comment whether this seems like the right fix.  I also wouldn't mind if someone just fixed it.  :)

**Comment by errm** [comment]
Looks like the correct fix to me, feel free to open a PR if you wish @keiths-osc
