### ISSUE TITLE
Regex is poorly documented 

### ISSUE THREAD

**Issue by rlewkowicz** [containous/traefik#5690]
### Do you want to request a *feature* or report a *bug*?

Bug

I would like a reference of all available HostRegexp options. I've pieced things together from the internet like ```rule = "HostRegexp(`{host:.*}`)"``` but where can I find all regex options? Can I just do ```HostRegexp(`*`)```? But for tcp it talks about an implicit `*` and thats just Host
<!--

**Comment by ldez** [comment]
Hello,

The explanation of the syntax and the pattern, does not that seem clear to you?

> Regexp Syntax
>
> In order to use regular expressions with `Host` and `Path` expressions, you must declare an arbitrarily named variable followed by the colon-separated regular expression, all enclosed in curly braces. Any pattern supported by [Go's regexp package](https://golang.org/pkg/regexp/) may be used (example: `/posts/{id:[0-9]+}`).


https://docs.traefik.io/v2.0/routing/routers/#rule

**Comment by rlewkowicz** [comment]
I didn't see that. Thank you
