### ISSUE TITLE
make "Skipping same configuration for provider docker" level DEBUG instead of INFO

### ISSUE THREAD

**Issue by hotzen** [containous/traefik#5693]
### Do you want to request a *feature* or report a *bug*?
feature / change of logging level of a specific message

### What did you expect to see?
instead of the current behaviour, which floods my INFO-logging with:
time="..." level=info msg="Skipping same configuration for provider docker" providerName=docker

i would hope that this becomes a DEBUG-level to stop spamming an INFO-log with non-information every 15 seconds...

**Comment by jairovsky** [comment]
There's a similar info log message a few lines above this one ("Skipping **empty** Configuration for provider ..."). Should it also be turned into a debug message?

**Comment by CybotTM** [comment]
With decline of https://github.com/containous/traefik/pull/5718 will this request also be declined?

**Comment by hotzen** [comment]
that would be consistent but makes absolutely NO sense - my log is getting spammed by this nonsense!

**Comment by SuperSandro2000** [comment]
> that would be consistent but makes absolutely NO sense - my log is getting spammed by this nonsense!

The quickest fix is to turn the debug output to warn when you don't need info. See https://github.com/containous/traefik/pull/5718#issuecomment-546395657

**Comment by mpl** [comment]
Closing, to be consistent with the decision to reject #5718
