### ISSUE TITLE
ProxyProtocol connection debug messages have level "info"

### ISSUE THREAD

**Issue by Owersun** [containous/traefik#5697]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Enabled ProxyProtocol in traefik and pointed external HAProxy to it

### What did you expect to see?

Log with requests with external IP's

### What did you see instead?

Four lines per request, one line of actual request logged and three debug lines of level "info":
```
time="2019-10-21T15:52:04Z" level=info msg="Trusted connection" entryPointName=http
time="2019-10-21T15:52:04Z" level=info msg="Use header remote addr" entryPointName=http
time="2019-10-21T15:52:04Z" level=info msg="Header parsed &{10.135.67.18:37306 10.135.77.105:80}" entryPointName=http
10.135.67.18 - - [21/Oct/2019:15:52:04 +0000] "GET / HTTP/1.0" - - "-" "-" 132 - - 0ms
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.0.2
Codename:     montdor
Go version:   go1.13.1
Built:        2019-10-09T19:26:05Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
    entryPoints:
      http:
        address: ':80'
        proxyProtocol:
          trustedIPs:
            - 10.0.0.0/8
    log:
      level: INFO
```

**Comment by traefiker** [comment]
Closed by #5712.
