### ISSUE TITLE
Traefik container + BoltDB backend - "Failed to test KV store connection"

### ISSUE THREAD

**Issue by nooproblem** [containous/traefik#570]
Docker run command:

```
docker run -d \
        --restart=always \
        -p 8080:8080 \
        -p 80:80 \
        -v $PWD/traefik.toml:/etc/traefik/traefik.toml \
        -v $PWD/traefik/v1.0.1/:/etc/traefik/ \
        --name traefik \
        traefik:v1.0.1
```

Boltdb config:

```toml
[boltdb]
endpoint = "/etc/traefik/traefik.db"
watch = true
prefix = "/traefik
```

One of many similar stderr output lines from docker logs:

```
time="2016-07-28T18:08:03Z" level=error msg="KV connection error: Failed to test KV store connection: Key not found in store, retrying in 33.964485548s"
```

Any thoughts or ideas in regard to where I might be going wrong or missing something will be greatly appreciated.

**Comment by emilevauge** [comment]
@nooproblem could you give us all your DEBUG logs ?

**Comment by nooproblem** [comment]
Hi thanks for your reply and sorry for the delay.

As requested, the logs with logLevel=DEBUG:
~~~
$   docker logs 6e0829d03a3c
time="2016-08-01T17:29:27Z" level=info msg="Traefik version v1.0.1 built on 2016-07-19_03:07:34PM"
time="2016-08-01T17:29:27Z" level=info msg="Using TOML configuration file /etc/traefik/traefik.toml"
time="2016-08-01T17:29:27Z" level=debug msg="Global configuration loaded {\"GraceTimeOut\":10,\"Debug\":false,\"AccessLogsFile\":\"\",\"TraefikLogsFile\":\"\",\"LogLevel\":\"DEBUG\",\"EntryPoints\":{\"http\":{\"Network\":\"\",\"Address\":\":80\",\"TLS\":null,\"Redirect\":null}},\"Constraints\":[],\"ACME\":null,\"DefaultEntryPoints\":[],\"ProvidersThrottleDuration\":2000000000,\"MaxIdleConnsPerHost\":200,\"Retry\":null,\"Docker\":null,\"File\":null,\"Web\":{\"Address\":\":8080\",\"CertFile\":\"\",\"KeyFile\":\"\",\"ReadOnly\":false},\"Marathon\":null,\"Consul\":null,\"ConsulCatalog\":null,\"Etcd\":null,\"Zookeeper\":null,\"Boltdb\":{\"Watch\":true,\"Filename\":\"\",\"Constraints\":null,\"Endpoint\":\"/etc/traefik/traefik.db\",\"Prefix\":\"/traefik\",\"TLS\":null},\"Kubernetes\":null}"
time="2016-08-01T17:29:27Z" level=info msg="Preparing server http &{Network: Address::80 TLS:<nil> Redirect:<nil>}"
time="2016-08-01T17:29:27Z" level=info msg="Starting provider *main.WebProvider {\"Address\":\":8080\",\"CertFile\":\"\",\"KeyFile\":\"\",\"ReadOnly\":false}"
time="2016-08-01T17:29:27Z" level=info msg="Starting provider *provider.BoltDb {\"Watch\":true,\"Filename\":\"\",\"Constraints\":null,\"Endpoint\":\"/etc/traefik/traefik.db\",\"Prefix\":\"/traefik\",\"TLS\":null}"
time="2016-08-01T17:29:27Z" level=info msg="Starting server on :80"
time="2016-08-01T17:29:27Z" level=error msg="KV connection error: Failed to test KV store connection: Key not found in store, retrying in 302.523189ms"
time="2016-08-01T17:29:28Z" level=error msg="KV connection error: Failed to test KV store connection: Key not found in store, retrying in 1.083936321s"
time="2016-08-01T17:29:29Z" level=error msg="KV connection error: Failed to test KV store connection: Key not found in store, retrying in 929.209959ms"
time="2016-08-01T17:29:30Z" level=error msg="KV connection error: Failed to test KV store connection: Key not found in store, retrying in 2.507125776s"
time="2016-08-01T17:29:32Z" level=error msg="KV connection error: Failed to test KV store connection: Key not found in store, retrying in 2.229036361s"
~~~
Any further thoughts or ideas in regard to where I might be going wrong or missing something will be greatly appreciated.

**Comment by CyrilPeponnet** [comment]
I have the same issue, I would like to use boltdb as a backend KV for a HA cluster deployment with compose v3:

```yaml
version: "3"
services:
  traefik:
    image: traefik:latest
    deploy:
      update_config:
        parallelism: 1
        delay: 10s
      mode: global
      placement:
        constraints: [node.role == manager]
    ports:
      - 80:80
      - 8080:8080
    networks:
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik_db:/db
    command: --docker -c /dev/null --docker.swarmmode --docker.domain=traefik --docker.watch --web --boltdb --boltdb.endpoint=/db/traefik.db --boltdb.watch --boltdb.prefix=traefik -l DEBUG

networks:
  backend:
      driver: overlay

volumes:
  traefik_db:
```

But I have the same error when starting:

```
time="2017-01-31T18:03:58Z" level=info msg="Traefik version v1.1.2 built on 2016-12-15_10:21:15AM"
time="2017-01-31T18:03:58Z" level=info msg="Using TOML configuration file /dev/null"
time="2017-01-31T18:03:58Z" level=debug msg="Global configuration loaded {\"GraceTimeOut\":10,\"Debug\":false,\"CheckNewVersion\":true,\"AccessLogsFile\":\"\",\"TraefikLogsFile\":\"\",\"LogLevel\":\"DEBUG\",\"EntryPoints\":{\"http\":{\"Network\":\"\",\"Address\":\":80\",\"TLS\":null,\"Redirect\":null,\"Auth\":null,\"Compress\":false}},\"Cluster\":{\"Node\":\"60a991c4-8fdc-40d9-ba82-32ff2c094939\",\"Store\":{\"Store\":{\"PersistConnection\":false},\"Prefix\":\"traefik\"}},\"Constraints\":[],\"ACME\":null,\"DefaultEntryPoints\":[\"http\"],\"ProvidersThrottleDuration\":2000000000,\"MaxIdleConnsPerHost\":200,\"InsecureSkipVerify\":false,\"Retry\":null,\"Docker\":{\"Watch\":true,\"Filename\":\"\",\"Constraints\":null,\"Endpoint\":\"unix:///var/run/docker.sock\",\"Domain\":\"traefik\",\"TLS\":null,\"ExposedByDefault\":true,\"UseBindPortIP\":false,\"SwarmMode\":true},\"File\":null,\"Web\":{\"Address\":\":8080\",\"CertFile\":\"\",\"KeyFile\":\"\",\"ReadOnly\":false,\"Auth\":null},\"Marathon\":null,\"Consul\":null,\"ConsulCatalog\":null,\"Etcd\":null,\"Zookeeper\":null,\"Boltdb\":{\"Watch\":true,\"Filename\":\"\",\"Constraints\":[],\"Endpoint\":\"/db/traefik.db\",\"Prefix\":\"traefik\",\"TLS\":null},\"Kubernetes\":null,\"Mesos\":null}"
time="2017-01-31T18:03:58Z" level=info msg="Preparing server http &{Network: Address::80 TLS:<nil> Redirect:<nil> Auth:<nil> Compress:false}"
time="2017-01-31T18:03:58Z" level=info msg="Starting provider *provider.Docker {\"Watch\":true,\"Filename\":\"\",\"Constraints\":null,\"Endpoint\":\"unix:///var/run/docker.sock\",\"Domain\":\"traefik\",\"TLS\":null,\"ExposedByDefault\":true,\"UseBindPortIP\":false,\"SwarmMode\":true}"
time="2017-01-31T18:03:58Z" level=info msg="Starting provider *main.WebProvider {\"Address\":\":8080\",\"CertFile\":\"\",\"KeyFile\":\"\",\"ReadOnly\":false,\"Auth\":null}"
time="2017-01-31T18:03:58Z" level=info msg="Starting provider *provider.BoltDb {\"Watch\":true,\"Filename\":\"\",\"Constraints\":[],\"Endpoint\":\"/db/traefik.db\",\"Prefix\":\"traefik\",\"TLS\":null}"
time="2017-01-31T18:03:58Z" level=info msg="Starting server on :80"
time="2017-01-31T18:03:58Z" level=debug msg="Node 60a991c4-8fdc-40d9-ba82-32ff2c094939 running for election"
time="2017-01-31T18:03:58Z" level=info msg="Node 60a991c4-8fdc-40d9-ba82-32ff2c094939 elected slave ♝"
time="2017-01-31T18:03:58Z" level=error msg="Leadership election error The current call is not supported with this backend, retrying in 294.608406ms"
time="2017-01-31T18:03:58Z" level=error msg="KV connection error: Failed to test KV store connection: Key not found in store, retrying in 388.808804ms"
time="2017-01-31T18:03:58Z" level=debug msg="Docker connection established with docker 1.13.0 (API 1.25)"
time="2017-01-31T18:03:58Z" level=debug msg="Filtering container without port and no traefik.port label proxy_traefik"
time="2017-01-31T18:03:58Z" level=debug msg="Configuration received from provider docker: {}"
time="2017-01-31T18:03:58Z" level=debug msg="Last docker config received more than 2s, OK"
time="2017-01-31T18:03:58Z" level=info msg="Server configuration reloaded on :80"
time="2017-01-31T18:03:59Z" level=info msg="Node 60a991c4-8fdc-40d9-ba82-32ff2c094939 elected slave ♝"
time="2017-01-31T18:03:59Z" level=error msg="Leadership election error The current call is not supported with this backend, retrying in 821.807238ms"
time="2017-01-31T18:03:59Z" level=error msg="KV connection error: Failed to test KV store connection: Key not found in store, retrying in 924.660999ms"
```

From what I see:

```
time="2017-01-31T18:03:58Z" level=error msg="Leadership election error The current call is not supported with this backend, retrying in 294.608406ms"
```

Looks like the HA clustering is not supported with boldb as a KV backend.

**Comment by traefiker** [comment]
I'll close the issue due to inactivity but feel free to re-open if needed.

**Comment by menew** [comment]
Hi, I've came across the same issue as @CyrilPeponnet by simply enabling BoltDB when evaluating traefik 7a141c8616a60414a048fe5cf7145d7f4e8a0d43 on my local environment.

    $ ./traefik version
    Version:      dev
    Codename:     cheddar
    Go version:   go1.9.2
    Built:        I don't remember exactly
    OS/Arch:      linux/amd64

    $ ./traefik storeconfig --debug --boltdb --boltdb.endpoint=/tmp/bolt.db
    2017/11/27 14:39:51 Storing configuration: {"LifeCycle":null,"GraceTimeOut":0,"Debug":true,"CheckNewVersion":true,"SendAnonymousUsage":false,"AccessLogsFile":"","AccessLog":null,"TraefikLogsFile":"","TraefikLog":null,"LogLevel":"ERROR","EntryPoints":{},"Cluster":null,"Constraints":[],"ACME":null,"DefaultEntryPoints":[],"ProvidersThrottleDuration":2000000000,"MaxIdleConnsPerHost":200,"IdleTimeout":0,"InsecureSkipVerify":false,"RootCAs":null,"Retry":null,"HealthCheck":{"Interval":30000000000},"RespondingTimeouts":null,"ForwardingTimeouts":null,"Web":null,"Docker":null,"File":null,"Marathon":null,"Consul":null,"ConsulCatalog":null,"Etcd":null,"Zookeeper":null,"Boltdb":{"Watch":true,"Filename":"","Constraints":[],"Trace":false,"DebugLogGeneratedTemplate":false,"Endpoint":"/tmp/bolt.db","Prefix":"/traefik","TLS":null,"Username":"","Password":""},"Kubernetes":null,"Mesos":null,"Eureka":null,"ECS":null,"Rancher":null,"DynamoDB":null,"Rest":null,"API":null,"Metrics":null,"Ping":null}

    $ sudo ./traefik --debug --boltdb --boltdb.endpoint=/tmp/bolt.db
    INFO[2017-11-27T14:40:18+09:00] Traefik version dev built on I don't remember exactly
    INFO[2017-11-27T14:40:18+09:00]
    Stats collection is disabled.
    Help us improve Traefik by turning this feature on :)
    More details on: https://docs.traefik.io/basic/#collected-data

    DEBU[2017-11-27T14:40:18+09:00] Global configuration loaded {"LifeCycle":{"RequestAcceptGraceTimeout":0,"GraceTimeOut":0},"GraceTimeOut":0,"Debug":true,"CheckNewVersion":true,"SendAnonymousUsage":false,"AccessLogsFile":"","AccessLog":null,"TraefikLogsFile":"","TraefikLog":null,"LogLevel":"DEBUG","EntryPoints":{"http":{"Network":"","Address":":80","TLS":null,"Redirect":null,"Auth":null,"WhitelistSourceRange":null,"Compress":false,"ProxyProtocol":null,"ForwardedHeaders":{"Insecure":true,"TrustedIPs":null}}},"Cluster":{"Node":"fe55c80e-4579-4122-9815-1bbdbc817f39","Store":{"Store":{"PersistConnection":false},"Prefix":"/traefik"}},"Constraints":[],"ACME":null,"DefaultEntryPoints":["http"],"ProvidersThrottleDuration":2000000000,"MaxIdleConnsPerHost":200,"IdleTimeout":0,"InsecureSkipVerify":false,"RootCAs":null,"Retry":null,"HealthCheck":{"Interval":30000000000},"RespondingTimeouts":null,"ForwardingTimeouts":null,"Web":null,"Docker":null,"File":null,"Marathon":null,"Consul":null,"ConsulCatalog":null,"Etcd":null,"Zookeeper":null,"Boltdb":{"Watch":true,"Filename":"","Constraints":[],"Trace":false,"DebugLogGeneratedTemplate":false,"Endpoint":"/tmp/bolt.db","Prefix":"/traefik","TLS":null,"Username":"","Password":""},"Kubernetes":null,"Mesos":null,"Eureka":null,"ECS":null,"Rancher":null,"DynamoDB":null,"Rest":null,"API":null,"Metrics":null,"Ping":null}
    INFO[2017-11-27T14:40:18+09:00] Preparing server http &{Network: Address::80 TLS:<nil> Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc4204703a0} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s
    INFO[2017-11-27T14:40:18+09:00] Starting provider *boltdb.Provider {"Watch":true,"Filename":"","Constraints":[],"Trace":false,"DebugLogGeneratedTemplate":false,"Endpoint":"/tmp/bolt.db","Prefix":"/traefik","TLS":null,"Username":"","Password":""}
    DEBU[2017-11-27T14:40:18+09:00] Node fe55c80e-4579-4122-9815-1bbdbc817f39 running for election
    INFO[2017-11-27T14:40:18+09:00] Node fe55c80e-4579-4122-9815-1bbdbc817f39 elected worker
    ERRO[2017-11-27T14:40:18+09:00] Leadership election error The current call is not supported with this backend, retrying in 481.551201ms
    INFO[2017-11-27T14:40:18+09:00] Starting server on :80
    DEBU[2017-11-27T14:40:18+09:00] Cannot get key /traefik/alias Key not found in store, setting default /traefik
    ERRO[2017-11-27T14:40:18+09:00] KV connection error: Failed to KV WatchTree: The current call is not supported with this backend, retrying in 415.055694ms
    DEBU[2017-11-27T14:40:18+09:00] Cannot get keys /traefik/frontends/ Key not found in store
    DEBU[2017-11-27T14:40:18+09:00] Cannot get keys /traefik/backends/ Key not found in store
    DEBU[2017-11-27T14:40:18+09:00] Cannot get keys /traefik/tlsconfiguration/ Key not found in store
    DEBU[2017-11-27T14:40:18+09:00] Configuration received from provider boltdb: {}
    INFO[2017-11-27T14:40:18+09:00] Server configuration reloaded on :80
    ERRO[2017-11-27T14:40:18+09:00] KV connection error: Failed to KV WatchTree: The current call is not supported with this backend, retrying in 793.367836ms
    INFO[2017-11-27T14:40:18+09:00] Node fe55c80e-4579-4122-9815-1bbdbc817f39 elected worker
    ERRO[2017-11-27T14:40:18+09:00] Leadership election error The current call is not supported with this backend, retrying in 1.001659088s
    ERRO[2017-11-27T14:40:19+09:00] KV connection error: Failed to KV WatchTree: The current call is not supported with this backend, retrying in 781.711434ms

As far as I can see, this issue occures because libkv does not support `WatchTree` on BoltDB backend. In other words, BoldDB seems not to support (a) clustering and (b) watching changes (hot-reload). Problem (a) causes `Leadership election error` and (b) causes `KV connection error: Failed to KV WatchTree`.

So, error (b) can be avoided by disabling watch with `--boltdb.watch=false` commnd line argument. But I could not find work around for (a) because following lines enable clustering forcibly if any of KVs are configured.
https://github.com/containous/traefik/blob/7a141c8616a60414a048fe5cf7145d7f4e8a0d43/cmd/traefik/traefik.go#L104-L125

To solve this issue, there are some different ways IMHO:

1. Deprecate BoltDB support at all.
2. Add option to disable clustering even if KV is used, and write limitations of BoltDB above in document.
3. Write some code to forbid clustering and watching on BoltDB.

What do you think about this?
