### ISSUE TITLE
Support logging of ingress namespace within the access logs

### ISSUE THREAD

**Issue by floriankoch** [containous/traefik#5701]
Feature

### What did you expect to see?
The access Log for a request should  logs the kubernetes namespace in which the ingress object exists

Use Case:
We use Elasticsearch / Kibana and restrict the access to the ingress  logs  to the developers who have access in the application namespace.

**Comment by dduportal** [comment]
Hi @floriankoch , we are sorry to decline this feature request, as Traefik is meant to be agnostic from providers. Access Logs cannot be tied to Kubernetes concepts or it would be quite a challenge for other providers.

To achieve your use case, I recommend you to take a look at tools as Loki from Grafana (https://grafana.com/oss/loki/), as it can links different data together.
