### ISSUE TITLE
SSL certificate chain is not properly presented to end user

### ISSUE THREAD

**Issue by Morishiri** [containous/traefik#5703]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
I'm using traefik on kubernetes infrastructure as Ingress controller.
I have bought official CA cert from `GlobalSign Root CA - R3`, which is signed by their intermediate cert  `AlphaSSL CA - SHA256 - G2`. To properly configure it on server side it is required to set the whole chain, which should then be presented to the user. I've created ingress resource containing both my domain cert and AlphaSSL CA cert in the format like this:
```
-----BEGIN CERTIFICATE-----
<- my cert ->
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
<- AlphaSSL CA cert ->
-----END CERTIFICATE-----
```

### What did you expect to see?

Command `openssl s_client -connect my-domain:443` being executed successfully with message:
`Verify return code: 0 (ok)`

### What did you see instead?

Command `openssl s_client -connect my-domain:443` returns error with message:
`Verify return code: 21 (unable to verify the first certificate)`. The same config works great with nginx ingress controller. It seems like traefik is presenting only the first cert, not both.
In browser it works, because browsers are able to search for proper chain on their own, but it fails on other tools (`curl`, `wget`, `npm`)

### Output of `traefik version`: (_What version of Traefik are you using?_)

Cannot exec easily, becuase in kubernetes it returns error. Dashboard shows:
```
v1.7.12 / maroilles
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Using traefik helm chart https://github.com/helm/charts/tree/master/stable/traefik. chart=traefik-1.70.2

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by Morishiri** [comment]
This is not a configuration problem.

**Comment by dduportal** [comment]
Hi @Morishiri , as only partial information is available (what is the Kubernetes cluster kind? topology? version? What is the state of the Traefik Deployment? How did you provide the secret? What is the Ingress?), we are unable to help you neither to confirm if it is a bug or a misconfiguration.

Could you open a topic on our community forum please? You would benefit from the community help? If it appears its a bug, we'll, of course, will re-open this issue with more context or reproduction.

Thanks for your understanding and your help in keeping the issue triage clean!
