### ISSUE TITLE
Missing information regarding mTLS

### ISSUE THREAD

**Issue by dash042** [containous/traefik#5716]
Hi,
I'm having trouble configuring traefik 2.0.2 for mTLS.
With 1.7 I had everything running.

How does the "secretCA" have to be created for traefik 2.0.2 to work?
Right now all I get are internal server errors...

Thank you!

`apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  name: default
  namespace: default
spec:
  clientAuth:
    secretNames:
      - secretCA
    clientAuthType: RequireAndVerifyClientCert
`

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
