### ISSUE TITLE
changes to the entrypoint whitelistsourcerange are ignored

### ISSUE THREAD

**Issue by johannges** [containous/traefik#5719]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I am using the Helm Stable Traefik chart, with traefik in Version 1.7.14.

When i add an IP  to the whitelistsourcerange and update the release, the IP will be added to the Consul Keystore. But the IP will not work, till i remove all Traefik Pods by hand.

When i remove an IP from the whitelistsourcerange and update the release, the IP will not be removed from the Consul Keystore. Even after manual removing the IP from the Consul Keystore, the IP will have Access, till i remove all Traefik Pods by hand.

### What did you expect to see?

After adding a IP to the entrypoint whitelistsourcerange, i exprected for that IP to have Access.
After removing a IP from the entrypoint whitelistsourcerange, i exprected for that IP to have no Access.

### What did you see instead?

No Change, till manual removal of the pods

No Change, till manual removal of the IP from the Consul Keystore and of the pods

### Output of `traefik version`: (_What version of Traefik are you using?_)

Docker Image:  traefik:1.7.18

**Comment by dduportal** [comment]
Hi @johannges , it looks like an issue in the Helm chart at https://github.com/helm/charts/tree/master/stable/traefik.

Could you provide us more information to help for reproduction (and eventually leading to fix the helm chart)?

We would need the `values.yaml` used for your release, and the description of the Traefik Objects (deployment, jobs) to help us analyze the problem?

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Community Forum](https://community.containo.us/).
