### ISSUE TITLE
How do I bind Path to Service ? 

### ISSUE THREAD

**Issue by lx0758** [containous/traefik#5741]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

For example, I want to bind domain.org/s1 to the service 127.0.0.1:8080, and then bind domain.org/s2 to the service 127.0.0.1:8081.

I use the version of Traefik v2.0.2 and run it with a docker-compose.

I have tried the following configuration:
# one/docker-compose.yaml
```yaml
...
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.traefik_http.rule=Host(`domain.org`) && Path(`/traefik`)"
    - "traefik.http.routers.traefik_http.entrypoints=http"
    - "traefik.http.routers.traefik_https.rule=Host(`domain.org`) && Path(`/traefik`)"
    - "traefik.http.routers.traefik_https.entrypoints=https"
    - "traefik.http.routers.traefik_https.tls.certresolver=acme-resolver"
    - "traefik.http.services.traefik.loadbalancer.server.port=8080"
...
```

# two/docker-compose.yaml
```yaml
...
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.portainer_http.rule=Host(`domain.org`) && Path(`/portainer/`)"
    - "traefik.http.routers.portainer_http.entrypoints=http"
    - "traefik.http.routers.portainer_https.rule=Host(`domain.org`) && Path(`/portainer/`)"
    - "traefik.http.routers.portainer_https.entrypoints=https"
    - "traefik.http.routers.portainer_https.tls.certresolver=acme-resolver"
    - "traefik.http.services.portainer.loadbalancer.server.port=9000"
...
```

As shown above, I also tried replacing Path with PathPrefix, but it didn't work. Both returned 404.

In addition, the 8080 above is actually Traefik itself, 9000 is portainer;If they were given separate subdomains they would all be working fine, obviously the Traefik agent is responsible for the breakdown.

Please help me, I'm going crazy...

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by lx0758** [comment]
[https://docs.traefik.io/v2.0/middlewares/stripprefix/](https://docs.traefik.io/v2.0/middlewares/stripprefix/)

It is okay.
