### ISSUE TITLE
WebUI: Providers tabs disappeared

### ISSUE THREAD

**Issue by emilevauge** [containous/traefik#577]
Since #558, providers tabs are not visible anymore in the webUI:

`docker run --rm -it --net host -v /var/run/docker.sock:/var/run/docker.sock containous/traefik:v1.0.1 --web -d --docker`

![capture du 2016-08-01 15 28 43](https://cloud.githubusercontent.com/assets/6207234/17295517/c5a3c648-57fc-11e6-99f4-a1c6158ee6ce.png)

`docker run --rm -it --net host -v /var/run/docker.sock:/var/run/docker.sock containous/traefik:experimental --web -d --docker`

![capture du 2016-08-01 15 30 09](https://cloud.githubusercontent.com/assets/6207234/17295539/db7b51ac-57fc-11e6-8cc8-d84bb02725fd.png)

Any idea @micaelmbagira ?

**Comment by micaelmbagira** [comment]
Right, I upgraded `angular-bootstrap` to `angular-ui-bootstrap` and forgot to change directives name !
