### ISSUE TITLE
HTTP -> HTTPS for a specific URL, only?

### ISSUE THREAD

**Issue by dm17** [containous/traefik#5772]
Slightly more verbose way to ask: Is there any way to make Traefik not forward HTTP -> HTTPS for a specific URL, only (while continuing to forward the rest to HTTPS)?
 
I'm going to switch from nginx if I can do this on traefik. Do you know if it is possible? And if so, then how? I've been trying with nginx here: https://github.com/jwilder/nginx-proxy/issues/1340

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by dm17** [comment]
I've opened a thread on the forum about it:
https://community.containo.us/t/http-https-for-a-specific-url-only/2829
