### ISSUE TITLE
Add tracing headers to forwardAuth middleware

### ISSUE THREAD

**Issue by aliksend** [containous/traefik#5774]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Add tracing headers to forwardAuth middleware. It will be nice to see traces and logs from my authorization service in full request trace.

**Comment by wdalmut** [comment]
:+1:

**Comment by aliksend** [comment]
I'll create PR for it

**Comment by traefiker** [comment]
Closed by #6072.
