### ISSUE TITLE
Traefik 2 - entryPoints for Kubernetes Ingress Controller

### ISSUE THREAD

**Issue by tlvenn** [containous/traefik#5790]
Hi,

At the moment, k8s ingresses are exposed through all the entrypoints, it would be great if we could configure over which entrypoints they should be exposed as an additional provider configuration.

**Comment by ldez** [comment]
Duplicate of #5624

**Comment by tlvenn** [comment]
My bad, did not see the other issue, thanks for the consolidation @ldez !
