### ISSUE TITLE
Uber-Trace-Id Header Not In Forward Auth Request When Using Jaeger Tracing

### ISSUE THREAD

**Issue by jralph** [containous/traefik#5793]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Setup Traefik using jaeger for opentracing and used forward auth.

### What did you expect to see?

I expected to see the `uber-trace-id` header in the request that is made from traefik to the forward auth target, and the `uber-trace-id` header returned by the forward auth target to be passed to the service, or a new span created from the previous span.

### What did you see instead?

No `uber-trace-id` header is sent to the forward auth target.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.0.4
Codename:     montdor
Go version:   go1.13.3
Built:        2019-10-28T20:23:57Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```
--log.level=DEBUG
--api.insecure=true
--providers.docker=true
--providers.docker.exposedbydefault=false
--entrypoints.web.address=:80
--tracing.jaeger=true
--tracing.jaeger.samplingServerURL=http://jaeger-agent:5778/sampling
--tracing.jaeger.samplingType=const
--tracing.jaeger.samplingParam=1.0
--tracing.jaeger.localAgentHostPort=jaeger-agent:6831
```

**Comment by dduportal** [comment]
Hi! This is feature not yet implemented, please check #5774 for this.
