### ISSUE TITLE
Documentation: Whitelisting not accurate enough

### ISSUE THREAD

**Issue by jmkgreen** [containous/traefik#5816]
### Do you want to request a *feature* or report a *bug*?

Documentation Bug

This concerns 1.x (1.7 specifically being used here) but may also apply to 2.x, and concerns the documentation more than the software.

### What did you do?

We added our AWS VPC CIDR to our whitelisting.

### What did you expect to see?

Secure access to backends from selected IP ranges and from other resources within our VPC deployment.

### What did you see instead?

In addition, we spotted we were now able to access protected resources from anywhere.

At this point, allow me to elaborate.

We have a VPC with an _internal_ ALB. Traffic from the outside world is routed in via a Global Accelerator. We use ECS a lot, so applied Docker Labels to containers to advertise themselves and apply source range whitelisting with X-Forwarded-For headers.

Initially, this worked fine to allow private access from say our office IP. But then we realised we have "sibling" resources within the VPC also needing to make connections so added our private IP CIDR range and asked the clients to reach us via the ALB. This, too, worked.

But, and here is the crux of this ticket: it seems by switching on x-forwarded-for, we are not asking Traefik to *only* examine x-forwarded-for, but add the x-forwarded-for headers to the source addresses of the traffic being inspected. If only the x-forwarded-for headers where used, traffic from foreign parties would never match, but because it's additive the ALB's own source IP addresses match too. Whoops.

Perhaps explain in the documentation that source range is always the source of the TCP transmission, and that switching on x-forwarded-for ADDS to this address, and does not REPLACE them.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
1.7.18
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

AWS with Global Accelerator linked to an _internal_ Application Load Balancer forwarding to various Traefik instances hosted by ECS.

Docker labels (CloudFormation in use):
```
traefik.frontend.whiteList.useXForwardedFor: "true"
traefik.frontend.whiteList.sourceRange: !Join [", ", [!Ref SourceIPRangesStaff,  "172.20.0.0/16"]] # 172.20/16 is our CIDR
```

By allowing our CIDR, it allows all traffic passing through the ALB in, too.

**Comment by traefiker** [comment]
Closed by #6571.
