### ISSUE TITLE
502 Bad Gateway an all services

### ISSUE THREAD

**Issue by enevole** [containous/traefik#5829]
I just set up the same solution we are running on some other data centers without any issues.
However, all the services just return "Bad Gateway" in the browser.

This is a docker swarm network, and Traefik is running on the swarm manager.
We are running Traefik v2.0.4 
Docker is running version 19.03.4

Traefik is launched through a stack with the following configuration:

version: '3.7'

volumes::
  traefik:
    image: traefik
    command: 
      - "--api=true" 
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--ping"
      - "--providers.docker=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.network=traefik-public"
      - "--providers.docker.swarmMode=true"
      - "--entrypoints.web.address=:80"
      - "--accesslog=true"
      - "--accesslog.bufferingsize=100"
      - "--accesslog.filepath=/var/log/traefik.log"
      - "--metrics.prometheus=true"
      - "--entryPoints.metrics.address=:8082"
      - "--metrics.prometheus.entryPoint=metrics"
      - "--metrics.prometheus.buckets=0.1,0.3,1.2,5.0"
      - "--tracing.jaeger=true"
      - "--tracing.jaeger.samplingServerURL=http://localhost:5778/sampling"
      - "--tracing.jaeger.samplingType=const"
      - "--tracing.jaeger.samplingParam=1.0"
      - "--tracing.jaeger.localAgentHostPort=127.0.0.1:6831"
      - "--tracing.jaeger.propagation=jaeger"
      - "--tracing.jaeger.traceContextHeaderName=uber-trace-id"
networks:
  monitor-net:
  traefik-public:
    driver: overlay
    external: true

And then a service is added through another stack with the following configuration. This is running on a docker node in the swarm:

version: '3.7'
services:
  frontend:
    image: enevodocker/enevoleadsfe:production
    ports:
      - 80
    environment:
      - SERVICE_PORTS=80
    deploy:
      labels:
        - "traefik.http.routers.portalproxy.rule=Host(`myportal.no`)"
        - "traefik.http.services.portalservice.loadbalancer.server.port=80"
        - "traefik.docker.network=traefik-public"
      replicas: 4
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 2
        window: 60s
      placement:
        constraints: [node.role != manager]
    networks:
      - web
      - traefik-public
    labels:
      - "traefik.docker.network=traefik-public" 

When I inspect the traefik container, as well ad the frontend container, both are connected to the traefik-public networks.

Now, if I visit http://myportal.no it just returns "bad gateway". 

I am now stuck in debugging this, and can't find anything to go further with. 
I have tried deleting the network, adding it again, deleting the stacks and adding them again and so on. 

Anyone with any further suggestions?

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
