### ISSUE TITLE
HTTP -> HTTPS redirection based on X-Forwarded-Proto Header

### ISSUE THREAD

**Issue by Fabian-K** [containous/traefik#5830]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

When running Traefik behind a load balancer that performs SSL termination, I want to be able to send a redirect from HTTP to HTTPS.

The current middleware RedirectScheme uses the schema to send a redirect. With a load balancer that uses SSL termination, the schema, however, is always HTTP for traefik. To indicate whether it originally was an HTTP or an HTTPS request, many load balancers set the `X-Forwarded-Proto` header accordingly.

Doing the redirection at the load balancer itself is not always supported. The GCP HTTP load balancer, for example, does not support it. IMO it makes sense to have a Middleware that sends redirects based on the `X-Forwarded-Proto` header.

**Comment by ldez** [comment]
Hello,

I answered to this issue on the forum: 
https://community.containo.us/t/http-https-redirection-based-on-x-forwarded-proto-header/2908/4
