### ISSUE TITLE
How to configuration traefik handle assets 404 when use sub path

### ISSUE THREAD

**Issue by cutiechi** [containous/traefik#5838]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you expect to see?
I want to configuration my service under xx.xx.com with path /application, but when i visit http://xx.xx.com/application the assets not working with 404.

Because  xx.js under /, not /application/.

How to fix it?

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
