### ISSUE TITLE
Does træfɪk support TLS certificate revocation?

### ISSUE THREAD

**Issue by adamkrellenstein** [containous/traefik#586]
Specifically for mutual authentication?

References:
- http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_crl
- https://jamielinux.com/docs/openssl-certificate-authority/certificate-revocation-lists.html

**Comment by Juliens** [comment]
You can use the redirect in entrypoint configuration

https://docs.traefik.io/toml/#entrypoints-definition

```
# [entryPoints]
#   [entryPoints.http]
#   address = ":80"
#     [entryPoints.http.redirect]
#       regex = "^http://localhost/(.*)"
#       replacement = "http://mydomain/$1"
```

**Comment by samgurtman** [comment]
Can anyone answer this?

**Comment by traefiker** [comment]
I'll close the issue due to inactivity but feel free to re-open if needed.
