### ISSUE TITLE
Error when execute the command: npm run dev，in webui folder

### ISSUE THREAD

**Issue by sunnycreate** [containous/traefik#5864]
### Do you want to request a *feature* or report a *bug*?
bug

I tried two computer(win 10 system),both have the same problem.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
(paste your output here)
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# (paste your configuration here)
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
npm run dev

> traefik-ui@2.0.0 dev D:\WS\traefik\webui
> export APP_ENV='development' && quasar dev -m pwa

'export' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! traefik-ui@2.0.0 dev: `export APP_ENV='development' && quasar dev -m pwa`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the traefik-ui@2.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
