### ISSUE TITLE
allow proxy to external URLs

### ISSUE THREAD

**Issue by JavierPandu** [containous/traefik#5869]
### Do you want to request a *feature* or report a *bug*?
feature

Feature

### What did you expect to see?
I'm very surprised I can't proxy to my front ends allocated in amazon's s3. Why has this been removed in v2? I see someone else raised this concern and never got an answer!
I believe this will be a very common use case, could you please clarify if this is in the roadmap or will never come?

**Comment by ldez** [comment]
Duplicate of #4674
