### ISSUE TITLE
Traefik don't find my service with HEALTHCHECK

### ISSUE THREAD

**Issue by batazor** [containous/traefik#5877]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

My Dockerfile:

```
FROM alpine:latest

# 7070: API
# 9090: metrics
EXPOSE 7070 9090

// ... building my application

HEALTHCHECK \
  --interval=3s \
  --timeout=3s \
  CMD curl -f http://localhost:9090/ready || exit 1

WORKDIR /app/
CMD ["./app"]
```

my docker-compose.yaml:

```
version: '2.4'

services:

  shortlink:
    build: .
  labels:
    - "traefik.enable=true"

  traefik:
    image: ....
```

If I use `HEALTHCHECK` in my Dockerfile then Traefik ignore my service
If delete `HEALTHCHECK` from Dockerfile then Traefik find my service

### What did you expect to see?

Traefik find my service

### What did you see instead?

Traefik ignore my service

### Output of `traefik version`: (_What version of Traefik are you using?_)

image: traefik:v2.0

```
Digest: sha256:380d2eee7035e3b88be937e7ddeac869b41034834dcc8a30231311805ed9fd22
Status: Downloaded newer image for traefik:2.0
Version:      2.0.5
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# default
```

```
      TRAEFIK_API_INSECURE: "true" # Don't do that in production
      TRAEFIK_PROVIDERS_DOCKER: "true"
      TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT: "false"
      TRAEFIK_ACCESSLOG: "true"
      TRAEFIK_ACCESSLOG_FORMAT: json
      TRAEFIK_METRICS_PROMETHEUS: "true"
      TRAEFIK_PING: "true"
      TRAEFIK_TRACING_JAEGER: "true"
      TRAEFIK_TRACING_JAEGER_GEN128BIT: "true"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by batazor** [comment]
Solve my problem https://stackoverflow.com/questions/47722898/how-to-do-a-docker-healthcheck-with-wget-instead-of-curl
