### ISSUE TITLE
Changelog "all commits" for 2.1 releases is against 2.0.0-rc1

### ISSUE THREAD

**Issue by neclimdul** [containous/traefik#5878]
### What did you do?

When looking at the changelog for RC1 and RC2(https://github.com/containous/traefik/blob/master/CHANGELOG.md) the "All Commits" links are a little weird. They diff against 2.0.0-rc1 which doesn't give a lot of useful information. 
https://github.com/containous/traefik/blob/master/CHANGELOG.md

### What did you expect to see?
For RC2 I expected to see the commits against RC1. For RC1 I would have expected some later version of the 2.0.0 branch instead of RC1 but I'm not sure how that's generally handled for your releases.

### What did you see instead?
As said above, the entire commit logs for the 2.0.0 branch as part of the 2.1.0 branch changelog links.

### Output of `traefik version`: (_What version of Traefik are you using?_)
n/a

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
n/a

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)
n/a

**Comment by ldez** [comment]
Hello,

the links are right:
- the v2.1.0-rc1 commits are from the branch master tag v2.0.0-rc1 to the branch master tag v2.1.0-rc1
- because of an error during the build v2.1.0-rc1, the v2.1.0-rc1 has been skipped. so the v2.1.0-rc2 link is also right.
