### ISSUE TITLE
Rancher 1.6.11 upgraded status not being picked up by traefik

### ISSUE THREAD

**Issue by maxifom** [containous/traefik#5886]
### Do you want to request a *feature* or report a *bug*?
Bug

### What did you do?
I have a service with 1 nginx container without health check on it. When I press upgrade, and it gets upgraded status, traefik doesn't catch it, and in dashboard I can see old container IP, so the server return Service Unavailable error.

### What did you expect to see?
Working service after upgraded status and new container start.

### What did you see instead?
New container not being picked up by traefik and received a Service Unavailable error when trying to navigate to the container label host.

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
Version:      2.0.5
Codename:     montdor
Go version:   go1.13.4
Built:        2019-11-14T18:11:01Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
I have a rancher 1.6.11 with 6 debian 9 hosts. Traefik version is v.2.0.5, started up as global container on all 6 hosts with open port 80. 
CLI Flags (No TOML/YAML file is passed):
```
--providers.rancher=true
--providers.rancher.exposedByDefault=false
--providers.rancher.enableServiceHealthFilter=true
--providers.rancher.intervalPoll=false
```

**Comment by SantoDE** [comment]
Hello @maxifom,

I can not reproduce your issue. If I upgrade a service and keep it in state "upgraded", my Traefik picks up the new container IP and routing still work.

Can you please give me your service definition? When do you see the "old" container ip? 

Thanks.

**Comment by maxifom** [comment]
I dk what the issue was, but now I checked again, and everything seems to be in order, container upgraded status handled successfully.
