### ISSUE TITLE
Docker Swarm Mode cannot scan self labels

### ISSUE THREAD

**Issue by lx0758** [containous/traefik#5889]
### Do you want to request a *feature* or report a *bug*?
*bug*

Bug

### What did you do?
use docker swarm deploy treafik:v2.0.5 , but its own tag does not work, and the tags of other services are recognized.

### Output of `traefik version`: (_What version of Traefik are you using?_)
Traefik:v2.0.5 for docker

```
(paste your output here)
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# (paste your configuration here)
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
