### ISSUE TITLE
accesslog add http request fields and ability to replace fields with other fields

### ISSUE THREAD

**Issue by Aqualie** [containous/traefik#5892]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?
Currently we choose from a predefined list of available access log fields listed here: https://docs.traefik.io/observability/access-logs/#limiting-the-fields
This does not allow us to for example specify other fields like for example "http_x_forwarded_for" or "http_cf_connecting_ip" both which are commonly used when behind a Cloudflare deployment. 

As a result of this limitation all access logs currently are not viable when deployment behind CF as it will just show the CF IP address and not the real users IP address (this is under the HTTP header CF_CONNECTING_IP). In nginx I can simply modify the format and replace the default remote_ip field with the correct name. It would be nice if we could do the same in traefik as well.

**Comment by juliens** [comment]
The `available fields` in the documentation, is for the `[accessLog.fields.names]` but doesn't apply to the `[accessLog.fields.headers.names]`, so you can specify any headers you want.
 If you want more information on this, please join our [Community Forum](https://community.containo.us/).
