### ISSUE TITLE
Using marathon backend , accessing https and wss on the same port

### ISSUE THREAD

**Issue by prasadnadendla** [containous/traefik#590]
Hi,

I am using marathon as backend, I have configured an application from marathon UI, Application has the ablitiy to process both **https** and **wss**( websocket secure channel) calls. If is set **traefik.protocol=https** then only https calls are processing successfully and If is set **traefik.protocol=wss** then **wss** calls are processing successfully but not **https** calls. How can i configure from marathon API to access both **https** and **wss** calls?

**Comment by mcoms** [comment]
I don't think this is backend-specific. Also having the same problem with the Docker backend.

[Rails' ActionCable](https://github.com/rails/rails/tree/master/actioncable) accepts both HTTP and WS on the same port (ws://.../cable by default).

**Comment by ldez** [comment]
I'll close the issue due to inactivity but feel free to re-open if needed.
