### ISSUE TITLE
No ACME certificate generation required for domains when using DNSChallenge behind a NAT

### ISSUE THREAD

**Issue by dimisjim** [containous/traefik#5912]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

My goal is to be able to generate ssl certificates with Traefik, for a service that runs inside an AWS VPC that is behind a NAT. I think the only way to have a cert with Traefik, is to use the dnsChallenge method. 

### What did you expect to see?

A cert successfully being generated.

### What did you see instead?

When I attempted to run traefik alongside the other services (Grafana, InfluxDB), Traefik was stuck at: `"No ACME certificate generation required for domains [\"xx.my-domain.tld\"]."`

This is also the  output when trying to run it from within a physical network, again bounded by a NAT. When tried to do the same from a network with an internet gateway, it worked fine.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
2.0.4 and 2.0.5
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

I am launching Traefik using a docker-compose yaml with the following labels:
```
- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--certificatesresolvers.ssl.acme.dnsChallenge=true"
      - "--certificatesresolvers.ssl.acme.dnsChallenge.provider=route53"
      - "--certificatesresolvers.ssl.acme.dnsChallenge.delayBeforeCheck=0"
      - "--certificatesresolvers.ssl.acme.email=my-mail@my-domain.com"
      - "--certificatesresolvers.ssl.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.ssl.acme.caServer=https://acme-v02.api.letsencrypt.org/directory"
```

and for the service:
```
- "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`my-domain`)"
      - "traefik.http.routers.grafana.entrypoints=http"
      - "traefik.http.routers.grafana.middlewares=redirect"
      - "traefik.http.middlewares.redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.grafana2.rule=Host(`my-domain`)"
      - "traefik.http.routers.grafana2.entrypoints=https"
      - "traefik.http.routers.grafana2.tls.certresolver=ssl"
```

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
