### ISSUE TITLE
Build ('make') does not work from release

### ISSUE THREAD

**Issue by dellelce** [containous/traefik#5914]
### Do you want to request a *feature* or report a *bug*?

This is a bug by my point of view, but it could be a "feature" by someone's else  point of view... considering that usually you would expect that source in "releases" to be buildable I'll stick to "bug".

Bug

### What did you do?

1. download "release"  (2.0.5) source from github releases "section"
2. untar
3. 'make' in directory
 

### What did you expect to see?

A nice big binary

### What did you see instead?

(this is with added ```set -x``` in script/binary)

```bash
Successfully built fa2e6e1a9247
Successfully tagged traefik-dev:master
docker run  -e "TEST_CONTAINER=1" -v "/var/run/docker.sock:/var/run/docker.sock" -it -e OS_ARCH_ARG -e OS_PLATFORM_ARG -e TESTFLAGS -e VERBOSE -e VERSION -e CODENAME -e TESTDIRS -e CI -e CONTAINER=DOCKER            -v "/projects/root/web/tmp/291119_traefik/traefik-2.0.5/"dist":/go/src/github.com/containous/traefik/"dist"" "traefik-dev:master" ./script/make.sh generate binary
---> Making bundle: generate (in /go/src/github.com/containous/traefik/script)

---> Making bundle: binary (in /go/src/github.com/containous/traefik/script)
++ test -e autogen/genstatic/gen.go
++ rm -f dist/traefik
++ FLAGS=()
++ '[' -n '' ']'
++ '[' -z '' ']'
+++ git rev-parse HEAD
fatal: not a git repository (or any of the parent directories): .git
++ VERSION=
make: *** [binary] Error 128
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

Sadly not possible

```
(paste your output here)
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Not applicable.

```toml
# (paste your configuration here)
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```

**Comment by ldez** [comment]
Hello,

the "sources" are added by GitHub it-self when we create a release.

It's not possible to disable this behavior.

You can use the sources from the git repo instead of the tarball.
