### ISSUE TITLE
Specify period for rate limiting on v2

### ISSUE THREAD

**Issue by Fabian-K** [containous/traefik#5918]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

1.7 supported to specify periods for rate-limiting, e.g. 10 requests per 60 seconds (https://docs.traefik.io/v1.7/configuration/commons/#rate-limiting). I don't see this functionality with v2 and the rate limit middleware (https://docs.traefik.io/middlewares/ratelimit/). 

Was this removed intentionally? Is the smallest possible rate limit with v2 therefore 1 per second?

**Comment by finndev** [comment]
Wondering the same.

It is not a docs bug too, the functionality is gone. R

**Comment by mpl** [comment]
@Fabian-K Yes, it was removed intentionally as golang.org/x/time/rate (and other algorithms we looked at) has no notion of such a period, and it did not seem useful to us to keep that notion. Is there anything you cannot achieve without such a notion?

And yes the minimum rate limit is indeed 1req/s. Is that a problem?

**Comment by Fabian-K** [comment]
Thanks for the insight. A minimum rate of 1/s might sound reasonable looking at seconds only, however this also means that its min of 3600/hour. Also I assume this is a local limit so it multiplies with the number of traefik instances.

Thinking about this, I might be rather looking for something like a "Budget/Quota" where lower values than thousands per hour make sense...

**Comment by finndev** [comment]
It is a problem for us. Maybe we can achieve it with another way we didn't find yet, but we use Traefik as our entrypoint for all our services, and sometimes we get DDoSd and we used this to rate limit users, e.g. 20req/60s. This seems to be not possible anymore in Traefik v2.

**Comment by mpl** [comment]
@Fabian-K and have you had any trouble with a rate of 3600/h so far?

**Comment by mpl** [comment]
@finndev I understand it's not exactly equivalent, but have you tried with a rate of 1req/s (and maybe with a burst of 20)? Would you still get DDoSd with such a configuration?

**Comment by Fabian-K** [comment]
> @Fabian-K and have you had any trouble with a rate of 3600/h so far?
That is too high, I want to aggressively limit traffic from certain regions (there should be no traffic from those regions) to something like a few requests per minute

**Comment by mpl** [comment]
@Fabian-K we think it might be possible to let you configure the rate as a float (e.g. 0.016 req/s). Would that help your use case if you could do that?

**Comment by Fabian-K** [comment]
Yes, that sounds promising!
