### ISSUE TITLE
traefik 2.1 dashboard  not show  is 404

### ISSUE THREAD

**Issue by zzxap** [containous/traefik#5934]
go generate 
 go build go build ./cmd/traefik
it build success
and then vim traefik.sample.toml  change port 80 to 8093 ,443 to 8094 save
./traefik --configFile=traefik.sample.toml 

http://192.168.1.7:8093/dashboard/  not show  .is 404

what should i need to do?

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by zzxap** [comment]
traefik.sample.toml is

[global]
  checkNewVersion = true
  sendAnonymousUsage = true
[entryPoints]
  [entryPoints.http]
    address = ":8093"
  [entryPoints.https]
    address = ":8094"
   
    
[log]

[api]
  dashboard = true
  insecure = true
[ping]

**Comment by zzxap** [comment]
go generate
go build go build ./cmd/traefik
it build success
and then vim traefik.sample.toml change port 80 to 8093 ,443 to 8094 save
./traefik --configFile=traefik.sample.toml

http://192.168.1.7:8093/dashboard/ not show .is 404

what should i need to do?

traefik.sample.toml is

[global]
checkNewVersion = true
sendAnonymousUsage = true
[entryPoints]
[entryPoints.http]
address = ":8093"
[entryPoints.https]
address = ":8094"

[log]

[api]
dashboard = true
insecure = true
[ping]

**Comment by dduportal** [comment]
Hi @zzxap as the bot told you, it is not a bug, but a misconfiguration.
Can you open a topic on the community forum (https://community.containo.us/) to get help please?
