### ISSUE TITLE
How to configure multiple zookeeper ？

### ISSUE THREAD

**Issue by VectorHo** [containous/traefik#594]
If my zookeeper is cluster mode, How should I configure.

![image](https://cloud.githubusercontent.com/assets/7578264/17390930/0a379732-5a44-11e6-96df-c796a4fdd814.png)

configure?

``` toml
endpoint = "127.0.0.1:2181,192.168.0.1:2181,192.168.0.2:2181"
```

**Comment by gomes** [comment]
The right answer is just what you proposed: 

endpoint = "127.0.0.1:2181,192.168.0.1:2181,192.168.0.2:2181"

**Comment by ldez** [comment]
I'll close this issue, because I think the question is answered, but feel free to continue the conversation.
