### ISSUE TITLE
Onlyoffice not work in version 2

### ISSUE THREAD

**Issue by Maurotb** [containous/traefik#5940]
Bug

Using Onlyoffice with any version of traefik > 2.0 
seem to work but when i open document nextcloud hung in "loading document"

With version < 2.0 , work correctly

      - traefik.http.routers.onlyoffice_2000net_it-https.rule=Host(`test.test.it`)
      - traefik.http.routers.onlyoffice_2000net_it-https.EntryPoints=https
      - traefik.http.routers.onlyoffice_2000net_it-https.tls.certresolver=letsencrypt-http
      - traefik.http.routers.onlyoffice_2000net_it-https.tls.options=

## traefik.yml
entryPoints:
  http:
    address: ":80"

  https:
    address: ":443"

certificatesResolvers:
  letsencrypt-http:
    acme:
      email: postmaster@test.it
      storage: acme.json
      httpChallenge:
        entryPoint: http

# Docker configuration backend
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

# API and dashboard configuration
api:
  dashboard: true
  insecure: true

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
