### ISSUE TITLE
Ingressrouter not give any bad status if backend pod is down it shift request to another route

### ISSUE THREAD

**Issue by jainbhavya65** [containous/traefik#5942]
i am using traefik 2.0 in which i am using ingressrouter in ingressrouter i define 2 rules like 
"- kind: Rule
    match: Host(`abc.example.com`)
    services:
    - name: service-1
      port: 80
  - kind: Rule
    match: Host(`abc.example.com`) && PathPrefix(`/abcd`) 
    services:
    - name: service2
      port: 8080"

according to this if any request on abc.example.com/abcd comes it goes into service2 rest are goes into srevice1 that work perfectly fine but when service2 pods in not available then request on abc.example.com/abcd is transfer to abc.example.com which is not expected. is there any solution that it gives 502 or 503 or 404 or any bad request?

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
