### ISSUE TITLE
Kubernetes Ingress host rules are not resolved correctly

### ISSUE THREAD

**Issue by mishushakov** [containous/traefik#5943]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Added wildcard Ingress rule

<img width="1087" alt="Screenshot 2019-12-05 at 13 31 34" src="https://user-images.githubusercontent.com/10400064/70235876-1e418400-1764-11ea-864e-dfae2270d111.png">

### What did you expect to see?

Wildcard redirects

### What did you see instead?

<img width="1349" alt="Screenshot 2019-12-05 at 13 32 42" src="https://user-images.githubusercontent.com/10400064/70235884-226da180-1764-11ea-9b3c-563e7f747628.png">

404 not found

### Output of `traefik version`: (_What version of Traefik are you using?_)

v2.0

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
        args:
          - --api.insecure
          - --ping
          - --entrypoints.http.Address=:80
          - --entrypoints.https.Address=:443
          - --entrypoints.smtp.address=:25
          - --entrypoints.smtp-auth.address=:587
          - --entrypoints.smtps.address=:465
          - --entrypoints.imap.address=:145
          - --entrypoints.imaps.address=:993
          - --providers.kubernetescrd
          - --providers.kubernetesingress
          - --providers.kubernetesingress.ingressclass=traefik
```

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by mishushakov** [comment]
Hello, you are wrong

**Comment by dduportal** [comment]
Hi @mishushakov , can you open a topic on the community forum at https://community.containo.us/ please?

We consider this issue is not a bug, neither a feature request, so we would like to have such conversation to happen on the community forum.

Thanks a lot.

**Comment by mishushakov** [comment]
Hey @dduportal,
thanks for your swift reply. Would you be so nice to reference it on forum for me? Don't wanna make accounts everywhere...

Thank you a lot

**Comment by dduportal** [comment]
@mishushakov , no need to create a new account: you can login in the community forum with your github authentication :)
