### ISSUE TITLE
Failed to renew Let's Encrypt certificates using helm chart

### ISSUE THREAD

**Issue by nodesocket** [containous/traefik#5948]
Running Traefik `1.7.18` in Kubernetes via official Helm chart.

All my ingress endpoints are serving the default example.com SSL certificate. Looking at the pod logs I see:

```
{"level":"info","msg":"legolog: [INFO] [de-novo.simplyagree.dev] acme: Trying renewal with 718 hours remaining","time":"2019-12-02T20:31:24Z"}
{"level":"info","msg":"legolog: [INFO] [de-novo.simplyagree.dev] acme: Obtaining bundled SAN certificate","time":"2019-12-02T20:31:24Z"}
{"level":"info","msg":"legolog: [INFO] [de-novo.simplyagree.dev] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/1517133705","time":"2019-12-02T20:31:25Z"}
{"level":"info","msg":"legolog: [INFO] [de-novo.simplyagree.dev] acme: Could not find solver for: tls-alpn-01","time":"2019-12-02T20:31:25Z"}
{"level":"info","msg":"legolog: [INFO] [de-novo.simplyagree.dev] acme: use http-01 solver","time":"2019-12-02T20:31:25Z"}
{"level":"info","msg":"legolog: [INFO] [de-novo.simplyagree.dev] acme: Trying to solve HTTP-01","time":"2019-12-02T20:31:25Z"}
{"level":"info","msg":"legolog: [INFO] [de-novo.simplyagree.dev] acme: Validations succeeded; requesting certificates","time":"2019-12-02T20:31:32Z"}
```

That seems to indicate that HTTP-01 validation worked and generated a new certificate. How can I further debug this? All my ingress domains, there are three of them are serving example.com.

**Comment by nodesocket** [comment]
I deleted an ingress and created it again, and confirm I see Traefik reloading the config. However nothing is printed to the log related to ACME or Let's Encrypt renewal.

```
{"level":"info","msg":"Server configuration reloaded on :80","time":"2019-12-05T22:03:31Z"}
{"level":"info","msg":"Server configuration reloaded on :443","time":"2019-12-05T22:03:31Z"}
{"level":"info","msg":"Server configuration reloaded on :8080","time":"2019-12-05T22:03:31Z"}
{"level":"info","msg":"Server configuration reloaded on :80","time":"2019-12-05T22:03:42Z"}
{"level":"info","msg":"Server configuration reloaded on :443","time":"2019-12-05T22:03:42Z"}
{"level":"info","msg":"Server configuration reloaded on :8080","time":"2019-12-05T22:03:42Z"}
```

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
