### ISSUE TITLE
Want to build on illumos (part 2)

### ISSUE THREAD

**Issue by bhechinger** [containous/traefik#5956]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Attempting to build on Illumos (OmniOS, specifically)

### What did you expect to see?

A successful build.

### What did you see instead?

```
# github.com/docker/docker/client
../go/pkg/mod/github.com/docker/engine@v0.0.0-20190725163905-fa8dd90ceb7b/client/client.go:120:35: undefined: DefaultDockerHost
../go/pkg/mod/github.com/docker/engine@v0.0.0-20190725163905-fa8dd90ceb7b/client/client.go:125:12: undefined: DefaultDockerHost
../go/pkg/mod/github.com/docker/engine@v0.0.0-20190725163905-fa8dd90ceb7b/client/client.go:128:12: undefined: defaultProto
../go/pkg/mod/github.com/docker/engine@v0.0.0-20190725163905-fa8dd90ceb7b/client/client.go:129:12: undefined: defaultAddr
```

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
v2.1.0-rc3
```

### How do we solve this problem?

So from what I can gather the support for solaris/illumos has been removed from docker several years ago. Based on this issue: https://github.com/terraform-providers/terraform-provider-docker/issues/69

As there is not actually any docker on a solaris/illumos machine having the provider built for docker makes no sense. Is there a way to disable the docker provider when building this on solaris/illumos?

**Comment by dduportal** [comment]
Hi @bhechinger , thanks for your interest! Alas it would require you change the code by removing all the dependencies.

You could still try on your fork by deleting the docker-related code, but without any guarantuee (I'm thinking on the next issues: Kubernetes, Rancher, etc.)

**Comment by bhechinger** [comment]
Commenting out the dependency on docker as well as the Docker stuff in the Providers struct worked. I don't have kubernetes or rancher to point this at to test with those, however, so I'm not sure if those would even work. It's probably a non issues because you would likely just point it all to an internal traefik instance anyway? Maybe? No idea. :)

The good news is I at least got it to work for my needs (static file based configs only) so thanks!
