### ISSUE TITLE
Error when starting 2.* windows based container: PowerRegisterSuspendResumeNotification failure

### ISSUE THREAD

**Issue by thijsvanbloemendaal** [containous/traefik#5968]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
I experience a bug when starting traefik 2.0 and 2.1 windowsservercore 1809 images. 1.7 does start.

### What did you expect to see?
Something like: `Using high precision timer`

### What did you see instead?
```
fatal error: PowerRegisterSuspendResumeNotification failure

runtime stack:
runtime.throw(0x2541033, 0x2e)
        /usr/local/go/src/runtime/panic.go:774 +0x79 fp=0x415fdb0 sp=0x415fd80 pc=0x433229
runtime.monitorSuspendResume()
        /usr/local/go/src/runtime/os_windows.go:294 +0x1a9 fp=0x415fe50 sp=0x415fdb0 pc=0x42f389
runtime.goenvs()
        /usr/local/go/src/runtime/os_windows.go:531 +0x1ba fp=0x415fea8 sp=0x415fe50 pc=0x42fd0a
runtime.schedinit()
        /usr/local/go/src/runtime/proc.go:554 +0xa9 fp=0x415ff00 sp=0x415fea8 pc=0x435c29
runtime.rt0_go(0x415ff30, 0x7ffe67c57974, 0x415ff30, 0x0, 0x7ffe67c57974, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/runtime/asm_amd64.s:214 +0x13d fp=0x415ff08 sp=0x415ff00 pc=0x45f9ed
```

### Output of `traefik version`: (_What version of Traefik are you using?_)
traefik:v1.7-windowsservercore-1809 works.
traefik:v2.0-windowsservercore-1809 throws error.
traefik:v2.1-windowsservercore-1809 throws error.

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
Docker on windows. Both windows 10 and 1809 throw the same errors. Haven't done any configuration yet, just wanted to start it up first.

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
fatal error: PowerRegisterSuspendResumeNotification failure

runtime stack:
runtime.throw(0x25bf75d, 0x2e)
        /usr/local/go/src/runtime/panic.go:774 +0x79 fp=0x421fdb0 sp=0x421fd80 pc=0x433229
runtime.monitorSuspendResume()
        /usr/local/go/src/runtime/os_windows.go:294 +0x1a9 fp=0x421fe50 sp=0x421fdb0 pc=0x42f389
runtime.goenvs()
        /usr/local/go/src/runtime/os_windows.go:531 +0x1ba fp=0x421fea8 sp=0x421fe50 pc=0x42fd0a
runtime.schedinit()
        /usr/local/go/src/runtime/proc.go:554 +0xa9 fp=0x421ff00 sp=0x421fea8 pc=0x435c29
runtime.rt0_go(0x421ff30, 0x7ffe67ad7974, 0x421ff30, 0x0, 0x7ffe67ad7974, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/runtime/asm_amd64.s:214 +0x13d fp=0x421ff08 sp=0x421ff00 pc=0x45f9ed
```

Thanks in advance!

**Comment by ldez** [comment]
Hello,

related to https://github.com/golang/go/issues/35447

**Comment by thijsvanbloemendaal** [comment]
Hi,

Seems related indeed. Using an older golang version should work as a workaround.

**Comment by dduportal** [comment]
Triage information: this issue is labelled as bug possible, time the upstream problem in golang is fixed.

**Comment by thijsvanbloemendaal** [comment]
I read the issue is resolved in golang, when will this go version be used by traefik?

**Comment by ldez** [comment]
https://github.com/golang/go/issues/35447#issuecomment-572605263

**Comment by thijsvanbloemendaal** [comment]
1.13 is the currently used version, 1.13.6 this issue is solved. Will this be used in Traefik soon, that’s a bit unclear for me. Thanks!

**Comment by ldez** [comment]
The problem is now solve in v2.1.4.

Thanks.
