### ISSUE TITLE
SNI not working with acme certificates

### ISSUE THREAD

**Issue by bd8392** [containous/traefik#5973]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you expect to see?
Strict SNI checking working with let's encrypt certificates

### What did you see instead?
Not working

### Output of `traefik version`: (_What version of Traefik are you using?_)
2
 2.0.6 tag

```
(paste your output here)
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# (paste your configuration here)
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by bd8392** [comment]
Can you please reopen? I didn't get an answer on the traefik forums too...and I don't know if it is an Issue, or am I missing something in the config docs...
