### ISSUE TITLE
Dark theme for UI

### ISSUE THREAD

**Issue by sh7dm** [containous/traefik#5975]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?
Light/dark switch in toolbar of web UI to switch color scheme.
This can be useful for night work or just for those who love dark theming.
Maybe I'll start this myself, but first I need some feedback about this feature.

**Comment by sh7dm** [comment]
@dduportal is this useful and should I start working on this?

**Comment by dduportal** [comment]
@sh7dm yes, sure, you're welcome to contribute! Thanks a lot !

**Comment by sh7dm** [comment]
@dduportal  Just wanted to know if somebody else needs this.
