### ISSUE TITLE
能否考虑对 Docker 和 Docker Swarm 的同时支持?

### ISSUE THREAD

**Issue by lx0758** [containous/traefik#5979]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

能否考虑对 Docker 和 Docker Swarm 的同时支持?
Could you consider supporting both Docker and Docker Swarm?

**Comment by dduportal** [comment]
Hi @lx0758 , both Docker and Docker Swarm are already supported, as explained in the documentation: https://docs.traefik.io/v2.0/providers/docker/.

**Comment by lx0758** [comment]
I mean support for both standalone Docker and Swarm labels, not support them separately.
Currently, the services deployed by me in Docker Swarm Manager node using docker-compose and Swarm's services cannot be discovered by Traefik at the same time.

**Comment by lx0758** [comment]
@dduportal I can get help ?

**Comment by dduportal** [comment]
Hi @lx0758 , thanks for the additional details. Please follow #182. Today, your request is not possible.
