### ISSUE TITLE
Allow multiple accounts per provider

### ISSUE THREAD

**Issue by kopax** [containous/traefik#5991]
# Feature

Allow multiple accounts per provider. For example, I have multiple OVH accounts, I want to be able to provide API key for all of them.

I am using version 2.1 and this is not possible yet.

# Purposed solution

Offer to override global values (if any) using `certificateResolvers.main.acme.environments`

**Comment by ldez** [comment]
Duplicate of #5472

**Comment by kopax** [comment]
Sorry I didn't saw it. Thanks for linking!
