### ISSUE TITLE
Docker image for Traefik 1.7.20 

### ISSUE THREAD

**Issue by darkl0rd** [containous/traefik#5992]
The docker image for v1.7.20 is missing from the Docker Hub.

**Comment by ldez** [comment]
Hello,

The official image is built by Docker, so you have to wait that Docker build and publish the image.

**Comment by darkl0rd** [comment]
Apologies, I was under the impression that the image was pushed from your build system and thought that maybe now that V2 is here ...

Thanks - I will wait for the official image to be built by Docker then :)
