### ISSUE TITLE
Documentation is inconsistent w.r.t. certificate resolvers

### ISSUE THREAD

**Issue by slhck** [containous/traefik#6018]
This is a request for improving documentation. It is a little bit inconsistent w.r.t. certificate resolver names. Under https://docs.traefik.io/https/acme/ the documentation defines a resolver with the name `sample`:

```
[entryPoints]
  [entryPoints.web]
    address = ":80"

  [entryPoints.web-secure]
    address = ":443"

[certificatesResolvers.sample.acme]
  email = "your-email@your-domain.org"
  storage = "acme.json"
  [certificatesResolvers.sample.acme.httpChallenge]
    # used during the challenge
    entryPoint = "web"
```

However, in all later examples, a resolver with the name `le` is used:

![image](https://user-images.githubusercontent.com/582444/70723757-b823a680-1cf9-11ea-9bb3-199be406e71a.png)

Since it is not so obvious that the name must be referenced, it would make sense to simply rename the `sample` as `le`, or vice-versa.

**Comment by traefiker** [comment]
Closed by #6019.
