### ISSUE TITLE
implement GRPC Health Checking Protocol 

### ISSUE THREAD

**Issue by Fengxq2014** [containous/traefik#6027]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

[GRPC Health Checking Protocol](https://github.com/grpc/grpc/blob/master/doc/health-checking.md)

**Comment by dduportal** [comment]
Hi @Fengxq2014 , thanks for your proposal. Could you explain a bit more what use case would this address please? Should it be on client / Traefik side, Traefik/server side ? For which situations that are not addressed today?

**Comment by Fengxq2014** [comment]
@dduportal ，i think it should be Traefik/server side， [this](https://github.com/salrashid123/grpc_health_proxy/blob/master/main.go#L231-L250) is a http demo implement grpc health checking protocol, and consul support grpc check health pprotocol too  [consul-checks](https://www.consul.io/docs/agent/checks.html)

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Community Forum](https://community.containo.us/).
