### ISSUE TITLE
URL path rewriting impossible?

### ISSUE THREAD

**Issue by ascora** [containous/traefik#603]
Hi,

I tried to find a way to proxy 2 URLs like this:

http://www.example.com/app1/testme.html -> http://localhost:81/testme.html

and

http://www.example.com/app2/testme.html -> http://localhost:82/mysecondapp/testme.html

Hwoever, so far I wasn't able to remove the path "app1"/"app2" to realize the mapping. Is such a mapping impossible with Traefik?

**Comment by emilevauge** [comment]
Using `PathPrefixStrip` should be ok to remove `/app1`:  http://docs.traefik.io/basics/#frontends.
But traefik cannot rewrite your app path for now.

**Comment by ascora** [comment]
OK, I will try this. Thanks a lot for the fast help. :-)

Do you know if the path rewriting will be supported in the future?



Best regards,

Sven

**Comment by timoreimann** [comment]
There's the older issue #133 that addresses URL rewriting already.

I'm going to close this one in favor of the other one.

**Comment by timoreimann** [comment]
@ascora actually, both of your use cases are covered by now: Traefik learned `AddPrefix` a bit ago, which should do the trick.

See [the docs](https://docs.traefik.io/basics/#frontends) for details.
