### ISSUE TITLE
Only accept HTTPS request for an entrypoint

### ISSUE THREAD

**Issue by BirkhoffLee** [containous/traefik#6034]
### Do you want to request a *feature* or report a *bug*?

I searched in the documentations / issues, and I think this is more of a **feature**.

### What did you expect to see?

For example, traefik runs on `1.2.3.4`.  There's only 1 entrypoint that listens on `:443`.  
`curl -vk https://1.2.3.4` is totally fine, but when you do `curl -v http://1.2.3.4:443`, it still works.  

This can bypass, for example, the TLS client certificate authentication. I'm not sure if this is actually intended, and I think it would be good to have an option to explicitly specify that an entrypoint should only accept HTTP/HTTPS requests.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
