### ISSUE TITLE
TLS 1.3 Support for Traefik 1.7

### ISSUE THREAD

**Issue by darkl0rd** [containous/traefik#6043]
Considering that Traefik 1.7 will be supported for another 2 years, can we expect TLS 1.3 support to be implemented for it? 

I am not quite ready to move my entire production landscape to Traefik 2.x anytime soon, but until I am, would like to ensure that I can continue to provide and comply with the current & highest security standards.

**Comment by ldez** [comment]
Hello,

you can already use TLS1.3 with Traefik v1, you have to define the following env var: `GODEBUG=tls13=1`
