### ISSUE TITLE
Documented steps for building Trafik from source doesn't work

### ISSUE THREAD

**Issue by UltraNemesis** [containous/traefik#6049]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Follow steps documented below (Method 2) for building Traefik from source.

https://docs.traefik.io/contributing/building-testing/

### What did you expect to see?

Traefik builds successfully.

### What did you see instead?

Traefik doesn't build. Get various errors. 

Build process does not seem to have been updated for the Traefik v2.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
2.1.1
```

**Comment by ldez** [comment]
Hello,

Could you provide your logs?

**Comment by UltraNemesis** [comment]
After deleting everything and starting from afresh, I have been able to build successfully. Earlier I was getting "case-insensitive import collision"  while running go generate
