### ISSUE TITLE
Please support JSON format for File backend

### ISSUE THREAD

**Issue by plombardi89** [containous/traefik#607]
Traefik is pretty awesome and I've been working on building an API gateway with it recently. We're using the File watcher backend updated by a sidecar process for the moment and one of the problems we're having is that Python has some pretty weak / buggy TOML libraries (PyTOML is now unmaintained by the author who has abandoned TOML as a format and https://github.com/uiri/toml has emitter issues). It would be nice if we could use JSON as a format because most languages have super mature JSON libraries. It looks like support for parsing JSON format probably already exists due to the way the REST API works so maybe just add a configuration option in the Main config or detect based on .json extension?

**Comment by emilevauge** [comment]
@plombardi89 couldn't you use the Traefik rest API instead ?

**Comment by plombardi89** [comment]
It could be done that way.... I guess. It's a bigger refactor then just dumping to a file and also the REST API appears to be read only per the docs. Also we lose the ability to use a shared volume with a single file updated from a single source that all Traefik servers are watching.

It still seems like it would be a "nice to have" ability to use JSON just in general to support languages with questionable TOML libraries and I can't imagine it adds too much overhead to the Traefik implementation other than selection a different parser when the rules file is loaded...

**Comment by JHK** [comment]
Just stumbled upon this issue when looking for something else but I think this has been resolved and should be closed:

Technically YAML is a superset of JSON and Traefik allows configuration via YAML. So valid JSON is also valid YAML.
