### ISSUE TITLE
Dashboard 308 Permanent Redirect Doesn't work correctly

### ISSUE THREAD

**Issue by robinwangrubin** [containous/traefik#6073]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I used the latest version of Traefik. It's Traefik:v2.1.1

### What did you expect to see?

I wanna access the dashborad.

### What did you see instead?
When i typed the url. "http://traefik.xxxx-dev.com/"

I was located to wrong url address: 

Like this:

http://traefik.xxxx-dev.com/dashboard/dashboard/dashboard/dashboard/dashboard/dashboard/dashboard/dashboard/dashboard/dashboard/dashboard/dashboard/dashboard/dashboard/dashboard/dashboard/dashboard/dashboard/dashboard/

By the way, I used Traefik to proxy Traefik-dashboard.

**Comment by robinwangrubin** [comment]
![image](https://user-images.githubusercontent.com/24934186/71231465-0ef83400-2329-11ea-87ce-85b95125e2cf.png)

**Comment by ldez** [comment]
Duplicate of #6041

**Comment by traefiker** [comment]
Closed by #6078.
