### ISSUE TITLE
The api version has changed for some deployment files

### ISSUE THREAD

**Issue by hhlb** [containous/traefik#6075]
### The api has changed and some file can not be applied successfully

This [link](https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/) shows that some tag(development) has been removed from extensions/v1beta1. So files like [https://github.com/containous/traefik/tree/v1.7/examples/k8s/traefik-deployment.yaml](https://github.com/containous/traefik/tree/v1.7/examples/k8s/traefik-deployment.yaml) can not be
applied successfully.

Please change the api from [extensions/v1beta1]() to [api/v1]().

/api out-of-date

**Comment by traefiker** [comment]
Closed by #6162.
