### ISSUE TITLE
How to get kubernetes service name instead of ip of a pod

### ISSUE THREAD

**Issue by jainbhavya65** [containous/traefik#6086]
when i try to track down if my request is reached to service or not then it's kind of hectic think track it down because we find RouterName like "namespace"-"ingressroute name"-"some random string"@kubernatescrd and Servicename like 
"namespace"-"ingressroute name"-"some random string" and instead of pod service name i found IP please provide Pod service name it will be easier to track down request using  access logs

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
