### ISSUE TITLE
Traefik 2.0 can not change port for dashboard

### ISSUE THREAD

**Issue by Macrame** [containous/traefik#6089]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I am trying to use Traefik 2.0 on kubernetes 1.16.2 and found it does not support to change the port of dashboard. It tries to bind the port 8080 which was used by kube-apiserver.
```
level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://docs.traefik.io/v2.0/contributing/data-collection/\n"
 traefik.go:67: command traefik error: error while building entryPoint traefik: error preparing server: error opening listener: listen tcp :8080: bind: address already in use
```
Is there any way to change this port? Hope to support this feature if not supports currently.

Thanks for such a great project.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by Macrame** [comment]
This is not a configuration problem. There is no way to configure the port of dashboard.

**Comment by ldez** [comment]
Sorry but it's a configuration issue.

https://docs.traefik.io/v2.1/operations/dashboard/#secure-mode

**Comment by Macrame** [comment]
It did not describe how to change the port for dashboard, it always wants to bind the port 8080.

**Comment by ldez** [comment]
Please join the community forum: https://community.containo.us/

**Comment by Macrame** [comment]
Anyway, traefik shoud provide a way to change/define the port of dashboard. Thanks!

**Comment by juliens** [comment]
Traefik provide a way to change/define the port of dashboard, if you follow the link (https://docs.traefik.io/v2.1/operations/api/#insecure) about the "insecure" you will see that `insecure=true`
```
Enable the API in insecure mode, which means that the API will be available directly on the entryPoint named traefik.

If the entryPoint named traefik is not configured, it will be automatically created on port 8080.
```

So if you create an entryPoint named traefik with a different port, you will be able to use this "new" port.

In addition, I think it's better to use the "secure" mode for your dashboard (as explained in the documentation) by using a specific IngressRoute, and with this specific IngressRoute you will be able to use the port you want, and even add some security like https, basic auth or other.

**Comment by ldez** [comment]
https://docs.traefik.io/v2.1/routing/services/#servers-load-balancer

**Comment by ldez** [comment]
https://community.containo.us/t/traefik-2-0-can-not-change-port-for-dashboard/3570/8
