### ISSUE TITLE
Doc Feature request - cli options listing

### ISSUE THREAD

**Issue by wshayes** [containous/traefik#6090]
This cli options listing is really helpful - I find myself going to it instead of the Traefik documentation for a single page overview of all of the command line options:

https://traefik.mattclemente.com/

**Comment by ldez** [comment]
Hello,

In the v2 doc, we created a dedicated page for the CLI options: https://docs.traefik.io/v2.1/reference/static-configuration/cli/

**Comment by wshayes** [comment]
Awesome - sorry - still on 1.7.   Awesome tool - thanks and Happy Holidays!  Didn't mean for anyone to look at this anytime this week.
