### ISSUE TITLE
Traefik 2.0 dropping Content-Type headers

### ISSUE THREAD

**Issue by derekslenk** [containous/traefik#6092]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I set up the docker image referenced: https://github.com/sissbruecker/linkding

I added labels to expose it to the HTTPS entrypoint with proper domain, etc.

Navigate to site behind traefik and see console error that the stylesheet is being server wrong.

Open dev tools, run it again, and see the stylesheet is being returned text/plain

### What did you expect to see?
I expected to see the stylesheet being returned as text/css, like it does when I navigate to the direct IP of the docker container.

### What did you see instead?
I saw the stylesheet returned as text/plain, which will not load as valid CSS over HTTPS

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.0.7
Codename:     montdor
Go version:   go1.13.5
Built:        2019-12-09T17:51:21Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: slenknet_default

entryPoints:
  websecure:
    address: ":443"
  metrics:
    address: ":9990"

http:
  middlewares:
    slenk-auth:
      basicAuth:
        users:
          - "######################"

certificatesResolvers:
  mytlschallenge:
    acme:
      email: my@email.com
      storage: "/letsencrypt/acme.json"
      tlsChallenge: {}

api:
  insecure: true
  dashboard: true
  debug: true

metrics:
  prometheus: 
    addEntryPointsLabels: true
    addServicesLabels: true
    entryPoint: metrics

accessLog: {}

```

```labels:
        - "traefik.enable=true"
        - "traefik.http.routers.linkding.rule=Host(`linkding.######.###`)"
        - "traefik.http.routers.linkding.tls=true"
        - "traefik.http.routers.linkding.entrypoints=websecure"
        - "traefik.http.routers.linkding.tls.certresolver=mytlschallenge"
        - "traefik.http.services.linkding.loadbalancer.server.port=9090"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```

**Comment by traefiker** [comment]
Closed by #6097.
