### ISSUE TITLE
Option to disable default TLS certificate

### ISSUE THREAD

**Issue by fgarcia** [containous/traefik#6099]
I've been trying for a few hours upgrading to Traefik 2 and one major hurdle I am having is the lack of some hard errors.

In my case I've been battling to serve three certificates for three different domains, but Traefik insists in using its own default certificate. I can manually set a default certificate, but then all domains start using the same one, ignoring their own.

I've seen plenty of official blog posts about how to set up TLS but my certs keep getting ignored with no warning or error.

An option to disable the default TLS and force the user to clearly specify a valid/wanted certificate would be great. It would be even better if I could make Traefik crash on invalid config.

**UPDATE**: After a while I noticed that my current pain point is that I have not seen a clear way to force/set a cert file from the route configuration. Something like "for this route use this certificate or fail" but right now despite seeing my certificates per domain loaded (DEBUG log level) the routes for those domains insist in generating a new one

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
