### ISSUE TITLE
TLS certificate with passphrase

### ISSUE THREAD

**Issue by msonowal** [containous/traefik#6101]
Feature

### What did you expect to see?
To have ability to supply passphrase

Now I am in final phases of deployment of the critical application which is running fine.
Now the client is giving own SSL certificates containing passphrase. After googling so much I have not found any options. and now kind of helpless that there is no way to supply passphrase while using custom tls certificates.
Can somebody atleast know any workarounds?

**Comment by ldez** [comment]
duplicate of #1262
