### ISSUE TITLE
Using HostRegExp leads to passing wrong Host to service

### ISSUE THREAD

**Issue by viict** [containous/traefik#6104]
### Do you want to request a *feature* or report a *bug*?

Bug, version 2.0

### What did you do?

Setup a docker service with multiple hosts using HostRegExp:

> "traefik.http.routers.haproxy.rule=HostRegexp(`{subdomain:[a-z0-9.-]+}.dev.domain.tld`, `{subdomain:[a-zA-Z0-9-]+}.sub.domain.tld`)"

also tried with:

> "traefik.http.routers.haproxy.rule=HostRegexp(`name1.{subdomain:[0-9]+}.dev.domain.tld`, `name2.{subdomain:[0-9]+}.dev.domain.tld`)"

### What did you expect to see?

Requests to reach the service with the correct (current) Host.

### What did you see instead?

Accessing the address `name1.55.dev.domain.tld` reaches the service with the previous parsed name `name1.72.dev.domain.tld`

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.0.0-rc3
Codename:     montdor
Go version:   go1.13
Built:        2019-09-10T17:10:04Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

It's a docker swarm cluster

**Comment by ldez** [comment]
Hello, could try with 2 latest stable version (v2.1.1) instead of an old RC.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Community Forum](https://community.containo.us/).
