### ISSUE TITLE
Add OpenApi V3 schema to all Traefik CRDs (+ other useful fields)

### ISSUE THREAD

**Issue by rhuss** [containous/traefik#6109]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

The current CRD schemas are currently only bare bones and contain the minimal necessary for defining such resources. They are missing some essential information like openAPI V3 schema for the CR or other nice things like printer columns to help with `kubectl get`.

BTW, afaik schemas are either already mandatory for Kubernetes 1.17 (or will become soon), so better to add them earlier than later.

**Comment by ldez** [comment]
Closed in favor of #5473
