### ISSUE TITLE
Allow k8s ingress controller serviceAccountToken and serviceAccountCACert to be changed

### ISSUE THREAD

**Issue by Dacode45** [containous/traefik#611]
Right now `serviceAccountToken` and `serviceAccountCACert` are hardcoded in 'traefik/provider/kubernetes.go'. They should be configurable like `defaultKubeEndpoint`.

``` go
const (
    serviceAccountToken  = "/var/run/secrets/kubernetes.io/serviceaccount/token"
    serviceAccountCACert = "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
    defaultKubeEndpoint  = "http://127.0.0.1:8080"
)
```

**Comment by enxebre** [comment]
Hey @errm, @Dacode45 is this still considered an issue? As Traefik is using "In cluster" config, this is handled internally by the k8s client. Also see https://github.com/containous/traefik/issues/876

**Comment by errm** [comment]
I don't this this is an issue, with k8s we expect Traefik to be in cluster... and we avoid a bunch of complexity by doing so.
