### ISSUE TITLE
enhance redirectScheme

### ISSUE THREAD

**Issue by MohamedMSaeed** [containous/traefik#6122]
### Do you want to request a *feature* or report a *bug*?
Feature

### Case:
I'm using Traefik v2.0.6 with Kubernetes. 

I'm trying to use redirectScheme to redirect all HTTP requests to HTTPS. 

While configuring it, I faced too many redirects issue which was solved by creating 2 IngressRoutes. One for HTTP with applying redirect middleware and the other for https with no middlewares. 

### What did you expect to see?
I expect to use one IngressRout for both. The redirectScheme middleware should detect if the request is http then redirect. if it is https then do nothing. 

Thanks

**Comment by SantoDE** [comment]
Hey @MohamedMSaeed,

thanks for your interest in the project.

Can you please provide my with your IngressRoute definitions?

**Comment by ldez** [comment]
Duplicate of #4863
