### ISSUE TITLE
Add Healthcheck to Kubernetes CRD

### ISSUE THREAD

**Issue by SantoDE** [containous/traefik#6128]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you do?

Currently, there is no real way to configure health-checks in the Kubernetes CRD Provider. We need to define a way how we want to handle that in the future and implement it.

**Comment by dtomcej** [comment]
Should we have the CRD handle healthchecks? Or should we offload that to the service endpoint healthcheck code that is built into kubernetes?

If the endpoint is present, then it passes the service healthcheck?

Or are you thinking for Traefik services?

**Comment by SantoDE** [comment]
I personally would offload it to the service endpoint, as the orchestrator should handle the healthchecks. 

WDYT?
