### ISSUE TITLE
Git support for Traefik

### ISSUE THREAD

**Issue by anoop-b** [containous/traefik#6134]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

-> Git plugin for all configuration related files.

caddy server has this feature here : [link](https://github.com/abiosoft/caddy-git/blob/master/README.md)

- It would be nice to have a single source of truth for all things traefik. 
- I also am aware of the issues related to reading changes to the dynamic config file from the host file-system which takes an assumption for underlying OS to support a few file-system specific features.

**Comment by mpl** [comment]
Sorry, we do not really see/understand a relevant use-case for that feature request.
