### ISSUE TITLE
basic auth: add exception for specified endpoints

### ISSUE THREAD

**Issue by dkossako** [containous/traefik#6136]
### Do you want to request a *feature* or report a *bug*?
Feature

### What did you expect to see?
It would be useful to add whitelisting for entryPoints.http.auth.basic. Like:
```
[entryPoints.http.auth.basic]
usersFile = "/etc/traefik/.htpasswd"
whiteList = [ "/something", "/.well-known" ]
```

Such feature would be used in projects where acme and authentication are used together.

**Comment by ldez** [comment]
Hello,

The v1 of Traefik is in maintenance mode: only bug fixes, no new features.

The v2 of Traefik has a new way to configure this.

**Comment by dkossako** [comment]
> The v2 of Traefik has a new way to configure this.

Can you provide more details? I don't see it in docs.
