### ISSUE TITLE
Switch from Alpine to Debian

### ISSUE THREAD

**Issue by sylr** [containous/traefik#6139]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Due to Apline not using glibc it is difficult to build go binary with the `-race` flag, see https://github.com/golang/go/issues/14481.

I'm wondering if you could migrate to debian so we can build traefik with this helpful debug mode.

Regards.

**Comment by SuperSandro2000** [comment]
I propose if at all, that we add a Debian variant.

**Comment by sylr** [comment]
I don't see the benefit of having multiple build images.

**Comment by ldez** [comment]
Hello,

You can create your own Debian based image if you really need it for debugging purpose.

For now, we don't plan neither to migrate to a Debian based image nor to create a variant.
