### ISSUE TITLE
Option to delay shutdown and serve unhealthy ping

### ISSUE THREAD

**Issue by etienne-napoleone** [containous/traefik#6153]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

- setting up a "shutdown delay"
- when receiving SIGTERM, the healthcheck becomes negative and treafik waits during "shutdown delay" before exiting

This feature would be helpful for situations where multiple instances of traefik listen on multiple machines behind a managed loadbalancer using healthchecks on `/ping`.

This would help updating the traefik service without downtime on this kind of setups.

There are some cases where people cannot rely on the cluster load balancing capabilities to ensure requests are routed to the right host. For example in our case, Docker Swarm has huge performance hits when using ingress network instead of direct host binding.

**Comment by mpl** [comment]
@etienne-napoleone We think this feature already exists through the options in https://docs.traefik.io/v2.1/routing/entrypoints/#lifecycle
Have you already tried them?
If yes, are you sure that there are ongoing connections allowing your traefik instance to stay alive during that grace period?
If yes, can you give us your full config and a way to reproduce your problem?

**Comment by etienne-napoleone** [comment]
@mpl My bad, I checked for options in `[ping]` but not in the entrypoints and my googlings where unsuccessful.
That's actually exactly what I need.
Thanks for pointing me out to the right place!
