### ISSUE TITLE
Gui cannot proceed to next page of results v2.0.6+

### ISSUE THREAD

**Issue by cakiwi** [containous/traefik#6165]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I Tried to open the next page of results in the dashboard for HTTP Routers

### What did you expect to see?
I expected to see next pages of results of configured/discovered HTTP Routers

### What did you see instead?
The mouse icon changes to the no_symbol    ⃠, mouse down action does nothing.

Reverting to v2.0.5 resolves this issue.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.0.7
Codename:     montdor
Go version:   go1.13.5
Built:        2019-12-09T17:51:21Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# (paste your configuration here)
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```

**Comment by ldez** [comment]
dulplicate of #5959
