### ISSUE TITLE
http router map to tcp service

### ISSUE THREAD

**Issue by smithyj** [containous/traefik#6176]
### feature

http router map to tcp service

### I wish traefik support http router host map to tcp service

- Because I want to be able to access the TCP service through the specified domain name, but now the TCP service is not support

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
