### ISSUE TITLE
It is unclear which providers have access to which functionality

### ISSUE THREAD

**Issue by jangie** [containous/traefik#618]
I am finding that though Marathon is a provider that works well out of the box, that it (and other providers) do not provide configuration access to the full set of functionality as provided by træfik. #616 is attempting to partially resolve this for the Marathon provider, and as long as this is accepted I'll be taking a stab at throwing in circuit breaker configuration along with loadbalancer choice, to fill out the Backend configuration options.

However, this still leaves gaps for other providers. While it is fully possible to ascertain support by examining the templates/[provider].go files, I think it would be worthwhile to create and maintain documentation around the current state of each provider's feature support. If there is a preferred place to put this kind of documentation, I am more than happy to create an initial markdown file collating the state of provider feature support.

**Comment by errm** [comment]
Seems reasonable

It would be good if we could also add and link issues for adding support of outstanding features, mostly these things should be nice small PRs that people can pick up...  Especially if there is an example implementation for other providers.

@jangie if you want to make a start on this that would be great...

**Comment by jangie** [comment]
Will do.

**Comment by jangie** [comment]
@errm realizing i forgot to tag you on last update, just in case you missed this

**Comment by ldez** [comment]
Now all providers have all configuration 🎉

**Comment by timoreimann** [comment]
Major effort -- kudos @ldez!
