### ISSUE TITLE
 tls.options is not applied if not named "default"

### ISSUE THREAD

**Issue by vvitayau** [containous/traefik#6181]
Followup for @jbdoumenjou to provide a  #5553 example for dynamic docker tag configure tls.options

### What did you do?

How do I configure a docker tag to
enable `clientAuthType=RequireAndVerifyClientCert` to enforce mTLS for https://apitester.xxx.com 
, whereas other URLs using the `tls.options=default` have `clientAuthType=NoClientCert`

I know that `clientAuthType=RequireAndVerifyClientCert` for https://apitester.xxx.com works if `tls.options=default` is configured this way, but then it breaks my other URL that don't require certificate.

### What did you expect to see?

```
# expect SUCCESS for tls.options=default
$ curl https://non-apitester.xxx.com

# expect FAILURE for tls.options=???
$ curl https://apitester.xxx.com
curl: (35) error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate

# expect SUCCESS
$ curl https://apitester.xxx.com --cert apitester.xxx.com.crt --key apitester.xxx.key
```

### What did you see instead?

```
# Success for
$ curl https://apitester.xxx.com

# but was expecting
# curl: (35) error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate

# meaning providing certificate was not required like
$ curl https://apitester.xxx.com --cert apitester.xxx.com.crt --key apitester.xxx.key
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.1.2
Codename:     cantal
Go version:   go1.13.5
Built:        2020-01-07T18:23:57Z
OS/Arch:      linux/amd64

Nomad v0.10.2 (0d2d6e3dc5a171c21f8f31fa117c8a765eb4fc02)
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```
tls:
  options:
    default:
      minVersion: VersionTLS12
      sniStrict: true
      clientAuth:
        clientAuthType: NoClientCert
    mtls:
      minVersion: VersionTLS12
      sniStrict: true
      clientAuth:
        caFiles:
          - /etc/traefik/tls/apitester.xxx.com.crt
        clientAuthType: RequireAndVerifyClientCert
```

https://nomad.xxx.com/ui/jobs/apigee-test-service/definition configured with
```
              "Tags": [
                "http",
                "traefik.http.routers.apitester-http.entrypoints=http",
                "traefik.http.routers.apitester-http.middlewares=https-redirect@file",
                "traefik.http.routers.apitester-http.rule=Host(`apitester.xxx.com`)",
                "traefik.http.routers.apitester-https.entrypoints=https",
                "traefik.http.routers.apitester-https.rule=Host(`apitester.xxx.com`)",
                "traefik.http.routers.apitester-https.tls=true",
                "traefik.http.routers.apitester-https.tls.certresolver=le",
                "traefik.http.routers.apitester-https.tls.domains[0].main=apitester.xxx.com",
                "traefik.http.routers.apitester-https.tls.options=mtls",
                "traefik.enable=true"
              ]
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

https://traefik.xxx.com/dashboard/#/http/routers/apitester-https@consulcatalog has status error for Router details 
```
 unknown TLS options: mtls@consulcatalog 
```

apitester-xxx.com works as expected if I configure
```
                "traefik.http.routers.apitester-https.tls.options=default",
```

But then everything else breaks for all the other URLs where certificate is not required

An alternative configuration below ...  did not show up above in traefik because its invalid based on `router not found: apitester-https@consulcatalog` after setting
```
                "traefik.http.routers.apitester-https.tls.options.default.clientAuth.clientAuthType=RequireAndVerifyClientCert",
```

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by vvitayau** [comment]
Found the example that helped me identify the issue is namespace in
  * https://github.com/containous/traefik/issues/5114
  * https://community.containo.us/t/unable-to-set-tls-options/2437/6

Resolved the issue by setting
```
                "traefik.http.routers.apitester-https.tls.options=mtls@file",
```

Instead of 
```
                "traefik.http.routers.apitester-https.tls.options=mtls",
```

As stated previously, otherwise an error would appear 
```
 unknown TLS options: mtls@consulcatalog 
```

The default namespace appearantly is `consulcatalog` for my setup and my dynamic file configuration was never picked up.

Notes in https://docs.traefik.io/migration/v1-to-v2/ only mentions below

Some Tips You Should Know
* Different sources of static configuration (file, CLI flags, ...) cannot be mixed.
* Now, configuration elements can be referenced between different providers by using the provider namespace notation: @<provider>. For instance, a router named myrouter in a File Provider can refer to a service named myservice defined in Docker Provider with the following notation: myservice@docker.
…
