### ISSUE TITLE
Dynamic configuration loading failed

### ISSUE THREAD

**Issue by xxlaila** [containous/traefik#6184]
``` 
When I used dynamic configuration, I found that the format uses .toml. If the toml format configuration fails multiple times, traefik fails to load multiple times. Traefik cannot update the configuration after correct modification or delete this configuration file, dynamic loading fails
```
``` 
traefik 2.1
```

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by xxlaila** [comment]
I also thought that it was my configuration problem, but I removed the file that was currently modified and the configuration could not be updated. So it's a little depressed, so I have to redeploy traefik
