### ISSUE TITLE
Must-Feature: Is there a reason that Traefik doesn't store LE certs after generation?

### ISSUE THREAD

**Issue by desmap** [containous/traefik#6189]
Feature which feels like a bug.

### What did you expect to see?

I'd have expected that Traefik saves the generated LE certs with k8s, either via volumes or secrets in order not to need to regenerate them everytime. In some weeks we easily face more than 50 deployments and would hit LE's rate limits very quickly having suddenly red lock on a production system which is a deal-breaker.

Why does Traefik let LE regenerate them every time? Is there a particular reason, I think eg Greenlock.js does not do this and checks if the last generated cert is ok.

Also it would be great if the docs told what Traefik does in this regard, since this auto-LE stuff via lego is Traefik's key feature. I had to find this myself, check your community, I asked in your community and I am not the only one: https://community.containo.us/t/are-the-le-certs-stored-persistently-with-k8s/3887/3

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by desmap** [comment]
> We dedicate the issue tracker to bug reports and feature requests only

This is a feature request. What was wrong with it?
