### ISSUE TITLE
[question] basic auth based on client source address

### ISSUE THREAD

**Issue by aol-nnov** [containous/traefik#6191]
Hello!

I'd like to know if it is possible to achieve something akin to the following nginx directives?

```
satisfy any;
allow 192.168.2.0/24;
deny all;

auth_basic "howdy!";
auth_basic_user_file /etc/nginx/conf.d/repo.passwd;
```

In other words, I'd like to have basic auth for a resource, but only if it is accessed from a WAN.

Traefik is running on a LAN machine and corresponding 80 and 443 ports are nat-ed by the LAN gateway to the WAN.

Browsing through issues I came to understanding that you are not going to support any of L4 features, but could you give me some advice how to do it?

I'm moving from nginx + jwilder's docker-gen + jrcs/letsencrypt-nginx-proxy-companion and I'm super excited with traefik 2, but this auth thing is a real show stopper for me..

Thanks in advance!

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
