### ISSUE TITLE
MD5, SHA1 are 

### ISSUE THREAD

**Issue by PackElend** [containous/traefik#6201]
The _OWASP Foundation, the Open Source Foundation for Application Security_ says MD5 and SHA1 are weak and shall not be used but I find supported by Traefik in 
https://github.com/containous/traefik/blame/master/docs/content/middlewares/basicauth.md#L74
and used in 
https://github.com/containous/traefik/blame/master/docs/content/middlewares/basicauth.md#L17

[Cryptographic Storage Cheat Sheet](https://owasp.org/www-project-cheat-sheets/cheatsheets/Cryptographic_Storage_Cheat_Sheet.html)
 --> Use-strong-approved-cryptographic-algorithms

so please stop supporting or even mentioning it.

see also https://github.com/containous/traefik/issues/1778

**Comment by ldez** [comment]
Duplicate of #1778
