### ISSUE TITLE
Running traefik proxy behind another traefik proxy

### ISSUE THREAD

**Issue by kdankert** [containous/traefik#6203]
### Do you want to request a *feature* or report a *bug*?

Feature

## What I would like to see being added to traefik

As far as I know there is no way to run multiple traefik instances using the same provider. 

I would really like to be able to serve a project, which is a microservice cluster running using docker-compose, behind a reverse-proxy powered by traefik, so that I forward all requests to a specific subdomain to my second traefik proxy using TCP routing. From there I would like to route my requests using the specified path to each service. 

I know that I could simply merge both reverse-proxies, but I need them to be separate, because the product needs to be installed on different systems with different environments. 

If what I plan is possible using traefik.enable labels and constraints (still haven't figured it out yet how to use constraints yet) I would be really happy if someone could share a code snippet or smt like that.

**Comment by kdankert** [comment]
I just got a question concerning my feature request. Can I actually specify the route path of a container using labels in a different  file or does traefik needs to be specified in the same file. 

If they need to be in same file this would solve my issue!

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by kdankert** [comment]
If this is already possible  I still think the documentation should be updated as this is not easy to understand then

**Comment by kdankert** [comment]
Figured out how to do it. If you want to know it, just reply
