### ISSUE TITLE
Allow specifying dashboard apiUrl through config

### ISSUE THREAD

**Issue by andsens** [containous/traefik#6207]
Feature

When hosting the dashboard on something that is not root (e.g. `/traefik/dashboard`) the dashboard still accesses the API at `/api` [because it is hardcoded at compiletime](https://github.com/containous/traefik/blob/e378cb410c4ce1f0d25be64f1e963d42e1c7c004/webui/quasar.conf.js#L118-L126).
It'd be great if we through the config file/cli could configure the dashboard to look elsewhere.

**Comment by ldez** [comment]
Duplicate #5853
