### ISSUE TITLE
404 response during deploy process

### ISSUE THREAD

**Issue by rogeriollacerda** [containous/traefik#621]
Hi,

I have Traefik with consul catalog backend. During an app deploy process, I get a lot of 404 errors while app containers are replaced (blue/green). Can I solve that using 'traefik.backend.circuitbreaker=NetworkErrorRatio() > 0.5' ? How that parameter can help us? Change DRR algorithm to another one can be a better solution?

Tks

**Comment by emilevauge** [comment]
Ping @samber, any idea ?

**Comment by ldez** [comment]
I'll close the issue due to inactivity but feel free to re-open if needed.
