### ISSUE TITLE
Windows traefik 2.1.2 as loadbalancer for mqtt over tcp with tls

### ISSUE THREAD

**Issue by Torsten1981** [containous/traefik#6213]
I am trying to use Traefik as Loadbalancer for MQTT over tcp with TLS (1.2). I found some posts here for the topic how to setup traefik for mqtt, but nothing related or solving my special problem/case.

I have setup the following configuration for simulating locally the behaviour of Traefik as a Reverse Proxy & Loadbalancer for MQTT on my developer Windows 10 machine

- Mosquitto_168_8883 on Windows locally on Port 8883 with TLS enabled/selfsigned certificates
- Traefik 2.1.2 on Windows listening on Port 7883 for routing to mqqt (toml see below)
- Node-Red 1.0.3  on Windows (NodeJs 12.14.1) client connecting (a) directly to Mosquitto (b) over Traefik to Mosquito

(a) Directly connecting and publishing is working for Node-Red Client (Port 8883)

(b) via Traefik: Node-Red can not connect or publish to MQTT (Port 7883)

My Traefik TOML Configuration is as follows:
```
[tracing]
  serviceName = "mqtt"
 [log]
  level = "DEBUG" # --log.level 
 
[entryPoints]
 [entryPoints.mqtt]
   address = ":7883"
 [entryPoints.traefik]
  address ="localhost:8091"

[api]
 dashboard = true
 insecure = true
 
[tcp] # YAY!
 [tcp.routers]
  [tcp.routers.mqtt]
   entrypoints = ["mqtt"]
   rule = "HostSNI(`*`)" # Catches every request   
   service = "mqtt"		
   
[tcp.routers.mqtt.tls]
     passthrough = true
      
    
 [tcp.services]
  [tcp.services.mqtt]
   [tcp.services.mqtt.loadBalancer]
    [[tcp.services.mqtt.loadBalancer.servers]]
      address = "localhost:8883"
```
Currently, I see nothing of interest within the active tracing and logging output. The Traefik UI shows no connection attemps via port 7883/TCP/Entrypoint mqtt

The expected behaviour from my side is that connecting to MQTT over TRAEFIK as Loadbalancer should work the same way for the client as connecting directly to mqtt or in case of a configuration miss match or mismatch of certificates, there should be an error or warning entry in log or trace.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by Torsten1981** [comment]
still having this problem after checking configuration and traefik documentation

**Comment by Torsten1981** [comment]
nothing found within the documentation, even the community has no answer on this. please re-open ticket !!!!!
