### ISSUE TITLE
Not sure why Traefik is reporting wrong backend port with Radarr

### ISSUE THREAD

**Issue by coolcat97** [containous/traefik#6217]
Hey everyone! Hopefully you can help me or point me in the right direction, but basically I have defined the default port in Radarr settings, and it works on my local network under the port 7878, SSL disabled on Radarr config. But yet Traefik is still seeing the backend port as 6868?

What could be the issue here? Images provided. Be gentle please, I'm a huge noob at all of this! Thank you!

https://imgur.com/a/HUAkjko

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
