### ISSUE TITLE
Process for security relevant issues

### ISSUE THREAD

**Issue by joernchen** [containous/traefik#6224]
Hi,

I'd like to file a security relevant issue in traefik and couldn't find a suitable way to do so.
Is there a prefered (and confidential) way of submitting more details?

**Comment by ldez** [comment]
Hello,

You can contact us: https://docs.traefik.io/contributing/submitting-security-issues/#report-a-vulnerability

**Comment by joernchen** [comment]
Hey, 

I've used the google docs form as per instructions on https://docs.traefik.io/contributing/submitting-security-issues/#report-a-vulnerability but haven't gotten any response since about two weeks.

How should I proceed? Just let me know if you need more time or if we can discuss the issue in public.
