### ISSUE TITLE
Elements per page in Routers/Services/Middleware overview

### ISSUE THREAD

**Issue by mr-manuel** [containous/traefik#6227]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

When I open the Routers, Services or Middleware overview I expect to see that I can change the elements to show per page. At the moment 10 elements per page are shown. It would be great if it's possible to show also 25. 50 ,100 and all elements on one page.

**Comment by ldez** [comment]
Hello,

in the next version the pagination has been replaced by an infinite scroll.

https://github.com/containous/traefik/pull/5875
