### ISSUE TITLE
Cipher Suites Order missing

### ISSUE THREAD

**Issue by mr-manuel** [containous/traefik#6228]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I'm missing the option "PreferServerCipherSuites" to enable cipher suites order by server, like here https://forge.tedomum.net/tedomum/peertube/commit/1dd59831f80ff4d49f3b60c8c3b2aabfb1512eeb

Example:

```
[tls.options.extended]
    sniStrict = true
    minVersion = "TLSv1"
    PreferServerCipherSuites = true
    cipherSuites = [
        "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA",
        "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA",
        "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256",
        "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384",
        "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA",
        "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA",
        "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256",
        "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384",
        "TLS_DHE_RSA_WITH_AES_128_CBC_SHA",
        "TLS_DHE_RSA_WITH_AES_256_CBC_SHA",
        "TLS_DHE_RSA_WITH_AES_128_CBC_SHA256",
        "TLS_DHE_RSA_WITH_AES_256_CBC_SHA256",
        "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
        "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
        "TLS_DHE_RSA_WITH_AES_128_GCM_SHA256",
        "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
        "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
        "TLS_DHE_RSA_WITH_AES_256_GCM_SHA384"
    ]
```

As it is now, it's only enabled (and nowhere documented) when specifying the maxVersion parameter:

[https://github.com/containous/traefik/pull/5650/files/6f6760a529f8b2c04df0fed8475d7d6c0a8561a5](https://github.com/containous/traefik/pull/5650/files/6f6760a529f8b2c04df0fed8475d7d6c0a8561a5)
![maxversion](https://user-images.githubusercontent.com/12592765/73033434-45eac980-3e42-11ea-86cc-2e9d82acf1e2.JPG)

**Comment by ldez** [comment]
https://github.com/containous/traefik/blob/dce6356d7596a7c0678354520c79e5f01c55849d/pkg/tls/tlsmanager.go#L222-L232

**Comment by ldez** [comment]
`PreferServerCipherSuites` is not a valid Traefik configuration option.

It's an option of the tls package of Go:

https://github.com/containous/traefik/blob/dce6356d7596a7c0678354520c79e5f01c55849d/pkg/tls/tlsmanager.go#L175

I don't understand what exactly do you want, could you explain?

**Comment by mr-manuel** [comment]
I want be able to enable `PreferServerCipherSuites` without specifying `minVersion` or `maxVersion`. Or at least it would be great if this where documented in the docs, that when adding `minVersion` or `maxVersion` the option `PreferServerCipherSuites` is enabled.
