### ISSUE TITLE
HTTPS redirect only works for root path

### ISSUE THREAD

**Issue by tstivers1990** [containous/traefik#6230]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
Configured Traefik with a catch-all redirect middleware and router

### What did you expect to see?
All paths redirected

### What did you see instead?
Only the root path redirected

### Output of `traefik version`: (_What version of Traefik are you using?_)
2.1.3

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
