### ISSUE TITLE
tcp load balancing issue

### ISSUE THREAD

**Issue by Torsten1981** [containous/traefik#6231]
even the community has no solution for this:

https://community.containo.us/t/struggling-with-traefik-as-loadbalancer-for-mqtt-tcp-tls-1-2/4034

**Comment by Torsten1981** [comment]
please state a reason for closing the issue. I definitivly need help. original issue was auto-closed by bot. the community has no solution for this, and anything I get here is an closed issue? Probably I will not suggest taefik for production usage in our projects.

**Comment by ldez** [comment]
Closed because:
- It's a duplicate of #6213 
- the 2 issues don't follow the issue template. https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/Bug_report.md
- it's a question.
