### ISSUE TITLE
documentation site not synced with GitHub?

### ISSUE THREAD

**Issue by j-craig** [containous/traefik#6236]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I'm looking at the documentation at https://docs.traefik.io and it doesn't appear to be synced up with what's on GitHub. Specifically, I'm looking at the Operations > Dashboard page. The "Dashboard Dynamic Configuration Examples" wasn't working for me so I clicked the "edit" icon on that page to see how old the documentation was and if it was maybe out of date.

### What did you expect to see?

I expected the content at docs.traefik.io would match up with what I saw on GitHub when I clicked the link.

### What did you see instead?

The content does not match up, specifically the file include-api-examples.md which has the dynamic config examples for the dashboard. I'm using Docker and the example shown on traefik.io has an "[email protected]" label which isn't in the GitHub example, whereas on GitHub it has a "traefik.http.routers.api.service=api@internal" label which seems to be the key piece I was missing.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.1.3
Codename:     cantal
Go version:   go1.13.6
Built:        2020-01-21T17:30:29Z
OS/Arch:      linux/amd64
```

**Comment by ldez** [comment]
Hello,

the documentation is synced with GitHub:

- [branch master](https://github.com/containous/traefik) -> https://docs.traefik.io/master/
- [branch v2.1](https://github.com/containous/traefik/tree/v2.1) -> https://docs.traefik.io and https://docs.traefik.io/v2.1
- [branch v2.0](https://github.com/containous/traefik/tree/v2.0) -> https://docs.traefik.io/v2.1
- [branch v1.7](https://github.com/containous/traefik/tree/v1.7) -> https://docs.traefik.io/v1.7
- [branch v1.6](https://github.com/containous/traefik/tree/v1.7) -> https://docs.traefik.io/v1.6
- etc.
