### ISSUE TITLE
Tip of tree crashes on invalid pointer on Marathon provider

### ISSUE THREAD

**Issue by snoby** [containous/traefik#624]
Compiling and deploying the tip of the tree: f0ea45a0f83ed50f450a1bd385a0acde4e5657af
Causes an invalid memory address  / dereferenced null when running on a marthon provider.

Thinking that this might be related to this commit:  e26e0955b355bd6ab7c62afdc22b3a8975916a81

Git of the crash here when loading the config:
https://gist.github.com/snoby/8f6edb4e7291724cbb4b6fe9156bd8a2

**Comment by errm** [comment]
I think #617 is a fix for this ....

**Comment by errm** [comment]
#617 was merged, @snoby if you would care to try testing HEAD again your issue should be fixed.

**Comment by snoby** [comment]
@errm  I tested with HEAD and verified correct functionality.  THANKYOU!!!!
