### ISSUE TITLE
Comprehensive documentation about Kubernetes CRD

### ISSUE THREAD

**Issue by sylr** [containous/traefik#6242]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Unless I'm mistaken the only documentation about using Kubernetes CRD is https://docs.traefik.io/master/reference/dynamic-configuration/kubernetes-crd/ and it only provides examples.

It would be good to have a real documentation with all the YAML objects structure and their properties listed/explained.

Regards.

**Comment by ldez** [comment]
Hello,

The documentation already exist:

- https://docs.traefik.io/v2.1/routing/providers/kubernetes-crd/
- https://docs.traefik.io/v2.1/providers/kubernetes-crd/
