### ISSUE TITLE
Reference Middleware from other provider

### ISSUE THREAD

**Issue by sylr** [containous/traefik#6243]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

It would be nice if we could create middlewares with the File provider which could be used in the kubernetes CRD provide.

https://github.com/containous/traefik/blob/dce6356d7596a7c0678354520c79e5f01c55849d/pkg/provider/kubernetes/crd/traefik/v1alpha1/ingressroute.go#L106-L110

**Comment by ldez** [comment]
Hello,

It's already possible.
