### ISSUE TITLE
Gophercloud package needs a bugfix update

### ISSUE THREAD

**Issue by kciredor** [containous/traefik#6245]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I have deployed Traefik 1.7.x with Helm. As soon as I deploy a website triggering loadbalancer creation on OpenStack, Traefik will go through gophercloud to sort this out.

### What did you expect to see?

A loadbalancer being created and becoming healthy.

### What did you see instead?

The OpenStack loadbalancer creation endpoint generated by gophercloud is appended with /v2.0/v2.0 instead of /v2.0. This is old gophercloud behaviour which has been fixed.

### My take on this issue

As of this PR https://github.com/gophercloud/gophercloud/pull/1829 gophercloud has been fixed to work with different OpenStack providers, where some of them append /v2.0 to their lb endpoint themselves and gophercloud should not do this anymore.

Kops has adopted the new gophercloud, I'm kindly requesting for Traefik (1.7.x and 2.x) to pull in the latest version as well, so Traefik immediately becomes usable with many more OpenStack providers.

**Comment by ldez** [comment]
Hello,

Traefik don't use the `NewLoadBalancerV2` method, I think it's related to your k8s cluster.
