### ISSUE TITLE
Route magic with consul catalog services

### ISSUE THREAD

**Issue by ingtarius** [containous/traefik#6249]
We have consul-catalog with auto-registration services like {BRANCH}-{SERVICE}-{PORT}
For example, if service have 2 ports (http and special port for api) in consul it will be like:
my-awesome-feature-project-80
my-awesome-feature-project-8080

I can manage traffic for single port via Service-Tag and catch Host parameter. For example
traefik.http.routers.service-name.rule=Host(`my-awesome-dev.t.example.com`)

But how to manage two ports? I add two EntryPoints - 80 and 8080, how to route traffic 

from: my-awesome-dev.t.example.com:8080 to: my-awesome-feature-project-8080
from: my-awesome-dev.t.example.com to: my-awesome-feature-project-80

Thanks for any help!

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
