### ISSUE TITLE
Updating to v2.1.3 ok forcing "2.1.3", changing back to "latest" pulls v2.1.2 back in

### ISSUE THREAD

**Issue by sspilleman** [containous/traefik#6257]
Bug

### What did you do?

I saw in the logs that v2.1.3. was available with the recommendation to update.
I changed the image tag in my docker-compose to 2.1.3. It updated perfectly
Changing the tag to "latest" and doing a docker-compose up, it pulled v2.1.2 back in. I checked on docker hub and they are supposedly aliases to each other (please see screenshot below)

### What did you expect to see?

I would expect the version to remain on v2.1.3

### What did you see instead?

It went back to the previous version v2.1.2. This is highly confusing at least

![image](https://user-images.githubusercontent.com/592486/73516278-32b69b80-43f8-11ea-9c38-c3363a3966d8.png)

**Comment by ZyanKLee** [comment]
i suspect that on that machine the `:latest` tag is already present. have a look at `docker image list` if it is in there. If it is, try running `docker-compose pull` or `docker-compose up -d --pull` to make sure it is updated.

**Comment by ldez** [comment]
Hello,

yes `latest` is a tag, and the tags are not linked together (It's a Docker behavior) so you need update the `latest` tag.

**Comment by sspilleman** [comment]
Ok, fair enough. I think you should update the documentation and put some sort of a warning in there maybe.

**Comment by ldez** [comment]
It's a basic behavior of Docker.

We strongly recommend to not use latest: Friends don't let friends use latest.
