### ISSUE TITLE
Allow configuration of SameSite settings for sticky session cookies

### ISSUE THREAD

**Issue by mattyb** [containous/traefik#6261]
Feature
With Chrome 80 going stable on Feb 4, 3rd party cookies without the `SameSite=None` setting will be blocked. https://blog.chromium.org/2019/10/developers-get-ready-for-new.html. In our testing, this breaks sticky sessions for services that are iframed into another page.

Relates to #2653, #4738

**Comment by mattyb** [comment]
Also filed vulcand/oxy#192 which may be a dependency

**Comment by umens** [comment]
Any updates on this ?

**Comment by MichaelErmer** [comment]
This is breaking our websocket based api. Any news? its a massive bug

**Comment by ldez** [comment]
I'm working on it, it will soon be corrected.

**Comment by traefiker** [comment]
Closed by #6538.

**Comment by traefiker** [comment]
Closed by #6537.

**Comment by traefiker** [comment]
Closed by #7667.
