### ISSUE TITLE
Let some traefik services manage their tls certificates themselves 

### ISSUE THREAD

**Issue by jmchantrein** [containous/traefik#6268]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I want to let more than one traefik services manage their own tls certificates themselves with or without let's encrypt.

I tried to do this with a tcp router in passthrough mode but without success.

1) Service can resolve http challenge only if traefik not manage let's encrypt, because when traeffik use let's encrypt, traefik does not transmit any request whose pathPrefix begins with ".well-known/acme-challenge". Apparently traefik considers that this type of request can only be for him ...

2) According to answer [here](https://stackoverflow.com/questions/59971646/is-there-a-way-to-let-some-traefik-services-manage-their-tls-certificates-themse), there is apparently a way to do passthrough tls for a particular service, but I have not managed to set it up with a file provider configuration, and the solution does not seem to be transferable to more than one service because only HostSNI(*) works in the configuration file (according to https://docs.traefik.io/routing/routers/#configuring-tcp-routers).

Regards.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by jmchantrein** [comment]
Hi.
I have already ask to the community: https://community.containo.us/t/is-there-a-way-to-let-some-services-manage-their-tls-certificates-themselves/4143 and [here](https://stackoverflow.com/questions/59971646/is-there-a-way-to-let-some-traefik-services-manage-their-tls-certificates-themse)

I really ask to a feature, there is no bug report in my post. Documentation not mentioned the use case I want.

Regards.
