### ISSUE TITLE
CORS Headers not applied

### ISSUE THREAD

**Issue by soullivaneuh** [containous/traefik#6278]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I added a CORS header to add Access-Control-Allow-Origin on the response.

The following documentation has been applied: https://docs.traefik.io/middlewares/headers/#cors-headers

You can see the concrete case on this public project: https://gitlab.com/nexylan/pass/-/merge_requests/8/diffs

### What did you expect to see?

I should see the `Access-Control-Allow-Origin` header on the response.

### What did you see instead?

```
❯ http --headers https://review-cors-heade-urtoi0.pass.nexylan.dev/v1/getPassword
HTTP/1.1 200 OK
Cache-Control: no-cache
Content-Length: 20
Content-Type: text/plain
Date: Tue, 04 Feb 2020 17:44:21 GMT
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.1.3
Codename:     cantal
Go version:   go1.13.6
Built:        2020-01-21T17:30:29Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Overrided entrypoint:

```
set -- traefik \
	--global.sendAnonymousUsage \
	--log.level=INFO \
	--api \
	--accessLog \
	--entrypoints.web.address=:80 \
	--entrypoints.web-secure.address=:443 \
	--certificatesResolvers.letsencrypt.acme.email="${NEXY_ACME_EMAIL:-postmaster@nexylan.com}" \
	--certificatesResolvers.letsencrypt.acme.storage=/data/acme.json \
	--certificatesResolvers.letsencrypt.acme.httpChallenge.entryPoint=web \
	--providers.docker \
	--providers.docker.exposedByDefault=false \
	"$@"

exec "$@"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

Not applicable AFAIK.

**Comment by ldez** [comment]
Hello,

a middleware need to be applied on a router: https://docs.traefik.io/v2.1/middlewares/overview/#configuration-example

**Comment by soullivaneuh** [comment]
Doh! I was sure it was something stupid like that.

Thanks for the help and sorry for the non-issue.
