### ISSUE TITLE
Dashboard authentication is getting bypassed using forward slash at the end of url

### ISSUE THREAD

**Issue by isaacnewtonfx** [containous/traefik#6282]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I added the docker provider config labels for basic auth middleware and then I run the traefik service in swarm mode to access the dashboard in my browser at the exposed port 9191

### What did you expect to see?

I expected to see the basic authentication form when my url ends with or without a trailing forward slash. Eg. Both `domain.traefik.com:9191/dashboard`  and `domain.traefik.com:9191/dashboard/` must request for user authentication.

### What did you see instead?

When i access the url like this  `domain.traefik.com:9191/dashboard` , it asks for authentication but when I access the url with a trailing slash at the end like this `domain.traefik.com:9191/dashboard/`, it bypasses the authentication and goes to dashboard straight away.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
2.0
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```docker-compose

version: '3'

services:
  reverse-proxy:
    # The official v2.0 Traefik docker image
    image: traefik:v2.0
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker --providers.docker.swarmMode=true
    ports:
      # The HTTP port
      - "91:80"
      # The Web UI (enabled by --api.insecure=true)
      - "9191:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
        - traefik-stack
    deploy:
        labels:
            - "traefik.http.services.reverse-proxy.loadbalancer.server.port=91"
            - "traefik.docker.network=traefik-stack"
            - "traefik.http.routers.api.service=api@internal"
            - "traefik.http.routers.api.middlewares=secured"
            - "traefik.http.routers.api.rule=PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
            - "traefik.http.middlewares.auth.basicauth.users=test:$$apr1$$bqEWT0Z2$$yUFoM5U9X/FbaSmx5v6ib."
            - "traefik.http.middlewares.replacepath.replacepath.path=/dashboard/" #without this line, error 404 occurs
            - "traefik.http.middlewares.secured.chain.middlewares=auth,replacepath"

        placement:
            constraints:
                - node.role == manager

networks:
   traefik-stack:
      external: true
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```

**Comment by isaacnewtonfx** [comment]
I tried the latest traefik version and basic auth did not pop up at all even with same configuration above.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
