### ISSUE TITLE
Are Kubernetes Ingress annotations still a work in progress?

### ISSUE THREAD

**Issue by leonboot** [containous/traefik#6284]
I've been trying to achieve a kubernetes based setup where I'm using Traefik 2 as a router and cert-manager to manage requesting Let's Encrypt certificates for my ingresses. So far I've managed to get things working. I've set up Traefik with a HTTP and HTTPS entrypoint, cert-manager is able to create an ingress through Traefik's HTTP entrypoint and Let's Encrypt successfully issues certificates, which are being picked up by Traefik.

I now want to proceed configuring my ingress to redirect any traffic to the HTTPS endpoint. I've not managed to do so. I assumed I could get this done by adding annotations to the ingress. This worked for Traefik 1.7, so it should work for 2.x. After a long dig I failed to find any info on the 2.x annotations in the docs. After a log of digging I suddenly ended up on a page containing a list of possible annotations, but these annotations seemed to do nothing when I applied them to my ingresses. Then I noticed the "master" part in the URL of the documentation page. I started digging the repository and found  commit https://github.com/containous/traefik/commit/6b7be462b84132c561ba1d2ef5b8a1a16ff2cc62 in the master branch.

May I safely assume that Kubernetes Ingress annotations haven't made their way into the 2.x code yet? And if so, is there any ETA of  the aforementioned commit to make it into a future release? If annotations are still a work in progress, could you perhaps add it to the documentation of the current 2.x releases? It would save anyone looking for this functionality a lot of time.

**Comment by SantoDE** [comment]
Hey @leonboot ,

thanks for your interest. 

correct. Ingress Support will be added with the release v2.2 later this year. 

What documentation page do you mean? You should only be able to see it, if you selected the "experimental" version on the documentation. On the current stable v2.1, there should be no indication of the "new" annotations.

**Comment by leonboot** [comment]
Hi @SantoDE,

Thanks for your swift reply! Thanks for confirming the annotations support is still being worked on. I found the page with the annotations by googling for one of the annotations that I somehow managed to find, I think I found it in the test fixtures in this repository. Google returned this page: https://docs.traefik.io/master/routing/providers/kubernetes-ingress/ After trying a few other annotations from that page I noticed the 'master' part in the URL and figured it was the expirimental version of the documentation, not the stable.

As Traefik 1.7 supports annotations for the Kubernetes Ingress provider, I assumed version 2 also had support for them. I can imagine more people who are upgrading from 1 to 2 have this assumption and might end up going down this rabbit hole. Therefore I suggested adding a note to the 2.0 and 2.1 docs stating that annotations for the Kubernetes Ingress provider is still under development.

Anyway, I'm glad to hear it's on the radar and due for release in version 2.2. I hope it gets releaseed soon!

**Comment by lukasmrtvy** [comment]
@SantoDE Problem is that You can not force http->https redirection without annotations with ingress provider...

**Comment by SantoDE** [comment]
@lukasmrtvy with the merged support, you can. You can create a middleware and reference that from the Ingress :-)

**Comment by lukasmrtvy** [comment]
@SantoDE yes, but there is no ETA for release yet..

Problem:
1. ingressCRD provider ( external-dns will not work with annotation https://github.com/containous/traefik/issues/4655, there is workaround with externalservice https://github.com/kubernetes-sigs/external-dns/issues/1257, but it is not clean..., cert-manager will not work with annotation  )
2. ingress provider ( external-dns will work with annotation, cert-manager will work with annotation  http->https redirection will not work )

Would be nice to have integration for IngressRoute to basic infrastructure tools like external-dns, and cert-manager.

**Comment by ryaneorth** [comment]
I agree with @lukasmrtvy on this. One of the primary reasons my organization is not adopting Traefik 2.x and is instead staying on Traefik 1.x is because external dns doesn't work with the new Traefik IngressRoute.

With Traefik 1.x this just "worked". No need to worry about manually setting up CNAMES or alias records in cloud providers to point to the underlying LB. Sure, custom solutions could be created but one of the greatest allures to traefik in the first place was that everything "just works". Having that not be the case with Traefik 2.x makes it very difficult to migrate to and ultimately may force us to move away from traefik entirely once support for traefik 1.x ends if this is not addressed.

**Comment by bradjones1** [comment]
I'd recommend this issue get locked and/or split into other tasks, e.g. relating to external DNS. For the time being, native Kubernetes ingress is supported and we are using it successfully in production, including referencing CRD middlewares by annotation. The issues raised since this was closed seem to address more specific functionality.

**Comment by ryaneorth** [comment]
@bradjones1 - can you expand on this:

> including referencing CRD middlewares by annotation

Is there documentation on how this can be accomplished/what annotations are available? I don't see anything in the v2.1 docs on the traefik website about this.

**Comment by bradjones1** [comment]
@ryaneorth https://docs.traefik.io/middlewares/overview/#provider-namespace

**Comment by ryaneorth** [comment]
Thanks @bradjones1 . Perhaps I am blind, but I don't see anywhere in that documentation how you can reference middlewares from an Ingress object (as opposed to IngressRoute) using annotations.

**Comment by bradjones1** [comment]
You are correct this is not entirely obvious from the documentation. An example annotation referencing a CRD middleware:

`traefik.ingress.kubernetes.io/router.middlewares: other-namespace-name-of-middleware@kubernetescrd`

See related: https://github.com/containous/traefik/issues/6318
