### ISSUE TITLE
Redirect Scheme middleware not redirecting page from http to https

### ISSUE THREAD

**Issue by starcraft66** [containous/traefik#6288]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I configured my routers to have a chain middleware that consists of a redirectscheme middleware and a headers middleware (that contains a strict-transport-security header).

### What did you expect to see?

Upon visiting an http page, I am not automatically redirected to the https version as I should be.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.1.3
Codename:     cantal
Go version:   go1.13.6
Built:        2020-01-21T17:30:29Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

https://github.com/starcraft66/infrastructure/blob/master/roles/tdude.traefik/templates/docker-compose.yml.j2
https://github.com/starcraft66/infrastructure/blob/master/roles/tdude.traefik/templates/http.toml.j2
https://github.com/starcraft66/infrastructure/blob/master/roles/tdude.traefik/templates/traefik.toml.j2

docker-compose with configuration labels for an example service:
https://github.com/starcraft66/infrastructure/blob/master/roles/tdude.matrix/templates/docker-compose.yml.j2

Ouput of curl on http and https pages

```
root@sapling:/opt/traefik# curl -I http://nerdsin.space
HTTP/1.1 404 Not Found
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Fri, 07 Feb 2020 04:53:04 GMT
Content-Length: 19

root@sapling:/opt/traefik# curl -I https://nerdsin.space
HTTP/2 200
accept-ranges: bytes
content-type: text/html
date: Fri, 07 Feb 2020 04:53:09 GMT
etag: "5e2ed12f-1123"
last-modified: Mon, 27 Jan 2020 12:01:51 GMT
server: nginx
strict-transport-security: max-age=315360000; includeSubDomains; preload
content-length: 4387
```

Screenshot of dashboard:
![image](https://user-images.githubusercontent.com/1858154/74002712-00e48e00-493e-11ea-8318-0ce78142e704.png)

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
