### ISSUE TITLE
Problems with defaultRule while migrating form v1.7 to v2.1

### ISSUE THREAD

**Issue by bambamboole** [containous/traefik#6295]
hi,

I have problems with the migration form `v1.7` to `v2.1`.

We use traefik in the development. It runs as a dedicated project on any development machine next to dnsmasq which points any `.test` domains to `127.0.0.1`.

All services (which have the corresponding labels) of a project are accessible via 
`{service_name}.{compose_project_name}.test` which worked like a charm for `v1.7` with the following `toml` config:

```
debug = true
defaultEntryPoints = ["http", "https"]

[entryPoints]
    [entryPoints.http]
    address = ":80"
    [entryPoints.https]
    address = ":443"

[traefikLog]
    format = "json"

[accessLog]
    format = "json"

[web]
    address = ":8080"

[docker]
    domain = "test"
    exposedbydefault = false
    watch = true
```

While migrating to `v2.1` I came up with the following `toml` config:

```
[entryPoints]
    [entryPoints.http]
    address = ":80"
    [entryPoints.https]
    address = ":443"

[providers]
  [providers.docker]
    watch = true
    exposedByDefault = false
    defaultRule = "Host(`{{ .Name }}.test`)"

[api]
  insecure = true
  dashboard = true
  debug = true

[log]
  format = "json"

[accessLog]
  format = "json"
```

The dashboard works like expected but when services enable traefik the dashboard registers the hosts domains as `{service_name}-{compose_project_name}.test` and when I try to access them via browser I get the message: `Internal Server Error`.

Maybe someone has a solution for the problem.

Thanks in advance 
bambamboole

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
