### ISSUE TITLE
Setting up docker is not installation

### ISSUE THREAD

**Issue by john-clark** [containous/traefik#6298]
**Describe the bug**
- Setting up your docker image should not be called installing

**To Reproduce**
1. Click on installation instructions
2. No installation information present

**Expected behavior**
1. Click on installation instructions
2. Information on installing presented

**Comment by ldez** [comment]
Hello,

sorry but I don't understand, what are you talking about? The documentation, the readme, etc. ?

**Comment by john-clark** [comment]
https://docs.traefik.io/getting-started/install-traefik/

The installation instructions presented are for configuring running the software, not for installing, as seen in the binary instructions:

"And run it:
./traefik --help"

The word "installation" is being used incorrectly. A more accurate wording would be "download and run". Installation typically refers to downloading source and compiling or step by step instructions to configuring a binary to work on an end user system. 

For decades people have been described running software virtually not as "installing" but rather as "running in a virtual environment". I came here in search of instructions on installing the software in my environment not running the software in another.

**Comment by scratchmex** [comment]
@john-clark  [What are the difference between install a program and run a program? I need to install a program for running it?](https://www.quora.com/What-are-the-difference-between-install-a-program-and-run-a-program-I-need-to-install-a-program-for-running-it)
> When you install a program you're putting it on your drive [...]

> When you go to run the program the program is moved into virtual memory [...]

> Not all programs need to be “installed” depending on what the complexity of the program is sometimes the source file can be loaded directly into main memory as long as it's an executable file [...]

**Comment by john-clark** [comment]
Yes, but this program is not a program, it is a bundle of programs to make a package.

Example of more appropriate documentation:
https://docs.gitea.io/en-us/install-from-source/

It is ok if you do not wish for people install your program but rather run it in a preconfigured docker but it is misleading to say "Install" when it the instructions are "run".

**Comment by ldez** [comment]
FYI:
- a Docker "run" is a "pull" (download and install image to the computer) and a "run" (launch the program)
- Traefik can also be installed from a binary (there is no ambiguity in this case)

We can add instruction with `docker pull` and `docker run` just to comply with the "installation" definition, but it will not make sense to the user.

Yes the word "installation", the Docker case, can be seen as ambiguous, but I don't think that will produce the end of the world :wink:

**Comment by john-clark** [comment]
That is because of the misinformation being pervade by software programmers who have to deal with end users that do not know how to correctly install and run software. You may have noticed they do have proper install instructions and detailed docker information, NOT just how to run the software.  Closing ticket due to lack of ability to understand or document properly. This shouldn't be something that is that difficult to understand. Installation is for running in end user environment, running in a docker environment is just that, running.

**Comment by ldez** [comment]
> Closing ticket due to lack of ability to understand or document properly. 

I understand your point or view, and I think you understand my point of view.

It's an open source software, the documentation is open source, you can contribute to the documentation.
It's sure that will not accept any kind of changes, but if you have a good idea you can open a PR and I will review it with pleasure.

**Comment by jc21** [comment]
This guy commented with the same template on my project as well - it's negative criticism without hope of improving our open source software. As developers we have actual bugs to fix and real problems to solve. But hey I'll review his PR just like anyone else's.

**Comment by john-clark** [comment]
It is a legitimate question on how to install software without docker. I am attempting to benefit the community by helping to alert with a concern in the documentation. I did give an example project of what I expected to see when I go to install software. No malice is involved. I appreciate and support the work you are doing, I just do not want to use docker. I want to install the software myself.

**Comment by dtomcej** [comment]
@john-clark,

Your bug report is based on a semantical argument on documentation.

You need to be aware that many contributors to these projects are *not* native english speakers, and that bug reports like this can be extremely annoying without any follow up.

You realistically have 2 options moving forwards:

1. Open a PR to improve the documentation and improve the wording you feel is incorrect
2. Do nothing and feel good about the fact that you _may_ be right semantically

Either way, arguing about it here doesn't accomplish anything.

I look forwards to reviewing your PR.
