### ISSUE TITLE
docker.defaultRoute creates both HTTP and HTTPS entrypoints despite no valid HTTPS certificate

### ISSUE THREAD

**Issue by StudioLE** [containous/traefik#6299]
### Do you want to request a *feature* or report a *bug*?

Bug (but could also be considered a feature request)

### What did you do?

Traefik automatically creates routes for docker containers when [no routing rule is applied](https://docs.traefik.io/providers/docker/#defaultrule). These routes are then applied to both `:80` and `:443` entrypoints despite the fact that the route has no valid TLS certificate.

### What did you expect to see?

For a default rule the `:443` entrypoint should only be created automatically if there is a valid TLS certificate.

There are a few different ways to solve this:

1. Let the user specify a default cert resolver in traefik.yml/traefik.toml that is applied to all default routes.:

```
providers:
  docker:
    defaultCertResolver: le
```

2. Give the user control over which entrypoints are used for the default routes:

```
providers:
  docker:
    defaultEntryPoints: web,websecure
... or ...
    defaultEntryPoints: web
```

### What did you see instead?

The `:443` route is created by default with an invalid certificate.

### Output of `traefik version`: (_What version of Traefik are you using?_)

docker-compose.yml: 
```
image: traefik:v2.0
```

```
Version:      2.0.7
Codename:     montdor
Go version:   go1.13.5
Built:        2019-12-09T17:51:21Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

n/a

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

n/a

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
