### ISSUE TITLE
Enable evenly distribution among backend

### ISSUE THREAD

**Issue by molfar** [containous/traefik#631]
Is there any mode or algorithm option that makes Traefik to distribute requests strongly evenly among all backends? So in a final results all backends have approximate quantity of "hits".

I'm looking something like balance algorithm in Haproxy http://cbonte.github.io/haproxy-dconv/1.7/configuration.html#4.2-balance

**Comment by emilevauge** [comment]
Weighted Round Robin using same weights should fit your needs.

**Comment by molfar** [comment]
But how to enable it? In case with docker containers

**Comment by emilevauge** [comment]
This is the default behavior, you don't have to configure anything.

**Comment by molfar** [comment]
Emile, thanks a lot for explaining.

**Comment by molfar** [comment]
Emile, thanks a lot for explaining.
