### ISSUE TITLE
[Documentation] Adding precisely how to reference Kubernetes-CRD Middleware from other providers

### ISSUE THREAD

**Issue by Aniem** [containous/traefik#6318]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

A Kubernetes-crd Middleware lives in kubernetes, and as such, has a kubernetes name (for instance `fooName`) and a kubernetes namespace (for instance `barNS`))
If one needs to configure traefik via another provider a routing using that middleware (for instance kubernetes Ingress middleware with the current master branch (commit 7c430e5c9de5305b2f58dce77cdf50eeba944a25 in my case) ), one needs to give the correct traefik name of the namespace. After some testing and a view of the dashboard, it appears the correct name is `barNS-fooName@kubernetescrd`

As this might be unclear for people getting familiar, I suggest the rule ( `<K8SNamespace>-<K8SName>@kubernetescrd`) be written in the documentation.

Furthermore, and I'll probably create some bug reports on that later, this naming rule can generate collision, for instance if one has a namespace `foo-bar` containing a middleware `baz` and a namespace `foo` containing a middleware `bar-baz`. This might require to change to traefik naming rule for kubernetes-crd, possibly before getting that rule written down in the documentation. I suggest using a `.` as separator, as this character is forbidden in kubernetes objet names.

**Comment by bradjones1** [comment]
Refs https://github.com/containous/traefik/issues/6322

**Comment by SantoDE** [comment]
Hello! 

I just raised a PR for that #6719. Is that enough for your request?

**Comment by traefiker** [comment]
Closed by #6719.
