### ISSUE TITLE
A simple reverse proxy example

### ISSUE THREAD

**Issue by basickarl** [containous/traefik#6319]
I cannot find a simple reverse proxy example that will take `x:y` and forward that request to `z:q` over the `http` protocol.

NGINX has a pretty simple approach:
```
events { }

http {
    upstream mop {
        server mop:3000;
    }
    server {
        listen   80;
        server_name  localhost;
        location /mop {
            proxy_pass http://mop;
        }
        location /mop/1 {
            proxy_pass http://mop;
        }
        location /mop/2 {
            proxy_pass http://mop;
        }
    }
}
```

HAProxy is the same, very simple:

```
global
    daemon
    maxconn 256

defaults
    mode http
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend http-in-path
    bind 127.0.0.1:80
    acl host_sg path_beg /sg
    acl host_sam path_beg /sam
    use_backend sg_nodes if host_sg
    use_backend sam_nodes if host_sam

backend sg_nodes
    server node_1 127.0.0.1:8082/sg check

backend sam_nodes
    server node_1 127.0.0.1:8081/sam check
```

This should be reflected in the Traefik documentation better, right as of now it is nowhere near beginner friendly.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by basickarl** [comment]
It is a configuration issue due to the lack of proficient documentation on this simple matter.

**Comment by basickarl** [comment]
https://community.containo.us/t/example-of-a-very-simple-reverse-proxy/4482/10
