### ISSUE TITLE
Kubernetes documentation error?  tls: {} in HTTPS & TLS: Let's Encrypt

### ISSUE THREAD

**Issue by GoingOffRoading** [containous/traefik#6326]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I'm troubleshooting my own issues getting LetsEncrypt working and spotted an inconsistency in the 2.0 documentation.

### What did you expect to see?

In the Kubernetes Configuration Examples of the v2.0 HTTPS & TLS: Let's Encrypt ( https://docs.traefik.io/v2.0/https/acme/#configuration-examples ) examples of Single Domain, Multi Domain and Multi Domain tls.domain, I would expect to see consistent use of the "tls:" or a note if different versions were required.

### What did you see instead?

--certificatesResolvers.**sample**.acme. in the Enableing ACME

- Single Domain Kubernetes: "tls: {}"
- Multi Domain Kubernetes: "tls: {}"
- Multi Domain Kubernetes: "TLS: certResolve: le"

### What did you expect?

Consistent use of the certificateResolver name...  If it's "sample", then use that.

In this (https://github.com/containous/traefik/pull/6324) branch, "le" is being changed to "myresolver".

So le, myresolve, sample... Having one through all of the documentation would be excellent.

Also, with the three Single/Multi/Multi examples above, what is the field supposed to be?  tls: {}?  The 2.0 User Guide: Kubernetes and Let's Enrcypt use 'default': "tls:   certResolver: default" Example: https://docs.traefik.io/user-guides/crd-acme/#traefik-routers

### Questions?

Let me know... I'm trying to get 2.0 with Lets Encrypt up and running in my own Kubernetes cluster and wanted to pass along my findings as I struggle through my own cluster issues.

**Comment by traefiker** [comment]
Closed by #6324.

**Comment by ldez** [comment]
FYI, the current stable version is v2.1.

We maintain only the last minor of the v2 (ie: v2.1), so the current doc is https://docs.traefik.io/v2.1/https/acme/#configuration-examples
