### ISSUE TITLE
Announce service domains via mDNS

### ISSUE THREAD

**Issue by schildbach** [containous/traefik#6334]
I'd like Traefik to announce a domain within my local network via Multicast DNS (Avahi/Zeroconf/Bonjour). Note this is explicitely *not* requiring a DNS server like #1191 is suggesting.

This would make it a lot easier for deploying multiple docker/docker-compose services on a small home network with just one server. E.g. Node-RED, Riot-Web, Nextcloud could be published as nodered.local, riot.local, nextcloud.local, etc. Home networks usually don't run their own internal DNS server, and services (e.g. Printers, Sensors, etc.)  usually announce themselves in a P2P manner (mDNS).

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

Issue templates help us help you by providing all necessary information.

Please edit your issue and use the available templates:

- [Feature request](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/Feature_request.md)
- [Bug report](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/Bug_report.md)

And remember: each time someone ignores the template, a cute little bunny dies.
<details>
<summary>#SaveTheCuteBunny :heart: :rabbit: :heart:</summary>

![southpark - estrella kill rabbit](https://user-images.githubusercontent.com/5674651/27143914-3cea7896-5130-11e7-81f8-02d8ac2da7a7.gif)

![southpark - estrella kill rabbit2](https://user-images.githubusercontent.com/5674651/27143924-49104c72-5130-11e7-82ae-ccedbd5dfa1c.gif)

</details>

**Comment by mpl** [comment]
Hi @schildbach ,
In addition to respecting the template, could you please describe a specific use-case of a problem, detailing how mDNS would help and fix the problem (just as if we did not know how mDNS works, which is pretty much the case)?

**Comment by schildbach** [comment]
I thought I had described a usecase in the second paragraph. mDNS is decentralized DNS. Any host or device in your local network can publish (broadcast) DNS records, that is hosts or services. Others use these broadcast to resolve named hosts or services.

Now, if you want to deploy e.g. Node-RED in your local network (on a server), you would want to announce a host for that app, e.g. "nodered.local". Traefik would be responsible for this; currently I'm doing this manually. Traefik would use SNI to destinguish between multiple these apps based on mDNS, just as it does already for normal DNS.

**Comment by mpl** [comment]
Sorry, but we do not think that feature belongs among the roles of a reverse-proxy.

**Comment by spacemud** [comment]
This is precisely what I'm trying to do at the moment - understandable that it's not considered to be within the scope of Traefik itself.

I wonder if you were able to find a solution @schildbach ? I'm struggling to create a config that can handle mDNS domains.

**Comment by schildbach** [comment]
@spacemud I've manually configured one mDNS domain per service. You might want to read https://github.com/lathiat/avahi/issues/40 as the intuitive way to add the domains `/etc/avahi/hosts` cannot be used either. See the discussion for workarounds via systemd.

**Comment by viraptor** [comment]
This can be done externally rather than in traefik itself. I've created this project which may satisfy what you're after. https://gitlab.com/viraptor/docker_mdns

**Comment by schildbach** [comment]
I think the solution I (and probably others) are looking for is an automatic one. As soon as a service is brought up that announces a `.local` domain to Traefik, the mDNS domain shall be broadcast. I agree that this is probably out of focus for Traefik itself – on the other hand I currently don't see another component that could automate this.
