### ISSUE TITLE
[Documentation] Dynamic Variable of requested page

### ISSUE THREAD

**Issue by brucke** [containous/traefik#6343]
Dynamic Variable of requested page

Hi, i use an oauth2 forwarder and for the redirect to the initial requested page i need an HTTP Header with the information about the requested page. Is there an dynamic variable with this information i can use in the middleware setting? 

I set a static redirect in the moment

```yaml
- "traefik.http.middlewares.testheader.headers.customrequestheaders.X-Auth-Request-Redirect=/whoami"
```

But i want a dynamic redirect: 

```yaml
- "traefik.http.middlewares.testheader.headers.customrequestheaders.X-Auth-Request-Redirect={requested_url}"
```

Doese somebody have an idea? 

Thanks! Have a nice day. 

i created already an ticket in the outh2 forwarder, but i guess its more an treafik issue. 

https://github.com/pusher/oauth2_proxy/issues/397

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
