### ISSUE TITLE
How to revoke a Let's Encrypt cerificate?

### ISSUE THREAD

**Issue by danielpetisme** [containous/traefik#635]
I configured traefik to with ACME, but now I have to revoke one of my certificate (to free the slot). 
Based on this thread [Certificate Revoke Steps](https://community.letsencrypt.org/t/certificate-revoke-steps/15746) I need the `pem` but traefik store everything in the JSON `storageFile`.

Do I have to copy/paste a part of the content of the JSON file to create the certificate file?

Thanks

**Comment by emilevauge** [comment]
@danielpetisme Yeah, we definitely lack some tooling on ACME certificates. Certificates are stored in the `DomainsCertificates` section. You can use the `PrivateKey` and `Certificate` that are in binary (DER). You should be able to convert those file in PEM for example. I will try to make a tool to revoke certs easily in the futur :)

**Comment by danielpetisme** [comment]
Can you be more explicit on the conversion steps please ?
I extracted the content of the field `PrivateKey` into `privateKey.der` and `Certificate` into `certificate.der`. Then I tried to convert them using `openssl x509 -inform DER -in <file> -out <file>` but it failed.
I'm  not very familiar with the `openssl` command 😢 
I tried to have a look to the GO code but didn' t help me. (in particular to the `acme_test.go` but there the certificates' content are not binary), 
Can you please help me ?

**Comment by danielpetisme** [comment]
I finally succeed, the trick is that the `PrivateKey` and the `Certificate` are store in plain PEM format but `base64` encoded. Traefik use the `pem.EncodeToMemory` function and according to the source code of [`encoding/pem`](https://golang.org/src/encoding/pem/pem.go), the content is a `base64` encoded array of bytes. Once decoded the content is not binary (is a clear PEM format).
From what I found only the Traefik default certificate is converted into [DER once generated].(https://github.com/containous/traefik/blob/master/acme/crypto.go#L45)

So finally 
```
cat acme.json | head -n <lineOfthePrivateKey> | tail -n 1 | cut -d ":" -f 2 | cut -d "\"" -f 2 | base64 --decode > private.key
cat acme.json | head -n <lineOftheCertificate> | tail -n 1 | cut -d ":" -f 2 | cut -d "\"" -f 2 | base64 --decode > certificate.pem
letsencrypt/letsencrypt-auto revoke -d <domain> --cert-path ./certificate.pem --key-path private.key
```

I post the above ugly snippet to help people, I don't need a more elaborate script right now...

**Comment by SAprelov** [comment]
@emilevauge does you store fullchain.pem in acme.json?

**Comment by ldez** [comment]
I'll close this issue, because I think the question is answered, but feel free to continue the conversation.

**Comment by sentriz** [comment]
here's a script based on @danielpetisme's 
```
#!/usr/bin/env bash

set -e 

ACME_FILE=/opt/traefik/acme.json # change

jq -r ".Certificates | .[] | select(.Domain.Main == \"$1\").Key" < $ACME_FILE | base64 --decode > /tmp/a.key
jq -r ".Certificates | .[] | select(.Domain.Main == \"$1\").Certificate" < $ACME_FILE | base64 --decode > /tmp/a.pem
letsencrypt revoke -d "$1" --key-path /tmp/a.key --cert-path /tmp/a.pem
```

use it like `$ ./script your.domain.com`
