### ISSUE TITLE
HostRegexp: syntax docs very unspecific

### ISSUE THREAD

**Issue by tagirb** [containous/traefik#6351]
[Documentation on `HostRegexp()`](https://docs.traefik.io/routing/routers/) is very unspecific. It states:

```
HostRegexp(`traefik.io`, `{subdomain:[a-z]+}.traefik.io`, ...) | Check if the request domain matches the given regexp.
```

It took me several hours to figure out that the regexp needs to be in the curly braces and prepended by `some_id:`. So, in these examples:
* ``HostRegexp(`^host.name$`)`` matches the literal `^host.name$`
* ``HostRegexp(`{^host.name$}`)`` matches no idea what, probably the literal `{^host.name$}`
* and only ``HostRegexp(`{host:^host.name$}`)`` DOES match the regexp `^host.name$`

Could you please add a very explicit explanation on how `HostRegexp()` parsing is done into the documentation?

**Comment by sbrattla** [comment]
I'd also like to add that an example with multiple regex "sections" would be very useful. I'm trying to work with something like `{www:(www\.)?}example.{tld:[a-z\.]+}` but haven't been able to get any variant of this working yet.

**Comment by agimenez** [comment]
I think it's been there already for a long time in https://docs.traefik.io/routing/routers/#rule , just under the the table, warning box named "Regexp syntax":

```
In order to use regular expressions with Host and Path expressions, you must declare an arbitrarily 
named variable followed by the colon-separated regular expression, all enclosed in curly braces. 
Any pattern supported by Go's regexp package may be used (example: /posts/{id:[0-9]+}).
```
Is that what you were missing?

**Comment by tagirb** [comment]
Exactly.. Sorry, I've totally overseen that.
