### ISSUE TITLE
I can't redirect to an external domain in traefik version 2.1.

### ISSUE THREAD

**Issue by Redskyer** [containous/traefik#6354]
### Do you want to request a *feature* or report a *bug*?

Not sure if its a bug or not.

### What did you do?

I've tried to convert my config from traefik version 1.7 to 2.1.

### What did you expect to see?

A redirect from http://service1.domain.com to https://domain.com:1234 or another domain like https://domain2.net:1234.

### What did you see instead?

That it doesn't work, because I just can put an ip-address instead of a name on my url in the service section of traefik version 2.1.
In traefik version 1.7 it was possible to use domain-names in the backend server url.

Thats the main reason for, becaus I can't move to traefik version 2.1. Do you have an idea how I could implement it alternatively?

### Output of traefik version: (What version of Traefik are you using?)

Traefik version 2.1.4 built on 2020-02-06T17:10:06Z

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Traefik 1.7 traefik.toml
```
[file]

[frontends]
    [frontends.service1]
        backend = "service1"
    [frontends.service1.headers]
        SSLRedirect = true
    [frontends.service1.routes.service1]
        rule = "Host:service1.domain.com"

[backends]
[backends.service1]
    [backends.service1.servers.service1]
        url = "https://domain.com:1234"
```

Traefik 2.1 traefik.toml
```
[http.routers]
  [http.routers.service1]
    rule = "Host(`service1.domain.com`)"
    service = "service1"
    middlewares = ["https-redirect"]
	[http.routers.service1.tls]

[http.middlewares]
  [http.middlewares.https-redirect.headers]
    sslTemporaryRedirect = true

[http.services]
  [http.services.service1.loadBalancer]
    [[http.services.service1.loadBalancer.servers]]
      url = "https://domain.com:1234"
```

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
