### ISSUE TITLE
mtls options based on path

### ISSUE THREAD

**Issue by abrausch** [containous/traefik#6362]
Hi,
I have a question. Is it somehow possible to define mtls options based on path rules?
In our environment we want to use traefik to provide access to some grpc services and our legacy java application (tomcat based).
This java application has some URLs (like /manage) which needs client cert support and some URLs (like /api) which should not use client certificates.
So the question is can I configure traefik to use different tls options for the same host but different URLs paths?

Thanks in advance 
Alex

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
