### ISSUE TITLE
Security contact / follow up to issue #6224

### ISSUE THREAD

**Issue by joernchen** [containous/traefik#6363]
I've used the form mentioned in issue #6224 about a month ago to
get in touch about some security relevant concerns. However I've not 
gotten any response yet.

Could someone from the traefik team at least let me know if the report
is being considered at all?

Thanks

joern

**Comment by ldez** [comment]
Hello,

Yes we received your report.

Normally someone has or will answer you.

Thanks.

**Comment by joernchen** [comment]
Well in this case I eagerly await your response.

I however might publish some details by end of April.
