### ISSUE TITLE
ForwardAuth forward cookie to auth server

### ISSUE THREAD

**Issue by Matthijsy** [containous/traefik#6366]
### Do you want to request a *feature* or report a *bug*?
Feature

### What did you expect to see?
I am using the ForwardAuth to protect my traefik dashboard. However, my auth server needs to identify which user wants to login. Currently this information is in a cookie of the domain (the auth server and the traefik dashboard are on the same domain). It would be great if I could control the ForwardAuth in such a way that it would forward this cookie to the server such that it can identify the user.

I think this is not possible at the moment, but if I am wrong please help me how to get this done. I do not understand how the auth server currently knows how to give access or deny access since it does not receive any information if I am right.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
