### ISSUE TITLE
Documentation: YAML vs CLI

### ISSUE THREAD

**Issue by dm17** [containous/traefik#6367]
I have a general question about your documentation:
When one of the categories is left out of your examples. For example, in some examples there is no "CLI," like for the priorities in routers doc. Does this mean that priorities cannot be defined using CLI (aka "labels")? Or is Traefik V2 totally "label compliant," as it were?
Thanks!

**Comment by ldez** [comment]
hello,

Configuration in Traefik can refer to two different things:

- The fully dynamic routing configuration (referred to as the dynamic configuration)
- The startup configuration (referred to as the static configuration

https://docs.traefik.io/v2.1/getting-started/configuration-overview/

the [static configuration](https://docs.traefik.io/v2.1/getting-started/configuration-overview/#the-static-configuration) can define with:
- CLI flags
- file (yaml, toml)
- env vars



The [dynamic configuration](https://docs.traefik.io/v2.1/getting-started/configuration-overview/#the-dynamic-configuration) can define with:
- file (yaml, toml)
- labels
- ingress
- ingressRoute (CRD)





If you have more question, you can ask it on the [community forum](https://community.containo.us)
