### ISSUE TITLE
Please include support for Dynu.com 

### ISSUE THREAD

**Issue by MichaelNZ85** [containous/traefik#6377]
Would it be possible to add Dynu.com to the list of DNS providers on [this page](https://docs.traefik.io/https/acme/)? It is incredibly cheap (US$9.99 per year) and does a great job.

**Comment by ldez** [comment]
Hello,

The DNS providers support come from [lego](https://github.com/go-acme/lego)

An issue already exist https://github.com/go-acme/lego/issues/986
