### ISSUE TITLE
Certificate Management in Dashboard

### ISSUE THREAD

**Issue by Dandrum** [containous/traefik#6381]
### Feature
- Show current Certs in Dashboard and their Information (validate date, expire date, version (Lets encrypt rate check for Duplicates etc)
- Button for Revoke Certs or Force Renew them.
- Show a list of Certs based on ACME/Certbot list from LE server instead of ACME.json
- If ACME.json is empty or dosnt have a Cert but LE Server contains Certs for Domain and User (Email + Priv Key) Then reuse the Server Cert instead of trying to request a new one (prevent LE limits)

**Comment by ldez** [comment]
Duplicate of #6156
