### ISSUE TITLE
Documentation bug: /v1.7/user-guide/docker-and-lets-encrypt/

### ISSUE THREAD

**Issue by adamshand** [containous/traefik#6385]
The first line in the "Container labels" section of the above page states:

> First, we specify the backend name which corresponds to the actual service we're routing to.

However the stanza that it is referring to doesn't have a backend name.

> - "traefik.docker.network=web"
> - "traefik.enable=true"
> - "traefik.basic.frontend.rule=Host:app.my-awesome-app.org"
> - "traefik.basic.port=9000"
> - "traefik.basic.protocol=http"
> - "traefik.admin.frontend.rule=Host:admin-app.my-awesome-app.org"
> - "traefik.admin.protocol=https"
> - "traefik.admin.port=9443"

**Comment by traefiker** [comment]
Closed by #6386.
