### ISSUE TITLE
Cant access dashboard / basicAuth doesnt work

### ISSUE THREAD

**Issue by emprove** [containous/traefik#6387]
Bug. 
Win 10 x64.

### What did you do?

Trying to setup dashoard with basic auth middleware.

### What did you expect to see?

Popup when accessing host url.

### What did you see instead?

404 page not found.

### docker compose config
  traefik:
    image: traefik:2.1.4
    command:
      - "--log.level=DEBUG"
      - "--api.dashboard=true"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.http.routers.api.rule=Host(`localhost`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=auth"
      -"traefik.http.middlewares.auth.basicauth.users=admin:$$apr1$$yneugp6h$$ngegdH9eDmaaoPGFN0vvP1"

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
time="2020-02-27T08:33:36Z" level=info msg="Configuration loaded from flags."
time="2020-02-27T08:33:36Z" level=info msg="Traefik version 2.1.4 built on 2020-02-06T17:10:06Z"
time="2020-02-27T08:33:36Z" level=debug msg="Static configuration loaded {\"global\":{\"checkNewVersion\":true},\"serversTransport\":{\"maxIdleConnsPerHost\":200},\"entryPoints\":{\"http\":{\"address\":\":80\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{}}},\"providers\":{\"providersThrottleDuration\":2000000000},\"api\":{\"dashboard\":true},\"log\":{\"level\":\"DEBUG\",\"format\":\"common\"}}"
time="2020-02-27T08:33:36Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://docs.traefik.io/v2.0/contributing/data-collection/\n"
time="2020-02-27T08:33:36Z" level=info msg="Starting provider aggregator.ProviderAggregator {}"
time="2020-02-27T08:33:36Z" level=debug msg="Start TCP Server" entryPointName=http
time="2020-02-27T08:33:36Z" level=info msg="Starting provider *traefik.Provider {}"
time="2020-02-27T08:33:36Z" level=debug msg="Configuration received from provider internal: {\"http\":{\"services\":{\"api\":{},\"dashboard\":{}}},\"tcp\":{},\"tls\":{}}" providerName=internal
time="2020-02-27T08:33:36Z" level=debug msg="No default certificate, generating one"
time="2020-02-27T08:43:57Z" level=warning msg="Error checking new version: Get https://update.containous.cloud/repos/containous/traefik/releases: dial tcp 165.227.206.205:443: connect: connection refused"
```

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by trankchung** [comment]
@emprove Make sure that you don't have `api.insecure=true` in your settings.

**Comment by emprove** [comment]
> @emprove Make sure that you don't have `api.insecure=true` in your settings.

Yes it is.
`command:
- "--log.level=DEBUG"
- "--api.dashboard=true"`
