### ISSUE TITLE
Routing rules support matching cookie

### ISSUE THREAD

**Issue by letian0805** [containous/traefik#6391]
Most web clients use cookie to store user and client information. We want to be able to do A / B testing based on user information and client information. So I wonder if it is possible to support matching cookie in routing rules?

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
