### ISSUE TITLE
TLS client cert conflicts with ACME

### ISSUE THREAD

**Issue by sprohaska** [containous/traefik#640]
When configuring client cert with PR https://github.com/containous/traefik/pull/461, ACME does not work anymore. Redacted error message:

```
server.go:2317: http: TLS handshake error from 66.133.109.36:49733: tls: client didn't provide a certificate
level=error msg="map[...:acme: Error 400 - urn:acme:error:tls - Failed to connect to ...:443 for TLS-SNI-01 challenge...]"
```

I haven't looked into the ACME implementation. Maybe it's possible to add a special case that disables client cert for ACME challenges.

**Comment by ldez** [comment]
Closed in profit of #942  - Feel free to subscribe there for updates.
