### ISSUE TITLE
Traefik does not pick up pre-existing IngressRoute CRD objects on the cluster when installed

### ISSUE THREAD

**Issue by dbsanfte** [containous/traefik#6403]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

- Installed Traefik in Namespace A
- Installed some services and IngressRoute CRD objects into Namespace B (Traefik sees these fine and picks them up)
- Uninstalled Traefik from Namespace A
- Reinstalled Traefik into Namespace A

### What did you expect to see?

I expected Traefik to 'see' the pre-existing IngressRoute objects that it had previously seen in Namespace B

### What did you see instead?

Traefik does not see these objects. I must uninstall and reinstall these objects in Namespace B before Traefik will pick them up again.

### Output of `traefik version`: (_What version of Traefik are you using?_)

v2.1.4

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Kubernetes v1.17.3
Kubernetes CRD provider active in Traefik.

**Comment by rtribotte** [comment]
Hi,

I've tried to reproduce the bug, but I didn't succeed. 
What did you mean by "uninstalled Traefik from namespace A", which command did you used to do that ?

**Comment by dbsanfte** [comment]
Hiya,

I am installing / uninstalling Traefik and the CRD definitions using a Helm template. To uninstall I am doing `helm del --purge`. Thinking about it, I imagine this removes the CRD defs from Namespace A and perhaps Kubernetes then decides to remove the CRD objects themselves from Namespace B?

**Comment by rtribotte** [comment]
Hi @dbsanfte,

Did you manage to see if the CRD defs from Namespace B were deleted ?

**Comment by dbsanfte** [comment]
Just tested this and looks like that was exactly what was happening. 

I moved the CRD inserts outside of the Helm template and insert them with a simple `kubectl apply -f` and can confirm the CRDs in Namespace B are picked up fine by Traefik when it is reinstalled.

Will close this. Cheers.
