### ISSUE TITLE
How to ignore specific subdomain with regex 

### ISSUE THREAD

**Issue by bittu664** [containous/traefik#6412]
I am using traefik v1.7 and I have a domain name ``` example.com ```  now what I want is to ignore this specific subdomain **admin** , **sync** , **manage** , **schedule** .  in regex expr wild card pattern domain like this :-   
``` "traefik.frontend.rule=HostRegexp: example.com, {subdomain:[a-z]+}.example.com" ```

So how to do this.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
