### ISSUE TITLE
Running Traefik v2 from BASH causes error: "msg="error while parsing rule Host(bash: "

### ISSUE THREAD

**Issue by Shogun8** [containous/traefik#6415]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I attempted to run the Traefik v2 container without loading any local files. I have a situation where I do not want to keep any static or dynamic TOML files, I wish only to load all of the arguments in the command line. 
### What did you expect to see?
I expect it to work exactly the same as it would when using static and dynamic TOML files.

### What did you see instead?
I couldn't connect to the dashboard or any applications behind the Traefik proxy.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.1.4
Codename:     cantal
Go version:   go1.13.7
Built:        2020-02-06T17:10:06Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```bash
#This is executed entirely form the command line in Fedora CoreOS

sudo docker run -it --rm --name traefik-proxy -p 80:80 -p 443:443 \
    --hostname traefikproxy \
    --network public \
    --network socketproxy \
    --log-driver=json-file \
    --label "traefik.enable=true" \
    --label "traefik.docker.network=public" \
    --label "traefik.http.routers.traefik.entrypoints=web" \
    --label "traefik.http.routers.traefik.rule=Host(`ui.docker.localhost`)" \
    --label "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=web-secure" \
    --label "traefik.http.routers.traefik.middlewares=traefik-https-redirect" \
    --label "traefik.http.routers.traefik-secure.tls=true" \
    --label "traefik.http.routers.traefik-secure.entrypoints=web-secure" \
    --label "traefik.http.routers.traefik-secure.rule=Host(`ui.docker.localhost`)" \
    --label "traefik.http.routers.traefik-secure.service=api@internal" \
	traefik:latest \
    --providers.docker=true \
    --providers.docker.exposedbydefault=false \
    --providers.docker.endpoint="tcp://socket-proxy:2375" \
    --providers.docker.network=public \
    --providers.docker.defaultrule="Host(`.docker.localhost`)" \
    --entrypoints.web.address=:80 \
    --entrypoints.web-secure.address=:443 \
    --api.dashboard=false \
    --api.insecure=true \
    --api.debug=true
```

BTW, It seems to connect to the docker socket proxy just fine.
```bash
sudo docker run --rm -d --name socket-proxy \
    --env CONTAINERS=1 \
    --env NETWORKS=1 \
    --env TASKS=1 \
    --network=socketproxy \
    -v /var/run/docker.sock:/var/run/docker.sock \
    --log-driver=json-file \
    --label traefik.enable=false \
	tecnativa/docker-socket-proxy
```
### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```bash
time="2020-03-03T00:02:40Z" level=info msg="Configuration loaded from flags."
time="2020-03-03T00:02:40Z" level=error msg="error while parsing rule Host(bash: ui.docker.localhost: command not found): 1:10: missing ',' in argument list" entryPointName=web routerName=traefik@docker
time="2020-03-03T00:02:40Z" level=error msg="error while parsing rule Host(bash: ui.docker.localhost: command not found): 1:10: missing ',' in argument list" routerName=traefik-secure@docker entryPointName=web-secure
```

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
