### ISSUE TITLE
Add status URL for service up checks

### ISSUE THREAD

**Issue by wizzu** [containous/traefik#642]
It would be useful to have a URL provided by Traefik which can be used to detect that the service is running/up. E.g. "ping" or "gtg" URLs, which return a static 200 OK response to HTTP requests.

The use case where I ran across this is running Traefik inside a pod in a Kubernetes cluster. Kubernetes supports liveness and readiness probes via HTTP requests to a URL in the container, detecting if/when the container is ready to respond to requests (and also, if the probe requests fail, when it is considered down). There are probably other use cases (AWS ELB comes to mind) where this kind of feature would be useful.

I resorted to using the /health endpoint from the dashboard API for the purpose, but it's returning metrics which aren't needed for this use case, so doesn't seem ideal.

**Comment by emilevauge** [comment]
This should be addressed by #630

**Comment by wizzu** [comment]
Oh, that's fast. I had a look at the open issue listing, but apparently that was already merged so didn't show up. :) Looks indeed like it was already addressed. Thanks for the fast response!
