### ISSUE TITLE
Middleware: Test for header value

### ISSUE THREAD

**Issue by pierresteiner** [containous/traefik#6424]
**Feature request**

It would be awesome if Traefik could test for a header value with a middleware

**Context**

We are currently using CloudFront in front of a k8s cluster (with Traefik as the ingress - of course), and we would like to enforce that only connexion from CloudFront get forwarded to pods

This is usually typically done by adding a secret header (https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/add-origin-custom-headers.html). Sadly at this stage it seems that traefik has no way of checking the presence of that header in an ingress context. This could be done with a router rule, but it is not relevant with the k8s ingress?

Cherry on the cake would be to be able to define this middleware at the entrypoint level.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
