### ISSUE TITLE
Feature request - Show active connections in web GUI

### ISSUE THREAD

**Issue by mr-manuel** [containous/traefik#6427]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

It would be great to see in the web GUI dashboard how many connections are actually active.

Maybe also over the past 15, 30 and 60 minutes, but therefor we already can use metrics?

**Comment by SantoDE** [comment]
Hey @mr-manuel ,

thanks for your interest in the project. Currently, we don't plan to show connections in the dashboard.  What would be your use-case? We're exporting a couple metrics already, e.g. a connection count. So what are you looking for exaclty?

Looking forward to your feedback!

**Comment by mr-manuel** [comment]
Hello @SantoDE,

sorry for late response. This would only be a fast method to see how many concurrent connections are opened to know for example if the server can be upgraded since there is not much traffic or something like that. But if I'm the only one you can close this FR.
