### ISSUE TITLE
implement rate limiting / api access (like tollbooth)

### ISSUE THREAD

**Issue by aparcar** [containous/traefik#643]
to limit access rates for specific resources a configuration like in [nginx limit module](http://nginx.org/en/docs/http/ngx_http_limit_req_module.html) would be nice

are there any plans to enable this feature?

the existing solution called [tollbooth](https://github.com/didip/tollbooth) could simply be integrated

**Comment by jangie** [comment]
You may be interested in the functionality enabled with maxconn configuration.

**Comment by aparcar** [comment]
thanks for the advice!

Still, I'd like to limit an API, only _n_ requests a day without an authentication

**Comment by michaelkrog** [comment]
I second this.  In a microservice environment rate limiting would often fit nicely in the proxy.

**Comment by errm** [comment]
I agree this sounds like a great feature to have....

**Comment by aparcar** [comment]
anyone looked into this?

**Comment by SuperQ** [comment]
I'm also interested in options to do global rate limiting for clusters and/or distributed services.  Even best-effort global rate limiting would go a long way towards preventing large scale API abuse.

**Comment by aparcar** [comment]
@SantoDE any updates?

**Comment by IngoThierack** [comment]
Also interessted on this feature. We are need here, to limit on a customer/api.
At the moment we use an nginx, but need in the future a more dynamic solution.
We do an limit on user/api, authentification done by nginx. So it would be nice to see this in trafik.

**Comment by machzqcq** [comment]
Traefik is an awesome tool and I experimented with Docker Swarm - works great. 
I second that we need rate-limits like [api-umbrella](https://api-umbrella.readthedocs.io/en/latest/api-consumer/rate-limits.html) for e.g.

**Comment by timoreimann** [comment]
Our to-go middleware tooling `oxy` [already comes with a rate limiting package](https://godoc.org/github.com/vulcand/oxy/ratelimit). Should be fairly simple to integrate.

**Comment by ldez** [comment]
Closed by #2034.
