### ISSUE TITLE
How to enable "X-Traefik-reqid" header?

### ISSUE THREAD

**Issue by hmeal** [containous/traefik#6436]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I want to use this header for create relationship between Traefik logs and Back-End logs

traefik version:
> Version:      v1.7.14
> Codename:     maroilles
> Go version:   go1.12.8
> Built:        2019-08-14_09:46:58AM
> OS/Arch:      linux/amd64

traefik.toml

> defaultEntryPoints = ["https","http"]
> [entryPoints]
>   [entryPoints.http]
>   address = ":80"
>   [entryPoints.https]
>   address = ":443"
>     [entryPoints.https.tls]
>   [entryPoints.traefik]
>     address = ":8080"
>     [entryPoints.traefik.auth.basic]
>     users = ["admin:password"]
> [kubernetes]
>   [kubernetes.ingressEndpoint]
>     publishedService = "traefik/traefik-ingress-controller-http-service"
> [ping]
> entryPoint = "http"
> [api]
> entryPoint = "traefik"
> [log]
>   filePath = "/logs/service.log"
>   level = "WARN"
>   format = "json"
> [accessLog]
>   format = "json"
>   [accessLog.fields]
>     defaultMode = "drop"
>   [accessLog.fields.headers]
>     defaultMode = "drop"
>   [accessLog.fields.names]
>     "ClientHost" = "keep"
>     "RequestMethod" = "keep"
>     "RequestPath" = "keep"
>     "RequestProtocol" = "keep"
>     "OriginStatus" = "keep"
>   [accessLog.fields.headers.names]
>     "Authorization" = "keep"

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
