### ISSUE TITLE
Docs for kubernetes tls integration not clear

### ISSUE THREAD

**Issue by simonstumpf** [containous/traefik#6438]
Hi Guys 
So I just implemented the TLS integration into a kubernetes cluster with traefik.
I followed the steps given by your [docs](https://docs.traefik.io/v1.7/user-guide/kubernetes/#add-a-tls-certificate-to-the-ingress)

However I needed to add the following lines to the traefik daemonset:
`       
        - containerPort: 443
          hostPort: 443
          name: https
          protocol: TCP
`

Don't you think this should be added to the docs?

**Comment by simonstumpf** [comment]
area/documentation

**Comment by traefiker** [comment]
Closed by #6457.
