### ISSUE TITLE
Traefik breaks all backends when incorrect label is used

### ISSUE THREAD

**Issue by dac388** [containous/traefik#6445]
Opening his issue again, because it was rudely closed, even though this problem crashed out entire production cluster of over 70 public services.  Please don't close it again, i'm happy to give any additional information you need to reproduce because we've confirmed this issue is as described by retesting before submitting the first time.  Traefik log even produces an error describing the incorrect regex escape character, so I'm not sure why issue issue 6431 would get closed.

Bug

What did you see?
Deploying a service with this label
"traefik.frontend.redirect.regex=^https?://(test\.beta\.redacted\.org|redacted\.com)/(.*)"

Causes the (preexisting) service to be unavailable (504 bad gateway).
Also, any other services deployed after this label is deployed will also begin to 504.
If traefik is redeployed or restarted after a service is deployed with this label ALL backends are not found (404).

I cannot post the correct syntax because slashes are being removed when I click update comment.

Everywhere there are two backslashes shoudl be changed to four backlashes because of escape characters in docker-compose.yml. We have that deployed and working now.

What did you expect to see?
There is a syntax error in that label. Traefik does produce an error identifying the incorrect syntax.

I do expect this could make the service with the label unavailable. I do not expect this would break other backends

Output of traefik version: (What version of Traefik are you using?)
Confirmed behavior with 1.7.20 and 1.7.21 (both alpine).

What is your environment & configuration (arguments, toml, provider, platform, ...)?
traefik.toml

InsecureSkipVerify = true
logLevel = "INFO"
defaultEntryPoints = ["https","http"]

[traefikLog]

[accessLog]
  [accessLog.filters]
  [accessLog.fields]
    defaultMode = "keep"
[entryPoints]
  [entryPoints.ping]
  address = ":8090"
  [entryPoints.http]
  address = ":80"
  compress = true
    [entryPoints.http.proxyProtocol]
      trustedIPs = ["redacted"]
    [entryPoints.http.forwardedHeaders]
      trustedIPs = ["redacted", "redacted"]
  [entryPoints.https]
  address = ":443"
  compress = true
    [entryPoints.https.tls]
	minVersion = "VersionTLS11"
      [[entryPoints.https.tls.certificates]]          
		  certFile = "redacted.cer"
		  keyFile = "redacted.key"
    [entryPoints.https.proxyProtocol]
      trustedIPs = ["redacted"]
    [entryPoints.https.forwardedHeaders]
      trustedIPs = ["redacted", "redacted"]

[ping]
entryPoint = "ping"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "docker.localhost"
watch = true
swarmmode = true
Service was deployed with docker-composer.yml, to Docker Datacenter using swarm mode orchestrator.

These are the other labels used in docker-compose.yml

      - "traefik.frontend.whiteList.sourceRange=${TRAEFIK_WHITELIST:-redacted}"
      - "traefik.docker.network=is-2"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:${TRAEFIK_HOST}"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.backend.loadbalancer.stickiness=true"
      - "traefik.frontend.headers.SSLRedirect=true"

**Comment by ldez** [comment]
Please speak in #6431 instead of creating a new issue.

Thank you.
