### ISSUE TITLE
TLS options: defined through CLI / env var

### ISSUE THREAD

**Issue by FuNK3Y** [containous/traefik#6453]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

It would be convenient to be able to define [tls ](https://docs.traefik.io/v2.2/https/tls/) options (minVersion, cipherSuites, ...) through the the CLI / var env.

Something like:
`--tls.options.default.minVersion=...`
`--tls.options.default.cipherSuites=...`

Right now it can only be done through the file provider (and k8s), while it works fine it requires me to manage an additional file on top of the docker-compose file; which is cumbersome as everything else can be managed dynamically.

This could also play nice with the recently introduced `--entrypoints.<name>.http.tls.options` flag from 2.2

It is somehow related to: https://github.com/containous/traefik/issues/5507 (CLI vs Label)

**Comment by lawrencedudley** [comment]
This would be really helpful, we have 1,596 ingress routes currently. Updating them all to add TLSOptions feels like something I don't want to do.

**Comment by ldez** [comment]
Hello,

We prefer the approach #5507.

We don't plan to add more options in the static configuration.

Thanks.
