### ISSUE TITLE
add go template support for other backend provides

### ISSUE THREAD

**Issue by wjzhou** [containous/traefik#6462]
# Do you want to request a *feature* or report a *bug*?
Feature

### What did you expect to see?
The current label based docker provider is kind of verbose and hard to use. (the fact that the label can not be changed after lunch makes it harder)

The file provider's go template is very powerful and well known for user. But it can not be used as is for docker provider because it need the dynamic information from docker provider.

---

What in my mind:
1. have a template folder and let traefik load the folder.
2. label the container with 
` -traefik.template="TEMPLATE_NAME"`
3. when the traefik get notification from docker, it runs the template and pass-in the dynamic information of the docker
e.g.`name, ip, exposed ports, etc.`
4. feed the generated content to file provider. (have an option to log the generated file will be very helpful for debugging.) 
---
 
Example usage: 
1. defined template to use
```
#/etc/traefik/template/websecure.toml
#context . from the traefik, where .name is the container name, ip is the container ip, port is the first exposed port 
   [http.routers.{{.name}}]
      entryPoints = ["websecure"]
      service = "service-{{$name}}"
      rule = "Host(`{{$name}}.example.com`)"
      [http.routers.{{$name}}.tls]
        certResolver = "dns"
        [[http.routers.{{$name}}.tls.domains]]
          main = "*.example.com"
    [[http.services.service-{{$name}}.loadBalancer.servers]]
      url = "{{.ip:.port}}"
```
2. label the container with
`-traefik.template="websecure.toml"`
---
Instead of the current verbose labels for each container:
```
        --label "traefik.http.routers.$DNAME.rule=Host(\`$DNAME.example\`)" \
        --label "traefik.http.routers.$DNAME.tls=true" \
        --label "traefik.http.routers.$DNAME.entrypoints=websecure" \
        --label "traefik.http.services.$DNAME.loadbalancer.server.port=8888" \
        --label "traefik.http.routers.$DNAME.tls.certResolver=dns" \
        --label "traefik.http.routers.$DNAME.tls.domains[0].main=*.wzhou.net" \
```
---
Summary:
1. This would greatly reduce the verbose of the docker labels. 
2. Need minimal programing effect. (reuse most of both the docker and file provider)
3. (Hidden) Provide a way to change configuration if needed. (e.g. if the main domain name change, instead of need to relaunch all the containers with updated label, we can update the template)

**Comment by ldez** [comment]
Hello,

We have already introduce in v2.2 a way to reduce the verbosity: https://github.com/containous/traefik/pull/6417

The discussion about simplification still continue here https://github.com/containous/traefik/issues/5630

We don't plan to re-introduce the template system of the v1.

You can follow and discuss in https://github.com/containous/traefik/issues/5630

Thank you for the detailed issue.

**Comment by wjzhou** [comment]
Your change will be very helpful for setup for the common case 👍.

But I still believe this proposal is different/complementary to the default routers configuration feature.

For me, I need the flexible of go template to providing several kinds of contains, and access to the go template will be very helpful.
e.g. the tensorflow kind:
need to expose both 8888 and 6006 ports

Could you consider this proposal one more time?
