### ISSUE TITLE
Request URL variable for header support

### ISSUE THREAD

**Issue by genert** [containous/traefik#6463]
With NGINX, you are able to set proxy header values with `$host`, `$scheme` and `$request_uri` variables:
```
proxy_set_header Host                    $host;
proxy_set_header X-Scheme                $scheme;
proxy_set_header X-Auth-Request-Redirect $request_uri;
```
Which allows you to do even fancier stuff like following (in multiple domains scenario):
```
proxy_set_header X-Auth-Request-Redirect $scheme://$host$request_uri;
```

We would like to see same feature in Traefik. Currently Traefik does support `$host` variable and it can be done through following configuration option:

```yaml
- "traefik.http.services.myservice.loadbalancer.passhostheader=true"
```

Traefik could add some extra configuration options to pass scheme, request uri with full redirect url as well:
```yaml
- "traefik.http.services.myservice.loadbalancer.passschemeheader=true"
- "traefik.http.services.myservice.loadbalancer.passrequesturiheader=true"
- "traefik.http.services.myservice.loadbalancer.passfulluriheader=true"
```

However, while this could be the easiest way to go then it does not solve the underlying problem as stated by some issues (#5063).

Perhaps this could be solved by allowing to configure proxy headers dynamically just like it is done with service routes:
```yaml
- "traefik.http.services.myservice.loadbalancer.passheaders=Scheme(`X-Scheme`),RequestURI(`X-Auth-Request-Redirect`),FullURI(`X-Auth-Full-Request-Redirect`)"
```

Where Traefik gives available methods which takes header name as parameter to be returned as header key with method's given value. This approach allows Traefik to add as many variables as it wishes for while keeping configuration option clean and clear for end-users.

This needs to be thought through... What are your opinions on this?

**Comment by genert** [comment]
Or perhaps like this:

```yaml
- "traefik.http.services.myservice.loadbalancer.passheaders.X-Scheme=$scheme"
```

or

```yaml
- "traefik.http.services.myservice.loadbalancer.passheaders=Header(`X-Scheme`, Scheme()),Header(`X-Auth-Request-Redirect`, RequestUri())"
```

or

```yaml
- "traefik.http.services.myservice.loadbalancer.passheaders.X-Scheme=Scheme()"
```

**Comment by kallangerard** [comment]
I agree. Lack of variables means forwardAuth and pusher/oauth_proxy2 can't work correctly together.

As it stands the 301 redirect error will take the browser to the oauth login page, but there's no way to pass the originally requested url to redirect to after success login.

**Comment by ldez** [comment]
Close in favor of  #5036 - Feel free to subscribe there for updates.
