### ISSUE TITLE
Unregistered domain used in documentation

### ISSUE THREAD

**Issue by MrRagnar** [containous/traefik#6470]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Read the documentation

### What did you expect to see?

Example domains or domains registered by the developers

### What did you see instead?

The current domain `my-awesome-app.org` is available for registration.
If a bad actor decides to register the domain and host malicious/offensive content it will reflect badly on this project.
Example domains should either be example.com / example.org or registered by the developers.

### Output of `traefik version`: (_What version of Traefik are you using?_)

N/A

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

N/A

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

N/A

**Comment by traefiker** [comment]
Closed by #6471.
