### ISSUE TITLE
Access logs don't follow documented format

### ISSUE THREAD

**Issue by martinb3** [containous/traefik#6481]
Hi there -- [according to documentation](https://docs.traefik.io/observability/access-logs/), the default Traefik access log format should be:

```
<remote_IP_address> - <client_user_name_if_available> [<timestamp>] "<request_method> <request_path> <request_protocol>" <origin_server_HTTP_status> <origin_server_content_size> "<request_referrer>" "<request_user_agent>" <number_of_requests_received_since_Traefik_started> "<Traefik_frontend_name>" "<Traefik_backend_URL>" <request_duration_in_ms>ms 
```

When I run:
```
$ docker run -traefik:v2.1.6 --ping --accesslog=true
```

And then separately trigger the `/ping` endpoint:
```
$ docker exec 012f6d76d399 wget localhost:8080/ping
```

I expect to see the backend and front URL fields rendered with quotes every time.

### What did you expect to see?

```
127.0.0.1 - - [13/Mar/2020:18:49:07 +0000] "GET /ping HTTP/1.1" 200 2 "-" "-" 1 "ping@internal" "-" 0ms
```

### What did you see instead?

```
127.0.0.1 - - [13/Mar/2020:18:49:07 +0000] "GET /ping HTTP/1.1" 200 2 "-" "-" 1 "ping@internal" - 0ms
```

Note the `"-"` vs. `-` in the last field before the `request_duration_in_ms` field.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
$ docker run traefik:v2.1.6 version
Version:      2.1.6
Codename:     cantal
Go version:   go1.13.8
Built:        2020-02-28T17:40:18Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

No additional configuration was performed.

**Comment by traefiker** [comment]
Closed by #6484.
