### ISSUE TITLE
Question: how to set ca for tls to services

### ISSUE THREAD

**Issue by mattharrigan** [containous/traefik#6488]
The documentation for getting tls for the entry point was excellent. It was very easy to setup and is working well. My question is how to setup tls for the services? I thought I could use cfssl to create a ca and then create certs for the various services. How do I  tell Traefik to use that ca? Is there an example? Is there a better way? Searching is difficult because there is so much on setting up tls for the entrypoint. Thank you.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
