### ISSUE TITLE
Docker dynamic settings for TLS not docummented

### ISSUE THREAD

**Issue by JonasJasas** [containous/traefik#6489]
### Do you want to request a *feature* or report a *bug*?
Both

### What did you do?
```yaml
labels:
  - "traefik.enable=true"
  - "traefik.docker.network=proxy"
  - "traefik.port=9292"
  - "traefik.tls.certificates.certFile=/etc/traefik/cert/${DOMAIN}.crt"
  - "traefik.tls.certificates.keyFile=/etc/traefik/cert/${DOMAIN}.key"
  - "traefik.tls.options.default.caFiles.clientAuthType=/etc/traefik/cert/cloudflare.crt"
  - "traefik.tls.options.default.clientAuth.clientAuthType=RequireAndVerifyClientCert"
  - "traefik.tls.options.default.minVersion=VersionTLS13"
  - "traefik.tls.options.default.sniStrict=true"

  - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_app.rule=Host(`${SUB_DOMAIN}${DOMAIN}`)"
  - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_app.tls=true"
  - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_app.tls.options=default"
```

### What did you expect to see?
Documentation how to set server and client certificates using Docker container labels.

### What did you see instead?
Couldn't find documentation and unable to set server and client certificates.

### Output of `traefik version`: (_What version of Traefik are you using?_)
2.1.6

**Comment by ldez** [comment]
Hello,

It's not documented because it's not availanle.

> Restriction
>
> In the above example, we've used the file provider to handle these definitions. It is the only available method to configure the certificates (as well as the options and the stores). However, in Kubernetes, the certificates can and must be provided by secrets.

https://docs.traefik.io/v2.1/https/tls/
