### ISSUE TITLE
Overriding toml configuration with environment variables

### ISSUE THREAD

**Issue by jmahowald** [containous/traefik#650]
volume mounts for the toml files can be difficult in a cluster.  Rancher or swarm for instance.  Yes, one can setup volume drivers, but that is a non-trivial setup.

Please consider using something like [viper](https://github.com/spf13/viper)  or [goconfig](https://github.com/dimfeld/goconfig) to allow you to easily allow environment variables to override.  For instance, in my case, I'd love to be able to have an env variable like

-e TRAEFIK_CONSULCATALOG_ENDPOINT=$CONSUL_ADDR

In the meantime, I have a dockerfile that extends yours adds in the toml, and allows changes via [dockerize](https://github.com/jwilder/dockerize)

**Comment by emilevauge** [comment]
Hi, you can override every parameters using arguments.

**Comment by jmahowald** [comment]
Great.   I was going to ask the convention, but I see them all in --help now.  
For anyone else who comes across this thread, the setting I'd want would be
      `  --consulcatalog.endpoint                           Consul server endpoint (default "127.0.0.1:8500") `
