### ISSUE TITLE
[2.2.0-rc2] kubernetes/ingress: bare host failed match on HTTP

### ISSUE THREAD

**Issue by kardianos** [containous/traefik#6501]
Bug

### What did you do?

Configure HTTP and HTTPS endpoints with middleware chain to redirect http to https.

### What did you expect to see?

Redirect HTTP to HTTPS in all situations, including no or bare "/" path.

### What did you see instead?

Without any path "" or maybe "/", the route "GET http://sub.domain" would fail to redirect to "https://sub.domain". It would just stop with a 404.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.2.0-rc2
Codename:     chevrotin
Go version:   go1.14
Built:        2020-03-11T17:42:16Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Static configuration through environment for endpoints and Kubernets Ingress and Kubernetes CRD setup. Kubernetes configuration for dynamic configuration for routes.

Kubernetes Ingress and KubernetesCRD, configured outside of the cluster.

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

Nothing applicable in DEBUG level log.

---

I'm using the newly (re-)introduced Kubernetes Ingress (not IngressRoute) for my main configuration for various reasons. I'm also using a Middleware chain that is redirecting http to https and non-www to www sub-domains (plus header addition, etc). Appears to work well.

When testing certain bare HTTP sub-domains, I found traefik would return a 404 *before* it even encountered the middleware. Testing was complicated due to HSTS header. But for example I found: `GET http://qa.mydomain.com` -> 404 (middleware not encountered) while `http://qa.mydomain/anything` -> 200 using middleware. I was able to use the jaeger integration to determine if the middle was was encountered at all.

I manually resolved this by creating Kubernetes IngressRoutes that bound directly on the HTTP endpoint only, used the same middleware, and only matched on the host, no Path or PathPrefix. This corrected the behavior to the desired behavior.

I suspect this has to do with how a Kubernetes Ingress object is internally represented + how HTTP (non-TLS) traffic paths are handled. Traefik creates to rules for Kubernetes Ingress objects: Host and PathPrefix. I suspect that internally the Request.URL.Path is either "/" or "" (empty) for this request either incoming or after processing. Then the created PathPrefix(`/`) rule doesn't match. This only appears to happen on HTTP, not HTTPS.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

Issue templates help us help you by providing all necessary information.

Please edit your issue and use the available templates:

- [Feature request](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/Feature_request.md)
- [Bug report](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/Bug_report.md)

And remember: each time someone ignores the template, a cute little bunny dies.
<details>
<summary>#SaveTheCuteBunny :heart: :rabbit: :heart:</summary>

![southpark - estrella kill rabbit](https://user-images.githubusercontent.com/5674651/27143914-3cea7896-5130-11e7-81f8-02d8ac2da7a7.gif)

![southpark - estrella kill rabbit2](https://user-images.githubusercontent.com/5674651/27143924-49104c72-5130-11e7-82ae-ccedbd5dfa1c.gif)

</details>

**Comment by rhzs** [comment]
@kardianos I think I encounter this as well, I tried to setup subdomain for my host at `covid.prixa.ai` (without trailing `/`) it won't redirect to HTTPS correctly. If you add, trailing `/`, then it will redirect correctly.

**Comment by rhzs** [comment]
This also happened on Traefik 2.1.6. 

Please help!

**Comment by ldez** [comment]
https://community.containo.us/t/http-entrypoint-404s-with-2-2-0-rc2/4894

**Comment by traefiker** [comment]
Closed by #6504.

**Comment by travisghansen** [comment]
@ldez I just got around to trying this out and the experience is still less than ideal :( now none of my ingresses have tls on them by default.

**Comment by ldez** [comment]
https://docs.traefik.io/v2.2/migration/v2/#kubernetes-ingress

**Comment by travisghansen** [comment]
@ldez ah, that helps. I'll do some more testing for a bit.

As an FYI the cli params did not work per the example in the doc:

- `--entrypoints.websecure.http.tls={}` = failure
- `--entrypoints.websecure.http.tls=true` = success

**Comment by ldez** [comment]
`--entrypoints.websecure.http.tls={}` is not a valid flag.

- https://docs.traefik.io/v2.2/routing/entrypoints/#tls
- https://docs.traefik.io/v2.2/reference/static-configuration/cli/

You have to click on the CLI tabs: https://docs.traefik.io/v2.2/migration/v2/#kubernetes-ingress

**Comment by travisghansen** [comment]
@ldez ah, thanks yet again! Overall this is looking much better (on rc4 atm)! I'll dig through several more scenarios and get even deeper into testing now that the basics are out of the way.
