### ISSUE TITLE
Possibility to add custom error pages

### ISSUE THREAD

**Issue by gregory90** [containous/traefik#652]
It could be nice if there was a way to add custom html error page when service is not available.

**Comment by DaMastah** [comment]
Please implement

**Comment by Yajo** [comment]
I'd say custom error page for each error code you want: 404, 503...

**Comment by Ranger-X** [comment]
+1

**Comment by marsmensch** [comment]
This would be great

**Comment by ldez** [comment]
You're welcome to submit a PR if we don't already created one.

Remember the gentle way to participate:
- add a "reaction" on the first message of the issue.
- add more useful and detailed information on the subject.
- solve the issue by making a PR.

**Comment by timoreimann** [comment]
A more concrete proposal exists with #1634.
