### ISSUE TITLE
Configuration discovery from other traefik instances

### ISSUE THREAD

**Issue by bontiv** [containous/traefik#6523]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I think it's a good idea to add a "configuration discovery" which discover other traefik instance and aggregate configurations from many clusters.

![image](https://user-images.githubusercontent.com/3851742/77074670-763d8700-69f1-11ea-8077-06bbe3821c2d.png)

In our company, we have physicals servers, one standalone Docker node, many physicals servers and virtuals machines. I've one traefik instance in front of all clusters and services and a traefik instance in each cluster. The instance in from of all others instance use a file provided configuration with rules to forward on others instances.

On the network map, Traefik2 and Traefik3 are services on the Traefik1 instances. But I need to write all routers on the Traefik1 instance.

Traefik already have APIs to get his configuration so writing a discovery provider to get all routers on "childrens" instances on which we need to forward connection may not be difficult.

**Comment by ldez** [comment]
Hello,

It's pretty complex to do that, there are a lot of constraints and technical issues behind this simple scheme.

I recommend to try TraefikEE: https://info.containo.us/contact-sales
