### ISSUE TITLE
level=error msg="Recovered from panic in http handler: net/http: abort Handler"

### ISSUE THREAD

**Issue by coolcat97** [containous/traefik#6535]
Hi! I'm running traefik in docker, 

traefik:1.7.2-alpine
on ubuntu linux

And getting this message filling my log.. any idea how to fix?

`level=error msg="Recovered from panic in http handler: net/http: abort Handler"`

Version:      v1.7.2
Codename:     maroilles
Go version:   go1.11.1
Built:        2018-10-04_01:44:36PM
OS/Arch:      linux/amd64

**Comment by ldez** [comment]
Hello,

could you update Traefik to current latest version: 1.7.22

Next could you follow the issue template, thanks.

**Comment by coolcat97** [comment]
How do I label that image on docker??
Right now it’s “traefik:1.7.2-alpine”

**Comment by ldez** [comment]
https://hub.docker.com/_/traefik?tab=tags

`traefik:1.7.22-alpine`

**Comment by coolcat97** [comment]
Seems to be working but now I have no logs?


-
Zack Cleaver

On March 20, 2020 at 7:21 PM, Ludovic Fernandez <notifications@github.com> wrote:






https://hub.docker.com/_/traefik?tab=tags


traefik:1.7.22-alpine
