### ISSUE TITLE
Fronting a domain with DNS A-record round-robin & ACME

### ISSUE THREAD

**Issue by niieani** [containous/traefik#654]
Automatic ACME works nicely if you use Traefik on a single server. How would you use it if you had multiple servers behind a single domain with Traefik in front? ACME domain ownership verification requires the response to be the same from all of the servers (or rather, from the single server that it resolves to). I currently do not see any way to do this. 
I presume sharing the `acme.json` file across the servers is enough to share the certs once they're generated, but not enough to actually pass the tri-monthly validation.
How could we remedy this?

**Comment by stongo** [comment]
@niieani see https://github.com/containous/traefik/issues/348

**Comment by niieani** [comment]
Thanks. Closing in favor of #348.
