### ISSUE TITLE
consul port is 0 and traefik.port is ignored

### ISSUE THREAD

**Issue by aep** [containous/traefik#6540]
version: docker  2.2.0-rc4

``` consul tags:

"traefik.enable=true",
"traefik.frontend.rule=Host:api.something",
"traefik.traefik.backend.healthcheck.port=7081",
"traefik.port=7081",
"traefik.loadbalancer.server.port=7081"

```

the host rule is picked up fine, but port is ignored, leaving backend listed as "http://172.22.1.2:0"

i.e. port zero

logs:
```
msg="Configuration received from provider consulcatalog: {\"http\":{\"routers\":{\"odb-liberator\":{\"service\":\"odb-liberator\",\"rule\":\"Host(`odb-liberator`)\"}},\"services\":{\"odb-liberator\":{\"loadBalancer\":{\"servers\":[{\"url\":\"http://172.22.1.2:0\"}],\"passHostHeader\":true}}}},\"tcp\":{},\"udp\":{}}"
```

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

Issue templates help us help you by providing all necessary information.

Please edit your issue and use the available templates:

- [Feature request](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/Feature_request.md)
- [Bug report](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/Bug_report.md)

And remember: each time someone ignores the template, a cute little bunny dies.
<details>
<summary>#SaveTheCuteBunny :heart: :rabbit: :heart:</summary>

![southpark - estrella kill rabbit](https://user-images.githubusercontent.com/5674651/27143914-3cea7896-5130-11e7-81f8-02d8ac2da7a7.gif)

![southpark - estrella kill rabbit2](https://user-images.githubusercontent.com/5674651/27143924-49104c72-5130-11e7-82ae-ccedbd5dfa1c.gif)

</details>

**Comment by ldez** [comment]
Hello,

You are mixing Traefik v1 and Traefik v2 labels.

Could you go the [community forum](https://community.containo.us/), thank you.
