### ISSUE TITLE
Routing GRPC through http router/service rules not working

### ISSUE THREAD

**Issue by snowzach** [containous/traefik#6542]
Bug Traefik version 2.1.8 built on 2020-03-19T15:08:56Z

I am trying to route grpc through Traefik with a bunch of other https rules. The back end service I am working with supports GRPC and HTTP on the same port unencrypted.

I have my tls entrypoint:

```
    [http.routers.myservice]
      entryPoints = ["https"]
      rule = "Host(`myservice.domain.org`) || PathPrefix(`/namespace.ClientRPC`)"
      service = "myservice"
      priority = 1000
      [http.routers.myservice.tls]
        certResolver = "letsencrypt"
      [[http.routers.myservice.tls.domains]]
        main = "*.domain.org"
        sans = ["domain.org"]

    [http.services.myservice.loadBalancer]
      [[http.services.myservice.loadBalancer.servers]]
        url = "h2c://insideserver.domain.org:8080"
```

When doing plain https, it works, the service answers, no problem there. When I attempt to use a GRPC client, it doesn't match the host nor PathPrefix name. It's like it doesn't hit any of the http rules. 

This is the log when I make a GRPC request:
```
traefik     | 192.168.3.12 - - [21/Mar/2020:15:31:20 +0000] "POST /namespace.ClientRPC/Search HTTP/2.0" - - "-" "grpc-go/1.28.0" 13 "-" "-" 0ms
```

I have played around with curl just to see if I could get it to trigger the rule... This works and the rule and it's routed to my grpc service.
```
curl -X POST --http2 'https://myservice.domain.org:443/namespace.ClientRPC/Search' -d "" -H 'Content-Type: application/grpc' -H 'Accept: application/grpc'
```

If I remove the `https` from the beginning of the URL, it's like traefik doesn't recognize it. I get the same behavior as the grpc client where it's just ignored and matches nothing. I am not totally sure if curl is calling it any differently.
```
curl -X POST --http2 'myservice.domain.org:443/namespace.ClientRPC/Search' -d "" -H 'Content-Type: application/grpc' -H 'Accept: application/grpc'
```

Any idea's? Why are grpc requests not handled/matched like http requests? (Aren't they just http2 requests?)

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by snowzach** [comment]
I have tried every combination of rules I can possibly think of including `HostRegexp(`{any:.*}`)` the request does not appear to be handled as an HTTP request (and thus not passed through HTTP routers as near as I can tell) when called with a go GRPC client.

@dtomcej would you be willing to open this one up again? I posted in the forum but no one has looked at it.

**Comment by dtomcej** [comment]
@snowzach can you please provide the link to your post? I can't find it. The forum is the best place to discuss configuration before we return here if there is an actual bug.

**Comment by snowzach** [comment]
@dtomcej sure: https://community.containo.us/t/routing-grpc-through-http-router-service-rules-not-working/5048
