### ISSUE TITLE
Add TLS outside of Kubernetes (KubernetesIngress)

### ISSUE THREAD

**Issue by FLavalliere** [containous/traefik#6544]
Feature

We use Traeffik with pre-made self-signed certs outside of Kubernetes.

Trying to use an HTTPS Endpoint, traeffik doesnt detect / find the secrets.
We would like a way to specify a default Certs so that the routing can be TLS detected?

ie: Using an HTTP endpoint it works, but using an HTTPS endpoint doesnt works since TLS isnt defined? It simply returns 404 for some reasons.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
