### ISSUE TITLE
How to reload static configuration

### ISSUE THREAD

**Issue by zhengqisong** [containous/traefik#6546]
### Do you want to request a *feature* or report a *bug*?
Feature

### What did you expect to see?
Hot loading static config? such as entrHypoints, metrics, accesslog, log.  for example: nginx -s reload

Start up traefik use ./traefik -f traefik.toml

How to hot loading static config? such as entrypoints, metrics, accesslog, log.
When the static config was changed , I expect to hot loading it, make sure my service is uninterrupted.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by zhengqisong** [comment]
@reopen

**Comment by zhengqisong** [comment]
re-open

**Comment by ldez** [comment]
duplicate of #1188
