### ISSUE TITLE
What status codes would Traefik log for DownstreamStatusCode when circuit-breaker is open / throttling due to max connection limit?

### ISSUE THREAD

**Issue by johnib** [containous/traefik#6555]
Hello,

I am unable to distinguish the Traefik logs of the requests that Traefik throttle, either due to max connection limit was reached, or due to circuit break being open.

Can you please help?

**Traefik v1.7**

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
