### ISSUE TITLE
[Docs] Helm 3 Install steps

### ISSUE THREAD

**Issue by jdbohrman** [containous/traefik#6562]
It would help if the docs reflected info on the current state of Helm. I can submit a PR if you all would be open to it?

**Comment by SantoDE** [comment]
Hey @jdbohrman,

thanks for your interest. I don't get exactly what you mean? Our Helm3 chart (for v2.X) is available here: https://github.com/containous/traefik-helm-chart

Is it that what you mean?

**Comment by ldez** [comment]
Take a look to https://docs.traefik.io/v2.2/getting-started/install-traefik/#use-the-helm-chart

**Comment by jdbohrman** [comment]
> Take a look to https://docs.traefik.io/v2.2/getting-started/install-traefik/#use-the-helm-chart

Yeah thanks! I was looking at an older version of the docs lol.
