### ISSUE TITLE
Can not keep X-Forwarded-For value for app

### ISSUE THREAD

**Issue by zhengqisong** [containous/traefik#6563]
### Do you want to request a *feature* or report a *bug*?
Bug

### What did you do?
version: 2.1.6
providers: kubernetes-crd
flow: client(10.1.1.2) -> elb(10.2.2.2) -> nginx(10.3.3.3) -> traefik(10.4.4.3) -> app

traefik host tcpdump:
X-Forwarded-For: 10.1.1.2,10.2.2.2,10.3.3.3

app host tcpdump
X-Forwarded-For: 10.3.3.3
X-Forwarded-Host: your.domain.com
X-Forwarded-Port: 80
X-Forwarded-Proto: http
X-Forwarded-Server: hostname
X-Real-Ip: 10.3.3.3
X-Ruxit-Forwarded-For: 10.1.1.2, 10.1.1.2

traefik.toml
```
[entrypoints]
  [entrypoints.web]
    Address = ":8000"

    [entryPoints.web.forwardedHeaders]
      insecure = true

  [entrypoints.websecure]
    Address = ":4443"
    [entryPoints.websecure.forwardedHeaders]
      insecure = true
```
### What did you expect to see?
X-Forwarded-For: 10.1.1.2,10.2.2.2,10.3.3.3,10.4.4.3

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by zhengqisong** [comment]
@re-open
