### ISSUE TITLE
About kubenetes standard document.

### ISSUE THREAD

**Issue by gouki777** [containous/traefik#6575]
### Do you want to request a *feature* or report a *bug*?
feature

### What did you do?
The k3s-traefik2.0 document has been published on the official website for more than half a year.
I hope Official release of standard kubenetes related documents

### What did you expect to see?

I would like to see traefik2.0 deployment documentation on kubenetes, Rather than rancher/k3s
I don't know.what is k3s?
I'm not sure if this is the same as k8s

I hope Official release of standard kubenetes related documents

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
