### ISSUE TITLE
how to express exact match location = /

### ISSUE THREAD

**Issue by shawndodo** [containous/traefik#6580]
sorry, I'm new here. I have read the table of all the available matchers. But I still want to know if  `Path(`/path`, `/articles/{category}/{id:[0-9]+}`, ...)` in traefik can express location = /.
In nginx I can set like
```
location = / {
    proxy_pass http://nginx-a
}
location ^~ /api/ {
    proxy_pass http://nginx-b
}
location / {
   proxy_pass http://nginx-b
}
```
Anyway, I just want to know that how traefik do this. Thank you.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
