### ISSUE TITLE
please add a step to step build tutorial about non-containerized traefik(v2.0)

### ISSUE THREAD

**Issue by wooddeep** [containous/traefik#6585]
Hi, I need a  a step to step build tutorial about non-containerized traefik. because I want modify some source code and compile the project, finally run the traefik in non-containerized mode, . 

I use "make run-dev" command to make the target:
`
run-dev:
	GO111MODULE=off go get -u github.com/containous/go-bindata/...	
	rm -rf static/ autogen/
	go generate
	#GO111MODULE=on go build ./cmd/traefik
	go build ./cmd/traefik
	./traefik
`
And then, I get the traefik's bin file in the root directory,  run the bin file with configure file (enable the dashboard). but when I access the http://127.0.0.1:8080/dashborad/, I get the response: 404 page not found!

thanks! with best wish!

**Comment by ldez** [comment]
Hello,

Take a look to https://docs.traefik.io/v2.2/contributing/building-testing/
