### ISSUE TITLE
how to set traefik(v2.0)'s api port?

### ISSUE THREAD

**Issue by wooddeep** [containous/traefik#6589]
when I set the api port at the entrypoint:
`
[entryPoints]
  [entryPoints.web]
    address = ":8080"

  [entryPoints.websecure]
    address = ":443"

  [entryPoints.foo]
   address=":9090"

[api]
  entrypoint="foo"
  dashboard = true
  insecure = true
` 
I got the error message:
2020/03/27 12:32:53 command traefik error: field not found, node: entrypoint

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
