### ISSUE TITLE
invalid service name with slash from COnsulCatalog

### ISSUE THREAD

**Issue by kinnalru** [containous/traefik#6592]
Feature

### What did you expect to see?

When providin configuration to Traefik 2.* by ConsulCatalog we have service name in catalog like  "dev/planner"

Traefik gets this configuration and works well with one issue: dashboard ui broken when looking into service.

404 error on page `/dashboard/#/http/services/dev/planner@consulcatalog`
But all other things works well

So I think it will be very useful to override default service name(taken from consul). Ex: with label `traefik.service.name=dev-plannel` or `traefik.consulcatalog.service.name=dev-plannel`

**Comment by ldez** [comment]
Hello,

to define the service name you have to define at least one "service" annotations:

https://docs.traefik.io/v2.2/routing/providers/consul-catalog/#services

**Comment by kinnalru** [comment]
thx. It works
