### ISSUE TITLE
Dashboard does not URL encode router or service names

### ISSUE THREAD

**Issue by wasabii** [containous/traefik#6600]
I have a router named `fabric:/FooBar/Blah@file`. It has invalid URL characters in it. Slashes, etc. Traefik is perfectly happy dealing with this router. It is in a healthy state. Works great.

However, the dashboard UI links to an incorrect URL: `http://localhost:19188/dashboard/#/http/routers/fabric:/FooBar/Blah@file`. The slashes and colon messes it up. If I manually encode the URL, the dashboard page comes back correctly. However, it fails then to call some APIs for the same reason.

Service and Router names should be URL encoded by the dashboard frontend before issuing requests or generating links.

This occurs in version 2.2.0.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

Issue templates help us help you by providing all necessary information.

Please edit your issue and use the available templates:

- [Feature request](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/Feature_request.md)
- [Bug report](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/Bug_report.md)

And remember: each time someone ignores the template, a cute little bunny dies.
<details>
<summary>#SaveTheCuteBunny :heart: :rabbit: :heart:</summary>

![southpark - estrella kill rabbit](https://user-images.githubusercontent.com/5674651/27143914-3cea7896-5130-11e7-81f8-02d8ac2da7a7.gif)

![southpark - estrella kill rabbit2](https://user-images.githubusercontent.com/5674651/27143924-49104c72-5130-11e7-82ae-ccedbd5dfa1c.gif)

</details>

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Community Forum](https://community.containo.us/).
