### ISSUE TITLE
go install throws invalid version: unknown revision 000000000000 on github.com/abbot/go-http-auth

### ISSUE THREAD

**Issue by krjw** [containous/traefik#6602]
Bug?

### What did you do?

- I ran `go install github.com/containous/traefik/v2` and got the error `github.com/abbot/go-http-auth@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000`

### What did you expect to see?

The package being installed.

### What did you see instead?

An Error.

### Output of `traefik version`: (_What version of Traefik are you using?_)

I am using 2.1.8 installed via helm.

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

I am running a kubernetes single node cluster with kubeadm. I used https://github.com/kubernetes/client-go to dynamically add new deployments and ingresses. Now I want to switch to the custom IngressRoute resource but I am not able to get the types from the package because of this error.

Does this have something to do with replacing the modules in `go_mod` with a local package? I am new to the go language.

**Comment by ldez** [comment]
Hello,

It's not a bug with Traefik.

We recommend to use:
- our [Binaries](https://github.com/containous/traefik/releases/tag/v2.2.0)
- our [Official Docker image](https://hub.docker.com/_/traefik?tab=tags)
- our [build method](https://docs.traefik.io/v2.2/contributing/building-testing/#method-2-using-go)
