### ISSUE TITLE
configuring consulCatalog and consul kv at the same time => consul kv does not come up

### ISSUE THREAD

**Issue by muradm** [containous/traefik#661]
Configuring consulCatalog and consul kv at the same time => consul kv does not come up. After traefik started, any update to keys under /traefik in consul activates consul backend.
Reproduce:
1. configure consulCatalog and consul at the same time
2. start traefik
3. observe that:
   - in web interface consul backend is missing
   - frontends and backends configured in consul backend are not working
4. open consul web app, and update any key under /traefik
5. observe that:
   - in web interface consul backend is appeared
   - frontends and backends configured in consul backend are now working

**Comment by mmatur** [comment]
@muradm Could you please test with latest version [v1.4.2](https://github.com/containous/traefik/releases/tag/v1.4.2) ?

**Comment by traefiker** [comment]
I'll close the issue due to inactivity but feel free to re-open if needed.
