### ISSUE TITLE
Dashboard doesn't update routers count on table pages

### ISSUE THREAD

**Issue by lukashass** [containous/traefik#6610]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Open the Dashboard at `..../dashboard/#/http/routers`. Now add a new router.

### What did you expect to see?

The number of routers in the toolbar at the top should update to the new number of routers.
![traefik_screenshot](https://user-images.githubusercontent.com/32853499/78081080-f380d880-73af-11ea-9dcc-e44c057b77bf.png)

### What did you see instead?

The number of routers doesn't change. Only the entries of the table are updated automatically to show the new router.

This applies to services and middlewares too. I only tested this with HTTP but it probably applies to the TCP and UDP pages as well.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.2.0
Codename:     chevrotin
Go version:   go1.14.1
Built:        2020-03-25T17:32:57Z
OS/Arch:      linux/amd64
```

**Comment by traefiker** [comment]
Closed by #6611.
