### ISSUE TITLE
Unable to parse the InfluxDB address

### ISSUE THREAD

**Issue by debu99** [containous/traefik#6612]
image: traefik:2.1.8

with parameter --metrics.influxdb.address=10.110.1.10:8086
```time="2020-04-01T00:14:10Z" level=error msg="Unable to parse the InfluxDB address parse 10.110.1.10:8086: first path segment in URL cannot contain colon: falling back on UDP." metricsProviderName=influxdb```

with parameter --metrics.influxdb.address=//10.110.1.10:8086
```time="2020-04-01T00:25:39Z" level=warning msg="InfluxDB address //10.110.1.10:8086 should specify a scheme (http or https): falling back on HTTP." metricsProviderName=influxdb
time="2020-04-01T00:25:39Z" level=debug msg="Configured InfluxDB metrics: pushing to http:////10.110.1.10:8086 once every 10s" metricsProviderName=influxdb
time="2020-04-01T00:25:49Z" level=error msg="Error while writing to InfluxDB: Post http:///10.110.1.10:8086/write?consistency=&db=traefik&precision=ns&rp=: http: no Host in request URL" metricsProviderName=influxdb
```

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by debu99** [comment]
why close?

**Comment by ldez** [comment]
Hello,

1. you don't follow the issue template, a lot of information are missing
2. a valid address for an InfluxDB HTTP endpoint must be a valid URL: `http//10.110.1.10:8086`
3. the `10.110.1.10:8086` is only for the InfluxDB UDP endpoint
