### ISSUE TITLE
Traefik 2.2 doesn't watch consul-catalog's service health

### ISSUE THREAD

**Issue by tle5** [containous/traefik#6613]
I am new to traefik, I tried to add consul-catalog provider into traefik with following settings:
```
[providers.consulCatalog]
  [providers.consulCatalog.endpoint]
    address = "http://192.168.10.211:8500"
    scheme = "http"
    datacenter = "dc1"
    token = "secret-token"
```
I can see my services from consul on dashboard.
Then I execute command to deregister one of my services from consul, and check the traefik dashboard, the de-registered service still remained in traefik in few seconds. 
Does traefik watch health from consul with blocking queries?

In my testing:
- Consul: 1.7.2
- Traefik: v2.2.0

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by tle5** [comment]
I think my configuration is OK, because everything works, except traefik doesn't update service's health status immediately when I call de-register service from Consul.
