### ISSUE TITLE
V2.2: dnsChallenge doesn't work

### ISSUE THREAD

**Issue by sgofferj** [containous/traefik#6616]
### What did you do?
I configured a separate cert resolver for DNS challenges.

### What did you expect to see?
Traefik using DNS challenge

### What did you see instead?
Traefik complaining:
```
level=error msg="Unable to obtain ACME certificate for domains \"www.saakeskus.fi\" : cannot get ACME client ACME challenge not specified, please select TLS or HTTP or DNS Challenge" providerName=letsencrypt-dns.acme
```

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
Version:      2.2.0
Codename:     chevrotin
Go version:   go1.14.1
Built:        2020-03-25T17:32:57Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```
...
[certificatesResolvers.letsencrypt.acme]
  email = "webmaster@gofferje.net"
  storage = "/etc/traefik/acme/acme.json"

  [certificatesResolvers.letsencrypt.acme.tlsChallenge]

[certificatesResolvers.letsencrypt-dns.acme]
  email = "webmaster@gofferje.net"
  storage = "/etc/traefik/acme/acme.json"
  caserver = "https://acme-staging-v02.api.letsencrypt.org/directory"

  [certificateResolvers.letsencrypt-dns.acme.dnsChallenge]
    provider = "cloudflare"
    delayBeforeCheck = 0
...
```

The service container explicitly references letsencrypt-dns.

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
time="2020-04-01T09:54:48Z" level=debug msg="Looking for provided certificate(s) to validate [\"www.saakeskus.fi\"]..." providerName=letsencrypt-dns.acme
time="2020-04-01T09:54:48Z" level=debug msg="Domains [\"www.saakeskus.fi\"] need ACME certificates generation for domains \"www.saakeskus.fi\"." providerName=letsencrypt-dns.acme
time="2020-04-01T09:54:48Z" level=debug msg="Loading ACME certificates [www.saakeskus.fi]..." providerName=letsencrypt-dns.acme
time="2020-04-01T09:54:48Z" level=debug msg="Building ACME client..." providerName=letsencrypt-dns.acme
time="2020-04-01T09:54:48Z" level=debug msg="https://acme-staging-v02.api.letsencrypt.org/directory" providerName=letsencrypt-dns.acme
time="2020-04-01T09:54:49Z" level=error msg="Unable to obtain ACME certificate for domains \"www.saakeskus.fi\" : cannot get ACME client ACME challenge not specified, please select TLS or HTTP or DNS Challenge" providerName=letsencrypt-dns.acme
```

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
