### ISSUE TITLE
Documentation error?

### ISSUE THREAD

**Issue by fabthegreat** [containous/traefik#6617]
On this page:
https://docs.traefik.io/v2.0/https/acme/
when I write
```
- traefik.http.routers.blog.rule=(Host(`company.com`) && Path(`/blog`)) || Host(`blog.company.org`)
```
Traefik raises 
```
error:level=error msg="Error parsing domains in provider ACME: 1:30: illegal character U+00A0"
```
When I remove spaces between ||, it works like a charm...

**Comment by ldez** [comment]
Hello,

there is no documentation: [U+00A0](https://www.compart.com/fr/unicode/U+00A0) is a No-Break Space, so I guess you are using a Mac. This character is not valid you must use a space [U+0020](https://www.compart.com/fr/unicode/U+0020)

**Comment by fabthegreat** [comment]
Hello, no I am under Debian Linux and using Traefik 2.0.
I don't know why but once those spaces were removed, certificates were well reached.
