### ISSUE TITLE
myresolver not defined in Traefik & CRD & Let's Encrypt

### ISSUE THREAD

**Issue by gbrault** [containous/traefik#6620]
https://github.com/containous/traefik/blob/v2.2/docs/content/user-guides/crd-acme/index.md

Install of CRD and creation of myresolver seems missing: am-I right?

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by ldez** [comment]
Take a look to:

- https://docs.traefik.io/v2.2/user-guides/crd-acme/#deployments
- https://docs.traefik.io/v2.2/user-guides/crd-acme/#traefik-routers
