### ISSUE TITLE
Ingress resource deleted, does not remove Let's Encrypt cert/private data from consul

### ISSUE THREAD

**Issue by nodesocket** [containous/traefik#6622]
Running Traefik version 1.82.0 with Consul KV. I deleted the Kubernetes ingress resource, but using the tool [traefik-certs-dumper](https://github.com/ldez/traefik-certs-dumper) I still see the domain listed in `cert` and `private`. Shouldn't it delete the Let's Encrypt domain cert and private from Consul when the Kubernetes ingress resource is deleted?

**Comment by mmatur** [comment]
@nodesocket Thanks for your question.

Unfortunately I think this is something that is not possible with Traefik. 
Traefik v1 use Consul K/V to store LE certificates so if for any reason ingresses are created, deleted , created it will require Traefik to regenerate certificates through LE and it can cause to reach the limit.

So I will close this issue because your question is answered.

Thanks

**Comment by nodesocket** [comment]
@mmatur so there is no way to delete provisioned let's encrypt certificates in Consul after they have been created by Traefik? In this case, the certificate is invalid, and I need to delete it. That seems really strange. What if you dynamically creating and deleting ingresses? All the certificates just stay in Consul?

**Comment by dtomcej** [comment]
@nodesocket, it's not that Traefik can't delete the certificates, the issue stems from how Traefik v1 requests certificates. Traefik does not track whether the certificate is currently being used or not.

Therefore, Traefik does not know "when" a certificate should be deleted.

Removing certificates can be done manually, and yes, if no certificates are deleted, they will persist in the KV store.

**Comment by nodesocket** [comment]
@dtomcej thanks for the reply. When you say they can be deleted manually, can I just delete one? How is that accomplished? When I view in the Consul web interface the value appears to be encrypted or binary.
