### ISSUE TITLE
Error: Protocol error, got "H" as reply type byte

### ISSUE THREAD

**Issue by Future2100** [containous/traefik#6623]
config as below:
```
[log]
  level = "debug"
  format = "json"

[accessLog]
  filePath = "./traefik.log"
  format = "json"

[entryPoints]
  [entryPoints.aq_proxy]
    address = ":6388/tcp"
[tcp]
  [tcp.routers]
      [tcp.routers.Router-1]
        rule = "HostSNI(`*`)"
        service = "my-service"
      [tcp.routers.Router-1.tls]
  [tcp.services]
    [tcp.services.my-service.loadBalancer]
       [[tcp.services.my-service.loadBalancer.servers]]
         address = "127.0.0.1:6379"
```
get title error, I  have gone through the doc but I can't find the reason out.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
