### ISSUE TITLE
Docker exposedbydefault = false didn't work

### ISSUE THREAD

**Issue by mcoms** [containous/traefik#663]
With the following `traefik.toml` and Traefik v1.0.2 (official docker image), all my docker containers are exposed, despite setting `exposedbydefault = false`.

```
defaultEntryPoints = ["https"]

[acme]
email = "domains@example.com"
storageFile = "/etc/traefik/acme.json"
entryPoint = "https"
onDemand = false
OnHostRule = true

[entryPoints]
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[retry]

[web]
address = ":8080"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "docker.localhost"
watch = true
exposedbydefault = false
```

**Comment by gaetancollaud** [comment]
I have the same issue, I had to put the label `traefik.enable=false` to hide some containers.

**Comment by thomasf** [comment]
I think that feature hasnt made it into any release version yet

**Comment by mcoms** [comment]
Ah yes, you're quite right. Sorry!

**Comment by bernhardberger** [comment]
Somehow this still doesn't work with either 1.5 or 1.6.

Pretty annoying if you have tons of projects up.. :/

```
[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "mydomain.tld"
watch = true
exposedbydefault = false
```

still creates a frontend and backend for any container started...

**Comment by ldez** [comment]
@bernhardberger come on Slack to explain your issue.

**Comment by bernhardberger** [comment]
seems like something in my docker command killed parts of the .toml file.

all good can be closed..

Ludovic Fernandez <notifications@github.com> schrieb am Fr., 4. Mai 2018,
17:34:

**Comment by Pyton** [comment]
@bernhardberger can you explain what was the issue? I have the same problem. 
My toml:
```
[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
exposedbydefault = false
```
but in debug logs there is `"ExposedByDefault":true,` and i have to add `traefik.enable: false` labels

**Comment by bernhardberger** [comment]
I had to specify the path to the configFile in the docker-compose "command".

I also had to omit any other parameters (the only param being the
configFile, somehow any param cancels out the use of this section in the
config file..

Lukas <notifications@github.com> schrieb am Di., 8. Mai 2018, 19:57:

**Comment by ldez** [comment]
https://docs.traefik.io/v1.6/basics/#static-trfik-configuration

> It means that arguments override configuration file, and key-value store overrides arguments.

> the provider-enabling argument parameters (e.g., `--docker`) set all default values for the specific provider.
> It must not be used if a configuration source with less precedence wants to set a non-default provider value.

To summary, don't mix CLI arguments and TOML on the same configuration section (ex: docker)

**Comment by Pyton** [comment]
Yeeeyyy...  I had in `docker-compose.yml` 
`command: --api --docker` 
and after remove that it starts working !!
