### ISSUE TITLE
Derive service name from router name when multiple routers are defined

### ISSUE THREAD

**Issue by SuperSandro2000** [containous/traefik#6638]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

This is a follow up feature request to #4807 and #5435.

If I take the example from https://github.com/containous/traefik/issues/4807#issuecomment-486025479 and remove the service lines:

```
labels:
- "traefik.http.routers.router1.rule=host(`service1.docker.localhost`)"
- "traefik.http.services.service1.loadbalancer.server.port=8381"
- "traefik.http.routers.router2.rule=host(`service2.docker.localhost`)"
- "traefik.http.services.service2.loadbalancer.server.port=8380"
```

I think it would be a reasonable default to name the service of ``router1`` just ``router1`` and the service of ``router2`` ``router2`` instead of erroring and ignoring both.

**Comment by ldez** [comment]
Hello,

We don't plan to do this, because there are a lot of side effects, and that doesn't fit with the Traefik design.

**Comment by SuperSandro2000** [comment]
It worked like this in Traefik 1 where you wouldn't need to be super verbose with names and could just add namesless labels to docker containers.

**Comment by SantoDE** [comment]
Hello @SuperSandro2000,

we're not arguing with that it was easier for some users in v1. However, the new internal architecture of Traefik (Routers, Middlewares, Services) made it required that we have some more explicit labels.

That in combination with the fact that labels are (internally) a map, we have no guaranteed order of the labels and thus, we can't easily derive it.

However, we're still committed to enhancing the User Experience and thus, I will think about if I can find another solution.
