### ISSUE TITLE
DDR : display current weight instead of initial weigth

### ISSUE THREAD

**Issue by gaetancollaud** [containous/traefik#664]
I'm trying to use the DDR load balancer. So far it works great ! But the weight are not updated in the API.

In the traefik log, I can see lines like:

```
 increasing weight of http://192.168.3.153:8080 from 1 to 4
```

But in the API, the weight does not change. It still the initial weight:

``` json
{
  "servers": {
    "pcgaetan": {
      "url": "http://192.168.3.153:8080",
      "weight": 0
    },
    "realintegration": {
      "url": "http://192.168.3.203:8080",
      "weight": 0
    }
  },
  "loadBalancer": {
    "method": "drr"
  }
}
```

Would it be possible to display the _current_ weight (or I don't know how to call it) in the API ?

**Comment by dtomcej** [comment]
Since the new API provider has been released as of 1.5 (https://docs.traefik.io/configuration/api/), the current weight is visible in the dashboard, as well as via the API.

For this reason, I will be closing this issue.

If you have any new issues, feel free to open a new issue.

Thanks!
