### ISSUE TITLE
traefik_v2.2.0 loadBalancer not work 

### ISSUE THREAD

**Issue by sain801028** [containous/traefik#6641]
I am not using docker

My app health check
No message received

![螢幕快照_2020-04-06_19-55-25](https://user-images.githubusercontent.com/17377422/78555948-a635b880-7840-11ea-844b-8e2d4a250eaf.png)

![螢幕快照_2020-04-06_19-58-41](https://user-images.githubusercontent.com/17377422/78556225-2bb96880-7841-11ea-8d67-c6c343f81743.png)

![螢幕快照_2020-04-06_19-59-01](https://user-images.githubusercontent.com/17377422/78556228-2d832c00-7841-11ea-8a39-1f5d57d81f87.png)

![螢幕快照_2020-04-06_19-59-24](https://user-images.githubusercontent.com/17377422/78556233-2f4cef80-7841-11ea-9cd8-e977bdf36ed2.png)

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
