### ISSUE TITLE
ACME storage in Consul KV

### ISSUE THREAD

**Issue by Legogris** [containous/traefik#6644]
Storing ACME/LE certs in Consul used to be supported, but is no longer possible in 2.2:

https://community.containo.us/t/traefik-2-2-features/5078/2
https://community.containo.us/t/traefik-2-2-with-consul-storeconfig-command-gone/5153/4

This effectively makes ACME certs not usable in an HA configuration/with stateless containers - every restart of Traefik will yield reprovisioning of certificates,

This request if for considering bringing back that functionality in Traefik v2.

**Comment by SantoDE** [comment]
Hello @Legogris,

thanks for your interest in the project.

As already mentioned (e.g. here #5792 ), this is intended as the behavior was very error prone in V1 and we decided to drop that support.

However, on certain orchestrators (e.g. Kubernetes) you can still achieve HA in combination with external tools such as Cert Manager.

Therefore, I close that issue.
