### ISSUE TITLE
A complete example of TCP sni on the k8s platform traefik2.x?

### ISSUE THREAD

**Issue by kuaiwenwu** [containous/traefik#6649]
Is it possible to produce an official tcp sni example of traefik2.x on the k8s platform? I cannot configure it to reuse an entrypoint for different domain names, because it is impossible to go to traefik deployment to create an entrypoint each time a new tcp service is released Restart, this is terrible.？

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
