### ISSUE TITLE
Docker dynamic config saved in consul if I provide the consul provider

### ISSUE THREAD

**Issue by dioptre** [containous/traefik#6652]
### Do you want to request a *feature* or report a *bug*?
I think this is both a bug and a feature.

Feature

### What did you expect to see?
If I add both the docker provider and the consul provider, the docker config should be saved to consul. This obviates the need to pass through the docker socket from the manager nodes to the traefik worker nodes (YUCKKKK). I should be able to run the traefik equivalent of a "leader" running on any manager node, which updates the consul config. The "child" traefik nodes should just be able to consume the read-only consul data. 

Even suggesting that I should run a reverse haproxy and expose the manager socket to the networks/machines as is the current solution to this is a bit ridiculous.

**Comment by ldez** [comment]
Hello,

we don't think that is a right way to achieve HA.

So we recommend to take a look to TraefikEE https://containo.us/traefikee/
