### ISSUE TITLE
Traefik NOT detected the new container and updated its own configuration.

### ISSUE THREAD

**Issue by pramitbiswas** [containous/traefik#6654]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
Follow this link to start playing: https://docs.traefik.io/getting-started/quick-start/

	version: '3'

	services:
	  reverse-proxy:
		# The official v2 Traefik docker image
		image: traefik:v2.2
		# Enables the web UI and tells Traefik to listen to docker
		command: --api.insecure=true --providers.docker
		ports:
		  # The HTTP port
		  - "80:80"
		  # The Web UI (enabled by --api.insecure=true)
		  - "8080:8080"
		volumes:
		  # So that Traefik can listen to the Docker events
		  - /var/run/docker.sock:/var/run/docker.sock
 
	  whoami:
		# A container that exposes an API to show its IP address
		image: containous/whoami
		labels:
		  - "traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)"

$ `docker-compose up -d reverse-proxy`
$ `docker-compose up -d whoami`
$ `curl -H Host:whoami.docker.localhost http://127.0.0.1`

### What did you expect to see?

$ `docker-compose up -d reverse-proxy`
able to see raw data http://localhost:8080/api/rawdata
able to see dashboard http://localhost:8080/

$ `docker-compose up -d whoami`
Traefik has automatically detected the new container and updated its own configuration.

$ `curl -H Host:whoami.docker.localhost http://127.0.0.1`
	Hostname: a656c8ddca6c
	IP: 172.27.0.3
	#...

### What did you see instead?

$ `docker-compose up -d reverse-proxy` (without `whoami` in ymlfile)
able to see raw data http://localhost:8080/api/rawdata
able to see dashboard http://localhost:8080/

$ `docker-compose up -d whoami`
Traefik NOT detected the new container and updated its own configuration.

$ `curl -H Host:whoami.docker.localhost http://127.0.0.1`
$ `curl: (7) Failed to connect to localhost port 80: Connection refused`

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.2.0
Codename:     chevrotin
Go version:   go1.14.1
Built:        2020-03-25T17:32:57Z
OS/Arch:      linux/amd64

```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

None

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

NA

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
