### ISSUE TITLE
Sporadic 502 responses after introducing traefik in EKS

### ISSUE THREAD

**Issue by ntrp** [containous/traefik#6656]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
Deployed traefik in EKS, using CRD and listening in two namespaces. The application it points to is a spring boot application with netty. Before Traefik we had the loadbalancer connect directly to the application with no 502s.
### What did you expect to see?
No errors in the requests
### What did you see instead?
Traefik sporadically returns "502 Bad Gateway" for about 1% of the requests (over 35k)
### Output of `traefik version`: (_What version of Traefik are you using?_)
```
Version:      2.1.3                 
Codename:     cantal                
Go version:   go1.13.6              
Built:        2020-01-21T17:30:29Z  
OS/Arch:      linux/amd64
```
### What is your environment & configuration (arguments, toml, provider, platform, ...)?
Platform: EKS 1.15
Provider: KubernetesCRD
args
```
--global.checknewversion=true
--global.sendanonymoususage=false
--entryPoints.traefik.address=:9000
--entryPoints.web.address=:8000
--entryPoints.websecure.address=:8443
--api.dashboard=true
--api.insecure=true
--ping=true
--providers.kubernetescrd
--log.level=TRACE
--accesslog=true
--accesslog.format=json
--accesslog.fields.defaultmode=keep
--accesslog.fields.headers.defaultmode=drop
--accesslog.fields.headers.names.X-Trace-Id=keep
--accesslog.fields.headers.names.X-Environment=keep
--providers.kubernetescrd.namespaces=custcomm,custcomm-dev
--serversTransport.maxIdleConnsPerHost=-1
--serversTransport.forwardingTimeouts.idleConnTimeout=1s
```
### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)
```
time="2020-04-09T14:03:40Z" level=debug msg="'502 Bad Gateway' caused by: readfrom tcp 10.10.11.221:53528->10.10.10.60:8080: read tcp 10.10.11.221:8000->10.10.10.191:16428: read: connection reset by peer"
```
Wireshark dump, there is a reset packet at the same time: 
[dump_pp.zip](https://github.com/containous/traefik/files/4456636/dump_pp.zip)

The chain of calls should be: NLB -> traefik -> application with the kube-proxy in between where appropriate.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by ntrp** [comment]
I guess his AI is not that advanced :P, can any human have a look on this please?
