### ISSUE TITLE
HostSNI-matcher for HTTPS router

### ISSUE THREAD

**Issue by elygre** [containous/traefik#6657]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I would like to be able to use a HostSNI-matcher for a regular HTTP or HTTPS rule. Today (docker 2.2.0) this fails with "Error while parsing rule: Unsupported function: HostSNI".

A use case is like this:

* On an internal server, there is a an app Sonarqube running in a docker container. Traefik is running on this server, mapping the name "sonar.internal.example.com" (including ACME for TLS). A request for "sonar.internal.example.com" gets routed correctly
* The decision is made to expose this app externally. On an external Apache httpd server, the host "sonar.external.example.com" is proxied to "https://sonar.internal.example.com"

As far as I can tell, Traefik will receive both the SNI information ("sonar.internal.example.com") and the HTTP Host header ("sonar.external.example.com"), but it will route based on the HTTP Host header -- which is a name it knows nothing about.

If we could have mapped by SNI, then traefik would route based on the name "sonar.internal.example.org", while Sonarqube would use the HTTP header to deduce that it's name was now "sonar.external.example.org", and render the proper links.

**Comment by ldez** [comment]
Hello,

the equivalent of the `HostSNI` for HTTP is `Host` 

https://docs.traefik.io/v2.2/routing/routers/#rule

**Comment by elygre** [comment]
This is not correct. For the case of HTTPS, Host() and HostSNI() are two different things.

I have set up traefik with two different whoami-servers, one matching `Host(whoami)` and the other matching `Host(ping)`. The script below first uses curl to demonstrate that the routing works, and then uses openssl to send a request where the SNI servername is `ping` but the HTTP Hostname is `whoami`.

When run, the output demonstrates that the Host() matcher does not use the SNI servername, but instead the HTTP-header "Host".

The original issue shows a simple usecase where this distinction is relevant, and where matching on SNI servername would be useful. There is a workaround, but seeing that traefik already has some concept of HostSNI(), I thought that it would be useful to have it consistent throughout.

Script:

```
#!/bin/bash

echo ===============================
curl --silent https://whoami.example.com |grep Host

echo ===============================
curl --silent https://ping.example.com |grep Host

echo ===============================
(openssl 2>&1 s_client -quiet -servername ping.example.com -connect ping.example.com:443 |grep Host) <<EOF
GET / HTTP/1.1
Host: whoami.example.com
Connection: Close


EOF
```

Output:

```
===============================
Hostname: 3936463c073b
Host: whoami.example.com
X-Forwarded-Host: whoami.example.com
===============================
Hostname: e4be2236d4bd
Host: ping.example.com
X-Forwarded-Host: ping.example.com
===============================
Hostname: 3936463c073b
Host: whoami.example.com
X-Forwarded-Host: whoami.example.com
```
