### ISSUE TITLE
ACME HTTP challenge should use router entry points

### ISSUE THREAD

**Issue by fuzzykiller** [containous/traefik#6667]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

<b>tl;dr</b>: Single entry point on ACME HTTP challenge does not mix well with multiple entry points on routers.

Currently, the ACME HTTP challenge supports a single entry point while routers can have any number of entry points assigned. This creates situations where certificates cannot be acquired or renewed because the verification request arrives at an unexpected entry point.

Consider the follow configuration:

```toml
[entryPoints]
  [entryPoints.https]
    address = "1.2.3.4:443"
  [entryPoints.https6]
    address = "[::1234]:443"
```

Now of course I want my services to be reachable with both IPv4 and IPv6. So my DNS name would have both A and AAAA records. The Traefik router would have these two entry points. All good! Almost.

Let’s Encrypt appears to prefer IPv6 if available. But I guess they would fall back to IPv4 like browsers do, so pretty quickly. That means I cannot really "pick the correct entry point".

One possible solution is to just use all port 80 entry points (ACME does not use other ports except when redirected to 443). The change could be as simple as removing the configuration option and adapting the following line to check for port 80 instead:

https://github.com/containous/traefik/blob/da8451c6373ce09cdfa0eedb770922cabf37426f/cmd/traefik/traefik.go#L266

Another possible solution is to simply support multiple entry points on the HTTP challenge configuration (and again adapting the line above). This was suggested pre-2.0 in #2710.

Both changes appear relatively small to me.

(I found that the TLS challenge works for me so this is not a priority.)

**Comment by ldez** [comment]
Hello,

This use case is a edge case of the HTTP challenge, and in this case the right challenge to use is the TLS challenge.

Handle this edge case will complicate all standard cases (99% of the cases)

So we will decline, thank you anyway.
