### ISSUE TITLE
Regexp exclude

### ISSUE THREAD

**Issue by danielgroen** [containous/traefik#6668]
Hi,

I am using Traefik version 2.2 and want to have my own 404 page for the server.

I created a simple docker-compose file with the label:
```yaml
 - traefik.http.routers.err_insecure.rule=HostRegexp(`{subdomain:(?!dashboard)([a-z]+)}.server1.domain.com`)
```
Dashboard.server1.domain is leading to the traffic dashboard.
So i want to exclude that domain, but for the rest i want to lead it to this docker-container.

However if i start the container traefik gives me the following message:
```
error parsing regexp: invalid or unsupported Perl syntax: `(?!`
```

**Comment by ldez** [comment]
Hello,

the Look-ahead and Look-behind are not possible in Go.
