### ISSUE TITLE
api.insecure marked as true by default but it's false

### ISSUE THREAD

**Issue by thisismydesign** [containous/traefik#6670]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Looking at https://raw.githubusercontent.com/containous/traefik/v2.2/traefik.sample.toml:

```
# Enable API and dashboard
[api]

  # Enable the API in insecure mode
  #
  # Optional
  # Default: true
  #
  # insecure = false
```

But then using my own config:

```
[api]
```

### What did you expect to see?

Can access http://localhost:8080/api/rawdata following docker-compose example.

### What did you see instead?

Could not access http://localhost:8080/api/rawdata unless explicitly setting

```
[api]
  insecure = true
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

2.2

```
(paste your output here)
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# (paste your configuration here)
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```

**Comment by traefiker** [comment]
Closed by #6671.
