### ISSUE TITLE
Dashboard not accessible unless `api.insecure` is set to true

### ISSUE THREAD

**Issue by thisismydesign** [containous/traefik#6672]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Followed the getting started guide with docker compose and my own config file:

```
[api]
```

or

```
[api]
  dashboard = true
```

### What did you expect to see?

Ability to access the dashboard.

### What did you see instead?

No server response.

If I do

```
[api]
  insecure = true
```

Then I can see the dashboard.

### Output of `traefik version`: (_What version of Traefik are you using?_)

2.2

```
(paste your output here)
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# (paste your configuration here)
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by thisismydesign** [comment]
Your advanced AI is wrong, hopefully this will indeed get reopened.

**Comment by ldez** [comment]
Hello, the bot is right:
- https://docs.traefik.io/v2.2/operations/dashboard/#secure-mode

**Comment by thisismydesign** [comment]
Hey @Idez, that doesn't work for me... It's either a but or documentation bug imo. By having `[api]` the dashboard should already be enabled as that's the default but it's not. Setting `dashboard: true` also has no effect.

This is unless I set `insecure = true`. Does that make sense?

**Comment by ldez** [comment]
For more help, could you join the [community forum](https://community.containo.us/), thanks.

**Comment by webyneter** [comment]
Doesn't work for me without `insecure = true` either, ain't there a way to serve the dashboard on HTTPS?

**Comment by webyneter** [comment]
This issue needs to be re-opened, I'm facing the exact same issue as well.

**Comment by SuperSandro2000** [comment]
There is an example in the docs https://docs.traefik.io/operations/dashboard/#secure-mode which I am running since a while and the dashboard works without ``insecure = true``.

**Comment by ldez** [comment]
For more help, could you join the [community forum](https://community.containo.us/), thanks.
