### ISSUE TITLE
I visited http://127.0.0.1:8034 and couldn't open the UI page

### ISSUE THREAD

**Issue by Xuzan9396** [containous/traefik#6677]
![image](https://user-images.githubusercontent.com/24741439/79246755-319bf300-7eac-11ea-9899-ba1aaacd1304.png)

![image](https://user-images.githubusercontent.com/24741439/79246781-38c30100-7eac-11ea-8acf-17ffce21a310.png)

![image](https://user-images.githubusercontent.com/24741439/79246818-46788680-7eac-11ea-87ff-bb0087874ff0.png)

![image](https://user-images.githubusercontent.com/24741439/79247021-863f6e00-7eac-11ea-9f90-8d94bca722d7.png)

What am I supposed to do now? I can't open kanban

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
