### ISSUE TITLE
Does kubernetesCRD conf apply to ingresses or ingressroutes ?

### ISSUE THREAD

**Issue by sylr** [containous/traefik#6680]
In the documentation of the kubernetesCRD provider we can read:

https://github.com/containous/traefik/blob/f624449ccbf42c56279c594eadc226fed6583993/docs/content/providers/kubernetes-crd.md#L174-L178

Should we really read `Ingresses` meaning that we can't select `IngressRoute` objects or is this a bad wording ?

**Comment by traefiker** [comment]
Closed by #6681.
