### ISSUE TITLE
Add arbitrary headers to requests.

### ISSUE THREAD

**Issue by errm** [containous/traefik#669]
Some applications need us to pass some headers with the request for config purposes.

e.g:
`nuxeo-virtual-host` - https://doc.nuxeo.com/display/ADMINDOC58/HTTP+and+HTTPS+Reverse-Proxy+Configuration
`X-Graylog-Server-URL` - http://docs.graylog.org/en/2.1/pages/configuration/web_interface.html

I propose that we add a mechanism to support adding headers to requests.  I feel like this may belong on the frontend but I am willing to be convinced otherwise.

There may be a better more dynamic way to do this, than just adding static headers... perhaps this could be configured with a template or something...

n.b. creating this after a discussion with `cnf` in the support slack.

**Comment by cnf** [comment]
Thanks! I'd also like to add a mention `X-Script-Name`  which quite a few things count on.

**Comment by dipadipa** [comment]
i need X-Script-Name also

**Comment by zyzop** [comment]
That's very much needed to me too.

**Comment by ldez** [comment]
You can follow the PR # #1236.

**Comment by ldez** [comment]
Closed by #1236.
