### ISSUE TITLE
Support Kubernetes IngressClass Ressource and pathType field

### ISSUE THREAD

**Issue by SantoDE** [containous/traefik#6690]
### Do you want to request a *feature* or report a *bug*?
Feature

### What did you expect to see?

Starting with Kubernetes 1.18, a new Ressource IngressClass was introduced which is aimed to replace the well known `kubernetes.io/ingress.class`annotation. Traefik should also check for that ressource (and the `ingressClassName` field on an Ingress) and use it to evaluate whether its responsible for a certain Ingress Ressource or not.

A potential value for the IngressClass name could be `traefik.io/ingress-controller`

Additionally, the Ingress Ressource received a new field "PathType", which can be used to further qualify how the Path should be handled.

Traefik should use that types as the following matchers:

- Exact => Path
- Prefix => PathPrefix
- ImplementationSpecific => should default to Path

One of the allowed values is "ImplementationSpecific"

IngressClass issue: https://github.com/containous/traefik/issues/6829
Path Update issue: https://github.com/containous/traefik/issues/6830

**Comment by dahu33** [comment]
I'm surprised there is no mention of the IngressClass `parameters` field which is in my opinion the most exciting feature of the IngressClass resource.

It would be extremely useful if Traefik could take advantage of that field so we could specify, the entrypoints, middlewares and maybe the tls options for an IngressClass.

I've created an issue here: https://github.com/containous/traefik/issues/7057

**Comment by traefiker** [comment]
Closed by #7087.
