### ISSUE TITLE
ACME cert resolver as an internal, routable service

### ISSUE THREAD

**Issue by maurete** [containous/traefik#6692]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Currently Traefik doesn't allow much configuration for the Let's Encrypt challenges, except for the entrypoint. It would be great if the ACME handler was exposed as an internal service so it could be routed. 
If there existed a service, say, `letsencrypt@internal` with a default router, we could let Traefik manage most of ACME challenges but still be able to let through those special cases where we need to generate Let's Encrypt certificates for other purposes other than HTTPS traffic.
In our situation, we're using Traefik as a frontend for HTTP(S) traffic at www.domain.com. Our mail server (mail.domain.com, same IP address but different DNS name) is unable to obtain certificates via HTTP challenge as they're "intercepted" by Traefik.

**Comment by ldez** [comment]
Hello,

I recommend to use the TLS challenge instead of the HTTP challenge.

https://docs.traefik.io/v2.2/https/acme/#tlschallenge

**Comment by maurete** [comment]
That worked like a charm, thanks!
