### ISSUE TITLE
tcp route not work

### ISSUE THREAD

**Issue by zzxap** [containous/traefik#6693]
my toml
tcp is no tls

[entryPoints.tcpproxy]
   address = ":8095/tcp"
kv tcp service

etcdctl put  traefik/tcp/services/mytcpservice/loadbalancer/servers/0/url 123.89.xx.xx:8096

etcdctl put traefik/tcp/routers/myrouter/rule 'HostSNI(`*`)'
etcdctl put traefik/tcp/routers/myrouter/entrypoints/0 tcpproxy
etcdctl put traefik/tcp/routers/myrouter/service mytcpservice

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
