### ISSUE TITLE
Option to translate Origin and Referer protocols from https to http

### ISSUE THREAD

**Issue by sanderPostma** [containous/traefik#6697]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

A config option to translate the protocol from https to http for the Origin & Referer headers. I have a 3rd party backend solution that checks the Origin & Referer headers against the request and blocks access because it notices that the browser is running on https:// but after proxying through Traefik the request protocol becomes http.

As far as I can see the existing headers middleware does not support RegEx replace features and I think it doesn't even allow replacing the Origin header, so I can't use that as a workaround.
(The only work-around for now I can think of is using a custom Traefik build including the Negasus Luascript middleware, but that's quite a hacky way to go.)

**Comment by jbdoumenjou** [comment]
Duplicate of #6047
