### ISSUE TITLE
Intermittent acme SSL issue, serving default example certificate 2% of the time

### ISSUE THREAD

**Issue by nodesocket** [containous/traefik#6699]
Hello, I am running Traefik version **1.7.18** in Kubernetes version **1.14.9** using Consul version **1.5.3** as the KV provider. I have a handful of other deployments that work spectacularly, but one of the deployments keeps on serving the default example.com certificate very intermittently. 98% of the time it works, but around 2% Traefik does not serve the valid Let's Encrypt certificate and falls back to serving default example.com.

I am monitoring the deployment and here is graph showing the issue:

<img width="957" alt="Screen Shot 2020-04-18 at 2 50 58 PM" src="https://user-images.githubusercontent.com/523312/79669855-529e6580-8184-11ea-9221-0a235f3bb572.png">

I am thinking perhaps something is wrong with the ingress definition for the deployment. Here it is:

```
$ kubectl describe ingress fusionauth

Name:             fusionauth
Namespace:        default
Address:
Default backend:  default-http-backend:80 (<none>)
TLS:
  SNI routes fusionauth.simplyagree.dev
Rules:
  Host                        Path  Backends
  ----                        ----  --------
  fusionauth.simplyagree.dev
                              /   fusionauth:http (192.168.10.3:9011,192.168.11.242:9011,192.168.47.66:9011)
Annotations:
  kubernetes.io/ingress.class:  traefik
  kubernetes.io/tls-acme:       true
Events:                         <none>
```

```
$ kubectl edit ingress fusionauth

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
    kubernetes.io/tls-acme: "true"
  creationTimestamp: "2020-04-18T01:49:14Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: fusionauth
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: fusionauth
    helm.sh/chart: fusionauth-0.3.3
  name: fusionauth
  namespace: default
  resourceVersion: "35478626"
  selfLink: /apis/extensions/v1beta1/namespaces/default/ingresses/fusionauth
  uid: ceeed239-8116-11ea-89e6-06161e3a9baa
spec:
  rules:
  - host: fusionauth.simplyagree.dev
    http:
      paths:
      - backend:
          serviceName: fusionauth
          servicePort: http
        path: /
  tls:
  - hosts:
    - fusionauth.simplyagree.dev
status:
  loadBalancer: {}
```

```
$ kubectl describe service fusionauth

Name:              fusionauth
Namespace:         default
Labels:            app.kubernetes.io/instance=fusionauth
                   app.kubernetes.io/managed-by=Tiller
                   app.kubernetes.io/name=fusionauth
                   helm.sh/chart=fusionauth-0.3.3
Annotations:       <none>
Selector:          app.kubernetes.io/instance=fusionauth,app.kubernetes.io/name=fusionauth
Type:              ClusterIP
IP:                10.100.208.18
Port:              http  9011/TCP
TargetPort:        http/TCP
Endpoints:         192.168.10.3:9011,192.168.11.242:9011,192.168.47.66:9011
Session Affinity:  None
Events:            <none>
```

Spot anything, or any ideas what could be happening? This has me completely stumped.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

Issue templates help us help you by providing all necessary information.

Please edit your issue and use the available templates:

- [Feature request](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/Feature_request.md)
- [Bug report](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/Bug_report.md)

And remember: each time someone ignores the template, a cute little bunny dies.
<details>
<summary>#SaveTheCuteBunny :heart: :rabbit: :heart:</summary>

![southpark - estrella kill rabbit](https://user-images.githubusercontent.com/5674651/27143914-3cea7896-5130-11e7-81f8-02d8ac2da7a7.gif)

![southpark - estrella kill rabbit2](https://user-images.githubusercontent.com/5674651/27143924-49104c72-5130-11e7-82ae-ccedbd5dfa1c.gif)

</details>

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Community Forum](https://community.containo.us/).
