### ISSUE TITLE
X-Forwarded-Proto and Websockets

### ISSUE THREAD

**Issue by dtomcej** [containous/traefik#670]
When using secure websockets (wss), the X-Forwarded-Proto gets set to http, instead of the intended wss.

In nginx, you configure the X-Forwarded-Proto using the request scheme via:

`proxy_set_header X-Forwarded-Proto $scheme;`

it would also be nice to include a Protocol Rule test, as it would be nice to be able to redirect traffic to different backends based on the protocol of the request, not just the entrypoint/hostname

**Comment by L8D** [comment]
Any update on this?

**Comment by mcoms** [comment]
In v1.1.0, `X-Forwarded-Proto` (and _X-Forwarded-anything_) doesn't get set at all for websocket upgrades.

The following was how I tested this, which might help someone investigating.

Setup: Rails running on localhost:4000. Traefik v1.1.0 running on test.localhost:5000. SSL enabled on the Traefik endpoint.

```
debug = true
logLevel = "DEBUG"
defaultEntryPoints = ["defent"]

[entryPoints]
  [entryPoints.defent]
    address = ":5000"
    [[entryPoints.defent.tls.certificates]]
      CertFile = "/Users/nick/Documents/traefik/ssl/cert"
      KeyFile = "/Users/nick/Documents/traefik/ssl/key"

[retry]

[web]
address = ":8080"

[file]
  [backends]
    [backends.testbe]
      [backends.testbe.servers.testsrv]
      url = "http://localhost:4000"
  [frontends]
    [frontends.testfe]
    backend = "testbe"
    passHostHeader = true
      [frontends.testfe.routes.testrt]
      rule = "Host:test.localhost"
```

Hitting https://test.localhost:5000/ in Chrome, and monitoring packets between Traefik and Rails (port 4000) with Wireshark...

```
GET / HTTP/1.1
Host: test.localhost:5000
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding: gzip, deflate, sdch, br
Accept-Language: en-US,en;q=0.8
Cache-Control: max-age=0
Upgrade-Insecure-Requests: 1
X-Forwarded-For: ::1
X-Forwarded-Host: test.localhost:5000
X-Forwarded-Proto: https
X-Forwarded-Server: Macbook-Air.local
EOT

<works — 200 OK, HTML returned>

GET /assets/jquery_ujs.self-784a997f6726036b1993eb2217c9cb558e1cbb801c6da88105588c56f13b466a.js?body=1 HTTP/1.1
Host: test.localhost:5000
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36
Accept: */*
Accept-Encoding: gzip, deflate, sdch, br
Accept-Language: en-US,en;q=0.8
Cache-Control: max-age=0
Referer: https://test.localhost:5000/
X-Forwarded-For: ::1
X-Forwarded-Host: test.localhost:5000
X-Forwarded-Proto: https
X-Forwarded-Server: Macbook-Air.local
EOT

<works — 200 OK, JS returned>

GET /cable HTTP/1.1
Host: test.localhost:5000
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36
Accept-Encoding: gzip, deflate, sdch, br
Accept-Language: en-US,en;q=0.8
Cache-Control: no-cache
Connection: Upgrade
Origin: https://test.localhost:5000
Pragma: no-cache
Sec-Websocket-Extensions: permessage-deflate; client_max_window_bits
Sec-Websocket-Key: eoLTzPZjnVdqtv6oc1/1Gg==
Sec-Websocket-Protocol: actioncable-v1-json, actioncable-unsupported
Sec-Websocket-Version: 13
Upgrade: websocket
EOT

<breaks>

HTTP/1.1 301 Moved Permanently
Content-Type: text/html
Location: https://test.localhost:5000/cable
Transfer-Encoding: chunked
EOT
```

Rails (like many others) checks for HTTPS like this .. and decides to fire a 301 redirect if the header isn't present.

```ruby
def ssl?
  @env['HTTPS'] == 'on' || @env['HTTP_X_FORWARDED_PROTO'] == 'https'
end
```

The result of Traefik not including the header for websocket upgrades in my particular case was every request to `/cable` resulting in a `301 Moved Permanently` when `config.force_ssl = true`.

If I turn off forcing SSL (and therefore ignore the header being missing), the websocket connection works perfectly.

Not a Rails specific bug, but I thought it might be useful to include my context for testing, and for others experiencing the issue with similar frameworks.

**Comment by dtomcej** [comment]
@mcoms I am going to be doing some header implementations for upcoming security work. Will hit this issue at the same time.

**Comment by scher200** [comment]
@dtomcej any update on the X-Forwarded-proto ?

**Comment by dtomcej** [comment]
Sorry, I was hoping to get it out for the 1.2 release, but this is my top priority right now.

**Comment by scher200** [comment]
@dtomcej may i suggest..
maybe you can make it variable so that you can set your own extra header: X-Forwarded-proto, X-Custom-Referrer, etc.. and there values.
Like a custom header that you can label to any app/container. That would satisfy all kinds of different app's.

**Comment by dtomcej** [comment]
Ideally I would like to tie it to backends, and template it out, so that you can have as many headers defined as you want per-backend. (as per #669)
However, I will not have it overwrite currently create headers (x-forwarded-proto).

**Comment by dtomcej** [comment]
I have a PR (from another repo) https://github.com/containous/oxy/pull/11 That should resolve this. Once approved, will test, and update this ticket.

**Comment by dtomcej** [comment]
@scher200 I am also working on #669 to resolve the other header issues.

**Comment by scher200** [comment]
@dtomcej awesome

**Comment by ldez** [comment]
I'll close this issue, because I think the question is answered, but feel free to continue the conversation.

**Comment by mikesir87** [comment]
I'm running into this with 1.4 (using Docker Swarm).  Like @mcoms mentioned above, I have an app that is looking for the presence of the `X-Forwarded-Proto` header and redirecting the user if that is not set. It is added for all non-WebSocket requests but all `X-Forwarded-*` headers are missing on the WebSocket connection. I have `passHostHeader` set, but no change there. I can't quite figure out from this issue what I might be missing.  Any pointers?

**Comment by Juliens** [comment]
@mikesir87 could you try with 1.5.0-rc2 ?

**Comment by mikesir87** [comment]
@Juliens - thanks for the quick response. Just updated to 1.5.0-rc2 and can confirm that the `X-Forwarded-*` headers ARE indeed added to the websocket requests. So... all good to go.  Thanks!
