### ISSUE TITLE
traefik tcp proxy single port multi-environment

### ISSUE THREAD

**Issue by xxlaila** [containous/traefik#6708]
I used traefik 2.2 version. The toml format is dynamically configured. I created dev, test, and uat multiple namespaces on the kubernetes platform to distinguish my environment. Under each namespace, there is a mysql service. I want to use traefik to proxy mysql.
When I proxy dev, there is no problem, I can connect to mysql
```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
   name: dev-traefik-tcp
   namespace: kube-dev
spec:
   entryPoints:
     -mysql
   routes:
   -match: HostSNI (`middle.dev.test.com`)
     services:
     -name: mysql5-6
       port: 3306
```
Then I added test.
```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
   name: test-traefik-tcp
   namespace: kube-test
spec:
   entryPoints:
     -mysql
   routes:
   -match: HostSNI (`middle.test.test.com`)
     services:
     -name: mysql5-6
       port: 3306
```
After the creation of dev and test, the connection to mysql is lost. In this scenario, how should I configure it?

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
