### ISSUE TITLE
Redirect HTTP -> HTTPS response returns 302

### ISSUE THREAD

**Issue by dtomcej** [containous/traefik#671]
When redirecting HTTP (:80) to HTTPS (:443) using `[entryPoints.http.redirect] entryPoint = "https"`, the browser receives a 302 (Found). A better response would be a 301, since that is the preferred response for HTTP to HTTPS redirection.

As per:
https://en.wikipedia.org/wiki/HTTP_301

**Comment by Yggdrasil** [comment]
Yes, Google appears to agree. 

> Redirect your users and search engines to the HTTPS page or resource with server-side 301 HTTP redirects.

Source: https://support.google.com/webmasters/answer/6073543?hl=en

**Comment by DMWOO7** [comment]
I totally agree with @dtomcej. We should change 302 to 301. Using Traefik, I also switched from HTTP to HTTPS with a site, which is hosted in a backend container. Google should know, that the old HTTP URLs are not used any more. So 301 would be preferable here.

**Comment by macman31** [comment]
More generally, `[entryPoints.http.redirect]` could accept a `redirectCode` key to indicate if the redirect should be a 301 or 302.

Indeed, `redirect` is not always used for redirecting HTTP to HTTPS. In some cases a 302 is preferred, especially when using `regex`/`replacement` instead of `entryPoint` in `[entryPoints.http.redirect]`.

**Comment by ston3o** [comment]
+1

**Comment by tomtastic** [comment]
Doesn't seem to work currently with v1.7.4 :

My traffic.toml has :
> [entryPoints]
>     [entryPoints.http]
>     address = ":80"
>         [entryPoints.http.redirect]
>             entryPoint = "https"


I start my Docker Traefik container with the label : `-l traefik.frontend.redirect.permanent=true`

But all HTTP redirects to HTTPS result in a 302 code :
`178.93.54.170 - - [03/Dec/2018:09:29:00 +0000] "GET / HTTP/1.1" 302 5 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36" 2857 "entrypoint redirect for http" "/" 0ms`
