### ISSUE TITLE
Fix the errorlog spam in docker swarm

### ISSUE THREAD

**Issue by chrisbecke** [containous/traefik#6711]
## Issue

When  I look at my traefik logs on my docker swarm they are full of errors:

```
level=error msg="service \"<service>\" error: port is missing" provider=docker container=<somecontainer>
```

## What I expect

Not to have to deal with growing error logs that are not errors.

### disableByDefault

The "disableByDefault" setting does exist, but this is a stupid requirement as the traefik consumer is already declaring their interest in using traefik by configuring the other required traefik labels. 

### providers.docker.constraints

The rational solution would be to make use of the static config parameter `providers.docker.constraints` - but if we are dumb we are basically re-implementing disableByDefault. Given that docker swarm mode absolutely requires a configured http router with a port it would therefore be ideal to simply create a constraint that checks to see if the corresponding label is set.

However, because these routers incorporate a dynamic component its - seemingly - impossible to construct such a constraint.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
