### ISSUE TITLE
Allow more than one server behind traefik to manage their own certificates themselves via let's encrypt

### ISSUE THREAD

**Issue by jmchantrein** [containous/traefik#6716]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Allow more one server behind traefik to manage their own certificates themselves and via let's encrypt.

It is currently not possible to allow **several** servers behind traefik to manage their own certificates themselves via let's encrypt.

This can be done via a TCP router and a TLS passtrough for **one** server, but not for several : https://stackoverflow.com/questions/59971646/is-there-a-way-to-let-some-traefik-services-manage-their-tls-certificates-themse. 

The likely cause of this limitation may be due to the following rule from https://docs.traefik.io/routing/routers/#configuring-tcp-routers:
_It is important to note that the Server Name Indication is an extension of the TLS protocol. Hence, only TLS routers will be able to specify a domain name with that rule. However, non-TLS routers will have to explicitly use that rule with * (every domain) to state that every non-TLS request will be handled by the router._

**Comment by juliens** [comment]
Thanks for your interest in the project.

I'm not sure to understand your use case, and I'm not sure if it's not already possible to do what you need.

In order to give us more information about this, could you please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

**Comment by jmchantrein** [comment]
Hello Julien, 

I had already asked the community forum. I have just added some explanations to my question which is here: https://community.containo.us/t/is-there-a-way-to-let-some-services-manage-their-tls-certificates-themselves/4143/2 

Please check if this seems more understandable to you and if necessary consider reopening my feature request. 

Regards, 

Jean-Mathieu
