### ISSUE TITLE
Provide a way of setting the default set of entry points

### ISSUE THREAD

**Issue by trajano** [containous/traefik#6718]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

a way of configuring an endpoint so it is not part of the default entry points.  I generally route everything to HTTPS and I want avoid explicitly stating the entrypoints per route to ignore the HTTP route.

**Comment by ldez** [comment]
Dupicate of #5672

**Comment by trajano** [comment]
Can #5672 be reopened.  The use case scenario is basically to remove the need to explicitly set the entrypoints just like `traefik` is not exposed by default.
