### ISSUE TITLE
middleware does not exist

### ISSUE THREAD

**Issue by OojaxoO** [containous/traefik#6724]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you see instead?
Meddleware does not exist when my middleware exceeds a certain amount( maybe 900)
![image](https://user-images.githubusercontent.com/31960021/80182935-83761300-863a-11ea-8d20-0b7b6d9da1f2.png)

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
2.0.5
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```
provider: kubernetescrd
platform: Ubuntu 18.04.1
kubernet: v1.13.4
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```
middleware
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  creationTimestamp: "2020-04-24T02:23:03Z"
  generation: 5
  name: ai.ai-api-web.path
  namespace: qa
  resourceVersion: "126476632"
  selfLink: /apis/traefik.containo.us/v1alpha1/namespaces/qa/middlewares/ai.ai-api-web.path
  uid: 86c58529-85d2-11ea-8a41-005056ad49fb
name: ai.ai-api-web.path
spec:
  stripPrefix:
    prefixes:
    - /

ingressroute
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  creationTimestamp: "2020-04-24T02:23:04Z"
  generation: 1
  name: ai.ai-api-web
  namespace: qa
  resourceVersion: "126438449"
  selfLink: /apis/traefik.containo.us/v1alpha1/namespaces/qa/ingressroutes/ai.ai-api-web
  uid: 86e4e23e-85d2-11ea-8a41-005056ad49fb
name: ai.ai-api-web
spec:
  entryPoints:
  - web
  routes:
  - kind: Rule
    match: Host(`qa.ai.lls.com`) && PathPrefix(`/`)
    middlewares:
    - name: ai.ai-api-web.path
      namespace: qa
    services:
    - name: ai-api-web
      port: "80"

global:
- --api.insecure=true
        - --accesslog
        - --entrypoints.web.Address=:80
        - --entrypoints.websecure.Address=:443
        - --providers.kubernetescrd
        - --certificatesresolvers.default.acme.tlschallenge
        - --certificatesresolvers.default.acme.email=foo@you.com
        - --certificatesresolvers.default.acme.storage=acme.json
        - --certificatesresolvers.default.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
