### ISSUE TITLE
Build Error: panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by shibumi** [containous/traefik#6731]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Hi,
I tried compiling the newest traefik from source for the official Arch Linux repositories.
Here is our current go environment:

* Go: 1.14.2
* go-bindata: 3.5.0 / https://github.com/shuLhan/go-bindata
* traefik: 2.2.0

Build Steps:

* go generate
* cd cmd/traefik
* go build -trimpath -ldflags "-extldflags ${LDFLAGS}"

PKGBUILD: https://shibumi.dev/share/PKGBUILD

### What did you expect to see?

I expect traefik to build properly.

### What did you see instead?

`go generate` seems to produce the following output:

```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/shuLhan/go-bindata.sanitizeChunks(0xc0000d6c10, 0x0, 0x0, 0x0)
	/build/go-bindata/src/src/github.com/shuLhan/go-bindata/release.go:144 +0x2d1
github.com/shuLhan/go-bindata.sanitize(0xc000247e00, 0x0, 0x200, 0xc0000d6c9f, 0x1, 0x1)
	/build/go-bindata/src/src/github.com/shuLhan/go-bindata/release.go:130 +0x2f9
github.com/shuLhan/go-bindata.nocompressMemcopy(0x55d228859940, 0xc0000f4480, 0xc00023c280, 0x55d228859a60, 0xc00000e0b8, 0x0, 0x0)
	/build/go-bindata/src/src/github.com/shuLhan/go-bindata/release.go:235 +0x175
github.com/shuLhan/go-bindata.writeReleaseAsset(0x55d228859940, 0xc0000f4480, 0xc0000ea210, 0xc00023c280, 0x0, 0x0)
	/build/go-bindata/src/src/github.com/shuLhan/go-bindata/release.go:83 +0x1e7
github.com/shuLhan/go-bindata.writeRelease(0x55d228859940, 0xc0000f4480, 0xc0000ea210, 0xc00023c000, 0x5f, 0x60, 0x1, 0x14)
	/build/go-bindata/src/src/github.com/shuLhan/go-bindata/release.go:36 +0xb0
github.com/shuLhan/go-bindata.translateToFile(0xc0000ea210, 0xc00023c000, 0x5f, 0x60, 0xc000226000, 0x5f)
	/build/go-bindata/src/src/github.com/shuLhan/go-bindata/translateToFile.go:43 +0x443
github.com/shuLhan/go-bindata.Translate(0xc0000ea210, 0x0, 0x55d2288599a0)
	/build/go-bindata/src/src/github.com/shuLhan/go-bindata/translate.go:46 +0x36d
main.main()
	/build/go-bindata/src/src/github.com/shuLhan/go-bindata/cmd/go-bindata/main.go:72 +0xbc
generate.go:4: running "go-bindata": exit status 2
```

**Comment by shibumi** [comment]
I have a feeling that this might be an issue with our go-bindata. Can you tell me which go-bindata you are using?

**Comment by shibumi** [comment]
Funfact: When I build this project with Hashicorps go-bindata it works as expected: https://github.com/hashicorp/go-bindata

**Comment by ldez** [comment]
Hello,

We use a fork of this original https://github.com/jteeuwen/go-bindata

Take a look to: https://docs.traefik.io/v2.2/contributing/building-testing/#method-2-using-go
