### ISSUE TITLE
Skipping empty Configuration for provider consul

### ISSUE THREAD

**Issue by bvivi57** [containous/traefik#6736]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
I deployed Traefik under Kubernetes with consul cluster access. 

### What did you expect to see?
I wanted to be able to configure traefik by adding via key/value in consul and use consul as configuration provider for traefik.

For example, I want to create a new entry point using the following configuration in consul:

```
traefik
   entrypoints
       test
           address :1704/udp
```
or change the log level
```
traefik
   log
       level INFO
```

### What did you see instead?
Traefik considers that the configuration in consul is empty whereas I did create values under the "traefik" tree. 

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
traefik:v2.2.0
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```
[tls]

  [tls.stores]
    [tls.stores.default]
      [tls.stores.default.defaultCertificate]
        certFile = "/etc/static_certs/prd/inf/prd_inf.cer"
        keyFile = "/etc/static_certs/prd/inf/prd_inf.key"

  [[tls.certificates]]
    certFile = "/etc/static_certs/prd/inf/prd_inf.cer"
    keyFile = "/etc/static_certs/prd/inf/prd_inf.key"

```
The container is launched with the following parameters: 
```
args:
       - --providers.kubernetescrd
       - --entrypoints.web.address=:80
       - --entrypoints.websecure.address=:443
       - --entrypoints.sftp.address=:2222
       - --api.dashboard=true
       - --log.level=DEBUG
       - --providers.file.directory=/etc/traefik/
       - --providers.consul.endpoints=svc-consul-for-traefik:8500
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
time="2020-04-27T10:21:43Z" level=debug msg="List: traefik"
time="2020-04-27T10:21:43Z" level=debug msg="Configuration received from provider consul: {}" providerName=consul
time="2020-04-27T10:21:43Z" level=info msg="Skipping empty Configuration for provider consul" providerName=consul
```

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
