### ISSUE TITLE
Support for sticky session with kubernetes ingress as backend

### ISSUE THREAD

**Issue by vijayrcse** [containous/traefik#674]
Hi

Can anyone suggest if sticky session(cookie based) is supported in traefik with kuebernetes ingress as backend.

I tried the below annotations in my ingress resource but this doesn't work. The request is being routed to multiple pod

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: node-web-app-ingress
  annotations:
    traefik.stickysession: "true"

Please advise

**Comment by tillkuhn** [comment]
[This PR](https://github.com/containous/traefik/pull/701) looks promising but apparently it has not (yet) been implemented for Kubernetes Ingress, but only for Docker and Marathon (see [Backend Configurations](traefik.backend.loadbalancer.sticky) and search for *traefik.backend.loadbalancer.sticky*). Any Go volunteers?

**Comment by errm** [comment]
Fixed in #1068
