### ISSUE TITLE
Marathon dynamic path routing

### ISSUE THREAD

**Issue by Salmondx** [containous/traefik#675]
Is is possible to route marathon services only by path without `Host` header?
Documentation says, that path is only additional hardcoded routing strategy, not primary one.

But in my case, it will be great if i could route without additional header.
Now i should send requests like this: 
`http 192.168.99.100 Host:marathon-service.marathon.localhost`
And i want like this:
`http 192.168.99.100/marathon-service/`

And path configuration loads dynamically without additional rows in traefik.toml

**Comment by Salmondx** [comment]
I found a solution: during marathon app deployment provide frontend rule ```traefik.frontend.rule="Path:/marathon-service"``` but with this solution i have to redeploy all apps.
Is it possible to set this path through traefik.toml configuration file?
Like this:
```frontend.defaultRule = "Path:/{containerName}.{domainName}"```

**Comment by Salmondx** [comment]
And with solution above, i've found a strange problem: when i send request ```http 192.168.99.100/marathon-service/api``` 404 code returned → /marathon-service/api is another path, not /marathon-service redirect with  /api.

**Comment by timoreimann** [comment]
@Salmondx As you found out by now, you can perfectly route via path matching only. Host headers are not required.

If you want to define the path matcher statically, you could take the default Marathon template file, adjust it to your needs, and specify your custom version in the configuration. It's just a Go template file.

`Path` matches an exact path. You want `PathPrefix` to route if a prefix matches. If your application listens on the root path, use `PathPrefixStrip` to strip the prefix prior to routing requests to your application.

I hope this answers your questions.
