### ISSUE TITLE
ACME certificates not created for dashboard with swarm [Traefik 2.2.0]

### ISSUE THREAD

**Issue by fredbcode** [containous/traefik#6758]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

With this configuration there is no exchange with letsencrypt at all for my dashboard (only)

```
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.api.rule=Host(`traefik.xxx.fr`)"
        - "traefik.http.routers.api.service=api@internal"
        - "traefik.http.routers.api.entrypoints=https"
        - "traefik.http.routers.api.tls=true"
        - "traefik.http.routers.api.certresolver=xxxx"
        - "traefik.http.routers.api.middlewares=auth"
```

### What did you expect to see?

Letsencrypt DNS-01 exchange

### What did you see instead?

Letsencryt for my all my domains except for my dashboard

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.2.0
Codename:     chevrotin
Go version:   go1.14.1
Built:        2020-03-25T17:32:57Z
OS/Arch:      linux/amd64

```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```
[log]
  level = "DEBUG"

[api]
   dashboard = true

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"

[providers.docker]
  endpoint = ["http://dockersocket:2375"]
  swarmMode = true
  watch = true

[certificatesResolvers.xxxx.acme]
  email = "xxxx@free.fr"
  storage = "/etc/traefik/acme.json"
  [certificatesResolvers.xxxx.acme.dnsChallenge]
   provider = "ovh"
   delayBeforeCheck = "30"
   resolvers = "1.1.1.1:53,9.9.9.9:53"

[certificatesResolvers.xxxx.acme]
  email = "xxxx@free.fr"
  storage = "/etc/traefik/acme.json"
  [certificatesResolvers.xxxx.acme.dnsChallenge]
   provider = "ovh"
   delayBeforeCheck = "30"
   resolvers = "1.1.1.1:53,9.9.9.9:53"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

time="2020-04-30T13:33:44+03:00" level=debug msg="Adding certificate for domain(s) e2guardian.xxx.fr"
time="2020-04-30T13:33:44+03:00" level=debug msg="Adding certificate for domain(s) nas.xxxx.fr"
time="2020-04-30T13:33:44+03:00" level=debug msg="Adding certificate for domain(s) portainer.xxxx.fr"

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
