### ISSUE TITLE
Middleware CRD spec as documented cannot be parsed after upgrading from v2.1 to v2.2

### ISSUE THREAD

**Issue by brandond** [containous/traefik#6760]
### Do you want to request a *feature* or report a *bug*?
Bug

### What did you do?
Configured redirectscheme middleware as per the documentation at https://docs.traefik.io/middlewares/redirectscheme/#port

### What did you expect to see?
Working middleware

### What did you see instead?
Errors in the logs suggesting that the port must be a quoted string, not a number

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
image: traefik:v2.2.1
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
Kubernetes CRD

```yaml
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-to-https
  namespace: traefik
spec:
  redirectScheme:
    scheme: https
    permanent: true
    port: 443
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
E0502 10:22:31.250816       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.3/tools/cache/reflector.go:105: Failed to list *v1alpha1.Middleware: v1alpha1.MiddlewareList.Items: []v1alpha1.Middleware: v1alpha1.Middleware.Spec: v1alpha1.MiddlewareSpec.RedirectScheme: dynamic.RedirectScheme.Port: ReadString: expects " or n, but found 4, error found in #10 byte of ...|e,"port":443,"scheme|..., bigger context ...|spec":{"redirectScheme":{"permanent":true,"port":443,"scheme":"https"}}}],"kind":"MiddlewareList","m|...
```

I had a similar error for the `permanent` option, but I'll give that one a pass since it isn't quoted in the documentation. However, I wasn't expecting the parser to be this fussy, especially since it worked fine on v2.1 and the docs didn't mention anything about the parser changing between versions.

```
E0502 10:14:27.377071       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.3/tools/cache/reflector.go:105: Failed to list *v1alpha1.Middleware: v1alpha1.MiddlewareList.Items: []v1alpha1.Middleware: v1alpha1.Middleware.Spec: v1alpha1.MiddlewareSpec.RedirectScheme: dynamic.RedirectScheme.Permanent: ReadBool: expect t or f, but found ", error found in #10 byte of ...|rmanent":"true","por|..., bigger context ...|815620dc"},"spec":{"redirectScheme":{"permanent":"true","port":443,"scheme":"https"}}}],"kind":"Midd|...
```

**Comment by traefiker** [comment]
Closed by #6769.
