### ISSUE TITLE
Kubernetes Ingress does TLS or not, but not both.

### ISSUE THREAD

**Issue by iridian-ks** [containous/traefik#6764]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

0. Already had ingress rules deployed with working http/https
1. Swapped ingress controller from NGINX to traefik

### What did you expect to see?

Mostly everything to keep working as-is. HTTP and HTTPS should continue working with the same Ingress rules.

### What did you see instead?

1. HTTP worked but TLS was not working.
2. Setting the "tls" annotation to true did the opposite. TLS worked but non-TLS didn't work
3. Cloning/duplicating the Ingress rule without the annotation gets both TLS and non-TLS to work, but requires 2 Ingress rules whereas a single one should suffice.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
/ $ traefik version
Version:      2.2.1
Codename:     chevrotin
Go version:   go1.14.2
Built:        2020-04-29T18:02:09Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

I didn't deploy any configuration as the official helm chart sets the entrypoints on the CLI by default.

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

None

**Comment by anthonyt123** [comment]
I'm having a similar issue but I can't get HTTPS working at all. I defined my tls certificate in the ingress and this actually gets picked up as it comes up when I navigate to the hostname, but I get a 404 with a valid certificate. The dashboard tells me that TLS isn't configured for that route, HTTP traffic works fine and I get through to the pod, but when I use the websecure entrypoint with my tls certificate, it's a 404 with a valid certificate. It works fine with Ingressroutes, but for my usecase I need to have an Ingress defined allowing both HTTP and HTTPS connections

**Comment by chilons** [comment]
Same issue, has been this way since v2.1. Not sure why this doesn't have much attention.

**Comment by SantoDE** [comment]
Hey all, 

yes, you're right and it's like that. Currently, an Ingress can only either be TLS or non TLS and thus, the annotation `traefik.ingress.kubernetes.io/router.tls: "true"` is used to indicate that.

However, you could use our `entryPoint` based TLS setting ```[entryPoints.<the-secure-entrypoint-name.http.tls]``` and then, you should be fine on your Ingress without the TLS annotation.

Does it make sense?

**Comment by iridian-ks** [comment]
Hi @SantoDE 

What your saying makes sense, but I'm wondering if that behavior is a bug? Setting TLS on the `http` entryPoint sounds like a serious hack.

Reading over the Ingress docs it looks like the Ingress controllers are always supposed to expose port 80 and if the `tls:` config is present then also export port 443. I could be mistaken but that's how I've interpreted it at least.

I _feel_ like it might be more appropriate to opt-out instead of opt-in? As in, if you want to turn off port 80 then you can add an annotation to do so (but more likely you'd want annotations to set HSTS headers as well as 302 redirects from 80->443).

Disclaimer: I don't want to sound like I'm bashing on Traefik. So far, it's behavior is the best as far as Ingress controllers go. NGINX for example can't do h2c. Gloo/Ambassador seem like overkill, etc.

**Comment by SantoDE** [comment]
Hi @iridian-ks,

thanks for your feedback and all good!

You would not be setting `tls` on the HTTP entrypoint. A full example would be:

`[entryPoints.websecure.http.tls]`

That indicates, that for the `websecure` entryPoint you activate `TLS` on the `http` settings. That's a little different.

However, I understand the confusion of handling. We might improve on that in the future. We're considering our options here.

As it's a question, I'll close that ticket for now and post an update later on.

**Comment by CuBiC3D** [comment]
@SantoDE sorry just throwing this into the closed issue, but did cost a lot of debug until finding this issue. This behavior is not documented as far as I can see and I expected `traefik.ingress.kubernetes.io/router.entrypoints: web, websecure` to actually route on both entry points - even the documentation says, that it's the default setting to route for every entry point without setting this.

**Comment by seeruk** [comment]
Spent a few hours looking for this one... The regular Ingress stuff is really difficult to follow right now, it's a LOT of trial and error, and this doesn't even seem to be documented even though it feels like it should be the default behaviour. I'd love to contribute to the docs, but am still sort of evaluating Traefik really for use as an Ingress Controller. At the very least I can feed back to say that the documentation could be fleshed out a LOT. Even just to put some really basic descriptions about the annotations in - the middleware one also took me finding an issue here on GitHub for answer (i.e. that the name of the middleware resource is not the same as what you need to put in the annotation, but it does follow a pretty predictable looking pattern that could be documented).
