### ISSUE TITLE
Traefik redirects .well-known endpoints for LetsEncrypt / ACME too

### ISSUE THREAD

**Issue by ekarlso** [containous/traefik#6766]
Bug

### What did you do?

After the change here was added 
[internal] Change the default priority on the router created by the redirect. (#6588 by ldez)

Installed Traefik v2.2.1 with the settings enabled for http -> https redirect and websecure enabled.

### What did you expect to see?

.well-known endpoint for Certmanager should be allowed to pass or allow a whitelist of endpoints to not be redirected

### What did you see instead?

Certmanager requests are failing

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
v2.2.1 / chart 8.1.4
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml  
 - --entryPoints.websecure.http.tls=true
    - --entrypoints.web.http.redirections.entrypoint.to=:443
    - --entrypoints.web.http.redirections.entrypoint.permanent=true
    - --providers.kubernetesingress
    - --providers.kubernetesingress.ingressendpoint.publishedservice=kube-system/traefik-v2
    - --serverstransport.insecureskipverify
    - --entryPoints.metrics.address=:8082
    - --metrics.prometheus.entryPoint=metrics
    - --metrics.prometheus
    - --accesslog
```

# Certmanager Log
```
E0505 07:41:25.544469       1 sync.go:184] cert-manager/controller/challenges "msg"="propagation check failed" "error"="wrong status code '404', expected '200'" "dnsName"="x" "resource_kind"="Challenge" "resource_name"="x" "resource_namespace"="x" "type"="http-01" 
```

# Traefik Access log
```json
{
  "ClientAddr": "10.98.16.5:60336",
  "ClientHost": "10.98.16.5",
  "ClientPort": "60336",
  "ClientUsername": "-",
  "DownstreamContentSize": 17,
  "DownstreamStatus": 301,
  "Duration": 341202,
  "OriginContentSize": 17,
  "OriginDuration": 164801,
  "OriginStatus": 301,
  "Overhead": 176401,
  "RequestAddr": "x",
  "RequestContentSize": 0,
  "RequestCount": 63,
  "RequestHost": "x",
  "RequestMethod": "GET",
  "RequestPath": "/.well-known/acme-challenge/-x",
  "RequestPort": "-",
  "RequestProtocol": "HTTP/1.1",
  "RequestScheme": "http",
  "RetryAttempts": 0,
  "RouterName": "web-to-443@internal",
  "StartLocal": "2020-05-05T07:45:23.411045332Z",
  "StartUTC": "2020-05-05T07:45:23.411045332Z",
  "entryPointName": "web",
  "level": "info",
  "msg": "",
  "time": "2020-05-05T07:45:23Z"
}
```

**Comment by ekarlso** [comment]
I guess this is a side-effect of the redirect, but it would be nice if there was a way to let the acme-challenge be forwarded anyways.

**Comment by ekarlso** [comment]
Noone that can fill in on this? We're going to run in production soon so it would be nice if it could work.

**Comment by SantoDE** [comment]
Hello @ekarlso,

we're hearing you and talking internally on that topic. I'll keep you posted 👍

**Comment by ekarlso** [comment]
This seemed like a multiple config problems at once which made this occur. Seems to work fine now sorry!
