### ISSUE TITLE
ACME provider KV storage in Traefik 2

### ISSUE THREAD

**Issue by eirikrye** [containous/traefik#6772]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Support storing Let's Encrypt certificates in KV store.

Traefik 1.7 documents the ability for configure the ACME certificateResolver to store the issued certificates in a KV storage:

https://docs.traefik.io/v1.7/configuration/acme/

```
# File or key used for certificates storage.
#
# Required
#
storage = "acme.json"
# or `storage = "traefik/acme/account"` if using KV store.
```

However, with Traefik 2, at least in its latest version (2.2.1), this feature appears to be gone:

https://github.com/containous/traefik/blob/efcaf64a43b2beb3d00cca08f3d3d5e7bb00377f/cmd/traefik/traefik.go#L280

The code appears to initialize a [LocalStore](https://github.com/containous/traefik/blob/master/pkg/provider/acme/local_store.go) for every ACME resolver, but this implementation of Store only supports saving to local files.

Has this feature been removed? It is a bit more confusing, because the latest documentation still says "file or **key**":

https://docs.traefik.io/https/acme/

```
  # File or key used for certificates storage.
  #
  # Required
  #
  storage = "acme.json"
```

**Comment by SantoDE** [comment]
Hello @eirikrye,

yes, this feature has been removed intentionally. As already stated (e.g. here: https://github.com/containous/traefik/issues/5792) having that possibility brought us a lot of issues in v1 and has therefore been dropped.

Currently, you can only store certs on file, or you could leverage tools like `cert-manager` to have them be stored in a secret.

**Comment by eirikrye** [comment]
Alright, thanks for the response. In that case, the wording  "or key" should be removed from the configuration reference. I assume this is a remnant from the documentation for the previous version.

**Comment by oniram88** [comment]
Hello @SantoDE , 
only for precision, then the only system to get traefik to work correctly in HA configuration with LE as certificate resolver is to get the EE version?

**Comment by SantoDE** [comment]
@oniram88, it depends.

As mentioned, you can do it by utilizing cert-manager to provision LE certificates rather than the internal LE System.

Or, as you guessed correctly, based on the changed architecture of EE it could get that working easily as well.
