### ISSUE TITLE
Documentation for installing traefik in kubernetes

### ISSUE THREAD

**Issue by willzhang** [containous/traefik#6776]
i can't find a docs for traefik install in kubernetes step by step。
the helm install way  too simple，It is not clear which parameters should be used。
just is helm install traefik traefik/traefik ， i'd like to config hostnetwork service type , enable dashboard , i don't know how to do that .

**Comment by willzhang** [comment]
can you add a sample directory with most yaml file for kubernetes in github repo.

**Comment by SantoDE** [comment]
Hello @willzhang,

what examples are you actually looking for?

As you said, most examples are available on the website and we can't have examples for everything.

Can you try to be a bit more precise?

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Community Forum](https://community.containo.us/).
