### ISSUE TITLE
Migrate k8s to kubernetes/client-go 

### ISSUE THREAD

**Issue by emilevauge** [containous/traefik#678]
The official k8s go client has now its own repository and seems a lot more useful than the old one (https://github.com/kubernetes/kubernetes/issues/11606): https://github.com/kubernetes/client-go
It's time to migrate :)

**Comment by ekozan** [comment]
the size of the client still ugly :/

**Comment by jsravn** [comment]
It's large, but handles all known failure cases with the apiserver. I don't think traefik's client is correct. Also, it uses protobuf now which is much more efficient.

**Comment by jsravn** [comment]
Ah I see this is a duplicate of an issue that covers many more of the problems, ignore me :)

**Comment by errm** [comment]
This should have been closed when #836 was merged
