### ISSUE TITLE
X-Forwarded-For only works for a while

### ISSUE THREAD

**Issue by diegosucaria** [containous/traefik#6787]
Hello, 

I'm using traefik in Kubernetes, with the CRD providers...

I've set up the following options on traefik deployment:
```
        - --entryPoints.http.forwardedHeaders.insecure=true 
        - --entryPoints.https.forwardedHeaders.insecure=true
        - --entryPoints.http.proxyProtocol.insecure=true 
        - --entryPoints.https.proxyProtocol.insecure=true
```
After I apply that config, I get the REAL client IP address in X-Forwarded-For and X-Real-Ip...

but after a minute or two, that values go back to be the internal lb IPs...

I've tried putting this instead, but no luck.        
```
 - --entryPoints.http.proxyProtocol.trustedIPs=127.0.0.1/32,10.48.0.0/14
 - --entryPoints.https.proxyProtocol.trustedIPs=127.0.0.1/32,10.48.0.0/14
```
Curious thing is that every time I make a change either in the `forwardedHeaders` value or the `proxyProtocol`, the REAL client IP appears for a minute....  then it goes back...

What could be the issue?  How can I provide more information to debug it?

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
