### ISSUE TITLE
Immediately after startup, many invalid TCP connections without a backend

### ISSUE THREAD

**Issue by sunliusi** [containous/traefik#6798]
Immediately after startup, the provider is not initialized, resulting in a connection without a backend.

No backend connection is meaningless, it cause program exception.

No backend connection should throw an exception.

**Comment by SuperSandro2000** [comment]
Can you please use the issue template.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Community Forum](https://community.containo.us/).
