### ISSUE TITLE
defaultEntryPoints empty using consul catalog as backend

### ISSUE THREAD

**Issue by ralberto** [containous/traefik#680]
Specifying consulCatalog as backend, defaultEntryPoints is an empty list []. According to documentation (traefik.toml), "http" should be the default entry point.

Setting: 
`defaultEntryPoints = ["http"]`
in traefik.toml explicitly, solves the "problem"!

**Comment by gjonespf** [comment]
I think I've struck this, however I'm adding entrypoints to the command line to fix the issue instead of TOML: 

`--entryPoints='Name:http Address::80' --entryPoints='Name:https Address::443 TLS:/etc/pfssl/$DOCKER_DC/ssc.crt,/etc/pfssl/$DOCKER_DC/ssc.key'
`

Will have to test it with rc3

**Comment by traefiker** [comment]
Closed by #2501.
