### ISSUE TITLE
traefik V1.7.24 : rewrite-target: test with tomcat

### ISSUE THREAD

**Issue by osaffer** [containous/traefik#6801]
Hi,

Maybe someone can help me with the following configuration.

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
    #traefik.ingress.kubernetes.io/use-regex: "true"
    traefik.ingress.kubernetes.io.rule.type: "PathPrefixStrip"
    #traefik.ingress.kubernetes.io/priority: "1"
    traefik.ingress.kubernetes.io/rewrite-target: "/"
    traefik.ingress.kubernetes.io/app-root: "/"
  name: tomcat
spec:
  rules:
  - host: myhome.com
    http:
      paths:
      - path: /tomcat 
        backend:
          serviceName: tomcat
          servicePort: 80

Thanks for your experience ;-)
With that configuration , the url http://myhome.com/tomcat/ brings me to good page.

As soon as I click for example on "Server Status for example

the url becomes : http://myhome.com/manager/status instead of http://myhome.com/tomcat/manager/status

The path tomcat/ is removed .

I tried different stuffs, without any success.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
