### ISSUE TITLE
Common Log Format customization [reopening]

### ISSUE THREAD

**Issue by scratchmex** [containous/traefik#6805]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I'm reopening a feature request left behind in a (supposed) closed issued 
_Originally posted by @TwinProduction in https://github.com/containous/traefik/issues/1079#issuecomment-450442894_:

> @dtomcej Just throwing it out there, I don't think that it's fair to call the current log customization a replacement for what was suggested in this issue.
> 
> While the elements logged are customizable (e.g. can `keep` or `drop` specific fields, as documented [here](https://docs.traefik.io/configuration/logs/#list-of-all-available-fields)), the format itself is not customizable. If I want to have something different from the [Common Log Format](https://docs.traefik.io/configuration/logs/#clf-common-log-format), it's not currently possible.
> 
> Take the following example:
> 
> ```
> 1.1.1.1 - - [28/Dec/2018:22:54:55 +0000] "GET /some/path HTTP/1.1" 302 5 [...]
> 10.1.1.1 - - [28/Dec/2018:22:55:32 +0000] "GET /some/other/path HTTP/2.0" 200 13 [...]
> ```
> 
> Because the IPs have a different length, they're not aligned.
> This might seem trivial, but this seriously hurts the readability of the logs, especially when in large quantity.
> 
> Rather than having to write a long list of each fields a user wants to have, I feel like having something like:
> 
> ```
> [accessLog]
> pattern = "${yyyy-MM-dd hh:mm:ss} ${BackendName} ${RequestMethod} ${RequestPath} ..." 
> ```
> 
> would be much more convenient, not to mention that some printf-like features for justifying text would also be a big plus.
> 
> 
> Left justification:
> 
> ```
> [accessLog]
> pattern = "${yyyy-MM-dd hh:mm:ss} ${BackendName%-15} ..." 
> ```
> 
> Would output:
> 
> ```
> 2018-12-28 12:34:56 backend         ...
> ```
> 
> Right justification:
> 
> ```
> [accessLog]
> pattern = "${yyyy-MM-dd hh:mm:ss} ${BackendName%15} ..." 
> ```
> 
> Would output:
> 
> ```
> 2018-12-28 12:34:56         backend ...
> ```

This could be really useful for readability and for example if I manage many hostnames I want the `Host` header to be included in the logs and not, for example, the `<Traefik_server_URL>`. I really hope you to reconsider as this feature could be implemented using Go string template. Thanks.

**Comment by SantoDE** [comment]
Hello @scratchmex,

thanks your interest in the project.

For the reasons mentioned in the original issue (keep / drop options, json export) we currently don't plan to make it more customizable.

Therefore, I close that issue.
