### ISSUE TITLE
Merge configuration consul catalog / consul

### ISSUE THREAD

**Issue by ralberto** [containous/traefik#681]
While configuring consulCatalog and consul as backend I think there's a problem merging configuration. Here's how to reproduce:
1. Configure `[consulCatalog]` and `[consul]` as backend
2. Make a request to an existing service (say "s1"), using the default generated rule (i.e. Host matches)
3. Add an extra rule, ex. `curl -i -H "Accept: application/json" -X PUT -d "Path:/foo" http://<consul ip>:8500/v1/kv/traefik/frontends/frontend-s1/routes/route-path/rule`
4. Make a request as in step 2, however use IP address in the requested URL, so the previous rule applies. (Request succeeds as expected)
5. Stop s1... any request fails.
6. Start s1 again. 
7. Request again as in step 4 (i.e. Using the IP address and not domain). Request now fails... :-/

Sorry if I'm not using these features in the intended way, but I'm just starting using traefik... which is a great project by the way ;)

**Comment by traefiker** [comment]
I'll close the issue due to inactivity but feel free to re-open if needed.
