### ISSUE TITLE
Parameter to toggle between TCP and HTTP router priority

### ISSUE THREAD

**Issue by dcam0050** [containous/traefik#6813]
### Do you want to request a *feature* or report a *bug*?

Feature - Would be useful to have the presence of a parameter to toggle the priority of tcp and http routers on the same entrypoint.

Status:
I have two connections on the same port.
- HTTP router for a specific subdomain on port 80 that redirects to HTTPS on port 443 
- TCP router with no TLS and host defined using HostSNI(`*`) on port 80

Current behaviour:
When the TCP router is enabled, browsing to HTTP fails due to TCP routers having higher priority than HTTP.

Given that the only HostSNI option is * for a non-TLS TCP connection, HTTP routers on the same port are never given priority.

### What did you expect to see?
I expect to see an option where the user can choose to give HTTP routers higher priority than TCP routers.

Using traefik:chevrotin docker image

**Comment by SantoDE** [comment]
Hello @dcam0050,

thanks a lot for your interest in the project. 

Sadly, we will have to close that request, as we don't see a technical way how we could implement such a behaviour.

As a HTTP connection has a TCP connection underlying, there is no way to detect "first" whether this this is "just" TCP or TCP with HTTP on top and thus, we don't see how we could implement such thing.

Therefore, I'll close that issue.
