### ISSUE TITLE
Using Pull Dog

### ISSUE THREAD

**Issue by ffMathy** [containous/traefik#6816]
I recently launched a service that I believe could be helpful in this repository. It's free to use (from a demo-cluster pool of free servers), and I need feedback. I think it could really be a win-win for us both.

https://dogger.io

It automatically spawns up a Docker-based test environment for each of your pull requests, based on a docker-compose.yml file that you choose.

I think it could be helpful in general, to test things out in production before they are merged.

What do you think? It is already used by the [Portainer project](https://github.com/portainer/portainer), and they have been very happy with it so far.

**Comment by SantoDE** [comment]
Thanks for your suggestion.

We're currently fine with how we run our CI and thus, I'll close that issue.

**Comment by ffMathy** [comment]
Thank you for looking into it. This is not a CI system though. 

It makes a test environment for every open pull request that's available, to better be able to test the feature that is being implemented 😊
