### ISSUE TITLE
Basic config setup not showing any providers

### ISSUE THREAD

**Issue by BluGeni** [containous/traefik#682]
I have just starting using the project and think it is awesome but im having some probably very beginner issues. I am using the docker image and starting it like this:

docker run -d -p 8086:8080 -p 8084:80 -v /home/me/traefik.toml:/etc/traefik/traefik.toml -v /var/run/docker.sock:/var/run/docker.sock traefik

I have enabled the web interface and that works for the health check. But I have no providers listed. I am not sure if my config is setup correctly, I have tried reading the docs and looked at examples.
Here is what I did in the config:

``` [backends]
   [backends.gitlab]
#     [backends.backend1.circuitbreaker]
#       expression = "NetworkErrorRatio() > 0.5"
#     [backends.backend1.servers.server1]
     url = "http://192.168.0.11:80"


 [frontends]
   [frontends.frontend1]
   backend = "gitlab"
     [frontends.frontend1.routes.test_1]
     rule = "Host: gitlab.mysite.com"

```

All I want to do it server the server 192.168.0.11 when host gitlab.mysite.com is requested.
I am probably missing something easy but not sure what, any help would be greatly appreciated!

**Comment by dky** [comment]
Hello, if you are using docker, and you appear to be binding to docker.sock, why not use labels? There are good config examples here:

https://docs.traefik.io/toml/

**Comment by dky** [comment]
I wasn't aware this was 12 days old, have you figured out your issue?

**Comment by PhilipSchmid** [comment]
Hi there,

I know its an old issue, but I still would like to add a solution in case of someone else runs into the same problem. I think this issue can be closed.

You are probably missing the `[file]` configuration part. Example of using external backends (which are e.g. running on a plain Ubuntu server):
```bash
root@srv1:/opt/traefik# cat traefik.toml | egrep -v '^#|^$'
 defaultEntryPoints = ["http"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
[web]
address = ":8080"
[file]
 [backends]
  [backends.rancher]
    [backends.rancher.servers.node1]
    url = "http://192.168.100.10:8080"
 [frontends]
  [frontends.rancher]
  backend = "rancher"
  passHostHeader = true
    [frontends.rancher.routes.test_1]
    rule = "Host:rancher.example.com"
```

Regards,
Philip

**Comment by jotaen** [comment]
@PhilipSchmid thanks heaps for adding this!

**Comment by otoomet** [comment]
For reference for other docker-newbies: I run into a similar problem as I had the lines
```
[docker]
  endpoint = "unix:///var/run/docker.sock"
```
commented out.  Inserting these lines fixed the issue.

**Comment by elboletaire** [comment]
Definitively that `[file]` documentation should be shown before (at least, as an example of . It's really hard to find it when it's inside the configuration section, at position > 10 in the menu... 

In the "basic" section, you can't even find the word "provider"...

Thank you so much @PhilipSchmid, without that comment I'd probably end-up reading the entire traefik documentation to find it :sweat_smile:
