### ISSUE TITLE
File Watcher for rules does not work 

### ISSUE THREAD

**Issue by ascora** [containous/traefik#683]
I started traefik like this:

```
docker service create \
     -p 80:80 -p 443:443 \
    --mount type=bind,src=/ds/rtsync/traefik/etc,dst=/etc/traefik \
    --name traefik \
    traefik:v1.0.2

```
The config lists:
```
[file]
filename = "/etc/traefik/rules.toml"
watch = true
```

This works fine and the rules.toml is located outside the container. However, if I modify it, traefik does not automatically reload the rules.

Is there a way to make traefik manually reload the rules?

**Comment by emilevauge** [comment]
@ascora which architecture are you using?

**Comment by ascora** [comment]
It's a bare metal server. I'm using the latest docker version 1.12.1 in docker swarm mode. 

I also tested it on a second server from digital ocrean (I assume that those are VMs) with the same result

**Comment by ascora** [comment]
@emilevauge As an intermediate solution: Is there a way manual to make traefik reload the file - e.g. via  a curl call?

**Comment by cheiff** [comment]
I am having the same issue. I have to stop and start the traefik container for getting configuration updated.
I have this in my traefik.toml
```
[file]
filename = "/etc/traefik/rules.toml"
watch = true
```
The file works and is found, because the rules are loaded.
It also happens that the rules do not work, give bad gateway all the time. Could that be related?
Many thanks

**Comment by ascora** [comment]
I found the reason for this. In our case, the rules.toml have been mapped to a shared drive (gluster) and it seems that Traefik uses inotofy to detect changes for the rules-file. But gluster doesn't supüport inotify yet...

**Comment by sunnysideocean** [comment]
I can confirm this with our gluster drive as well.
