### ISSUE TITLE
Apply default middlewares depending on the docker network used to connect to the services.

### ISSUE THREAD

**Issue by NokiDev** [containous/traefik#6834]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Apply middlewares configuration depending on the docker networks used to connect to the services.

For example, I have three networks public, protected and private.
What I would like is to attach default middlewares for each of the networks.
Such as private services would be available only on the LAN, protected secured with a forward auth, and public have default headers set.

The purpose of this is to allow to design services with less knowledge of the traefik deployment and configurations.
Also reduce a bit verbosity of traefik labels.

Have a good day

**Comment by SantoDE** [comment]
Hello @NokiDev,

thanks for your interest in the project.

What you could do, is have 3 different entryPoints defined into Traefik with each, having its own middlewares attached and then only issue requests to the specified entrypoint whether you're coming from the LAN or another network.

Currently, it's not possible to mix provider specific things like the docker networks in conjunction with your request.

Therefore, we'll close that issue.

**Comment by NokiDev** [comment]
Hi @SantoDE,

Thanks for the reply. If I understand correctly, you mean, adding configuration to middlewares with provider specific configs is not doable at the moment, right ?

Does using provider way to configure would help. Such as using labels like "traefik.network=public" would implicitly attach the middleware of the same name to the container configuration ?
With in the main configuration a docker provider option such as "docker.bind_middleware_to_network = true"
When parsing container label, check the main config option, then if true, add the middleware to the http service. 

Your solution is not really satisfying. Using 3 entrypoints will lead to use three different ports, and that's not really something I want to.
