### ISSUE TITLE
[TCP routing] Not working when the server is the first to send data

### ISSUE THREAD

**Issue by Totalus** [containous/traefik#6838]
### Do you want to request a *feature* or report a *bug*?

Bug / Feature (we could argue about which one it is, so leaving both)

### What did you do?

Trying to route TCP traffic to a server in a case where the server is the first to send data on the TCP stream: the client connects, upon connection the server sends data, then the client sends data.

### What did you expect to see?

The connection established, and the data sent by the server received by the client.

### What did you see instead?

The connection not established with the server. Traefik waiting for the first bytes sent by the client to see if it is TLS or not before actually forwarding the connection to the server.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.2.1
Codename:     chevrotin
Go version:   go1.14.2
Built:        2020-04-29T18:02:09Z
OS/Arch:      linux/amd64
```

### Suggestion for implementing

There should be a configuration option to tell Traefik to forward the TCP traffic of a TCP router without waiting to see data from the client. There are a few cases where we just want Traefik to forward whatever it gets without asking questions.

**Comment by SantoDE** [comment]
Hey @Totalus,

thanks a lot for your interest in the project.

The issue you're describing is the same as in #6786. If you define a TCP router which has its own entrypoint (and the SNI wildcard rule), it should work as it's then just forwarding the traffic then.

I'll open a separate issue to document that behaviur.

Thanks!

**Comment by Totalus** [comment]
Oooh, I see. So it does forward the traffic "without asking questions" only if both of those conditions are met :
1. The TCP router rule is ```rule: HostSNI(`*`)```
2. The TCP router is the only of all (TCP or HTTP) routers listening to the corresponding entrypoint

So to get that behavior, we must specify entrypoints to all of our routers to make sure no other router are listening to the TCP entrypoint we wish to forward that way.

Note that technically if the first condition mentioned above is met, on the second condition Traefik could only check if there are any other TCP router that listens to the corresponding endpoint. The HTTP routers entrypoints have no impact as the TCP routers have priority over HTTP routers and condition 1 means it will match the request. We already know the TCP router its going to handle the request even if some HTTP routers are listening on the same entrypoint.

Anyway those are kind of special cases that only a few people run into. Maybe just clearer documentation on that would be enough.
