### ISSUE TITLE
Support for renewing LetsEncrypt certificates with the same public key 

### ISSUE THREAD

**Issue by Exadra37** [containous/traefik#6855]
## Do you want to request a *feature* or report a *bug*?

Request a feature.

## What did you expect to see?

To be able to renew the LetsEncrypt certificates with the same private/public key, but currently the [docs](https://docs.traefik.io/https/acme/) don't mention any way of doing this.

So what I expect is what I think it's already possible to achieve with another LetsEncrypt client, the Certbot, at least from reading their `--help`:

```
docker run --rm -it certbot/certbot --help all
```

That shows us this option:

```
--reuse-key           When renewing, use the same private key as the existing certificate. (default: False)
```

### Why It's this feature useful?

Nowadays mobile apps are using more and more the certificate pinning approach to pin the connection to the API server, and once pinning is easy to get wrong, the recommend approach is too pin against the public key of the certificate.

As it stands now Traefik will do the amazing job of taking care of renewing the certificates for us, but this will occur with a new private/public key pair, therefore not making feasible for mobile apps to pin against the public key of the certificate for any APIs behind Traefik, because that would mean to have to release a new mobile app after each LetsEncrypt certificate renewal. This would mean that users of the mobile app would be forced to upgrade and be locked out from using the mobile app during this transition period.

### What did I tried until now?

* I have done a lot of research with Google searches and I was not able to find any reference to enable this in the Traefik `acme` configuration.
* I asked in the [forum](https://community.containo.us/t/how-to-renew-letsecncrypt-certificates-with-the-same-public-key/6177).
* I asked also on [StackOverflow](https://stackoverflow.com/questions/62006529/how-to-renew-letsecncrypt-certificates-with-the-same-public-key).

**Comment by notsureifkevin** [comment]
Hi @Exadra37 , thank you for bringing this to our attention.

The implementation of acme in Traefik (both 1.7 and 2.x), by default, passes the private key which was generated at the genesis of your certificate - so the new public certificate issued should resolve to the existing private key. I'd like to investigate further though, and I believe this may be a configuration issue with your mobile client. Let's continue this on the forum in order to come to a resolution on this.
