### ISSUE TITLE
Traefik labels can support DNS name to discovery container

### ISSUE THREAD

**Issue by myugan** [containous/traefik#6865]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Since Traefik container uses the labels to tell our load balancer what container port to direct requests to, what domains to listen and route to this container, and etc. For example if we want to add subdomain with specific container we can define it with **traefik.http.routers.myapp.rule=Host(\`myapp.example.com\`)** and it works. But, when we use different networks from Traefik let's say **custom-network**, load balancer cannot get container information into a dashboard but each container can talk to each other although not in the same network. What I want is Traefik can add a new label like **traefik.http.service.myapp=container.service.consul** so that load balancer know which container should be a direct request from the endpoint.

**Comment by SantoDE** [comment]
Hello @myugan,

thanks for your interest in the project.

I'm sorry, but I can't fully follow what you're asking for :-) What is the reference between the host rules and custom network?

Can you post a configuration example? What is the internal DNS name used for?

**Comment by myugan** [comment]
This is the references for custom network https://docs.cilium.io/en/stable/gettingstarted/docker/ so when i using this network, Traefik can't get the container with defined labels like i'm say on this request. Then to discover this things, i'm try to use Consul as service discovery and i think Traefik can integrate with Consul to reach other container by following DNS name that stored in Consul if Traefik can't reach other container by the same network.

**Comment by SantoDE** [comment]
Hey :-)

You're mixing up things a bit, with how it works. If you attach containers to a custom network, they can only be reached by other containers on this network, no matter the dns name.

A this is a question, I'll close that issue. However, please feel free to take this to the community forum https://community.containo.us/c/traefik/traefik-v2/10 if you want to further discuss this.
