### ISSUE TITLE
Support rsocket protocol

### ISSUE THREAD

**Issue by yuri-li** [containous/traefik#6866]
I have a Kubernetes cluster where I deploy Spring Boot applications that communicate using RSocket.
but,when deploying RSocket services with the Netifi broker the services would communicate via their Netifi service names and **not rely on K8s service discovery.
I'm a little dumbfounded. Can traefik get through the connection between `springboot applications`,`RSocket`,`Netifi broker`,`kubernetes`？

**Comment by notsureifkevin** [comment]
It appears that RSocket is a communication protocol that relies on [existing transports](http://rsocket.io/docs/Protocol#framing-protocol-usage) including:

* WebSocket
* TCP
* Aeron
* HTTP/2



It's possible there is a configuration or setup issue here, as we support 3 out of those 4 transports.
