### ISSUE TITLE
Having to grant list and watch access to all namespace secrets is a security risk.

### ISSUE THREAD

**Issue by mightyatom-boc** [containous/traefik#6870]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you do?

Because of security concerns raised by penetration testing, we tried to restrict Traefik's access to secrets.

Security review test findings:

Finding
The “traefik-ingress-controller” cluster role was assigned “list secrets” privileges: This privilege was only bound to this specific cluster role, and was bound to no other role.

Risk
If an attacker manages to gain access to the “traefik-ingress-controller” cluster role, they can use the privilege to list all secrets in the cluster and elevate their privileges.

Recommendation
Establish whether the “list secrets” privilege is needed for “traefik-ingress-controller", and if it is not needed then remove it.

We tried:

1. Separating the secrets that traefik needed to see into a different namespace
2. Restricting the access to certain resourcenames.
3. Restricting traefik access to list secrets

### What did you expect to see?

That traefik could only see the secrets (TLS certs and keys) that it needed.

### What did you see instead?

If we used a different namespace then traefik became unhealthy.
If we restrict get by resourcename then traefik still has list access and therefore 'get all' access to all secrets.
If we restricted list access from traefik then traefik became unhealthy.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
2.2.0
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
Kubectl version 
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.10-docker-1", GitCommit:"3ffbabe840b101d7c84263431c8a18b27785929a", GitTreeState:"clean", BuildDate:"2019-05-10T17:53:06Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```

**Comment by SantoDE** [comment]
Hello @mightyatom-boc,

you don't have to use a cluster role, in case you only want to to work with specific namespaces.

I've created you an example that you can find [here](https://github.com/SantoDE/traefik-examples/tree/master/k8s_secrets_rbac), to show you how to do it.

In my example, Traefik is only capable of listing secrets in a specific namespace.

Therefore, I'll close that issue as a question. If you have further questions, please don't hesitate to head over to the community forum (https://community.containo.us/c/traefik/traefik-v2/10) so you can receive further help.
