### ISSUE TITLE
Error when importing Traefik

### ISSUE THREAD

**Issue by pawalt** [containous/traefik#6873]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I tried to import traefik at `v2.2.1` into a separate go project so I could consume the CRD types.

### What did you expect to see?

I expected the import to be successful

### What did you see instead?

The go get failed because of a replaced dependency.

```
$ go get github.com/containous/traefik/v2@v2.2.1
go get: github.com/containous/traefik/v2@v2.2.1 requires
        github.com/abbot/go-http-auth@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```

### Traefik Version:

```
v2.2.1
```

### Potential Fix

I think doing a `go get -u  github.com/abbot/go-http-auth` on the Traefik project should do the trick by updating the dependency to a version that's actually live. It shouldn't matter what that version is since it's getting replaced anyway.

**Comment by pawalt** [comment]
This also happens with:
```
github.com/go-check/check
github.com/docker/docker
```
for the same reasons

**Comment by ldez** [comment]
Hello,

To import Traefik as a dependency, as the `replace` directives are not transitive, you have to set manually the same the `replace` directives as Traefik.

It's a Go modules limitations.

https://github.com/containous/traefik/blob/7928e6d0cd4c7751a14bea5f74124f8a3cb829c0/go.mod#L99-L109
