### ISSUE TITLE
Unable to get X-FORWARDED-* information

### ISSUE THREAD

**Issue by avinash-0-singh** [containous/traefik#6877]
We have an on-prem Kubernetes setup via _KUBEADM_ with **traefik** as an ingress controller. **Traefik** service is exposed over nodePort and we use port-forwarding to access our applications. Recently we tried to capture **X-FORWARDED-*** via the below setting for our config map but unable to capture the client IPv4's.
```
  traefik.toml: |
    # traefik.toml
    logLevel = "info"
    defaultEntryPoints = ["http", "httpn"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      compress = true
        [entryPoints.http.proxyProtocol]
        trustedIPs = ["0.0.0.0/0"]
        [entryPoints.http.forwardedHeaders]
        trustedIPs = ["0.0.0.0/0"]
      [entryPoints.httpn]
      address = ":8880"
      compress = true
        [entryPoints.httpn.proxyProtocol]
        trustedIPs = ["0.0.0.0/0"]
        [entryPoints.httpn.forwardedHeaders]
        trustedIPs = ["0.0.0.0/0"]
```

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
