### ISSUE TITLE
Unexpected 404 on some containers

### ISSUE THREAD

**Issue by gocmarek** [containous/traefik#6879]
I'm observing from time to time that on some dockers that are running NodeJS services  very various interval(in average two/three days) I'm geting response 404 ubder url where should be this NodeJS service. To make it clear the docker itself and theservce on it is runnng fine, I guess that otherwise it would be 502 error. For the moment restart of the particular docker is helping but ths is the way it shuld be. There are some other services mainly with PHP app on docker and there is no problem with them. Please help, give any hints what I'm going wrong and how to solve this case.

I'm using docker with labels - example below:

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web_net"
      - "traefik.maal.frontend.rule=Host:domain.com;PathPrefix:/"
      - "traefik.maal.frontend.redirect.regex=^https?://domain.com/(.*)"
      - "traefik.maal.frontend.redirect.replacement=https://www.domain.com/$${1}"
      - "traefik.maal.frontend.redirect.permanent=true"
      - "traefik.app.frontend.rule=Host:www.domain.com;PathPrefix:/"
      - "traefik.admin.frontend.rule=Host:www.domain.com;PathPrefix:/admin"
      - "traefik.api.frontend.rule=Host:www.domain.com;PathPrefixStrip:/api"
      - "traefik.app.port=8080"
      - "traefik.api.port=3000"
      - "traefik.admin.port=8081"
      - "traefik.tags=web"

Thanks a lot for any sugestions.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
