### ISSUE TITLE
[Question] Forward Auth, update cookies

### ISSUE THREAD

**Issue by StiviiK** [containous/traefik#6882]
This is not a Bugreport nor a Feature request more a question (I hope it's okay if I ask my question here):
A few weeks ago I started building an OIDC Forward Auth handler for Traefik, today I reached my first working version. I also wanted to implement the logic to refresh the credentials if they are expired, I save the access token and the refresh token in a cookie. Traefik forwards the request to my handler and it checks if the token is valid and if not tries to refresh it, everything up to here works fine, but then I try to update the cookie but this seems not to do anything as the cookie still has the old value.
Here's the code in question so it's easier to understand: https://github.com/StiviiK/oidc-forward-auth/blob/master/pkg/forwardauth/auth.go#L70

Maybe this is by design of Traefik or do I something wrong? Maybe somebody of you has an Idea?
Thanks!

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
