### ISSUE TITLE
Routes missing after upgrade 2.2.0 to 2.2.1

### ISSUE THREAD

**Issue by wopl** [containous/traefik#6888]
Bug

### What did you do?
Running Traefik 2.2.0 on K3S with Ingress RouteCRD.

Have a couple of HTTP Routes (7), Services (8), Middlewares (5), TCPRoutes (1).
After upgrade to 2.2.1 (latest) I see from Dashboard
HTTP Routes (2), Services (3), Middlewares (2) TCPRoutes (0)

Switching back to 2.2.0 (without any further actions) will bring back my full list.!--

### What did you expect to see?
All Routes, Services and Middlewares as before in 2.2.0

### What did you see instead?
All my defined Routes, Services and Middlewares are not shown in the dashboard anymore
With kubectl all is still there.

**Comment by notsureifkevin** [comment]
There are a few additional details which will be required to help better understand the issue you're seeing, which were requested in the issue template. Please include:

* Configuration of Traefik and the configuration of the configuration of the routes/services/middlewares which were no longer present
* Debug logs

Thank you.

**Comment by wopl** [comment]
I am not the only one. More details here.

https://community.containo.us/t/routes-missing-after-upgrade-2-2-0-to-2-2-1/6374/4

As I currently cannot do another trial to 2.2.1, I cannot provide logfiles at the moment. As said: basically all my routes, services and middlewares are gone from the UI (still available in Kubernetes). Only the most basic Traefic services survived.
Switching back to 2.2.0 (mithout modifying or applying the routes again): all o.k. as it was before upgrading. No further actions needed. Therefore it must be a UI problem only.
