### ISSUE TITLE
control Marathon CB/LB schemes via labels

### ISSUE THREAD

**Issue by BrianHicks** [containous/traefik#69]
Proposal:

What if one could control Marathon circuit breaker (CB) and load balancer (LB) schemes with labels? Something like this:

``` json
{
    "traefik.circuitbreaker": "NetworkErrorRatio() < 0.5",
    "traefik.loadbalancer": "wrr"
}
```

This, however, would mean that we couldn't combine apps to do blue/green or canary deployments. So, here are some proposals for how to get around that issue:
## meta-information on the app

We could have another label on the app that controlled grouping, (e.g. `traefik.backend`.) When set to the same value, apps would load balance together. Each instance of the app could use the circuit breaker defined locally, which leaves load balancing information. 

Several approaches could work for load balancing information:
1. use the first one Traefik grabs. This means that the LB used could be a function of Marathon's message delivery order, so it's not great.
2. enforce all the apps matching `traefik.loadbalancer` labels. This could work, but could cause unavailability/incorrect behavior if the operator doesn't understand this constraint.
3. have a higher-order key on the app (e.g. `{"traefik.multiloadbalancer": "wrr"}`.) Ties would be broken on an arbitrary metric (newest app makes sense to me, but that could be configured on the config backend level.)

I like a combo of 3 and 2, personally: prefer `traefik.multiloadbalancer` then `traefik.loadbalancer`, and resolve inconsistencies using a configurable tiebreaker. We could use the same approach for CBs, if I'm wrong that you could potentially use different types per instance.
## externally stored information

We could have a higher-level provider that combines an automatic service generator with a K/V store. So, for example, one could use Marathon and Consul together. The information about instances would come from the automatic provider, and the information on which to include would come from the K/V store.

As an example, say you have two apps (ID `/app/1` and `/app/2`) in Marathon. They don't know about each other, but there's a key in Consul `/traefik/multi/marathon/instances` whose value is `/app/1,/app/2`. That creates a backend which balances between the backends of the two apps. The apps then have their individual CB/LB configurations respected at that level.

---

I feel that either approach could be good, but the external approach requires a fair bit more setup (despite having a clear single source of truth.)

**Comment by EmileVauge** [comment]
Thank you @BrianHicks ! Great proposal! Ping @vdemeester

**Comment by anners** [comment]
+1 I would love to see something like this to support blue/green deploys.

**Comment by manishrajkarnikar** [comment]
+1

**Comment by BrianHicks** [comment]
For anyone who wants this now: set `traefik.frontend.rule` and `traefik.backend` to the same value across apps. Then you can mess with the scale and weight to shape your traffic how you like. General formula: multiply each app's scale by it's `traefik.weight` (default 1). The percentage of traffic to that app will be the app's score divided by the total of all scores for apps where the frontend and backend is the same.

**Comment by kbroughton** [comment]
+1

**Comment by timoreimann** [comment]
This seems possible now [according to the docs](https://docs.traefik.io/toml/#marathon-backend).

Any objections to closing the issue?

**Comment by timoreimann** [comment]
@BrianHicks ^

**Comment by BrianHicks** [comment]
Up to you! I don't use Marathon or Mesos anymore so I can't confirm. :)

**Comment by timoreimann** [comment]
@BrianHicks gotcha, thanks for the heads up!

Closing.
