### ISSUE TITLE
YAML identation error

### ISSUE THREAD

**Issue by javierlga** [containous/traefik#6914]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Restarted traefik pods.

### What did you expect to see?

No error messages.

### What did you see instead?

`yaml: line 5: could not find expected ':'` 

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
1.7.12
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```
toml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
data:
  traefik.toml: |
    # traefik.toml
    defaultEntryPoints = ["https","http"]
    [entryPoints]
      [entryPoints.http]
        address = ":80"
      
      [entryPoints.https]
        address = ":443"
        [entryPoints.https.tls]
          sniStrict = true
          minVersion = "VersionTLS12"
          cipherSuites = [
            "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
            "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
            "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
            "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
            "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
            "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
          ]
      [entryPoints.traefik]
        address = ":8080"
      [entryPoints.ping]
        address = ":8082"
    [kubernetes]
    [ping]
    entryPoint = "ping"
    [api]
    entryPoint = "traefik"
```
```
Arguments
---
spec:
      containers:
      - name: traefik-ingress
        args:
        - --api
        - --kubernetes
        - --logLevel=INFO
        - --configfile=/config/traefik.toml
        - --kubernetes.ingressclass=stage
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
time="2020-06-11T23:21:32Z" level=error msg="yaml: line 5: could not find expected ':'"
time="2020-06-11T23:21:32Z" level=error msg="yaml: line 5: could not find expected ':'"
time="2020-06-11T23:21:32Z" level=error msg="yaml: line 5: could not find expected ':'"
time="2020-06-11T23:21:32Z" level=error msg="yaml: line 5: could not find expected ':'"
time="2020-06-11T23:21:32Z" level=error msg="yaml: line 5: could not find expected ':'"
time="2020-06-11T23:21:32Z" level=error msg="yaml: line 5: could not find expected ':'"
time="2020-06-11T23:21:32Z" level=error msg="yaml: line 5: could not find expected ':'"
time="2020-06-11T23:21:33Z" level=error msg="yaml: line 5: could not find expected ':'"
time="2020-06-11T23:21:33Z" level=error msg="yaml: line 5: could not find expected ':'"
time="2020-06-11T23:21:33Z" level=error msg="yaml: line 5: could not find expected ':'"
time="2020-06-11T23:21:33Z" level=error msg="yaml: line 5: could not find expected ':'"
```

I'm not exactly sure why traefik is complaining about YAML indentation, but the pods are giving a lot of error messages, all the Kubernetes files are correct and AFAIK, traefik doesn't use any YAML syntax file.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
