### ISSUE TITLE
Unknown entrypoint https for ACME configuration when enabling consul

### ISSUE THREAD

**Issue by BechirLandolsi** [containous/traefik#6915]
hello, I want to deploy the helm chart of traefik 1.7, when enabling the consul configuration I got the error unknown entrypoint https for ACME configuration with the chart version 1.87.1
![Screenshot from 2020-06-12 17-01-15](https://user-images.githubusercontent.com/29604359/84522374-62db4880-acce-11ea-9e3e-0fe2c829bdab.png)

![image_2020_06_12T14_03_36_286Z](https://user-images.githubusercontent.com/29604359/84522417-7edeea00-acce-11ea-878d-5bc77eb724cb.png)

Any help please !!

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
