### ISSUE TITLE
Routes and services entry are missing when call traefik api directly

### ISSUE THREAD

**Issue by sachina787** [containous/traefik#6917]
### Do you want to request a *feature* or report a *bug*?
bug

Bug

### What did you do?
Created 100 plus containers with the traefik labels mentioning services and there routers

### What did you expect to see?
when I call traefik API http://traefik.private.xyz/api/http/services and http://traefik.private.xyz/api/http/routers both should return an array of json object as a response with all the routes and services entry.

### What did you see instead?
for 100 plus container I am not receiving the response more than 100. Both routers and services entries are missing for some containers

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
2.2.1
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# Docker configuration backend
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.docker-stack-name.private.xyz`)"

entryPoints:
  default:
    address: ":80"
  metrics:
    address: ":8082"

accessLog:
  format: json

log:
  filePath: "/home/traefik.log"
  format: json
  level: DEBUG
  
# API and dashboard configuration
api:
  insecure: true

metrics:
  prometheus:
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0
    entryPoint: metrics
    addEntryPointsLabels: true
    addServicesLabels: true
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
not getting any error in logs
```

**Comment by notsureifkevin** [comment]
Greetings, the default number of responses per each request is `100` (https://github.com/containous/traefik/blob/v2.2.1/pkg/api/criterion.go#L11-L14)

This can be increased, or rather, consider paginating through them. The api returns a 'nextPage` in the response. Here is a test case on how you might accomplish this. 

https://github.com/containous/traefik/blob/master/pkg/api/handler_http_test.go#L350

**Comment by sachina787** [comment]
Thanks @notsureifkevin  this was really helpful. We can close this ticket now.
