### ISSUE TITLE
Rate limit options for HTTPS behind network load-balancers

### ISSUE THREAD

**Issue by Sarke** [containous/traefik#6927]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

In addition to the IP and header options for the RateLimit middleware, I would like a way rate limit connecting clients while behind a load-balancer or proxy, where it's not possible to see the clients IP.

I'm thinking would there be a way of using the connecting client's public key or signature to identify them as unique?  I don't know enough about the workings of TLS to know if this is doable, or if anything unique lives on beyond each HTTP request.

Our situation is that the HTTPS connection is terminated by Traefik, and all it sees is the IP of the load-balancer.

**Comment by notsureifkevin** [comment]
@Sarke most modern load balancers should support Proxy Protocol, which can be enabled when configuring your entrypoint in Traefik. When you configure the rate limiter for services assigned to that entrypoint it will, by default, use the actual client IP for stickiness criteria as long as the Proxy Protocol headers were sent by your upstream proxy.

https://docs.traefik.io/routing/entrypoints/#proxyprotocol

If you have any additional questions or trouble configuring this, please create a thread on our [community forums](https://community.containo.us) and feel free to ping me there. Thank you!

**Comment by Sarke** [comment]
Thank you for your suggestion, but the Rackspace load balancer doesn't support Proxy Protocol.

However, as this problem appears to be solved by using newer tech I doubt it will be implemented, so closing.
