### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by Hedgehogues** [containous/traefik#6933]
Hello. I am confused. I study the traefik. It is very strange for me that this tool uses api call of docker. Why you don't use environment variables instead?

**Comment by SantoDE** [comment]
Hello @Hedgehogues,

thanks a lot for your interest in the project.

Not sure I understand your issue tough. We use the Docker API to retrieve information about the containers, so I don't really see how this work in conjunction with ENV variables?

Therefore, I'll be closing that issue.

Please do not hesitate to head over to the community forum https://community.containo.us/c/traefik/traefik-v2/10 and share your thoughts about it.
