### ISSUE TITLE
Add retry methods configuration

### ISSUE THREAD

**Issue by nkonev** [containous/traefik#6942]
Feature

### What did you expect to see?

I would like to see the methods parameter in the retry middleware configuration.

Purpose of it is setting which of HTTP methods traefik should to retry, same as in methods in [Spring Cloud Gateway](https://cloud.spring.io/spring-cloud-gateway/reference/html/#the-retry-gatewayfilter-factory).

### Motivation

I want to have ability to enable retries for several methods, not for all, only for GET for example, but skip it for POST ones.

Let's consider we have game application. It has in-play payment system. I don't want to retry any money charges(POST, PUT for example), but I still want to retry all non-modifying GET queries.

PR https://github.com/containous/traefik/pull/6941

**Comment by notsureifkevin** [comment]
related issues: 

https://github.com/containous/traefik/issues/5282
https://github.com/containous/traefik/issues/4578
