### ISSUE TITLE
Add iOS homescreen icon

### ISSUE THREAD

**Issue by Heisenberg74** [containous/traefik#6945]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?
I expect to see a very beautiful (official traefik logo) icon when adding my traefik portal to my iOS homescreen.

### The current behavior:
Right now, when bookmarking my traefik to my iOS device, ugly icon is generated by my device and it is difficult to find the shortcut on the springboard.

![traefik](https://user-images.githubusercontent.com/8171300/85221165-f5a47300-b3b1-11ea-8afa-d585eaeefdda.jpg)

### Suggestion
Add the following line of code in the HTML template:

`<link rel="apple-touch-icon" href="touch-icon-iphone.png">`
`<link rel="apple-touch-icon" sizes="152x152" href="touch-icon-ipad.png">`
`<link rel="apple-touch-icon" sizes="180x180" href="touch-icon-iphone-retina.png">`
`<link rel="apple-touch-icon" sizes="167x167" href="touch-icon-ipad-retina.png">`

**Comment by Heisenberg74** [comment]
The PR has been approved and the result is nice. Issue can be closed.

**Comment by ldez** [comment]
Closed by #6946
