### ISSUE TITLE
healthcheck activated but fails

### ISSUE THREAD

**Issue by grafra** [containous/traefik#6949]
### Do you want to request a *feature* or report a *bug*?
Bug

### What did you do?
I tried to upgrade my traefik to version 2.x setup and tried to enable and use the healthcheck. 
I follwed the instructions to enable the ping module. 
My stack looked like this

``` 
# stack traefik
# use docker stack deploy to start a service running traefik
#
version: '3.7'

services:  
  router:
    
    image: traefik:v2.2
    # perform the static configuration in the stack file
    # configs:
    #  - source: traefik.toml
    #    target: /etc/traefik/traefik.toml
    command:
      - "--log.level=DEBUG"
      # docker healthchecks
      - "--ping=true"
      # docker api & dashboard
      - "--api=true"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      # enable prometheus monitoring 
      - "--metrics.prometheus=true"
      # - "--metrics.prometheus.buckets=0.100000, 0.300000, 1.200000, 5.000000"
      # enable the docker provider 
      # but containers must be exposed explicitly 
      - "--providers.docker=true"
      # - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedbydefault=false"
      # file provider 
      # watch for configuration files in 
      - "--providers.file.directory=/opt/traefik/config"
      - "--providers.file.watch=true"

    # export the following ports 
    ports:
       - "80:80"
       - "443:443"   
       - "8800:8080"

    deploy:
      replicas: 1

    volumes:
      #  access  docker API via unix sockets 
      - /var/run/docker.sock:/var/run/docker.sock
      #  mount the certificates on the docker host
      - /etc/pki/tls:/etc/pki/tls:ro
      # mount the conifiguration files
      - ./config:/opt/docker/config:ro


    # use the built in health check command of taefik
    healthcheck:
      test: [ "CMD", "traefik","healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
``` 

### What did you expect to see?

I excepted that the service would start and the service would become healthy.
### What did you see instead?

The healthcheck failed wirt the message 
``` 
Error calling healthcheck: please enable `ping` to use health check
```
However without the healthcheck lines the container starts ok and calling the ping endpoint in the browser return an 200 and an OK. 

If I login into the container I can  perform an ping bur not an traefik healthcheck
```
/ # wget localhost:8080/ping
Connecting to localhost:8080 (127.0.0.1:8080)
saving to 'ping'
ping                 100% |*************************************************************************************|     2  0:00:00 ETA
'ping' saved
/ # cat ping
OK/ 
# traefik healthcheck
Error calling healthcheck: please enable `ping` to use health check
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

Version:      2.2.1
Codename:     chevrotin
Go version:   go1.14.2
Built:        2020-04-29T18:02:09Z
OS/Arch:      linux/amd64

```
(paste your output here)
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# (paste your configuration here)
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```

**Comment by SantoDE** [comment]
Hello @grafra,

as the error message says: you need to enable the `ping` in order for the healthcheck command to run.

If you have more issues configuring your Traefik instance, please head over to the community forum https://community.containo.us/c/traefik/traefik-v2/10 and ask your questions there :-)

**Comment by grafra** [comment]
I think I have had the ping enabled.  
Is this not what the option  --api.ping=true  is for.

Also as I said the ping worked when I access it via curl.
But not via the command traefik healthcheck
