### ISSUE TITLE
Log message "Skipping same configuration for provider docker" once every hour instead of 5 times each second

### ISSUE THREAD

**Issue by RolandvdH** [containous/traefik#6955]
Feature/Change in behaviour

### What did you expect to see?
One/no message about Skipping same configuration for provider docker instead of thousands.

I've read multiple inquiries about this, which have been declined (#5718, #5693) based on the "informational" nature of the message.

Whether this is an INFO or a DEBUG message may be a subjective debate, but printing this message 4-5 times every second, floods the logfile, which very quickly looses any informational purpose.

I've resorted to putting the loglevel to WARN as suggested, but with this change I loose some rather informational messages, like the status of my letsencrypt process (which I care about).

So, if yo really feel this is an INFO message, great, but could you please add some more logic to it, like printing it once every hour (or something along this line, even once every minute would go a long way). If you feel the abundance is of importance, maybe add a counter how many of these skips have occurred in the last timeframe. 

NB might I add that, in the docker context, it's "hard" to change the configuration inside on a running container (as in: not customary). So in my particular situation/provider docker, this message is less informational than in other setups. To go short: leaving this message out if the provider is docker, would tickle my fancy just the same ;-) (and I would gladly issue a PR for this)

**Comment by ldez** [comment]
Hello,

if the log appears 4 to 5 times per second in a Docker context, I think you have a problem because, in a Docker context, the configuration is refreshed only when a new "container" event is sent by Docker.
So this means that you have one or more containers that start or restart 4-5 times per second.

**Comment by RolandvdH** [comment]
Hi,

To be honest, upon closer inspection the log message appear every 15 seconds/4 times per minute (my bad).

Let's hope not. Docker reports the traefik container running for 4 weeks. Both the container and the service (we're running in swarm mode) are in Running/Up state with no errors. And the application is useable/running fine. Still the traefik log is hammered with messages.

The service:
ID                  NAME                  IMAGE               NODE                DESIRED STATE       CURRENT STATE           ERROR                              PORTS
fpnnt9cyuwmp        proxy_traefik.1       traefik:alpine      localhost           Running             Running 4 weeks ago                                        *:8080->8080/tcp,*:443->443/tcp,*:80->80/tcp

The container:
2c1d20b65e06        traefik:alpine                                          "/entrypoint.sh trae…"   4 weeks ago         Up 4 weeks          0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:8080->8080/tcp   proxy_traefik.1.fpnnt9cyuwmpqtbxkydz0h2o1

The log (just a tiny part of it ;-)
time="2020-06-24T13:04:03Z" level=info msg="Skipping same configuration for provider docker"
time="2020-06-24T13:04:18Z" level=info msg="Skipping same configuration for provider docker"
time="2020-06-24T13:04:33Z" level=info msg="Skipping same configuration for provider docker"
time="2020-06-24T13:04:48Z" level=info msg="Skipping same configuration for provider docker"
time="2020-06-24T13:05:03Z" level=info msg="Skipping same configuration for provider docker"
time="2020-06-24T13:05:18Z" level=info msg="Skipping same configuration for provider docker"
time="2020-06-24T13:05:33Z" level=info msg="Skipping same configuration for provider docker"
time="2020-06-24T13:05:48Z" level=info msg="Skipping same configuration for provider docker"
time="2020-06-24T13:06:03Z" level=info msg="Skipping same configuration for provider docker"
time="2020-06-24T13:06:18Z" level=info msg="Skipping same configuration for provider docker"
time="2020-06-24T13:06:33Z" level=info msg="Skipping same configuration for provider docker"
time="2020-06-24T13:06:48Z" level=info msg="Skipping same configuration for provider docker"
time="2020-06-24T13:07:03Z" level=info msg="Skipping same configuration for provider docker"
time="2020-06-24T13:07:18Z" level=info msg="Skipping same configuration for provider docker"
time="2020-06-24T13:07:33Z" level=info msg="Skipping same configuration for provider docker"
time="2020-06-24T13:07:48Z" level=info msg="Skipping same configuration for provider docker"
time="2020-06-24T13:08:03Z" level=info msg="Skipping same configuration for provider docker"
time="2020-06-24T13:08:18Z" level=info msg="Skipping same configuration for provider docker"
time="2020-06-24T13:08:33Z" level=info msg="Skipping same configuration for provider docker"
time="2020-06-24T13:08:48Z" level=info msg="Skipping same configuration for provider docker"
time="2020-06-24T13:09:03Z" level=info msg="Skipping same configuration for provider docker"
time="2020-06-24T13:09:18Z" level=info msg="Skipping same configuration for provider docker"
time="2020-06-24T13:09:33Z" level=info msg="Skipping same configuration for provider docker"
time="2020-06-24T13:09:48Z" level=info msg="Skipping same configuration for provider docker"

**Comment by ldez** [comment]
The swarm mode doesn't listen event (due a Docker Swarm API issue), in this case the provider call every 15s the Docker Swarm API to get the information.

You can change the refresh time: https://docs.traefik.io/v2.2/providers/docker/#swarmmoderefreshseconds

**Comment by RolandvdH** [comment]
You are my hero :-) Thanks for a great solution!
