### ISSUE TITLE
Documentation for Dashboard is wrong

### ISSUE THREAD

**Issue by felixsanz** [containous/traefik#6958]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Documentation is wrong

### What did you expect to see?

This page: https://docs.traefik.io/operations/dashboard/#secure-mode
Says:

```
# Dashboard
#
# Optional
# Default: true
#
--api.dashboard=true
```

If I omit the parameter, `Default: true` should take place. But that's not true. Default value is actually `false`.

### What did you see instead?

```
time="2020-06-24T15:25:19Z" level=error msg="api is not enabled" entryPointName=https routerName=dashboard@docker
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

Not relavant

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Not relavant

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

Not relavant

**Comment by ldez** [comment]
The default value of `--api.dashboard` is true.

**Comment by felixsanz** [comment]
@ldez that doesn't make sense if you still need `--api`. Documentation is confusing.

In fact as a new traefik user i can tell you that documentation is a torture in general. Please, accept feedback and start improving it. There are many people with issues just because documentation is so confusing

**Comment by ldez** [comment]
We always accept constructive feedback, and we always appreciate constructive feedback.

The default value of `--api.dashboard` is `true`, and you have to `--api` to enable the api and dashboard.
The dashboard require the api, so `dashboard` is a sub-option of `api`.

**Comment by felixsanz** [comment]
Yeah, now i get it, but here is another example:

If you just set `--api.dashboard=false` you are enabling `api` and disabling `dashboard`? that is so confusing.

Plus if `--api.dashboard` is `true` but default, why that doesn't work? Documentation should state that you still need to enable `api`. Is not explained and not obvious

**Comment by ldez** [comment]
> Plus if --api.dashboard is true but default, why that doesn't work? Documentation should state that you still need to enable api. Is not explained and not obvious

The default value of `dashboard` in `--api.dashboard` is true, but this default value is applied only if you enable the API.

The dashboard require the api:
- the dashboard need that the api is enable.
- if the api is not enable, the dashboard is not enable also.
- if the api is enable, the dashboard is enable also.

We don't activate the api by default because of security reasons.

**Comment by felixsanz** [comment]
Then update documentation with this useful info, because now lacks of it and it's really confusing
