### ISSUE TITLE
Traefik rate limiting when header specified in extractorFunc is not sent in request headers

### ISSUE THREAD

**Issue by dylanbfox** [containous/traefik#6965]
### Do you want to request a *feature* or report a *bug*?

Bug

Bug

### What did you do?

I set a rate limit rule like this in my docker compose file:

```
traefik.frontend.rateLimit.extractorFunc=request.header.My-Custom-Header
```

Some of my clients are _not_ sending this header, but are still getting rate limited.

### What did you expect to see?

No rate limiting to happen if the header is not found in the request - or at least docs around what happens in this case.

### What did you see instead?

Traefik is rate limiting requests that are sent without the header I defined in the rate limit rule above, but it is unclear what traefik is using to rate limit if not the header I specified.

### Output of `traefik version`: (_What version of Traefik are you using?_)

`traefik:v1.7-alpine` docker image

```
traefik:v1.7-alpine
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Docker compose, using the `traefik:v1.7-alpine` image

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
