### ISSUE TITLE
Ability to throttle a service calling another third party or cloud service

### ISSUE THREAD

**Issue by alouane** [containous/traefik#6966]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Ability to throttle a service calling another third party or cloud service

For example: Throttling a service from exceeding AWS SES (emails) rate limits

Of course, it can be achieved at the service level, but I believe Traefik has the right tools to make it happen in the routing edge

What do you think?

**Comment by mpl** [comment]
Sorry we don't get it. I understand that you're asking if Traefik could throttle the outgoing traffic of your backend service when it's sending requests to the outside world? If yes, then you misunderstood what Traefik does: it is a reverse-proxy, so its role is to handle the incoming traffic from the outside world that is going to your backend service, not the other way around.

**Comment by alouane** [comment]
Ok thanks for the clarification

I guess the only way around is backoff strategies at the service level, or maybe wrapping aws ses service with an internal rate limiter. Overall it's a design issue

Thanks again for the support @mpl I appreciate it :)
