### ISSUE TITLE
[Kubernetes] URL rewrite based on User Agent 

### ISSUE THREAD

**Issue by osamamaruf** [containous/traefik#6974]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?
Currently in traefik rewrite the url to point to a different path based on User Agent. 

To give an idea let me show what I mean by an example in nginx.  One can do the following;

```
# User Agent Detection
	map $http_user_agent $ua_target {
        default 'web';    
        ~*(iPhone|iPod|android|blackberry) 'mobile';
	}
```
and then

```
location /cdn {	
		if ($ua_target = 'mobile') {
			rewrite ^(.*)cdn/es5/src/assets(.*)$ $1cdn/es5-mobile/src/mobile-assets$2;
		}			
		proxy_pass	http://docker-cdn;
    }
```

**Comment by SantoDE** [comment]
Hello @osamamaruf,

thanks for your interest in the project.

This should be possible with the combination with the combination of 2 routers. 1 router, could check for the `user-agent` header and have a middleware attached which redirects to the desired endpoint.

The second router, could only match for the the path `/cdn` and then proxy to your desired service directly.

Does it make sense?

As this is a configuration question, I'll close that issue. If you need more help on configuration, please head over to tour community forum https://community.containo.us/c/traefik/traefik-v2/10 and ask your question there.
