### ISSUE TITLE
[documentation/feature] Consul/etcd support atomic multiple key changes now

### ISSUE THREAD

**Issue by strarsis** [containous/traefik#698]
According to current [traefik documentation](https://docs.traefik.io/toml/#atomic-configuration-changes), Consul and etcd backends 
do not support updating multiple keys atomically.

However, the referenced issues for [consul](https://github.com/hashicorp/consul/issues/886) and [etcd](https://github.com/coreos/etcd/issues/860) have been closed.
Wouldn't this also mean that this feature can be deprecated now 
(maybe still useful for older consul and etcd servers)?

**Comment by emilevauge** [comment]
@strarsis We use https://github.com/docker/libkv to abstract kv stores connections. Until this feature is supported in libkv, we still need to use the hacky way http://docs.traefik.io/toml/#atomic-configuration-changes.

**Comment by strarsis** [comment]
So an issue is left in libkv and not in Consul or etcd.

**Comment by Leon99** [comment]
It's been a while and it looks like libkv supports it now:
![image](https://user-images.githubusercontent.com/6840381/52928710-53c3df00-3395-11e9-878c-d03a30cdc386.png)
It's possible that I'm looking at a wrong thing though, @emilevauge could you possibly link libkv issue re. Consul support so we could track that?
