### ISSUE TITLE
Bind services to multiple networks with network specific rules

### ISSUE THREAD

**Issue by ptr727** [containous/traefik#6991]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

For reference see my [forum question](https://community.containo.us/t/binding-to-specific-network-when-using-multiple-networks/6731).

I would like the ability to bind multiple ingress networks to traefik.
I would like to create rules that are network specific.
I would like to be able to run a single traefik instance that can distinguish between LAN traffic and WAN traffic.

E.g.
Bind Traefik to two networks, a local network and a macvlan network with static IP, container has ports exposed to host.
Internet -> Router -> Port Forward -> macvlan static IP network -> Traefik -> Always Auth -> Services
LAN -> host network -> exposed port -> No Auth required -> Services

Reason for using a macvlan with a static IP for port forwarding is to isolate internet traffic from the host, i.e. I do not want to forward traffic to the server running docker, I want to forward it to the specific IP dedicated to routing internet traffic. This allows me to move the IP to whatever container needs to handle the traffic, without needing to reconfigure the router. It also allows me to use ports that may be in use by the host, e.g. my unifi router breaks when doing hairpin NAT on different ports (443 to 443 works, 443 to 9443 works external but internal hairpin NAT), so external 443 must be routed to internal 443, that means no 443 on the docker server which is not always possible.

In my testing it seems that when a local bridge network and a macvlan network is bound to the traefik container, the traefik server is only attached to the macvlan IP. 
I am really not sure if this is a docker network problem, or if traefik is not binding to macvlan and the the host mapped ports?
E.g. I can access the dashboard over `http://192.168.1.10:8080` but no over `http://serverhostname:8080`.
```yaml
networks:
      - name: "{{ docker_public_network }}"
        ipv4_address: 192.168.1.10
      - name: "{{ docker_local_network }}"
    published_ports:
      - 80:80
      - 443:443
      - 8080:8080
```

I would like to create a rule that invokes auth middleware based on the ingress network, i.e. any traffic coming from the internet must auth, local traffic does not need ot auth.

If it is not possible to bind to multiple networks, and have network specific rules, I have to run two instances of trafik, one bound the macvlan network and one bound to the host network. This is less desirable.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by ptr727** [comment]
Hmm, I already asked in the forum.
If this is possible, please advise, if not possible, then it is a feature request.
