### ISSUE TITLE
Ability to override default middlewares when defining a router

### ISSUE THREAD

**Issue by disklosr** [containous/traefik#6999]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Ability to override default middlewares when defining a router.

I currently have a default authentication middleware, declared as part of static config, so that all my services are secured behind a login screen by default. Sometimes, I'd like to make a service publicly available without auth. Currently, there's no way of achieving this, except by removing the default middleware and manually adding it to all services except those public ones. This solution is not only tedious, but it could lead to security issues caused by misconfiguration due to the absence of a default auth middleware.

I didn't find anything in the docs about the ability to override default middlewares in router definition. I tried overriding, but it seems the behavior of Traefik is to merge the router middlewares with the default ones.

**Comment by redge76** [comment]
same request here : https://github.com/containous/traefik/issues/5630#issuecomment-608366749

**Comment by disklosr** [comment]
The old issue was originally about default configs which were implemented in v2.2, this one is about overriding default values.

I'm not familiar with how the maintainers prefer to manage issues, but I guess this one is sufficiently different from the old one and it deserves to be tracked separately.
