### ISSUE TITLE
Global InsecureSkipVerify does not work

### ISSUE THREAD

**Issue by mattymo** [containous/traefik#700]
Forwarding https to my backend seems to fail:
```WARN[2016-09-27T11:33:53Z] Error forwarding to https://node2:443, err: x509: certificate signed by unknown authority 
```
I tried adding InsecureSkipVerify = true to the global section in traefik.toml, but it still won't validate my backend. I'm using 1.0.3 release binary.

**Comment by emilevauge** [comment]
This option is not available in 1.0.x, it will be in 1.0, please refer to [this issue](https://github.com/containous/traefik/issues/667) and this [PR](https://github.com/containous/traefik/pull/557).

**Comment by ralphtheninja** [comment]
@emilevauge Wait what do you mean not available in 1.0.x but in 1.0?

**Comment by errm** [comment]
@ralphtheninja  This option: `InsecureSkipVerify` does not work in the current 1.0.x release, but will work as expected in 1.1.0 when it is released...

I think that 1.0 was a typo by @emilevauge ...

**Comment by ralphtheninja** [comment]
Thanks! ;)

**Comment by emilevauge** [comment]
Indeed, v1.1, not v1.0 ^^ My bad.
