### ISSUE TITLE
Geo block traffic

### ISSUE THREAD

**Issue by Kwinnieprince** [containous/traefik#7004]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

As far as I can tell it is only possible to whitelist and blacklist IP ranges in Traefik. It is possible to block other countries using this method but it is really cumbersome to do it using a whitelist middleware.

This is handy when you want to expose a service to a limited set of people or a service that is only relevant in that specific country.

Is this a viable option?

**Comment by jbdoumenjou** [comment]
Close in favor of #4026
