### ISSUE TITLE
Backend has too many servers configured, every second request fails

### ISSUE THREAD

**Issue by AndreKR** [containous/traefik#7009]
### Do you want to request a *feature* or report a *bug*?

Bug.

### What did you do?

I have an Ingress configured with a single backend service which points to a single pod:

```yaml
[...]
spec:
  rules:
    - host: [REDACTED]
      http:
        paths:
          - path: /issue-20-alternatives-a/
            backend:
              serviceName: review-app-issue-20-alternatives-a
              servicePort: 80
```

```text
# kubectl describe ingress review-app-issue-20-alternatives-a
Name:             review-app-issue-20-alternatives-a
Address:          [REDACTED]
Default backend:  default-http-backend:80 (<none>)
Rules:
  Host                                          Path  Backends
  ----                                          ----  --------
  [REDACTED]
                                                /issue-20-alternatives-a/   review-app-issue-20-alternatives-a:80 (10.42.0.221:80)
```

```text
# kubectl describe service review-app-issue-20-alternatives-a
[...]
Selector:          app=review-app-issue-20-alternatives-a
Type:              ClusterIP
IP:                10.43.187.63
Port:              <unset>  80/TCP
TargetPort:        80/TCP
Endpoints:         10.42.0.221:80
Session Affinity:  None
Events:            <none>
```

### What did you expect to see?
Normal operation, all requests served successfully

### What did you see instead?
Every second request fails with "bad gateway".

I'm guessing it has to do with the fact that in the Traefik Dashboard there are two Servers listed:

![image](https://user-images.githubusercontent.com/1188538/86812456-5654d080-c07f-11ea-9f40-c145afa7f9e1.png)

`10.42.0.221:80` is from the Kubernetes Service but I don't know where `10.42.0.222:80` comes from or how to get rid of it.

### Output of `traefik version`: (_What version of Traefik are you using?_)

The Helm Chart that comes with k3s.

Dashboard shows: V1.7.19 / MAROILLES

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

k3s  
https://k3s.io/  
https://github.com/rancher/k3s

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

Currently it seems my log level is pretty high because the log doesn't say much:

```json
{"level":"info","msg":"Server configuration reloaded on :8080","time":"2020-07-07T12:55:31Z"}
{"level":"info","msg":"Server configuration reloaded on :9100","time":"2020-07-07T12:55:31Z"}
{"level":"info","msg":"Server configuration reloaded on :80","time":"2020-07-07T12:55:31Z"}
{"level":"info","msg":"Server configuration reloaded on :443","time":"2020-07-07T12:55:31Z"}
{"level":"info","msg":"Skipping same configuration for provider kubernetes","time":"2020-07-07T12:55:31Z"}
{"level":"info","msg":"Server configuration reloaded on :8080","time":"2020-07-07T12:55:33Z"}
{"level":"info","msg":"Server configuration reloaded on :9100","time":"2020-07-07T12:55:33Z"}
{"level":"info","msg":"Server configuration reloaded on :80","time":"2020-07-07T12:55:33Z"}
{"level":"info","msg":"Server configuration reloaded on :443","time":"2020-07-07T12:55:33Z"}
```

**Comment by notsureifkevin** [comment]
Hi @AndreKR - would it be possible for you to open up a thread in the community forum with details on how you've configured your services (deployment/service yaml), and possible steps to reproduce this issue you're having? It's hard to say what the issue could be without knowing more about the services and how they're configured.

Thank you

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by AndreKR** [comment]
[Done](https://community.containo.us/t/backend-has-too-many-servers-configured-every-other-request-fails/6826)
