### ISSUE TITLE
No Docker Image for Traefik 2.2.3 on Docker Hub

### ISSUE THREAD

**Issue by albers** [containous/traefik#7023]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

run `docker run --rm -it traefik:2.2.3`

### What did you expect to see?

Traefik 2.2.3 should be pulled from Docker Hub and a container with it should be launched.

### What did you see instead?

```
docker: Error response from daemon: manifest for traefik:2.2.3 not found: manifest unknown: manifest unknown.
```

This is because no Docker image was created for the 2.2.3 release.
The [last release on Docker Hub](https://hub.docker.com/_/traefik?tab=tags) is 2.2.2.

**Comment by vkudrik** [comment]
Important due to many deployments locked to v2.2 are getting failed.

**Comment by ldez** [comment]
Hello,

The image is published by Docker it-self (not the Docker Hub process).

So we have to wait Docker: https://github.com/docker-library/official-images/pull/8333

**Comment by albers** [comment]
Ah, I see. There is some delay because of a problem in the [first attempt](https://github.com/docker-library/official-images/pull/8329) to update the library image.

Thanks for pointing me there @ldez
