### ISSUE TITLE
[LEGO] Support ACME CNAME following

### ISSUE THREAD

**Issue by SomeGeek** [containous/traefik#7030]
The LEGO library, used for requesting Let's Encrypt certificates, supports CNAME following to host the challenge on a different DNS-zone. This has many advantages.

https://github.com/go-acme/lego/pull/791

The way to enable it is by passing an environment variable. However, as the LEGO is used as a library rather than a standalone client, I don't suspect this to work here.

Is it possible to add a configuration option to enable this?

**Comment by ldez** [comment]
Hello,

the CNAME support in Lego is an experimental feature.
To enable this feature you have to set the env var  `LEGO_EXPERIMENTAL_CNAME_SUPPORT`

https://github.com/go-acme/lego/pull/791#issuecomment-461997317
