### ISSUE TITLE
Intermittent 404 issue since upgrade from 2.2.1

### ISSUE THREAD

**Issue by AndrewSav** [containous/traefik#7031]
There are several threads on the support forum, where people are getting intermittent 404 **which are fixed by  downgrading to 2.2.1 without changing the configuration*. Examples:

- https://community.containo.us/t/v2-https-domain-and-subdomain-error-404/6848
- https://community.containo.us/t/v2-intermittent-404-errors-across-our-docker-containers/6853
- https://community.containo.us/t/404-even-when-route-exists/6854

Since this is reported by different people within short time frame it is likely to be a genuine issue. No one has given a repro so far, but given intermittent nature of the problem it could be difficult.

I'm leaving it here in case the developers are interested into investigating this a bit more in case there is a genuine issue.

**Comment by tborychowski** [comment]
Same here. I checked all browsers (as my Firefox updated about the same time, so suspected that) and the issue happens everywhere.
Sometimes full reload (cmd + shift + r) helps, but the 404 happens very often.
Almost every visit to a page!

**Comment by AndrewSav** [comment]
I opened a new thread trying to get a repro. Unsuccessful so far: https://community.containo.us/t/consolidated-404-issue-thread-in-versions-since-2-2-1/6865

**Comment by ldez** [comment]
related to https://github.com/containous/traefik/issues/7020.

I recommend to use v2.2.4

**Comment by ldez** [comment]
Closed in favor of #7020

Thanks you for reporting.
