### ISSUE TITLE
sending /<path> to alternative port on same backend

### ISSUE THREAD

**Issue by bitprocessor** [containous/traefik#704]
I'm trying to use traefik as a frontend for Odoo containers.
An Odoo instance listens to port 8069 for all normal traffic and port 8072 for long-polling traffic.
Basically:
/< anything > except /longpolling => 8069 on backend
/longpolling => 8072 on backend

Is this something that is possible with traefik? I wasn't really able to find this kind of info in the documentation... 
Either as a configuration-settings, or through the use of labels?

If not possible at the moment, will it be implemented in future versions?

**Comment by naleek** [comment]
Why not just set up another backend with the different port number? A backend with two different listening ports really is two separate back ends anyway.

**Comment by mwaaas** [comment]
@naleek  you are write, what about for some reason you need to direct to a different backend using path. How do you do it in traefik

**Comment by emilevauge** [comment]
@bitprocessor are you using the Docker backend ?

**Comment by bitprocessor** [comment]
@emilevauge - thanks for replying
yes, I'm using the docker backend (regular one, not the swarm one)

**Comment by mwaaas** [comment]
@bitprocessor  Try this example see if it fits what you want
traefik: 
command: "--web --docker --docker.domain=docker.localhost --logLevel=DEBUG"
image: traefik
ports: 
- "80:80"
- "8080:8080"
volumes: 
- "/var/run/docker.sock:/var/run/docker.sock"
- "/dev/null:/traefik.toml"
whoami1: 
image: emilevauge/whoami
labels: 
- traefik.backend=whoami
- "traefik.frontend.rule=Host:whoami.docker.localhost"
whoami2: 
image: emilevauge/whoami
labels: 
- traefik.backend=whoami2
- "traefik.frontend.rule=Path:/test2/, /mwas/"

**Comment by ldez** [comment]
Fixed by #1257
