### ISSUE TITLE
Add support for blacklisting TLS ciphers (instead of only whitelisting)

### ISSUE THREAD

**Issue by mfriess2** [containous/traefik#7053]
Feature

### What did you expect to see?

Currently, Traefik 2.2.5 only supports the white-listing of ciphers as documented here: https://docs.traefik.io/https/tls/#cipher-suites

When running "sslscan", two 3DES ciphers are mentioned as insecure:
```
Accepted  TLSv1.2  112 bits  TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA
Accepted  TLSv1.2  112 bits  TLS_RSA_WITH_3DES_EDE_CBC_SHA
```

Instead of whitelisting 20+ ciphers, I would like to blacklist these two insecure ciphers. Because a whitelist is a) harder to determine correctly for all kinds of clients and b) would need maintaining in the future as new ciphers come out.

Would it be possible to add support for this?

**Comment by jbdoumenjou** [comment]
Hi @geosmart,

Thank you for your interest in Traefik.
As it is a small finite list of elements, we do not think that a black list is useful in this case.
We close this issue accordingly.
