### ISSUE TITLE
X-Forward-For header filter

### ISSUE THREAD

**Issue by sidneiweber** [containous/traefik#7067]
### Do you want to request a *feature* or report a *bug*?

Security Feature

### What did you expect to see?

I'm doing a rate limit for the X-Forwarded-For header, but a hacker can manipulate this header and add ips generics, ex:
X-Forwarded-For \ ": [\" 231.82.17.203, 179.178.31.181 \ "]

it would be interesting to be able to filter this header to get the real value.

Testing in traefik v1.7 in ECS cluster

**Comment by ldez** [comment]
Hello,

you can already defined a list of trusted IPs:
- https://docs.traefik.io/v1.7/configuration/entrypoints/#forwarded-header
- https://docs.traefik.io/v2.2/routing/entrypoints/#forwarded-headers

**Comment by sidneiweber** [comment]
As it is, the rate limit does not take the attacking handler or the x-forward-for and add ips randomly

**Comment by ldez** [comment]
https://docs.traefik.io/v2.2/middlewares/ratelimit/#sourcecriterion

**Comment by sidneiweber** [comment]
v2 work with ecs?

**Comment by ldez** [comment]
- https://community.containo.us/t/traefik-realease-v2-3-0-rc2/6942
- https://docs.traefik.io/v2.3/providers/ecs/
