### ISSUE TITLE
an always true rule expression

### ISSUE THREAD

**Issue by osher** [containous/traefik#7075]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Consider a complex service mesh.
Consider a dev docker-compose setup, where all services talk to each other via `traefik`.
This way, when I decide to run a process on my dev host, I do not need to restart containers in order to direct them to it. Instead - I use traefik rules to direct to `host.docker.local` or to a docker container according to where I need the container to run in.

This requires me to define an entrypoint, a service and a router for every node in the mesh - ok. fine. I'll template that :)

But I have nothing "smart" to say in the router rule, because I already know exactly what service is sought by the entrypoint the request came through(i.e port).

I tried skip the rule attribute, I got a rejection because the rule does not parse.

This requires me to use some useless catch-all rule like:
```
   rule: HostRegexp(`.`)
```

## What I suggest?

So I would like 
 -  either be able to define empty rule
 -  or have some always-true rule expression that returns true without really check anything

I believe this will not only be nice on the config, it will also be more efficient.

**Comment by ldez** [comment]
Hello,

an always true expression is `hostregexp(`{anyhost:.+}`)`

**Comment by osher** [comment]
Yes, functionally it works - actually, that's what I do. If at all  - `PathPrefix('/')`, which is cheaper than a regexp. But why get to this check in the first place if it's useless?
