### ISSUE TITLE
K8s 1.18.6 Traefik 1.7 no matches for kind "Deployment" in version "extensions/v1beta1"

### ISSUE THREAD

**Issue by claflico** [containous/traefik#7089]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Trying to learn Kubernetes and setup a traefik 1.7 ingress controller. Following along with the guide found here: https://docs.traefik.io/v1.7/user-guide/kubernetes/

`kubectl apply -f https://raw.githubusercontent.com/containous/traefik/v1.7/examples/k8s/cheese-deployments.yaml`

### What did you expect to see?

A message that the deployments were successful

### What did you see instead?

```
unable to recognize "https://raw.githubusercontent.com/containous/traefik/v1.7/examples/k8s/cheese-deployments.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"
unable to recognize "https://raw.githubusercontent.com/containous/traefik/v1.7/examples/k8s/cheese-deployments.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"
unable to recognize "https://raw.githubusercontent.com/containous/traefik/v1.7/examples/k8s/cheese-deployments.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
1.7
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```
K8s environment setup via kubeadm on standalone bare metal VM (not minikube)
```
Will submit a PR to fix.

**Comment by ldez** [comment]
Closed by #7090
