### ISSUE TITLE
logger.go should optionally log X-Forwarded-For and other useful headers feature request

### ISSUE THREAD

**Issue by kbroughton** [containous/traefik#711]
This could be used for discovering the ip responsible for requests when traefik nodes are sitting behind an ELB.

https://github.com/containous/traefik/blob/master/middlewares/logger.go

**Comment by dtomcej** [comment]
Due to the improvements of the logging functions in Traefik, you can now select headers to log through the access log: (https://docs.traefik.io/configuration/logs/).

I will go ahead and close this issue. If you have any further issues, please feel free to open a new ticket.

Thanks!
