### ISSUE TITLE
Dose it support docker swarm mode 

### ISSUE THREAD

**Issue by mwaaas** [containous/traefik#712]
It supports several backends (Docker, Swarm, Kubernetes, Marathon, Mesos, Kubernetes, Consul, Etcd, Zookeeper, BoltDB, Rest API, file...) 

what about the swarm mode built in Docker, is it supported

**Comment by ralphtheninja** [comment]
It will have support for docker swarm in version 1.1

**Comment by emilevauge** [comment]
Support added with #602 :)
