### ISSUE TITLE
Remove or dismiss Traefik pilot warning 

### ISSUE THREAD

**Issue by DanyHenriquez** [containous/traefik#7120]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

The ability to dismiss the traefik pilot warning opr remove it through CLI. The irritation is very high due to the amount of screen space taken

**Comment by ldez** [comment]
Hello,

could explain what do you call "the traefik pilot warning"?

**Comment by DanyHenriquez** [comment]
The extremely large banner on the dashboard of the latest 2.2.x and 2.3.x versions

**Comment by ldez** [comment]
ok, you are talking about the pilot notification:

![Screenshot_2020-07-29 Traefik](https://user-images.githubusercontent.com/5674651/88801563-2f834900-d1aa-11ea-98ab-38d4b03094a1.png)

**Comment by traefiker** [comment]
Closed by #7200.
