### ISSUE TITLE
How to create a fallback reverse proxy on Kubernetes ?

### ISSUE THREAD

**Issue by scorsi** [containous/traefik#7121]
Hello,

I would like to know how to create a fallback reverse proxy with Traefik on Kubernetes.

I am actually migrating from a old monolithic application to a micro-services architecture, step by step. The idea is to create micro-services one by one and fallback to the old monolithic when the service (the path) doesn't exists.
More explicitly:
 - `/service-a/**` -> `api.service-a.svc.cluster.local`
 - `/service-b/**` -> `api.service-b.svc.cluster.local`
 - `/**` -> `https://api.somedomain.com/`

So when we will do `/service-c` it will reverse proxy the request to `https://api.somedomain.com/service-c`.

I know how to achieve the both first but not the reverse proxy, I searched on the documentation but I don't figured out how to achieve that in Kubernetes.

Thanks,

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
