### ISSUE TITLE
Using secrets for Path()...

### ISSUE THREAD

**Issue by docwhat** [containous/traefik#7127]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

In order to hide and secure certain pages I sometimes use a secure URL. e.g. a URL that is hard to "guess" such as `https://example.com/eikee-shae7pobi9xohNiadequi4nonih9oeraeJ4wo4eezseesh4max.ics`

I would expect there would be a way to use the `Path*` rules with a Kubernetes Secret to protect the path portion of the secret URL.

I could then store the Path as a Kubernetes Sealed Secret safely in my git repository.

I have no idea how this would work in practice.  Possibly the whole `Rule` could be loaded from a Secret?

**Comment by mpl** [comment]
Hi,

this seems like a really niche feature nobody except for you would use, so we're not going to spend time on it, sorry.

However, out of curiosity, could you explain why having a part of the URL path in a Kubernetes Secret would improve security in any way? What is the set of people who can access your traefik config, but who are not able to access your Kubernetes Secrets (if that is the point)?

**Comment by docwhat** [comment]
> However, out of curiosity, could you please explain why having a part of the URL path in a Kubernetes Secret would improve security in any way?

A lot of calendaring software doesn't like HTTP basic auth or other authentication mechanisms for fetching `.ics` files.

A common pattern is to use a really long random URL so that it can't be guessed, making it secure that way.

> What is the set of people who can access your traefik config, but who are not able to access your Kubernetes Secrets (if that is the point)?

I store my [kubernetes configuration](https://github.com/holtje/hive-config) in GitHub (gitops via [fluxcd](https://fluxcd.io/)).  The traefik config is public.  Secrets are [`kubeseal`d](https://github.com/bitnami-labs/sealed-secrets#readme) and therefore not readable on GitHub.
