### ISSUE TITLE
Invalid K8s configs in Traefik 1.x->2.x migration docs

### ISSUE THREAD

**Issue by PCM2** [containous/traefik#7130]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you expect to see?

https://docs.traefik.io/migration/v1-to-v2/#http-to-https-redirection-is-now-configured-on-routers

The documentation on migrating from Traefik 1.x to 2.x should include valid example configuration files for demonstration purposes.

### What did you see instead?

On https://docs.traefik.io/migration/v1-to-v2/#http-to-https-redirection-is-now-configured-on-routers , several objects in the K8s IngressRoute configs have names that include underscores (_). This goes against [K8s naming convention](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/), in which names for most resource types must follow [RFC 1123](https://tools.ietf.org/html/rfc1123).

Sample output (truncated):

```
% kubectl apply -f test.yaml      
Error from server (Invalid): error when creating "test.yaml": IngressRoute.traefik.containo.us "http_catchall" is 
invalid: metadata.name: Invalid value: "http_catchall": a DNS-1123 subdomain must consist of lower case 
alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', 
regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

### Notes

- One fix might be to change from an underscore (_) to a hyphen (-)
- Presumably, the names in the K8s examples should match the ones in the Docker examples and the TOML and YAML static config files
- This issue appears to exist in docs versions 2.1 and later
- The same issue may affect other docs

**Comment by traefiker** [comment]
Closed by #7131.
