### ISSUE TITLE
Missing CORS headers since v2.2.8

### ISSUE THREAD

**Issue by soullivaneuh** [containous/traefik#7140]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

As a web user, I download assets from `assets.domain.com` required by `domain.com` to show font awesome icons.

### What did you expect to see?

The assets are downloaded and the icons rendered.

Also, we can see the CORS header shown:

```
❯ http --headers https://assets.domain.com/fa-pro/webfonts/fa-solid-900.woff2 | grep 'Access-Control-Allow-Origin'
Access-Control-Allow-Origin: *
```

### What did you see instead?

Icons loading failed with this message:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://assets.domain.com/fa-pro/webfonts/fa-solid-900.woff2. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
```

And no more header:

```
❯ http --headers https://assets.domain.com/fa-pro/webfonts/fa-solid-900.woff2 | grep 'Access-Control-Allow-Origin'
```

### Output of `traefik version`: v2.2.8

```
Version:      2.2.8
Codename:     chevrotin
Go version:   go1.14.6
Built:        2020-07-28T15:46:03Z
OS/Arch:      linux/amd64
```

Note: This is working well with **exact same environment** under v2.1.6.

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Binary options:

```
--global.sendAnonymousUsage
--log.level=INFO
--api
--accessLog
--entrypoints.web.address=:"${ROUTER_HTTP_PORT:-80}"
--entrypoints.web-secure.address=:"${ROUTER_HTTPS_PORT:-443}"
--certificatesResolvers.letsencrypt.acme.email="${ACME_EMAIL:-postmaster@domain.com}"
--certificatesResolvers.letsencrypt.acme.storage=/data/acme.json
--certificatesResolvers.letsencrypt.acme.httpChallenge.entryPoint=web
--providers.docker
--providers.docker.exposedByDefault=false
```

Traefik labels of the assets container:

```
"traefik.enable": "true",
"traefik.http.middlewares.domain-assets-production.headers.accessControlAllowOrigin": "*",
"traefik.http.routers.domain-assets-production.middlewares": "domain-assets-production@docker",
"traefik.http.routers.domain-assets-production.rule": "Host(`production.assets.domain.com`)",
"traefik.http.routers.domain-assets-production.tls.certresolver": "letsencrypt"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```

**Comment by rtribotte** [comment]
Hi @soullivaneuh,

Thanks for your interest in Traefik!

Please refer to the migration guide [v2.1 to v.2.2](https://docs.traefik.io/v2.2/migration/v2/#v21-to-v22), the option has changed it's now `accessControlAllowOriginList`.
I will close this issue accordingly.
