### ISSUE TITLE
How to install dashboard? 

### ISSUE THREAD

**Issue by fz8770** [containous/traefik#7143]
I refer to https://docs.traefik.io/getting-started/install-traefik/#exposing-the-traefik-dashboard

helm install traefik2  traefik/traefik --set  service.type=NodePort,dashboard.enable=true,dashboard.ingressRoute=true --namespace traefik

# dashboard.yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: dashboard
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`traefik.domain.cn`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService

kubectl apply -f dashboard.yaml

browser access

404 page not found

![1](https://user-images.githubusercontent.com/50136484/89368278-b76ad500-d70d-11ea-8c0c-5af19dd64505.png)

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
