### ISSUE TITLE
Separate access log files by router

### ISSUE THREAD

**Issue by tobia** [containous/traefik#7150]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I would like the possibility to write access logs into separate files according to the router name. This would help in shared hosting / multi-tenant situations, where a single Traefik frontend is used to publish services for different customers, whose data should never be mixed up.

For example:

    [accessLog]
    filePath = "/var/log/traefik/{{.RouterName}}-access.log"

**Comment by Heisenberg74** [comment]
Hi,
Nice idea.
Even better: having a parameter to define the path of the access log for each router.

Marc

**Comment by jbdoumenjou** [comment]
duplicate of #6369
