### ISSUE TITLE
Understanding support / release cycle

### ISSUE THREAD

**Issue by SpatialJ** [containous/traefik#7153]
Hi,

in the documentation / readme it says

> Each version is supported until the next one is released (e.g. 1.1.x will be supported until 1.2.0 is out).

Is this per major version? I see there are bugfixes for 1.7 although we are currently at 2.3.
Will 1.x be supported in the future? Is there a roadmap for 1.x?

Im asking this in the context of figuring out a reasonable upgrade approach for our production systems.

Thanks,
Johannes

**Comment by ldez** [comment]
Hi,

> Is this per major version?

It's only by minor version, currently we support v1.7 and v2.2 (v2.3 is in the release candidate phase).

> Will 1.x be supported in the future? Is there a roadmap for 1.x?

Traefik v1 is in a maintenance mode: features are frozen, we only apply bug fixes.

The support of the v1.x version will continue until the end of 2021. 

- [Supporting the 1.X Branch for Two Years](https://containo.us/blog/traefik-2-1-in-the-wild/#supporting-the-1-x-branch-for-two-years-)


Thanks.
