### ISSUE TITLE
PostgreSQL as config store

### ISSUE THREAD

**Issue by erichiller** [containous/traefik#7157]
This a a feature request for adding PostgreSQL as a configuration store/discovery source, much like [etcd](https://docs.traefik.io/providers/etcd/) is now. It could be achieved in a number of numbers ways (NOTIFY for config updates, etc) and it would be very useful for those running in an environment where PostgreSQL is already setup and etcd or other stores are not.

**Comment by ldez** [comment]
Duplicate of #1856

**Comment by erichiller** [comment]
That's from 3 years ago and it's closed, does this mean it's not going to happen?
