### ISSUE TITLE
Expose traefik service health check status as metrics (prometheus, datadog, etc)

### ISSUE THREAD

**Issue by hansehe** [containous/traefik#7168]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

The metrics exposed by traefik are missing typical service health check status.
In general, one of the most common metrics use-cases are service statuses. 
It would be very helpfull if service statuses are exposed as metrics, to create valuable service status dashboards.

**Comment by ldez** [comment]
Duplicate of #3783
