### ISSUE TITLE
Error while parsing rule Host() && (PathPrefix(): 1:24: expected ‘)’, found newline

### ISSUE THREAD

**Issue by taro-cmd** [containous/traefik#7176]
i notice that it is very strict on using the werid quote "\`"
syncCatalog can detect the rules but regular consul connect cannot detect the rules

traefik.enable=true,traefik.http.routers.static.rule=Host(`webservice.domain`) && (PathPrefix(`/siteone`)

is there a way to escape the "` `" ?

basically it comes out as 

traefik.enable=true
traefik.http.routers.static.rule=Host() && (PathPrefix()
traefik.http.routers.static.entrypoints=web
traefik.http.services.static.loadbalancer.server.port=8080

I also notice even though it shows an error, the pathprefix does work

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
