### ISSUE TITLE
Add section covering Time Zones for AccessLog in v2

### ISSUE THREAD

**Issue by notsureifkevin** [containous/traefik#7177]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

https://github.com/containous/traefik/blob/v1.7/docs/configuration/logs.md#time-zones in 2.x documentation.

In the 1.7 documentation, there is a brief section covering how to enable the local server timezone for access logs that appears to have never been ported to 2.x. The functionality seems to still exist and was confirmed as functioning per @kevinpollet and was re-discovered per https://github.com/containous/traefik/issues/7163

**Comment by traefiker** [comment]
Closed by #7178.
