### ISSUE TITLE
Unable to access Traefik via local IP

### ISSUE THREAD

**Issue by y2klol** [containous/traefik#7180]
I have traefik dashboard working. I can access it via traefik.example.xyz.
But when I enter my public ip address or my local ip address I get a 404 page not found. It doesn't redirect.
I would like to be able to access traefik via ip address both local and public.

Why would I want to do this?
The hairpinning/NAT Loopback on my router sucks. I want to be able to access traefik at home via local network so I can actually use it. In addition, having the local ip address would allow me to add
192.168.0.108 traefik.example.xyz traefik
to my /etc/pihole/lan.list

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by y2klol** [comment]
I have already tried the forums and have gotten no response there.
