### ISSUE TITLE
Traefik with Docker, multiple ip addresses

### ISSUE THREAD

**Issue by JanDevDE** [containous/traefik#7184]
Hello,

I did try to ask this question in the community forums but unfortunately got no reply, so I thought maybe I can ask that here and get a reply from the developers:

In the documentation there is a section about listening to a specific IP address such as "entrypoints.specificIPv4.address=192.168.2.7:8888", but unfortunately, that is not possible within docker because those IP addresses are not available inside the traefik container (obviously).

So, how can I use traefik for multiple IP addresses?

(The only other way how I was able to do that was the following:

...
    command:
      - "--entrypoints.95http.address=:80"
      - "--entrypoints.92http.address=:81"
    ports:
      - "1.1.1.1:80:80"
      - "2.2.2.2:80:81"
...
)

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
