### ISSUE TITLE
level=error msg="error: port is missing"

### ISSUE THREAD

**Issue by gvdhoven** [containous/traefik#7187]
In my case the error is flooding my logs for my mosquitto docker container for which i only use traefik to generate and renew the certificate. The certificate itself is copied to mosquitto internally.

These are the only (required) labels for a working setup, but apparently Traefik requires more?

    ports:
      - 1883:1883
      - 8883:8883
      - 9001:9001
      - 9883:9883
    labels:
      # Enable traefik
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"

      # Router: image-specific
      - "traefik.http.routers.network-mosquitto.rule=HostHeader(`mqtt.at.vdhoven.info`)"
      - "traefik.http.routers.network-mosquitto.entrypoints=websecure"
      - "traefik.http.routers.network-mosquitto.tls=true"
      - "traefik.http.routers.network-mosquitto.tls.certresolver=leresolver"

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by gvdhoven** [comment]
This is not a a question but an actual bug report.

**Comment by ldez** [comment]
Hello,

take a look to the documentation: https://docs.traefik.io/v2.2/providers/docker/#port-detection_1

**Comment by notsureifkevin** [comment]
When reporting a bug, please follow the bug report template and include steps to reproduce, your entire configuration, and debug logs. The bot thinks your issue is a question because the format isn't followed and there isn't enough information for the team to troubleshoot your issue.

In your case it appears that you've not mapped a port for traefik to route on your application. Please see the documentation @ldez has referenced above.

**Comment by gvdhoven** [comment]
@ldez sorry for my blunt reply; it removes the feel to help i get that; Here are the answers:
* I have multiple ports as shown in my config
* I am not running in swam mode (to which the docs refer to)
* The ports which are exposed are TCP services, not HTTP. I only am 'mis-using' traefik to get the certificate renewal.

Therefore, for Traefik it doesn't care to which port it should forward the requests, right? Hence my request to be able to turn off this message.

**Comment by ldez** [comment]
Could you  join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik). Thank you.
