### ISSUE TITLE
Feature Request: access log file name prefix based on route

### ISSUE THREAD

**Issue by PawelJ-PL** [containous/traefik#7188]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

It would be great if I could add a prefix to the access log file name for each route.
Alternatively, a prefix could be added to the name by adding an appropriate label (for example `traefik.http.routers.foo.logprefix: "foo"`).
This would allow better management of log files and create different `fail2ban` rules for each service separately.

**Comment by rtribotte** [comment]
duplicate of #6369
