### ISSUE TITLE
backend How to get IoT SNAT-Addr and SNAT-Port after traefik?

### ISSUE THREAD

**Issue by Roarain** [containous/traefik#7189]
traefik:v2.2  on k8s(v1.16.8) daemonset using ingressrouteudps.
# datastream 
Input: IoT(SNAT1) --> traefik(SNAT2) --> backend
Output: backend --> IoT
# problem 
1. backend get udp snat is traefik(SNAT2) 
2. when backend communicate to IoT cannot get  IoT(SNAT1)
3. So, communicate is disconnect.
# How 
Using Transparent Proxy to help backend get original SNAT1 .

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
