### ISSUE TITLE
[kubernetes] Use TLS secrets from other namespaces 

### ISSUE THREAD

**Issue by javipolo** [containous/traefik#7193]
Allow kubernetes ingress to refer to a secretName in a different namespace, so I can store TLS credentials separate from the applications

Example:
`- secretName: kube-system/domain-tls`

I can think of different use cases where this would be handy:
- If you use the same domain name in different namespaces, have the certificate/key in a single place, avoiding mistakes when updating it
- Hide TLS keys from developers

In case this would pose a security risk it could be disabled by default, and enabled explicitly with a configuration setting

**Comment by SantoDE** [comment]
Hello @javipolo,

👋  long time no see! :) 

We already thought about that but, as for now, we're not going to implement something like that. We're a bit too afraid of the potential security risk with people, forgetting to disable that behavior or so.

Therefore, I'll be closing that issue. 

PS: Hope you're doing good over there! :)

**Comment by javipolo** [comment]
That's why I proposed to be a non-default behaviour :)

PS: All good, nice to see you around hehehe
