### ISSUE TITLE
Forward requests based on same port

### ISSUE THREAD

**Issue by MatteoInfi** [containous/traefik#7213]
### Do you want to request a *feature* or report a *bug*?

Feature

#### My use case
Let's say I am developing a small hosting service using a multi-container system on ECS and Autoscaling. 
Each container have a specific port assigned through its entire life-cycle and it is meant as stand-alone application. I will be often moving those containers around (for autoscaling, OS updates, etc...), thus the IP will change quite often.

**So now I am looking for having one IP (static) routed to different IPs depending on the requested port**
**The traffic is pretty much only from TCP and UDP**

#### Solution
First of all it would be great to allow port ranges
```
[entryPoints]
    [entryPoints.tcp]
    address = ":2000 - :25000"
```

And then for the router something like that

```
[tcp.routers]
  [tcp.routers.Router-1]
  rule = Port(`<incoming_port>`)
```

So it would be similar to a port forwarding routing

Is this even possible?

Thanks

PS: I cannot use DNS

**Comment by SantoDE** [comment]
Hey @MatteoInfi,

thanks for your interest in the project.

What you're trying to achieve has been briefly covered here, in case you want to take a look: https://containo.us/blog/do-machines-learn-testing-in-production-with-traefik/

Apart from that, the feature's you're asking for (entryPoint range and a new matcher) doesn't really fit with Traefik per se, which is the reason for me closing that issues. We have something else in mind, which could solve that issues but we're not sure yet. If we happen to do something like that, we'll bump that issue again.

Thanks a lot.
