### ISSUE TITLE
tls.store.default.defaultCertificate not reading secretName.

### ISSUE THREAD

**Issue by sainipankaj90k** [containous/traefik#7216]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

AIM: Use tls.store.default.defaultCertificate instead of IngressRoute.spec.tls to use certificate from single namespace where Traefik is deployed. If this does not work, I've to create kubernetes secrets in each namespace where IngressRoute is required.
_FYI, IngressRoute.spec.tls.secretName works as expected and hence tls-cert secret in Kubernetes contains right certificate in right format._ 

Using traefik:v2.2

Created a 'tls-cert' in kubernetes secret. Verified it working if specified in IngressRoute.spec.tls _secretName:tls-cert_.

Created a configMap for tls.Store and have it consumed in traefik-deployment with image = traefik:v2.2.
_Ignore the commented '#', that is the example that was running successfully._

```
apiVersion: v1
data:
  shared.yaml: |
    tls:
      stores:
        default:
          defaultCertificate:
            secretName: tls-cert
            # certFile: /ssl/cert1/cert1.pem
            # keyFile: /ssl/cert1/cert1.key
kind: ConfigMap
metadata:
  name: traefik-config

```

### What did you expect to see?

I expected traefik to pick certificate from secrets. (Just like it worked from IngressRoute.spec.tls.secretName).

### What did you see instead?

A traefik-default-cert was used for tls.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
traefik:v2.2
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```
# (paste your configuration here)
kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.9", GitCommit:"a2cfecc33f6911261fb8a670d2df2714094002a6", GitTreeState:"clean", BuildDate:"2020-05-29T21:50:25Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

Logs from Traefik
```
time="2020-08-26T16:42:11Z" level=info msg="Configuration loaded from file: /etc/traefik/traefik.yaml"
{"level":"info","msg":"Traefik version 2.2.1 built on 2020-04-29T18:02:09Z","time":"2020-08-26T16:42:11Z"}
{"level":"info","msg":"\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://docs.traefik.io/contributing/data-collection/\n","time":"2020-08-26T16:42:11Z"}
{"level":"info","msg":"Starting provider aggregator.ProviderAggregator {}","time":"2020-08-26T16:42:11Z"}
{"level":"info","msg":"Starting provider *file.Provider {\"directory\":\"/etc/traefik/dynamic\",\"watch\":true,\"debugLogGeneratedTemplate\":true}","time":"2020-08-26T16:42:11Z"}
{"level":"info","msg":"Starting provider *traefik.Provider {}","time":"2020-08-26T16:42:11Z"}
{"level":"error","msg":"Error while creating certificate store: failed to load X509 key pair: tls: failed to find any PEM data in certificate input","time":"2020-08-26T16:42:11Z","tlsStoreName":"default"}
{"level":"info","msg":"Starting provider *crd.Provider {}","time":"2020-08-26T16:42:11Z"}
{"level":"info","msg":"label selector is: \"\"","providerName":"kubernetescrd","time":"2020-08-26T16:42:11Z"}
{"level":"info","msg":"Creating in-cluster Provider client","providerName":"kubernetescrd","time":"2020-08-26T16:42:11Z"}
{"level":"error","msg":"Error while creating certificate store: failed to load X509 key pair: tls: failed to find any PEM data in certificate input","time":"2020-08-26T16:42:12Z","tlsStoreName":"default"}
{"level":"error","msg":"Error while creating certificate store: failed to load X509 key pair: tls: failed to find any PEM data in certificate input","time":"2020-08-26T16:42:13Z","tlsStoreName":"default"}
```

**Comment by ldez** [comment]
Hello,

`secretName` is not a valid field for the TLS configuration for a configuration use by the file provider:

- https://docs.traefik.io/v2.2/https/tls/#default-certificate

`secretName` is a valid field for the CRD named `tlsstore` (related to the CRD provider)

- https://docs.traefik.io/v2.2/routing/providers/kubernetes-crd/#kind-tlsstore

**Comment by sainipankaj90k** [comment]
Interesting and weird at the same time :).
Thanks, will try with kind-tlsstore.
