### ISSUE TITLE
Clarification on HostSNI removal

### ISSUE THREAD

**Issue by myoung34** [containous/traefik#7229]
### Do you want to request a *feature* or report a *bug*?

Bug

In the migration docs [here](https://docs.traefik.io/v2.2/migration/v2/#v21-to-v22) :

```
HostSNI rule matcher removal¶
In v2.2.2 we introduced a new rule matcher (HostSNI) which was allowing to match the Server Name Indication at the router level. Since v2.2.5 this rule has been removed, and you should not use it anymore.
```

In creating a TCP router, using `Host('*')` results in:

```
time="2020-08-30T16:31:34Z" level=error msg="unknown rule Host(`pihole.cluster.local`)" entryPointName=dns routerName=default-pihole-dns-a2be5f
1a3e4fc38e3759@kubernetescrd
```

The error disappears if i use `HostSNI` but the docs say that it's removed.

`HostSNI` is also referenced in the v2.3 docs [here](https://docs.traefik.io/v2.3/routing/providers/kubernetes-crd/#kind-ingressroutetcp)

### What did you expect to see?

An error using `HostSNI` and no error using `Host`

### What did you see instead?

An error using `Host` and no error using `HostSNI`

### Output of `traefik version`: (_What version of Traefik are you using?_)

± kubectl exec -it traefik-85d7c864fb-hw64j traefik version
Version:      2.3.0-rc4
Codename:     picodon
Go version:   go1.15
Built:        2020-08-19T16:02:03Z
OS/Arch:      linux/arm64

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

no relevant

**Comment by traefiker** [comment]
Closed by #7237.
