### ISSUE TITLE
RedirectScheme doesn't work if router also got TLS

### ISSUE THREAD

**Issue by fireba11** [containous/traefik#7236]
# Do you want to request a *feature* or report a *bug*?

Bug (at least id' classify it as such)

### What did you do?

Set up an IngressRoute listening to web and websecure, with middlware RedirectScheme to get everyone on HTTPS.

kind: IngressRoute
metadata:
  name: my-app
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`mydomain.com`)
      middlewares:
        - name: http-to-https
          namespace: default
      services:
        - kind: Service
          name: my-app
          namespace: default
          port: 80
  tls:
    certResolver: myresolver

### What did you expect to see?

HTTPS requests answered directly
HTTP requests redirected to HTTPS

### What did you see instead?

HTTPS requests answered directly
HTTP requests got 404

### Output of `traefik version`: (_What version of Traefik are you using?_)

traefik v2.2.8 (using the containous chart traefik-9.1.0)

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

kubernetes

### It works when
I make two seperate IngreeRoutes,
one with entrypoint web and the redirect
one with entrypoint websecure and the certResolver

For me this is
a) highly unexpected
b) if fixed would allow for more compact configuration (halfing the number of ingressRoutes needed)

This seems to be the same root cause as #6892

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Community Forum](https://community.containo.us/).
