### ISSUE TITLE
Provider file watch finishes if file does not initially exist.

### ISSUE THREAD

**Issue by MrBlenny** [containous/traefik#7240]
### What did you do?
I have configured traefik with a file provider mounted in a docker volume. The reason being, I have another service that writes configuration to the file dynamically.

```
[providers]
  [providers.file]
    filename = "/traefik_data/traefik.config.toml"
    watch = true
```

### What did you expect to see?

As `traefik_data` is a docker volume, when the volume is first created it is empty. Then Traefik starts and then the traefik.config.toml is created a few moments later. I would have expected traefik to error but then continue to watch for this file and use it if it exists.

### What did you see instead?

Traefik throws an error `/traefik_data/traefik.config.toml - open /traefik_data/traefik.config.toml: no such file or directory"` and then stops watching this file. Even if it created a few moments later it is no longer being watched so traefik will not use the config.

### Output of `traefik version`: v2.0

```
time="2020-09-03T07:35:59Z" level=info msg="Configuration loaded from file: /etc/traefik/traefik.toml"
time="2020-09-03T07:35:59Z" level=info msg="Traefik version 2.0.7 built on 2019-12-09T17:51:21Z"
time="2020-09-03T07:35:59Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://docs.traefik.io/v2.0/contributing/data-collection/\n"
time="2020-09-03T07:35:59Z" level=info msg="Starting provider aggregator.ProviderAggregator {}"
time="2020-09-03T07:35:59Z" level=info msg="Starting provider *file.Provider {\"watch\":true,\"filename\":\"/traefik_data/traefik.config.toml\"}"
time="2020-09-03T07:35:59Z" level=error msg="Cannot start the provider *file.Provider: error reading configuration file: /traefik_data/traefik.config.toml - open /traefik_data/traefik.config.toml: no such file or directory"
```

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
