### ISSUE TITLE
Improve the doc for secretName in IngressRoute.tls

### ISSUE THREAD

**Issue by kehao95** [containous/traefik#7244]
## Issue
I was confused by the doc for `secretName` and I noted my misunderstanding in the [community post](https://community.containo.us/t/how-to-use-tls-in-k8s-ingressroute/7529):

So I'm very confused, which describe secretName better?
- A. For ACME only: it's a name that Traefik will use to create an kubernetes Secrect to store the cert files obtained by acmeresolver.
- B. For user defined cert only: Traefik will try to load this secret and use the certificate inside it.

:question: IF A then will the resolver save the certs to both /data/acme.json (mentioned before) and the k8s secret?
:question: IF B then how should the secret be created. What the data structure should be like. How do I assign different route with different certs? There seem to be no example in the doc.

## Suggestion
I suggest we reword the description for the `secretName` and provide a proper `Secret` definition example. There is no way for the user to guess it out the proper structure of the secret.

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: mycert
type: Opaque
data:
  tls.crt: ... ...
  tls.key: ... ...
```

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
