### ISSUE TITLE
issues with marathon app ids containing a dot

### ISSUE THREAD

**Issue by polaru** [containous/traefik#726]
When the marathon app id contains a dot (/myapp.example.com), traefik can't create the backend:
```
DEBU[2016-10-09T13:31:48Z] Creating backend
ERRO[2016-10-09T13:31:48Z] Undefined backend '' for frontend frontend-myapp
```
The same application config but with an ID not containing any dots works fine.
Traefik version v1.0.3 built on 2016-09-22_01:15:33PM
Marathon v0.15.3

**Comment by emilevauge** [comment]
Fixed by #728
