### ISSUE TITLE
No Docker Image for Traefik 2.2.11 on Docker Hub

### ISSUE THREAD

**Issue by tlex** [containous/traefik#7265]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
`docker run --rm -it traefik:2.2.11`

### What did you expect to see?

Traefik 2.2.11 should be pulled from Docker Hub and a container with it should be launched.

### What did you see instead?

```docker: Error response from daemon: manifest for traefik:2.2.11 not found: manifest unknown: manifest unknown.```

This is because no Docker image was created for the 2.2.11 release.
The last release on Docker Hub is 2.2.10.

I couldn't find any PR for 2.2.11 in [docker-library/official-images](https://github.com/docker-library/official-images/pulls?q=is%3Apr+traefik)

**Comment by ldez** [comment]
Hello, 

The [PR](https://github.com/docker-library/official-images/pull/8679) contains v2.3.0-rc5 and  v2.2.11

The July 7 is holiday in the US, as Docker folks are based in the US, we have to wait.
