### ISSUE TITLE
Why ErrorPage middleware use bad Host 0.0.0.0 ?

### ISSUE THREAD

**Issue by gmarsay** [containous/traefik#7275]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I've configured a "ErrorPage" middleware for return custom pages when an error occured on my services.
My middleware use a service named "service-errors", this service has one server "http://error.my-domain.com"

My server "error.my-domain.com" is an independant Apache webserver with a VirtualHost configured for this domain. He work correctly without Traefik.

My use case :
* I've multiple servers on my service
* healthcheck is enabled on my service
* when all servers are down, healthcheck return HTTP 503
* when i've a 503 error, I want capture this with ErrorPage middleware

### What did you expect to see?

When all servers are down, I want see my custom error page from error.my-domain.com.

### What did you see instead?

I see default Apache page "It work !"

After analyze with a tcpdump, in HTTP header, I see this : "Host 0.0.0.0" instead of "Host error.my-domain.com".

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
# traefik version
Version:      2.2.8
Codename:     chevrotin
Go version:   go1.14.6
Built:        2020-07-28T15:46:03Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

I use YAML file for my configurations.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
