### ISSUE TITLE
Traefik 2.x support for kvs atomic configs?

### ISSUE THREAD

**Issue by dariopb** [containous/traefik#7284]
Sort of a question more than a bug per se.
Traefik 1.x KVS config backend had the "**traefik.alias**" key that could be use to make atomic updates to the whole configuration (instead of whatching the whole prefix, only the traefik.alias key is watched and then the target used as config). I'm having a hard time finding the same functionality in the 2.x versions.

Is there a similar way to achieve full atomic config updates in 2.x? If not, what is the suggested way to achieve something like that (won't traefik watches trigger an update for every key update having intermediate, wrong, configuration?).

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
