### ISSUE TITLE
Use Alpine as a base image to help with debugging?

### ISSUE THREAD

**Issue by joonas-fi** [containous/traefik#729]
I know Traefik is highly optimized in that the base image is as minimal as possible ("FROM scratch"). But would using Alpine be a good tradeoff since it would enable entering the container to do debugging work? It is only 2 megabytes. https://hub.docker.com/r/library/alpine/tags/

I had a case where I wanted to debug connectivity from Traefik's container by trying to run:

```
 $ docker exec -it $CONTAINER_OF_TRAEFIK sh
 rpc error: code = 2 desc = oci runtime error: exec failed: exec: "sh": executable file not found in $PATH
```

I wanted to curl, ifconfig and debug other network related stuff from inside the container.

After that I realized it is because Traefik is using "FROM scratch" so the container does not have a shell - basically I cannot do anything inside it.

What do you think?

**Comment by vdemeester** [comment]
I would think we could provide a special tag for the `containous/traefik` image with alpine (something like `containous/traefik:alpine` or something).

/cc @containous/traefik wdyt ?

**Comment by joonas-fi** [comment]
Pros:
- Would not incur/force Alpine's overhead to all images

Cons:
- That would add a small amount of complexity to the build process

Additional considerations: Alpine's overhead is only on disk (which there is plenty and 2 MB is negligible), not on RAM (which is precious). I'm all for minimizing RAM usage but using Alpine as a base would not consume additional RAM.

Just my two cents. I like the idea! :)

**Comment by emilevauge** [comment]
We could add alpine support using tags (like Redis does https://hub.docker.com/_/redis/).
But the `from SCRATCH` image should be preferred in production from a security point of view.

**Comment by gjonespf** [comment]
This will be awesome for debugging, however I'm not seeing any tags for this here:
https://hub.docker.com/r/containous/traefik/tags/
Any docs on where this can be used?

EDIT: Apologies, thought adding it to the issue was probably better than the PR which is already merged.

**Comment by f0** [comment]
why not use [nsenter](http://man7.org/linux/man-pages/man1/nsenter.1.html) for debugging? 
You can only join the network namespace with all tools from the host

**Comment by gjonespf** [comment]
I'm not sure of @joonas-fi usecase, but for me @f0 while this is a good idea in principle, many hosts are either unavaliable (mobylinux) or don't have tooling for doing anything useful (CoreOS).  I'm all for keeping the main image as low profile for mem/security reasons, but it'd be useful to docker exec into Traefik to check e.g. did I mount my TOML or SSL certs correctly.  For me, this is becoming less of an issue as I'm trying to do everything through KV store :)

**Comment by errm** [comment]
@emilevauge can we close this issue now?

**Comment by emilevauge** [comment]
@errm sorry not yet, It still need some work on Travis.

**Comment by emilevauge** [comment]
Alpine image is here: `v1.1.0-alpine`, `camembert-alpine` https://hub.docker.com/r/library/traefik/
We can close this one :)
