### ISSUE TITLE
traefik * Users: unsupported type: slice

### ISSUE THREAD

**Issue by csawyerYumaed** [containous/traefik#743]
When I have users in my consul KV backend, I get this error on startup.

to duplicate..
config in toml format:
[Web]
address = ":8080"
[web.auth.basic]
users = ["test:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/"]
then run storeconfig, and then run it against -consul

**Comment by emilevauge** [comment]
Fixed by #759
