### ISSUE TITLE
Swarm Docs - How to use a FQDN

### ISSUE THREAD

**Issue by programster** [containous/traefik#744]
I managed to follow and get working the[ rc2 docs for running in a docker swarm cluster](https://github.com/containous/traefik/blob/v1.1.0-rc2/docs/user-guide/swarm-mode.md), after figuring out that while we are in release I need to pull/use `traefik:v1.1.0-rc1 ` instead of just `traefik` because `traefik:v1.1.0-rc2` doesn't seem to exist yet.

However, I can't figure out how to get this working with a FQDN such as `my-site.programster.org`. The docs simply show testing with `curl -H Host:whoami0.traefik http://$(docker-machine ip worker1)`. I make sure to update my `/etc/hosts` file to point `my-site.programster.org` to any of the swarm nodes, but I just get a `404 page not found` message. 

Is this a simple configuration change, such as changing:

```
docker service create \
    --name whoami0 \
    --label traefik.port=80 \
    --network traefik-net \
    emilevauge/whoami
```

...which could be clarified in an update to the docs or is it just not possible? I tried changing `--name` and `--label` values with no success.

**Comment by ascora** [comment]
Try this:

```
docker service create \
    --name whoami0 \
    --label traefik.port=80 \
    --network traefik-net \
    --label traefik.frontend.rule=Host:my-site.programster.org \
    emilevauge/whoami
```

**Comment by programster** [comment]
Brilliant! I just tested it and that's exactly what I needed!

**Comment by emilevauge** [comment]
If your issue is solved, can you close it? Thanks @programster :)

**Comment by programster** [comment]
I'm closing this thread, but I do suggest the documentation is updated to include this example because I won't be the only one. Thanks for the help.
