### ISSUE TITLE
Traefik as ingress controller for SNI based routing in kubernetes

### ISSUE THREAD

**Issue by hrdcdr** [containous/traefik#745]
Is it possible? It's unclear for me. Currently the ingress definition only supports a single TLS cert, but traefik supports SNI. How can I use them together to get SNI feature in kubernetes?

**Comment by ArchiFleKs** [comment]
I don't think Traefik supports TLS inside ingress definition, someone correct me if i'm wrong. But you can mount the secret with the certificate inside traefik and use it with a configmap without specifiing TLS inside the ingress yaml file.

**Comment by ArchiFleKs** [comment]
@hrdcdr you can use let's encrypt or mount your kubernetes secret into Traefik pods and use it in your traefik.toml configmap. I wrote an article about how to use Traefik with Kubernetes and Let's encrypt if you want to check it out https://archifleks.github.io/blog/kubernetes-ingress/ 

You can get SNI support with ingress rules without specifing anything in traefik as long as your certificate works for the hosts.

**Comment by hrdcdr** [comment]
@ArchiFleKs thank you for a detailed response. Your article has proved very useful :)

**Comment by tobilarscheid** [comment]
Honestly I don't really feel like this should be closed. Are there no plans on supporting the ingress tls definition in the future?

**Comment by gugahoi** [comment]
Any updates?
