### ISSUE TITLE
HTTP basic auth per frontend

### ISSUE THREAD

**Issue by ArchiFleKs** [containous/traefik#751]
Hi, I think it has been asked before but how would you implement http auth basic on a per backend basis ? Currently it is only on the entrypoint.

**Comment by ViViDboarder** [comment]
Do you mean per frontend? 

It was discussed on a previous PR that was merged (#547), but it's probably worth tracking Basic Auth for Fronteneds on a new issue.

**Comment by ArchiFleKs** [comment]
Yes what I meant was on a per host basis for exemple so yes per frontends and not just entrypoints

**Comment by SantoDE** [comment]
I hope to have some time soon again. This is one of the first features I'd contribute then :)

**Comment by Starefossen** [comment]
This would be a very welcome enhancement, I have been poking around in the træfik source code to see if I can make this myself - but I lack the sufficient go knowledge to make this on my own 😢

**Comment by damonpetta** [comment]
+1

**Comment by j0hnsmith** [comment]
There's lots of discussion in #547 but it should be continued here. 

Can the title be edited to say "HTTP basic auth per frontend" as that's what would satisfy most of the requests for this behaviour.

**Comment by scher200** [comment]
Hi there,
I am learning go, so please help out.
I found this peace of go code to do basic auth. Does anyone know where to puzzle it in?
```
func basicAuth(username, password string) string {
  auth := username + ":" + password
   return base64.StdEncoding.EncodeToString([]byte(auth))
}

func redirectPolicyFunc(req *http.Request, via []*http.Request) error{
 req.Header.Add("Authorization","Basic "+basicAuth("username1","password123"))
 return nil
}

def main() {

  client := &http.Client{
    Jar: cookieJar,
    CheckRedirect: redirectPolicyFunc,
}

req, err := http.NewRequest("GET", "http://localhost/", nil)
    req.Header.Add("Authorization","Basic "+basicAuth("username1","password123"))

    resp, err := client.Do(req)
}
```

**Comment by joshuacox** [comment]
I'd like to +1 on this being a necessary feature

**Comment by scher200** [comment]
@joshuacox could you maybe point me in the right direction. Where to a label influenced function like this?

**Comment by joshuacox** [comment]
well where to puzzle that bit of code in I'm not so certain.  But if you merely need an http auth in front of a dev project or something else that does not have it's own auth you can do as I suggested in [referenced issue](https://github.com/rawmind0/rancher-traefik/issues/31) and place an nginx container in front of the webapp you are adding auth to, e.g.:

internet -> traefik -> httpAuth nginx -> mywebappcontainer

btw I have yet to learn Go, but I believe the Caddy server is written in Go (which is very similar to traefik) and it does have basic auth:

https://caddyserver.com/docs/basicauth

perhaps looking at their code might be illuminating for you @scher200 , let us know if you make progress

**Comment by scher200** [comment]
hmm, thats true, maybe later in my go career i'll give it another try

**Comment by SantoDE** [comment]
hey @scher200, @joshuacox , @j0hnsmith and others,

I've just put up a PR with a basic implementation of that :-)

**Comment by SAprelov** [comment]
Actually IMHO I can suggest a workaround till we waiting @SantoDE PR. It`s relatively safe only with HTTPs.
You can use this config
`
  [frontends.frontend1]
    backend = "backend1"
  [frontends.frontend1.routes.test_1]
    rule = "Host:test.localhost;HeadersRegexp:Cookie, YOUR_PASSWORD"
`
And all you need is store pass in cookie on client machine. Go to test.localhost and use this snippet in js console:
 document.cookie="traefik=YOUR_PASSWORD"

**Comment by Yajo** [comment]
Why only basic auth? All auth should be by frontend.

**Comment by timoreimann** [comment]
@Yajo Please create additional issues for more specific auth methods.
