### ISSUE TITLE
k8s provider w/ acme?

### ISSUE THREAD

**Issue by krancour** [containous/traefik#752]
Is there a comprehensive example of using the Kubernetes provider with ACME support?

It's really awesome that Traefik can be used as an ingress controller, but so far, what I can't get it to do is use ACME to request certificates for whatever hosts are named in my ingress resources. i.e. I still need to explicitly include the following in my toml:

```
[[acme.domains]]
  main = "stilton.krancour.deis.ninja"
[[acme.domains]]
  main = "cheddar.krancour.deis.ninja"
[[acme.domains]]
  main = "wensleydale.krancour.deis.ninja"
```

Updating that configuration each time I add or modify ingresses doesn't seem ideal.

Can the ACME module work seamlessly with the k8s provider? Or is that not yet possible?

**Comment by emilevauge** [comment]
In the 1.1 version (v1.1.0-rc2 released 2 days ago), you can enable `OnHostRule` that will request a certificate from Let's Encrypt for each frontend with a `Host` rule: http://docs.traefik.io/toml/#acme-lets-encrypt-configuration

**Comment by ArchiFleKs** [comment]
@krancour I tested it with Kubernetes recently and wrote a post here : https://archifleks.github.io/blog/kubernetes-ingress/ 

basically if you are using a configmap like that It should work seamlessly : 

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-conf
data:
  traefik.toml: |
    # traefik.toml
    defaultEntryPoints = ["http","https"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      [entryPoints.http.redirect]
      entryPoint = "https"
      [entryPoints.https.auth.basic]
      users = ["klefevre:$HASH"]
      [entryPoints.https]
      address = ":443"
      [entryPoints.https.tls]
    [acme]
    email = "lefevre.kevin@gmail.com"
    storageFile = "/acme/acme.json"
    entryPoint = "https"
    onDemand = true
    onHostRule = true
    caServer = "https://acme-staging.api.letsencrypt.org/directory"
    [[acme.domains]]
    main = "archifleks.net"
```

**Comment by krancour** [comment]
@emilevauge @ArchiFleKs this looks like exactly what I am looking for. I'll take that for a test drive. Thanks!

**Comment by krancour** [comment]
This worked like a charm. Thank you guys!

**Comment by craigwillis85** [comment]
@ArchiFleKs I followed your tutorial, but unfortunately my ingress controller always fails with a `CrashLoopBackOff`

**Comment by errm** [comment]
Hi @craigwillis85 could share the logoutput from the crashed traefik?

**Comment by craigwillis85** [comment]
@errm is there an easy way to do that?

**Comment by craigwillis85** [comment]
@errm I have an issue. I'm running `kubeadm`, so trying to get logs from the pods is currently broken as of:

https://github.com/kubernetes/kubernetes/issues/22770

**Comment by ArchiFleKs** [comment]
@craigwillis85 can you log into the node and get the log from the docker daemon ? Did you use a host volume for acme storage ? One of the crash cause I've seen was du to a configuration error with acme storage

**Comment by craigwillis85** [comment]
I managed to get this working with the lets encrypt staging.

So, all is good!
