### ISSUE TITLE
dependencies installation error

### ISSUE THREAD

**Issue by mlangry** [containous/traefik#755]
During the build, dependencies installation generates errors.

`[ERROR]	Failed to set version on github.com/mailgun/manners to fada45142db3f93097ca917da107aa3fad0ffcb5: Unable to update checked out version`

`[ERROR]	Failed to set references: Unable to update checked out version (Skip to cleanup)
The command '/bin/sh -c glide install' returned a non-zero code: 1
Makefile:51 : la recette pour la cible « build » a échouée
make: *** [build] Erreur 1`

**Comment by emilevauge** [comment]
This is already fixed in branch v1.1, I will merge it in master soon :)

**Comment by mlangry** [comment]
Thanks :)
