### ISSUE TITLE
An example of using web socket with docker backend

### ISSUE THREAD

**Issue by mwaaas** [containous/traefik#762]
I want to use django-channel with traefik, django-channel handles both http and websockets. Is there an example of handling both web sockets and http in docker backend

**Comment by mwaaas** [comment]
any one who as tried this to help me with

**Comment by rllola** [comment]
Hello,

I had the same problem as you and I just made it worked so I thought I would share my solution in case someone is facing the same problem.

I used traefik:raclette in a my Dockerfile.

traefik.toml :

**Comment by ldez** [comment]
I'll close this issue, because I think the question is answered, but feel free to continue the conversation.

**Comment by jp83** [comment]
Are you having to pass through nginx to help resolve the issue, or that's just part of your app?  I'm having the same problem with WebSockets through traefik.  The app works if I pass ports directly from the docker container, but not through traefik.  I was on 1.3.2 and just updated to 1.3.3.
