### ISSUE TITLE
Stats not consistant in docker swarm mode with >1 replica

### ISSUE THREAD

**Issue by sunnysideocean** [containous/traefik#763]
Hi,

I'm deploying traefik on docker swarm mode, with more than one instance (e.g. replica 3)

```
docker service create \
    ...
    --replicas 3 \
    --name traefik \
    traefik:v1.1.0-rc2
```

How, when I open the health UI, graphs (e.g. "Total Status Code Count") are fluctuating.

I assume that this is because docker routes the UI to different instances of traefik.

Is there any way to have one holistic view on all stats in the cluster?

**Comment by emilevauge** [comment]
Hi @sunnysideocean, indeed, we don't have any centralized metrics for now. As a workaround, I suggest to export traefik's metrics into a tool like Prometheus to get a global view.

**Comment by sunnysideocean** [comment]
OK but would that be possible at all? Because even the requests to Traefiks API would be distributed accross the swarm instances as far as I know...? So if this is the case, then there would be no way to Access the stats from a specific traefik Container instance...

**Comment by ldez** [comment]
I'll close this issue, because I think the question is answered, but feel free to continue the conversation.
