### ISSUE TITLE
Build error with clean checkout from master

### ISSUE THREAD

**Issue by skeptomai** [containous/traefik#769]
Clean checkout of master branch, running `make binary`

`[INFO] --> Setting version for gopkg.in/mgo.v2 to 29cc868a5ca65f401ff318143f9408d02f4799cc.
[INFO]  --> Setting version for gopkg.in/fsnotify.v1 to a8a77c9133d2d6fd8334f3260d06f60e8d80a5fb.
[ERROR] Failed to set references: Unable to update checked out version (Skip to cleanup)
The command '/bin/sh -c glide install' returned a non-zero code: 1
Makefile:51: recipe for target 'build' failed
make: *** [build] Error 1
`

I can start searching about inside the container, but wanted to check if I'd missed something silly first.  I have read contributing.md.

**Comment by nathan-osman** [comment]
No, you're not the first one to notice this. I've left a note on Slack for the developers. The error itself is a bit unusual since the commit with that hash is still accessible from the repository.

**Comment by emilevauge** [comment]
Hi @skeptomai @nathan-osman, it should be fixed by #773

**Comment by skeptomai** [comment]
Merci.  That does seem to fix it for me.  I'm new to the codebase, so I don't see the equivalent of a 'clean' target in the makefile though, to ensure I'm really safe.
