### ISSUE TITLE
HTTP Basic Auth support

### ISSUE THREAD

**Issue by leonfs** [containous/traefik#77]
First of all I wanted to say that the project looks very good. Congratulations and keep up the good work.

Second: I wasn't able to find any documentation/information about HTTP Basic Auth setup.

Does the tool support it at all?

**Comment by emilevauge** [comment]
Hi @leonfs, there is no basic auth for now, but it could be added quite easily ;)

**Comment by altvnk** [comment]
+1, per backend auth with groups of users

**Comment by metalseargolid** [comment]
+1 this would be fantastic

**Comment by WTFKr0** [comment]
Hi

Any news on that feature ?
Ideally, I want to protect the dashboard with ldap auth, filter by user
Ideally ++, I want to protect the frontend rules with some auth too, each apart from each other

Thanx

**Comment by WTFKr0** [comment]
For my case, I can set an nginx reverse proxy with auth ldap in front of my traefik.
It seems to work very well

**Comment by aparcar** [comment]
Any progress on implementing LDAP support?

**Comment by svscorp** [comment]
@aparcar do you mean to act as a single-sign on (combining with http basic auth)? That would be great.

@WTFKr0 do you have anything on backend that uses ldap auth as well? (I believe it should be passed to the tool from NGinx) I am curious, did you achieve stability? I am facing issue with continuous `closed keepalive connection` and `client closed connection while waiting for request` messages. Looking to Traefik to replace it.
> For my case, I can set an nginx reverse proxy with auth ldap in front of my traefik.
> It seems to work very well

@ldez @emilevauge Hi Ludovic, Emile. Is there indeed a plan to include LDAP support in Traefik?
