### ISSUE TITLE
docker inside travis isn't changed

### ISSUE THREAD

**Issue by guilhem** [containous/traefik#770]
Inside travis build context, we are trying to change docker version but it appear to change only "client" part. Server part isn't updated

https://travis-ci.org/containous/traefik/jobs/170125041#L274

```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64
Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        2016-07-28T22:00:36.714318713+00:00
 OS/Arch:      linux/amd64
```

If this is not a problem... we can remove all the stuff done to set docker version (and so speedup build part)

**Comment by errm** [comment]
Confirmed that we do indeed seem to be running an incorrect version on travis.

I think we would like to test suff against a number of docker versions, @emilevauge wdyt, should we fix this?

**Comment by vdemeester** [comment]
It's more https://travis-ci.org/containous/traefik/jobs/170125041#L2199 that is important (than the other line). It's weird, it used to work… I'll have to take a look at it...

**Comment by WTFKr0** [comment]
Hi,

```
sudo curl https://get.docker.com/builds/Linux/x86_64/docker-${DOCKER_VERSION} -o /usr/bin/docker
```
just update the client binary
Apparently, you have to update dockerd daemon by apt itself like that : 
https://graysonkoonce.com/managing-docker-and-docker-compose-versions-on-travis-ci/

**Comment by guilhem** [comment]
https://github.com/containous/traefik/pull/843/commits/1481d655f11b1b3ca26db4b535f11322d9aa1909 fix it
