### ISSUE TITLE
Support Opentracing

### ISSUE THREAD

**Issue by errm** [containous/traefik#771]
OpenTracing http://opentracing.io/ is an open standard for instrumenting code for distributed tracing.  They have a library for go https://github.com/opentracing/opentracing-go.

It does not on the face of it seem too difficult, but we should probably have a think about what architecture would support this and better metric gathering in a clean way.

I have no experience with such a tool in production so it would be good to get some views from anyone who is?

**Comment by Vlaaaaaaad** [comment]
Any updates on this? https://github.com/containous/traefik/issues/390 also seems inactive.

**Comment by pieterbreed** [comment]
We have to implement distributed tracing in our environment. opentracing seems like a nice vendor-neutral take on the problem. There are good open-source tools that work with this (OpenZipKin and jaeger). if traefik had first-class support for this, it could become a part of the toolchain. [Here is a blurb on that.](http://opentracing.io/documentation/pages/instrumentation/common-use-cases.html)

> OSS Services: Beyond embedded libraries, entire OSS services may adopt OpenTracing to integrate with distributed traces initiating in – or propagating to – other processes in a larger distributed system. For instance, an HTTP load balancer may use OpenTracing to decorate requests, or a distributed key:value store may use OpenTracing to explain the performance of reads and writes.

**Comment by AlmogBaku** [comment]
@emilevauge
