### ISSUE TITLE
traefik-1.1.0-rc1: build error

### ISSUE THREAD

**Issue by duanyanli** [containous/traefik#781]
Try to build traefik-1.1.0-rc1 source
got the following error when "RUN glide install"

[INFO]  --> Setting version for github.com/mattn/go-shellwords to 525bedee691b5a8df547cb5cf9f86b7fb1883e24.
**[ERROR] Failed to set version on github.com/mailgun/manners to fada45142db3f93097ca917da107aa3fad0ffcb5: Unable to update checked out version**
...
[INFO]  --> Setting version for gopkg.in/mgo.v2 to 29cc868a5ca65f401ff318143f9408d02f4799cc.
[ERROR] Failed to set references: Unable to update checked out version (Skip to cleanup)
The command '/bin/sh -c glide install' returned a non-zero code: 1
make: **\* [build] Error 1

How to solve the issue?
I want to add more traceable log to debug traefik configuration failure issue.

**Comment by TerraTech** [comment]
I was able to build v1.1.0-rc3 from source without any problems, except for one very minor glitch: https://github.com/containous/traefik/pull/788

**Comment by emilevauge** [comment]
Yep, this has been fixed, closing this for now :)
