### ISSUE TITLE
There is no doc about how to pronounce "traefik"

### ISSUE THREAD

**Issue by alvaroaleman** [containous/traefik#795]
When telling others about traefik, I'd like to properly pronounce it. t would be helpful if there was a short note about that in the docs.

**Comment by emilevauge** [comment]
I will add some help on this 😉
We simply say traffic, written træfɪk using the international phonetic alphabet.

**Comment by michaelkrog** [comment]
Only obstacle be that not everyone have `æ` on their keyboard - like here in Scandinavia! (Muhahaha) 😄

**Comment by ldez** [comment]
Fix by #1067
