### ISSUE TITLE
cannot access webui/dashboard 

### ISSUE THREAD

**Issue by ArchiFleKs** [containous/traefik#796]
I'm using latest experimental on Kubernetes, I'm getting this on port 8080 : 
![screenshot from 2016-11-03 11-22-51](https://cloud.githubusercontent.com/assets/1276073/19962468/0a8576ee-a1b8-11e6-842d-9171ba9640af.png)

**Comment by emilevauge** [comment]
Maybe due to an error in `make binary` target: https://travis-ci.org/containous/traefik/jobs/172521101

**Comment by deepthawtz** [comment]
adding the term dashboard so this comes up in Issue search, I missed this

**Comment by SantoDE** [comment]
Hey folks, 

I just submited a bugfix :) Waiting for the others to review my changes.

**Comment by rrichardson** [comment]
Glad to know I wasn't crazy :)

**Comment by emilevauge** [comment]
Fixed by #829
