### ISSUE TITLE
Access Traefik WebUI in HTTP (+ authentication)

### ISSUE THREAD

**Issue by giopas** [containous/traefik#797]
Hi,

I am discovering this great peace of code and I would like to know if it would be possible to access to the WebUI in HTTP.

Indeed I have some problems to access non standard ports (i.e. other than 80, 443 and 8080) from where I am testing, therefore I am temporary using a simple Apache reverse proxy to access the Traefik WebUI. My intention is to understand how Traefik works and then replace all my existing reverse proxies with Traefik.

By now, when I tries to access Traefik through reverse proxy (which however for some reasons currently only works on port 80), I - unsurprisingly - receive the following error:

    Bad Request
    
    Your browser sent a request that this server could not understand.
    Reason: You're speaking plain HTTP to an SSL-enabled server port.
    Instead use the HTTPS scheme to access this URL, please.

Can you please tell me if it possible to change such behavior and make the WebUI accessible through HTTP? In such a way the reverse proxy will work and I can make all the tests and slowly move from Apache reverse proxy to Traefik.

I see from the configuration file that there is the following section:
```toml
    ################################################################
    # Web configuration backend 
    ################################################################ 
    # Enable web configuration backend  
    # 
    # Optional 
    #  
    # [web] 
     
    # Web administration port 
    # 
    # Required
    #  
    # address = ":8080" 
        
    # SSL certificate and key used
    # 
    # Optional
    # 
    # CertFile = "traefik.crt"
    # KeyFile = "traefik.key"
    # 
    # Set REST API to read-only mode  
    # 
    # Optional
    # ReadOnly = false
```
Can/how should I edit it in order to have access to the WebUI in HTTP mode? 

Finally, is it possible to have/enable a login screen to access Traefik WebUI? How to do so?

Thanks in advance

**Comment by SantoDE** [comment]
Hey @giopas,

the WebUI is accessible by HTTP only. As long as you don't set the CertFile and KeyFile setting, it's plain HTTP. That should work out.

Having the WebUI protected by Basic Auth is only possible with the most current [release-candidate](https://github.com/containous/traefik/releases/tag/v1.1.0-rc3) , or the experimental docker tag from [here](https://hub.docker.com/r/containous/traefik/).

Enabling the WebUi is then just a matter of setting the correct value to the .toml file. Have a look at the [docs](https://docs.traefik.io/toml/), it will help you out :)

**Comment by SantoDE** [comment]
Hey @giopas,

did you manage to solve your problem or do you need any more help? Is there any further way to assist you?

**Comment by giopas** [comment]
Hi SantoDe,

Thank you for your reply.

With the support of a very patient person ( :-) ), I have created two files files and some configuration.

Here is an example (to simplify, I have only enabled HTTP by now):

traefik.toml

```
################################################################
# Global configuration
################################################################

# Entrypoints definition

[entryPoints]
	[entryPoints.http]
		address = "192.168.1.3:80"
#	[entryPoints.http.redirect]
#		entryPoint = "https"
#	[entryPoints.https]
#		address = "192.168.1.3:443"
#	[entryPoints.https.tls]
#	[[entryPoints.https.tls.certificates]]
#	CertFile = "/share/CACHEDEV1_DATA/.qpkg/Traefik/certificate-xxxx.crt"
#	KeyFile = "/share/CACHEDEV1_DATA/.qpkg/Traefik/20160901_xxxx.key"

################################################################
# Web configuration backend
################################################################

# Enable web configuration backend
#
# Optional
#
	[web]

# Web administration port
#
# Required
#
	address = ":8181"

# SSL certificate and key used
#
# Optional
#
# CertFile = "traefik.crt"
# KeyFile = "traefik.key"
#
# Set REST API to read-only mode
#
# Optional
	ReadOnly = false

################################################################
# File configuration backend
################################################################

# Enable file configuration backend
#
# Optional
#
	[file]

# Rules file
# If defined, traefik will load rules from this file,
# otherwise, it will load rules from current file (cf Sample rules below).
#
# Optional
#
	filename = "servers.toml"

# Enable watch file changes
#
# Optional
#
	watch = true
```
And this is an extract of my servers.toml

```
loglevel = "DEBUG"

[backends]
	## NAS access
		[backends.bigqnap]
			[backends.bigqnap.servers.server1]
			url = "http://127.0.0.1:8080"
		[backends.littleqnap]
			[backends.littleqnap.servers.server1]
			url = "http://192.168.1.2:8080"
	## Traefik
		[backends.traefik]
			[backends.traefik.servers.server1]
			url = "http://127.0.0.1:8181"
	## Router
		[backends.router]
			url = "https://192.168.1.1"
	## littleqnap installed applications
		[backends.pydio]
			[backends.pydio.servers.server1]
			url = "http://192.168.1.2/Pydio"
		[backends.sonarr]
			[backends.sonarr.servers.server1]
			url = "http://192.168.1.2:8989"
	## External sites
		[backends.pastebin]
			[backends.pastebin.servers.server1]
			url = "http://pastebin.com"
#			[backends.gmail] # <- how is the right way to do so (if it is possible)?
#			[backends.gmail.servers.server1]
#			url = "https://mail.google.com"

[frontends]
	## QTS access
		[frontends.bigqnap]
			backend = "bigqnap"
			entrypoints = ["http"]
			[frontends.bigqnap.routes.bigqnap_1]
			rule = "Host:bigqnap.mydomain.com"
		[frontends.littleqnap]
			backend = "littleqnap"
			entrypoints = ["http"]
			[frontends.littleqnap.routes.littleqnap_1]
			rule = "Host:nas.mydomain.com"
	## Traefik
		[frontends.traefik]
			backend = "traefik"
			entrypoints = ["http"]
			[frontends.traefik.routes.traefik_1]
			rule = "Host:traefik.mydomain.com"
	## Router
		[frontends.router]
			backend = "router"
			entrypoints = ["http"]
			[frontends.router.routes.router_1]
			rule = "Host:router.mydomain.com"
	## littleqnap installed applications
		[frontends.pydio]
			backend = "pydio"
			entrypoints = ["http"]
			[frontends.pydio.routes.pydio_1]
#			rule = "Host:file.domainone.com" # <- how can I use two different domains? Should I create an entire new backend and frontend section?
			rule = "Host:file.domaintwo.com"
		[frontends.sonarr]
			backend = "sonarr"
			entrypoints = ["http"]
			[frontends.sonarr.routes.sonarr_1]
			rule = "Host:sonarr.mydomain.com"
	## External sites		 
		[frontends.pastebin]
			backend = "pastebin"
			entrypoints = ["http"]
			[frontends.pastebin.routes.pastebin_1]
			rule = "Host:pastebin.mydomain.com"
#		[frontends.gmail]
#			backend = "gmail"
#			entrypoints = ["https"]
#			[frontends.gmail.routes.gmail_1]
#			rule = "Host:gmail.mydomain.com"
```
The problem now is that, whenever I try to reach my subdomains I get "Connection refused". For example I can access (via 192.168.1.3:80) the Traefik WebUI, but I if I try to do so via traefik.mydomain.com, I get "Connection Refused".

Where could it be the problem there? I really don't have any clue of it!

Besides I also included two questions in the servers file. :)

Thanks a lot for your work and support,

giopas

**Comment by traefiker** [comment]
I'll close the issue due to inactivity but feel free to re-open if needed.
