### ISSUE TITLE
traefik, coreos, rancher

### ISSUE THREAD

**Issue by peceka** [containous/traefik#801]
Hi,

I run traefik on coreos machine (with rancher).
On the same machine I've started stack with apache and php application. Stack is running with labels:
traefik.domain=test.dev
traefik.enable=stack
traefik.host=NAME
traefik.port=80

And when I display traefik admin dashboard I can see on fronted where Route:services is registered with correct Rule: Host:NAME.test.dev, but on backend column I've got only information about backend without any Server/URL/Weight rules.
In traefik log I've:

time="2016-11-03T21:43:49Z" level=debug msg="File event:\"/opt/traefik/etc/rules.toml\": CREATE"
time="2016-11-03T21:43:49Z" level=debug msg="Configuration received from provider file: {\"backends\":{\"NAME\":{\"circuitBreaker\":{\"expression\":\"NetworkErrorRatio() \\u003e 0.5\"},\"loadBalancer\":{\"method\":\"drr\"}}},\"frontends\":{\"NAME\":{\"entryPoints\":[\"http\",\"https\"],\"backend\":\"NAME\",\"routes\":{\"service\":{\"rule\":\"Host:NAME.test.dev\"}},\"passHostHeader\":true,\"priority\":0}}}"
time="2016-11-03T21:43:49Z" level=debug msg="Last file config received more than 2s, OK"
time="2016-11-03T21:43:49Z" level=debug msg="Creating frontend NAME"
time="2016-11-03T21:43:49Z" level=debug msg="Wiring frontend NAME to entryPoint http"
time="2016-11-03T21:43:49Z" level=debug msg="Creating route service Host: NAME.test.dev"
time="2016-11-03T21:43:49Z" level=debug msg="Creating backend NAME"
time="2016-11-03T21:43:49Z" level=debug msg="Creating load-balancer drr"
time="2016-11-03T21:43:49Z" level=debug msg="Creating circuit breaker NetworkErrorRatio() > 0.5"
time="2016-11-03T21:43:49Z" level=debug msg="Wiring frontend NAME to entryPoint https"
time="2016-11-03T21:43:49Z" level=debug msg="Creating route service Host: NAME.test.dev"
time="2016-11-03T21:43:49Z" level=debug msg="Reusing backend NAME"
time="2016-11-03T21:43:49Z" level=info msg="Server configuration reloaded on :8080"
time="2016-11-03T21:43:49Z" level=info msg="Server configuration reloaded on :8443"

any tips what I've done wrong?

regards,
p.
<img width="527" alt="zrzut ekranu 2016-11-03 22 47 39" src="https://cloud.githubusercontent.com/assets/607428/19986582/9892345e-a217-11e6-9573-90936780ca7f.png">

**Comment by SantoDE** [comment]
Hey :)

Did you set a healthcheck in Rancher for the Service which should act as backend? Only Services with a healthcheck and Status healthy will be populated.

**Comment by peceka** [comment]
Hey :)

No, I didn't. Thank you! :-)
Could you please point me to docs where it is written that health check is important to allow treafik to add backend? I would like to know where I've skipped or misunderstand requirements.

Regards!
p.

**Comment by SantoDE** [comment]
Hey @peceka ,

atleast it's written in this git repository of the traefik / rancher integration [here](https://github.com/rawmind0/rancher-traefik). I'm not sure if it's written down elsewhere :)

Regards
