### ISSUE TITLE
docs: deployment doesn't work

### ISSUE THREAD

**Issue by philips** [containous/traefik#808]
Steps to reproduce:

1. Read docs https://docs.traefik.io/user-guide/kubernetes/
2. Deploy traefik `kubectl create -f https://raw.githubusercontent.com/containous/traefik/master/examples/k8s/traefik.yaml`
3. Get error: `"message": "container \"traefik-ingress-lb\" in pod \"traefik-ingress-controller-3665949876-ei7h1\" is waiting to start: trying and failing to pull image",`

**Comment by emilevauge** [comment]
Hi @philips,
We are in the process of releasing `v1.1.0` but we only the `v1.1.0-rc3` has been released for now.
In the meantime, you can replace `image: traefik:v1.1.0` by `image: traefik:v1.1.0-rc3` in `https://raw.githubusercontent.com/containous/traefik/master/examples/k8s/traefik.yaml` :)

**Comment by errm** [comment]
We should do something to automatically update version numbers in example files when we release a new version...

**Comment by emilevauge** [comment]
Indeed, or simply use the latest.

**Comment by philips** [comment]
Please don't use latest for software. It makes debugging so annoying.

**Comment by errm** [comment]
For now this fixes the immediate issue of broken examples.

This example is intended mainly to support the guide at http://docs.traefik.io/user-guide/kubernetes/ i.e. just kicking the tires on minikube.
I think we need to add some extra documentation how to do production deployments properly too.

The documentation site updated with the releases, and the code snippets there should be correct. I think if we point the urls at the current stable release branch then stuff should work out ok.

We should make a script or something to check all the versions line up.

**Comment by ldez** [comment]
I'll close this issue, because I think the question is answered, but feel free to continue the conversation.
