### ISSUE TITLE
ACME challenge bug

### ISSUE THREAD

**Issue by OndroNR** [containous/traefik#810]
I just deployed v1.1.0-rc3 with single LE certificate for ~10 domains. At first it had problem with validating one domain for some time:

```
time="2016-11-07T09:06:34Z" level=debug msg="Challenge GetCertificate redacted.com"
time="2016-11-07T09:06:34Z" level=debug msg="ACME got nothing redacted.com"
```

This domain had live traffic, that cannot be stopped.

After a while (minutes) it validated and created certificate. But I still see this in log appearing every few seconds even after restarting traefik:
```
time="2016-11-07T09:43:32Z" level=debug msg="Challenge GetCertificate redacted.com"
time="2016-11-07T09:43:32Z" level=debug msg="ACME got domain cert redacted.com"
```

**Comment by emilevauge** [comment]
@OndroNR We need a bit more details on your config: TOML file, and all you DEBUG logs.

**Comment by OndroNR** [comment]
I hope it will help. Log is from few minutes of already running https://gist.github.com/OndroNR/5273d5b02d6ef01fd1e2e711baa2e5a8

**Comment by djmaze** [comment]
Had the same problem. After a few tries (changing the requested host name via the frontend rule) it validated successfully. 

LE is probably having intermittent problems: https://github.com/letsencrypt/boulder/issues/1217

**Comment by ldez** [comment]
I'll close the issue due to inactivity but feel free to re-open if needed.

**Comment by cretz** [comment]
@ldez - I too am having this issue. The slack invites are either not being sent out or are being sent out slow. Shall I create a new issue with detailed information or can you reopen this one and I'll put the logs and what not here?

**Comment by cretz** [comment]
Ok, this appears to be due to lack of `[[acme.domains]]` and/or me using `onHostRule` instead of `OnHostRule` (not sure which change fixed it). The documentation conflicts...one part has an example with `OnHostRule` (https://docs.traefik.io/user-guide/docker-and-lets-encrypt/), another has an example with `onHostRule` (https://docs.traefik.io/configuration/acme/). Also, is `[[acme.domains]]` required?

**Comment by ldez** [comment]
@cretz `[[acme.domains]]` required only if you want provide SANs.

**Comment by cretz** [comment]
@ldez - how about the `OnHostRule`/`onHostRule` inconsistency...or whether `https` entrypoint has to be setup on a frontend for the cert to be created?

**Comment by ldez** [comment]
Thanks for your interest in Traefik 😃 

This issue is closed. Please discuss this in :
- the [Traefik community Slack channel](https://traefik.herokuapp.com)
