### ISSUE TITLE
Content-Type "text/event-stream" not propagated properly with version 1.1.0-rc3

### ISSUE THREAD

**Issue by git-oca** [containous/traefik#819]
Hello, 
The Content-Type "text/event-stream" seems not to be propagated properly with version 1.1.0-rc3

Here is my test case:

I use a simple python server like that one:

```python
from flask import Response
from flask import Flask
app = Flask(__name__)

@app.route('/hello')
def hello():
    return Response("Hello\n", mimetype='text/event-stream')

if __name__ == "__main__":
    app.run(host='0.0.0.0', port=8085)
```

when calling the application without traefik, the content type is 'text/event-stream' as expected:

```
root@9a41b8a25543:/oca# curl -i localhost:8085/hello
HTTP/1.0 200 OK
Content-Type: text/event-stream; charset=utf-8
Content-Length: 6
Server: Werkzeug/0.11.10 Python/2.7.9
Date: Tue, 08 Nov 2016 15:17:54 GMT

Hello
root@9a41b8a25543:/oca#
```

but when I use traefik in between to redirct port 8085 to 80, the Content-Type then become 'text/plain'.

```
root@9a41b8a25543:/oca# curl -i localhost:80/hello
HTTP/1.1 200 OK
Date: Tue, 08 Nov 2016 15:22:55 GMT
Content-Type: text/plain; charset=utf-8
Transfer-Encoding: chunked

Hello

``` 
I also tested with the fix #592 and this is not working either  (but this case was working with version 1.1.0-rc2 which doesn't contains fix #592 )
 
Notice that other Content-type seems to work fine. for instance:

```python
...
return Response("Hello\n", mimetype='application/json')
...
```

is working fine

```
root@9a41b8a25543:/oca# curl -i localhost:80/hello
HTTP/1.1 200 OK
Content-Length: 6
Content-Type: application/json
Date: Tue, 08 Nov 2016 15:26:04 GMT
Server: Werkzeug/0.11.10 Python/2.7.9
```

**Comment by git-oca** [comment]
Not sure yet, but I think this is not working when "Content-Type" contains also the charset like that:
"text/event-stream; charset=utf-8"

**Comment by ldez** [comment]
I'll close the issue due to inactivity but feel free to re-open if needed.
