### ISSUE TITLE
Support active health checking like HAProxy

### ISSUE THREAD

**Issue by klausenbusk** [containous/traefik#824]
Hello

It could be very useful if Traefik had a option similar to HAProxy [httpchk](https://cbonte.github.io/haproxy-dconv/1.7/snapshot/configuration.html#4-option%20httpchk) option.
The current solution (circuitbreaker) isn't enough, as it depends on a client request to be made first and that it wouldn't necessarily trigger if only ex. dynamic pages request fails.
Adding a `httpchk` option also allow clients to create a custom health script they can run on every server and thereby easily define what a healthy service is.

Kristian

**Comment by errm** [comment]
We have mainly supported this via providers, eg in the docker and kubernetes providers.

@klausenbusk what provider are you using?

**Comment by klausenbusk** [comment]
@errm I gonna use etcd to configure traefik. We currently use vulcand, but we need websocket support and I'm not gonna switch lb in prime time :)

**Comment by errm** [comment]
Yeah, I think that it does make sense to have this functionality in traefik, even if it is duplicated by most of the orchestration tools, for cases like this where people are rolling there own thing...

**Comment by thorerik** [comment]
Would be very handy for example in a Riak CS deployment to distribute Stanchion and have Træfik check http://stanchionhost/ping and check that it get's pong back, since you can only have one stanchion active at any one moment.

**Comment by garetw** [comment]
We have a use-case here as well. It makes it nice for organizations that are in the process of incremental change from something like HAProxy.

**Comment by klausenbusk** [comment]
It seems like this has already been merged:
https://github.com/containous/traefik/pull/918
Just missing docs and test: https://github.com/containous/traefik/pull/1132

**Comment by klausenbusk** [comment]
Closing, included in v1.2.0-rc1.
