### ISSUE TITLE
1.1.0-rc4 dashboard UX not displaying

### ISSUE THREAD

**Issue by deepthawtz** [containous/traefik#828]
I just deployed the latest rc4 and when I hit `/dashboard/` I only see:

<img width="633" alt="screen shot 2016-11-11 at 7 02 45 am" src="https://cloud.githubusercontent.com/assets/31030/20219203/245940e8-a7dd-11e6-8201-03deadab1256.png">

**Comment by emilevauge** [comment]
Duplicate of #796

**Comment by emilevauge** [comment]
Thanks for reporting @deepthawtz, I will fix this ASAP.
