### ISSUE TITLE
webDAV

### ISSUE THREAD

**Issue by giopas** [containous/traefik#832]
Hi,

I wonder to know if it is possible to access webDAV resources (in my case a KeyPass database) in a webDAV share behind a traefik reverse proxy.

This seems to be similar to this issue [1] relating to apache.

If so, how to do so?

Thank you,

giopas

[1] http://stackoverflow.com/questions/1110710/webdav-behind-a-reverse-proxy

**Comment by errm** [comment]
I don't think there is anything in particular that should stop this from working... There are a few complexities to webdav so there could be some issues...
Why not try it out? If there are any issues we can try to fix them.

**Comment by giopas** [comment]
Hi errm,

thanks for your reply. I try to explain my set-up.

I want to access a KeyPass db in a webDAV folder located in a different server (within the same LAN) where Traefik is installed.

The file is directly accessible on: http://10.0.0.3/DAV/Pass.kdbx

I want then to create a reverse proxy with Traefik to access to this file.

I am thinking of doing this (but it does not work):

```
[backends.general]
    [backends.general.servers.server1]
    url = "http://10.0.0.3"
    
[frontends.webdav]
    backend = "general"
    priority = 99
    passHostHeader = true
    entrypoints = ["http"]
    [frontends.webdav.routes.webdav_1]
    rule = "Host:webdav.mydomain.com;Path:/DAV/"
```

How to do so in the right way? Thanks!

**Comment by giopas** [comment]
@errm can you please help me on this or suggest me where to look at? Thanks in advance!

**Comment by errm** [comment]
I think you are just missing the port from the backend url...

Could you paste the log if you have any more issues?

**Comment by giopas** [comment]
Hi @errm , I managed to make webDAV partially work:

```
[backends.general]
    [backends.general.servers.server1]
    url = "http://10.0.0.3:80"

[frontends.webdav]
    backend = "general"
    priority = 99
    passHostHeader = true
    entrypoints = ["http"]
    [frontends.webdav.routes.webdav_1]
    rule = "Host:webdav.mydomain.com"
```

However this is not the correct way as I need to go to http://webdav.mydomain.com/DAV/myfile.kdbx to access the resource, whether my intention is to directly go to http://webdav.mydomain.com/myfile.kdbx.

How can I do this?

By the way I have activated the log in traefik.toml as follows but I have no information saved in the log:

```
# Traefik logs file                                                                                             
# If not defined logs to stdout                                                                                 
traefikLogsFile = "traefik.log" 
loglevel = "DEBUG"
```

Thanks

**Comment by giopas** [comment]
Hi there,

anyone ( @errm maybe) could help on how to use a subdomain to redirect to a specific subfolder?

In my example above I want to access to reverse proxy http://10.0.0.3:80/DAV/ to http://webdav.mydomain.com/

How to do so?

Thank you,

giopas

**Comment by jacksgt** [comment]
Hi there,

I'm also trying to use Traefik with Nextcloud (the official `nextcloud:12-apache` image), web access works fine, but I'm having trouble with Cal/CardDAV, e.g. with DAVDroid:
```
EXCEPTION:
at.bitfire.dav4android.exception.InvalidDavResponseException: Expected 207 Multi-Status, got 200
```

**Comment by jacksgt** [comment]
Just a quick heads up, my issue is/was actually related to https://github.com/containous/traefik/issues/2351 .

Reverting to `1.4.0` fixed the issue for now.

**Comment by traefiker** [comment]
I'll close the issue due to inactivity but feel free to re-open if needed.
