### ISSUE TITLE
Docker Swarm Mode is not Load balancing (dnsrr)

### ISSUE THREAD

**Issue by pascalandy** [containous/traefik#833]
Hey folks,

I'm testing the load-balancer (from Traefik) and when I refresh the webpage or do `curl -H Host:$ENV_DOMAIN1 http://$NODE_IP`, the system only use the first container. 

I don't understand why.

```
ENV_DOMAIN1=iamfoo.example.com
ctn1_NAME=iamfooA
ENV_NET_STATIC=net_static

docker service create \
--name $ctn1_NAME \
--network $ENV_NET_STATIC \
--restart-condition any \
--replicas 2 \
--constraint node.labels.apps_accepted==yes \
--label traefik.frontend.rule=Host:$ENV_DOMAIN1 \
--label traefik.docker.network=$ENV_NET_STATIC \
--label traefik.port=80 \
katacoda/docker-http-server
```

I tried with:
- traefik:v1.1.0-rc4
- traefik:v1.1.0-rc3
- traefik:v1.1.0-rc2
- traefik:v1.1.0-rc1

**Keep alive** - I don't think it's related to a keep alive situation like https://github.com/containous/traefik/issues/727 or https://github.com/containous/traefik/issues/730

**dnsrr** ([dns round-robin](https://docs.docker.com/engine/swarm/networking/#/use-dns-round-robin-for-a-service)) - I think is related to `--endpoint-mode dnsrr` not being supported at the moment :

- https://github.com/docker/docker/issues/25016#issuecomment-236741760
- https://github.com/docker/swarmkit/pull/1693#issuecomment-256215855

I would keep this issue open for documentation :)

Cheers!

**Comment by pascalandy** [comment]
I think is related to:

- https://github.com/docker/docker/issues/25016#issuecomment-236741760
- https://github.com/docker/swarmkit/pull/1693

**Comment by ldez** [comment]
I'll close the issue due to inactivity but feel free to re-open if needed.
