### ISSUE TITLE
StatsD (e.g. DataDog) support

### ISSUE THREAD

**Issue by jippi** [containous/traefik#834]
Hi,

I'm currently evaluating traefik for our internal services, and so far I'm very impressed - good job on such an easy approachable project.

I can't find any instrumentation for statsd to get runtime information into a nice UI view like datadog.

Is this something planned, or is it there already and I totally missed it somewhere?

Would like to have insights into errors, requests, errors and so forth for frontend (and maybe backend) 

`/health` do provide some information, but not in a very granular level :)

**Comment by errm** [comment]
We are planning to add prometheus metrics.

And there is also a proposal to add support for opentracing #771

**Comment by jippi** [comment]
@errm okay, so no plans to add basic statsd support? both prometheus and opentracing  are fairly new technologies, where statsd is old and wildly supported and understood :)

**Comment by errm** [comment]
At this stage I understand the plan is to add metrics using https://github.com/rcrowley/go-metrics.

This should make supporting a number of metrics systems quite simple, I think there is a client for statsd.

**Comment by enxebre** [comment]
this is partially covered now by #1022 and #1042. We'd need to add an statsD implementation analogous to Prometheus one https://github.com/containous/traefik/blob/master/middlewares/prometheus.go by using https://github.com/go-kit/kit/tree/master/metrics/statsd

**Comment by aantono** [comment]
I have a PR ready, but will probably wait till #1504 gets merged (unless there is a desire to get the changes in for 1.3 release)

**Comment by timoreimann** [comment]
We have already frozen the 1.3 branch for features (only bug fixes at this stage), so waiting should be fine. 👍

**Comment by hkaj** [comment]
Hey all,
Prometheus support is coming to Datadog and we're adding a check for Traefik using it (should be ready to use with the 5.14 release). That means auto discovery will work with Traefik, and also that these metrics will be official metrics in Datadog and not billed as custom metrics. Here's the PR for tracking: https://github.com/DataDog/integrations-extras/pull/64

That's just a heads up, StatsD instrumentation is still great for other solutions.

**Comment by ldez** [comment]
Closed by #1701
