### ISSUE TITLE
Slow WebDAV with Nextcloud

### ISSUE THREAD

**Issue by qrevel** [containous/traefik#837]
Hi,

I currently use [Nextcloud 10.0.1](https://nextcloud.com) with docker. I also use traefik 1.0.3 as a reverse proxy for all my microservices in docker. However traefik slows down the webdav connection to Nextcloud.

```
nextcloud-fpm | 172.18.0.9 - admin 13/Nov/2016:22:05:08 +0000 "MKCOL /remote.php" 201
nextcloud-nginx | 172.18.0.4 - admin [13/Nov/2016:22:05:38 +0000] "MKCOL /remote.php/webdav/litmus/frag/ HTTP/1.1" 201 0 "-" "litmus/0.13 neon/0.30.1"
traefik | time="2016-11-13T22:05:38Z" level=debug msg="Round trip: http://172.18.0.9:80, code: 201, duration: 30.299085646s tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:****"
```

When traefik is disable, litmus (webdav tester) complete in less than 5 seconds. But when it's enable, it would take more than half an hour. What can i do to use both Nextcloud webdav service and traefik ? They are two great software and it would be amazing if i can use them both at the same time.

EDIT: Also tested with 1.1.0-rc4, it didn't work.

Thanks

**Comment by fuco809** [comment]
we had on some win-clients also a performanceproblem with webdav in a reverse proxy (apache) environment, maybe a solution of your problem can help me too.

**Comment by qrevel** [comment]
I don't have any WebDAV problem with other reverse proxies (nginx and apache for example). I hope you'll find a solution for your problem.

**Comment by ldez** [comment]
I'll close the issue due to inactivity but feel free to re-open if needed.
