### ISSUE TITLE
Traefik Stats System + Prometheus Exporter

### ISSUE THREAD

**Issue by SantoDE** [containous/traefik#839]
Traefik should receive a basic stats system to gather stats about the application itself. These stats should then be exportable to backends. Our first exporter will be Prometheus

**Comment by deepthawtz** [comment]
Would this be a `/metrics` endpoint Prometheus can scrape from?

**Comment by deedubs** [comment]
I would like this to be able to return or at least some combination of metrics that would allow the calculation of these values:

**Per frontend**
- requests per second
- breakdown of response codes counts
- response times

**Per backend**
- count of healthy backends

**Comment by samart** [comment]
This would be valuable.

Requests per second
Latency
Errors

**Comment by enxebre** [comment]
this can be closed now by https://github.com/containous/traefik/pull/1022 and https://github.com/containous/traefik/pull/1042 then we can open follow up tickets to specific improvements
