### ISSUE TITLE
Still a memory leak with k8s - 1.1 RC4

### ISSUE THREAD

**Issue by rrichardson** [containous/traefik#844]
I know this was addressed in https://github.com/containous/traefik/pull/387  

I also note that somebody reported an existing leak in the new solution (back in May). 

 I am running 1.1 RC4

Here is what I'm seeing: 

![traefik](https://cloud.githubusercontent.com/assets/124171/20273665/0c3747b4-aa47-11e6-8c3a-9ba7865480f2.png)

The 2nd item in the list git the memory limit and was killed.

**Comment by emilevauge** [comment]
Ouch, can you give us more details? Which Kubernetes version are you using? Were you running traefik 1.0 before? Any difference?
/cc @containous/traefik

**Comment by rrichardson** [comment]
k8s version :  Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:10:32Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"} 

I haven't run a prior version of Traefik (at least not while monitoring and using the cluster much) 

Are there any debug/gc metrics I can pull out of Traefik to help narrow this down?

**Comment by emilevauge** [comment]
Anything in the logs?

**Comment by rrichardson** [comment]
Here's an anonymized debug log,  I'm not really sure what I'm looking for.. 

[traefik.log.gz](https://github.com/containous/traefik/files/590049/traefik.log.gz)

**Comment by errm** [comment]
Are you running a HA master with the `--leader-elect` flag set on kube-scheduler and/or kube-controller-manager ?

**Comment by rrichardson** [comment]
I am running HA with leader-elect=true on the controller-manager.

**Comment by emilevauge** [comment]
There was an old issue with event spamming, but it did not lead to a memory leak...
https://github.com/containous/traefik/issues/449

**Comment by emilevauge** [comment]
I tried to reproduce this with Kubernetes v1.4.4 and have not run into a memory leak in ours, despite the leadership election events spamming.
Another way to investigate would be to `kill -SIGABRT $PID_OF_TRAEFIK` (while traefik uses a lot of memory) and send us the stack.

**Comment by rrichardson** [comment]
I wonder if it a function of the number of services/pods.  We currently have about 70 pods across 30 services.   Either way, attached is the stack trace. 

[traefik-abrt.log.gz](https://github.com/containous/traefik/files/592199/traefik-abrt.log.gz)

**Comment by emilevauge** [comment]
@rrichardson thanks for your help on this, it will help us alot :)

**Comment by emilevauge** [comment]
Hey @rrichardson, it would be awesome if you could test with this docker image `containous/traefik:k8s`, it has been built with the fix #845.

**Comment by rrichardson** [comment]
The new image has been running for 1 hour and so far the results are encouraging.  Each pod is using about 20MB of RAM.  I don't have any pretty charts yet, but things look good so far.

**Comment by emilevauge** [comment]
@rrichardson I love what you are saying :+1:

**Comment by rrichardson** [comment]
![traefik](https://cloud.githubusercontent.com/assets/124171/20358354/5b4cd838-abe0-11e6-987a-50645d07c999.png)

**Comment by Rio** [comment]
definitely an improvement on this...

**Comment by rrichardson** [comment]
It hasn't leveled off yet, which is a bit of a concern.  However, the previous build would increase at a rate of 35MB/hour.  The current build went from 20MB to 40MB in 2.5 hours, or 8MB/hr.  I'll check again this evening to see if it has stopped increasing.

**Comment by emilevauge** [comment]
@rrichardson 
>It hasn't leveled off yet, which is a bit of a concern

Indeed...
Could you `kill -SIGABRT $PID_OF_TRAEFIK` again?

**Comment by rrichardson** [comment]
[traefik.log.gz](https://github.com/containous/traefik/files/595651/traefik.log.gz)

**Comment by emilevauge** [comment]
I updated the Docker image `containous/traefik:k8s` with another fix.
Goroutines number and memory allocation are pretty stable on my laptop:
![screenshot from 2016-11-17 14 39 13](https://cloud.githubusercontent.com/assets/6207234/20391470/d1826434-acd3-11e6-90bc-36801fc53264.png)

**Comment by rrichardson** [comment]
I've been breaking and fixing prometheus all day, so I don't have much historical data, but I have been running the new image for almost an hour, and so far.  

In the previous build, the instances were at 25MB by now,   these seem to be holding steady at 14MB.  I'll report back tomorrow. 

![traefik](https://cloud.githubusercontent.com/assets/124171/20404634/901acb1c-acba-11e6-9cad-562d7f22a7d2.png)

**Comment by rrichardson** [comment]
The latest fix definitely worked.  All 3 instances are sitting at 14MB after almost 24 hours.

**Comment by emilevauge** [comment]
@rrichardson Awesome news :) I really would like to thank you for your help on this :+1:
