### ISSUE TITLE
HTTP links turn to HTTPS Links on doc.traefik.io get started page

### ISSUE THREAD

**Issue by scor** [containous/traefik#8506]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

Cloning https://github.com/traefik/traefik/issues/8346 as the fix didn't resolve the problem (or the problem came back). 

Read quick start page: https://doc.traefik.io/traefik/getting-started/quick-start/ and click on the first link to http://localhost:8080/api/rawdata

### What did you see instead?

The hyperlink on http://localhost:8080/api/rawdata is HTTPS which make clicking on it 404.

The source HTML of that page contains the HTTPS variant even if the visible link string does not:
```
<p>You can open a browser and go to <a href="https://localhost:8080/api/rawdata">http://localhost:8080/api/rawdata</a> to see Traefik&#39;s API rawdata
```
The Github HTML rendering does not tamper with this link and it works there: https://github.com/traefik/traefik/blob/master/docs/content/getting-started/quick-start.md

Something happens when the HTML is deployed/rendered on https://doc.traefik.io/traefik/getting-started/quick-start/

### What version of Traefik are you using?

NA - this is about the public docs

### What is your environment & configuration?

NA

**Comment by traefiker** [comment]
Closed by #8507.
