### ISSUE TITLE
TLSOptions clientAuth secret do not extract CA certificate from the ca.crt key

### ISSUE THREAD

**Issue by GustavJaner** [containous/traefik#8511]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

In the Client Auth docs https://doc.traefik.io/traefik/https/tls/#client-authentication-mtls for the Kubernetes configuration, it reads
```
...
  clientAuth:
    # the CA certificate is extracted from key `tls.ca` or `ca.crt` of the given secrets.
    secretNames:
      - secretCA
```

I tried to configure the TLSOptions with a secret that _only_ has the `tls.ca` key/entry

### What did you see instead?

Error message printed, the CA certificate is not picked up and mTLS is not working.

`msg="Failed to extract CA from secret traefik-system/ca-cert: the **tls.ca** entry is missing from secret traefik-system/ca-cert" providerName=kubernetescrd tlsOption=default namespace=traefik-system`

It works fine only when the given secret contains the `tls.ca` key/entry. This is not what the documentation describes, where either of `tls.ca` or `ca.crt` of the given secrets can be used. For my case, it would be very useful if traefik could extract the CA certificate also if the secret only contains the `ca.crt` key.

### What version of Traefik are you using?

v2.4.7

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```

Add more configuration information here.
Kubernetes/K3s: v1.20.6+k3s1

### If applicable, please paste the log output in DEBUG level

`msg="Failed to extract CA from secret traefik-system/ca-cert: the **tls.ca** entry is missing from secret traefik-system/ca-cert" providerName=kubernetescrd tlsOption=default namespace=traefik-system`

**Comment by rtribotte** [comment]
Hello @GustavJaner,

Thanks for your interest in Traefik!

As you can see in the [TLSOption v2.5 documentation](https://doc.traefik.io/traefik/v2.5/routing/providers/kubernetes-crd/#kind-tlsoption), the key `ca.crt` is now supported.
