### ISSUE TITLE
consul service catalog, disable by default

### ISSUE THREAD

**Issue by jippi** [containous/traefik#854]
Hi,

I'm adding traefik to our existing, fairly big and busy consul cluster.

We want to use the consul service catalog feature, but hit a minor bump on the road.

It would be great to control in the traefik toml configuration, whether `traefik.enable=false` would be false or true by default from traefiks point of view.

e.g. in our case, we want consul services to opt *in* to traefik (`traefik.enable=true`) rather than opting *out* (`traefik.enable=false`) to avoid having a huge list of non-relevant, non-http services listed in traefik that will never be used anyway

**Comment by emilevauge** [comment]
Like what is done with `ExposedByDefault` in Docker/Mesos provider, I fully agree.

**Comment by rokka-n** [comment]
would be nice to have it implemented more logical way: e.g services are disabled by default

**Comment by psyhomb** [comment]
Is this going to be implemented any time soon?

**Comment by ldez** [comment]
@psyhomb Remember the gentle way to participate:
- add a "reaction" on the first message of the issue.
- add more useful and detailed information on the subject.
- resolve the issue by making a PR.

**Comment by psyhomb** [comment]
Sry my bad :(
