### ISSUE TITLE
Docker v1.1.0 image does not exist

### ISSUE THREAD

**Issue by jaygorrell** [containous/traefik#861]
Documentation is updated to reference a non-existent tag (v1.1.0), breaking the examples.

**Comment by mcoms** [comment]
I switched my image to [containous/traefik](https://hub.docker.com/r/containous/traefik/) to get around this for now, as directed here: https://github.com/containous/traefik-library-image/issues/3

Not sure why the official docker image lags so far behind.

**Comment by emilevauge** [comment]
I don't understand why you opened an issue for that... We have not made any announcement for the 1.1 release. Please wait for the official announcement :)

**Comment by jaygorrell** [comment]
1. Previously, the documentation referred to v1.1.0 which was an image that did not exist. This has since been changed to `latest` so we're good there.
2. Now that v1.1.0 is on the docker repository, the `latest` tag used in the documentation pulls an unreleased version.

Either way you look at it, this appears to be a valid issue. If not a "missing image" issue, it's a documentation issue.

**Comment by emilevauge** [comment]
@jaygorrell 

1. Indeed, an issue was already raised on this :)
2. It's impossible to synchronize with Docker on publishing our official image. We tagged `v1.1.0` and it took 4 days to publish the official image (a little bit longer than usual).

In the future, we will template our documentation & examples with version number, and generate it at each release. But it needs some time that we don't for now :) In the meantime, indeed, there will be a little delay between a release and the Docker image publishing.

**Comment by jaygorrell** [comment]
Completely understood and that's reasonable - I just wanted to explain since there was question around why the issue was opened, that's all! :)
