### ISSUE TITLE
Marathon & Mesos providers' GroupsAsSubDomains option broken

### ISSUE THREAD

**Issue by ryanleary** [containous/traefik#867]
Currently, the `GroupsAsSubDomains` option returns a reverse-*sorted* subdomain instead of a reverse-ordered subdomain.

As an example, if the application path is `/d/c/b/a`, the proper subdomain should be `a.b.c.d` (reversed). However, with the current implementation, the subdomain returned is `d.c.b.a` because it always returns in reverse sorted order.

**Comment by emilevauge** [comment]
Fixed by #868
