### ISSUE TITLE
digest auth example is incorrect

### ISSUE THREAD

**Issue by Cedric-Venet** [containous/traefik#869]
When I follow the example from the documentation:
```
[entryPoints]
   [entryPoints.http]
   address = ":80"
   [entryPoints.http.auth.basic]
   users = ["test2:traefik:518845800f9e2bfb1f1f740ec24f074e"]
```

I get the error:
Error starting server: Error parsing Authenticator user: test2:traefik:518845800f9e2bfb1f1f740ec24f074e" 

based on the code, I tried to replace entryPoints.http.auth.basic by entryPoints.http.auth.digest.
With this it seems to works

(I forgot to mention I am using the docker image traefik:v1.1.0)

**Comment by emilevauge** [comment]
Fixed by #900
