### ISSUE TITLE
Docker labels: allow to manage redirect from http to https

### ISSUE THREAD

**Issue by nsteinmetz** [containous/traefik#870]
Hi,

First thanks to make Traefik, a pleasure to play with and my small contribution with the [docker arm images](https://hub.docker.com/r/nsteinmetz/traefik-arm/) which are also merged with hypriot/rpi-traefik.

Back to my issue: on my servers, I have websites that cannot switch to https due to some iframe integration with some crappy partner which does not see the point with https... Anyway.

So I would like to set up at a *frontend* level the ability to redirect http to https via *docker labels*. It seems not yet possible after some tests to have as docker labels the equivalent :

```
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
```

Even for frontends within  a basic toml file, I'm not sure if it's yet supported. All samples I found are set at `[entryPonts]` level.

Thanks,
Nicolas

**Comment by valentin2105** [comment]
+1
It would be awesome to pass a label like `traefik.redirect.https=True" in services definition.

**Comment by emilevauge** [comment]
I think it's a duplicate of https://github.com/containous/traefik/issues/541 right ?

**Comment by nsteinmetz** [comment]
Hi @emilevauge 

Yes indeed ; sorry for the duplicate, I missed it (I don't know how). I close this one and will follow #541 instead.
