### ISSUE TITLE
Kubernetes connection error failed to create watch

### ISSUE THREAD

**Issue by r0bj** [containous/traefik#883]
After upgrade traefik from 1.0.3 to 1.1.0 I got error messages:

```
time="2016-11-23T15:46:36Z" level=error msg="Kubernetes connection error failed to create watch: failed to do version request: GET \"https://dev.kubernetes-controller.service.consul:6443/apis/extensions/v1beta1/ingresses\" : failed to create request: GET \"https://dev.kubernetes-controller.service.consul:6443/apis/extensions/v1beta1/ingresses\" : [Get https://dev.kubernetes-controller.service.consul:6443/apis/extensions/v1beta1/ingresses: net/http: invalid header field value \"Bearer XXXXXXX\\n\" for key Authorization], retrying in 2.845880675s"
```

It causing frontends and backends unconfigured.

Traefik 1.0.3 works fine with that setup.

My traefik config:
```
traefikLogsFile = "/var/log/traefik/traefik.log"
accessLogsFile = "/var/log/traefik/access.log"
logLevel = "ERROR"

defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"

[retry]

[web]
address = ":8080"

[kubernetes]
endpoint = "https://dev.kubernetes-controller.service.consul:6443"
```

**Comment by emilevauge** [comment]
@r0bj are you sure you only change traefik version? It seems kubernetes needs an authentication here.

**Comment by r0bj** [comment]
Yes, the only change is traefik version.
Authentication is provided by token in:
`/var/run/secrets/kubernetes.io/serviceaccount/token`
and CA cert in:
`/var/run/secrets/kubernetes.io/serviceaccount/ca.crt`

**Comment by emilevauge** [comment]
Could you activate DEBUG Traefik logs and put those here?

**Comment by r0bj** [comment]
Sure:
```
time="2016-11-23T18:29:26Z" level=info msg="Traefik version v1.1.0 built on 2016-11-18_09:27:31AM"
time="2016-11-23T18:29:26Z" level=info msg="Using TOML configuration file /etc/traefik/traefik.toml"
time="2016-11-23T18:29:26Z" level=debug msg="Global configuration loaded {\"GraceTimeOut\":10,\"Debug\":false,\"CheckNewVersion\":true,\"AccessLogsFile\":\"/var/log/traefik/access.log\",\"TraefikLogsFile\":\"/var/log/traefik/traefik.log\",\"LogLevel\":\"DEBUG\",\"EntryPoints\":{\"http\":{\"Network\":\"\",\"Address\":\":80\",\"TLS\":null,\"Redirect\":null,\"Auth\":null,\"Compress\":false}},\"Cluster\":null,\"Constraints\":[],\"ACME\":null,\"DefaultEntryPoints\":[\"http\"],\"ProvidersThrottleDuration\":2000000000,\"MaxIdleConnsPerHost\":200,\"InsecureSkipVerify\":false,\"Retry\":{\"Attempts\":0},\"Docker\":null,\"File\":null,\"Web\":{\"Address\":\":8080\",\"CertFile\":\"\",\"KeyFile\":\"\",\"ReadOnly\":false,\"Auth\":null},\"Marathon\":null,\"Consul\":null,\"ConsulCatalog\":null,\"Etcd\":null,\"Zookeeper\":null,\"Boltdb\":null,\"Kubernetes\":{\"Watch\":true,\"Filename\":\"\",\"Constraints\":[],\"Endpoint\":\"https://dev.kubernetes-controller.service.consul:6443\",\"DisablePassHostHeaders\":false,\"Namespaces\":null,\"LabelSelector\":\"\"},\"Mesos\":null}"
time="2016-11-23T18:29:26Z" level=info msg="Preparing server http &{Network: Address::80 TLS:<nil> Redirect:<nil> Auth:<nil> Compress:false}"
time="2016-11-23T18:29:26Z" level=info msg="Starting provider *main.WebProvider {\"Address\":\":8080\",\"CertFile\":\"\",\"KeyFile\":\"\",\"ReadOnly\":false,\"Auth\":null}"
time="2016-11-23T18:29:26Z" level=info msg="Starting provider *provider.Kubernetes {\"Watch\":true,\"Filename\":\"\",\"Constraints\":[],\"Endpoint\":\"https://dev.kubernetes-controller.service.consul:6443\",\"DisablePassHostHeaders\":false,\"Namespaces\":null,\"LabelSelector\":\"\"}"
time="2016-11-23T18:29:26Z" level=debug msg="Kubernetes token: XXXXXXX\n"
time="2016-11-23T18:29:26Z" level=debug msg="Kubernetes CA cert: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
time="2016-11-23T18:29:26Z" level=debug msg="Kubernetes endpoint: https://dev.kubernetes-controller.service.consul:6443"
time="2016-11-23T18:29:26Z" level=error msg="Error retrieving ingresses: failed to create ingresses request: GET \"https://dev.kubernetes-controller.service.consul:6443/apis/extensions/v1beta1/ingresses\" : failed to create request: GET \"https://dev.kubernetes-controller.service.consul:6443/apis/extensions/v1beta1/ingresses\" : [Get https://dev.kubernetes-controller.service.consul:6443/apis/extensions/v1beta1/ingresses: net/http: invalid header field value \"Bearer XXXXXXX\\n\" for key Authorization]"
time="2016-11-23T18:29:26Z" level=error msg="Error starting provider failed to create ingresses request: GET \"https://dev.kubernetes-controller.service.consul:6443/apis/extensions/v1beta1/ingresses\" : failed to create request: GET \"https://dev.kubernetes-controller.service.consul:6443/apis/extensions/v1beta1/ingresses\" : [Get https://dev.kubernetes-controller.service.consul:6443/apis/extensions/v1beta1/ingresses: net/http: invalid header field value \"Bearer XXXXXXX\\n\" for key Authorization]"
time="2016-11-23T18:29:26Z" level=debug msg="Using label selector: ''"
time="2016-11-23T18:29:26Z" level=info msg="Starting server on :80"
time="2016-11-23T18:29:26Z" level=error msg="Error watching kubernetes events: failed to create watch: failed to do version request: GET \"https://dev.kubernetes-controller.service.consul:6443/apis/extensions/v1beta1/ingresses\" : failed to create request: GET \"https://dev.kubernetes-controller.service.consul:6443/apis/extensions/v1beta1/ingresses\" : [Get https://dev.kubernetes-controller.service.consul:6443/apis/extensions/v1beta1/ingresses: net/http: invalid header field value \"Bearer XXXXXXX\\n\" for key Authorization]"
time="2016-11-23T18:29:27Z" level=error msg="Kubernetes connection error failed to create watch: failed to do version request: GET \"https://dev.kubernetes-controller.service.consul:6443/apis/extensions/v1beta1/ingresses\" : failed to create request: GET \"https://dev.kubernetes-controller.service.consul:6443/apis/extensions/v1beta1/ingresses\" : [Get https://dev.kubernetes-controller.service.consul:6443/apis/extensions/v1beta1/ingresses: net/http: invalid header field value \"Bearer XXXXXXX\\n\" for key Authorization], retrying in 581.870509ms"
time="2016-11-23T18:29:28Z" level=debug msg="Using label selector: ''"
time="2016-11-23T18:29:28Z" level=error msg="Error watching kubernetes events: failed to create watch: failed to do version request: GET \"https://dev.kubernetes-controller.service.consul:6443/apis/extensions/v1beta1/ingresses\" : failed to create request: GET \"https://dev.kubernetes-controller.service.consul:6443/apis/extensions/v1beta1/ingresses\" : [Get https://dev.kubernetes-controller.service.consul:6443/apis/extensions/v1beta1/ingresses: net/http: invalid header field value \"Bearer XXXXXXX\\n\" for key Authorization]"
```

**Comment by emilevauge** [comment]
@r0bj Hum `\n` at the end of the token...
@errm, have you ever seen this?

**Comment by r0bj** [comment]
I've just checked and 1.0.3 log looks similar:
```
time="2016-11-23T18:41:45Z" level=info msg="Traefik version v1.0.3 built on 2016-09-22_01:15:33PM"
time="2016-11-23T18:41:45Z" level=info msg="Using TOML configuration file /etc/traefik/traefik.toml"
time="2016-11-23T18:41:45Z" level=debug msg="Global configuration loaded {\"GraceTimeOut\":10,\"Debug\":false,\"AccessLogsFile\":\"/var/log/traefik/access.log\",\"TraefikLogsFile\":\"/var/log/traefik/traefik.log\",\"LogLevel\":\"DEBUG\",\"EntryPoints\":{\"http\":{\"Network\":\"\",\"Address\":\":80\",\"TLS\":null,\"Redirect\":null}},\"Constraints\":[],\"ACME\":null,\"DefaultEntryPoints\":[\"http\"],\"ProvidersThrottleDuration\":2000000000,\"MaxIdleConnsPerHost\":200,\"Retry\":{\"Attempts\":0},\"Docker\":null,\"File\":null,\"Web\":{\"Address\":\":8080\",\"CertFile\":\"\",\"KeyFile\":\"\",\"ReadOnly\":false},\"Marathon\":null,\"Consul\":null,\"ConsulCatalog\":null,\"Etcd\":null,\"Zookeeper\":null,\"Boltdb\":null,\"Kubernetes\":{\"Watch\":false,\"Filename\":\"\",\"Constraints\":null,\"Endpoint\":\"https://dev.kubernetes-controller.service.consul:6443\",\"DisablePassHostHeaders\":false,\"Namespaces\":null}}"
time="2016-11-23T18:41:45Z" level=info msg="Preparing server http &{Network: Address::80 TLS:<nil> Redirect:<nil>}"
time="2016-11-23T18:41:45Z" level=info msg="Starting provider *main.WebProvider {\"Address\":\":8080\",\"CertFile\":\"\",\"KeyFile\":\"\",\"ReadOnly\":false}"
time="2016-11-23T18:41:45Z" level=info msg="Starting provider *provider.Kubernetes {\"Watch\":false,\"Filename\":\"\",\"Constraints\":null,\"Endpoint\":\"https://dev.kubernetes-controller.service.consul:6443\",\"DisablePassHostHeaders\":false,\"Namespaces\":null}"
time="2016-11-23T18:41:45Z" level=info msg="Starting server on :80"
time="2016-11-23T18:41:45Z" level=debug msg="Kubernetes token: XXXXXXX\n"
time="2016-11-23T18:41:45Z" level=debug msg="Kubernetes CA cert: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
time="2016-11-23T18:41:45Z" level=debug msg="Kubernetes endpoint: https://dev.kubernetes-controller.service.consul:6443"
```

But this version works fine.

**Comment by emilevauge** [comment]
@dtomcej @errm any idea?

**Comment by dtomcej** [comment]
What version of Kubernetes are you running @r0bj

**Comment by r0bj** [comment]
@dtomcej Kubernetes 1.4.6

**Comment by dtomcej** [comment]
If you run the alpine image, and curl the kubernetes endpoint manually (make sure to specify the CA), do you get the same error?

**Comment by r0bj** [comment]
No, curl works fine:
```
curl --cacert ca.crt -H "Authorization: Bearer XXXXXXX" https://dev.kubernetes-controller.service.consul:6443/apis/extensions/v1beta1/ingresses
{
  "kind": "IngressList",
  "apiVersion": "extensions/v1beta1",
  "metadata": {
[...]
```

**Comment by emilevauge** [comment]
@r0bj I cannot reproduce your issue :'(. Could you provide us your TOML file, and the command line used to launch traefik?

**Comment by Hades32** [comment]
Same is happening here. Versions, see below. What I found is, that the token is actually a little strange. Normally it should decode to some JWT but this one contains some arbitrary(?) data at the end.

`JWT:
eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJkZWZhdWx0LXRva2VuLTFxdmkwIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImRlZmF1bHQiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiIyOGVkMzI4ZS1iM2VjLTExZTYtOGI1MS1mNmJkODg0NWM0OWEiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZS1zeXN0ZW06ZGVmYXVsdCJ9.orh9YkgaGOdZZezFvTHoVcUEH5_7eKuUpiep7reT-wSsAKLHqhtjTARHD8L2R_fYl739Cai1n8tmSg2-qX0qEKx2pANHvSHwLjeaetGUWr73X0reTl0oHgMKvxRo0xxHqAV7GCnbncZWjvkuZuWX1cmDWQxqGjfDb7YiFz7kfsTKJdH_rhfzUkBfaCcz6bGjaFNiEwWmDcp7hL9QZuHJmRNhLGzWbrhiXm8XVDPGSTGKkcjj3ZKrht3XcL_2xCX1yLrw0BweE_N3_PjtEfHbeVX5wiTbEUQo8tPUZ0VOr2yq3vVUnBo0bFAsoOlQeczlR_1-JbsHCzjpDCUD2uMkXA
`

`
[root@pine64 traefik]# ./traefik_linux-arm64 version
Version:      v1.1.0
Codename:     camembert
Go version:   go1.7.3
Built:        2016-11-18_09:27:31AM
OS/Arch:      linux/arm64
[root@pine64 traefik]# kubectl version
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.4", GitCommit:"3b417cc4ccd1b8f38ff9ec96bb50a81ca0ea9d56", GitTreeState:"clean", BuildDate:"2016-10-21T02:48:38Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/arm64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.4", GitCommit:"3b417cc4ccd1b8f38ff9ec96bb50a81ca0ea9d56", GitTreeState:"clean", BuildDate:"2016-10-21T02:42:39Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/arm64"}
[root@pine64 traefik]# docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   23cf638
 Built:        Tue, 27 Sep 2016 12:25:38 +1300
 OS/Arch:      linux/arm64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   23cf638
 Built:        Tue, 27 Sep 2016 12:25:38 +1300
 OS/Arch:      linux/arm64
`

**Comment by Hades32** [comment]
API Server is saying this:
[root@pine64 traefik]# docker logs --tail=1000 e9c31 2>&1 | grep -v node-controller | grep -v kube-scheduler | grep -v kube-controller-manager
E1126 23:27:07.245734       1 handlers.go:55] Unable to authenticate the request due to an error: illegal base64 data at input byte 342

**Comment by r0bj** [comment]
Actually it may be related to DNS resolver. When I start traefik 1.1.0 there is no traffic to the kubernetes api-server.

traefik.toml:
```
traefikLogsFile = "/var/log/traefik/traefik.log"
accessLogsFile = "/var/log/traefik/access.log"
logLevel = "DEBUG"

defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"

[retry]

[web]
address = ":8080"

[kubernetes]
endpoint = "https://dev.kubernetes-controller.service.consul:6443"
```

Domain `dev.kubernetes-controller.service.consul` resolves into `10.14.30.116`.
Address `10.14.30.124` is set in /etc/resolv.conf as a nameserver.

execute:
`./traefik_linux-amd64_1.0.3 -c traefik.toml`

Everything works fine.

execute version 1.1.0:
`./traefik_linux-amd64_1.1.0 -c traefik.toml`

There is no traffic to address `10.14.30.116`.
Strace log (token, cert, hosts has been redacted):
https://gist.github.com/r0bj/abe37ec2a6814d1b46fe9937da187274

In that strace there is no mention of address `10.14.30.116`. So I assume that resolving name `dev.kubernetes-controller.service.consul` into `10.14.30.116` just failed.

**Comment by r0bj** [comment]
I changed kubernetes endpoint from:

`endpoint = "https://dev.kubernetes-controller.service.consul:6443"`
to:
`endpoint = "https://10.14.30.116:6443"`

but still there is no network communication.

**Comment by Hades32** [comment]
Might be this: https://github.com/kubernetes/kubernetes/issues/20391 happens after some time for me

**Comment by r0bj** [comment]
I run traefik not as kubernetes pod/container, just a standalone binary. There is no kube-proxy on the host where I run traefik.

**Comment by marcolenzo** [comment]
I had the very same issue running traefik on the command line.

Initially I thought it must be traefik adding `\n` at the end of the token. I was sure there was no new line in the file where I store the token when opening it with `vim`. I was able to hit the API with the same certificate and token using `curl`.

So I decided to open the token file with some other text editor (Sublime) and the new line at the end of file was there! I am assuming it has to be with some encoding issue.

My advice is open the file where you store the token with another text editor. Unfortunately I am not a Linux expert so I cannot give you a better option.

**Comment by r0bj** [comment]
I've tried to run traefik as a kubernetes pod instead of standalone binary and result is the same.

**Comment by EamonZhang** [comment]
run traefik in kubernetes with yaml

```
apiVersion: v1
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress-lb
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
        version: v1.0.0
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: traefik:v1.0.0
        name: traefik-ingress-lb
        resources:
          limits:
            cpu: 200m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 8080
        args:
        - --web
        - --kubernetes
```

kubectl get pod --all-namespaces
`kube-system   traefik-ingress-controller-501149844-canko   1/1       Running   0          26s`

kubectl log traefik-ingress-controller-501149844-canko --namespace=kube-syste

```
time="2017-01-10T07:42:20Z" level=error msg="Error watching kubernetes events: failed to create watch: failed to do version request: GET \"https://77.77.0.1:443/apis/extensions/v1beta1/ingresses\" : http error 401 GET \"https://77.77.0.1:443/apis/extensions/v1beta1/ingresses\": \"Unauthorized\\n\"" 
time="2017-01-10T07:42:21Z" level=error msg="Kubernetes connection error failed to create watch: failed to do version request: GET \"https://77.77.0.1:443/apis/extensions/v1beta1/ingresses\" : http error 401 GET \"https://77.77.0.1:443/apis/extensions/v1beta1/ingresses\": \"Unauthorized\\n\", retrying in 32.370111282s" 
time="2017-01-10T07:42:54Z" level=error msg="Error watching kubernetes events: failed to create watch: failed to do version request: GET \"https://77.77.0.1:443/apis/extensions/v1beta1/ingresses\" : http error 401 GET \"https://77.77.0.1:443/apis/extensions/v1beta1/ingresses\": \"Unauthorized\\n\"" 
time="2017-01-10T07:42:55Z" level=error msg="Kubernetes connection error failed to create watch: failed to do version request: GET \"https://77.77.0.1:443/apis/extensions/v1beta1/ingresses\" : http error 401 GET \"https://77.77.0.1:443/apis/extensions/v1beta1/ingresses\": \"Unauthorized\\n\", retrying in 1m26.257863816s
```
IP 77.77.0.1 is my kubernetes master address

**Comment by Tedezed** [comment]
@EamonZhang I have same error:

`kubectl create -f https://raw.githubusercontent.com/containous/traefik/master/examples/k8s/traefik.yaml`

```
time="2017-01-10T11:36:12Z" level=error msg="Kubernetes connection error failed to create watch: failed to do version request: GET \"https://10.254.0.1:443/apis/extensions/v1beta1/ingresses\" : failed to create request: GET \"https://10.254.0.1:443/apis/extensions/v1beta1/ingresses\" : [Get https://10.254.0.1:443/apis/extensions/v1beta1/ingresses: dial tcp 10.254.0.1:443: getsockopt: connection timed out], retrying in 297.148284ms" 
```

**Comment by dtomcej** [comment]
@EamonZhang Your kubernetes issue of `/apis/extensions/v1beta1/ingresses\": \"Unauthorized` is not the same as the original poster. Please open a new issue.

**Comment by dtomcej** [comment]
@Tedezed Your kubernetes issue of `/apis/extensions/v1beta1/ingresses: dial tcp getsockopt: connection timed out` is not the same as the original poster. Please open a new issue.

**Comment by timoreimann** [comment]
@r0bj did you try to validate @marcolenzo's [suggestion](https://github.com/containous/traefik/issues/883#issuecomment-267754779)?

**Comment by r0bj** [comment]
@timoreimann somehow I cannot replicate the issue anymore. I'm not sure what was the real cause. I currently run traefik 1.2.1 with success. So I guess we can close this issue.

**Comment by timoreimann** [comment]
@r0bj thanks for the quick response.

I think switched over to the official Go client since you reported the problem. So chances are it was solved that way.
