### ISSUE TITLE
Custom or more verbose 404 page

### ISSUE THREAD

**Issue by WTFKr0** [containous/traefik#884]
Hi !

I'm trying the new feature of traefik constraints.
I have a front traefik, which route to n traefik instances.
Those traefik route to a set of containers.
All filtering by tags
It's not working and it's a pain to debug that when i got a 404 not found. I can't easily see which traefik send me that.

Is there a way to put some information (maybe customizable) in the default 404 page ? (like hostname or tags ?)

Thanks for reading

**Comment by emilevauge** [comment]
@WTFKr0 We will add support OpenTracing #771 to easily debug this kind of issue. It should help ;)

**Comment by WTFKr0** [comment]
OpenTracing should certainly help for that.  
Beyond that, I think it would be necessary for companies using traefik to provide a template for the 404 page.  
Like the ability to place a logo, a text, or some variables in that page

**Comment by ryanleary** [comment]
> Like the ability to place a logo, a text, or some variables in that page

Perhaps even a template per frontend.

**Comment by WTFKr0** [comment]
Hum I think of the 404 page when there is no front-end rule found 😁

**Comment by salizzar** [comment]
Another good option is to redirect to a custom domain, like this thread http://stackoverflow.com/questions/9147862/nginx-return-301-redirect-when-404-error 🙂

**Comment by ldez** [comment]
Closing this issue in favor of  #1634.

**Comment by emilevauge** [comment]
Reopening, as it's a bit different from #1634 ;)

**Comment by emilevauge** [comment]
Closing in favor of #1634 and #771
