### ISSUE TITLE
file vs inline config

### ISSUE THREAD

**Issue by opichon** [containous/traefik#888]
The docs mention a `[docker]` config section in the `traefik.yoml` configuration file, but the example for running traefik via docker mention similar options on the command line:

`--web --docker --docker.domain=... `

Are these 2 ways to set the configuration equivalent?

**Comment by emilevauge** [comment]
Yes.

**Comment by opichon** [comment]
I've tried launching a traefik container via docker-compose _without_ including the `command --web --docker ...` argument, having these same arguments setup in the `traefik.toml` config file (which was mounted as a volume). Traefik fails to launch. 

To be precise: The container is running, but the logs are empty, and the web ui page loads intermittently.

**Comment by emilevauge** [comment]
@opichon 
Please make and effort when you report an issue on an open source software.
>Traefik fails to launch.

Is really not sufficient for us to investigate on this.
We need you config file, your version, your DEBUG logs, etc...

>logs are empty

Have you at least tried to launch Traefik in DEBUG?

**Comment by opichon** [comment]
logs are empty: that's because the log _is_ empty (after launch). Nothing. Nada. And traefik _is_ running in DEBUG mode.

As I explained: the container is running, but the web ui page loads intermittently.

**Comment by opichon** [comment]
Apologies: trawfik was indeed _not_ running in DEBUG mode. However, having set logLevel = "DEBUG" in traefik.toml, the log is definitely not empty. 

Treafik is working, in the sense that trying to open one of the urls being proxied does open that url.

However, the web ui is not working: every other time I refresh the page, I get an error message "server unreachable". When the web ui page does display, the providers section is empty.
