### ISSUE TITLE
ACME (letsencrypt) interface or plugin

### ISSUE THREAD

**Issue by F0rth** [containous/traefik#89]
Let's encrypt had proposed an ietf draft to automate ssl certificats creation and renewal. It would be awesome in the futur to have auto-https frontend.

https://github.com/ietf-wg-acme/acme/blob/master/draft-ietf-acme-acme.md

**Comment by emilevauge** [comment]
Hi @F0rth, I'm currently already working on that ^^

**Comment by jpillora** [comment]
:+1: letsencrypt all the things!

**Comment by ludovicc** [comment]
There is a Go library (https://github.com/xenolf/lego) used by Caddy.

**Comment by emilevauge** [comment]
@ludovicc yep, I have seen what Caddy does with letsencrypt using lego. It would be awesome to add that feature in Traefik :)

**Comment by strarsis** [comment]
+1

**Comment by sheerun** [comment]
I'm also interested. Maybe running traefik on top of consul-template would work?

**Comment by strarsis** [comment]
https://github.com/emilevauge/traefik/issues/211

**Comment by emilevauge** [comment]
Hi all, I created a traefik docker image with let's encrypt support: `containous/traefik:add-lets-encrypt-suppport`
I invite you to test it before the PR is merged ;)
Here is the new toml file to use:

```
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
email = "test@mymail.com"
# group domains to get SNA
domains = [["test.local1.com", "test.local2.com"], ["test.local4.com", "test.local3.com"]]
storageFile = "acme.json"
onDemand = true
# Uncomment the line to run on the staging let's encrypt server
# Leave comment to go to prod
# caServer = "https://acme-staging.api.letsencrypt.org/directory"
entryPoint = "http" # must point en entrypoint on port 80
```

Your feedback is welcome :)

**Comment by strarsis** [comment]
So the domains for the ACME client are listed in the domains option of acme key in configuration file.
Can this also be dynamically changed? Could one flag containers with an acme or even letsencrypt flag so traefik knows that the domains in the routes for these containers should have certs/keys requests over acme?

**Comment by emilevauge** [comment]
@strarsis, thanks for your feedback!
If you enable `onDemand = true`, traefik will dynamically download cert at the first request.
But, this is not perfect, I know that.
Maybe a new option on frontend, that would trigger cert download.
I was wondering if I had to rely directly on `Host` frontend rules, but they can be also wildcard :'(

**Comment by thorhs** [comment]
Maybe this could fit? https://github.com/dkumor/acmewrapper

**Comment by djmaze** [comment]
@emilevauge Letsencrypt does not (yet) support wildcard certificates, and generating certificates upon request is not desirable. So, in my opinion, if the Host rule contains a wildcard, ACME/SSL support should automatically be disabled for that particular frontend. Then certificates need to be generated only when a new frontend is added.

**Comment by djmaze** [comment]
@emilevauge Your toml file example works for me if I set `defaultEntryPoints` to just `["https"]`. Otherwise Traefik only serves the backend service(s) on port 80, and the `.well-known` directory is not reachable.
