### ISSUE TITLE
file backend: using external file - doesn't work

### ISSUE THREAD

**Issue by opichon** [containous/traefik#892]
The docs indicate that the file backend can "include" an exernal fil with this syntax:

```toml
[file]
filename = "rules.toml"
```

This doesn't work.

I presume the `rules.toml` file has to be located in the same directory as the main `traefik.toml` config file. There is nothing in the docs that says otherwise. Is this the case?

Is there any support for using a file in another directory using either an absolute or relative path?

**Comment by emilevauge** [comment]
@opichon 
It works as expected.
Have you ever tried `/etc/traefik/rules.toml` ?
