### ISSUE TITLE
api backend readOnly: what is the purpose of this setting

### ISSUE THREAD

**Issue by opichon** [containous/traefik#893]
The web or API backend has a `readOnly` setting. The docs do not explain what this if for.

In the web ui, it seems to have no effect. If set to `false`, there appears to be no location in the web ui to actually input anything or make changes to the traefik config.

In the API, the docs only give examples of read (GET) requests.

What am I missing?

**Comment by emilevauge** [comment]
In the docs:

```
# Set REST API to read-only mode
#
# Optional
# ReadOnly = false
```

aka, you cannot push new configurations anymore to the API (not web ui).

>In the API, the docs only give examples of read (GET) requests.

Obviously we could add more example in doc on this, but already:
```
/api/providers/{provider}: GET or PUT provider
```
