### ISSUE TITLE
More generic traefik constraints "tags" for docker provider

### ISSUE THREAD

**Issue by WTFKr0** [containous/traefik#895]
Hi,

I think it would be great if the `--constraints` parameter become more generic.
Some of labels are automatically placed by docker or compose (and maybe by other orchestrator), and traefik could use them to filter

Today we place a constraint (`--constraints='tag==eu'`)
And then a label `traefik.tag=eu` is placed on container

For example, if my container already have a label like `"com.docker.compose.project": "proj1"`, I would like to tell traefik instance to manage only this project

Maybe the `--contraints` parameter can be more generic by letting user decide which label to check, like : 
`--constraints='com.docker.compose.project=="proj1"'`
So the old way can be done with : 
`--constraints='traefik.tags=="eu"'`

WDYT ?

**Comment by danieladams456** [comment]
This would be good for filtering by Docker network.  We have two traefik instances for different dev teams on different docker networks.  It would be nice to not have them discovering each other's services and getting 504s when the wrong instance was used.  With a filter it would be a more correct (and faster) 404.

**Comment by danbo** [comment]
It would be great to be be able to run multiple instances of traefik and scope containers to one of those instances even for dev purposes / outside of k8s / swarm.

**Comment by cerw** [comment]
Has this been resolved? How do you manage multiple instances on one docker server or in separate stacks?

**Comment by traefiker** [comment]
Closed by #4965.
