### ISSUE TITLE
Traefik not scanning containers on added engine in Docker Swarm (legacy)

### ISSUE THREAD

**Issue by ThinkBriK** [containous/traefik#899]
Hi,

We encountered a problem with Traefik not updating it's back-end configuration in the following case
- Docker 1.12
- Docker swarm version 1.2.5 (27968ed) Yes the legacy, proxy-like one
- Traefik 1.1

We're running Traefik and Docker swarm at the same time on boot and Traefik initialize _before_ swarm has discovered docker engines.

```shell
time="2016-11-24T08:26:08Z" level=debug msg="Docker connection established with docker swarm/1.2.5 (API 1.22)"
time="2016-11-24T08:26:08Z" level=debug msg="Configuration received from provider docker: {}"
```

But then Swarm add a node's engine:
```shell
time="2016-11-24T08:27:03Z" level=info msg="Registered Engine ip-10-0-1-196.local at 10.0.1.196:2375"
```
And Traefik does not scan the added node.

Traefik then only updates on the first docker event received:

```shell
time="2016-11-24T09:09:44Z" level=debug msg="Docker event received {Status:start ID:0fff697ce3c83e209812dd0ec902162eeb3093db32c1663f197b417e71ec091a From:hello-world node:ip-10-0-1-196.local Type:container Action:start Actor:{ID:0fff697ce3c83e209812dd0ec902162eeb3093db32c1663f197b417e71ec091a Attributes:map[node.id:LVUV:BIES:ROZO:RCLW:7RRR:GIMJ:5G2B:HB63:AB2J:L2XG:AGF7:6I4G node.ip:10.0.1.196 node.name:ip-10-0-1-196.local image:hello-world name:angry_lichterman node.addr:10.0.1.196:2375]} Time:1479978584 TimeNano:1479978584068563468}"
```

It looks like adding a node to swarm does **NOT** trigger a scan of the node by Traefik.

**Comment by emilevauge** [comment]
Hum, @vdemeester, I didn't test this but I assume Swarm should throw an event when a node joins a cluster right?

**Comment by ldez** [comment]
I'll close the issue due to inactivity but feel free to re-open if needed.
