### ISSUE TITLE
Remote-XXX Headers From Authelia Not Available from 2.6.2

### ISSUE THREAD

**Issue by alexkoon** [containous/traefik#9062]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Using Traefik and Authelia in docker. Noticed that the Remote-XXX headers from Authelia were not sent through to the resulting web application after upgrade from 2.5.x to 2.7.0. I downgraded Authelia first, but still had problems. Found the Authelia WEB API to test on their latest version and can see it does return the configured Remote-XXX headers. Downgraded Traefik back to v2.5.7 and installed the whoami webapp with basic authentication turned on (and confirmed again via Authelia Web API that the Remote-XXX headers were returned). The whoami webapp reported the Remote-XXX headers again.
Upgraded to Traefik v2.6.0 and headers again were ok, same for v2.6.1. When I upgraded to v2.6.2, the Remote-XXX headers were not seen in the whoami webapp.

### What did you see instead?

Remote-XXX headers not available/found.

### What version of Traefik are you using?

Error found in v2.6.2 onwards.

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```

Add more configuration information here.

**Comment by rtribotte** [comment]
Hello @alexkoon,

Thanks for your interest in Traefik!

Can you share the configuration of the middleware?

This is probably due to a misinterpretation of the configuration. There was a bug with the configuration parsing (a non-compliant YML list based on commas was parsed), and we fixed it in v2.6.2 (https://github.com/traefik/traefik/pull/8850).
