### ISSUE TITLE
Kubernetes updating deployment image requires Ingress to be remade 

### ISSUE THREAD

**Issue by AlecTroemel** [containous/traefik#909]
Traefik version: v1.1.0

Currently, when the docker image of a kubernetes deployment is updated, the traefik route becomes broken and a new ingress needs to be created. I get these errors on updating a deployment as well
```
level=error msg="Undefined backend 'agentchat.mirus.io/example' for frontend my.domain.com/example" 
level=error msg="Skipping frontend my.domain.com/example..."  
```

Doesn't make sense that traefik ends up routing to a single pod (which is terminated and replaced on updating), since the ingress exposes a service, but thats my current thought from my understanding of the web ui 
<img width="558" alt="screen shot 2016-11-28 at 11 48 24 am" src="https://cloud.githubusercontent.com/assets/8620042/20679489/bf305d6e-b560-11e6-9836-1d102f028e49.png">

Any thoughts/solutions on this?

**Comment by emilevauge** [comment]
@errm any opinion on this ?

**Comment by AlecTroemel** [comment]
Updating to v1.1.1 resolved this issue, closing it!
