### ISSUE TITLE
Kubernetes: should not remove configured frontends and backends when we loose contact with apiservers

### ISSUE THREAD

**Issue by jonaz** [containous/traefik#912]
When i do a rolling upgrade of my kubernetes masters traefik must be able to continue serving traffic while the API is momentarily away (a few seconds). Currently traefik seems to remove all configuration as soon as it detects error from api. I think expected behaviour would be to keep current config until otherwise told (reconnected to apiservers).

**Comment by george-angel** [comment]
+1

**Comment by yvespp** [comment]
@jonaz with which version did you see this? This works in our cluster but we are still on 1.0.3.
Can you please add logs? Does traefik restart?

**Comment by AlecTroemel** [comment]
+1 this

**Comment by cameronattard** [comment]
+1

**Comment by abh** [comment]
This happened to me today, too. (We just started testing Traefik). Maybe the new change (unreleased) using the standard k8 go-client fixes it? Or helps?

**Comment by jonaz** [comment]
This might be resolved with #1295?

**Comment by timoreimann** [comment]
@jonaz highly likely -- thanks for pointing out! 🎉 

The just-released v1.2 contains the fix, so closing.
