### ISSUE TITLE
I am getting a connection error while creating traefik with consul backend "dial tcp 127.0.0.1:8500: getsockopt: connection refused"

### ISSUE THREAD

**Issue by himanshuverma123** [containous/traefik#917]
I have consul container running on 127.0.0.1:8500.
**Output of curl -v **"http://127.0.0.1:8500/v1/kv/traefik?recurse=&wait=30000ms":**

*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 8500 (#0)
> GET /v1/kv/traefik?recurse=&wait=30000ms HTTP/1.1
> Host: 127.0.0.1:8500
> User-Agent: curl/7.49.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: application/json
< X-Consul-Index: 13
< X-Consul-Knownleader: true
< X-Consul-Lastcontact: 0
< Date: Tue, 29 Nov 2016 14:09:44 GMT
< Content-Length: 782
<
* Connection #0 to host 127.0.0.1 left intact
[{"CreateIndex":10,"ModifyIndex":10,"LockIndex":0,"Key":"traefik/consul/endpoint","Flags":0,"Value":"MTI3LjAuMC4xOjg1MDA="},{"CreateIndex":12,"ModifyIndex":12,"LockIndex":0,"Key":"traefik/consul/prefix","Flags":0,"Value":"dHJhZWZpaw=="},{"CreateIndex":11,"ModifyIndex":11,"LockIndex":0,"Key":"traefik/consul/watch","Flags":0,"Value":"dHJ1ZQ=="},{"CreateIndex":8,"ModifyIndex":8,"LockIndex":0,"Key":"traefik/defaultentrypoints/0","Flags":0,"Value":"aHR0cA=="},{"CreateIndex":9,"ModifyIndex":9,"LockIndex":0,"Key":"traefik/entrypoints/http/address","Flags":0,"Value":"Ojgw"},{"CreateIndex":7,"ModifyIndex":7,"LockIndex":0,"Key":"traefik/loglevel","Flags":0,"Value":"REVCVUc="},{"CreateIndex":13,"ModifyIndex":13,"LockIndex":0,"Key":"traefik/web/address","Flags":0,"Value":"OjgwODE="}]

And by running Traefik using docker compose I get:

Starting traefik_traefik_1
Attaching to traefik_traefik_1
traefik_1  | 2016/11/29 14:11:33 Error loading configuration: Get http://127.0.0.1:8500/v1/kv/traefik?recurse=&wait=30000ms: dial tcp 127.0.0.1:8500: getsockopt: connection refused
traefik_traefik_1 exited with code 255.

Any Help or Hint?

**Comment by himanshuverma09** [comment]
Okay solved it.

Used the following config for traefik compose file:-

traefik:
  image: traefik
  command: --consul  --consul.endpoint=127.0.0.1:8500
  ports:
    - "80:80"
    - "8080:8080"
  net: "host"

**Comment by emilevauge** [comment]
Ok closing this is then ☺️

**Comment by ojacquemart** [comment]
I got the same error with docker-compose files from the examples folder.

```
traefik_1  | Error loading configuration: Get http://127.0.0.1:8500/v1/kv/traefik?recurse=&wait=30000ms: dial tcp 127.0.0.1:8500: getsockopt: connection refused
whoami2_1  | Starting up on port 80
whoami1_1  | Starting up on port 80
```

docker -v
`Docker version 17.03.1-ce, build c6d412e`

docker-compose -v
`docker-compose version 1.13.0, build 1719ceb`

Any idea?
