### ISSUE TITLE
Excessive requests to kubernetes apiserver

### ISSUE THREAD

**Issue by rrichardson** [containous/traefik#922]
Apologies if this is a known issue,  but in a multi-master k8s cluster,  it seems that Traefik receives and then responds to every event which comes across the k8s bus, included leader election information, which is very chatty.  Then the nearest that I can tell, it responds to every event with an apiserver request.  The resulting effect is that my k8s master (master) is pegged at 100% cpu.   Is there a way to filter the events to which Traefik responds?

**Comment by Hades32** [comment]
Even on a single node k8s installation, traefik+kube-apiserver use up ~150% CPU on my 4 code ARMv8 server! When traefik is stopped it sits comfortably below 20%...

**Comment by emilevauge** [comment]
This should be solved in the next release with https://github.com/containous/traefik/pull/836.
@errm WDYT?

**Comment by errm** [comment]
Yes this should be fixed by #836, chattiness should be significantly reduced...

**Comment by Hades32** [comment]
FYI: current master has *great* performance now. My little ARM board is now actually usable again. Great work!
