### ISSUE TITLE
Best approach for filtering by origin IP or x-forwarded-for?

### ISSUE THREAD

**Issue by rrichardson** [containous/traefik#925]
As far as I can tell, the only way I can restrict service to specific  IPs/subnets is to use HeaderRegexp: "192.168.*"  or somesuch.  Is there a better option?

**Comment by rrichardson** [comment]
Ah, I just found https://github.com/containous/traefik/issues/623  so I reckon that this is a yet unsolved problem.

**Comment by emilevauge** [comment]
Closing this one then ;)
