### ISSUE TITLE
SNI based routing without TLS offloading

### ISSUE THREAD

**Issue by Hades32** [containous/traefik#933]
The competition has an interesting feature:
https://github.com/eBay/fabio/wiki/Features#tcpsni-proxy-support

Not sure if the terrible traefik docs just didn't explain it right, or I think Traefik is currently missing this feature.

**Comment by emilevauge** [comment]
>the terrible traefik docs

Thanks. Have you plan to help?

**Comment by dtomcej** [comment]
Traefik Is L7. SNI proxies operate at L4.

**Comment by Hades32** [comment]
I didn't had the impression that it's declared mission is to be on a specific layer. I thought traffic tries to make routing for modern architectures  easy. And one thing that's more and more common is end to end security. So maybe you want to change your mind on that one eventually

**Comment by dtomcej** [comment]
@Hades32 There is a ticket to investigate TCP forwarding, but it requires a major rewrite. If that moves forward, L4 proxying will definitely be implemented.

**Comment by shantanugadgil** [comment]
Hi @dtomcej 
Which issue would be the one about **TCP + SNI (without decrypting)** that one should keep an eye on?
I see a few related, but not sure if they are related to the same issue.
Basically: TCP pass-through with SNI matching.

#10
#1376 
#1409 

Thanks and Regards,
Shantanu

**Comment by shantanugadgil** [comment]
@emilevauge  @dtomcej 
sorry to bother again, just wondering if this ever got done and I missed it while going through the 'Changelog'

Regards,
Shantanu

**Comment by shantanugadgil** [comment]
Hi @emilevauge @dtomcej  @Hades32 
Has the `TCP + SNI` feature been implemented in Traefik?
I just scanned the Changelog of 1.4.0rc2 and don't seem to find it yet.

Just like my previous question, which issue should I keep an eye on to see if/when it gets implemented.

Thanks and Regards,
Shantanu

**Comment by ldez** [comment]
@shantanugadgil You can follow #10 for the TCP support.
