### ISSUE TITLE
Traefik on Swarm mode 1.13.rc3 seems broken

### ISSUE THREAD

**Issue by pouicr** [containous/traefik#945]
Hi,

I was trying to setup Traefik on last 1.13 RC but I got strange behavior.

```
$ docker info
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 8
Server Version: 1.13.0-rc3
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: lxdosuvx00h2n8g7k5y5xs5bp
 Is Manager: true
 ClusterID: 2diztlydkcdxiiwgphpo9vfph
 Managers: 1
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.90.250.46
 Manager Addresses:
  10.90.250.46:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 51371867a01c467f08af739783b8beafc154c4d7
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-229.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
```

Here is the steps i go throught:

```
docker network create traefik-net

docker service create   --name traefik   --constraint=node.role==manager   --publish 80:80   --publish 8080:8080   --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock   --network traefik-net   traefik   --docker   --docker.swarmmode   --docker.domain=traefik   --docker.watch   --web

docker service create --name whoami --label traefik.port=80 --network traefik-net emilevauge/whoami
```

Traefik is running, it detect the whoami service.

The `curl -H Host:whoami.traefik http://127.0.0.1` answer *Bad Gateway*

If I scale whoami (=3) then nothing change in the GUI (I cannot see 3 backends) but since I am running a 3 node swarm, one whoami is running on the master node (next to traefik).

Then I can reach the app (but no round robin - an issue is open on that)

I am wrong somewhere or is there an issue?

BTW, thanks for your great job :)

**Comment by manpirez** [comment]
Hi, I have this same problem but in version 1.12.3

```
$ docker info
Containers: 6
  Running: 4
  Paused: 0
  Stopped: 2
Images: 9
Server Version: 1.12.3
Storage Driver: aufs
  Root Dir: / var / lib / docker / aufs
  Backing Filesystem: extfs
  Dirs: 49
  Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
  Volume: local
  Network: overlay weavemesh null bridge host
Swarm: active
  NodeID: 6wna0pc5r4h1irt8pliljcuix
  Is Manager: true
  ClusterID: 338kvec680h59huzre98lnf86
  Managers: 1
  Nodes: 3
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Heartbeat Tick: 0
   Election Tick: 3
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
  Node Address: 10.0.0.76
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.2.0-42-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64

**Comment by Michael-Hamburger** [comment]
Same here on 1.13 rc3 :/

**Comment by tlvenn** [comment]
Same problem here, for some reason, Traefik lookup the VIP address for a given service even though the VIP is not used and therefore not plumbed on the container.

Maybe it used to be plumbed all the time and now with 1.13 unless you actually publish a port using the ingress mode, the VIP will not be plumbed/available which actually make sense.

@vdemeester any idea if the work around the new `--port` command with the `mode=port` could explain the issue ?

@diegofernandes what is the current logic to select the IP for a given instance of a service ? Any idea why traefik selects the VIP address ?

Thanks !

**Comment by diegofernandes** [comment]
I think the problem here It's because the traefik can't call the Swarm API on managers.

@tlvenn, the swarm mode support use the Swarm VIP, we choose that because makes the things simples, using this traefik just route to VIP and the Swarm do the routing to the containers.

**Comment by Michael-Hamburger** [comment]
@diegofernandes But this isn't the way it should be, shouldn't it? 

As far as I understand https://github.com/containous/traefik/blob/master/docs/basics.md#backends round robin should be used. But when the swarm does the routing to the containers this isn't round-robin anymore. On my setup I have two manager and two container. After refreshing the page the other container should be used but that's not the case. It's not round robin anymore. Do I miss something here?

**Comment by diegofernandes** [comment]
@Michael-Hamburger the Docker Swarm do the round robin, but you are correct. We have plans to do use the container IP instead the VIP.
For now the VIP works well

**Comment by pouicr** [comment]
Well it seems I am also having a routing issue when I try on plain swarm service fashion.
I.E. if I have 3 nodes and 2 hosting a service (with pusblished port) I can only join the service on those 2, not on the last one...

**Comment by tlvenn** [comment]
>For now the VIP works well
@diegofernandes I am not so sure it will hold true with the publish mode host (vs ingress aka VIP). For example, because I need to preserve the source IP , I am not using the ingress mode anymore with Docker 1.13.

**Comment by Michael-Hamburger** [comment]
I can say that the internal swarm routing is working on my end. IP 10.0.1.4 is the virtual ip of the whoami-service I deployed on my swarm. This service is also accessible via whoami.haembi.de. Via curl on a container inside this network to 10.0.1.4 i get:

```
root@875a4e9ca025:/# curl 10.0.1.4
Hostname: b26f538e5670
IP: 127.0.0.1
IP: ::1
IP: 10.0.1.6
IP: 10.0.1.4
IP: fe80::42:aff:fe00:106
IP: 172.18.0.5
IP: fe80::42:acff:fe12:5
GET / HTTP/1.1
Host: 10.0.1.4
User-Agent: curl/7.38.0
Accept: */*

root@875a4e9ca025:/# curl 10.0.1.4
Hostname: e6ce4f6205fb
IP: 127.0.0.1
IP: ::1
IP: 10.0.1.5
IP: 10.0.1.4
IP: fe80::42:aff:fe00:105
IP: 172.18.0.7
IP: fe80::42:acff:fe12:7
GET / HTTP/1.1
Host: 10.0.1.4
User-Agent: curl/7.38.0
Accept: */*

root@875a4e9ca025:/# curl 10.0.1.4
Hostname: 73057da87253
IP: 127.0.0.1
IP: ::1
IP: 10.0.1.7
IP: 10.0.1.4
IP: fe80::42:aff:fe00:107
IP: 172.18.0.5
IP: fe80::42:acff:fe12:5
GET / HTTP/1.1
Host: 10.0.1.4
User-Agent: curl/7.38.0
Accept: */*

root@875a4e9ca025:/# curl 10.0.1.4
Hostname: d5a3a15d7758
IP: 127.0.0.1
IP: ::1
IP: 10.0.1.8
IP: 10.0.1.4
IP: fe80::42:aff:fe00:108
IP: 172.18.0.6
IP: fe80::42:acff:fe12:6
GET / HTTP/1.1
Host: 10.0.1.4
User-Agent: curl/7.38.0
Accept: */*

```

When surfing to http://whoami.haembi.de/ I mostly get the b26f538e5670 container. Only when refreshing really often I get another container.

**Comment by vdemeester** [comment]
@Michael-Hamburger yeah, there is some really weird optimization going on with browser on swarm load balancing… I'm not sure how/why…

**Comment by Michael-Hamburger** [comment]
@vdemeester It's not only on browsers. I only get the same behavior when curl whoami.haembi.de

```
root@297ad9085804:/# curl whoami.haembi.de
#Hostname: b26f538e5670
IP: 127.0.0.1
IP: ::1
IP: 10.0.1.6
IP: 10.0.1.4
IP: fe80::42:aff:fe00:106
IP: 172.18.0.5
IP: fe80::42:acff:fe12:5
GET / HTTP/1.1
Host: whoami.haembi.de
User-Agent: curl/7.38.0
Accept: */*
Accept-Encoding: gzip
X-Forwarded-For: 10.255.0.3
X-Forwarded-Host: whoami.haembi.de
X-Forwarded-Proto: http
X-Forwarded-Server: 3223cccdc7af

root@297ad9085804:/# curl whoami.haembi.de
Hostname: b26f538e5670
IP: 127.0.0.1
IP: ::1
IP: 10.0.1.6
IP: 10.0.1.4
IP: fe80::42:aff:fe00:106
IP: 172.18.0.5
IP: fe80::42:acff:fe12:5
GET / HTTP/1.1
Host: whoami.haembi.de
User-Agent: curl/7.38.0
Accept: */*
Accept-Encoding: gzip
X-Forwarded-For: 10.255.0.3
X-Forwarded-Host: whoami.haembi.de
X-Forwarded-Proto: http
X-Forwarded-Server: 3223cccdc7af

root@297ad9085804:/# curl whoami.haembi.de
Hostname: b26f538e5670
IP: 127.0.0.1
IP: ::1
IP: 10.0.1.6
IP: 10.0.1.4
IP: fe80::42:aff:fe00:106
IP: 172.18.0.5
IP: fe80::42:acff:fe12:5
GET / HTTP/1.1
Host: whoami.haembi.de
User-Agent: curl/7.38.0
Accept: */*
Accept-Encoding: gzip
X-Forwarded-For: 10.255.0.3
X-Forwarded-Host: whoami.haembi.de
X-Forwarded-Proto: http
X-Forwarded-Server: 3223cccdc7af
```

**Comment by ralphtheninja** [comment]
> I think the problem here It's because the traefik can't call the Swarm API on managers.

@diegofernandes You mean traefik can only call the swarm api on managers and not on workers?

**Comment by diegofernandes** [comment]
@ralphtheninja yeah, Docker Swarm API only run on masters.

**Comment by ascora** [comment]
Do you also get this problem with the final version of Docker 1.13?

**Comment by pouicr** [comment]
Hi!

I don't experiment "bad gateway" any more!

However the GUI is still not updated when a service scale. 
Same GUI problem if I start a service with 2 replicas (I only get one)

(Consequence? ) The load balancing is not working.

BR

Loïc

**Comment by vdemeester** [comment]
>  Same GUI problem if I start a service with 2 replicas (I only get one)
The current implementation only lists the service (and thus doesn't see the containers behind) — that's why there is always only 1 replica shown. The load-balancing is then also delegate to the internal swarm-mode load-balancer — either it's a bug there or some overly weird optimization browsers do.

An alternative mode is being worked on here : https://github.com/containous/traefik/pull/1033.

**Comment by hamburml** [comment]
I am using another reverse proxy based on HAProxy which also uses the vip of the service and the load balancing is working there perfectly.

**Comment by tpbrown** [comment]
Docker networking can be problematic on that old of kernel (3.10).

I've seen if fail regularly when regularly deleting & recreating overlay networks - like when you're developing. 

HTH

**Comment by ldez** [comment]
I'll close this issue, because I think the question is answered, but feel free to continue the conversation.

See #1033
