### ISSUE TITLE
Feature Request: set allowed ips 

### ISSUE THREAD

**Issue by dlaub3** [containous/traefik#946]
It would be nice to have a way to set allowed IPs. I have some admin apps running on sub-domains. They are password protected. But they are not protected from brute-force attacks. I'm thinking of something like: 

traefik.docker.allowedips=[ip1, ip2]

**Comment by timoreimann** [comment]
Duplicate of #816.

PR #1332 is currently building support for Kubernetes and Docker.

Closing.
