### ISSUE TITLE
Problem with docker.usebindportip

### ISSUE THREAD

**Issue by eesprit** [containous/traefik#953]
Hi,

I am currently testing `traefik:camembert` with Swarm (standalone, not mode swarm, so using traefik docker mode) and with  `--docker.usebindportip=true`.

I don't get what I think I should with this mode, the backend is still listed with its internal IP and internal port, not the external IP of the swarm node nor the published port (I use -P, so the port is randomly chosen).

Is anyone have the `docker.userbindportip` correctly functionning ?

Am I missing something or did I get wrong what it is supposed to do (the docs are pretty light around this functionnality) ?

Thanks

**Comment by eesprit** [comment]
Some logs to illustrate :

> time="2016-12-09T11:10:41Z" level=info msg="Traefik version v1.1.1 built on 2016-11-29_03:32:44PM" 
> time="2016-12-09T11:10:41Z" level=info msg="Using TOML configuration file /dev/null" 
> time="2016-12-09T11:10:41Z" level=debug msg="Global configuration loaded {\"GraceTimeOut\":10,\"Debug\":false,\"CheckNewVersion\":true,\"AccessLogsFile\":\"\",\"TraefikLogsFile\":\"\",\"LogLevel\":\"DEBUG\",\"EntryPoints\":{\"http\":{\"Network\":\"\",\"Address\":\":80\",\"TLS\":null,\"Redirect\":null,\"Auth\":null,\"Compress\":false}},\"Cluster\":null,\"Constraints\":[],\"ACME\":null,\"DefaultEntryPoints\":[\"http\"],\"ProvidersThrottleDuration\":2000000000,\"MaxIdleConnsPerHost\":200,\"InsecureSkipVerify\":false,\"Retry\":null,\"Docker\":{\"Watch\":true,\"Filename\":\"\",\"Constraints\":null,\"Endpoint\":\"tcp://192.168.150.111:3376\",\"Domain\":\"demo.ol\",\"TLS\":{\"CA\":\"/ssl/ca.pem\",\"Cert\":\"/ssl/server.pem\",\"Key\":\"/ssl/server-key.pem\",\"InsecureSkipVerify\":false},\"ExposedByDefault\":false,**\"UseBindPortIP\":true**,\"SwarmMode\":false},\"File\":null,\"Web\":{\"Address\":\":8080\",\"CertFile\":\"\",\"KeyFile\":\"\",\"ReadOnly\":false,\"Auth\":null},\"Marathon\":null,\"Consul\":null,\"ConsulCatalog\":null,\"Etcd\":null,\"Zookeeper\":null,\"Boltdb\":null,\"Kubernetes\":null,\"Mesos\":null}" 
> time="2016-12-09T11:10:41Z" level=info msg="Preparing server http &{Network: Address::80 TLS:<nil> Redirect:<nil> Auth:<nil> Compress:false}" 
> time="2016-12-09T11:10:41Z" level=info msg="Starting provider *provider.Docker {\"Watch\":true,\"Filename\":\"\",\"Constraints\":null,\"Endpoint\":\"tcp://192.168.150.111:3376\",\"Domain\":\"demo.ol\",\"TLS\":{\"CA\":\"/ssl/ca.pem\",\"Cert\":\"/ssl/server.pem\",\"Key\":\"/ssl/server-key.pem\",\"InsecureSkipVerify\":false},\"ExposedByDefault\":false,\"UseBindPortIP\":true,\"SwarmMode\":false}" 
> time="2016-12-09T11:10:41Z" level=info msg="Starting provider *main.WebProvider {\"Address\":\":8080\",\"CertFile\":\"\",\"KeyFile\":\"\",\"ReadOnly\":false,\"Auth\":null}" 
> time="2016-12-09T11:10:41Z" level=info msg="Starting server on :80" 
> time="2016-12-09T11:10:41Z" level=debug msg="Docker connection established with docker swarm/1.2.5 (API 1.22)" 
> time="2016-12-09T11:10:41Z" level=debug msg="Filtering disabled container /lb" 
> time="2016-12-09T11:10:41Z" level=debug msg="Filtering disabled container /wp_db" 
> time="2016-12-09T11:10:41Z" level=debug msg="Load balancer method '<nil>' for backend backend-wp-web: Invalid method, using default. Using default wrr." 
> time="2016-12-09T11:10:41Z" level=debug msg="Configuration received from provider docker: {\"backends\":{\"backend-wp-web\":{\"servers\":{\"server-wp_web\":{\"url\":\"http://10.0.1.3:80\",\"weight\":0}},\"loadBalancer\":{\"method\":\"wrr\"}}},\"frontends\":{\"frontend-Host-wp-demo-ol\":{\"entryPoints\":[\"http\"],\"backend\":\"backend-wp-web\",\"routes\":{\"route-frontend-Host-wp-demo-ol\":{\"rule\":\"Host:wp.demo.ol\"}},\"passHostHeader\":true,\"priority\":0}}}" 
> time="2016-12-09T11:10:41Z" level=debug msg="Last docker config received more than 2s, OK" 
> time="2016-12-09T11:10:41Z" level=debug msg="Creating frontend frontend-Host-wp-demo-ol" 
> time="2016-12-09T11:10:41Z" level=debug msg="Wiring frontend frontend-Host-wp-demo-ol to entryPoint http" 
> time="2016-12-09T11:10:41Z" level=debug msg="Creating route route-frontend-Host-wp-demo-ol Host:wp.demo.ol" 
> time="2016-12-09T11:10:41Z" level=debug msg="Creating backend backend-wp-web" 
> time="2016-12-09T11:10:41Z" level=debug msg="Creating load-balancer wrr" 
> time="2016-12-09T11:10:41Z" level=debug msg="Creating server server-wp_web at **http://10.0.1.3:80** with weight 0" 
> time="2016-12-09T11:10:41Z" level=info msg="Server configuration reloaded on :80" 

docker $(docker-machine config --swarm swarm1) ps  
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS   
22f1a596d22b        wordpress:4.6.1     "docker-entrypoint.sh"   About an hour ago   Up About an hour    **192.168.150.112:32770**->80/tcp                                swarm2/wp_web

**Comment by ldez** [comment]
I'll close the issue due to inactivity but feel free to re-open if needed.

**Comment by oszi** [comment]
I have the same problem.
Any update on this?

**Comment by denzuko** [comment]
Traefik's documentation points out that this is:

--providers.docker.useBindPortIP=true

https://docs.traefik.io/master/providers/docker/#usebindportip

Try include the `providers` part of the flag.
