### ISSUE TITLE
Drain connections in Traefik

### ISSUE THREAD

**Issue by maauso** [containous/traefik#963]
Hi

is ti possible  drain Traefik connections before remove the docker in Marathon, It's necessary because we need to give time to application to finish the requests, now if you remove docker in marathon you lose client requests, because Traefik remove the docker after to marathon remove it

we tried to change weight value using traefik api, but we don't find the correct call

**Comment by timoreimann** [comment]
This is not possible right now; see #41 also.

The canonical way to handle this in Marathon is to install a termination handler with each application, or as a workaround enable retries and make sure requests towards the terminating tasks can be redirected towards healthy replicas.

**Comment by timoreimann** [comment]
See also #1185 for some general discussion on the topic; #1250 for the documentation of possible mitigation strategies; and the documentation PR #1578 being worked on as we speak.
