### ISSUE TITLE
Docker provider / sticky sessions enable/disable ambiguity

### ISSUE THREAD

**Issue by eesprit** [containous/traefik#965]
For the Docker provider, the doc (https://docs.traefik.io/toml/#docker-backend) says that you can enable sticky sessions using this label :
`traefik.backend.loadbalancer.sticky=true`

Which is totally true.

But it suggests that you can also disable them explicitly using :
`traefik.backend.loadbalancer.sticky=false`

which is totally false, because the code (https://github.com/containous/traefik/blob/master/provider/docker.go#L462) only checks if the `traefik.backend.loadbalancer.sticky` label is defined, and return true if it is (whatever you put in it), and false if not.

You might get the doc more explicit (the "true" value doesn't have any meaning) or update the code to check for the asked value and return it.

**Comment by timoreimann** [comment]
The state of the `getSticky()` method from [back then](https://github.com/containous/traefik/blob/db09007dbc3f55e89512f6ccb9e96eb7c45a4ab3/provider/docker/docker.go#L631-L636) has improved by now and [supports disabling stickiness](https://github.com/containous/traefik/blob/db09007dbc3f55e89512f6ccb9e96eb7c45a4ab3/provider/docker/docker.go#L631-L636) too.
