### ISSUE TITLE
Updating certificates with configuration file.

### ISSUE THREAD

**Issue by ivanjaros** [containous/traefik#968]
Hi, I am running in GKE and I handle LE certificates on my own. I have a cron worker that check if there is any change and if so it will retrieve the certificates and write them into the configuration file defined in treafiks configuration under filename with watch enabled. But since I'm using kubernetes I think this is being ignored and no certificates is used and also when the file us updated I don' see anything in logs which makes me think that Kubernetes has more priority over File and only one "driver" is used at a time.

Is this correct? If so how do I tell Traefik which certificates to use on my own terms?

**Comment by emilevauge** [comment]
@ivanjaros 
https://twitter.com/ivanjaros/status/808671593958408192
https://twitter.com/ivanjaros/status/807672575467909128
Apparently, no more help is needed...
Closing this one then.

**Comment by ivanjaros** [comment]
Yep, I'm moving to Nginx for now.

**Comment by emilevauge** [comment]
For the future, if you need some help on a (totally free) open source project, avoid complaining on Twitter. This really doesn't help solving your issue.
