### ISSUE TITLE
Aggregate responses from multiple backends

### ISSUE THREAD

**Issue by eladtamary** [containous/traefik#983]
### What version of Traefik are you using (`traefik version`)?
Version:      v1.1.2
Codename:     camembert

Question:
Is it possible to aggregate results from multiple backends in one request?
For example, in case I have two microservices and I want the UI frontend to perform a single request that will be mapped to two requests. One request for each microservice.
Is it possible to do it with Traefik?

Thanks,
Elad Tamary

**Comment by ldez** [comment]
I'll close the issue due to inactivity but feel free to re-open if needed.

**Comment by thexpand** [comment]
I am also interested in how this can be achieved, using Traefik.
Anyone?
