### ISSUE TITLE
ACME DNS provider broken since v2.9.9

### ISSUE THREAD

**Issue by eduarrrd** [containous/traefik#9879]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Update from traefik 2.9.8 to 2.9.9 and subsequent version up until and including v2.10.1 without changes in my static configuration.

### What did you see instead?

* Traefik fails to renew certificates by failing to complete ACME's DNS-01 challenges.
* Traefik starts registering additional accounts with the configured ACME DNS server.

(This template doesn't have field for "why do you think this happened" so I'm putting it here.)

In chronological order:

1. go-acme/lego adds https://github.com/go-acme/lego/commit/56fda1abd846295b76c7dfaa7f57c5b36e8d9af9 which introduces the bug 
1. go-acme/lego releases v4.10.1 which contains the bug
1. go-acme/lego releases v4.10.2 which contains the bug
1. go-acme/lego adds https://github.com/go-acme/lego/pull/1863/commits/1a92f8224db91fc13ac9c94552f3432f10248c03 which is the fix
1. traefik releases 2.9.9 which updates from go-acme/lego-v4.10.0 to go-acme/lego-4.10.2
1. acme-dns is now broken on traefik
1. acme-dns is broken until $today

### What version of Traefik are you using?

v2.9.9 to v2.10.1 at least.

### What is your environment & configuration?

```yaml
...
[certificateResolvers.acmednsio.acme]

  [certificatesResolvers.acmednsio.acme.dnsChallenge]
    provider = "acme-dns"
      resolvers = ["8.8.8.8:53"]

...
```

**Comment by ldez** [comment]
The problem has been introduced in this PR: https://github.com/go-acme/lego/issues/1861
And the fix is in this PR: https://github.com/go-acme/lego/pull/1863

The fix will be a part of the next release of lego and then the next release of Traefik.

As a workaround, you can use Traaefik v2.9.7

**Comment by ldez** [comment]
Official release v2.9.8 doesn't have 11 CVEs, there is only one real CVE, and we are not impacted by the others, the analysis of Docker is wrong.
The only CVE is about Go.

We cannot roll back without creating regression.
The only solution is the release of lego.
