### ISSUE TITLE
How do you pass SSL certificate parameters via docker labels?

### ISSUE THREAD

**Issue by nathantreid** [containous/traefik#990]
### What version of Traefik are you using (`traefik version`)?
1.1.2 (docker)

I'm using Traefik with docker, and I'm wondering how to use docker labels to specify the SSL cert and key files. For some sites we are using Let's Encrypt, but for others we have purchased certificates. For example, if I deploy a website for container www.foo.com, I want to also pass in the CertFile path. Our deploy process would handle dropping the file in the proper folder.

Here's an example of what I'm trying to achieve:
```
docker service create \
    --name foo \
    --label traefik.frontend.rule=Host:www.foo.com \
    --label traefik.frontend.certFile=/certs/www_foo_com.crt
    --label traefik.frontend.keyFile=/certs/www_foo_com.key
   --network traefik-net
   foo
```
Is this possible?

From the documentation, I don't see any way to do this via labels - the only way I currently see to do this is by editing traefik.toml.

**Comment by aro1976** [comment]
having the same doubt here, but in my case I plan to bundle the certificate in a traefik image.

**Comment by ncrmro** [comment]
@nathantreid any luck with this?

**Comment by chulkilee** [comment]
In my case I just list all certs under `[endpoint]`. I don't think traefik reads certs on run-time.

**Comment by absolutejam** [comment]
@chulkilee Can you please elaborate on this?

At the minute I don't seem to have any way to provide https using Docker backend, but I feel like I must be missing something?

**Comment by chulkilee** [comment]
See https://docs.traefik.io/toml/#entrypoints-definition. cert config is under endpoint, not under frontend.

- traefik automatically picks certs based on host name
- all certs must be given at `[endpoint]` when traefik started (wildcard doesn't work)

**Comment by nathantreid** [comment]
I was afraid that might be the case, but I was hoping that there was something I was missing. I guess I need to turn this into a feature request then. The problem with loading the certificates manually through the config is that I have to write a process to edit the file (more complexity on my end) and restart traefik to load the certificates, which means all of our websites go down just so I can load new SSL certificates for one site.

**Comment by ldez** [comment]
Close in favor of  #1623 - Feel free to subscribe there for updates.
