### ISSUE TITLE
Separate access logs per service 

### ISSUE THREAD

**Issue by lonix1** [containous/traefik#9955]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

In nginx (and similar tools) one has an app log (for nginx itself), and access and error logs per service. So app1 has different access logs to app2.

In traefik the access log is the same for all services.

It was confirmed by @bluepuma77 that this [isn't possible](https://community.traefik.io/t/separate-access-logs-per-service/18957/2), currently.

There is a workaround: pass the access log to some other tool which splits it into separate logs. But for a small server, that is massive overkill for something so simple that most (/all?) similar tools do natively.

Please consider adding this functionality?

**Comment by bluepuma77** [comment]
Traefik is not a web server. You can still get the logs from the web-servers that split per service. If you want to run Wordpress for example, you still need a web-server behind Traefik.
