### ISSUE TITLE
Ability to remove X-Forwarded-* headers

### ISSUE THREAD

**Issue by erkexzcx** [containous/traefik#9979]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Hello Traefik Team,

I'm opening this feature request to address a situation with the handling of `X-Forwarded-*` headers in Traefik. Currently, these headers are added after the middlewares have been processed, which makes it impossible for **custom middlewares** (plugins) to remove or alter these headers. While I understand that these headers are vital for proper functioning of many architectures, giving the users an option to control these headers can provide additional flexibility and can be crucial in certain scenarios.

### Use Cases:

1. In some scenarios, we might want to fully control the headers passed on to the downstream services, and these automatic headers may conflict with the control.

2. It might be a security concern for some users. While `X-Forwarded-*` headers are generally harmless and useful, there might be cases where users don't want to expose certain information about the request's path.

3. It provides more flexibility in terms of header management, which could be useful in complex architectures and during debugging.

### Proposed Solution:

Introduce a configuration option that enables users to choose whether to include these headers or not. This option can be true by default to maintain the current behavior, which is adding these headers.

Please note that this feature request is not about disabling these headers completely, but about giving users a choice. If a user doesn't specify anything, the default behavior should remain intact, that is, the headers should be added as they are now.

P.S. ChatGPT wrote this, did way better job than I would be able to. :pray:

**Comment by ldez** [comment]
Hello,

there is existing option to handle this header: https://doc.traefik.io/traefik/routing/entrypoints/#forwarded-headers

**Comment by nmengin** [comment]
Hey @erkexzcx!

Thanks for your suggestion.

We are interested in this issue but are unsure about the use case and the traction it will receive, so we are going to leave the status as "kind/proposal" to give the community time to let us know that they would like this.

**Comment by bartlaarhoven** [comment]
I don't believe this is resolved yet. in #10132 only `X-Forwarded-For` is fixed, but the other `X-Forwarded-*` headers (like `X-Forwarded-Host`) are still not removable..?

**Comment by rtribotte** [comment]
Hello @bartlaarhoven,

Thanks for your feedback.
We tested the removal of other `X-Forwarded-*` headers and could not reproduce the problem you are describing.
Can you please open a new issue and share a minimal reproducible case with us?

**Comment by bartlaarhoven** [comment]
> Hello @bartlaarhoven,
> 
> Thanks for your feedback. We tested the removal of other `X-Forwarded-*` headers and could not reproduce the problem you are describing. Can you please open a new issue and share a minimal reproducible case with us?

I believe my reproducible case was documented in https://community.traefik.io/t/can-not-remove-x-forwarded-headers-anymore/19474?
I don't have a Kubernetes cluster available right now with Traefik v3; because of this issue I'm still on v2 so I can't create a reproducible case easily.

**Comment by rtribotte** [comment]
Hello @bartlaarhoven,

Can you please open a dedicated issue for v3?
